### ISSUE TITLE
Hook api for PDF generation.

### ISSUE THREAD

**Issue by SpudNyk** [diegomura/react-pdf#1000]
Instead of using BlobProvider wrapper component a hook based api would be useful. This would allow easier integration into existing components.

I have a gist of an implementation (this was made against v2) here: https://gist.github.com/SpudNyk/44b6602e4fc3c4d4d9197fb6b6876a44

The gist includes a version of the PDFViewer component to show how it can easily be used.

I use a version of this hook in production to have a combined viewer with an upload button to allow publishing.

**Comment by diegomura** [comment]
Ended up implementing something very similar on 2.0! Thanks!
