### ISSUE TITLE
Component PDFViewer: set props height to 100 % does not work

### ISSUE THREAD

**Issue by JacobGeoGeek** [diegomura/react-pdf#1003]
**Describe the bug**
Based on the [react-pdf documention](https://react-pdf.org/components), you can set the props height for the PDFViewer. I was wondering is it possible to add a % for height ? I have also tried with the Width and this props accept the %.

here example with 100 %: 
![image](https://user-images.githubusercontent.com/19539781/92536974-f8707080-f208-11ea-9600-2b401608f93d.png)

expected result ( I would like to have a PDF to be fully cover the page): 
![image](https://user-images.githubusercontent.com/19539781/92537115-556c2680-f209-11ea-9746-cf9f4af91f32.png)

**Comment by Axel19992017** [comment]
could you solve it?

**Comment by JacobGeoGeek** [comment]
No i wasn't able to solve it

**Comment by Axel19992017** [comment]
Did you try adding width and height property to pdfviewer?

**Comment by JacobGeoGeek** [comment]
Yes I've set height=100% and width=100%

**Comment by Axel19992017** [comment]
I have an example where the pdfviewer works correctly, let me look it up.

**Comment by Axel19992017** [comment]
![image](https://user-images.githubusercontent.com/30581844/94076625-c2abba00-fdba-11ea-8b1c-2828a491b292.png)

![image](https://user-images.githubusercontent.com/30581844/94076664-d6572080-fdba-11ea-9df3-2c0bd65cbe03.png)
Do you have this like that?

**Comment by JacobGeoGeek** [comment]
after testing this syntax: 

`function App() {
  return (
    <PDFViewer width={"100%"} height={"100%"}>
      <MyDocument />
    </PDFViewer>
  );
}`

I still have the same problem:
![image](https://user-images.githubusercontent.com/19539781/94154297-bde31680-fe4b-11ea-9de1-7c565e2034a9.png)

**Comment by andrewdourado** [comment]
My temporary solution is to use `window.innerHeight` instead `100%`.

**Comment by JacobGeoGeek** [comment]
do you have example ?

**Comment by andrewdourado** [comment]
Just change height value in `PDFViewer` component:

```
<PDFViewer height={window.innerHeight} width="100%">
  <PDFDocument />
</PDFViewer>
```

**Comment by JacobGeoGeek** [comment]
it works, but the only (more UI related problem) is that their two scroll bars: 

![image](https://user-images.githubusercontent.com/19539781/94282453-d9b6ed00-ff1d-11ea-9fde-a220bac6bc7f.png)

**Comment by andrewdourado** [comment]
Try this: 
```
<PDFViewer
      style={{ position: 'absolute', border: 0, height: '100%', width: '100%' }}
>
   <PDFDocument />
</PDFViewer>
```

I insert `border: 0` because of the edge browser.

Credits: https://stackoverflow.com/a/18665613

**Comment by JacobGeoGeek** [comment]
it works !

**Comment by meharbhutta** [comment]
Try this:
```
<PDFViewer
      style={{ flex: 1 }}
>
   <PDFDocument />
</PDFViewer>
```
