### ISSUE TITLE
unhandled rejection (error) stream.push() after EOF

### ISSUE THREAD

**Issue by sathish-1997** [diegomura/react-pdf#1008]
made react pdf download link into a functional component and added it into my listing. The problem is that everytime i go to the page my component is implemented i get the above error. Have tried all the github solutions provided. Someone please help me out with a solid solution.
![11111](https://user-images.githubusercontent.com/57295985/93157357-a2398b00-f73c-11ea-8127-e27d2d93c1bc.PNG)
ps: Im using Typescript React

**Comment by SahilCodezeros** [comment]
@sathish-1997 problem solved? if not please share your code here so i can check that.

**Comment by xorander00** [comment]
I just ran into the same thing.  I'm going to continue exploring and see what diagnostic info I can dig up.  Let me know if anyone has any ideas or wants more info.

**Comment by AugustoMarcelo** [comment]
I went through this problem too. The PDF was being rendered normally, but after turning the function that set the values into asynchronous, it started to break. In my case, I had an api call, just removed `async` and` await` and used `then`

**Comment by sathish-1997** [comment]
i solved the issue already the PDF renders to fast hence the error just had to add in timeout

**Comment by steveHornseyDeveloper** [comment]
For anyone else reading this, the `stream.push() after EOF` error seems to occur when the Component is rendered multiple times. The app I am working with has several pointless rerenders (due to legacy reasons) and was causing the PDF download link to fail.
I have now extracted the download button to a standalone component and wrapped it in a React.memo() and the PDF now downloads successfully

```

const MyDoc = () => {
  console.log('rendering pdf');
  return (
    <Document>
      <Page>
        <Text fixed>
          ~ Created with react-pdf ~
        </Text>
        <Text>Don Quijote de la Mancha</Text>
        <Text>Miguel de Cervantes</Text>
      </Page>
    </Document>
  );
};

const PdfRenderer: React.FC<Props> = (props: Props): JSX.Element => (
  <div>
    <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
      {({ loading }: { loading: boolean }) => {
        console.log('loading...');
        return (loading ? 'Loading document...' : 'Download now!');
      }}
    </PDFDownloadLink>
  </div>
);
```

**Comment by ngbrown** [comment]
Using `console.log` I could see that it is only rendering once, and still having this problem. https://github.com/diegomura/react-pdf/issues/844#issuecomment-662842953 seems to be a better solution. I think it is waiting until the equivalent of component did mount.
