### ISSUE TITLE
Bug Style with map function

### ISSUE THREAD

**Issue by Axel19992017** [diegomura/react-pdf#1012]
Ok, sorry if it's messy, some things are in Spanish (it's my native language) but I hope it's understood.

This document has about 192 fields, grouped by "Tables" of different formats.

The variable values is the response of the API, its structure is:

`[{
        "name_data": "Antecedentes Heredofamiliares HTA",
        "value_data": "false"
    }, {
        "name_data": "Antecedentes Heredofamiliares DM",
        "value_data": "false"
    }.....]`

This is a type of formatted tables that are in MedicalRecord (the React-pdf component):

![image](https://user-images.githubusercontent.com/30581844/93789528-3305e000-fbef-11ea-8226-3948fea3f470.png)

And I call it as follows:

![image](https://user-images.githubusercontent.com/30581844/93789615-516bdb80-fbef-11ea-8b3d-57d196be9a4c.png)

Stylesheets
![image](https://user-images.githubusercontent.com/30581844/93789775-84ae6a80-fbef-11ea-93a1-e99e5e189858.png)

And finally this component I call it here:

![image](https://user-images.githubusercontent.com/30581844/93789943-b58e9f80-fbef-11ea-8428-f1afa7f58958.png)

information, resultsExam, patient  is passed correctly, I have tried it, but in the end the styles are not shown correctly.

It should look like this:

![image](https://user-images.githubusercontent.com/30581844/93790178-fb4b6800-fbef-11ea-8a61-2be786ec56e6.png)

But it shows like this:

![image](https://user-images.githubusercontent.com/30581844/93790224-0900ed80-fbf0-11ea-833d-e837da22f626.png)

Thanks for your time.

**Comment by fauxsoup** [comment]
I'm also encountering this issue. It appears to go away upon re-render.

**Comment by diegomura** [comment]
Could you upgrade to 2.0 and test if this remains? Also, it would be super hard for me to test or replicate this since all your snippets are images. If still happens in 2.0, it would be helpful if you can provide a minimal way or replicating this issue. Thanks

**Comment by Axel19992017** [comment]
I will, when I try it, I will comment here on the result
