### ISSUE TITLE
How to display the PDF without native overlays

### ISSUE THREAD

**Issue by 3DJakob** [diegomura/react-pdf#1014]
I need to display a created pdf document. The problem is using the `PDFViewer` whichever browser I am in adds its own pdf overlay controls with things like a download button. I need to get rid of this.

The weird thing is that exactly that is made on the wiki page https://react-pdf.org/repl
where custom overlay has been added.

How is this possible? I can't seem to find any way to do this.

**Comment by 3DJakob** [comment]
This is apparently a duplicate of https://github.com/diegomura/react-pdf/issues/477
Check over there for a solution.

**Comment by LinusU** [comment]
Here is a `PDFViewer` component that you could use, that uses react-pdf under the hood:

```javascript
import React, { useEffect, useState } from 'react'
import { pdfjs, Document, Page } from 'react-pdf'
import { pdf } from '@react-pdf/renderer'

pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`

const PDFViewer = ({ children }) => {
  const [pdfUrl, setPdfUrl] = useState(null)

  useEffect(() => {
    const child = React.Children.only(children)

    pdf(child).toBlob().then(blob => {
      setPdfUrl(URL.createObjectURL(blob))
    })
  }, [children])

  return (
    <Document file={pdfUrl}>
      <Page renderMode='svg' pageNumber={1} />
    </Document>
  )
}

export default PDFViewer
```
