### ISSUE TITLE
Table of Content

### ISSUE THREAD

**Issue by FabianSchempp** [diegomura/react-pdf#1015]
I need to render a table of content section. For that, I need to know the page-numbers of beginning and end of each chapter component in advance, taking automatic wrapping into account.

My first general Idea for that would be to

1. Render each chapter to and receive an information about how many pages long that chapter is when rendered or any way to pre-test a section of its page-length when rendered?
for Example: 
let chapterPagesArray = preRenderView(chapters[0]);
let chapterLength = chapterPagesArray.length;

2. Render the table of content section with that information.

3. render the whole document with new that information filled in.

If that is possible with the current system, it would be very nice to get some suggestions.

**Comment by krishankantray** [comment]
something similar to   [https://pdfmake.github.io/docs/0.1/document-definition-object/toc/](PDF Make TOC)

**Comment by FabianSchempp** [comment]
Im working on a patch. You can simply pass a propery called: toc_section={'Your Section Title'} to a component and while wrapping the pages, this is evaluated. Than the toc object is passed as prop along with pageNumber and totalPages like {pageNumber, totalPages, tableOfContent} to the dynamic rendering. So far it works fine. What im struggle with, is the ability to render not fixed dynamic content. Not fixed dynamic content is needed for rendering the table of content. I will dive deeper into this.

**Comment by ithustle** [comment]
@FabianSchempp , anything?

**Comment by marcovolle** [comment]
@FabianSchempp Hi, did you manage to get it working?

**Comment by kmooney517** [comment]
following!

**Comment by diegomura** [comment]
Duplicated #479. Please check for pre-existing issues before creating new ones. Thanks!
