### ISSUE TITLE
@react-pdf/renderer taking higher time to generate pdf at node level 

### ISSUE THREAD

**Issue by AgarwalShyam** [diegomura/react-pdf#1017]
**Describe the bug**
Hi Team,

Thanks for this package.

We tried to use this package to generate pdf from react components but we also faced the same issue which is already reported.
https://github.com/diegomura/react-pdf/issues/510,
https://github.com/charto/nbind/issues/128

So we tried to move the code at the node level and used the same package @react-pdf/renderer in the controller in node API.
Please find below the way we have implemented but in the actual scenario, the code is bulky and the data volume is pretty high.

![image](https://user-images.githubusercontent.com/47396452/94558254-5844bf00-027d-11eb-9226-43f4a2c5e33a.png)

![image](https://user-images.githubusercontent.com/47396452/94559057-4d3e5e80-027e-11eb-9f2a-bfa868239d0d.png)

We are able to generate pdf at the node level successfully but we are experiencing high response time. Node js is taking almost 30 sec to generate pdf and time is increasing if request data gets larger. As per our findings, this is due to high CPU utilization.

**Expected behavior**
Response time should be less

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome
 - React-pdf version: 1.6.11("@react-pdf/renderer")

Has anyone implemented @react-pdf/renderer package at node js and getting high response time due to high CPU utilization?

Thanks & Regards,
Shyam Agarwal

**Comment by sz-FarmersEdge** [comment]
We are having the same issue. Trying to use Puppeteer instead.

**Comment by zss1980** [comment]
We're having the same issue CPU and memory increase. We're trying to use Puppeteer instead.

**Comment by klis87** [comment]
+1, not to mention it seems to be a memory leak too

**Comment by klis87** [comment]
I noticed that a memory leak was fixed in 1.5.6, so I wil upgrade and let here know this still is the issue

**Comment by diegomura** [comment]
As @klis87 said memory leak is fixed, and latest version also ships a new yoga version with higher memory limit. Closing this now. Let me know if something like this persist
