### ISSUE TITLE
.fillAndStroke not available as painter method

### ISSUE THREAD

**Issue by heyalexchoi** [diegomura/react-pdf#1020]
**Describe the bug**
`.fillAndStroke` not available as painter method.

[Documentation](https://react-pdf.org/components#canvas) states 
>>>Painter object
Wrapper arround pdfkit methods you can use to draw inside the Canvas. All operations are chainable. For more information about how these methods work, please refer to pdfkit documentation.

[PDFKit documentation](http://pdfkit.org/docs/vector.html) states 
>>>Note that calling fill and then stroke consecutively will not work because of a limitation in the PDF spec. Use the fillAndStroke method if you want to accomplish both operations on the same path.

React-PDF tells me `Unhandled Rejection (TypeError): painter.circle(...).lineWidth(...).fillAndStroke is not a function`
If I'm looking at the right [file](https://github.com/diegomura/react-pdf/blob/master/src/utils/painter.js), seems that method is not available.

Is there no way to stroke and fill the same path in react-pdf Canvas? I would expect either react-pdf to make that method available, or for the react-pdf documentation to explain how react-pdf's API works where it is different.

If someone knows how to do this, I would appreciate some help!

Thank you for the great library 🙏

**Comment by diegomura** [comment]
Fixed [here](https://github.com/diegomura/react-pdf/commit/fbd97fbea9144c41cce9278f6d13411b34c5137e)
