### ISSUE TITLE
How can I use react-barcode?

### ISSUE THREAD

**Issue by sabbirsristy7494** [diegomura/react-pdf#1028]
I want to integrate react-barcode on the react-pdf//render. But it show me an error that **Error: Invalid element of type svg passed to PDF renderer** Can I use custom component on react-pdf? Has it been developed yet this feature to use custom component or html tags. This is my code that I actually want to implement.
![Capture3](https://user-images.githubusercontent.com/56749379/95802969-b0b99900-0d20-11eb-855a-2daa319dde04.PNG)

**Comment by barreeeiroo** [comment]
Hi @sabbirsristy7494,
I currently volunteer at @PC-Compostela, and we use react-pdf to generate reports of activities. Here is a sample one (hiding some information):
![image](https://user-images.githubusercontent.com/19251112/96800315-4fbb5080-1405-11eb-88d5-55940e331308.png)

To render the barcodes and QRs, we don't use `react-barcode`, but instead `qrcode` and `JSBarcode` (both on npm).

1. Generate canvas for both types of codes:
```js
let canvas;
// For QR Code
canvas = document.createElement('canvas');
QRCode.toCanvas(canvas, your_data);
const qr = canvas.toDataURL();
// For Barcode
canvas = document.createElement('canvas');
JsBarcode(canvas, your_data);
const barcode = canvas.toDataURL();
```

2. Take react-pdf's Image component, and use it like this:
```js
<Image src={barcode || qr}/>
```

**Comment by sabbirsristy7494** [comment]
@barreeeiroo thanks a lot. Your solution worked for me.

**Comment by ivanjeremic** [comment]
Any example on where the code should be, is useEffect the right place for ````let canvas;
// For QR Code
canvas = document.createElement('canvas');
QRCode.toCanvas(canvas, your_data);
const qr = canvas.toDataURL();
// For Barcode
canvas = document.createElement('canvas');
JsBarcode(canvas, your_data);
const barcode = canvas.toDataURL();``

**Comment by diegomura** [comment]
In 2.0 will be possible as well wit SVG. Thanks!

**Comment by lkevenson** [comment]
Hello

I cant use this: 

_let canvas;
// For QR Code
canvas = document.createElement('canvas');
QRCode.toCanvas(canvas, your_data);
const qr = canvas.toDataURL();
// For Barcode
canvas = document.createElement('canvas');
JsBarcode(canvas, your_data);
const barcode = canvas.toDataURL();_

with NextJS,,


How can I integrate React-barcode and React-pdf inside a NextJS Project.

**Comment by faberchri** [comment]
> In 2.0 will be possible as well wit SVG. Thanks!

So is there now (after release of SVG support) a way to embed a SVG-barcode (in my case a QR code generated with `qrcode.react`) into the PDF without converting it first into a PNG or JPEG and thereby losing quality? Thanks a lot for the clarification.

**Comment by mdodge-ecgrow** [comment]
Glad I found your post @faberchri .  I just spent the last hour trying to figure out why my QR code from qrcode.react wasn't showing up in my PDF.  I will now try your methods instead.

**Comment by fnimick** [comment]
For anyone else struggling with this for pure barcodes rendered on the server side with no DOM or canvas: I got it working with https://github.com/metafloor/bwip-js.

```
  const imageBuffers = await Promise.all(
    strings.map((s) =>
      bwipjs.toBuffer({
        bcid: "code128",
        text: s,
        scale: 2,
        height: 12,
        includetext: true,
        textxalign: "center",
      })
    )
  );
```

Then, when rendering the pdf:
```
      {imageBuffers.map((buf) => {
        const imgSrc = `data:image/png;base64,${buf.toString("base64")}`;
        return (
          <View style={...}>
            <Image src={imgSrc} />
          </View>
        );
      })}
```

**Comment by bryantobing12** [comment]
any update on how to this?

**Comment by Nabi-Barki** [comment]
> I want to integrate react-barcode on the react-pdf//render. But it show me an error that **Error: Invalid element of type svg passed to PDF renderer** Can I use custom component on react-pdf? Has it been developed yet this feature to use custom component or html tags. This is my code that I actually want to implement. ![Capture3](https://user-images.githubusercontent.com/56749379/95802969-b0b99900-0d20-11eb-855a-2daa319dde04.PNG)

use jsbarcode library instead react-barcode 
try it... definitly working for you 
const [barcodeData, setBarcodeData] = useState("ABCD123");
  const [barcodeImage, setBarcodeImage] = useState(null);

  useEffect(() => {
    const canvas = document.createElement("canvas");
    JsBarcode(canvas, barcodeData, { format: "CODE128" });
    const barcodeDataURL = canvas.toDataURL();
    setBarcodeImage(barcodeDataURL);
  }, [barcodeData]);

**Comment by m-muiznieks** [comment]
Here is the working component. 
```JS
```
import { Image, View } from '@react-pdf/renderer';
import { useEffect, useState } from 'react';
import bwipjs from 'bwip-js';

interface QRProps {
    codeType?: string;
    barCode: string;
    width?: number;
    heightInMillimeters?: number;
    height?: number;
    showText?: boolean;
    textXalign?: string;
    
}
export const QRCodeForPdf = ({ barCode }: QRProps): JSX.Element => {
  const [code, setCode] = useState(barCode);
   const [imageSrc, setImageSrc] = useState("");

  useEffect(() => {
    const generateBarcode = async (code: string) => {

      const options = {
        bcid: 'code128', // Barcode type
        text: code, // Text to encode
        scale: 3, // 3x scaling factor
        height: 15, // Bar height, in millimeters
        includetext: true, // Show human-readable text
        textxalign: 'center', // Center-align the text
      } as bwipjs.RenderOptions;

      let canvas = document.createElement('canvas');
      try {
        const buffer = bwipjs.toCanvas(canvas, options);
        const src = canvas.toDataURL('image/png');
        setImageSrc(src); // Update state with the generated barcode image source
        return src;
      } catch (error) {
        console.error('Error generating barcode:', error);
      }
    };

    generateBarcode(code); // Generate barcode
  }, [imageSrc]); 
  console.log(imageSrc);
  
return (
    <View style={{ margin: 10 }}>
        {imageSrc && <Image src={imageSrc} style={{ width: 100, height: 30 }} />}
    </View>
);
};
```

If you are building at next.js - use bwipjs.toCanvas() not .toBuffer() //this took me a time to understand

**Comment by hormiai76** [comment]
Hi,
I'm trying to render a barcode using bwipjs in react but bwipjs.toCanvas()  doesn't exists so I use bwipjs.toSVG() but then in my pdf the barcode is not shown... 
I'm using "@react-pdf/renderer" v3.4.4. and bwipjs v4.3.2
i need help
