### ISSUE TITLE
<Image> in <Text>

### ISSUE THREAD

**Issue by emorling** [diegomura/react-pdf#1030]
I have a situation where Image will be rendered within a Text element.

Is there any styling I can apply to the Text to allow the image to take more space? For example make the Text element auto-adjust it's height to an Image that is 300x300?

**Comment by alew140** [comment]
image:{ float: left} ?
show more info please

**Comment by diegomura** [comment]
Thanks @alew140 for addressing issues! @emorling can you share an example of what you are trying to achieve?

**Comment by emorling** [comment]
I found that the issue is that using this:

`<Text><Image ... /></Text>
`

Will cause the Image to be confined to the line-height of the Text element, making it ridiculously small.

**Comment by alew140** [comment]
try this !
<Text><Image style={{width: 300 , height: 300 }} ... /></Text>

**Comment by emorling** [comment]
Thank you that works!
