### ISSUE TITLE
React Pdf renderer falling into the issue after having 2807 records

### ISSUE THREAD

**Issue by Akshaykapadi** [diegomura/react-pdf#1031]
Getting Cannot enlarge array error.Please help me to get this issue fix. PFA 
![Screenshot (136)](https://user-images.githubusercontent.com/58328620/96337591-f02c1080-10a5-11eb-8f25-64765388de64.png)
@diegomura

**Comment by Akshaykapadi** [comment]
@diegomura please help me. I have a deadline to my client. Please help me to get this done asap.

**Comment by diegomura** [comment]
@Akshaykapadi what do you mean 2807 records? You can test the new 2.0 version on npm (it's on beta). this memory issue has been already reported please check if anything there helps.

**Comment by Akshaykapadi** [comment]
2807 records means i am having 100000 set of records and while generating pdf document in a loop one by one it generates about 2807 records and throws memory error.
@diegomura  i have visited old issue but can see the issue to be fixed

**Comment by diegomura** [comment]
What you are trying to achieve I think it's beyond react-pdf capabilities. Try the new version, reducing the amount of nodes rendered on the docs, or split those 100000 into different docs

**Comment by Akshaykapadi** [comment]
@diegomura I think 2.0.16 version is having flaw. I can't see things working out. It giving error as soon one file is going to generate pdf. Please check attahment below
![Screenshot (138)](https://user-images.githubusercontent.com/58328620/97839359-125d9980-1d08-11eb-9851-892e2e213354.png)

**Comment by Akshaykapadi** [comment]
@diegomura  version 2.0.0 is also not stable i can see. Please can you help me with the version on which i can check whether memory issue is fixed or not
I found below issue on 2.0.0 version 
![Screenshot (140)](https://user-images.githubusercontent.com/58328620/97839715-bcd5bc80-1d08-11eb-9926-928df81e8cd5.png)

**Comment by diegomura** [comment]
I can't know what's going on with so little information. I don't know your app and what document is trying to generate. You will have to provide some way of reproducing this. 2.0 it's not _very_ stable but you should be able to generate a document just fine.

**Comment by Akshaykapadi** [comment]
Can you help me to solve this issue? Can we connect so that i can show you the issue and how to reproduce it and you can actually help me @diegomura

**Comment by diegomura** [comment]
Can't right now. Have my own deadlines too 😄  Please provide a way to reproduce it. It's impossible for me to familiarize with each specific product react-pdf is being used in sorry
