### ISSUE TITLE
New line in a Text element

### ISSUE THREAD

**Issue by emorling** [diegomura/react-pdf#1032]
How can I force a new line within a Text element? Similar to `<br/>`

**Comment by alew140** [comment]
use this not is the best solution but work 

`<Text> text here up {'\n'} Text here Down <Text>`

**Comment by Natedeploys** [comment]
Is this related to #1021 ? I haven't found a workaround at all

**Comment by diegomura** [comment]
@alew140 is the way. If you don't like it that way you can create your own `<br />` like 

```
const Br = () => "\n";

<Text> text here up <Br /> Text here Down <Text>
```

**Comment by alew140** [comment]
Thanks diego you method is clean can you integrate in demo or in code source ?

**Comment by diegomura** [comment]
This should not be part of the lib code in my opinion. Will try to add it to the docs
