### ISSUE TITLE
Cannot read property 'size' of undefined (this.page is undefined)

### ISSUE THREAD

**Issue by ihd-dev** [diegomura/react-pdf#1036]
Hi

During generation of the PDF, the browser crashes with the error:

**Unhandled Rejection (TypeError): Cannot read property 'size' of undefined**

![image](https://user-images.githubusercontent.com/50595319/96874752-c5133980-1476-11eb-8406-f9707361d498.png)

As you can see from the image above, it seems as if `this.page` is undefined. 

I am rendering a rather large document (about 20 pages) and the contents/information is a bit sensitive so I have a hard time to re-create the issue in a codesandbox/similar. 

It seems to bug out on the end, i.e. after all render methods have successfully run returning my each part of my content (I'm looping an array holding the content).

**Comment by alew140** [comment]
size is a property only of <Page size="A4">
check your code and please show you document to can help you

**Comment by ihd-dev** [comment]
Page size is set. The error I receive indicates that the entire **this.page** is undefined.

**Comment by diegomura** [comment]
Can you share an example I can use to reproduce this?

**Comment by Salablefuzzball** [comment]
I got this error by forgetting to wrap the page content in the `<Page>` component. 

I suggest you to go through your code for this kind of mishap.
