### ISSUE TITLE
Hyphenation occurs even when hyphenation disabled with nested Text tags and new lines

### ISSUE THREAD

**Issue by morningcocoa** [diegomura/react-pdf#1038]
If a Text tag is inside another Text tag, but the nest tag is on the next line, a hyphen occurs on the line before.

Ex.
`<Text>Example text and this text is going to hit the next <Text style={boldStyle}>line right here</Text></Text>`

The output will look like this:
Example text and this text is going to hit the next -
**line right here**

**Comment by morningcocoa** [comment]
So, I noticed you can set an integer to hyphenationCallback, so what does the 600 mean?
hyphenationCallback | Specifies how much hyphenated breaks should be avoided | Integer | 600
-- | -- | -- | --

**Comment by PauloQuagliatto** [comment]
> If a Text tag is inside another Text tag, but the nest tag is on the next line, a hyphen occurs on the line before.
> 
> Ex.
> `<Text>Example text and this text is going to hit the next <Text style={boldStyle}>line right here</Text></Text>`
> 
> The output will look like this:
> Example text and this text is going to hit the next -
> **line right here**

Maybe there is not much to do with the response, but how did you manage to make the text bold? (mine has a ```fontWeight: 900``` and still is as normal as the rest)

**Comment by diegomura** [comment]
The `hyphenationCallback` integer is no longer supported. You can now pass a hyphenationCallback function at the Text component as you would do in [here](https://react-pdf.org/advanced#hyphenation)
