### ISSUE TITLE
Page size in mm

### ISSUE THREAD

**Issue by 3DJakob** [diegomura/react-pdf#1041]
I need to make a PDF 400mm by 300mm. By doing some simple math on your preset sizes I managed to figure out that if I take my size in mm * 2.8346464646 I get the size 300mm x 400mm with I tiny precision error. But I can't figure out what that scale comes from! Also is there any way to make the PDF exact dimensions in mm? 

It would be very nice if the documentation was updated to say what unit it takes.

**Comment by 3DJakob** [comment]
Interestingly if I open the PDF in Affinity Designer (a software like illustrator) the size shows up in mm as the same number you input in the size prop. However, to get the right size in preview I need to make the conversion as mentioned 🤔 Seems like something is off here!

**Comment by diegomura** [comment]
This is already supported on the 2.0 version! I just updated the TS types to reflect this
