### ISSUE TITLE
Table left column goes to the next page while the right column stay in the current page

### ISSUE THREAD

**Issue by Irene5460** [diegomura/react-pdf#1042]
**Describe the bug**
I have a table which has two columns (left column is a title in bold and right column is the value) and only one row. It works well (see Good table in the screen shot) except if the table is displayed at the end of a page, the left column goes to the next page while the right column stay in the current page (see Bad table in the screen shot). Any idea what caused this and how to fix it?
![TableProblem](https://user-images.githubusercontent.com/57916343/97514010-1aae8100-1964-11eb-92d2-933a0c678a0d.png)

Source code for the table
```
    <View style={pdfStyles.descriptionItem}>
      <View style={pdfStyles.descriptionRow}>
        <View style={pdfStyles.descriptionItemTitle}>
          <Text style={pdfStyles.descriptionContentTitle}>
            Number of books borrowed from library
          </Text>
        </View>
        <View style={pdfStyles.descriptionItemDescription}>
          <Text style={pdfStyles.descriptionContentDescription}>
            30
          </Text>
        </View>
      </View>
    </View>

```
And CSS
```
  descriptionItem: {
    display: 'table',
    borderWidth: 0.1,
    marginLeft: 12,
  },
  descriptionRow: {
    paddingTop: -10,
    flexDirection: 'row',
  },
  descriptionItemTitle: {
    width: '40%',
    textAlign: 'left',
    paddingRight: 25,
    paddingTop: 0,
  },
  descriptionItemDescription: {
    width: '60%',
    textAlign: 'left',
    paddingTop: 0,
  },
  descriptionContentTitle: {
    marginTop: 10,
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    fontWeight: 'bold',
    textAlign: 'left',
  },
  descriptionContentDescription: {
    marginTop: 10,
    fontSize: 12,
    fontFamily: 'Helvetica',
    fontWeight: 'normal',
    textAlign: 'left',
  },

```
**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by diegoarcega** [comment]
same issue here

![image](https://user-images.githubusercontent.com/1951007/134742749-c6353955-cf09-4e7d-b3ec-5fddf3770aee.png)

**Comment by jeetiss** [comment]
@Irene5460 @diegoarcega  you can disable page wrapping for table row. [here docs](https://react-pdf.org/advanced#page-wrapping)
but use it carefully, wrap prop can break layout if table row will be bigger that page size

    
```js
   <View style={pdfStyles.descriptionItem}>
      <View wrap={false} style={pdfStyles.descriptionRow}> // wrap prop here
        <View style={pdfStyles.descriptionItemTitle}>
          <Text style={pdfStyles.descriptionContentTitle}>
            Number of books borrowed from library
          </Text>
        </View>
        <View style={pdfStyles.descriptionItemDescription}>
          <Text style={pdfStyles.descriptionContentDescription}>
            30
          </Text>
        </View>
      </View>
    </View>
```

**Comment by Irene5460** [comment]
I solved the problem. Here is my solution:

        <Text
          style={pdfStyles.descriptionContentDescription}
          orphans="0"
          widows="0"
        >
