### ISSUE TITLE
How would I render a local image in the pdf renderer

### ISSUE THREAD

**Issue by joshsuson** [diegomura/react-pdf#1045]
I'm rendering the pdf in the browser through the rendering component. I can't figure out how to get the image to render. I have tried multiple different ways and it always tells me that it's not a valid image extension. 

Any ideas on how to resolve this?

**Comment by themikegit** [comment]
Have you  tried to import your image like this
import Img from "../assets/some_image.png";

Then pass it in component regularly
<Image src={Img} />

**Comment by joshsuson** [comment]
I did not try that, but it worked. I don't know why I didn't think of that. Thank you so much.

**Comment by poshan-kandid** [comment]
how to render hosted image in react-pdf/renderer
