### ISSUE TITLE
Creating charts using popular chart libraries in React.js ecosystem

### ISSUE THREAD

**Issue by furkankly** [diegomura/react-pdf#1050]
**Is your feature request related to a problem? Please describe.**
I think, if it was possible to be able to somehow use Chart.js(canvas api)  / Recharts(svg) bindings we would have so much better time creating simple charts in our pdf templates. The biggest problem is **rendering charts not included in the actual page** IMO. 

Using **base64 image urls** as `<Image />` **source** need you to render the chart first in your actual page and you have to position them out of the viewport to not show them in the actual page. This solution sounds insane to me for what it achieves. I'll try it out but not sure if it will be performant at all.

Using `<Canvas />` to draw charts which look similar to what I have  in my actual page is a big pain for me and would be for most of the people i guess. That's why we use these chart libs in our actual components in the first place.

**Describe the solution you'd like**
Bindings for popular chart libraries, at least for just one of them if that's even possible.

**Describe alternatives you've considered**
Having a higher level of api to draw charts specifically using `<Canvas />`.

**Comment by diegomura** [comment]
Will be possible using SVG with the 2.0 version. The bindings between each chart library and react-pdf will not be included inside this lib

**Comment by benedict-w** [comment]
I'm trying to do just this with [chart.js](https://www.chartjs.org/). Are there any examples of tutorials floating around?

**Comment by nader-fl** [comment]
> I'm trying to do just this with [chart.js](https://www.chartjs.org/). Are there any examples of tutorials floating around?

:(

**Comment by KhanimambaMasuka** [comment]
Does anyone have an idea on how to do this with Victory Charts?

**Comment by SagnikPradhan** [comment]
Has anyone made any progress? I see only stuff from recharts

**Comment by SagnikPradhan** [comment]
Has anyone made any progress? I see only stuff from recharts
