### ISSUE TITLE
Generate PDF at different ( Kannada ) text in reactjs

### ISSUE THREAD

**Issue by prahladjshenoy** [diegomura/react-pdf#1054]
I have Register the Kannada font (from google font) in the Font family

```Font.register(
  {
    family: 'Oswald',
    src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf',
    
  },
  {
    family: 'Baloo Tamma 2',
    src: 'https://fonts.gstatic.com/s/balootamma2/v1/vEFK2_hCAgcR46PaajtrYlBbd7wfws-_Wo7H.woff2'
  }
);
```
my code

![image](https://user-images.githubusercontent.com/50204019/98441040-73c7a300-2122-11eb-820e-c2e3bb433840.png)

An error occurring as .., 

![image](https://user-images.githubusercontent.com/50204019/98441085-86da7300-2122-11eb-8d6b-ac59ab638cc4.png)

Guid me out how to use react-pdf to generate Kannada pdf .

**Comment by DewangS** [comment]
Not sure if this the right way to register multiple fonts.. have you tried separating them?
e.g. 

```
Font.register({
    family: 'Oswald',
    src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf',
    
  });
  Font.register({
    family: 'Baloo Tamma 2',
    src: 'https://fonts.gstatic.com/s/balootamma2/v1/vEFK2_hCAgcR46PaajtrYlBbd7wfws-_Wo7H.woff2'
  });
```

I am curious on how did you get that gstatic link to a true type font? **TTF**? I am struggling to register Roboto fonts from Google as the ONLY links which I can extract from their stylesheet are of **WOFF2** type fonts... see below... I even tried to download the Roboto font family and tried to use the local TTF font files from my server as a SRC, it still fails to recognise the font and there is no help available at all from anyone.. it's really disappointing that neither the author of this NPM package nor the community comes around to explain how to do these things...

```
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 100;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgVxIIzIXKMny.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

**Comment by diegomura** [comment]
Should work on latest version. Check [example](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231cccfbd590090d70384c2032984083303102a4c20719840ad30809a606200e98403a98407a980718402a9840599840069840369808c00a9840319820c03e98407498407e980744d90e4d2a007a5d7d0d2d02de0152c2ba0666567602006e3232003170285900270c3e24680c2ebc090e00331e46241121002e18007200211e11101079801a0e082ee039f9800b2828000708198282d18eb93e681e282460595046028802f915b5a809c61e0013014006e40e0401455a006900401f40e006100209f1800025000b000d9783c0015940ba004d1122de44a003b001dd46000e28142008c00750a452001250002c88164c751bccc8aa268b54090030986438180019525181941c30184eb007a0f0c30c388a151cc469a138f0944a24180f8da1009ce60066002b16c0d469359b16e82808118732c7daf2304371b4d7c76480ba48001787456369f651545b0e058a07adf7fcba7d301cd190087671aeac19786303680030e72889a4488907c0cc2cf1086812146424dafaf3505684ca6b305b2d56eb0e1c6284291590d1181e300a05c1a2b5ba2c2520cf054442a1d05802b1045400000). In the snippet above a `woff2` font is being used which is not supported on react-pdf yet
