### ISSUE TITLE
pdf(<MyDocument/>).toBlob() fails on the 2.0.0-branch

### ISSUE THREAD

**Issue by bencergazda** [diegomura/react-pdf#1056]
Thank you very much, @diegomura for this great library!

**Describe the bug**
Calling `pdf(<MyDocument/>).toBlob()` throws `Cannot read property 'length' of undefined` error at resolvePagination.js:226:36. (Firefox: `doc.children is undefined` at resolvePagination.js:226:19) The same example works correctly at @react-pdf/renderer@1.6.12

**To Reproduce**
Please check the following reduced test case: https://codesandbox.io/s/react-pdf-toblob-error-gonde?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser Chrome 86.0.4
 - React-pdf version v2.0.0-alpha.17

**Comment by emielvanlankveld** [comment]
If anyone is looking for a workaround I had success following @rmathis's directions here: https://github.com/diegomura/react-pdf/issues/932#issuecomment-655166369
