### ISSUE TITLE
[v2] - Error: ENOENT: no such file or directory, open '//data.trie'

### ISSUE THREAD

**Issue by tafelito** [diegomura/react-pdf#1058]
**Describe the bug**
I think updating to the new version of `textkit` in this commit https://github.com/diegomura/react-pdf/commit/3a5bb34e87622263ef2988f887458241a68690b8 breaks the build using webpack

I've been using the v2.beta in a `nextjs` app and everything was working fine until beta.14. As soon as I updated to beta.17 I started to get this error. I googled it and it seems that a few people had that issue and webpack with pdfkit, so I assumend it had to do with the update of `textkit` to v0.4 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser NA
 - React-pdf version 2.beta.17

**Comment by Mario8419** [comment]
same problem here, it was working with beta.14. Any idea or how is it going in general with mobile support @diegomura ?

**Comment by tomaswitek** [comment]
@tafelito @Mario8419 are you using next.js? If yes, what kind of build target did you use in your next.config.js? 
I started to have these kind of problem after changing the build target from `server` to `serverless`.
I think it's related to this issue: https://github.com/foliojs/pdfkit/issues/990

**Comment by Mario8419** [comment]
sry, I'm on gatsby. solved the enoent problem with proper state handling...the problem occurs if you do have to much rerenderings. ;)

**Comment by tomaswitek** [comment]
@Mario8419 thx for the info

**Comment by tomaswitek** [comment]
I found a workaround for next.js serverless apps.
This [commit](https://github.com/Pzixel/PDFKit-example/pull/1) should fix the issue.
It's inspired by https://github.com/Pzixel/PDFKit-example

**Comment by tomaswitek** [comment]
Hey @diegomura,
I think updating `unicode-properties` should resolve this issue: https://github.com/foliojs/unicode-properties/pull/2

**Comment by diegomura** [comment]
This is fixed in the last versions. Thanks!
