### ISSUE TITLE
Non compatible with electron-react-boilerplate

### ISSUE THREAD

**Issue by AdelNamani** [diegomura/react-pdf#1059]
**Describe the bug**
importing and using ReactPDF in the electron-react-boilerplate doesn't work after packaging the app for windows ( That works perfectly in the dev mode )

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. clone the electron-react-boilerplate
2. go to app folder, and then yarn add @react-pdf/renderer ( In the app folder to install it as a nodeJs module, I need the render function)
3. go to app/components/Home.tsx and then do something like: 

```
import React from 'react';
import { Link } from 'react-router-dom';
import routes from '../constants/routes.json';
import styles from './Home.css';
import ReactPDF from '@react-pdf/renderer';

export default function Home(): JSX.Element {
  console.log(ReactPDF.version);
  return (
    <div className={styles.container} data-tid="container">
      <h2>Home</h2>
      <Link to={routes.COUNTER}>to Counter</Link>
    </div>
  );
}
```
4. execute yarn start and notice that it works
5. execute yarn package-win and install the app, that won't work.

**Expected behavior**
That should work just like with yarn start

**Desktop (please complete the following information):**
 - OS: [Windows]
 - React-pdf version [v1.6.12]

**Comment by diegomura** [comment]
Hey! Just tried exactly what you said and worked for me. This is the builded application, not dev (although dev also worked)

<img width="1136" alt="Screen Shot 2021-05-08 at 20 08 19" src="https://user-images.githubusercontent.com/5600341/117555867-5031d680-b039-11eb-82b4-44bc3269587f.png">

Can you provide more information or check what error get's logged on your prod build? Thanks!
