### ISSUE TITLE
Uncaught TypeError: a.o is not a function

### ISSUE THREAD

**Issue by jatinnair** [diegomura/react-pdf#1060]
After we build the react code using babel, it throws the below error in browser console on execution from a server :

Invalid asm.js: Unexpected token
Uncaught TypeError: a.o is not a function

Tried with all the older versions of this library but the error remains the same

The react-pdf/renderer library works fine when direct run from create-react-app. But it throws error on the react-pdf/renderer library once we build it and try to run the web app in browser.

![err](https://user-images.githubusercontent.com/38095529/99084380-e0441580-25ec-11eb-8d3f-af0e8a0bd797.JPG)

 - OS: Windows 10
 - Browser: chrome
 - React-pdf version: v1.6.12

**Comment by diegomura** [comment]
Can you provide a way of replicating it?

**Comment by jatinnair** [comment]
Hi,

It’s been too long that I created the ticket. Thanks! But I rectified the issue by updating my react-dom and react-scripts library to the latest v17 from v16.

Regards,
Jatin
