### ISSUE TITLE
Can't build with dfa 1.2.0

### ISSUE THREAD

**Issue by kemalturksonmez** [diegomura/react-pdf#1061]
One of the dependancies for @react-pdf/fontkit is the dfa library. Currently the libraries current version is 1.2.0 and it causes the build procedure to exit out. One can still build by rolling back the dfa library to 1.1.0 and 1.0.0. Just thought I should give A heads up. Here's a screen shot of the specific file that throws the error.
<img width="445" alt="Screen Shot 2020-11-17 at 12 28 09 PM" src="https://user-images.githubusercontent.com/56357795/99425444-d5310400-28d0-11eb-8f6b-fd7a75cab30d.png">

**Comment by diegomura** [comment]
Thanks! Keeping #643 for dfa@1.2.0 bugs. I'll try to solve it asap
