### ISSUE TITLE
Issues using custom fonts

### ISSUE THREAD

**Issue by joshsuson** [diegomura/react-pdf#1064]
I am having all sorts of issues using custom fonts. 

If I use the relative path on the fonts then I get an error saying unknown font format even though it's just a .ttf file. If I import the font first then I get dataUrl.split is not a function. I tried hosting my font on S3 but I'm very inexperienced when it comes to that and can't seem to get over CORS problems from that route. Nevertheless, it all ends in the error can't access property "hasGlyphForCodePoint", font is null. 

Any advice or help would be greatly appreciated.

**Comment by benRivello** [comment]
Are you running react-pdf in node.js? I noticed the required font files were located off the 'default' property.

So instead of 
```
const bold = require("../../../assets/fonts/sharpsans/SharpSansNo1Bold.ttf")
```
it am using
```
const bold = require("../../../assets/fonts/sharpsans/SharpSansNo1Bold.ttf").default
```
