### ISSUE TITLE
Wrap on text with border causes border to disappear

### ISSUE THREAD

**Issue by tg137** [diegomura/react-pdf#1065]
## Description
Text that spans multiple pages has no padding between text and border.

This ultimately means that the border disappears because the padding isn't applied to the text on the second page post-wrap.

Perhaps I'm missing a style setting somewhere but I can't find what it is in the docs.

## Screenshot
![wrap](https://user-images.githubusercontent.com/14982322/99730155-dec69180-2ab3-11eb-89b3-3d44abe253ea.PNG)

## Code snippet
Style for the text box:
```
textBox: {
    margin: 20,
    fontSize: 12,
    paddingTop: 15,
    paddingLeft: 5,
    fontFamily: "Frutiger",
    backgroundColor: "#E8EDEE",
    border: "1pt solid #000",
    width: "560pt",
    minHeight: "250pt",
    lineHeight: "2pt"
}
```
Style for the page:
```
page: {
    backgroundColor: "white",
    paddingTop: 25,
    paddingBottom: 25
}
```

## Expected behaviour
That the padding on the `textBox` be applied to the new textbox created on the second page. Although I suspect I'm missing a style setting somewhere!

**Comment by diegomura** [comment]
This is actually on purpose...there are also cases in which you don't want the paddings as well. Maybe we can add a way of toggle this, I'm open to suggestions about what a nice API for this would be

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/733
