### ISSUE TITLE
dpi / resolution prop (300 dpi)

### ISSUE THREAD

**Issue by sines99** [diegomura/react-pdf#1066]
Please add a 300 dpi version. Generating PDFs for printing with 72 dpi is a no-go.
300 dpi is a must have!

How about a document prop "dpi" (number like 300) or "resolution" (string / boolean like "low - high" / true - false)?

**Comment by jackvik** [comment]
Is this being added?

**Comment by TD-DO** [comment]
This would be very helpful because right now my images are blurry

**Comment by rodionme** [comment]
> This would be very helpful because right now my images are blurry

Faced the same problem with blurry pictures.

I have found that if you save images at 2x size (f.e. 46x46), and then set them to their normal size through styles (`width: 23, height: 23`), the result is quite acceptable.

Check screenshots from generated PDF:
1x size
![Screenshot 2021-11-18 at 12 20 36](https://user-images.githubusercontent.com/5216046/142397631-d4695b19-0080-4688-b891-1fc0144e8cb8.png)

2x size
![Screenshot 2021-11-18 at 12 21 15](https://user-images.githubusercontent.com/5216046/142397626-4fe33ea5-eaa0-45fc-b4ee-d513efdbc1c7.png)
