### ISSUE TITLE
Rendering performance problem with node and large documents

### ISSUE THREAD

**Issue by alanatkinson** [diegomura/react-pdf#1069]
**Is your feature request related to a problem? Please describe.**

I'm processing text files to create PDFs on demand using node SSR. 
I have a lot of large text files - the sample I'm using is on the smaller side at 500 pages.
Each page is a single text string of 1...n lines so the pages are built like this:

```
for (let i=0; i<arr.length; i++) {
        map.push(
            <Page size="tabloid" orientation="landscape" key={`pdf-page-${i}`} wrap="false">
                <Text style={style.text}>{arr[i]}</Text>
            </Page>
        );
    }
```
About as simple as it could possibly be in other words.
I need to convert the document to a base64 representation so I can inject it into a different process that takes either these files or other (real) PDFs and shows them in a browser.

To convert the PDF, I call the toBuffer() function, but it takes an inordinate amount of time to return.
It takes me about a minute to return from the call with my sample.
A few console.log timing outputs tell me that 59s out of the minute is in the first render. The rest of the process takes under a second.

**Describe the solution you'd like**
Something more performant, or a workaround to get this data out in a more timely manner. Some of these PDFs are 10000 pages and I can't have a user wait for 20 minutes to get a response.

**Describe alternatives you've considered**
I may have to do this manually if there's no workaround. This is to see if there's something I missed. Code runs through dist/es if that helps.

**Additional context**

**Comment by alanatkinson** [comment]
For completeness I moved the code to build the PDF and convert it to base64 into the browser to see what happened there.
60s goes to 30s. Still not as good as I would hope, but a healthy improvement.

Code's running in chrome on a mac.

**Comment by diegomura** [comment]
Sorry to hear that. 10000 PDF document seems like a lot, and it might be something that this library might not be prepared for. I recommend you testing the upcoming 2.0 version (`2.0.0-beta.20` on npm) but I cannot promise you will have significant different results. 

Trust me, if I could provide "something more performant" I would, but PDF generation and layout computation is expensive. This is not a new feature

Keeping performance issues on #544. Please feel free to contribute with more information there.
