### ISSUE TITLE
Base64 image string does not work with PDFDownloadLink

### ISSUE THREAD

**Issue by ShyamKatti** [diegomura/react-pdf#1072]
**Describe the bug**
PDFDownloadLink does not support having an Image component with base64 string data of the image as it's source.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Use the `toBase64Image()` provided in Chart.js library to export a chart as base64 string. The output looks like the following:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABWAAAAK...`

2. In the impl of the document associated to `PDFDownloadLink`, I am doing this:
`<Image src={{data:<base64 string data>, format: 'png'}}></Image>`.

3. Don't see the image added to the pdf and the entire pdf css is broken now.

**Expected behavior**
Expected to see the chart inserted as an Image component in the downloaded pdf.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome, Safari
 - React-pdf version : `npm list --depth=0 | grep react-pdf
├── @react-pdf/renderer@1.6.12
├── react-pdf@5.0.0`

**Comment by pengw00** [comment]
@ShyamKatti , is this resolved? I am getting same issue.

**Comment by ze-gomes** [comment]
It worked for me like this:

```javascript
const base64imgString = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABWAAAAK..."

....

<Image src={base64imgString} allowDangerousPaths="true"></Image>
```

**Comment by swinogrodzki** [comment]
@ze-gomes You are incorrect. Your solution only applies to server (Node) side rendering, and @ShyamKatti clearly said that they're using PDFDownloadLink, that is @react-pdf/renderer on-fly (browser-side) rendering, not the server side one. The documentation also clearly states that allowDangerousPaths is Node only feature. Please don't confuse the devs. Thank you

**Comment by ze-gomes** [comment]
> @ze-gomes You are incorrect. Your solution only applies to server (Node) side rendering, and @ShyamKatti clearly said that they're using PDFDownloadLink, that is @react-pdf/renderer on-fly (browser-side) rendering, not the server side one. The documentation also clearly states that allowDangerousPaths is a Node only feature. Please don't confuse the devs. Thank you

It was how I solved a similar issue, that's why I posted it. It might serve someone else with a similar problem. Im by no means an expert in the matter

**Comment by diegomura** [comment]
It's fixed on latest versions (check doc below)

This is my code:

```jsx
const MyDoc = () => {
  return (
    <Document>
      <Page style={styles.body}>
       <Image src={IMG} />
      </Page>
    </Document>
  )
}

const App = () => {
  return (
   <PDFDownloadLink document={<MyDoc />}>
      {({ url }) => {
        return (
          <div>{url}</div>
        )
      }}
    </PDFDownloadLink>
  )
}
```

[document (1).pdf](https://github.com/diegomura/react-pdf/files/6332899/document.1.pdf)

**Comment by outpark** [comment]
any solution to this? this is still not fixed

**Comment by Rammah-N** [comment]
Still not working

**Comment by yasinkavakliat** [comment]
This issue still occurs in v4.1.6 in January 2025.
