### ISSUE TITLE
Using Redux with library react-pdf

### ISSUE THREAD

**Issue by maitedev** [diegomura/react-pdf#1074]
I want to use the react-pdf library but if impossible to connect with redux. I am getting the following error:

Error: Could not find "store" in the context of "Connect(AdminForm)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(AdminForm) in connect options.

`import React, { Component } from "react";
import { connect } from "react-redux";
import { Page, View, Document, StyleSheet } from "@react-pdf/renderer";
import FormTopRight from "./reportContent/header/FormTopRight";
import FormTopLeft from "./reportContent/header/FormTopLeft";
import FormContent from "./reportContent/FormContent";

const styles = StyleSheet.create({
  page: {
    flexDirection: "row", 
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
});
class AdminForm extends Component {
  render() {
    return (
      <Document>
        <Page size="A4" style={styles.page}>
          <FormTopLeft />
          <View style={styles.section}>
            <FormTopRight />
          </View>          
          <FormContent />
        </Page>
      </Document>
    );
  }
}
export default connect(null, null)(AdminForm);`

**Comment by ubinatus** [comment]
Hi @maitedev. The mentioned issue is not associated with react-pdf, it escapes the scope of this repo. You could find some good answers on StackOverflow or even on redux's repository itself. Just as a friendly reminder, make sure to either wrap your root component with <Provider store={store}></Provider>.

**Comment by maitedev** [comment]
Thanks !!

**Comment by mobileexpert1** [comment]
I am also getting the same erorr for missing wrapper but my app is already wrapped

**Comment by maitedev** [comment]
Hi  @mobileexpert1 I'm sharing part of my code with you to see if it's of any use to you.

`import React from "react";
import { Page, View, Document, StyleSheet, Font } from "@react-pdf/renderer";
import HeaderTopRight from "./header/headerTopRight";
import HeaderTopLeft from "./header/headerTopLeft";
import ReportContent from "./ReportContent";

const ReportMain = (props) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.row}>
          <View style={styles.leftRow}>
            <HeaderTopLeft />
          </View>
          <View style={styles.rightRow}>
            <HeaderTopRight />
          </View>
        </View>
        <ReportContent
          patient={props.patient}
        />
      </Page>
    </Document>
  );
};

export default ReportMain;

import React from "react";
import { View, Text, StyleSheet, Font } from "@react-pdf/renderer";
import RxCardList from "./rxCard/RxCardList";
import AgreementCard from "./agreementCard/AgreementCard";
import SignatureCard from "./signatureCard/SignatureCard";
import { handleColumnDateFormat } from "../../../../../../../../../core/helpers/dateHelpers";
import RobotoLight from "./static/font/Roboto-Light.ttf";
import CopaymentCard from "./copaymentCard/copaymentCard";

// Register font
Font.register({ family: "Roboto-Light", src: RobotoLight });

const styles = StyleSheet.create({
  container: {
    marginTop: 30,
  },
  column: {
    flexDirection: "column",
  },
  hRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  hLeftRow: {
    flexDirection: "column",
    justifyContent: "center",
  },
  hRightRow: {
    flexDirection: "column",
    justifyContent: "center",
    boxSizing: "border-box",
  },
  hCenterRow: {
    flexDirection: "column",
    justifyContent: "center",
  },
  row: {
    flexDirection: "row",
    marginTop: 20,
  },
  leftColumn: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContentSelf: "flex-start",
    marginLeft: "auto",
    marginRight: "auto",
    width: "50%",
  },
  rightColumn: {
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContentSelf: "flex-end",
    marginLeft: "auto",
    marginRight: "auto",
    width: "50%",
  },
  signatureColumn: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContentSelf: "flex-end",
    marginLeft: "auto",
    marginRight: "auto",
    width: "50%",
  },
  textField: {
    flexDirection: "column",
  },
  label: {
    fontSize: 10,
    color: "grey",
    fontFamily: "Roboto-Light",
    justifyContentSelf: "flex-end",
  },
  value: {
    fontSize: 10,
    fontFamily: "Roboto-Light",
    justifyContentSelf: "flex-end",
    marginTop: 5,
  },
  hr: {
    display: "block",
    height: 1,
    border: 0,
    borderTop: 1,
    margin: 1,
    padding: 0,
    borderColor: "grey",
    backgroundColor: "grey",
  },
});

const ReportContent = (props) => {
  return (
    <View style={styles.container}>
      {/* column 1 */}
      <View style={styles.column}>
        <View style={styles.hRow}>
          {/* textField 1 */}
          <View style={styles.hLeftRow}>
            <View style={styles.textField}>
              <Text style={styles.label}>Patient</Text>
              <Text style={styles.value}>{props.patient}</Text>
              <View style={styles.hr}></View>
            </View>
          </View>
......

    </View>
  );
};

export default ReportContent;

`
