### ISSUE TITLE
How to register Google fonts?

### ISSUE THREAD

**Issue by DewangS** [diegomura/react-pdf#1075]
I want to use [Roboto Font](https://fonts.google.com/specimen/Roboto) from Google. Currently I am using this font family for my Reacty app by using the css though the Font.Register() api of react-pdf doesn't allow CSS, how am going to use this font? So, far I even tried to download TTF font files from Google and placed them under my /public/fonts folder and tried to use my /public/fonts/Roboto.ttf as a source and it fails to compile. Any idea?

When I tried below ....

```
Font.register(
    '/public/fonts/Roboto-Regular.ttf',
    { family: 'Roboto' },
  );

```
I got the below error ...

> Unhandled Rejection (Error): Unknown font format
> push../node_modules/@react-pdf/fontkit/dist/fontkit.browser.es.js.fontkit$1.create
> node_modules/@react-pdf/fontkit/dist/fontkit.browser.es.js:68
> FontSource._callee2$
> src/font/font.js:44
>   41 | } else if (BROWSER || isUrl(this.src)) {
>   42 |   const { headers, body, method = 'GET' } = this.options;
>   43 |   const data = await fetchFont(this.src, { method, body, headers });
> > 44 |   this.data = fontkit.create(data);
>      | ^  45 | } else {
>   46 |   this.data = await new Promise((resolve, reject) =>
>   47 |     fontkit.open(this.src, (err, data) =>

I also tried below though it refers to CSS NOT the actual font so, obviously it won't work and I can't find direct links to font files on Google Fonts ...

Font.register(
    'https://fonts.googleapis.com/css?family=Serif',
    { family: 'Roboto' },
  );

**Comment by DewangS** [comment]
This is clearly not working with Google fonts (TTF and woff2) I even tried to extract the gstatic link from the CSS and still getting the same error. i.e. unknown font format. So, the question is how do we use different font styles in a single document without being able to register the font? I would really appreciate if someone can please get back with even a YES or NO answer to this feature ?

```
Font.Register(
'https://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgVxMIzIXKMnyrYk.woff2', 
{ family: 'Roboto'})
```

**Comment by linhnguyen11** [comment]
"Can you try importing the font directly in your import statements of JS file like
import someFont from 'someDir/Lato-Italic.ttf';
and then use someFont in your src attribute of Font.register().
The only disadvantage is that you have to import all the fonts individually."

**Comment by DewangS** [comment]
@linhnguyen11 

Thanks very much for the tip. Yes, it worked..!!!! below is my code extract if anyone else run in to this issue.

```
import Roboto from "../../../../assets/fonts/Roboto-Regular.ttf"

Font.register({
    family: 'Roboto',
    format: "truetype",
    src: Roboto
  });

const styles = StyleSheet.create({
    page: {
      marginTop: 0,
      paddingLeft: "2mm"
    },
    blankText: {
        marginBottom: -10
    },
    textName: {
      marginLeft: 12,
      paddingTop: 15,
      fontSize: 12,
      fontWeight: 'heavy',
      textAlign: "justify",
      fontFamily: "Roboto",
    }
});
```

**Comment by nanokoko89** [comment]
> @linhnguyen11
> 
> Thanks very much for the tip. Yes, it worked..!!!! below is my code extract if anyone else run in to this issue.
> 
> ```
> import Roboto from "../../../../assets/fonts/Roboto-Regular.ttf"
> 
> Font.register({
>     family: 'Roboto',
>     format: "truetype",
>     src: Roboto
>   });
> 
> const styles = StyleSheet.create({
>     page: {
>       marginTop: 0,
>       paddingLeft: "2mm"
>     },
>     blankText: {
>         marginBottom: -10
>     },
>     textName: {
>       marginLeft: 12,
>       paddingTop: 15,
>       fontSize: 12,
>       fontWeight: 'heavy',
>       textAlign: "justify",
>       fontFamily: "Roboto",
>     }
> });
> ```

Hi
Thanks for your conclusion
Do you know how to add fonts with bold, medium, italic ?
Thanks

**Comment by DewangS** [comment]
@nanokoko89 not sure about individual TTF as when you download the Roboto font family from Google, you do get various TTF like Roboto-Bold.ttf, Roboto-Medium.ttf etc .. I normally use the fontweight CSS styling to make it bold.

**Comment by qcho** [comment]
FTW Just found a better solution in https://stackoverflow.com/a/70577891

Resulting in something like:
```ts
Font.register({
  family: 'Inter',
  fonts: [
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyeMZhrib2Bg-4.ttf',
      fontWeight: 100,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyfMZhrib2Bg-4.ttf',
      fontWeight: 200,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf',
      fontWeight: 300,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf',
      fontWeight: 400,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf',
      fontWeight: 500,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf',
      fontWeight: 600,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf',
      fontWeight: 700,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyYMZhrib2Bg-4.ttf',
      fontWeight: 800,
    },
    {
      src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf',
      fontWeight: 900,
    },
  ],
});
```

**Comment by mmubashshir** [comment]
This actually works for me, and coincidentally I wanted  the same font 'Inter'. And all weights are also accessible. Thank you for the solution.

**Comment by Loner291999** [comment]
> FTW Just found a better solution in https://stackoverflow.com/a/70577891
> 
> Resulting in something like:
> 
> ```ts
> Font.register({
>   family: 'Inter',
>   fonts: [
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyeMZhrib2Bg-4.ttf',
>       fontWeight: 100,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyfMZhrib2Bg-4.ttf',
>       fontWeight: 200,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf',
>       fontWeight: 300,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf',
>       fontWeight: 400,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf',
>       fontWeight: 500,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf',
>       fontWeight: 600,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf',
>       fontWeight: 700,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyYMZhrib2Bg-4.ttf',
>       fontWeight: 800,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf',
>       fontWeight: 900,
>     },
>   ],
> });
> ```

bless you, wanted the same font

**Comment by franklinjavier** [comment]
> FTW Just found a better solution in https://stackoverflow.com/a/70577891
> 
> Resulting in something like:
> 
> ```ts
> Font.register({
>   family: 'Inter',
>   fonts: [
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyeMZhrib2Bg-4.ttf',
>       fontWeight: 100,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyfMZhrib2Bg-4.ttf',
>       fontWeight: 200,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf',
>       fontWeight: 300,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf',
>       fontWeight: 400,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf',
>       fontWeight: 500,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf',
>       fontWeight: 600,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf',
>       fontWeight: 700,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyYMZhrib2Bg-4.ttf',
>       fontWeight: 800,
>     },
>     {
>       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf',
>       fontWeight: 900,
>     },
>   ],
> });
> ```

it worked here too... thank you

**Comment by Elham13** [comment]
> @linhnguyen11
> 
> Thanks very much for the tip. Yes, it worked..!!!! below is my code extract if anyone else run in to this issue.
> 
> ```
> import Roboto from "../../../../assets/fonts/Roboto-Regular.ttf"
> 
> Font.register({
>     family: 'Roboto',
>     format: "truetype",
>     src: Roboto
>   });
> 
> const styles = StyleSheet.create({
>     page: {
>       marginTop: 0,
>       paddingLeft: "2mm"
>     },
>     blankText: {
>         marginBottom: -10
>     },
>     textName: {
>       marginLeft: 12,
>       paddingTop: 15,
>       fontSize: 12,
>       fontWeight: 'heavy',
>       textAlign: "justify",
>       fontFamily: "Roboto",
>     }
> });
> ```

It didn't work form me, got following error

Cannot find module './Roboto-Regular.ttf' or its corresponding type declarations.

**Comment by Elham13** [comment]
> > FTW Just found a better solution in https://stackoverflow.com/a/70577891
> > Resulting in something like:
> > ```ts
> > Font.register({
> >   family: 'Inter',
> >   fonts: [
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyeMZhrib2Bg-4.ttf',
> >       fontWeight: 100,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyfMZhrib2Bg-4.ttf',
> >       fontWeight: 200,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf',
> >       fontWeight: 300,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf',
> >       fontWeight: 400,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf',
> >       fontWeight: 500,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf',
> >       fontWeight: 600,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf',
> >       fontWeight: 700,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyYMZhrib2Bg-4.ttf',
> >       fontWeight: 800,
> >     },
> >     {
> >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf',
> >       fontWeight: 900,
> >     },
> >   ],
> > });
> > ```
> 
> bless you, wanted the same font

I got this error

Could not resolve font for Inter, fontWeight 800

**Comment by mohamedtsx** [comment]
For TTF URLs of Google Fonts, check this [gist](https://gist.github.com/karimnaaji/b6c9c9e819204113e9cabf290d580551).

**Comment by qir4ni** [comment]
> > > FTW Just found a better solution in https://stackoverflow.com/a/70577891
> > > Resulting in something like:
> > > Font.register({
> > >   family: 'Inter',
> > >   fonts: [
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyeMZhrib2Bg-4.ttf',
> > >       fontWeight: 100,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyfMZhrib2Bg-4.ttf',
> > >       fontWeight: 200,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf',
> > >       fontWeight: 300,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf',
> > >       fontWeight: 400,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf',
> > >       fontWeight: 500,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf',
> > >       fontWeight: 600,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf',
> > >       fontWeight: 700,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuDyYMZhrib2Bg-4.ttf',
> > >       fontWeight: 800,
> > >     },
> > >     {
> > >       src: 'http://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf',
> > >       fontWeight: 900,
> > >     },
> > >   ],
> > > });
> > 
> > 
> > bless you, wanted the same font
> 
> I got this error
> 
> Could not resolve font for Inter, fontWeight 800

Thank you, this works for me when i tested on `https://react-pdf.org/repl`. You just have to use `https` instead of `http`
