### ISSUE TITLE
Can't resolve 'stream' and 'zlib' when build app with nx monorepo

### ISSUE THREAD

**Issue by EmilBuszylo** [diegomura/react-pdf#1079]
**Describe the bug**
I'm trying to use @react-pdf/renderer in react project based on [NX monorepo](https://nx.dev/latest/angular/getting-started/why-nx). During build app (or just run dev server), I got errors:

![pdf errors](https://user-images.githubusercontent.com/20420991/101614541-5e89b100-3a0d-11eb-99ab-57580bd8a8e0.png)

I was trying to resolve the problem by install `stream` and `zlib` packages but after that, during build time I get:
![zlib_bindings_error](https://user-images.githubusercontent.com/20420991/101615067-fb4c4e80-3a0d-11eb-9bc5-29211c6b7ae5.png)

Any help on this would be appreciated.

**Comment by diegomura** [comment]
It seems nx it's not loading the correct bundle. If you are trying to us the lib server side, try importing it directly from `@react-pdf/renderer/dist/react-pdf.es.js` or `@react-pdf/renderer/dist/react-pdf.browser.es.js`. Closing for now. Let me know it works!

**Comment by exihuatl** [comment]
It does not. I have the same error as mentioned in the ticket.

**Comment by knoefel** [comment]
Please reopen this issue. I have exactly the same problem after using `@react-pdf/renderer` with NX. @exihuatl Were you able to fix the problem?

**Comment by starkWebDev** [comment]
I also have the same issue using NX monorepo. Explicitly expressing the import location did not solve the issue.
