### ISSUE TITLE
(node:1568) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by Constantini21** [diegomura/react-pdf#1086]
![image](https://user-images.githubusercontent.com/23006463/103309440-d1c28980-49f3-11eb-8d3a-8abb8270c8b4.png)

error happens when accessing this component

![code-snapshot](https://user-images.githubusercontent.com/23006463/103309704-8b215f00-49f4-11eb-9434-caf652e4bb4d.png)

**Comment by diegomura** [comment]
Duplicated #589
