### ISSUE TITLE
SourceSansPro-regular not correctly rendered

### ISSUE THREAD

**Issue by mnowotnik** [diegomura/react-pdf#1088]
**Description**

SourceSansPro-regular not correctly rendered

**Steps to reproduce**

1. Choose "download family" from https://fonts.google.com/specimen/Source+Sans+Pro
2. Register SourceSansPro-regular font with react-pdf
3. Create a sample to render:
```
    <Document>
      <Page >
        <Text style={{fontFamily:"SourceSansPro"}}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni voluptatibus dolores accusantium similique mollitia eligendi autem? Voluptate fugit nulla quia tempore consequatur? Perferendis, dicta. Architecto neque iusto quas fuga quia?</Text>
      </Page>
    </Document>
```
4. Render pdf
5. See output
![lorem](https://user-images.githubusercontent.com/8244123/103382047-dff4d080-4aed-11eb-9cdf-0b71a3a46e50.png)

**Expected behavior**

See properly rendered lorem ipsum text.

**Additional information**

SourceSansPro-italic seems to be rendered correctly. Others not so much.

**Environment**

 - react-pdf version: 1.6.12
 - React version: 16.12.0

**Workaround**
Get fonts from https://github.com/google/fonts

**Comment by firzx77** [comment]
Hi @mnowotnik,

Have you fixed this? I'm facing the same issue

**Comment by firzx77** [comment]
@mnowotnik I don't know what was wrong, but what I did is convert the .ttf font into otf via this service: https://convertio.co/
and convert back to .ttf, and it works.

**Comment by mnowotnik** [comment]
@firzx77  I switched to downloading fonts from https://github.com/google/fonts ; they work without a problem

**Comment by ze-gomes** [comment]
> @firzx77 I switched to downloading fonts from https://github.com/google/fonts ; they work without a problem

Where did you find  SourceSansPro on google fonts repository? I've searched everywhere and could not find it.

Having the exact same issue, the stranger thing is that it worked perfectly before, only yesterday I started having this bug

**Comment by mnowotnik** [comment]
@ze-gomes  https://github.com/google/fonts/tree/master/ofl/sourcesanspro

**Comment by ze-gomes** [comment]
> @ze-gomes https://github.com/google/fonts/tree/master/ofl/sourcesanspro

Thank you! I eventually found the .otf version of the font and it worked fine.

**Comment by diegomura** [comment]
Glad it's fixed
