### ISSUE TITLE
How can I use PDFViewer without rendering toolbar?

### ISSUE THREAD

**Issue by azat-io** [diegomura/react-pdf#1090]
Hi there!

I need property in PDFViewer component to render pdf without toolbar. You can make it just by adding `#toolbar=0` to blob PDF URL

![image](https://user-images.githubusercontent.com/5698350/104010392-78114a80-51bd-11eb-9872-7de1cbbce612.png)

**Comment by diegomura** [comment]
No. The PDFViewer its just an iframe and uses the native browser PDF viewer (as you would see if you open any PDF using your default browser). There's nothing this lib can to to change how it looks. However, you can try building your own PDF viewer, similar to how the REPL in the site works. Here's the code for reference: https://github.com/react-pdf/site/blob/master/src/components/Repl.js
