### ISSUE TITLE
Incomplete or corrupt PNG file

### ISSUE THREAD

**Issue by fabionke** [diegomura/react-pdf#1091]
**Describe the bug**
I want to insert an Image in the pdf. My image is in base64 string format, but when i try to insert it I recived this warning in browser console:

![image](https://user-images.githubusercontent.com/50916563/104039471-b5ce9d00-51d6-11eb-9fb8-1e89eb15b242.png)

and the image isn't displayed.

**To Reproduce**
try to display this image: 

`R0lGODlhqgHBAMQQAIWWpcLL0khieBo7VvDy9ODl6CpIYmd9j9HY3aOwu3aKmjlVbbK9x5SjsFhwgwsuS////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAABAALAAAAACqAcEAAAX/ICSOZGmeaKqubOu+cCzPdG3feK7vfO//wKBwSCwaj8ikcslsOp/QqHRKrVqv2KwWAeh6v+CweEwum8/otHptZgy57Lh8Tq/bw24h/L5GsAgCD4KDhIWGh4iJiouMjY6PkI0GeT0FgZGYmZqbnJ2IBgE/lp6aAgUpBAOkq6ytrpEJPamvtLW2q7E8s7eLA6cnl7zCw8SFAwQ8wcXLzK/Hyc2GAicI0dbXnQA71djd3o0N298PfiUN4+jpgtM65+rv3ew5AOPaJfTw+dHyOPj6/8T43fDXzR4JggAT1hJoA6HCh6wY1nBozeAIihAzbpJIA6PGj5A4zvDIzKIIkiBT/yoSKQOlypeFWMZwScwkBJowYcqEgTOnyp0vevKyKdTnR6AuihrNiLSF0lpEl0ol1JTF06kAq664+ioqVqlaVXD9Ci9sirGtvJL1aRYF2rXo2p54u0ot3JdyTdC9G2/HXk92+YLMe08wXr/19Br+iXjx4MbeAjt+SPjg5KOQCyq+zDQz54SVLyYu/Jmy59L6Qp8cbRk16NOu36m+yVp07H+z/96mlbv26t35egMvCzua5OHfwunQjXyV8Mibm497tlx6uueaSVv3Fqr49mbYsR3/XsxAOe/ki4W/Nj7aAAV84sufc54Hc07v59cxEBf9svbMDFCfFgSKNd2AThCwwP8461UUXTcHFCjhVuNESAUDDPpXDID/TejhXL5BEUCG1X3D4YYfpmgbdFSM+E2Dxj0onooq3qeJTU+46A2MzZxYE40p2pgJjk7o2FeJLLaWJJASCokJkU0YiQ2PJcnIHpMeOhkJlExIeQ2VHWqXHZYFagkJl0t4aQ2YKIo5I5llhpgjifOEaOYjaMIZxZ2O5JmEmvto+KObV+qpBZ+N+IkEoOAJOoyPjxp6qJxF0tmPnZRKumemXVo6EKYmaooFoowoegSjzLA5qJJjikoFqYuYagSqy6gaKaEOuloFrIrIWgSt6jkqDKTD6rorp2l62hCoSxoLBa+J+EoEsAEJO5T/lbk6u2moLSo7EbOtausEtIhIOwS1w9haLK4xivssskqgK4y617Lbo7vvcjuFvLzQewux9eLbBLmHmCsEv7f4awvA/wo8Lrx/etsRuG86vATBhhgchDs7WtuwvVVafDHEp6ryoscLY9uuDgrwl9ICB3RnH8kAuGyYwlCpfC+SMCnQA8aF+An0mijnDHKYOSjT88z6qqC0YDjTwnDKOjz9ksyXNp2C1XdF3ZXOISctlYV1ao0C13B57crURou9lNpptYD2WnCzwrbUO8yNGc8VO31Z3XWBjTQOemsEOCl+Fo7V4YAJ3qbbRjGejdx/F4330Y8TDpblX7Og+FSSc3J3/+eQs8X52pRPFvomo6Ne9eZ8F7rC57CX3SxtZtdAu0Kr35i6Y70P6fiqmr99etyeVx57tiuGa8Pury2/st+qH2/38LeWnlPwT/6+GPdbYr+u9jpZH3jy1Uu/M6t93wB9VuYj7v3N8TeOOfHu15717cAob7vzQxuExkzwPtzUb3LoA94BRSe+gBUvcgtk3fygFkHf3S97DzSd+sJGPQVucHC/4R8NCpiaCgovgd8zYfcuOL4Mbk+F4UMh/T6YuRA6T3f6+1TuCOi//QGQZBM8DA3xd7Ye6vB2ARTEAEvggBwua4clOIARn4hEILKgADZ74RAxiIoFefB/7cOdCGsQgP8ymvGMaExjGaUosZEAUY1wjKMczcjGk22xhTYM4xPqeCQwyk4KfJwSDM/UwI/tq40tseKvEDkTiv0xCgizBfgI2S07+pF5eXykiBjJE0VOi5NBcSQmN2lJH+qxUqU84g+h2KlUUvGGqOzYHR2YyVHOyZXfYmWycDkxsyXxAUv0QSQXMkg8VWGYvClmnwpJtUPy0o26jBcokyLK6UFymk7x5LmwaZVqrk8KyHzFJI1ZSVle0ppihGWUuEmhaEbsmYn0pTYPxk4DuXNR9TyLNzl4TXg28p6nyqdb9glCUprTlJq85UFVGcZfBrMH4XTFOJdZzj4idJQOPaZAQQTQWW3/lJlta94p1+nPTnZ0kSUNpTxP+smUUpOl23RpNlc6xlYu9JUjtalFGarJjFZUkLM0JDg/ykJapjOnu7xpLmua1J3itKfzDEJEWzHRRGlUpt2kqTp1CtRzfrOfSu1lFb/hs59+SZlWNSvRgtpMkV7DAMiYQiDPytaQgtWpS13lixgwx7769a+/fEBVS3XVsEJzrOmhq1f5aVC8ilWviQ1UXS/nTMPGE7GRbdRkSTdUrLYTs5mtFVoJq1bJLraggbXOYGNVWMceFrKhDdZmXVdZ114WtrFN12hZW1rNnraGR83tvHbbq9Z29aLoTK10Vlvc3qaKuNECqXA3At1yGVex/8j9anCnK8nqFuy6a/0tEZXbHOZG17minS3y2Mfd7qr3euiVrXi5uN32itO7GQOvabPLWPIix7zWjW+13ns+9tr3vgSWn4B1m2D7GfjAVMVv0PTrW/6iFsIJkzAhHsqDqUZEwwKULoYbAeDvLni4DUbgg0fsiRLn98T9ArESRczilcgYmBR+booZWNQaO8LFE4ZxhncswR77mBFA3nCO0ztfPEIAQ0dmBdlwAGVvUGIKFdpBlbtx5RFkMcqcwBoOvhwNA1xhrtEQ8w3I3Awzn8DDYJ5yDuDciS5LYRfXKKuWrZyCBJgMzJmQsw78bI0B5OIKCGAzMfTMA0K759AoKP+AAkhY4wE4QM07kDSlMyEABfwiCwRogAD+LAwDxCwIkvZiQDwtsla7+tWwjrWsZ03rWtv61rjOta53zete+/rXwA62sIdN7GIb+9jITrayl83sZjv72dCOtrSnTe1qW/va2M62trfN7W57+9vgDre4x03ucpv73OhOt7rXze5244sACFIBAuK6ggLEuwUEMGMMzEhvIdi7RTAowKchWsZ+Z4HfTPj3hwpQxnuvYBaMNpAv6q0KSLMAAQf48gIAYHASFKBmhTD1wEUgiAGkwGUkcJEDPF7xFDSRHCJQUC9aoAqTkyAQSHER1hKQiAEcYOQlkPSXRX6CR5yC1IooBzf/OEIAAKhaEEQ3wcsxfYKaX7HlKnjECHieiEv37wFAF0ECXk4Vi0OAjWrWUdhLsAuqj0ABUHcBAeDec+WYA+mFUEC/B5ECvo/ARfxwEXV4+IDuUKsFfh/BIMz+dYvoTUADVUTEIfCIUFReBIA/QQPwTgi9l+ASbi9B4vX5ADf33REj4HwhBA16EyDg6YYwz80FkfZBCDo6oYfAn+1sApkzQsxofjHJBXH6B6R8HccXxO0h0HoIHJ4Fo6d83FegI8czAq4mCH4hFrB3R/jh8s5HfhTTOoLmQ5/4K9h91lE/fEZE3PwiQIDqCzH7wpvASGuP+Z9Dz3VBrHx2g/AefJVv/wlwCdjXPAeQAAGQbwxQR/URfSQwepn3d4SAac3nIgsgR4iHfoq3eAA4Y+UnCA2QRnVkdyJAd8rHV87XgH82ZWk0CGkUf2jkRSN4RnE1gSPAMQ+QgAsYAA0Ig59Hey4AgSXQf4KlAi9Ie2jUgYWXRgqwf/WHNXhmACMocAHQAC7zfyIAf5hHCMtnQ6EHe/kHAf3nAB3nfJPgcYOwAPFmCRFHhO2XfIFHCAvwdYYnfjUQfYRgem+mZCFof5tRhyPADQ/AhidQAKrGe3GYOlSHgxBQAIMgeybghoSXe0z4gYMwhqLHgSYAhwTgMlMGf3VEJA3AfVF4f4WwdngGiNQQif+CMHkk4DJVwUaDt4HGhwISiIfhRwgmuIVCuIuEoYeEwHgikEXWx4pqyIkvd4An4HuCWHScSD2NqIu0qImVOITRWAKEaDKwiIvZeIkoAGU254usCIkiCANcuIu2hwKB5HZsJABcN44mUGXWOAIE4IEwAIfSd4tdeIQUSAi1yHy/6IgzIIyRiAJGiGN/SHWJd4+/mAKEeG/6GITIKIf2iI/o+JArMJHvGI9nCI382InfyIT0Zn5094wukI5eAnTmWIEo4JAPwAC7QIx094UnAGV8iI0huYkh6YguYgDcSJF36I95GI2GwHhfdoyYJnhbN30r8HJEMpGn2IdEiZMzkI7/3riTJDCTM6mTxacCXiQz5ucyxLg1GtmPAgCK2VdyYYkC7uBmJ1lEMWlS3bh+WgmOaCmH/lAfF6iLBWmUyueUTRmYCkmOauZ7Wkh3dUkCXMcRUrmQKICD+LCYZlmRX+mW00d3OXmZIGmXJfmLMPmRlVl7gtV/9dGSBXiWXgaCLYlpmZiRD1CWxScAtFmbtZmLRAmMECCLUyl4tmmbosmTPImaJQCK+HCMC/CbowaE5KiIJfCTWZmSqpmX5Cibo+mVKOAy9tCatsiZJhCPvSkIKCmdlpl5vDkCbGRmWFlln7mDnQmbliiSjWCR/zgNVXZofakIL2CQZwd19NZ/HweC/+SoCCiJle8pn+Q5jURpoAiARgNnoAhKlWA3Ai9nk3gZoa5nMqE4kH7JiKh4hP3XHcSJlRVKAuyJoQkqA1pXn/R5CdSRn4jQFPzZkgahlsdZf7y1j8EZgSP5mIYZmXiIlYQ4CFookJYZnSdQoiNAj+d3l+0nBnz0oByamyn6nOJ3CeyQnj8adMy5moV5oR4aAwI0Brg5h/7YkmWVnwYgBg6HovsoArSIDACKO8d4AGFAdjCne4Kwo2Dap3KpoPKAlSg4CPwAocI5iV1ajALqnTy5CL2Yn0VapfSpIwFAnEaqZnFJGpvpo1OZjyP5piwaqmLkB/kZjIB5i7vAcWpJp/+dSgLyp3xb2qRIij6ACpl6UZteVKjTeaCtsZlvKatZqQi9eKnUCZ8fGqjrsIy2SgImIwBhgIIW95ovcAnWyauHWqy6GXO8Wao3wJ+/8R7SeqPLWoR+dwnOmXybuYi0CqQLKgjW6YiGyqN32azPipGzKp+/GYBhl5/jGab0qY4YyYUJmQgCYa50qaKfWqb/+mSLx6024K0QsIru+RtKmQIm4wd05yeNea/SyK7yMJnUp4vx2qcDG6MbmbDR6A/DSqwROwh8KpTHiqOl16oQAHuKMHA1CQNWKaYo25O6SJAG2JbZWpQ7OXoEMXEUS7OnyHXpKnWLKq+SaqVVKZhUqav/R2qtRtoIbaqPEOiiQDeW7hoDKvmzhHBl8EeIymmbGmqi0opv9tqd9+qTftmSzEmQCFu0nIhnFiGusWoCLhMKMJl7Ecmx11m1Fxm2KQCvu+qmaJu2tLm2jAq1Qdes13iCHfqBpFmwfimKlzuYtXieKIAAJhinqMBxksurckulRzWUpoq3O4kPtci3LPuh/LiMoumMkfunHksCpLu742qX46e6jFlyosm138gxJmF+LbmyS8qXqkmQrypm5geT56qnsTm8/neGAYB1j7iGbbggU2a8PpubdruKrNutp8p2qtCLsouVvicPhLgAYed7Vwuq62q4I9CShjiJuaq099qV/ypgMsxrv276h3nat6OImZDXt9gacx1nfr/aTjkZDO9Rqc43doTAKgegggjAgl0qvgtrt2TokruYgXEEt34KdO0rgmmEhYNwZQSxwX7QwU+4jrlrh76bg17IADPswa9YfzUIR/Q2eu4gj5HXtAR8rZMrnq06hSNIAPnmwkH6vJ1bubv5tIeYqPSrCHKmfXQ4xD0bwp0bDEO5CCisru10jIsQqf3JCKZ4w1YstQzhxWvYb4ojM6OnnVf0woTrpyJQZQbBha/KCPhJxcKLwwwrCPX4cpE6d4owACu7eZLXfU5KwKnLEYRYxvoJrH68GWpMsGcIAPP3AJSZxIUbsyYgybGJ4HkkgKeJcLpq1wJsxMZorMROKwjlkI6jkAiSyMAQsHQuMHW/YaH/aMQiUAAZt32m+5JOF3I/J5LG7KXJV6QqlwJwN45bjAg0F41W1wLuYBElu4aymWohx2os0M3oc2/A3IzNvIfPPI+j/ABFis7uQMtUGc16is/WqwK7YCGXcG8M4ABI5wBmh3Ye0nAx0KDxaQTz1mr6JiEKPWwMZ8HuVtEWfdEYndEavdEc3dHPFgIAOw==`

both source format:

- `_srcImage = 'data:image/png;base64,IMG'`
- `const _buf = new Buffer(IMG, 'base64') 
   _srcImage = { data: _buf, format: 'png' }`

**Expected behavior**
I expect to display the image in the pdf, but don't work.
The file is fine, because if I use it in a html tag image I can display it.
Even if I put the base64 string in this site https://codebeautify.org/base64-to-image-converter I can display the image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome  87.0.4280.141
 - React-pdf version v1.6.12

**Comment by y0n3t4n1** [comment]
This worked for me, although not straightforward:
```
_srcImage = { uri: 'data:image/png;base64,IMG', method: 'GET', headers: [], body: '' }
```

**Comment by diegomura** [comment]
Thanks @y0n3t4n1 !
