### ISSUE TITLE
PDF renders in wrong orientation

### ISSUE THREAD

**Issue by peterzanetti** [diegomura/react-pdf#1092]
**Describe the bug**
PDF renders in the wrong orientation if the resolution meta data is incorrect.

**Expected behavior**
PDF renders in correct orientation based on paper size, as it does in desktop PDF applications.

I have a PDF that reports its dimensions when inspected as 792 x 1224. When rendered in react-pdf, it is displayed in portrait orientation which is wrong. The document also has a paper size of 17 inches x 11 inches.

Adobe Acrobat and Preview.app have no issues displaying in the correct orientation.

**Comment by diegomura** [comment]
Not sure I understood. Can you provide either a snippet so I can replicate it or more information?

**Comment by Suman-Jaiswal** [comment]
I have the same issue. The app undergoes infinitely loading mode by setting orientation = "landscape"

**Comment by AdelineDs** [comment]
Hello,

I have the same problem ...
