### ISSUE TITLE
cannot display Japanese language in the pdf

### ISSUE THREAD

**Issue by Razi321** [diegomura/react-pdf#1094]
i'm trying to display Japanese words in the pdf but i only get weird  characters . i found other people who have the issue  here but their solution didn’t work for me .
can you provide the steps to resolve this issue ? thanks

**Comment by daihuaye** [comment]
What were the solutions? The general solution is register a new Japanese font and apply the font family on the text. What about other non English such as Korean and Chinese? Do you have any issues?

**Comment by Tabraizahmed** [comment]
I am also facing this issue for the Chinese language. I am using the following method
`import font from "./font/NotoSerifSCMedium.ttf";`
` Font.register({
    family: "NotoSerifSCMedium",
    src:font
  });
`
then in Style.js

`tableCellName: { padding: "8px 5px", textAlign: "left", fontSize: 14, fontFamily: "NotoSerifSCMedium" },`

and then using it like 

` <View style={{...styles.tableColBB25, borderColor: "#BCBCBC"}}>`
            `<Text
              style={styles.tableCellName}
            >{'華龍關先生'}</Text>`
         ` </View>`

For reference please visit [this](https://github.com/diegomura/react-pdf/issues/409#issuecomment-577133593) and [this](https://github.com/diegomura/react-pdf/issues/680#issuecomment-527619387) comment, against same kind of issue.

**Comment by diegomura** [comment]
The solution is loading a Japanese font as @daihuaye said. Closing this as is duplicated #793

**Comment by anhcnt197vn** [comment]
I found this font can help you guys display the Japanese character correctly in pdf!
[Nasu-Regular.ttf.zip](https://github.com/diegomura/react-pdf/files/8905435/Nasu-Regular.ttf.zip)
