### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by gubbigubbi** [diegomura/react-pdf#1097]
Image files are not rendering.

**To Reproduce**
Here is my code:
```
{props.data
            ? props.data.map((item, index) => {
              return (
                <View key={index} style={styles.row}>
                  <View style={styles.image}>
                    <Image source={item.photo} />
                  </View>
                  <View style={styles.textContainer}>
                    <Text>{item.photo}</Text>
                    <Text>Quantity: {item.quantity}</Text>
                    <Text>Print type: {item.selectedPrintType}</Text>
                    <Text>Frame color: {item.selectedFrameOption}</Text>
                    {/* <Text>Fabric type: {item.selectedFabricOption}</Text> */}
                    <Text>Print size: {item.selectedSize}</Text>
                    {/* <Text>Frame type: { item.selectedFrameOption }</Text> */}
                    <Text>Orientation: {item.selectedFrameOrientation}</Text>
                    {item.addWhitePaperBoard && <Text className="font-italic">Printed on a white mat board</Text>}

                    {SHOW_PRICING && (
                      <Text className="total">${item.price} ex gst</Text>
                    )}
                  </View>
                </View>
              );
            })
            : ''}
```

The image does not render. I can see the url is correct.

I have also tried manually entering a url, for example:
https://theitteam.com.au/wp-content/uploads/2020/02/the-it-team-cool-graphic.png

**Expected behavior**
The images previously did render. I tried rolling back versions as well (to 1.6.7).

**Screenshots**
![pdf-render](https://user-images.githubusercontent.com/16090465/105436236-9772a200-5caa-11eb-9de7-44e472b7370f.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome/Firefox
 - React-pdf version: 1.6.7 / 1.6.12

**Comment by daihuaye** [comment]
@gubbigubbi The issue is that theitteam.com.au block other site download the image.

Here is the quick test in the react-pdf.org playground. It doesn't work due to the CORS policy.
![image](https://user-images.githubusercontent.com/764050/105760744-119f6280-5f07-11eb-8d4f-e87995374f52.png)

**Comment by gubbigubbi** [comment]
Thank you very much for that - should have known better as I saw that error in my console.
