### ISSUE TITLE
App crash when null changed to string

### ISSUE THREAD

**Issue by Krzyku** [diegomura/react-pdf#1098]
**Describe the bug**
The problem is when one parent element has multiple children. When the value of one child is changed from null to e.g. string, rendering explodes.
I'm not sure if the problem is in the react-pdf or yoga-layout

**Example**
Source code: https://codesandbox.io/s/react-pdf-bug-udiin
Demo: https://udiin.csb.app/

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS Catalina
 - Browser: chrome, safari, firefox
 - React-pdf version v1.6.12 NOTE: Works fine in 2.0.0-beta18

**Comment by diegomura** [comment]
Fixed in 2.0. Please upgrade! You should not change anything from your solution. Thanks!

<img width="858" alt="Screen Shot 2021-04-07 at 1 54 28 AM" src="https://user-images.githubusercontent.com/5600341/113812269-318fa580-9744-11eb-9113-135d8bf515c6.png">
