### ISSUE TITLE
Add watermark support

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#11]

**Comment by diegomura** [comment]
I don't think this should be a part of the core library anymore.
In the future, if someone needs this this feature he can use a Text with some transformation

**Comment by RodolfoSilva** [comment]
@diegomura thanks for this awesome library.
Do you have any example with watermark? I need add in all pages a watermark as background.

**Comment by tosifkhan01** [comment]
@RodolfoSilva have you found any workaround on this?

**Comment by tosifkhan01** [comment]
> @diegomura thanks for this awesome library.
> Do you have any example with watermark? I need add in all pages a watermark as background.

@diegomura have you found any workaround on this?
