### ISSUE TITLE
Merge with existing pdf possible?

### ISSUE THREAD

**Issue by mortmoe** [diegomura/react-pdf#1101]
I'm using react-pdf to create pdfs from a form. The users can add attachments, both images and other pdf's. Adding the images is no problem, but is there a way to merge existing pdfs into the document? (I have access to the attachments as blobs)

**Comment by rykon** [comment]
Were you able to resolve this?

**Comment by mortmoe** [comment]
Nope :-) I could probably make the pages into images and insert them but that's not really what I wanted. I ended up downloading PDF attachments to my form in a zip alongside the generated one. Works in my case as attachments can be any file type. (Office documents, PDF, images and weird map files 😄) Would be nice to have a way og merging 2 pdfs though...

**Comment by diegomura** [comment]
It's not possible to do it, and it's not in the roadmap to add it, mostly because of technical challenges involved with it. It was asked previously but unfortunately the answer is still the same. sorry 😞
