### ISSUE TITLE
make signature zones

### ISSUE THREAD

**Issue by jean-Box** [diegomura/react-pdf#1109]
Hello,
I want to make a pdf that will be signed by several people.
- person A generates the file with a 1st signature
- person B receives this PDF and must sign it
- and ditto for person C.

Can react-pdf do this job?
What solution can you advise me? Canvas? Other?
Thank's for your time
David

**Comment by ddcech** [comment]
I think this is outside the scope of this project. react-pdf only renders pdf documents. If you want all people to digitally sign, you can do that outside of react-pdf. 
One solution: You can create a webpage that takes a persons signature (as image upload). When a person uploads their signature, you can generates a completely new PDF file adding that signature, and then the next person is notified to sign, and generate the pdf a 3rd time and so on, until all signatures are provided.

**Comment by jean-Box** [comment]
Thank you for your answer, I will think about it

Thanks again

**Comment by arpitprod** [comment]
@jean-Box Please suggest me if you found anything, how can solve this issue
