### ISSUE TITLE
Showing PDF on mobile? (in lieu of official support)

### ISSUE THREAD

**Issue by acomito** [diegomura/react-pdf#1113]
As others have found, we don't have support for mobile yet (unless something changed). In particular PDFViewer doesn't work on iOS.

- https://github.com/diegomura/react-pdf/issues/962
- https://github.com/diegomura/react-pdf/issues/714

Has anyone found a good solution for this in the mean time?

Somebody had mentioned turning your PDF into a PNG, which I was working on but ran into a few hitches with PNG pages being upside down etc.

**Comment by skdavies** [comment]
I have a solution that's working pretty decently using this package to generate the PDF and [https://github.com/wojtekmaj/react-pdf](https://github.com/wojtekmaj/react-pdf) to display it. Here's a code snippet (spacing is a little messed up but whatever):
```
import { BlobProvider } from '@react-pdf/renderer';
import { Document, Page } from 'react-pdf/dist/umd/entry.webpack';

<BlobProvider document={<MyDocument/>}>
            {({ blob, url, loading }) => {
              return loading ? <InfiniteLoading isLoading/> : (
                <Document file={url}
                                    onLoadSuccess={(pdf) => this.handleLoadSuccess(pdf, blob)}
                                    renderMode="canvas">
                      <Page pageNumber={1}
                                 width={window.innerWidth}/>
                </Document>
              );
            }}
</BlobProvider>
```
Obviously, if you have more than one page, iterate through them all and render them. The number of pages is passed in the `pdf` object to `onLoadSuccess`.

I think you could also just `window.open` the `url` returned from the blob provider. It's not working inside my Cordova app, but seems to work when I run my app locally in the browser.

I actually haven't tested on Android yet but it's working on iOS. Good luck...

**Comment by acomito** [comment]
Thanks @skdavies

**Comment by acomito** [comment]
@skdavies where does this.handleLoadSuccess come from?

**Comment by skdavies** [comment]
That's just a function I defined to save the pdf data and blob data to state when it's done loading.

**Comment by sudonitin** [comment]
Thanks a lot, @skdavies !!!

Was struggling to resolve this issue on a tight deadline project. You're a true lifesaver 🙌🏻

**Comment by JessyZeroual** [comment]
thanks @skdavies

**Comment by agus4402** [comment]
I worked for me that way
**https://github.com/diegomura/react-pdf/issues/714#issuecomment-1962087670**
