### ISSUE TITLE
Unhandled Rejection (Error): Could not resolve font for undefined, fontWeight 400

### ISSUE THREAD

**Issue by Sakib8080** [diegomura/react-pdf#1116]
const font = require("../../src/fonts/SutonnyMJ.ttf").default

  Font.register({
    family: 'MyFont',
    src: font
  });

const styles = StyleSheet.create({
    page: {
        fontFamily: 'MyFont',
        fontSize: 11,
        paddingTop: 30,
        paddingLeft: 60,
        paddingRight: 60,
        paddingBottom:22,
        lineHeight: 1.5,
        flexDirection: 'column',
    },

This way I try to add font but it showing this "Unhandled Rejection (Error): Could not resolve font for undefined, fontWeight 400"
please any one help me?

**Comment by ze-gomes** [comment]
try 

```javascript
Font.register({
    family: 'MyFont',
    format: 'truetype',
    src: font
});
```

If it doesn't work it's possible that you're importing your font incorrectly or that it doesn't have a fontweight of 400

**Comment by joelybahh** [comment]
I'm getting the same issue. Tried using the src URL provided from google fonts, and also tried simply downloading the ttf family directly and referencing them locally, all of which result in this error. Even the example (As seen at this link: https://react-pdf.org/repl?example=font-register) Throws the error. 

Only when I try to set the fontFamily: 'Oswald' in my page style it throws the error. It registers fine presumably, just setting fontFamily to what I've tried to import throws the error. Is there another step missing from the documentation?

`Font.register({
        family: 'Oswald',
        src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
      });

    const styles = StyleSheet.create({
		page: {
			flexDirection: 'col',
			backgroundColor: 'white',
			width:"100%",
            padding: 0,
            fontFamily: 'Oswald'  // If i remove this line, or use a standard font such as, Times-Roman, everything works.
		}
});

**Comment by joelybahh** [comment]
for me, it was the fonts array import breaking it. 

` Font.register({family: 'Montserrat', src: 'https://fonts.gstatic.com/s/montserrat/v15/JTUSjIg1_i6t8kCHKm45xW4.ttf', fontStyle: 'normal', fontWeight: 400, format: 'truetype'});
     Font.register({family: 'Montserrat', src: 'https://fonts.gstatic.com/s/montserrat/v15/JTURjIg1_i6t8kCHKm45_ZpC7g4.ttf', fontStyle: 'normal', fontWeight: 500, format: 'truetype'});
     Font.register({family: 'Montserrat', src: 'https://fonts.gstatic.com/s/montserrat/v15/JTURjIg1_i6t8kCHKm45_bZF7g4.ttf', fontStyle: 'normal', fontWeight: 600, format: 'truetype'});
     Font.register({family: 'Montserrat', src: 'https://fonts.gstatic.com/s/montserrat/v15/JTURjIg1_i6t8kCHKm45_dJE7g4.ttf', fontStyle: 'normal', fontWeight: 700, format: 'truetype'});` Seperating font registration between 4 seperate register calls works fine.

**Comment by diegomura** [comment]
Thank you all for helping on this! Indeed, it was caused by an font register error
