### ISSUE TITLE
Memory error when Text/View content is larger than 1 page and wrap=false

### ISSUE THREAD

**Issue by 1Jesper1** [diegomura/react-pdf#1121]
> Uncaught (in promise) abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
>     at jsStackTrace (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:15134)
>     at stackTrace (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:15294)
>     at abort (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:359307)
>     at abortOnCannotGrowMemory (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:15823)
>     at enlargeMemory (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:16282)
>     at fC (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:348771)
>     at jS (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:315245)
>     at Te (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:104321)
>     at Ki (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:150178)
>     at Xi (https://react-pdf.org/_next/static/chunks/f057a831.98f5305ffb028c0f996e.js:1:150270)

Memory error when Text/View content is larger than 1 page and wrap=false

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/repl
2. Add wrap={false} to first  `<Text style={styles.text}>`
3. Paste amount of characters to first `<Text style={styles.text}>` untill the content won't fit 1 page.

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - https://react-pdf.org/repl

**Comment by jeffbum** [comment]
Just ran into this as well. I'm looping an array of data, and will never know the size of array. I'd like to be able to create page(s) with a header and footer and not wrap the view around the array.
