### ISSUE TITLE
This Library is Incompatible with React 17

### ISSUE THREAD

**Issue by osimuka** [diegomura/react-pdf#1123]
**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
```npm install @react-pdf/renderer```

**Expected behavior**
```
Found: react@17.0.1
node_modules/react
react@"^17.0.1" from the root project
Could not resolve dependency:
peer react@"^16.0.0" from @react-pdf/renderer@1.6.13
```

**Comment by vineethsagar** [comment]
@diegomura Hey, can you please make the library compatible with React 17

**Comment by princefishthrower** [comment]
Made a pull request to bump react version here: https://github.com/diegomura/react-pdf/pull/1157
You can meanwhile just fork this and issue npm update react, it works fine and then all tests pass, not sure where any maintainers are on this one, the original React 17 version issue was raised last October...

**Comment by diegomura** [comment]
Keeping just #1062 to track this
