### ISSUE TITLE
`PDFViewer` -> display two pages side-by-side, as in a book.

### ISSUE THREAD

**Issue by c4lliope** [diegomura/react-pdf#1129]
I was surprised when I went to use PDFReader that I couldn't display two pages side-by-side  in a webpage using `<PDFViewer/>`.

I imagined [the guide] would display some recipe for changing the viewer layout options.
[the guide]: https://react-pdf.org/components#pdfviewer

**Describe the solution you'd like**

Since I am building a rendering preview for a book I'd like to print and bind,
a side-by-side page view is necessary.

I am making do by bypassing `react-pdf`, but I will need a good preview plan
before I begin designing any page-based graphics.

Here's my desired page view; much obliged.

![Screen Shot 2021-02-24 at 2 39 33 PM](https://user-images.githubusercontent.com/30454698/109056196-21e56180-76ae-11eb-97d8-7d62f22f89e0.png)

**Comment by diegomura** [comment]
Hey. `PDFViewer` is just an iframe with the resulting PDF element. It's rendered by the browser as any PDF opened with it. So there's nothing I can do to achieve something like that. If you are interested in some more custom viewer,  you can try achieving something like what's build on the REPL: https://github.com/react-pdf/site/blob/master/src/components/Repl.js
