### ISSUE TITLE
Major memory leak when rendering PDFs that are missing embedded fonts

### ISSUE THREAD

**Issue by peterzanetti** [diegomura/react-pdf#1130]
**Describe the bug**
Memory usage continually increases while the component is mounted.

**To Reproduce**
Render an offending file. I have not yet been able to determine why one file is a problem, and not another, but it is 100% consistent within.

We are downloading and rendering PDFs with the Document and Page components. Certain PDF files, while rendered, cause a runaway memory issue where memory usage (JS heap ) keeps increasing until the component is unmounted, and then memory stops increasing but does not go back down.

I can provide example of bad vs. good pdf if anyone can please help us with this.

**Comment by peterzanetti** [comment]
Please if there is anyone here that can assist, I can give you a document to show that it is an issue with react-pdf. We have tried in our application and in a sample demo app using react-pdf and the issue remains. Certain PDFs cause massive memory leak any time render is called in React.

Please. Help!

**Comment by peterzanetti** [comment]
I am finding now that files with issues are ones that are missing embedded fonts. Does that help?

**Comment by peterzanetti** [comment]
Is there anyone here that can respond or address this concern that PDFs with missing embedded fonts (which seems to be incredibly common) cause massive memory leak when render is called in react-pdf?

**Comment by diegomura** [comment]
Just published a new version with a yoga build with way more memory. Please try it. Closing this until further notice :)
