### ISSUE TITLE
Misconfigured @react-pdf/unicode-properties

### ISSUE THREAD

**Issue by ECWireless** [diegomura/react-pdf#1131]
As described [here](https://github.com/snowpackjs/snowpack/discussions/2370#discussioncomment-400148), the @react-pdf/unicode-properties package is misconfigured. It's "module" field points to `dist/unicode-properties.es.js` but the actual file is `dist/unicode-properties.esm.js`. Is causing `yarn` builds to be halted.

Would be as simple as changing this [line](https://github.com/react-pdf/unicode-properties/blob/master/package.json#L6), but it looks like the repo is archived, so I couldn't make a PR.

**Comment by diegomura** [comment]
Should be fixed in 1.6.15! Let me know if persist
