### ISSUE TITLE
Square emojis are being cut off in the half

### ISSUE THREAD

**Issue by andvirga** [diegomura/react-pdf#1132]
**Describe the bug**
Square emojis are being cut off in the half. This seems to happens only with square type emojis (for example: 🔲  ⬜ or 🔳)

**To Reproduce**
Attached [react-pdf REPL](https://react-pdf/repl) example of this issue:

```javascript
const styles = StyleSheet.create({
  container: {
    height: 700,
    marginVertical: 70,
    marginHorizontal: "10%"
  },
  text: {
    fontSize: 100,
    textAlign: 'center'
  }
});

Font.registerEmojiSource({
  format: 'png',
  url: 'https://twemoji.maxcdn.com/2/72x72/',
});

const MyDocument = () => (
  <Document>
    <Page>
      <View style={styles.container}>
        <Text style={styles.text}>
          🔲 🔳 😀 💩 👻 🙈 ⬜ 🏟️
        </Text>
      </View>
    </Page>
  </Document>
);

ReactPDF.render(<MyDocument />);

```

**Expected behavior**
All squares emojis should be fully rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/12242771/109166461-7d215d80-775b-11eb-8315-3c7f503ed112.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04.5 LTS
 - Browser: Chrome 88.0.4324.96 (Build oficial) (64 bits) 
 - Node: v 12.19.0
 - React-pdf version: 1.6.13

Any help would be very appreciated!

**Comment by diegomura** [comment]
Related to this #1023. Will keep that as reference so there are no duplicated issues. Thanks for reporting this
