### ISSUE TITLE
Page breaks not working! 

### ISSUE THREAD

**Issue by saio23** [diegomura/react-pdf#1133]
`<Document>
<Page>
<View break/>
</Page>
</Document>`

When ever i tried using break in primitive types it didn't work and had to create new <Page/> all the time any possible causes to these problem or solutions?

**Comment by diegomura** [comment]
Fixed in the upcoming 2.0 version. You can test it here https://v2.react-pdf.org/repl and install it via the `2.0.0-beta.20` version. Will be officially published in a couple of days

**Comment by saio23** [comment]
Thank you will try it out!
