### ISSUE TITLE
boxSizing style missing on Styles interface

### ISSUE THREAD

**Issue by ebasic** [diegomura/react-pdf#1140]
**Is your feature request related to a problem? Please describe.**
Important when setting padding or borders on <View> element. A

**Describe the solution you'd like**
User should be able to set box-sizing on <View> element.

**Comment by kanapka94** [comment]
@ebasic why closed?

**Comment by maasha** [comment]
This bug I still there

<img width="1155" height="86" alt="Image" src="https://github.com/user-attachments/assets/9fe400d4-08c8-4e58-935e-20280e4a5192" />
