### ISSUE TITLE
React Pdf not working on iOS

### ISSUE THREAD

**Issue by RishavGoswami** [diegomura/react-pdf#1145]
I'm using React-pdf, which works fine on chrome, both on desktop and android devices but doesn't seem to work on iPhone ( both chrome and safari ) and mac safari. What is the solution for this?
```
import { Document, Page, pdfjs } from 'react-pdf/dist/esm/entry.webpack'

 <Document
    options={{
        cMapUrl: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`,
        cMapPacked: true,
    }}
    file={url}
    onLoadSuccess={onDocumentLoadSuccess}
>
    <Page pageNumber={pageNumber} />
</Document>

```
<img width="1264" alt="ITxLn" src="https://user-images.githubusercontent.com/36010407/110930867-a04d2f00-834f-11eb-92c0-8d4a45c16c20.png">

**Comment by corneliushka** [comment]
Don't know if it's related, but try to update your system, yesterday i had a bug that freezed the browser (Chrome/Firefox/Safari), when the popup to save file occured (Mac Os Big Sur 11.1). An update to 11.2 did the job.

**Comment by RishavGoswami** [comment]
Did you face the same error as above? I'm on Mac Os Mojave ( 10.14.6 ) but this also doesn't work on my iPhone which is on iOS 12 and I can't upgrade that.

**Comment by phongnt57** [comment]
Get same problem on ios and android chrome too. Update chrome make problem disapprear but we can not update on ios

**Comment by RishavGoswami** [comment]
> Get same problem on ios and android chrome too. Update chrome make problem disapprear but we can not update on ios

I got it fixed by downgrading react-pdf from the latest to version 4.2.0.

**Comment by diegomura** [comment]
This ticket belongs to https://github.com/wojtekmaj/react-pdf
