### ISSUE TITLE
When @react-pdf is introduced, a setInterval is added globally, and performance test is performed in chrome devtool, which leads to browser crash

### ISSUE THREAD

**Issue by iyuping** [diegomura/react-pdf#1147]
**Describe the bug**
When @react-pdf is introduced, a setInterval is added globally, and performance test is performed in chrome devtool, which leads to browser crash

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Enter `setInterval(() => {}, 100)` in REPL;
![image](https://user-images.githubusercontent.com/19379305/111033185-ecc96500-844a-11eb-906f-a8d83961e8b8.png)

2. Open chrome devtool
![image](https://user-images.githubusercontent.com/19379305/111033212-023e8f00-844b-11eb-887c-4d1b581deeed.png)

3. Click the record button
![image](https://user-images.githubusercontent.com/19379305/111033255-39ad3b80-844b-11eb-8c78-ba942780ea79.png)

4. Crash
![image](https://user-images.githubusercontent.com/19379305/111033267-4f226580-844b-11eb-9ed4-21c9eddf4095.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.3
 - Browser: Google Chrome  90.0.4430.19 beta (x86_64)
 - React-pdf: v1.6.13

**Comment by daihuaye** [comment]
I think it doesn't matter what code is entered, when pressing the recorded button from the Performance tab, the page crashes. I have the same issue with the library recently using the chromium browser. It is really bad experience for developers. Not sure whether the browser update causes the issue? Or the library update? Could you try to use older versions locally and test if it can repro?

**Comment by iyuping** [comment]
I tested versions 1.0.0 and 1.2.0, which also have this problem

**Comment by daihuaye** [comment]
If you remove the `setInterval(() => {}, 100)` code, will it work?

 If you have older version of Chromium browser - 79 or below, or download from here: https://www.slimjet.com/chrome/google-chrome-old-version.php, the Performance tab record is working for the React-PDF site.

![image](https://user-images.githubusercontent.com/764050/111228460-7ee38180-85a1-11eb-8f1d-3042194c8902.png)

**Comment by diegomura** [comment]
I do not understand this issue. Is it a bug with the REPL or react-pdf?

**Comment by iyuping** [comment]
> I do not understand this issue. Is it a bug with the REPL or react-pdf?

React-PDF

**Comment by diegomura** [comment]
How can I replicate it without the REPL then?

**Comment by iyuping** [comment]
> How can I replicate it without the REPL then?

After the upgrade of chrome（90.0.4430.51）, it can no longer be reproduced
