### ISSUE TITLE
Support for core-js3 & React 17!

### ISSUE THREAD

**Issue by ivaylopetrovdev** [diegomura/react-pdf#1148]
To Reproduce
Steps to reproduce the behavior including code snippet (if applies):
npm install @react-pdf/renderer
npm install core-js

Expected behavior

NOT to receive such error:
ERROR in ./node_modules/babel-runtime/core-js/promise.js
Module not found: Error: Can't resolve 'core-js/library/fn/promise' in 'project_path/node_modules/babel-runtime/core-js'
@ ./node_modules/babel-runtime/core-js/promise.js 1:30-67
@ ./node_modules/babel-runtime/helpers/asyncToGenerator.js
@ ./node_modules/page-wrapping/dist/page-wrapping.es.js
@ ./node_modules/@react-pdf/renderer/dist/react-pdf.browser.es.js
@ ./src/app/util/pdf-generator.worker.js

**Comment by ivaylopetrovdev** [comment]
@diegomura please address this with highest priority :)

**Comment by princefishthrower** [comment]
@ivaylopetrovdev Made a pull request to bump react version here: https://github.com/diegomura/react-pdf/pull/1157
You can meanwhile just fork this and issue `npm update react`, it works fine and then all tests pass, not sure where any maintainers are on this one, the original React 17 version issue was raised last October...

**Comment by ivaylopetrovdev** [comment]
> @ivaylopetrovdev Made a pull request to bump react version here: #1157
> You can meanwhile just fork this and issue `npm update react`, it works fine and then all tests pass, not sure where any maintainers are on this one, the original React 17 version issue was raised last October...

@princefishthrower lovely, can't wait to see your PR merged so we can start using this :) Appreciate your efforts!

**Comment by KolbySisk** [comment]
Any updates on this? I'd like to use this with a new CRA project, but I'm unable to until React 17 is supported.

**Comment by diegomura** [comment]
Keeping #1062. It's confusing to keep the conversation in both sorry
