### ISSUE TITLE
BackGround Color for linearGradient(360deg, #0063FF 0%, #46E9FF 100%)

### ISSUE THREAD

**Issue by a3596287** [diegomura/react-pdf#1149]
**Describe the bug**

BackGround Color for linearGradient is not working, is this a bug or new feature to be developed? 

**To Reproduce**

BackGround Color for linearGradient is not working, is this a bug or new feature to be developed?

**Comment by diegomura** [comment]
Hey. You mean `<LinearGradient />` on the upcoming 2.0 version? That component does not take a background color as a valid prop, and in the future, you will definitely need more context in order to reproduce the "bug" on my end. Closing this for the moment
