### ISSUE TITLE
Removing iframe background color

### ISSUE THREAD

**Issue by jesper-bylund** [diegomura/react-pdf#1158]
**Is your feature request related to a problem? Please describe.**
I can't find anything in the docs or issues, or examples, about this so I had to create an issue:
How do I change the background color on body inside the iframe? It's being set inline.

**Describe the solution you'd like**
Add either a parameter for this, or an example of how to change this.

**Describe alternatives you've considered**
I've tried to add background colors to every element, but I can't reach body.

**Comment by diegomura** [comment]
The `PDFViewer` just uses browser default view to load the document. Just did a quick search and apparently there's no way to change that natively on chrome at least. The ongoing 2.0 will support eventually different viewers but the `iframe` one is the only one supported so far. If you need something more custom you might find the site's REPL implementation helpful [here](https://github.com/react-pdf/site/blob/master/src/components/PDFViewer.js)

**Comment by jesper-bylund** [comment]
That explains a lot, thank you!

**Comment by Sahil1109** [comment]
Is it allowed to change in v2?
