### ISSUE TITLE
Zoom in and out

### ISSUE THREAD

**Issue by 1Jesper1** [diegomura/react-pdf#1159]
**Is your feature request related to a problem? Please describe.**
Zooming not available.

**Describe the solution you'd like**
We would like to zoom in and out in the pdf.

**Describe alternatives you've considered**
Use the scale method.

**Comment by diegomura** [comment]
Hi @1Jesper1 ! Not sure what you mean by zoom in and out. By using the `PDFViewer` you just load the default browser PDF viewer which in most cases has zooming features build in. If you download the doc or you are creating it serverside, any PDF reader will give you similar features. Can you expand a bit on what you meant?

**Comment by 1Jesper1** [comment]
Hello @diegomura For example at: [](https://projects.wojtekmaj.pl/react-pdf/) I would like to have an zoom in/zoom out button to look into the PDF.

**Comment by diegomura** [comment]
This is not that project. Please go to https://github.com/wojtekmaj/react-pdf
