### ISSUE TITLE
Output File's not unlocked when render promise is resolved

### ISSUE THREAD

**Issue by theobat** [diegomura/react-pdf#116]
express cannot stream the file even if awaiting for the async render to resolve:

```
import ReactPDF from '@react-pdf/node';
  ReactPDF.render(<MyDocument />, fileName);
```
Then in an express controller function like this:
```
(req, res) => {
  const fileName = path.resolve(__dirname, `../../../../tmp/${req.params.id}.pdf`)
  await ReactPDF.render(<MyDocument />, fileName);
  res.download(fileName) // Set disposition and send it.
}
```
It is streaming a corrupted file. But accessing directly to the file is working, it seems like the file's unlock is not dependent on the render promise. Using the callback produces the same result.

Context:
node 8.1.2
express: 4.14.0
react: 15.6.1

**Comment by diegomura** [comment]
The `render` method accepts a callback as a third parameter, which is called after the document was rendered. Can you try something like this? :

```
(req, res) => {
  const fileName = path.resolve(__dirname, `../../../../tmp/${req.params.id}.pdf`);
  ReactPDF.render(<MyDocument />, fileName, () => {
     res.download(fileName);
  });
}
```

**Comment by theobat** [comment]
@diegomura yeah I noticed this possibility in the code, however it produces the same result (the downloaded doc cannot be opened in any pdf viewer. Using a setTimeout with the callback you mentioned works though, that's why I think there's a race condition.

**Comment by mmmeff** [comment]
@theobat I know this is a late response in a closed issue, but I had a very similar issue and found the cause. If you're using livereload on the same server, it may be corrupting the PDF response.

I fixed it by ensuring my PDF generating code was at a route ending with ".pdf" and then adding that ignore definition to my livereload configuration.
