### ISSUE TITLE
how to dynamically change page size

### ISSUE THREAD

**Issue by yedajiang44** [diegomura/react-pdf#1160]
I need to gather all the content on a page, although I can set the page size, but I don't easily know in advance, so if there is any way, I can know and adjust the Page size.
or have other solutions？？？

**Comment by diegomura** [comment]
If you just set up the `width` of a page (without the `height`) you will get all your document rendered in a single page:

```
 <Page size={{ width: 600 }}>
```

**Comment by ntsim** [comment]
Noticed this is only applicable in the 2.0-beta (not in 1.6)

**Comment by sunkehappy** [comment]
Can anyone make the PDF width responsive, I mean to be equal width as it's parent so that when the page is big it's big. Fixed width looks not so nice on big screen.
