### ISSUE TITLE
Incorrect PDFDownloadLinkProps type in 2.0.0-beta.19

### ISSUE THREAD

**Issue by ntsim** [diegomura/react-pdf#1161]
**Describe the bug**

The type exported for `ReactPDF.PDFDownloadLinkProps` in `@react-pdf/renderer/index.d.ts` currently exports:

```typescript
interface PDFDownloadLinkProps {
  children?:
     | React.ReactNode
     | (params: BlobProviderParams) => React.ReactNode;
}
```

However, when compiled, TypeScript will throw the compilation error:

```
node_modules/@react-pdf/renderer/index.d.ts:403:10 - error TS1385: Function type notation must be parenthesized when used in a union type.
```

This can be solved simply by wrapping the `children` function type with parenthesis:

```typescript
interface PDFDownloadLinkProps {
  children?:
     | React.ReactNode
     | ((params: BlobProviderParams) => React.ReactNode);
}
```

**To Reproduce**

1. Create a project using TypeScript v4+
2. Install `@react-pdf/renderer` @ 2.0.0-beta.19
3. Import ReactPDF components as per usual.
4. Run `tsc`.
5. The described compliation error should be thrown.

**Expected behavior**

There should be no compilation error.

**Comment by diegomura** [comment]
Thanks @ntsim ! Also for testing 2.0. I already fixed this on the v2 branch. I'll deploy a new version asap.
