### ISSUE TITLE
Android chrome website not loading with an error Uncaught RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by djaffer** [diegomura/react-pdf#1167]
The issue seems chrome-specific on android. I tried multiple different devices same issue. Had to revert back to version "1.6.13". This was a nightmare of the bug to deal with causing major breakage.

Path: static/node_modules/@react-pdf/yoga/src/build/Release/nbind.js

![image](https://user-images.githubusercontent.com/5740725/113501985-d31db980-94ee-11eb-9b7b-8cb079af3b0d.png)

![chrome-android](https://user-images.githubusercontent.com/5740725/113502030-18da8200-94ef-11eb-8bec-a6e23078f1ee.jpg)

**Comment by nguyenhaduchieu** [comment]
The same issue, android and chrome windows.

**Comment by khmm12** [comment]
The same issue on AWS Lambda.

**Comment by diegomura** [comment]
Oh 😞  Any clue about what's the limit on android chrome? Or is there any way of programatically find out the limit so we allocate valid memory based on the device?

**Comment by khmm12** [comment]
Isn't possible to ship yoga built with [`ALLOW_MEMORY_GROWTH=1`](https://emscripten.org/docs/optimizing/Optimizing-Code.html#memory-growth)?

**Comment by khmm12** [comment]
There is a bit hacky way to detect and initialize yoga with pre-measured memory limit.

```js
function getTotalMemory() {
  const configuredTotalMemory = /* e.g. from process.env */
  if (configuredTotalMemory) return roundBy2(configuredTotalMemory)

  if (isBrowser) {
    const totalMemory = getBrowserTotalMemory()
    if (totalMemory) return roundBy2(totalMemory)
  } else if (node) {
    const totalMemory = getNodeTotalMemory()
    if (totalMemory) return roundBy2(totalMemory)
  }

  return DEFAULT_TOTAL_MEMORY
}

function getBrowserTotalMemory() {
  // Chrome
  // https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory
  if (typeof window.performance !== 'undefined' &&
    typeof window.performance.memory !== 'undefined' &&
    typeof window.performance.memory.jsHeapSizeLimit === 'number') {
    return window.performance.memory.jsHeapSizeLimit
  }
}


var totalMemory = getTotalMemory()

nbind({ TOTAL_MEMORY: totalMemory }, function (err, result) {
  if (ran) {
    return;
  }

  ran = true;

  if (err) {
    throw err;
  }

  ret = result;
});
```

**Comment by diegomura** [comment]
Shipping yoga with ALLOW_MEMORY_GROWTH=1 it's definitely the best fix, but I tried once and couldn't achieve it. I'm not super familiarized with the yoga building process and not even who nbind works. That's why I'm just importing the npm package as it is and changing just those parts of the code.

Something like you shared would be possible also! At least we can reuse the same stuff we already have. How `getNodeTotalMemory` is implemented?

**Comment by khmm12** [comment]
> Something like you shared would be possible also! At least we can reuse the same stuff we already have. How getNodeTotalMemory is implemented?

Just via NodeJS API https://nodejs.org/api/os.html#os_os_totalmem

> Also, what does roundBy2 does exactly?

As far I understood emscripten buffer size should power of 2. 67108864 bytes instead of 65000000.

**Comment by drummerpva** [comment]
I have a similar error, using v 1.6.16 or 2.0.0, return same error in self library of this issue:
I tried the modifications of pull request, but no success. It's causing major breakage also, but not in all browser.

![error-stack](https://user-images.githubusercontent.com/43733472/113942766-be377380-97d7-11eb-981b-ec86683b3f1f.png)

![error_code](https://user-images.githubusercontent.com/43733472/113942944-19696600-97d8-11eb-915c-9053e5f7678f.png)

**Comment by diegomura** [comment]
I'll release a new version today with a lower heap size (by bigger than the 128mb that we had before), at first, not with this logic. Might be 256mb (which is still the double than before) and we can keep increasing it in the future if people still has memory issues

**Comment by diegomura** [comment]
Latest version already includes yoga with less memory. Is this issue persis?

**Comment by capsulejj** [comment]
> Latest version already includes yoga with less memory. Does this issue persist?

The latest 2.0.3 works. Thanks.

**Comment by diegomura** [comment]
Thanks!! Let's keep it in 256mb. Hopefully it will be enough for everyone. We can increase it a bit more in the future and test Android devices again.

**Comment by ihmpavel** [comment]
Hi everyone, I am experiencing same issue `@react-pdf/renderer` in the latest version `2.0.20` on the latest Chrome, Android phone. Windows PC is fine.

![image](https://user-images.githubusercontent.com/42217494/140109557-201e998c-0b37-497c-8885-768ba8839f59.png)
