### ISSUE TITLE
[ReactPdf v2] Fonts are loaded multiple times 

### ISSUE THREAD

**Issue by duyank** [diegomura/react-pdf#1168]
**To Reproduce**
When I use, `fontFamily` for every text, fonts are loaded multiple times (even though they have the same font)

**Expected behavior**
If fonts are the same. It should be loaded one time to reduce loading time

**Screenshots**
Pdf Preview
![image](https://user-images.githubusercontent.com/19285404/113511053-12e4af80-9588-11eb-8d48-2344cd69f06c.png)
Fonts register
![image](https://user-images.githubusercontent.com/19285404/113510942-77533f00-9587-11eb-8405-6e5254d15110.png)
Fonts are loaded
![image](https://user-images.githubusercontent.com/19285404/113510973-9782fe00-9587-11eb-8ee5-d0e300969584.png)

**Comment by diegomura** [comment]
Thanks! I'll take a look ASAP

**Comment by diegomura** [comment]
Fixed in https://github.com/diegomura/react-pdf/pull/617/commits/78c0d5fd90b972e1ed80708d73f9359f546b8d16

**Comment by duyank** [comment]
the first time, when I go to the page (font hasn't loaded) then fonts still load multi times

This commit just fix when the font is loaded one time
