### ISSUE TITLE
v2: @react-pdf/renderer .d.ts syntax error

### ISSUE THREAD

**Issue by benmerckx** [diegomura/react-pdf#1170]
There's a comma missing after this line (https://github.com/diegomura/react-pdf/commit/55f767bc6c8355b4756ad68c5a4ff30450c3e8d0):
https://github.com/diegomura/react-pdf/blob/11410e7a99ddd00642421e91bcc830877d7430c1/packages/renderer/index.d.ts#L7

Resulting in Typescript complaining:
````
node_modules/@react-pdf/renderer/index.d.ts:8:5 - error TS1005: ',' expected.
8     Orientation,
````

**Comment by diegomura** [comment]
Fixed https://github.com/diegomura/react-pdf/pull/617/commits/9b7083e6ce5b4567ea96772a511e9d714cabfa62 ! Thanks
