### ISSUE TITLE
Range Error - Start offset undefined is outside the bounds of the buffer

### ISSUE THREAD

**Issue by navied** [diegomura/react-pdf#1177]
**Describe the bug**

Started to see users have this bug recently once we upgraded from beta.18 to anything higher,  although reverting back to beta.18 doesn't seem to have solved it.

![image](https://user-images.githubusercontent.com/1896993/113901256-adb5d780-979c-11eb-9a05-114822ebb3ac.png)

**To Reproduce**

I have not been able to reproduce this personally, but have had it happen to several different users. 

**Expected behavior**

Not to crash 

**Desktop (please complete the following information):**
 - Windows 7 and Windows 10
 - Chrome 89
 - v2.0

**Comment by diegomura** [comment]
Related to #1167. It's caused by the new yoga prebuilt. I'll keep that one as reference if thats ok. Thanks!
