### ISSUE TITLE
Page's paddingBottom is ignored

### ISSUE THREAD

**Issue by nicolasschabram** [diegomura/react-pdf#1189]
Thanks and congrats for releasing v2! It seems to be fixing quite a few issues I've had with v1 :) There's just one thing that's causing me some trouble after updating:

**Describe the bug**

I'm setting different values for `paddingTop` and `paddingBottom` on `<Page>`. For some reason, the `paddingBottom` seems to be ignored.

**To Reproduce**

[Here's an example where you can observe the behavior.](https://react-pdf.org/repl?code=3187b0760ce02e0040a200f021816c00e01b0298c0bc3002804a3c03e420281801e004446005714b30a52a98bea005240732c9cb9768013db2e00de538488090689001365012cc3f002a20d002e1800980033180343003d259801dc4002700d610612575811a2cc0a1665725c8a2aea9a004220505020280600acc656366afc608efe3000b4e48c101afc46a6301ad0582a302000663009813000bef575ca5800468cfc721c2222d45a9eec755c0032e928c56810cc30ca20188e3079b0a8585016a090abab8c0e8b2a6a93c0f93058186a500e161019eaa8306960cc62276a0e2820ca307ee80b1a006e6a65230d830462c0304856ba44eb059bcc1c3814008c0483719c008e8c311dcb00e241ad1637351dcfe73461a0a08c24000e8600041581fd7120138803ccb601302038d8000ad72d119a305970f4bb24ea8847b450b480329f960c033941514e7727df88c56ae3f808b0058d284d44aa9c6a244aaf6605f2e44ed01828c11e30394dc6a2dd92cdc2c282d21d582764da66ec5b9d3dab75b81ae0a9d9edd48763a9dce974267d6ee30793c5e6f0f97cfd685f9800140905826010a8422613339b4291a95452031589c5e209d714f13c6a48c3932934fa63399acf152139b91e4c1f9d01170aabf0ac38aca3029730e50a9812bceaaf54c135da872eb58069675d8d485379b51dcab6523c76df7fa5db38587a56defb58c268fa0cbebde1cd947dd7d8e34d04e6549336c660edee700332c15e7793e6f8f35d9fe405815804b32da15589f0ad6b144d1351316c5c65c5f12b889124c90a4a95a41918099070592c0d94ac472e5c749d05204456ac1105d2536857181e51c2370b4d5080352d4753d48f234be33ccd7c52f241af1b5e7581ef4fd033e383658bd5a4b8218605a1183515c240c13f418d384e6995e350761c0830d0600002d586501107043372fe46030340c17c470265955b5ae181de6c1a0350700d9ae4c5c8db230628306ed5d3e2702c1181812a5cbf86256047832d452a11cd4338f24b2072624e2638751c502bd2b272a70a9d4114523002cbc9c64c4d41815a084c075160340f179d587047b7c5a6000bc16df2d2969b05eb960e918173ccd70dd1c0fc7cb0aa404352a217cb2aeaad41f43f67574f85f4d0c0944a7c28d71371630b28e1021356d28b4c60940506797ad69dcfb22c842be0d08e22c30f049074870fdba2e45eb46d9b7c418b24a0250df6327a1e800555816c0b286d60cd0fba28d0a9a657ad402c41b5c349a0071184f93c5c48e452a0351c0504ca94140071bc77572238d010de672cf99662cb4a4b06c88f32d013810095d7188109645ee4adf3322cb71accececdca9d5f39cdc38a3003caf27cbf36d80a8290b0ef0a4379ca298b34f8ab5cd9f58b1c2f4b32dc272bca0a8e98afb902f3a2aa38aedab6cfab9926a9816ad4b6a051643e7e720d48faaa706e1b46f1a6049a9069a416ec2979bc625a569994e4a736cd476a3651c3a23fe04e92a63f2b2ef268c9804c800e4ee338f71cc7e5d8d3c5871d44d25688da6ed402ac68a8297e76d8d95bfb8d4772aae29d05c5d46466263901181316cc9105aa9cc0473236038fdebcc207eadc77f84ed2eeaca1e9fcc31fb6b8be1b63bd2025f5e332a0a2ed8ee3a620620cd4183086100a19f32b46858b023246b09b2aa33ac84592a9116cd8dbb2e37c4b48499d87262717ab8c72828169a9b06628099aed6826cc39bab6e6434551f30167dd85a383168b02581c6962016591b5ea10115b2c46c071d5a6b50040c3e2eb08c581f590f3a8d412c3f40408307a0e8be0821ba0d04b0f40d38cd0e044000370500a000094ca2f81e0b400018b523d42d01c0106a0881502601c0961482d88a04000)

**Expected behavior**

I'd expect the text on the page to be offset from the top by 200px and from the bottom by 50px. In fact, that's what the colored shapes suggest when enabling the `debug` prop. Instead though, the text doesn't fill all the available space but wraps to the next page "earlier" than needed. It looks to me like `paddingTop: 200` is applied to the bottom of the page as well.

**Screenshots**

![image](https://user-images.githubusercontent.com/1027642/114172533-11273d00-9936-11eb-8ceb-d94fffc93b60.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - React-pdf version: 2.0.2

**Comment by diegomura** [comment]
The padding is correctly configured. It might be something about text wrap between pages. I'll take a look asap

**Comment by diegomura** [comment]
Good catch! Just fixed it. Page wrapping is so complex 😓  I'll publish a new version today

**Comment by nicolasschabram** [comment]
That works – thanks so much for taking care of it, @diegomura!
