### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by cesar-cardinale** [diegomura/react-pdf#1197]
**Describe the bug**
I just install @react-pdf/renderer, zlib was missing, I installed it too.
Now the file /zlib_bindings is missing.

**Logs**
```
$ /Users/_/_/node_modules/.bin/encore dev --watch
Running webpack ...

 ERROR  Failed to compile with 1 errors                                                        19:33:28

Module build failed: Module not found:
../node_modules/zlib/lib/zlib.js contains a reference to the file ./zlib_bindings.
This file can not be found, please check it for typos or update it if the file got moved.
```

**Desktop:**
 - OS: MacOS Big Sur 11.0.1
 - Browser Safari 14.0.1
 - React-pdf version ("@react-pdf/renderer": "^2.0.2")

Can someone help me to get this file ?
Thank you !

**Comment by diegomura** [comment]
I don't get it. pdfkit uses Node built in `zlib` bindings. What Node version are you using?

**Comment by cesar-cardinale** [comment]
My Node version is v15.14.0.

**Comment by diegomura** [comment]
You don't need to install `zlib`. Try uninstalling it. Can you check your package-lock.json or yarn.locl file and share who's importing `zlib` ?

**Comment by cesar-cardinale** [comment]
Now without zlib installed, I'm getting those errors : 
```
Module build failed: Module not found:
../node_modules/@react-pdf/pdfkit/dist/pdfkit.browser.es.js contains a reference to the file zlib.
This file can not be found, please check it for typos or update it if the file got moved.

../node_modules/@react-pdf/png-js/dist/png-js.browser.es.js contains a reference to the file zlib.
This file can not be found, please check it for typos or update it if the file got moved.
```

I searched for `zlib` in the yarn.lock file and `zlib` is not mentioned once.

**Comment by cesar-cardinale** [comment]
I need your module, but I can't use it, help me please !

**Comment by eatlambs** [comment]
i'm having the same problem. it's prompting me for the following packages
- stream
- util
- zlib

once i installed all these packages i got  ./zlib_bindings, file not found error / can't resolve.

node v15.0.1
@react-pdf/renderer v2.0.5
webpack v5.35.0

**Comment by diegomura** [comment]
Keeping https://github.com/diegomura/react-pdf/issues/1029 for Webpack 5 support

**Comment by Vennisha-Naidoo** [comment]
Hi. Was this issue solved?

**Comment by Vennisha-Naidoo** [comment]
> I need your module, but I can't use it, help me please !

Hi. Was this issue solved?
