### ISSUE TITLE
How can we hide the thumbnail in the pdfview as default ? 

### ISSUE THREAD

**Issue by ngvtuan** [diegomura/react-pdf#1200]
**Is your feature request related to a problem? Please describe.**
When we open the pdf `<PDFViewer style={pdfStyles.viewer}>` is there any attribute to set the thumbnail is hide as default ?

<img width="357" alt="Screen Shot 2021-04-10 at 12 54 08 PM" src="https://user-images.githubusercontent.com/10944387/114259985-38e0d880-99fc-11eb-8b5c-2d29e509822b.png">

**Comment by diegomura** [comment]
The PDFViewer uses the browser native PDF interface. The same one the browser shows if you open any PDF document using your browser. That's not something that depends on this library and as far as I know there's no way of altering that UI that much. If you need a custom visualization layer for your PDF I recommend you looking at https://projects.wojtekmaj.pl/react-pdf/ or check how the REPL is build at http://gitHub.com/react-pdf/site
