### ISSUE TITLE
Margin auto support

### ISSUE THREAD

**Issue by AlanCorralejo** [diegomura/react-pdf#1212]
**Is your feature request related to a problem? Please describe.**
I want to push a element to the bottom of the page

**Describe the solution you'd like**
Margin top auto

**Comment by gabrielvincent** [comment]
Wouldn't `position: 'absolute', bottom: 0` achieve what you want?

**Comment by diegomura** [comment]
@gabrielvincent is right! Should be done like that

**Comment by AlanCorralejo** [comment]
I can't use 'absolute' because the container must continue with the flow of the content and with 'absolute' position it is placed over other content
