### ISSUE TITLE
Requires babel-polyfill when bundled

### ISSUE THREAD

**Issue by ferdinandsalis** [diegomura/react-pdf#122]
When running my bundled app I get the following error: `ReferenceError: regeneratorRuntime is not defined`.

Including the `babel-polyfill` in my build solves the issue. I guess this is not the expected behaviour?

**Comment by CentaurWarchief** [comment]
You need to incude babel-polyfill @ferdinandsalis. It's for async/await support

**Comment by ferdinandsalis** [comment]
@CentaurWarchief yes, however I am running node v8.1.4 which as async support so I wouldn’t need to include the regenerator runtime.

**Comment by CentaurWarchief** [comment]
Yeah, that's the issue I've opened recently here: #120. Unfortunately, we have this dependency. But I wish to PR this repository soon proposing the changes so we will only need to transform JSX.

**Comment by ferdinandsalis** [comment]
I guess I will close this in favor of #120 then. Thanks.

**Comment by VrajSolanki** [comment]
@ferdinandsalis hey, I am using react pdf and I am not sure how to add babel-polyfill in the dist step. Can you guide? 
my dist command looks like: `babel src --out-dir dist --presets es2015,react,babel-polyfill && node dist && node dist/index.js`
