### ISSUE TITLE
Segmentation Fault when profiling in Chrome

### ISSUE THREAD

**Issue by ldgrp** [diegomura/react-pdf#1223]
**Describe the bug**
Attempting to profile a page that renders a `Document` results in a segmentation fault. 

![image](https://user-images.githubusercontent.com/12184705/115101187-66da9580-9f85-11eb-85df-edf3fa9fb77b.png)

**To Reproduce**
Using Google Chrome 89.0.4389.114 and a modified `App.js`  file from `create-react-app`:

```js
import { Document, Page, PDFViewer } from '@react-pdf/renderer'

const App = () => {
  return (
    <div className="App">
      <PDFViewer>
        <MyDoc/>
      </PDFViewer>
    </div>
  );
}

const MyDoc = () => {
  return (
  <Document>
    <Page>
    </Page>
  </Document>
  )
}

export default App;
```

Attempting to profile this page with Inspect > Performance > Record results in a segmentation fault.

The same behaviour occurs when swapping out `PDFViewer` for `PDFDownloadLink`

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Google Chrome 89.0.4389.114
 - @react-pdf/renderer: 2.0.4

**Comment by daihuaye** [comment]
This is fixed with in Chrome 90. Please update the Chrome browser and try it again.

**Comment by ldgrp** [comment]
Updated to Google Chrome 90.0.4430.72. This is no longer an issue.

Thanks!
