### ISSUE TITLE
TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by ferdinandsalis** [diegomura/react-pdf#123]
`TypeError: Cannot read property 'register' of undefined`

This seems to be an issue with the latest release. Inspecting the index file in the `lib` folder it does not contain a reference to the Font module. However the `src` folder does.

To reproduce,
```
import { Font } from '@react-pdf/core';

Font.register(`${__dirname}/fonts/whitney-book.ttf`, { family: 'Whitney' });
```

**Comment by diegomura** [comment]
You're right. There is something very odd happening here. There are bunch of files that were erased in old versions of the library, but they are still going to the `lib` builded folder, such as `Catalog` and `GraphicState`:

<img width="410" alt="screen shot 2017-07-16 at 1 00 16 pm" src="https://user-images.githubusercontent.com/5600341/28249154-d59025dc-6a26-11e7-8acc-29bb96490d46.png">

Trying to figure out whats going on...

**Comment by diegomura** [comment]
I think it's fixed. @ferdinandsalis I released the v0.4.1. Can you test again?

**Comment by ferdinandsalis** [comment]
Tried to test it. When installing the new version of `react-pdf/core` I get this wanring — `npm WARN react-dom@16.0.0-alpha.4 requires a peer of react@^16.0.0-alpha.4 but none was installed.`. When running the app: `Error: Cannot find module 'react/lib/checkPropTypes'`.

**Comment by ferdinandsalis** [comment]
@diegomura I can confirm using the Font module works. Also installing the latest react alpha fixed the missing module error.

**Comment by diegomura** [comment]
Awesome. Thanks!
