### ISSUE TITLE
Nested flex containers throws error

### ISSUE THREAD

**Issue by tomaszzmudzinski** [diegomura/react-pdf#1231]
**Describe the bug**
When we need to have nested flex container error is thrown.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://codesandbox.io/s/elated-buck-m3crj?file=/src/App.js
2. Click the button
3. Error is thrown

**Expected behavior**
It should be able to nest multiple flex containers

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - React-pdf version: 2.0.4

**Comment by mdarens** [comment]
There appear to be 2 problems with this example:

1. The Roboto font is not being registered. When  `fontFamily: "Roboto"` is removed from the Page's style prop, the remaining error is caued by
2. The left and right Views in the nested flexContainer have primitive values as children. Once "123" and "234" are wrapped in Text components, there are no uncaught exceptions on clicking the generate PDF button, and you can see the blob in the console.

**Comment by tomaszzmudzinski** [comment]
My stupid mistake, sorry for that. And thanks for fast help ❤️
