### ISSUE TITLE
PDFViewer does not show characters special

### ISSUE THREAD

**Issue by tuanhai2712** [diegomura/react-pdf#1233]
I'm vietnamese and I want to show vietnamese in PDFViewer, I used font register with Roboto-Regular font but maybe it's does not work
Here is my code: 
![1](https://user-images.githubusercontent.com/35209688/115334549-ce7f2380-a1c5-11eb-9beb-3bc45f66d88b.PNG)
And this is result:
![2](https://user-images.githubusercontent.com/35209688/115334562-d4750480-a1c5-11eb-99e1-ce1e566f065e.PNG)

**Comment by daihuaye** [comment]
Looking at the example, it looks like Vietnamese characters. To make it render properly, it needs to import a font to support those characters. In fact, you can go to "C:\Windows\Fonts" folder to find the one works for your language and load it in your application.

**Comment by diegomura** [comment]
Thanks @daihuaye !! Indeed, that's the fix
