### ISSUE TITLE
LinearGradient doesn't render properly

### ISSUE THREAD

**Issue by maxcena** [diegomura/react-pdf#1237]
When using linear gradient for SVGs components (circle, rectangle...), it renders as fully black (and not the specified gradient color)

To reproduce, it can be done by using an existing example: https://react-pdf.org/repl?example=lineargradient

![image](https://user-images.githubusercontent.com/82497786/115433770-335b6d80-a208-11eb-9edf-213b69e1c358.png)

 - OS: MacOS
 - Browser:  Chrome 89.0.4389 
 - React-pdf version: 2.0.5

**Comment by diegomura** [comment]
That's just on the REPL. Unfortunately PDF.js which is what's being used there does not render the gradient correctly, not sure why. Try downloading that very same file and you will see it working. I should probably write this somewhere

**Comment by maxcena** [comment]
Thanks Diego.  It works indeed when linear gradient is applied to the fill parameter. However when I try to apply it to the stroke parameter, it remains black.

`<Svg viewBox="0 0 10 20" width="170">
      <Defs>
        <LinearGradient id="myLinearGradient">
          <Stop offset="5%" stopColor="gold" />
          <Stop offset="95%" stopColor="red" />
        </LinearGradient>
      </Defs>

      <Circle cx="5" cy="5" r="4"
        fill="white"
        fillOpacity={0}
        stroke="url('#myLinearGradient')"
        strokeWidth={2} />

    </Svg>`

![image](https://user-images.githubusercontent.com/82497786/115462163-978f2900-a22a-11eb-8ebf-5ff305fe5864.png)

**Comment by diegomura** [comment]
Please open a new issue with that and label it as `new feature`!
