### ISSUE TITLE
Webpack update V4 -> V5

### ISSUE THREAD

**Issue by Mario8419** [diegomura/react-pdf#1243]
I run into a bunch of errors after updating webpack v4 to v5

Can't resolve 'zlib' .....node_modules/@react-pdf/pdfkit/lib'
Can't resolve 'stream' .....node_modules/blob-stream

ERROR in ./node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.es.js
ERROR in ./node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.es.js
ERROR in ./node_modules/@react-pdf/png-js/dist/png-js.browser.es.js
ERROR in ./node_modules/blob-stream/index.js
ERROR in ./node_modules/restructure/src/EncodeStream.js

 - OS:  MacOS
 - Browser: chrome, safari]
 - React-pdf version: 2.0.5

"@react-pdf/renderer": "^2.0.5",
"gatsby": "^3.3.1",
"react": "^17.0.2",

**Comment by diegomura** [comment]
Check https://github.com/diegomura/react-pdf/issues/1029#issuecomment-740607786

**Comment by Mario8419** [comment]
unfortunately, this solution is not working for me...

**Comment by diegomura** [comment]
Keeping https://github.com/diegomura/react-pdf/issues/1197 for Webpack 5 support
