### ISSUE TITLE
Transformations not applied to Rect children of G element

### ISSUE THREAD

**Issue by OliverLeighC** [diegomura/react-pdf#1251]
**Describe the bug**

The `transform` attributes on `G` components are not being applied to it's children, in this case `Rect` children. 

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

Here is an example on the repl

[EXAMPLE](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774806500373e18349843490927702800311e46241121002e18002200090c11028c2824601e36801a2ad63ca4002f0c56b68046002678943698555552d0a570ec368036000603b6d2cb243e73285dc3e3d282a40c60802110145d83980f9b981b93ca5cea001c44a1e1812878501e2c526b1241806c6f3681d64733f87840f16898484bb5469528505b0f1208e102d918bb42712202208460f00056002701d860c8393288b6741d2f02ca204106623c2c4e6c33980a85f4b98c02568ffbe3a800250c0c441a09822200cc00161d6c819f28f0e2da0b265cc0d46cd16c766d7655b38670b95d4d071d43b28ce11089760062002093268fe9f0f83d654248000d6e236afb1c09c4f87a0dc98c01d490db732e3c318ac498738a8c8032854155ab15944462d9186cacc04d0c8b5d635214cedbedf5a765d767af77d6bd3eb8e0783a1e4e46637ec4d27eb29e8c603359c2eb6f3c06c72e3cc5d2a6501ee00242650a7c00665780277264e80c662b1d8040037190c8356aac9fc7c24340ec78090711cf54685a1800072001e4206087811094603860e0205b18056980cb8a078820668320c949560e43e1a00840659140460320803210020a82940c80a398b50c8004d001f5b4001a400353d84000038d31000a7900055250b54619880034991e1fd7f564280a047180b215407c9f501200304c19070180f26d2303c92c3e988a89301fc38450545697f4d13125094384f86d031568b5064e0bb3ac472c03e05e052404615a3d83cd29ec9f2f80e8c9299aa282dcd0b285513c981fa280c41b34a1c2a0099a6568161d592824f4281fd111ce30190e00584c16c58332ea8ea0689a643c0c83a0e5312e4a78041c232432cd0b29ca665941642a52e2b4af2b2aeaaec3ab34460785b03f301fca8102d68755643824be0841e454bd29816cce106a9986b9878b1a16a5ae15691631ab2c6b0096aa8f6bb6e4b307d1face1aee5aeed1beaf18cebba0ad293e92acabe02a902002b041a02411c210e693a1a8039a903b4241980816225502e243ab5992ec7f861b8eca17eb8438bb1fa214ee84a7ec5b96a8b6c18b5838b65239929db284b1ac3b1becf5aa21bfeabb99b8556f5a60058b6cd1c1c9aa1e9b5859ac6d00443ea40be1fc64679e4b310100039261e44168eb0b28b0890701909e1e4080401107a8c051e1681dca46b1b1400a82980b5397383111c2815a00f283679d50ec685721e8780aaa55daad5c7735e03b58c175f7a54b52c8155a2280b81a06a37c581b16c3c0a844150740b062cd4a00)

And a gist with the code and the plain svg for reference (you can see how the bars are horizontal in the svg, but the component renders them diagonal because the transform property on G isn't being applied to the rectangles)

[GIST EXAMPLE](https://gist.github.com/OliverLeighC/b4a5b02889b15eef75dedae8e91f5be9)

**Expected behavior**

I expect the transformation attribute `transform="translate(590,509) rotate(90) scale(-1,1) scale(1 1)"` to be applied to the children of the `<G />` component, so that the bars render horizontally. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]
 
 React-Pdf v2.0.2
 
 Chrome browser, Mac OS

**Comment by dennemark** [comment]
Hi,
svgs use transform normally within their xml tag `<svg transform={...}>`, but react-pdf svg want to use it within its style object.
In my converter mentioned in the issue #1234 above it is possible to implement it rather easy via 
`style: {...getStyleObjectFromString(node.properties.style as string), transform: componentProps.transform ?? "" }`
But it seems the transformations are still not identical. This is, because the svg transform is not equal to css transform.
I.e. svg rotation: `transform="rotate(90 100 100)"` 90 is degrees angle and 100 100 is the rotation origin.
in css it is rather `transform: rotate(90deg); transform-origin: 100 100`
