### ISSUE TITLE
AWS Lambda Error: ENOENT: no such file or directory, open '/var/task/data.trie

### ISSUE THREAD

**Issue by martinval** [diegomura/react-pdf#1256]
trying to use v.0.12.1 with AWS CDK and a Lambda function (tried both typescript and js).
When I try to run I get this error:
```
Error: ENOENT: no such file or directory, open '/var/task/data.trie
```
Lambda looks like this:
```
const PDFKIT = require("pdfkit")

const pdfPromise = new Promise(resolve => {
        const doc = new PDFKIT()
      
        doc.text('hello pdf Kit...Please work', 100, 50)
        doc.end()
      
        const buffers = []
        doc.on("data", buffers.push.bind(buffers))
        doc.on("end", () => {
          const pdfData = Buffer.concat(buffers)
          resolve(pdfData)
        })
      })

```
Lambda runtime is Nodejs_12_x
I'm not using webpack or anything else, so no idea how/where to resolve this

**Comment by diegomura** [comment]
I'm confused. Where are you using this library in the lamda function? It seems that this issue belongs to https://github.com/foliojs/pdfkit

**Comment by martinval** [comment]
OMG Sorry, I totally posted on the wrong bowser tab. My Bad. Been a long day...
