### ISSUE TITLE
Failed to load PDF file on Iphone 8 Safari

### ISSUE THREAD

**Issue by niktnikt** [diegomura/react-pdf#1259]
Hi,
I'm using react-pdf version 5.2.0 in my project. Everythign works perfectly on most devices/browsers.
I decided to test my app on Iphone 8 Safari (using BrowserStack) but unfortunately it doesn't work - the PDF file fails to load.
In dev tools I'm getting this message:
`The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. ReadableStream and/or Promise.allSettled); please use an ES5-compatible build instead.`
What's the issue and how can i fix this?
Thanks!

**Comment by diegomura** [comment]
Wrong project. This issue belongs to https://github.com/wojtekmaj/react-pdf
