### ISSUE TITLE
Question: using react-storybook

### ISSUE THREAD

**Issue by jmjpro** [diegomura/react-pdf#126]
Can I use react-storybook to design a PDF with react-pdf?

**Comment by jbovenschen** [comment]
It's not supported currently, if we get the dom bindings working again. You will be able to just use the `@storybooks/react-storybook` package directly. 

If we want to use the node version we should create a `storybooks-react-pdf` package, which does not have any priority with the current state of the project. But would be cool to have.

**Comment by diegomura** [comment]
Closing this. It's not an issue, but a question that was already answered

**Comment by jmjpro** [comment]
@jbovenschen what are the main things missing from the DOM bindings?
