### ISSUE TITLE
Is possible remove the hyphens in the Text component ?

### ISSUE THREAD

**Issue by fabianmedina09** [diegomura/react-pdf#1262]
The text component only have the _hyphenationCallback_ property but I have tried with different values and I can't get the hypens to disappear at the end of the lines with the textAlign: 'justify'

is it possible to remove them completely?

Thanks for the help

**Comment by diegomura** [comment]
Please check https://react-pdf.org/fonts#disabling-hyphenation . If you are already trying that, please provide a snippet of what you are doing so I can take a look
