### ISSUE TITLE
How to display fonts in text in multiple lines

### ISSUE THREAD

**Issue by TianYu0605** [diegomura/react-pdf#1266]
**How to display fonts in Text tag in multiple lines? Please describe.**

**Comment by diegomura** [comment]
Not sure I understood. You mean being able to use multiple fonts in different parts of a paragraph? Such as inline styles?

**Comment by sandren** [comment]
> Not sure I understood. You mean being able to use multiple fonts in different parts of a paragraph? Such as inline styles?

@diegomura Is this supposed to be possible? I haven't been able to get differently formatted text to appear on the same line. When bolding or italicizing a single word within an otherwise normal formatted sentence each part will appear on its own line.
