### ISSUE TITLE
Text nested inside Link is not clickable (not a link) in generated PDF

### ISSUE THREAD

**Issue by olhapi** [diegomura/react-pdf#1267]
**Describe the bug**
When I'm trying to stylize some part of Test inside Link component that stylized part becomes non-clickable, it isn't a link anymore.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create Link component
2. Inside of it create text component with some styles (or without, doesn't matters)
3. See result: test wrapper in Text component non-clickable.

```
<Link>Some <Text>stylized</Text> text link</Link>
```

**Expected behavior**
All content inside Link should be clickable link, like in html.

**Desktop (please complete the following information):**
 - React-pdf version [v2.0.8]

**Comment by sudonitin** [comment]
Facing same issue

**Comment by natterstefan** [comment]
Is this related to the fix https://github.com/diegomura/react-pdf/issues/1186, @diegomura?

**Comment by olhapi** [comment]
@natterstefan @sudonitin I think it's been fixed already in some latest version.

**Comment by natterstefan** [comment]
> @natterstefan @sudonitin I think it's been fixed already in some latest version.

I need to verify that again when I am working on the project again, but from what I’ve seen, this is still a bug.

When a Link wraps Text, the text is not clickable.

Can you verify it works with the latest version?

**Comment by olhapi** [comment]
@natterstefan I tested it in my client's project and it worked. But I can't be sure that it'll work for everyone, because I'm converting wysiwyg content to PDF and there are a lot of staff happening in between 🤔

Also, unfortunately, I can't create some sandbox to check it. Stackblitz and Codesandbox are failed to run latest version.

**Comment by natterstefan** [comment]
> (...) I'm converting wysiwyg content to PDF and there are a lot of staff happening in between 🤔

Ok, that’s what I’m doing too. Which library do you use for that? Can you tell me, please?

**Comment by sudonitin** [comment]
> @natterstefan @sudonitin I think it's been fixed already in some latest version.

Not sure about the latest update but the below code snippet worked for me after commenting here.

`<Link wrap={true} src="https://website.com/" render={() => "www.website.com"} />`

**Comment by olhapi** [comment]
> > (...) I'm converting wysiwyg content to PDF and there are a lot of staff happening in between 🤔
> 
> Ok, that’s what I’m doing too. Which library do you use for that? Can you tell me, please?

@natterstefan  Sure, why not. I'm using *draftjs* wrapped in *mui-rte* as wysiwyg and *redraft* to convert wysiwyg content to *react-pdf* components. We still having some issues with displaying images from wysiwyg, but in general it worked pretty well.
