### ISSUE TITLE
Transform:"scale()" not working

### ISSUE THREAD

**Issue by dluigirafael** [diegomura/react-pdf#1268]
**Describe the bug**
 Transform on both axis its not working 
 (transform on just one axis works)
 0.9<= values make the element disappear

**To Reproduce**
 { transform:'scale(nr)' }

https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed2870e9da804946fc3369d31a78a95144639480c0d5c6744004ec1b002200f4b70c44f011d9000add030009964001cc0f9dd1c613c3538298ca93d780492d2e8199959d80801b8c8c800c5c0a1659c30f891a0319cf0243800cc791890448400b86001c801e42001dc784494fa0068385d817afa002ca0a12221bb3d3c5a2ae4f9a078a091816541193cfc4046c6953c00dc011801993c013401f4005401a400d400d840001c0075100dde400552503d18af000680138780041246c9962d3e991544512a8120b03304070300032a58c42485860309560355f61826871142a5eb3474911e128944818bbc40915e83c00acd30e57279310010ba0a020462f57ea2e3273b9bcbe0002440ce24000bc2a632172b28aa314707c02367180cce5a981be0d03b010d303bb1b3836bb56a75fad60baee000600d8b381b181419c3c4816d9c0afe8419d623c1840853631862351880c6157d04d8c30b0e4ea643944cf47b5b9fcd899e7807aa64a2690d627164001286078c02817068a52a8b0940d3c15110a8508258838a00

**Expected behavior**
Scale on both axis simultaneously

**Desktop**
 - OS: Linux
 - [Firefox , Chrome ]
 - React-pdf version latest(2.0.8)

**Comment by kidroca** [comment]
My workaround for the moment:

```jsx
<Component data={data} style={[{ transform: 'scaleX(2), scaleY(2)' }]} />
```

**Comment by tgermain-da** [comment]
This issue is holding me up. A scale of 
```
scale(0.2,0.2)
```
is correctly scaling the horizontal axis, but not the vertical axis
![image](https://user-images.githubusercontent.com/56657503/120219212-19924a80-c1f8-11eb-862a-4b3204919e14.png)
