### ISSUE TITLE
React 17.0.2 incompatibility 

### ISSUE THREAD

**Issue by gabrielrbl** [diegomura/react-pdf#1275]
**Describe the bug**
I can't install the @react-pdf/renderer in react 17.0.2. Incompatibility issues. Any help?

**Desktop**
 - OS: [Windows 10]
 - Browser [Opera GX]
 - React-pdf version [v.2.0]

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/1062
