### ISSUE TITLE
CssSyntax error: Unknown word, when using react-app-rewired

### ISSUE THREAD

**Issue by winterscall** [diegomura/react-pdf#1277]
Hi, I'm new to this issue report...

**Describe the bug**
I have been encounter some error css while using react-pdf, i've tried in newly created create-react-app it's working fine...
but when i'm using react-app-rewired i have this error, what should i do?

**To Reproduce**
![Screen Shot 2021-04-30 at 21 29 14](https://user-images.githubusercontent.com/7325314/116702246-703f1580-a9fb-11eb-8a9b-20841c19f7be.png)

**Screenshots**
![Screen Shot 2021-04-30 at 21 34 13](https://user-images.githubusercontent.com/7325314/116702561-d1ff7f80-a9fb-11eb-85a1-30e7c7547b59.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Safari
 - React-pdf version v2

**Comment by diegomura** [comment]
I'm not familiarized with `react-app-rewired` but maybe it's something to post there and not here. `normalize-svg-path` is a dependency of react-pdf but I do not own that package. Please file an issue there asking why that package is not working
