### ISSUE TITLE
Cannot run the example

### ISSUE THREAD

**Issue by tuananhtd** [diegomura/react-pdf#128]
I want to run the `example\dom-bindings`. I'm not used to Yarn, should I just go inside the folder and do `yarn install` and `yarn start`?

I got this error:
```
Failed to compile.

Error in /Users/tuananhtd/workspace/react-pdf/packages/react-pdf/~/tough-cookie/lib/cookie.js
Module not found: 'json' in /Users/tuananhtd/workspace/react-pdf/packages/react-pdf/node_modules/tough-cookie/lib
```

I though I have to do `npm install` but then I got another error 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-pdf@0.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@react-pdf/dom'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tuananhtd/.npm/_logs/2017-08-09T11_59_51_031Z-debug.log
```

**Comment by diegomura** [comment]
Hi @tuananhtd . `dom-bindings` examples are not currently working since we are not done yet with setting up `pdf-kit` to work on a node standard environment. @jbovenschen do you know if there is any progress on this? this is starting to cause lots of trouble.

**Comment by diegomura** [comment]
Closing this in favor of #101
