### ISSUE TITLE
typescript typings incompatible with inline styling

### ISSUE THREAD

**Issue by grahampcharles** [diegomura/react-pdf#1284]
**Description

When using inline styling with a POJO as described at https://react-pdf.org/styling , typescript returns compile errors.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create a tsx file (that would compile to jsx) like the following:

```
export default function MyDoc() {
const myStyle = {        display: "flex"     }
return ( <Document><View style={myStyle}></View></Document>);
```

2. TS will return a compiler error, since style is typed as Style | Style[] | undefined.

**Expected behavior**

If inline styling using plain objects is to be supported, this code should compile.

**Desktop (please complete the following information):**
 - Typescript 4.1.3
 - @types/react-pdf 5.0.2

**Comment by grahampcharles** [comment]
Hmm, on experimentation it seems that *only* `display: "flex"` causes this compilation issue. Stay tuned... I'm playing around with it.

**Comment by grahampcharles** [comment]
So: 

```
myStyle = {        borderWidth: 1,
        borderColor: "#000000",
        borderRadius: 5,
        paddingVertical: 10,
        paddingHorizontal: 20,
}
``` 

and it compiles fine. But if you add `display: "flex"` or any of the flex properties (`flexDirection`, `alignItems`, etc.) then it won't compile. I'm wondering if there are some missing definitions in the underlying @types for pdfjs-dist.

**Comment by grahampcharles** [comment]
Yeah, I'm in over my head searching the pdfjs source code. I'm going to leave this here as a bug report, even though I suspect it's in the underlying library. In the meantime, Stylesheet.Style still compiles, so I'll stick with that.

**Comment by grahampcharles** [comment]
More odd info... if you embed the style as a plain object:

```<View style={{ display: 'flex'}} >```

It will not throw a compiler error. Maybe this is something I'm not understanding about typings.

**Comment by grahampcharles** [comment]
Okay, got a workaround, anyway -- or maybe I should have known this all along. You have to import { Style } and typecast the object. (Do you say typecasting in Typescript? Anywho... 

```
import { Style } from '@react-pdf/types' 
const myStyle: Style = { display: 'flex'};
```

... solves the problem. To me, this implies a type name collision -- there's some other `Style` being referenced out there. But I wasn't importing a different `Style` -- the only one referenced was from `@types/react-pdf` , so I'm not sure where that would have been coming from. So... yeah. But it's done.

**Comment by diegomura** [comment]
Not sure I understood everything here but glad it's not an issue anymore 😅  Closing this now
