### ISSUE TITLE
Critical dependency: the request of a dependency is an expression in ./~/@react-pdf/core/~/ajv/lib/async.js

### ISSUE THREAD

**Issue by monkeydri** [diegomura/react-pdf#129]
I have this warning on webpack build (I use Webpack DLL plugin).

My react app then works fine but I cannot use ReactPDF, when I `import ReactPDF from '@react-pdf/node';` the app does not load anymore (not error shown in browser console or node console).

Might be related to issue https://github.com/diegomura/react-pdf/issues/120 as it might be needed to use a babel plugin so it can transpile async/await calls, but I really don't know how to.

I tried to use the babel plugin `transform-async-to-generator` but it did not change anything.
- `@react-pdf/node` &` core` v0.4.1
- `node v8.2.0`
- `yarn v0.27.5`
- `chrome v60.0.3112.90`

**Comment by monkeydri** [comment]
I don't have the warning if using `ajv` module v5. App still does not launch if I import ReactPDF though, no error shown anywhere, don't know if it is related to async/await...

**Comment by kennylbj** [comment]
+1

**Comment by diegomura** [comment]
You need to use the dom-bindings to run this lib on the web. You can check the `dom-bindings` example to see how to configure webpack and make it work. Going to close this for the moment
