### ISSUE TITLE
notes on moving to a production build

### ISSUE THREAD

**Issue by jmjpro** [diegomura/react-pdf#131]
1. We should consider adding an `engines` section to package.json listing with which node versions react-pdf is compatible like this:

"engines": {
  "node": "^6.4.0"
},

2. package.json dependencies can be both simplified and dynamic by adding babel-preset-env instead of babel-preset-es2015, babel-preset-stage-0, and babel-register. Here's the corresponding change to .babelrc lines:
```
{
	"presets": [
		[
			"env",
			{
				"targets": {
					"node": "current"
				}
			}
		],
		"react"		
	]
}
```
babel-preset-env is then smart enough to include the right polyfills depending on the node version:
```
node 6.10:
transform-exponentiation-operator {"node":"6.10.2"}
transform-async-to-generator {"node":"6.10.2"}
syntax-trailing-function-commas {"node":"6.10.2"}  node 7

node 7.9:
syntax-trailing-function-commas {"node":"7.9"}

node 8:
no special plugins
```

3. The dependency on babel-node at runtime can be removed by adding `import 'babel-polyfill';` to the first line of index.js, for example in the examples. Then we can have as parts of the `scripts` section:

```
    "build-server": "babel --source-maps --out-dir ./build ./src",
    "build": "npm run clean && npm run build-server",
```

and the examples can be run with `node` instead of `babel-node`.

Open question: why is babel-plugin still required if using node 8?

**Comment by diegomura** [comment]
I never used the `babel-preset-env`. Seems pretty convenient. Never had a problem manually specifying the presets though. What critical disadvantage do you see about doing that?

I don't have yet a list of all the engines that this library support, and it seems its needed for what you mentioned in points number 1 and 2.

For the point number 3, I got a bit lost to be honest. I think we are only using `babel-node` for the examples. Is that right? If so, it's not that crucial. Can you expand a bit more what advantages this could have?

**Comment by jmjpro** [comment]
My understanding is that without babel-preset-env we are loading each polyfill regardless of whether the environment (i.e. node version) already provides the language feature associated with the polyfill. So babel-preset-env means both less configuration and less runtime code.

For the engines section I left off the word _minimum_: we should specify the minimum supported node version. That's what `^6.4.0` achieves. FYI I tried to bable-node/babel with node v4.X and I ran into the error `Block scoped declarations (let, const, function,class) not yet supported outside strict mode`. I tried a few ways to overcome it but maybe we don't need to worry about node 4...

My point in 3 could be addressed in a paragraph added to the documentation/readme directing users how to run react-pdf in production. I forgot to mention that I can produce the PDF examples seem about twice as fast on my recent model MacBook when I first compile the code with babel and then run with node instead of babel-node.

**Comment by jbovenschen** [comment]
I did creata a 'babel-preset-env' branch a while ago, with the idea to be able to create different packages for node / dom inside the `@react-pdf/core` packages which could be resolved in the suitable packages, but don't have yet a fully working solution yet. Will come back to it hopefully soon.

**Comment by diegomura** [comment]
This is being done now
