### ISSUE TITLE
react-pdf V2 breaking change:  <Image> component doesn’t accept a function as image source

### ISSUE THREAD

**Issue by fgelaw** [diegomura/react-pdf#1316]
**Describe the bug**
react-pdf v2 Image component doesn’t accept a function as image source. 

**Expected behavior**
Should be able to pass a function as image source

**Screenshots**

**V1:**
![image](https://user-images.githubusercontent.com/5766490/118030983-00eaef00-b334-11eb-86e2-98ee283fdd4e.png)

**V2:**
![image](https://user-images.githubusercontent.com/5766490/118030648-933ec300-b333-11eb-8ba6-0bd9ee5965e8.png)

**Desktop (please complete the following information):**
 - React-pdf version [2.0.12]

**Comment by diegomura** [comment]
Fixed already [here](https://github.com/diegomura/react-pdf/commit/54962aa7b01fd21548b3bee35804fd5da19c9087). I'll publish a new version today. Thanks!

**Comment by fgelaw** [comment]
Thank you @diegomura !!

**Comment by albertodeavila** [comment]
Hello @diegomura! I think this fix isn't published yet. When it will be available? Thanks and good job with this amazing library
