### ISSUE TITLE
React pdf REPL - You are not rendering a valid document

### ISSUE THREAD

**Issue by nec0der** [diegomura/react-pdf#1319]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to 'https://react-pdf.org/'
2. Click on "Try it out!"
3. See an error "You are not rendering a valid document"

**Expected behavior**
Should display a valid example of the react-pdf

**Screenshots**
<img width="1278" alt="react-pdf-error" src="https://user-images.githubusercontent.com/15326429/118294781-13d30000-b4a9-11eb-9b2b-299a3fdd074a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Google Chrome - Version 90.0.4430.85 (Official Build) (x86_64)
 - React-PDF Repl 2.0.12

**Comment by diegomura** [comment]
This is a known bug I didn't habe time to solve yet. Please apply any change for a first time on the textarea and you will see the doc. Keeping this opened until I fix it

**Comment by nec0der** [comment]
@diegomura Thank you for a quick response!

**Comment by diegomura** [comment]
Fixed
