### ISSUE TITLE
Render PDF

### ISSUE THREAD

**Issue by brxshncy** [diegomura/react-pdf#1321]
Hello, how do I render my PDF from a web view PDF to view it as a whole PDF 
from this
![Screenshot_2](https://user-images.githubusercontent.com/54626649/118644841-ca6c1300-b810-11eb-855d-d29227daae0e.png)
to this 
![Screenshot_3](https://user-images.githubusercontent.com/54626649/118644873-d6f06b80-b810-11eb-898b-71cb0adda099.png)

**Comment by diegomura** [comment]
`<PDFViewer />` accepts a style or classname props. You style it as a regular react component
