### ISSUE TITLE
it does not work on safari mobile and chrome mobile

### ISSUE THREAD

**Issue by Denise-David** [diegomura/react-pdf#1323]
**Describe the bug**
The PDF is neither displayed nor downloaded on safari and chrome mobile browsers.

**To Reproduce**

retrieve these files from my bucket on an html page via script:

https://s3.eu-central-1.amazonaws.com/aptonbucket/bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/12.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/11.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/10.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/9.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/8.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/7.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/6.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/5.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/4.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/3.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/2.bundle.js
https://s3.eu-central-1.amazonaws.com/aptonbucket/0.bundle.js

or visit this link:

https://multimmobiliare.webflow.io/pdf

**Expected behavior**
It is expected that when the page is opened on the desktop the PDF will be displayed, the download will be started in mobile(as happens in firefox).

**Screenshots**
![image](https://user-images.githubusercontent.com/76938295/118777118-017e0b00-b889-11eb-8381-21edcd25b27c.png)

the error that chrome gives me is that one of the bundle files is too big, its size is 315MB

**Desktop (please complete the following information):**
 - OS: [Android,iOS]
 - Browser [chrome, safari]
 - React-pdf version [ v2.0.0]

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/714 
Going to keep the previous one to track these issues
