### ISSUE TITLE
Html <span> quivalent feature is achievable with react-pdf tags

### ISSUE THREAD

**Issue by shilpihjp12** [diegomura/react-pdf#1324]
**Html <span> quivalent feature is achievable with react-pdf tags**
We have multiple text tags and we wanted then to show them as a signle text line. like when we are using span tag in html and the line is not breaking. Is there any way to achieve this.

Any help is appreciated.

**Comment by shilpihjp12** [comment]
> **Html quivalent feature is achievable with react-pdf tags**
> We have multiple text tags and we wanted then to show them as a signle text line. like when we are using span tag in html and the line is not breaking. Is there any way to achieve this.
> 
> Any help is appreciated.

**Comment by diegomura** [comment]
Hey! You can use nested `<Text />` elements as spans
