### ISSUE TITLE
Image examples are not working

### ISSUE THREAD

**Issue by elpic** [diegomura/react-pdf#133]
Image used in the example doesn't exist anymore. Maybe examples could be updated.

**Comment by elpic** [comment]
Maybe you can use this service. https://unsplash.it/300/300.jpg what do you think?

**Comment by diegomura** [comment]
Haha. Thanks @elpic . I just run across the same problem and solve it here https://github.com/diegomura/react-pdf/pull/132 (with another image though 😂 )
