### ISSUE TITLE
Flex `order` does not work

### ISSUE THREAD

**Issue by kidroca** [diegomura/react-pdf#1340]
**Describe the bug**
Ordering flex children using the `order` style has no effect

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Have a container View with flex direction row
2. Have some View elements of equal width
3. Assign a different `order` to the elements
4. The elements stay in their original order

[Repl Snippet: Row items using order](https://react-pdf.org/repl?code=3187b0760ce02e0040b204f012880ee302f0c01404a4c07c3805030c00f002223002b80b602998501a591400a02180e68cc680800da30c01bc8688800e80118800260802f9b0e1dc803500968dd14b1e2036a1d9a05b71d611802700ba6bd868090daf41a8228e9afd26702330b0800d0c388c082da29d80170c000b0c0aa38139000aa30007ab0028a2a2b7344c003294114035b9003d264e5a756ebeba868c1b9367b784afb7b990687864745c4c0033326a46766b0004b7040c3720aa14628c1837131ac024a04d5d6b0d474b6bbbbea09f8f99807f58446ac8c02304da94fd401c880c228eadbe883080066fb698358ece0e3b43c172e899ae81609dc86315b3c4004c2f3481c08001955a450130003ab58a076407f441f5238784e2e0a23569109a8f1f82d1ab50e84c161b170006e623102cd01874930a54b89400168c46140027f6e193b0e27602994f155468000edc02b5978e91036be2a3002b08421bafd58178002110140a0207a3c4006c16ab5ea7eb69994474002f7039584a6cf5905496b2059cad61196a3880d116528bf46300a03a703c400e4b6340e6a389e4d136cdc134c073a832f6b0bec48fb011a1f084293d90038be750f147916c8f422af1ac5a3b26780dc66da2fb30540e91450296e746a31928c00a4758d080006ee4e11a17352b9cc4c09b8e00f6c43b02e600b4e300030c11f77b3d91ad3ede2e71e8fc79bb5f30051865b04979d17319a7402510018401289730018918345183751800138cf06c547e505241186e0334e128000c4643f8c0145b072110141d06a8081c2800)

**Expected behavior**
Ordering items differently using flex order should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - React-pdf version 2.0.12

**Comment by kidroca** [comment]
I was originally trying to recreate one of the flex tables here: https://css-tricks.com/accessible-simple-responsive-tables/#responsive-tables-with-flexbox. But then I saw that flex order doesn't seem to work

[Repl Snippet: My PDF Table](https://react-pdf.org/repl?code=3187b0760ce02e0040b204f00a810c04601b0298c0bc3002804a3c03e420281860078011118015c05b2cc294abada005140398e6809b2e00de23b040074684001304017cb8f1e3401a804b2c01dc614ac1203691d9a038a6d60b002700baabbba80905b741a3a7ccce0583030006861c46040ec15ec00b860011842d0518001ac04ec4098c01401844030236201c80188b1ca8a61949d486890b0003d38014414145122600194a03a526801e9ea9b6a0675f4d5d461ddc6bca1458dc4cde7a4fc038343c32262600098aa6aeb1b380024502060510cf4221460c050d8ee0125fd078739076726dc3df50c568b6582c2ceb109856e3b003301d544711800e4403005368ecfa7c800cddec751b7c5c3c19a78010b1f20341817056ca276588005961b50fa900032b770a626000751b141ec98f58e2465f4f17009d4227fdbc4b5f3f9299b486d3e289649a432595cbe50a3052b94b0956a9c399002970374c0203d10b3e635178ba67f39a9265e4b5bca21db257ed0d4cdc59c2e57080dd3a0f278c0d9600130030282b50d712289bdb254eb10ba416e8d87a69b1184fbe19c3a1a231184c6c400e2000b10341ad78bb54c1db3125a781ab39567a93b067e79900690b5e82e16a82566c023ae26f462c6ca65b40d9582159ed8824604954ba532d93c81495ba8aa320ba400209d810571e9f527b6a4ecf1df3b24663b54c56c5bd87667fb2ed776686b077022e5028d80def8bdecdb4a6d96014a766f8c079a7eb8916e88dca5ac4088206c1d8da0a060436531ce5062eee9764a8f648622c8b80583e17784ab42ded3812833f04224c83030cc1b01c17044000dc1405096340f385cf80f40b17495b94501f8e88a07c810e2370f2128b10a9ea0000e281b4e392020169b9800ac410123a5e9918004220140500802c2c4001b299e66e9a8a4627044da0005ee02f41809966750ca30530258bd0d83b2693c262d803428560c0140da380c50647a11461750716345c9d8281193a9e80556959770a17701d86904ae50d396196aed94c02c074020d89a3d829700282057b3357a3680a28ec5142508c863400a4e57a8200006efc8147a314639b4ec0cd3c2b5763b560314002d0c200030c0c741d1b75016479023147131d71139e77ae8a8f2c3656b9b35f227abbb6abaaec58139580009c1b655ca009424004a58324502f07400062323a2d93d8040d0882a0980e003290e0d00000)

**Comment by jeetiss** [comment]
Hello @kidroca! `react-pdf` uses `yoga-layout` that doesn't support flexbox ordering https://github.com/facebook/yoga/blob/master/javascript/sources/entry-common.js#L173-L210

this is only one issue that I found https://github.com/facebook/yoga/issues/1037, bump it)

**Comment by kidroca** [comment]
Thanks, I've moved away from trying to use `order`
I guess we can just render the elements in the order we need them 😄

**Comment by gedion** [comment]
If flex order is not supported, the documentation(https://react-pdf.org/styling) should not claim that does.


<img width="1122" alt="Screen Shot 2022-02-25 at 2 34 17 PM" src="https://user-images.githubusercontent.com/1224206/155799228-5c5bb4c5-c656-4181-a1c9-6afd90872409.png">
