### ISSUE TITLE
Issue in rendering large text on PDF

### ISSUE THREAD

**Issue by emohnish** [diegomura/react-pdf#1347]
**Describe the bug**

I am using @react-pdf/renderer package for my enterprise application. It is used for creating the pdf. Following is the one issue I am getting:

**Facing issues in rendering large content**. I am not facing any problem with rendering smaller content. On UI, I am having certain free text boxes. If I enter smaller content (few lines/words) then its not an issue.

But when I enter few lines in those text boxes, there is a problem and browser Chrome or Edge both becomes not responding.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

My pdf contains one section of text only. If text length become more than certain characters (alphanumeric, spaces only) then it breaks. Number of characters are not fixed. Sometimes it break at 1670 characters, sometime at 1800 or even more.

Following is the code snippet:

const generatePDF = async () => (

  const doc = <DocumentPdf />;
  const asPdf = pdf([]);
  asPdf.updateContainer(doc);
  **const blob = await asPdf.toBlob();**
  saveAs(blob, 'document.pdf');
}

For larger text, above line of code (in bold) breaks down, not able to create the blob and browser becomes not responding. Eventually, browser has to be killed.

**Expected behavior**

I am not sure why it is failing on sometimes at 1669 characters, sometime at 1800 characters and sometime more. Is this related to memory. These many characters are very less and my pdf size with this text is around 3 KB only.

It always breaks at asPEF.toBlob().

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Edge
 - @react-pdf/renderer - 2.0.4

 Sure.

**Comment by diegomura** [comment]
Can you provide the document implementation? Your snippet shows the container update and blob rendering but that's shared for any document.
