### ISSUE TITLE
"debug" prop no longer works in 2.0.14

### ISSUE THREAD

**Issue by tgermain-da** [diegomura/react-pdf#1351]
When using the debug prop, the following error appears in developer console:

index.js:1 TypeError: Cannot read property 'right' of undefined
    at PDFDocument._initOptions (pdfkit.browser.es.js:2665)
    at PDFDocument._text (pdfkit.browser.es.js:2592)
    at PDFDocument.text (pdfkit.browser.es.js:2615)
    at renderDebug.js:127
    at tap (tap.js:26)
    at _dispatchable.js:38
    at _curry2.js:19
    at f1 (_curry1.js:16)
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
    at when (when.js:32)
    at _curry3.js:28
    at f1 (_curry1.js:16)
    at tap (tap.js:26)
    at _dispatchable.js:38
    at _curry2.js:19
    at f1 (_curry1.js:16)
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
    at renderNode.js:78
    at forEach (forEach.js:42)
    at _checkForMethod.js:20
    at _curry2.js:19
    at f1 (_curry1.js:16)
    at _pipe.js:3
    at _arity.js:10
    at renderNode.js:70
    at when (when.js:32)
    at _curry3.js:28
    at f1 (_curry1.js:16)
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
    at renderNode.js:78
    at forEach (forEach.js:42)
    at _checkForMethod.js:20
    at _curry2.js:19
    at f1 (_curry1.js:16)
    at _pipe.js:3
    at _arity.js:10
    at renderNode.js:70
    at when (when.js:32)
    at _curry3.js:28
    at f1 (_curry1.js:16)
    at _pipe.js:3

**Comment by kidroca** [comment]
I think I've stumbled on this one when I used a percentage value or the word `auto` for width/height/margin. 
Yep, I think it was for a footer that I keep fixed on the bottom with `marginTop: 'auto'`. 
If you set `debug` to such a View I think a function that computes sizes (width/height), to show them in the debug information, throws when it tries to deal with the non numeric value `auto`

**Comment by jeetiss** [comment]
looks like #1328 breaks debug prop 

this [line](https://github.com/diegomura/react-pdf/pull/1328/files#diff-9791eb3a23499fad9e6b51ec68d121b6aeeeab228c5f6f2924d6b049974fc8deR43) lose `this` context at `this._line`

and [this](https://github.com/diegomura/react-pdf/pull/1328/files#diff-9791eb3a23499fad9e6b51ec68d121b6aeeeab228c5f6f2924d6b049974fc8deR85) `this.page` doesn't have `margins` prop

I don't know how to fix that, @diegomura do you have any suggestions?

**Comment by luskin** [comment]
+1

**Comment by OlivierLouvet** [comment]
+1

**Comment by diegomura** [comment]
Sorry about this. I know what happened. Working on fixing it today
