### ISSUE TITLE
White line on the bottom of the rendered PDF

### ISSUE THREAD

**Issue by jperestrelo** [diegomura/react-pdf#1357]
**Describe the bug**

Not sure if its a bug...
I´m trying to use an image as a background and It showing a white line on the bottom of the rendered pdf.
Can't find a way to remove it, I have tried, many different page sizes and image sizes, the result is always the same.

[here is a printscreen](https://monosnap.com/file/yz2tNMm4dF9GJyuL6x5Ezbx4LAbxC3)

If its not a bug, can you help somehow?

Thanks,

**Comment by diegomura** [comment]
Can you provide a small snippet replicating this? I can't tell from just an image. Thanks!

**Comment by jperestrelo** [comment]
Hi @diegomura ,

I can isolate the code just to this, and you will be able to replicate the issue:

`import React from 'react';
import { Page, Image, Document } from '@react-pdf/renderer';
import Background from '../../assets/images/diploma_background.png'

export const diploma = () => {

    return (
        < Document >
            <Page size="A4" orientation="landscape">
                <Image src={Background} />
            </Page>
        </Document >
    )
}
`

I also attach the background image
![diploma_background](https://user-images.githubusercontent.com/65506551/120919404-51463a00-c6b1-11eb-95d1-bcb26a1bd06d.png)

**Comment by diegomura** [comment]
You need to set the image width and height to 100%. You can also use objectFit: "cover" or similar so it adjust to the container

**Comment by jperestrelo** [comment]
thanks @diegomura , setting the width and height to 100% solved it. 
And thanks for the library, it works really nice and its really easy to use 👏 🙏
