### ISSUE TITLE
Missing `layoutData` in `onRender` method of `<Document/>`

### ISSUE THREAD

**Issue by jeremy-christian** [diegomura/react-pdf#1360]
Hi there!

Not sure how to flag this, but moving from V1 -> V2 the `layoutData` property passed to the `onRender` arguments for the `Document` component has disappeared?

I cannot remember if this property was ever documented, but I've been using it to dynamically build a contents page on-the-fly.

```
const onRender = ({layoutData}) => {
 // do my thing
}
return <Document onRender={onRender}>{children}</Document>
```
I'm struggling to figure out what happened to it, anyone who could point me in the right direction would be much appreciated! 😁

**Comment by diegomura** [comment]
I think this got accidentally deleted on v2. I'll work on adding it back asap. Thanks for raising this and sorry

**Comment by jeremy-christian** [comment]
> I think this got accidentally deleted on v2. I'll work on adding it back asap. Thanks for raising this and sorry

That's amazing thank you so much.

It'd be really handy to have it documented too - it turned out to be a massive help when doing multiple re-renders for content specific pages - like table-of-content pages.

**Comment by evgimov** [comment]
@diegomura Any updates on when it is going to be added?

**Comment by diegomura** [comment]
@evgimov no updates here

**Comment by manuschillerdev** [comment]
We would also need to have access to `layoutData` in `onRender` as well.
I'd love to contribute bringing the feature back to react-pdf@@v2, but I'd need some small hints in the right direction @diegomura - would you be open to a contribution regarding this feature?

**Comment by manuschillerdev** [comment]
I tried to use https://github.com/diegomura/react-pdf/pull/421 as a starting point, but the APIs have changed too much in the past 4 years for me to understand where I'd need to start :/

**Comment by manuschillerdev** [comment]
@diegomura since I'm still stuck with this feature - would it be possible to sponsor this feature to bring `lyaoutData` back? :) 
If you are interested you can get in touch via DM as well any time https://twitter.com/ManuSchiller/

**Comment by bastiampos** [comment]
@diegomura I need dimensions and having layoutData in onRender can be very helpful. it would be grat if you add it again

**Comment by jeetiss** [comment]
I released the new version with `_INTERNAL__LAYOUT__DATA_` in `onRender` callback. Use it at your own risk
