### ISSUE TITLE
Fonts dont apply to PDF (ciryllic)

### ISSUE THREAD

**Issue by griffith-yo** [diegomura/react-pdf#1366]
I cant see russian symbols.
ReactJS 17.0.2
@react-pdf/renderer: 2.0.15

My code: 

```javascript
Font.register({
    family: 'Roboto',
    src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf',
  })
const styles = StyleSheet.create({
    page: {
      fontFamily: 'Roboto',
    },
})
return (
<PDFViewer>
    <Document>
      <Page size="A4" style={styles.page}>
        <View>
          <Text>Some text: какой-то текст</Text>
        </View>
      </Page>
    </Document>
</PDFViewer>
  )
```

After downloading the document i can see this:
![Issue](https://i2.paste.pics/CRDS7.png?trs=9a9c19a88aa6fcc0962466e37ea06ff3616432dbb6308a96444626b53a4fc5cd)

I used solutions fron here #328. Can anybody help?

**Comment by diegomura** [comment]
It is working [here](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634ad0049467e0c43cd11e35339245381550bce085b606c00220cbbb3880c80473a834008cb25abc4f8ef2786406941d3ed8663518dd6410043c8ca500a8c3383e1e3c400b75004088403023800b86a58282d87850569345a305018094486012000cfd5210c030b53b07239a49b0ad1c3c4608020a4f3120943c111f149345913d2888243d530ab2c1323a5d1e93cf6392350cae2559261f4ea354c000a2d50435444083e0f16c3ae6ab5f5dd1e000693d0c21292c020463c9fc3050cc001483b293a233796d99801e8e1a3c9c46021baa4b286118f152402b01b2406df1ad274c165f2c548b7552cf4b4c0002f568b0603c6812044625b08003d6775bb6ddb05821fd917a3e3aa8e16a8060bcb77d799337f12866b21800154c0ad101f619580552a608c0021c40605b602b44bb6bbed8c0f180c4015f176772bdd7cbf5f43dd198019284b092d7af225846db1366070c17bc8d614a7eada622b0fcb76cd136659d82f84043a2a0017f54f102a61920d19343c0008fd61ca082d29875e9ba30e452a7863ee02a28c256ce8613499830091b60ec9eaa235b4471ab23c36e768acfe3400d91e6b9742e8f1c30f0c1ada4d06ccb3ba9800677888ed931a5b2c2ea6e827baad0b4d7b38663d2d78b2c3020d7891ac020f39368c880b68b11024a01ac14a256265f2ac246100169d2b4914d6e02d208729ce4de664cc48336a49feb6b38a1b6eba18095985c95deef8c04eab412bde4b259efa25de63993bf8ac14ebcb95c308011b913c2da25946a49f6181ba8975958460e47e94b995d524aad836cc84a45a4df10b4ed806bd776f8ada2c040bd8b48972cd3b00b39ae928c0501863c2254c916f28d8b4b6e0018ad8482d5d6476b767a6012cd000eb6ad6a7a924e6c11c9744b3355d951485f20c534a0216620a05cb54fe07253a458bac3eeae1c8666940b0b514c7340e3f48000370c07c2d2d3758b62ba8847abc84a0b1cd4c9deedb6e1a9d89d8d81c87a0fae3674b08541dd28462c18662e7a1aad4c38c0a4a20662cb782f59dbd9328695da2ae5569482385cd7448076ce9369339df24c6d54d8d01602569266300cf7c82c0104393abd516b60716000a44ad2d78e9c4fe22c4c8c3234e8585982b27605b822ea2d29c3526ad1793f13c67c829b69dc1efd2827d009946df4d280d83e779308740555609d932fbad8b4872df9280025cacd1ac5efa2add40bd5bc44eb9dcdab401edd46964fb36270be808a98488c896bec3680b769e18277dc0608975d86b755f66081d46eecb98329ca00e054dad2e775e2ac57086daf412052a92caf6f54e31e795e3a8acd4480442c5f2b0dcd06068e220900462f236d2e82a7ec214bd99d6d81559c0371e414c5cb9d2de5810f1962509c9e68ed4f4e742caf756076c563f2414ec9ef8ea142ad0d98b52ecd58993581626005e8d20928dd040207121c8583ca726bc8069f06c1ad1e9110e728f9e8bdf1da1f57915b3a4e44edb5435668252ab22e4e78730f46bc3d05f1ba50af98ebb1e5b4915c32d2102b48031096a1619e22d20f4c03406853bc08406ad810a4557a9883b07c2bb0407c4cd0c406c4e46398ab76611ca09b030682ae4100591e84ec3d28a302de29a3e0a6ccc2c022c50cd78c42da2121808ea74581d51e424913afd49b2f5386bdda51f23141281f8c007acb1c867439a001957b16c724b9266078ea12d19e87d2686246c54a5a13c04b11e6bce359e97461cd79692cd5c2ce48437640ae70059e4829d509a2a75b0365bc5fe664939593f53104342a800e8e13340ac17f0b1830038a5c8f8f4861268b231c3e241cab1c01344ecd997d2b93d20247a11e7da1001d9841009489922cf6154386391385d51d6b9e74ac8b439708c06bd604ac5382f8188b14883c15b37e160f386e7e4ec53d5aa9390c5cc063bd401e3790b8313d6298a53d15a1f49c312026ed512269c801959ba40b5820a82fb3238cb057ab695650c9cb39163e410d91967dccc0d09251b2e9df894ca315811c0cc3280833a0065e44d87a3007f95ccad66e186075980a33b8925fbaf547554abd2da0d8f2a299531b0ecc47bf4534f09cd18c528f3db12501f0e00754615e4c63d09a105924bc00093d9c143b0ac22c92c9c640b4e07409b90ef9420b49981d2221e0b762c01ec238f0bb0364cd4ea48ae15a8bba10e22c581944dcca2dba36231d10ac9a674adab3b4f0b8c0c41d4bd53a001059eb404e4980641be745660731842b2964188404e4248b69f6100db8001c9db6bead1b32f21299d8818614b083230aca98d000859a67417aab02073c8164ebe42560b1bd3aaac56f87c0baa257763317d6742b6e78783d962631c004d63447199b788d31df228ba1571c7905812da9d3849a4d549786181d845a03430e3e7647499e95af02a1c688c814e69c9c911854103f6b54312a6dc0e52cfeb9a3d2a21422020716ad68a33982954a2932991755cdf20c41761d2ee5cc64d0059a252ad18015ebe45368c0735cea9c3b16265d29c46dc9814ce54d6824e3332b10ac2ca66b1109b405ac5713181303789da3b2624552d6fb9308d6721761c67560eee3aac628fddcbb6f9175fc1a4660095e42c8ca17d26ca9d201334ed693492c51243aa660212a67941006c4ca1a3bb17aaa58e5ac7b9960a8c9281d060f6b928ba3741e89f95706287c4c6347a0fdd29b5849c9b8b6b540e97c0000fcb076c2edda8e6840178561c4c2a52332bf2703b9a5c77cde02211d71d1b0b688e0649689800c5cb180d3b4e30550a001c5260b4726a70e2d982c087bd921e2bc0190afc4c5268bfc8f94d94b1e4f7c9e68557aba4cc96730687e854f359c7f61fb4d314236deab834f13a7fbb8d72f56e50854aa5595b001982cfcea8b765a0cc00cb7bf15cd0bbd61f10ddbbb5383dbf35c691d0ab9eaec70d942cb1646c91066eb099b9c9983bb60c436fc3df2cd359313743e94447f8998df939f254a7ad391f6f636ccab62a1280855430a12c02028d8c076c6e955266634071cdd9a444d716795a2800bd7183a4886610f1aeee40185ba62f257ed80360911fdd3b189310310b9728ac7354206f1080b6800a586c9180840f0b9ac0006428e6469f1b505371293e8894f4fbedf3e368da38d71a8a5ce18c660b10661fdd46e62b904f31429f46d831ad7350138bf1513e67998d57e774dd1c0b720614db8000caa14e491414d32714cd57c761d63d278b35531095846ebf7b1c4c872f8cf4756e04b12cbcbc95eecbad06cd64c0042f48a6697ccc1f2be72f5bdc7d97bdce408f2b7d76494f240319b0d50e5269b20804b11d84ce42c29410125d49a2ad56049f65830e5c573c70922a1937b859324678322721e6b05b47c10aa69333d0bc58c7f32935b90c26941a27946993002536146590f10c05fd7834b15b42f774c4ba42a7402eb16134a7c0c7271d1ce5563c52744dc3370f00b77600e060d49e50d64412201043d26078907026a3ba4903c00904b2390850cde33a7400545e00106bc5502206c05203c05b400003000120905908c0790f0c3b00700c81806b0f3a2bf7d0b30550730a780200706701405701806844384c80f0f704c83a00605ff76002052632032007a7002805907f06036b65b03508e071460e2104a400072000250ea7401003c8d2f1786007c8f302802807880807240c80c86002506f639054f1001890a57f05903860c81e01961400c87b15f87220006b0c800066590104204000060c84355605f8228c5073a0c801c5589005886013e06a8d88608479458e489a8c70328b20230f88c48d60148c1a1613b04c8ca06c8dec5c89803c880079080608054250338ca00a8aa89a8ba8868858a48b903e00ae3286001e8b0c0c85f82942f89102500c80d82040988c80004d0007d6d00006900035000361000000e000751000d87901dc250098c604c48000d0004e1e069d69d4b4280538f38d88f8896468029e10e5c03693183694b07731e8a884c00788bf6501788904381222503640c96d01007884a4098800561bf4b2454d6247d7400334a4024ad4f94eb0254be00000934a2592bf754934ca055052f0c43104a4394cd02388e956c0c04a400026000166d4fb769d1d8b007c8ab53425b05f8ce023887a266110178f78cf8ef8bc88e04748e053643e5b0574c380f4a402f4ca42041f4c0cfd860c85850cd78f0c93b28cca04336033007d49a8b0c4a43f4d98d2f34cbf8b44674ef4980374e8ca48cf4eeca04624ed4dacf2202ca2c9cca48d8c9c8fc895892894c874a74fd86cccd051cf2cc2ced4dccfcc98020400cc3820c90cfc88261ec4702106aca7029cb8c84cb9cf3a05c98076c9802036ecdec9ac91c7223c4bb048485402cfb4acc37cb002b4e7a1b4efc9dcd98d6cd4cd2f4b06b03b015cbecd6001cf1c91cffc86cc349801f4f02cd003cb2cb0cd1d48ced4d001242ccd78ca644f28c87cdb0fb0f89582ca022c1da3287007c8cba6941744c073cadcc1c89ccd0558d428988c2ce03104702804a43e2ca067a5d8a12980112c167d052cbe072cbc8cacbb073c8229987c8922b3cb6ce42230b88b20028ab01882e01a007a1b8a8e0c8aa00d43406d46846e4a000000). Can you check you are not having a CORS error message somewhere?

**Comment by LitvinenkoEvgeny** [comment]
![image](https://user-images.githubusercontent.com/12531457/124939040-dd81af00-e019-11eb-9e3f-dc7bbe5bba54.png)
