### ISSUE TITLE
Incomplete or corrupt PNG file

### ISSUE THREAD

**Issue by tianyanqiu** [diegomura/react-pdf#1367]
**Describe the bug**
I want to insert an Image in the pdf. My image is in base64 string format, but when i try to insert it I recived this warning in browser console:
![image](https://user-images.githubusercontent.com/25222222/121502146-779e0980-ca12-11eb-92c7-adb140c0deb3.png)

and the image isn't displayed.

This is my code:

![image](https://user-images.githubusercontent.com/25222222/121503646-d6b04e00-ca13-11eb-8aae-5034df2303ff.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - React-pdf version 2.0.15

**Comment by diegomura** [comment]
Can you provide the PNG's base64 code?
