### ISSUE TITLE
Warning in Test code

### ISSUE THREAD

**Issue by dngwoodo** [diegomura/react-pdf#1368]
Hello, i am writing a test code using '@testing-library/react' and it passes the test, but Warning will pop up as shown in the screenshot. How should I solve this part?

![스크린샷 2021-06-11 오후 11 44 10](https://user-images.githubusercontent.com/77663233/121704669-ec566e00-cb0e-11eb-92a5-64b977244463.png)
![스크린샷 2021-06-11 오후 11 44 20](https://user-images.githubusercontent.com/77663233/121704688-f1b3b880-cb0e-11eb-8697-513f0cccf9fc.png)

The code is as below.

Resume.jsx
```jsx
import {
  Text,
  Page,
  View,
  Document,
} from '@react-pdf/renderer';

import personalDetails from '../../../fixtures/personalDetails';

export default function Resume() {
  const {
    jobTitle,
    firstName,
    lastName,
    email,
    phone,
  } = personalDetails;

  return (
    <Document>
      <Page size="A4">
        <View>
          <Text>
            {jobTitle}
          </Text>
          <Text>
            {firstName}
          </Text>
          <Text>
            {lastName}
          </Text>
          <Text>
            {email}
          </Text>
          <Text>
            {phone}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
```

Resume.test.jsx
```jsx
import { render } from '@testing-library/react';

import Resume from '.';

import personalDetails from '../../../fixtures/personalDetails';

describe('Resume', () => {
  it('renders input value', () => {
    const { getByText } = render(
      <Resume />,
    );

    Object.keys(personalDetails).forEach((personalDetail) => {
      expect(getByText(personalDetails[personalDetail])).toBeInTheDocument();
    });
  });
});

```

**Comment by jeetiss** [comment]
Hi @dngwoodo
You can't use `@testing-library/react` for testing pdfs because it uses `react-dom` under hood.

**Comment by diegomura** [comment]
@jeetiss is right. Hope that answers it!

**Comment by jeetiss** [comment]
@dngwoodo hi again! I just add proposal for visual testing here #1372
try it, if you want
