### ISSUE TITLE
Custom Font Rendering Issue

### ISSUE THREAD

**Issue by KerenChandran** [diegomura/react-pdf#137]
Love this project so much that I decided to use it to build my resume. I'm trying to use Open Sans and Lato fonts for my resume, however, the resume isn't building correctly. In some cases, the last line of text is replaced with a blank line. I tried removing the custom fonts, and the pdf renders correctly, so I'm pretty sure it has to do with rendering custom fonts.

Here's a repo containing my resume: https://github.com/KerenChandran/resume
Resume can be found under `src/resume.pdf`

@diegomura @jbovenschen Any thoughts?

**Comment by diegomura** [comment]
hey @KerenChandran . Is this still an issue? Couldn't see what's the line that is getting blank on the `output.pdf` file that you got in the project

**Comment by diegomura** [comment]
Oh yes. I now see it. I think it's a layout issue. Yoga is giving less space than the text requires, and pdfkit is trimming it. I'll work on this. Thanks for reporting it.

Btw, this is one of the coolest usages I've seen of the lib so far 😉

**Comment by diegomura** [comment]
@KerenChandran I deployed `v0.4.6` that fixes this issue.
Also, I changed the `Page Layout` example with a `Resume` one, very similar than yours 😄  I hope yo don't mind

**Comment by KerenChandran** [comment]
@diegomura yeah I got a notification from your release! I'm cool with you using a resume example! Thank you so much for fixing the issue!

**Comment by diegomura** [comment]
Please try it and let me know if not working!

**Comment by KerenChandran** [comment]
Yup everything looks good! Thanks so much. Will need to continue working on this and then push out a new version
