### ISSUE TITLE
Feature request: Set creation date in Document props

### ISSUE THREAD

**Issue by icopp** [diegomura/react-pdf#1375]
**Is your feature request related to a problem? Please describe.**
Easily testing PDFs in a completely deterministic way isn't possible, because the creation date is newly-generated every time, making it impossible to just compare buffers.

**Describe the solution you'd like**
A `creationDate` prop for `Document` that takes a `Date` or whatever else would be useful, used to set the PDF's creation date.

**Describe alternatives you've considered**
Currently, I'm not aware of any other good methods for editing the creation date after it's already been generated, and visual comparisons all seem to require external non-Node dependencies that I don't want to deal with on CI platforms/

**Additional context**
This came about as part of trying to attempt to fully unit test PDFs generated and cached on-the-fly on a server.

**Comment by satelllte** [comment]
Hi 👋 
Is this feature planned? 🙏🏻
