### ISSUE TITLE
Create React Component in Node to render a pdf file

### ISSUE THREAD

**Issue by theanh28** [diegomura/react-pdf#1383]
Hi, sorry if this is a trivial question, but I have not found a solution online. 

I have copied the /examples/page-wrap/index.js and I want to render a pdf file in my Express server. But it seems Node does not allow the use of React. Could you suggest a way to allow that / another way to create the pdf without using React components?

**Comment by diegomura** [comment]
> Node does not allow the use of React

Not right out of the box. You need to compile your JS code using Babel and [react-preset plugin](https://babeljs.io/docs/en/babel-preset-react)
