### ISSUE TITLE
PDFViewer  and PDFDownloadLink nor working in SPFX (SharePoint React) project

### ISSUE THREAD

**Issue by ahmadbakhshi** [diegomura/react-pdf#1385]
PDFViewer  and PDFDownloadLink not working in SPFX (SharePoint React) project

dependencies:
![image](https://user-images.githubusercontent.com/17783744/123309326-05352b00-d4e2-11eb-936f-f1240c5a4c62.png)

that's how I call it in my component
![image](https://user-images.githubusercontent.com/17783744/123309138-c7380700-d4e1-11eb-9b0d-336ebb865aa7.png)

gulp.js:
![image](https://user-images.githubusercontent.com/17783744/123311662-a9b86c80-d4e4-11eb-9e74-13bffecc783e.png)

It just freeze with no error and makes me to close the tab at this point
![image](https://user-images.githubusercontent.com/17783744/123310939-d91aa980-d4e3-11eb-8339-ffbedac805c8.png)

I have tested in chrome and edge

**Comment by diegomura** [comment]
I'm not very sure what a SharePoint React is. Can you provide a way to replicate it?

**Comment by ahmadbakhshi** [comment]
@diegomura
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

It is working fine in localhost workbench, but not in online workbench.
to run your app in online workbench, you need a SharePoint account.
You can find all information in these two links

**Comment by diegomura** [comment]
Thanks @ahmadbakhshi ! 

Unfortunately right now I don't have bandwidth to get familiarized with a new technology just to fix a bug here. There are just too many environments or tools where JS can run. I'll leave this open but can't say I'll be working on this soon. Sorry 😞
