### ISSUE TITLE
fontStyle italic throws error

### ISSUE THREAD

**Issue by dearenot** [diegomura/react-pdf#1387]
**Describe the bug**
Error is thrown on setting the 'fontStyle' style property to italic

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/repl
2. Set 'title' style to
    title: {
    fontSize: 24,
    textAlign: 'center',
    fontFamily: 'Oswald',
    fontStyle: 'italic'
  },
3. See error ' Could not resolve font for Oswald, fontWeight 400'

**Expected behavior**
Italic text should appear in the PDF document

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - React-pdf version [e.g. v2.0.14]

**Comment by michaelmarziani** [comment]
Hi @dearenot,

This will fail because no italic font has been [registered](https://react-pdf.org/fonts#register) (link to docs). In my code I register a Roboto Bold font and use it like so:

```jsx
// Fonts
import robotoBold from '../fonts/Roboto-Bold.ttf';

// Register fonts for react-pdf
Font.register({
  family: 'Roboto',
  src: robotoBold,
  fontStyle: 'bold',
});

// Create styles for react-pdf
const styles = StyleSheet.create({
  bold: {
    fontFamily: 'Roboto',
    fontStyle: 'bold',
  },
}
```

**Comment by diegomura** [comment]
Thanks @michaelmarziani !! That's indeed the correct answer. Closing this as resolved
