### ISSUE TITLE
Ability to print PDFs?

### ISSUE THREAD

**Issue by codebu5ter** [diegomura/react-pdf#1388]
I'm looking for a way to print PDF files on the fly, without rendering the components.
For download, the **PDFDownloadLink** component works well, but for printing, I'm not sure how to make it work.

Here's how my component is coded for now -

```
const MyDoc = () => (
  <Document>
    <Page>
      // My document data
    </Page>
  </Document>
);

const App = () => (
  <div>
    <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
      {({ blob, url, loading, error }) =>
        loading ? 'Loading document...' : 'Download now!'
      }
    </PDFDownloadLink>
  </div>
);
```

Is there a way to print PDF files on the fly too?

**Comment by contactsimonwilson** [comment]
import print from 'print-js';
...          
const blob = await pdf(<MyDoc />).toBlob();
print(URL.createObjectURL(blob));
...

**Comment by uwemneku** [comment]
> ```
> import print from 'print-js';
> ...          
> const blob = await pdf(<MyDoc />).toBlob();
> print(URL.createObjectURL(blob));
> ...
> ```

This works. Thanks @contactsimonwilson

**Comment by diegomura** [comment]
Thanks for answering! Closing it as resolved
