### ISSUE TITLE
enhancement idea: support css media queries

### ISSUE THREAD

**Issue by jmjpro** [diegomura/react-pdf#139]
Enhancement idea: the Page component should support the CSS Paged Media Draft Specification. See
- https://www.w3.org/TR/css3-page/
- http://caniuse.com/#feat=css-paged-media and -
- https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/

**Comment by diegomura** [comment]
@jmjpro I don't see how the `@page` css property should work for the `Page` component. `@page` is used to define how an html document should be printed right? In PDFs, what you print is what you have.

However, I do see great benefit on supporting `@media` of components in general.

Please let me know if there's something I'm missing

**Comment by jbovenschen** [comment]
Could it beneficial to support a `onLayout` property like react-native does for `View`, so you could derive the width calculated by `yoga-layout`. If that works you could create your own abstractions for `@media` and `@page`. 

The hard part will be the node renderer, which should wait until the page is fully rendered.

**Comment by diegomura** [comment]
I still don't see what we can do with `@page` 😅 .
`onLayout` would definitely be a cool feature, but do we need it to support `@media`? From what I can see so far, if we can somehow pass page attributes (width, height and orientation at least) down to the `Stylesheet` declaration (in layouting time), we can infer specific styles for a component using media-queries.

Last night I started this project https://github.com/diegomura/media-queries to have a media-queries engine in case we need it in the future

**Comment by jbovenschen** [comment]
If we wan't to support the @media in the StyleSheet declarations, we don't need onLayout. We can just derive the "viewport" from the Page instance.

**Comment by diegomura** [comment]
Exactly. That's why I'm building that "media-queries engine". With that, it should be pretty straightforward. 
I still don't see how `@page` (which as far as I know are styles for printing) can have any relevance in the project.

**Comment by jbovenschen** [comment]
I neither see any need for the @page at this moment we should be ok, to just support @media and onLayout at this moment? Should I try to get onLayout implemented correctly.

**Comment by diegomura** [comment]
That would be great. 
I'm not sure yet how the media-query API will work yet. Im not a big fan of defining object keys as strings (`{ '@media(whatever)': { styles }`). At least not as a public API. 

Any ideas?

**Comment by jbovenschen** [comment]
Could maybe support nested values within `Stylesheet.create` thing is we should document it after we finish the documentation site. You could take a look within glamorous how it would look like.

**Comment by diegomura** [comment]
The media-queries engine first version is ready! It supports `and` and `,` (or) operators and enable you to query for max and min height|width, and page orientation. For the moment I think is more than enough. I still have to upload the npm package (any naming ideas?) and integrate it into react-pdf. I'm pretty excited with this feature. It seems to me it is one of those things that react-pdf can really do differently in comparison with other technologies. Never saw a PDF component that renders differently based on the page size 😂
