### ISSUE TITLE
Image component doesn't handle EXIF image metadata so rotates some images

### ISSUE THREAD

**Issue by SamWoolerton** [diegomura/react-pdf#1391]
**Describe the bug**
`Image` component doesn't handle EXIF image metadata so displays some images rotated.

**To Reproduce**
Display an image taken in portrait orientation (without stripping the metadata first).

**Expected behavior**
The image should display in the original portrait orientation.
It instead displays rotated.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Brave (basically Chrome)
 - React-pdf version: 2.0.12

I've worked around this by using [exif.js](https://github.com/exif-js/exif-js/) to detect the orientation and then apply CSS transforms (rotate and scale) to get the image back to how it should be; would be nice for that to all be handled by the `Image` component itself though.

**Comment by taipignas** [comment]
I also have this issue with photos taken with iphone.
Photos have metadata "OrientationRotate 90 CW" and pdf renderer renders them without rotation, while html rotates them to intended rotation.

**Comment by jeetiss** [comment]
@SamWoolerton @taipignas can you provide minimal reproduction with photo for this bug? I try to fix it

**Comment by jeetiss** [comment]
[I did it](https://react-pdf.org/repl?code=140630f60760ce02e004b027806c0a6538178e06518b51c00b5551803a1002754043195002806f60e38023300134402e38addbb000eb5bb700961003980804c001800d1b38017d57a809401b982848b0e00113020b1c46dab003e2b6a00f1990015c02daa08316daf68e001568655011f0d1319890d0a1c8b979d4112400bd5130008801040059d37d85851c0125dd8342a0a8403288606044a0f801e91aa96801ddc8652460895c395ca1512b2019bd28c1dc5b50dca906a91b50003d2400cc0168c0a924bc61e92520d69769dc44631b4b60871a00656821b8a04168455001f401d9c800ac4464f31d1a2532be50a8d2088441009707876be3d0198000253a080600113000c5c8347b90d18ce731c11ab678500000)

**Comment by tomherbin** [comment]
Hello, same issue here.
Are you working on a fix @jeetiss ?

**Comment by jeetiss** [comment]
I wrote the exif parser for `jpeg` and faced with code duplication problem, project use two copy of image classes: 
- https://github.com/diegomura/react-pdf/blob/master/packages/image/src/jpeg.js
- https://github.com/diegomura/react-pdf/blob/master/packages/pdfkit/src/image/jpeg.js

This affects performance and adds headache for right exif implementation, so I pause work on this task. You can help, if you want.

**Comment by phamyqb** [comment]
Any updates for this?

**Comment by chathu-novade** [comment]
@SamWoolerton I think rotating later after the calculation might have this issue https://github.com/diegomura/react-pdf/issues/2014
