### ISSUE TITLE
text not wrap correctly

### ISSUE THREAD

**Issue by DrMisQ** [diegomura/react-pdf#1394]
I'm using Arabic font for my pdf, everything works fine except when I have long text that needs to be wrapped, it wrap incorrectly (from down to up) instead of wrapping from up to down, any idea how can I fix the problem?

**Note**: English text wrap correctly without any problem, only Arabic wrap in reverse lines

<img width="791" alt="Screen Shot 2021-07-06 at 3 10 25 AM" src="https://user-images.githubusercontent.com/37986642/124525801-42b28600-de09-11eb-9945-b6717f58686e.png">

**Comment by GlennFernandes** [comment]
Hey @DrMisQ which font family did you use to get arabic text. Tried a few fonts and none seem to work for me

**Comment by Shabnam-Veranloo** [comment]
i have same problem with wrapping text 
@GlennFernandes what is your font?

**Comment by GlennFernandes** [comment]
Helvetica gave me garbled text as mentioned here [https://github.com/diegomura/react-pdf/issues/732](https://github.com/diegomura/react-pdf/issues/732) . Roboto gave me empty squares. I finally switched to Lateef . Its a google font, so downloaded the ttf file and registered it

**Comment by Shabnam-Veranloo** [comment]
@GlennFernandes thanks to your response i try Lateef and other font but still i have this problem :((

**Comment by diegomura** [comment]
This seems to be related to RTL support (https://github.com/diegomura/react-pdf/issues/747). This is not something we support right now, although I made some progress already.

**Comment by ahmadf16** [comment]
any update?

**Comment by klay964** [comment]
updates ?

**Comment by fr60** [comment]
Any updates?

**Comment by DrMisQ** [comment]
any Updates or suggestion to solve this problem?

**Comment by bondai-fahad** [comment]
Any Updates related to RTL issue? @diegomura .
I am stuck because of this problem. I really appreciate your help regarding this issue

**Comment by sadam-hussien** [comment]
Any solutions??

**Comment by kassah-mahmoud** [comment]
Any updates pls?

**Comment by sadam-hussien** [comment]
no,but iam create function which return the array of number of words in
array to made each array of words inside Text tag.[image: Capture.PNG]

**Comment by sadam-hussien** [comment]
Thank you  ❤

في الأربعاء، ٢٩ يونيو ٢٠٢٢ ٥:٥١ م Sina ***@***.***> كتب:

**Comment by shanike** [comment]
> ```
> const [splitedText, setSplitedText] = useState([])
> useEffect(()=>{
>    const _splitedText = text.split(" ");
>    setSplitedText(_splitedText)
> },[])
> ```

This can be a regular simple `const splitedText = text.split(" ");` (:
It doesn't need to be a state, even if there are many renders, it's a realy easy proccess to do every render it's not worth a state (:

**Comment by shanike** [comment]
Notice that if you had `textAlign: "center"`, using @X3rom-S 's workaround you need to change it to `justifyContent: "center"` on the View

**Comment by canimnazli** [comment]
RTL support ?

**Comment by abolfazl-zare** [comment]
I need rtl

**Comment by dashty94** [comment]
Can someone please give an update on this? It is apparently very important for a lot of people

**Comment by dashty94** [comment]
Splitting the words works but makes loading the document TOO SLOW since it has to load a Text component for each word.

Please someone add the feature to support RTL. It is important for so many people.

**Comment by YungVDev** [comment]
I see this issue is marked as completed however I'm encountering the same issue, even with the latest version of the package. Splitting the string and using a <Text> for each word doesn't seem to work as intended either.
