### ISSUE TITLE
Can't download in parts

### ISSUE THREAD

**Issue by Gricardov** [diegomura/react-pdf#1395]
**Describe the bug**
Hi chamos. I wanted to download and show a pdf file with only the first two pages. However, I saw the whole document was downloaded in the background anyway. I would like to know how to prevent that bug and only download the pages I need.
Thanks for your awesome project!

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Download the package and place two <Page> tags inside the <Document> tag.

**Expected behavior**
I expected it to download only two pages, but it download the whole document in the background.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrosme Versión 91.0.4472.124 (Build oficial) (64 bits)
 - React-pdf version v5.2

**Comment by michaelmarziani** [comment]
Hi @Gricardov,

From the version number (React-pdf version v5.2), it looks like you're using a different package with the same name:
https://github.com/wojtekmaj/react-pdf

Please ask your question in the issues section of that repository.

**Comment by diegomura** [comment]
Indeed. This belongs to the other project
