### ISSUE TITLE
updateInstance working example

### ISSUE THREAD

**Issue by redaben** [diegomura/react-pdf#1396]
Does anyone have working code that uses "updateInstance" function of usePDF hook? 

Unfortunately, in the documentation, there are only examples of "instance", nothing for the update function.

**Comment by kidroca** [comment]
Here's how we use it to rebuild when graphql data is fetched

```jsx
  const { data, loading: queryLoading, refetch } = useQuery(MY_QUERY, { variables }});
  const document = <MyPdfDocument data={data} />;
  const [ pdf, update ] = usePDF({ document });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(update, [data]);
  
  return (
    <>
       {loading && <Loader position="absolute" />}

       <ContextButton
          component="a"
          Icon={DownloadIcon}
          color="success"
          href={pdf.url}
          download="myPdfFile.pdf"
          disabled={queryLoading}
        />

        /* this is a custom PDF viewer */
       <PdfViewer url={pdf.url} />
    <>
  )
```

1. `data` is used in the Document
2. `data` is a dependency to `useEffect`
3. each time it changes it triggers the `update` function 

- note: `update` can't be put in the `useEffect` dependencies as it would cause a loop. It needs a `useCallback` here to fix this
https://github.com/diegomura/react-pdf/blob/f62f1499a6aa69960025bb6a2d266ce086ae60af/packages/renderer/src/dom.js#L67-L71

**Comment by redaben** [comment]
@kidroca you rock ! Thx a lot 🙏

**Comment by starInEcust** [comment]
@kidroca thanks for your example, but the url will be updated twice quickly.
Due to the rapid changes, there will be no problem downloading using the <a /> tag
```
useEffect(() => {
    if (!pdfInstance.loading && pdfData) {
      timer += 1;
      if (timer === 2) {
         window.open(pdfInstance.url);
      }
    }
  }, [pdfInstance, pdfData]);

```

**Comment by amiraiman** [comment]
@kidroca shouldn't the prop on the PdfViewer be src instead of url?
`<PdfViewer src={pdf.url} />`
