### ISSUE TITLE
Automatically covert urls to links

### ISSUE THREAD

**Issue by ACPK** [diegomura/react-pdf#1398]
What is the recommended way to automatically convert text to links. The document contains text coming in from the database with urls. As such, we'd need to convert each url to

`<Link wrap={true} src="https://website.com/" render={() => "www.website.com"} />`.

**Comment by diegomura** [comment]
@ACPK that's what you should do. Transform the text you get from the DB to the correct primitives. No need to use the `render` prop though. I don't recommend it. You can do [this](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a006491800d6302002760d801100776bb2f88107cc6cd08dcc6cd5a00a8614b1a78a928510c394c5f750e0f4e00513018043891043e1e6318252c111e1800591e3060000b1e488f2a007a6f5f774e52cd0add031aea72de01770aba0666567602006e32320031702859630c3e24680c633c090e00331e46241121002e1800720079084b1e11251d801a0e13606d9dc2a8280007084df2f2a5b1b93e681e2824606710231ca10728810ec725394006e00460033394009a007d4f001a4006a0036100003800ea20287c800aa4a3863191000d00270f00082f4d93dc963b322a8064350240fc41190e06000653e46105850c061c6c0498fc300b0e22854db45a681e3c25128f47c4f0801edb38401582eaaf566ac07c0010ba0a080ed9628da53546ab500091031890002f31b1df50eca2a98d305f940c4cad2bbd5882af461b60026000b1072861283d244483e1806ec0162618ce708d8d86ab7596d76072389cd9018b8730664001286078c02817068c3098b032f32a22150e82c395889ca000)
