### ISSUE TITLE
Styles not cascading?

### ISSUE THREAD

**Issue by jmjpro** [diegomura/react-pdf#140]
Use case: View element with child element
```
...
const styles = StyleSheet.create({
    header: {
      color: 'white',
      backgroundColor: semiBlackBackground,
    },

    reportName: {
      //color: 'white'
    },

<View style={styles.header}>
      <Text style={styles.reportName}>Behavioral Report</Text>
</View>
...
```
_expected_: Without `color:white` on the reportName, the text is visible and the PDF output is a black block with white text
_actual_: Without `color:white` on the reportName, the text is not visible and the PDF output is an all-black block

**Comment by diegomura** [comment]
Initial set of properties to do cascading styles:

- color
- font-family
- font-size
- font-style
- font-weight
- letter-spacing _(not implemented)_
- line-height _(not implemented)_
- text-align
- visibility _(not implemented)_
- word-spacing _(not implemented)_
