### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by GusMartins499** [diegomura/react-pdf#1407]
Hi guys,
how i can render a graph in my document ?

**Comment by aaronjedwards** [comment]
@GusMartins499 Version 2 now has support for drawing SVG elements which you should be able to use to achieve what you want. To quote the release [announcement](https://react-pdf.org/blog/announcing-react-pdf-v2):
> ## SVG Support
>
>React-pdf now ships with a set of new primitives to render SVG images! This has been on the backburner since the beginning of this project, postponed for several different reasons throughout the years for it being challenging to implement with the previous implementation.
>
>And this is HUGE. Having SVG support opens this library to a whole new world of possibilities. This doesn't just mean being able to render your own SVG (such as your company logo or similar), but also building integrations with pre-existing libraries that output SVG, such as the popular chart library recharts. As a future reference, just bear in mind that react-pdf does not take the same React SVG primitives but their own, so you will need to transform from one to the other. Should be as simple as cloning elements.

You can read more about the specifics of what is supported on the [documentation site](https://react-pdf.org/svg).

**Comment by GusMartins499** [comment]
Thanks @aaronjedwards ! I will read and study about

**Comment by diegomura** [comment]
Thanks @aaronjedwards for answering. Closing this now since it's the correct answer 😄
