### ISSUE TITLE
@react-pdf/renderer > react-reconciler@0.23.0" has incorrect peer dependency "react@^16.0.0

### ISSUE THREAD

**Issue by ACPK** [diegomura/react-pdf#1408]
When upgrading React using ```yarn add react@latest react-dom@latest```, we get:

```warning "@react-pdf/renderer > react-reconciler@0.23.0" has incorrect peer dependency "react@^16.0.0".```

**Comment by diegomura** [comment]
Related to https://github.com/diegomura/react-pdf/issues/1062 . React17 support it's a WIP due to inconsistencies for 16 version. Leaving that one open
