### ISSUE TITLE
(in Promise) Failed to excute 'fetch' on window: illegal invocation issue in latest Chrome 91 version 

### ISSUE THREAD

**Issue by Annshuk** [diegomura/react-pdf#1409]
**Describe the bug**
Font.js file having issue on chrome latest version (91+) and not able to download fonts and images

**typeError: (in Promise) FAiled to excute 'fetch' on window: illegal invocation**
font.js : 25

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to '...' chrome 
2. add react-pdf/rendere and downnload pdf
3. See error

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by Annshuk** [comment]
this is really big issue, as fetch calll is not working in chrme from font.js and image

**Comment by diegomura** [comment]
Has been incomplete for a lot of time. Closing
