### ISSUE TITLE
any idea on this error for running tests:

### ISSUE THREAD

**Issue by tzookb** [diegomura/react-pdf#141]
lerna info version 2.0.0-rc.5
lerna ERR! build:clean Errored while running script in '@react-pdf/core'
lerna ERR! execute Error: Command failed: npm run build:clean
lerna ERR! execute sh: rimraf: command not found
lerna ERR! execute
lerna ERR! execute npm ERR! Darwin 16.7.0

**Comment by jbovenschen** [comment]
Did you run `yarn run lerna bootstrap` before running the tests? It seems that there are packages missing in `@react-pdf/node` and `@react-pdf/core`

**Comment by diegomura** [comment]
I think `rimraf` is missing from devDependencies. I added it in one of the last PRs. Please pull the last code and try again

**Comment by tzookb** [comment]
Thanks guys, it works !

thought it will open a browser and not save the pdf.

do we have view in browser or only saving as pdf?
I noticed a comment somewhere its still in development

**Comment by diegomura** [comment]
Exactly. browser support is still under development. For the moment, I can only guarantee to work on Node, saving pdf's to the file system
