### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by GusMartins499** [diegomura/react-pdf#1410]
Hi guys, i'm trying to render a graph using Recharts lib, but, i not fluent english yet, so, maybe i don't understand all correctly. How i can import SVG container with react-pdf ?

`
import {
  Font,
  Document,
  Page,
  Text,
  Canvas,
  Image,
  View,
  StyleSheet,
  PDFViewer,
  Svg,
  Line,
} from '@react-pdf/renderer';
`

`
<Svg height="210" width="500">
            <Line
              x1="0"
              y1="0"
              x2="200"
              y2="200"
              strokeWidth={2}
              stroke="rgb(255,0,0)"
            />
          </Svg>
`

Link: https://react-pdf.org/repl?example=line

I have this error: 

![image](https://user-images.githubusercontent.com/43645525/126208792-dd2ab9aa-7d5b-43db-9981-ca83bac52188.png)

package.json : `"@react-pdf/renderer": "^2.0.16",`

**Comment by aaronjedwards** [comment]
@GusMartins499 Where are you experiencing this error? I see the line rendered as expected with the link you have posted to the react-pdf repl. Are you seeing the error in your own code base? If so and you can provide a link to an example repository, it will be easier to figure out where things are going wrong.

**Comment by GusMartins499** [comment]
@aaronjedwards  Im sorry bro, i don't know what i did, its work now.

![image](https://user-images.githubusercontent.com/43645525/126362352-39bb056a-abaa-4c7d-aeac-5e5411c5bac6.png)
