### ISSUE TITLE
React-pdf freezing page for long time. It's happen if file have more than 2-3 pages

### ISSUE THREAD

**Issue by BulavinaNk** [diegomura/react-pdf#1411]
**Describe the bug**
A react-pdf freezing page for a long time. It happens if the file has more than 2-3 pages. Will be great to have the opportunity to move the preparing file to a separate thread and don't block the main process. Likee it done for react=pdf library for viewer https://github.com/wojtekmaj/react-pdf  

**Expected behavior**
Move building pdf file to another thread and don't freeze the main process

**Desktop (please complete the following information):**
 version: "@react-pdf/renderer": "2.0.15",

**Comment by utegenovkamel** [comment]
@BulavinaNk че там как там решила свой вопрос?)

**Comment by diegomura** [comment]
Can you share a way of replicating it? Thanks!
