### ISSUE TITLE
PDFDownloadLink doesn't work

### ISSUE THREAD

**Issue by utegenovkamel** [diegomura/react-pdf#1421]
![image](https://user-images.githubusercontent.com/45562442/126748778-afebdbca-8f23-4774-b7e9-f2fde7fd79d6.png)
I also wrote this code in my project, it also does not work
and in other examples where PDFDownloadLink is used, the text 'loading' is returned and nothing else happens

**Comment by michaelmarziani** [comment]
I don't think you can compose text inside of ```<Page>``` directly. Try this code:

```jsx
const MyDoc = () => (
  <Document>
    <Page>
      <View>
        <Text>Text #1</Text>
      </View>
      <View>
        <Text>Text #2</Text>
      </View>
    </Page>
  </Document>
);
```

**Comment by diegomura** [comment]
That's correct! Thanks @michaelmarziani once again. I'll create a ticket to throw a more comprehensive error in these cases since it seems it a quite common one. Closing this as resolved
