### ISSUE TITLE
PDFViewer causing browser and app to crash

### ISSUE THREAD

**Issue by isheanesu** [diegomura/react-pdf#1423]
**Describe the bug**

When I add the PDFViewer to my app it causes it to crash and the browser to hang indefinitely. I am using the sample code provided in the Playground/REPL. If I use the Document alone it renders instantly in the browser, but the moment I wrap it inside the PDFViewer it crashes and the browser hangs without any warnings or error messages. 

I am using single-spa's create-single-spa and webpack. 

**To Reproduce**

1. Create a new single-spa project using create-single-spa
2. Install @react-pdf/renderer
3. Add React class component and include PDFViewer and sample react-pdf Document

**Expected behavior**

**Screenshots**

Webpack config:
![image](https://user-images.githubusercontent.com/19770786/126820625-7539ece0-5836-4fa9-82cd-22a501e498d6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome & Microsoft Edge
 - React-pdf version ^2.0.16
 - Webpack version: ^5.8.0

**Comment by michaelmarziani** [comment]
Please post your code to a sandbox so that I can take a look.
