### ISSUE TITLE
how to get pdf of render in react

### ISSUE THREAD

**Issue by bilal-abubaker** [diegomura/react-pdf#1429]
how can i download pdf of my rendered data which is a table ! please Help

  import React, { useEffect, useState } from "react";
  import { db } from "../Firebase";
  import TextField from "@material-ui/core/TextField";
  import StaticDateRangePicker from "@material-ui/lab/StaticDateRangePicker";
  import AdapterDateFns from "@material-ui/lab/AdapterDateFns";
  import LocalizationProvider from "@material-ui/lab/LocalizationProvider";
  import { Box } from "@material-ui/core";
  import { useParams } from "react-router-dom";
  import { Table } from 'react-bootstrap'; 
  import './AdminBookerExpense.css'
  import { Button } from "react-bootstrap";
  import Pdf from "react-to-pdf";
  import { PDFDownloadLink, Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

  function AdminBookerExpense(props) {
    const emailForCheck = localStorage.getItem('testing');

    console.log(emailForCheck)
    const [dates, setDates] = React.useState([new Date(), new Date()]);
    const [recordExpense, getRecordExpense] = React.useState([""]);
    var [getTest, test] = React.useState([""]);
    const { data } = useParams();
    const newData = data.split("+");
    console.log(getTest)
    console.log(props.tester)
    
    const styles = StyleSheet.create({
      page: {
        flexDirection: 'row',
        backgroundColor: '#E4E4E4'
      },
      section: {
        margin: 10,
        padding: 10,
        flexGrow: 1
      }
    });
    
    let email = newData[0];
    var lastDate = "Pick A Date"
    var Lmonth = ""
    var Lyear = ""
    const ref = React.createRef();
    const options = {
      orientation: 'landscape',
      unit: 'in',
      format: "[4,2]"
  };
    var filteringByEmail = [];
    filteringByEmail = recordExpense.filter((c) => c.emailId === emailForCheck);
    const resetTime = (dateIsoString) => {
      const date = new Date(dateIsoString);
      date.setHours(0);
      date.setMinutes(0);
      date.setSeconds(0);
      date.setMilliseconds(0);
      return date;
    };
    var arrayForDates = filteringByEmail.filter((e) => {
      const _startDate = new Date(resetTime(dates[0]));
      const _endDate = new Date(resetTime(dates[1]));
      const _creationDate = new Date(resetTime(e.CreatedAt));

      if (!dates[0] || !dates[1]) return false;

      console.log(_startDate === _creationDate);
      if (_startDate == _endDate) {
        return _startDate === _creationDate;
      }

      return _startDate <= _creationDate && _creationDate <= _endDate;
    });
    const firstDate = dates[0];
    const Fday =firstDate.getDate()
    const Fmonth =   firstDate.getMonth()+1
    const Fyear = firstDate.getFullYear()
    try {
      useEffect(async () => {
        await db
          .collection("recordsExpense")
          .onSnapshot((snapshot) =>
            getRecordExpense(snapshot.docs.map((doc) => doc.data()))
          );
      }, []);
    } catch (error) {
      console.log("not found");
      alert("not Found");
    }

    if (dates[1]==null){
      
      console.log("Pick a Date")

    
    }
    else{
      lastDate = dates[1].getDate()
        Lmonth = dates[1].getMonth()+1
        Lyear = dates[1].getFullYear()
    }
    console.log(lastDate)
    const Lday = lastDate

    console.log(filteringByEmail);
    console.log(arrayForDates)

    var accumulator1 = [];
    accumulator1 = arrayForDates.reduce(function (accumulator, currentValue) {
      return accumulator +Number( currentValue.records.total);
    }, 0);
    console.log(accumulator1);
    const MyDoc = () => (
      <Document >
        <Page size="A4" style={styles.page}>
          <View style={styles.section}>
            <Text>
              
              test
            
            

            </Text>
            
          </View>
         
        </Page>
      </Document>
    );
    
    return (
      <div>

        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <StaticDateRangePicker
            displayStaticWrapperAs="desktop"
            value={dates}
            onChange={(newValue) => {
              setDates(newValue);
            }}
            renderInput={(startProps, endProps) => (
              <React.Fragment>
                <TextField {...startProps} />
                <Box sx={{ mx: 2 }}> to </Box>
                <TextField {...endProps} />
              </React.Fragment>
            )}
          />
        </LocalizationProvider>
        {/* <Pdf targetRef={ref} style={{pageBreakAfter:"always"}} x={-105} y={5} size="A4" scale={1} filename="div-blue.pdf" >
          {({ toPdf }) => <Button className="btn-b" onClick={toPdf}>Generate Pdf</Button >}
        </Pdf> */}
        <div className="App">
      <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
      {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
    </PDFDownloadLink>
    </div>
        <div  style={{pageBreakAfter:"always"}}  ref={ref}>
          <>
          <h1 style={{textAlign:"center"}}>

  {`You Picked From ${Fday}-${Fmonth}-${Fyear}  To ${Lday}-${Lmonth}-${Lyear}`}

  </h1>
            { test = arrayForDates.map((item) => (
              <>
                <div style={{ display: "flex", marginBottom: 10 }}>
                <Table className="mid-b" striped bordered hover>
    <thead>
      <tr>
        
        
        <th>Area</th>
        <th>Fares</th> 
        <th>Kilometres</th>
        <th>LocalOutStation</th>
        <th>OsExtra</th>
        <th>Petrol</th>
        <th>total</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{item.records.area}</td>
        <td>{item.records.fares}</td> 
        <td>{item.records.km}</td>
        <td>{item.records.localOutstation}</td>
        <td>{item.records.osExtra}</td>
        <td>{item.records.petrol}</td>
        <td>{item.records.total}</td>

      
      </tr>
    
    
    </tbody>
  </Table>
                
                </div>
              </>
            
            
            )
            
            
            )}
      
            
  <h1 className="mid-flex-b"> Total = {accumulator1} </h1>

          </>
        </div>
      </div>
    );
  }

  export default AdminBookerExpense;

**Comment by letsandeepio** [comment]
Hey Bilal, it is not possible to reproduce this issue on my machine - can you please set up a code sandbox example - it might be possible to do what you are trying to do actually?

**Comment by bilal-abubaker** [comment]
bro i am just trying to do is. i want to print the specific data in jsx which is rendered !

**Comment by bilal-abubaker** [comment]
i want a button when i click it will start download the pdf file.... and i want in it the rendered content on screen like i printed the Hello World 200 times on screen and i want it with page breaks cause all the 200 hello World cant be in one page. Did you got my point now ?

**Comment by letsandeepio** [comment]
AFAIK It is not possible to use the in-page rendered JSX to pdf using react-pdf. You have to define JSX separately or the react pdf (see here: https://react-pdf.org/) - It is a little harder to get the on-page jsx to a pdf even using other libraries. Your best bet would be to convert your JSX to canvas element and then use canvas element inside pdf but that would not be the optimal solution.

**Comment by bilal-abubaker** [comment]
i am doing it with a library but its not printing more then 1 page !
