### ISSUE TITLE
SVG node of type 'x' is not currenty supported

### ISSUE THREAD

**Issue by GusMartins499** [diegomura/react-pdf#1430]
Hi guys, somebody can explain why this happening ?

My console:
![image](https://user-images.githubusercontent.com/43645525/127197050-44968bae-9edc-4a11-a2ac-6ee82b4daa58.png)

My document
```jsx
          <Svg height={500} width={300} viewBox="0 0 500 300">
            <Graph />
          </Svg>
```

My Graph:
```jsx
export const Graph = () => {
  return (
    <BarChart
      ref={currentChart}
      width={500}
      height={300}
      data={data}
      margin={{
        top: 5,
        right: 30,
        left: 20,
        bottom: 5,
      }}
    >
      <CartesianGrid />
      <XAxis dataKey="name" />
      <YAxis />
      <Legend />
      <Bar dataKey="pv" fill="#8884d8" />
      <Bar dataKey="uv" fill="#82ca9d" />
    </BarChart>
  );
};
```
I think that my function render a svg graph, or not ?
i searched into ref of graph, a found this, i think this is all my graph, its possible render this in my document ?
![image](https://user-images.githubusercontent.com/43645525/127198170-1e709cdb-2b95-4c88-930f-024723f6a03c.png)

My document:
the last page was to be the chart
![image](https://user-images.githubusercontent.com/43645525/127198999-6f71a56d-c730-4daf-b5ef-756a1740624d.png)

**Comment by diegomura** [comment]
You are trying to render React DOM primitives inside a react-pdf document. You have to use the primitives react-pdf provides (ex. `import { SVG } from '@react-pdf/renderer'`)

**Comment by GusMartins499** [comment]
> import { SVG } from '@react-pdf/renderer

I using svg from @react-pdf/renderer

```jsx
import {
  Font,
  Document,
  Page,
  Text,
  Canvas,
  View,
  StyleSheet,
  PDFViewer,
  Svg,
} from '@react-pdf/renderer';
```

**Comment by diegomura** [comment]
Yes, but all the other primitives should be as well `<G />` , `<Line />` and so on. Here's the docs: https://react-pdf.org/svg

**Comment by GusMartins499** [comment]
> Yes, but all the other primitives should be as well `<G />` , `<Line />` and so on. Here's the docs: https://react-pdf.org/svg

Ooh, i understant now, thanks bro
