### ISSUE TITLE
BlobProvider passes null url if it is inside conditional rendering

### ISSUE THREAD

**Issue by krzydrab** [diegomura/react-pdf#1433]
**Describe the bug**
When `BlobProvider` is in conditional rendering it stops returning url after it was hidden.

**To Reproduce**
Create simple react app, add react-pdf/renderer and change app.js to:
```js
import './App.css';
import * as React from "react";
import {
  BlobProvider,
  Document,
  Page,
  Text,
} from "@react-pdf/renderer";

const DocumentContent = ({ results }) => {
  return (
    <Document title="document">
      <Page size="A4">
        <Text>Counter:{results.counter}</Text>
      </Page>
    </Document>
  );
};

const DocumentOpenIcon = ({ document }) => {
  return (
    <BlobProvider document={document}>
      {({ error, url }) => {
          console.log(error, url);
          return url && (
            <a href={url} rel="noreferrer" target="_blank">
              Open the document
            </a>
          )
        }
      }
    </BlobProvider>
  );
};

function App() {
  const [results, setResults] = React.useState({ counter: 0 });
  const isEven = results.counter % 2 === 0;
  const document = <DocumentContent results={results}/>

  return (
    <div className="App">
      { isEven && <DocumentOpenIcon document={document}/> }
      <button onClick={() => setResults({ counter: results.counter + 1 })}>
        Increment
      </button>
    </div>
  );
}

export default App;

```

**Expected behavior**
It renders the link for every even number and we can see the url in the browser console.

**Current behavior**
For counter equal to 0 (at start) it renders properly
For counter equal to 1 `BlobProvider` is hidden
For counter equal to 2 `BlobProvider` passes `null` as `url` and no error is given

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 91
 - React-pdf: 2.0.17

**Comment by krzydrab** [comment]
Downgrading version to `2.0.16` solves the issues. I think it's related to https://github.com/diegomura/react-pdf/issues/1432.

**Comment by krzydrab** [comment]
It is caused by the commit: https://github.com/diegomura/react-pdf/commit/cb15f022fd45a033ba7eb55b6d9e150f5232bf66.

**Comment by diegomura** [comment]
Already reverted the PR https://github.com/diegomura/react-pdf/pull/1436 . I'll publish a new version today. Thanks!
