### ISSUE TITLE
Pdf is not show html parse data 

### ISSUE THREAD

**Issue by Jatinsecond** [diegomura/react-pdf#1434]
Not showing html parse data is there any other way to do it 
(using html-react-parser)
  <Document>
                <Page wrap>
                    <View>
                        <Text>Question ID</Text>
                        {this.state.Questions.map(item => (
                            <View>
                                <Text style={{ margin: '10px' }}>{item.question_assoc.id}</Text>
                                <Text>{parse(item.question_assoc.question_text)}</Text> // question_text =<p>uyduvf</p>
                            </View>
                        ))}
                    </View>
                </Page>
            </Document>

**Comment by letsandeepio** [comment]
Hi Jatin, the react-pdf will not render the JSX Elements that come out of the parser - you are using react-pdf inbuilt component <Text></Text> and it is actually expecting a string passed as child in order to be able to render it (instead of h1, h2, or other HTML elements that may get passed to it)
