### ISSUE TITLE
Question: how to  use annotations and attachments? 

### ISSUE THREAD

**Issue by ajitbohra** [diegomura/react-pdf#1443]
Unbale to find examples or docs on adding and annotations and attachments to PDF.

**Comment by diegomura** [comment]
Attachments are not currently supported. What annotations specifically you refer? There's a `Note` and `Link` component. Others are not supported either

**Comment by ajitbohra** [comment]
Thanks for the clarification was looking at this https://github.com/diegomura/react-pdf/commit/2a8152e66e02cf71406fb96e3c49642946a24be0

Wanted to attach/merge additional pdf.
Was not sure if it was just low-level implementation or also supported in rendered via components.

ended up using `react-pdf` for generating the main pdf and `pdf-lib` for injecting/merging other document to it.

closing this.
