### ISSUE TITLE
Can PDFViewer have a close button

### ISSUE THREAD

**Issue by rlgordey** [diegomura/react-pdf#1457]
I'm always frustrated because PDFViewer doesn't have a close button.

I open the "Frame" with a button click:
`
function handleInvoiceClick(e, invoice) {            
            e.preventDefault();
            console.log("Invoice: " + invoice)
            const pdf = <Fragment><PDFViewer width="1000" height="600" className="portal"><Invoice invoice={invoice} waitBeforeShow={500}/></PDFViewer></Fragment>;
            ReactDOM.render(pdf, document.getElementById('root'));
        }
`

If you just put a close button my problem would be solved

I have tried to get PDFViewer to open in a new browser tab, but I haven't been successful.

**Comment by rishFilet** [comment]
I found a workaround for this using the method `useClickAway` from the package `react-use` located [here](https://github.com/streamich/react-use/blob/master/docs/useClickAway.md)

This was my implementation:
Well first, the pdf opens with a button click like this under ShareButton which sets the showPdf prop to true on click:
```
export const TotalBar = ({ total, showPdf }) => {
  const [currTotal, setCurrTotal] = useState(0.0);

  return (
    <FormSectionContainer>
      <RowContainer>
        <TotalContainer>
          <TotalBarText>Total</TotalBarText>
          <TotalBarText>
            {" "}
            ${" "}
            <CountUp
              start={currTotal}
              end={total}
              duration={0.8}
              onEnd={() => setCurrTotal(total)}
              decimals={2}
              redraw={true}
            />
            / Visit
          </TotalBarText>
        </TotalContainer>
        <ShareButton
          color="secondary"
          startIcon={<ShareIcon />}
          variant="contained"
          onClick={() => showPdf(true)}
        >
          Share
        </ShareButton>
      </RowContainer>
    </FormSectionContainer>
  );
  ```

Then this passes the showPdf prop up to my main page:
```
export function Home() {
//Extra code omitted
  const [showPdf, setShowPdf] = useState(false);
 

  return (
    <MainLayout
      page="home"
      showPdf={showPdf}
      closeViewer={(showPdf) => setShowPdf(showPdf)}
    >
     // Extra code omitted
      <Offset />
      <FooterContainer>
        <OpacityContainer />
        <TotalBar
          total={convertTotaltoView(total)}
          showPdf={(showPdf) => setShowPdf(showPdf)}
        />
        <Feedback />
      </FooterContainer>
    </MainLayout>
  );
}
```

Then i send the showPdf prop up to my main layout. the reason for this is that i have a fixed container at the top layout container and need the pdf viewer to be on top of that container.

Now in the main layout container , i display the Pdfviewer component based on the showPdf value and then also set the showPdf via closeViewer which is then set by the pdfViewer component:
```
const MainLayout = ({ children, page, showPdf, closeViewer }) => {
  const ref = createRef();

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <ClientSideRendering>
        {page === "home" && <Banner />}
        {showPdf && (
          <QuotePdf ref={ref} showPdf={(boolVal) => closeViewer(boolVal)} />
        )}
       //Extra Code Omitted
      </ClientSideRendering>
    </ThemeProvider>
  );
};
```
Here is my pdf viewer file where it detects the click outside the viewer container:
```
export const QuotePdf = forwardRef((props, ref) => {
  useClickAway(ref, () => {
    props.showPdf(false);
  });

  return (
    <div ref={ref}>
      <PDFViewer style={styles.viewer}>
        <Document>
          <Page size="A4" style={styles.page}>
            <View style={styles.section}>
              <Text>Hello</Text>
            </View>
            <View style={styles.section}>
              <Text>World</Text>
            </View>
          </Page>
        </Document>
      </PDFViewer>
    </div>
  );
});
```
