### ISSUE TITLE
Images don't show

### ISSUE THREAD

**Issue by rlgordey** [diegomura/react-pdf#1458]
We store our images on a sql server as a byte array. I fetch them and I get a json string from the api. In react, I normally use the following to display a fetched image:

`<img src={ "data:image/png;base64," + data.image} id="logoImg" />`

I have tried the following without success:
`<Image style={styles.logo} src={{ data: "image/png;base64," + data.image}} />`
`<Image style={styles.logo} src={{ "data:image/png;base64," + data.image}} />`
`<Image style={styles.logo} src={{ data: data.image, format: 'png' }} />`

The pdf logo image is always blank with no errors.

**Desktop:**
 - OS: Windows
 - Browser Firefox
 - React-pdf@renderer version 6.14.14

**Comment by mikey0000** [comment]
It expects a url and fetches, doesn't support that AFAIK

**Comment by rlgordey** [comment]
I rechecked the web site: [...as well as base64 encoded image strings](https://react-pdf.org/components#image).

I changed my code to this:

`               const buff = new Buffer(data.image, 'base64');
                let pdf = (
                    <Fragment>
                        <PDFViewer width="1000" height="600" className="portal">
                            <Invoice invoice={invoice} buff={buff} />
                        </PDFViewer>
                    </Fragment>
                );`

And this:

`<Image style={styles.logo} src={{ data: buff, format: 'jpg' }} />`

Now it works.
