### ISSUE TITLE
Link wrapped in Text doesn't work anymore

### ISSUE THREAD

**Issue by tinkatinka** [diegomura/react-pdf#1469]
**Describe the bug**
Since the update of @react-pdf/layout to v2.0.19 Link components wrapped in Text elements don't work anymore

**To Reproduce**
See [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00400a0110188c0bc30050128d03e4c05030c00f0223002b80b60299852e471a5c02180e6b532cb2402ab4007a366bc0240061004eb4d945a004c60077009650005a900326ac006b1811a7054008935428001c2002e00f48f65b605002d0dc500cc01d08348739ae2bbb97af89239ea1ae1fbc589f23a0888f127b171a5479151d03131600370100129cbba2121fac9822ad348609254c23ae11411000)

**Expected behavior**
Links wrapped in text should still work

**Screenshots**
Not necessary, I think

**Desktop (please complete the following information):**
 - OS: MacOS v11.4
 - Browser: Safari v14.1.1
 - React-pdf version v2.0.19

**Comment by oliviermtl** [comment]
Same issue
