### ISSUE TITLE
Warning: Ignoring invalid character "33" in hex string

### ISSUE THREAD

**Issue by hello-cw** [diegomura/react-pdf#147]
![n 1 gnedgbd1clu 2gvr4p](https://user-images.githubusercontent.com/22360683/30469444-eafed59a-9a22-11e7-9a92-47e8580c2c73.png)
How to solve it?

**Comment by diegomura** [comment]
Can you give a bit more detail of what's happening to you? 
You can't expect us to understand what's going on based just on that image 😄

**Comment by hello-cw** [comment]
I want to display PDF on the page, but it's garbled when it comes to Chinese.

**Comment by diegomura** [comment]
Can you provide the code needed to replicate this? Thanks!
