### ISSUE TITLE
Error: Font family not registered: Inter. Please register it calling Font.register() method.

### ISSUE THREAD

**Issue by yusokolsky** [diegomura/react-pdf#1480]
since 2.0.18 version i have this error, on 2.0.17 version evrething was ok
`Error: Font family not registered: Inter. Please register it calling Font.register() method`
how i`m using Font.register()
```

 Font.register({
      family: 'Inter',
      fonts: [
        {
          fontStyle: 'normal',
          fontWeight: 400,
          format: 'woff',
          src: `${hostPath}/assets/fonts/Inter400.woff`
        }
      ]
    })
console.log(ReactPDF.Font.getRegisteredFonts());
    Font.register({
      family: 'Inter-Bold',
      fonts: [
        {
          src: `${hostPath}/assets/fonts/Inter600.woff`
        }
      ]
    })
```
![image](https://user-images.githubusercontent.com/15705470/131870771-781d50f3-bfd0-4be9-9b26-eca115cd8dfd.png)

**Comment by diegomura** [comment]
Can you provide a more complete snippet I can use to replicate this error? Just checked and nothing changed related to font-loading between those versions. There were some changes about how font-weight get's processed. Maybe there's a bug there? I'll need more details

**Comment by yusokolsky** [comment]
> Can you provide a more complete snippet I can use to replicate this error? Just checked and nothing changed related to font-loading between those versions. There were some changes about how font-weight get's processed. Maybe there's a bug there? I'll need more details

It works like this: I have a private repository for pdf generation, and a backend server where my private repository is connected.
Locally in the repository everything works as before, but when I use it on the server, such an error occurs, although as you can see in the server console I get a registered font.

Now I have rolled back to version 17 and everything works fine

i`m calling on server like this: 
```
export default async function (options: Props): Promise<Buffer> {
    const res = await reactPdf.renderToStream(react.createElement(ExportPdfFileComponent, options) as any);
    return streamToBuffer(res);
}
```

and registring like this: 

```
export const ExportPdfFileComponent = (props) => {
Font.register({
      family: 'Inter',
      fonts: [
        {
          fontStyle: 'normal',
          fontWeight: 400,
          format: 'woff',
          src: `C:/assets/fonts/Inter400.woff`
        }
      ]
    })
  return (
    <React.Fragment>
      <ExamplePDF  props={props}  />
    </React.Fragment>
  )

```


using like this: 

fonts.js: 
`export const FONT_FAMILY_NORMAL = { fontFamily: 'Inter' }`

inside one of component : 
```
const styles = StyleSheet.create({
  page: {
    ...FONT_FAMILY_NORMAL,
    fontWeight: 400,
    fontSize: '8px',
    flexDirection: 'column',
    padding: '28px',
    paddingBottom: '33px',
    lineHeight: '1.4',
    color: '#3a3a39'
  }
})
```

**Comment by yusokolsky** [comment]
at 2.0.20 is no longer reproduced
