### ISSUE TITLE
File Object as Image source

### ISSUE THREAD

**Issue by SimonBellucci-Adeliom** [diegomura/react-pdf#1481]
Hello, is it possible to add a file object which comes from an `<input type="file"/>` as `<Image/>` source ? If so how would you do it ?

I tried to do : `<Image src={{uri: URL.createObjectURL(myFile)}} />` or even `<Image src={{data: myFile}} />` but the image doesn't appear on the generated PDF (the variable myFile is a file object).

This is not really a bug I think, maybe I misunderstood something.

**Comment by kidroca** [comment]
I think it should work with a URL create from a `File` object 

Maybe just pass it as 

```js
<Image src={URL.createObjectURL(myFile)} />
```

and not as an object with `uri`

**Comment by SimonBellucci-Adeliom** [comment]
Thank you @kidroca, it worked like a charm ! In fact my issue was related to another piece of code which isn't related to this library. It now works perfectly, thanks again !
