### ISSUE TITLE
textDecoration isn't flattened/merged correctly

### ISSUE THREAD

**Issue by danomatic** [diegomura/react-pdf#1489]
**Describe the bug**
When using an array of styles, or nested tags with `textDecoration`, the values should be merged 

**To Reproduce**
This works:
```jsx
      <Text style={{ textDecoration: 'underline line-through' }}>underline AND strikethrough</Text>
```

But these don't:
```jsx
      <Text style={[{ textDecoration: 'underline' }, { textDecoration: 'line-through' }]}>underline AND strikethrough</Text>
      <Text style={{ textDecoration: 'underline' }}>
        <Text style={{ textDecoration: 'line-through' }}>
          underline AND strikethrough
        </Text>
      </Text>
```

REPL link:
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5400a8614b1a004f003619b006f45313249a19400271e50938005c300390230004c316d948c161b7602d1400165a4023e2f8cc00bebf88cd2dad6cb0010400e46861a0b49001ac315ddd3c5ca801e9c5248585a8b2a4a0e4151401b454d4a035b575f4c08d4c2cac1c307d7c006861ca252b344074f50c4d9b9cdc3cbd5a017402829b426123a3621293475233f27384c5ba630be494bbd57bfb6bea6642ed5a023972f27665f79555baaafa6b078d8792c7bcfdaf6f84e766bcca2bb38a25bea91bae5d6dd4d8893270e846578021c864e80c662b1d8040037190c800317014000745a0c1f090d02b1e1141c00198f1184859349ea007908001dc78b273318da1c0816980f517140a0000708019d2e9466922064be3406ac03268118e9083a440bcfe799d20037002300199d2004d003ea8800d20035001b080001c00751009a004600557305b18b6800680138786130992a58ce31917cf8c240094303c60140b8342245258c13c15110a874161d2c464d00000

REPL Using HTML and CSS:
https://www.w3schools.com/code/tryit.asp?filename=GU8R1DYNZXS2

**Expected behavior**
Text should be both underline AND strikethrough

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - React-pdf version Latest

**Comment by jeetiss** [comment]
hello @danomatic
thanks for detailed issue!

I create PR with fix for case with inherited `textDecoration`  👇🏻

```jsx
<Text style={{ textDecoration: 'underline' }}>
  <Text style={{ textDecoration: 'line-through' }}>
    underline AND strikethrough
  </Text>
</Text>
```

and I think that your first example works properly now 👇🏻

```jsx
<Text style={[{ textDecoration: 'underline' }, { textDecoration: 'line-through' }]}>
  underline AND strikethrough
</Text>
```

if we will merge `textDecoration` in this case too,  it will breaks `textDecoration` disabling, and you can't disable it for links for example.

**Comment by jeetiss** [comment]
@diegomura @danomatic do you know any other css properties that works in browser the same way as `textDecoration`? let fix them too.

**Comment by danomatic** [comment]
@jeetiss thanks for the quick response! this is a very weird CSS property. I'm not I know others like it. I thought it could be disabled with `text-decoration: none`, but I was doing some testing and it didn't quite work. But perhaps I have a bug in my CSS:

https://www.w3schools.com/code/tryit.asp?filename=GU0PGQOHK49G

**Comment by Pavek** [comment]
@danomatic MDN [documents](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration) this behavior pretty well:

> Text decorations are drawn across descendant text elements. This means that if an element specifies a text decoration, then a child element **can't remove the decoration**. 

Looks like [the standard means it](https://drafts.csswg.org/css-text-decor/#valdef-text-decoration-line-none):

> none
Neither produces **nor inhibits** text decoration.
