### ISSUE TITLE
Internals or other private api for tools, libraries, etc

### ISSUE THREAD

**Issue by jeetiss** [diegomura/react-pdf#1496]
**react-pdf dev tools**

I made dev tools for `@react-pdf/renderer` for fun, it looks like [👇🏻 this 👇🏻](https://react-pdf-experiments.vercel.app/)

<details>
  <summary>screenshot</summary>
  <img width="1440" alt="Снимок экрана 2021-09-10 в 10 35 04" src="https://user-images.githubusercontent.com/6726016/132817588-1aae1f63-e851-4b3b-a47a-a16960cb8ece.png">
</details>

it shows parsed and computed styles, pages and `react-prd`s rendering primitives after all pagination magic. it more helpful than `debug` prop, because it interactive ✨. I wanna make it more library like, and I have problem — `@react-pdf/renderer` doesn't provide `layout` info in any way, so maybe you have any ideas how it should work.

**Describe the solution you'd like**
best solution here is dev-tool extension for chrome, but it requires alot of work and integration with [react-pdf](https://github.com/wojtekmaj/react-pdf) that usually used for rendering. I think that now will be enough some thing like reacts internal `__DO_NOT_USE_OR_YOU_WILL_BE_FIRED` or maybe something else.

**How it works now**
I patch `@react-pdf/renderer` with `patch-package` library, yeaas this is hack, but it works

<details>
  <summary>and here the change</summary>

```diff
diff --git a/node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js b/node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
index 52d4b40..bc8a9fe 100644
--- a/node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
+++ b/node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
@@ -219,7 +219,9 @@ var pdf = function pdf(initialValue) {
 
             case 6:
               layout = _context.sent;
-              return _context.abrupt("return", renderPDF(ctx, layout));
+              var result = renderPDF(ctx, layout);
+              result.__INTERNAL_LAYOUT = layout
+              return _context.abrupt("return", result);
 
             case 8:
             case "end":
@@ -264,6 +266,7 @@ var pdf = function pdf(initialValue) {
                     callOnRender({
                       blob: blob
                     });
+                    blob.__SECRET_LAYOUT_DO_NOT_USE_OR_YOU_WILL_BE_FIRED = instance.__INTERNAL_LAYOUT
                     resolve(blob);
                   } catch (error) {
                     reject(error);
```

</details>

here the source: https://github.com/jeetiss/react-pdf-experiments

**Comment by diegomura** [comment]
Omg. This is awesome! I truly think this can be very useful. Right now I always log the layout, and that's only because I know the internals to do it. How can we do to make it available? Ideally it would be a plugin that hooks to the rendered layout (I saw you did it with the `__SECRET_LAYOUT_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` 😂 ). I think this also raises a need of having better internal APIs to support this sort of initiatives. Since layout and render are independent right now, we should layout once and use that as input for any render process but also any plugin such as this (specially thinking about the SVG viewer as well)

**Comment by sagar-tts** [comment]
Hi @jeetiss 
Create PR for only expose layout please review.
