### ISSUE TITLE
(CTRL+p )  or download the rendered page with puppeteer 

### ISSUE THREAD

**Issue by johnico** [diegomura/react-pdf#1499]
i have a rendered pdf . now I would like to download the page with puppeter 

if I use ctrl +p in my browser i see a blank page.
I dont want to use file . 
is it possible to use ctrl + p also after the page is rendered as pdf ?

**Comment by diegomura** [comment]
Not sure I understood. But how is this a react-pdf issue? Seems to me that's most like a puppeteer question. Also, why using puppeteer when you can use the API this lib provides to create documents using Node?

**Comment by William-ST** [comment]
It's not an error but I would like to know if there is a way to download the created pdf
