### ISSUE TITLE
Custom Page Size

### ISSUE THREAD

**Issue by anthonnyc2** [diegomura/react-pdf#1504]
I'm trying to set my own page size, which in reality I want to use half of a letter page. So, in theory, is the same width but the height is exactly half as the letter size height.

When I do this for some reason when I print the page it changes the landscape mode, even when I set the orientation property to "portrait".

I'm not sure if I'm doing something wrong. 

This is my code:
`
<Document>
<Page size={[700, 396]} wrap={true} orientation="portrait" style={pageStyle}>
    <Header></Header>
    <SomeContent></SomeContent>
    <Footer></Footer>
</Page>
<Document>
`

**Comment by diegomura** [comment]
What do you mean when you print the page? Is that using a physical printer or you mean render the document on screen?

**Comment by anthonnyc2** [comment]
I generate the pdf and then I must print it. Look this is an example.
[ORDEN-831 (1).pdf](https://github.com/diegomura/react-pdf/files/7163087/ORDEN-831.1.pdf)

**Comment by diegomura** [comment]
The PDF is being rendered with the dimensions you passed. Then what happens after printing it is not really inside the scope of this project, so I cannot help

**Comment by AdelineDs** [comment]
Hello,

I have the same problem. Despite a "portrait" orientation, the generated PDF is indicated as being in landscape.

The problem comes from generating the PDF and making it impossible to print...

Thanks for your help

`<Page
      orientation={'portrait'}
      size={[107.82, 71.88]}
      wrap={false}
>`
