### ISSUE TITLE
My Linter is complaining that Page, View and Document are not defined in the @react-pdf/renderer namespace

### ISSUE THREAD

**Issue by bobber205** [diegomura/react-pdf#1505]
![image](https://user-images.githubusercontent.com/5841107/133689430-e7437a01-6054-48d5-a5bf-afa44924c4f2.png)

Seeing this when trying to use the download link component (PDFDownloadLink)

```
warning.js:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

This definitely seems like my linter (eslint) is correct and that Page, View etc are NOT exported in renderer. Where should I import it from?

**Comment by diegomura** [comment]
What version are you using? Either way, `Page`, `View`, etc are definitely being exported so not sure what the cause of this issue is 😅

**Comment by bobber205** [comment]
v2. Ok good to know.

**Comment by carlobeltrame** [comment]
This and more issues are also reported in #1317. React-pdf does not have named exports currently. What you can do is use the default export instead:
```js
import pdf from '@react-pdf/renderer'
const { Page, View } = pdf
```
