### ISSUE TITLE
Is it possible to render without iframe (PDFViewer)?

### ISSUE THREAD

**Issue by smac89** [diegomura/react-pdf#1506]
I just noticed the repl site (https://react-pdf.org/repl) and I see that it does not seem to be using the PDFViewer aka no iframe, and I am wondering how this was done.

I tried doing the same by attempting to render the following document:

```jsx
<Document
    title={title}
    language={language}
>
    <Page
        size={documentSize}
        wrap={false}>
        <View>
            <Box display="flex"
                flexDirection="row"
                justifyContent="center"
                alignItems='stretch'
                p={2}>
                <Box display="flex"
                    flexDirection="column"
                    justifyContent="center"
                    alignItems="flex-start">
                    <div>
                        <Image
                            src={Logo}
                            cache={false} />
                        <Text
                            wrap={false}>
                            <View>
                                <Typography variant="h4">
                                    Some text here
                                </Typography>
                            </View>
                        </Text>
                    </div>
                </Box>
            </Box>
        </View>
    </Page>
</Document>
```

Just above the code, I am importing `Logo` using:
```ts
import Logo from 'assets/images/logo.png';
```

If I try to render the above document, this is what I see in the HTML:
```html
<document title="My title here" language="en-CA">
  <page>
    <view>
      <div class="MuiBox-root MuiBox-root-177">
        <div class="MuiBox-root MuiBox-root-179">
          <div>
            <image src="/static/media/logo.629a8342.png"></image>
            <text>
              <view>
                <h4 class="MuiTypography-root MuiTypography-h4">Some text here</h4>
              </view>
            </text>
          </div>
        </div>
      </div>
    </view>
  </page>
</document>
```

This looks wrong because it is literally rendering unknown html tags (`view`, `text`, `image`, etc). However, the dom produced by the `repl` site does not seem to have this problem.

When the above code is shown in the browser, this is what I see:

![Screen Shot 2021-09-16 at 22 17 14](https://user-images.githubusercontent.com/8305511/133723383-734eccf8-1c3e-4fee-88a0-a1fcbdd9bab7.png)

The image doesn't load, which makes sense because there is no such element as `<image>`, so the browser does not attempt to load the image.

What am I doing wrong? Is there a compilation process needed before the render can occur? How do I accomplish this in the browser?

**Comment by kidroca** [comment]
The repl creates PDFs using the renderer, but doesn't display the created files with the viewer. I think it uses pdfjs to render the created PDF files 

So the repl works differently it creates a file and then renders it with something. It does not render the tree you've posted.

The repl project is also available on github is you want to see exactly how it works

**Comment by smac89** [comment]
@kidroca yes thank you!
I actually went back and looked at the code used in the repl and saw that it was transpiling the pdf and then displaying it. I was initially using their method, then I discovered `usePDF` like you mentioned :smile: .

**Comment by diegomura** [comment]
It is. `usePDF` returns the document blob. You can use that to render the document where you want, but it's not something build inside this lib

**Comment by Somyadeep-Chowdhury** [comment]
with usePDF, how can we display the pdf content without iframe. Can you share any code snippets with example?

**Comment by NiallEccles** [comment]
For anyone looking to do the same, Issue #477 mentions how it's done. 

You can find the source code for the REPL PDFViewer here: 

https://github.com/diegomura/react-pdf-site/blob/master/src/components/Repl/PDFViewer.js
