### ISSUE TITLE
Blurred view in Mobile but downloaded pdf is clear

### ISSUE THREAD

**Issue by jackvik** [diegomura/react-pdf#1511]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by jackvik** [comment]
When rendering pdf using a blob in react-pdf, the view is blurred and not clear. But on zooming it's clear. and on downloading pdf also, it's crisp and clear. I tried renderMode="svg" also but not working.

**Comment by diegomura** [comment]
Wrong repo. I think you refer to https://github.com/wojtekmaj/react-pdf

**Comment by jackvik** [comment]
can your react-pdf solve the issue I am pointing to?
