### ISSUE TITLE
React-PDF seems to want everything to be one big component?

### ISSUE THREAD

**Issue by bobber205** [diegomura/react-pdf#1513]
Having a pretty bad time trying to get react-pdf in our large project off the ground. I've read some issues about the Yoga layout engine having issues with rendering components with `&&` 

That lead me down a pretty deep rabbit hole where I discovered the following: It seems that sending `PDFDownloadLink` or `PDFViewer` 's document parameter with a component that has another component inside that implements a render() method causes errors like this.

![image](https://user-images.githubusercontent.com/5841107/133840564-b5ad93ce-73ff-4fd1-8c5e-d80098ed1b1f.png)

Very strange huh?

Check this out.

*** 
This works

```jsx
    const justSomeText = function () {
      return (
        <Provider store={store}>
          <Document>
            <Page size='A4'>
              <View>
                <div>
                  <Text>Hello there! again</Text>
                </div>
              </View>
            </Page>
          </Document>
        </Provider>
      )
    }
///other code here

 <PDFDownloadLink document={justText} fileName='somename.pdf'>
          {({ blob, url, loading, error }) =>
            loading ? 'Loading document...' : 'Download now!'
          }
        </PDFDownloadLink>

```

This DOES NOT (gets the error above)

```jsx
//near top of the file
class TestTitle extends Component {
  constructor (props) {
    super(props)
    this.state = {title: 'Alex State Title Test'}
  }

  render () {
    return <div>{this.state.title}</div>
  }
}

const justSomeText = function () {
      return (
        <Provider store={store}>
          <Document>
            <Page size='A4'>
              <View>
                <div>
                  <Text>Hello there! again</Text>
                  <TestTitle />
                </div>
              </View>
            </Page>
          </Document>
        </Provider>
      )
    }

 <PDFDownloadLink document={justText} fileName='somename.pdf'>
          {({ blob, url, loading, error }) =>
            loading ? 'Loading document...' : 'Download now!'
          }
        </PDFDownloadLink>
```

Note how the ONLY change was adding in another component to the rendering process.

Is this a known issue?

**Comment by richcsmith** [comment]
Even though your first example works, I ran into tons of issues using non-ReactPDF primitives inside of the `<Document>` component, so I suggest replacing your `<div>`s with `<View>` components to start with. It's also suspicious that the `PDFDownloadLink` works in your first example even though it's wrapped in a `<Provider>`.

In my experience, the rendering library is very specific and brittle, so while it will be a little painful, you will have to try to work with it and perform some trial and error in order to accomplish what you want. You may have already come across this, but I found [another Github issue](https://github.com/diegomura/react-pdf/issues/924) related to this that might be helpful.

**Comment by richcsmith** [comment]
I was messing around in the React-PDF REPL, and [I got your code to work by replacing the divs with `Text` elements](https://react-pdf.org/repl?code=3187b0760ce02e00402a05369c096500d82605e1802804a1c03e1806f00a0619449601b4a353006860812950c10174718009410043605001d00570e0194a08a808f00720082980078c798ab374cf091415040371518009d394ab606001e449aa31324c7805f4701e85db85178505303a0884040c1a98081400058215a2323316022b82180009947098a4803088002d8003b8166c25352d341594b88815be1955881944110d753b1499525e1b475765b5024a0404b41e80879a40170c3aac425251b43c1a4ab07530658d8e7ae13918f5adbd93807b84d4ccd284a7a60fbf86605ed0485d6c1a995940800cca460710a1c0f86e99da836281d81c78286f51c001110300a4252ab1111bd27000144400732c04050002f04361d4001615363710ca4400d45008003bbd3195ce71bd880009043a1d020181ac6c0042181124428301f9ae38ee4a4b869182f9395c86638627144b258c062c3ab15b8bf0b3d91aee6f809c4cb69b7ca8f4662c0ef06410cefb356f9f1c88018aa2d96061489b2001959401ac60d934462aad8322fcca5e180025098001c889315488294b2d984048cad9005d228be6f6f4c878320c00046c2fadb0ece836307b2b2c25b092ed1697888d86c657191daecc000fccb50c8043e398d3aaa1265ca8604b1500683b3ec8c1626cf14a82b558f88e9cd6bf66e3be1b0047b1147cb88f17e8921db2836d5fcd5c4730508000):

```js
const TestTitle = () => {
  const [title, setTitle] = React.useState('Alex State Title Test');
  return <Text>{title}</Text>
}

class AnotherTestTitle extends React.Component {
  constructor (props) {
    super(props)
    this.state = {title: 'Another Test Title'}
  }

  render () {
    return <Text>{this.state.title}</Text>
  }
}

const App = function () {
  return (
    <Document>
      <Page size='A4'>
        <View>
          <Text>Hello there! again</Text>
          <TestTitle />
          <AnotherTestTitle />
        </View>
      </Page>
    </Document>
  )
}

ReactPDF.render(<App />);

```

**Comment by bobber205** [comment]
I have a HUGE project that generates reports -- I cannot afford, at last atm, to go through and update everything like you did, though I really appreciate it. We also aren't using hooks FWIW -- does a hookless version work too?

**Comment by richcsmith** [comment]
>We also aren't using hooks FWIW -- does a hookless version work too?

Yup, I left your class-based component in the example to illustrate that it work, too. Feel free to play around in the REPL and see for yourself.

**Comment by bobber205** [comment]
So you think there's little chance I can give React-PDF a big chunk of my react app wrapped in a document and maybe a few <page><view> combos and just have it work?

**Comment by diegomura** [comment]
@bobber205 if that big chunk has HTML elements (like `divs`) you cannot. Same as if you would try to render react native elements in the web.

**Comment by bobber205** [comment]
So react-PDF can only render stuff like <Document> and <Page> And <Text>? Not custom components?

**Comment by richcsmith** [comment]
>So react-PDF can only render stuff like <Document> and <Page> And <Text>? Not custom components?

That's correct—you'd have to recreate your components using React-PDF primitives such as `<View>` and `<Text>`.

**Comment by bobber205** [comment]
What a bummer! Thanks for the follow up.
