### ISSUE TITLE
SVG transform crashes react-pdf 2.0.19

### ISSUE THREAD

**Issue by SpudNyk** [diegomura/react-pdf#1514]
**Describe the bug**
Using any transform will crash react-pdf 2.0.19

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Use an svg transform in a document.
Example Svg code:
```jsx
<Svg width="600" height="300">
    <G style={{ transform: 'translate(0, 50)' }}>
        <Rect fill="red" width="200" height="50" />
    </G>
</Svg>;
```
2. React-pdf will crash with e.trim() error

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**
The transform to work and not crash

**Desktop (please complete the following information):**
 - OS: Tested on MacOS, Windows
 - Browser Tested in: Chrome, Edge(Chrome)
 - React-pdf: 2.0.19

**Comment by SpudNyk** [comment]
[REPL Example](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634ad00650dbe10a42570ec0022003600067beb984b05f3281b806647ebf600483f95000e2c331a4824505b274208e19a30005cd7487425a983c3dc003430002b3dc08d7553a90e9a404009430312712044221bbf894cf50a5dcc3700130fc5e183787daeb8eb86406e90c90305d40c89cf8a2aa0012518fc0c313382363298e44839409548aca0416cc01b865d5f288064008e75068011964b5789f1ae8a8162a74fb5069946aad904010f2329402aa2ca0f878f1002dd401022100c1a5f09a9619150569345a305018094486012000cfd5210c030b53b367b3d19b0ad1c3c4608020d1f305c78223e34668b26d4d490f54c2acb0a98e9747aceacbeca5436549564987d1123c9c0028b5410d511020f83c5b2f79aad01f747858a683084d1b008118f27f0c14f3073520ecd1e88cc941be6163af43b9e5118086eb46ca18461e268dcd2c0362403650d5a65c5e46d9b72cfb5acb7168c0000bd5a160601e1a06a4c45b0402c5ac0ddd70edb6058107dd227a1436a91c169401800b75ce0b4c667a4665906000154c0568401a5932c09b16c604600043880602d980568408eda4db0c07bcb10809b788b33cdb7092c48934f6e8cc03c9628c2482c408bdb64428ce1944f91ac5ac310ecc45608b2c39a442c0bb11488008e6c002fea9e226ccf241af268780011fac0b8102855c8929420ac016cbcb93c06f51848257173213306000b6c1d8b76f45e688ef0cc780e3e7159fc681e0fe258ae9570cb861e18f0ec9a0d9960dd302c5a4910d0b8b40e595778b728dd5a16824e70cc24c24f4d860402480b5804168c42531003b460900806b2c52ca512081b0b5612f08000ce95a33a5e700a11b3eaf9b24a1a6624090e8db48ed9c53c38dd0c04838e87ba49526065d5a6ac64a5946952eef5b66f23fc5602882c41e18400bd829e03b102af68c690c1d73bbc6b72b9272b1247aa1ac50f82d36ac8086372968d0ac4b1ac3430ec58080709e0eee5928e01a89626b180a033cb9f1b5a2039f1b0a10e200315b1b6d17b742d25adcc0259a03c23b06d9f662e6cb3b32e89604730b0aecc2c62c3ccf788c4141736a9fc6cc28b3be8c3c374f3eccfd8eda8a62a6f08d640001b8603e0a1727ac5b0d75b33702dab058a9d4da4b4238c40ef7877b6cd375933dcc17ef42563ac2f160cf42eb714f6a4226068d103302bbc0b18c3a6fac5acc39b106daa411c3b058477fecb326617aa9bc219b1a02c101e8ccc601e5f905802008e5cb1a036c14ac062c23284248eafdd0cb6991864699ce3a73a9687c10fb168e54edcb9e283f89ef42c6a8edd525e935cbe807caf7572168c1816185a0e6cb4070658030aa61e2b60a13660d24a00025cac6bc57454b360c69eda0bc465cc2c90ab42de92d873f4674e38c10aa190539f62ce4fcf38bcae5756079041733b04cc21b4d410a8de9166730f59608b63da884a130b092f5c804d90ecf40902d668c75c9868758a225c4af6158e14401102bacf809b340c07619a1200bc6b4c7a8b5c6b610e8af216db141b38281f998382d6168c2b01f13024a0733530e65b98588d741ac0278ac22c258b3188dec0e55a227446985a0aa66b05b4c036d6441630a82062ad985833e20e059719f0271ad093278f9a725a29888e62ac0b08f1e0651af0371aab631e8665cc2247f0f40923d114bae23aff8204090ec675cf142250d14289e520956ca126e110da2fd96e6923640c61d7fa58cc41d814998420286668620360e612200cb0a64e508841839945a080468f419e9b82b1190594d0dc621289895970590549ecf285226a592603c852a02c71a212c6a010082d2f14e1ab38898032d961f8ce854c8e3522d8f083b12f5994125a3cb1564d08abc43f6212780817e212582a4260ad259f04928494d3cbcd210584f683ccfc4f2f9a742dc77d6c04d059da4d33910cc38cc43e3506ea334562c32965fc2de0c03a38c9c92ea2e49a314c70a19f0aac7004d030b7e3dc8b4ba8e51e8fc5b984029e610401c654c24ba0752b9ca9839980435d519988917a16bf78248c0b424c4ac3948a46296d4883c050869160b45f945207598c219cd5b5cc14fbd42c1924bf8c54eeb606b37a284a4c4c79e240303aa1ec8e5ea320ac2cf67dc443f0b4c7792c96376a51b9338160a8d8822663023c5981397ba1341fb651c51d2b02c27ca1dcb327444d8847a3002555ddfb7c50b63cd9803b754a553056331dfebb70760d8a5b83a871b049cf068e021ae82718c528643032f87004da5c8164e9ce49cb12cf5e0072a3283a79cdf8970994d970802ef67e2e550836a6603a8886b2584b012f23e492ec04d44d23cff94208a4ca728f333aac02e1caac608210874e88634df0bd46d7fc926a75bd5b476b4600082f2da00e64c0321948dab303f8c218d51a314200e628c6cc690800e2000e427908d68df80b3bc8c27ac5ca586452e58b41e8004260b3a36d5588addf67b71df212096278510cae91a3e0e8ceea2f1984bb3a08f1123c1a698cd99581cc0fa3bc30772774b952159ca1881242c582689e67edbf9d32b9858562ff5b0b4d718d9b925dbf17f6e32fbc228c85bef7ce6bb9a6ca2db9b5422afddb4dfa8510fb3737a072a327f81ed4ce8acf0d72dc497533a307df20c42610eacb4135d3655f531e905f51f3b82bc133a54d859ca619e2d571ca1031b94ae7d16eb94ef046b10c893e4b7110acd3d95d1cbcc13002cb35ab10e68356e3c55c8c144995663b41241d87ee93d723223bf96916a3307281674ca52102213be901639ff6b9d18ae94626d3306ca876fa080361bd3a9585e77fad9a56c300e71ee7347983011d0f5573ae4dc922404c50e15d31a3d04c121dac39178a6cdaa142be00007e581a139e28def4205122b18e5fd0296f48b36987d062e56f011063bf98d80ecd2912aa23b031408dca03a4748124c16841ce511db3058158d663e2e24b12bd939b55ad5e1b854b04adca9b074b4f95e60a8b1af1a4c564d9a9a4ca7df224148ab7d6ae5c5093b9adbd45bf1bd02dfa6d82c47619301ebe72d0661624132eaa9be1ee7a1979ff3be9330b3a7e1ce7f5b8e615f9ca02bba64ccb13fa50b1d941c10c4f18a34e9f66d305198fdb5997aaf398ed80d211e1e87b88589beb8ae78ed829b1ff3faa781c9606d1e85aa1a175ced8e71ec1c81bbf41ba228c43c634e280e42e722e488660f8951bcc588e05da9f51bd80138ac9982309153103117a654c7b7fab64d94ca1003b2e94b0124c410824954d8012289e69bcfe26fdad332e74577917e85bdfb1189a5987b4fc158df8bb384481a3a1beab38c1a2f6e76aa56cec4e2a0e5dc3a28ea2ea8eea7c0d6d78e2c76027c3cc2fa6581c4000328e4398674a56a9855808c4b2f66516d8a4f6c6690418e322232a2a0444b25b8ddca625b477654285e4d0d763605d048094a6f22528fa94a1fa2a432a66c8268d854242ac8022a7ec044358d5458803c75a33474c998100fd23b04fc804b58da264674cbfaac0d81cb007c4ea2243b2bdcad06a645676c6aeb01382d601d86e2a0c2415c6a24b782b6a140e112475811444a300c14e5665864a6411448bc6341d853eef85cc7f4e8070ed12cf48e1b34a9cafc0dcceacb8f14ade1e0ede0706de842ee8bde720de8be8e501800e085c3c0000d67bac186181184f6d28b18f1842c7c2f66d96f2c63a9744d88d86aea8af12ad251194c1e64fc8942c0f92ad807a65c0d06ba1de6deb28f281d24429386a68511d27a8068f31268b78dd8180ac8b20f108940e87384e89919bab31dbaa423387ba00012148f524a634287a8b4fe0be1622eecd8c43cdb40f88b01b8cf89b8acaff8ea19846fcaea1411809dc98268aeccb769e2044e8a80ea241caa5679c4f67814d8afc58c53ed7650cc025acd107f4891b5219a454498b60cf8a844ec78c7e4e6cf4a7dc28e604df210c689a2cfc17da0c24fe760f9a65e52c180684c0166a24a97a0224c275a9f1da1f20ff27c9c6a1e0cc0f504328a11808b6a29cd4650308d107601c40009a8b2a18e46d508297943d8881b607582b6e6e3c41fa0f478addc161c7ac146ae3c49987d8a04e660eac0c2b67281143c404467a86e37ab626cc314772af4b344d8d14e22034cea3944d0000529182fe76a2f84e297291eee10b4984b1a7c19366664e205c978a48a223c424cd42d34974f127289e656c5fc4129d4cf80ee5d29ea1990802449f1eb8b21678b59db8c4974cffad964b0f94ad055822040c4d0d04a006d2f9c6d11929e634c1b49ec73428e198beeea89964e4d9231c2208a0784bd1ed49a27340c0309afc558d982322ac64e2821feb64b94f2c1c16a41fc454c29184a062c6ed02e42182c02e4574d49ff4a0e1396caba68012444825004e26826098c1d929801029a18e9058498220952ffa404f44a560d8eb6024e5ced629475a684cf8858804d543c00b28e010cc669248d67f1a98cc0d219c1d69c9ea0c299e8e539fa24faa5e4b03d4e00edaa1ae341804527a2fae7608a6eaed6e35e2f43600a6db26d6244299ff6d503727c0649a9ef780b2e828dc6ae4f6f858eeeeee118d1ab21b8c9942e1d82569d080ccc582ca785fa7ae8fa4a4c3056900450940c38993c87272af52c89b493301d2f126602a5b60bd1a98eb83c46741543548b440593af726b6a9c07a7e83e85609b84be7598f2784f10d81baa82e2e4e82b6919aacacbef40bd26ae911ad0b6a4697d2f15ff20129ec8c9fa98242999b8b2578486ee8aea8f7c58cc2c014674044de15b4498b124d0911b589b4752349824b414f6885615600ca4a49d5053e47999a234a0216419672950575e0e6b9c600154e5e5821242f82e47a55d05c17497742328049c14ca92a5803019562c0b6183127ecd091cc01b32d182a5306b22729d042f815a81c74c20e35476ac2aff99680001c1d80583961cc8b0352454d2491272af36b8c5b09b8dd56ae496a6ef12a9ec045d98a6724fe0c7e19a65e9842410b91ccd007f47815d96841b56567fcbd2bbe6de2381316915913de938fde83e1e02a927ed71fa4d4c912df99fc8668f517cdb0824e56ebce650dec543b5234e9860d9399f8cc07862067e227e7188002804000fd29ca9a0b6959165d7878d964e56170f781243f1404c94539eca234482eb82450802844acd6152cad00d8354f2cf66b8680a71abda97166cf5c220c860fe4a588493cd3ca9c580d78404894144e9a23469210c03208cd15402d6a70acd1b01db6985af24d02e9174b42c9de753c0000fc718f86d76026ea51e69106660c01ca1d8a5d7c47f8586ee2da6889f6d298a0c838ad005866001465840cdd162c71433084434d9f8960664474de80d27605ed01933ccc654231c65d87e576180204a6cc166a408cf14a3d738014285384bb207a53dc990145e18e4ef10d2ea571681992c0b90b6220fda55660ab44e44625358b9c0ed831985edd9442a4985f86419956204b42d7cb1dad092d41260cf22724cb0c0a6d67064a62dd2955d90a13c64d8e98619a3afa5960c241c2f2ca4aba9b149b433050539457471ac883643d496d00a5585eda65b4ef2ad50a313d8edd1d8bb83d0a03bcd8daa22b582959d65c179110dac2820f12f43c0a68d1d8d9906c42d5f5b96a84192dcde8c9b8ffa3cca448b0d18676e00a22234c18bf1cce9ec6d0e00ff8220a91428f820715de5ba9e82cd7ba6a9b01a988ed6aeffa53e50d1a6b85da19e135231ea54f14aad340ec2fc3cacd600c41d20b04f631e1c2758f8d864984f141987422204a0b60309b6df6d8da1232a457d6841145a4874efe7389987c0be574108cfc4e55ff43a25d05cd7652206a49534aaa24b1a7c4a7603689d574975d9c5ccc06b465c6004311bdc8f55304191c400085000f21105003e4ca45ccfe2f41dbd6ee2f12c0c2a50881a67c5c1e0c1f23d0ae2f405a5d069b9330e00d12024c9d8ca78ce79cedd116ed00084d230803022d83d849e0e695c2200e2583d6a6f246c300323e8c799bf2014614f7c80e1e46f4b2ac74b613b25a4526ee3a78c16f24fe01bce635a074d1910cd871d91ccdbba1d8e814b0c249f61f37f4be31cda362e28ed8eef216da5d98de40a566aad933e60a9d04a79634091806c560635a6c23aa3cd4c530e0499616ab73ed07d5984549fe2cc098933c7a69dcbf8ff423c77c998b1a580058fe03967b82abbb655464459e9849f4ee37762692ea9f1a1a11d1b8fea9b87234e38ba31a71abd21c45c02204f33c066c6743cb14486372d00466463223c3d80bafcdf346bc42b359a356ae0be2e40c0d468b4da681bfec244d21a342ae1801c43e007a8dcb8ab162a4dd919add5714db42a15cd5729b5ceac615eb26afd5f3487ef3556e479d50ecc1809e172a13a59233569aeca98212ce4eb159f817de44c5869b19b3f5f0b8ac59d3dd25426ed067c447cb74992f4a218f2c796b269f8916e64c99c3a9521e51035840be824bd810280ebfeb8188467475854266ecb63d5d9c1f6d86e3118b79058b4cdc717631d8c182e2c4171336ef0b1995698f84e4fda9062c440cc5a63c2635a54f58e915b1e04f67b2f9c07c67b8caa2c483b6058cb781ccb014d55a5ab878c38c04bf7dc2a6009898078582808caa543dc9fe5b0518a726234e0a8358066494c1c480303ceaacdcc5a5985d39f808a679f553143c022dd95845827c452a54ac9fe5c0a83d18e81a246a4fda588f9bedcfda96a10ca9830c46123208b5b8ee49e2e16355a4110cc789c8d6e7062445bc6440730db7cbe3cd7ee8d266266bc1335daaf2c8bee5e9b53c47bcec34633831443942890a21981f67f8c61c8d5e90c4de4984fbe96bca4f127847cc96270296e1aae7e69ad08b64c16df82c9ba2c5408e8c58e95b4cba1fc761aaaf9466070a71b9a22e223c0c068c7662dcd25697d84cc695c0d7c8c728e5c3fd9beaed6190aa6299a00ec20002095331c093ac18720e923ecc09985a5454d56cedd5825c0588a441695a588d496f8b2d26a54e219ca311dda6637f5ed434e9d827fcfb858ce2785e14b3b66dc9ec866434c029b7245576a4355e17bc4584ca5bc00a249c95f3454f48e691a462018ea3b3641c4813b587fa4bb40c5033cdc01a925ca4a30f77f1a6df67244d1774aa8b940e916384fb460938014020ac64c02720e0f0c52c920780120a3444f24f4c9c2c505bc0020124aa0440d80a407801d8000060002412084f180c4fe787600e01903007cf0cf4d84cf660aa05cf8a80400e0ce0280ae0300fb168bd2fee09907400c0f21ec004001c64064032c263b20fe0ea6a3cb6054f1c0f43d48420718000e4133100c104d84a0f6fefeba8c000efef0500f10100f08190190b08ac07207c0402650c00b20bf2190268b582efc931901b09689f01902a9000fada0000d20006ab7020000d000ea2001b0f209c44a09f08c069f0001a0009c3c0f86f865385008e0f6f640acf06f640d2d050aa838030047063047096080e51f5106881201c08a02a0718e3f9a067d998894da0200f107189f0d88853c9bf3f7c0a26e80ad6718b706bf87073f1ae671cf48434d82bf07f940aa0efe7e8620d3f870c1f50050a284180718ac80002cebffdef862322530ef2a7a0577783fc4c632c58e0880ede300477b3bd5deadf2bfbbf9fb8f837bfa6811fecff57f8c012d0ac82ffbec07fe0b03003ffd30cb602006680dacea630036fca00bbf1803bfd3101c06bf8700f22b7f3404cfd380280a400bfce3080d75f89038281c0cc07003580a00dde0402a01f1f377ad026fefb02406701b81780f405f0390126354047033fe8706ffaffd641f6f6f636111c04202204b02401600e107681eaa10058836645d4b009801d03280f3129057e0888c146cf8b24bb42200e065fda410e0b0009fc086e075707a031e0efe6b06721ac07603b053811416c0b404602b819e0f206503d90580fd00e02ffe9008005d80f419405000d1c1de21c0e29e8282102f21789c8c2166d30823c41de5cc3ac2ae1300190f086b00941720f5fa28028167815f8d033406204701400e30ed0ce03cb0f80ef01e86242a00c908d05a43081ebf2c84cc0721d8d7c87d91dbe86f7243440a005c01a00cb14de8064b795005386801ec00a1f5e6402000000)

**Comment by esdrasjnr** [comment]
It's weird behaviour. @SpudNyk to workaround your problem you can set the `transform` as a direct property of the `G` component:
```jsx
<Svg width="600" height="300">
    <G transform="translate(0, 50)">
        <Rect fill="red" width="200" height="50" />
    </G>
</Svg>;
```
Another important point: the `translate` function will only work with two arguments (in SVG purely, it [could also have only one argument](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#translate)). Anyway, I don't know if it's a bug itself.
