### ISSUE TITLE
Render to stream

### ISSUE THREAD

**Issue by rogierslag** [diegomura/react-pdf#152]
Internally react-pdf already uses readable streams to push the data into a file. For some use cases it might be beneficial to expose a regular NodeJS stream directly (instead of rendering to a file).

For our case, we are now writing to a file, reading it again and exporting it, then deleting the file. We could save a lot of overhead if `ReactPDF.render` had a `ReactPDF.renderStream` sister.

**Comment by diegomura** [comment]
I like the idea!  I think the API you define is fine. Do you think you can submit a PR about it? 
I would do it, but I didn't have much time lately
