### ISSUE TITLE
Function toBlob broken in 2.0.19

### ISSUE THREAD

**Issue by taipignas** [diegomura/react-pdf#1521]
.toBlob() broken after 2.0.19 update

TypeError: Cannot read property 'length' of undefined
    at getLineBreak (splitText.js:25)

TypeError: Cannot read property '0' of undefined
    at renderText (renderText.js:230)

I am using it in react project but for me toBlob is the easiest solution if i want to render on click while using functions for dynamic documents
const MyDoc = (var1,var2,...) => (
  <Document>
    <Page>
      // My document data
    </Page>
   <CustomPageComponent (props and logic with variables)/>
  </Document>
);

**Comment by Phrensoua** [comment]
Maybe same as my issue: https://github.com/diegomura/react-pdf/issues/1518, I'm surprised it is not coming up more. I'm doing a very basic implementation. It is blocking for me, I will probably downgrade....

**Comment by taipignas** [comment]
Yeah, looks like the same error.

https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e658212005e19b002200820059c4c68013c00d9880de8a5440074008c4001305017dda74e5401a920c01dde54656a0328395005478e955aa279546606c009c78001db15400cc789420304c38cd292daced82c223a363e34c92f3f3a8dc305160359d5c303cbc30b42142798030824ca801e88a4b720af2daad6cbbcd5afa6c06db780572dae8199959d80801b8c9974121605d1caa54706036549c002c3030a0b58082307930f15512617daa00b8616ef323c0a000c479189094159e0072003c8406c317d202003477333e89075250f00130712445428710c20ae8e28d090176014090e067b89404a26180b1b0ce1e882fa2680064309128192008ca1143c8404a243e8605e06801ac696623363e4f5469059eaf7c91c907c03bb2601c802b1dd25642322d969f0f9682e7c0466082370e3457eff20683c14a4854a2041601035550508411ead56bbd58da3e340ae486019c408c568415a20304435a00370e401995a004d003e9b800d216001b080001c0075100267400557d32718198006801387892490f8a091406ebf56455b41ec8e080ecf61843b1d4ee74bb5c157a433cb61f57d3c2c07c3708142cf64f263552bc82e977c0010ba0a011e7b48000c3ba49ee90cb965b39e00764bed32837e5c009595aae78739f529d528624a0150e7331fd2809c110306780026690af4c04a491f93e0c02051a5609a684ee083be1b451104e34753b4a10098078040a0038403945e5c23e283445fd60c438a28050e55d0981014c3cd1c2cc460782094d3008f2804f460cf17cc8e74101d180d03e8f0318e837f42caf21244dbc58abcf09f8fe423ed08548981c8a42d5055282d344dd218d6098983d5042ee0b338b4281000ac106809048814013387d208a04dc24198080005a0fc231e0c0533c8f0bf8272ac9806cdbc2c26989600625fdb73b9d2b0000095a2440f972f55cf192cca948e1e1193a3528831cbb304e1344f1324b83aaa03d8f73b8de2587e2af0a568a04f80b802802a57a804000e4981d09a30338509632418952478cf0203e4a88c102ca19ab53d5562ee3d024d3c6064c7a9805407c605ba826fcd55badcd4206be3b091af931a7889a3029a381d4f5258c80fd2e224b81a13e6345806af02a110541d02c15a621f520000

**Comment by diegomura** [comment]
No longer failing in latest versions
