### ISSUE TITLE
Add `gap` property to StyleSheet API

### ISSUE THREAD

**Issue by JuanM04** [diegomura/react-pdf#1522]
**Is your feature request related to a problem? Please describe.**
When generating dynamic content (like tables), [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) provides a simple way of creating spaces between elements inside a flexbox without necessity of doing weird things with margins and widths.

**Describe the solution you'd like**
Maybe something like `gap`, `gapVertical` and `gapHorizontal`.

**Comment by jeetiss** [comment]
`@react-pdf` uses yoga layout under hood and should be implemented in yoga first

Upvote this issue if you agree. https://github.com/facebook/yoga/issues/812

**Comment by process0** [comment]
There seems to finally be activity on the PR that implements gap for yoga https://github.com/facebook/yoga/pull/1116

**Comment by axel7083** [comment]
Since the PR is still pending, here is a solution I found which work fine: [flex-gap-in-unsupported-browsers](https://nosleepjavascript.com/flex-gap-in-unsupported-browsers/)

**Comment by ajayvikas** [comment]
Seems it has been implemented in yoga.

**Comment by Sheharyar566** [comment]
Doesn't seem to be working for me

**Comment by RNm-dove** [comment]
In my case, `gap` not works, but `columnGap` works.
