### ISSUE TITLE
Render props issue

### ISSUE THREAD

**Issue by ncoderslab** [diegomura/react-pdf#1527]
**Describe the bug**
When using render props it is not working as it is supposed to behave, for some cases, it is working fine but in some cases, it does not produce the expected result.

**To Reproduce**
[Play ground/REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e65803b80271e001dda74e5400a8614b184b00261987600de7834c31fc3003926008cd401a1851d0f0036bc04418017c8b65278394ca000c00906bd01234653612718007a187f2b285b7b0c08276f4f4e02708033540c6548f654ca2a0035240c4118253055752d1d40c3133567577702ce0f2f2f62d2f2e8004f1b0c4d1d631e60006b3e6110042a802e180072256545e727494eaeb90562004945c61800372408246341982430185b1b5d7d0800422a089db636a93792b2cdce821b5d279549bc129b379d018cc563b008006e3200094306328170680031001d255aa782a22150e82c0458808b210000)

**Expected behavior**
In both cases, it should show the text, but it does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/11809012/135636631-74a34e28-c634-48a1-a94f-6ddff82a608d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome, edge
 - React-pdf version 2.0.19

**Comment by diegomura** [comment]
Closing duplicate
