### ISSUE TITLE
Create a new package for predefined vector icons for react-pdf

### ISSUE THREAD

**Issue by joseDaKing** [diegomura/react-pdf#1528]
**Is your feature request related to a problem? Please describe.**
Currently, there are not any predefined vector components for react-pdf

**Describe the solution you'd like**
The solution is to create predefined vector icons that can easily change size and color dynamically for react-pdf, the library would be equivalent to react-native-vector-icons (for react-native) and react-icons (for web)

**Describe alternatives you've considered**
The alternative is copy-pasting the raw SVG myself and creating the components myself

**Comment by diegomura** [comment]
I like the idea but I don't think it should be included inside this project's scope (the same way `react-native-vector-icons` is not part of `react-native`). It's a nice idea for a third-party package though. Would be cool to see it in the future
