### ISSUE TITLE
How to load data from a file?

### ISSUE THREAD

**Issue by AmirHussain93** [diegomura/react-pdf#1531]
I don't see the option to load data from a file or url

Could you please share an example? or let me know if this is not available.

Documentation Doesn't say anything about how to load data from a file or url

**Comment by diegomura** [comment]
You don't see it because it's not supported 😄 

Repeated #735

**Comment by dhwaj1902** [comment]
> @diegomura Yeah I **figured it out!** after researching on it for a day.

Hi, @AmirHussain93 can you please share the way to do that?
