### ISSUE TITLE
npm shows v1 as new major version

### ISSUE THREAD

**Issue by fkocovski** [diegomura/react-pdf#1532]
**Describe the bug**

`npm outdated` lists v1.6.17 as the latest version even if the actual latest v2.0.20 is installed

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Run `npm outdated`
2. See results

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

Since v2 is the latest version, npm should not be listing v1 as the latest 1

**Screenshots**

![Screenshot 2021-10-06 at 11 02 36](https://user-images.githubusercontent.com/9000611/136173062-705ced9e-606d-46dc-b20f-eaca86eda5ba.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - React-pdf version v2.0.20

**Comment by jeetiss** [comment]
this happen because of `v1 release` with default tag

@diegomura this npm commands should help to fix this tag problem

```
npm dist-tag rm @react-pdf/renderer latest
npm dist-tag add @react-pdf/renderer@2.0.20 latest
```
here the docs about `dist-tag` operation
https://docs.npmjs.com/cli/v7/commands/npm-dist-tag
