### ISSUE TITLE
Should `updateInstance` have an argument?

### ISSUE THREAD

**Issue by SNikhill** [diegomura/react-pdf#1537]
# Description

If I want to update my PDF instance then, I need to send an argument to update it with something. 
Like, a whole new document.

```js
const [instance, updateInstance] = usePdf({
 document: defaultDocument
});

/* SOME OPERATION THAT LEADS TO A FULLY NEW PDF */
updateInstance({
 document: FULLY_NEW_DOCUMENT
})
```
But, this doesn't work. `updateInstance` doesn't seem to accept an argument. (I have linked the code below)
 
https://github.com/diegomura/react-pdf/blob/bef5d6e39ee877fb0ca6957652984dda09e1cb71/packages/renderer/src/dom/usePDF.js#L66-L71

![image](https://user-images.githubusercontent.com/51415616/136399940-d75a8793-329d-4ce5-b792-41459dc32371.png)

**Comment by dandresfg** [comment]
You need to try something like:


``` javascript
const [instance, updateInstance] = usePdf({ document:  <Document data={data} /> });

updateInstance() // This does not receive any argument, it just make another pdf file.
```
