### ISSUE TITLE
is it possible to generate a pdf from inputfields?

### ISSUE THREAD

**Issue by lindamacdonald** [diegomura/react-pdf#1542]
Hey there :)
I am nor sure if this is a feature request or already possible. Is it possible to generate a downloadable pdf from inputfields in a react form?
if not it would be a wonderful feature :) I havent seen any examples of this other than html

**Comment by diegomura** [comment]
Indeed. The generated PDF can have data coming from any source, wether it is a react form, API call, static content, etc
