### ISSUE TITLE
Hyperlink to jump in between pages

### ISSUE THREAD

**Issue by Warkanlock** [diegomura/react-pdf#1543]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a link that you can click and go to a specific section of the document (location? page number?)

I don't know if exists any workaround so far to tackle this using the library, I would like to know if there is one, but also It could be nice to have built-in inside the tool

Regards

**Comment by Warkanlock** [comment]
> This is already built-in, no workaround needed:
> 
> ```js
> <Text id="anchor">I want to jump here.</Text>
> ```
> 
> generates an anchor. You can create a link to it using
> 
> ```js
> <Link src="#anchor">Go there</Link>
> ```

Awesome! Maybe adding it to the documentation?

**Comment by diegomura** [comment]
Keeping it open until I can add this to the docs. Thanks
