### ISSUE TITLE
SVG use tag

### ISSUE THREAD

**Issue by bbloomf** [diegomura/react-pdf#1545]
**Is your feature request related to a problem? Please describe.**
SVG use tag is not implemented

**Describe the solution you'd like**
Are there any plans to implement it?

**Describe alternatives you've considered**
If I could get access to the pdfkit document, I might be able to use this library instead: https://www.npmjs.com/package/svg-to-pdfkit to handle rendering the SVG into the pdf, but it doesn't look like the Canvas component gives enough low-level access for that package to be able to do all of its magic, but I have used that package in the past, and it does handle defs and use tags.

**Comment by diegomura** [comment]
Fixed
