### ISSUE TITLE
Build error: nbind.node is not a valid Win32 application

### ISSUE THREAD

**Issue by gusdewa** [diegomura/react-pdf#155]
Hi, 

I have followed the steps to run the example:
```
git clone https://github.com/diegomura/react-pdf.git
cd react-pdf
yarn install
```
Then I start the example with `yarn example -- fractals`

However, I get an error `react-pdf\packages\react-pdf\bin\8\nbind.node is not a valid Win32 application\`.

I am using Node v8.5.0 x64 in Windows. Do you happen to have any suggestions how to solve the build error? Thanks.

**Comment by diegomura** [comment]
Seems related to #151 .
Thanks for reporting it. I was aware of this, but unfortunately I didn't have time to review it yet.
I'm closing this issue for the other one 😄

**Comment by gusdewa** [comment]
Hi @diegomura , OK no problem. Hopefully, it will get fixed very soon 👍
