### ISSUE TITLE
backgroundColor with rgba() renders black

### ISSUE THREAD

**Issue by Simon-44** [diegomura/react-pdf#1554]
Hello,

**Describe the bug**
`<View />` with a `backgroundColor: rgba(15,200,155,0.5)` renders a black background.

**To Reproduce**
I don't know how to reproduce, it seems to work [here](https://react-pdf.org/repl?code=3187b0760ce02e004026260c0bc300500a06300f00451015c05b014cc2803e2db5c005010c0735260804b00bd4e4022010400b2f6ab568e006aed480773650027801b1e01bd54c504a40027005c300390c8016eca294300686002306c0035931d21098380184436fd867533d9a0023002b15801300031455987854401d28402535b6058007943f12bb131801a1b039058eba7103007b214c0033144c002f936898b8800aa936650032a930143b380c0031304e003d174f4d1894d4ac9b7614e30b1b54c1300929750a403706060012a903941d1e0018a24eb91c290e9a023001c6100000)

**Screenshots**
![Capture d’écran 2021-10-21 à 12 30 26](https://user-images.githubusercontent.com/59820603/138260656-334eac5d-3d25-4961-9598-360e7e335b05.png)

Thanks

**Comment by diegomura** [comment]
Seems to work for me too. What react-pdf version are you using?

**Comment by Simon-44** [comment]
Wow it seems I was using the 1.6.17, I wonder why it's an old version, I installed it a few weeks ago! It's working now in 2.0.21 *facepalm*

**Comment by jeetiss** [comment]
thats why https://github.com/diegomura/react-pdf/issues/1532

**Comment by Simon-44** [comment]
Oh thanks for the explanation.
