### ISSUE TITLE
The page becomes unresponsive while generating a pdf from an array with a large dataset

### ISSUE THREAD

**Issue by reetamtaj1408** [diegomura/react-pdf#1558]
Currently I am using an onclick functionality to generate and download a large pdf while passing an array to the document. While the array consists 40-50 elements (dictionaries), the pdf works okay and it generates as expected. But for a large number of record in an array (>150), the webpage becomes unresponsive and ultimately after waiting for a some time its get downloaded. For an array that has records more than 500, it takes a long time and the pages becomes unresponsive for hundreds of times. In the meantime the webpage becomes unresponsive multiple times and I have to manually keep clicking "Wait".
I tried to same with pdfDpwnlodLink, and it is taking forever to get the data ready while loading the page. Could anyone please suggest what might be a workaround for this issue?

Using the below snippet for on click.
```
<DropdownItem
            onClick={async () => {
              const doc =  await pdf((
                          <PdfDoc
                          data={filteredData} />)).toBlob(); 
                           saveAs(doc, "example.pdf");
            }}
          >
```
Please find the below snippet (similar structure to what I am using but mine has a 15 to 20 fields per element of an array what I am putting inside the pdf as well) for PdfDoc
```
function PdfDoc(props) {
  return (
    <Document>
      <Page>
        {props.data
          ? props.data.map((a, index) => {
              return (
                <View key={index}>
                  <Text>{a.id}</Text>
                  <Text>{a.name}</Text>
                  <Text>{a.color}</Text>
                </View>
              );
            })
          : ""}
      </Page>
    </Document>
  );
}
```
@diegomura could you provide any suggestion here?

**Comment by gwalshington** [comment]
I'm experiencing this as well with trying to create and preview large pdfs with /renderer. If there's more than about 100 pages, it takes to long it crashes the browser.

**Comment by KMJ-007** [comment]
i am also facing a similar issue!

any update on this ?

**Comment by carlobeltrame** [comment]
Web workers are the solution. Have you tried those?

**Comment by KMJ-007** [comment]
just tried it!

takes time but it works

https://x.com/KaranJanthe/status/1710288494772334673?s=20

**Comment by carlobeltrame** [comment]
Great! In case you want to help out, could you share how you got web workers working so quickly, for others who have the same problem and find this issue? My own [setup](https://github.com/ecamp/ecamp3/blob/devel/frontend/src/components/print/print-client/generatePdf.js) uses Vue instead of React and Vite instead of Webpack, so it isn't really helpful for the average react-pdf user.

**Comment by KMJ-007** [comment]
sure why not 

code is open source here

https://github.com/KMJ-007/react-pdf-webworker

i learned about it from blog

**Comment by naveenApplikation** [comment]
worker sample for download the pdf please ?
