### ISSUE TITLE
SVG extract from library(tree-graph-react) to used as base64 image src in pdf...?

### ISSUE THREAD

**Issue by Waseem-javed** [diegomura/react-pdf#1561]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by jeetiss** [comment]
Hi @Waseem-javed 
Please, provide more information and fill the issue template, and then feel free to reopen the issue
