### ISSUE TITLE
How to deal with non-English language line breaks

### ISSUE THREAD

**Issue by hayoung0Lee** [diegomura/react-pdf#1568]
Hi, I want to share how I handled line-breaking issues related to Korean. 
It could be helpful to anyone who is using react-pdf with languages other than English. 
And I'd like to get some feedback if it is the proper way to handle issues. 

## Issue
![image](https://user-images.githubusercontent.com/70381940/139658170-2140367a-c0ec-4eeb-94e0-b5adcc324a81.png)

![image](https://user-images.githubusercontent.com/70381940/139658185-94d43156-317d-481d-b76b-669150b51db8.png)

The issue was that because it is not English, syllables are not calculated properly. And also, even when it is calculated well, Korean doesn't usually use hyphens to connect words when there is a line break. (Maybe it is just me)

Anyway, how I solved this issue was to split every word into pieces and add empty character after every piece. 

```javascript
const hyphenationCallback = (word: string) => {
  // Return word syllables in an array
  const splittedWord = word.split('');
  const result = [] as string[];
  for (const l of splittedWord) {
    result.push(l, '');
  }
  return result;
};

Font.registerHyphenationCallback(hyphenationCallback);
```

I am wondering if there is an option I can give to disable hyphenation other than returning `const defaultHyphenationEngine = word => [word];`?
 

## Solved
![image](https://user-images.githubusercontent.com/70381940/139658745-8bf03240-b611-4588-a6a6-52e4d7d4eb4f.png)

![image](https://user-images.githubusercontent.com/70381940/139658772-b99578ac-6346-4452-9465-28e969b461da.png)

**Comment by diegomura** [comment]
Thanks @hayoung0Lee ! Very helpful data :) I'm closing this issue since they are for tracking remaining things to do or bugs, but will appear in any future search for people in the same situation

**Comment by hayoung0Lee** [comment]
Thanks @diegomura !
