### ISSUE TITLE
How to save file server side

### ISSUE THREAD

**Issue by MrEremenko** [diegomura/react-pdf#1569]
**Describe the bug**
How can I use this on the server?
I've tried the repo provided in #1471, but still gives the same issue.
I tried both of these solutions:

https://react-pdf.org/node:
```
const MyDocument = () => (
  <Document>
    <Page>
      <Text>React-pdf</Text>
    </Page>
  </Document>
);

await renderToFile(<MyDocument />, `${__dirname}/my-doc.pdf`);
```

https://react-pdf.org/:
```
import ReactPDF from '@react-pdf/renderer';

ReactPDF.render(<MyDocument />, `${__dirname}/example.pdf`);
```

This is the error I am getting:
```
  <Document>
  ^

SyntaxError: Unexpected token '<'
```
**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
Run the code above

**Expected behavior**
It should save it to a file

**Desktop (please complete the following information):**
 - OS: Windows
 - @react-pdf/renderer: ^2.0.20

**Comment by diegomura** [comment]
That's not an issue of this library. You are not transforming JSX syntax. You should use https://babeljs.io/docs/en/babel-plugin-syntax-jsx
