### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hmz22** [diegomura/react-pdf#1571]
Hi Dear;
When use this library and using Arabic or Persian language direction problem,
Please add RTL support for text and style direction: "rtl"

![](https://user-images.githubusercontent.com/37986642/124525801-42b28600-de09-11eb-9945-b6717f58686e.png)

**Comment by askariacc** [comment]
Hi @hmz22 
How did you get the text in the right Unicode with this library?
I get something like:
![image](https://user-images.githubusercontent.com/54035524/142046572-50a69f1c-c267-4363-b0a6-a20832a2f812.png)

**Comment by askariacc** [comment]
> 
> 
> Hi @hmz22 How did you get the text in the right Unicode with this library? I got something like: ![image](https://user-images.githubusercontent.com/54035524/142046572-50a69f1c-c267-4363-b0a6-a20832a2f812.png)

Its worked!
Just by adding  ``` format: "truetype" ``` in font registration section. and giving it to Page element in StyleSheet section.

```
Font.register({
	family: "iranyekan",
	format: "truetype",
	src: iranyekanwebregularfanum,
	fontStyle: "normal", fontWeight: "normal",
});
```
then: 
```
const styles = StyleSheet.create({
	page: {
		fontFamily: "iranyekan"
	}
});
```

**Comment by sadam-hussien** [comment]
when pdf downloaded the arabic shown as a numbers and squares
what is the problem

**Comment by kassah-mahmoud** [comment]
Hi @hmz22, did you find a workaround for this issue?

**Comment by kassah-mahmoud** [comment]
![image](https://user-images.githubusercontent.com/75623572/154229859-46a43f5c-5a81-4476-ac73-cd344a4e3e99.png)
Having the same issue here

**Comment by ItaiPendler** [comment]
Any updates?
has anyone found a solution?

**Comment by X3rom-S** [comment]
> Any updates? has anyone found a solution?

Hi, I found a way
Test the code below, it might work for you too

`
const [splitedText, setSplitedText] = useState([])
useEffect(()=>{
   const _splitedText = text.split(" ");
   setSplitedText(_splitedText)
},[])
`
store the list of words in the array
now we need styles to show the all word correctly inside a <View> tag
`
const styles = StyleSheet.create({
  flexRowReverse: {
      flexDirection: "row-reverse"
   },
   flexWrap: {
      flexWrap: "wrap"
    },
    ml1: {
       marginLeft: "2pt"
    }
})
`
then map splitedText inside View tag
`
<View style={[styles.flexRowReverse, styles.flexWrap]}>
            {splitedText.map((word, idx) => {
              return (
                <Text style={styles.ml1} key={idx}>
                  {word}
                </Text>
              );
            })}
          </View>
`

**Comment by X3rom-S** [comment]
> Any updates? has anyone found a solution?

Hi, I found a way
Test the code below, it might work for you too

```
const [splitedText, setSplitedText] = useState([])
useEffect(()=>{
   const _splitedText = text.split(" ");
   setSplitedText(_splitedText)
},[])
```
store the list of words in the array
now we need styles to show the all word correctly inside a <View> tag

```
const styles = StyleSheet.create({
  flexRowReverse: {
      flexDirection: "row-reverse"
  },
  flexWrap: {
      flexWrap: "wrap"
  },
  ml1: {
      marginLeft: "2pt"
  }
})
```

then map splitedText inside View tag

```
<View style={[styles.flexRowReverse, styles.flexWrap]}>
      {
          splitedText.map((word, idx) => {
              return (
                <Text style={styles.ml1} key={idx}>
                  {word}
                </Text>
              );
          })
      }
</View>
```

**Comment by shanike** [comment]
Using @X3rom-S 's idea [here](https://github.com/diegomura/react-pdf/issues/1571#issuecomment-1170146553) I created a component for RTL Text:

* The idea: reverses the sentence (mainly) by using `flexDirection: "row-reverse"`
* Takes new lines ("\n") into account 
* Notice: style on the text is different bcos each word is a <Text> so I added supports for textAlign: "center" by passing textAlign="center"
```tsx
import { Text, View } from '@react-pdf/renderer';
import { FC } from 'react';


interface RtlTextProps {
    containerStyle?: any | any[];
    textAlign?: "center";
    children: string;
}

/**
 * When using <Text> component and the text is longer than 1 line, the hebrew text (and arabic I THINK) is rendered wrong.
 * This component fixes that.
 */
export const RtlText: FC<RtlTextProps> = ({ children: text, ...props }) => {
    const { containerStyle: containerStyleProp, textAlign } = props;

    const sentences = text.split("\n");
    if (sentences.length > 1) {
        // each "sentence" doesn't have "\n"s in it
        return <>{sentences.map((sentence, i) => <RtlText key={i} {...props} >{sentence}</RtlText>)}</>
    }

    const words = text.split(" ");

    const TextStyle: Record<string, any> = { marginLeft: "2pt" }; //! couldn't get the `style` interface! https://github.com/diegomura/react-pdf/issues/2291

    const ContainerStyle = Array.isArray(containerStyleProp) ? containerStyleProp : [containerStyleProp]
    ContainerStyle.push({ flexWrap: "wrap", flexDirection: "row-reverse" });

    if (textAlign === "center") {
        ContainerStyle.push({ justifyContent: "center" });
    }

    return (
        <View style={ContainerStyle}>
            {
                words.map((word, index) => <Text style={TextStyle} key={index}>{word}</Text>)
            }
        </View>
    );
};

```
Usage example:
```tsx
<RtlText textAlign={"center"} >
    {text}
</RtlText>
```
Related: #1394

**Comment by mzaien** [comment]
<Text style={{ textAlign: "right" }}>اهلا انا عربي </Text> worked fine with me despite the view this text was inside
