### ISSUE TITLE
Bug in fontkit - ReferenceError: Cannot access 'index' before initialization

### ISSUE THREAD

**Issue by MikkelStampe** [diegomura/react-pdf#1572]
When rendering PDF server side, we get the exception "ReferenceError: Cannot access 'index' before initialization".
It's only when rendering specific PDF's.

I cannot find a system for what makes the difference. But after digging into the stack trace, and debugging the libraries, I found the following, which seems like a bug in fontkit.

I have no idea why in 95% of the times we don't hit this piece of code.

The stack trace points back at:
`at GSUBProcessor.applyChainingContext (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:7475:15)
  at GSUBProcessor.applyLookup (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:34974:21)
  at GSUBProcessor.applyLookups (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:7268:26)
  at GSUBProcessor.applyFeatures (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:7246:10)
  at ShapingPlan.process (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:6277:19)
  at OTLayoutEngine.substitute (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:35416:17)
  at LayoutEngine.substitute (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:35550:19)
  at LayoutEngine.layout (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:35536:10)
  at TTFFont.layout (/app/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:38725:31)
  at /app/node_modules/@react-pdf/textkit/lib/layout/generateGlyphs.js:63:25`

If I look at that piece of code, it's totally correct that 'index' variable at line 7475 isn't initialized or declared in this 'case 2' scope.

If I fix this in my installed library locally, all works perfect.

```
applyChainingContext(table) {
    switch (table.version) {
      case 1:
        let index = this.coverageIndex(table.coverage);

        if (index === -1) {
          return false;
        }

        let set = table.chainRuleSets[index];

        for (let rule of set) {
          if (this.sequenceMatches(-rule.backtrack.length, rule.backtrack) && this.sequenceMatches(1, rule.input) && this.sequenceMatches(1 + rule.input.length, rule.lookahead)) {
            return this.applyLookupList(rule.lookupRecords);
          }
        }

        break;

      case 2:
        if (this.coverageIndex(table.coverage) === -1) {
          return false;
        }

        index = this.getClassID(this.glyphIterator.cur.id, table.inputClassDef);
```

**Comment by MikkelStampe** [comment]
To be exact the bug is here:

https://github.com/diegomura/react-pdf/blob/3bcb031858062ca12865de7513c5fb5eb6ab3e4f/packages/fontkit/src/opentype/OTProcessor.js#L408

**Comment by jeetiss** [comment]
this is artefact after migration from `coffeescript`, like https://github.com/diegomura/react-pdf/pull/1557

can you make PR with fix?

**Comment by cheald** [comment]
This same issue exists here, too: https://github.com/diegomura/react-pdf/blob/b536a2eef20e45e634d79b8b26bc72b4c131cb6b/packages/fontkit/src/glyph/CFFGlyph.js#L139-L140

case 29 references both `index` and `subr`, which are let scoped in case 10. The let needs to be hoisted out of the switch statement.

**Comment by markingvar** [comment]
I'm sure I'll catch some flak from the let/const crowd, but since it's the block scoping that's causing the issue you can mitigate the issue by using var instead of let:

![Screen Shot 2022-04-16 at 7 28 38 AM](https://user-images.githubusercontent.com/81870543/163678918-268197dd-51e4-4ee6-8b46-df909007a7f5.png)
