### ISSUE TITLE
Missing children in prop types for Document and Page

### ISSUE THREAD

**Issue by darklight9811** [diegomura/react-pdf#1573]
**Describe the bug**
Document and Page components do not have the children props type inside them, when I try to run the example code in the documentation, it fails because of the type error. View and Text components have properly children prop type setup.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. use typescript
2. copy paste the code in the documentation home example

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**
Document and Page components allowing children.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows] zorin
 - React-pdf version [e.g. v1.1.0] 2.0.20

**Comment by diegomura** [comment]
It [does](https://github.com/diegomura/react-pdf/blob/master/packages/types/node.d.ts#L77). Can you elaborate more about your case?
