### ISSUE TITLE
Copy/pasting text from the pdf with registered font does not work

### ISSUE THREAD

**Issue by pkandathil** [diegomura/react-pdf#1576]
**Describe the bug**
When you copy and paste certain text from the PDF. It looks like gibberish. The text renders fine by copy & paste fails. This only occurs for sections that use the registered font. Sections that use "Times New Roman" work fine.

**To Reproduce**
1. Go to this [url](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1751a1e51243e73585e60246760186d24661858ee983a307864002b742c1b18111e1800591e30607349ccfcdcad7c984362c2b3591e0470907b6229da840c1118319f3b003759cc0825bd3634ad0049467e0c17cd0de353390ea7d54df4e0416cc06c000883280810403200472188c008cb241bc4f8909046456941d13dd65b4dbfd6410043c8ca500a9e338551a9d41ad1669215aed4eb7539be1e3c400b75004088403057800b80658282d878504998c26305018094aca40019ffa4218061067626935853673a38788c1004185e62412878223e30a68b210651104861a602e58054cce60b180831e3900dad7e2559261f4ea676f5aa225abd4608d165b23a584e57200a2fd043f444083e0f16c9ef1a4c7df31e000698b0c2130ac020463c9fc307acc091483b30ba2071b6d99855d6c2da38c043cd85650c231e2c2a4561ae486baf326399815a6d76c357bcdc589980005e93160c078d024088c4b610157ac8582f46ee274ae45e8bcfea3826a01816a0b1bc541dfc4a01cb20c0002a98093080e79ca582daf68c08c00087100c0b7300932ced19a1b61809d956102daf12b21a896c8621c87d6f319855928a710ac856ab39367736e747ac087c8d639a15b46622b03a89ee336ef39d838440d79da0017ff4f12da0d920ad98c3c0008fd635a0834a8272180630f27da62661e03928c12eb980952998300c9b63dcc5b92abb322c0dac0466e73f8d026e505fe731e6267acd5080d198cd719c85a60559a12201e5a5ce671e68065985a4c13321ce198b2b214abac08321326b0083bedbbca014789c0e91019a55ab14a12ed176aac3361024eb324c8d6aee034a1c579594a1b141c480eec2991d1b38f5b01ba1804b9d5dd5a1f84c039a4ca6ba1a7025f867545465082162c2ca5596af37ac20136f24f0d1ace2db0ae786005a7549509183c96157e737f4669ee9ba2aa6b4e4f7c41301e5599d27af2d18b01019e132756733ec02be7f99a301400d8f09d42ad38da3634ac040062b6120ab525879a3c5980a734097b466bac1c2a65ac5347329cac02d4a571da8696328053988283aafd3f84d13e8d67e6ce16a2771256502c20c7b3bd97a9320000dc301f0d28bdd62d8f9a714596aa6ad4ef42a6841ec06ba7611e361344586162fc32c24d90c5a4d8b00dbdbc5aba830de3030a881986ede06751e6965ad531e76bcd81734c6dcc4821eb9b6ebb0236e5b6cb4d8d01603370a6630038fc82c010d78e66774eb6019602ea02b4ac870532ef23a4c8eb28cfc5d59832a760278217a1307c031bacd42bf1276dabb9d187405eca967d05d8b624d4a54fd308c2b1c7404b5604782ae06d8d2934c45280025f9cadab5f85da2765b2bbc4398233ba4c15da3019644f2d204be844a98248c8e193c51a5b1998996493d460848dd87facb4d2a0843a005593984b4d6929a556dcd2811b215f60bc38b467a0481cd30a1f6c0395a697824853d39c652200882b51b4375c606066e7189b21514e48d6d05e1aa45de19dc05a2d1b993d3e0d9411900ac0905e71283541f541b16046f154fab034ee70751ea5549b878a4c7d64f8b58ae054d60749805c65299926f410081ec9344723c01596a4ba7c08464c594922b2a61752e8341a132d449c653c934efd1fdaf09eaca9d53c151c0b19082c1c20596a84e35ed05a323546cd2868b4a2ac56514436788d288b350996d59e865d5b0354a699d3107604c71e080bc9c61886b86a9ef34d13c9639436e060cc47282078a0b0b39162347440a58c311db9345802e1f599098868c564303435982c3fa3c80ecfd1d985d6dc675d9a9f0b4da98d29a0c13013199c554b31de8006533cb714510c838b931444c1c684cc61d9249e699471e59c5059083d1c67306f3216946f5449652102792a97c4b6c33467f4318bdd6c3250296451526d654174c435d05a1439b8f07b9ac5fc3b60c0343e8a6150a024c6338c70bc8af05c7006308f08e72c39542859058504218400ce6104038a054ef374428f58f24597f4006f05faa72dae062301ff161e703e0e10d23a5220f03dcc44583be245a718020ad3acb5329f2ce8b398605f14293c34a383b0669c92c4a7ab291b1202ded32a17c53104b90e65b562b681062a0ecac4ce9051d5728173c9681410553ce702cc0f897564afddcc83c8895811c01c3282d1662ed776013a2292e368ab00ab3486cc179874299e7cce8669195e88f98b6b8eeb15b2b1b006c6fb2c60c8494316c528efd692501f0e00434092d4913f89f137952bc0059105d550f39c69c4ecd08714c95226024b391bb50299860a221d889e2c005c1ba393b0c94e35276dad2854a828b2b6db6b5a425674f796e089d111280e7eac1bb6a390ec1a5d36e33860010471b40354980641e15e56614718444a0943484035442981b9e100c04001c9a76419304716a499479a98094b0e7204aba96d00085366cc5c6171e857e68c99be412e389c7396ab5584c753abe7038a5b661277823c0d29a4dc9581cc0520ec8d4c02d8e8984a14bf12c9d04ad98ae59cf965b1a9a9626181d82fa97404e6156432871a2afa2b5c548c81ee7dd32974a0ef4221bf43b2b1ce8fcac8617a389167243c4900d0a0d931ae73059a8a59164c63aa3a9198863cc14f291aad464bfc4f5553143a31facdc8d5de8230f8293ecde60f89bb0b27991a41d2c8762d5621b46c32ece7881a5b56a0e630260029a0c8163485ac1dc0a0955caa8ec2dcdd88676d3de849ee3c0f7ed4153d48bf978e5a895194626db97ba406d6db5ba70a56a4284341c0b3b30c68206b8834fc49e10bf9a32a2482b2c0f99754860c0d37753cc0588b160a5e1a520544d18f41cf92b6b09b500b037e87b2f80001f9600787381d11d08010b9c6699341c60d1d4747dcf8eaacbc044066986361a32bc5e913130184f763019f47c6aab540038aec0980ac3e075b3058120eb2482484ab0599691e47979562a62d4fba2a147fd464b716cba4730c2aba0476d07d31d17949c6cc5071ace888d824cfc3450d1e03b61bc4db05586ad12fe868e2601c2aca87457bd447d61792a3f474f80b85b3168dd26bc1e3c332d19359541bda4801ae90ac4f5a70d280f39f0e4d9ca865bf1fea5624a41c622333baa2bed9bcf807472d5b717894049af58789601b351c6001e02c4e84aa0667871e433123f8afc231400fe62cb3244330904ff46a2ac3bdf96cab2ec0084558f3e478ec988188ea49f1f3af4cbaaa471532101a30514b003230108472ef58019cb718a9fbdc6aaad933a7a949903f4b84fb8d80d4598b234a3d0581c1d29ac086f8b1c08a25ff2cf302c8456de363428568aa97dae4aa85e3c964ec3a331353a0d30100032bc4d52354f30a84d033229c2774e99f03f4fad61692a65e1621b31966bc22962c75b5611d261b6fe4f760535d08e1f91800e259407939f12a3c50256fe5436816fe545640745500e3c3343722ac38e00d74a27a1540807897b841e29c7341b32fd27a25d56067f3383ae61578229365e5730f83e03730e15f60d22be6b068c31105a1733c176c0ab6735a260d0b41521b44793006f30344f93635237a778968c42f41c24649a74063b2d13ea3837c14316b248f74d1cc40258f0f078f7be24f67e14f6d87244a47280c00707b61e00006b46d6e43e401471b5783140947867816131461c60cd16a06b1b47a74b97d1509630b7a65941e5e91607b107416d1761184ad3be00c7784f808964f30c5844f08897042841847e0b304446444c0000265907885e96c412a5c46ad47e5ad52434f0cf12a000091197f13895fe56d1ca7f0350f4111673a04e5c62ec2e142c5ec3c164209c0608bf69c3155bb6d43d573e2b910621b4916bc24902b0426854f341d71b37f07545e18042f01b3c616e7266881b666b5f16856ea5945b01b47dc7e62ba2921663197b54bb79c39965a078fa159d0800584552df0143b04755f626e7f003c2df62b7795ed44160100d658ad67906ca304bf93166606186492a08c052b2c4ffe328080134584e020004d4295e46fd20542c4030f47b33b00b40ab01770259d6ea07a75b0e176d7927a770215406f1422e341567a38365266a6bc2ed35f01d5e16060d226701a0ca5b47520c168a1150b2318000294147413c21823ec2114e965001272464242c2c77408f03709f13b666c000253417023e2518b4a16a7d10f873805949e45110a1b44972892952112b34b61bc5b002c32086c68cfd15dc03c6fa3a31465384b0a705b42732c015c50030973803e1f1367342060e614bb6543570e82a670046e73e2d61104504bc548a0a66e4ca06033891e3a4b3c6f57b21230008f034661424979226842271e3b27c49361c70836980121e41605b4b9c74129a2db4fa69e0630ba22492a2a911028021113e038e80eb15874ce31038d540cf115d69c4fc4f32b40b0e8257668b03200d03c788c9c138fc202947065a363694d6c7c678249c530f14eb705a3ec4e22c50e75c227a59c70a70048d3ec1820a12713a1582a132bd11710f7ea1b041cf8644642e58ca8295b7e81e93e0004db74ec0292a77723ff6143fc9ab057030c88d29764874c5b4b67905dc19a442b867ac79d767061382e2b6d429c3722b0e913a54694257f111e5a3622b163b2330262db054885402c70246a6727721ca13cecd1627636ab4bc7e82a40a42b022c4af0402194bc78867f0654c701253e4948f88852af7a05af7a7230c983e53e4cd73b2824cf4678d84d6a4e2a2c6a2cbc35f31c8cd19c65a04619246a6bc1802cd59453762c230f3461c3f1424e64cab47cfbd700734ca2fe842f6fb24a0c05e478a200819100dcad40b0f1131326727f779445cd22e40de2a40884e4621e48e5051c52c063f235160710cc89ef7187562df5c94629265257c133a15c074af579627a4ca7f67e534543c9440000e68c2d46b95062e1574fd172cd715649290c05b822c4cafa71ff7a73b25b738abb05234c27f06ef0f8a44bb9790bacc802d149a37f2ccb4cb6afb4ef352e2e2fb0dbe20c44f1ad528bad37e48c7f08649ef5f4d80ed66f4f8a626163462f6e3b8182306f5238288f01cddc78a25423a8a712a4730aa2a0eab68571440014020007ed747350b852b564e7aa9a5626f36b44ec5588ec060fd24b63a90f883e02c0bf3cc3dc12c1ea6f8eb02972b47721c661332a1cc8356dc4b031c6fe5f611073d09f062e4274e4ce7bd2c056c4d884cc856dccbaae15429eb764bf49e55b2d4c203388cb13193180f81527023fe05e2633151e00007e71467d01b143562b1335649906068568c10ec8271c3bd7110ccc98134696b6ae3c5f44982d433019203459a648fc62d2038579726420c1aaca0097d53d4f675ea6fe2d650e8197eb0c059c26635342206640256f7f91e017cb065a916d3b4e3c5b01926508a15e94da04d41cfab38a4e22ea1a211045527a66038c77c4da7bc3ec700006cbe4c8f88f4e99637667d5d4a35042cf45760f88541e286345145a0214c233835928b23d32368b069044b6d640db4254434f4d5984a23824811c60f94e4cd261c28d5b40b256a0356d10e270a4b509d134756e12f1d6974ee7744e089868c32c0583fe33eab50123411b91ca58b240974e8cb013d1356b5927ae8c4f4da63c6b5a86c67b0b10fa0d176495d3335601386146eb70034178a1f04dce0acb62987ace753b0f4828684f7b0a70a28170fad446e8c264a97054510a08452bb8a0cf46fa10290549542b4ba6c024669a00811b96d44710895a871b1374812597bace226e3f21102505b0338c96840696e0d041c21fb203c1525221aa274cd01543e06d28808662825b056a23c1a13982a27ee060110422489a5e17a0420de9ae03a87a42c2899e34b65944beefe789102920c8e6e6d9ad2e79c80042800790882800923c224635cc808eef9739896034569465556e240a5a2997b25117a07b6e2c8ec8387002d16825f69052ba679498456b8e48e000421a18402de7b40f42b72b67761100116fe9e5640fa61805a1e3a1f4b176523ee35b6c241a0253aa7109a95223c333afe935ac2c7f032e711ad0491c70d86e70b0c3e8ff0fbf53838239b1d9c9a1372994027e2d1b7ea5519ab0a088d2cca8e5593e34669a9f30276d89d9a1a04145a62b0734a6634d64e0fa3d805c3acce5459e981cae3c104b5ce60678ace4633d50df59c9a0d70240142a7a7f06b972c0e5f5ad7213827763c11a33ae1b014d155ec4e8336ada5848ce8f415192d3d50dec351e06022e01103599e066646a025a7c0874b666048cb4924e0f462d6c6aca12e325a8cb004f172f0120607fd1ca3a3535d967bc12084a5360c060266d7713d294a8337c24b08f8ccaad25c65a0b89ae97b49152933d5b161750a36ca7183aacef01cdf21060c0250c2554aab6a4328573e5461fb1b2bb5160458dd42f596d0daa7982357724e5ceb34a7a5b648206e0ea376fe81e41c62f642311696d72f2ec6f8b69b3a352c9879e72f542f467f03283dd5c146a0b46fe7e772b2cabc9d9b46b7c8e86e919f9d91bf986d68c0119116ff7b90b849a279e8cb14eec3e2584cf350059a57514e7acf64a62a4aa11d8dadc919cf469d9057a167eb3a76c50629704af64bcc2ba0ba205dfaf69dc9b16184e6e3d01052990db05f40f3a3448a702cc8f426237a60243eb8e2a540e57556451acb61394b2688a971e00268d2002923d7124382d35f2e0643e147bf0424224552ac60dd0e4552e565a05475a6e0b8c679a0a432ad328af1b33a5ac55c65d65023d7bc0ae47c2b29f58f454e61f2e6cb07b22826aaba51c60af68e7b4f021ae36acc1dfeec1fee7a742f06359b71c2937bad54afc7120cefa04d6c016ea4bc6864d40d1a176a57ef6995987c24eea5eba3daa05853b5f759495f2b6ea951eab23a0ff9275e6e11124e06023a21320e12ae113285ff2cb3e9794d765dec6f256c34e255dc8f05e6100010649960c02071972994ecf660154764bb27f3399d342762d41c25536f52ac50481c4a68f03106187d4961ca395d72bb1808f2ac7da306cac01d95506c685e94a9710e4b616358a45e2ebc96feb301e60e2b71e7b505e842544bd9bb2002614e2241945b9795618e2602631f3465d76dd9a6bed61adf531585661e5b8bf358afa53f0f06d94a25190f9fc42f9ae88285f9f869920104832601690707f0644c903c009004a707c87873846540de03841805502206c05203c068c00003000120903078c0087c6c3b00700c8180627d47db4747b305507c79040200706701405701804e8891867f704c83a00600a0f600203963203204c67acd907f0010e4e5b07878e0041b3c210714000726a98806085b4250157b9f304600557fa82807880805140c80c848d5603903e005e3286005907660c87847344d7a718c86b8144000660c80648007d6d00006900035000361001da800751006b87901022500f7c601f78000d0004e1e067d67d70c280470157b202c7d17b20726e079ae5c01d92d81d94b002b7b7a884c0797ca045015071409017811e9545e96d01007887140f78005627496fdd24c374048b71460fdefe6feb056fbe0018bea201db42efb1fca055039f2a431046f9780b7a803d93dc0c071446880016274b4f67d38c109d57f63d871d7f5ffaccc66d61106579803578d7ad79cfc5fb9f58e001b5fcd00dfadf9df980144468c3f93c18feb5030019fd6f4b604bfa680a2c02130020fca00c3f1801efc0000c73e25f8700dc22bf5ff937cbfef591ffb8a176a4e96807c91f01000abfab006fed5c7bfa3fc5dedaf0e01a0328069e4ffa9516f0c40bffa902701ac03c05ffc0fe2f023f89fd4010ff49629e11c0420480670037e140a57aabdd9066058827a54542ff4c79cf9ca24c0ca01102c0081f0449298440f8085fb303e32f2469fa00d6f63a0bff9202501740b9f2581e5ab6055053817014806df89030812c0d8050fc1b0bbf0b06680f81200b005f102014e950010a16c10ff2561778c41f40c47993d91e210ec06701a70a0c328380155e48c0b41e61300620ca037fd1c1bff7ff93a5140f008f04c003de5e0ce018811c0500714294328038c4641543001fa060069fc1fee7f3b02642ff0c10d579843441a80ee21e7cc5eee92b00c40b803404c614bcd7472f2a02ba0d001e85c408bcc804000)
2. Enter the following text in any of the <Text> tags `Daylight Pacific Time` 
3. In the new PDF generated on the right hand side, try and copy and paste `Daylight Pacific Time`. 
4. Copy and paste will work for any section that uses Times New Roman as the font but will be broken for any section that uses Oswald as the font.

**Expected behavior**
Copy and paste should work for registered fonts

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome

**Comment by diegomura** [comment]
Duplicated 915
