### ISSUE TITLE
Can't get coordinates and dimensions of the rendered elements in pdf

### ISSUE THREAD

**Issue by evgimov** [diegomura/react-pdf#1578]
Can't get coordinates and dimensions of the element since box property is empty for each element.
The goal is to draw lines (by using either canvas or svg line) between two components in the pdf document.
Here is the little snippet of what I'm doing:

```
  const el = useRef<any>()

  useEffect(() => {
    if (el.current) {
      console.log(el)
    }
  }, []);

<Text ref={el} debug>Some text here</Text>
```

Here is what I get:
```
{
  "current": {
    "type": "TEXT",
    "box": {},
    "style": {
      "border": "1 solid #D6D6D6",
      "padding": 5,
      "marginTop": 30
    },
    "props": {
      "debug": true
    },
    "children": [
      {
        "type": "TEXT_INSTANCE",
        "value": "Some text here"
      }
    ]
  }
}
```

For some reason box property is empty for each element, however I can see in the source code that it should have the following props:
```
  const {
    left,
    top,
    width,
    height,
    marginLeft = 0,
    marginTop = 0,
    marginRight = 0,
    marginBottom = 0,
  } = node.box;
```
https://github.com/diegomura/react-pdf/blob/master/packages/render/src/primitives/renderDebug.js#L146

I have also commented out on another two issues related to the same problem:
https://github.com/diegomura/react-pdf/issues/979
https://github.com/diegomura/react-pdf/issues/1360

**Comment by diegomura** [comment]
Lets keep #979 and close this one
