### ISSUE TITLE
Possible bug in transform translate

### ISSUE THREAD

**Issue by GabrielNexT** [diegomura/react-pdf#1589]
Hi guys, I think I found a possible bug in transform translate.

I want to line up a text and an arrow so it's on top of a bar and based on the input, this arrow moves on the bar, from 0 to 100.

I did it using CSS grid, using translate(-50%, 0) to leave the middle of the arrow at the beginning of the bar, but in the PDF I'm having some difficulties.

**Current:**
You can find part of my code in [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00403204b3014c04204301381c53e809b2012b2003889ac02f0c005009431501f0c037805030c9b2500ae98c1d2edc6001e006a099007718d0027801b6454d92d51001d283051d12649802fb35162274b90aa0ab51aed6ed10121002ac80079433172c4a78fb31c32001994284478803d10543980448c75aca240548cbca6838e4e8011960030b80191a9ba52664d8e7a9e76a1663c6a5f9265b8bc6dbd9d53b201563c5980328028802aac7c65464a5674fb6a576a8f7dbf457f956a46db6d5b1b0c36a1fd6350dbb2000d0c217000358039a6083f183e09728500170c00110031003b00198008c0056001b000c5be3013099b696662c552f30c96cda015dbed0e2e5e9ad4e844bb5dee8f67abc40ef4c17cfe80f4300000cb4985c21162246cce4a8ee322e6db1e672f98b5dbd55c1e6f2f8b9817173088083b8002ca0b28554126d2be472d2fe7e56bb8f400370704c868e1e9a0304f341904c3a23058ec512f00442113b4002220603f000b6c87d2a3c40005741ddadae00179a9be0041000b0c38578ed29043c8569b5c48814060707842091c8941880662c1d0f4d621eaf6fbfda20351a4d66d81e46d435e90de5c83e2e978e828321689c6e0a7435f21d8853f87c120eeee10290be80d079dfc93e9d80eea810140a0206f57dc1cbd5c11d777000485010e1d2ba1948ba3e59890f278bcde9f1fafd215fef8afb8265fcc07a194281520ea58612a85e1ba082f0c014008380d4a3cb20fefe2de729800024bf6de840d4b007ebf6982a17f801a2b20f118efe37a581dc4805e9815e379de30202da3fc0fac200634253e886081547819057cc0801ffa888d2096227672a2a8bbfcda271dc041de341b07c1884fcc84915c4490338aa9149dc13ea4abe14bbedf2f0f80e9dc3a177161385e13f0a95e000b4d01605037ca2389c67e93e119571d2248bee4a52d483c5d980364c0501e090184143ee3f1c5e8240ca1f603ab9a0bd2002939cf4bd03a6f94166004b20814c92ab52c0bd2794c52e489624ae263d61c09074940819ba90b68bc0bcc62d01d1f4fd8c0c5bd6400000).

**Expected:**
![image](https://user-images.githubusercontent.com/38765665/140929062-1cff96a7-8181-4446-80c6-14d103c4dd13.png)

The translate behavior is weird, it doesn't seem like it's shifting just 50% to the left.

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser Brave
 - React-pdf version 2.0.20

Thanks for your help and for this amazing project!

**Comment by GabrielNexT** [comment]
It seems that in the transform operation the unit % is not supported, so this is not a bug, it's a new feature.

Any idea how I can do this?

https://github.com/diegomura/react-pdf/blob/5afedfe22dc133e3a27a1e5ec0b9197df7bd6dc1/packages/stylesheet/src/transform/units.js#L28-L45

**Comment by EmilyRagan** [comment]
Not sure how this would be done, but I would love if it was!

**Comment by imatwork** [comment]
Looks like you'd have to:

* Carry `node` through the `@react-pdf/layout` -> `@react-pdf/stylesheet` boundary. Currently computing the style resolution doesn't get any information about the node to be able to compute this.
* Pass `node.box.x` (or y or z depending on which scalar is transformed) into the `transformUnit` call [here](https://github.com/diegomura/react-pdf/blob/e94e50a931df7347a8febc717ca76843502826c8/packages/stylesheet/src/transform/index.js#L21)
* Then you should be able to add a `case '%'` that would allow you to return `scalar.value / 100 * xxx` where xxx is the passed `node.box.x` or y or z
