### ISSUE TITLE
Spinning Logo on the official docs.

### ISSUE THREAD

**Issue by noor-codes** [diegomura/react-pdf#1594]
**Is your feature request related to a problem? Please describe.**
I just started reading the React-PDF official documentation and the spinning logo is extremely distracting, I can't focus on the documentation itself. Please make it stop 🛑 ✋ 

**Describe the solution you'd like**
A on liner css magic should do the trick.

**Additional context**
If the logo isn't spinning, it would be way less distracting and help us enjoy the documentation. Hope it helps the next person who visits the docs. 

Thanks 🙏 
![EF9E5EF6-6A84-4B22-BEFB-ECFC7A9721BA](https://user-images.githubusercontent.com/28804764/141736494-0f52614b-50b3-4539-94be-f48ad8011ff8.jpeg)

**Comment by akatsukilevi** [comment]
This is a serious project with serious issues, but I can't control myself

SPEEEEEEEEEEEEEEEEEEN

**Comment by jeetiss** [comment]
PR welcome 

https://github.com/diegomura/react-pdf-site

**Comment by jeetiss** [comment]
duplicate
- https://github.com/diegomura/react-pdf-site/issues/61
