### ISSUE TITLE
cannot execute "examples" command.

### ISSUE THREAD

**Issue by ohhonggi** [diegomura/react-pdf#1595]
I'm an undergraduate student taking a class contributing to opensource. I'm interested in this repository and trying to find some issues that I can contribute.

I wanted to know how the react-pdf open source works, so I ran the examples script.

**Describe the bug**
<img width="628" alt="스크린샷 2021-11-16 오후 1 58 24" src="https://user-images.githubusercontent.com/33611439/141923587-42c73f0e-17d7-469b-ac8d-900aa3ac3a69.png">

Looking at the package.json script in the packages/examples folder, I found that an error occurred because there was no script called 'start'.

**Expected behavior**
Therefore, I wrote an issue thinking that a script called 'start' is needed in the package.json file of packages/examples.

And I checked the history of packages/examples package.json and it seems to have worked in the previous version. If you give me a guide on how to make it work in the current version, I will try it.
And can you guide me if there are other issues to try?

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: chrome
 - React-pdf version: v2.0.0

**Comment by diegomura** [comment]
Now it's `dev`
