### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by christiangenco** [diegomura/react-pdf#160]
I'm trying to get `react-pdf` working in a `create-react-app` new project.

I created the project with `create-react-app pdfdemo`, then added `react-pdf` with `yarn add @react-pdf/core`, then tried to `import { Page, Text, View, Document, StyleSheet } from "@react-pdf/core";` in my `App.js` generated file.

This failed with `ReferenceError: regeneratorRuntime is not defined`, which I fixed with `import "babel-polyfill";` at the top of `index.js` (from [It can not run in next.js #125](https://github.com/wojtekmaj/react-pdf/pull/41)).

However, now it gives me the new error `TypeError: Cannot read property '1' of null`:

<img width="712" alt="screen shot 2017-10-25 at 3 59 51 pm" src="https://user-images.githubusercontent.com/179361/32022969-9023f5f2-b99d-11e7-8823-bf488d357eda.png">

What am I doing wrong? D:

**Comment by diegomura** [comment]
`react-pdf` is not running on the browser yet. That's why you get that. You can read or comment on #101 for more info. Thanks!
