### ISSUE TITLE
error Cannot read properties of undefined (reading 'height') at setNodeHeight

### ISSUE THREAD

**Issue by jeetiss** [diegomura/react-pdf#1602]
```js
const Component = ({ name }) => {
    return (
        <>
            {name &&
            <Text>
                {name}
            </Text>}
        </>
    );
}

<Component name='' />
<Component name={0} />

```

Example above cause fatal errors in `@react-pdf`, but it should render nothing.

[👉🏻 repl](https://react-pdf.org/repl?code=140630f60760ce02e0040613016c00e902985e05e3802806f382010d90ce017c04a38700f8e43838db80270c6015c3884b94a00c985c003c00543000f180d0990a55c407a69721b02ac177868f00228f009632c0c4a79f1d460558480226040f0ad8b7b090015480730c4f2f0924344c6c410a1c007268b85520af7150f4082c78250c1c4200062a78c489555f00a0b567577779601a006e5d00250c5210186f470031003a2e0800130c0e7c7163330b4a04bae02000)

### Discussed in https://github.com/diegomura/react-pdf/discussions/1599

<div type='discussions-op-text'>

<sup>Originally posted by **joseDaKing** November 17, 2021</sup>
I get this error in my code and I don't why

error:

TypeError: Cannot read properties of undefined (reading 'height')
    at setNodeHeight</div>

**Comment by mkamalkayani** [comment]
I also got this error. After trying out a lot of stuff, I realised that the extra ";" outside the Text and inside the View component was the reason for the error.

```jsx
<View>
      <Text>some text</Text>;
</View>
```

**Comment by Nases** [comment]
try 
`
{ name ? <Text>{name}</Text> : <></> }

`

**Comment by jepek** [comment]
In my case I just copied some example from docs and forgot to wrap the next inside `<Page>` with the `<Text>`

I had: 

```jsx
const MyDoc = (
  <Document>
    <Page size="A4">
      My document data
    </Page>
  </Document>
);
```

But it should be:
```jsx
const MyDoc = (
  <Document>
    <Page size="A4">
      <Text>My document data</Text>
    </Page>
  </Document>
);
```

**Comment by doksel** [comment]
You should just add styles to Text
`const Component = ({ name }) => {
    return (
        <>
            {name &&
            <Text style={{height: 50}}>
                {name}
            </Text>}
        </>
    );
}

<Component name='' />`

**Comment by doksel** [comment]
You should just add styles to Text
```
const Component = ({ name }) => {
    return (
        <>
            {name &&
            <Text style={{height: 50}}>
                {name}
            </Text>}
        </>
    );
}

<Component name='' />
<Component name={0} />
```
