### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by TD-DO** [diegomura/react-pdf#1614]
**Describe the bug**
I have a lot of Cypress tests. Before I added react-pdf, they could all run at the same time without crashing. Now, just importing react-pdf causes the tests to crash when I try to run all the tests at the same time. The error I get is Memory Exceeded.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Have a project with a lot of cypress tests
2. Try to run all of the cypress tests at the same time
3. The first 5 will work but once you get to around the 6th you will get a memory exceeded error from chromium

**Expected behavior**
I expected all of the cypress tests to run without getting an error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - React-pdf version 2.0.20

**Comment by TD-DO** [comment]
I'm planning on writing a PR to fix this issue and any help would be appreciated!

**Comment by TD-DO** [comment]
Here's a better way of recreating the bug.
1. Create-react-app
2. Install @react-pdf/renderer, react-router-dom, cypress and @testing-library/cypress
3. npx cypress open (This will get cypress set up)
4. Make a new test in cypress/integration called App.spec.js:
```
describe('App', () => {
  it('crashes when react-pdf is reloaded too many times', () => {
    // This crashes after about the 15th time on my computer
    for (let i = 0; i < 2000; i++){
      cy.visit('localhost:3000/pdf')
      cy.visit('localhost:3000/non-pdf')
    }
  })
})
```
5. Change App.js to:
```
import NonPDFPage from './pages/NonPDFPage';
import PDFPage from './pages/PDFPage';
import {
  BrowserRouter as Router,
  Routes,
  Route,
} from "react-router-dom";

function App() {
  return (
    <div className="App">
      <a href='/pdf'>PDFPage</a>
      <a href='/non-pdf'>NonPDFPage</a>
      <Router>
        <Routes>
          <Route path='/pdf' element={<PDFPage/>} />
          <Route path='/non-pdf' element={<NonPDFPage/>} />
        </Routes>
      </Router>
    </div>
  );
}

export default App;
```
6. Make a folder called pages in src
7. In folder make two files: NonPDFPage.js and PDFPage.js
8. PDFPage.js: 
```
import { PDFDownloadLink } from '@react-pdf/renderer'
function PDFPage() {
  return (
    <div>
        PDFDownloadLink is imported
    </div>
  );
}

export default PDFPage;
```
9. NonPDFPage.js:
```
function NonPDFPage() {

  return (
    <div>
        Nothing is imported
    </div>
  );
}

export default NonPDFPage;
```

**Comment by TD-DO** [comment]
I made a test repo that shows the issue. Here's how to recreate it:
1. Create-react-app an app called test-repo
2. Change package.json to:
```
{
  "name": "test-repo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@react-pdf/renderer": "^2.0.21",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router-dom": "^5.1.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^12.0.0",
    "cypress": "^8.6.0"
  }
}
```
3. Delete node_modules and package-lock.json then do npm install
4. Change App.js to:
```
import NonPDFPage from './pages/NonPDFPage';
import PDFPage from './pages/PDFPage';
import {
  Switch,
  Route,
} from "react-router-dom";

function App() {
  return (
    <div className="App">
      <a href='/pdf'>PDFPage</a>
      <a href='/non-pdf'>NonPDFPage</a>
        <Switch>
          <Route path='/pdf'>
            <PDFPage/>
          </Route>
          <Route path='/non-pdf'>
            <NonPDFPage/>
          </Route>
        </Switch>
    </div>
  );
}

export default App;
```
5. Add a folder called pages and in there put NonPDFPage.js and PDFPage.js
6. PDFPage:
```
import { PDFDownloadLink } from '@react-pdf/renderer'
function PDFPage() {
  return (
    <div>
        PDFDownloadLink is imported
    </div>
  );
}
export default PDFPage;
```
7. NonPDFPage.js:
```
function NonPDFPage() {

  return (
    <div>
        Nothing is imported
    </div>
  );
}

export default NonPDFPage;

```
8. CLI npm start and in another terminal npx cypress open (to get cypress set up)
9. Create App.spec.js in cypress/integration with:
```
describe('App', () => {
  it('crashes when react-pdf is reloaded too many times', () => {
    // This crashes after about the 30th time on my computer
    for (let i = 0; i < 2000; i++){
      cy.visit('localhost:3000/pdf')
      cy.visit('localhost:3000/non-pdf')
    }
  })
})

```
10. Run App.spec.js in the cypress window
11. See crash

**Comment by TD-DO** [comment]
I added package.json up there because it turns out it's important which version of react and react-dom you use. It breaks on 16 but works fine on 17 IN THE TEST REPO. In my actual project, I have react and react-dom set up at 17.0.2 and it's still breaking. It's possible to upgrade the other dependencies and nothing changes, but I left in the dependency versions I'm using in my actual project just in case.

**Comment by jeetiss** [comment]
@TD-DO thanks for the detailed reproducing instructions.

can you publish your test repo? I try to check the issue

**Comment by TD-DO** [comment]
@jeetiss That would be great! Unfortunately, my organization is worried about security and doesn't want me to publish the repo, even though it doesn't have any internal information. I'm currently trying to convince them to let me but I'm not sure how successful I'll be. The detailed instructions are to get around not being able to publish the repo and I apologize for how tedious they are. I'm going to try to see if they'll let me publish the repo under my non-work own account.

**Comment by taradia** [comment]
@jeetiss https://github.com/taradia/test-repo

**Comment by diegomura** [comment]
I think this had been fixed for a long time. Will close until further notice
