### ISSUE TITLE
Cannot read property of null (reading 'value')

### ISSUE THREAD

**Issue by kevinRoomies** [diegomura/react-pdf#1623]
**Describe the bug**
Upon using pdf.toBlob(), the app crashes with the following error:

> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')
    at parseColor (parseColor.js:13)
    at drawBackground (renderBackground.js:29)
    at renderBackground (renderBackground.js:46)

This error is new as I didn't change this bit of code for weeks and it was working fine.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
0. Install @react-pdf/renderer
1. Create a react component for template
2. Generate a pdf by passing it the template
3. Generate a blob with the method toBlob() of pdf

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
My blob would be generated and I would be able to use it for my document viewer or for download.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - React-pdf version: 2.0.21

**Comment by patrickrnelson** [comment]
@kevinRoomies Did you get this solved? I am having the same issue right now

**Comment by BernardoQuina** [comment]
Having the same problem but only in production, did you manage to solve it @patrickrnelson ?

**Comment by leeor** [comment]
Running into this issue when I have a text node with color style set to `inherit`.

The REPL reproduction below gives a different error (`TypeError: t is null`) than what I get in production: `TypeError: Cannot read properties of null (reading 'value')`.

[REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5400a8614b1a004f003619b006f453142c90009c0170c00e448c000b0c1a9145d3002fa5a1c338065283c019b398010582804ac7ab0ec25400f4e292b681a15250720acaaa20eada7a0046b23cc000d616d6c4c191e1d441bc02b6c1740cccacec0400dc64640062e05000741a187c48d026788a1cce3c8c48b2d23aba00f21000ee3cb20026ba00341c101ac063865050000e105a4141cecd102d7cd03c5048c02da08c41104120d3b37341006e008c00cc41009a00faa20034800d4006c200007001d4406f6480154e65f463fc001a004e1e3b9dc2d2db3974644b2d5ea00250c3a4a05c1a034da2c398f4a888543a0b04162092800000)

Overriding the color to never be `inherit` prevents this crash.

The crash happens in this code:
```
var parseColor = function parseColor(hex) {
  var parsed = colorString__default["default"].get(hex);
  var value = colorString__default["default"].to.hex(parsed.value.slice(0, 3)); <<<<
  var opacity = parsed.value[3];
  return {
    value: value,
    opacity: opacity
  };
};
```

**Comment by leeor** [comment]
Same crash happens when color is set to 'windowtext' or 'window'. This also happens when the value is not a valid CSS color value.

**Comment by ihsajjad** [comment]
sdf

**Comment by ihsajjad** [comment]
I also faced the problem. In my case, I used var(--primary-bg) along with the color that's why I got the error. When I removed the var and the problem was fixed.
