### ISSUE TITLE
Cannot find module "fs"

### ISSUE THREAD

**Issue by Bamii** [diegomura/react-pdf#163]
Hi, i keep on getting this error from npm
Uncaught (in promise) Error: Cannot find module "fs"
    at webpackMissingModule (index.js:7)
    at eval (index.js:7)
    at Object../node_modules/@react-pdf/node/lib/index.js (reactBoilerplateDeps.dll.js:1257)
    at __webpack_require__ (reactBoilerplateDeps.dll.js:49)
    at eval (eval at 61 (5.chunk.js:16841), <anonymous>:1:42)
    at Object.61 (5.chunk.js:16841)
    at __webpack_require__ (main.js:687)
    at fn (main.js:106)
    at Object.eval (eval at ./app/containers/PatientsDetails/pdf.js (5.chunk.js:39), <anonymous>:13:74)
    at eval (eval at ./app/containers/PatientsDetails/pdf.js (5.chunk.js:39), <anonymous>:90:30)

**Comment by diegomura** [comment]
You are trying to run the library on the web right?

**Comment by Bamii** [comment]
Not exactly, i'm running it on a dev server. But i'm connected to the internet.

**Comment by diegomura** [comment]
Could you please give more information about what you are doing?
That error message seems to point that you are not running the code on Node. The web version of this library is not working yet, but I'm working on it (check #101)

**Comment by tzookb** [comment]
How do we have browser examples?

but when I try to run the code snippet from the main readme

I get those "fs" "tls" errors?

is there something Im missing?

**Comment by diegomura** [comment]
@tzookb the library is not working on the browser yet

**Comment by tzookb** [comment]
Thanks @diegomura

Any tips on how to develop a pdf and easily viewing the result in the process?

Can I use the node version and instead of saving the file to stream the output with pdf headers?

**Comment by tzookb** [comment]
If I'll do something like this in node:

any idea how to get the "buffer" from the "PDFDocument" ?

```
app.get('/', async (req, res) => {
    let buffer = await ReactPDF.renderToStream(<MyDocument />)
    
    res.set('Content-Type', 'application/pdf')

    res.write(buffer,'binary');
    res.end(null, 'binary');
})
```

**Comment by rogierslag** [comment]
You can check out this code: https://github.com/inventid/pedeffy/blob/master/src/index.js#L33-L53

**Comment by diegomura** [comment]
Not yet 😞
