### ISSUE TITLE
Baht symbol in pdf

### ISSUE THREAD

**Issue by mitchan** [diegomura/react-pdf#1633]
**Describe the bug**
Display the baht symbol ฿ in the pdf

**To Reproduce**
I have prepared a small repo [here](https://github.com/mitchan/bath-in-pdf)
The resulting pdf can be found [here](https://github.com/mitchan/bath-in-pdf/blob/main/lib/example.pdf)

**Expected behavior**
The ฿ symbol instead of the ? and the THB

**Screenshots**
![image](https://user-images.githubusercontent.com/5127300/144868332-ad781b92-17b4-44b0-ac0e-cb6eb50b2350.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - NodeJS 12
 - React-pdf version 2.0.21

**Comment by lindenwells** [comment]
I'm having a similar issue with ≥ rendering as e. I've tried at length to register a different font, but no luck. Apologies for not providing a working example, but it's using create-react-app with babel and running within a docker container.
I would be happy to provide a working example if someone is interested.

**Comment by diegomura** [comment]
You will need to provide a custom font for non-latin characters
