### ISSUE TITLE
View component does not fill the remaining space on the page after 2.0.21 update

### ISSUE THREAD

**Issue by vasiastep** [diegomura/react-pdf#1634]
**Describe the bug**
There seems to be trouble with the View component render after updating to 2.0.21.
If the View component starts on the 1 page and end on the 2 page - it does not fill the remaining space on the 1 page (screenshot 2) - but it should.
The problem appears if the View component has child components that have not enough space to be rendered on the previous page of the pdf document

**Expected behavior**
View component should fill the remaining space to the end of the page
<img width="854" alt="Снимок экрана 2021-12-06 в 17 32 25" src="https://user-images.githubusercontent.com/58212703/144875677-6e205f13-8252-48dd-92e8-d37801dcf5f4.png">

**Actual behavior**
View component breaks itself causing fake padding at the bottom of the page
<img width="854" alt="Снимок экрана 2021-12-06 в 17 36 04" src="https://user-images.githubusercontent.com/58212703/144875705-387072b7-ccfe-4650-b758-81c099ebbef6.png">

Has anybody faced this issue?

**Comment by jeetiss** [comment]
@vasiastep could you please provide repl with this problem?

**Comment by vasiastep** [comment]
@jeetiss What kind of reply do you need? Are you able to reproduce the issue?

**Comment by jeetiss** [comment]
I mean https://react-pdf.org/repl

could you provide minimal code with reproduction of the behavior that you describe above?

**Comment by vasiastep** [comment]
@jeetiss It seems the repl uses version 2.0.19 and it can not be reproduced in that environment.

<img width="347" alt="Снимок экрана 2021-12-07 в 20 19 54" src="https://user-images.githubusercontent.com/58212703/145084743-e87f5618-ebab-40e1-8572-f108928bccd1.png">

**But you can paste this code in 2.0.21 environment and see the behaviour**

```
const styles = StyleSheet.create({
  title: { marginTop: "90%" },
  emphasis: { fontFamily: 'Helvetica-Bold', color: '#F22300' },
  breakable: { width: '100%', height: 400, backgroundColor: 'tomato' },
  unbreakable: { width: '100%', height: 400 },
  
  
  exampleErrorView: {
    backgroundColor: '#fff',
    marginBottom: 25,
    padding: 30
  },
});

const doc = (
  <Document>
    <Page style={styles.page} size="A4" wrap>
      <Text style={styles.title}>This is a <Text style={styles.emphasis}>breakable</Text> component. You can see how it wraps to the next page:</Text>
      
      <View style={{padding: 10,backgroundColor: '#ccc'}}>
         <View style={styles.exampleErrorView}>
            <Text >View 1</Text>
          </View>
         <View style={styles.exampleErrorView}>
            <Text >View 2</Text>
          </View>
        
          <View style={styles.exampleErrorView}>
            <Text>View that is supposed to break</Text>
            <Text>View that is supposed to break</Text>
          </View>
      </View>
     
      
      <Text style={styles.title}>This is an <Text style={styles.emphasis}>unbreakable</Text> component. Instead of wrapping, it jumps to the next page:</Text>
      <Image src="/images/quijote1.jpg" />
    </Page>
  </Document>
);

ReactPDF.render(doc);

```

**Comment by jeetiss** [comment]
thanks @vasiastep

I can [reproduce](https://react-pdf-experiments.vercel.app/repl?code=MYewdgzgLgBNCeAbAphGBeGBlKTlYAtlkoA6YAJ2QEMpkAKAbwCgYYoBLKFALhkZgBbahQDmHMABUQABz4AiABwAGAKTyYAXwA0rGMkEyC1CBwh8BAM3BQAYtUEdE8PgHIAEskQA3Eh2DUALQAQiCIACau2jCgiCAUbgDEtgBMKQDMysquWrpsAEZU1ADW1Pm8_DAA7hzhUARuAIxZqlEwRByiBFB8ACxZ0fnUwMWiFCAArmDhAMJh8W5QIMJLOTp6U4U0peXIFtW19U0tbR1dPTD9yrl6t2zIAB4OMigAohTjFABqHMhVFnoCsNRuMprN5gkYK5EpZYVFAUIROIwKEoEtBHwUgBWPJsGAyajhcISUR8TJ6daaACUAG5mMxQJBYOEQMAMDB6HoADwAEVZE0EyDAUAAfAiuQAFaiiZBwDgAL2Q6HkAEFevIxXi8VzJI9YAgUOhGAbUKRONxkJoRZICGYYHbqDAdXq4LhDca3aaDEYTGYrVsSmUUFyAPS6h6imLLGTgIVkGAATUmMWoYDgxHaICq9tgVQo1BkaCW7CIMDALoJMp4ofDooRbHrTp-f1deCNjAJRJJfWUg2BY0m0zmcUhriokU0Vsb2ub2ZNRpNEFIj2ebw-8VnU612-1tZgItnMEaNb1mp32pDs7P565h_nHrwS5XhjXn031_PbGdEf3h5SJ4jD8d1DK9pxgMCvzvT0F09J8nhfZB3jfX4qi3T9d1PQ96loe00AgCYZBjCBkHCdgQBgANigAut0IwwCsOMWA7XwwiQGI0ji0o6igO3ECUJ4vi_iAxtG2_fVoIfFAl3NFArRtO0HTTMTW3dRdl0MYxTAgK1NiKHZgzDU8o0MWNhVIGAAEkmRoUiQEsap80Ikloi4GAACsBULMiS1lcsf0rPZuNEizhBlOAKGAZVuigQseBDEMimAKBAhkcJLFIeJRBDDhQtQEMAEcJg4NyQDoRpSDcmRRA0EMP1DKUZTPUM-WAAU4zFWl6SoaZkAoegWWATqgA) it
Looks like it was broken in https://github.com/diegomura/react-pdf/pull/1541

I gonna fix it asap, until there is [a workaround](https://react-pdf-experiments.vercel.app/repl?code=MYewdgzgLgBNCeAbAphGBeGBlKTlYAtlkoA6YAJ2QEMpkAKAbwCgY4AHa4ZALhhbZsAttQoBzAJZgAKiHZ8ARAA4ADAFIFAGmatBAej0woBCWhEBrVEaIcuyGMhRDkYWGKrIAJvBjUwnmAlYdgBXCAIHADdkCnhjKTEjEGt7ACMQKCgQIV02ADMUAA8AcQoQAHc-AEZdAF9tXWQhdgJqCFM-Rhg88CgAMWohCUR4PgByAAlHaKgJYGoAWgAhEERPMc0YUEQQCnGAYj6AJiOAZhUVMZh63VSqanNqVJROmHKJT2Nxqou1DZgiBIxAQoHwACwXTapLjmdwgEL-ADCq124yyIiyVxubARdxoj2evH4bw-XxgYx-6n-gOBoJgEJU120bF0jUKg3YKAAohQyhQAGoSZCVfi5GDQ4CwsoIzzInZ7cn7PLKjZikTiKQrTLZPhHACszMEnE8ngSfHOdW0tQAlABuHSgSCwTwgYAYGD0XQAHgAIq6Qs5XAA-MVegAK1DE9naAC9kOgFABBMEKEOCQRewXCuC4FDoRgIFAQUgQTjcWowPQhsVsL3SZCFKBB6QmNCmXwwOsN2CF-MF3OoUhNFptUy1IN4h5PFBevT1xtBrbZdjgFxkGAATXhWz8cGIAIqgVg5Qo1HYaCyKRgYG7ME4UZ4s_nTZrMFfmaF5RzeHzjGNprAMRwRUKEYThGU5VRckqHWWpx1fDMsy_Xt817YsGw5bleV2JD4PTfCM2fGAgyQmAqifbs0wIjM9CQqjqI_bMUP7PB0PZZosL5XD6Oo2siJIz8YCOCiFwQmi6LEsTa1I5i0KHdjOWQHkuM_PDeMIyjSOMWhAjQCAQnYFcIC8JJxXucwRJfdSNIXLTWlgdt9MMkBjICS9JwsudKKkztaM_Hjaz84UAvfGSB1Qgdi1LOwKyrV932fZtW103wwE7IjZMiodmladoIHHXFzOnZBLMXUBmlXVxSBgABJJ0aACEA8jeU9DISTYghgAArANz1M4x7BvRs70jXhSvfGqRCjOAKGABMQSgc8eAMe5gCgBZ2E8PJSF2MQ9AkKbUD0ABHEIJC6jJkCqUguvYMQFErHjZwjKMqNnP1gADNcQztHQqH8GJ6BdYBfqAA) for the problem
