### ISSUE TITLE
Circle not render properly when in renderMode svg

### ISSUE THREAD

**Issue by amakaa** [diegomura/react-pdf#1637]
**Describe the bug**
I am rendering a PDF with the prop renderMode: svg and there are some circles in the file. However it renders with a square box around it and with a weird shape inside

**Expected behavior**
<img width="41" alt="Screenshot 2021-12-09 at 10 22 51" src="https://user-images.githubusercontent.com/2635534/145369148-fa789157-3db9-44d4-a959-fcbd9812b73c.png">

**Screenshots**
<img width="83" alt="Screenshot 2021-12-09 at 10 19 00" src="https://user-images.githubusercontent.com/2635534/145368969-2b4ef5de-ff4c-472c-b153-e0133b854dca.png">

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - v3.0.5

**Comment by jeetiss** [comment]
hi @amakaa 

looks like you are talking about [wojtekmaj/react-pdf](https://github.com/wojtekmaj/react-pdf) and not `@react-pdf/renderer` that is placed in this repository
