### ISSUE TITLE
Bold, Italics specific word in Text

### ISSUE THREAD

**Issue by VrajSolanki** [diegomura/react-pdf#164]
Hello @diegomura 
I wanted to certain word to be made bold in the <Text></Text> block, but was unsuccessful.
Approaches I tried: 
1. `<Text><Text>this line contains </Text> <Text styles ={boldStyle}bold words </Text> </Text>`
error: > Cannot read property 'getAbsoluteLayout' of null

2. <b></b> doesn't work.
Is there a way that it can be done? Please Suggest.

**Comment by diegomura** [comment]
There is currently no way of doing something like this. The main reason is because of the difficulty of rendering text on the document. You would have to calculate where to stop rendering a text, and where to start the next one with different styles. In addition, there are issues like line splitting and more that I'm not even taking into account for the moment

**Comment by VrajSolanki** [comment]
@diegomura true that was the issue I was facing, okay let me pull and try to figure this out, if I can I will send a PR.

**Comment by diegomura** [comment]
That would be awesome! Thanks @VrajSolanki

**Comment by diegomura** [comment]
Now you can do this by creating inline texts. The only thing to take into account is that provide the fonts for each particular style you want to apply. If you want to use the built-in fonts, you should also change the font-family to each particular part of the text. These are:

'Courier',
  'Courier-Bold',
  'Courier-Oblique',
  'Courier-BoldOblique',
  'Helvetica',
  'Helvetica-Bold',
  'Helvetica-Oblique',
  'Helvetica-BoldOblique',
  'Times-Roman',
  'Times-Bold',
  'Times-Italic',
  'Times-BoldItalic',
  'Symbol',
  'ZapfDingbats',

**Comment by rajit** [comment]
@diegomura Do you have an example of using "inline texts"? Is it just a matter of:

```
<View style={{ flexDirection: 'row', justifyContent: 'flex-start' }}>
  <Text style={{ ... }}>This is </Text>
  <Text style={{ ... }}>emphasised</Text>
  <Text style={{ ... }}> text</Text
</View>
```

If the text is very long, does it wrap and still inline correctly with the next `<Text/>`?

**Comment by rajit** [comment]
For future visitors, this is how you can achieve inline styling:

```
<Text>This is some text. Some of it is <Text style={{ fontFamily: 'italic font' }}>italicised</Text>, some made <Text style={{ fontFamily: 'bold font' }}>bold</Text>.</Text>
```

This will look something like this:

> This is some text. Some of it is _italicised_, some made __bold__.

**Comment by liron-navon** [comment]
@rajit As a visitor from the future, I appreciate this =)

**Comment by ReenanCampos** [comment]
As a visitor from the future. I appreciate this too, thanks 😄

**Comment by GuidodMeli** [comment]
@rajit As a new visitor from the future, I really appreciate your help. Thanks a lot!

**Comment by atscub** [comment]
And yet another visitor from the future. Thanks a lot.

By the way, this should be in the documentation for future reference.

**Comment by sfertman** [comment]
This is a problem because it makes sense to define you font family once somewhere and then play around with styles on top of that. One doc could be Courier, another perhaps Times-Roman. There's no way to reuse pdf components if the element/span that needs to be bold has to "know" about the font defined somewhere in the parent.

**Comment by sfertman** [comment]
@rajit, I'm not saying that workarounds are impossible. For example I do this one all over the place:
```jsx
function MyComponent({style, ...}) {
  return <View style={{...style, ...moreStyles}}> ... </View>;
}
```
This way I can pass `fontFamily: ...-Bold` to the component. But, the whole point is that I should not have to control font family in every component only to change font weight. I understand that react-pdf supports only a small subset of what's possible with CSS, but you got to agree that `font-weight: bold;` is one of the most basic ones. A reusable inter-document component could be:

```jsx
function MyTextWithTitle({...}) {
  return <View>
    <Text style={{fontWeight: "bold"}}>My Bold Text</Text> 
   // ^^ impossible with react-pdf, only `fontFamily: "<...>-Bold"` works
    <Text>Some normal text....</Text>
  </View>
}
```

Silly example, I know, but look at the bigger picture. The component should not know anything about `fontFamily` to control `fontWeight`. This should be up to the internal workings of the framework to figure out.

**Comment by alvarodeveloop** [comment]
Hi , somebody had troubles when the font size is a little small , like 8 for example. In that kind of size the weight bold is loose and I don't know why

**Comment by luskin** [comment]
We are running into the same problem, the following code does not work. According to `react-pdf` documentation, `Helvetica-Bold` comes "out of the box".

```tsx
import { Document, Page, StyleSheet, Text } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 45,
    paddingHorizontal: 35,
    position: 'relative',
  },
  regular: {
    fontFamily: 'Helvetica',
    fontWeight: 400,
  },
  bold: {
    fontFamily: 'Helvetica-Bold',
    fontWeight: 900,
  },
})

export function TestDocument(): JSX.Element {
  return (
    <Document>
      <Page style={styles.body}>
        <Text>Regular text</Text>
        <Text style={styles.bold}>Bold text</Text>
      </Page>
    </Document>
  )
}
```

<img width="1254" alt="Screenshot 2024-06-12 at 10 23 55 AM" src="https://github.com/diegomura/react-pdf/assets/5702322/309385ae-79ef-4f88-bc87-d3acd5af1edf">

**Comment by jhgeluk** [comment]
@diegomura Do you know how we can use the solution of @rajit in combination with custom fonts?

**Comment by KieranBrett** [comment]
Hey @luskin, did you ever find a solution? We're running into the same issue when generating a PDF for users to download 🤔

**Comment by jjsmclaughlin** [comment]
> For future visitors, this is how you can achieve inline styling:
> 
> ```
> <Text>
>   This is some text. Some of it is <Text style={{ fontFamily: 'italic font' }}>
>   italicised</Text>, some made <Text style={{ fontFamily: 'bold font' }}>bold</Text>.
> </Text>
> ```
> 
> This will look something like this:
> 
> > This is some text. Some of it is _italicised_, some made **bold**.

This does not work.

**Comment by jjsmclaughlin** [comment]
This works:

```
Font.register({ family: 'Lato', src: '/Lato-Regular.ttf', fontStyle: 'normal', fontWeight: 'normal' });
Font.register({ family: 'Lato', src: '/Lato-Bold.ttf', fontStyle: 'normal', fontWeight: 'bold' });
Font.register({ family: 'Lato', src: '/Lato-Italic.ttf', fontStyle: 'italic', fontWeight: 'normal' });

<Document>  
    <Page size="A4" wrap>
        <View style={{ flexDirection: 'row', justifyContent: 'flex-start' }}>
            <Text>This is </Text>
            <Text style={{ fontWeight: 'bold' }}>bold</Text>
            <Text style={{ fontStyle: 'italic' }}> italic</Text>
            <Text> text</Text>
        </View>
    </Page>
<Document>
```

Contrary to the docs, you cannot nest <Text> components with different styles and expect it to work. You must use sibling <Text> components and flexDirection: 'row' to force them onto the same line. It is a limitation of the library.

**Comment by Finalet** [comment]
> We are running into the same problem, the following code does not work. According to `react-pdf` documentation, `Helvetica-Bold` comes "out of the box".
> 
> ```tsx
> import { Document, Page, StyleSheet, Text } from '@react-pdf/renderer'
> 
> const styles = StyleSheet.create({
>   body: {
>     paddingTop: 35,
>     paddingBottom: 45,
>     paddingHorizontal: 35,
>     position: 'relative',
>   },
>   regular: {
>     fontFamily: 'Helvetica',
>     fontWeight: 400,
>   },
>   bold: {
>     fontFamily: 'Helvetica-Bold',
>     fontWeight: 900,
>   },
> })
> 
> export function TestDocument(): JSX.Element {
>   return (
>     <Document>
>       <Page style={styles.body}>
>         <Text>Regular text</Text>
>         <Text style={styles.bold}>Bold text</Text>
>       </Page>
>     </Document>
>   )
> }
> ```
> 
> <img alt="Screenshot 2024-06-12 at 10 23 55 AM" width="1254" src="https://private-user-images.githubusercontent.com/5702322/339070534-309385ae-79ef-4f88-bc87-d3acd5af1edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjE5NTIsIm5iZiI6MTcyMTc2MTY1MiwicGF0aCI6Ii81NzAyMzIyLzMzOTA3MDUzNC0zMDkzODVhZS03OWVmLTRmODgtYmM4Ny1kM2FjZDVhZjFlZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTkwNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUyNDhlNDAwMDM0ZGIyMDNkZjdiYWYzNWZhMTBmMGQ2ODRhYWFlYjA0ZWU1ZDI5YmEyZjJjYzFjOGZiODU4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EXCLr3dz-DxVfsQng4fPJTQYWonScVn9AGJXladv4PY">

This does not work for us as well, using `Times-Bold`

**Comment by MustehsanGhouri** [comment]
### Working Solution for Text Alignment and Wrapping in `@react-pdf/renderer`

This approach works effectively, allowing you to nest `View` components and manage text styles, alignment, and wrapping.

```jsx
import React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";

const ExampleComponent = () => {
  const styles = StyleSheet.create({
    container: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center", // Aligns text vertically in the center
    },
    text: {
      margin: 6, // Handles spacing between words
      fontSize: 14,
      textAlign: "justify",
      color: "#000000",
      fontWeight: "normal",
      marginLeft: -3, // Adjust margin to align text correctly
    },
    textBold: {
      margin: 6, // Handles spacing between words
      fontSize: 14,
      textAlign: "justify",
      color: "#000000",
      fontWeight: "bold",
    },
  });

  return (
    <View style={styles.container}>
      <Text style={styles.text}>Hello</Text>
      <Text style={styles.textBold}>World</Text>
      <Text style={styles.text}>. Again, I am not bold, WOW</Text>
    </View>
  );
};

export default ExampleComponent;

**Comment by MustehsanGhouri** [comment]
![issue](https://github.com/user-attachments/assets/a9414b19-df79-4d8e-b9c4-c855c105a3a1)

**Comment by l4time** [comment]
Was struggling a lot with this issue.
Even with the solutions given by @jjsmclaughlin @MustehsanGhouri it didn't work properly in many cases.
In some cases I would put a word in bold and there would be line breaks before and after the word for no apparent reasons even when flexDirection: "row" was specified.

For instance with:

      <View style={{ flexDirection: 'row', flexWrap: 'wrap', alignItems: "center", }}>
        <Text style={styles.text}>Hellooooooooooooooooooooooooooooooooooo </Text>
        <Text style={styles.textBig}>Worldddddd.</Text>
        <Text style={styles.text}>And again, I am not bold, WOW</Text>
      </View>

<img width="413" alt="image" src="https://github.com/user-attachments/assets/3ba873d8-ba38-4902-88be-b4d914d04ed1">

The third text tag starts in a new line when there is obviously enough place at the end of the line (using Times-Roman font sizes 14 and 18).
Probably it thinks that the whole sentence "And again, I am not bold, WOW" should fit entirely after the "Worldddd..." string in the same sentence which it cannot.
In order to avoid this we would need to calculate the max number of characters we can fit in a line to split content accordingly.

The quick workaround I use is to put each single word in a Text tag:

      <View style={{ flexDirection: 'row', flexWrap: 'wrap', alignItems: "center", }}>
        <Text style={styles.text}>Helloooooooooooooooo</Text>
        <Text style={styles.textBig}>o</Text>
        <Text style={styles.text}>oooooooooooooooooo </Text>
        <Text style={styles.textBig}>Worldddddd. </Text>
        <Text style={styles.text}>And </Text>
        <Text style={styles.text}>again, </Text>
        <Text style={styles.text}>I </Text>
        <Text style={styles.text}>am </Text>
        <Text style={styles.text}>not </Text>
        <Text style={styles.textBig}>bold, </Text>
        <Text style={styles.text}>WOW</Text>
      </View>

<img width="400" alt="image" src="https://github.com/user-attachments/assets/e3f2d8eb-4b95-44f5-9fa8-905a6f3bc30a">

**Comment by raci-aivy** [comment]
> ### Working Solution for Text Alignment and Wrapping in `@react-pdf/renderer`
> This approach works effectively, allowing you to nest `View` components and manage text styles, alignment, and wrapping.
> 
> ```js
> import React from "react";
> import { Text, View, StyleSheet } from "@react-pdf/renderer";
> 
> const ExampleComponent = () => {
>   const styles = StyleSheet.create({
>     container: {
>       flexDirection: "row",
>       flexWrap: "wrap",
>       alignItems: "center", // Aligns text vertically in the center
>     },
>     text: {
>       margin: 6, // Handles spacing between words
>       fontSize: 14,
>       textAlign: "justify",
>       color: "#000000",
>       fontWeight: "normal",
>       marginLeft: -3, // Adjust margin to align text correctly
>     },
>     textBold: {
>       margin: 6, // Handles spacing between words
>       fontSize: 14,
>       textAlign: "justify",
>       color: "#000000",
>       fontWeight: "bold",
>     },
>   });
> 
>   return (
>     <View style={styles.container}>
>       <Text style={styles.text}>Hello</Text>
>       <Text style={styles.textBold}>World</Text>
>       <Text style={styles.text}>. Again, I am not bold, WOW</Text>
>     </View>
>   );
> };
> 
> export default ExampleComponent;
> ```

Great but what if you have to support different languages with i18n module. I really wonder why that doesn't work

**Comment by ZivojinNedeljkovic** [comment]
Simply add {'\r'} at the end of the Text component's children like so: 

```
<Text>
  This is some text. Some of it is <Text style={{ fontStyle: 'italic' }}>
  italicised{'\r'}</Text>, some made <Text style={{ fontWight: 'bold' }}>bold{'\r'}</Text>.
</Text>
```
I hope this helps

**Comment by egoldfarb-malyavi** [comment]
> Simply add {'\r'} at the end of the Text component's children like so:
> 
> ```
> <Text>
>  This is some text. 
>  <Text style={{ fontStyle: 'italic' }}>italicised{'\r'}</Text>
>  some text
>  <Text style={{ fontWight: 'bold' }}>bold{'\r'}</Text>.
> </Text>
> ```
> 
> I hope this helps

Hi, can you verify that this works? I tried it and it made no difference.

**Comment by JomarMonreal** [comment]
> For future visitors, this is how you can achieve inline styling:
> 
> ```
> <Text>
>   This is some text. Some of it is <Text style={{ fontFamily: 'italic font' }}>
>   italicised</Text>, some made <Text style={{ fontFamily: 'bold font' }}>bold</Text>.
> </Text>
> ```
> 
> This will look something like this:
> 
> > This is some text. Some of it is _italicised_, some made **bold**.

As a visitor from the future, this is exactly what I want! Thanks!

**Comment by enijar** [comment]
This also took me a while to figure out, so dropping here to hopefully save others time

If you have a variable font TTF file, you need to extract the weights into different .ttf files and load the different weights like this:

```tsx
import { Document, Page, Text, StyleSheet, Font } from "@react-pdf/renderer";

Font.register({
  family: "Work Sans",
  fonts: [
    { src: "work-sans-regular.ttf", fontWeight: 400 },
    { src: "work-sans-semibold.ttf", fontWeight: 600 },
  ],
});

const styles = StyleSheet.create({
  text: {
    fontFamily: "Work Sans",
    fontWeight: 400,
  },
  bold: {
    fontWeight: 600,
  },
});

function Example() {
  return (
    <Document>
      <Page size="A4" orientation="portrait">
        <Text style={styles.text}>
          <Text style={styles.bold}>Name:</Text> Jane Doe
        </Text>
      </Page>
    </Document>
  );
}
```
