### ISSUE TITLE
Loading large size pdf on ios will crash

### ISSUE THREAD

**Issue by starInEcust** [diegomura/react-pdf#1641]
**Describe the bug**
When I loading a pdf that pagesize greater than 150.  I can only see pages that are multiples of 11。
For example, page 1 to page 33, page 1 to page 44.

when another pdf pagesize greater then 500.  It must be crash when I scroll to a page that is a multiple of 11。
error message is "null is not an object".
This bug will only occur under IOS webview。

**Screenshots**
<img width="436" alt="截屏2021-12-14 下午6 28 14" src="https://user-images.githubusercontent.com/5434131/145981115-5a8f2531-a9bd-4ba5-b467-43c41f9465c0.png">
<img width="435" alt="截屏2021-12-14 下午6 28 36" src="https://user-images.githubusercontent.com/5434131/145981122-19d6c263-089e-40b5-b345-91ca9f05c012.png">
<img width="444" alt="截屏2021-12-14 下午6 28 45" src="https://user-images.githubusercontent.com/5434131/145981126-2e3b71ff-bc7b-4f93-8ecf-a05816411c8a.png">

**Desktop (please complete the following information):**
 - OS: ios 14 - 15
 - Browser： ios webview
 - React-pdf version [5.5.0]

**Comment by jeetiss** [comment]
> React-pdf version [5.5.0]

looks like you confused the repo. there is for `@react-pdf/renderer` and it have not had fifth version yet

please move your issue to https://github.com/wojtekmaj/react-pdf

**Comment by starInEcust** [comment]
Many thanks for your help. problems solved.
