### ISSUE TITLE
debug attribute throws: Error: unsupported number: NaN

### ISSUE THREAD

**Issue by ctsstc** [diegomura/react-pdf#1647]
**Describe the bug**
When adding the `debug` attribute to a component with margin auto it throws: 

```
Error: unsupported number: NaN
```

**To Reproduce**

[Repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634ad0049467e0c43cd11e35339245381550bce085b606c00220cbbb3880c80473a834008cb25abc4f8ef2786406941d3ed561879020f8c331a8c6eb208021e46528054619c1f0f1e2005ba802044201811c005c352c1416c3c282b49a2d18280c04a24300900067ea90860185a9d979bcaa4d8568e1e23040102a798904a1e088f8549a2c89e9444121ea98047355a1d2e8f49e7b1cb9a865712ac930fa7536a6000516a821aa22644f16c86f649bba3c000d21a18422a580408c793f860119800290762a744662adb3318371b3479388c04374a9650c231e2548056036480d8935aee9812a556ac956129105f674005ead160c078d024088c4b610307acdebe0f09ddb0582083917a093aa8e16a80604289d3639337f12866b21800154c0ad1020f5958557aa608c0021db6b6c056b969d8fdb18093c1882abe23c8151adbb79b611b74663064a12cad9aef192cd1b6cf2b34f044037bc8d63ca8193a622b0229f6087de899bea06f66a8005fd53c4aaa46481c64d0f00023f58ca8204cae1ab251603aa103a139a509c9628c0d61e8e18c99830391b60ec86962f5b44899723c3eece8acfe340cd99e5b9749e809c30f06193a4d06ccb37a983068f8885d9b6fa72c9eaeea277aad0b46db38660b26da72c30206db91ac020cbbc16c8804ea304804072b069052835859580b0c270cc5a74ad04058398e0132287a9ee4c00660e33120be9528053ace046fbae8600d6c2b545263e5f8c0eeab4b293e4b2d95fba5fe6b9b3bf8ac1ce42bd5c3080d195193b71d056071a0e1804ee97d9f041954719505d672876cd872b2a96507c42d176c1b96bd8402493a2c040038b4e972cf3b008b96e728c0502463c3a5eca962a8d84cbee0018ad8c163df6776af61a6012cd030e4e836979526e641bc9744b375bdad16870acc534a0096620a0fcb54fe2f273925abaa3debbe9c51d602d4532adc388320000dc301f04cb54a7128b617abb8fa42aca0b2adeca3e5dbeeba9d83d8d8bc8facf88d98395dd8ac0ab462c24672e1abaad4638c054a20662ab781ed3db398a8e94462cc79e94823842d74483761ebc1933ddca68d08b40580d554998c037df20b00428eee9eda5ad82fb80a2b924cbde4981d414c8714222ae5592dbd0ed25cd0b4a70d47a82574fc449b0a2a53a773fb2ca89f4326b1b038ca4370fdd74ca1d0135d1609b1b7a4caf27f9280025cac719275f9aac377175bc4eebdded965762bde6964fb01270be8a8a98e88c8b239102000724c27bf62442c1bd921e0122d9abfaf76306f74b2222f0021b6aa110d82907813a0001800241232f181af519d80e064300bfa7eaa17ccc2a807e4f0080386702815c0c068487132200f70990e8030660ac1d80101a6640c807d700501643f83e0c15302d83de1c065247210748003900079080c11551284a15c5862bc2a1e60a0140788100690640c88e0705c83e0b5cca30059068c322fc794f42441280c81b081000660c800134003eb68000d2000d4001b0800001c001d44006c79007894028c60aa200068004e1e0001041c5da2808e1285906be182c82f1028370700c0000ca630026580c0b83dd8040c0243282281507482421c7224a1b93b16d0201e21d20510015998650249292f800021740f75181d21d13931275802900025728ad6ea22132654ca0aa1986e2310f130e3f0d60012900760c07480013000165c9775f60389100b0c0150e00314ec130ee93823e973110142600d0ba10c3dc6b4e61b6c52ad82e99a07a5403e9032e9102219e33ed140299332e642cdb04b33429c5b0042c03148e1918e908c8000ccc2da4702c4389ca20c9800924e4e0f39e0a813e8f196f23e550db62005e6705e1d79c71514b9d73966b0559e42a86d0e918c238102ca0b738e6e62c5b326015cf19a726165cb198716e7dcbe0b4b287937ec8e0841a2ca0a720940e0d9943b41dc330b10001283d300bb260392980df004152ca088aa8968bb02235525c969d4bde5513a9df41a59f4b97f201592e61961ac1d81554e1a17f4d85b8b5e4d2af9a538679acd06cba6472c795859e78cd009488e66c866180f9602e616fc3f86f5b5a584e994700c8be402a4f4981f95dade90ea7178cc50df2ca4c00511eb38188470500e9116ca0df4f83b0f2d3732677ace5f32fd7a6c0d330a8686f0d16a3c7a0cc192aac0c42e03403e9e0ede760f01505d46800d3421ed400000)

**Expected behavior**
It should not crash when trying to debug.

**Screenshots**

Shows how it tries to subtract auto from a number yielding `NaN`

![image](https://user-images.githubusercontent.com/416814/146474919-4e67e831-e62d-4c95-8cf1-b2a66411d3c1.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - React-pdf version: `v2.0.21`

**Comment by ctsstc** [comment]
I'm not sure if this is related to why I cannot seem to set a font size without the layout/margin/spacing breaking.

When I set the font size on the element after it, all the spacing seems to break.

## Before Font Size
![image](https://user-images.githubusercontent.com/416814/146475285-8004ea34-1781-46fb-99a5-91f845d45713.png)

## After Font Size

Seems to be spacing everything out.

![image](https://user-images.githubusercontent.com/416814/146475396-6ede3b17-1ba4-46b9-b95d-219990fcc124.png)

**Comment by ctsstc** [comment]
Awesome I appreciate the quick PR up already @jeetiss 

Do you know if the odd spacing occuring after I add a `font-size` is potentially related? It seems to be around the elements that have `margin: auto`. I'm going to try flex today for centering instead and see if that helps.

**Comment by ctsstc** [comment]
I can now confirm that removing `margin: auto` and instead using `display: flex` with `alignItems: 'center'` resolves the weird spacing issue on the `margin: auto` elements after I tried to add a `fontSize` to a sibling of the same parent.

**Comment by jeetiss** [comment]
That happens because `margin: auto` adds space in all directions to top and bottom.

you can try `margin: 0 auto`, but it doesn't work and that is a well-known bug that is fixed in 
https://github.com/diegomura/react-pdf/pull/1535

**Comment by ThePiyushAggarwal** [comment]
I was getting a similar error. Instead of NaN, I was getting -Infinity.
I had to remove the textAlign: 'right' which wasn't even working.

**Comment by EvHaus** [comment]
Looks like this is still a bug. Link to REPL [here](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e54024a37e183b0ca004c30023047db006f28009c10600bed2674009e006c31ad51235f246000c860066500170c00e43c114106e75e999c101ac0d8004400f448120210e1008ec80056e818008c007489000e7ca1fa94e14222e1bc024554e1740cccacec0400dc6464004a183cc0505c340062e91a2cf21a785488a82930850d64400000).
