### ISSUE TITLE
Rendering fonts is broken

### ISSUE THREAD

**Issue by nojvek** [diegomura/react-pdf#1649]
**Describe the bug**
Tried loading Inter ttfs (via url, via local.ttf, via file-loader, ttf-loader, raw-loader). 

It doesn't render all the characters. Always broken. I read a bunch of other issues related to this but still doesn't work. Spent about 4 hours fighting this. Please help.

```ts
import { Font } from '@react-pdf/renderer';
import InterRegular from '../fonts/Inter-Regular.ttf';
import InterSemiBold from '../fonts/Inter-SemiBold.ttf';

export const registerFont = () => {
  Font.register({
    family: 'Inter',
    fonts: [
      {
        // src: 'https://assets.recurrency.com/fonts/Inter/Inter-Regular.ttf',
        src: InterRegular,
        fontWeight: 400,
      },
      {
        // src: 'https://assets.recurrency.com/fonts/Inter/Inter-SemiBold.ttf',
        src: InterSemiBold,
        fontWeight: 600,
      },
    ],
  });
};
```

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
Fonts render. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1018196/146632088-04fbc37d-7718-4295-953c-16db16932ab4.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome
 - React-pdf version [1.6.13

**Comment by muyanli** [comment]
Have similar issue, rendering font doesn't work
![image](https://user-images.githubusercontent.com/50149228/150809712-f4f1a5c3-fa91-492e-9508-db9b2cbdd555.png)

**Comment by joggienl** [comment]
I've experienced the same kind of problem of fonts not rendering (correctly). The fix for me was to use `renderToStream` in stead of the `renderToString` method (on a NextJS project).

**Comment by tom2strobl** [comment]
I had the issue of fonts being missing in a PDF and after fiddling around for a couple of hours I noticed that `renderToString` gives a **COMPLETELY** different output compared to renderToFile.

`renderToFile` yields this https://gist.github.com/tom2strobl/ef96d3a64e2fdd0e7e7c47b862a0f713
`renderToString` yields this https://gist.github.com/tom2strobl/e3eb16cce5f6d7e7ba629689daba3871

note for example the fonts being embedded into the file and on the `renderToString` helvetica popping up out of nowhere and the body of the pdf being completely different as well.

**Comment by joggienl** [comment]
So basically the `renderToString` does not embed the font as `renderToStream` and `renderToFile` do. This might be what @nojvek is experiencing as well.

I have not looked at the source code to either confirm this but it seems to be the case indeed.

**Comment by tom2strobl** [comment]
So in my case I'm using electron and render the pdf in the main (node) thread to not block the ui thread and need to send the result back and forth via RPC calls. If it helps anyone, I reserted to buffering the ReadbleStream from `renderToStream` and sending over the buffer as Base64 to the client and it works, although I gotta test it with big documents.

```typescript
async function stream2buffer(stream: NodeJS.ReadableStream): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const buf = Array<Uint8Array>()
    stream.on('data', (chunk) => buf.push(chunk))
    stream.on('end', () => resolve(Buffer.concat(buf)))
    stream.on('error', (err) => reject(new Error(`error converting stream - ${err}`)))
  })
}
async function someAsyncFunctionThatIsUsedInAnAsyncRPCCall() {
  const stream = await renderToStream(Document)
  const buffer = await stream2buffer(stream)
  return buffer.toString('base64')
}
```

What's strange, is that `renderToStream` is practically just https://github.com/diegomura/react-pdf/blob/ca360e0f7e0f2640c002968135bd939dafd86a03/packages/renderer/src/node/renderToStream.js#L5

And `renderToString` is practically just https://github.com/diegomura/react-pdf/blob/ca360e0f7e0f2640c002968135bd939dafd86a03/packages/renderer/src/node/renderToString.js#L5

off the same `pdf(element)` call. 🤔 

Maybe the `toString` serialization has unintended side-effects?
