### ISSUE TITLE
No such code example provided for running pdf on node.js 

### ISSUE THREAD

**Issue by binjahid** [diegomura/react-pdf#1657]
I really appreciate that you guys have a code example for running react pdf on client which is really declarative and easy to understand every process, like : https://react-pdf.org/repl
But there is no declarative example provided for node.js that why i am really facing difficulties  to run react pdf on node.js server. Actually i am traying to make an API endpoint, on that particular endpoint i want to render the pdf i have created,
could you guys suggest me how can i achieve this functionality?

**Comment by jeetiss** [comment]
Hi @binjahid

I added a benchmark that works in node js. it not exactly what you want but it should help to understand how to work with react-pdf in node js

- https://github.com/diegomura/react-pdf/pull/1644

**Comment by jeetiss** [comment]
this is a minimal setup to run react-pdf on node.js
https://github.com/machinsk/react-pdf-renderer-server-example

**Comment by Qurishe** [comment]
@jeetiss I tried the repo, i have express server but when i try to import my ReportViewer Component it gives me the following error!
![image](https://user-images.githubusercontent.com/32069358/189483648-82e53bee-1ea5-4b50-a4c9-ab56c41b7d98.png)

**Comment by Qurishe** [comment]
Do i have to setup babel?
