### ISSUE TITLE
PDFViewer  option showToolbar="false" doesnot work

### ISSUE THREAD

**Issue by krushna-cruxbyte** [diegomura/react-pdf#1663]
**Describe the bug**
I am using PDFViewer to display the created pdf doc. I want to hide the toolbar in the pdf viewer. I have set the option showToolbar="false" but in vain. 

**To Reproduce**
"< PDFViewer width="1000px" height="600px" showToolbar={false}>
                ....
</ PDFViewer >"

**Expected behavior**
 I want to hide the toolbar in the pdf viewer. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [chrome, firefox]
 - "@react-pdf/renderer": "^1.6.17",

**Comment by Krishna00001** [comment]
I am facing the same issue.        <PDFViewer showToolbar={false} style={{ width: "100%", height: 800 }}>
It doesn't work on chrome

**Comment by ap-1** [comment]
This bug still exists on Firefox 117.0b5

**Comment by RiccardoElisabetti** [comment]
2 years have passed and nobody has found a solution?

**Comment by diegomura** [comment]
I'm seeing the expected behaviour in chrome and brave. Firefox default PDF rendering works differently and there's no way this lib can change that. [Here's something you can try](https://support.mozilla.org/en-US/questions/1119523)
