### ISSUE TITLE
Error: Could not resolve font for 'font that try to register', fontWeight 400

### ISSUE THREAD

**Issue by mikica6** [diegomura/react-pdf#1665]
**Describe the bug**
I need latinic letters in my project. I tried register Roboto and Calibri font and some others as it is defined in react-pdf documentation but it doesn't render pdf and throws this error.
I tried everything others sugested here but it throws always this same error.
I use react js

**Expected behavior**
I expected that I will have document with latinic letters but instead I have blank page in Browser and this error

**Screenshots**
![error](https://user-images.githubusercontent.com/96483805/147919595-c5535d6a-cb8b-41f6-9c73-6fa310354434.PNG)

What I tried:
1.
  import Roboto from "../../../assets/fonts/Roboto-Regular.ttf/Roboto-Regular.ttf"
  
  Font.register({
      family: 'Roboto',
      format: 'truetype',
      src: Roboto
  });
  const styles = StyleSheet.create({
      page: {
          fontFamily: "Roboto",
          paddingTop: 15,
          paddingLeft: 15,
          paddingRight: 15,
          lineHeight: 1.5,
          flexDirection: 'column',
      }
      })
2.
  Font.register({
      family: "Roboto",
      src:
          "https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf"
  });
  const styles = StyleSheet.create({
        page: {
            fontFamily: "Roboto",
            paddingTop: 15,
            paddingLeft: 15,
            paddingRight: 15,
            lineHeight: 1.5,
            flexDirection: 'column',
        }
        })
I try same for Calibri, and for NotoSans-Regular and always get same error: Could not resolve font for Roboto/Calibri/NotoSans-Regular , font Weight 400 react-pdf

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome and Mozilla Firefox
 - React-pdf version: v2.0.21

Thank you in advance for any suggestions!

**Comment by mgoldenbe** [comment]
I am experiencing a similar problem, only in my case I downloaded the font, so it's not working even though the font is local

**Comment by mikica6** [comment]
@mgoldenbe I also downloaded font and use it local.
I just made it work. Yeeeeej

Problem was that inside Page tag I have few components and I used Helvetic font at the beginning and I styled those components with:
 invoiceDate: {
            fontStyle: 'bold',
    },
It seems that this is problem because it couldn't resolve _font Style: bold_. I delete those from all components and register Roboto and Roboto Bold and where I need bold I use :
  invoiceDate: {
           fontWeight: 600,
    },
    and everything works now.
    This is mine code:
    import Roboto from "../../../assets/fonts/Roboto/Roboto-Regular.ttf";
import RobotoBold from "../../../assets/fonts/Roboto/Roboto-Bold.ttf"

Font.register({
    family: 'Roboto', fonts: [
        { src: Roboto }, 
        { src: RobotoBold, fontWeight: 600 },
    ],
    format: 'truetype',
});

Hope this will help you too :)

**Comment by mgoldenbe** [comment]
It was the same problem for me. It would save people much time if the error messages were more informative.

**Comment by DavidPopa** [comment]
> I'd like to chime in since I was stuck for a day on this and I just figured out what I was doing wrong.
> 
> 1. I wasn't using `StyleSheet.create()` to define the object used for my stylesheet. I don't know if this contributed to the issue but I switched to using it.
> 2. My stylesheet originally looked like this:
> 
> ```js
> const stylesheet = StyleSheet.create({
>   'p, li': {
>     fontSize: 12,
>     marginTop: 0,
>     marginBottom: 0,
>     fontFamily: 'Roboto',
>   },
> });
> ```
> 
> And I found changing it to this and referencing it as `stylesheet.text` helped things:
> 
> ```js
> const stylesheet = StyleSheet.create({
>   text: {
>     color: '#212121',
>     fontFamily: 'Roboto',
>     textAlign: 'justify',
>     'p, li': {
>       fontSize: 12,
>       marginTop: 0,
>       marginBottom: 0,
>       fontFamily: 'Roboto',
>     },
>   },
> });
> ```
> 
> 3. I couldn't use a google font, so I just downloaded them, included in the project and registered like so:
> 
> ```js
> import Roboto from '@shared/fonts/Roboto-Regular.ttf';
> import RobotoItalic from '@shared/fonts/Roboto-Italic.ttf';
> import RobotoBold from '@shared/fonts/Roboto-Bold.ttf';
> import RobotoBoldItalic from '@shared/fonts/Roboto-BoldItalic.ttf';
> 
> Font.register({
>   family: 'Roboto',
>   fonts: [
>     {
>       src: Roboto,
>     },
>     {
>       src: RobotoBold,
>       fontWeight: 'bold',
>     },
>     {
>       src: RobotoItalic,
>       fontWeight: 'normal',
>       fontStyle: 'italic',
>     },
>     {
>       src: RobotoBoldItalic,
>       fontWeight: 'bold',
>       fontStyle: 'italic',
>     },
>   ],
>   format: 'truetype',
> });
> ```
> 
> Hope this helps anyone else landing here!

It helps a lot, thx mate, thx, after a few hours i finally do it, thx a lot
