### ISSUE TITLE
Text `align` style property should be `textAlign`

### ISSUE THREAD

**Issue by rclai** [diegomura/react-pdf#167]
I noticed that the text alignment style property is called `align`, shouldn't it be `textAlign` in order to match CSS standards?

https://github.com/diegomura/react-pdf/blob/75e9b5241855cc67dbf743bebede7b462d761258/packages/react-pdf/src/elements/Text.js#L121

**Comment by diegomura** [comment]
Good catch. I agree. I can address this on a few days or feel free to create a PR for that. I would like to still support ‘align’ and maybe show a warning for compatibility purposes
