### ISSUE TITLE
Font.register() method is not recognized by my IDE and behaves strangely.

### ISSUE THREAD

**Issue by Steelcrow-test** [diegomura/react-pdf#1675]
**Describe the bug**
When i invoke .register() method of imported "Font" object, my IDE (Webstorm 2021.2) says that no such method exists, more so - "Font" has no available methods at all, even though Constant type checks out (typed as Interface "FontStore"). 

If i choose to ignore my IDE's warnings and use that method, it actually works, albeit in a way i can't comprehend: if i use component PDFDownloadLink, resulting PDF seems to be generated just fine, with registered fonts used; on the other hand, using PDFViewer component produces PDF without any custom fonts at all.

Also, there's some even weirder behaviour: when i experimentally delete PDFDownloadLink, PDFViewer stops working too.

There's certainly some error on my side that leads to such a behaviour, but i don't know where i failed. Hope someone can help me figure it out.

**To Reproduce**
1. Install WebStorm 2021.2 and update it to latest patch (i so happened to update mine the day before 2021.3 came out). I'm not sure IDE is at fault, though.
2. Make new React project.
3. If you are trying to reproduce this situation without Webstorm, then use latest version of create-react-app (react 17.0.2, react-dom 17.0.2, react-scripts 5.0.0). 
4. Install @react-pdf/renderer
5. Prepare some sample document component and means of rendering it (preferrably another component with both PDFDownloadLink component and PDFViewer component). You can use sample code i presented in my post.
5. Import Font from @react-pdf/renderer
6. Type "Font." and see if IDE shows any available methods.
7. Import some external font and use it to style the document.
7. Render download link and/or PDFViewer components. Download document via link and compare resulting PDF styling.
8. Try to delete download link from code and see if PDFViewer is still working.

If you need code example then you can use example code from react-pdf.org quick setup page.

**Expected behavior**
After you import Font constant, it won't have any methods available.

**Screenshots**
![Screenshot of invoking register method in IDE](https://user-images.githubusercontent.com/83637179/148960940-3edc7c00-9620-4ce3-82b0-939cb46d986a.png)

**Code samples (will contain Cyrillic symbols):**

PDF document component:
```js
import {Page, Text, View, Document, StyleSheet, Font} from '@react-pdf/renderer';
import myFont from '../../../Static/Roboto-Regular.ttf';

//Fonts registration
Font.register({ family: 'myFont', src: myFont })

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'row',
        backgroundColor: '#E4E4E4',
        fontFamily: 'myFont'
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: 0
    },
    tableSection: {
        border: '1pt',
        borderStyle: 'solid',
        borderColor: 'black'
    },
    sectionAlignRight: {
        selfAlign: 'flex-end'
    },
    sectionAlignCenter: {
        selfAlign: 'center'
    }
})

// Create Document Component
const JudgeRecordCard = (props) => (
    <Document>
        <Page
            size="A4"
            orientation={"landscape"}
            style={styles.page}
        >
            <View style={styles.section}>
                <Text>Section #1</Text>
            </View>
            <View style={styles.section}>
                <Text>Секция 2</Text>
            </View>
        </Page>
    </Document>
)

export default JudgeRecordCard
```

PDF download link jsx (there's some routing code there that's not required for that example so i cut it out):
```js
import {PDFDownloadLink, PDFViewer} from "@react-pdf/renderer";
import JudgeRecordCard from "./Components/PrintForms/JudgeRecordCard/JudgeRecordCard";
...                       
return (
    <div
        style={{height: '100vh', width: '100%'}}
    >
        <PDFDownloadLink document={<JudgeRecordCard />} fileName="somename.pdf">
            {({ blob, url, loading, error }) =>
                loading ? 'Loading document...' : 'Download now!'
            }
        </PDFDownloadLink>
        <PDFViewer
            width={'100%'}
            height={'100%'}
        >
            <JudgeRecordCard />
        </PDFViewer>
    </div>
)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox 95.0.2 (x64)
 - React-pdf version: 5.6.0

**Comment by diegomura** [comment]
Types were wrong. This should be already fixed
