### ISSUE TITLE
Use the official react-reconcilier

### ISSUE THREAD

**Issue by crubier** [diegomura/react-pdf#168]
When using react-pdf with the latest react version 16.2, I end up with this error:

```
Failed to rebuild.
./node_modules/@react-pdf/core/lib/renderer.js
Module not found: Can't resolve 'react-dom/lib/ReactFiberReconciler' in 'myProject/node_modules/@react-pdf/core/lib'
```

I think this project should use the official react-reconcilier

https://github.com/facebook/react/tree/master/packages/react-reconciler

**Comment by diegomura** [comment]
Yes! Thanks. It’s been awhile I want to do this. I will be adressing this very soon
