### ISSUE TITLE
Image not showing in pdf

### ISSUE THREAD

**Issue by Aashu-007** [diegomura/react-pdf#1684]
hey there, I made a document with texts and image, but Image is not getting displayed while all other texts are getting displayed in the pdf. please help. 
This is my code below : 
`<Document>
				<Page size="A4" style={styles.page}>
					<View>
						<Text style={styles.title}>{plantData.LocalName}</Text>
						<View>
							<Image src={plantData.ImgUrl} />
						</View>
						<View>
							<Text>Local Name : {plantData.LocalName}</Text>
							<Text>
								Scientific Name : {plantData.ScientificName}
							</Text>
							<Text>Types : {plantData.Types}</Text>
							<Text>
								Distribution Name : {plantData.Distribution}
							</Text>
							<Text>Parts Used : {plantData.PartsUsed}</Text>
						</View>
						<Text style={styles.subtitle}>Description</Text>
						<Text style={styles.para}>{plantData.Description}</Text>
						<Text style={styles.subtitle}>Uses</Text>
						<Text style={styles.para}>{plantData.Uses}</Text>
					</View>
				</Page>
			</Document>`

**Comment by jeetiss** [comment]
Hi @Aashu-007 
Could you please provide a repl at https://react-pdf.org/repl
