### ISSUE TITLE
dynamic image from backend showing cors Error

### ISSUE THREAD

**Issue by Abdul-aziz-shuvo** [diegomura/react-pdf#1686]
// <Image
                                //     source={{ uri: 
                                    `${process.env.REACT_APP_URL_BASE}/images/application/${file?.application_id}/${file?.file_path}`}} 
                                />

                                // <Image
                                //     src={`${process.env.REACT_APP_URL_BASE}/images/application/${file?.application_id}/${file?.file_path}` + '?noCache=' + Math.random().toString()}
                                //     source={{
                                //         headers: {
                                //             'Access-Control-Allow-Origin': '*'
                                //         }
                                //     }}
                                // />

                                // <Image key={key} style={styles.img}
                                //        src={file.path + '?noCache=' + Math.random().toString()}
                                //         source={{
                                //             headers: {
                                //                 'Access-Control-Allow-Origin': '*'
                                //             }
                                //         }}
                                // />

                                // <Image  key={key} style={styles.img} src={{ uri: `${process.env.REACT_APP_URL_BASE}/images/application/${file?.application_id}/${file?.file_path}`, method: 'GET', headers: {}, body: '' }}/>
                             
                                // <Image
                                //     src={`${process.env.REACT_APP_URL_BASE}/images/application/${file?.application_id}/${file?.file_path}`}
                                //     source={{
                                //         uri: `${process.env.REACT_APP_URL_BASE}/images/application/${file?.application_id}/${file?.file_path}`,
                                //         method: "GET",
                                //         headers: {
                                //              "Cache-Control": "no-cache",
                                //             "Access-Control-Allow-Origin":"*",
                                //             'X-XSRF-TOKEN': token ,
                                //             'Content-Type': 'image/jpeg',
                                //             'Access-Control-Allow-Credentials': 'true'
                                //         },
                                //         body: ''
                                // }}
                                //         />

                                <Image src={{ uri: `${process.env.REACT_APP_URL_BASE}/images/application/${file?.application_id}/${file?.file_path}`, method: "GET", headers: { "Cache-Control": "no-cache" }, body: "" }} />

i tried all of the above solution and nothing is working for me.it just keep showing cors error but my cors configuration is ok.bcz my other component images from backend is working fine , only react pdf image showing cors error. if anyone know how to fix this please help

**Comment by Abdul-aziz-shuvo** [comment]
can anyone help me?

**Comment by jeetiss** [comment]
Hello @Abdul-aziz-shuvo

You have to set up `"Access-Control-Allow-Origin":"*"` header at the backend side

this is unsplash image that works fine with react-pdf:

![car](https://images.unsplash.com/photo-1624976172336-54d765427b6b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FyJTIwcG9ydHJhaXR8ZW58MHx8MHx8&w=1000&q=80)


These are headers that are set for each response:
```
curl -i 'https://images.unsplash.com/photo-1624976172336-54d765427b6b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FyJTIwcG9ydHJhaXR8ZW58MHx8MHx8&w=1000&q=80'
HTTP/2 200 
last-modified: Tue, 25 Jan 2022 08:46:08 GMT
cache-control: public, max-age=315360000
server: imgix
x-imgix-id: 0c45b640b3db519a1c9cc01b6d01ed9c523de3ab
date: Wed, 26 Jan 2022 14:17:39 GMT
age: 106290
accept-ranges: bytes
set-cookie: ugid=093ade752421cbfa0347755df3a88cb75477355;domain=.unsplash.com;path=/;expires=Thu, 26 Jan 2023 14:17:39 GMT;SameSite=None;Secure
content-type: image/jpeg
access-control-allow-origin: *
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
x-served-by: cache-sjc10023-SJC, cache-bma1668-BMA
x-cache: HIT, HIT
content-length: 140112
```

**Comment by Nutriadmin** [comment]
what about images loaded from an external site, where you cannot change their CORS configuration? Is there a way to handle that scenario?
