### ISSUE TITLE
Position relative is not working

### ISSUE THREAD

**Issue by all2pie** [diegomura/react-pdf#1691]
**Describe the bug**
`position: 'relative'` is not working properly

**To Reproduce**
[Reproduction](https://react-pdf.org/repl?code=3187b0760ce02e00400a20812ca4f0c0bc30050129301f0e0140c3003c00888c00ae02d80a661406964570086039a3334009e006d18600de434440074f4b9230017cd870ee401a924601dc0541163241e93344033282bc807a2dbb55a8af6f54a36f64027243c00595c727676d57137730d9002310000f251800134648da1e09284f5a466b3b10c0f55c8776325b6e3e475b6a3a2616365c006e6226d048580f4c18006530cedf46462819604f462e28466c71767945002e1829b568cf24cf798072004600071881106124049848e12e60006b75801a62c4a4086db3c10df351189bbbb7c618ca2411e02a1c01b4f080749f3536d102834180418c33aa0006e8c084c094b732058a0f34587122e70b8f141b43002400c207101ac60eb50608b8c253964d1646f8c5e69b76063d8de3f0e216770265d892052452a934f5b13fa60564c1d99cee6624eb15c50b09a2f165384d4f8425e57d1f3f9e6005600030aac83a239417c66cb5dc005e0049324fd398ec87428170da571221003ad1c6f2ec7cdcddcf6346940d26800954680b825000623211bbb3cd87202190be980d80871a00)

**Desired Behavior**
The box should show relative to the main container ( on the far left side )

**Comment by jeetiss** [comment]
`react-pdf` uses [yoga layout](https://yogalayout.com/) for `flex-box` and `position` emulation and it doesn't have `position: static;` all nodes are `relative` or `absolute`, so you can set position only relative to the parent node. 

check the issue at yoga repo https://github.com/facebook/yoga/issues/787
