### ISSUE TITLE
How to pass dynamic data in PDF using @react-pdf/renderer

### ISSUE THREAD

**Issue by jaintarun268** [diegomura/react-pdf#1696]
I am building an electron app that allows user to auto populate a PDF based on some data pulled from an internal server. I'm trying to use @react-pdf/renderer for displaying and creating the PDF.

I've been using these two pages primarily for information related to the topic. [On the fly rendering Dynamic content](https://react-pdf.org/advanced#dynamic-content)

I'm pass a API data using props to PDFfile.js 

**Index.js**

```
import React, { useEffect, useState } from 'react';
import { PDFDownloadLink, PDFViewer } from '@react-pdf/renderer';
import PDFDOC from "./PDFDOC"

const IndexPage = (props) => {
	return (
		<PDFDownloadLink
		document={<DownloadSalary data={apiResSelector} />}
		fileName="somename"
		>
		{({loading}) => loading ? "loading data...." : <button className="btn btn-blue" type="button"> Export PDF </button>}
		</PDFDownloadLink>
	)
}

export default IndexPage
```

PDDfile.JS
```
import React, { useEffect, useState } from 'react';
import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
    page: {
        flexDirection: 'row',
        backgroundColor: '#E4E4E4'
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1
    },
    pageNumber: {
        position: 'absolute',
        fontSize: 12,
        bottom: 30,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: 'grey',
    },
});

const PDFFile = (props) => {
    const api = new Api();
    const pdfDAta = props.data
    return (
        <Document>
            <Page size="A4" wrap={false}>
                <View style={styles.section}>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">First</th>
                                <th scope="col">Last</th>
                                <th scope="col">Handle</th>
                            </tr>
                        </thead>
                        <tbody>
                            {pdfDAta && pdfDAta.map((data, index) => {
                                return (
                                    index < 2 ?
                                        <tr key={index}>
                                            <th scope="row">{data.id}</th>
                                            <td>{data.name}</td>
                                            <td>{data.salary}</td>
                                            <td>{data.total_salary}</td>
                                        </tr>
                                        : null
                                )

                            })}

                        </tbody>
                    </table>

                    <Text style={styles.pageNumbers} render={({ pageNumber, totalPages }) => (
                        `${pageNumber} / ${totalPages}`
                    )} fixed />
                </View>
            </Page>
        </Document>
    );
}

export default PDFFile;
```

I'm hoping that someone more experienced with the library can assist me with understanding how to pass dynamically data in the PDF.

**Comment by esdrasjnr** [comment]
@jaintarun268 I'm not 100% sure about it, but I believe that right is not possible to update your PDF in a reactive way by the library. I think the way is to force your PDF wrapper to re-render it every time some data changes...

By now I'm also doing it in my project, hope it helps you. If someone has a better idea, I will be glad to hear 😃

**Comment by Milankorangi** [comment]
**please use pdf() from react-pdf/render**

import { pdf } from "@react-pdf/renderer";
import * as FileSaver from "file-saver";

                const generatePdfDocument = async (csvReport, ReportsDownload, fileName) => {
                    const blob = await pdf(
                        <PdfDocument csvReport={csvReport} ReportsDownload={ReportsDownload?.data}/>
                    ).toBlob();
                    FileSaver.saveAs(blob, fileName);
                };

                generatePdfDocument(csvReport, ReportsDownload, fileName);

**Comment by maitedev** [comment]
Hello, here I bought a solution that worked for me, I hope it helps you.                                                                                                        `import React, { Component } from "react";
import { connect } from "react-redux";
import { pdf } from "@react-pdf/renderer";
import { saveAs } from "file-saver";

const tableColumns = [
  {
    title: "Item",
  },
  {
    title: "Size",
  },
  {
    title: "Qty",
  },
  {
    title: "Cost",
  },
  {
    title: "Total Cost",
  },
];

class PDFViewerButton extends Component {

  handleDownloadPDF = async () => {
    try {
      const responseData = await this.props.getData({
        activeObject: "rx",
        searchParameters: {
          service_id: service_id,
          patient_id: patient_id,
        },
      });

      const foundObjects = responseData.data?.foundObjects || [];

      if (foundObjects.length > 0) {
        return foundObjects;
      } else {
        this.props.updateModalVisibilityShow("modal_alert", {
          title: "No Data Found",
          message:
            "We're sorry, but there is no data available to generate the report at the moment.",
        });
      }
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  render() {
    return (
      <Button
        onClick={async () => {
          try {
            const data = await this.handleDownloadPDF();

            if (data) {
              const doc = (
                <MyPDFDocument data={data} tableColumns={tableColumns} />
              );
              const fileName = `somename.pdf`;
              const asPdf = pdf([]);
              asPdf.updateContainer(doc);
              const blob = await asPdf.toBlob();
              saveAs(blob, fileName);

              // Open the PDF in a new tab
              const pdfUrl = URL.createObjectURL(blob);
              window.open(pdfUrl, "_blank");
              URL.revokeObjectURL(pdfUrl);
            }
          } catch (error) {
            console.error("Error generating PDF:", error);
          }
        }}
      >
        PRINT
      </Button>
    );
  }
}`
