### ISSUE TITLE
ReactPDF.Image is not rendering base64 images

### ISSUE THREAD

**Issue by Olivr3** [diegomura/react-pdf#1698]
**Describe the bug**

 ReactPDF.Image component is not rendering base64 images. 

I am able to see the images using <img src="..." /> but not using <Image source="..." /> from the lib. 

**To Reproduce**

Try rendering base64 images using ReactPDF.Image. 

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

See images in the PDF document.

**Screenshots**

 
![Screen Shot 2022-01-28 at 6 45 11 PM](https://user-images.githubusercontent.com/20702895/151630076-506614dc-a65a-44a4-9c8e-2d744593bff6.png)
![Screen Shot 2022-01-28 at 6 45 24 PM](https://user-images.githubusercontent.com/20702895/151630086-1fba1a8c-a931-4b0c-8ae2-4dfd60cdd4d6.png)
![Screen Shot 2022-01-28 at 6 46 48 PM](https://user-images.githubusercontent.com/20702895/151630089-223fb5f7-9300-4f87-8cf2-82b36a923a07.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by 03127346118** [comment]
did you find solution?

**Comment by psilvaricardo** [comment]
did you find a fix for this?
