### ISSUE TITLE
Production Mode is laggy

### ISSUE THREAD

**Issue by yashu2001** [diegomura/react-pdf#1701]
First off thank you for this amazing library.

I am using the renderer package and ran into an issue where my react app lags when used in production mode.

I tried using the same build locally but it works fine.

To explain my use case more:
We are looking to implement a live invoicing feature in our order management system and so as and when information is typed the PDF is expected to rerender, I understand this is a lot of state updates but it works flawlessly in development mode.
Do let me know if you need more info.

**Comment by petr-motejlek** [comment]
Funny thing is, I tried a similar thing, and the page was lagging so hard (for seconds) even in dev mode, whenever a change was made, that I scrapped the idea.

Now, I have a modal component that opens when a user clicks a button to download the PDF and the modal components actually renders the PDF as the modal renders. So, they do have to wait a bit, but at least the page doesn't lag when they work with it.

Strange thing is, if you close the modal, boom, a lag as well. I do wonder what's happening to cause it.
