### ISSUE TITLE
dynamically image rendering

### ISSUE THREAD

**Issue by poshan-kandid** [diegomura/react-pdf#1702]
I am unable to load image 

getting this
![image](https://user-images.githubusercontent.com/89506773/151946743-77848c04-de76-406a-899f-07c9811d9718.png)

**Comment by poshan-kandid** [comment]
but this image working fine with html img

**Comment by jeetiss** [comment]
setup CORS headers for that image

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by poshan-kandid** [comment]
![image](https://user-images.githubusercontent.com/89506773/151958253-fe9bb17c-bfc9-4115-bd4e-f88b093fdb2c.png)
after adding Access-Control-Allow-Origin getting same
![image](https://user-images.githubusercontent.com/89506773/151958410-ea042237-cd04-44b0-a035-f51dbf547786.png)

**Comment by jeetiss** [comment]
@poshan-kandid you have to add this header at the server-side to the response.
