### ISSUE TITLE
Image Does Not Render Properly

### ISSUE THREAD

**Issue by gedion** [diegomura/react-pdf#1709]
**Describe the bug**
When using https://react-pdf.org/components#image component as shown below, the image does not display correctly.

**To Reproduce**
1. [Here is a react-pdf/repl snippet](https://react-pdf.org/repl?code=3187b0760ce02e004032203988605e18028094681f260281860078011118015c05b014cc297238d2005010d13b9d75920248d2e7459f18d0027801b3aa803794d91001d004b61dc02f98f110013b05400880059428001c2002e00f476d7a8046ce5683b00dd3c02500d27e7000ea76701c921000b408c82a966088c6bac476bce2ba24769cdc699914d4f48ccc5800dc04e5a090b04a7410683000ca5032740da6747450eefa741c507418f2302c1a223630f2bac2fa886a60006a74fa506ac01cd2e3008c00ac0034531c3373001220fa6a005ee050eb5b000c77fbc45afb045aa5e53ebdc0506c6400622a1e98000264b0c09062285487c800)
```JavaScript
const Logo = () => (
  <Document>
    <Page>
      <Image
       style={styles.image}
        src="https://i.ibb.co/vvRKKLW/Lays-Logo.png"
      />
      
    </Page>
  </Document>
);


const styles = StyleSheet.create({ 
  image: {
    marginVertical: 15,
    marginHorizontal: 100,
  },

});

ReactPDF.render(<Logo />);
```
**Expected behavior**
Image should look like the below screen shot. The image can be found at https://i.ibb.co/vvRKKLW/Lays-Logo.png

**Screenshots**
Expected image to look like
<img width="83" alt="Screen Shot 2022-02-03 at 2 21 40 PM" src="https://user-images.githubusercontent.com/1224206/152422837-4410f26d-436f-4577-87d4-96587a772acc.png">

What react-pdf shows
<img width="1305" alt="Screen Shot 2022-02-03 at 2 22 10 PM" src="https://user-images.githubusercontent.com/1224206/152422906-5bfa875f-397d-4d7f-9e07-8db4b4fa85bc.png">

**Desktop (please complete the following information):**
 - OS`MacOS`
 - Browser: `chrome`
 - React-pdf version: `v1.1.0`

**Comment by aymanxdev** [comment]
I would do two things, import the image and use it in variable instead of putting the whole url. Also, consider adding the image into your images folder. Secondly, Upgrade to React-PDF V2, as it is much better with additional features too. V1 will no longer receive updates.
