### ISSUE TITLE
Warning: Can't resolve 'iconv-lite'

### ISSUE THREAD

**Issue by arobert93** [diegomura/react-pdf#1712]
**Describe the bug**
Using the latest version `"@react-pdf/renderer": "^2.1.1"` with Next.js I get the following warning:

```bash
./node_modules/@react-pdf/fontkit/lib/fontkit.browser.es.js
Module not found: Can't resolve 'iconv-lite' in './node_modules/@react-pdf/fontkit/lib'

Import trace for requested module:
./node_modules/@react-pdf/font/lib/index.browser.js
./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
```

**Desktop:**
 - OS: MacOS
 - Browser: Any
 - React-pdf version: 2.1.1

**Comment by Kiko915** [comment]
It also occured to me when using with NextJS.

**Comment by HIRAHARANAOKI** [comment]
Exactly the same problem

**Comment by LB22** [comment]
Same here. 

"@react-pdf/renderer": "^2.1.1",
"next": "^12.0.10",
"react": "17.0.2",

> wait  - compiling...
> warn  - ./node_modules/@react-pdf/fontkit/lib/fontkit.browser.es.js
> Module not found: Can't resolve 'iconv-lite' in 'C:\WebAppDir\node_modules\@react-pdf\fontkit\lib'
> 
> ./node_modules/restructure/src/DecodeStream.js
> Module not found: Can't resolve 'iconv-lite' in 'C:\WebAppDir\node_modules\restructure\src'
> 
> ./node_modules/restructure/src/EncodeStream.js
> Module not found: Can't resolve 'iconv-lite' in 'C:\WebAppDir\node_modules\restructure\src'

**Comment by marcog83** [comment]
hi, i faced the same problem and looking at the webpack configuration, i solved the error setting an alias for `iconv-lite` to `false` like here

[LINK](https://github.com/diegomura/react-pdf/blob/e9744aa90036e75c806d80d6733e8233759fa93f/packages/renderer/.size-limit.js#L12)

**Comment by isaaclyman** [comment]
`npm install --save iconv-lite` fixed it for me, of course, but it's odd that it's not an explicit dependency of the library.

**Comment by yanayhollander** [comment]
as @isaaclyman suggested `yarn add --dev iconv-lite` fix it for me

**Comment by jonahallibone** [comment]
@diegomura I still get this issue in `2.3.0`

**Comment by Killal19** [comment]
I tried them but I still face the same issue with React.js

**Comment by Silvia-t** [comment]
Same issue two years after the last comment -- this fixed it
> `npm install --save iconv-lite` fixed it for me, of course, but it's odd that it's not an explicit dependency of the library.
