### ISSUE TITLE
Can't load Font Family

### ISSUE THREAD

**Issue by kamran96** [diegomura/react-pdf#1717]
**Describe the bug**
I'm trying to add this font to react-pdf but when I add the font URL the PDF screen disappears. 

`
// Register font
Font.register({
  family: 'Roboto Slab',
  src: 'https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;500;600&display=swap',
});

// Reference font
const styles = StyleSheet.create({
  pdfPage: {
    fontFamily: 'Roboto Slab',
  },
});

`

**Expected behavior**
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/28526984/154044428-f5e6581e-5d58-45c1-8ba1-774967471995.png">

**Screenshots**
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/28526984/154044232-d625fdb0-945f-4ea7-bd56-044bca8f9e84.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by aymanxdev** [comment]
From your screenshot I can see that you are using TypeScript and in that case you may need to add a declaration for ttf and otf. But first, try this  
```js
Font.register({
family: 'Roboto Slab',
src: 'https://fonts.gstatic.com/s/robotoslab/v22/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjojIWWaA.ttf', fontWeight: 600
});

```
Also, refer to this for more info #680

**Comment by nowtryz** [comment]
@aymanxdev is right, you cannot use a CSS file as a source for your font, you must use the otf/ttf files

**Comment by MarkForLoop** [comment]
@aymanxdev where did u get the src link from I can't see to find it anywhere.

```
  Font.register({
    family: `Montserrat, sans-serif`,
    src: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;800&display=swap',
  })
```

I am not using typescript tho

**Comment by nowtryz** [comment]
Open the CSS file, all links are available inside--

*Damien Djomby*

Étudiant en 5ème année,

Informatique, Données et Usages,
Polytech Annecy-Chambéry


M +33 6 65 12 90 24

M +1 (514) 600-9447
***@***.***
