### ISSUE TITLE
recharts SVG render: "Error: unsupported number: 3 3"

### ISSUE THREAD

**Issue by AlekseyKovalchuk** [diegomura/react-pdf#1720]
**Describe the bug**
@react-pdf\pdfkit tries to convert string to number in attribute `strokeDasharray="3 3"`. I've used this gist to render SVG chart directly in pdf - [gist](https://gist.github.com/kidroca/19e5fe2de8e24aa92a41e94f2d41eda4)

**To Reproduce**
[repro](https://codesandbox.io/s/sad-microservice-w02psm?file=/src/components/CustomLineChart.js)

**Expected behavior**
SVG chart is rendered

**Actual behavior**
"Error: unsupported number: 3 3" is thrown and PDF file is not created.

**Comment by diegomura** [comment]
There must be an error on the recharts to pdf logic and something ends up like `3 3`. This falls a bit out of the lib for me to debug

**Comment by Romain63hm** [comment]
Very late but found the solution if it can help someone. Use "3, 3" instead of "3 3". Worked for me.
