### ISSUE TITLE
Target prop not working in Link tag

### ISSUE THREAD

**Issue by poshan-kandid** [diegomura/react-pdf#1726]
I am unable to open react pdf's Link src in new tab.
can we add target prop in Link tag, like :- 
![image](https://user-images.githubusercontent.com/89506773/155302456-6b5982a8-3077-4921-9330-8d90ddbdc609.png)

**Comment by THSoftware** [comment]
Hi, was this fixed? I need to open an image via the Link component in a new tab

**Comment by diegomura** [comment]
Closing in favor of https://github.com/diegomura/react-pdf/issues/2393
