### ISSUE TITLE
Incompatible with webpack 5 in case insensitive systems due restructure dependency

### ISSUE THREAD

**Issue by Sasurtio** [diegomura/react-pdf#1732]
**Describe the bug**
When webpack compiles the node_modules folder in a case insensitive operative system (like Windows or MacOS), in the `restructure` dependency, it generates a file called `buffer.js` instead of `Buffer.js` for the development server.

When include the shim buffer library (following the README instructions), webpack will do an automatic `require` whenever it founds the unasigned variable `Buffer` (see highlighted line).

![image](https://user-images.githubusercontent.com/81442463/155771010-80a1c993-78c2-4875-8420-e5b991cbb07c.png)

Because of that, when the app tries to require the shim using `Buffer` what it really does is a `var Buffer = require('buffer/').Buffer`

![image](https://user-images.githubusercontent.com/81442463/155770685-e97b1f49-6cbc-4a65-925b-94f400beffb4.png)

But, because of the compilation of webpack 5 with case insensitive OS, it will find the file `buffer.js` that is relative to the `DecodeStream.js` file instead of the buffer library and result in `var Buffer = undefined`

**Expected behavior**
`var Buffer = Object`

**Desktop (please complete the following information):**
 - OS: Windows 10, MacOS
 - Browser: Edge
 - React-pdf version: 2.1.1

**Comment by diarcastro** [comment]
@Sasurtio perhaps this solution can help you as well!
https://github.com/diegomura/react-pdf/issues/1740#issuecomment-1065509181
