### ISSUE TITLE
translation not working inside of PDF document

### ISSUE THREAD

**Issue by Hiiiij** [diegomura/react-pdf#1734]
**Describe the bug**
I'm using `gatsby` and `react-i18n` for translation along with react-pdf/renderer's `PDFViewer` component, however the translation is missing within PDFViewer / iframe and only the translation keys are rendered instead, it seems to work properly however outside

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://github.com/Hiiiij/gatsby-pdf
2. run `npm install`
3. run `npm start'

**Expected behavior**
`intro` key within the rendered / downloaded PDF should show the translated text as set in `translation.json`

**Current behavior**
only translation key is rendered instead

**Comment by pascalporedda** [comment]
Yeah, experiencing the same issue right now

**Comment by sagargulati** [comment]
Any example for using `useTranslation` on `/api/ route` endpoints with Next.js?

I tried import `{ i18n } from 'next-i18next'`;

but `i18n?.init()` always returns `null`

**Comment by diegomura** [comment]
Closing in favor of https://github.com/diegomura/react-pdf/issues/1942
