### ISSUE TITLE
web-pack 5 incompatible issue in react scripts 5.0.0 (CRA) without craco


### ISSUE THREAD

**Issue by Gopisuresh-Akula** [diegomura/react-pdf#1740]
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
	- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "zlib": false }

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
	- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "zlib": false }

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
 
If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

I'm getting this issue while I'm using CRA react scripts 5.0.0 please check this issue
 @jeetiss @dfdumaresq

**Comment by diarcastro** [comment]
@Gopisuresh-Akula I solved the issue by using this package https://github.com/Richienb/node-polyfill-webpack-plugin and using the exclude option like the example: https://github.com/Richienb/node-polyfill-webpack-plugin#excludealiases

My `craco.config.js` looks like this:

```js
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');

module.exports = {
  webpack: {
    plugins: {
      add: [
        new NodePolyfillPlugin({
          excludeAliases: ['console'],
        }),
      ]
    },
  },
};
```

**Comment by Gopisuresh-Akula** [comment]
@diarcastro  thanks for ur response moreover i need without craco.config.js

**Comment by diarcastro** [comment]
@Gopisuresh-Akula I think you can install the dependencies (you need) described here: https://github.com/Richienb/node-polyfill-webpack-plugin/blob/master/package.json#L27
and later apply the fallbacks you need in your webpack configuration.

Do you have a code sandbox to play with?
In that way, I could try help you.

**Comment by oregev** [comment]
Try this:
https://www.npmjs.com/package/react-pdf-browser

**Comment by adamduncan** [comment]
To elaborate on [@inouekun's comment](https://github.com/diegomura/react-pdf/issues/1744#issuecomment-1110636319), we managed to work around this with [`patch-package`](https://www.npmjs.com/package/patch-package), using CRA5 and without ejecting or resorting to `craco`. These steps should hopefully get things rolling:

1. [As per `README`](https://github.com/diegomura/react-pdf#webpack-5), install all native Node modules that Webpack 5 will require. E.g.

```
npm install --save-dev process browserify-zlib stream-browserify util buffer assert
```

2. [Install `patch-package`](https://github.com/ds300/patch-package#set-up):

```
npm install --save-dev patch-package
```

(Worth also adding a `"postinstall": "patch-package"` script to your `package.json` scripts so patch is automatically applied for all contributors on install.)

3. Modify local `react-scripts` `webpack.config.js` (`/node_modules/react-scripts/config/webpack.config.js`) file with [`README`-suggested additions](https://github.com/diegomura/react-pdf#webpack-5) (adding `resolve.fallback` and `ProvidePlugin` mappings into CRA's beast of a config file.
4. Run `patch-package react-scripts` (this should produce `patches/react-scripts+5.0.1.patch`).
5. Run `npm start` or `npm run build` to run `react-scripts` and confirm app is running/building with no errors and `react-pdf` working as intended.

Hopefully that helps some of you out there 👍

**Comment by MakamiSupport** [comment]
> Try this: https://www.npmjs.com/package/react-pdf-browser

The browser freeze in production mode. Please advise
