### ISSUE TITLE
Change download file name from the toolbar

### ISSUE THREAD

**Issue by SourceCipher** [diegomura/react-pdf#1759]
I cant seem to be able to change the file name of the download button generated within the toolbar. It all works perfect and I am able to change the name of the pdf file by passing the title as prop to the Document component, but when I try to download the pdf, the name of the file seems like a blob name. 

Can we have a prop to the document component for changing the name of the file which user can download via toolbar?

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/919
