### ISSUE TITLE
renderToString does not render images

### ISSUE THREAD

**Issue by pooya121** [diegomura/react-pdf#1767]
**Describe the bug**
`renderToString` does not render images

**To Reproduce**
Render any image with `renderToString`

**Expected behavior**
The image should be visible in renderToString like it does in `renderToFile`

**Screenshots**
![image](https://user-images.githubusercontent.com/30743348/161220232-f7d10f8f-cbd8-4744-9db3-6c58681342c5.png)

**Desktop:**
 - OS: Windows 10
 - Node: 16.13.0
 - React-pdf version: 2.1.1

**Comment by nkalinov** [comment]
This is a huge blocker to using this library in backend environment. Any known workaround @diegomura ?
I tried both base64 and Buffer, none of them renders.
Open to help with PR, any hints where to look at?
