### ISSUE TITLE
"Failed - Network Error" when using Vite

### ISSUE THREAD

**Issue by paule89123** [diegomura/react-pdf#1770]
**Describe the bug**
After upgrading from @react-pdf/renderer v2.0.13 to 2.1.1, I am no longer able to download a PDF using PDFDownloadLink. The error message in chrome is "Failed - Network Error" (see screenshot).

I am using Vite.

**To Reproduce**
Using Vite, try and download a pdf with PDFDownloadLink.

**Expected behavior**
PDF file should download as normal.

**Screenshots**
<img width="242" alt="Screenshot 2022-04-06 at 09 59 02" src="https://user-images.githubusercontent.com/54537991/161940232-8941178e-1c8f-446c-b37d-57b037b5101d.png">

**Desktop**
 - MacOS
 - Chrome
 - @react-pdf/renderer v2.1.1
 - vite v2.7.10
 - vite-plugin-shim-react-pdf v1.0.5

**Comment by diegomura** [comment]
Can you provide a way to replicate this? If you try viewing the document using `PDFViewer` it renders?
