### ISSUE TITLE
react-pdf/renderer   unicode problem

### ISSUE THREAD

**Issue by taj567** [diegomura/react-pdf#1775]
Hi guys,
using react-pdf/renderer am able to download the pdf and read in English but with another language (like Hindi) am receiving it in binary digits.

frontend:<Text
                  style={{
                    fontWeight: 600,
                    fontSize: 15,
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  TABLE OF CONTENTS
                </Text>
                <Text className="hindiText">हिंदी में किसी Break 52</Text>

inPDF:TABLE OF CONTENTS
9?&@ .G ?8@ 

any solution on how to display Unicode in pdf.

**Comment by bit314** [comment]
You need to include a font that will display it correctly.

```
import { Font } from '@react-pdf/renderer';
Font.register({ family: 'Roboto', src: './Roboto-Regular.ttf', });
Font.register({ family: 'Roboto', src: './Roboto-Bold.ttf', fontWeight: 'bold' });
```
