### ISSUE TITLE
Throws an error at `$ yarn check`.

### ISSUE THREAD

**Issue by ShunichirouKamino** [diegomura/react-pdf#1781]
**Is your feature request related to a problem? Please describe.**
When using React17 or later, the following error occurs at yarn check.

```sh
error "@react-pdf/renderer#react-reconciler#react@^16.0.0" doesn't satisfy found match of "react@17.0.1"
```

**Describe the solution you'd like**
Are there any plans to update React itself?

**Comment by diegomura** [comment]
Please check in the issues for React 17 compatibility
