### ISSUE TITLE
Fragments aren't working

### ISSUE THREAD

**Issue by yaralahruthik** [diegomura/react-pdf#1782]
**Describe the bug**
Any jsx tag other than the ones supported by react-pdf will break the app but only in production.
Even if you use React Fragments!

**Problem Faced**
Doing something like `<><Text>Random Text</Text><>` will work in the dev server but will break during production.
While doing something like `<View><Text>Random Text</Text></View>` will work everywhere!

**Suggested Solution**
Better Documentation or at least allow React Fragments to handle conditional logic.

**Comment by diegomura** [comment]
Non react-pdf primitives inside the document aren't allowed, and will fail. Fragments should be valid thought.

**Comment by diegomura** [comment]
Just checked. Fragments are working correctly in master. As said above, non react-pdf primitives JSX elements inside a PDF document will break. Only primitives types are supported
