### ISSUE TITLE
Read Table of Contents to Provide a Menu for navigation into PDF

### ISSUE THREAD

**Issue by qaisershehzad** [diegomura/react-pdf#1785]
Hello I need help with Table of Contents of a PDF file.

I have a PDF file with table of Contents which working fine normally. But I want to provide side menu from where user can navigate into PDF file. Left Outline like thing. Is there a way I can read Table of Contents of the PDF file so that I can generate a separate view for Table of contents.

[sample.pdf](https://github.com/diegomura/react-pdf/files/8493727/sample.pdf)

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/479

There's currently no API to do this. You'll need it to do it manually yourself

**Comment by 1Jesper1** [comment]
@qaisershehzad Is this wat you are looking for? [https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-interactive-table-of-contents](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-interactive-table-of-contents)
