### ISSUE TITLE
Unable to build project on development due to primitives import error

### ISSUE THREAD

**Issue by celikn** [diegomura/react-pdf#1786]
When we run the project in the local environment, we are not getting any errors. However, when we try to build the project on the development server, we are getting the error below; 

index.js:56 Uncaught ReferenceError: $8f55928bf6443dcf$import$d53e6be1e6f9a8f3 is not defined at index.js:56:6

![image](https://user-images.githubusercontent.com/15700676/163566762-54813c9d-d72d-4a55-9046-b7e7500101a0.png)

To note that, we are using Parcel V2 to build the project.

Could anyone give us any suggestions on how we could solve this problem?

Thank you in advance,

**Comment by diegomura** [comment]
This should be fixed in the latest version. Primitives are now shipped as a CJS module and ESM
