### ISSUE TITLE
Download PDF with dynamic data

### ISSUE THREAD

**Issue by rasteli** [diegomura/react-pdf#1787]
Hi, there!

I'm generating a PDF document with dynamic data from a form. I've managed to render the document on the web successfully and, as soon as the data is entered, the document gets re-rendered with the new data.

PDF Document:
![PDF Document](https://user-images.githubusercontent.com/59903124/163687860-056e0a6a-ad5b-44d2-8ddb-27045ae8700d.png)

Document on the web:
![Document on the web](https://user-images.githubusercontent.com/59903124/163687888-ca5c99c6-fe82-4a70-ba87-bb0f720628a5.png)

The problem, though, is when I try to download the document, what I get is the one with none of the data. I get a blank page. I'm using the usePDF hook to get the instance and the url from it. I pass the url to the href property of an anchor tag.
![3](https://user-images.githubusercontent.com/59903124/163687978-9bff59ef-c895-45b3-8f3c-92df33e41258.png)

I attempted to use the update function from the hook and the PDFDownloadLink component, but the same problem occurs. Does anyone have some idea on why this is happening?

```
Next: 12.1.4
React: 18.0.0
@react-pdf/renderer: 2.1.1
```

**Comment by diegooa116** [comment]
Hello, sorry, did you have any problem when you ran the command npm install '@react-pdf/renderer --save'  with React 18.0.0 version?

I'm very new to React, and I'm trying to use React-pdf and I haven't been able to install the library.

![error React](https://user-images.githubusercontent.com/61633319/163831681-c0228bb1-1671-4d42-99be-0994041edbbd.PNG)

**Comment by AdamSitar** [comment]
This problem was discussed in https://github.com/diegomura/react-pdf/issues/736

**Comment by leean613** [comment]
> Hello, sorry, did you have any problem when you ran the command npm install '@react-pdf/renderer --save' with React 18.0.0 version?
> 
> I'm very new to React, and I'm trying to use React-pdf and I haven't been able to install the library.
> 
> ![error React](https://user-images.githubusercontent.com/61633319/163831681-c0228bb1-1671-4d42-99be-0994041edbbd.PNG) im using react 17 to run, i supose react-pdf does not support react18 yet.

**Comment by diegomura** [comment]
Should be fixed
