### ISSUE TITLE
set iframe full width

### ISSUE THREAD

**Issue by Nuruddin999** [diegomura/react-pdf#1788]
I read docs and made basic example , but i have small pdf document window . In dev tools inspecting elements i found that iframe does not have full width and height, how can i fix that ? Are there any props of document component or page component by which i can fix this ?
![Снимок экрана от 2022-04-17 17-55-34](https://user-images.githubusercontent.com/40308227/163720081-65ed85dc-bc91-49a2-97ac-97fab8b3b697.png)

Here is my code 
/App.js
`  <Route path='/flpdf'>
            <MyDoc />
          </Route>
`

/MyDoc

```function MyDoc() {
  const { isLoading, reqStatus, name } = useSelector((state: RootState) => state.user)
  const dispatch = useDispatch()

  return (
        <PDFViewer>
        <Document>
    <Page style={styles.body} size='A4'>
      <Text style={styles.header} fixed>
        ~ Created with react-pdf ~
      </Text>
      <Text style={styles.title}>Don Quijote de la Mancha</Text>
      <Text style={styles.author}>Miguel de Cervantes</Text>
      <Text style={styles.subtitle}>
        Capítulo I: Que trata de la condición y ejercicio del famoso hidalgo D.
        Quijote de la Mancha
      </Text>
      <Text style={styles.text}>
        En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha
        mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga
        antigua, rocín flaco y galgo corredor. Una olla de algo más va
        ..........
        </PDFViewer>

**Comment by nadongguri** [comment]
Hi @Nuruddin999,
add width and height property in ```<PDFViewer>```
```
<PDFViewer width="100%" height="1000px">
```

Actually, even I set width as 100%, still height is the same as before, setting ```height="100%"``` seems not working.

**Comment by diegomura** [comment]
Setting `width` and `height` props work (tested). If 100% doesn't work is probably due to wrapping elements not filling the entire window. Closing
