### ISSUE TITLE
The problem with styles and the wrap

### ISSUE THREAD

**Issue by YozhikM** [diegomura/react-pdf#179]
Hey. I use user content to fill in the pages. The pages are not created and not wrapped on their own, so I tried it in a new `page-wrapping` branch. In it, too, there is a problem: a part of the blocks-components literally eaten and disappear, and the layout becomes incorrect.

I use not Text, but also View.

**Comment by diegomura** [comment]
Hey @YozhikM. Can you provide an example of the type of layout you are having problems with?
The branch `page-wrapping` is experimental yet. There are many use cases already covered, but maybe yours not

**Comment by YozhikM** [comment]
The problem was solved in the master after the last PR. Thank you

**Comment by diegomura** [comment]
Awesome! Good to know. Thank you
