### ISSUE TITLE
Uncaught TypeError: _interopRequireWildcard is not a function

### ISSUE THREAD

**Issue by helloanil** [diegomura/react-pdf#1791]
Hey guys, getting this error for a while now and can't really find a solution to it. Did this happen to anyone else before?

![CleanShot 2022-04-19 at 02 33 04](https://user-images.githubusercontent.com/6314657/163897577-1cec323b-0f6d-4eb9-b20d-4d635bb447ef.png)

**Comment by diegomura** [comment]
Can you provider a way to replicate?

**Comment by diegomura** [comment]
It's been incomplete for far too much time
