### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-RAMDA-1582370] in ramda@0.26.1     introduced by @react-pdf/renderer@2.1.1 > ramda@0.26.1 and 4 other path(s)   This issue was fixed in versions: 0.27.2

### ISSUE THREAD

**Issue by AustinAmoruso** [diegomura/react-pdf#1792]
**Describe the bug**
Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-RAMDA-1582370] in ramda@0.26.1
    introduced by @react-pdf/renderer@2.1.1 > ramda@0.26.1 and 4 other path(s)
  This issue was fixed in versions: 0.27.2

**To Reproduce**
run snyk test on newest version of react-pdf

**Expected behavior**
Upgrade ramda to version 0.27.2

**Desktop (please complete the following information):**
Any and all

**Comment by lsaque** [comment]
@diegomura, any update here?

**Comment by diegomura** [comment]
Ramda is no longer a dependency in the latest version. So it's fixed
