### ISSUE TITLE
ts 版本的react-pdf不能使用

### ISSUE THREAD

**Issue by sdhushu** [diegomura/react-pdf#1794]
**Describe the bug**
ts版本下 document page view不能被作为一个组件使用

**Screenshots**
![image](https://user-images.githubusercontent.com/54340686/164201254-6f6ab8a6-7edb-4780-867b-80262d6bf7ff.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - React-pdf: 2.1.1

**Comment by diegomura** [comment]
Sorry @sdhushu , can't understand either the title or content of this issue. Please write it in english

**Comment by diegomura** [comment]
It's been incomplete for far too much time
