### ISSUE TITLE
Creating SVG QR Code

### ISSUE THREAD

**Issue by mdodge-ecgrow** [diegomura/react-pdf#1796]
**Describe the bug**
I am attempting to create an SVG QR code on my PDF and nothing is showing up.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
I have 2 files that should be enough to show what I am doing.
First is TestPDFPlacard.js
```js
import React from 'react';
import {
	Page,
	Text,
	View,
	Document,
	StyleSheet,
} from '@react-pdf/renderer';
import InsidePDFPlacardQR from './InsidePDFPlacardQR';
import PlacardQRCode from './PlacardQRCode';
import QRCode from 'qrcode-svg';

// Create styles
const styles = StyleSheet.create({
	page: {
		flexDirection: 'row',
		backgroundColor: '#E4E4E4',
	},
	section: {
		margin: 10,
		padding: 10,
		flexGrow: 1,
	},
});

const generateQrCodePath = (content, size) => {
	// console.log({ content, size });
	const htmlStr = new QRCode({
		content,
		join: true,
		width: size,
		height: size,
	}).svg({ container: 'none' });
	const parsableHtml = new DOMParser().parseFromString(
		htmlStr,
		'text/html'
	);
	const dElement =
		parsableHtml
			.querySelector('html > body > rect > path')
			?.getAttribute('d') ?? '';
	console.log({ dElement });
	return dElement;
};

// Create Document Component
const TestPDFPlacard = () => (
	<Document>
		<Page size={'A4'} style={styles.page}>
			<View style={styles.section}>
				<PlacardQRCode
					dPath={generateQrCodePath('some content', 100)}
				/>
			</View>
		</Page>
	</Document>
);

export default TestPDFPlacard;
```

And seoncd PlacardQRCode.js:
```js
import React from 'react';

const PlacardQRCode = ({ dPath }) => {
	console.log({ dPath });

	return (
		<svg>
			<path d={dPath} fill={'black'} />
		</svg>
	);
};

export default PlacardQRCode;
```

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
The QR code should show up on the PDF.

**Screenshots**
![image](https://user-images.githubusercontent.com/57459547/164325664-f8363a99-74b2-45f9-aa1e-93ce8dcd7a3d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Browser: Firefox
 - React-pdf version: @react-pdf/renderer@2.0.16

**Comment by mdodge-ecgrow** [comment]
I finally got this to work.  Feels terribly hacky though, not clean at all.  So I would love for someone to show me a better way.

Anyways, here is what I did.  I figured it out from this github comment: https://github.com/zpao/qrcode.react/issues/85#issuecomment-605933953
So I went to the parent and I tried to do this directly inside the component code:
```js
	const qrCodeCanvas = document.querySelector('canvas');
	const qrCodeDataUri = qrCodeCanvas.toDataURL('image/jpg', 0.6);
	setQRCodeString(qrCodeDataUri);
```
But it kept complaining about qrCodeCanvas being null for the second line.  So I figured it wasn't rendered on the page yet when that code was being called.  So I found this crazy promise function to return when an element exists from this SO answer: https://stackoverflow.com/a/61511955/571723

So now my code became this:
```js
	waitForEl('canvas').then(() => {
		const qrCodeCanvas = document.querySelector('canvas');
		const qrCodeDataUri = qrCodeCanvas.toDataURL('image/jpg', 0.6);
		setQRCodeString(qrCodeDataUri);
	});
```

And then in the render of the parent, I have this:
```js
{QRCodeString && (
	<PDFViewer width={497} height={400}>
		<Placard
			numPages={1}
			startPalletNumber={startPalletNumber || 0}
			lotNumber={lotNumber}
			activeOrder={activeOrder}
			image={QRCodeString}
		/>
	</PDFViewer>
)}
```

And finally in the render of the child component itself: `<Image source={{ uri: props.image }} />`

So like I said, it feels so very hacky and I would love it if someone could provide a cleaner way to do this.  But for now, I'm just happy I got it to work.

**Comment by mdodge-ecgrow** [comment]
Even if someone could just tell me how to get the base64 of the QR code without having to display it on the site and then hiding it with `display; none`.

**Comment by diegomura** [comment]
> Even if someone could just tell me how to get the base64 of the QR code without having to display it on the site and then hiding it with display: none.

That's not possible within this library. This lib is for rendering PDF documents only. How you get the data to render it's outside it's scope

**Comment by edgar97-hub** [comment]
> **Describe the bug** I am attempting to create an SVG QR code on my PDF and nothing is showing up.
> 
> **To Reproduce** Steps to reproduce the behavior including code snippet (if applies): I have 2 files that should be enough to show what I am doing. First is TestPDFPlacard.js
> 
> ```js
> import React from 'react';
> import {
> 	Page,
> 	Text,
> 	View,
> 	Document,
> 	StyleSheet,
> } from '@react-pdf/renderer';
> import InsidePDFPlacardQR from './InsidePDFPlacardQR';
> import PlacardQRCode from './PlacardQRCode';
> import QRCode from 'qrcode-svg';
> 
> // Create styles
> const styles = StyleSheet.create({
> 	page: {
> 		flexDirection: 'row',
> 		backgroundColor: '#E4E4E4',
> 	},
> 	section: {
> 		margin: 10,
> 		padding: 10,
> 		flexGrow: 1,
> 	},
> });
> 
> const generateQrCodePath = (content, size) => {
> 	// console.log({ content, size });
> 	const htmlStr = new QRCode({
> 		content,
> 		join: true,
> 		width: size,
> 		height: size,
> 	}).svg({ container: 'none' });
> 	const parsableHtml = new DOMParser().parseFromString(
> 		htmlStr,
> 		'text/html'
> 	);
> 	const dElement =
> 		parsableHtml
> 			.querySelector('html > body > rect > path')
> 			?.getAttribute('d') ?? '';
> 	console.log({ dElement });
> 	return dElement;
> };
> 
> // Create Document Component
> const TestPDFPlacard = () => (
> 	<Document>
> 		<Page size={'A4'} style={styles.page}>
> 			<View style={styles.section}>
> 				<PlacardQRCode
> 					dPath={generateQrCodePath('some content', 100)}
> 				/>
> 			</View>
> 		</Page>
> 	</Document>
> );
> 
> export default TestPDFPlacard;
> ```
> 
> And seoncd PlacardQRCode.js:
> 
> ```js
> import React from 'react';
> 
> const PlacardQRCode = ({ dPath }) => {
> 	console.log({ dPath });
> 
> 	return (
> 		<svg>
> 			<path d={dPath} fill={'black'} />
> 		</svg>
> 	);
> };
> 
> export default PlacardQRCode;
> ```
> 
> _You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_
> 
> **Expected behavior** The QR code should show up on the PDF.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://user-images.githubusercontent.com/57459547/164325664-f8363a99-74b2-45f9-aa1e-93ce8dcd7a3d.png)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 11 x64
> 
>     * Browser: Firefox
> 
>     * React-pdf version: @react-pdf/renderer@2.0.16
maybe you should to  npm install --save qrcode  
import  QRCode from "qrcode";
QRCode.toDataURL("test").then((data)=>{
            setsrc(data)
        })
<Image src={QRCodeString}/>

**Comment by edgar97-hub** [comment]
maybe you should to npm install --save qrcode
import QRCode from "qrcode";
QRCode.toDataURL("test").then((data)=>{
setsourceqr(data)
})
<Image src={sourceqr}/>

**Comment by perisicnikola37** [comment]
This still works in 2023 :)

**Comment by JMRodriguez-work** [comment]
Is it possible to show me the code ? I can't get it to work

**Comment by T-Mohamed-adam** [comment]
I recommned to use qrcode & react-pdf/renderer
npm i qrcode
Then generate QR code string
const [QRCodeString, setQRCodeString] = useState('');
 const qrCodeData = "Your data";

    useEffect(() => {
      QRCode.toDataURL((qrCodeData)).then((data)=>{
          setQRCodeString(data)
      })
      
    }, []);
finally path QR code string to Image
 <Image src={QRCodeString}/>
