### ISSUE TITLE
'Document' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by ModaxDev** [diegomura/react-pdf#1800]
Hey all, 

Since yesterday, my document cannot be used as  a JSX component.
 Its instance type 'Document' is not a valid JSX element.

"@react-pdf/renderer": "^2.1.1",
Node : 16.1

const MyDocument = () => (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.section}>
                    <Text>Section #1</Text>
                </View>
                <View style={styles.section}>
                    <Text>Section #2</Text>
                </View>
            </Page>
        </Document>
    );

Thanks if you got  a idea

**Comment by Don-Ghead** [comment]
I am seeing this same issue, what version of React are you running?

**Comment by tell-y** [comment]
How about updating `@types/react` and `@types/react-dom` to `latest` version?
In my case, it can be a workaround with #1825 patch.

**Comment by diegomura** [comment]
Can you provide a way to replicate it? I'm not sure I understand your snippet

**Comment by ilovett** [comment]
@ModaxDev  @Don-Ghead @diegomura  I was able to reproduce this and when investigating the versions I had installed found that I had:

```
react@17.0.2
react-dom@17.0.2
@types/react-dom@17.0.44
```

but

```
@types/react@18 // -- some how this was on version 18 by some other dependency
```

I added a resolution to use version 17, and the type errors when away after that...

**Comment by chathu-novade** [comment]
I'm seen this with latest and ^17.0.0 of react and @types/react

**Comment by sbuys** [comment]
> I'm seen this with latest and ^17.0.0 of react and @types/react

Same here. react 17 and @types/react

**Comment by bryantobing12** [comment]
any solution?

**Comment by JohnMaroe** [comment]
> any solution?

Simply updating react, react-dom and its type fixed the issue

**Comment by ilyabo** [comment]
Some of dependencies I had depended on an older `@types/react@17.x.x`, so I added it to "resolutions" in "package.json" and it solved the issue (only works with `yarn`, for `npm` use `overrides`):
```
"resolutions": {
  "@types/react": "18.0.9"
}
  ```
