### ISSUE TITLE
Is there a way to use multiple fontFamilies per page?

### ISSUE THREAD

**Issue by arsendev** [diegomura/react-pdf#1801]
```
Font.register({
  family: 'Lato',
  fonts: [
    { src: PDFFont.LatoThin, fontWeight: 100 },
    { src: PDFFont.LatoLight, fontWeight: 300 },
    { src: PDFFont.LatoBold, fontWeight: 700 },
    { src: PDFFont.LatoBlack, fontWeight: 900 }
  ]
});

Font.register({
  family: 'Noto',
  fonts: [
    { src: PDFFont.NotoKr, fontWeight: 300 },
  ]
});


` fontFamily: "'Lato', 'Noto'"`

`Font family not registered: 'Lato', 'Noto'. Please register it calling Font.register() method.`

const styles = StyleSheet.create({
  body: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 35,
    fontFamily: "'Lato', 'Noto'"
  }
}
```

I need to create a page where English, Korean, Japanese and Chinese fonts are displayed at once. But now, when I use it like the above code, it still shows the error code and I can't use multiple fontFamily, leaving the problem like this.

I left a question using a translator.

**Comment by diegomura** [comment]
What error code about you cannot use multiple fontFamily? It should be possible to use multiple font families by just using a different style per text block

**Comment by diegomura** [comment]
It's been incomplete for far too much time

**Comment by nikgraf** [comment]
@diegomura I checked out the bidi support, but wonder how does the bidi support solve multiple fonts and eventually fall back from one to another in case e.g. Arabic is supported in the fallback, but not in the primary one?

**Comment by denisbetsi** [comment]
Try removing single quotes from font names
fontFamily: "Lato,Noto"
