### ISSUE TITLE
PdfViewer doesn't display in production build and dev build page, but locally it works well. 

### ISSUE THREAD

**Issue by cocoball200** [diegomura/react-pdf#1802]
**Describe the bug**
Hello, Thank you for developing this library. It is useful for my project.
I develop a PDFfile and display this PDFfile by using PdfViewer on a page. When I develop on a local, it works well. 
But When I build a page for this, PDFViwer doesn't display the page.  
 

**To Reproduce**

```
//temp.tsx 
import React, { useState } from "react";
import TempPDF from "../../src/components/printBarcode/temp";

const index = () => {
  return <TempPDF />;
};

export default index;
```

```
import React, { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import TempDocument from "./TempDocument";

const PDFViewer = dynamic(
  import("@react-pdf/renderer").then((module) => module.PDFViewer),
  {
    loading: ({ error, isLoading, pastDelay, retry }) => {
      return <div>{isLoading}</div>;
    },
    ssr: false,
  }
);

function TempPDF() {
  return (
    <div>
      <PDFViewer
        //@ts-ignore
        width="100%"
        height="660px"
      >
        <TempDocument />
      </PDFViewer>
    </div>
  );
}

export default TempPDF;
```
```
import React from "react";
import {
  Document,
  Font,
  Page,
  View,
  StyleSheet,
  Text,
} from "@react-pdf/renderer";

Font.register({
  family: "Nanum Gothic",
  fonts: [
    { src: "/static/font/NanumGothic.ttf" },
    { src: "/static/font/NanumGothic-Bold.ttf", fontWeight: "bold" },
  ],
});

const TempDocument = () => {
  const styles = StyleSheet.create({});

  return (
    <Document>
      <Page wrap={false} break size={[80, 60]}>
        <View>
          <Text>Please display</Text>
        </View>
      </Page>
    </Document>
  );
};

export default TempDocument;

```

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Screenshots**

>>>> local (works well)
<img width="1428" alt="스크린샷 2022-04-29 오후 6 25 31" src="https://user-images.githubusercontent.com/66788867/165918831-f97c75b5-84b7-41ff-8ac8-8f4ce0d5896b.png">

>>> dev in vercel (just blankPage )
<img width="927" alt="스크린샷 2022-04-29 오후 6 26 55" src="https://user-images.githubusercontent.com/66788867/165919027-bad05e28-3ce4-4c5d-b711-2e5d1cfbb4eb.png">

<img width="487" alt="스크린샷 2022-04-29 오후 6 29 04" src="https://user-images.githubusercontent.com/66788867/165919383-200e52cf-9e68-4267-837a-a964347d5614.png">

-> There are not attributes.

<img width="873" alt="스크린샷 2022-04-29 오후 6 31 51" src="https://user-images.githubusercontent.com/66788867/165919836-2f3e1291-f3bd-4099-b8d8-e22099da6ed6.png">

-> this warning can not show in local, but it shows in dev page. 

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - React-pdf version [^2.1.1]

**Comment by cocoball200** [comment]
I solve this problem by setting at next. config.js with the line " swcMinify: false".

**Comment by cocoball200** [comment]
I solve this problem by setting at next. config.js with the line " swcMinify: false".

**Comment by TheMikeyRoss** [comment]
> I solve this problem by setting at next. config.js with the line " swcMinify: false".

I tried that but it still didn't work :(
