### ISSUE TITLE
Slow image rendering for big pdf documents

### ISSUE THREAD

**Issue by t3reetan** [diegomura/react-pdf#1807]
When I have a document that contains > 15 images, it takes 2 seconds to render the inital pdf viewer with text and then around 5-7 more seconds to for a second render(which causes a refresh animation to the pdf viewer) to load the remaining images.

Is this a bug? Or is there a work around for this? Am I doing something wrong?

**Comment by diegomura** [comment]
It's not a bug. Latest version should be faster, and https://github.com/diegomura/react-pdf/commit/d958b0ae06a61c157b2581488a9121a0464222f4 can help too. Rendering a document, and specially images, will always take some time
