### ISSUE TITLE
Can I render an image with a relative path?

### ISSUE THREAD

**Issue by flaurida** [diegomura/react-pdf#181]
Hi React PDF,

Still plugging along, is it possible to render an image that is stored in the project? I try relative paths and get `invalid URI` errors:

```
const LOGO_PATH = '/app/pdf/images/logo.png';
<Image src={LOGO_PATH} />
```

Thanks!

Sincerely,
Laura

**Comment by diegomura** [comment]
Yes! You can. Please check how it's being done here:

https://github.com/diegomura/react-pdf/blob/75032fc8277600f6534b1e39cee640b4c01f56a6/packages/react-pdf/specs/imageSpec.js#L35

You just have to pass an object `{ data: imageData, format: 'png' }` to the `Image` source, being `imageData` a buffer

**Comment by flaurida** [comment]
Hi Diego,

Thanks so much!!! I think I then need to configure webpack so I don't get this error: `TypeError: Cannot read property 'readFileSync' of undefined`, however will try to do so. Have a great rest of your week 😊

**Comment by flaurida** [comment]
Ah, the issue is I am not sure how to load the image as a buffer on the client. At least the URL works for now and can keep playing with it.

**Comment by LivioGama** [comment]
fs can't be use in the browser, I ended up doing :
```javascript
<Image src={window.location.origin + '/images/image.png'} />
```
Assuming your folder `images` is in public folder of `create-react-app`

**Comment by seyitalitek** [comment]
> fs can't be use in the browser, I ended up doing :
> 
> ```js
> <Image src={window.location.origin + '/images/image.png'} />
> ```
> 
> Assuming your folder `images` is in public folder of `create-react-app`

Thanks. This solution helps me after two year
