### ISSUE TITLE
Make the vertical padding reappear on new pages for a component that spans multiple pages

### ISSUE THREAD

**Issue by joseDaKing** [diegomura/react-pdf#1814]
**Is your feature request related to a problem? Please describe.**
Make the vertical padding reappear on new pages for a component that spans multiple pages

**Describe the solution you'd like**
Add a new property that will make the vertical padding reappear on new pages for a component that spans multiple pages

**Describe alternatives you've considered**
Adding padding on a Page component, in my case it wont work because my pdf will have a sidebar

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/733
