### ISSUE TITLE
Problem running react-pdf webpack-5 isValid react-pdf/png

### ISSUE THREAD

**Issue by FranciscoBruno351** [diegomura/react-pdf#1819]
Trouble running the library in a windows environment with node 14.5, it works in a macbook with node 14.5.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/105390923/168619412-80d5ffaf-ff0d-4b26-bb22-772a13f1973e.png)

Doesn't render the page where react-pdf is imported due to this block of code as showed in the printscreen. If the block of code is commented the code goes runs like usual.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/105390923/168619225-614ea10c-7b6d-4964-87a3-0e30d56096a0.png)

From react-pdf i am pretty much using the hook usePDF to generate a pdf
<img width="438" alt="Captura de ecrã 2022-05-16, às 15 41 40" src="https://user-images.githubusercontent.com/105390923/168619076-5ccc4faa-f46c-41ec-94fd-63d6abff3e16.png">

if extra info needed just say so.

**Comment by oregev** [comment]
Can this help?
will bypass the wp5 config for CRA 18+
https://www.npmjs.com/package/react-pdf-browser

**Comment by diegomura** [comment]
Can you provide a way to replicate this? I tested rendering PNG images using webpack 5 and didn't get such error

**Comment by FranciscoBruno351** [comment]
> Can you provide a way to replicate this? I tested rendering PNG images using webpack 5 and didn't get such error

Somehow it started to work properly after a few updates to RN18. 
If I happen to run into this issue again I will say so.

Therefore this issue should be closed
