### ISSUE TITLE
React-pdf/renderer doesn't work on iOS

### ISSUE THREAD

**Issue by Bluuuuuuuu** [diegomura/react-pdf#1824]
So I'm creating a PWA using Reactjs. I tried to access the app in the test environment and the PDFDownloadLink works fine in Android. It downloads the PDF file. Unfortunately, in iOS, it only displays the PDF page (a receipt btw) instead of downloading it in the local storage. Anyone has the same issue? I'm using the latest version.

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/714

**Comment by vinryde** [comment]
The only way it worked for me was by flattening the PDF, i.e combining all the layers [text, images, etc.] on the PDF into a single image. React-pdf renders layer by layer, and it also conflicts with the canvas limits in iOS. Flattening the PDF was the only way that worked for me.
