### ISSUE TITLE
<Path fill="url(#gradient)" /> does not work with webpack v5

### ISSUE THREAD

**Issue by jeckvld** [diegomura/react-pdf#1831]
**Describe the bug**
`<Path fill="url(#gradient)" />` does not work with webpack v5

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to the REPL example and upgrade next js to v11+
2. Try to render Path with gradient color
3. Observe that there is an error "arcToCurve is not a function" (from "normalize-svg-path")

**Expected behavior**
Works same as with webpack v4

**Screenshots**
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/24661867/170500321-a4432ade-d853-412d-b173-29a24f9a232e.png">

```tsx
const Quixote = () => (
    <Document>
      <Page>
        <Svg width="222" height="222"  viewBox="-1 -1 2 1">
          <Defs>
            <LinearGradient id="myLinearGradient" >
              <Stop stopColor="gold" />
              <Stop stopColor="red" />
            </LinearGradient>
          </Defs>

          <Path
            d="M-1,-1.2246467991473532e-16A1,1,0,1,1,1,0L0.8,0A0.8,0.8,0,1,0,-0.8,-9.797174393178826e-17Z"
            fill="url('#myLinearGradient')"
          />
        </Svg>
      </Page>
    </Document>
);

ReactPDF.render(<Quixote />);

```

**Comment by oregev** [comment]
This could help?
Will bypass webpack5 config.
https://www.npmjs.com/package/react-pdf-browser

**Comment by jeckvld** [comment]
@diegomura thanks for a quick fix! when do you plan to make a new release that includes this fix?

**Comment by diegomura** [comment]
Very soon. I just need to update docs!
