### ISSUE TITLE
Disable Iframe Scrolling

### ISSUE THREAD

**Issue by Qurishe** [diegomura/react-pdf#1840]
**Describe the bug**
I have components which are displayed using PDFViewer but there is this scrollbar that won't go i have tried overflow:hidden and set the PDFViewer scrolling='no' but it does nothing. basically what i want is to display only the pdf and not the scrollbars
and there is some extra space inside the PDFViewer which you can see in the image bottom i want to style it so that it fits the div.
**To Reproduce**
display PDFViewer without scrollbars

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/32069358/170944931-cc91c701-1160-4e39-928c-fda2ea135973.png)

**Comment by diegomura** [comment]
This does not seems related to the lib itself, but about how iframes are rendered in the browser. Not sure how can be achieved but there's nothing we can do from within the library that isn't exposed (passing styles or classes to the iframe reference)

**Comment by Sashacomputer476** [comment]
Observe this crucial insight



https://app-routerotting.github.io/mlhnddBX-inBri4_dnazhPdU7Il47U_zXY1cCtSX5EZJzy4UCeC6KMmAAe_Iyw/
