### ISSUE TITLE
Vite error: Buffer is not defined

### ISSUE THREAD

**Issue by blind675** [diegomura/react-pdf#1847]
I get the following error:

Uncaught ReferenceError: Buffer is not defined
    at node_modules/@react-pdf/unicode-properties/lib/unicode-properties.es.js (unicode-properties.es.js:268:31)
    at __init (chunk-ACCAMVX6.js?v=3dcd2ad6:15:56)
    at node_modules/@react-pdf/fontkit/lib/fontkit.browser.es.js

"vite": "2.9.9",
"@react-pdf/renderer": "2.1.2",

any idea why ?

**Comment by MarkForLoop** [comment]
globalThis.Buffer = Buffer
put that in ur index

**Comment by antoniocaporrini** [comment]
In my case this is what worked for me:

1. npm install buffer @esbuild-plugins/node-globals-polyfill --save-dev
2. Adjusted my vite config in vite.config.ts like this:
```
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';

export default defineConfig(({ mode }) => ({
  plugins: [react()],
  server: {
    host: true,
  },
  build: {
    sourcemap: mode === "development",
    rollupOptions: {
      plugins: [],
    },
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: "globalThis", // added for Buffer
      },
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
      ],
    },
  },
  resolve: {
    alias: [
      { find: "buffer", replacement: "buffer/" }, //  added for Buffer
      ...getAliasesToDebugInProduction(),
    ],
  },
  base: "./",
}));
```
3. Finally, in my index.ts i added this:

```
import { Buffer } from 'buffer';

globalThis.Buffer = Buffer;
```
