### ISSUE TITLE
404 adding module

### ISSUE THREAD

**Issue by dprosper** [diegomura/react-pdf#186]
**OS:** Tried on Mac and Windows 

**React-pdf version:** latest

**Description:** 404 when performing a yarn add @react-pdf/core

**How to replicate issue (if applies):** 
1. create-react-app <appName>
2. cd <appName>
3. yarn add `@react-pdf/core`

$ yarn add @react-pdf/core
yarn add v1.3.2
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.com/@react-pdf%2fcore: Not Found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\dev\\dimitri_prosper\\sizing-service-print\

**Comment by diegomura** [comment]
I just follow those steps and everything went well 🤔 
Are you sure this is not an issue in your end? Maybe your network cannot access to `registry.npmjs.com` for some connectivity issue? 
Just take in consideration that dom-bindings usage requires a special webpack config (in case you want to use create-react-app)
Closing this issue for the moment
