### ISSUE TITLE
The text has the wrong width in flexbox layouts with columns

### ISSUE THREAD

**Issue by jeetiss** [diegomura/react-pdf#1877]
**Describe the bug**

The text has the wrong width in flexbox layouts with columns

**To Reproduce**

go to [repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a00d490600ee31a788912600333128692004e1981424e00170c0044b643ef73157a8e4d4a1d3d7d40a0ca6349097088ca4b0c1400712f7d370046001a58b884940065000b5b2430006b0cecb8ce7f1cca0d6aea001544d828d31800071e252552be0c80064c98791e6032be2f04302500611011105b3700727d428c1e2855bf00c6ce0019703e184c14587d242842981e5199a5313b9811241118328c3297f2fe304f8c1204a730fccae50015919cce5180420110251d48290e07988165444622188f46c20198a5022212082623e146544404930a85802184b2529e1e66466911649242241748819599b48e67d7170b2bc3c930cfb95b9d2b16cc20e8c27c2d99c4c492ca78be51341109555000f42d0b8342206dd0184d411081855ed1881de25622895ca6e618ab2857250dcdc002641bba1d30460f16c7c52a1c30e6281fb030ed012c561e7b129dc5546ad5aa96d351ad80075000480134604d0028800349a300024be4600039003cb566b0d98000850e4db9801a400fc83836e7b35a7d79bf4a3b36852d06de0081a06ba03198ac7601000dc6432281206d2828830101c0c1f207b11143018282c980f66d860f0f6d1b28846e67e51babd7e934409d37000cc002b3a69f8f47d1807c076e8140202306e0006c207845f8417c016cb1200017b80500f022201c8650aa364aa26edb8004a5b2385c0d00018ac8f62cc182d878150882a0e8160fab10e45000)

**Expected behavior**

The text should be in the colored block

**Screenshots**

<img width="608" alt="Снимок экрана 2022-06-07 в 15 57 36" src="https://user-images.githubusercontent.com/6726016/172385394-be03a7ef-0530-4015-b235-77bae66adda2.png">

I dug into the issue a little bit and the text component has debug box with the right width, so I think the problem is in the `@react-pdf/render` or `@react-pdf/textkit` package.

**Desktop (please complete the following information):**
 - React-pdf version 2.2.0

**Comment by diegomura** [comment]
Thanks. Is this something introduced in the last version or it works the same in older ones? I'll try to take a look

**Comment by jeetiss** [comment]
For some reason, yoga calls `measureText` with full-page width firstly and after the real width is here but lines are already calculated and saved to the node. Any ideas why yoga adds a `measureText` call?


https://github.com/diegomura/react-pdf/blob/master/packages/layout/src/text/measureText.js#L22-L33

**Comment by jeetiss** [comment]
as duplicate of #2182
