### ISSUE TITLE
React 18 peerDeps problem

### ISSUE THREAD

**Issue by rasmusrim** [diegomura/react-pdf#1878]
Should support React 18

**Comment by modosc** [comment]
fwiw we're using react@18 without any issues other than the warnings from yarn:
```
error "@react-pdf/renderer#react@^16.8.6 || ^17.0.0" doesn't satisfy found match of "react@18.1.0"
error "@react-pdf/renderer#react-reconciler#react@^16.0.0" doesn't satisfy found match of "react@18.1.0"
```

**Comment by rasmusrim** [comment]
[See this PR](https://github.com/diegomura/react-pdf/pull/1879)

**Comment by rasmusrim** [comment]
@modosc We are also able to use it, but it seems like a trivial task to just add version 18 to the peer dependencies. 

I seem to have forgotten to add the PR here. Sorry - that would be confusing. Did that now.

**Comment by diegomura** [comment]
@rasmusrim Im not so sure is that trivial. We tried supporting react 17 with the same fix in the past but things didn't worked, due to the react-reconciler being from a different version. I need to dig deeper in this

**Comment by rasmusrim** [comment]
I see that the reconciler is a problem, but do we need to upgrade that package?

I set up a sandbox environment which uses the changes in my PR to render all the example PDFs here: https://github.com/rasmusrim/react-pdf-sandbox

I run into some problems doing the same in our project. I will look a bit more into it.

**Comment by rasmusrim** [comment]
The problem seems to be this package: https://github.com/ai/size-limit/tree/main/packages/time. It installs React 17 so there are two versions of React. But that is only a devDependency, so doing a production build of @react-pdf, leaves me with only one version of React.

**Comment by LB22** [comment]
@diegomura Have you had time to dig deeper into this issue yet? Have you found anything in regards to this that you can share? There is [this](https://github.com/diegomura/react-pdf/pull/1879) PR, are there any issues with it? If so, please comment here and in the PR. I appreciate your hard work!

**Comment by mkbcodes** [comment]
I'm having an issue similiarly, with it not recognizing react 18 and it spitting an error saying react dependency peer react@"^16.8.6 || ^17.0.0"

**Comment by rasmusrim** [comment]
You can try out this one: https://www.npmjs.com/search?q=react-18-pdf

It comes with absolutely no warranties or gurantees! I do not have time to maintain this, and will remove it as soon as I can.

**Comment by rasmusrim** [comment]
It should, yes. But right now it doesn't build on my system. Will see if I have some more time to look into it later. Please tell me how you are faring!

**Comment by trihoang1011** [comment]
after installing `@react-18-pdf/renderer`, I got this error `can't resolve '@react-18-pdf/yoga'`

**Comment by LimaoCode** [comment]
> after installing `@react-18-pdf/renderer`, I got this error `can't resolve '@react-18-pdf/yoga'`

I have the same issue

**Comment by PixelForm** [comment]
create-react-app error with react 18.2.0 since react-pdf seems to only support up to react 17.0.0, will this soon get updated?

**Comment by Flaviano-Rodrigues** [comment]
I trying to use this but in react 18.2.0 don't work

**Comment by IamIGI** [comment]
Still do not work :(

**Comment by Flaviano-Rodrigues** [comment]
> Still do not work :(

exactly, unfortunately it's not working with react 18. I found another repository (similar) that has served me well

**Comment by IamIGI** [comment]
> > Still do not work :(
> 
> exactly, unfortunately it's not working with react 18. I found another repository (similar) that has served me well

Cool, could you link me to this repo. I am using pdfkit instead, but right now I have to make pdf on sercer side.... which is not what I want it... cuz I can't use react now to style pdf format.... :(

**Comment by Flaviano-Rodrigues** [comment]
> Cool, could you link me to this repo. I am using pdfkit instead, but right now I have to make pdf on sercer side.... which is not what I want it... cuz I can't use react now to style pdf format.... :(

I'm using react-to-print. It generates the pdf and shows the user the option to print from the browser (which is exactly what I needed). I don't know if it will work for you bro, but I hope so!

Repo: https://github.com/gregnb/react-to-print#readme

**Comment by lwhiteley** [comment]
Also sad about this not working but it got me to do an open experiment to generate pdfs server-side with React as a template engine. 

still a WIP but good it to work end-to-end so far 

if you are able to generate PDFs server-side then maybe this research will help someone

https://dev.to/lwhiteley/react-and-puppeteer-pdf-generation-project-setup-1he2

**Comment by vlakius** [comment]
Still not working...
`react": "^18.2.0",`

**Comment by gitname** [comment]
For those wanting to use `@react-pdf/renderer` with React 18 today, here is a two-part **workaround** you can use to do so:

1. Add an `"override"` property to your React app's `package.json` file
2. Create and use some custom SVG-related components (this is only necessary for _TypeScript_ projects that use the `<Svg>`, `<G>`, or `<ClipPath>` elements)

I documented those two things in detail in the following gist: 
https://gist.github.com/gitname/bdc1fb7fe5bd0c22f6656b7905f57cd6

And I demonstrated them in the following video (the demo begins at the 1:20 mark): 
https://www.youtube.com/watch?v=YZP5r7Uy_bU

**Comment by chathu-novade** [comment]
Shall we get this fixed soon?

**Comment by Sebastian-Nielsen** [comment]
Bump

**Comment by Tmodurr** [comment]
This would be majorly helpful to get this supported at React `18.2.0`.

**Comment by hugrave** [comment]
I'm facing the same issue and it is compromising the whole system
