### ISSUE TITLE
Using PDFDownloadLink at all throws: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by alextownleymakes** [diegomura/react-pdf#1882]
**Describe the bug**
PDFDownloadLink throws an error every time, no matter what configuration:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
Build a component, use PDFDownloadLink, pass anything into it at all

<PDFDownloadLink document={<Document><Page><Text>Test</Text></Page></Document>}>
{({ blob, url, loading, error }) => loading ? "Loading document..." : "Download Pdf"}
</PDFDownloadLink>

**Expected behavior**
PDF generates and downloads

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - React-pdf version 2.2.0

**Comment by arbitora** [comment]
This seems to be still a problem.
Not aware where the core problem is, but it happens with the Download PDF Link object.

`
import { Document, Page, PDFDownloadLink } from "@react-pdf/renderer"
/* Basic react constructions */
        const pdfDocument = () => {
            return (
                <Document>
                    <Page size="A4" key={"a"} style={{ padding: "2vh 4vw" }}></Page>
                </Document>
            )
        }
        <PDFDownloadLink document={pdfDocument()} fileName={"test.pdf"}>
            {({ blob, url, loading, error }) => {
                if (error) {
                    console.log("PDF Download Link", "error")
                }
            }}
        </PDFDownloadLink>
`

React-pdf version 3.1.2

**Comment by jeetiss** [comment]
provided code works fine

https://codesandbox.io/s/code-that-works-w4u85j
