### ISSUE TITLE
Error adding bookmarks v2.2.0

### ISSUE THREAD

**Issue by jjsanchez88** [diegomura/react-pdf#1888]
Hi!

I´m getting error adding bookmark in every components such as Page or Text: 

![errorBookmark](https://user-images.githubusercontent.com/55842834/173871892-3976dcfb-2075-4047-ab9b-e1f700b6a994.png)

I´m using version  "@react-pdf/renderer": "^2.2.0",

Thank you in advance

**Comment by process0** [comment]
Bookmark prop is missing from the types. See https://github.com/diegomura/react-pdf/issues/1979
