### ISSUE TITLE
production mode  getting issue when using  react-pdf-browser 

### ISSUE THREAD

**Issue by Gopisuresh-Akula** [diegomura/react-pdf#1900]
production mode  getting issue when using  react-pdf-browser 
[Could not load content for webpack://react-pdf @react-pdf/renderer/lib/react-pdf.browser.es.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME](https://www.google.com/search?rlz=1C1ONGR_enIN1004IN1004&q=Could+not+load+content+for+webpack://react-pdf+@react-pdf/renderer/lib/react-pdf.browser.es.js.map:+Fetch+through+target+failed:+Unsupported+URL+scheme;+Fallback:+HTTP+error:+status+code+404,+net::ERR_UNKNOWN_URL_SCHEME&spell=1&sa=X&ved=2ahUKEwj6kt_76sL4AhXXT2wGHYSjC4EQkeECKAB6BAgBEDM&cshid=1655961964001777)

when imported from react-pdf-browser production app crashing 
@oregev pls check out these

_Originally posted by @Gopisuresh-Akula in https://github.com/diegomura/react-pdf/issues/1744#issuecomment-1163969703_

**Comment by diegomura** [comment]
This seems to be an issue with your webpack setup, not the lib
