### ISSUE TITLE
Max Width Media Query

### ISSUE THREAD

**Issue by tpreusse** [diegomura/react-pdf#1904]
**Describe the bug**

Starting with v2.1.2 (max-width) media queries seem not to work any more. For our A5 PDF we use the following which is no longer applied:
```js
const styles = StyleSheet.create({
  center: {
    paddingHorizontal: 90,
    '@media max-width: 420': {
      paddingHorizontal: 0
    }
  }
})
``` 

<img width="901" alt="Screenshot 2022-07-01 at 11 32 32" src="https://user-images.githubusercontent.com/410211/176871689-e07460b9-ae53-4bbc-bb23-e528ae71af72.png">

**To Reproduce**

1. Use a max-width: 420 media query with page size A5
2. Visually verify that it is not applied

[REPL Example](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e658212005e19b007200820159c4c68013c00d9880de8a5440074008c4001305017c63e8c3a11f769d395002a1852c0d6a5f6a848a0aa3c4e9878c80056e85866304a3c3000b23c60c000163c5400f40e4ed636d469ce50caaeb99a5a3c0850f120004e3e51487c08184aa65800c218e5006eb1981029d919365400928cfc181c99f205f979da48c30246639910e5c0d80044c9b32310c9008e4121008c5a81000e7c6b8b94c97db6d91379d8ea93da10083a1e5e183e579c4d3ca7002dd40104a100c006002e00960a0e51e1412261088c140607d12180480033ff814300c2055a58ac782cc0d00198f1182008383e2487d0f0947c704d0b4bf4a22090c14c235c291189c512bf1ea38d8a2fb8b89e6e2d2609c2633058ac9c9800145fc087f1292c3c72bf25142848f00034fc86029c1601023074e52c35a60fb242b5c13c5039499e56619b1d22f1a51180804b823c184629dc1fb2c1b4906d40644b530065325964ac1822006d8b09222c180f1a048250a9ca20334f0bd7c1e2ab3a350429a6065e0203fc1488a8060f8eada751157b7e82a5a1800154c091100969158666b2608c0021d663ac048b4755abf29815d66883334e98dc40ab38bacf5a12180819bf4754cd769d753b67569e117c40173a4aed24daa952b10985abecb8ba5ba5e158b20017ff8a7332369208e9843c0008f95a32083c24069870580ac95e1bb806f23009b6a805c2978c0307945d3f26f326ee8bae88f01cb8c62ba48b0a4bc008190a474030cc2b0ec01000371906400062e01405a3da7c120d02b4782a81c1528c3160a342e2000f210000eeccbe8e20fe9432cc0069f11405029c10242c932414a49da1f0d002298968a0230c90ecb49e94a3e8c91b487000ccc90009a003e9d800348006a001b0800007000ea201b43a08efa2058c18500068009c3c248921ca50052e219046309a25a2d003c9a0e030000ca93235f106018149c03da088608a4707a218d0929360c1fa062385d82029cd0a05d21199c28de35f00010ba0500dad0ac57362c8b7c17c0001215088927323376d363880000b3018a44c30a0002d0e98ca94d08002c00130000ce210dbf2ed3861de531dac29d3021c5f7cd3627ec0000d67c1965abe84d24e1506903b953602c94118f367c2a1fd363d9ac23522060d087d6f543303ca502484a0d460069c00b0983948662cc4d40627526a469da4f906470b8c70c529468cc0c36705ce93a23428707dd4ed3f4e33cceb3ad0733630ce52c9602ad1646d301bd90f0bf35bc1f27804e4b9ce49b2f93e0c25d4f6bbafcb8acdbac0f3aa528ea4c05a6e9fa6633008b942d384e70cefc1aef5332d93f2d538b32b0cdf04cefb81020458520a26bd2e499edf3bedd8b325e0f4004a36ac4d9e50574dd481dd3c23dcf7e8af51bdf6fdd6f8cdacd491cc026f8c30fc388fa228d82e53a31810b58e9b1c16c02187819eabaf45ad078ab928f2f9de1c2ff050320e226bf835f6f741cfe9548964097183ba5017034189d24b06639478150dc9a07c8dc5550000)

**Expected behavior**

The max-width media query should take effect and modify the applied style.

**Desktop:**
 - OS: macOS
 - React-pdf version: 2.1.2 and 2.2.0

**Comment by diegomura** [comment]
Thanks for reporting this @tpreusse ! So good to see your name around 😄 
Also very glad to see you are using v2. How did it work for you. Last time we talk I think you were on v1

**Comment by tpreusse** [comment]
Thank you for the quick fix 🎉 

We upgraded [last summer](https://github.com/orbiting/pdf/commit/e1ff815db66197cf9f3519aac7adc92bb9037839) and went quite smoothly. Let's catch up soon.

**Comment by diegomura** [comment]
Glad to hear that @tpreusse !!
Yes please! Let's catch up soon
