### ISSUE TITLE
Text on top of Image

### ISSUE THREAD

**Issue by arumdyaharum** [diegomura/react-pdf#1905]
I have to make certificates which contain full page of image and adding dynamic name on top of it. I already tried some ways to achieve that :

1. I tried to used positioning and z-index. the page or view that wrap the content is using **{ position: 'relative' }** and the content (image and text) is using **{ position: 'absolute', z-index: _(10 for text, 0 for image)_ }**. It doesn't work. I even found a bug that when I apply absolute to the image or apply absolute to view that wrap the image, the image is disappear.
2. I tried to used transform and z-index. The transform is working but z-index isn't. Here's the code and the result.

```
--- some imports ---
import { Page, Text, Image, Document, StyleSheet, PDFViewer } from '@react-pdf/renderer';

const Certificate = () => {
   --- some code  ---
   {!certificateLoading && certificateData && certificateData.template && (
      <PDFViewer width={CERTIFICATE_WIDTH} height={CERTIFICATE_HEIGHT}>
         <MyDocument template={certificateData.template} />
      </PDFViewer>
   )}
   --- some code ---
};

const styles = StyleSheet.create({
   text: { transform: `translate(0px, 10px)`, zIndex: 10 },
   img: { zIndex: 0 },
});

const MyDocument = ({ template }) => (
   <Document>
      <Page size="A4" orientation="landscape">
         <Text style={styles.text}>Dyah Achwatiningrum</Text>
         <Image style={styles.img} src={template} />
      </Page>
   </Document>
);

export default Certificate;
```

![image](https://user-images.githubusercontent.com/88584168/176882443-48d433ca-eefe-429e-b00f-5f0441b03a47.png)

**Comment by sb110197** [comment]
Hey @[arumdyaharum](https://github.com/arumdyaharum) Try this css https://www.w3schools.com/howto/howto_css_image_text.asp that might can help.

**Comment by aerielcruz** [comment]
@arumdyaharum This worked for me :)
```
  <Document>
    <Page page='A4' style={{ position: 'relative' }}>
      <Text style={{ position: 'absolute', top: 0 }}>text</Text>
      <Image src={image} style={{ position: 'absolute', zIndex: -1, top: 0, width: '100%' }} />
    </Page>
  </Document>
```
