### ISSUE TITLE
How can we pass React JSX/Component inside the <Doucment /> tag?

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [diegomura/react-pdf#1918]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by diegomura** [comment]
Please at least add some detail in the PR description 😄 

It's not possible to render React primitives inside React pdf Document. Only our set of primitives. Hope that answers your question
