### ISSUE TITLE
BlobProvider/PDFDownloadLink slows down the page a lot

### ISSUE THREAD

**Issue by Mohammed-Mounir** [diegomura/react-pdf#1921]
**Describe the bug**
So I have a page which contains multiple components, and there is a component that is a table, 
where each row have a view pdf link and download pdf link.
I'm using BlobProvider so the user can click on the view pdf and open the pdf file in a new tab,
and I'm using PDFDownloadLink so the user can click on it and download the pdf file.
but the page slows down a lot basically freezes the page. 
tried using BlobProvider alone or PDFDownloadLink alone, but I'm getting the same slow down.

tldr: using BlobProvider alone or PDFDownloadLink alone or both to generate multiple pdfs slows down the page a lot,

**Expected behavior**
I want to generate pdf so the user can click on a link to view it, or click on another link to download it, for each row in the table,
without any slow down.

**Code**
```
const ViewDownloadStatement = ({ data }) => {
  return (
    <>
      <BlobProvider document={<Report report={data} />}>
        {({ url, loading }) =>
          loading ? (
            <Typography>Loading...</Typography>
          ) : (
            <Button href={url} target="_blank" rel="noopener noreferrer">
              View
            </Button>
          )
        }
      </BlobProvider>
      <PDFDownloadLink document={<Report report={data} />} fileName="accounting_statement">
        {({ loading }) =>
          loading ? <Typography></Typography> : <Button color="primary">Download</Button>
        }
      </PDFDownloadLink>
    </>
  );
};

export default memo(ViewDownloadStatement);
```

**Desktop:**
 - OS: Windows 10
 - Browser: Latest Microsoft Edge
 - React-pdf version: v2.3.0

**Comment by Mohammed-Mounir** [comment]
Solution:

```
const ViewDownloadStatement = ({ data }) => {
  const downloadPdf = async () => {
    const blob = await pdf(<Report report={data} />).toBlob();
    saveAs(blob, 'statement');
  };
  const openPdf = async () => {
    const blob = await pdf(<Report report={data} />).toBlob();
    const pdfURL = URL.createObjectURL(blob);
    window.open(pdfURL, '_blank');
  };

  return (
    <>
      <Button onClick={() => openPdf()}>View</Button> |{' '}
      <Button onClick={() => downloadPdf()} color="primary">
        Download
      </Button>
    </>
  );
};

export default memo(ViewDownloadStatement);
```

**Comment by SOMONSOUM** [comment]
I also got the same issue when I generate pdf to multi pages around 60-100 pages it crashed the browser. Does the solution above still work? Or you have any good solution for this issue?

**Comment by Mohammed-Mounir** [comment]
works fine!
