### ISSUE TITLE
Error createDeflate is not a function

### ISSUE THREAD

**Issue by artcce2022** [diegomura/react-pdf#1935]
Hi, im newly on react programing, so maybe is a silly question. 
i receive this error when i try to generate a pdf .
TypeError: zlib__WEBPACK_IMPORTED_MODULE_3___default(...).createDeflate is not a function
    at PDFReference.initDeflate (pdfkit.browser.es.js:43:1)
    at PDFReference._write (pdfkit.browser.es.js:65:1)
    at doWrite (_stream_writable.js:409:1)
    at writeOrBuffer (_stream_writable.js:398:1)
    at __webpack_modules__../node_modules/readable-stream/lib/_stream_writable.js.Writable.write (_stream_writable.js:307:1)
    at PDFPage.write (pdfkit.browser.es.js:442:1)
    at PDFDocument.addContent (pdfkit.browser.es.js:38655:1)
    at PDFDocument.transform (pdfkit.browser.es.js:1980:1)
    at PDFDocument.addPage (pdfkit.browser.es.js:38570:1)
    at renderPage (index.es.js:1037:1)
    
using this code
 `    <PDFDownloadLink document={<ORderPdf />} fileName="somename.pdf">
              {({ blob, url, loading, error }) =>
                loading ? 'Loading document...' : 'Download now!'
              }
            </PDFDownloadLink>`
            
 and OrderPdf Code

  `const ORderPdf = () => {
  return (
    <Document>
      <Page size="A4">
        <View>
          <Text>Section #1</Text>
        </View>
        <View>
          <Text>Section #2</Text>
        </View>
      </Page>
    </Document>
  );
};`

thanks in advance

**Comment by tbor00** [comment]
Hi, you can provide more information for this? You can create a codesandbox with this issue?

**Comment by artcce2022** [comment]
I tried to create codesandbox but it works fine. 


https://codesandbox.io/s/thirsty-lehmann-dd78h5

**Comment by artcce2022** [comment]
So, i uninstalled everything related to react-pdf and installed again and works fine. 
thanks

**Comment by artcce2022** [comment]
sorry, i just uninstall everything and installed again.
Some packages need to be installed with  --legacy-peer-deps.
ex. npm install --save @react-pdf/renderer --legacy-peer-deps

**Comment by NathanFirmo** [comment]
For me, it works running this:

~~~bash
npm install assert buffer process stream-browserify uti @react-pdf/zlib
~~~

and changing webpack config to:

~~~js
const webpack = require('webpack')

module.exports = {
    plugins: [
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
      new webpack.ProvidePlugin({
        process: 'process/browser',
      }),
    ],
    resolve: {
      fallback: {
        zlib: require.resolve('@react-pdf/zlib'),
        stream: require.resolve('stream-browserify'),
        buffer: require.resolve('buffer'),
      },
    },
  }
~~~
