### ISSUE TITLE
Setting up development environment to work on PDFs

### ISSUE THREAD

**Issue by luke-concannon** [diegomura/react-pdf#1937]
newb dev here...

I'm trying to setup a fast and enjoyable dev environment to work on my pdfs e.g. HMR etc. Can someone throw me some direction on setting up a development environment? I've had a play with next, with NoSSR hacks, nodemon/express but can't seem to get it working well.

Any advice would be hugely appreciated!

**Comment by Maarcosv99** [comment]
See this comment https://github.com/diegomura/react-pdf/issues/1940#issuecomment-1912881269
