### ISSUE TITLE
Testing Typescript error

### ISSUE THREAD

**Issue by chathu-novade** [diegomura/react-pdf#1938]
**Describe the bug**
Try to setup snapshot testing with jest.
I'm getting following error.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

Create a jest typescript setup and create a test file as following.

```tsx
import { pdf, Text } from '@react-pdf/renderer';
import * as React from 'react';
import Center from '../../src/components/center';

describe('<Center>', () => {
  it('should render', () => {
    const { container } = pdf(
      <Center>
        <Text>Section #1</Text>
      </Center>,
    );
    expect(container).toMatchSnapshot();
  });
});

```

Getting and error

```
(alias) const Text: typeof ReactPDF.Text
import Text
'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/Users/chathuvishwajith/Library/Caches/typescript/4.7/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.ts(2786)
```

**Expected behavior**
Use component without issues in test environment.

Is there any guide on this using with @testing-library/react rather than using pdf method?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - React-pdf version [^2.3.0]

**Comment by luke-concannon** [comment]
I came across similar issues running react-pdf, next and jest, this resolved my issue - https://github.com/kulshekhar/ts-jest/issues/2805
