### ISSUE TITLE
Request link to Starter Repo for efficient DX (HMR or equivelent working)

### ISSUE THREAD

**Issue by danalexilewis** [diegomura/react-pdf#1940]
**Is your feature request related to a problem? Please describe.**
We have been using react-pdf for a while on one project and never got to having a good DX. 

The best we got to was loading the pdf in the browser and then restarting the server each time the files were changed and manually refreshing the browser (using nextjs with NOSSR) OR generating pdfs via the CLI after each change and opening them.

**Describe the solution you'd like**
Ideally it would be great if HMR worked with . Or possibly some sort of server & client reloading (quickly experimented with Nodemon + livereload). 

**Describe alternatives you've considered**
 Keep going with the status quo 😓 

Thanks
🙏

**Comment by Maarcosv99** [comment]
If you use Vite + React, add this in `main.tsx` file

```tsx
import.meta.hot?.on('vite:afterUpdate', () => {
    window.location.reload()
})
```

This code reload the page after each update.

**Comment by dmitov** [comment]
Just released a CLI that solves the DX issues, check it out: https://github.com/dmitov/react-pdf-preview
