### ISSUE TITLE
pageLayout props not listing under Document

### ISSUE THREAD

**Issue by Kaliyani** [diegomura/react-pdf#1943]
**Describe the bug**
@diegomura  pageLayout property is not working. Can someone help me to solve this issue. I am passing pageLayout property in Document like below
`<Document pageLayout="twoColumnLeft">
<Page></Page>
</Document>`
correct me if i am wrong.

_You can refer [react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198b000e02180e6180321c04f1008a3600445003b8800c22000d9330bc3003328638854ad4002b72cd007c8cd803791931001d002310004c0405f2d3a755002a1852c4ba62ca18c306c002c30381c30009d9c615550301cdddc7400fc6065a223301c612490a14261b23980a00168d81d5460d3b5dca801e9bd7c531b5afc824dcdfc6ca10a4d5ce8c1e19000add0b0a261e43860016438c18142399b3bda3d3a61fd7bba43ac3845424163881690b81031e46066646200dd973020367ca0b728a80125180c0d549ed02c11b120013c67103dc1068b01c44d08418204d002384ca600466b38cd85c310c2604d6fb507620beb5820085b00ca04352650641c360016ea0087908060bf001718cb05068870a0f3199cc60a03003890c0240019f460218061c631395cbb9513baa8388c10041b9a12403838f22e37268d622651104849a61ee580952c566b2247cda1ef241df660eb2617cae1b4c000a2a30428d145c0e3449db379abb561c000d3c6184218180408c5b364b3dc8c52062dcb299d4dd1661a7b330776a4748c042adb9030c230d8859b8c09e4827ab3e691dac9acd16f8d722063e5800bde62c18071a04879099a22034e45633190ebcae0854c95e8acd1aa8e6a01832a63e6ee681a2d90719dac30002a981e60a094cc47dcc60010e272f601e60c43010d00e88c012cd3080cd361654541309d7f09db35584234c1c1b9c773c60602f35780d598088807f5b1220345310c4c5615505d08ffd8b702d0f9dcd000bf464e0b9460901ad3f0011f2213410614e8fb8736e22d08028fad28295a9461fb28d68a144218138688de78da95acca62da50e11f50cee6c9a02d56e094a560114053764104010c662796e58d3034d00f906709c1cb32107bd54d8de639827048425142729576040274e1580404f023c53b3a4980b8881f534cb0871fb4f2b016194dd8db659e6080b0538c061548c95c008bbb332ce240c76fcff10c126cd1f6f0c07ec55518b4c03a098123798f5202bb4e1a08aa12b0af76c9587dd9501b76100f36e23810d8082d66130630aa028231cee25cec3077d4a7533253d43b6c2d83986734cd685d5910c58080973982adb80f6008f4abf5180a01cc380aa250ed4d2898547c00316889031a02d9c41f8cc01b9a055c436354d2bd2aa8c08b94561b866f9d78f225561266501db13050055466c8e57dd8ab3d49d8c20c931eb01c61114ed5d91900006e180b8615460041c6881018def38d953d4ae53bcc8e06747ced188e7288e538d8090d300eb673b90d3cc581cdf5f8ced71837181b944042336f035ae710a8d41198eb95f7b290551959589059cb189d8e3fb8c9c2bb289a02c17aee442600a1db058021d748cd68eda2503c035439615ff12c20564b8ab1f2a754daeab5d0703c319d39801319ed42af9b604b1544c90c2144f45553e852cb3246856bcf1bfaf9d23a061a72c52b358d85395e0870004bbb86b62a6cf3456a4b07361233fb271aba21063d1693e524bc4f9765f5412b0034f98324b4349354a47d0c30019896eaec42c3116bbd65538877462d74a08e14fe89d6d80f522219e8120034dc86d93f4162249093a3b81c10991039ea69b6acc0c0311661203ccf15438033342b8b2b27518a29f1870048e3c953f348a7f51f9600503d81c3ca33acf5e31fd5f22bd583873b8aa9d52ca3014e928bcc402375b0b1c61e910b89806864287484f430081b49ca160a68f9b2a65c180b8130f98242d7b52502424c073d786ca98388a6e2e1d463db5a1355a502a64a4d8d604e358104633655fa0c44988124ac557330a0c2c28d31a9211398d830a38cf20b057374c783d47442ca5d44b9a0988aa3e71670da1809e3ca6dcd557ab68c70d8cf7270a8a3e41db4738cda9c70a49986c208948b00cec0889810c6a43027d658bf5da6d85d2df5b916135a64c57a1a1543a8f5380980e0d6e1f0e58a74003292e178bc99a59c35ae64e6143786330b4a84834b35e730165cb45f69431581b82730a13accc2280805ce94bc7491696d3460cc5aed11028a4d810c1962f97515b506924b8c1c1f65616c84583036089c02140b395a23314c6a85646b944b4a21ef63931456722a4d601cb7a10123a14100fc82539cb9182376371625a30eeb257aa14af39ac6001816f874bb800820b092e2251e5bc1160279014dc065525a4bf4aaab4b98097498ebc9e277612eed2b01a212bb3452e624093d4627ce94bd2303f6459494b099a7fe9298b1f4a0e580a5485126bd9b8b0e3c83287b2be660d45318217aeca40e44010c73d5419c018e43961a6654045e95ce66034c9219c314ef4436b4884ba4d79ad28d0ca13086335c8de600b2f918015b6f4d8de80f852038fd0cfa324c855442ad16543e268b51339f2dc00a917999475ab723680548ac4ae1301d99f0c4590a92b07472f204882e2c089d0bb28988815fd53a62aac1853f15792a5de8ce818f79ac6cf674895a4b41302fb8a473adcaca21893694a3f40020943680f293015828234a42136428fe4fcb09080f28b923d65c2011f0003970e403e62366545d2e738540ab586230e00141caa80021499cb1a1bdc3c1e78430d32c1fd90272caec73d9117065a1541399c7e682d83b250e0e6a088ac92a3498b0cefd17e3114f11a2712236fd160183de9732eed846a70cc94371a205d7514c740aca11450c19442fcafc4ac0d73aee1578d9a3c16f5ba828bf6446f97bd328782e31e8dd5913af155206ab9981f54fc40be632d56d00c4c3ce4723140276146c68a6aa49b41c9bcc74e8c0a74fe802709f30ae9305d91596ccb5662aa58b3af1303227a7317900f5bc48e933181300a4e7a4f27ca0d734f34b910e2518e6a5a0e68211262304cb19fb6f480aee8856c80765452806223022b5d2034b5cab53b91cf5cbf6da22914166d41013c6fc0e217326d692a4064a5960b4c9d7bd0609e3aab4658cf816db09538be3a63d035ee9a30991566300e65700003f2c0672c705a2da100fe3b86b16c275231df955111eb3edad33e879021abe94410cbf1ea5cc4c0b78df0c053dc2d591b8800e2c70e61f3004356421606fdb28141fe34c7d6ca699165d0df53349b8b60b92df369892ea434f49bf3c2cbd95c18fc65829ed8925848e48c9bbeb17591d8e13a80cff2d10d3295a4530121dcc338699c2256699f1841e44307f1921e727dc89c359252d69d500fce3268e0cd94a1941439f5e4fbc7ccd68d61e714e4b086660113a5173463f544846d338f0555f55617acb69edb2c692acd2e54ead99289602c1dec600ce18cd69eb27a2f8b9b7c21f6087e84fa06280e7da4b861282101403ec54699a79e71e5e9d801309d116316eb4b4efb8d68b3bf230d14bbaa4a285c204e1300219469d4b2b18f3e37d5c53a32bc4ea9424ba5e7b4eddea77dd415f59b52b7066670b8a4b381a8a3f89807e79d6cfd326173795b60a65aca79fcbe9276bdb8368e3770bb66a47cbc0a8bca62ab66252ea19a59d58e29a059d99d16ac5ed24e7161089e0bd71a4998d375e1b5a29ae47329d16b2884f61b918052251437541f5483850452be61748334c1056403052e675c7d463234c7f607550a6c219408020937846e76c0342c11bd51165d13f5b869841433464a7c90490945c32b32a64491e74724de4884d63573d94c20945fc22c57c78c4d337505a7e253409c6e27b34d44b92a30c344920910c74f1ac5bb4ea74035b6913aa0033fc43518816e3b616548c7bc20f54810f3de1f448f63e4386a45a44180c03887d60e00006b62d6643640e45cb5f83e40145fa3fe5636330841e762b61c4494d905156c40721c13a61946e7a91604314b42aa1362986cd5de0f47f84046f123e4a45c35b08f57844446c8d4422c0740c0000266b03607a94247ac12430f2e8730ca418f38f7ac000095694714091be1755a25090c969b3016666ac4ec68652c6b858c0ac64a2d0d6c220f9c56e3657db35014b4eb05116b6822e276b75c1e8a801fc0d55b31d65cb73f7d541e18074f158e430df7ac7a54ea3d0fb10d56aa514760b0011162a2e03626267693d574d1ec4a311a27a3c17b210820d2e75fa0130351775064cd58c5bd32a5ad690a7e075718a965b048a6f8bb97ac6604983091c08c04cb2833be0180805d406568847c0004d549564284a4338c35247400b1884340108671763ed7911807da3e8f820ad6e22270127bf6ec5a34657ea0108047e257c75c6ad49f46d5a147a61246706a30a3342127016ca165152198000294e43012822c058c4602616a935709c6a45f61171666f11a32613d67cc0002550157c6a20e8b2d6aa0043b80194ee2112725346e75f12e508a6dc0ac18c0c09cc2b4851398478f9865451d206104f985d47903332c041c1bc6145d63343b11a0c02220a216232f93070844336a24e15117907b055c488af238c70a0606d896e424a5c6b56d23bb47f21f32255263939458276e2d22449567872fd4585a21641605a239e2f884939b73a6ee2f94d56dc62b28026165e5f8b58e2c80728e13029d700eb151d0ec33c5b36347cb08d5367f364e07519c53415476c6320e01495502ec2a37e49ac58664a36c0d0a2770e6123d4bdb24a23756f6c26023ff3002f54ac5d4b411315c136d0215dd7aa6064f77aa28866cdfa7fa24e24a2fcb0a2aa627578dfcde64ba4ee3bf4227880137dc650df093017800533490c3c76585ea3ff1fa6cc01d33a482c823254b12bcab609cee15c512921705c16e423142add0511083bc98848889418c57c62a03213228a65cd8d46912a3e112c6214281a408838c39c3d37b955c36013f7c51876e89f25d25f25812d22e479b238d50f985a5264d975d2e4481124a404b9e2fcaac9894a749f5097f0d5c4493fa51a414cb32e25142d7198550834137071144f2482283c8627001d4978d1874f122b415645f267f4690335c4e656f73636d630003257771421cb34d00f0cda2d525f8c0626e2f65791852c035f4731604d6588faf598316484c495cb51299d0989cac1c3d4ab51c2fab52d1323ce50505cac40000e10c28cae65dc3b11ea6966cc4a4f51722f366e33ba7d93a70510a73bf163480f7048e0c03af5b89776e0daa4c667a6804ea73f01319c49c5f67b342f0af6309de2f460f3309e80b0c2d20c62d124faf274abe2cce5a5b8c460a378872e5785d497aa12162df726cf0cdf259219613710834a1c0e528d57e440014020007ebb45557b84cb284fc2cca8ce2915060222988ec734e927555f262b18c198c5029c04c0de1061e763413228656314a788519434271368a265b67900f50067e115902208e28e0622c01ac0ec7a97dc466de94da2ec32b7b8ae8ea566928610d22a74c8bceb7198114c2a5be01e3233650e00007e7e453d16b5a254ace31a30600d510c07685016c43d761223038f6692af9c37448cfae4e04d43ea308e1230309653954664086a88a116b95616a62daa2be2964769af66b0c060242629358219a7bc37afac4e063c97a6c62aa134f9c4135393417a93dc2710066b262b4cb146aaa0c279044d65453737645016cd483d4f003baf987b3208c0eae633653d254c73002fce19c8e6ea2bd233a0ae6d45025b83193f313444568ca329d0f2d500b34294354c8d1a2f0851c5382860b95a4ba21376f5777634c6a8341915225724290ca9197d42196c2de7448c7412a90c24c3585be5365b8b035011d928a4505872824b48bb7cc2d25d44feebc0f2a675483b49c6186ec232653b2d165ee5a6a4a232d35605dc6e451a9422decc829ca72e9205870056c790230c680fad0f2fabcd4c882d53e7fa90c3249e7094360f86012e38b7495abc1149041012034ec6fbc3c69a077e1d91546310f52b85cb4d7538219210f9c7bc64579e1166d8d66840766b03441881ed219c7e24422ca23a9d01942e0292f8c5ca7c158c39e39c6c115826208e4e4582688671a161fc3955ce28cfda271a1e4d61b3100a0917cb40af67a0ee43bcb4e01c80042800796282801622822968b140242ec1740e5d250561455a6c30882be61a6e93585617a065b25d0c11bc70069108d4b69790d16397981e6ff62f60004210c1b484049e0b44747d76f6f3679006163eea5500bc6180741b0683a0e75e23ae29b7026fc0452ea4e0a2eea5054c910227ab51e52b1b0648cfae30efa808068a2d10c5e01b851c21b519cea4d7132c457b71617e1c8852b2c0ac0512e1211cb40b223c6e49d083d6ee24937981a04e41c60881d4c264f110e33a1105ec4330a54e9c5828af9c4f8fe16605467be52377666c04960e5ae194102ec26c86d964c225f0a4e35dc0b779c16a506f6b7f8ab68ac315256d8c71b0054753e1e9538c9884fe85547c5d07907e98e022662a285fdc6fb24a6605f4a8960e47414d6e36a454e045ae53006b11d15a206047d28a223795946542b40bf25560c047c3904b1592b6495368275279ef0acf26867c0a621a95f61653a0895e926357911af6cab4126ceb227a0c0510c4518d1210cab5542935e582a2a0406f77ae8e0354135b1ab5e506d7c0aa13690830eed4ec225d05042e72a6d17691642860e2ded066aaa5cf6ae8966b14f9f987ee1d1502d066c801805d11262a616dbd27646762ed480e41ec52b439961e39b61fa88e1c68e7085c2b73a08d1c6d3c1b002b4ee4b2c6a2224db35003ea35a5263a1e5b5eac14b75fac5cb4f95d62a0d6d9793c14c368835a22c67a1e77f2e5b4500d15e92b9c2cbc996ae72b280e31401795d219b61f1782e4729564cf9c743c213a47c29eff64c547635dd9467da152ec3f0836bb35ca0556ead86cf35128e6e1f5d0104ee45e01fc5820154daae65760654a5583df08227d43371c17e4f6b3935f2dcb35a4cc70856e1947bc6dc360ddc6a9b35c7430e36f7c2a63ac53980cadc528635e0a6a0efbec9c001d3efdc15235a74f2f941b16c49d9daa94f3c75c7812af3659818fa2fa65469e0f512a471d5c3556586820d9eeeac3b713580db29d59ef1f79e9d76e88c52edf7051d360b2569d06025a1632762c2be2f2ef360ede14b8db366793e2b38354f001ddd481a61001e06f1ac02962d1e79632f8744f66019465b2d26730a9eb3a366540824936b534c2f8c18ef749815499dee451d64b9f717ea1491e87194c35a343a79faa5edd94e64a7f64633241e418d66e6b3bed20f4b76e3d54ee9fc19c00e108c4f200ad726924a2ff4913c147c59183424b5a33f964daeab514da5c1deb998da6bbf6dc4d3b694618f0661d30a1d9faca44e01e06fd26032938869a5067303c03303f23bb87bd9f3fa700fd01e009c6702206c05203c010c00003000123305bb8c07bbdcc1883882681802879fbb343fb908670307a240203880481402486242d86687479486683a00602c0ad00201e63203207063a1eb06c83c310e68837bed0441a5c0107e4000722498804903340706e7c153846001e7d082802803600805e42682682f55601b02e001e0186006b0326268544034017f900702682782c4000662681248007d4f000069000350003610069a800751002785b027c070437c605378000d0004e0e053d53d00c2805506e7b204079a7b205923a8dce5c019903819970814b757d284c0367ca07b02707e43302044e00701947a94f01003607e443780056480dcffcfae01837405f37e41b7f2f9cfc882afe68baa2beb3412fc6fca06704153a41302cfa04057a8039929c0c07e41288001648098f53d0895b19e7e23807617c1fba1f066967902e79805e7fe7c17d0feefc153f60be81ff7021f91fb1f9802c4128e9fcf859fab830005f83d68865ff703f33c33001afc979cc7e409f800064151efed01584fbee7f6cf89fce8667f7e40cd5202aff6e22402afe2bf5601afc7389bf6df8ebc85eda0000650063cc7f06c26e160117f78058035801008bf94fc81033f39fbdfcb7eecc45c2a80040cff1d010fc9019cf1e7a781fc21000a81da55947bf1802602d9290810050206016002b78e84c4cf20480577d701d1037fab7d2fa1bb09045fc7fe7ff0c060a9c20af36880e03280a7f24028fce01d00bc07bfd6be5ff1800944541ee00a05dfc1fed4427fa405400bfb1e780b14ea0c0be04c3ce1e6522d06b719e80307000f3c0188684502600181da0f006e83cfe97f480bd813fe8c012fb9827402607503f20e21940286170025e490ebfaf816fef3f2dfa2fc620c10caa0382b7e4e0fa07ffc288e1f5a78da4220e505d00d01c188cf71d2b3ca8076834023a0490d4f32010000)

 - React-pdf version [v2.3.0]

**Comment by jeonshine** [comment]
+1

**Comment by Kaliyani** [comment]
@diegomura Any update on this issue

**Comment by Kaliyani** [comment]
@jeetiss Any update on this issue? Kindly help me to resolve this

**Comment by diegomura** [comment]
This is working. But probably not doing what you think it is. this is just PDF metadata so readers know how to render the doc
