### ISSUE TITLE
Can't resolve 'stream' and 'zlib' (fix using react-rewired?)

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [diegomura/react-pdf#1944]
I am gettin gthe error `Can't resolve 'stream' and 'zlib'`

I know you can fix it using craco [as shown here](https://github.com/diegomura/react-pdf/issues/1645#issuecomment-999072302)

But craco is soon to be discountinued, so I would rather use react-rewired. So, my question is, how do I fix this resolve issue using react-rewired?

**Comment by carlobeltrame** [comment]
This should be fixed with #1891, once react-pdf is released in a new version.

**Comment by carlobeltrame** [comment]
This should now be fixed in @react-pdf/renderer v3.0.0. Can we close this issue?
