### ISSUE TITLE
dpi is not prop of Page

### ISSUE THREAD

**Issue by ghost** [diegomura/react-pdf#1946]
**Describe the bug**
Try to change dpi of a page and following TypeScript error.

```
No overload matches this call.
  Overload 1 of 2, '(props: PageProps | Readonly<PageProps>): Page', gave the following error.
    Type '{ children: Element[]; size: "A4";wrap: false; dpi: number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
      Property 'dpi' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
  Overload 2 of 2, '(props: PageProps, context: any): Page', gave the following error.
    Type '{ children: Element[]; size: "A4"; wrap: false; dpi: number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.
      Property 'dpi' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Page> & Readonly<PageProps>'.ts(2769)
```

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create a TypeScript project.2. 
2. Try to use dpi prop of Page component.3. 3. 

**Expected behavior**
Should be able to use dpi prop of the Page component in TypeScript .

**Desktop (please complete the following information):**
 - OS:  MacOS
 - React-pdf version : 2.3.0

**Comment by bashunaimiroy** [comment]
I believe this is fixed by https://github.com/diegomura/react-pdf/pull/2106

**Comment by grahamdaw** [comment]
I was just confused by this exact error and came across this issue. Check if you are using [`react-pdf`](https://github.com/wojtekmaj/react-pdf). This issue and repository is for `@react-pdf/renderer` module.
