### ISSUE TITLE
Not working in android's chrome

### ISSUE THREAD

**Issue by Drealler** [diegomura/react-pdf#1947]
**Describe the bug**
PDF not loading in android chrome.
It stucks with a Open button that does nothing.

**To Reproduce**
1. Open any generated PDF in android's chrome

**Expected behavior**
Works as it does in a web browser

**Screenshots**
(Abrir means Open)
![image](https://user-images.githubusercontent.com/14021153/180047251-0ff3dd5c-7b0d-4dc9-b0b5-b3b11ae8cf1b.png)

**Specs:**
 - OS: Android
 - Browser: Chrome
 - React-pdf version: 2.3.0

**Comment by dany68** [comment]
Hi, any update about it ? I have the same issue

**Comment by diegomura** [comment]
Seems like it's working, just that the browser seems not able to render the document. `<PDFViewer />` just renders an `iframe` that leverages whatever the browser chooses to render the doc. If you need something more custom you will need to build it yourself. Like getting the documet blob, and rendering it with https://github.com/wojtekmaj/react-pdf
