### ISSUE TITLE
'clipPath' definition missing on SVGPresentationAttributes type

### ISSUE THREAD

**Issue by juan-nepris** [diegomura/react-pdf#1948]
**Describe the bug**
Hi, the `clipPath` property is missing from the SVGPresentationAttributes or ReactProps definitions.
It causes our build to fail so I'm just doing a work-around for now.

**Expected behavior**
`clipPath` property should be defined in SVGPresentationAttributes (not sure if this is the right place).

**Screenshots**
![image](https://user-images.githubusercontent.com/62254989/180048401-7b495d1c-a213-4cb4-a8c8-be2fc78fd79b.png)

Thanks for this library, it's really awesome.

**Comment by diegomura** [comment]
It's there now
