### ISSUE TITLE
Setting DPI changes page size

### ISSUE THREAD

**Issue by jacobo** [diegomura/react-pdf#1953]
**Describe the bug**
I would expect that changing the DPI of PDF pages would not reflect as a change in inches/printed size (just higher resolution). But I am observing that that inches dimensions of PDFs does changes based on `dpi`.

**To Reproduce**
1. render a pdf with e.g. `<Page wrap dpi=300 orientation="landscape" size="Letter">`
2. Open PDF in OS X Preivew
3. Choose Tools -> Show Inspect

**Expected behavior**
The PDF shows Page Size: 11 × 8.5 inches

**Actual behavior**
The PDF shows Page Size: 45.84 × 35.42 inches

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - React-pdf version 5.7.2

**Comment by chathu-novade** [comment]
I can not set the dpi in typescript. DPI prop is not there.

**Comment by NicolasPanda** [comment]
Any update on this bug ?

**Comment by nikischin** [comment]
Unfortunately I have the same issue. So working with anything other than 72 dpi breaks the page dimensions in mm. This is caused by #1869 I guess. Could you have a look at it @diegomura? Thank you!

**Comment by NicolasPanda** [comment]
I will try to explain what I understood and how I resolved my issue with DPI. A PDF doesn't really have DPI, as it is vector-based. However, you can include images inside it that are 300 DPI, and you will have a "300 DPI" PDF with the correct size in cm.
