### ISSUE TITLE
Warning when `styles` is passed instead of `style`

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#196]
**OS:**
Any

**React-pdf version:**
Latest

**Description:**
We should display a warning when a prop `styles` is passed instead of `style`

**How to replicate issue (if applies):**
Pass a `style` prop and see the warning in the console

**Comment by rogierslag** [comment]
I thought this was unnecessary but as it turned out I spend 40 minutes cursing on flexbox until I realized I did exactly this.
