### ISSUE TITLE
Wrong type 'function'. Fixed version not published 2.3.0

### ISSUE THREAD

**Issue by vrinceanuv** [diegomura/react-pdf#1961]
**Describe the bug**
wrong type version not published. I see the type updated 24 days ago, but no npm version published with that fix. the latest version 2.3.0 was published over a month ago. with any clean install cannot get this one fixed over npm at all.

**To Reproduce**
Try to run a build in a ts project

**Solution**
Please publish a new version with the type fix made 24 days ago. Thank you

**Workaround**
Downgrade to 2.2.0

**Screenshots**
![Screenshot 2022-08-04 at 11 22 25](https://user-images.githubusercontent.com/4588351/182800252-22e4a2d5-4b5b-404f-8e78-884332447a8f.png)

**Comment by diegomura** [comment]
Fixed
