### ISSUE TITLE
disallowed MIME type (“”)

### ISSUE THREAD

**Issue by AdamHasma** [diegomura/react-pdf#1963]
**Describe the bug**
`Loading module from “http://127.0.0.1:5173/node_modules/.vite/deps/@react-pdf_renderer.js?t=1659645435486&v=bbc08a1d” was blocked because of a disallowed MIME type (“”).`
That's what I get when I tried the quick guide on the website. I tried it in multiple different ways, always the same issue

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Vite + React Ts + Tailwind
2. Quick Guide
3. Bug

**Expected behavior**
Showing the content

**Screenshots**
![image](https://user-images.githubusercontent.com/59115022/182951216-b2ed92b8-e18b-470c-8746-0b0ae3c4ada3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - React-pdf version 2.3.0

**Comment by rayoplateado** [comment]
Hi all! I can reproduce this bug. Same configuration on my side but without Tailwind.

**Comment by diegomura** [comment]
I'm running this in vite without issues. There's an example in the source code. Closing it. Please report back if still happens
