### ISSUE TITLE
util.inherits is not a function

### ISSUE THREAD

**Issue by Legal-Dan** [diegomura/react-pdf#1966]
**Describe the bug**
On running 'npm install @react-pdf/renderer --save' the library attempts to install a dependency of blob-stream. This then throws the above error in the browser on running the app. In the gitHub repository this package has been removed, however in the node module the dependency is still present.

**Comment by carlobeltrame** [comment]
This should be fixed in #1891, we are just waiting for a release of react-pdf.

**Comment by carlobeltrame** [comment]
This should now be fixed in @react-pdf/renderer v3.0.0. Can we close this issue?
