### ISSUE TITLE
iPhone doesn't display all pages of the PDF document.

### ISSUE THREAD

**Issue by Jeerjmin** [diegomura/react-pdf#1969]
**Describe the bug**

I have PDF file with 55 pages. The problem that the document displayed in half (25 pages) on iPhone 13 (Safari, Chrome), another pages are blank. PC is displaying all pages perfectly.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

```
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import { pdfjs } from "react-pdf";

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;


    <Document file={url} onLoadError={console.error} onLoadSuccess={onDocumentLoadSuccess}>
                {Array.apply(null, Array(numPages))
                    .map((x, i)=>i+1)
                    .map(page => <Page pageNumber={page}/>)}
            </Document>
```

"react-pdf": "^5.7.2"

**Comment by gitname** [comment]
Hi @Jeerjmin, I think the package you are using is `react-pdf` (https://github.com/wojtekmaj/react-pdf), as opposed to this one, `@react-pdf/renderer` (https://github.com/diegomura/react-pdf). 

(I'm not involved with either project except as a consumer and, occasionally, an issue reporter/tester. I just saw this issue as I was scrolling through the open issues.)
