### ISSUE TITLE
Need help in table creation 

### ISSUE THREAD

**Issue by wahajStar** [diegomura/react-pdf#1970]
Hello,
I try to create table but its not working properly, when I add more rows and page limit exceed it throw error can u please provide a feasible small code example it would help,
thanks in advance...
[Refrence example](https://react-pdf.org/repl?code=3187b0760ce02e00404207901280440a2483e818410196460178601c8062008c0331a6d20285125915434c065005404d3cd3132104001b0096004d1b3683171e008c9803a804914dc00490802c00189b8390a01caa8dda8400a45fbf4c00b4f3f32f59ab404a1801e86006623161868004f51005308214e287088ce000b0888a8003a6000270880432808eb006f0618184a104950802e1862d2d280071cc949713000731abb1298005f001a1ea81cca489ac2981ed2d68806d11cea98002261d188a5fec9fa9800772928449aa59c805728100dadfaf2ccc908ccd8f89ab6742c1e7e344da9b2905bfbec312fd9ec8578e1f0c841b6c6e774c8a9f68718228be50df8c290e276a24a070c901c6afa6475d51f738080a0e7002d8e2f130070f4065755a4490201db8caea50a4e532ed3691d4ee74bb7da89100078a1c4d960141c4e023a65594b2b832862348803448a2d2e461ecef9ed7108851b92c3a003519000a4a442695a1f74798de0208e3bc04b69f9fd321aa073bd85805043bef6cca93c9200a4fb32350a3d9f436e0f1361f0ae87a437808b51b129da5a693dc10035a908c329419db555ac35dae6bdcf5db034d2cc160f0c02d4b4b50a515ec744581feae1f1dd1ccf4c2a3fdd06069090a257ac394f1d91c87184f7661c5d4c8fd399ece1bf179af4168b39d2df536a54afaac48a7afd51b46d70b6ac16d235a0f30dec4f5d43cf96e938b9783829c673b4930dd1177dee0ccb3702093fd0f42d60e55cf464d5088355bd4a7bc6a66ddc67d964ed20878e227500b787f2220097403705a744cbd7029178261683771a4e0fa26123c90fa509265d0889445106b5d56a6f8b91e4f918000560f5a8700a04e1c4000bcfb444002610260792c06c4220c4b11a9a4fb1788bd4a7e3b0413444c260093793008cb9214a5354ae8e932c185e93c001b818208e4001144e71145324221b1bc220003e181ac1e8001e140406004e0a4225d2a2ef9e28001472769c2b09222210a42aa2349ca4a97a4cbb6529e2800d5c408876108488898ad2a20349f8aaa476d9eac6b9ad2bdad6b3afe2591d87aef86a981faa6a5af8986f8946b42352d4757b926e9ba6f8bb8089455808692a46aea56ab2448daa2eca154904e695e29f176fda62a9a6afba1aa6b9eadbea59b06d6b16c8996aacc473b324dabeefb1e83afea3a9693aab33bd6d06a2ee142068227bb21cfbc1b7a06ac6be9fbe6a2a61806e1abd84c46c1f0666c8709b6b89b2a2c8476b247b2fb96549031bdaa03c6b69c63edeb5ef7b7e85be9c06c990729ec669c3a3ad2604a1225cbb32711807461eae679eda7c21735efbb5dc65edaa85da7fe866d0f1b25edb8d9978e8b3af4b779e97a1d9719a12aaa41726951c6ca50000c539a7a05bebf5fe70defbade776d95ac4077b6a76459774eb76a2ff003ee683bd6758ce8d81a4dd16e58d4aab0efaf8e89c4fe1e4fd4fd114001391c7d1d4c70aba70602aeabfaf1bdaed3dd7839d78b99a2384ea3a074458f5ed2ee9f2fd52b2aae93001a826efb399a439d87be5eb3b0e099b761b1b5931e73b9bb7926edcd5f7886b9bcea7f9747a8a0041300c964932180151d917feef9d5e97adf239dfa39be97ad509ea6cc5b5f2aad8072034000b75004e288100300d40d420ae14a02643c8390601dc180f3060330568c01c400067b00301420c0088000adee210c21082ee2886d239029080110301121481c8a21da020940690c3905710942c2960f0ab82002c8e4300c01120e477e54d3f9af03ec2ccbb0f32645ca99008be47ccd8571be55d6bbd76924dc1c33836efa1eb800764705ddd5a070fe2bdaab6341eaa2ff88f33e5a3f6a5f351602a2ba979ef23b1a388ce8a2be8bd4515947c2e57ca4e3ee92514a694328301f27e43d8e46943ed7d9a46c86006135878a82342be45f05147c9000)

**Comment by chathu-novade** [comment]
What's the error are you getting. I tired adding more row but didn't see any errors.

[Sample](https://react-pdf.org/repl?code=3187b0760ce02e00404207901280440a2483e818410196460178601c8062008c0331a6d20285125915434c065005404d3cd3132104001b0096004d1b3683171e008c9803a804914dc00490802c00189b8390a01caa8dda8400a45fbf4c00b4f3f32f59ab404a1801e86006623161868004f51005308214e287088ce000b0888a8003a6000270880432808eb006f0618184a104950802e1862d2d280071cc949713000731abb1298005f001a1ea81cca489ac2981ed2d68806d11cea98002261d188a5fec9fa9800772928449aa59c805728100dadfaf2ccc908ccd8f89ab6742c1e7e344da9b2905bfbec312fd9ec8578e1f0c841b6c6e774c8a9f68718228be50df8c290e276a24a070c901c6afa6475d51f738080a0e7002d8e2f130070f4065755a4490201db8caea50a4e532ed3691d4ee74bb7da89100078a1c4d960141c4e023a65594b2b832862348803448a2d2e461ecef9ed7108851b92c3a003519000a4a442695a1f74798de0208e3bc04b69f9fd321aa073bd85805043bef6cca93c9200a4fb32350a3d9f436e0f1361f0ae87a437808b51b129da5a693dc10035a908c329419db555ac35dae6bdcf5db034d2cc160f0c02d4b4b50a515ec744581feae1f1dd1ccf4c2a3fdd06069090a257ac394f1d91c87184f7661c5d4c8fd399ece1bf179af4168b39d2df536a54afaac48a7afd51b46d70b6ac16d235a0f30dec4f5d43cf96e938b9783829c673b4930dd1177dee0ccb3702093fd0f42d60e55cf464d5088355bd4a7bc6a66ddc67d964ed20878e227500b787f2220097403705a744cbd7029178261683771a4e0fa26123c90fa509265d0889445106b5d56a6f8b91e4f918000560f5a8700a04e1c4000bcfb444002610260792c06c4220c4b11a9a4fb1788bd4a7e3b0413444c260093793008cb9214a5354ae8e932c185e93c001b818208e4001144e71145324221b1bc220003e181ac1e8001e140406004e0a4225d2a2ef9e28001472769c2b09222210a42aa2349ca4a97a4cbb6529e2800d5c408876108488898ad2a20349f8aaa476d9eac6b9ad2bdad6b3afe2591d87aef86a981faa6a5af8986f8946b42352d4757b926e9ba6f8bb8089455808692a46aea56ab2448daa2eca154904e695e29f176fda62a9a6afba1aa6b9eadbea59b06d6b16c8996aacc473b324dabeefb1e83afea3a9693aab33bd6d06a2ee142068227bb21cfbc1b7a06ac6be9fbe6a2a61806e1abd84c46c1f0666c8709b6b89b2a2c8476b247b2fb96549031bdaa03c6b69c63edeb5ef7b7e85be9c06c990729ec669c3a3ad2604a1225cbb32711807461eae679eda7c21735efbb5dc65edaa85da7fe866d0f1b25edb8d9978e8b3af4b779e97a1d9719a12aaa41726951c6ca50000c539a7a05bebf5fe70defbade776d95ac4077b6a76459774eb76a2ff003ee683bd6758ce8d81a4dd16e58d4aab0efaf8e89c4fe1e4fd4fd114001391c7d1d4c70aba70602aeabfaf1bdaed3dd7839d78b99a2384ea3a074458f5ed2ee9f2fd52b2aae93001a826efb399a439d87be5eb3b0e099b761b1b5931e73b9bb7926edcd5f7886b9bcea7f9747a8a0041300c964932180151d917feef9d5e97adf239dfa39be97ad509ea6cc5b5f2aad8072034000b75004e288100300d40d420ae14a02643c8390601dc180f3060330568c01c400067b00301420c0088000adee210c21082ee2886d239029080110301121481c8a21da020940690c3905710942c2960f0ab82002c8e4300c01120e477e54d3f9af03ec2ccbb0f32645ca99008be47ccd8571be55d6bbd76924dc1c33836efa1eb800764705ddd5a070fe2bdaab6341eaa2ff88f33e5a3f6a5f351602a2ba979ef23b1a388ce8a2be8bd4515947c2e57ca4e3ee92514a694328301f27e43d8e46943ed7d9a46c86006135878a82342be45f05147c9000)
