### ISSUE TITLE
Mobile Doesn't Work: Doesn't Display on Android | Chrome and Safari on iPhone will display but cannot save PDF

### ISSUE THREAD

**Issue by TheJoeyBeans** [diegomura/react-pdf#1977]
**Describe the bug**

iPhone Behavior:
When creating a PDF I'm unable to save that PDF to my phone.
-Chrome displays an error displaying "Cannot Save Image" Error saving image.
-Safari attempts to save to photos but the PDF is not actually saved.

Android Behavior:
PDFs are not displaying. "Open PDF" button is appearing but interacting with it does nothing. 

*All behavior works as expected on desktop*

**Expected behavior**
Mobile experience should be consistent with Desktop.

**Screenshots**
Android: 
![Android PDF](https://user-images.githubusercontent.com/47164559/185675144-30357812-669f-4bfa-b88b-a3d166757995.jpeg)

iPhone:
![IMG_5994](https://user-images.githubusercontent.com/47164559/185676109-ef429495-ca2e-428e-a465-1c989a7ff55c.jpg)

**Comment by chathu-novade** [comment]
Can you add more information about your setup. What do you use like renderToString or another method to render the PDF?

**Comment by TheJoeyBeans** [comment]
> 

We're currently using the PDFViewer component from @react-pdf/renderer to render out our PDFs.

**Comment by TheJoeyBeans** [comment]
> Can you add more information about your setup. What do you use like renderToString or another method to render the PDF?

We're currently using the PDFViewer component from @react-pdf/renderer to render out our PDFs.

**Comment by TheJoeyBeans** [comment]
> Can you add more information about your setup. What do you use like renderToString or another method to render the PDF?

`    <PDFViewer
      style={{
        border: 0,
        height: '100vh',
        margin: 'auto',
        maxHeight: 1400,
        width: '100%',
      }}
    >
      <Document title={pdfTitle} author="{author}" creator="{creator}">
        <Page size="A4" style={styles.page} orientation="landscape">
          <View style={{ marginTop: 16 }}>
            <Text>{text}</Text>
            <Text>{text}</Text>
          </View>
        </Page>
      </Document>
    </PDFViewer>`

**Comment by jeetiss** [comment]
duplicate #714

**Comment by Mario8419** [comment]
> > Can you add more information about your setup. What do you use like renderToString or another method to render the PDF?
> 
> We're currently using the PDFViewer component from @react-pdf/renderer to render out our PDFs.
> 
> ` <PDFViewer style={{ border: 0, height: '100vh', margin: 'auto', maxHeight: 1400, width: '100%', }} > <Document title={pdfTitle} author="{author}" creator="{creator}"> <Page size="A4" style={styles.page} orientation="landscape"> <View style={{ marginTop: 16 }}> <Text>{text}</Text> <Text>{text}</Text> </View> </Page> </Document> </PDFViewer>`

Have you already checked the issue, if a PDF, for e.g. have 2 sites or more, that the PDFViewer is only showing the first site...
