### ISSUE TITLE
Type Error: Main types folder in '@react-pdf/renderer' not importing some types from nested "types" folder 

### ISSUE THREAD

**Issue by jcramercodes** [diegomura/react-pdf#1979]
**Describe the bug**

Many components will throw typescript errors due to insufficient alignment between '@react-pdf/types' and '@react-pdf/renderer/index.d.ts' -> 

For example the "bookmark" prop will throw an error when added to any component because NodeProps interface doesn't have the "bookmark?: Bookmark" type. 

Simply importing:  

import { Bookmark } from '@react-pdf/types/bookmark';

and then adding - 

interface NodeProps {
    id?: string;
    style?: Style | Style[];
    fixed?: boolean;
    break?: boolean;
    minPresenceAhead?: number;
    **bookmark?: Bookmark;**
  }

-addresses this issue. But obviously an update in the package manager (adding/removing other libs) will constantly overwrite the types directory. 

Is there any plans to remedy these type issues? Otherwise - what would you recommend?

**Comment by chathu-novade** [comment]
Seems lot of type issues due to this https://github.com/diegomura/react-pdf/issues/1965

**Comment by jordhanpoillot** [comment]
You can use :


`
  const properties = {
    bookmark: "Coordonnées",
  };

  return (
    <View style={StylesGlobal.section} wrap={true} {...properties}>
      <Text style={styles.titre}>Coordonnées</Text>
      <ItemsTable data={coordonnees} columns={colonnesCoordonnees} />
    </View>
  );
`

or : 



`
  return (
    <View style={StylesGlobal.section} wrap={true} {...{bookmark: "Coordonnées"}}>
      <Text style={styles.titre}>Coordonnées</Text>
      <ItemsTable data={coordonnees} columns={colonnesCoordonnees} />
    </View>
  );
`
