### ISSUE TITLE
Question: dependencies

### ISSUE THREAD

**Issue by styfle** [diegomura/react-pdf#198]
The `dependencies` show jest and learna.

https://github.com/diegomura/react-pdf/blob/master/package.json#L13

Are these required at runtime or can these be moved to `devDependencies`?

**Comment by diegomura** [comment]
I think they can. I don't think it really matters because this is a Lerna project and that package.json does not belong to any npm package in particular. But I don't think there's going to be any damage if we move them to `devDependencies`

**Comment by styfle** [comment]
I see now.
I was curious which dependencies this package relies on.
I think the file I'm for is [react-pdf/package.json](https://github.com/diegomura/react-pdf/blob/master/packages/react-pdf/package.json) which matches [npm](https://www.npmjs.com/package/@react-pdf/core).

Here's a visualization of all the dependencies for anyone who is curious:

http://npm.anvaka.com/#/view/2d/%2540react-pdf%252Fcore

I'll close this ticket since you said that the top level package.json is not published.
