### ISSUE TITLE
zlibWEBPACK_IMPORTED_MODULE_3.createDeflate is not a function while renderin react-pdf component

### ISSUE THREAD

**Issue by Hasham-dev** [diegomura/react-pdf#1987]
**Describe the bug**

I'm using the react-pdf in my CRA application, I implemented the changes craco to resolve the webpack issues 

The react-pdf demo component renders properly in Ubuntu, but when I attempt to run it on a MAC, I get an error. **zlibWEBPACK_IMPORTED_MODULE_3.createDeflate is not a function** , I noticed the similar problem #1935, which was likewise closed without debate.

I tried the solution described in #1935, but it did not work for me. The problem only occurred on the MAC.

**To Reproduce**

I'm not sure if the same issue occurred on any other MAC, but the problem was only in the development environment on deployed link PDF rendering for MAC fine.

```<PDFDownloadLink document={<ORderPdf />} fileName="somename.pdf"> {({ blob, url, loading, error }) => loading ? 'Loading document...' : 'Download now!' } </PDFDownloadLink>```

**Expected behavior**

It should generate an error-free PDF.

**Screenshots**

<img width="657" alt="Screen_Shot_2022-08-26_at_3 09 51_PM" src="https://user-images.githubusercontent.com/64362929/187053648-8e537709-45d1-4aa8-980b-ce61cc80ae40.png">

**Desktop :**

- OS: MAC
- Browser: Chrome
- React-pdf version: 2.2.0

**Comment by NathanFirmo** [comment]
For me, it works running this:

~~~bash
npm install assert buffer process stream-browserify uti @react-pdf/zlib
~~~

and changing the config to:

~~~js
const webpack = require('webpack')

module.exports = {
    plugins: [
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
      new webpack.ProvidePlugin({
        process: 'process/browser',
      }),
    ],
    resolve: {
      fallback: {
        zlib: require.resolve('@react-pdf/zlib'),
        stream: require.resolve('stream-browserify'),
        buffer: require.resolve('buffer'),
      },
    },
  }
~~~
