### ISSUE TITLE
Rollup "browser" build includes "Node.js" dependencies

### ISSUE THREAD

**Issue by kaheglar** [diegomura/react-pdf#1992]
**Describe the bug**
The following is included in the bundle when building a browser bundle with rollup.
```js
import require$$1$1 from 'events';
```

**To Reproduce**
See workspace - https://stackblitz.com/edit/node-9tjqve?file=dist/index.js

**Expected behavior**
No Node.js dependencies included in the bundle when building a browser bundle with rollup.

**Comment by chathu-novade** [comment]
Which react-pdf version are you using?

**Comment by kaheglar** [comment]
3.0.0
The issue is recreated here https://stackblitz.com/edit/node-9tjqve?file=dist%2Findex.js

**Comment by wuelcas** [comment]
If anyone is having this issue still, I solved it by using [the rollup-plugin-polyfill-node plugin](https://github.com/FredKSchott/rollup-plugin-polyfill-node).
