### ISSUE TITLE
Migration guide for 3.0.0

### ISSUE THREAD

**Issue by ghost** [diegomura/react-pdf#1993]
**Describe the bug**
A page or a guide on migration to 3.0.0. We can keep this issue as a guide.

### Breaking changes

* Node.js 12 is not supported anymore.
* You can remove jest config `testEnviroment:'jsdom'` as it no longer needed.

**Desktop (please complete the following information):**
 - React-pdf version [e.g. v3.0.0]

**Comment by ticpoi** [comment]
this.subset.encodeStream is not a function

I got this message after update, What to do to fix this error?

**Comment by jasiekkrk** [comment]
Do you have some external fontkit reference in your package.json?
if so try updating it.

**Comment by ticpoi** [comment]
We found the reason on local and solved. 

We were using <Link> inside <Text> and that was working fine, new version does not accept that. Now <Text> is inside <Link> and the last tag around the text content.

By the way, we are using "@react-pdf/renderer' and @react-pdf/styled-components together.

No other font kit defined in package.json.

**Comment by ticpoi** [comment]
We found the reason on local and solved.

We were using "Link" inside "Text" and that was working fine, new version does not accept that. Now "Text" tag is inside and the  "Link" tag and "Text"  is the last tag around the text content.

By the way, we are using "@react-pdf/renderer' and @react-pdf/styled-components together.

No other font kit defined in package.json.

**Comment by ticpoi** [comment]
We found the reason on local and solved.

We were using "Link" inside "Text" and that was working fine, new version does not accept that. Now "Text" tag is inside "Link" tag and "Text" is the last tag around the text content.

By the way, we are using "@react-pdf/renderer' and @react-pdf/styled-components together.

No other font kit defined in package.json.

**Comment by jasiekkrk** [comment]
Asked about fontkit, because we had same error - but with older version, and initially i thought it was the something related to fontkit we use (some other fontkit ;) ).
But now it looks like the issue with conflicting dependencies of @react-pdf/pdfkit (version 2.4.0 depends on react-pdf/fontkit) and @react-pdf/font (2.3.0 depends streamline fontkit). It happened on fresh install of renderer v2.0.21.
Updating to 3.0.0 fixed the issues (as it uses stramline fontkit across all products). Bit unfortunate to not use major revision for such change :)

**Comment by chathu-novade** [comment]
While running my jest tests I'm getting 

```
 ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      1 | 
      2 |
    > 3 | import { Font } from '@react-pdf/renderer';
        | ^
      4 |
      5 | 
      6 |  

      at Object.<anonymous> (../../node_modules/.pnpm/restructure@3.0.0/node_modules/restructure/dist/src/EncodeStream.js:3:21)
      at Object.<anonymous> (../../node_modules/.pnpm/fontkit@2.0.2/node_modules/fontkit/dist/browser.cjs:1:46)
      at Object.<anonymous> (../../node_modules/.pnpm/@react-pdf+font@2.3.0/node_modules/@react-pdf/font/lib/index.cjs.js:11:15)
      at Object.<anonymous> (../../node_modules/.pnpm/@react-pdf+renderer@3.0.0_react@17.0.2/node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:10:17)
      at Object.<anonymous> (src/utils/index.ts:3:1)
      at Object.<anonymous> (__test__/jest-setup.ts:2:1)
```

**Comment by richardsondx** [comment]
+1 
These solutions didn't  work for me. This is the actual error:
````
rollbar.umd.min.js:1 TypeError: this.subset.encodeStream is not a function
    at EmbeddedFont.embed (pdfkit.browser.es.js:36713:1)
    at EmbeddedFont.finalize (pdfkit.browser.es.js:36866:1)
    at PDFDocument.end (pdfkit.browser.es.js:38689:1)
    at render (index.es.js:2109:1)
    at _callee$ (react-pdf.browser.es.js:226:1)
    at tryCatch (regeneratorRuntime.js:86:1)
    at Generator._invoke (regeneratorRuntime.js:66:1)
    at Generator.next (regeneratorRuntime.js:117:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    ```

**Comment by chathu-novade** [comment]
@richardsondx What the font you are using and how do you load it?

**Comment by jasiekkrk** [comment]
Is it happening on v2 or v3?

**Comment by GavinThomas1192** [comment]
I can confirm I'm getting this on version 2, in our production environment only (running node16.17). TypeError: this.subset.encodeStream is not a function.

**Comment by jasiekkrk** [comment]
Just lock the react-pdf/font to version 2.2.1. It should solve it.

**Comment by richardsondx** [comment]
Locking the react-pdf/font  version to 2.2.1 worked! Thanks

**Comment by marsmallos** [comment]
^This does not work for me. Here are my dependencies:

```
"dependencies": {
    "@react-pdf/font": "^2.2.1",
    "@react-pdf/renderer": "^3.0.0",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.0",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.16",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.11",
    "browserify-zlib": "^0.2.0",
    "chart.js": "^3.6.0",
    "file-saver": "^2.0.5",
    "fontkit": "^2.0.2",
    "react": "^17.0.1",
    "react-chartjs-2": "^3.3.0",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.4.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-spinners": "^0.11.0",
    "sass": "^1.54.0",
    "stream-browserify": "^3.0.0",
    "typescript": "^4.7.3",
    "util": "^0.12.4",
    "web-vitals": "^0.2.4"
  },
```

All I did was update @react-pdf/renderer to 3.0.0 and now I have the error:

```
./node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.es.js
Attempted import error: 'create' is not exported from 'fontkit' (imported as 'fontkit').
```

Would appreciate any help fixing this so I can get back to coding.

**Comment by chathu-novade** [comment]
@marsmallos Any specific reason to install  "@react-pdf/font" dependency?

**Comment by jasiekkrk** [comment]
Hello,
I think if you are using @react-pdf/renderer in version 3, just use react-pdf/font 2.3.0 (or remove the dependency if you are not using it).
Suggestion to "lock" font package is usefule only when you need ot keep renderer on 2.x for any reason.

**Comment by teamayka-git** [comment]
https://github.com/diegomura/react-pdf/issues/1991#issuecomment-1231866752

**Comment by fidaay** [comment]
This worked for me:

https://stackoverflow.com/a/73569921/13593674

Install @react-pdf/renderer@2.1.0
And @react-pdf/font@2.2.0
Then add the resolutions property

```
"@react-pdf/renderer": "2.1.0",
"@react-pdf/font": "2.2.0",

"resolutions": {
    "@react-pdf/font": "2.2.0"
},
```

**Comment by mdodge-ecgrow** [comment]
> ### Update
> 
> You can remove jest config testEnviroment:'jsdom' as it no longer needed.

Can you elaborate on how to do that?  I am getting the error `ReferenceError: TextDecoder is not defined` while running tests in my React project.

**Comment by diegomura** [comment]
Discussion here seems unrelated to issue title. If this is still ongoing please open a new issue specifically for it :)
