### ISSUE TITLE
RangeError [ERR_ENCODING_NOT_SUPPORTED]: The "ascii" encoding is not supported

### ISSUE THREAD

**Issue by Avery246813579** [diegomura/react-pdf#1994]
**Describe the bug**
This is an awareness bug so someone can look up this error caused by breaking changes to v3.0.0. 

It seems v3.0.0 doesn't support Node v12. Trying to run on Node v12 causes the error below. 

`RangeError [ERR_ENCODING_NOT_SUPPORTED]: The "ascii" encoding is not supported`

We had "^2.3.0" in our package.json, and somehow our CI upgraded us to 3.0.0 even though it was a major change. To fix this just lock the version to "2.3.0" or upgrade to a higher node version.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Node v12
 - React-pdf version v3.0.0

**Comment by DaveFPath** [comment]
I am encountering this problem and locking version 2 does not solve the problem.

**Comment by DaveFPath** [comment]
After several days I found the solution to my problem. I am writing this up here for any google'ers that may come across it.

The solution of rolling back to version 2 and locking in the package.json _is correct_... however, in my case I was using a mono-repo with lerna and yarn. Every time I did a yarn install it would end up putting pdfkit version 2.4.0 in the node_modules - This will cause the problem. I had to roll pdfkit back to 2.2.0 and couldn't figure it out.

Until now!

According to the documentation, yarn is supposed to be able to do version overriding in the package.json file via the resolutions block.... but it wasn't working. I am using a mono-repo, and the trick is to put the resolutions in the ROOT package.json - not in the workspaces package.json. (duh! Bad Dave, Stupid Dave. You should have known that!)

Anyway, in the project root package.json, I added this:

```
  "resolutions": {
    "@react-pdf/fns": "1.0.0",
    "@react-pdf/font": "2.2.0",
    "@react-pdf/fontkit": "2.1.0",
    "@react-pdf/image": "2.1.1",
    "@react-pdf/layout": "3.0.0",
    "@react-pdf/pdfkit": "2.2.0",
    "@react-pdf/png-js": "2.1.0",
    "@react-pdf/primitives": "3.0.1",
    "@react-pdf/render": "3.0.0",
    "@react-pdf/renderer": "2.1.2",
    "@react-pdf/stylesheet": "3.0.0",
    "@react-pdf/textkit": "3.0.0",
    "@react-pdf/types": "2.0.9",
    "@react-pdf/yoga": "2.0.4"
  },
```
And HUZZAH! It is now working with node 12.

You should be able to update individual parts to whatever the latest version numbers for react-pdf 2.x so long as pdfkit doesn't exceed 2.2.0.
