### ISSUE TITLE
paragraph from MUI multiline component

### ISSUE THREAD

**Issue by sgavathe** [diegomura/react-pdf#2002]
With the Material UI Multiline Component with the paragraph mentioned below, it breaks the PDF

Steps to reproduce the behavior including code snippet (if applies):
1. Under Material UI Text component, add the below sample text
```
ijklhglkgfnslkgnsdlkgnsdk gnsdlkgnsdfklfgnsdkgskglkgdsgnslgnsdklgslkgsdlgnsdlgnsdlgnsdljgnsdljgnsljgsdjgnsjlgnsdflgnsdflgnlgjnjn hiuosuhsofnsof

hiuosuhsofnsof

fluafbklasbfujoaf

KLUuoafbaskfbauofbauof

LUBDKLABDKASBDKLADBSASDBADBAJSD
```
2. With the SPACE + NEW LINE , the pdf breaks with the below error in the screenshot.
3. Apologies if I am not giving enough content to be able reproduce the error.
4. Material UI Text component is very simple

```
<TextField
          label={DISPLAY_STRINGS.acquiree_description}
          name="description"
          multiline
          maxRows={5}
          className={caseClasses.multilineLarge}
        />
```
_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
Export a PDF with the text above

**Screenshots**
![image](https://user-images.githubusercontent.com/6047188/187990058-412e8ab1-eb47-4d8a-8670-f3eabd0a1ae7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [edge, chrome]
 - React-pdf version ^2.1.2

**Comment by jd-carroll** [comment]
Hey @sgavathe, how do you have your `<Document>` setup? (Is there a `ThemeProvider`?)

I'm facing a similar issue but wondering if its something with the construction of MUI in a separate document tree

**Comment by jd-carroll** [comment]
Well I think the issue is that you can't use MUI components under the React-PDF document tree... : stuck_out_tongue_closed_eyes:

**Comment by diegomura** [comment]
Exactly :)
