### ISSUE TITLE
Tspan elements produce an error in v3

### ISSUE THREAD

**Issue by tinkatinka** [diegomura/react-pdf#2003]
**Describe the bug**
Tspan nodes within Text nodes within Svg nodes create an error:
`TypeError: undefined is not an object (evaluating 't.box')`

**To Reproduce**
See [this repl](https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a06180076a0736402e191876a004d8404b305df8036000c3002f801a660a025006e66cd42458c24300c31eab180078008a180ae016d9182800f8cdb730015bb238b853a46041408524e1e053831002f647400220041001638d736748b2c00372e182cb1640077002110000f78f979002624f93ad4b70c8b00156432d80ab880465938987878dec6e6e6f316884e30182ee181a1bee700251a6028005a7661003318313450104473007a09a9b4d18b33f69726f713ecae4b87af1e4bd3eb607b473bcd6d15b50d61e4b000c548543030990147a01980ff200)

**Expected behavior**
Tspan within Text nodes should render without errors.

**React-pdf version:** 3.0.0

**Comment by marco-hd** [comment]
The same error in 3.0.1. Can't use `<Tspan />`.

**Comment by PieterT2000** [comment]
Anybody found a workaround for this?

**Comment by diegomura** [comment]
Linked example works in latest version
