### ISSUE TITLE
PDF on aws lambda broken

### ISSUE THREAD

**Issue by FloMueh** [diegomura/react-pdf#2009]
i deployed a JavaScript Lambda function to aws including the react pdf ogic. 

locally everything looks like expected.
generated with aws lambda the pdf is broken.

i am using the node api from react-pdf.

checkout the screenshots.

i use local and on the aws lambda the same version of node, npm etc. 
i cant share and repo cause the issue just happens when its deployed to aws.
Its the bottom part of the generated page if this matters. 

Any ideas how to fix this? Would appreciate each hint.

**Screenshots**
expected and locally:
![good](https://user-images.githubusercontent.com/20256515/188861512-a109ff7d-c756-4b91-bb72-8bec3ffc24fc.png)

over aws function:
![broken](https://user-images.githubusercontent.com/20256515/188861528-d2e874a7-25fb-4d0e-87a1-f9547d647f0a.png)

package.json
`"dependencies": {
		"@react-pdf/renderer": "^3.0.0",
		"aws-sdk": "^2.979.0",
		"html-react-parser": "^1.2.8",
		"hyphen": "^1.6.4",
		"i18n": "^0.13.3",
		"lodash": "^4.17.21",
		"mkdirp": "^1.0.4",
		"moment": "^2.29.1",
		"node-fetch": "^2.2.0",
		"ppsharedlibrary": "^0.9.53",
		"react": "^16.8.6",
		"short-uuid": "^4.2.0",
		"uuid": "^8.3.2"
	},`

**Comment by carlobeltrame** [comment]
From the looks of it, the font you are using in the pdf is not available on aws, so react-pdf falls back to the default Helvetica font. If your font has some high line height embedded, that could also explain the layout differences.

**Comment by FloMueh** [comment]
hi @carlobeltrame , 

thanks for the hint!

i use Roboto font. I embedded this font in the project und assets as ttf files. I copy the whole project folder to an docker container. 

I am just wondering cause the issue is "just" on the first page. On the second, third etc everything looks fine

**Comment by carlobeltrame** [comment]
Then it might be an async font loading problem. Please check out #1494 and related issues for other users who had to make sure the registered fonts were finished loading before they could be used.

**Comment by diegomura** [comment]
Thanks @carlobeltrame . Flagging this as resolved
