### ISSUE TITLE
TypeError: module.runSetters is not a function

### ISSUE THREAD

**Issue by sherryysj** [diegomura/react-pdf#2011]
**Describe the bug**
It throws this error `module.runSetters is not a function` when I use it on `Meteor React JS`. 

I also tried `npm ci`, delete `node module` then reinstall, and also on version 2.3.0, all throw the same error as well.  

![image](https://user-images.githubusercontent.com/45263452/189010831-7283bad4-ff36-45df-bc20-914dc0badbd8.png)

Code:
![image](https://user-images.githubusercontent.com/45263452/189012812-c4622b94-af8c-4bc0-af5a-fe4c766ee82d.png)

![image](https://user-images.githubusercontent.com/45263452/189012832-5adb07a4-f977-4370-b6cc-82267f0f5fa5.png)

Similar questions found online:
https://stackoverflow.com/questions/73636378/i-am-trying-to-integrate-react-pdf-renderer-in-my-proyect-and-i-get-this-error/73642851#73642851

**To Reproduce**

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by LucianoCanziani** [comment]
Same problem

**Comment by Floriferous** [comment]
Here's a very simple reproduction: https://github.com/Floriferous/react-pdf-meteor-error

**Comment by sherryysj** [comment]
> Here's a very simple reproduction of the error: https://github.com/Floriferous/react-pdf-meteor-error

Thanks for this!!!!

**Comment by Floriferous** [comment]
It seems like version 2.1.2 created this bug, whereas on 2.1.1 everything works fine.

**Comment by sherryysj** [comment]
Thanks! I am going to have a look for 2.1.1, if there are not many differences with 2.3, I could roll back to use that version for now.

**Comment by paulincai** [comment]
This talk about Meteor's Reify operation (https://blog.meteor.com/reify-meteors-evolving-javascript-module-compiler-70425fa45d81). This seems to be a problem related to Reify. Since React-PDF is an NPM library could you try to recompile it with Meteor's compiling system and see if there is any change (https://guide.meteor.com/using-npm-packages.html#recompile). I am not sure what changed here between versions. Will try to understand this a bit deeper.

**Comment by paulincai** [comment]
Could be related to adding this: 'rollup-plugin-polyfill-node'

**Comment by diegomura** [comment]
There's no `runSetters ` call inside our code nor any code it brings. Could be what @paulincai said but it's unrelated to this project
