### ISSUE TITLE
I can't download the dependency

### ISSUE THREAD

**Issue by CesarGMEFA** [diegomura/react-pdf#2012]
**Describe the bug**
I am downloading the dependency but I immediately get an error. is it me or is it the package?
[IMAGE of terminal with error download](https://prnt.sc/8_dU2ErEHpod)

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
I want to download and use it :D

**Screenshots**
![image](https://user-images.githubusercontent.com/83330595/189218343-da0f0559-7d8c-48bb-8d14-1e4b1fc4eb42.png)

**Desktop:**
 - OS: Windows
 - Browser chrome
 - React-pdf version v3.0.0

**Comment by axel7083** [comment]
The library is not compatible with React 18 see https://github.com/diegomura/react-pdf/issues/1971

**Comment by CesarGMEFA** [comment]
@axel7083 Oh thank you!
