### ISSUE TITLE
Please add support for react 18

### ISSUE THREAD

**Issue by alokjain-lucky** [diegomura/react-pdf#2020]
Try installing the preact-pdf package with React 18, it will give you an error 

![image](https://user-images.githubusercontent.com/5526402/190994166-548766ff-b3cc-4fa0-b5da-4f52836d485a.png)

**Comment by chathu-novade** [comment]
Duplicate of #1971 , #1878

**Comment by jeetiss** [comment]
duplicate of https://github.com/diegomura/react-pdf/issues/1878
