### ISSUE TITLE
Slow with many elements for custom table element?

### ISSUE THREAD

**Issue by imatwork** [diegomura/react-pdf#2032]
When I try rendering a large amount of elements for a table in a PDF, it takes @react-pdf a long time to render it. It specifically seems related to `resolveDimensions` and whatever Yoga is doing.

Here's an example of the timings I'm seeing:
110 rows (10 subheadings w/ 10 rows each), 26 columns   - **2860 elements at 2.3s**
510 rows (10 subheadings w/ 50 rows each), 26 columns   - **13260 elements at 6.7s**
1010 rows (10 subheadings w/ 100 rows each), 26 columns - **26260 elements at 21.7s**
2010 rows (20 subheadings w/ 100 rows each), 26 columns - **52260 elements at 36.3s**

Now I can understand @react-pdf does a lot of stuff internally that might make it slow. The tables we're rendering at least have fixed widths for columns and rows, so we can calculate everything up front. Unfortunately, there was no way that I could lay out the table that would make it much faster.

I tried using fixed page sizes, turning off `wrap` on page and all other elements, using `position: 'absolute'; top: N; left: M;` styling, using SVG elements to layout the table. None of these were able to get a 500 row 26 column table rendered in under 5s.

Am I doing something wrong? Any insight on how I can speed up this table, setting anything with the dimensions values we have precalculated up front (x, y, width, height) to speed it up?

Thanks

**Comment by carlobeltrame** [comment]
Yoga is a flexbox implementation, and is used for calculating the dimensions and positions of all elements rendered into the pdf. It is written in C and is run as WebAssembly, or using asm.js if WebAssembly is not supported on your platform, so it is already optimized for performance. It is an integral part of react-pdf and there is currently no way to "skip" it. Since [Yoga](https://github.com/facebook/yoga) is a separate software project from react-pdf, you could try researching speedup options there. But there is a chance that there is simply no way to make it faster.

One idea though: You could try splitting up the table into multiple `<Page>` elements. I am not completely sure, but that might trigger react-pdf to call yoga mutiple times with smaller workloads, which might make the internal calculations easier.

**Comment by imatwork** [comment]
> One idea though: You could try splitting up the table into multiple <Page> elements. I am not completely sure, but that might trigger react-pdf to call yoga mutiple times with smaller workloads, which might make the internal calculations easier.

This was something I tried previously as well but no luck, didn't see a difference in timings

> Worst case you could always just use https://pdfkit.org/ directly. React-pdf uses that internally to render the layouted PDF. But then you lose the layouting and pagination features which react-pdf implements, so you will have to calculate the positions and dimensions of all texts and lines yourself.

I will look into this

> Yoga is a flexbox implementation, and is used for calculating the dimensions and positions of all elements rendered into the pdf. It is written in C and is run as WebAssembly, or using asm.js if WebAssembly is not supported on your platform, so it is already optimized for performance. It is an integral part of react-pdf and there is currently no way to "skip" it. Since [Yoga](https://github.com/facebook/yoga) is a separate software project from react-pdf, you could try researching speedup options there. But there is a chance that there is simply no way to make it faster.

Well, would there not be a way for it to do less work? If I lay out 2000 elements each with fixed width, height, top and left and no text wrapping, what is there for Yoga to need to calculate. It should be lightning fast for a case like this but that's not what I'm seeing.

I made a couple test cases and I'm very confused by the performance of these:

[Position Absolute 42 Rows, 26 Cols](https://stackblitz.com/edit/react-ts-cwkeh1?file=index.tsx) - This one doesn't actually finish... If you bump down the rows to 39 it does finish in ~700ms. Maybe a bug in `resolvePageDimensions` when an element is position absolute'd off the page. That's at least the function it spends more of it's time in when I pause the debugger.

[Position Absolute 500 Rows, 26 Cols w/ large static page size](https://stackblitz.com/edit/react-ts-wyg9lr?file=index.tsx) - 13000 elements finishes in ~9s. Uses position absolute, top left width height flexWrap nowrap, page wrap={false} and size={[612,12000]} so _everything_ is fixed/set in styles and shouldn't do any extra layout stuff, but it is still 9s. The profile is below:

![image](https://user-images.githubusercontent.com/95493333/193213997-292bd439-a27c-483b-b440-29a518a5850a.png)

About 50% of the time is spent in resolvePagination but there's only one page with a fixed size of more than the elements I'm drawing. It also has wrap={false} so should not ever page break. I'm not sure why this is.

[Flex box 500 Rows, 26 Cols](https://stackblitz.com/edit/react-ts-vlpvjv?file=index.tsx) - 13000 elements finishes in ~7.5s. Uses one large column of fixed width/height Views, each with cells of fixed width and height. All use flexWrap: nowrap, wrap={false}. Everything but position is fixed/set in styles. Surprisingly faster than the above where everything is fixed.

The output of this breaks the table over 13 pages, but it had size="LETTER" and wrap={false}, so it should not break, right? A bug?

Here's the profile:

![image](https://user-images.githubusercontent.com/95493333/193216093-76036d8e-c074-40e8-a932-0aca500bb731.png)

~50% in resolvePagination, but it should only be rendering one page.

These cases are not all that complex and should not be this slow, right? Especially when so many constraints are applied to each element that it shouldn't have to measure the content, do word wrapping, etc to determine all the "hard" values. It should be able to take a fast path.

Thanks

**Comment by imatwork** [comment]
> I managed to fix my problem by setting the first column to a fixed width and additionally wrapping its contents inside a <View style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }}></View>. This way, the contents of the first column cannot influence the sizing of the remaining columns in any way. 

Hmm, did you try that on the examples and it was faster? I saw no change in those stackblitz when doing that.

> And specifically by fast path... (from my last comment)

I implemented a few of these changes in my local branch of react-pdf and have begun seeing how they affect performance. One is also a bug fix. I will make PRs for these shortly.

**Comment by carlobeltrame** [comment]
In my case I was not concerned with performance. I was simply reporting my experiences with the layouting engine, and how I managed to "disable" parts of the layouting logic by encapsulating some components in absolutely positioned wrappers.

Nice to see you are getting around to propose some fixes though :) let's hope the maintainer can find some time to have a look at it.

**Comment by imatwork** [comment]
> Worst case you could always just use https://pdfkit.org/ directly. React-pdf uses that internally to render the layouted PDF. But then you lose the layouting and pagination features which react-pdf implements, so you will have to calculate the positions and dimensions of all texts and lines yourself.

So I tried this and my tables render in a negligible amount of time now. I am going to switch my efforts to working with this and exposing more of the pdfkit/PDFDocument internals from react-pdf so I can work more with the low level stuff while also using the high level API.

<details>
  <summary>If anyone else wanted to tackle performance issues though, here was my last findings:</summary>

I put together a table example in the `packages/examples` repo which you can find in my fork. I also added a timer to the examples so you can see how long a render takes, but Chrome/Firefox's profiler works better to check actual timings.

`resolveDimensions` takes a large amount of time but can't really be skipped because it traverses every node and calculates all dimensions (maybe you could make a layout with everything known ahead of time but I didn't want to mess with checking for that, seemed hacky). Here's the profile:

![image](https://user-images.githubusercontent.com/95493333/196510256-efc43080-a514-40cd-8cc0-43f8c91a0a5c.png)

This mostly descends into Yoga, but what I didn't realize earlier, is that there are callbacks to `react-pdf` at some point (maybe the measure functions? I didn't look). You can see in the below profile though that Yoga eventually calls into [`layoutText`](https://github.com/diegomura/react-pdf/blob/master/packages/layout/src/text/layoutText.js#L73).

![image](https://user-images.githubusercontent.com/95493333/196510588-77f4772b-6404-4ce9-b3e3-2ad36e0b0412.png)

`layoutText` has a simple responsibility and gets called a lot so I looked into optimizing this. What I noticed is that `react-pdf/textkit` gets passed a couple runs generated in [`getAttributedString`](https://github.com/diegomura/react-pdf/blob/master/packages/layout/src/text/getAttributedString.js#L91) as fragments but turned into runs with `fromFragments()` (it can generated excess fragments by not reusing old string fragments when possible). These runs start going through textkit's [`layoutEngine`](https://github.com/diegomura/react-pdf/blob/master/packages/textkit/src/layout/index.js#L43). Each one of these runs generate 3 more runs in [`preprocessRuns`](https://github.com/diegomura/react-pdf/blob/master/packages/textkit/src/layout/preprocessRuns.js#L30) which then are [flattened](https://github.com/diegomura/react-pdf/blob/master/packages/textkit/src/run/flatten.js) into a flat set of runs with unique attributes applied to each part. I started to optimize this but switch focus.

The above, when applied to many simple text elements causes a lot of excess work that doesn't need to be done to happen.

</details>

**Comment by imatwork** [comment]
I have been able to solve my problem by switching to `pdfkit` and rendering my table pages through there instead. [This PR](https://github.com/diegomura/react-pdf/pull/2059) would allow me to do this in the main package.

**Comment by astahmer** [comment]
[related](https://github.com/wojtekmaj/react-pdf/issues/1295), created kind of the same issue but in the wrong repo (😅 )
