### ISSUE TITLE
Empty PDF

### ISSUE THREAD

**Issue by MRThomsen1** [diegomura/react-pdf#2033]
**Describe the bug**
When i download the PDF with the PDFDownloadLink I can't open the file. Acrobat Reader says: "There was a problem opening this document, This file can't be opened, because it doesn't contain any pages".
When i try to display the PDF in the browser with the PDFViewer there is no PDF. Just a button that says: "Open". When i click the Open button, nothing happens, and the console logs: "Not allowed to load local resource: blob:http://localhost:3001/6cb2609e-813e-48ee-9c2e-67e966133323#toolbar=1"

![billede](https://user-images.githubusercontent.com/75175688/193141433-18e0d48e-cf38-45f8-8a22-c9245870faba.png)

![billede](https://user-images.githubusercontent.com/75175688/193141268-7e0b52fe-bcda-4ace-879f-4f4310037f40.png)

![billede](https://user-images.githubusercontent.com/75175688/193140920-d317ae76-efa9-4c10-8917-afe5fd4fd97f.png)

I had thought the problem was with React 18, so I tried downgrading to 17, but the problem persists.

I simply copied and pasted the example from the docs.

**Comment by MRThomsen1** [comment]
This was fixed by changing pdfDocument to PdfDocument as a react component must be capital starting letter. I didn't get any errors in the console apparently because in both instances it was wrapped in either PDFDownloadLink og PDFViewer... Lot's of troubleshooting for one letter not being capitalized properly.. damn

**Comment by rspauwen** [comment]
I'm facing the same problem, but the solution doesn't help. The problem only occurs in Chrome for me: Firefox works fine.

![image](https://github.com/diegomura/react-pdf/assets/538220/81310f88-087e-4152-98de-dab5d2f5c068)
