### ISSUE TITLE
node_modules/base64-to-uint8array/index.js:1:49: ERROR: Expected ";" but found "+"

### ISSUE THREAD

**Issue by andyhmltn** [diegomura/react-pdf#2037]
**Describe the bug**
I'm trying to build a vite project that uses `@react-pdf/renderer`. I'm getting the following error on build:

```
✘ [ERROR] Expected ";" but found "+"

    node_modules/base64-to-uint8array/index.js:1:49:
      1 │ import * as __require_for_vite_b7Wt3v from 'buf' + 'fer';
        │                                                  ^
        ╵                                                  ;

11:21:13 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/base64-to-uint8array/index.js:1:49: ERROR: Expected ";" but found "+"
```

**To Reproduce**
I've got a library package that installs:

```
"@react-pdf/font": "2.3.0",
"@react-pdf/renderer": "3.0.0",
```

When importing that library into my Vite project I receive the above build error

**Expected behavior**
It should build without error

**Comment by diegomura** [comment]
Please check examples in the code, there's a vite project working there
