### ISSUE TITLE
Version doesn't support

### ISSUE THREAD

**Issue by Amyx000** [diegomura/react-pdf#2039]
React 18.2.0 doesn't work with @react-pdf/renderer 3.0.0 ?

npm ERR! Found: react@18.2.0

<img width="295" alt="image" src="https://user-images.githubusercontent.com/104687128/194226639-72367a13-55c4-4584-ac8d-38eb1cf1d5b0.png">

**Comment by kalanchoej** [comment]
We've also been running into this issue.

**Comment by chathu-novade** [comment]
Duplicate of #2020 #1971 #1878 #1926
