### ISSUE TITLE
index.js:1 TypeError: fontkit__WEBPACK_IMPORTED_MODULE_6__.create is not a function

### ISSUE THREAD

**Issue by dhananjay-nickelfox** [diegomura/react-pdf#2044]
**Describe the bug**
Not able to download the pdf. Getting this error. 

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

Getting this is console. Not able to see the download button.

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/92445462/194487690-03b40643-6bf4-4ff9-8469-8036477944ac.png)

![image](https://user-images.githubusercontent.com/92445462/194487740-1e9b772d-d380-4ae4-843a-69681e5d9599.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser ==> Chrome
 - React-pdf version [3.0.0]

**Comment by ErikBahena** [comment]
Hey, @dhananjay-nickelfox 👋
 I'm encountering the same issue. Any resolution?

**Comment by dhananjay-nickelfox** [comment]
Hey @ErikBahena. Not did not find any solution to this. You can down grade to the lower 2.x version and try that. The font family css was creating the main issue here.

The only workaround was to use the font family that are initially supported by the library. That would not create an issue. 

![image](https://user-images.githubusercontent.com/92445462/195086099-fd3eb1a3-4a17-4e34-ac9a-91f16c96dab0.png)

**Comment by ErikBahena** [comment]
@dhananjay-nickelfox Thank you!

**Comment by dobahoan2792000** [comment]
I tried to downgrade to the lower 2.x version but it seem not work, anyone have another solution :(

**Comment by ErikBahena** [comment]
@dobahoan2792000 only thing that resolved it for me was using an old .lock file when building
