### ISSUE TITLE
Numbers are reversed when mixed with RTL text

### ISSUE THREAD

**Issue by madebydor** [diegomura/react-pdf#2045]
RTL is being a real pain in a project I currently work on

Take a look at the attached picture:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/7532901/194505757-703558c9-139a-4e46-abf8-29bf69bf43dc.png">

**On the right** - "Agent 007" - 007 is displayed correctly
**On the left** - "סוכן 007" - Note how the number is **reversed**

I believe it will be the same with Arabic
Is there anyone who faced the same issue?

**Comment by chathu-novade** [comment]
There is no official RTL support yet. https://github.com/diegomura/react-pdf/pull/1821 and https://github.com/diegomura/react-pdf/pull/1485 was supposed to bring the feature and still haven't

**Comment by diegomura** [comment]
There is RTL support now. Given this was posted before it was I'll close it. Please lmk if this issue remains
