### ISSUE TITLE
`Not valid image extension` when using `SVG` `url` on `<Image />`

### ISSUE THREAD

**Issue by ItzaMi** [diegomura/react-pdf#2048]
On my project I'm fetching data from Sanity and I have an SVG that I want to display in the PDF. I'm using `Image` for it but my PDF comes out empty and I have a `Not valid image extension` coming from React Devtools.

Any idea on what might be happening? This seems to happen with any SVG URL.

[REPL example](https://react-pdf.org/repl?code=3187b0760ce02e0040ca04302d801c03605318178600a0128700f9f00a061801e004446005724330a622cba8014101cc3760121055009248f9608009d8360044002ca141410017007a4d2050b60680258a04d2a003a10d37a680262003b98342012dcd019802300062f013800d934bc01580058009922bd02bc01d9fdcc2000dd79e461354938603928a93479f9d9f334e9199959d80801b8c9ea0094301180a0b86800c5cda4596c31a4f0a911513133896ac880000)

**Comment by chathu-novade** [comment]
Image component only support jpg and png only. SVG images are not supported. Use <Svg> tags to construct the SVG image. https://react-pdf.org/svg

**Comment by anhtuan219** [comment]
@ItzaMi I have a similar issue. I have SVG data url and when I passed it to `<Image />`, I got `Not valid image extension` error too. I found [this solution](https://stackoverflow.com/questions/40509755/convert-svg-dataurl-to-base64) that worked for me. It might help you. Basically, you should convert SVG url to SVG data url then continue convert it to PNG url, then you can passed PNG url to `<Image />` like normal
