### ISSUE TITLE
Adding empty view to crash overflow and layout

### ISSUE THREAD

**Issue by Akaprog** [diegomura/react-pdf#2049]
In some cases (one example is from real-life application, not fully isolated) adding empty <View/> at line 115 would crash layout
![image](https://user-images.githubusercontent.com/2947779/194923295-5ea5b10b-7b46-42c0-ac4b-dabd332c19eb.png)

[REPL](https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e181bc05037cca185008602598c804e017367818c016c990399351d013000c00d037c017d06322519313ab91a31000dda8033442003b9d00e44cc80133d52b58b9f92400f2801e4955551bb724488c80070864231a17202d897300190a543a004613111352002314191f4618902a432a0021102828105f3a002230d7580810173d18362a64787cc8b964d4ea0025764e02a292b2fd4aeadafaa494b4c0e4652e1842e2b86e8aaa9abac48246b4801510570ea9d2f2def981827f2a360a358d89805a4e85c60048757d28261a2d000e5e00522d1f611f7aaa077a299f0aa643980022646ab00a06470015feea6b902482e361800092925f041b4c029248a85f462887cc027b60813045b03c0500032990005ec870809a930658b4dae34997476737ebb3ee7a47b68002c1f6f2535c2403050d82331ab3f6f8195cac06c56871c6613674b657a7969ce862954c0d5868d665b2b91359b94b480188917c64443c00a74900015ca878ba4912000057f9d390aecca20f4f96fbd4008e2f04a521dc40673395ec94d419daef767a7d7ee400783a1f0d9123d1d8e938049a04b1b9da5d64acdb618700510041545800aae830a091a62cda659305d59a2df2c54eaf540c9c6ab5ed31ecf4cf3b631a60a6f65afad393ca6ecdc2d14c0b4003666e669d2eb747a265edf7fb031010c810730127e098bc1a16139b42d274d33f254090f03186bb3c002b314c6166398def983e4593e2f82c1f872201e8b7ac87381af2b3c0033300be112040fcc2000dc3823ab480074d531cd035000050e1c0b5e7989ef7a16c5b3eff14a040407eb689c140ee0d0003d04994080b46180a0c464140103d1de84959840127718f8962039ccd3206c37a88090542d1593285f3080025151d45d10c67804ab13e3281c6de5a369c86e915809f81093589ea2789524c9727200a5292a5506a4695a4163a5f17a456e6540964e03655134710f46194e4b16c4c06e6e61e579bc4be61846651e87e5c0c2505d9085d2720b27c98a729aa7a9b4a69654a1ff39c95590c9146a97a5994e0ca37a60342b0980300ac543c00028950ff150cc75980810d5140be9cdcc7b2000f18220300deaf8f88007ceca3087506241b0c81c04cb20e83e41d98af91c050120af560080a02a72458708d7652a621d001a990c83a860c1050cc3ea37dbf7a0ff4fd80ed1b10a0a0d1d2b282250637f403a82d15fa83801e082006220802b08200bc208017082000c20302004220803c882006c2034e008220ace001c203020b803f08200022034e002c20801f082b380130828b4cc0b800f0814b7ce0bfcdd354ff312fd3acd3387449f8e58f0fe006f43b0c9b30223b0ca3281a324ca9d8f20b8e52d6f2324fdb44f451a0bbe0e9be6fbb44e7bbf4a964afb7eedd46d4097600842052ccbb2cd3acdf3b2d4bb2d3380370820b59cc04ae4bfcd6b74cf30cff334cc08030880f319f9780330820b12c67eccc012ff34ccd774eab02c9742cc019cd38038883d3fcd37803b0813380230814b7dfa774f0f15dcb34e8b9cceb74dd380348812b301f34cdd312d33a2deb9bde72de17c5d4b8027080c0c2d4b2ae009220fcc490cd67b3e0fc5ff39bf8b0ccdff4def5afb34ac007e03651d2dabb09201d40502376b6d8997b5a2c018038708ea6c40600220266efad0d81348110dc05231c156cf045b1f066df049080e30383a632764836e8508f6e8c43bd11f6042e85234a18c331987561502406007c1051669ca58b70ce4cc79a0019105ee82ca5ad34662cd45bf362e2cc45a08c002220fcd444332ee2cd5388f1569cdd7a00511018074c69b8f51135ca598b61eacc8c56f296e3cd780b73e402b071b1ba08c885c30f1fedd8430876f03104f088668230700ec13e308440a3a5e32da90e216c26dbf8b8134208740e494c2112d0a81f4283a70d26dc3226476c18011040d786729142d35b6b5d6301659af766b2cfb9d32dea9c69bcb1a679d5794b571203227c4ef1c83d25e4809083b25fb43aa12f7b84f71433624c4e89b75e6624c0ea8df263b1207119d9a4dc96b202564e0956d765db759f029838cf06933b0408a1122355a489ce7dd07acf32e1acb58af3d6753ec42724e29d4bbd8ade7ad77bef43e0fdcb82f25e2bdd792b15132ca597f51130b7a444b998b223b0cbd9702c661ce29c6dd074cb71d1dfa72ca8124b4d992e4147291849389c7360530d49474e9550d26073fa732d398532942310131d598d3616f4d2479744ee2dba5ab2f9acc6fbf0180fdca57371a6aa269968b5e301e153331eb3c9bb1f02e1accfa5f6be77c547f344e39c198c005623d65bf3016800e440aa7bcdd64cd916ccf4514b5d872d194128a4f2ec1e830012082f312e65da5b3331efca33b8894e2cdac7f70d61ddce15749629de98774be3cd65bb311efcc66512d45642c05a2f2545aa9524919293364e31d97e3cb664961eca6b662a615cbb955b101fead7a4f5163009f9889e6fcdd47332d6f5d1b9aad91ddc3a5ef18023da5a08d96e23ed70b2665ac9d610be9f9a127a2cf558bbd6b6b6d7ea602002c105113cdfb60ee5d73d274b319d52ce742eabe17b576cb0b534c47b9748d7adf96e77cea7c4bb18a968002441f9a4f735cc4001c80061083300002c92d668419acae6c39032d2452d43e431b49c8098ca3d561fa598cd950ceddcdbce4e2df5c6d8f5f681dfcc8765ef1653a6f5dec5d8fae9a7ce7de2cdf47ec5665c756fefe6ffa80c81980e06a0ec1f838868f708ba0e79208766e0044c518a643c4a4b5e1b2d4dab86eed6d572f14c025a7403a5748ee65dcba18f2e12c00d0f32e3cd3b94b7665aa6574b6be19d67846f112677b80f6b32a63760cd2525a30cac8e13872b76ca65f865977b75017382c64ae16467d4a0eb973b84468c51923c58ef77e17aa5aaf35ebc717958851ecc05bb317579add5a99c991739769ee5ba7a3ba0c00b82049d7cd5582d0173af16eeba5b567618ad5b22e46281b75a62ca192309762ef0ec1800304079a18e11d3a2794f769d97d9bb5899eea6ac69d1b5a7a6c8483df5385a289de9b72e76d9eb9baaeff9df1bb608e935c33b7fac3de8b076fac85ac5896f7635cba14d599ef669ebccbb5f24d12cfe53766b31d9ba8ea6369dc453725d2bad8e60f5d1d7aee5cc9b053eae52dfbe83000e0806b1cb91b3cd998b35665e4f709242c73aa753d40ad3b34ff9cfbf973cff9c223ba58efd3cdd995354728bd1eddb904173c605ac71b286f56fbb5179878d86dd2f3977d9d3203002d080ab2d679733879a664dd5982b5964ac74583bf965ca1f9dc2dbd7d4cbd997d8a92feebd3ad7598c0400b220eaff9a6b92717cd9beba566bdcdd758c74b302fa1f1758cc2f0da8e9f6987934bafeab3839ff96f26a4a3931f2379b975163cd557e38a6e7645dddeb7a729ec4350f446b76d5d194ae1ac80c00c420ccd398da9076a2346489963ac99fb3195cfabf94ac119bce993345b22279c3ee474eff988f73863c601438ab2872ef0bd0fb6e7ee84c0044208bc99a0ad9602d5fb06b5500e699339a6fef707559bb71243c57c1b55a22c2bfd9f5b88d5fd23ef77174718e08bc457f66e562a79b9c3f1e6d798c4bf9cf8bf9ce02594c52f91c4338a58af8e75259e986039f473c85927da7d67cd7405cb6ccfd17c9fdf6dc8d92d8d8601b804fd85c17df3ca257ac46d5ecc3d25d6fd0bdefce5d1fcefcbec5fc28cdfdfb900114409dc91d4b851c48283d2dd9eca3cf02edd7ec601208c50c20c21f8345d043cfc4852fd982195c3ca5de82e04cbc26497cabd71c4050005041158744d784ecdf8643e42982d439b471c864404883781b81b81ce1780001d9ce1b814f14c228303d64231dc82a8265d8bd85d23de2d49863c045f98e35d7865479941c1c4538d3899965880ccb92d5ad4ed41d593cf58f3d1422c3a84542e838435941fdcbc942a6df03edda38c22222d78a22623c78e23d39123fe45226d5f99ed4cdd095e7db02e2d6b444257c0f5fb4f993a581c3c3c820427c217d4fcc84143ee91e92e80d84e8ce82e98812d9ac83287000c8481a10830c111d1728c00d21989265168568d686006956c8f752e2ae3ae26e2a916e3ee21e31e34c0edc9e35e2de3f00800000)

**Comment by diegomura** [comment]
REPL works now (besides some small overflow issues) but not like in the screenshot. I assume the other is a small style that needs fixing. Will close
