### ISSUE TITLE
Error Nextjs Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by bogordesaincom** [diegomura/react-pdf#2053]
**Describe the bug**
Application error: a client-side exception has occurred (see the browser console for more information).
 
Just show that on production

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

**Screenshots**
<img width="1429" alt="Jepretan Layar 2022-10-12 pukul 23 12 51" src="https://user-images.githubusercontent.com/51335197/195395001-56ea0554-2263-453a-a155-97662cefac52.png">

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Browser chrome
 - React-pdf version [e.g. v3.0.0]

**Comment by mkhennoussi** [comment]
Same issue for me, happens only in production not dev. Any ideas ? Thanks !

**Comment by bogordesaincom** [comment]
yes that `next.config.js` change to `swcMinify: false `

**Comment by steveluscher** [comment]
See https://github.com/vercel/next.js/issues/41527.

**Comment by DAJAKMPM** [comment]
does your app build successfully? mine is lagging on the "next build" process

**Comment by itspasindu** [comment]
> 

In which tag should this code be put?

**Comment by itspasindu** [comment]
> Same issue for me, happens only in production not dev. Any ideas ? Thanks !
> 
> Edit : It works now if you put `swcMinify: false,` in the next.config.js file ! Seems an issue with swc not react-pdf

In which tag should this code be put?

**Comment by omunite215** [comment]
> Same issue for me, happens only in production not dev. Any ideas ? Thanks !
> 
> Edit : It works now if you put `swcMinify: false,` in the next.config.js file ! Seems an issue with swc not react-pdf

It Worked. I have been trying hard to solve this error for so long. Thank you so much.
