### ISSUE TITLE
Issue with flexbox under page with wrap

### ISSUE THREAD

**Issue by flaurida** [diegomura/react-pdf#206]
Hi React PDF,

I am noticing some issues with flexbox after applying the `wrap` flag to the parent page. For example, I cannot get a component to wrap in a flex row. What happens visually is the second nested component (in this case the red box) simply disappears. The component below is a simple example:

```
const styles = StyleSheet.create({
  main: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'green',
  },
  blue: {
    width: 200,
    height: 200,
    backgroundColor: 'blue',
  },
  red: {
    width: 200,
    height: 200,
    backgroundColor: 'red',
  },
});

const Info: React.StatelessComponent = () => {
  return (
    <View>
      <View style={styles.main}>
        <View style={styles.blue} />
        <View style={styles.red} />
      </View>
    </View>
  );
};
```

And I try to render it like so:
```
  return (
    <Document title={copy.documentTitle}>
      <Page size="A4" style={styles.page} wrap>
        <View style={styles.container}>
          <Info  />
        </View>
      </Page>
    </Document>
  );
```

Please let me know how to fix this? Thanks!

Sincerely,
Laura

**Comment by flaurida** [comment]
Note that I am also happy to pursue an alternate solution, as long as I can get two columns. Please let me know!

**Comment by flaurida** [comment]
Isolating this issue, it is generally when there are nested elements with flex display.

**Comment by flaurida** [comment]
I am also having issues where the content is overflowing the page a bit, even after adding padding to the container `View`. Thanks again for all the help!

**Comment by flaurida** [comment]
Update - I realized I needed to add the padding to the page itself. My last major issues are nested flex and the fact that extra pages are rendered at the end. Thanks so much for the help!

**Comment by flaurida** [comment]
Unrelated, but does the `lineHeight` property work on `Text` elements?

**Comment by diegomura** [comment]
No. It's not supported yet

**Comment by flaurida** [comment]
OK, no worries. My biggest question now is how to remove the extra 1-2 pages I am seeing. Thanks so much again Diego. The flex stuff works OK so long as I use percentage widths and don't use more than two children elements.

**Comment by diegomura** [comment]
Currently I don’t think there is any way of removing those while using the wrap feature with 2 columns. It’s just not the way it’s working right now. Sorry. 
There is an ongoing effort of changin the text layout algorithm, which will have impact on the wrapping feature as well

**Comment by flaurida** [comment]
No worries - I really appreciate all you've done, and if I can help with some stuff please let me know. Will keep updating the library as well :) Thanks again and have a great weekend 🎉

**Comment by flaurida** [comment]
Quick question - when do you think will be possible to do page numbers, even if it is just `Page 1` not `Page 1 of 4`? Thanks again so much, this is looking awesome 🔥 💯

**Comment by diegomura** [comment]
Yes. It would. [Here](https://github.com/diegomura/react-pdf/pull/166) I shared with you the API I would like to see, but not sure if it's possible. Would you like to tackle this?

**Comment by crubier** [comment]
Hi, thanks for the good work, however this bug (which you are talking about on top of this page) is totally blocking us !

We want to display some kind of tables using flexbox, but we are seeing wildly incorrect results, it's so bad it's even fun !

# Example

So here is a simple example. We use these styles:

```javascript
export default StyleSheet.create({
  page: { flexDirection: "column", padding: 25 },
  table: {
    fontSize: 10,
    width: 550,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignContent: "stretch",
    flexWrap: "nowrap",
    alignItems: "stretch"
  },
  row: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignContent: "stretch",
    flexWrap: "nowrap",
    alignItems: "stretch",
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: 35
  },
  cell: {
    borderColor: "#cc0000",
    borderStyle: "solid",
    borderWidth: 2,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "auto",
    alignSelf: "stretch"
  },
  header: {
    backgroundColor: "#eee"
  },
  headerText: {
    fontSize: 11,
    fontWeight: 1200,
    color: "#1a245c",
    margin: 8
  },
  tableText: {
    margin: 10,
    fontSize: 10,
    color: neutralDark
  }
});
```

## Case 1 (empty table)

Now here is an example of an empty table:

```javascript
<Page style={styles.page} size="A4" wrap>
    <View style={styles.table}>
          <View style={[styles.row, styles.header]}>
              <Text style={[styles.headerText, styles.cell]}>Column 1 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 2 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 3 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 4 Header</Text>
          </View>
    </View>
</Page>
```

The result is the following:

<img width="771" alt="screen shot 2018-03-12 at 18 02 47" src="https://user-images.githubusercontent.com/2954572/37298053-9c6dcf38-261f-11e8-9680-dcc392f4f575.png">


## Case 2 (1 row in table)

Now here is an example of an empty table:

```javascript
<Page style={styles.page} size="A4" wrap>
    <View style={styles.table}>
          <View style={[styles.row, styles.header]}>
              <Text style={[styles.headerText, styles.cell]}>Column 1 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 2 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 3 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 4 Header</Text>
          </View>
          <View style={[styles.row]}>
            <Text style={[styles.cell]}>Column 1 Row 1</Text>
            <Text style={[styles.cell]}>Column 2 Row 1</Text>
            <Text style={[styles.cell]}>Column 3 Row 1</Text>
            <Text style={[styles.cell]}>Column 4 Row 1</Text>
          </View>
    </View>
</Page>
```

The result is the following:

<img width="765" alt="screen shot 2018-03-12 at 18 08 23" src="https://user-images.githubusercontent.com/2954572/37298364-6285f5f6-2620-11e8-8e72-025d91d7a623.png">

## Case 3 (2 rows in table)

Now here is an example of an empty table:

```javascript
<Page style={styles.page} size="A4" wrap>
    <View style={styles.table}>
          <View style={[styles.row, styles.header]}>
              <Text style={[styles.headerText, styles.cell]}>Column 1 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 2 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 3 Header</Text>
              <Text style={[styles.headerText, styles.cell]}>Column 4 Header</Text>
          </View>
          <View style={[styles.row]}>
            <Text style={[styles.cell]}>Column 1 Row 1</Text>
            <Text style={[styles.cell]}>Column 2 Row 1</Text>
            <Text style={[styles.cell]}>Column 3 Row 1</Text>
            <Text style={[styles.cell]}>Column 4 Row 1</Text>
          </View>
          <View style={[styles.row]}>
            <Text style={[styles.cell]}>Column 1 Row 2</Text>
            <Text style={[styles.cell]}>Column 2 Row 2</Text>
            <Text style={[styles.cell]}>Column 3 Row 2</Text>
            <Text style={[styles.cell]}>Column 4 Row 2</Text>
          </View>
    </View>
</Page>
```

Result:

<img width="755" alt="screen shot 2018-03-12 at 18 07 37" src="https://user-images.githubusercontent.com/2954572/37298345-51052702-2620-11e8-9137-489cce229f6d.png">

## Other cases

You get the idea, react PDF displays as many columns as there are rows, or something like that... Note how the border of the "next column" are displayed even when the text is not.

**Comment by diegomura** [comment]
Thanks for reporting it and for the extensive research @crubier ! 
I was looking at your snippets and you are right, this  error seems to be with the `wrap` prop. You can see how it shows up when that prop is gone in [here](localhost:8080/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a06180076a0736402e1918c006628007801100965581449e1f8022508802b805b308a00d076a004df64b05df802600ac3002fb6d630a35004629f8b366c87828592402f3e18004600063b0f180077497d28027e0b0b30fb36230876446a78251164511d14e13129193905186510354d0288802b556849217800616f6430281cb1005a686a0a285a8f6a44492e3076aeceee8ae82a28600211cf3100750a6a7625301048adf655983189b000493a750825059265c57b5b7b0a7db742b48cac9ebce3dc896932164f2301295e91638349a2d699d0bab74e30190bd4188154607d31d4e93586cd6e504583dc21e7fa6db6bb7da1cb1e349a5d90d77c61256c4b59e400e2e0fe32422ff420518c006b2e4b28a790010b5020921b8c000cc1627b129188443bc224e10051f4c80a3b5109aa50018980c01099a42c70d56a75383c2dcaa314b66bb514758c4e2e6117fc396f6097ac47cc17f082fef164ba54a6a2a8a0206a59cb0c84410919f715a2bec44030ead51e273518002ae2bdd1fa3d41a2a86e23211e6c679b1332e800a9e4e6ee127797c0160c870a5e2ebad9013021cc82663348a54e5c521a82d433000582cc063ba9065c633f0001ce9b62385cc866e895b8555c51d7a0e0b73db5d4ee054213aab9600e486f353e9ecc6b0012800dccc66280902c0fa080c0060303d0f60003ce22811a2cc001f214504000adc320702e0283a08c02028040a42703c358703f8c83a08a00082f3a28484446c141001aa48c8244985e0385e1a82907b8a0d61d1f4431cc6b1ec7618c000da5c411e0ae8526900d8ea002ebf1852095061eb01719c561dc429140692476a4e2a85c0217a868603043000012340ba50400f41a409824311a689e46e13a4117a41930119265995505930198365d93aa39ce6a9f47a92d879da5e03e445fa4b686720c6699e666872b8559850514b62e6b97151e09579497c9295f901565c14e5f39e5f6539454c50c439c2644c57b59d7158e5a13c0098e6c1c03c15d121bfbfe00128d0b20a1e200062a4150188eaf4081c024d4000).

`wrap` is a really an unstable feature right now, and only works for just vertical layouts, such as the one in the `page-wrap` example. I'm in the middle of changing the text-layouting algorithm, which is a first step of having a more advanced wrapping. However, there is no precise solution I can provide right now other than not using the wrap feature

**Comment by rclai** [comment]
Yeah, I've been noticing that there are a bunch of pages being appended at the end and my layout has a bunch of columns with rows with columns and so forth.

**Comment by diegomura** [comment]
I've been working on improving the current wapping algorithm, which is quite poor and as you said here you were having problems with. Also this involves changes and improvements in the way flexbox work. Just wanted to give a heads up. I hope to be able to release this soon as a beta version, so you can try it. Spoiler on how its currently working (just with very ugly Views for the moment, but the concept is the same for other elements, such as Texts):

<img width="640" alt="screen shot 2018-04-05 at 11 25 38 pm" src="https://user-images.githubusercontent.com/5600341/38401015-9d2f443e-3929-11e8-88c9-bd19c457aac5.png">

As you can see, now every element that does not fit the page, get's splited and resumed on the next page. Any inputs of feedback about what you see so far? It would be much appreciated!

@flaurida @crubier @rclai

**Comment by diegomura** [comment]
Another cool feature about this: if a wrapped element suddenly gets alone in his container (imagine the blue box being a bit shorter and ending before the page break), with the correct flexbox properties, it can dynamically adjust, enabling very complex layouts:

<img width="616" alt="screen shot 2018-04-05 at 11 38 49 pm" src="https://user-images.githubusercontent.com/5600341/38401181-b37bb406-392a-11e8-85e5-4b571ba9d4a6.png">

The "two" yellow boxes aren't two Views. It's the same one that adjusts based on the page (or pages) that he is being rendered into

**Comment by rclai** [comment]
That is great progress.

Will you be supporting the CSS `page-break-after/before/inside` properties? I feel like being able to achieve those functionalities will get page wrapping in good standing.

**Comment by diegomura** [comment]
I didn’t though about that. That’s actually a very good idea. It would be great for a second iteration. And you are more than welcome to contribute!. I don’t want to be that ambitious on this one because it’s already a very complex issue to solve. Thanks!!

**Comment by pedroteixeira** [comment]
Looks impressive!

**Comment by diegomura** [comment]
Thanks for your feedbacks!
@crubier I get what you say. To solve that I thought about being able to pass a prop to an element that disables wrapping for that element. If that element happens to be at the end of a page, it's going to be rendered completely on the next page. If not present, I think it would be ok to expect the text to break if it's at the end of a page. Otherwise you will have that text outside the page boundaries, which shouldn't be allowed. right?

**Comment by VrajSolanki** [comment]
@diegomura Amazing way the library has matured! kudos
I have been using it for the similar case with pages having dynamic breaks and columns in rows which makes things break.
I saw you actively working on the textkit branch, right?
just wanted to know if its stable to use?

**Comment by diegomura** [comment]
Hi @VrajSolanki . Thanks!
Yes. I've been working extensively there lately, and the results so far have been quite good for the use case I need to cover. But it's experimental yet. If you want, you can give this version a shot by installing `0.7.7-1` version of react-pdf packages. Just bare in mind that execution time is a bit slower now (much things going on: page wrapping, line-breaking, hyphenation, inline styling, among others). But I plan to do a performance test eventually and see where I can improve it.
If you do test it, I would really appreciate you sharing your experiences!

**Comment by diegomura** [comment]
Thanks for the report. Can you upload the snippet that is throwing that error?

**Comment by VrajSolanki** [comment]
@diegomura yes sharing the code snippet 

`export const createPdf = async (template, data, response, fileName) => {
	const started = new Date();
	try {
		let reactTemplate;
		try {
			reactTemplate = getBaseComponent(PDFCOMPONENTS, template);
		} catch (e) {
			logger(LOGLEVELS.WARN, `Template ${template} does not exist`);
			response.status(404).end();
			return;
		}
			response.set('content-type', "application/pdf");
			const readStream = await renderReact(reactTemplate, data);
			readStream.pipe(response);
			// When the stream end the response is closed as well
		readStream.on('end', () => {
			logger(LOGLEVELS.INFO, `Rendered template ${template} in ${new Date() - started}ms`);
		});
		
	} catch (e) {
		logger(LOGLEVELS.ERROR, `Error occurred while rendering: "${e}"`);
		response.status(500).end();
	}
};`

**Comment by VrajSolanki** [comment]
@diegomura sure but seems difficult to add the entire block.

```
export const createPdf = async (template, data, response, fileName) => {
	const started = new Date();
	try {
		let reactTemplate;
		try {
			reactTemplate = getBaseComponent(PDFCOMPONENTS, template);
		} catch (e) {
			logger(LOGLEVELS.WARN, `Template ${template} does not exist`);
			response.status(404).end();
			return;
		}
			response.set('content-type', "application/pdf");
			const readStream = await renderReact(reactTemplate, data);
			readStream.pipe(response);
			// When the stream end the response is closed as well
		readStream.on('end', () => {
			logger(LOGLEVELS.INFO, `Rendered template ${template} in ${new Date() - started}ms`);
		});
		
	} catch (e) {
		logger(LOGLEVELS.ERROR, `Error occurred while rendering: "${e}"`);
		response.status(500).end();
	}
};
```

**Comment by VrajSolanki** [comment]
I am using npm. yes there can be issue with this I can check that if with yarn.
Fair enough will upgrade to 7-2.

**Comment by diegomura** [comment]
Thanks! This is definitely an issue (hate when this happens).  Please tell me if it works with yarn

**Comment by VrajSolanki** [comment]
Yup atleast got it built with yarn and currently on version `0.7.7-2`
@diegomura lets do one thing add yarn in the build setup until the npm stuff with pdfkit is figured out, it would be helpful.
Seems interesting to work on the layouts now!!
Also currently I am able to see the rows, columns in the flexbox will work drill more on the layout and page-break and keep you posted.

**Comment by diegomura** [comment]
It's great you could make it work. And glad to hear it's you find the new layout and page wrapping feature interesting. Probably it has things to improve yet, but test it and report anything you see.
The yarn thing is definitely something I should fix soon. I can't expect to all the users to use yarn. It's a shame npm does not support this

**Comment by diegomura** [comment]
This is fixed on the `1.0.0` branch, which is the ongoing effort in releasing a more stable version, with tons of new features. However, I didn't have enough time to wrap it and deploy a release candidate yet. You can temporarily try that version, or as you said, flat the document design 😄

**Comment by tim-soft** [comment]
Some more flex weirdness, you can copy/paste the code below directly into the repl to see what I'm talking about.

The page layout works as expected with only _one_ `<TwoColumnLayout />`. With every _additional_ `<TwoColumnLayout />`, two blank pages get added to the document, plus the last word in each `<Text />` gets chopped.

![capture](https://user-images.githubusercontent.com/10257939/41007967-9f60c214-68e5-11e8-801a-dba9faf6e933.PNG)
![capture](https://user-images.githubusercontent.com/10257939/41007985-b85a09e2-68e5-11e8-9761-8fdba34c91e6.PNG)

 
```js
const TwoColumnLayout = () => (
  <View style={{ flexDirection: 'row', justifyContent: 'space-around' }} >
    <View style={{ flexDirection: 'column' }} >
      <Text>Left Column</Text>
    </View>
    
    <View style={{ flexDirection: 'column' }} >
      <Text>Right Column</Text>
    </View>
  </View>
);

const doc = (
  <Document>
    <Page style={{ padding: 30 }} wrap>
      <TwoColumnLayout />
      <TwoColumnLayout />
      <TwoColumnLayout />
      <TwoColumnLayout />
      <TwoColumnLayout />
    </Page>
  </Document>
);

ReactPDF.render(doc);
```

**Comment by diegomura** [comment]
New `v1.0.0-alpha.7` implements the new wrapping algorithm. REPL is already running that version.
I'm closing this, and if anything else pops up, submit a new issue with proper example

**Comment by YohanObadia** [comment]
First of all thank you very much for that library. I am trying to generate a PDF on-the-fly with a varying number of same-size images (QR Codes). I managed to add the images to the PDF but only figured out how to either align all of them on the same row or same column. I would like to have some kind of a wrapping that distribute Images in a row and when their is no more space left to go to the row bellow. It seems like a trivial problem to me but I know nothing about flexboxes and would appreciate some directions :)

The layout I would expect is the following with O representing the Images I have :
         _____page 1_____
row0 |  O  |  O  |  O  |  O  |  
row1 |  O  |  O  |  O  |  O  |
row2 |  O  |  O  |  O  |  O  |
row3 |  O  |  O  |  O  |  O  |
         _____page 2_____
row0 |  O  |  O  |  O  |  O  |  
row1 |  O  |  O  |  O  |  O  |
row2 |  O  |  O  |  O  |  O  |
row3 |  O  |  O  |  O  |  O  |

Thank you in advance !

**Comment by DewangS** [comment]
@crubier First of all thanks for the samples, it really helped me in understanding various styles. My requirement is a tabular report i.e. I need below on my report 

Header on each page with the company logo on the top left and on the same line REPORT TITLE on the RIGHT

COLUMN HEADERS on each page (under the above LOGO with REPORT TITLE)

A horizontal line under the column headers

report data rows under column headers .. around 20 rows per page. Report data is dynamic and fetched via API...

See below ..... as you can see data shifts depending upon the size of the data...

Last Name              First Name          Registration No              License Number.          Address.                                 Phone
_______________________________________________________________________________________________________________________________
ABCDEFGHIJK            ERMMDLKFLL           ERM92388T                   9088837747            450, Henry Street,                8947736

Any idea on how to align these values??

While using your example I could manage to get the REPORT HEADER with LOGO and columns, I can't get the report data properly aligned i.e. the data doesn't properly aligned under each column headers.

**Comment by crubier** [comment]
Since you tagged me here 3 years later @DewangS , I can update on my status on this: 

We realized 2 years ago that generating PDF report with react was just much easier if you just render normal HTML with react-dom, and then use [react-to-print](https://www.npmjs.com/package/react-to-print) to print to PDF on the browser. For rendering PDFs in the server, same thing, using puppeteer or playwright. Just make some html, and print to pdf. Faster that react-pdf, and gives access to all the dom capabilities (including canvas, 3d stuff and all), with no bugs. 

react-pdf is amazing and has its use cases, but most people probably don't need it. Modern browsers go a long way with pdf now.

**Comment by SreenivasForLeafcraft** [comment]
Hey @diegomura FTF! The project of React-Pdf is a great one. Can i know if we have any update on the table component ?

**Comment by Owais-Ahmed7** [comment]
since everyone is talking about how to make tables and flex-wrap, I also came up with a solution by myself of how to create tables in react pdf renderer not sure if it's related to the topic but I hope it will help someone
![sytles](https://user-images.githubusercontent.com/76119305/204055173-6d646014-bf65-48a6-adf6-ce0344cf5085.png)

so the first image of table rendering I am making a header of the image using (row, col(4,5)) from the stylesheet so using col (s) I can keep the width of boxes as I wanted them, next coming to the map function on every iteration i am creating rendering new row for every medicine so in that it looks like a table and fulfills my requirements. Hope it Helps someone

![table](https://user-images.githubusercontent.com/76119305/204055176-5b30f588-0520-48e5-9e38-c1016110878f.png)
