### ISSUE TITLE
Link component is not rendered, neither in the repl nor in nodejs

### ISSUE THREAD

**Issue by philiiiiiipp** [diegomura/react-pdf#2060]
**Describe the bug**
I seem to be unable to use a Link component

**To Reproduce**

1. Go to https://react-pdf.org/repl
2. Add a Link e.g. `<Link src="https://www.google.com">test 123123</Link>`
3. Nothing happens

<img width="1248" alt="Screenshot 2022-10-20 at 17 03 39" src="https://user-images.githubusercontent.com/1035746/196986539-7d5077fd-3cf2-478c-ad0e-f6757c163dce.png">

Another, possibly related issue, if I nest a `Link` element within a `Text` element when running it in nodejs I get 
```
Invalid 'Some name' string child outside <Text> component
``` 

Neither in the repl nor in nodejs a link is rendered for me.

**Expected behavior**
A link component should be rendered.

**Desktop (please complete the following information):**
 - OS: OSX (12.6)
 - Browser - chrome, but this also happens when compiling it in nodejs v14.18.2
 - React-pdf version 3.0.0

**Comment by moein-karimi** [comment]
I have the same issue after update react-pdf to version 3.
If use `Link` element within a `Text` it not render and use it out of `Text` element, show link with problem (yellow box in below image get link).

```
<Text style={styles.text}>
                En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha
                <Link src="https://www.google.com">google</Link>
                mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga
                antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que
                carnero, salpicón las más noches, duelos y quebrantos los sábados,
                lentejas los viernes, algún palomino de añadidura los domingos,
                consumían las tres partes de su hacienda. El resto della concluían sayo
                de velarte, calzas de velludo para las fiestas con sus pantuflos de lo
                mismo, los días de entre semana se honraba con su vellori de lo más
                fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina
                que no llegaba a los veinte, y un mozo de campo y plaza, que así
                ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro
                hidalgo con los cincuenta años, era de complexión recia, seco de carnes,
                enjuto de rostro; gran madrugador y amigo de la caza. Quieren decir que
                tenía el sobrenombre de Quijada o Quesada (que en esto hay alguna
                diferencia en los autores que deste caso escriben), aunque por
                conjeturas verosímiles se deja entender que se llama Quijana; pero esto
                importa poco a nuestro cuento; basta que en la narración dél no se salga
                un punto de la verdad            
</Text>
<Link src="https://www.google.com">google</Link>
```

![2022-10-24_07-57-34](https://user-images.githubusercontent.com/46858581/197450167-7874d333-82fa-4f50-9ca4-0b6051a650aa.png)



- "@react-pdf/renderer": "^3.0.0"
- "react": "^17.0.2"
- "react-dom": "^17.0.2"

**Comment by bostadskalkylen** [comment]
I have the exact same issue. Hoping there will bea patch or workaround made available.

**Comment by akashdevgan95** [comment]
The link is also missing the style prop.

**Comment by leogilmour** [comment]
😭 this is also not working for me

**Comment by leogilmour** [comment]
I have tried wrapping in `<Text>`, `<View>`, ensuring it has a style prop... no luck!

**Comment by jeetiss** [comment]
I find the problem going to fix it soon

You can add a link to a text as a workaround. [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5400c923001ac6000b004e18019b6004432a14000e10017007a3d7c9141908011803a508cf40132418f884608e4f3d0a7b028016936dc51521611800482a00150c143600014f6f3f008f165b0c05392a3d2898e0e12cf1293cea3d5e0160acba0666567602006e323200250c2f282e1a00310b053034b93c2a4454742c3d6206b2200000)

**Comment by Kpa6i** [comment]
@jeetiss, thanks for the fix. 
So how all should look? Like this?
```
<Link src="some_link_here"><Text>some text</Text></Link>
```

**Comment by jeetiss** [comment]
yep, or just `<Link href="some_link_here">some text</Link>`
