### ISSUE TITLE
React-pdf hook (usepdf) update not working

### ISSUE THREAD

**Issue by CoetzeeLeague** [diegomura/react-pdf#2066]
I have a pdf that should download when user clicks on a button. The content for the pdf gets set:
```
const [instance, updateInstance] = usePDF({
    document: (
      <PDFDocument projectsData={projectsData} projectId={projectId} />
    ),
  });
```
When projectsData is updated I call updateInstance. But the content of the PDF still reflects the original projectsData, and not the updated.

I have tried calling updateInstance in a useeffect when projectsData is updated as well.

**Comment by trevortumas** [comment]
I am facing this same issue.

**Comment by gfazioli** [comment]
Same for me. I got
<img width="312" alt="image" src="https://user-images.githubusercontent.com/432181/201518267-d0ad9ad5-bdf3-444f-a63e-d492f2849ae1.png">

**Comment by suzan-rana** [comment]
hello, did you find any solution for this, I am facing similar problem

**Comment by shamar-morrison** [comment]
Also facing a similar problem

**Comment by mcmxc** [comment]
I believe `updateInstance` should be called in `useEffect` with your props in a dependency array

**Comment by CoetzeeLeague** [comment]
The useEffect approach did not work. The only way I got around the issue was to create/remove the download button based on a state change. If it gets recreated, it gets retendered. 

`PDFGenerate ? (
                    <PDFDownloadLink
                      document={...}
                      fileName={...}
                    >
                      {({ blob, url, loading, error }) => (
                        <Button>
                          <div>Download Schedule</div>
                        </Button>
                      )}
                    </PDFDownloadLink>)
                    : ()`

**Comment by Blankeos** [comment]
I noticed that `usePDF` works for **case 1**, but not for **case 2**.
The difference is obvious here, case 1 uses a JSX.Element constant, while case 2 is a Functional Component that returns JSX.Element. Although the end-values are the same, I think react has a different way to transpiling them.

Knowing that this library is for generating pdf files, the usual case is passing dynamic props to MyDoc so it can have dynamic content. I don't see how I can do that with case 1.

### Case 1
```jsx
import { usePDF, Document, Page } from '@react-pdf/renderer';

const MyDoc = (
  <Document>
    <Page>
      // My document data
    </Page>
  </Document>
);

const App = () => {
  const [instance, updateInstance] = usePDF({ document: MyDoc });

  if (instance.loading) return <div>Loading ...</div>;

  if (instance.error) return <div>Something went wrong: {error}</div>;

  return (
    <a href={instance.url} download="test.pdf">
      Download
    </a>
  );
}
```

### Case 2
```jsx
import { usePDF, Document, Page } from '@react-pdf/renderer';

const MyDoc = () => (
  <Document>
    <Page>
      // My document data
    </Page>
  </Document>
);

const App = () => {
  const [instance, updateInstance] = usePDF({ document: <MyDoc /> });

  if (instance.loading) return <div>Loading ...</div>;

  if (instance.error) return <div>Something went wrong: {error}</div>;

  return (
    <a href={instance.url} download="test.pdf">
      Download
    </a>
  );
}
```
