### ISSUE TITLE
React PDF is not working with fresh React installation using Vite

### ISSUE THREAD

**Issue by sulemankhann** [diegomura/react-pdf#2067]
I have a fresh react application which I installed using vite library. In fresh react application I installed react-pdf and put the basic getting started code from react-pdf site but I am getting errors:
`Cannot read properties of undefined (reading 'call')`
`The above error occurred in the <PDFViewer2> component:at PDFViewer2`

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. install react using vite
2. install react-pdf
3. put getting started  react-pdf code to view the pdf file
4. check console for the errors

The expected behavior should be shown the pdf file

Attached are screenshots of the code and the error
<img width="572" alt="Screen Shot 2022-11-02 at 8 31 19 AM" src="https://user-images.githubusercontent.com/29842193/199389218-db6e97fc-309d-4c41-b9ee-38ebdc26b7f2.png">
<img width="728" alt="Screen Shot 2022-11-02 at 8 25 01 AM" src="https://user-images.githubusercontent.com/29842193/199389256-8f55139f-92b1-42fc-a4b8-c2e555d9bd80.png">

 - OS: MacOS
 - Browser: chrome, safari
 - React-pdf version v3.0.0

**Comment by simonurmi** [comment]
Try this https://github.com/diegomura/react-pdf/pull/1879#issuecomment-1300566495

**Comment by gustavetsopmo** [comment]
Hello, I am facing the same issue. Any solution please.

**Comment by raibtoffoletto** [comment]
I can confirm that manually adding the events package ( `yarn add events` ) solves this issue!

**Comment by SteveTro** [comment]
I have the same problem, manually adding the events package did not solve it for me.

**Comment by SalamanderXing** [comment]
Same issue here

**Comment by JK369x** [comment]
Same issue, How to solve a problem

**Comment by jeetiss** [comment]
@JK369x update to the latest version it should work with `vite` from the box

**Comment by JK369x** [comment]
> @JK369x update to the latest version it should work with `vite` from the box
ty, work sir
