### ISSUE TITLE
<Image/> src invalid image extension

### ISSUE THREAD

**Issue by MatheusHCP** [diegomura/react-pdf#2075]
**Describe the bug**
Hello, I'm having a problem with the use of images in the library, in the <image/> when importing any image by file it is causing "not valid image extension" error, only base64 is working what can it be? Formats used .png, .jpg

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. example <Image src="anuncio.jpg"/>

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/65426315/200304389-a99d070a-5bb5-4382-ace5-516537013f5e.png)
![image](https://user-images.githubusercontent.com/65426315/200304533-1b9a3e53-9543-4276-9c8e-4d947460a974.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Microsoft Edge]
 - React-pdf version [3.0.0]

**Comment by mbhadra23** [comment]
Hi @MatheusHCP  - What was the resolution? I am facing the same issue.

<Image src={{ uri: { dataurl}, method: "GET", headers: { "Cache-Control": "no-cache" }, body: "" }} style={styles.Logo} />
