### ISSUE TITLE
Image dont appear when i render it to string

### ISSUE THREAD

**Issue by cris-ms** [diegomura/react-pdf#2095]
**Describe the bug**
When a render a pdf with image on my api using renderToString and send this string to my react and download this pdf. The image dont appear in the pdf. But when i render this pdf using the method renderToFile and save on server side the ima is showing.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create a pdf with image
2. render this pdf to string and send to a front end encoded a base64
3. decode this pdf and download it

**Expected behavior**
I expect the image appear when i download it on front end

**Desktop (please complete the following information):**
 - OS: [Ubuntu(ZorinOS)]
 - Browser [chrome, nodev16(nestjs)]
 - React-pdf version [e.g. v^3.0.1]

**Comment by cris-ms** [comment]
I made a workaround. I renderToFile read this file and transform it in a base64 then i delete the file

**Comment by mengzhou44** [comment]
I have encountered the same issue.

**Comment by bryantee** [comment]
I have also been able to reproduce this. My work around was similar to @cris-ms :

```tsx
const stream = await renderToStream(React.createElement(COMPONENT, ARGS) );

const buff = [];

for await (let chunk of stream) {
  buff.push(chunk);
}

const str = Buffer.concat(buff);

// do whatever with string buffer
fs.writeFileSync(filePath, str, { encoding: "base64" });
```
