### ISSUE TITLE
PDFViewer Iphone

### ISSUE THREAD

**Issue by Dmitry-savenkov** [diegomura/react-pdf#2108]
Pages after the first one are not displayed in the PDFViewer component when viewing a document from an iPhone

![IMAGE 2022-12-16 12:04:25](https://user-images.githubusercontent.com/73306821/208062638-08ac7449-5cc2-4720-b516-55bbb52dab12.jpg)

Works well on the web from a PC
<img width="639" alt="Снимок экрана 2022-12-16 в 11 53 08" src="https://user-images.githubusercontent.com/73306821/208060655-f41be62f-135d-45d9-bcd3-9b8885ad3a0e.png">

 - Browser [chrome, safari]
 - React-pdf version [v3.0.0/v3.0.1]

**Comment by devon2018** [comment]
I'm having the same issues, same react-pdf versions as well.

**Comment by jeetiss** [comment]
duplicate #714
