### ISSUE TITLE
Error on registering font

### ISSUE THREAD

**Issue by PatrykRudzinski** [diegomura/react-pdf#2109]
**Describe the bug**
I receive following error on registering ttf font. It doesn't matter if I use local font or CDN as a source.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tables')
    at $f08dd41ef10b694c$export$2e2bcd8739ae039.findSubtable (CmapProcessor.js:47:1)
    at new $f08dd41ef10b694c$export$2e2bcd8739ae039 (CmapProcessor.js:10:1)
    at get _cmapProcessor (TTFFont.js:259:1)
    at descriptor.get (decorators.js:10:1)
    at $4c1709dee528ea76$export$2e2bcd8739ae039.hasGlyphForCodePoint (TTFFont.js:278:1)
    at index.es.js:1890:1
    at Array.reduce (<anonymous>)
    at buildSubsetForFont (index.es.js:1889:1)
    at index.es.js:1900:1
    at Array.map (<anonymous>)
```

**To Reproduce**
I've been trying register it in different ways, but all cause the same problem:

```
import font from 'assets/fonts/Roboto.ttf';
Font.register({ family: 'Roboto', src: font });
``` 
or
```
Font.register({ family: 'Roboto', src: '/fonts/Roboto.tff' });
```
or
```
Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/fonts/roboto/Roboto-Regular.ttf' });

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Browser: Chrome
 - React-pdf version: 3.0.1
 - React version : 18.0.0

**Comment by jeetiss** [comment]
Could you provide reproduction? seems like your font is working in all playgrounds that I have

- [default react pfd repl](https://react-pdf.org/repl?code=1887b07602e07404e0a6073025819c27180280de002019808602d9200d809e0172e039004a2004620422d00d2e28c0318db40058408001c51500f493780133000ac5145e644005759f8ca1782a4314984161001e92c92262927142e861242960179c490018a004e001c50011925f1c0206c61995841251858d80169e911d47460a045f16970017c012801b800a10b79c0d17001454c4944c8e17001797131731a00f99b0b7170007800444179d588e120dabbbb7a00150811ea5090dc1a0088010401d99770411d4621ec91c05674c16451790944e0b6d028ea1bb0f099097801ac1023d54e018440d460040062380009941a0acb65b2e349a4c7a0035241c000eedc081dce00f6c08520c012391a8745894538b85121164b224180103410478a130d85c2002a7053040dac4b62e1d01cdc004410066000b2f3d9101ea48d91ca67337a32ce6000841007c2080461015600844055b84d6015841005c208041104d40b8562fd71b3552c55cae192444a3c6135842291a8dbbdd1e648a5526974867425dcc9eadafa70220a420e2fe60b4531c974a2576d76db551aed6eb0d26b37c72d269b72783dd2963b911d60d4a66732654a06431198d0a05629245e10299f580b051ac830981e9546a755c248da2da00)

- [experimental one](https://react-pdf-experiments.vercel.app/?version=3.0.1&cp_code=GIewdgLgdATgpgcwJYGcJxgCgN4AIBmAhgLZIA2AngFy4DkASiAEYgQi0A0uKMAxjbQAWECAAcUVAPSTeAEzAArFFF5kQAV1n4yheCpDFJhBYQAekskiYpJxQuhhJClgF5xJABigBOABxQARkl8cAgbGGZWEElGFjYAWnpEdR0YKBF8WlwAXwBKAG4AKGLecDRcAFFTElEyOFwAXlxMXMaAPmbC3FwAHgAREF51YjhINq7u3oAFQgR6lCQ3BoAiAEEAdmXcEEdRiHskcBWdMFkUXkJROC20CjqG7DwmQl4AawQI9VOAYRA1GAEAGI4AAmUGgrLZbLjSaTHoANSQcAA7twIHc4A9sCFIMASORqHRYlFOLhRIRZLIkGAEDQQR4oTDYXCACpwUwQNrEti4dAc3ABEEAZgALLz2RAepI2RymczejLOYACEEAfCCARhAVYAhEBVuE1gFYQQBcIIBBEE1AuFYv1xs1UsVcrhkkRKPGE1hCKRqNu90eZIpVJpdIZ0JdzJ6tr6cCIKQg4v5gtFMcl0oldtdttVGu1usNJrN8ctJptyeD3SljuRHWDUpmcyZUoGQxGY0KBWK8FOGEwPSqNTquEkbRbQA)

**Comment by Krzyku** [comment]
I faced the same issue. Here is minimal reproduction [LINK](https://github.com/Krzyku/react-pdf-font-register/tree/main).
Working on it, I faced an interesting fact: I have this issue almost always when caching is disabled in dev tools and rarely with caching enabled.
It's the same for react-pdf v1 and v3 (check the branch on my repo).

**Comment by jeetiss** [comment]
it works on my computer, do you use windows?

<img width="1508" alt="Снимок экрана 2023-01-30 в 18 23 46" src="https://user-images.githubusercontent.com/6726016/215518783-4f3e622a-2870-427d-8787-2eb538f088b3.png">

**Comment by Krzyku** [comment]
No, OSX. Have you opened dev tools with the "disable cache" option?

**Comment by jeetiss** [comment]
yes, it just works
<img width="1427" alt="Снимок экрана 2023-01-31 в 14 27 35" src="https://user-images.githubusercontent.com/6726016/215747891-72312870-b369-4f92-b9fe-b2caeb867cf2.png">

**Comment by Krzyku** [comment]
Holy cow! In my case, it didn't work because of the Mokku plugin :o @PatrykRudzinski what about your problem?

**Comment by cisc-out** [comment]
> Holy cow! In my case, it didn't work because of the Mokku Chrome plugin :o @PatrykRudzinski what about your problem?

I was struggling with the same error, I've tried everything and nothing was working. Turns out it was because of the Mokku plugin...
Thanks @Krzyku !!

**Comment by garyfagan** [comment]
Yea same here Mokku stopped it from working.
