### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by rexkenley** [diegomura/react-pdf#211]
OS: windows 10
React-pdf version: 0.7.5
Description:  I get the error below when I do 

"yarn add @react-pdf/core"

error An unexpected error occurred: "C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout: Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c npm run build:node
Directory: C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout
Output:
> yoga-layout@1.9.3 build:node C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout
> npm run copy-sources && autogypi && node-gyp configure build

> yoga-layout@1.9.3 copy-sources C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

'!' is not recognized as an internal or external command,
operable program or batch file.
'rsync' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 copy-sources: `! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.9.3 copy-sources script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\\Users\\kenleyr\\AppData\\Roaming\
pm-cache\\_logs\\2018-03-21T20_18_11_578Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by diegomura** [comment]
May be related to #185 
I don't have a Windows machine to test. I've been trying to find the time to setup a windows VM to test the lib, but I couldn't yet. Some help in here would be very welcomed. Are you open to contribute somehow with the fixes needed for Windows?

**Comment by rexkenley** [comment]
Sure.

Send me the instructions and I will see what I can do

**Comment by diegomura** [comment]
It seems to be a [`yoga`](https://github.com/facebook/yoga) issue. Maybe the first test can be creating a new project and installing yoga in there to see if it installs correctly in windows.

**Comment by rexkenley** [comment]
That was my first thought and I can confirm that you are correct that yoga is the main culprit.

I tried both yarn and npm when trying to install yoga only. I was able to get past the rsync error. 
https://itefix.net/cwrsync

But I can't figure out the rest.

> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

'!' is not recognized as an internal or external command,
operable program or batch file.
**rsync: change_dir \"/cygdrive/c/Code/kenleyr/Projects/JavaScript/DaveyJS3/node_modules/yoga-layout//../yoga\" failed: No such file or directory (2)**
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
npm ERR! code ELIFECYCLE
npm ERR! errno 23
npm ERR! yoga-layout@1.9.3 copy-sources: `! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)`
npm ERR! Exit status 23

**Comment by rexkenley** [comment]
@diegomura

I tried running the install under git bash. No luck there either. 

I tried installing yoga first in git bash, got a little bit further although I had to skip the copy-sources, but still ended up with a TON of build errors.

**Comment by vadistic** [comment]
@rexkenley 

Temp workaround is to run yarn in bash under WSL (Windows Subsystem for Linux).

1) Install Ubuntu WSL from MS Store
2) Install node (your node modules sync, you don't even need to download/install them again)
`curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash `
`sudo apt-get install -y nodejs`
3) `bash` & `yarn install` 👌 

There's even a config option for VSCode (if you use it) to use as default WSL node version
https://blogs.msdn.microsoft.com/commandline/2017/10/27/running-node-js-on-wsl-from-visual-studio-code/

**Comment by mutouzdl** [comment]
try this: https://www.npmjs.com/package/yoga-layout-windows

**Comment by diegomura** [comment]
This refers to old react-pdf build. Closing this now, and in case there still issues please open a new one related to last version

**Comment by AirborneEagle** [comment]
I am having this issue right now .
@diegomura what / where is the newer build that you are referencing?
When I run 
`npm i @react-pdf/renderer`
I am getting the same error : 
`Failed at the yoga-layout@1.9.3 install script`

I also tried the yoga-layout-windows, but to no avail. I probably did not use it properly?
any advice would be great!
Thanks all.

**Comment by tnoelcke** [comment]
I also found that it required rsync. This can be installed by running the following command:
```sh
choco install rsync
```

**Comment by tnoelcke** [comment]
I also found that the yoga layout for windows worked for me but it needed to come before react pdf in the package.json.

**Comment by atherdon** [comment]
just to let know( I actually test it on my windows machine) 
With the latest release 1.0.0 - packages installation and builds working fine.
i deleted `yoga-layout` and `react-pdf renderer` and reinstall only `react-pdf renderer`
so in my case - everything is working perfectly. Big thanks to @diegomura & @DuncanMacWeb

**Comment by AirborneEagle** [comment]
Likewise here!  I clean install of react-pdf renderer is working very nicely.  :)  🎆 🎉
