### ISSUE TITLE
Destinations: Undocumented but Fully Functional Feature

### ISSUE THREAD

**Issue by yohgen** [diegomura/react-pdf#2110]
I was fruitlessly trying to find a way to add intra-document navigation to my pdfs, but failed to spot anything useful on the topic. After finding out that `pdfkit` actually supports the so-called [`Named Destination`](https://pdfkit.org/docs/destinations.html)'s, I thought I'd give a go at adding this functionality to `react-pdf`, but after researching `react-pdf`'s code base, it turned out that there is full yet undocumented support for the `Named Destination`'s already.

If you find this post in search of `Named Destination`'s, here's how to add them. Set the prop `id` on any primitive that supports it (`<Page>`, `<View>`, `<Text>`, even `<Link>`, etc.) to a string. This is your `Named Destination`. Then set `src`/`source` on a `<Link>` you want to go __from__ to `#destination name` (notice the hash symbol (`#`) in front of the `src`, spaces in destination names work just fine, btw). In the end you should get something like this:
```JavaScript
// Notice the hash symbol!
<Link src='#Very Important Chapter'>
  Click me to get to Very Important Chapter
</Link>

// ... 

// No hash symbol, just the name of the destination
<Text id='Very Important Chapter'>
  Very Important Chapter Title
</Text>
```

Maybe I'll try to properly document this feature later, but my English isn't the best as I'm not a native speaker.

**Comment by SankarshanDudhate** [comment]
Hey, why don't you try documenting it and paste it here? We'll proofread and try to improve if there's any scope for it :)

**Comment by yohgen** [comment]
@SankarshanDudhate Thank you for encouraging me :)
I've created a PR in the `react-pdf-site` repo: diegomura/react-pdf-site#102

**Comment by yohgen** [comment]
My PR has been merged, hooray
