### ISSUE TITLE
Glitches with non-latin characters (or TTF format?)

### ISSUE THREAD

**Issue by larimaza** [diegomura/react-pdf#2112]
**Description**

I'm encountering some trouble while trying to implement PDF generation that works across browsers with both latin and cyrillic characters.
Previously, I was using Helvetica, and it worked for all cases except cyrillic characters. I have updated React-PDF to the latest version, as well as followed the recommendation in [this issue](https://github.com/diegomura/react-pdf/issues/328) to use Roboto, like below:

```
Font.register({
  family: 'Roboto',
  src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-medium-webfont.ttf'
});
```

It almost appears to work on Firefox, but it partially doesn't render (see the list items at the bottom).
Then Safari just renders this alien text - it looks the same when opening the PDF locally with Acrobat Reader or similar, after getting the error `"Cannot extract the embedded font 'WWDSWO+Roboto-Medium'. Some characters may not display or print correctly.".`

Firefox | Safari
-|-
![Screenshot 2022-12-20 at 17 40 50](https://user-images.githubusercontent.com/25252211/208712195-71658418-7570-4f2a-95fa-5d57d773c2bc.png)|![Screenshot 2022-12-20 at 17 42 09](https://user-images.githubusercontent.com/25252211/208713043-53abd761-209a-4189-a44c-0c7d410df9e5.png)

One thing I noticed while writing this issue is that even the latin character version of the same document has the same glitch when I change the font to Roboto in TTF. I'm trying to fix this with TTF format because that's what the library seems to expect, according to the aforementioned issue but also to errors that I got while trying to use other formats:

```
unhandledRejection: TypeError: Cannot read property 'version' of undefined
  at TTFSubset.encode ( ... /node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:38125:31)
  at ... /node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:37906:12
```

Any thoughts?

**Desktop**
 - OS: MacOS Ventura 13.1
 - Browser: Chrome, Firefox and Safari
 - React-pdf version: 3.0.1

**Comment by voronianski** [comment]
just a small follow up on that - we see that in [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634ad0049467e0c43cd11e35339245381550bce085b606c00220cbbb3880c80473a834008cb25abc4f8ef2786406941d3ed8663518dd6410043c8ca500a8c3383e1e3c400b75004088403023800b86a58282d87850569345a305018094486012000cfd5210c030b53b07239a49b0ad1c3c4608020a4f3120943c111f149345913d2888243d530ab2c1323a5d1e93cf6392350cae2559261f4ea354c1005820800610401708200f84100ac20b14010880ba608041104037080bb004c203ea7600384100022061ff7fac3807110376fb5d6ea3565f6d8b87e811a6244c92dfb1b479380051080006860f125b9675c31e3c8ec1580560ccdae97c9fc6cee8cae50aa54564910489d2a53066df3a0f59e2dbe84829692f0e3bb2759aa3c60010e87a2980f0008f20220411a539df343076669203ba3a6b00a722312d9f13c082da59307a6b15a3c67073b9305e5166804026c961804011036395396645f2416b28194524ab56149658f90155e764e71d56d264ef000bc780ad79499aa265ac4609030090681693fdaa269511807a0e458794006e0039a310f81835a4fd10e181037c105b0e70817b209791b0203a5a8b43aa56c40b1cc08d9d8ae460460106e85f1633a0c0f83d29a328ec5a570a2d2823d180edac31388cac7873340461e25a56c4bdaf2dcb03bde40551f67c8716154dd5cf5b0b8d22207c4788c0364e56d56998bbce48fc90a1c186d9472ac94195eb0bd4541c22842d298068b0116301473116d7889c8c18067daa4fc607909060a5cd250710b991015c841a53e4c5095e71800031659b0ce8452c00065241209e1c91aa6671df0969c4f9482262104ad6c2941cd239b07cf4ea2696a2ef794875a408f00cc6128417c077392cc73fc06a57269e23b05a0808a8ddd28413a1ca62a32fcd3cc40bc7823abaff00136abc802df273e96f2753931c7c4549cb5916daa6d374a1d6adb0767d38eb06cc601c4c4329265aeffc6c3c312ea2e9ea9c7568a8e1c08ffc8f7d3800c02b132152d20cf3239966f93011c1699b3e6cb5b5c777dc5e6042fa96b264366ac695691c3b125545691223f0955a8012faa0cb594ea3067c9697aba85510f4adaaebc726835d6dccb64a09a336d58906f625161b577c7e89c696587edb479c70663297f4e90dd1d58e0b9837b5c1981974353faaee36b50eebb3be79a69c5ef76e8d68f85a471a235522d8d038ebb35116b8f32b4a042d2c9f1c030ef4de5acfe5b63bbaedbb09bb09467d06cac400ec7cfbd1f342565a99061448db564f524475cfc9e7e219825cc071db07ec3764a0f695dc9c99127a3d5839454f1d2ae1975100a3e889c87268e2e82d6034e5d27aa22024a18000105c4b404e498064056492910cc0e9308efd5ea254e42496d047100b206000039342938c1b695e4ad5dab7750e960369e9576ddc001084d4e8b455609e210b68de95e67c15977ad871c3cdbe1f06a2279c707098095c819dd5381ed472ad2c0e60d11b51bea25690e50ac8fc6c2d427213c4c8b00bce84f69d1524bc910b037420c0ec2ef18aca39ea59214749c49f321c7dc3005f1905c4be9ed1ea4d4908ee1687e5c9b54662931108792864b0561bf3f21e5511e12bcae243ab4372bd4cc2671dcd0d5a1f0df2f58c40ee752ac1eca1b7c63d0873a95b16796d37b69a479a6aa55381e4993c41104c00e830a3e5819c354216f10da9ab568620b58f5201fe5f11472c07139826022a925188207949e22a9749ec6c40db71322758441b5672dddd0740a40338691ae1e0420661dd5e42c8ca180040594581c92a241d4723f1e6248c38cc3099d1307680401b1491e497c253ea9dd1725f40f872568ef88c7d95accc4ea5190f28b8c09ff730bd467aac7a042584528406394d075439a7c0000fcb0222041a074f7f0cc8103ae1583d1e404f492c0d983d40f26921f1d8152bc0442a77c48c42c516238e545a2605b0e6549300d38e3d51800714982d0b8a9c21c62279960f64105370563090d95c76e0019286a92c79024805bd509e0fda88554eabc44f10b065f3c750ac71a8a10d970f827d810255419678a7b8f205bd4899390ac7fdb18c07152d066056321a71cc480e15f88c544a8721c39b2da03e13c084ee0ea9b43d6b26c2ff8bd6a51ca5c41f9a167273c996da6602b3590e89529fd9a83e198ff83ab09162baca69da985e442a7ab05441c27b3abb6580af2b460a4448cad70f0f5c331371cc2ddc61b70ee4598b3547f0d28ea4310ac26c560f31608e16904060030504a297ad620620e4eea772864be29ce44be4bd4aadd0ee988210ec42a70075afbb9f539152bc8babbad464496c2b57ddbfbff61b17cf88e58bd6dcbbd40222db05443c8c92ce3a4e159e46c4fd5d51e1dd93cf9bf86bc7ab859803fe71b4b82953c2e26c0797424bdb086098000064c41804e4478325327145f8a2a24831a48827a0eea6219f062d5c438565790ac2076b0b03bc5f8ae6a11ac75b3ebb10934811e8b53a4fe51e9af04918ca5306bb0bd86b2c364018044cee4940ba2b004e606c7b89b20805ea762da3b8bbd248eab30c066f940463cb11a3522169290c65e9803c35257256630bccba95b09b5e37286fcc92b4bae38660112771e3a439a505f4ba816c0164e14f8687248b61dd4bd6da55da5572a52d68e81ccaca602e25d9a6e664ab3e904b7fe4ea72b0ef486984d070534f09cd18c390b5404160a60aaa1c3f843e920f0048472c3746ca1c42f48442f0010439541106c0a40f02da00006000482410d8c02366c9d80701906001dc5b0a856d985503b69e010070ce0502b8180d090e2645bbee1321d00609660e0100e2640c828d700501643f85e1d00ec34d8e0e28a888821094800390002569ee80400a3b03c315e2a3f30500a03c4080e48320646004a0c02d4390cfa4024ca96755640b90c83c1544a00c8c277e351000d619000332c8104408000306418eac17e063c50884321ed197201620acbe084f6230423312e21d13c7038ec83ad90760f58243c32b44f95c3ca008fe6b2398028e003c8406080a8942ebab2f8e6de13e27a4fc9e6bb907c127194600ccf7a8645f85291dc88250190361027e719000268007d6d0001a4001a8003610000038003a8800d8f20002a9287e78c013c000d0009c3c180700cb450075deba0720e593406cc57d700cd3183352c06008794c020607372d59435b8908716a928364e55b4080788949f9c00565c794127f4fbe0543d0221460949d3f2f89fd61d7c00091984806e97e1100bff7e50550b8e311884a4e3f3426bb9a044302520004c0005857c7e7d8c0395cc0151cf987f96c05dd38135d468250add51deddc3d9dc3816fc381fc4e156c11fd0e05fccfddfc6008103fd7fcdb80021608026dc402f95c03280aa5784c0137c89d7a9290bfc45d71c902ac8d11efdb029fc203c1d5fdb02810b3d7fd283a892917037fd203a0291d51da5cb1c51d102efdf61d03340043883842302b82b028427fd0e008300351c979a009011c0841c829c1c1ca0311daddd1d31d109a426fd71c785d830e114353cec003c150843afd3811424fdc49cfc96c84245d1826423812c1ac0ec1e43383581b82842f021c29c8a82683b7d3fc023340b42883802838ec08c3400490d026dd2b83010c298371c8ec4ed554c2357ca50c20e7188251deb1174a603008c3302dfca237fc65c122601f9c923380c411c0a01290ba3281c4855cfa2600062ffdf41082f81aa34823237fcb2266151cf220a3023d6d81cc80d1cac0620b806814698dd0f8f00a80350d01b51a119bc800000) it works but we use `@react-pdf/renderer` on Node.js server.

Is the behaviour of `Font.register` different when used on the server? 

e.g.

```js
import React from 'react';
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Font,
  renderToString
} from '@react-pdf/renderer';


const generatePdfDocument = () => {
  Font.register({
    family: 'Roboto',
    src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf',
  });

  const styles = StyleSheet.create({
    body: {
      paddingTop: 35,
      paddingBottom: 65,
      paddingHorizontal: 35,
    },
    text: {
      margin: 12,
      fontSize: 14,
      textAlign: 'justify',
      fontFamily: 'Roboto'
    }
  });

  const PDF = () => (
    <Document>
      <Page style={styles.body}>
        <Text style={styles.text}>Какой-то текст + also Latin</Text>
      </Page>
    </Document>
  );

  return <PDF />;
}

async function handler(req, res) {
  const pdfDocument = generatePdfDocument();
  const pdfString = await renderToString(pdfDocument);

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-disposition', `attachment; filename="test.pdf`);

  return res.end(pdfString);
}

```

**Comment by jeetiss** [comment]
Hello, I can not reproduce your problem, this is PDF created from your code example on a server and it is totally fine. 

[test.pdf](https://github.com/diegomura/react-pdf/files/10278623/test.pdf)

Could you create a repo with reproduction so I can help


And this error looks weird because `@react-pdf/renderer` doesn't depends from `@react-pdf/fontkit` for a while 

> ```
> unhandledRejection: TypeError: Cannot read property 'version' of undefined
>   at TTFSubset.encode ( ... /node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:38125:31)
>   at ... /node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:37906:12```

maybe this is reason

**Comment by larimaza** [comment]
> Hello, I can not reproduce your problem, this is PDF created from your code example on a server and it is totally fine.
> 
> [test.pdf](https://github.com/diegomura/react-pdf/files/10278623/test.pdf)
> 

Hello, thanks for replying. Does opening that PDF with Acrobat Reader, Mac's Preview or Safari work for you too? Both me and my coworkers get the same problem, here's what we get opening your PDF:

Acrobat | Preview | Safari | Coworker's Preview
-|-|-|-
<img width="1512" alt="Screenshot 2022-12-21 at 15 59 36" src="https://user-images.githubusercontent.com/25252211/208935369-ae7fbbbe-cf34-4d79-8a35-bb87f286b360.png">|<img width="1512" alt="Screenshot 2022-12-21 at 16 04 31" src="https://user-images.githubusercontent.com/25252211/208936505-da2b798f-4701-4090-9330-f7dd7302add3.png">|<img width="1512" alt="Screenshot 2022-12-21 at 16 02 33" src="https://user-images.githubusercontent.com/25252211/208936173-478f8fbf-9da8-4149-88ec-ec8d1b0a18dd.png">|![Screenshot 2022-12-21 at 17 01 50](https://user-images.githubusercontent.com/25252211/208937105-ec8ff123-8f0d-46e8-8144-8318b21b704a.png)

**Comment by jeetiss** [comment]
I found the problem, it seems like `renderToSring` doesn't work as expected. 

Here is the simple fix for provided script:

```js
import React from 'react';
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Font,
  renderToString
} from '@react-pdf/renderer';
import { Buffer } from "node:buffer";

const generatePdfDocument = () => {
  Font.register({
    family: 'Roboto',
    src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf',
  });

  const styles = StyleSheet.create({
    body: {
      paddingTop: 35,
      paddingBottom: 65,
      paddingHorizontal: 35,
    },
    text: {
      margin: 12,
      fontSize: 14,
      textAlign: 'justify',
      fontFamily: 'Roboto'
    }
  });

  const PDF = () => (
    <Document>
      <Page style={styles.body}>
        <Text style={styles.text}>Какой-то текст + also Latin</Text>
      </Page>
    </Document>
  );

  return <PDF />;
}

const streamToBuffer = (stream) =>
  new Promise((resolve) => {
    let parts = [];
    stream.on("data", (data) => {
      parts.push(data);
    });

    stream.on("end", () => resolve(Buffer.concat(parts)));
  });

async function handler(req, res) {
  const pdfDocument = generatePdfDocument();
  const rawPdf = await streamToBuffer(await renderToStream(pdfDocument));

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-disposition', `attachment; filename="test.pdf`);

  return res.end(rawPdf);
}

```

after the pdf file works in safari and default mac preview, can't test Acrobat

[test(fixed).pdf](https://github.com/diegomura/react-pdf/files/10280039/test.fixed.pdf)

**Comment by larimaza** [comment]
This is great, thank you so much! I'll implement the temporary fix while the PR isn't released.
