### ISSUE TITLE
Attachments is broken after @react-pdf/pdfkit 2.0.12

### ISSUE THREAD

**Issue by chris-morgan** [diegomura/react-pdf#2120]
Details in https://github.com/diegomura/react-pdf/pull/1607#issuecomment-1364461205, just filing this separately since that PR is not *open*.

That patch should either be reverted or fixed properly.

Workaround to get the old, functional version: it’s *probably* enough to, in your package.json, specify exact versions for all relevant packages:

```
{
	"dependencies": {
		"@react-pdf/renderer": "2.0.21",
		"@react-pdf/layout": "2.0.21",
		"@react-pdf/pdfkit": "2.0.12",
	}
}
```

**Comment by jeetiss** [comment]
Thanks for your investigation!
