### ISSUE TITLE
Use CSS variables in react-pdf

### ISSUE THREAD

**Issue by davydaenen** [diegomura/react-pdf#2128]
I have split up my Pdf into components for example a 'Header' component. In this component i use the Text component from react-pdf. Ideally i would like to define css-variables on the root document/page and just use the css-variables in the styles for Text etc. This is what i want to achieve using react-pdfs stylesheet:

.page {
  --pdf-primary: '#00ACBF';
}

.title {
color: var(--pdf-primary)
}

The reason i want to achieve it using css-variables is because the pdf can be whitelabeled for customers. So the colors are dynamic. I dont want to pass a theme/color object into the props for all these components since they could just reference a variable on the root.

I havent been able to make this work with the current StyleSheet.create, do you see a way this can be done? Thanks

version: react-pdf/renderer: 3.0.0

**Comment by jeetiss** [comment]
react-pdf doesn't support CSS variables. Use react context to avoid prop drilling

[something like that](https://react-pdf-experiments.vercel.app/?version=3.0.2&cp_code=MYewdgzgLgBAKgCwKYFskGFxSQD1gXhmACckBDbTMbPACgG8BfASgG4Aod0SWACXIAmSYjEIMiCAJYAbAaTAwWogHwx67GEXDQYUZGlEwArhAxZcUWolRnqFtp02koR4gtobNMADwA1SUgA7jDQAJ7SSPj09DAADmQCApJgAOYAXLr6SAB0EPHASIqMyp5ePnAWIVDhkdFa0iDEGXo22cgJwpgNIozF9MBSsvKM3gD0FXglZWP-QVMwDowcXNqwAApkxGQpW7EIhuIDMnJICkr4quqa3DotBoQmtjSW1mhUzw6ezq7upT6zwTCESiMXiiWS6UyrTyZAKRXm0wmsCBtRioG6zSy2WeXUa8P6gxOYBG4wsCJ8owB80WyxusDuhUIVxg7SExFxTRgACJSAIuQAaTw4kAY7k7JCnAWeGEFDIAJgADIKlpw6TAAKI4MgoWIRA7MFQwDyabyvJ4WbJrYggABukjZMBtZGkRlqDOKf28ABEQMAjGhqOSTRsUoUIJIAF6RLkAQQAbFyYI0AtQKJJwPgudIyGABBBgGRYkguUGvN5-B1iMp-NIGjBAo1ZABCFtjCts0vBzbbXYIauF2KhGAAOSCMAAmuRiC2m2MNlsdoW-38TaMQ0hyWMfX6A1B5mMze8LVbbfbhCVPvI2bRvJrtbrCqNlA4gA)

**Comment by davydaenen** [comment]
@jeetiss , the solution with React Context works great! Thanks and happy new year ;)
