### ISSUE TITLE
Cannot render image stored on Google Cloud Storage

### ISSUE THREAD

**Issue by flaurida** [diegomura/react-pdf#213]
Hi Diego! How are you? I am sorry for being MIA for a bit, a lot going on here.

Anyway, I am trying to render an image in React PDF that is stored on Google Cloud Storage. The image link looks something like: 
```
https://storage.googleapis.com/photos/userId%2Fphotos%2Fprofile_photo.png?GoogleAccessId=project@project-id.iam.gserviceaccount.com&Expires=1521750430&Signature=TOKEN
```

When I try to use an image tag linking to this image, I get the following error:
```
/Users/laura/
      throw new Error('Image type not supported: ' + extension);
            ^
Error: Image type not supported: com&Expires=1521750430&Signature=TOKEN
```

Any ideas for what to do? Thanks!

Sincerely,
Laura

**Comment by diegomura** [comment]
Hi!
Yes. Yesterday I merge a fix for this. I’ll release a new version tomorrow maybe. I’ll let you know, and you can test if that got solved. Sounds good?

**Comment by diegomura** [comment]
Done @flaurida . `0.7.6` published. Please try with this new version and close this issue if everything worked fine 😄

**Comment by flaurida** [comment]
I will try now, thanks for the quick response as always Diego!! 🎉 have a great weekend!

**Comment by diegomura** [comment]
Great news! Thanks to @YozhikM actually who was the one who fix this!
