### ISSUE TITLE
`renderToString` returns blank pages as of 3.0.2

### ISSUE THREAD

**Issue by Naddiseo** [diegomura/react-pdf#2136]
**Describe the bug**
It seems that pages are now blank as of 3.0.2, possibly from the changes in https://github.com/diegomura/react-pdf/pull/2115

**To Reproduce**
```typescript
import { renderToString } from "@react-pdf/renderer";
import { Document, Page, Text } from "@react-pdf/renderer";

const getDocument = ()=> {
    return (
        <Document>
          <Page >
            <Text  >
              page 1
            </Text>
          </Page>
          <Page>
            <Text >
              page 2
            </Text>
          </Page>
        </Document>
      );
}

const root = getDocument();
const fileData = await renderToString(root);
await updateFileDataToS3(fileData);
// Then view the pdf, it is a two page blank document

```
_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_
(the repl is on version 3.0.0)

**Expected behavior**
The two pages should have text on it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows && Linux
 - Browser node version 16
 - React-pdf version 3.0.2

**Comment by jeetiss** [comment]
@Naddiseo seems I broke default fonts when fixing custom ones (

I research how to fix this and it is super hard because `string` is the worst representation for binary pdf format.  Pdf contains different encodings so it is challenging to convert it to a string. I suggest using the `renderToBuffer` method which returns a nodejs buffer instance that is a much better container for binaries and you can pass it to `updateFileDataToS3` without modification

**Comment by Naddiseo** [comment]
> @Naddiseo seems I broke default fonts when fixing custom ones (
> 
> I research how to fix this and it is super hard because `string` is the worst representation for binary pdf format. Pdf contains different encodings so it is challenging to convert it to a string. I suggest using the `renderToBuffer` method which returns a nodejs buffer instance that is a much better container for binaries and you can pass it to `updateFileDataToS3` without modification

Thanks, I'll look into it

**Comment by charkour** [comment]
For a current workaround, you can use v3.0.1

**Comment by Smirow** [comment]
And seems like `renderToBuffer` is not correctly exported by the module. (it can however easily be implemented by the end user)

**Comment by Naddiseo** [comment]
@jeetiss 
> @Naddiseo seems I broke default fonts when fixing custom ones (
> 
> I research how to fix this and it is super hard because `string` is the worst representation for binary pdf format. Pdf contains different encodings so it is challenging to convert it to a string. I suggest using the `renderToBuffer` method which returns a nodejs buffer instance that is a much better container for binaries and you can pass it to `updateFileDataToS3` without modification

As @Smirow pointed out, `renderToBuffer` isn't exported, and adding onto my earlier issue, the Buffer returned is a `NodeJS.ReadableStream`, but unfortunately the awk sdk  for s3 uses the webstream interface (and I'm using node 16 in my current project so I can't use the conversion function that node 18 has).

**Comment by Smirow** [comment]
@Naddiseo 

Not tested on S3 and the way you implemented `updateFileDataToS3` you may try with `blob` ?
```javascript
import { pdf } from "@react-pdf/renderer";
const fileData = await pdf(root).toBlob();
await updateFileDataToS3(fileData);
```
or get the `ReadableStream` out of `blob`:
```javascript
import { pdf } from "@react-pdf/renderer";
const fileData = (await pdf(root).toBlob()).stream(); // should be good with node 16 see https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream
await updateFileDataToS3(fileData);
```

**Comment by jeetiss** [comment]
@Naddiseo @Smirow could you explain which problems you faced when tried to use `renderToBuffer` because i checked it a couple of times and it is exported from the package

I create codesandbox to test it here:
https://codesandbox.io/p/sandbox/naughty-forest-cufd5m

> And maybe `pdf().toBlob()` is a better path.

Nope, it is not. This method does not return a fresh `Blob` instance that was introduced in node 18, it returns a blob polyfill made from array buffers and because of it `ReadableStream` is not available on that 'blob' instance

**Comment by Smirow** [comment]
@jeetiss Seems I can only access thoses export:
https://github.com/diegomura/react-pdf/blob/a3f62c910c0128e0b4312480414dbf8b26dbca1c/packages/renderer/src/node/index.js#L37-L51

**Comment by jeetiss** [comment]
@Naddiseo how do you import `renderToBuffer`?

> Maybe its a type definition thing

yes, i forget about typescript here

**Comment by Naddiseo** [comment]
> @Naddiseo how do you import/require `renderToBuffer`?
> 
> > Maybe its a type definition thing
> 
> yes, i forget about typescript here

@jeetiss, if it **is** exported in the package, then it's definitely missing from the typescript definition:
![image](https://user-images.githubusercontent.com/115951/214903325-4d709476-0463-498d-abc8-f47083b9e694.png)

**Comment by Naddiseo** [comment]
@jeetiss, thanks for fixing the typescript in 3.1.0, I'm now able to use `renderToBuffer` and it works easily with the s3 sdk. (However, I'm assuming the original issue with `renderToString` still exists but it's not present in `renderToBuffer`)
