### ISSUE TITLE
Upgrade from 5.2 to 6.2 throws error on safari 14 related to private name

### ISSUE THREAD

**Issue by sk-roofr** [diegomura/react-pdf#2148]
**Describe the bug**
I upgraded the version from 5.2 to 6.2 and it start to throw errors on safari 14.
I targeted build to es2015.

**To Reproduce**
Load the site and it shows error message

```
unexpected private name #s cannot parse class method with private name

Syntax Error: invalid character ‘#’
```

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
The browser parse the code smoothly

**Desktop (please complete the following information):**
 - OS: [Bigsur]
 - Browser [safari 14]
 - React-pdf version [6.2]

**Comment by Krzyku** [comment]
You probably mean the different package [react-pdf](https://github.com/wojtekmaj/react-pdf)

**Comment by intelcoder** [comment]
Sorry,  please close this.
