### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined 

### ISSUE THREAD

**Issue by Im-Goutham** [diegomura/react-pdf#215]
**OS:** MAC

**React-pdf version:**  0.7.6

**Description:** .  How to fix this issue in create-react-app project.  

**How to replicate issue including code snippet (if applies):**

**Comment by rogierslag** [comment]
Try to include `require('babel-polyfill')` at the top of the calling script, or use a proper webpack configuration to make this error go away

**Comment by tgmarinho** [comment]
I have the same problem, but I am using meteor and ES6 imports, how Can fix it? Should I open a new issue in here?

**Comment by diegomura** [comment]
Hi @tgmarinho. Never used meteor, sorry. I wouldn't know how to solve it. @rogierslag fix didn't worked? If it's the same error message please don't open a new issue

**Comment by tgmarinho** [comment]
Ok, thanks for your feedback
