### ISSUE TITLE
Send Email the generated pdf  from React-pdf

### ISSUE THREAD

**Issue by salavudeenH** [diegomura/react-pdf#2153]
Hello,
I want send the generate pdf from react pdf to email. I Can download is ok. 

**I want send this pdf to email with sendgrid in backend how i can pass from frontend this attachement in backend to send email without downloading**

<PDFDownloadLink document={<MyDoc />} fileName="file2.pdf">
      {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
    </PDFDownloadLink>

**Comment by Krzyku** [comment]
Basically, You need to get a blob and send it to the backend. Similar to e.g. attachments that users can upload via file input. No new feature is needed in react-pdf. Here is an example solution, details depend on your setup.

```ts
const [instance, update] = usePDF({ document });

const send = () => {
  if (!instance.blob) {
    alert('not ready yet');
    return
  }
  const formData = new FormData();
  formData.append('file', instance.blob);
  fetch(url, {body: formData, method: 'POST'}).then(/*...*/);
}
```
