### ISSUE TITLE
🐛 Memori Leak

### ISSUE THREAD

**Issue by robyhuzwandar** [diegomura/react-pdf#2154]
**Describe the bug**
Memory leak

when import react pdf got this memory leak

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/20414047/214986923-b0f55b1c-cdfe-431d-8696-743cd2dbf5b1.png">

**Comment by jeetiss** [comment]
@robyhuzwandar `@react-pdf/yoga` was configurated to allocate `256mb` 🙃 so this is not a memory leak
