### ISSUE TITLE
Allow Rendering of Images as base64 strings

### ISSUE THREAD

**Issue by TimonSotiropoulos** [diegomura/react-pdf#216]
Great package! I am trying to use this to render some graphs that I have converted into base64 png images. Is it possible to get this to work with your Image component? Or is there an easy fix to get this to work?

**Comment by diegomura** [comment]
First, @TimonSotiropoulos thanks for exposing your research in such details. Is really interesting how you handle to render SVG. That's something we are not supporting, but I will eventually. I'll came back to this when that time arrives.

About rendering base64 images, apparently was supported the whole time (my bad!). All you have to do is passing the base64 string in the `src` prop of `Image`:

```jsx
<Image src="data:image/jpeg;base64,/9j/2wCEAAgGBgcGBQgHBwcJC..." />
```

**Comment by dylanjt** [comment]
@TimonSotiropoulos I'm actually working on a problem I think you addressed in your update:

> the issue seems to lie in the fact that currently your library can only extract the width/height of a png image when it is in the Uint8Array format.

Have you found a workaround to this? I'm creating an image buffer using component-image library, then converting it into a datauri using the datauri library (looks like `data:image/png;base64,iVBORw0KGgoAAA...`), however when I pass that string into `<Image src={} />` I'm getting this error:

```
TypeError: this.calculateHeight is not a function
```

Is this what you were referring to? I pasted the generated data URI into a plain HTML image component to verify it works / is valid -- it is.

**Comment by diegomura** [comment]
@dylanjt I don't think that's related. That error was reported here https://github.com/diegomura/react-pdf/issues/263, and I fixed it here https://github.com/diegomura/react-pdf/commit/fe903060aa599043705c1186c422a3a06858573e, just that I didn't released a new version yet with those changes.
Doesn't mean that what @TimonSotiropoulos said can still cause you troubles, but it's just not the cause of that error

**Comment by dylanjt** [comment]
@diegomura oh! Cool. I'll reference the commit in my package.json until a formal new version. Reitertating was Timon said - thanks for putting this package together.

**Comment by diegomura** [comment]
No problem @dylanjt ! idk if pointing to a commit will work though, since there's no going to be a `dist` folder where to get the builds.
