### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled 

### ISSUE THREAD

**Issue by shuvamgrad** [diegomura/react-pdf#2162]
Getting this error today "Support for the experimental syntax 'classProperties' isn't currently enabled", please check

**Comment by jeetiss** [comment]
I'm going to close this issue. @shuvamgrad could you please more info about the problem? How to reproduce? Library version?

**Comment by shuvamgrad** [comment]
./node_modules/@react-pdf/yoga/dist/index.esm.js
SyntaxError: react-app/node_modules/@react-pdf/yoga/dist/index.esm.js: Missing class properties transform.

**Comment by shuvamgrad** [comment]
I got this error while running "npm build" which was running fine before.

**Comment by jeetiss** [comment]
@shuvamgrad could you provide `node` version and react-pdf version?

**Comment by shuvamgrad** [comment]
node version - 14.9.0
"@react-pdf/renderer": "^3.0.1"

**Comment by shuvamgrad** [comment]
./node_modules/@react-pdf/yoga/dist/index.esm.js 117:10
Module parse failed: Unexpected token (117:10)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   var C2 = Xu(Hu()),
|     Qu = class {
>       left;
|       right;
|       top;



this is error when running "npm start"

**Comment by imranbukuhari** [comment]
Got this error when trying to react-scripts start
SyntaxError: ../node_modules/@react-pdf/yoga/dist/index.esm.js: Missing class properties transform.

**Comment by erica4appz** [comment]
i am also experiencing the same issue 
but works fine when npm run build 
but not with yarn build
