### ISSUE TITLE
Module parse failed: Unexpected token, You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by nugrohoarfianto** [diegomura/react-pdf#2166]
**Describe the bug**
Hi, suddenly today I got an error when trying to build my react app. I'm not doing any update to the package or anything.

```
ERROR in ./node_modules/@react-pdf/yoga/dist/index.js 3:2249
Module parse failed: Unexpected token (3:2249)
You may need an appropriate loader to handle this file type.
| 'use strict';

*content of ./node_modules/@react-pdf/yoga/dist/index.js* 

 @ ./node_modules/@react-pdf/layout/lib/index.cjs.js 16:11-37
 @ ./node_modules/@react-pdf/renderer/lib/react-pdf.browser.cjs.js
 @ ./app/containers/QuotationDetails/index.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js
```

**To Reproduce**
1. Remove node_modules & package_lock.json
2. npm install
3. npm run build

**Expected behavior**
React app built successfully

**Screenshots**
<img width="990" alt="Screenshot 2023-01-30 at 13 46 15" src="https://user-images.githubusercontent.com/22047468/215406826-f20eb118-6733-4d6b-ad95-3bd672e71381.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - React-pdf version : 3.0.0 (tried to update to 3.1.1, but no luck)

Is there anything I could do to build my app just like before?

Thanks.

**Comment by ntquang98** [comment]
same error
