### ISSUE TITLE
Background Image URL

### ISSUE THREAD

**Issue by audiolion** [diegomura/react-pdf#218]
**OS:** OSX/Ubuntu 16.04

**React-pdf version:** latest

**Description:** Getting background images for the page

**How to replicate issue including code snippet (if applies):**

```js
render() {
  const styles = StyleSheet.create({
    container: {
      background: 'url("http://imgur.com/nd3yf1Q.png") no-repeat center center fixed',
    }
  });
  return (
      <Document>
        <Page size="LETTER" orientation="landscape">
          <View style={styles.container}>
            {/* inner content of view */}
          </View>
        </Page>
      </Document>
  );
}
```

I am trying to have my entire page contain this background image from a url, is this possible with `react-pdf`? I can do it with `pdfkit`

**Comment by diegomura** [comment]
@audiolion No. Not currently possible.
The only way I can think to make it work is by positioning an absolute image and some elements after. I recommend you give it a try

**Comment by audiolion** [comment]
I actually checked through `pdfkit`, I dont think `pdfkit` supports this feature actually. I am going to try a few different ways and will report back if I find a solution.

**Comment by diegomura** [comment]
absolute positioning is not something that `pdfkit` implements, but `react-pdf` does. You can see an example of absolute positioning [here](https://github.com/diegomura/react-pdf/tree/master/examples/knobs)

**Comment by audiolion** [comment]
Awesome, yep this works to create a background image covering the pdf

```js
const styles = StyleSheet.create({
  pageBackground: {
    position: 'absolute',
    minWidth: '100%',
    minHeight: '100%',
    display: 'block',
    height: '100%',
    width: '100%',
  },
});

class MyComponent extends React.component() {
  render() {
    return (
      <Document>
        <Page size="LETTER" orientation="landscape">
          <Image src="http://imgur.com/nd3yf1Q.png" style={styles.pageBackground} />
        </Page>
      </Document>
    );
  }
}
```

**Comment by diegomura** [comment]
@audiolion awesome! Glad it worked

**Comment by captain-hayze** [comment]
You rock!

**Comment by ampsteric** [comment]
Why is it not working in my case?

import React, { useMemo } from "react";

import {
    PDFDownloadLink,
    Document,
    Page,
    View,
    Text,
    Image,
} from "@react-pdf/renderer";

const styles = {
    pageBackground: {
        position: "absolute",
        minWidth: "100%",
        minHeight: "100%",
        display: "block",
        height: "100%",
        width: "100%",
    },
};
const MyDoc = () => (
    <Document>
        <Page size="A4" size="LETTER" orientation="landscape">
            <View>
                <Image
                    src="http://imgur.com/nd3yf1Q.png"
                    style={styles.pageBackground}
                />
            </View>
        </Page>
    </Document>
);

export default function Appa() {
    return useMemo(
        () => (
            <PDFDownloadLink document={<MyDoc />} fileName="some-nane.pdf">
                {({ loading }) => (loading ? "loading..." : "download")}
            </PDFDownloadLink>
        ),
        []
    );
}

**Comment by abdalla-ayman** [comment]
> Awesome, yep this works to create a background image covering the pdf
> 
> ```js
> const styles = StyleSheet.create({
>   pageBackground: {
>     position: 'absolute',
>     minWidth: '100%',
>     minHeight: '100%',
>     display: 'block',
>     height: '100%',
>     width: '100%',
>   },
> });
> 
> class MyComponent extends React.component() {
>   render() {
>     return (
>       <Document>
>         <Page size="LETTER" orientation="landscape">
>           <Image src="http://imgur.com/nd3yf1Q.png" style={styles.pageBackground} />
>         </Page>
>       </Document>
>     );
>   }
> }
> ```

it only worked in first page for me how to aply it to all pages

**Comment by jeromem-EC** [comment]
> > Awesome, yep this works to create a background image covering the pdf
> > ```js
> > const styles = StyleSheet.create({
> >   pageBackground: {
> >     position: 'absolute',
> >     minWidth: '100%',
> >     minHeight: '100%',
> >     display: 'block',
> >     height: '100%',
> >     width: '100%',
> >   },
> > });
> > 
> > class MyComponent extends React.component() {
> >   render() {
> >     return (
> >       <Document>
> >         <Page size="LETTER" orientation="landscape">
> >           <Image src="http://imgur.com/nd3yf1Q.png" style={styles.pageBackground} />
> >         </Page>
> >       </Document>
> >     );
> >   }
> > }
> > ```
> 
> it only worked in first page for me how to aply it to all pages

`<View fixed={true}><Image src="http://imgur.com/nd3yf1Q.png" style={styles.pageBackground} /></View>`

**Comment by spartan4cs** [comment]
How to add the data after setting the background image


import { Document, Image, Page, StyleSheet } from "@react-pdf/renderer";
import React from "react";
import BillTo from "./BillTo";
import InvoiceItemsTable from "./InvoiceItemsTable";
import InvoiceNo from "./InvoiceNo";
import InvoiceThankYouMsg from "./InvoiceThankYouMsg";
import InvoiceTitle from "./InvoiceTitle";
import logo from "../../logo.svg";
import hcbgImage from "../../asset/bg-img.jpg";

const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "red",
    /// backgroundImage: `url(${logo})`,
    //  backgroundImage:"url('https://media.geeksforgeeks.org/wp-content/uploads/rk.png')",
    // backgroundSize: "cover",
    fontFamily: "Helvetica",
    fontSize: 11,
    paddingTop: 30,
    paddingLeft: 50,
    paddingRight: 50,
    lineHeight: 1.5,
    flexDirection: "column",
  },
  pageBackground: {
    position: "absolute",
    minWidth: "100%",
    minHeight: "100%",
    display: "block",
    height: "100%",
    width: "100%",
  },
  logo: {
    width: 84,
    height: 70,
    marginLeft: "auto",
    marginRight: "auto",
  },
});

const PdfDocument = ({ invoicedata }) => {
  return (
    <Document>
      <Page size="A4">
        <Image src={hcbgImage} style={styles.pageBackground}>
          <InvoiceTitle title={"Invoice"} />
          <InvoiceNo invoice={invoicedata} />
          <BillTo invoice={invoicedata} />
          <InvoiceItemsTable invoice={invoicedata} />
          <InvoiceThankYouMsg />
        </Image>
      </Page>
    </Document>
  );
};

export default PdfDocument;

**Comment by joehunterdev** [comment]
Any one had success getting this to work accross two pages ? Thanks in advance 

```
<Page size="A4" style={{ ...styles.container }}>
  <View style={styles.pageBackgroundContainer}>
    <Image
      src={BackgroundImage}
      style={{ height: "830px", width: "794px" }}
    />
  </View>
  {/* ... rest of the content ... */}
</Page>

<Page size="A4" style={{ ...styles.container }}>
  <View style={styles.pageBackgroundContainer}>
    <Image
      src={BackgroundImage}
      style={{ height: "830px", width: "794px" }}
    />
  </View>
  {/* ... rest of the content ... */}
</Page>
```

**Comment by Psycokwet** [comment]
Hello, so I tried something that seems to work, but look a tiny bit like black magic, here it is :

I use tw integration so keep that in mind, but here is the working code 
```js

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from '@react-pdf/renderer';
import { PDFViewer } from '@react-pdf/renderer';
import { createTw } from 'react-pdf-tailwind';
import tailwindConfig from '../../../tailwind.config';
import { notFound } from 'next/navigation';
import { useQuery } from '@apollo/client';
import { GetMostRecentCalculationByClaimIdDocument } from '../../../graphql/generated/graphql';
import { useRouter } from 'next/router';
import backgroundImage from '../../../public/pdf_background_pattern.png';
const tw = createTw(tailwindConfig);

const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    position: 'relative',
  },
  image: {
    position: 'absolute',
    zIndex: -1,
  },
});
const PageWrapper = ({ children }: { children: React.ReactNode }) => (
  <Page size="A4" style={styles.page}>
    <View>{children}</View>
    <Image
      src={backgroundImage.src}
      style={{ ...styles.image, ...tw('absolute w-full h-full bg-blue-100 ') }}
    />
  </Page>
);

export function MyPdf(props: any) {
  const { description } = props;
  console.log(description);
  return (
    <Document>
      <PageWrapper>
        <Text style={tw('font-bold text-5xl text-red-900')}>Section #1</Text>
      </PageWrapper>
    </Document>
  );
}
```

On top of the styling the <Image> MUST be put AFTER the content, and I cannot fathom why.

**Comment by joehunterdev** [comment]
Hi guys, yes this is totally doeable. Infact i have done it accross multiple pages aswell, so i thought id share my react-pdf repo. Features nearly all design elements in documentation. Great Stuff!
https://github.com/joehunterdev/react-pdf-cv

**Comment by urfx** [comment]
> Hi guys, yes this is totally doeable. Infact i have done it accross multiple pages aswell, so i thought id share my react-pdf repo. Features nearly all design elements in documentation. Great Stuff! https://github.com/joehunterdev/react-pdf-cv

@joehunterdev thanks for sharing that looks really good and helpful. 

what is "weight" line 57 https://github.com/joehunterdev/react-pdf-cv/blob/main/src/App.jsx ?

**Comment by Akhtar7862** [comment]
Hi! I have seen the solutions in the above comments but none of them address the issue of inserting a background image to a page WHICH HAS CONTENT IN IT. After I add a background image to a component, I am unable to add any content on the image. Whatever I enter goes below or above the image.

**Comment by joehunterdev** [comment]
Hi there,
              weight should be width on Ln 57. Basicly background-image css
attribute will not work. So what you have to do is create a <view>that
contains the image that has absolute positioning usually the height of your
page postioned top. This must come first. You can then continue on with
your <Page> content just make sure you have top:0 and absolute also. No
magic here this is just html + css. Google placing text over absolute div.

Good Luck

**Comment by joehunterdev** [comment]
> > Hi guys, yes this is totally doeable. Infact i have done it accross multiple pages aswell, so i thought id share my react-pdf repo. Features nearly all design elements in documentation. Great Stuff! https://github.com/joehunterdev/react-pdf-cv
> 
> @joehunterdev thanks for sharing that looks really good and helpful.
> 
> what is "weight" line 57 https://github.com/joehunterdev/react-pdf-cv/blob/main/src/App.jsx ?

that should be width... typo

**Comment by Thangvanle2000** [comment]
> Awesome, yep this works to create a background image covering the pdf. Are u kidding me

**Comment by Qudusayo** [comment]
> Hi guys, yes this is totally doeable. Infact i have done it accross multiple pages aswell, so i thought id share my react-pdf repo. Features nearly all design elements in documentation. Great Stuff!
> https://github.com/joehunterdev/react-pdf-cv

This won't work as I cannot determine the content of the page as my page only contains table which could break to the next page.
