### ISSUE TITLE
registerEmojiSource example is not showing the emoji

### ISSUE THREAD

**Issue by janmiofsky** [diegomura/react-pdf#2180]
**Describe the bug**

The Emoji in the Documentation: https://react-pdf.org/repl?example=emoji are not shown in the PDF anymore.

This is due to MaxCDN been shutdown. See https://github.com/twitter/twemoji/issues/580. 
But when I try to change it to a new CDN link mentioned in the thread like https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/ it still does not show any emoji's. 

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to 'https://react-pdf.org/repl?example=emoji'
2. See error

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**
<img width="1503" alt="React PDF Docs 1" src="https://user-images.githubusercontent.com/18344019/216021193-0a8443bd-f253-418f-a72e-9ae4642086c8.png">
<img width="1503" alt="React PDF Docs 2" src="https://user-images.githubusercontent.com/18344019/216021212-222b84ee-fd5d-481b-9ff8-3870e45d2354.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome
 - React-pdf version: Official documentation playground

**Comment by janmiofsky** [comment]
I got it to work. The example does not load the new font so this was confusing. When I use a new emoji source in my code it works.

**Comment by Dev-Jariwala** [comment]
but share the code that worked bro
