### ISSUE TITLE
memory leak in renderer@3.1.3

### ISSUE THREAD

**Issue by modosc** [diegomura/react-pdf#2184]
**Describe the bug**
we've noticed a memory leak when upgrading from `@react-pdf/renderer@3.03` to `@react-pdf/renderer@3.1.3`

**To Reproduce**
(note: i'm working on a sharable example)

in our repo we have snapshot tests that render ~100 pdfs via `renderStream` and compares them to stored stringified values.

with `@react-pdf/renderer@3.03` the heap size remains more or less constant throughout the test.
with `@react-pdf/renderer@3.1.3` the heap grows until we eventually hit an `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` error.

**Expected behavior**
there shouldn't be a memory leak

**Desktop (please complete the following information):**
we are using node `v18.12.0`. 
this behavior occurs on both macos and linux.

**Comment by alextselegidis** [comment]
Hello! 

FYI I'm using "@react-pdf/renderer": "3.0.2" in a Meteor app and get a memory error as well. 

The app crashes with: 

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed

**Comment by modosc** [comment]
i tried updating again - we don't see the memory issues now but we do see a ton of changes in our pdf layout (which is surprising for a change in a dependency of a dependency - i'd expect a version bump in `@react-pdf/renderer` at least?). i'm investigating these now.

**Comment by modosc** [comment]
it looks like pretty much all of our flex layout is broken in some way now.

**Comment by jeetiss** [comment]
that is my fault, sorry. I revert flex shorthand defaults and it should help, could you please check it out? (yet another change in a dependency of a dependency)

> which is surprising for a change in a dependency of a dependency - i'd expect a version bump in @react-pdf/renderer at least?

yes, this is a problem, we definitely should change release strategy

**Comment by modosc** [comment]
just updated again - no more layout changes and no more memory leaks. thanks!

**Comment by anwarjaved** [comment]
I am getting the same error on 18.14.0 and @react-pdf/renderer 3.1.3

`<--- Last few GCs --->

[23612:000001545EAB4350]   723336 ms: Scavenge 2020.3 (2045.1) -> 2005.0 (2045.4) MB, 3.0 / 0.0 ms  (average mu = 0.320, current mu = 0.302) allocation failure 
[23612:000001545EAB4350]   723363 ms: Scavenge 2020.7 (2045.4) -> 2005.4 (2045.6) MB, 3.0 / 0.0 ms  (average mu = 0.320, current mu = 0.302) allocation failure
[23612:000001545EAB4350]   723391 ms: Scavenge 2021.0 (2045.6) -> 2005.7 (2046.4) MB, 3.2 / 0.0 ms  (average mu = 0.320, current mu = 0.302) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6CF82606F napi_wrap+133327
 2: 00007FF6CF7BF646 DSA_meth_get_flags+63062
 3: 00007FF6CF7C04DD node::OnFatalError+301
 4: 00007FF6D00A499E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6D008978D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6CFF32F8C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF6CFF3E3AA v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF6CFF3B4E9 v8::internal::Heap::PageFlagsAreConsistent+2457
 9: 00007FF6CFF30081 v8::internal::Heap::CollectGarbage+2049
10: 00007FF6CFF36E97 v8::internal::Heap::GlobalSizeOfObjects+231
11: 00007FF6CFF7177B v8::internal::StackGuard::HandleInterrupts+891
12: 00007FF6CFC7E8D6 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+8230
13: 00007FF6D012FDCD v8::internal::SetupIsolateDelegate::SetupHeap+474253`

**Comment by anwarjaved** [comment]
I tried to downgrade it to 3.0.3 but still same error

**Comment by jeetiss** [comment]
@anwarjaved could you provide `@react-pdf/yoga` version that you use?
