### ISSUE TITLE
Container shouldn't wrap if no children can fit in the initial page

### ISSUE THREAD

**Issue by Solpatium** [diegomura/react-pdf#2197]
**Describe the bug**
The issue is that a parent container that can't fit into a single page is split, but no children is actually displayed on the first page. This means that if parent container has some background the resulting pdf will show wrapper with no content.

This is an edge case that happens when:
- parent can be wrapped,
- no child can fit on processed page or be split into two.

Here's the simplfied example of it happening: 

Page 1:
![image](https://user-images.githubusercontent.com/10278469/218280138-9f089866-3951-4e5c-9a5e-40c0d4e0c4d4.png)

Page 2:
![image](https://user-images.githubusercontent.com/10278469/218280146-bf03137e-b471-4f92-aa4c-2f401496ebd1.png)

The red area is the parent container that contains two blue containers. I can't dissalow wrapping for parent container, because in case blue can fit I do want to wrap it. In this paricular case however I don't want to start parent container on the previous page.

I've looked into the code and the problem is that [this logic](https://github.com/diegomura/react-pdf/blob/992b91b3866e8e24efa014eef4d3eeec6a40f9a5/packages/layout/src/steps/resolvePagination.js#L95) doesn't consider this particular case. Currently the end result is that node is assigned to both initial (with children = []) and the next page (with all children). After `relayoutPage` upper part of the parent gets adjusted height. 

Can you advise what would be the best way of dealing with that? I could create a PR if this would make it easier for you.

**To Reproduce**
See [repro](https://react-pdf.org/repl?code=3187b0760ce02e0040a200f021816c00e01b0298c0bc3002804a3c03e420281860078011118015c52cc294abada005240731cd0027b65c01bdc5a24004c6404b30fc0170c004c001800d0c0046498006b7e009c4133032030880c204ea804419e7f0016514d6618e02fafce6e6e71006d00461d35005d003a1424340262324a20a0807a002a180015377908180037792c0077186024300072583724229c329304890033240c082c5f1d5d2c2aa61e9879769808457e6c4afc8c1951c2a45d19f6f958701828371c69411800491832ead828101834265875ad9d932c18984cf4ae34da0035528a9131491878899f88a0010880a0e7142a8d400561d348e4535500199b47a03318cc166b2d9ec4e00310c861000e003b1931cd47f0c102ef6e0d0bee563ab4d01d2e8f57c1328288b01271195e4326d938c21a0d001491c3a1dab83c28b17f431a6732586c76070c11cf8b26e98944a94029040d078321d0987f9d2b4ba67dbeccb6b893add5e972797c8150adc22b164ba55859541e568fd11995d8b55e335dad26ebf596eb5a468e94659413d4221117c6f5a3a4f8825a52618cc563b138440037050ab00252c018a03c3a000c4620f4b1604c041a22150981c15a2b1420000).

**Expected behavior**
I want the parent container to be removed from the initial page in case like this.

**Possible workaround**
You can wrap every child in a view with `wrap={false}` and add background & paddings to those wrappers, like [this](https://react-pdf.org/repl?code=3187b0760ce02e0040a200f021816c00e01b0298c0bc3002804a3c03e420281860078011118015c52cc294abada005240731cd0027b65c01bdc5a24004c6404b30fc0170c004c001800d0c0046498006b7e009c4133032030880c204ea804419e7f0016514d6618e02fafce6e6e71006d00461d35005d003a1424340262324a20a0807a74983e1336580037792c007718372408182418503b1318002b26681828101808371052a872d8797ecae8790c0c56b72c5c9d66c57e71f94ae2fb432424330b1918617318197000725862a4761801d6f6f2fc9c13e11adb7b2e34da003522d29131491878937e450010880a06d142a8d400561d3e88ca6732586c7527001880066004e19160b18e6a3f86081679a4686f128c18a260484951480c040b0be0e94144580938860d2392cd5400666d073640a2510241a0f0542f406633ac110f070c11cb9192e260fe4251389a4d2852a9e21a5d2194c965b38af2192f49c610d06800a48e1d04d5c1e5e75ba152b846d11f6144003800ecba1f4c8217e5f3a5d51ada3a4b511e78012049ef2357dd99ca14a8607c9d1a7660015101a154fc9874be1d639538952ab553c897184d6bc994b435369f4c667d59925379adc96eb5da1d58275405dc5f74cbcb4885723fd81e0e87c3b58d4d1a3ef58f715731e5cc088445f2d7577c41213570c662b1d89c22001b828f780129600c501e1d00062315ca5926041a221504c07070d6f0a0800).

**Screenshots**
Here's a real life example of this behaviour:
![image](https://user-images.githubusercontent.com/10278469/218280490-ba657a40-5d17-4a4c-9746-e4923095004b.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - React-pdf version 3.1.3

Thank you for this library <3

**Comment by Solpatium** [comment]
I've created a PR that fixes this behaviour #2198. I'd appreciate any feedback ❤️

**Comment by jeetiss** [comment]
Thanks for your contribution 🙌🏻
