### ISSUE TITLE
Using react-pdf with meteor js

### ISSUE THREAD

**Issue by windgaucho** [diegomura/react-pdf#220]
Hello I am trying to use react-pdf package (0.7.6 version) in a meteor js application, using react.js.
I can not use webpack because meteor has its own build tool, so I can not use transform-loader also, there is another solution to use this package inside meteor js app ?

**Comment by diegomura** [comment]
Hi @windgaucho 
To be honest, I don't know. Currently for the browser you need to do that specific setup with webpack. I think the answer you should be looking is how to replicate that config on meteor, which I don't know if it's possible.
Sorry for not being more helpful

**Comment by windgaucho** [comment]
@diegomura thank you anyway. I will try to resolve the problem and let you know in case some one else had the same problem.

**Comment by pmogollons** [comment]
Hi @windgaucho,

Were you able to use it? Im using meteor 1.7 and is working fine when rendering in server code. You just need to import the following as per the docs.

```js
import 'regenerator-runtime/runtime';
```

Cheers.

**Comment by windgaucho** [comment]
Hi @pmogollons 
I didn't try with meteor 1.7. I ended up using pdfmake that works with meteor 1.6

**Comment by diegomura** [comment]
It should work now with the new `v1.0.0-alpha.X` version
