### ISSUE TITLE
Link component rendered as a string, when originates from react-18next

### ISSUE THREAD

**Issue by viktordanko** [diegomura/react-pdf#2213]
**Describe the bug**
`<Link>` component is rendered as a string, when it comes from a translation key using [react-18next](https://www.npmjs.com/package/react-i18next) library.

**Relates to**
[Issue](https://github.com/diegomura/react-pdf/issues/381)

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to [CodeSandbox](https://codesandbox.io/s/react-i18next-forked-jyrgy5?file=/src/app.js)

**Expected behavior**
`<Link>` component is clickable inside the generated PDF file

**Desktop (please complete the following information):**
 - OS: "MacOS"
 - Browser "Chrome"
 - React-pdf version "3.0.1"

**Comment by x-Wawa** [comment]
Hi, Sorry but you are just using react-18next lib wrong, after reading the docs see here how to solve your issue:

[example sandbox](https://codesandbox.io/embed/react-i18next-forked-kclfyt?fontsize=14&hidenavigation=1&theme=dark)

replace the `<RenderTrans />` component by:
```javascript
const RenderTrans = () => {
  return (
    <Text>
      <Trans
        i18nKey="Link"
        values={{
          linkMessage: "Try to click on this -> ",
          linkText: "link"
        }}
        components={[<Text />, <Link src="https://www.example.com" />]}
      />
    </Text>
  );
};
```

and your i18 file like that:
```javascript
import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        translations: {
          Link: "<0>{{- linkMessage}}:</0> <1>{{- linkText}}</1>"
        }
      }
    },
    fallbackLng: "en",
    debug: true,
    ns: ["translations"],
    defaultNS: "translations",
    keySeparator: false,
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
```

**Comment by jeetiss** [comment]
@x-Wawa thanks ❤️

**Comment by viktordanko** [comment]
@x-Wawa Thanks a lot!
