### ISSUE TITLE
Table Nested exploration

### ISSUE THREAD

**Issue by AbyssDark** [diegomura/react-pdf#2219]
I want to render a table like this in my project but I don't still find out how, can you guy help me? I kind of lost don;t know what to do next.
![image](https://user-images.githubusercontent.com/44426410/221818595-fbaacec4-4843-4a18-8249-28159a37cfcd.png)
my table design base on this code
![image](https://user-images.githubusercontent.com/44426410/221819356-3c6bd456-91b0-4710-a016-39100727d9f4.png)

**Comment by vicksbr** [comment]
unfortunately the `display: table` is not supported, but u can implement a table with flexbox as demonstraded [here](https://www.npmjs.com/package/react-pdf-table)

**Comment by AbyssDark** [comment]
> unfortunately the `display: table` is not supported, but u can implement a table with flexbox as demonstraded [here](https://www.npmjs.com/package/react-pdf-table)

thank , but i manage to write a Nested Table with flex , and react-pdf-table not working at all
