### ISSUE TITLE
Unable to load local font file with Font.register in Next.js

### ISSUE THREAD

**Issue by leonace924** [diegomura/react-pdf#2223]
**OS**: Windows 11
**React-pdf version**: 3.1.6

Description:
Hello, I've been trying to register a font for the document from the local file system (since I'm using Nex.js). What i've noticed is that if I use the following, the document is never generated 

`Font.register({
  family: "Helvetica Neue",
  fonts: [{ src: "/public/fonts/helveticaNeue-std.woff2" }],
});`

I need to use local font because Helvetica font is not on google fonts, but it doesn't read the from the local
Could you give me the solution for this?

Thank you

**Comment by leonace924** [comment]
@diegomura , could you help me on this please?
Thank you

**Comment by jeetiss** [comment]
@leonace924 remove `public` from the font path

**Comment by leonace924** [comment]
> @leonace924 remove `public` from the font path

@jeetiss , that doesn't work neither,
could you share some example with nextjs local font import, if you don't mind?

Thank you

**Comment by leonace924** [comment]
@jeetiss 
Main problem is font glyph doesn't work, like this symbol
do you have any solution for this?
I used `Helvetica Neue` font, it works fine on local but doesn't work on pdf even I import the same font

![image](https://user-images.githubusercontent.com/42954461/223176925-5a8265d2-e4c8-4e40-8746-36e15c4dae3e.png)

**Comment by leonace924** [comment]
This shows same on playground too - https://react-pdf.org/repl

https://prnt.sc/L5u1-IiZQJl_

**Comment by tunjayhuseynov** [comment]
Hi,

Is there any update?

**Comment by denisprado** [comment]
I am having the same issue... :(

**Comment by ferisjuan** [comment]
Same here

**Comment by Ariuk0112** [comment]
any update ?

**Comment by rafhpabustan** [comment]
Though this is closed, let me just leave this here incase someone needs it. I managed to make it work through trial and error by registering like this:
```
Font.register({
  family: "FontName",
  src: "/fonts/font-file.otf",
});
```
I have my fonts on public directory. Using relative path `.../.../public/font/font-file` didn't work for me. probably related to nextjs's webpack config. After figuring out the solution, I saw this [documentation](https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets) from next.js, pointing out how to access public files.

**Comment by mmany** [comment]
same here , can't load the font (be it ttf, otf or woff2):

<img width="529" alt="Screenshot 2023-12-10 at 12 45 17" src="https://github.com/diegomura/react-pdf/assets/7147886/95a28b29-c3e8-4771-9d94-69efb625f1f5">

```
import {
  Page,
  View,
  Document,
  StyleSheet,
  Text,
  Font,
} from "@react-pdf/renderer";

Font.register({
  family: "inter",
  src: "/fonts/Inter-Regular.otf",
});

// Create styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: "#ffffff",
    padding: "48px",
    fontSize: "16px",
    fontFamily: "inter",
  },
  header: {
    height: "27%",
    display: "flex",
    alignItems: "stretch",
  },
  headerLeft: {
    width: "60%",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    justifyContent: "space-between",
  },
});

**Comment by KayBeSee** [comment]
Same issue. Can this be reopened @leonace924?

**Comment by isaico** [comment]
@

> Though this is closed, let me just leave this here incase someone needs it. I managed to make it work through trial and error by registering like this:
> 
> ```
> Font.register({
>   family: "FontName",
>   src: "/fonts/font-file.otf",
> });
> ```
> 
> I have my fonts on `$root/public `directory. Using relative path `.../.../public/font/font-file` didn't work for me. probably related to nextjs's webpack config. After figuring out the solution, I saw this [documentation](https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets) from next.js, pointing out how to access public files.

This works for me, i moved my fonts file from app to public and directly use it on the register function like this: 
` Font.register({
        family: 'Calibri',
        format: 'truetype',
        src: "/fonts/calibri.ttf",
    });`

**Comment by Sergey-lang** [comment]
![image](https://github.com/diegomura/react-pdf/assets/63201050/977af530-b57c-4f1c-b96d-2aa1dfdd89a0)
this is work, but only if I wrote string in src (NextJs 12.2.4, "@react-pdf/renderer": "3.3.8")

**Comment by ln-dev7** [comment]
> Though this is closed, let me just leave this here incase someone needs it. I managed to make it work through trial and error by registering like this:
> 
> ```
> Font.register({
>   family: "FontName",
>   src: "/fonts/font-file.otf",
> });
> ```
> 
> I have my fonts on `$root/public `directory. Using relative path `.../.../public/font/font-file` didn't work for me. probably related to nextjs's webpack config. After figuring out the solution, I saw this [documentation](https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets) from next.js, pointing out how to access public files.

Thanks so much ! it works for me !

**Comment by aliBit68** [comment]
> @
> 
> > Though this is closed, let me just leave this here incase someone needs it. I managed to make it work through trial and error by registering like this:
> > ```
> > Font.register({
> >   family: "FontName",
> >   src: "/fonts/font-file.otf",
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have my fonts on `$root/public `directory. Using relative path `.../.../public/font/font-file` didn't work for me. probably related to nextjs's webpack config. After figuring out the solution, I saw this [documentation](https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets) from next.js, pointing out how to access public files.
> 
> This works for me, i moved my fonts file from app to public and directly use it on the register function like this: ` Font.register({ family: 'Calibri', format: 'truetype', src: "/fonts/calibri.ttf", });`

Thanks this worked for me

**Comment by ashkankiani** [comment]
I am having the same issue... :(

**Comment by jaandrews** [comment]
I'm having this issue as well, even with the relative path that is supposed to start from the public directory. Currently running nextjs **14.2.4** and version **9.0.0** of react pdf. Tried "/fonts/my-font.otf" and various levels of drilling up directories with "../" without success. This works just fine for other relative references, like the @font-face lines in the website css, but for whatever reason fails when loading it with Font.register.

**Comment by zahranaserii** [comment]
> I'm having this issue as well, even with the relative path that is supposed to start from the public directory. Currently running nextjs **14.2.4** and version **9.0.0** of react pdf. Tried "/fonts/my-font.otf" and various levels of drilling up directories with "../" without success. This works just fine for other relative references, like the @font-face lines in the website css, but for whatever reason fails when loading it with Font.register.

i have same problem in next 14.2.3 and add font.register
do you find any solotion?

**Comment by moitorrijos** [comment]
I am having the same issue. Currently running nextjs 14.2.5 and react-pdf/renderer 3.4.4. When I use the I get the following error in the console.
![CleanShot 2024-07-26 at 11 25 03](https://github.com/user-attachments/assets/dee192cd-39ad-4d50-9dab-edd6fcd93817)
![CleanShot 2024-07-26 at 11 25 32](https://github.com/user-attachments/assets/79549651-fa36-4b4d-97ee-57bf1061118a)

**Comment by TristanBeaton** [comment]
Hey everyone, I have also been having lots of trouble trying to get custom fonts working with Next.js. I have managed to get it working and just wanted to post here in case anyone finds it helpful. I am using Next.js 14.2.4.

In the root project folder I created a folder called `assets/fonts` which I have put all my font files into. I have then added the `copy-webpack-plugin` to my `next.config.js` file which copies the fonts to the build folder.

```
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

const nextConfig = {

  /* ... other config stuff ...*/
  
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins.push(
        new CopyWebpackPlugin({
          patterns: [
            {
              from: path.resolve(__dirname, 'assets/fonts'),
              to: path.resolve(__dirname, '.next/server/fonts'),
            },
          ],
        }),
      );
    }
    return config;
  },
};
  ```
  
Then I was able to register my fonts using `path.resolve` 
  ```
  import path from 'path';
  import { Font } from '@react-pdf/renderer';
  
  Font.register({
  family: 'PlusJakartaSans',
  fonts: [
    {
      src: path.resolve(
        '.next/server/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf',
      ),
      fontWeight: 'normal',
    },
    {
      src: path.resolve(
        '.next/server/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf',
      ),
      fontWeight: 'bold',
    },
  ],
});
```

**Comment by yanuu1337** [comment]
Agreed. I'm getting a crap ton of errors because of this exact issue. 
![image](https://github.com/user-attachments/assets/66c3ea21-fab7-4c36-8173-15f7a4836015)

**Comment by ascii-husky** [comment]
Put font-file in public folder. Rename your font-file from `.ttf` to, for example, `.wtf`. Register like this: 
```
Font.register({
   family: 'Söhne',
   src: path.join(process.cwd(), 'public/soehne-buch.wtf'),
})
```
Works for me :)

**Comment by yanuu1337** [comment]
It is in the public folder though, weirdly enough Font#register is using the absolute path instead

**Comment by timB73** [comment]
> Hey everyone, I have also been having lots of trouble trying to get custom fonts working with Next.js. I have managed to get it working and just wanted to post here in case anyone finds it helpful. I am using Next.js 14.2.4.
> 
> In the root project folder I created a folder called `assets/fonts` which I have put all my font files into. I have then added the `copy-webpack-plugin` to my `next.config.js` file which copies the fonts to the build folder.
> 
> ```
> const path = require('path');
> const CopyWebpackPlugin = require('copy-webpack-plugin');
> 
> const nextConfig = {
> 
>   /* ... other config stuff ...*/
>   
>   webpack: (config, { isServer }) => {
>     if (isServer) {
>       config.plugins.push(
>         new CopyWebpackPlugin({
>           patterns: [
>             {
>               from: path.resolve(__dirname, 'assets/fonts'),
>               to: path.resolve(__dirname, '.next/server/fonts'),
>             },
>           ],
>         }),
>       );
>     }
>     return config;
>   },
> };
> ```
> 
> Then I was able to register my fonts using `path.resolve`
> 
> ```
> import path from 'path';
> import { Font } from '@react-pdf/renderer';
> 
> Font.register({
> family: 'PlusJakartaSans',
> fonts: [
>   {
>     src: path.resolve(
>       '.next/server/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf',
>     ),
>     fontWeight: 'normal',
>   },
>   {
>     src: path.resolve(
>       '.next/server/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf',
>     ),
>     fontWeight: 'bold',
>   },
> ],
> });
> ```

Did you get this working on a production deployment? It works fine locally but when I deploy on Vercel I get this error:

Error: ENOENT: no such file or directory, open '/var/task/client/.next/server/fonts/Arial/arial-unicode-ms.ttf'

**Comment by TristanBeaton** [comment]
I am not familiar with Vercel, but we have this working in a production environment on ECS. 

We use the Dockerfile provided by Next.js [here](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile). We did have to add this line to line 58, so that the docker image would copy over the files.
`COPY --from=builder --chown=nextjs:nodejs /app/.next/server/fonts ./.next/server/fonts`

One thing I have seen from reading the Next.js docs in the past, is that they expect that static assets are hosted by a CDN. This doesn't really matter in this case since we just need the fonts available on the server, but it means that Next.js only picks up the files it cares about. You may have to look into how to ensure these files are copied to your Vercel deployment.

**Comment by timB73** [comment]
Thanks for the reply @TristanBeaton 
I was finally able to get a solution working with this:

```
Font.register({
  family: 'Arial',
  fonts: [
    {
      src: path.join(process.cwd(), 'public/fonts/Arial/arial-unicode-ms.ttf'),
      fontWeight: 400
    },
    {
      src: path.join(process.cwd(), 'public/fonts/Arial/Arial-Unicode-Bold.ttf'),
      fontWeight: 'bold'
    },
    {
      src: path.join(process.cwd(), 'public/fonts/Arial/Arial-Unicode-Italic.ttf'),
      fontStyle: 'italic'
    }
  ]
});
```

I think the reason I couldn't just access the public folder with the usual leading slash like others are doing is because I am doing this in a route handler and it seems using this is the only way to access the public folder from here.

**Comment by Vanals** [comment]
It does work for me if I am doing client side rendering with PDFViewer, but if I am building the pdf in the server side

like

Server
```
  const buffer = await renderToBuffer(<ApprenticeshipReviewPDF />);
  ```
  
  Client:
  
       <iframe
        src={`data:application/pdf;base64,${pdfBase64}`}
        width="100%"
        height="600px"
      />
      
  
  It then breaks.. I get no useful error but. assume is due to the font not being loaded? as break when the font is required in the stylesheet

**Comment by MariuzM** [comment]
with Nextjs 15 there is issue I'm getting `TypeError: dataUrl.split is not a function`

**Comment by MariuzM** [comment]
> import localFont from 'next/font/local'
> const font = localFont({ src: './font.ttf' })

I don’t understand how this works for you because i get these errors 

<img width="863" alt="Image" src="https://github.com/user-attachments/assets/48f2f862-b3ac-46e9-a561-de6119333634" />

**Comment by MariuzM** [comment]
Ok this looks like it worked 

<img width="1310" alt="Image" src="https://github.com/user-attachments/assets/5ab1951d-bd53-4077-816c-791ff6f04fcf" />

**Comment by PeterMarinov** [comment]
When used in api route or server components, pointing the process root solved the issue `process.cwd()`. 

Example:
```tsx
Font.register({
  family: "Roboto-Bold",
  fonts: [
    {
      src: `${process.cwd()}/public/fonts/Roboto-Bold.ttf`,
      fontWeight: "bold",
      fontStyle: "normal",
    },
  ],
});
```

Try this and let's see if it works
