### ISSUE TITLE
Special character (U+2265) symbol issue with fonts

### ISSUE THREAD

**Issue by leonace924** [diegomura/react-pdf#2227]
**OS**: Windows 11
**React-pdf version**: 3.1.6

Description:
Hello, my problem is font glyph doesn't work, like this symbol
do you have any solution for this?
I used `Helvetica Neue` font, it works fine on local but doesn't work on pdf even I import the same font

![image](https://user-images.githubusercontent.com/42954461/223176925-5a8265d2-e4c8-4e40-8746-36e15c4dae3e.png)

Could you give me the solution for this?

Thank you

**Comment by leonace924** [comment]
This shows same on playground too - https://react-pdf.org/repl

![image](https://user-images.githubusercontent.com/42954461/223179531-ec580fd5-1699-4b0d-9cc4-4bbdfbcc307b.png)

**Comment by leonace924** [comment]
@diegomura , could you give me advice on this issue?
I am trying to launch one product, but this is the only issue
Thank you
Best,

**Comment by leonbloy** [comment]
In the repl, at least, you are using Oswald font, which does not support that unicode character (U+2265)

https://fonts.google.com/specimen/Oswald?preview.text=%E2%89%A5&preview.text_type=custom

**Comment by leonace924** [comment]
@leonbloy , thanks for your checking my issue

I am using `Helvetica Neue` font, it's working well on the Next.js page, but it doesn't on react-pdf

Do you know why that happens?

**Comment by leonace924** [comment]
@jeetiss , could you have a look at this one, please?
Appreciate it

**Comment by jeetiss** [comment]
> I am using Helvetica Neue font, it's working well on the Next.js page, but it doesn't on react-pdf

browser fallback to the next font from `font-family` if current doesn't have a glyph for the symbol. react-pdf doesn't support font fallback, so you have to control this manually. 

i can't find any font on google fonts that support your symbol. You have to find that and render this symbol with it like that

[general idea](https://react-pdf-repl.vercel.app/?cp_code=JYWwDg9gTgLgBAbzgFQKYA8YBo4AUCGA5qjgCIQDGAriKgHbZwBiEDcAvnAGZQQhwAiAAJRU-CjAC0YACZcA9KLozUoqAIDcAKC0sGAOlGFgAZxiqAFAi1xu-EMAA2ATwBcggPImA7vkcyBLBs4EygKdwEACxgYMBNXeXkuVhgTfUIzfBhgCn0KPnkTeQgfPxl5ADcARgBmeQBNAH1kAGkANQA2CAAOAHUICoAjAFUZGpBGgA0ATnwAQTn9GK5ArXYASm1dFMNUYzNLa1sueyc3TzB6OABlfDoTVdtQ8MFo2PjE5IY0jJgsnLyBSKEEu9zuRWqAHZ5LQQN16vgAOImKoAJg6AFlgAAtMAAITmkmGTDa2IADKgljAVkENlsMJBYHAVCcqI54BZ1nAALwAPjgFmCAB5yNRaAxecFbEKCMQpbYQsAAF6obkIADaNTJZIAuux5U8YM5HKqEEg_MBCHQAJLmEDxQQUejmdQ4ABWVDMwC4zgAwilnREnQxVIE4GB8DIZMA6IR3FUyRx9Qq4JKU9K0JgQkaTWqkF8YExTi4Il5fP4BEm0-nbJFUI5HBA4ELM_AzMbTfmUkWHCWLldbvdK-x2LyANQToXyVv87zQfwG5vTjAwavS-Sy1DVqeimjOyWbLRAA&modules=true)

**Comment by leonace924** [comment]
@jeetiss , thank you for your recommendation

I resolved with `Arial` font for those two glyph issue

Now I close this ticket
