### ISSUE TITLE
Missing font-manager module

### ISSUE THREAD

**Issue by bkoltai** [diegomura/react-pdf#223]
**OS:**
Mac OS 10.13.4

**React-pdf version:**
0.7.7-7

**yarn version**
1.6.0

**Description:**
I'm seeing the following error at compile time:
```
./node_modules/@react-pdf/textkit/dist/layout/FontSubstitutionEngine.js
Module not found: Can't resolve 'font-manager' in '<project>/node_modules/@react-pdf/textkit/dist/layout'
```

**Comment by bkoltai** [comment]
I'm trying to use this on a client, with `@react-pdf/dom`

**Comment by diegomura** [comment]
Seems fair. ‘font-manager’ it’s not built for working on the dom. that version is yet experimental (has a beta tag) and shouldn’t be used yet. It got installed by default or you just installed manually? Please use the last stable version, which is 0.7.6
