### ISSUE TITLE
Missing props types on Document element

### ISSUE THREAD

**Issue by x-Wawa** [diegomura/react-pdf#2231]
**Describe the bug**
When we add the props `pageMode` or `pageLayout` to the `<Document />` element using typescript we got an error

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create a Document
2. Add the `pageMode` or `pageLayout` prop to the `<Document />` element
3. run the app

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_
replication:
replace any `<Document />` element by the following open tag:
```javascript
<Document pageMode="fullScreen" pageLayout="twoPageRight">
```

**Expected behavior**
Should not return an error

**Screenshots**
![image](https://user-images.githubusercontent.com/66263633/223536051-612bfb87-8ff6-4330-9073-a6adb87aa071.png)
![image](https://user-images.githubusercontent.com/66263633/223536318-ad538f30-17e0-4655-973b-66cfcff9d714.png)
![image](https://user-images.githubusercontent.com/66263633/223536451-a967ba05-b98a-44ec-b6b0-a7faf1f9232b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox developer edition
 - React-pdf version: "^3.1.6"

**Comment by robbeman** [comment]
Not sure if related, but I see the document props do not contain the `style` prop as well.

I use this prop to set the body font globally like this:
```
<Document style={{ fontFamily: 'Poppins' }}>
```

This seems to work, but typescript does not allow it.
