### ISSUE TITLE
Module not found: Can't resolve '@swc/helpers/src/_ts_decorate.mjs'

### ISSUE THREAD

**Issue by TorrCod** [diegomura/react-pdf#2239]
# Failed to compile
![image](https://user-images.githubusercontent.com/105502630/224403587-caee2d84-e945-4838-b423-bd6a9c4bd64b.png)

After i install the package in next typescript and import the package and save it in my component it return me a module not found

```
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import React from "react";

const styles = StyleSheet.create({
  page: {
    flexDirection: "row",
    backgroundColor: "#E4E4E4",
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
});

const PdfDOcs = () => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text>Section #1</Text>
        </View>
        <View style={styles.section}>
          <Text>Section #2</Text>
        </View>
      </Page>
    </Document>
  );
};

export default PdfDOcs;
```

**Comment by TorrCod** [comment]
oh i just reintall the package and its works

**Comment by TorrCod** [comment]
## I solve the problem
im using it incorrectly

**Comment by joacub** [comment]
> ## I solve the problem
> im using it incorrectly

how do you solve it ?

**Comment by phoenixcoded20** [comment]
> 

If you are solving something, its better to share resolution so that the community can help from that. if possible, please share the resolution.

**Comment by joacub** [comment]
> If you are solving something, its better to share resolution so that the community can help from that. if possible, please share the resolution.

There is no solution, there is a uf so no solution possible. You can fix by your self following my approach in the meantime next fix by them self

https://github.com/vercel/next.js/issues/48577

https://github.com/vercel/next.js/discussions/48110#discussioncomment-5702542

**Comment by jobajuba** [comment]
You don't need @react-pdf/renderer. Use iFrame to render, it does the same job. 
Example: "<iframe
          src={pdfPath}
          title={pdfName}
          width="100%"
          height="550px"
          style={{ border: 'none' }}
          seamless
        />"
