### ISSUE TITLE
PDFViewer not working in firefox developer edition browser?

### ISSUE THREAD

**Issue by MezianeKhalil** [diegomura/react-pdf#2246]
i take same code from documentaion its work in chrome brawoser but firefox developer edition is not render pdf
from devtools:
![image](https://user-images.githubusercontent.com/67861260/224695128-b1d830b0-3fa6-40b3-8c33-9b43e32673e2.png)

**Comment by x-Wawa** [comment]
Hey can you share your code because it work well for me:

see an example:
![image](https://user-images.githubusercontent.com/66263633/224816103-79004915-bff1-4fbe-bfb5-f340d9c3167d.png)

**Comment by MezianeKhalil** [comment]
> 

i take same code of doc nothing change pdf is download by default but nothing in preveiw and i use Render in DOM option

**Comment by MezianeKhalil** [comment]
i have been use jspdf and pdf-lib always same issue with firefox  but when use object tag  instead of use iframe its work fine
```
// generate PDF
function generatePdf () {
        const doc = new JsPDF()
        doc.autoTable({
            head: [tableHeaders],
            body: tableData
        })
        return doc.output('datauristring')
    }
    const pdfDataUrl = generatePdf()

// return 
<object
      data={pdfDataUrl}
      type="application/pdf"
      width='100%'
      height='450px'
      style={{
          width: '100%',
          maxHeight: '100%'
      }}
  >
    <div>No online PDF viewer installed</div>
</object>
```
