### ISSUE TITLE
textAlign issue with flex

### ISSUE THREAD

**Issue by notzippy** [diegomura/react-pdf#2253]
**Describe the bug**
The text align does not appear to work when used with flexGrow:1

**To Reproduce**
[Sample](https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a06180076a0736402e1918c0046d58006b2e144005730004c0308844202bf00e4504005b5a21d4c00be006959c64c0a004b70fd1803314003c0389480eebc0233198a055a8c3abb81159d3aaf88b8a48cbc92806f3a90a234b2044c1d13940020a215971806853e41143a6e851715a14c0033000311b32180250037333328242c1c8830060c3d19800f0008bf74b6b21814001f199b08c002b7321c158017b23a001136400b2edc2e0a3a23020a0429270f2182db23cc08c01a95b23b89de39c3b398d59512c361aaec3cbb5f350f20500249d1b4107e2eda0542830008e0e128824525922994aa44bb1aa6275219ee8b47801215eef4fa5c768c5fb215c1e6f2f9fc04a0884c2694896262b8f881292295e4659939284d5d4c52e2940c648793ca923000a84ae65800108c165a518243f260641c846007a75564954f6a59ade1f6b4abed74d3832992c902787c7e7c60582a1709f3a238b8afb129262181d2994951a8a2532919c9ca9565be6dadd4260d529379ad38eb62db9d05e79db69259a47cbe674663999ff407596c305067a3186985c2112de4490d118a8b63627884ba889601262a2985cacbbbeb5e71b93d6c9f424b901b160e05a1d1f2552d1896e4e3413d626a72999fe7a106ed0c1c01922266e5503cc6ba73022f97dfe6e2c53cdab1e09573426600a6199e6661da4e800251a12c658c6000c5482a1e4640287a0fa600a0a0000)
    
Sample document
    
      <Document>
        <Page size="A4" style={styles.page}>
          <View style={{flexDirection: "row", alignItems: "stretch", backgroundColor:'pink'}}>
      	    <View style={{flexGrow:1, color: 'white', backgroundColor:'blue', textAlign: 'right' }}>
        	    <Text>SB right aligned</Text>
      	    </View>
      	    <View style={{flexGrow:1, color: 'white', backgroundColor:'green', textAlign: 'right' }}>
        	    <Text>SB right aligned</Text>
      	    </View>
          </View>
          <View style={{flexDirection: "row", alignItems: "stretch", backgroundColor:'pink'}}>
      	    <View style={{flexGrow:1, color: 'white', backgroundColor:'blue', textAlign: 'right' }}>
        	    <Text>I am on the right</Text>
      	    </View>
          </View>
        </Page>
      </Document>

Does not align the `SB right aligned` text to the right

**Expected behavior**
I expected the text to be aligned to the right

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser Chrome
 - React-pdf version 3.1.8

**Comment by leonace924** [comment]
@notzippy , please use the `flex: 1` instead of `flexGrow`

`<Document>
    <Page size="A4" style={styles.page}>
      <View style={{flexDirection: "row", alignItems: "stretch", backgroundColor:'pink'}}>
      	<View style={{flex:1, color: 'white', backgroundColor:'blue', textAlign: 'right' }}>
        	<Text>SB right aligned</Text>
      	</View>
      	<View style={{flex:1, color: 'white', backgroundColor:'green', textAlign: 'right' }}>
        	<Text>SB right aligned</Text>
      	</View>
      </View>
      <View style={{flexDirection: "row", alignItems: "stretch", backgroundColor:'pink'}}>
      	<View style={{flexGrow:1, color: 'white', backgroundColor:'blue', textAlign: 'right' }}>
        	<Text>I am on the right</Text>
      	</View>
      </View>
    </Page>
  </Document>`
  
  Here are the code snippet and screenshot
  
![image](https://user-images.githubusercontent.com/42954461/225717818-831cae53-c1a6-4dd1-a73a-730a0fad3e90.png)

Hope this answeres your question

**Comment by jeetiss** [comment]
I think this bug is related to https://github.com/diegomura/react-pdf/issues/2182

yoga layout failed to calculate `flexBasis` on the text node, so text layout can't apply `text-align` after but when `flexBasis` is specified it works
