### ISSUE TITLE
FontWeight Not Working

### ISSUE THREAD

**Issue by chea-young** [diegomura/react-pdf#2259]
**Describe the bug**
I tried to apply `fontWeight: bold` , but it isn't working.
used font: https://fonts.gstatic.com/s/notosansjp/v42/-F62fjtqLzI2JPCgQBnw7HFowAIO2lZ9hg.otf
code
```
pdf_table_style1: {
    backgroundColor: '#ffffff',
    alignItems:"center",
    textAlign:"center",
    fontWeight: "bold",
  },
pdf_table_style2: {
    backgroundColor: '#ffffff',
    alignItems:"center",
    textAlign:"center",
    fontWeight: "700",
  }
```

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/repl?example=font-register
2. See error

**Desktop (please complete the following information):**
 - OS: Window
 - Browser chrome
 - React-pdf version "@react-pdf/renderer": "^3.0.0"

**Comment by chea-young** [comment]
Resolved

Reference: https://snyk.io/advisor/npm-package/@react-pdf/renderer/functions/@react-pdf%2Frenderer.Font.register

**Comment by vasco3** [comment]
does fontWeight works with the default fonts without having to register?

**Comment by chea-young** [comment]
@vasco3 
No, If you want to use fontWeight.
You register fontWeight, too.

Example: This code was written to use the Bold type and the regular type Font.
```
import NotoSansDefaultBold from '../../../font/default/NotoSansKR-Bold.otf'

import NotoSansJPBold from '../../../font/jp/NotoSansJP-Bold.otf'

import NotoSansZHBold from '../../../font/zh/NotoSansSC-Bold.otf'

const langCode = getLanguageSetting();
let fontSrc = "";
let fontBoldSrc = NotoSansDefaultBold;

if (langCode == "jp-JP") {
  fontSrc = "https://fonts.gstatic.com/s/notosansjp/v42/-F62fjtqLzI2JPCgQBnw7HFowAIO2lZ9hg.otf";
  fontBoldSrc = NotoSansJPBold;
}
else if (langCode == "zh-CH") {
  fontSrc = "https://fonts.gstatic.com/s/notosanssc/v26/k3kXo84MPvpLmixcA63oeALhL4iJ-Q7m8w.otf";
  fontBoldSrc = NotoSansZHBold;
}
else {
  fontSrc = "https://fonts.gstatic.com/s/notosanskr/v27/PbykFmXiEBPT4ITbgNA5Cgm20HTs4JMMuA.otf";
}

Font.register({ family: "Noto Sans", fonts:[
  {src: fontSrc },
  {src: fontBoldSrc},
]},);

```
