### ISSUE TITLE
SVG rotate uses 0,0 as origin when another origin is specified

### ISSUE THREAD

**Issue by Kinna** [diegomura/react-pdf#2275]
**Describe the bug**
The rotate transformation on SVG uses 0,0 as the origin, even when another origin is specified. 

**To Reproduce**
Steps to reproduce the behavior including code snippet:
1. Go to [react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a000efc3005f769d395006a483007718d3c54a8a231c8026009c7aea460faa8eeb9f3aa019401b9f272f7e54392123e7e7eb6e6500016005c300044008c00acc08cb10034c1212e1118487c11503109c9a919597ecaca99e5301e3aba0042202892b100b489301d30f1000c3dbdb15535ea6a23ea54004a18c050d5232ded89b1f33542d84b2be32e61911b7d5bdbea397905fb83abe5d0962000d61800ea48e11192bdb2bd89c3479cd777e2b1001188878c05ba1c7e30001992044220dae822484c043b6007a7625cfc68b44f450f1030011c103c4b161e4200832290e00c398603c582f4d2bd2c6f8a63339a43288b0bb7260eb589f3b9bb57825514713be4a0fb0976cfef7278bcde1f2f9b2fc30b846c40d67b060e5e31022980c8c17bd96eae7062c896f50e2609374232cc0c9b820c0f4f3060a13c04088992cdb469a6b320fa91600260348d0551b0e71451b38ff2a56758b27b99af850244087d7c72846d069a5500166fa42a0ba88142758c0d8dca0cebc297120468d65adf1fb5b822203f7d31bced77f63d3000331a52730404216043cc04047eefa733fa766806078e678c7343fcc8c77cab1a3d6513e9d3c8553328bc17a1b0ecd816997bf02a0164f30bf7c6fa55ec24ef4f82b1f8ab1e1205ad2c7ad6205c3016d1229ca776dbb3188e20ca83453c3e190f28d0ed0f42c2d0de004318d0ba0186615876008001b86d3214048160430975c0dc130c45ec300c0a0591803259b208604500418804ce0a1310501a090325661a4c0229405cd18301d21f1015056e3e0dd0f40061100441d48a00188a1532ccd53d4451cc730ec3e08a789641282cce0ac9b3ec268a028040461ecc725267394328602b06c5b2449f1c48c050189e220b281e0443c8c0001253046020052584c12c67328000ac1068090284843d3582cb32f2a72a0b02b21946a26d69941280b81a00031590c90f4304b0f02a110541d02c03106a8000)
2. The red border rectangle should not be displayed over the blue rectangle, since the rotate origins are different

**Expected behavior**
In the code above I added a blue rectangle in the SVG and rotated it 45 degrees without setting an origin, which defaults to 0,0. I also added a rectangle (red border) where the rotate origin was set, but the rotated rectangle is displayed on top of the blue rectangle. I would expect the red border rectangle to rotate around the specified origin instead of 0,0.

**Screenshots**
See steps to reproduce

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:  chrome
 - React-pdf version: 3.1.8

**Comment by MitchMilton** [comment]
I have also experience this issue when working with recharts pdf and rotating the angle of the <LabelList> component

**Comment by diegomura** [comment]
> The red border rectangle should not be displayed over the blue rectangle, since the rotate origins are different

It is not, anymore at least

<img width="475" alt="Screenshot 2024-11-17 at 18 44 30" src="https://github.com/user-attachments/assets/e813fe90-4d05-4ebd-8e6c-7643a5363c6a">
