### ISSUE TITLE
Can't import the `style` interface

### ISSUE THREAD

**Issue by shanike** [diegomura/react-pdf#2291]
**Describe the bug**
When using **components of the library** there's type-intellisense on the `style` prop. 
**But** I would like to have access to the **`style` interface** **in my own components**. 
The components will accept a `style` prop with the correct `style` type. 

**Currently**, sadly I don't seen to have access to the **`style` interface**. Therefore in the screenshot below it's of type `any` 

![image](https://user-images.githubusercontent.com/56911506/236665823-49df2684-c2c2-492c-92d0-b10772179543.png)

Thank you!

**Comment by RollingTom** [comment]
Hi,

To access the style interface in your own components, you can import it from the "@react-pdf/types" package. Here's an example of how you can do that:

```
import { Style } from "@react-pdf/types";

interface MyComponentProps {
  style: Style;
}

const MyComponent: React.FC<MyComponentProps> = ({ style }) => {
  // Use the style object here
  return (
    <div style={style}>
      {/* your component code */}
    </div>
  );
};

export default MyComponent;
```

By importing the "Style" interface from "@react-pdf/types" and defining it as the type of the "style" prop in your component, you should have access to the correct style type. This will provide type-intellisense and ensure type safety for your component's style prop.

Hope this helps!
