### ISSUE TITLE
Cannot correctly render ō character

### ISSUE THREAD

**Issue by Cyklan** [diegomura/react-pdf#2305]
**Describe the bug**
Using any font, I can't get the character `ō` to render correctly.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to [this repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659da74e5400a8614b0019aa0c004dd804845a302ca0006b1e48e6a98009440f391d85500f4e32509167780ebe6e8366add8100dc64c9e8c3d8142e1a0031003a002716390c30bc2a4454742c33620f32200)

**Expected behavior**
I expect to correctly see this character

**Screenshots**
![image](https://github.com/diegomura/react-pdf/assets/37187056/ee73b319-40b9-4483-ba72-2b661c01c90b)

**Desktop (please complete the following information):**
 - OS: Windows, MacOS
 - Browser: Chrome, Firefox (assumingly others)
 - React-pdf version 3.6.0

**Comment by diegomura** [comment]
You need a custom font for special chars. Default font contains just a limited set of unicode characters

**Comment by Cyklan** [comment]
Thanks for the swift response. I no longer work at the job where I needed this, but if I recall correctly, we were using a custom font where this character was, in fact, supported.
