### ISSUE TITLE
Nested Text components don't inherit backgroundColor

### ISSUE THREAD

**Issue by carlosbaraza** [diegomura/react-pdf#2316]
Nested Text components don't inherit backgroundColor. The expected behaviour is that every text node under a text node with a background should inherit it unless overwritten.

# Example issue

```
const styles = StyleSheet.create({
  body: {
  	margin: 50,
  },
  highlight: {
    backgroundColor: 'tomato',
  }
});


const doc = (
  <Document>
    <Page size="A4">
     <View style={styles.body}>
       <Text>
         Single line text with 
         <Text style={styles.highlight}>inline text highlighted</Text> 
         Again Black Text
       </Text>
       
       <Text>
         Nested Text with
         <Text style={styles.highlight}>
           inline
           {/* THE BACKGROUND COLOR OF THE HIGHLIGHT SHOULD BE INHERITED */}
           <Text>text where highlighting disappears</Text>
           highlighted
         </Text> 
         in a long, long, long, long, long, long, long, long multi-line paragraph
       </Text>
      </View>
    </Page>
  </Document>
);

ReactPDF.render(doc);
```

# Screenshot
![Screenshot 2023-05-31 at 15 22 37](https://github.com/diegomura/react-pdf/assets/1270425/23aa1f36-9ceb-47ba-a42c-d86d22516b5e)

# Reproduction
https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618023100137802e1859b0090016da8500e6012cc3f00ac001800d2b18017c55b0252241443a0947e82d876ac0035848a2002b982e01844221015f80722820c778f9bd598d4012801b99823412160b841803061e95400780044e36c4590c0a000f954d9920015a82590e0a400bd91d00088010400596bf34d0a00d4a59001dce17051d118105021493878d55adb0a005590003cf20ba7b064245061f4c1cae91661baa4a0086197a792e6f7866a87fb5149b575f574a12664b67617601ef40ce8b99200f4173c89c56a67a849a832180008510e60b0c181a7429033e53698a260e774562d80039541fc919f7da1c0878ec702fa784195d46df27a192694b61bc64c85640801002a244002400a2b0faa3800d200710012801e400aaf8d48c11c32800c8caa53019400c405c2fe4012425fcd551bf9336c3f3e5aaa54c38506fc50aa50699a0a953c805a8b938c5ae576b06e910a830466fcd6302e14820d400038c66814082038118b04860c4cbfa5393e8d05a7a1d44db80244a22d804b658aeb9cba5ead578bb586e5660225b220a052002d3bc6031f129428b18a58273be946033a3d54e024a6529a03d2c04cb6496610894a68c02811552dad21501cc80a3d162c035d00000

**Comment by danomatic** [comment]
I just found this issue as well. Here is my simple recreation:

```jsx
<View>
  <Text>
    <Text
      style={[
        {
          margin: '0',
        },
        {
          backgroundColor: '#ffff00',
        },
      ]}
    >
      <Text
        style={[
          {
            color: 'blue',
          },
          {
            margin: '0',
          },
        ]}
      >
        Blue text
      </Text>
    </Text>
  </Text>
</View>
```
