### ISSUE TITLE
Unable to install when using with react-boilerplate

### ISSUE THREAD

**Issue by lalithnarayan** [diegomura/react-pdf#232]
**OS:**
Mac OS
**React-pdf version:**
^0.7.6

**Description:**
Hi thanks for this wonderful library I was trying to add to a project based on [https://github.com/react-boilerplate/react-boilerplate](React Boilerplate)
I followed the instructions as stated in the documentation but couldn't get it working.
It throws errors (Attaching the screenshot)
![screen shot 2018-05-16 at 6 01 50 am](https://user-images.githubusercontent.com/11024780/40090322-bfc5c828-58ce-11e8-8a18-c242ff269823.png)

Hope you can help me.

**Comment by EdoAPP** [comment]
Same for me! @lalithnarayan Could you solve the problem?

**Comment by diegomura** [comment]
Please try installing the last `v1.0.0-alpha.6`.
It's a bit experimental, but test worked pretty well

**Comment by diegomura** [comment]
I tested `v1.0.0-alpha.7` using the last version of `react-boilerplate` and worked without any special setup
