### ISSUE TITLE
Console error: Attempted import error: 'create' is not exported from 'fontkit' (imported as 'fontkit')

### ISSUE THREAD

**Issue by medardm** [diegomura/react-pdf#2324]
There is an error regarding [fontkit](https://www.npmjs.com/package/@react-pdf/fontkit) with the following package
- [pdfkit](https://www.npmjs.com/package/@react-pdf/pdfkit) 

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Use the following versions of node, npm, yarn and react in your project (I haven't tried on other versions yet)

```
   - npm: 8.11.0
   - node: v16.15.1
   - yarn: 1.22.19
   - react: ^17.0.1

```
2. `yarn start` and observe

**Expected behavior**
There shouldn't be any error regarding [fontkit](https://www.npmjs.com/package/@react-pdf/fontkit) regardless the version

**Screenshots**
<img width="711" alt="image" src="https://github.com/diegomura/react-pdf/assets/20562573/2627510d-fadb-4ab0-ab79-6a3bc1c10af6">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge
 - React-pdf version : ^3.1.11

**Comment by aimeetacchi** [comment]
I'm getting this version and I haven't even upgraded! I was on version - 2.0.21 could someone fix this please. I shouldn't have to install extra packages. I didn't need to before

**Comment by jeetiss** [comment]
could you please create a reproduction or send `lock` file to reproduce the bug?

**Comment by medardm** [comment]
> +1, same error with :
> 
> `npm: 7.20.3 node: 16.6.2 react: 17.0.2 `
> 
> _There are some solutions are : #2015 but none of them worked for me._
> 
> **Update** : [#2015 (comment)](https://github.com/diegomura/react-pdf/issues/2015#issuecomment-124573392) worked for me. I add to upgrade npm to the latest version so that the overrides could be applied (feature introduced in NPM [v8.3](https://github.com/npm/cli/releases/tag/v8.3.0)).
> 
> @medardm, you could try that solution (upgrading npm to 8.3 and `overrides (npm)` @react-pdf/font and @react-pdf/pdfkit in your package.json). If you are using yarn, please refer to that comment : [#2015 (comment)](https://github.com/diegomura/react-pdf/issues/2015#issuecomment-1246286312) and replace `overrides` by `resolutions`

Hi thank you so much it worked!

**Comment by biel-fyq** [comment]
+1
npm: 9.6.5 node: v16.17.0 react: 18.0.0
