### ISSUE TITLE
render prop doesnt allow array map logic

### ISSUE THREAD

**Issue by taipignas** [diegomura/react-pdf#2328]
i would like to put complex components inside render prop because i want to implement dynamic table row cutting, but i noticed immediately that js map function doesnt work.

delete the .map code to work (line 14)
https://react-pdf.org/repl?code=3187b0760ce02e00460ae05b011814c04e04177a08604f1805e1806d009801a180666a01601740286744960115e012c00f105153118002802531007c6398c1800780088860495182852e7cc500157007361d1f001b5444037a98b1001d3210004df005f6dbb742802aa8fac2da58d9439aa038005aa2e33861b8c0019bf2a33a797ae801f8c0030ba3450b38c003b8f14044c1e6e3014002d0003b3824c064e9782803d1f805a5b57606845b59043942945878a980c370f0015a0b0ac4c19ae0c002cae1830046e075f4f779f4c1050c0f87dae3c19483a079acf21bc2a198c12f646001ba6d0841eff96ab5bc00351e2a08a150d2c5d0d6511586075232a0007248343a0606e4911064a2407a51420b071cced638720aa006b433a040f030338005c3000391e59ccc8c478f1f8c53ec0092ccc40c1c0664207c78101e3202c301e14c5c85047182000423fb75b9f8ab02050186c1e1f0f6442e0eaa23e36379ff2900a8522b144aa532b970b9c8ac46abd55a711b935de76a128a077937a60ed20e5a02c4b0a9cc20e257235171087d23030b87c651baf4350a0825c1980cca8c56271be800180048ac19c4edd43302aee6a0f9c2f84dc65ee486927c14a860e1d56da43a2a352203400f1001b958003170141ec794304a84e8584e812b8440f1454ce6401e420457cfb3283a083a1807b88940a07508033daed04bce1c86682e146c07b28110ed083b42011e27bb41f0008c343b40026800fa3e000d2408006c200001c003a8801f320002ab3834220304001a00272e098260f62de09332cc262d39b0e0340519d822000ca671b1512a00bb0095108ebbc84e2b84c95880822ae9ca860f8201d44c8d0002b19e5e049ce1490010a08b9a204c9214a789311a96021800048dc3c0005ef3be6f27e9f21b8ca4c0a314016289808be9a1b1966a04cb90f4239f2108012606603c601eec038e1833201624f38ce5b8eef81ee87b1e663b23a0393a25cd73a06e5781e5405e4593e4c060550809055008561445517a031602c6ba0cb9809a6de200e9303d00003239597c8103c0c8339ae4c062415f3b15a5581a86c5cd6b54cb95b16150976ebb8b2a949eb47d98e555f96e80b5ca4b45593679de52dfe655ff0d5863852caccf03403c024f8235675406b5257b8f83c18e100d40012a759b0ed18a397f622077c847580408605f8d9655d9876e02d5ca667a0967596612d3d5f599639510c4183437179d2549df35a3ad7b5da6f904d78556ddf773291668d16c5a0198371eed4aa06f7f58e4d65999375101a50f0e01eeb8320100806615ca83bdba215d3553809381d57534233ba058091404c9ebf2163860dec6ec5cce85775d51cc355cc2bbccb2fce0b84dd153ab080f44d51e84a0ce8ba42182880a0cc021087da7b40000

**Comment by diegomura** [comment]
Fixed in latest versions!
