### ISSUE TITLE
Document name, it is not changed at the time of download even with the title defined in the pdf viewer

### ISSUE THREAD

**Issue by BrScoti** [diegomura/react-pdf#2332]
**Describe the bug**
Even passing the title parameter to the document component, when I download the file via the toolbar the name is not what it should be

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Use PDFViewer;
2. Set a title for the Document;
3. Download from the toolbar;

**Comment by BernardoQuina** [comment]
Did you find a solution?

**Comment by diegomura** [comment]
This is a limitation of chrome PDF render ui, not an issue of this lib. There's no way I can change that name as chrome takes it from the iframe blob url. If you need extra customization you can do something like what we do on our [site](https://github.com/diegomura/react-pdf-site)
