### ISSUE TITLE
Unable to load external image due to CORS issue  No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Nutriadmin** [diegomura/react-pdf#2340]
**Describe the bug**
I need to load an image hosted in an external domain I have no access to. The image loads fine in my HTML using an `img` tag, but when I try to load it in react-pdf I get the following error

`Access to XMLHttpRequest at 'https://spoonacular.com/recipeImages/604524-556x370.jpg' from origin 'https://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

<img width="506" alt="Screenshot 2023-06-20 at 08 27 01" src="https://github.com/diegomura/react-pdf/assets/28564596/e88f297e-3658-4750-ac0c-3d026702727b">

**To Reproduce**
Just try to render:
`<Image src="https://spoonacular.com/recipeImages/604524-556x370.jpg" />`

You can load the image by copying the url in your web browser on a new tab. You can also load the image with a regular HTML `img` tag, but when using the `Image` tag from `react-pdf` it won't load due to CORS.

I've tried the no-cache suggestions in #766 and other suggestions in the issues section, but I haven't found a solution.

Ultimately, this image is hosted on an external server I have no access to, so I can't change the CORS settings in the server. I don't really understand the mechanism that react-pdf uses to load the image and how that would be different from a regular HTML tag.

Is there a way to circumvent the problem? I've thought of using javascript to download the images, make them into base64, then replace the url for the corresponding base64 string for react-pdf, but not sure how to do this exactly and maybe there is a better solution? 

Any help would be appreciated,

**Comment by v1shant** [comment]
You can add a dummy parameter like url + "?not-from-cache-please";
which will turn out to `<Image src="https://spoonacular.com/recipeImages/604524-556x370.jpg?not-from-cache-please"/>`
I hope it works

**Comment by Nutriadmin** [comment]
> You can add a dummy parameter like url + "?not-from-cache-please"; which will turn out to `<Image src="https://spoonacular.com/recipeImages/604524-556x370.jpg?not-from-cache-please"/>` I hope it works

Thanks, I've tried that but it doesn't work. I think this solution works if the remote host is configured to allow CORS, but in this case they are blocking the request, so even if you bypass the cache it won't load.

I guess my question is, how can I load the image like the browser does (ignoring CORS, that's why it works with an `img` tag) then embed that image in the PDF? Anything that uses the `fetch` API or javascript will be blocked by CORS as far as I understand

**Comment by Nutriadmin** [comment]
I'm also thinking of making my code download all these images, then upload copies to my own server so that I can control CORS, but that would be such a brute force approach and would have to do it for thousands of images. There must be a better way

**Comment by Nutriadmin** [comment]
OMG - after spending hours and hours trying to fix this problem I figured it out with ChatGPT, you can see my chat [here](https://chat.openai.com/share/616400f0-4c71-455d-bae2-bececb3c5f80)

For anyone else struggling with this problem, essentially what I am doing is:
1. Making a POST request to my nodejs server
2. The nodeJS server loads images using axios - the server doesn't have CORS problems as CORS only impacts browsers
3. Once I get the images in the server, I convert them to base64 strings
4. I send the strings back to the browser
5. I render the base64 strings in @react-pdf instead of the url

Here are some relevant code snippets.

In the server:
```
app.post('/load-local-images', async (req, res) => {
  try {
    const fetchImagePromises = req.body.images.map(async (image) => {
      const response = await axios.get(image, {
        responseType: 'arraybuffer',
      });
      const imageBuffer = Buffer.from(response.data, 'binary');
      const base64Image = imageBuffer.toString('base64');
      const image = `data:${response.headers['content-type']};base64,${base64Image}`;
      return image;
    });

    const images = await Promise.all(fetchImagePromises);
    res.json({ images });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: 'Error fetching images' });
  }
});
```

then in the front end I render the images I receive from the server instead of the original URLs. These will be base64 strings (very long strings of encoded data, so no need to make cross-server requests) so they will render without problem.

Hope this helps anyone stuck with this problem! I've seen loads of issues referenced here

**Comment by muhamedsahin** [comment]
thanks for every thing

**Comment by ZeeshanAhmadKhalil** [comment]
> You can add a dummy parameter like url + "?not-from-cache-please"; which will turn out to `<Image src="https://spoonacular.com/recipeImages/604524-556x370.jpg?not-from-cache-please"/>` I hope it works

This solution is not working for `.pdf`

**Comment by abhipdgupta** [comment]
`        const imageElements = contentToCapture.getElementsByTagName('img');
        for (const img of imageElements) {
          const imgSrc = img.src;
          let response;
          try {
            response = await fetch(imgSrc,{cache: 'no-cache'});
          } catch (error) {
            console.error(error);
            continue;
          }
          const blob = await response.blob();
          const reader = new FileReader();
          
          await new Promise((resolve) => {
            reader.onload = () => {
              img.src = reader.result as string; // Replace src with base64 data URL
              resolve(null);
            };
            reader.readAsDataURL(blob);
          });
        }`

you can use this in your pdf creation ... rather than relying on img tag to get the image you can replace them  with base64 string.

also get rid of cors issue with cache:'no-cache' option in fetch.

hope it helps.

**Comment by hossain45** [comment]
> You can add a dummy parameter like url + "?not-from-cache-please"; which will turn out to `<Image src="https://spoonacular.com/recipeImages/604524-556x370.jpg?not-from-cache-please"/>` I hope it works

I have implemented a backend-driven solution to solve the CORS issues with images in the PDF. 

Instead of the client fetching the images directly from S3/External URLs (which triggers CORS restrictions), the backend now acts as a proxy. It fetches the image, converts it to a Base64 data URL, and sends it back to the client. Basically, we can avoid cors issue in this approach.
