### ISSUE TITLE
Image cuts off on page break

### ISSUE THREAD

**Issue by OlofMoriya** [diegomura/react-pdf#2344]
When rendering an image with the Image tag the image is cut off at page break. This seems inconsistent with image styling in general. 

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
![image](https://github.com/diegomura/react-pdf/assets/13721900/528d937f-96aa-460f-8906-4558333aa3f3)

  ```
 <View key={attachementIndex} style={[pdfStyles.fieldColumn, { width: '100%;', backgroundColor: 'red', minHeight: 500 }]} >
         <Image src={attachement.base64String} style={[pdfStyles.image]} break />
 </View>
```
```

image: {
        marginTop: 6,
        marginLeft: 3,
        marginRight: 3
    },
```

**Expected behavior**
The image should render on both pages. Alternatively there should be some example and information about the image rendering in the documentation.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - React-pdf version 2

**Comment by arelsirin1** [comment]
Hi @OlofMoriya , have you tried the wrp property?

According to the documentation (https://react-pdf.org/advanced):

```
Breakable vs. unbreakable components
We can identify two different types of components based on how they wrap:

Breakable components try to fill up the remaining space before jumping into a new page. By default, this group is composed by View, Text and Link components
Unbreakable components are indivisible, therefore if there isn't enough space for them they just get rendered in the following page. In this group by default we only find Image.

Disabling component wrapping
React-pdf also enables you to transform breakable elements into their opposite, forcing them to always render in a new page. This can be done by simply setting the prop wrap={false} to any valid component.
```

It looks like Image is unbreakable by default, but anyway, maybe you can try setting `wrap={false}` to your View Tag.

**Comment by diegomura** [comment]
Answer above is correct. Hope it helped. Will close until further updates
