### ISSUE TITLE
Changing font on client side

### ISSUE THREAD

**Issue by klis87** [diegomura/react-pdf#235]
**OS:**
Linux
**React-pdf version:**
0.7.6
**Description:**
Is it possible to somehow change font with dom binding? I have problem with polish characters, so ąćżź etc is not displayed properly. I tried `Font.register` but I guess this is only for Node usage.

**Comment by diegomura** [comment]
Hi!
You should be able to use `Font.register` client-side by providing a valid url to it. Did you try that?

**Comment by klis87** [comment]
@diegomura I tried it but I guess it wont work because some nodeJS modules are being execuded, like `request` https://github.com/diegomura/react-pdf/blob/master/packages/react-pdf/src/utils/font.js#L1

I tried to cheat a little bit with:
```js
const resp = await axios.get('https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmSU5fCRc4EsA.woff2' );

Font.register(
     'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmSU5fCRc4EsA.woff2',
     {
       family: 'Roboto',
       data: resp.data,
       loaded: true,
     }
 );
```
but this also won't work, if I remember correctly `fs` module failed - it is available only on server side.

I guess a separate `font` file should be available in `@react-pdf/dom`, with dedicated client side logic.

Btw, thank you for this package, I used `pdf-make` before but this is so much better and easier to use, thx to React components and flexbox for styling. I was even able to integrate it with `slate-html-serializer`, so you can dynamically create pdf with WYSIWIG, I really appreciate your work!

**Comment by diegomura** [comment]
Now working. You can see it in action on the [REPL](http://react-pdf.diegomura.com/repl)

**Comment by klis87** [comment]
@diegomura it still doesnt seem to work, please try ąę for instance, getting squares instead

**Comment by klis87** [comment]
@diegomura Ok, thanks, I didnt notice font load is there in REPL example.

One question though. Did it require any change in library code? As last version of package is published 2 months ago.

**Comment by diegomura** [comment]
Oh, yes.
you should start using the new `v1.0` (still in alpha). The package name changed, it's now on `@react-pdf/react-pdf`. Going to write a migration guide soon, but didn't have enough time. The README is updated. You can use it as a guide temporarily

**Comment by klis87** [comment]
@diegomura I see, we are approaching version 1.0! good news, thx again for your help and this awesome project

**Comment by Dimitreee** [comment]
Still got this.
fontkit.browser.es.js:18 Uncaught (in promise) Error: fontkit.openSync unavailable for browser build
    at Object.fontkit$1.openSync (fontkit.browser.es.js:18)
    at Object._callee$ (react-pdf.browser.es.js:239)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:290)
    at Generator.prototype.(anonymous function) [as next] (webpack:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js?:116:21)
    at step (asyncToGenerator.js:21)
    at eval (asyncToGenerator.js:39)
    at new Promise (<anonymous>)
    at new F (_export.js:43)
    at Object.eval (asyncToGenerator.js:18)


OS:
macOS Hight Sierra 10.13.3
React-pdf version:
1.0.0-alpha.13

```
Font.register("localhost:8080/fonts/HelveticaNeue/Regular.woff", { family: "Helvetica" });

```
