### ISSUE TITLE
Links are not working at react-pdf website.

### ISSUE THREAD

**Issue by upsu9** [diegomura/react-pdf#2353]
**Describe the bug**
Many "See it in action" links in Advanced concepts are not working. For example : - For Fixed Components :- 

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to "https://react-pdf.org/advanced"
2. Click on "See it in action" for "Fixed components" and "Debugging" and there are also some more links which are not working.
3. Go to next page. You will find that page does not render anything. 

![s1](https://github.com/diegomura/react-pdf/assets/65008607/2abd5ce2-3590-4f9a-9b3f-54e3354fe83a)

![s2](https://github.com/diegomura/react-pdf/assets/65008607/e6b45199-7243-4f7c-b8dd-86d9873aa66b)

**Comment by diegomura** [comment]
Fixed!
