### ISSUE TITLE
I can't use renderToBuffer, renderToStream, etc ... in server side with NextJS 13

### ISSUE THREAD

**Issue by GuysmoB** [diegomura/react-pdf#2356]
**Describe the bug**
I want to create a PDF server side with NextJS but it's impossible to use these functions.
See the screenshot for more details on errors.
I don't know if it's a misunderstanding or a bug but I can't found any help.
I tried to create a dedicated component in a different folder, with and without <FC> but it doesn't like the syntax at all.

**Expected behavior**
I should able to use renderToBuffer/Stream without errors

**Screenshots**
![image](https://github.com/diegomura/react-pdf/assets/42407006/6085f886-2980-4cbf-b472-70bf05a3d75f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Brave
 - "@react-pdf/renderer": "^3.1.12",
 - NextJS : 13.4.3

Thanks for any help :)

**Comment by GuysmoB** [comment]
Nop, this is a 'route.ts' from Nextjs 13

**Comment by caprica** [comment]
But route.ts or route.tsx?

I can use code like you posted with no errors in VS Code or with tsc when using a route.tsx file, but then I hit the runtime issue as described in #2350.

**Comment by Naddiseo** [comment]
> Nop, this is a 'route.ts' from Nextjs 13

The error you posted a screen shot of looks like using jsx in a .ts file. To use jsx in a typescript, you need the file extension to be .tsx
