### ISSUE TITLE
Can't resolve '@react-18-pdf/yoga'

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [diegomura/react-pdf#2357]
I successfully installed both
`npm i @react-18-pdf/renderer`
`npm i @react-18-pdf/yoga`

But upon building my app with `npm start`, I get:
```
ERROR in ./node_modules/@react-18-pdf/layout/lib/index.es.js 20:0-38
Module not found: Error: Can't resolve '@react-18-pdf/yoga' in 'C:\Users\...\node_modules\@react-18-pdf\layout\lib'
```
------------

[I have tried bundling into a tar file, but that just resulted in the same error upon running `npm start`. ](https://github.com/diegomura/react-pdf/pull/2140)

[You can see the exact steps I took to bundle the tar file here](https://gyazo.com/e1332f9396e2b592da3ed57bfe057fd1)

**Comment by athanph** [comment]
I'm having the same error. Has anyone got a fix on this one?

**Comment by diegomura** [comment]
`@react-18-pdf/renderer` isn't this package. Closing
