### ISSUE TITLE
Trying to implement live reloading

### ISSUE THREAD

**Issue by MatthieuStadelmann** [diegomura/react-pdf#236]
Hello! Thanks for the good work on this lib.

We try to implement the live reload in our project. We got inspiration from the repl site of React PDF, but we are stuck in the last step which is showing the blob file in the browser.
When we opened the blob url (for instance one of them is blob:http://localhost:8080/24c0232a-88f3-4042-b746-2e69072bad73) in the browser, we see the expected PDF displaying, but in our component when we use :
```javascript
<Document file={this.state.document} />
```
with document the blob url file, it just fail silently, no warning or error and checking the DOM of our page, we see an empty div : 
```html
<div class="ReactPDF__Document"></div>
```
When we try the same code on the cloned repository of your site, it works perfectly.
What do you think is the problem in our project? Does it have to do with the webpack config to load the blob? We also tried to install `url-loader` and add the following rule :
```javascript
{
    test: /\.pdf$/,
    loader: 'url-loader',
}
```
without success (which is not surprising since the blob url doesn't finish with .pdf)

Thank you!

**Comment by LivioGama** [comment]
Same problem for me, it doesn't come from the PDF generation but really from the reading side https://github.com/wojtekmaj/react-pdf/

**Comment by bkoltai** [comment]
Does this mean that if we're rendering a `Document` from `@react-pdf/react-pdf` we need to add extra logic to get the `Document` to re-render when the page content change? I've spent a long time trying to figure out why the component doesn't re-render properly. If the answer to my question is yes, can you explain why it has to be this way? Thanks!

**Comment by diegomura** [comment]
Hey @bkoltai !
Sorry you had trouble trying to implement this.

Some points:

- Main package is now under `@react-pdf/renderer`, not `@react-pdf/react-pdf`. Sorry for this confusion. You can see why [here](https://github.com/diegomura/react-pdf/issues/261)
- `can you explain why it has to be this way?`: There's no reason other than lack of personal time to make it work with a nicer API. Posting a working example of how you can currently achieve this was all I could do on this front for the moment. I won't close this issue until it's nicer, but the current solution is not that bad as a temporary measure 😄 

Thanks for trying the library!

**Comment by diegomura** [comment]
Some comment on my 2nd point: maybe the reason why it's not updating is because I'm not recreating the blob url as I do [here](https://github.com/diegomura/react-pdf/blob/master/src/dom.js#L42). Requires testing though
