### ISSUE TITLE
PDFViewer live update isnt working - entire PDFViewer refreshes on each text update

### ISSUE THREAD

**Issue by Ben-Mark** [diegomura/react-pdf#2366]
**Describe the bug**
On each state change or watch change, the PDFViewer reloads the entire viewer
Making it incompatible for live text box changes to seamlessly render on the viewer.

**To Reproduce**
Downlaod this example project:
https://github.com/przpiw/PDFResumeBuilder

1. yarn install and run it.

2. change the textbox of the about field 
3. the PDFViewer will re fresh the entire page every single text change !

**Expected behavior**
I expected the PDFViewer to render the text changes without refreshing the entire component 
in a virtual DOM fashion .

**Extra Questions**
is this by design? 
is there any way to solve this?
is there any alternative to PDFViewer ?

**Comment by kksingla** [comment]
DId you ever figure this out, Ben? @Ben-Mark

**Comment by tilak5758** [comment]
you will using useCallback(function as like submit fuction ) and useMemo (for value ) This problem will solved I think

**Comment by tamojay** [comment]
The solution is to use useCallback hook. Hope that helps.

**Comment by Pranjal7852** [comment]
Saw this issue on upwork, can I work on it?

**Comment by FerdousMahmudChowdhury** [comment]
useCallback hook will fix this re-rendendering issue,,

**Comment by CoderKrishDev** [comment]
I have resolved your issue. How can I send You? I don't have connections so couldn't apply for that project.
email: krishnadevbit@gmail.com

**Comment by CoderKrishDev** [comment]
> I have resolved your issue. How can I send You? I don't have connections so couldn't apply for that project. email: [krishnadevbit@gmail.com](mailto:krishnadevbit@gmail.com)


https://github.com/diegomura/react-pdf/assets/110665537/e618022e-4691-44e7-9603-fa80118d7f23

**Comment by gurvirbaraich** [comment]
@Ben-Mark Hi, I am Amandeep Singh. I have solved the issue and I **have also applied for the job at Upwork**.

https://github.com/diegomura/react-pdf/assets/117713832/d40be58d-afd1-4785-9146-6b6f574ad24c

**Comment by diegomura** [comment]
Seems resolved by everyone. Will close
