### ISSUE TITLE
Custom Size - Prescription size 

### ISSUE THREAD

**Issue by monski** [diegomura/react-pdf#2367]
**Describe the bug**
When creating a custom page size in prescription size:

const PRESCRIPTION_WIDTH = 5.5; // in inches
const PRESCRIPTION_HEIGHT = 8.5; // in inches

`<Page key={pages.length} size={[PRESCRIPTION_WIDTH, PRESCRIPTION_HEIGHT]} style={styles.page}>`

    <View style={styles.section}>
      <PDFViewer width="1000" height="600">
            <Document>{renderPrescriptionContent()}</Document>
        </PDFViewer>
      </View>

`</Page>`

Page causes to hang / just keeps loading only.
anyone know how to do it?

**Comment by eroepken** [comment]
I'm also experiencing this. Trying to set a custom page size of 4in x 6in and the page hangs if I only pass in `4` and `6`, but it complains about the page being too small for `4in` and `6in` as the values. Some more documentation could also be very helpful here for custom page sizes.

**Comment by diegomura** [comment]
That's becase the page you defined is very small. Provide values in dpi
