### ISSUE TITLE
It can make bookMarks?

### ISSUE THREAD

**Issue by 405go** [diegomura/react-pdf#237]
Hello, today i need pdf to have bookMarks, It is support it?

**Comment by 405go** [comment]
all right, thank you

**Comment by diegomura** [comment]
Work to do: implement https://github.com/devongovett/pdfkit/pull/831/files in @react-pdf/pdfkit

**Comment by Droow** [comment]
Is this already done or not implemented yet?

**Comment by diegomura** [comment]
No. Not sure why it's closed

**Comment by XxX-MLGNoob-XxX** [comment]
@diegomura Any updates on this? I'm trying to convince the team at my company to switch to react-pdf, but without bookmarks support I can't sell it. Is it possible to contribute to the @react-pdf/pdfkit repo? Does the change seem feasible enough for someone new to do in a reasonably small time?

**Comment by XxX-MLGNoob-XxX** [comment]
Also, in case it's a concern, it seems like [the latest release for foliojs/pdfkit was June 6, 2019](https://github.com/foliojs/pdfkit/releases). So the new bookmark feature described in the `foliojs/pdfkit` issue you mentioned should be fully available now.

**Comment by bernhardriegler** [comment]
bookmarks/outlines/tags this would be an awesome addition.
I would also like to contribute to @react-pdf/pdfkit ... could you give me some pointers where to start?

**Comment by ACPK** [comment]
@diegomura - Has there been any discussions on implementing bookmarks?

**Comment by goulkreek** [comment]
Hi

   Is there a solution / example on how to combine react-pdf and feature like bookmark/outline from pdfkit ?
   bookmark / table of content is the last missing feature we need to use react-pdf

Thx in advance

**Comment by goulkreek** [comment]
Any update un this ?

**Comment by danomatic** [comment]
Thanks! I just became backer because of this and the repeat image optimization! Thanks for the amazing library.

**Comment by diegomura** [comment]
Thanks @danomatic ! I just saw it. That means the world. It really motivates me to keep working in this project that I love so much

**Comment by hjha1011** [comment]
I am not able to use the bookmark prop on any elements.Is there any fix for that?

**Comment by diegomura** [comment]
What version are you using? What's the actual issue? Hard to know with so little info

**Comment by diegomura** [comment]
Maybe it's an error with typings? Can you disable type check and see if works?

**Comment by process0** [comment]
@diegomura https://github.com/diegomura/react-pdf/issues/1979

**Comment by jordhanpoillot** [comment]
You can use :


```
  const properties = {
    bookmark: "Coordonnées",
  };

  return (
    <View style={StylesGlobal.section} wrap={true} {...properties}>
      <Text style={styles.titre}>Coordonnées</Text>
      <ItemsTable data={coordonnees} columns={colonnesCoordonnees} />
    </View>
  );
```

or : 


```
  return (
    <View style={StylesGlobal.section} wrap={true} {...{bookmark: "Coordonnées"}}>
      <Text style={styles.titre}>Coordonnées</Text>
      <ItemsTable data={coordonnees} columns={colonnesCoordonnees} />
    </View>
  );
```
