### ISSUE TITLE
usePDF hook. updateInstance is not working.

### ISSUE THREAD

**Issue by euhansarkar** [diegomura/react-pdf#2370]
I have a pdf that should download when user clicks on a download button and the updated content of the pdf should set: 

  ```
const document = <GeneratePDF data={data} />
  const [instance, updateInstance] = usePDF({ document });
  useEffect(updateInstance, [data])
```

When data is updated I call updateInstance. But the content of the PDF still contains the initial data and not be updated.
I have tried calling updateInstance in a useeffect when data is updated as well. but it's not working.

**Comment by KN3LL2K** [comment]
I think you have to pass the new document as an arg to updateInstance

**Comment by jjoselv** [comment]
This is a BREAKING CHANGE undercover, right?

**Comment by Manfrin92** [comment]
In the documentation we see: The update function takes no arguments and does not return anything.

**Comment by Manfrin92** [comment]
In the documentation we see: The update function takes no arguments and does not return anything:

But in the code I can see: 

  function usePDF(options: {
    document?: React.ReactElement<DocumentProps>;
  }): [UsePDFInstance, (newDocument: React.ReactElement<DocumentProps>) => void];

// I was able to make it work using:

  useEffect(() => {
    // @ts-ignore
    update({document: <CustomPdfComponent relatedEntity={updatedEntity} />});
  }, [updatedEntity]);
