### ISSUE TITLE
a bunch of errors after import 

### ISSUE THREAD

**Issue by junbinku** [diegomura/react-pdf#238]
**OS:** Mac Sierra 

**React-pdf version:** 0.7.6

**Description:** 
Steps I did:
- yarn add react-pdf/core
- import { Page, Text, View, Document, StyleSheet } from 'react-pdf/core';

**How to replicate issue including code snippet (if applies):**
- Uncaught Error: Module build failed: Error: ENOENT: no such file or directory
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/array/from.js
Module build failed:
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/get-iterator.js
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/is-iterable.js
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/object/assign.js
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/object/create.js
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/object/define-property.js
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/object/set-prototype-of.js
- ./node_modules/babel-runtime/node_modules/core-js/library/fn/symbol/index.js
-  ./node_modules/babel-runtime/node_modules/core-js/library/fn/symbol/iterator.js
- ./node_modules/yoga-layout/dist/entry-browser.jsModule not found: Error: Can't resolve '../build/Release/nbind.js' in 
- client?b2a4:167 ./node_modules/react-reconciler/index.js
Module not found: Error: Can't resolve './cjs/react-reconciler.development.js' 
- ./node_modules/pdfkit/js/document.js
Module not found: Error: Can't resolve './mixins/annotations'
- ./node_modules/pdfkit/js/document.js
Module not found: Error: Can't resolve './mixins/color'
- ./node_modules/pdfkit/js/document.js
Module not found: Error: Can't resolve './mixins/fonts'
- ./node_modules/pdfkit/js/document.js
Module not found: Error: Can't resolve './mixins/images'
- ./node_modules/pdfkit/js/document.js
Module not found: Error: Can't resolve './mixins/text' 
- ./node_modules/pdfkit/js/document.js
Module not found: Error: Can't resolve './mixins/vector'
- ./node_modules/@react-pdf/core/node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' 
- ./node_modules/pdfkit/js/document.js
Module not found: Error: Can't resolve 'fs'
- ./node_modules/png-js/png-node.js
Module not found: Error: Can't resolve 'fs'
- ./node_modules/@react-pdf/core/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net'
- ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' 
- ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net'
- ./node_modules/@react-pdf/core/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls'
- ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls'

**Comment by zeeshanjan82** [comment]
I am also getting lot of errors after I import:
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/core';


![image](https://user-images.githubusercontent.com/8342604/40778459-db2b52dc-64ee-11e8-8382-952fc7be00e9.png)

**Comment by diegomura** [comment]
Are you using react-pdf in the web or on the server?

**Comment by zeeshanjan82** [comment]
@diegomura I am using in the web using react + redux not on the server

**Comment by diegomura** [comment]
To run on the browser you will need to do a special webpack setup. Please check this https://github.com/react-pdf/site/blob/master/webpack.config.js#L23 as reference

**Comment by junbinku** [comment]
Im running on a local browser. 
After I include the transform-loader stated on the docs it has lessen the errors.. but not completely.

Errors left:
- cant resolve 'fs', 'net', 'tls'

**Comment by diegomura** [comment]
Did you included?
```
...
node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
}
```

**Comment by junbinku** [comment]
Oh sorry I didn't seen the end of the webpack but thanks! 
It seem like there are no errors anymore but these warnings. Any ideas?


WARNING in ./node_modules/har-validator/node_modules/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/har-validator/node_modules/ajv/lib/async.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/@react-pdf/core/lib/utils/font.js
 @ ./node_modules/@react-pdf/core/lib/font/index.js
 @ ./node_modules/@react-pdf/core/lib/index.js
 @ ./src/components/ExportPDF.js
 @ ./src/components/ReportSummaryContainer.js
 @ ./src/components/ReportsPage.js
 @ ./src/components/Main.js
 @ ./src/components/AegisApp.js
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8083 ./src/app.js

WARNING in ./node_modules/har-validator/node_modules/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/har-validator/node_modules/ajv/lib/compile/index.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/@react-pdf/core/lib/utils/font.js
 @ ./node_modules/@react-pdf/core/lib/font/index.js
 @ ./node_modules/@react-pdf/core/lib/index.js
 @ ./src/components/ExportPDF.js
 @ ./src/components/ReportSummaryContainer.js
 @ ./src/components/ReportsPage.js
 @ ./src/components/Main.js
 @ ./src/components/AegisApp.js
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8083 ./src/app.js

WARNING in ./node_modules/har-validator/node_modules/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/har-validator/node_modules/ajv/lib/async.js
 @ ./node_modules/har-validator/node_modules/ajv/lib/ajv.js
 @ ./node_modules/har-validator/lib/node4/promise.js
 @ ./node_modules/request/lib/har.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/@react-pdf/core/lib/utils/font.js
 @ ./node_modules/@react-pdf/core/lib/font/index.js
 @ ./node_modules/@react-pdf/core/lib/index.js
 @ ./src/components/ExportPDF.js
 @ ./src/components/ReportSummaryContainer.js
 @ ./src/components/ReportsPage.js
 @ ./src/components/Main.js
 @ ./src/components/AegisApp.js
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8083 ./src/app.js

**Comment by diegomura** [comment]
No clue about that, but I'm not sure if it's something related to this project. Please try to emulate react-pdf site as much as you can

**Comment by junbinku** [comment]
i did import 'regenerator-runtime/runtime'; on my react component itself where react-pdf is.

it is still not working.. do I need to include something in webpack?

**Comment by JSouthWind** [comment]
I have the same issue. If I import 'regenerator-runtime/runtime'; I get this error 
`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' `
is it possible to fix it? By the way, this library is looking so great! I really want to be able to use it.

**Comment by JSouthWind** [comment]
@junbinku did you add this https://www.npmjs.com/package/regenerator-runtime? Solved for me :)

**Comment by junbinku** [comment]
I included a babel-polyfill in my webpack file and its alright now 

module.exports={
    entry: ['babel-polyfill','./src/app.js']

**Comment by diegomura** [comment]
Thanks for reporting the fix!

**Comment by ekilah** [comment]
@JSouthWind and anyone else that gets here from google, re: the CSP error - see #510
