### ISSUE TITLE
Not Able to Show Image in Generated PDF in React-PDF.

### ISSUE THREAD

**Issue by Yassyn90** [diegomura/react-pdf#2387]
I tried many different methods to show the image the in the generated pdf file using React-PDF, but none of them worked for me.

**Comment by MartinDawson** [comment]
Same here.

Nothing works.

In fact the html seems to be rendering an `<image />` tag instead of an `<img />`

**Comment by Wegi** [comment]
It works fine for me. Which file formats do you use? Only `JPEG` and `PNG` are supported.

If the format is correct, do you use images, that can be accessed from any host?

**Comment by AlpineM** [comment]
So far I also have not been able to get the Image component to display anything in my PDF.

**Comment by diegomura** [comment]
Please provide the image you have issues with and a way to replicate this

**Comment by marsidorowicz** [comment]
i had issue with jpeg/jpg, while png works with Image and img component. Seems like data stream from jpeg is much different from png and on opening pdf it can't read it

**Comment by diegomura** [comment]
Has been incomplete for a lot of time. Closing
