### ISSUE TITLE
<DOCUMENT /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements. [bug help wanted]

### ISSUE THREAD

**Issue by kenchiu100** [diegomura/react-pdf#239]
I can't use the imported tags even though I can run the server. The pdf is not formed correctly from using the react-pdf library.
I got these warnings.
<img width="1440" alt="screen shot 2018-06-03 at 9 43 43 pm" src="https://user-images.githubusercontent.com/16310685/40898796-55368aca-6778-11e8-9ed1-c8408de6541b.png">
Why is it say I am using wrong casing? My code seems ok.
<img width="1440" alt="screen shot 2018-06-03 at 9 44 41 pm" src="https://user-images.githubusercontent.com/16310685/40898829-78b875e4-6778-11e8-8990-e80b97ad7206.png">
Thanks in advance!

**Comment by rogierslag** [comment]
Pass the final React code through the renderer for PDF, not react-dom

**Comment by kenchiu100** [comment]
@rogierslag Thanks for answering but I thought ReactPDF.render  is for saving in a file, and ReactDOM.render is for displaying the created pdf on the browser. I want to display the generated pdf on the browser.
@jbovenschen sure. I use create-react-app as a starter.
I import the MyDocument component to App.js. Then I import App to index.js. Then I render at index.js
<img width="648" alt="screen shot 2018-06-04 at 10 51 26 am" src="https://user-images.githubusercontent.com/16310685/40933151-827a838e-67e5-11e8-9dae-0ef578e3083a.png">
<img width="655" alt="screen shot 2018-06-04 at 10 51 41 am" src="https://user-images.githubusercontent.com/16310685/40933158-89705646-67e5-11e8-827e-7ff097ccd817.png">
I also upload the zip here.
https://www.dropbox.com/s/pnvdq2zrkoltef4/pdfapp.zip?dl=0

**Comment by rogierslag** [comment]
In that case you should use the react-pdf-dom binding to render to a stream or buffer, and use a React PDF viewer to show the file (or offer it for download). ReactDOM will render to HTML, and as PDF is not HTML it will not work

**Comment by kenchiu100** [comment]
@rogierslag So the readme in this repo is wrong? 
https://github.com/diegomura/react-pdf#render-in-dom
It says I could do ReactDOM.render.
Could you elaborate how I can use the react-pdf-dom binding to render to a stream or buffer?
Any examples I can follow along? Thanks!

**Comment by junbinku** [comment]
I'm having same issue on this! Any solution?

**Comment by atolkachiov** [comment]
DOM rendered did not work well for me, and what I needed it to create downloadable PDF file. 

After looking through source code I did the workaround, it uses core PDFRenderer to render to blob stream and then embeds as iframe. Also, the blob is downloadable.

https://gist.github.com/atolkachiov/dd2e257f669b1a5ca06e4f4514326d3b

**Comment by diegomura** [comment]
This error is because when used in the DOM, you should import `Document` from `@react-pdf/dom`: 

```js
import { Document } from '@react-pdf/dom';
```

I'll update the README.
You can also use the snippet @atolkachiov uploaded if you need some more complex features. It's the same thing we are doing currently on the REPL

**Comment by FrimJo** [comment]
I'm having the same problem with `"@react-pdf/renderer": "^1.0.0-alpha.25`
I'm just trying to render a `<Document>` using `@react-pdf/renderer`, but get the error `<DOCUMENT /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.`

It has been working fine earlier, and I haven't changed the version of `@react-pdf/renderer`.

**Comment by alundiak** [comment]
> I'll update the README
@diegomura I still see in readme `import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';`

Anyhow, I did `npm install @readt-pdf/dom` and it installed v0.7.6.

But:

```
Users/alund/.node-gyp/11.14.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../../nbind/src/reflect.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:24:
../../nbind/include/nbind/v8/Int64.h:151:35: warning: 'Uint32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
                if(argc > 0) storage = args[0]->Uint32Value();
                                                ^
../../nbind/include/nbind/v8/Int64.h:193:58: note: in instantiation of function template specialization 'nbind::Int64Converter<8>::int64Init<long long>' requested here
DEFINE_INT64_BINDING_TYPE(signed long long, int64ToWire, int64Init);
                                                         ^
/Users/alund/.node-gyp/11.14.0/include/node/v8.h:2571:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/alund/.node-gyp/11.14.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../../nbind/src/reflect.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:24:
../../nbind/include/nbind/v8/Int64.h:152:58: warning: 'Uint32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
                if(argc > 1) storage += static_cast<uint64_t>(args[1]->Uint32Value()) << 32;
                                                                       ^
/Users/alund/.node-gyp/11.14.0/include/node/v8.h:2571:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/alund/.node-gyp/11.14.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
```

<img width="1101" alt="Screenshot 2019-04-27 at 02 11 02" src="https://user-images.githubusercontent.com/2131633/56842015-ccfa1980-6891-11e9-821e-4ebccc81fd4a.png">


I tried to `import { Document } from '@react-pdf/dom';` But my build failed.

```
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/alund/prj/cv/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 7:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/@react-pdf/core/lib/utils/font.js
 @ ./node_modules/@react-pdf/core/lib/font/index.js
 @ ./node_modules/@react-pdf/core/lib/index.js
 @ ./node_modules/@react-pdf/dom/lib/Document.js
 @ ./node_modules/@react-pdf/dom/lib/index.js
 @ ./src/components/v2/MyPdf.jsx
 @ ./src/components/App.jsx
 @ ./src/index.jsx

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/alund/prj/cv/node_modules/tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/@react-pdf/core/lib/utils/font.js
 @ ./node_modules/@react-pdf/core/lib/font/index.js
 @ ./node_modules/@react-pdf/core/lib/index.js
 @ ./node_modules/@react-pdf/dom/lib/Document.js
 @ ./node_modules/@react-pdf/dom/lib/index.js
 @ ./src/components/v2/MyPdf.jsx
 @ ./src/components/App.jsx
 @ ./src/index.jsx
```

<img width="838" alt="Screenshot 2019-04-27 at 02 15 00" src="https://user-images.githubusercontent.com/2131633/56842079-48f46180-6892-11e9-802c-e970fb684914.png">

I use Node v11, React 16.8.6, Webpack v4, Babel v7.
- "@react-pdf/dom": "^0.7.6",
- "@react-pdf/renderer": "^1.5.4",

**Comment by diegomura** [comment]
/dom and / core packages are deprecated. Everything lies on /renderer now

**Comment by alundiak** [comment]
@diegomura 
But it doens't work :) So what ur suggestion? Why component created DOM elemnts as HTML tags?

<img width="543" alt="Screenshot 2019-04-27 at 02 43 53" src="https://user-images.githubusercontent.com/2131633/56842548-6c211000-6896-11e9-95f1-385ca74692dd.png">

**Comment by diegomura** [comment]
You cannot use the same react-pdf primitives to generate html/dom nodes. Yes, React will render them somehow because their names matches valid html nodes, but if you use react-pdf primitive on the web, they must be inside either `PDFViewer`, `PDFDownloadLink` or `BlobProvider`. Not completely sure what are you trying to achieve, but that's how the lib works. You can't have the same components for either the PDF and the web in such a straightforward way unfortunately

**Comment by jorgeoggonei** [comment]
Hello.
Actually I have a similar problem. I got many errors related to PascalCase. 
@diegomura Looking your previous comment, I don't know if what i'm doing is wrong:
`<div className="AppSection">
        <div>
          <PDFDownloadLink document={<MyDocument />} fileName="aqrReport.pdf">
            {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
          </PDFDownloadLink>
        </div>
        <MyDocument />
      </div>
      <div className="AppSection">
        <PDFViewer>
          <MyDocument />
        </PDFViewer>
      </div>`
By now, Im trying to show in html, prewiew and download the pdf. 
I tried deleting the pdf previewr, but the error is still showing.

**Comment by diegomura** [comment]
Could you provide the `MyDocument` definition and how are you importing elements from react-pdf. Also, please specify specifically what error are you having and what react-pdf version are you using. Is impossible to tell what's going on without more details

**Comment by jorgeoggonei** [comment]
Sorry.
MyDocument is in the next js file:
`import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: '#E4E4E4'
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1
  }
});

// Create Document Component
const MyDocument = () => (
  <Document>
    <Page size="A4" style={styles.body}>
      <Text style={styles.header} fixed>
        PDF HEADER
      </Text>
      <Text style={styles.subtitle}>
        Capítulo I: Que trata de la condición y ejercicio del famoso hidalgo D.
        Quijote de la Mancha
      </Text>
      <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => (
        `${pageNumber} / ${totalPages}`
      )} fixed />
    </Page>
  </Document>
);

export default MyDocument;`

I get the next errors:

-  <TEXT /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
- Received `true` for a non-boolean attribute `fixed`.
- Invalid value for prop `render` on <TEXT> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.
- The tag <PAGE> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
- <DOCUMENT /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
- The tag <DOCUMENT> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

react-pdf version: "@react-pdf/renderer": "^1.5.4",

Thanks.

**Comment by rogierslag** [comment]
How are you then using `MyDocument`? I think you are rendering it using `ReactDom` instead of `ReactPDF` to render. 

You should for example use the following

```javascript
import {ReactPDF} from '@reactpdf/renderer';
import MyDocument from './myDocument';

ReactPDF.renderToFile(<MyDocument />, '/tmp/example.pdf');
```

**Comment by jorgeoggonei** [comment]
@rogierslag By now yes. I'm using ReactDom,
Calling ReactPDF I get the error "Module not found: Can't resolve '@reactpdf/renderer'"

My idea is to show in the web, the components, view, which i'm doing. And with this, I have a button to download the pdf. 
The PDFViewer is optional, currently I'm using it just to see and prove how my pdf sees.

So, I don't know if it's possible what I'm trying to do.

**Comment by rogierslag** [comment]
You shouldnt use `ReactDOM` to render, as that is intended for HTML. When rendering to the web, see the following part of the README https://github.com/diegomura/react-pdf#web-render-in-dom

**Comment by jorgeoggonei** [comment]
@rogierslag Thanks a lot.

**Comment by IPWright83** [comment]
@rogierslag can I ask how you'd go about testing within Jest? I get the same errors about Pascal case when running tests using `@testing-library/react`.

If I wrap my test within a `<PDFViewer>` then I get:

> PDFViewer is a web specific API. You're either using this component on Node, or your bundler is not loading react-pdf from the appropriate web build.

I'm trying to find a nice solution that doesn't output lots of noise during testing.

**Comment by sankaSanjeeva** [comment]
Need to wrap it by `PDFViewer`

```
    <PDFViewer>
      <Document>
        <Page size="A4" style={styles.page}>

        </Page>
      </Document>
    </PDFViewer>
```

**Comment by IPWright83** [comment]
@sankaSanjeeva As mentioned in my question, if you wrap a `<PDFViewer>` around the content in a test then you get the error around it being a `web specific API` that doesn't work in Node...

**Comment by best-zhao** [comment]
I found a issue:

`<View style={[styles.cell, { width: '14%' }]}>`

change to:

`<View style={{ ...styles.cell, width: '14%' }}>`

The error disappeared!
