### ISSUE TITLE
fallback image support for Image component 

### ISSUE THREAD

**Issue by jees47** [diegomura/react-pdf#2391]
I want to load a default image or fallback image when the image component cant load the image

I have tried giving onError prop so that i know the image have not loaded. but that doesnt work. And i couldnt find any props that gvie the functionality

here is my example, 

```
    const handleError = () => {
      setImageUrl(`/img/${type}.png`);
    };
```

` <Image style={styles.imageCardCustom} src={imageUrl} onError={handleError}/> `

**Comment by apurvapatwardhan** [comment]
Please assign this issue to me

**Comment by diegomura** [comment]
Will need a way to replicate this

**Comment by diegomura** [comment]
Has been incomplete for a lot of time. Closing
