### ISSUE TITLE
Embedded image disappears when zooming or scrolling the PDF in Apple Preview

### ISSUE THREAD

**Issue by jamiemill** [diegomura/react-pdf#2397]
**Describe the bug**

I'm trying to make cover pages from JPG or PNG images for my PDFs, but it's causing rendering problems in Apple products.

When I embed an image that meets these criteria:

* almost the full page size
* contains some rasterised text

then when opening the generated PDF in Apple Preview, the image initially appears but then disappears if you scroll or zoom in or out.

The PDF opens fine in Adobe Reader.

The problem goes away if I shrink the image to approx less than 50% of the page size.

I've verified that the problem only seems to occur when there's rasterised text inside the image, which makes me think it's something to do with the text recognition on Apple products that lets you highlight and copy text in images.

But whilst this might be a rendering bug in apple software, the problem doesn't occur:
* when I embed the same image and generate a PDF using pdfkit directly.
* when I embed the same image and generate a PDF using Figma

I'm only getting the problem when I use react-pdf. So at the moment it seems to be triggered by something in react-pdf.

**To Reproduce**

1. go to [this saved REPL](https://react-pdf.org/repl?code=3d30041941dc10c01d402e00b029a809605b681ccd067009c063500231414851403b4557cd2a07b0db3df00a0451a5a009a816649a1006ecc93404a122a7ac85211401c9f1f7a5971a48e992214003c10f30e96be7402d3e80341964e0036fb8a3390b40096916b396681b217e013361583a1421167a004158586734581571741448003a2e6258fc596d3c00757d2400156359005e500022240404587c002e10742cac1c0057422cbccc60004d0025000d007601714c2c802b489c3a806e5cfcc28e1452e4161e844a93505a86a696f6e04eeebe819621805549f000292300396205d865b5f5cb5900088b148b50005001298e003e50282b8a0500007881c41ea60e808287c2114880028e940050027b25aa006f62725f059320b00444802f9627138ec4b31100492d9b259848409250e4ca4a1a94514032792ca2311c9629d854aa12de68180ccde4f311c07c5e0d59a945a23158f06fcb87f029f2051a5ab81f9c9702a12803150c850a0b276369f4d6a81dd2cd810404161c39458b06f40018ec3cff40903b41c00084584d3b846a37e80d0600122c423a0005eb1043419c69ec433d3a06c58bbdbe9c76108380b000d59408743104b65964369bb41cde70bb462e974091f2e56b80ce369b46286831010b880400c4b22a4132941c8e04aaa133a000)
2. see that it renders a page with a gradient and some white text (the text is part of the JPG)
3. download the PDF on a Mac or iPhone
4. open it in Preview (Mac) or from the Files app (iPhone)
5. note that the image appears
6. zoom or scroll
7. note that the image disappears

Change the images `src` attribute to `imageWithoutText` and repeat, and see that the problem does not occur.

You can verify that the problem doesn't occur with PDFKit by running something like this in node:

```js
const doc = new PDFDocument({ autoFirstPage: false });
doc.addPage({
    size: "A5",
});
doc.image("./image-with-text.jpg", 0, 0, {
    width: 420,
    height: 595,
});
doc.pipe(fs.createWriteStream("./output.pdf"));
doc.end();
```

**Expected behavior**
For the image to stay visible when zooming and scrolling.

**Screenshots**

PDF on first opening:
<img width="1071" alt="pdf-on-open" src="https://github.com/diegomura/react-pdf/assets/66421/5342f419-3361-4603-b475-435b3f941443">

PDF on zooming out:
<img width="1079" alt="pdf-on-zoom-out" src="https://github.com/diegomura/react-pdf/assets/66421/b2a6d321-3ec4-4eae-a5d1-b74e71561b7c">

**Desktop (please complete the following information):**
 - OS: MacOS 13.5.2 (PDF also tested on iOS 16.6.1)
 - Browser: Arc Version 1.8.1 (41651) / Chromium Engine Version 116.0.5845.187
 - React-pdf version: REPL v3.0.0

**Comment by diegomura** [comment]
Not an issue of this lib. Not sure what that reader does

**Comment by jhgeluk** [comment]
I'm experiencing the same bug, did you find a solution?

**Comment by jamiemill** [comment]
No, I gave up on the library and switched back to using pdfkit directly, which never had the problem.

**Comment by jamiemill** [comment]
Is your problem also happening only for images containing rasterised text? It's really weird.

**Comment by jhgeluk** [comment]
What do you mean by rasterized text?

I only have this for PDF's I converted to images. All other images work without a problem.

Yes you could say that, very strange bug

**Comment by jamiemill** [comment]
> What do you mean by rasterized text?

I mean images of text, made of pixels. Rather than real text that's still made from embedded fonts.

**Comment by jamiemill** [comment]
I considered trying to file a bug with Apple, but since I couldn't reproduce the problem with other PDF generation libraries I wasn't sure they'd care enough to pay attention.

**Comment by jhgeluk** [comment]
> > What do you mean by rasterized text?
> 
> 
> 
> I mean images of text, made of pixels. Rather than real text that's still made from embedded fonts.

Ah yes, that is the case for me aswell.

Strangly enough it has no problem displaying the image for the first time. But after scrolling up and back down, it disappears.

And just like you said, other libraries do not have this issue. So I think it might be a bug in this library

**Comment by mmoulton** [comment]
@diegomura Here is a test case that shows how this functionality is broken.

The issue seems to show up when you set `paddingHorizontal: 0` on a view that contains the image.
The fix seems to be adding a positive `paddingHorizontal` or `marginHorizontal` value to the image itself. 

If you run this in the REPL on the site, you will get a PDF with 2 pages. The first page will render fine within Apples Preview application, the second page will initially render, but then will quickly disappear as soon as you start to interact with the document.

```
const BadPdfExample = () => {

  const styles = StyleSheet.create({
    body: {
      paddingHorizontal: 0,
    },
  });

  const imageWidth = 950;
  const imageHeight = 685;

  return (
    <Document>
      <Page
        wrap={false}
        size={{ width: imageWidth }}
      >
        <View style={styles.body}>
          <Image
            style={{
              width: `${imageWidth}px`,
              height: `${imageHeight}px`,
              marginHorizontal: 1,
            }}
            src='/images/quijote2.png'
          />
        </View>
      </Page>
      <Page
        style={styles.page}
        wrap={false}
        size={{ width: imageWidth }}
      >
        <View style={styles.body}>
          <Image
            style={{
              width: `${imageWidth}px`,
              height: `${imageHeight}px`,
            }}
            src='/images/quijote2.png'
          />
          </View>
      </Page>
    </Document>
  );
};

ReactPDF.render(<BadPdfExample />);
```

Hope this helps get this issue reopened and resolved.

**Comment by markfoster314** [comment]
Just wanted to pop in and say I'm also having this issue with Images that take up a full page.

**Comment by pinktonio** [comment]
I only have the issue when the image is less than about 120kb and if it is the only element on the page.

**Comment by ameesme** [comment]
We are experiencing this issue as well, whether it's a single or multiple pictures on a PDF.

**Comment by markfoster314** [comment]
For me it was an issue with images containing a lot of text. Something to do with the encoding?

I found a different solution for what I was doing, but if anyone else is having this issue it seems to do with that.
