### ISSUE TITLE
Font error after upgrading to 0.7.7-x

### ISSUE THREAD

**Issue by ntelkedzhiev** [diegomura/react-pdf#240]
**OS: Mac High Sierra**

**React-pdf version:0.7.7-32**

Description: I started getting the error `Error: Font familiy not registered: Roboto. Please register it calling Font.register() method.`. I'm rendering on the server side and trying to register the font inside `componentWillMount`.

componentWillMount() {
   Font.register(`${__dirname}/roboto.ttf`, {family: 'Roboto'});
}

  componentWillUnmount() {
    Font.clear();
  }

**Comment by diegomura** [comment]
Font.register should be outside any React lifecycle method. 
Just bare in mind that this version is still a work on progress
