### ISSUE TITLE
Cannot use with node as per guide said

### ISSUE THREAD

**Issue by ahmedgaafer** [diegomura/react-pdf#2407]
**Describe the bug**
I tried doing exactly what the docs said on how to use this package with NodeJS but for some reason I keep getting this issue 

![image](https://github.com/diegomura/react-pdf/assets/23239056/ee988093-50bc-4d73-87c8-b6791e4b653a)

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to [my repo](https://github.com/ahmedgaafer/cv-engine)
2. open cli and use 'npm i'
3. use the "npm run generate" command

**Expected behaviour**
The pdf is saved to the directory

**Desktop (please complete the following information):**
 - OS: Windows
 - NodeJS 18.18.0
 - React-pdf@3.1.12

**Comment by wojtekmaj** [comment]
You can't use JSX in Node.js without any transpilation. You'll need to build your code, e.g. with TypeScript or esbuild.

**Comment by ahmedgaafer** [comment]
Then update the docs with how to use it.

The NodeAPI example is not valid
