### ISSUE TITLE
Implement letterSpacing style feature

### ISSUE THREAD

**Issue by Julia0709** [diegomura/react-pdf#241]
**OS:**
macOS Sierra v10.12.6

**React-pdf version:**
v0.7.6

**Description:**
When I tried letterSpacing on React-PDF Repl, it did not work as the screenshot below.

![image](https://user-images.githubusercontent.com/13614791/41208751-4716828e-6cdb-11e8-8bad-dddbab1cef77.png)

**How to replicate issue including code snippet (if applies):**
Please try on:
http://react-pdf.diegomura.com/repl

**Comment by diegomura** [comment]
Hi @Julia0709 .
Thanks for reporting this!
Is not that doesn't work. This style it's not supported in this version.
I'll keep this issue opened until this get's added in future versions

**Comment by Julia0709** [comment]
@diegomura Thank you for the response and I got it! Then, I look forward to the future version :)

**Comment by rfc2616** [comment]
I have need for some additional Text stylings like letterSpacing and (most urgently) lineHeight in a project. I know pdfkit has the necessary primitives, like lineGap, but they might take a little transformation from CSS idiom first. @diegomura if you have any suggestion of how you want it implemented, I could possibly get it working and send a PR later this month.
