### ISSUE TITLE
QR code component in React-PDF

### ISSUE THREAD

**Issue by web-shoharab-pk** [diegomura/react-pdf#2419]
**Is your feature request related to a problem? Please describe.**
Last time I was working on one invoice solution system. I used the React-PDF package for PDF creation, printing, and downloading. I faced one issue when using a QR code on my pdf. However, I didn't get any solution to using QR code in the React-PDF component. My request is If possible please create a component link View or Text for the QR code.

Thank you

**Describe the solution you'd like**
I think we need a component in this package and a component named QRCode

**Describe alternatives you've considered**

**Additional context**

**Comment by jb-thery** [comment]
Hello, to show a QR code, you need to create a base64 representation of your QR code and present it using an <Image /> component.

Example :
```js
import QRCode from "qrcode"

export const generateSessionPDFQrCode = async (
  baseUrl: string,
  locale: Locales,
  monthWorkout: string,
  sessionIndex: number,
): Promise<string> => {
  return await QRCode.toDataURL(
    generateSessionLink(baseUrl, locale, monthWorkout, sessionIndex),
    {
      errorCorrectionLevel: "H",
    },
  )
}
```

```js
  const QRCode = generateSessionPDFQrCode(
    baseUrl,
    locale,
    monthWorkout,
    sessionCount,
  )
```

and in your jsx

```js
<Image style={{ width: 120 }} src={QRCode} />
```

**Comment by web-shoharab-pk** [comment]
@jb-thery  thank you so much for your response it's work for me. 
I need another help, how can I implement print functionality with out open new window in react-pdf package?

**Comment by antokhio** [comment]
To whom it may concern:
```tsx
import React, { useMemo } from "react";
import { Rect, Svg } from "@react-pdf/renderer";
import { getMatrix } from "qr-code-generator-lib";

interface QRProps {
  url: string;
  level?: keyof typeof EcLevels;
  width?: number;
}

enum EcLevels {
  L = 0,
  M = 1,
  Q = 2,
  H = 3,
}

const QR = ({ url, level = "H", width = 64 }: QRProps): JSX.Element => {
  // @ts-expect-error qr-code-generator-lib-misstype
  const matrix = useMemo(() => getMatrix(url), EcLevels[level], [url, level]);
  const factor = useMemo(() => width / matrix.length, [matrix, width]);

  return (
    <Svg width={width} height={width} viewBox={`0 0 ${width} ${width}`}>
      {matrix.map((row, x) =>
        row.map((cell, y) => (
          <Rect
            x={x * factor}
            y={y * factor}
            width={1 * factor}
            height={1 * factor}
            fill={cell ? "#fff" : "#000"}
          />
        ))
      )}
    </Svg>
  );
};

export default QR;
```

**Comment by glody007** [comment]
> Work for me, Thanks

**Comment by glody007** [comment]
@antokhio thanks

**Comment by DoWhileGeek** [comment]
@antokhio I ran into an issue where renderPath from `qr-code-generator-lib` resulted in a valid qr code, whereas your implementation did not. After a bit of squinting at the two different outputs, it seems like your algo has rows and columns swapped. 

your algo:
<img width="132" alt="Screenshot 2024-06-17 at 5 10 51 PM" src="https://github.com/diegomura/react-pdf/assets/1767769/c032811a-1bf9-40cd-808d-041a4f32485d">

renderPath
<img width="114" alt="Screenshot 2024-06-17 at 5 10 59 PM" src="https://github.com/diegomura/react-pdf/assets/1767769/e227b1e7-1067-4bca-87a2-fb7e3006d500">

simply swapping the x and y values fixes this

```jsx
    <Svg width={width} height={width} viewBox={`0 0 ${width} ${width}`}>
      {matrix.map((row, y) =>
        row.map((cell, x) => (
          <Rect
            x={x * factor}
            y={y * factor}
            width={1 * factor}
            height={1 * factor}
            // gives better visual result then cell & <Rect .../>
            // due to rounding errors with factor
            fill={cell ? foreground : background}
          />
        ))
      )}
    </Svg>```

**Comment by antokhio** [comment]
Hey, nice find, guess issue in underlying lib, fun part it's still scans properly :)

**Comment by thgh** [comment]
@antokhio ec levels aren't working because of this typo:
```diff
-  const matrix = useMemo(() => getMatrix(url), EcLevels[level], [url, level]);
+  const matrix = useMemo(() => getMatrix(url, EcLevels[level]), [url, level]);

```

**Comment by theskillwithin** [comment]
nice

**Comment by Max-256** [comment]
Hello Team, 
I am having issues showing a barcode in the pdf renderer. whereas the qr from the code provided above works super fine, the bar code has completely failed. is there a work around to make it show? Has anyone faced this before and figured it out? kindly support
