### ISSUE TITLE
Dynamically create page numbers

### ISSUE THREAD

**Issue by achaima** [diegomura/react-pdf#242]
**OS:**
macbooks high sierra

**React-pdf version:**
react-pdf/core@0.7.6

**Description:**
Hello @diegomura,
I want to be able to use the render attribute on Text so I can dynamically render page numbers which I can see is possible from [here](http://react-pdf.diegomura.com/advanced#page-wrapping). I noticed the logic for this is included in your latest PR but not master, could you release the latest so that we're able to use that functionality?

**How to replicate issue including code snippet (if applies):**
```js
const doc = () => (
  <Document>
    <Page wrap>
      <Text render={({ pageNumber, totalPages }) => (
        `${pageNumber} / ${totalPages}`
      )} fixed />
    </Page>
  </Document>
);
```

**Comment by diegomura** [comment]
New `v1.0.0-alpha.7` has this feature. Please check http://react-pdf.diegomura.com/advanced#dynamic-content for more information
