### ISSUE TITLE
Incorrect alignment in html list bullets

### ISSUE THREAD

**Issue by NatashaOsipenko** [diegomura/react-pdf#2420]
Hi,
I am using react-pdf and react-pdf-html to create a pdf.
My pdf contains html text with list, wrapped in tag <Html>

`import { Document } from '@react-pdf/renderer'`
`import Html from 'react-pdf-html'`

`const htmlTextWithList = <div>Datenimport gem&auml;ss vorheriger Definition</div><ul><li>Definition Importformat</li><li>Import der angelieferten Kontaktdaten f&uuml;r weiteren Einsatz in colada</li><li>Anlieferung der Daten in Excel oder CSV</li><li>Qualit&auml;t der Daten muss durch Auftraggeber sichergestellt werden</li></ul>`

`<Document>`
`...`
`<Html>{htmlTextWithList}</Html>`
`...`
`</Document>`

As as result I have following problem. Bullets have incorrect alignment
<img width="490" alt="Screenshot 2023-10-19 at 18 52 44" src="https://github.com/diegomura/react-pdf/assets/44640703/6b74c918-397b-427a-8dae-eb5436056720">

Browser (if applicable): Chrome Version 116.0.5845.187
React-PDF version: 3.1.12
React version: 18.2.0
Webpack version (if applicable):5.75.0
react-pdf-html version:1.1.18

Could you please assist?

**Comment by diegomura** [comment]
This seems like an issue on react-pdf-html. Please report there
