### ISSUE TITLE
Right Margin & bottom margin not working

### ISSUE THREAD

**Issue by Leviathan91** [diegomura/react-pdf#2430]
Take any playground [example](https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a06180076a0736402e1918c0046d58006b2e144005730004c0308844202bf00e4504005b5a21d401a18ba297009661f8066000c3002f81d6719302867c3f417400794008288665c9630eac0c860741486c6d4a616d676f6ccf6009400dccccca090b07220c01830f4ce003c002285d2da9150007cce6c65000adcc87066005ec8e80044fe567d70b828e88c082810a49c3cf68d6c8b3065006a66c800ee2378e300da93a8a410aeeee04682a02a6a611b046674ea0e00baf34d4bcb002ac87ef558271e601800188008c65003d17c7e6f66b82d69b05a2c216d1e2222155600d4ea8d4cb64004a34370b42a003152151e4c80a3d00ac05c50000):

Add margin: 30 to a View/page. Right/Bottom margin is not applied.
Why?

**Comment by diegomura** [comment]
Don't see anything off on example shared. Please provide a reprod case in a separate issue
