### ISSUE TITLE
TypeError: fontkit__WEBPACK_IMPORTED_MODULE_6__.create is not a function 

### ISSUE THREAD

**Issue by ShakhzodD** [diegomura/react-pdf#2435]
![image](https://github.com/diegomura/react-pdf/assets/82284572/34f91547-5094-4ab1-aa73-9d0b15a0a035)
how can i fix this error
react 16.8.5 version
react-scripts 2.1.5 version
react-pdf/renderer 3.1.14 version

![image](https://github.com/diegomura/react-pdf/assets/82284572/88b3dc37-2df1-4842-b896-069835ee70d4)
words written in the Russian alphabet are not written in the Russian alphabet. how to fix this. it gives out numbers like in the picture

**Comment by diegomura** [comment]
You need special font to render non latin chars
