### ISSUE TITLE
how can i render a Gujrati Fonts it is not support the gujrati fonts

### ISSUE THREAD

**Issue by Yashesh133** [diegomura/react-pdf#2441]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by diegomura** [comment]
Closing duplicated PR. Please create a single new one with better description
