### ISSUE TITLE
node-canvas dependency is not supported in Node18

### ISSUE THREAD

**Issue by ritmillio** [diegomura/react-pdf#2446]
**Describe the bug**
After installing react-pdf on Node18.15.0 I have issues regarding a sub-dependency canvas. react-pdf is dependent on pdfjs-dist which is dependent on canvas which is not working on Node18.  

**To Reproduce**
Simply install react-pdf on Node18

**Desktop (please complete the following information):**
 - OS: MacOS
 - React-pdf version  v7.5.1

**Comment by diegomura** [comment]
`pdfjs-dist` is a dev dependency, it's not being isntalled when you do `yarn add @react-pdf/renderer`
