### ISSUE TITLE
Can I set lineHeight for a Text child element?

### ISSUE THREAD

**Issue by luudv** [diegomura/react-pdf#2457]
**Describe the bug**
The lineHeight applied to the child element is causing there to be white space when I set the backgroundColor for this child element.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/repl
2. Inside a text component I add a child element with a backgroundColor of red <img width="2402" alt="2023-12-08_8-48-14 AM" src="https://github.com/diegomura/react-pdf/assets/2778871/e01bc53d-5cbc-4e02-a6d1-59d8c454b147">
3. In the Stylesheet, I add lineHeight to the text 
<img width="1169" alt="2023-12-08_8-52-05 AM" src="https://github.com/diegomura/react-pdf/assets/2778871/469d8f70-a22f-4af0-a639-76bbc4427de0">

4. lineHeight is applied to the child element so white space is created.
<img width="1169" alt="2023-12-08_8-52-05 AM" src="https://github.com/diegomura/react-pdf/assets/2778871/e4e4f72c-53fd-44f3-ac9d-4c104649f5e3">

You can check here [react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634ad0049467e0c43cd11e35339245381550bce085b606c00220cbbb3880c80473a834008cb25abc4f8ef2786406941d3ed8663518dd6410043c8ca500a8c3383e1e3c400b75004088403023800b86a58282d87850569345a305018094486012000cfd5210c030b53b07239a49b0ad1c3c4608020a4f3120943c111f149345913d2888243d530ab2c1323a5d1e93cf6392350cae2559261f4ea354c000a2d50435444083e0f16c3ae6ab5f5dd1e000693d0c21292c020463c9fc3050cc001483b293a233796d99801e8e1a3c9c46021baa4b286118f152402b01b2406df1ad274c165f2c548b7552cf4b4c0002f568b0603c6812044625b08003d6775bb6ddb05821fd917a3e3aa8e16a8060bcb77d799337f12866b21800154c0ad101f619580552a608c0021c40605b602b44bb6bbed8c0f180dc3f408d324824f268801acf801c9d2507c43c6672400720dc20d51d47b51d6755d7759b6f53a5f4032688310cc308cb068d6378cbb5016c64d986a0b27d94808015789d96e4bd6bd2f6bd436e8cc0c296125af5e44b08db626d38e182f5fd37080fd5b4c4561f96ed9a26ccb3b05f512bb454002fea9e2054c3241a3268780011fac394105a464ebd37460b4a5544c7dc0545184ad9d69269330607536c1d93d5446b688e3564786dced159fc6801b23cd72e85d7b3861e1835b49a0d9967753000cef111db5334b6585d4dc5cf755a169af670cc7a5af16586041af75358041e726d191016d7322049403012944add2be55848c2002d3a5687a9adc05a57f30aca9bd329989066d492636d671436dd743012b4eac6bbda89809d568257bc961cba891aea92b277f15829d792db86100232d2785b44b28d493ec3037446bcb648c0b4a4a974dbaa4955b06d990948b1fbe2169db00c1eeedf15b4580817b16846e59a76016735d25180a030c7811a9922de51b1696dc00315b09003af28ec09cf4c0259a001d6d5ad4f5254a812392e89633abb5d2a500cec63dd1b06f42e5aa7f03929c7ac5d30f7414b13334a0585a8a6406077a640001b8604033a73dac5b090cdc3d5e42505901a64ef76db70d4ec4ec6c0e43d07de5cc65815b91e9570d0dc348c9a0d56a61c6052510331fdbc01ecec8a995a2a53167dd62a411c1b6ba2403b6749b498b1a0a633da6c680b075b4933180327e41600821c9d07a8b5b1acb0005225696bde2d57f1732646191a2933acc1593b0b3c11751694e1a9353eb35f890888f6d3b8abfa45cfa01328ce99a459ce6b1cd77f68176ac13b265f75b1690e5e8a50004b959a301ba8c54eea77ab7889d2c650f1a48eb08d0a24d4cddf028bf6b8644b5f61b49d9da45277cd88791c6761219ed22a821ae86e764e60651ca6662d49b2d22c6d78c3a6f5fcb69e8120294a4943940da4a9d1895e1d42b0f4880220035e51bd6681817b8882401196a9e71c60a9fb3b51ae98db636d67087c7916b72a58d2056043c65894272206f0d3d1636ca77d58017158fc9053b23c13a9c4ab40b6e74bb356264d61cc980726349bc91f410080bc872160f2935af267a7c0a46b47a48a2caa3e232783e1b535e439ce916902ed5023a88f1aac8b939e1cc3d1af0f417c6e83abe67dec796d0f52f6d608c94e5725a2c33c45a41e8984b08ea7797f33d5b0ed55683d3107616c576080f899a1880d89c8c71ad6ec4e3941360607c42a8206ca3d04b87a5149c52a5343914d88c58018efc5ce13b572181518eb671301e40f97464f49b03d500859ca928a70129f04c0626cb0d4674406001957b16c724b68ab994ad12d0c9b532689e4b254a1d13c04b11e6bc5f4c997461cd79690030526548437616a933e5b4cd99d509a38f5b0f952a5316649395913d310af5b6bd0deeaf2388097f0044f252e47c895a49341f18e1f120e558e009a2766ccbe82aa256723d08f12308045cc20804a44c8fe598cd1c30b4972ea850dcf14d7e5edd2c4600c2d48152eb17cc65cca441e0ad9e88b079c98a6678afba7b54a88ab22259ea23f0d84bd8c82714c529524065e4f49c312063ed51da522fa19582e53b0120a9d073238c0241e9c54350c9cb169241410d91967dccc124a8d7ca7c9e9a656ec892b0238198651f867473501d227446a536d802b8198c78563303167707c83f07af9ad557a5b406a8ab196d63dd2dabf7e8a69e139a318a51ffb624a0a040266f2e2edd981fb492bf215780672d0ada87615845970903429fd8b652b351e4a842c5330f14441096ec580ab9776b1761f28a69ce2c04c7e9185ce4dda1eb94e4a1eb9f46c893a22e534c5342361eeb17198cb2346a18c00209936809c9300c800c322828e6308b9472b190809c8492c33ec201b70003902e5835a3665e48b33b2b3692960ee7492f5e0060000210399d1c9aac761f8a9d816f909580315cbda035be1f05ba2352b8cc2d6c4273aeb2adab2f69881ac688e30f53006e36926e34c0d8fdb14816ddd7bb23556cbc7eb0cbe42b0181d8106cf5b4a82ccc428e91932cd3da7abe919063d08a952530a9d85236a89e5d39b1d551420a721544e259840e70dad09e7300da3a4de5325ba8e7e41f19e0f14aaad214d34a2278d7d3f422b5f89d43d5019635383923ccba538fbbdd1f1f9a4a45c9c647e6204c72ca522206193b01a9e6302604a9f0d21574eda8a92e8921ac6a3f98a6c98d66152be8c901360e01a4038397a3168a3319caf21646516993671e9004da1e919a480693588eb617f310c5a080360cd70931a9dbc568beb3c7b77716a35918306320f22c4ba3741e90876f632082bda347a00fdb592849c9b961b545397c0000fcb076c65cae94e860178560f495a9e266bf23638e68a792de0221f35a31b0b688e18c968981e24071809fb4e1b50ea001c5260b44d6a7086d982c0f07d921e2bc01956ef490a42a9abd52994b102f92bb62b4af459274c8a5eb91a95b0f67790bd9181140a687a3234f2f3d8df42e798ec16b956c1f373bf8689cb4198019b0e9c4d338ef1fe2427c4ed24cc476f2dbb8ad543444c33287f62c8d9008f032d33726b2bd05d8c90bf8c0d40e6b2556e4a8c4f0e742496c3d17590b62c76ba3912ea06a77d50a90f4ad50ce24b033094e301db1ba5541fcdf81c0fe669110ff718568a0000f960e92219843c207b900653ea2b954376005239c43f4ec9e4c40c43357dd455f1f5214c1c8405b42c52c35e310421ac603600b73fc73229f29b5a894a194651674ffaecbedaf54b96f2d451cf296331cc91b1171169e830e57ddffba37e53cc86d8b0895d2bf99f758bd183cdd842697fe770a6dc0006424a721ea7c69938a19d354b49ab49762f9b162f186025627d8993342b9af31548d4952b7c99d3991cda29287a7a34d8d812730282c9d2070b02b2eb51292820761920a290e2b2018baab10e24a105006067286b150fd1b20403a48ec14f21614a3308018fd06eab02ffb2c0770f09e6a804ef2b4231bf988b177bdf9370132da1c8b6d2f98a185e2c63ee27a3d9846b4a3e93ca07c980085b0a00299494054e2572e52da2d7ba60e30ad3a03ddb18a4d2a84952beacf3871e6b011c1bd6a5123687e336b222a23a23940600382e10f01fe3b6af81e221231229211c0521522631a080b1e31933e6bf5275bca17785da632bebd840332994f18c8b0078b2a3e1afb0341787bf07815009c19c224be785a231b04624abc07c17c3dc1983fc202260000132c83c418ca422663420f857f114017ab6b5a044400048cc844ad19d31f33768b93f82185e0acb23d16739302622c3ba32639e190be63705761cf0ca8c046002703f23c9c32cda2890e164a5585e122905b299358006ba96f0c02d7b4d85303f93b0f42ccaad3be87858d3d233f1b604b0bd2a91f2310ac07f02d21960f1a6e8dc76093b0e7002440a6312c1b91226752130603b629f8d59fcb0e860940a86bec71b3c826c9925698781f68e681f8d81d5ad254519404038a166ad836e00026a205f5a42b212b936a33fad834a06874bac71a27988c017d0b003baf20d5977bee1b22ea296209b8aafd0a19e91f510e00e88b98ea88ac33192f3b4d09502a1193e0ba51e6b3913400014b121e0a0189e0a614890c8dbb5e2a235e3ba193a6fa66004684bbb24600012ae0bee24902c5153f5058a9c0a9a6492f1688253ca1f3324a2aab893b30e2d81ba2305861489b7a743b62831b19e33626cf38a0883799603563112d20ac25f284a0bb030b3bcb2950d6be39dc0b338037703f31b08822800e3e45c52f72950839732726f6006979351b5f16fb582921649690722d102f2793526db0539c1bb43491e20b034900d2225024a9936422a7436518818e25f140148adf0dc5a04b8a63b171880a6bd208810496e91622e1f1aca158b9d9490a5b59286bb626441603c751254a381ed0984de1c5a5339e01623872a5bbb6d0a61ce4128ceabe0fd0963253803c68a609e3d0b789b0ba154983ebcb82794d0d834e6633633570664a14953e1a8c9f034247b80e254880b051779358416b594e4ad2321d4b210fa4edbcb2059a11e06606862aeb4e87086152a4815052a7b23217174b92844acf2b1ad17cb2791980f16d83e45321ba3ee0f53f93050552de51684cb358fe7e18621a215807a2b782025c80e3c42ff9b2a93b491df2aa7dabc29b7bd02a49779d86b408aa4a5a4ab966c868bfc7a698a4ba7258c95c388b82e7e68407520802f7a6a6487993d203b9341d854a035384ae27430c93596beb8033a7317542d7b839e51407650ef3f13c06b24be527b3b32d2743f90c7a3236e7d142c8b63ad2d18a25e534f3270c29129600ebaf14b022871478fb3412129f994a920f150981c6b27560fa7fa86b0fd29504728a81115e502000072da2f213cbc322c2064589de218b9292a73d16c07a3e5577bd9977a7910baa549163e3f818fbda9873541686766403188ad0007626164f577a485bd70897a4367b6227f27e38c45a117897a660f278fa4646049b3867652d337193820f36c09e0c35190614a794e4b63650b225d736666179b352b04b5922a522000a010003f46a0daaac1d580a6a56ad0090859ca3c635e11c51615913b1dab6525f1ba09c4ba2b617a13f0133dfaca30519300b23536ca4a34a2449cc4205870882deb2f9715362173172be9e13ce78036649e7dabd89ed375982646acf3990b95dc3dfbd66647cc93429c3e93ee04aa6f1dfad20003f25227eb4d9618d878ea44009830122ada0475813b55b23c8b166b438a22b4f557601a2b42f21983a930a06d1c4b19046a1b0fca330d044d5951eb49aaeb74e84d22931b24748f94d8600960f30f6ad119d08925c8f02498231b4be197a5762d83a91e87d098ca4e1a6b4e4759651ce68d1bd8881668fd330130bce24e18e09a87552b70b6647676ab3fb27ea5a5859f704abf699e6b41896f910310f28a23e32c2ecb2585ead1ba76749d80b05a182a0b22da7be9a125819e0209933fc88a4990350269c7a7a64d54a098afe32522283558a0ecb4a02570ba6e35439476a0f56da0fa0f439f69e53d3492e0b3c8551a59e04065e66c08ca78a0eb4b33b0ac1ada2867b30936ed5863fda38adf6dd07a16eb2338e22c29218db802e0b652e231c4a393b1b417647aa67b5442368c7235182a35b6ada1f27df9323c875817796ead7add7318f02548ea5b21ba4b366e3b34d03c0b3c9f2178a2482c135bdb8208a0dbd5ce4f71450881282d813c7cb42022b4468d0c90d793b63e92313b51fa4781b21f031967a21ea106c56ad0b09742808a94882d12c4f5285e09a9b739d57d3ba00d0cd53b3d2189700981b303d072720b4ad54c25a76e000214003c8441403292018e33a8bca6f0a1b2408f90112d206abf71e06ed12c8f42c8bd032119e87a311380318b1e1077428bd17cab41ab46732700021230c2031f12a36a2bbb3b007088048aff50a82ca730c0130edd04662bae904f263b461d93f8a286b4a31291ae8e860f693e3f80370c8fc3436ae79368344b69ff14c6da27f92c19e26d9ecff1498f92a604c8868e1304a33e9383624a70eca89bb28c01b35d4f983bb424c6d0d03123b315833a4f32fe6e710314c3962767f2b2cfb411557636b01e730233380a718272e62ad0e738f1b21e14fd3f813cafa372ded60504e2fb9763cd2e8dcdb2eb4aa9115b7819aa87a0b0fa8cfa9381d80eb6a4b6e17008806ccf00206198e684a97bb24aab3c5b6a2569ab1951d7252c2ab57977b37b490302818551b1a9af2f18e3d04e51db06036e2768bb5362534dc5b9010c0720daac393070680b0cb7a588765388fcb27abd1b951c05e297e747404a400602e8792a16b388356daa2283f3e3043b3973a8b02ec40a17afe1bed73cf918fb41777922ea5fb4a328975356ceb1e21933070518b66d95f128f474d779e955f776337be16133f819409eac04f52eb5f5b472f380fbe4c6d975a544e7b545e7b7f128e02d3b2e20c8b999bcaac0ad33cde656915ba491725f1a8006d17a9e71767212ad66a4c6e66135bb49d647714ef42bb0abf6d803d2c63c33df9632b902d4bd13d082f0356c5e4fcb0626394a03428f931db6f96c1078790589e976a2f100336e31f46703294717abb2381e6635c8ac47b719305a1ea055417059c58f152b76f97029669227f85e2d11668063e57ced6f9e1c0aaf1b2453624a1308bce7a1c92288999b993583d3060d626eb2805e98e13704e28cd76b6a3e71cf80b65817911e0354b29930b78908e7640ca10e0fff54e33903d2d7a9e46d9e62805bd61a52e10e05090f9cae0185880e2a3208a9f2cba3294fadaa743510892af7d1c750f423d947a6a7efa06d3b9797d2bb1e6616e9372f2bc58300dd149b470b150ee0f7639856eb1fb3ef66e90ec8da992529d266818b0800082c4f1b3a0d4297486a797b301b21398c676d97923d8fd0be3e9806806222789927bd435a670f4616ea55f279c0d6a704bd21fa03d351f42d4d1c909a54a7cb156b4699f66c7bd23ac06df04d582f0bab2f45e21241ce7906e3ca4c879e53b1b4e18bb0b6e398d4a26ebb6c6d168ae37ba1cf8a2870d2dd389c631c69ba6611cab12cca7cd681c8cfcef85fcf223a90083c19302f483829d2132481e00480e5183c43e625630be6f000835e2a81103602901e02da0000180009048283c60383f861d80380640c0113ca3c2a1a3d982a81e3d3c0100383380a02b80c008c7c37d3fb82641d00303307b00103ab1901903131766c83f8131ae72d81c3c700d0ef61082520412d4c4030402a12804126f8bc30032bf981401403c40403920640643c6ab01c81f026f1943002c83ac8642fc14a3abdb8c6406c102000330640f24003eb68000348001a8001b08031d4003a88006c3c80ee1283bbe3037bc0006800270f027ea7ea5a140238041190263c8bd902d358c7392e031c98c31ca582559dbd442601cbe502280a825204821c38f5b218cb683a56523bbc002b284f37c59011ba0125a52107f77d37f580b7df034c64d080c2a077c8fe502a826f862188037e1c39bd4029cab60602520f44000b284d17a7e930844f2bd66a492d816beafd7671309b08812bcc00abdabc6bc5ffcfe6fba7100cafe681afc6fd6fcc01020f47effec10fe0b030009fd9f4e7f509b25898c6007ef81bcc309481df80001937c0bf0e0004497e3ff46fa7fcbb2dff4a409d42012382d22e03ffe97f56035fd5b877f07fb3bd35e1c014065008bc1ff2cc0102401bff6205603580380dff9efd0e007f23fb3022084ac1ec2380840cff4e01afcc818af657b6803da100588286475c220ca03f1c300b310583ebdc902084ef8d0337c4d106065012015a400f87f5d9033f5ff9cfd1815992d224fd80637b1102e02101480ad047012c0d603b02e829c0d80a4026fc881f808b0740207e7009800f441c19a01e0700340167f0505ae083ccaf4020601841c80cdf093cc9ebd237044b4c20eb16578e311b65300c02442bfe9e09ff9ffd4268a058063003bec10ce018811c05004a4054328064c3e01a82600750e763e80801c7f7bfa9fd31c910d003443efeb10f88638373ea2f60c95806205c01a0313125e3ba59795003506806d4342185e64020000) 

**Expected behavior**
can remove the space in that child element or can set lineHeight for it (I tried but without success)

**Comment by mfucek** [comment]
I tried setting the lineHeight to a percentage, and it worked:
```
{
    lineHeight: "100%"
}
```

Funny enough, setting lineHeight to a "px" value hangs the whole page 😄

**Comment by luudv** [comment]
> I tried setting the lineHeight to a percentage, and it worked:
> 
> ```
> {
>     lineHeight: "150%"
> }
> ```
> 
> Maybe just encapsulating it with quotes would do the job, as (I think) it is mentioned in the documentation.
> 
> Funny enough, setting lineHeight to a "px" value hangs the whole page 😄

yes, I also knew how to make it work.
Thanks
