### ISSUE TITLE
Error IMG and Properties Undefined Width 

### ISSUE THREAD

**Issue by TomasSalas** [diegomura/react-pdf#2461]
Error de en una propiedad Width y error en una Image 

<img width="537" alt="Captura de pantalla 2023-12-14 a la(s) 16 55 00" src="https://github.com/diegomura/react-pdf/assets/57121296/c0d458c9-b082-4f18-805c-3104c0a04cb5">

**Comment by TomasSalas** [comment]
<img width="812" alt="Captura de pantalla 2023-12-14 a la(s) 16 55 45" src="https://github.com/diegomura/react-pdf/assets/57121296/ff65aae0-f059-4517-8991-062e7cbf2104">

Esta es la implementacion de las imagenes :)

**Comment by diegomura** [comment]
I'll need an image to test

**Comment by diegomura** [comment]
Has been incomplete for a lot of time. Closing
