### ISSUE TITLE
In pdf not showing Trademarks symbols like " ® ™ © "

### ISSUE THREAD

**Issue by Ekant-Ashish-Tyagi** [diegomura/react-pdf#2462]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [^3.1.14]

**Comment by diegomura** [comment]
Fixed by https://github.com/diegomura/react-pdf/pull/2496
