### ISSUE TITLE
Questions about usability / rendering

### ISSUE THREAD

**Issue by Joshuad2uiuc** [diegomura/react-pdf#247]
I have a couple questions about the library.

1. How does the library handle page breaks that cut off information, is there a way to make sure that something like a bullet point list will not be split?
2. How much control do we have over the images and how they render in terms of size and relation to the page?

**Comment by diegomura** [comment]
Hi @Joshuad2uiuc 

1- The current stable version does not support that, but the outgoing v1.0 will. would be just adding a `wrap={false}` prop to each component you don't want to wrap (or "break")
2- Almost the same one as the web. You can use css fixed dimensions, percentage, flexbox, etc.

**Comment by Joshuad2uiuc** [comment]
Thanks for the quick and good response!

**Comment by diegomura** [comment]
Hard to tell. I want it to be ready asap, but couldn't find time yet

**Comment by Joshuad2uiuc** [comment]
Is there a manual work around right now if I was to do it, and then just update it when v1.0 is out?
