### ISSUE TITLE
Problem on table page wrap

### ISSUE THREAD

**Issue by Cosmin-Mihaila** [diegomura/react-pdf#2470]
Hello! I have this annoying bug where I need automatic page wrap.
I have a table consisting of VIEWs. When it is on one page, everything is ok. But when I go to several pages, the last page is ok, but the other previous pages have this small GAP between the components. The side border of the table appears ok because it is on the entire table, but the borders between the columns in each row have a small partition. I noticed that the GAP is done automatically when switching to another page, even if I give the table GAP 0.
All rows have wrap={false}.

CSS: 
 table: {
      display: "flex",
      fontFamily: "Roboto",
      flexDirection: "column",
      width: "auto",
      borderStyle: "solid",
      borderColor: "#D3D3D3",
      borderWidth: 1,
      borderTopWidth: 0,
      borderBottomWidth: 0,
      borderCollapse: "collapse",
      gap: 0,
      alignItems: "stretch",
      flexFlow: "row wrap",
      fontSize: 0,
    },
tableRow: {
      margin: "auto",
      flexDirection: "row",
      width: "100%",
    },

Any ideas for a solution?

![image](https://github.com/diegomura/react-pdf/assets/57093643/0502f3c9-788b-4000-932a-589375a53911)

**Comment by diegomura** [comment]
Please provide a way to reproduce this

**Comment by diegomura** [comment]
Has been incomplete for a lot of time. Closing
