### ISSUE TITLE
Text component nesting bug

### ISSUE THREAD

**Issue by antonin-arquey** [diegomura/react-pdf#249]
**OS:** Linux 4.13.0-45-generic

**React-pdf version:** 0.7.6

**Description:** 
When you nest some Text components (one is enough), the text after the nested Text is wrapping in a weird way over the text before the nested Text (see REPL).
The documentation say so it should work.

> Text supports nesting of other Text or Link components to create inline styling.

**How to replicate issue including code snippet (if applies):**

[REPL](http://react-pdf.diegomura.com/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618023100137802e1859b0090016da8500e6012cc3f00ac001800d2b18017c55b768802bb27e82d8c50884057e01c9b5e8baad733501280373337a122c2e2180618f554007800447c744590c0a000f954d9020015a82590e0a400bd91d0008801040059b3628de200d4a59001dce17051d118105021493878d58a4a608502005590003c62b040223911a98001ac60e906617a07611ab21b6b505b7591db8747ad5366a10201e8fb07a2617225a864600085c6a6614f0e4f163a4b8fcaabdfe68e92523ac750b01c29118b305c6e00128d1805004b040062a42a180b8c80a3d1bcc04850000)

**Comment by johanventer** [comment]
I have created a PR which resolves the issue for me here: https://github.com/diegomura/react-pdf/pull/256

**Comment by dariuszpaluch** [comment]
I have similar problem with nested Text

[PERL](http://react-pdf.diegomura.com/repl?code=140630f60760ce02e004013308e05e38029801e008b2057016c05308600f98386b9b001404301cc4eb69aa012c02f1350044010400b00f61d6004f0036fc037bc891ce0007460811708cc0171c004c001800d328e00cce400f5c5c013891030ba47d01c9c0ce211dd995b400468c2000d6ccf66004100800c2603260f61e00c400621999eee67000beb93900eef68caa39495c64308c2e9082328c315020a524e21c540134d8006a9585399230b20a4a5d2a5a50aa0d521e5624d67e832aea9adacc00426030306044fa00cca6cb96903000cabc24fa008c06277905e39de374002a0b940032492444705c551418870002d3bd3e70691c9508a0b19d2e7c7d01800ac2638178921e40b7848ee7c85071041236000f41f6b250103546192299465992fa24428bc02bd7e83da1a3078d126d3462cce0ee79a2dfcaf1a2acb43a2d8ecf6876384a68f0f2223ae701b800381ef9659b2bad87a5438630c50621258e14a444004e001b001d902227c6e4283f473fd01c0a21d33efa8e133fa01da07259c691ac3e4882e14c66731b1f8e0a2bb2399cae0807922855748703ccc28474dd19545caeb75339b12c92b4a2d275bb4da93852e02060000b0f11c00a4ee479e65486c840e02020f5fc014090521ab50ae3c118a4183a3c0d0270c04830023d8e01a406c640eb3809064f3f45404808441818f5c0214088602bc6e88aa24af368da43d6810d178011e0069025f98f7806710288160204617753c004702118000e8e000155e0320b87f834380886d0b0b8000374c31774410d8ce0080c0581ec020100fc68058487b10f6a96a080e00206406888700e02022a28128d8cb84e3e021d2922d4652cd5644d12ad2d770893c409652fd4a428734d70426a1437002028c6000920015a31c063af59db43a0be6d14228458c11c72f4a7220047757e1727d3256c881420a11c5511c76cc804198f9c010e30884808550d893388d3c30a802f0c4b86e3a70b51c63c0864c08660b81a928ae21a351187b10aaddec2422c80145ac1004838a486dce7720e06405a2708a90162d6c69780a88e282b015b2a9cf3fd228c4b8f50e07223a8b02c2e10f182c28bd68f202cc7db888b1a0235b63d607e31860368a2090f68957521909483164473a00b292a364c1172c354ad311addc148eb06c9b7445b36d3b6140e1457b7ec3f0926ea546831d3cc9c7d4b29239c1725c574802f6713756af75500f23c4f33ca14bdaf5bdef47d9f3f8df7b02cafd5b56d268038ed3a4ccdd91ecb20e61a0d82b81d250f438f080089c2f0e17fe62385d22e683284aa268ba22ca6258f9c6a0cd38ee3173e2048aae5912c4de7c8d518f6b18f183c0221299bd570bc74980f4d97776334cedcd8586f92caa6c0b82d0bc2f81ace8bbc38a6a04a89e4b52c3c32ff9c0eca5abca0aa2a2012a60f502a9a9b71abddb81eac6b9ad6bb876b3ac61baf817afc7a936328c80d4488c6f2026f6bacdea6459be6b0116e5b0ac404875aff2da1224b77716012bc7bc024ea49880baa1f25fd078eed65e7a7bb917a64f7a6e4fab2d48feb491b66d5b0ecbb706fb024a1fa41e8e1e1cf511ccb676e0d1cdc31b5db1aab772d1f1e6909a4bcf526907261f27c7005f0d33a6101bf23376accc759b33025944c9731e68c1e0a2101618587a8b7c212c489103228ede58c05a2f44b3b2b5626adabb275e237875851616dc00d920be60658d82c336e692d93e6b698c481db0768659d8385761646397b26a3ec621fb29a81d62bc522261d0e84774ade1a39c09caf1d2ab154d6654d39554ceeec739350dcf9db43c022e25da6b9701a55d86ad730af5ca124d26e334609b70ee2b5bbaf74da59db6a0f3da5e94791d1d653d2eadd59e1a5e7a9202c03817bea3244c1580bc324f817aa9072054000250006e600c000012890108301e82e03484851c388fb0180900804c9c00800)

Style in nested <Text> component in View > View don't work.
When I remove ```flexDirection: 'row'``` from View, style to nested Test is apply correcly.

**Comment by diegomura** [comment]
Try now on the REPL. It's fixed. New `1.0.0-alpha.7` version.
Soon releasing the official `1.0.0`
