### ISSUE TITLE
Cannot find module: 'yoga-layout/sync'

### ISSUE THREAD

**Issue by sachindabadu-ai** [diegomura/react-pdf#2492]
using "@react-pdf/renderer": "3.0.0", where a sudden issue has raised.
 
 getting this error in building of the react project.
 
 ```.js
./node_modules/@react-pdf/layout/lib/index.es.js
Cannot find module: 'yoga-layout/sync'. Make sure this package is installed.

You can install this package by running: npm install yoga-layout/sync.
```

**Comment by diegomura** [comment]
What are you using for building your project? Seems like it's not picking up the `exports` values of yoga package.json [here](https://github.com/facebook/yoga/blob/release-v2.0/javascript/package.json#L12)

**Comment by sachindabadu-ai** [comment]
is there a minimum node version requirement for yoga package?

**Comment by diegomura** [comment]
Not sure, but node 14 reached end of life. I recommend bumping to node 18 at least and try again. Not familiarized wit craco. Might be using an old webpack version that do not resolve `exports`

**Comment by ProgrammerLakhan** [comment]
@diegomura, is there any way to resolve this with Node version 14.21.3 ?

**Comment by sachindabadu-ai** [comment]
@diegomura how this effecting us when we have not updated the `@react-pdf/renderer` version?

this version `3.0.0` has been working fine till now, if we have not update the version it should not effect us right?

**Comment by sachindabadu-ai** [comment]
no, currently we only use `@react-pdf/renderer`

```
./node_modules/@react-pdf/layout/lib/index.es.js
Module not found: Can't resolve 'yoga-layout/sync'
```

this is the error we are getting even while trying out in local

**Comment by diegomura** [comment]
@sachindabadu-ai you clearly updated the react-pdf version (some of it deps)

**Comment by sachindabadu-ai** [comment]
```
"@react-pdf/renderer": "3.0.0",
"react-pdf": "5.7.2",
```

we don't even use `^` to avoid update, can you help us with any particular deps that could use this.

**Comment by dgrigoriciuc** [comment]
Hi! I have the same issue. It seems to be something related to `@react-pdf/layout v3.7.0`. @diegomura, could you take a look, please?

As a workaround, I added the following line to my `package.json`:
> "@react-pdf/layout": "3.6.4"

**Comment by diegomura** [comment]
Yes. Newer version changes yoga-layout source. We had a local copy of it that was impossible to maintain and also very heavy. We are now using the official lib again, that uses `exports` in package.json to define entrypoints. 

Using prev version of layout version will work but it's just a patch. I recommend switching to newer node version and bundlers that resolves `exports`

**Comment by dgrigoriciuc** [comment]
> Yes. Newer version changes yoga-layout source. We had a local copy of it that was impossible to maintain and also very heavy. We are now using the official lib again, that uses `exports` in package.json to define entrypoints.
> 
> Using prev version of layout version will work but it's just a patch. I recommend switching to newer node version and bundlers that resolves `exports`

@diegomura, I will try to do this in the future. Thank you!

**Comment by sachindabadu-ai** [comment]
@dgrigoriciuc thanks, this solution worked.
