### ISSUE TITLE
No native wasm support detected - issue on startup

### ISSUE THREAD

**Issue by Conorfu** [diegomura/react-pdf#2493]
**Describe the bug**
We've recently upgraded to version **3.1.17** of "@react-pdf/renderer" but are now getting the following error when starting our NextJS app:

` /Users/xyz/project/app/app-name/client/node_modules/yoga-layout/binaries/wasm-sync-node.js:11
process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",function(a){throw a;});l.inspect=function(){return"[Emscripten Module object]"};var ja=l.print||console.log.bind(console),q=l.printErr||console.warn.bind(console);Object.assign(l,ca);ca=null;var ka;l.wasmBinary&&(ka=l.wasmBinary);var noExitRuntime=l.noExitRuntime||!0;"object"!=typeof WebAssembly&&v("no native wasm support detected");var la,ma=!1;
`

Specifically this error is highlighted: **no native wasm support detected**

Upon inspection of the package-locks, it appears that the "yoga-layout" dependency was introduced as part of "@react-pdf/layout" **3.8.0** which is throwing the above error. We're using NextJS v13.5.6, Node v18.18.2 if that helps (using webpack 5 I believe)

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Bump @react-pdf/rendered version to 3.1.17 in a nodejs app and install, v3.8.0 of @react-pdf/layout is pulled in
2. Start the app using `node server/app.js`
3. App fails to start with the above error

**Expected behavior**
The app to not crash on startup

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac0S
 - Browser: None
 - Node version: v18.18.2
 - React-pdf version v3.1.17

**Comment by jhgeluk** [comment]
@Conorfu I'm also experiencing this, do you still remember what the bug on your end was?

**Comment by theskillwithin** [comment]
I am also experiencing this. what was the bug!?
