### ISSUE TITLE
how to install using NPM?

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [diegomura/react-pdf#250]
how to install with npm ?

i tried npm install --save @react-pdf/core.
but not worked.

**Comment by diegomura** [comment]
It's on the README:

```
# You should always install the core package
yarn add @react-pdf/core

# And also the bindings that you need
yarn add @react-pdf/node
yarn add @react-pdf/dom
yarn add @react-pdf/mobile
```

**Comment by diegomura** [comment]
Sorry.
I just tried `npm install @react-pdf/core --save` and worked correctly. Please give more information about error messages or behavior after installation

**Comment by nilaybrahmbhatt** [comment]
![capture](https://user-images.githubusercontent.com/6310631/41914042-89637408-796f-11e8-954f-342306b5064f.PNG)

**Comment by diegomura** [comment]
Your problem is with yoga compiling, not npm. Please refer to #244
