### ISSUE TITLE
Module not found: Can't resolve 'yoga-layout/sync'

### ISSUE THREAD

**Issue by jjose230391** [diegomura/react-pdf#2500]
**Describe the bug**

Hello, I'm experiencing an issue when installing "@react-pdf/renderer": "3.1.17" and "@react-pdf/layout": "3.6.4". It's showing the error "Module not found: Can't resolve 'yoga-layout/sync'." I'm using Node version 12 and react 16.13.1
help please!!!

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/2499

Why would you open another issue after commenting in one that's exactly the same as this? Please help the project to be organized :)
