### ISSUE TITLE
Module not found: Error: Can't resolve 'yoga-layout/sync' in '../node_modules/@react-pdf/layout/lib'

### ISSUE THREAD

**Issue by ThaiDQ-FE** [diegomura/react-pdf#2501]
Hi guys.
I'm using node version: 14.17.3
Yesterday while I deploy source code and get error in aws ec2 like this:
[1m[31mERROR in ./node_modules/@react-pdf/layout/lib/index.cjs.js
Module not found: Error: Can't resolve 'yoga-layout/sync' in '../node_modules/@react-pdf/layout/lib'
 @ ./node_modules/@react-pdf/layout/lib/index.cjs.js 16:11-38
 @ ./node_modules/@react-pdf/renderer/lib/react-pdf.browser.cjs.js
 @ ./app/containers/Report/ListDriving/ListDriving.js
 @ ./app/containers/Report/index.js
 @ ./app/containers/Report/Loadable.js
 @ ./app/routes/index.js
 @ ./app/routes/mainRoutes.js
 @ ./app/layouts/MainPage.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js[39m[22m
Child [1mhtml-webpack-plugin for "index.html"[39m[22m:
     1 asset
    Entrypoint [1mundefined[39m[22m = [1m[32mindex.html[39m[22m
error Command failed with exit code 2.

in the past, it completely succeeded.

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2499
