### ISSUE TITLE
Is it possible to iterate <Page>?

### ISSUE THREAD

**Issue by jhunexjun** [diegomura/react-pdf#2503]
My use case is I want to iterate through the `<Page>` so that the whole document which starts with the header down to the footer will be rendered depends on array length.

I tried something like
```
return (
   <Document>
   {
      props.scheds?.map(sched => {
         sched.technicians?.map(
            <Page size='LETTER' style={styles.page}>
		<HeaderIndex {...props} />
		<Schedules {...props} />
	   </Page>
         )
      })
   }
   </Document>
)
```
When I do that, it produces an error.

**Comment by diegomura** [comment]
What error?

**Comment by VikasRajput-18** [comment]
can i work on this issue?

**Comment by diegomura** [comment]
Yes of course

**Comment by VikasRajput-18** [comment]
in which file this issue located?

**Comment by diegomura** [comment]
I'm not sure what is "this" as it's unclear what's the error in this ticket

**Comment by jhunexjun** [comment]
This is the error:

<img width="875" alt="image" src="https://github.com/diegomura/react-pdf/assets/6801369/9d82971b-0876-4d1e-bf93-70ed898e81d9">

**Comment by diegomura** [comment]
That does not give much information. Please provide a way to reprod, ideally using site's REPL

**Comment by diegomura** [comment]
Has been incomplete for a lot of time. Closing
