### ISSUE TITLE
Docker build not giving error ERROR in ./node_modules/yoga-layout/src/generated/YGEnums.ts 10:7 282.5 

### ISSUE THREAD

**Issue by gaphel1** [diegomura/react-pdf#2506]
**Describe the bug**
During docker build we are getting error ERROR in ./node_modules/yoga-layout/src/generated/YGEnums.ts 10:7
282.5 Module parse failed: Unexpected token (10:7)
282.5 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
282.5 | // @generated by enums.py
282.5 | 
282.5 > export enum Align {
282.5 |   Auto = 0,
282.5 |   FlexStart = 1,
282.5  @ ./node_modules/yoga-layout/src/entrypoint/asmjs-sync-web.js 9:15-46
282.5  @ ./node_modules/@react-pdf/layout/lib/index.es.js 13:0-36 1536:44-57 1537:46-61 1538:47-63 1539:45-59 1996:42-55 1997:44-59 1998:45-61 1999:43-57 2057:48-61 

**Desktop (please complete the following information):**
 - OS: [ MacOS M3]
 - "@react-pdf/renderer": "^3.1.14",
 - "react-pdf": "^7.1.2",
It was working fine till 3 days back. We are using it for project now we are unable deploy from docker image. Any suggestion is very much appreciated

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2499

**Comment by gaphel1** [comment]
> Duplicated: #2499

we never migrated from  3.1.14 to 3.1.17. and we are not using older react npm install @react-pdf/renderer@3.0.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: easm-frontend-app@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6 || ^17.0.0" from @react-pdf/renderer@3.0.0
npm ERR! node_modules/@react-pdf/renderer
npm ERR!   @react-pdf/renderer@"3.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/tenzingaphel/.npm/_logs/2024-01-18T11_29_34_164Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/tenzingaphel/.npm/_logs/2024-01-18T11_29_34_164Z-debug-0.log
