### ISSUE TITLE
Unable to hide scrollbar in a PDFViewer

### ISSUE THREAD

**Issue by NumanAnees** [diegomura/react-pdf#2513]
**Problem**

I am displaying a list of PDFs, and I want to ensure that the PDFs do not show a scrollbar even if they contain more than one page. However, currently, there is no apparent way to hide the scrollbar.

https://stackblitz.com/edit/vitejs-vite-sjxjiz?file=src%2FApp.tsx

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : chrome
 - React-pdf-renderer version: 3.1.14

**Comment by diegomura** [comment]
The browser controls how the PDF is shown there (it's like right-clicking a PDF file and choosing your browser). This lib can't control much of that experience, and as far as I'm aware not scrolling. If you want a more custom pdf layout you can try something like https://github.com/wojtekmaj/react-pdf

**Comment by NumanAnees** [comment]
Thank you for the clarification.
