### ISSUE TITLE
Installing mobile package end up with "not found" error

### ISSUE THREAD

**Issue by mitkpl** [diegomura/react-pdf#252]
**OS:** Windows

**React-pdf version:** 0.7.6

**Description:** I am trying to install `yarn add @react-pdf/mobile` but it ends up with "not found" error

**How to replicate issue including code snippet (if applies):**
1. Run `yarn add @react-pdf/mobile` in some CMD
2. Error appears:
`error An unexpected error occurred: "https://registry.yarnpkg.com/@react-pdf%2fmobile: Not found".`

PS. I've changed main dependency according to this #251 , I don't know if it has to do with something, but I thought I will mention that

**Comment by diegomura** [comment]
There's no ` @react-pdf/mobile`
Please check this: https://github.com/diegomura/react-pdf/issues/243

**Comment by mitkpl** [comment]
Ok, sorry
