### ISSUE TITLE
Some styles (border) don't work in render props

### ISSUE THREAD

**Issue by Mudbill** [diegomura/react-pdf#2531]
**Describe the bug**

When using `<View render={() => /* */} />`, the rendered components fail to apply certain styles such as border. Font-size still works however.

**To Reproduce**

Create a component with styles such as border, padding, margin. Render this component directly in the Document and observe that it renders correctly. Then move the component into a render prop and observe how the border disappears, and the margin and padding also acts a bit strange.

```typescript
const TextWithStyle = () => <Text style={{ border: 1 }}>Hello</Text>

const PDF = () => (
  <Document>
    <Page style={{ padding: 30 }}>
      <View render={() => <TextWithStyle />} />
      <TextWithStyle />
    </Page>
  </Document>
);
```

Link to [react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00402a053007940ea04b2802c0ca5027803608c02f0c00500946407c9405030c00f2228cd110a9037af309b361008c40027002609c402e1801188405f65b487300900024121422084b00f4eca3aaa0c1a848b00228057744841412e5a9d46cc5801110c00e00b60860e61aac000a008600e6245cc47c02000ed19292e860b1f200cc000c30aaeac2c22c006ae80800ee30e2a1d2e27c9ea4f46cc86898b804c430c6b4ca7d25a5ac6618d878dc43112631f1c326fe8121611600dc56004a08d1c05091be00620074f5608d142c8eceae24fd541b400000) 

**Expected behavior**
I expect components rendered in the render prop to act the same as components rendered directly as children. If there are limitations, I expect those to be documented and warned about.

**Screenshots**
From the above code:
<img width="632" alt="image" src="https://github.com/diegomura/react-pdf/assets/8832665/9ffb78c7-b446-4427-864e-e6fcabc3cb0a">

**Desktop (please complete the following information):**
 - OS: Any (in my case macOS)
 - Browser: Chrome
 -  "@react-pdf/renderer": "^3.1.17"

**Comment by jrtell1** [comment]
I also noticed that `fontFamily` isn't working either, which is a problem when a certain type of font is required for machine reading :P

**Comment by KYZNCODE-Sebastian-Roese** [comment]
Related to this: I think inside the render props styles are not propagated to children (e.g. setting fontSize on a View does not work inside of render)
