### ISSUE TITLE
3.3.1 can't resolve fs

### ISSUE THREAD

**Issue by rammoozz** [diegomura/react-pdf#2534]
**Describe the bug**
updating from 3.1.14 to 3.3.1 causes error
```
 ⨯ ./node_modules/jpeg-exif/lib/index.js:3:0
Module not found: Can't resolve 'fs'
```

**Comment by eialanjones** [comment]
did u found a solution?

**Comment by eialanjones** [comment]
This solved my case

webpack: (config, { isServer }) => {
      if (!isServer) {
        config.resolve.fallback = { fs: false };
      }
      return config;
    },

**Comment by rammoozz** [comment]
> This solved my case
> 
> webpack: (config, { isServer }) => { if (!isServer) { config.resolve.fallback = { fs: false }; } return config; },

Yes this is what I ended up doing, I wasn't sure if that's appropriate solution but it works!

**Comment by ytreister** [comment]
> This solved my case
> 
> webpack: (config, { isServer }) => { if (!isServer) { config.resolve.fallback = { fs: false }; } return config; },

Where do I insert this code?

**Comment by michaelcais** [comment]
> > This solved my case
> > webpack: (config, { isServer }) => { if (!isServer) { config.resolve.fallback = { fs: false }; } return config; },
> 
> Where do I insert this code?

I added the code in next.config.js as [documented here](https://nextjs.org/docs/app/api-reference/next-config-js/webpack).

**Comment by benAzouzYassin** [comment]
> I'm using craco, adding this to the craco.config.js file resolved my issue:
> 
> ```js
> module.exports = {
>     // From here
>     webpack: {
>         configure: (webpackConfig, {env, paths, isServer}) => {
>             if (!isServer) {
>                 webpackConfig.resolve.fallback = {fs: false};
>             }
> 
>             return webpackConfig;
>         },
>     },
>     // To here
> };
> ```
i keep getting an error when building...
![image](https://github.com/diegomura/react-pdf/assets/109908376/2a2d09f5-5d71-4191-b83f-11af701d7162)

**Comment by benAzouzYassin** [comment]
> > I'm using craco, adding this to the craco.config.js file resolved my issue:
> > ```js
> > module.exports = {
> >     // From here
> >     webpack: {
> >         configure: (webpackConfig, {env, paths, isServer}) => {
> >             if (!isServer) {
> >                 webpackConfig.resolve.fallback = {fs: false};
> >             }
> > 
> >             return webpackConfig;
> >         },
> >     },
> >     // To here
> > };
> > ```
> 
> i keep getting an error when building... ![image](https://private-user-images.githubusercontent.com/109908376/300295581-2a2d09f5-5d71-4191-b83f-11af701d7162.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Nzk2NTUsIm5iZiI6MTcwNjQ3OTM1NSwicGF0aCI6Ii8xMDk5MDgzNzYvMzAwMjk1NTgxLTJhMmQwOWY1LTVkNzEtNDE5MS1iODNmLTExYWY3MDFkNzE2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQyMjAyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmI5MGFlMjE0NmNjZmMyYTdmYTgyMzc0NmI0MDVjNDQzNzcyZmVlYjAxNjdjYjRmMjU2ODNmMjhkOTBlMmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vswtKev5X3b2S_fOn4cufzt-GLuc0VP6pV1Ce30KK68)
solved by daynamicly importing the component while disabling the ssr
```
const Pdf = dynamic(() => import("@/components/invoices/template1/Pdf"), {
    loading: () => <p>Loading...</p>,
    ssr: false,
    });
```
