### ISSUE TITLE
Is there a way to group records with total in each groupings?

### ISSUE THREAD

**Issue by jhunexjun** [diegomura/react-pdf#2537]
I've read the article but looks like there's no way to make a report same as the attached screenshot?
I just want to make sure.

<img width="581" alt="crystal_report_grouping" src="https://github.com/diegomura/react-pdf/assets/6801369/f2ebd229-2a61-4dc7-b5f4-a0a84140c282">

**Comment by diegomura** [comment]
You can using flexbox. There's no Table component or anything like that
