### ISSUE TITLE
obtain aspect ratio of portai image

### ISSUE THREAD

**Issue by ribx** [diegomura/react-pdf#254]
**OS:**
Dev: Gentoo Linux
Prod: Ubuntu

**React-pdf version:**
@react-pdf/core@0.7.6

**Description:**
I have different sized images and I want to fit them in a predefined square by respecting their aspect ratio. I could not achieve it through any combination of _width/height, min*, max*_ or _auto*_.

If I give a width and a height, the height is ignored. Right now, I have a container View with the width set and give a height directly to the image. This results in scaling every image to a square.

I think the problem lies somewhere here in this function, but I don't understand exactly how it works, as it is used as a parameter to a yoga function:
https://github.com/diegomura/react-pdf/blob/master/packages/react-pdf/src/elements/Image.js#L28-L48

**How to replicate issue including code snippet (if applies):**
```javascript
<Document>
  <Page>
    <View style={{width: 144, height: 144, borderWidth: 1}}>
      <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/" +
                 "Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/ " + 
                 "800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"/>
    </View>
  </Page>
</Document>
```

**Comment by ribx** [comment]
Please also note: CSS respects the aspect ratio if you give a width and a height to an image.

**Comment by diegomura** [comment]
If I understood right, this is fixed now.
You just have to define the image this way:

```jsx
<Image style={{width: 144, height: 144, borderWidth: 1}} src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"/>
```

Please check out [REPL example](react-pdf.diegomura.com/repl?code=3187b0760ce02e004026260c0bc300500a06300f00451015c05b014cc2803e2db5c005010c07353adb69c049639d2668027801b52c80379880ee012ce14001600b860046002c6a00d0c79a5a53795197aad3001188004e714a580eab217180becffa5e0c801121a8001c211401e88308fc844018e000e86401ada4c8e1a419a2ac9883e3a4fd49921883418989c020821448cc8348ab80820165c01801f40065a420180148009801849acc055b491bac409ae19a00d5a4c181a47bfa00cd2c41889b7bba0094ea00c49b2d48a0410981746200acfc3200380018eefc003c01681ac19ada3b1606865a463e6309b4d66f31f8acd61b6d9ec0e471399d72d12b930bc4136070828c163a270410230048e42a0600094006e0c060b6a406300a0743c2eda287300d92c6804301c918200000)

Please report anything back here if this is not what you meant. Closing the issue until then
