### ISSUE TITLE
Module not found: Can't resolve 'yoga-layout'

### ISSUE THREAD

**Issue by betofrasson** [diegomura/react-pdf#2543]
I'm having trouble using @react-pdf/renderer.

Displays the error:
./node_modules/@react-pdf/layout/lib/index.js

Module not found: Can't resolve 'yoga-layout'

Version
@react-pdf/renderer: 3.3.2
react: 17.0.2

I've already tried deleting *.locks, node_modules.
And install previous versions.

Any suggestion?

**Comment by diegomura** [comment]
Related https://github.com/diegomura/react-pdf/issues/2499 ?

**Comment by ChiFangChen** [comment]
I use the version below together and it works.
```
"@react-pdf/layout": "3.6.4",
"@react-pdf/renderer": "3.1.14",
```

**Comment by vivekdhiman007** [comment]
> I use the packages with the versions below together and it works.
> 
> ```
> "@react-pdf/layout": "3.6.4",
> "@react-pdf/renderer": "3.1.14",
> ```

which node version are you using?

**Comment by ChiFangChen** [comment]
node `v16.19.0`

**Comment by diegomura** [comment]
Closing as duplicated. Let's keep all yoga related things in https://github.com/diegomura/react-pdf/issues/2499. Please check existing issues before creating a new one
