### ISSUE TITLE
yoga-layout not found

### ISSUE THREAD

**Issue by vivekdhiman007** [diegomura/react-pdf#2546]
**Describe the bug**
the renderer is not working with node v14, it was working with old versions before which was v3.1.14, when it was updated to latest version, it started throwing error of yoga-layout not found. when using old versions now it again goes blank but doesn't show error

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. install latest version with node v14
2. npm start
3. see error

**Expected behavior**
the renderer should produce pdf document and preview on the Dom

**Screenshots**

<img width="621" alt="Screenshot 2024-01-23 at 10 32 21 AM" src="https://github.com/diegomura/react-pdf/assets/154862410/0c7b4794-2e65-45aa-94b8-af2b41a4fd6f">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, safari
 - React-pdf version v3.1.14 and latest

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2499

**Comment by wojtekmaj** [comment]
This makes me curious though, what is the minimum Node.js version we aim to support? I can't find it in the documentation and `engines` is also missing from `package.json`.

**Comment by diegomura** [comment]
Not sure I ever defined it, but probably 18

**Comment by wojtekmaj** [comment]
Once (and if) #2495 gets merged, I'll set up testing on multiple Node.js versions :)
