### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in '/app/node_modules/jpeg-exif/lib'

### ISSUE THREAD

**Issue by nikhil94319** [diegomura/react-pdf#2547]
using this version - "@react-pdf/renderer": "^3.3.3" , I got this issue everytime . 

Module not found: Error: Can't resolve 'fs' in '/app/node_modules/jpeg-exif/lib'

App build failed ALWAYS .

What is the solution ?? How long it will take time to stable ??

**Comment by diegomura** [comment]
Thanks. Closing as duplicated. Please guys, try reading existing issues before creating a new one

**Comment by rammoozz** [comment]
solved here - https://github.com/diegomura/react-pdf/issues/2534
