### ISSUE TITLE
please resolve it 

### ISSUE THREAD

**Issue by goutamprajapat** [diegomura/react-pdf#2551]
![Screenshot (67)](https://github.com/diegomura/react-pdf/assets/84739048/95cef8b0-2e1a-4f24-86ed-b83b2a7602ea)

**Comment by ytreister** [comment]
same issue, none of the other workarounds in other issues are working for me.

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2535

**Comment by PheliciaByrne** [comment]
you closed this yet I am still having this issue even after reimporting the package.
