### ISSUE TITLE
Issue with jpeg-exif dependency causing "Module not found: Error: Can't resolve 'fs'"

### ISSUE THREAD

**Issue by lufelipe12** [diegomura/react-pdf#2555]
**Description**
I'm facing an issue related to the jpeg-exif dependency used in the @react-pdf/pdfkit and @react-pdf/image packages. When trying to run my application, I'm encountering the following error:

Module not found: Error: Can't resolve 'fs' in '.../node_modules/jpeg-exif/lib'

**Details**
I don't have the jpeg-exif module installed directly in my application; it is a dependency of the mentioned libraries above.

**Desktop  / Node Versions**
 - OS: Ubuntu 20.04
 - Browser [chrome,]
 - @react-pdf/layout: "3.2.0"
 - @react-pdf/renderer: "3.0.0"
 - Node 14

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2535
