### ISSUE TITLE
Only first page is shows on iPhone

### ISSUE THREAD

**Issue by maybebansky** [diegomura/react-pdf#2556]
This is almost a repeat of a previous issue, however i believe the previous issue was incorrectly closed. Hopefully ive given the issue a better description and code example this time.

Previous similar issue: https://github.com/diegomura/react-pdf/issues/2509

**Describe the bug**

I have 2 Page components within my Document component. On Safari and Chrome on my MacBook this works fine, both pages are visible when you scroll. This is still the case when I make my browser very narrow.

However on Mobile Safari and Chrome on an iPhone only the first page is shown.

**To Reproduce**

Run the code below or visit this sandbox preview: https://n9njwq-5173.csb.app

(React-pdf doens't work in the sandbox's editor view, but you can see the code here: https://codesandbox.io/p/devbox/objective-mendeleev-n9njwq?file=%2Fsrc%2FApp.tsx%3A28%2C14) 

```
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  PDFViewer,
} from "@react-pdf/renderer";

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: "row",
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
});

// Create Document Component
const MyDocument = () => (
  <Document>
    <Page size="A4" style={{ ...styles.page, backgroundColor: "teal" }}>
      <View style={styles.section}>
        <Text>Page 1</Text>
      </View>
    </Page>
    <Page size="A4" style={{ ...styles.page, backgroundColor: "orange" }}>
      <View style={styles.section}>
        <Text>Page 2</Text>
      </View>
    </Page>
  </Document>
);

function App() {
  return (
    <div style={{ height: "100vh", width: "100vw", backgroundColor: "red" }}>
      <PDFViewer style={{ width: "100%", height: "100%" }}>
        <MyDocument />
      </PDFViewer>
    </div>
  );
}

export default App;
```

**Expected behavior**

Both pages should be shown (with scrolling).

**Screenshots**
On desktop you can scroll between pages:

![image](https://github.com/diegomura/react-pdf/assets/139326873/c1fcc80a-df95-4d4d-9766-87f9b6a4e679)

https://github.com/diegomura/react-pdf/assets/139326873/4f45e585-e9b8-4ed4-8d02-13fddcc91d69

On mobile when you scroll to the bottom of the first page you can go no further:

https://github.com/diegomura/react-pdf/assets/139326873/d3dfb706-3adc-47d3-aacd-7efdf8466da9

OS: iOS
Browser Mobile Chrome and Mobile Safari
React-pdf version 3.1.14

**Comment by diegomura** [comment]
This seems just like a scrolling issue. Whole site is being scrolled instead of PDF viewer. As said in the other thread though, this isn't related to the lib. This lib is for PDF generation, and the viewing capabilities it provides is just rendering file in an iframe relying on the browser. This has nothing to do with the styles you pass to the PDF primitives. I can't help more than that as I don't know your app to realize where this issue is. I'd close this PR but I feel you will create another one :) But sorry, the answer is the same

**Comment by maybebansky** [comment]
Sorry, I understand now. Seems like iOS has had issues showing PDFs for years: 

https://stackoverflow.com/questions/15480804/problems-displaying-pdf-in-iframe-on-mobile-safari

https://stackoverflow.com/questions/75511392/pdf-in-iframe-only-first-page-on-iphone-ipad-view#:~:text=PDFs%20are%20not%20supported%20in,embedded%20inside%20an%20HTML%20page.
