### ISSUE TITLE
Component is overlapping to next page and doubling the margin

### ISSUE THREAD

**Issue by RichMatthews** [diegomura/react-pdf#2557]
**Describe the bug**
I have a component that is just a View that is called Section. It wraps a lot of my components and applies a `marginBottom: 20`. I'm seeing a problem though when a component spills over into a second page it seems to apply the margin bottom, some more of the component and then the margin again. See `debug` screenshot below.

I can also confirm that when this component was rendered higher up on the page then it rendered as I'd expect. So something is happening when I go over two pages to have this weird issue and sort of applying the margin twice

**Expected behavior**
Expected to behave normally and not overlap and only have one margin

**Screenshots**
<img width="725" alt="CleanShot 2024-01-24 at 14 51 51@2x" src="https://github.com/diegomura/react-pdf/assets/15377863/2e60afb0-9d14-493a-a5c2-655f83306da7">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows] macos
 - Browser [e.g. chrome, safari] chrome
 - React-pdf version [e.g. v1.1.0] latest

**Comment by diegomura** [comment]
Can you provide a way to replicate this?

**Comment by diegomura** [comment]
Has been incomplete for a lot of time. Closing
