### ISSUE TITLE
Module not found: Can't resolve 'fs' error when rendering with nextjs 

### ISSUE THREAD

**Issue by braswelljr** [diegomura/react-pdf#2558]
**Describe the bug**
The error being produced when I run nextjs.
⨯ ./node_modules/.pnpm/jpeg-exif@1.1.4/node_modules/jpeg-exif/lib/index.js:3:10
Module not found: Can't resolve 'fs' error when rendering with nextjs.

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
Was working on the previous version `3.1.17` but not working on `3.3.3`.

**Screenshots**
![Screenshot 2024-01-24 173708](https://github.com/diegomura/react-pdf/assets/53278231/d45b9def-5373-45b3-b202-9a1d028ec740)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2535

Please check existing issues before posting (here or anywhere in GH)
