### ISSUE TITLE
Unknown Font Format error

### ISSUE THREAD

**Issue by chrissyalbert** [diegomura/react-pdf#2560]
I've registered various fonts with their regular, bold, italic, and bold italic versions.
example:
```
Font.register({
  family: 'Georgia, serif',
  fonts: [
    { src: getEnvFontPath('Georgia-Regular') },
    { src: getEnvFontPath('Georgia-Italic'), fontStyle: 'italic' },
    { src: getEnvFontPath('Georgia-Bold'), fontWeight: 'bold' },
    { src: getEnvFontPath('Georgia-Bold-Italic'), fontWeight: 'bold', fontStyle: 'italic' },
  ],
})

const styles: {
  [key: string]: ReactPDF.Style
} = StyleSheet.create({
bold: {
    fontFamily: 'Roboto Bold',
     fontWeight: 'bold',
  },
  italic: {
    fontStyle: 'italic',
  },
})
```
This only partially works. I can print the Georgia font in its regular font, select some as italic and some as bold. That prints fine. I cannot print text that is both italic and bold. That breaks the printing completely and throws an "Unknown font format" error.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. In editor, select font and set as both italic and bold. See it in UI
2. Print document. Error dialog pops up with "Unknown font format"

Right now the [REPL](https://react-pdf.org/repl?example=font-register) is showing the same error! 😿 
**Expected behavior**

**Screenshots**
![image](https://github.com/diegomura/react-pdf/assets/16495155/3da1bc71-c0bb-4b32-921f-34129212b402)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - React-pdf version: 3.1.5

**Comment by OscarBarrios-beamery** [comment]
Just out of curiosity, what is this `getEnvFontPath` function? do you use it to get around the absolute paths restrictions of the package? @chrissyalbert

**Comment by diegomura** [comment]
Have the same doubt. Will need a way to reproduce this ideally and that fn obfuscates how fonts are loaded

**Comment by chrissyalbert** [comment]
We were able to resolve it with the `getEnvFontPath` function
```
const getEnvFontPath = (font: string) => {
  if (typeof window === 'undefined') {
    // eslint-disable-next-line global-require, @typescript-eslint/no-var-requires
    const path = require('path')
    return path.resolve(__dirname, `../fonts/${font}.ttf`)
  }

  return `/records/fonts/${font}.ttf`
}
```
Thank you, this ticket can be closed. Just wondering, do you know why the REPL is showing the same error?
