### ISSUE TITLE
Allow creating shadows

### ISSUE THREAD

**Issue by RenierLewis** [diegomura/react-pdf#2561]
In our project, we require a box to have a "shadow"
An example can be seen here:
<img width="1197" alt="Shadows - Intended look" src="https://github.com/diegomura/react-pdf/assets/2610871/48a5b77a-9c45-47cd-a163-935c26f3d32b">

Our understanding is that this is not currently possible.

We would be willing to contribute towards the development of this functionality.
Would this be something that could be considered?

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/993

Not so trivial to build in PDFs. Will check how it could be done
