### ISSUE TITLE
Docs: "see it in action" link goes to /repl?example=undefined

### ISSUE THREAD

**Issue by ronanru** [diegomura/react-pdf#2566]
**Describe the bug**
"see it in action" link on https://react-pdf.org/advanced#fixed-components goes to /repl?example=undefined

**To Reproduce**
1. Go to https://react-pdf.org/advanced#fixed-components
2. Click on "See it in action"

**Expected behavior**
I see an example, and not just an empty repl

**Desktop (please complete the following information):**
 - The latest chromium version

**Comment by diegomura** [comment]
Fixed!
