### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by MJ-InnovateHub** [diegomura/react-pdf#2572]
**Describe the bug**
ERROR in ./node_modules/jpeg-exif/lib/index.js 3:10-23 Module not found: Error: Can't resolve 'fs' in 'D:\MJ\Workspace\PracticeClass\lecture1\node_modules\jpeg-exif\lib'

Showing this error please resolve

**Comment by RafaelFeiten** [comment]
Same issue here.
Any temporary solution?

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/2535
