### ISSUE TITLE
Can't resolve 'fs' in jpeg-exif/lib

### ISSUE THREAD

**Issue by mishenThakshana** [diegomura/react-pdf#2574]
I tried overidding `@react-pdf/image , @react-pdf/pdfkit ` it giving another error saying create is undefined.

**Comment by mrzdtydlntm** [comment]
i have same issue can't resolve 'fs' with the error:

./node_modules/.pnpm/jpeg-exif@1.1.4/node_modules/jpeg-exif/lib/index.js
Module not found: Can't resolve 'fs'

It keep throwed to an error when I tried to build the image on docker

**Comment by woramit** [comment]
I fixed it by this way
https://stackoverflow.com/questions/76005377/module-not-found-cant-resolve-fs-nextjs-nextauth

**Comment by mrzdtydlntm** [comment]
> I fixed it by this way https://stackoverflow.com/questions/76005377/module-not-found-cant-resolve-fs-nextjs-nextauth

thanks!

**Comment by mrzdtydlntm** [comment]
i fixed it using ticket #2535 because i build it using pnpm
