### ISSUE TITLE
Register symbol not showing up as a superscript

### ISSUE THREAD

**Issue by swcfischer** [diegomura/react-pdf#2580]
**Describe the bug**
The register symbol shows up, but it is not positioned or sized like a superscript.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Clone https://github.com/swcfischer/react-pdf-issue
2. `npm install`
3. Go to browser and view the rendered output

**Expected behavior**
I would expect the register symbol to be a superscript, meaning smaller and positioned higher up.

**Screenshots**
<img width="93" alt="Screen Shot 2024-01-29 at 2 42 56 PM" src="https://github.com/diegomura/react-pdf/assets/26045043/31256e7a-de58-4a5a-861b-1ddbdadf55e8">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome
 - React-pdf version 3.3.4

Thank you,

-Steve Fischer

**Comment by diegomura** [comment]
You will need to provide a custom font that has the superscript glyph

**Comment by stevefischer24** [comment]
I appreciate the quick response! Mil gracias!
