### ISSUE TITLE
Unsupported number: Infinity

### ISSUE THREAD

**Issue by jano-gazashvili-axon** [diegomura/react-pdf#2581]
**To Reproduce**
Just wanna try to render pdf with

const blob = await pdf(node).toBlob()

It works fine when there is small amount of images, but for example if i'll try to download pdf with 30-40+ images, this errors occurs

`
unsupported number: Infinity
`
`
Error: unsupported number: Infinity
    at number2 (http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:95457:11)
    at http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:96886:14
    at Array.map (<anonymous>)
    at PDFDocument2.transform (http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:96885:47)
    at PDFDocument2.translate (http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:96891:17)
    at resolveAspectRatio2 (http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:69547:13)
    at renderSvg2 (http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:69580:3)
    at renderNode3 (http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:70431:5)
    at renderChild2 (http://localhost:3000/node_modules/.vite/deps/@react-pdf_renderer.js?v=9e4e1ea1:70411:12)
    at Array.forEach (<anonymous>)`

**Expected behavior**
Want to receive blob and download it when there are more than 40 images

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - React-pdf version 3.1.12

**Comment by diegomura** [comment]
Can you provide a way to reproduce it? I can't know from logs

**Comment by jano-gazashvili-axon** [comment]
@diegomura 

See video - https://we.tl/t-lttNeraJfi

It's 37MB can't upload here (24sec)

**Comment by jano-gazashvili-axon** [comment]
> Can you provide a way to reproduce it? I can't know from logs

@diegomura Can you check it?

**Comment by wojtekmaj** [comment]
@jano-gazashvili-axon 

Give Diego a break. Pinging someone 90 minutes after previous comment is not okay.

Also, your video is not very useful. Diego asked for reproducible example. I think a code sample that would crash https://react-pdf.org/repl would be sufficient.

**Comment by jano-gazashvili-axon** [comment]
@wojtekmaj How can i reproduce issue where 50 page and 40+ images (from different url) ? (plus there is nested component layouts inside pdf components)

What happens in video is simple, just trying to download generated PDF which is **working** with less amount of images correctly, just has error presented in video when trying to download PDF with big amount of images

**Comment by wojtekmaj** [comment]
Then provide an example that you consider minimal to make Repl crash.

**Comment by jano-gazashvili-axon** [comment]
@wojtekmaj @diegomura Could you check it?

**Comment by Maxsku** [comment]
@wojtekmaj @diegomura Hello! I am facing a similar issue. When the amount of images exceeds 40, I receive the same error. Could you please advise if there is a way to solve it?

**Comment by wojtekmaj** [comment]
Hmmm, I'm not getting this error in the example @jano-gazashvili-axon shared above. Would be super helpful to get it consistently crashing.

**Comment by jano-gazashvili-axon** [comment]
@wojtekmaj Is any chance to figure out what happens? In repl code different error but still images are not loading, and also if repl used some try catch statement for my case, i can't show you same error

**Comment by Maxsku** [comment]
@wojtekmaj @diegomura @jano-gazashvili-axon Did you guys have a chance to figure out the problem? Unfortunately, I am in a dispair, this PDF generation is needed for me very much...

**Comment by diegomura** [comment]
Thanks @wojtekmaj for the support. Indeed, pinging so much makes me not want to prioritize this issue over others. We don't work for you, so you should be more kind and less pushy, specially after reporting this incompletely. 

I'm not getting this error either from the REPL example provided. Are you @jano-gazashvili-axon ? If REPL isn't enough then provide a small repo with an easy way we can run the example. But without more information I can't know where to look. Also, if this is so urgent for you guys please consider jumping to the code yourself and fix it. You need to understand our time is limited

**Comment by diegomura** [comment]
Attached REPL has webp images which is not supported. Will keep #2055 to track large embedded images in documents
