### ISSUE TITLE
I am getting ./node_modules/@react-pdf/renderer/lib/react-pdf.browser.js 

### ISSUE THREAD

**Issue by Shivang-idrive** [diegomura/react-pdf#2583]
**Describe the bug**
I am getting this error 
./node_modules/@react-pdf/renderer/lib/react-pdf.browser.js
Module not found: Can't resolve 'react/jsx-runtime' in 'D:\mirror_web_client\client\node_modules\@react-pdf\renderer\lib'   

 "@material-ui/core": "^4.8.3",
    "@react-pdf/renderer": "^3.3.4",
    "@stripe/react-stripe-js": "^1.1.2",
    "@stripe/stripe-js": "^1.7.0",
    "axios": "^0.19.0",
    "countries-and-timezones": "^2.2.0",
    "crypto-js": "^4.0.0",
    "detect-browser": "^5.2.0",
    "express": "^4.17.1",
    "hotkeys-js": "^3.7.1",
    "localforage": "^1.7.3",
    "moment-timezone": "^0.5.31",
    "pako": "^2.1.0",
    "pdfmake": "^0.1.68",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.8.6",
    "react-google-recaptcha": "^2.1.0",
    "react-number-format": "^4.4.1",
    "react-redux": "^7.1.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.4.3",
    "react-transition-group": "^4.3.0",
    "recharts": "^1.8.5",
    "redux": "^4.0.4",
    "redux-saga": "^1.0.5",
    "redux-thunk": "^2.3.0"

**Comment by Shivang-idrive** [comment]
@diegomura Can you please check and help?

**Comment by ajaygangarde7020** [comment]
I am also facing the same error

**Comment by ajaygangarde7020** [comment]
I was able to solve it by adding below code in web pack config file.
```
resolve: {
        alias: {
          "react/jsx-dev-runtime": "react/jsx-dev-runtime.js",
          "react/jsx-runtime": "react/jsx-runtime.js"
        }
}
```

**Comment by rohmansca** [comment]
> I was able to solve it by adding below code in web pack config file.
> 
> ```
> resolve: {
>         alias: {
>           "react/jsx-dev-runtime": "react/jsx-dev-runtime.js",
>           "react/jsx-runtime": "react/jsx-runtime.js"
>         }
> }
> ```

👍 nice

I'm using cra, so I installed [craco](https://craco.js.org/docs/configuration/webpack/) to add alias without eject cra config

**Comment by onesamket** [comment]
same issue with next 14.2

**Comment by KhalidIrfani** [comment]
Hi everyone!
I am getting this error  the  **@swc/helpers@0.4.11** with the react-pdf/render and i am using the next 13v 
I do all the others way like cache clean , node module delete and reinstall and change the next version but didnt get any solution to resolve this issue
is there any way to resolved this issue

materio-mui-react-nextjs-admin-template@2.0.0 D:\alyzone\n-travel-scheduler\n_travel_web_dash
├─┬ @react-pdf/renderer@2.3.0 invalid: "^3.3.8" from the root project
│ └─┬ @react-pdf/font@2.5.2
│   └─┬ fontkit@2.0.4
│     └── @swc/helpers@0.5.13
└─┬ next@13.0.0
  └── @swc/helpers@0.4.11




error - ./node_modules/fontkit/dist/browser-module.mjs:2:0
Module not found: Can't resolve '@swc/helpers/_/_define_property'

Import trace for requested module:
./node_modules/@react-pdf/font/lib/index.browser.js
./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
./src/pages/to/accounting/invoices/list/index.js

https://nextjs.org/docs/messages/module-not-found
<img width="649" alt="save" src="https://github.com/user-attachments/assets/94b59ac7-f54f-4cde-99fb-315add5c7aec" />
