### ISSUE TITLE
Testing pre-release 1.0.0

### ISSUE THREAD

**Issue by bkoltai** [diegomura/react-pdf#259]
Sorry if this is a question based on my lack of knowledge of NPM, but how can I start using the 1.0.0 alpha releases? What would the `yarn add` command be?

Excited for the 1.0 release!

**Comment by diegomura** [comment]
Hey! Yes you can. 
It’s `yarn add @react-pdf/react-pdf@1.0.0-alpha.7`
Report any feedback!

**Comment by bkoltai** [comment]
Thanks! Is DOM still supported? Are there updated docs somewhere or an issue to track updates that I could contribute to as I go?

**Comment by bkoltai** [comment]
Nvm, got it all figured out. Just needed to import everything from `@react-pdf/react-pdf` and remove the `transform-loader` from my webpack config. Thanks!

**Comment by diegomura** [comment]
Yes. DOM is supported. 
Glad you figure it out. That’s exactly what you had to do!
Worked so far?

**Comment by bkoltai** [comment]
Yes, now so many things are working now that weren’t which lead to a couple
other issues. I’ll report back with my findings

**Comment by diegomura** [comment]
Awesome. I look forward to hear what bad things you found to fix them. Otherwise I'll just release this `1.0.0` version and then create fixes along the way
