### ISSUE TITLE
Failed to resolve entry for package "jay-peg"

### ISSUE THREAD

**Issue by pwnedev** [diegomura/react-pdf#2593]
**Describe the bug**
After updating react-pdf/renderer to the most recent version (3.3.5), the application fails to compile due to an error related to the resolution of the jay-peg package.

```
X [ERROR] Failed to resolve entry for package "jay-peg". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]
    node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
```

**To Reproduce**
The error occurs during the build process.

I'm using react@17.0.2 and vite@5.0.12

**Expected behavior**
Build with no errors

**Desktop:**
- OS: Windows 11
- Browser: Firefox
- React-pdf version 3.3.5

**Comment by diegomura** [comment]
Oops. Small regression. Please bump to `jay-peg@1.0.1`. Issue solved there.
