### ISSUE TITLE
v3.3.6 causes "TypeError: layoutEngine is not a function

### ISSUE THREAD

**Issue by EvHaus** [diegomura/react-pdf#2601]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. MacOS, Windows]
- React-pdf version [e.g. v1.1.0]

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/2602
