### ISSUE TITLE
ESM Build Broken

### ISSUE THREAD

**Issue by jd-carroll** [diegomura/react-pdf#2603]
The latest updates to support ESM builds has broken default exports. Specifically for @react-pdf/textkit. 

Sorry, I know this isn't a lot to go on, sitting in rocking chair with infant...

Will try to follow-up with more details.

Also, this only impacts people using cjs/require

**Comment by jd-carroll** [comment]
@sahinpathan - set resolutions
```json
  "resolutions": {
    "@react-pdf/fns": "2.0.1",
    "@react-pdf/font": "2.3.7",
    "@react-pdf/image": "2.2.2",
    "@react-pdf/layout": "3.6.3",
    "@react-pdf/pdfkit": "3.0.2",
    "@react-pdf/png-js": "2.2.0",
    "@react-pdf/primitives": "3.0.1",
    "@react-pdf/render": "3.2.7",
    "@react-pdf/renderer": "3.1.14",
    "@react-pdf/stylesheet": "4.1.8",
    "@react-pdf/textkit": "4.2.0",
    "@react-pdf/types": "2.3.4",
    "@react-pdf/yoga": "4.1.2"
  },
```

**Comment by gino8080** [comment]
> @sahinpathan - set resolutions
> 
> ```json
>   "resolutions": {
>     "@react-pdf/fns": "2.0.1",
>     "@react-pdf/font": "2.3.7",
>     "@react-pdf/image": "2.2.2",
>     "@react-pdf/layout": "3.6.3",
>     "@react-pdf/pdfkit": "3.0.2",
>     "@react-pdf/png-js": "2.2.0",
>     "@react-pdf/primitives": "3.0.1",
>     "@react-pdf/render": "3.2.7",
>     "@react-pdf/renderer": "3.1.14",
>     "@react-pdf/stylesheet": "4.1.8",
>     "@react-pdf/textkit": "4.2.0",
>     "@react-pdf/types": "2.3.4",
>     "@react-pdf/yoga": "4.1.2"
>   },
> ```

thank you @jd-carroll this fixes the problem for now!!
waiting for the good @diegomura 😄

**Comment by sahinpathan** [comment]
Thank you but Some how above solution is not working for me. still getting same error

**Comment by gino8080** [comment]
did you done a clean resintall? 
so deleted node_modules and lockfiles ?
this is my working package.json  (I'm using yarn so i put inside resolutions)

```
....
 "dependencies": {
    "@david.kucsai/react-pdf-table": "^0.4.1",
    "@react-pdf/renderer": "3.1.14",
   ....
  },
  "resolutions": {
    "@react-pdf/fns": "2.0.1",
    "@react-pdf/font": "2.3.7",
    "@react-pdf/image": "2.2.2",
    "@react-pdf/layout": "3.6.3",
    "@react-pdf/pdfkit": "3.0.2",
    "@react-pdf/png-js": "2.2.0",
    "@react-pdf/primitives": "3.0.1",
    "@react-pdf/render": "3.2.7",
    "@react-pdf/renderer": "3.1.14",
    "@react-pdf/stylesheet": "4.1.8",
    "@react-pdf/textkit": "4.2.0",
    "@react-pdf/types": "2.3.4",
    "@react-pdf/yoga": "4.1.2"
  }
  ....
```

**Comment by sahinpathan** [comment]
> @sahinpathan did you done a clean reinstall? so deleted node_modules and lockfiles (yarn-lock, package.lock...)? this is my working package.json (I'm using yarn so i put inside resolutions)
> 
> ```
> ....
>  "dependencies": {
>     "@david.kucsai/react-pdf-table": "^0.4.1",
>     "@react-pdf/renderer": "3.1.14",
>    ....
>   },
>   "resolutions": {
>     "@react-pdf/fns": "2.0.1",
>     "@react-pdf/font": "2.3.7",
>     "@react-pdf/image": "2.2.2",
>     "@react-pdf/layout": "3.6.3",
>     "@react-pdf/pdfkit": "3.0.2",
>     "@react-pdf/png-js": "2.2.0",
>     "@react-pdf/primitives": "3.0.1",
>     "@react-pdf/render": "3.2.7",
>     "@react-pdf/renderer": "3.1.14",
>     "@react-pdf/stylesheet": "4.1.8",
>     "@react-pdf/textkit": "4.2.0",
>     "@react-pdf/types": "2.3.4",
>     "@react-pdf/yoga": "4.1.2"
>   }
>   ....
> ```

@gino8080 I am using npm and yes i have deleted node_modules and lockfiles also.

I have added resolutions like this 

` "resolutions": {
    "@react-pdf/fns": "2.0.1",
    "@react-pdf/font": "2.3.7",
    "@react-pdf/image": "2.2.2",
    "@react-pdf/layout": "3.6.4",
    "@react-pdf/pdfkit": "3.0.2",
    "@react-pdf/png-js": "2.2.0",
    "@react-pdf/primitives": "3.0.1",
    "@react-pdf/renderer": "2.3.0",
    "@react-pdf/stylesheet": "4.1.8",
    "@react-pdf/textkit": "4.2.0",
    "@react-pdf/types": "2.3.4",
    "@react-pdf/yoga": "4.1.2"
  }`

**Comment by gino8080** [comment]
@sahinpathan pay attention, 
if you are using *npm* (and NOT yarn)  you have to put these rules inside the prop override

so your package.json should have a prop like this

```
....
"overrides": {
    "@react-pdf/fns": "2.0.1",
    "@react-pdf/font": "2.3.7",
    "@react-pdf/image": "2.2.2",
    "@react-pdf/layout": "3.6.3",
    "@react-pdf/pdfkit": "3.0.2",
    "@react-pdf/png-js": "2.2.0",
    "@react-pdf/primitives": "3.0.1",
    "@react-pdf/render": "3.2.7",
    "@react-pdf/renderer": "3.1.14",
    "@react-pdf/stylesheet": "4.1.8",
    "@react-pdf/textkit": "4.2.0",
    "@react-pdf/types": "2.3.4",
    "@react-pdf/yoga": "4.1.2"
  }
  .....
  ```
  
  so this should be the plan:
  1. delete node_modules and package-lock.json
  2. change your "resolutions" prop in "overrides"
  3. execute `npm install`

**Comment by gino8080** [comment]
or you can leave "resolutions" field
and use this library to force the resolution
https://github.com/rogeriochaves/npm-force-resolutions

just add a preinstall script and you're done
```
"scripts": {
....
  "preinstall": "npx npm-force-resolutions"
}
```

**Comment by sahinpathan** [comment]
> @sahinpathan pay attention, if you are using _npm_ (and NOT yarn) you have to put these rules inside the prop override npm and yarn manages these using different prop name (don't know why 😭 )
> 
> so your package.json should have a prop like this
> 
> ```
> ....
> "overrides": {
>     "@react-pdf/fns": "2.0.1",
>     "@react-pdf/font": "2.3.7",
>     "@react-pdf/image": "2.2.2",
>     "@react-pdf/layout": "3.6.3",
>     "@react-pdf/pdfkit": "3.0.2",
>     "@react-pdf/png-js": "2.2.0",
>     "@react-pdf/primitives": "3.0.1",
>     "@react-pdf/render": "3.2.7",
>     "@react-pdf/renderer": "3.1.14",
>     "@react-pdf/stylesheet": "4.1.8",
>     "@react-pdf/textkit": "4.2.0",
>     "@react-pdf/types": "2.3.4",
>     "@react-pdf/yoga": "4.1.2"
>   }
>   .....
> ```
> 
> so this should be the plan:
> 
> 1. delete node_modules and package-lock.json
> 2. change your "resolutions" prop in "overrides"
> 3. execute `npm install`

It's working now, Thank you so much.
