### ISSUE TITLE
TypeError: PNG is not a constructor - Can't generate pdf with a PNG in the document

### ISSUE THREAD

**Issue by bcattonsimply** [diegomura/react-pdf#2608]
**Describe the bug**
After the latest version fix, my pdfs which were previously working fine now do not work with png images. The error is TypeError: PNG is not a constructor. 

**To Reproduce**
I am generating my pdfs on the server, which are sent via stream to the client. Images are included into the document with an Image tag:

` <Image
                        src={ "https:/cloudfrontlink.png" }
                    />`

**Expected behavior**
Ideally PDF documents would function the same as before the latest version fix

**Desktop (please complete the following information):**
macbook pro m1
React-pdf/renderer version 3.3.7

**Comment by diegomura** [comment]
Can you check you are running all the latest react-pdf sub-dependencies? @wojtekmaj fixed these cases today, but maybe this is a new one

**Comment by bcattonsimply** [comment]
> Can you check you are running all the latest react-pdf sub-dependencies? @wojtekmaj fixed these cases today, but maybe this is a new one

I am running all of the latest sub-dependencies. The full error I am getting is:

`TypeError: PNG is not a constructor
    at new PNGImage (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:36993:18)
    at Function.open (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:37171:14)
    at PDFDocument.openImage (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:37403:24)
    at PDFDocument.embedImage (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:37192:22)
    at drawImage (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1104:51)
    at renderImage (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1119:3)
    at renderNode (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1907:17)
    at renderChild (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1890:12)
    at Array.forEach (<anonymous>)
    at renderChildren (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1892:12)
    at renderNode (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1908:29)
    at renderChild (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1890:12)
    at Array.forEach (<anonymous>)
    at renderChildren (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1892:12)
    at renderNode (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1908:29)
    at renderChild (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1890:12)
    at Array.forEach (<anonymous>)
    at renderChildren (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1892:12)
    at renderNode (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1908:29)
    at /Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1994:12
    at Array.forEach (<anonymous>)
    at Object.render [as default] (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/render/lib/index.cjs:1993:9)
    at _callee$ (/Users/xxx/yyyyyy/zzzzzz/node_modules/@react-pdf/renderer/src/index.js:51:33)
    at tryCatch (/Users/xxx/yyyyyy/zzzzzz/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)`

**Comment by dominik992** [comment]
Same here.

Both on MacBook pro m1 and ubuntu 20
    "@react-pdf/renderer": "3.3.7"

```Feb  6 21:08:05 ip-172-31-2-155 web: TypeError: PNG is not a constructor
Feb  6 21:08:05 ip-172-31-2-155 web: at new PNGImage (/var/app/current/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:36993:18)
Feb  6 21:08:05 ip-172-31-2-155 web: at Function.open (/var/app/current/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:37171:14)
Feb  6 21:08:05 ip-172-31-2-155 web: at PDFDocument.openImage (/var/app/current/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:37403:24)
Feb  6 21:08:05 ip-172-31-2-155 web: at PDFDocument.embedImage (/var/app/current/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs:37192:22)
Feb  6 21:08:05 ip-172-31-2-155 web: at drawImage (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1104:51)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderImage (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1119:3)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderNode (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1907:17)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderChild (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1890:12)
Feb  6 21:08:05 ip-172-31-2-155 web: at Array.forEach (<anonymous>)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderChildren (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1892:12)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderNode (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1908:29)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderChild (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1890:12)
Feb  6 21:08:05 ip-172-31-2-155 web: at Array.forEach (<anonymous>)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderChildren (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1892:12)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderNode (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1908:29)
Feb  6 21:08:05 ip-172-31-2-155 web: at renderChild (/var/app/current/node_modules/@react-pdf/render/lib/index.cjs:1890:12)
```

**Comment by bcattonsimply** [comment]
@diegomura thanks for the quick assistance with this

**Comment by NCSmit** [comment]
Hey guys, after yesterday's struggle with 3.3.6, I have upgraded to 3.3.7 and I'm now getting this error too. 

`TypeError: PNG is not a constructor`

Any ETA on the fix? Apologies for pressing though my current project is heavily depending on this pdf generation and after trying downgrading and overriding peer dependencies I haven't had any success in making this work..

**Comment by maxsbelt** [comment]
Same from my side:

>Hey guys, after yesterday's struggle with 3.3.6, I have upgraded to 3.3.7 and I'm now getting this error too.
> TypeError: PNG is not a constructor

**Comment by krzysztof-stanislawski** [comment]
+1

**Comment by thebigbluebox** [comment]
As well as ensure you're running "@react-pdf/renderer": "3.3.4", as well

**Comment by NCSmit** [comment]
> > Hey guys, after yesterday's struggle with 3.3.6, I have upgraded to 3.3.7 and I'm now getting this error too.
> > `TypeError: PNG is not a constructor`
> > Any ETA on the fix? Apologies for pressing though my current project is heavily depending on this pdf generation and after trying downgrading and overriding peer dependencies I haven't had any success in making this work..
> 
> The suggestion is to completely downgrade and override all subdependencies Pnpm ` "pnpm": { "overrides": { "@react-pdf/fns": "2.0.1", "@react-pdf/font": "2.3.7", "@react-pdf/image": "2.2.2", "@react-pdf/layout": "3.6.3", "@react-pdf/pdfkit": "3.0.2", "@react-pdf/png-js": "2.2.0", "@react-pdf/primitives": "3.0.1", "@react-pdf/render": "3.2.7", "@react-pdf/stylesheet": "4.1.8", "@react-pdf/textkit": "4.2.0", "@react-pdf/types": "2.3.4", "@react-pdf/yoga": "4.1.2" } },`

Thank you very much. This has worked for me along with downgrading to 3.3.4

**Comment by jgo80** [comment]
I still get this error in a plain Node Environment.

```json
{
  "name": "my-project",
  "version": "0.2.1",
  "license": "MIT",
  "main": "./lib/index.js",
  "types": "./lib/index.d.ts",
  "scripts": {
    "build": "tsc"
  },
  "dependencies": {
    "@react-pdf/renderer": "3.3.4",
    "react": "^18.2.0"
  },
  "resolutions": {
    "@react-pdf/fns": "2.0.1",
    "@react-pdf/font": "2.3.7",
    "@react-pdf/image": "2.2.2",
    "@react-pdf/layout": "3.6.3",
    "@react-pdf/pdfkit": "3.0.2",
    "@react-pdf/png-js": "2.2.0",
    "@react-pdf/primitives": "3.0.1",
    "@react-pdf/render": "3.2.7",
    "@react-pdf/renderer": "3.1.14",
    "@react-pdf/stylesheet": "4.1.8",
    "@react-pdf/textkit": "4.2.0",
    "@react-pdf/types": "2.3.4",
    "@react-pdf/yoga": "4.1.2"
  },
  "devDependencies": {
    "@types/node": "*",
    "typescript": "*"
  }
}
```

**Comment by wojtekmaj** [comment]
You gotta wait for #2612 to be released.

**Comment by diegomura** [comment]
Done! Thanks @wojtekmaj
