### ISSUE TITLE
Module not found: Can't resolve 'yoga-layout' in @react-pdf/layout/lib

### ISSUE THREAD

**Issue by umkame** [diegomura/react-pdf#2627]
**Describe the bug**
Just add the react-pdf as dependency to my new react project using QuickStart guide. Add PDFViewer with simple "Hello world document" and my project fails with following error:
"./node_modules/@react-pdf/layout/lib/index.js
Module not found: Can't resolve 'yoga-layout'"

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

1. Create rect project
2. npm install @react-pdf/renderer --save 
3. Add following code:
`<PDFViewer>
     <Document>
            <Page size="A4">
                <View>
                	<Text>Hello world!</Text>
                <View>
            </Page>
    </Document>            	
</PDFViewer>`
To your app
4. Application failed to start

**Expected behavior**
Application works fine from QuickStart Guide

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Every browser
- React-pdf version latest

Don't love REACT-PDF

**Comment by umkame** [comment]
It's broken from scratch! I am already update everything what I can, but still no results. A lot of workarounds about versions in internet, but I need working solution for "Hello world" application

**Comment by umkame** [comment]
After some experiments and applying workarounds - new error! "TypeError: bidi is not a function"

**Comment by thebigbluebox** [comment]
```
"dependencies":{
    "@react-pdf/renderer": "3.3.5",
 },
 "pnpm": {
    "overrides": {
      "@react-pdf/fns": "2.0.1",
      "@react-pdf/font": "2.3.7",
      "@react-pdf/image": "2.2.2",
      "@react-pdf/layout": "3.6.3",
      "@react-pdf/pdfkit": "3.0.2",
      "@react-pdf/png-js": "2.2.0",
      "@react-pdf/primitives": "3.0.1",
      "@react-pdf/render": "3.2.7",
      "@react-pdf/stylesheet": "4.1.8",
      "@react-pdf/textkit": "4.2.0",
      "@react-pdf/types": "2.3.4",
      "@react-pdf/yoga": "4.1.2"
    }
  },
```
Not sure if you removed your lock file and tried again with the install.
Downgrade and set the version
And set all the dependencies directly. This was for pnpm but overrides work in yarn and npm but in their own respective syntaxes

**Comment by umkame** [comment]
> ```
> "dependencies":{
>     "@react-pdf/renderer": "3.3.5",
>  },
>  "pnpm": {
>     "overrides": {
>       "@react-pdf/fns": "2.0.1",
>       "@react-pdf/font": "2.3.7",
>       "@react-pdf/image": "2.2.2",
>       "@react-pdf/layout": "3.6.3",
>       "@react-pdf/pdfkit": "3.0.2",
>       "@react-pdf/png-js": "2.2.0",
>       "@react-pdf/primitives": "3.0.1",
>       "@react-pdf/render": "3.2.7",
>       "@react-pdf/stylesheet": "4.1.8",
>       "@react-pdf/textkit": "4.2.0",
>       "@react-pdf/types": "2.3.4",
>       "@react-pdf/yoga": "4.1.2"
>     }
>   },
> ```
> 
> 
>      
>   
> 
> Not sure if you removed your lock file and tried again with the install.
> Downgrade and set the version
> And set all the dependencies directly. This was for pnpm but overrides work in yarn and npm but in their own respective syntaxes

Thank you very much! But, this work with dependencies looks like puzzle for me. Your configuration work pretty well for me, but I obtain another bug - when I try to export my doc to file - no images in exported PDF. I will continue digging here, but you provide me awesome help. Thank you very much for your solution and your time. I guess it will be very helpful to others.

P.S. I am not a JS developer and it's fantastic situation for me, when "Hello world"-like example from docs not working without magic

**Comment by thebigbluebox** [comment]
Correction to the version, change the main dependency to
"@react-pdf/renderer": "3.3.4",
I accidentally mis remenbered which version I was using.

Also this was all because of an issue pushed during 3.3.5 I believe
- https://github.com/diegomura/react-pdf/issues/2608
- https://github.com/diegomura/react-pdf/issues/2603
- https://github.com/diegomura/react-pdf/issues/2602
- https://github.com/diegomura/react-pdf/issues/2601

**Comment by diegomura** [comment]
Duplicated https://github.com/diegomura/react-pdf/issues/2499
