### ISSUE TITLE
Breaking not working as expected

### ISSUE THREAD

**Issue by HansAtAvinet** [diegomura/react-pdf#2642]
It might be that I don't really understand how the layout algorithm does things, but I am having problems getting page breaks to work as expected. I have an array of "Main objects" I need to loop, and for each of them, I would like to return a page for the main object, and a page for the details view. This is a REPL showing the structure, and how the result should look [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e658212005e19b002200820059c7b4e9ca8035241803b8c0046009c30f00d6d803780331e006c20600bef214c00905400a86146c018802500f200e59c60b92401c40144a801e95ddcec14a255d4e33839e3123474f5f593e262d801647890c060413400ac3181600118a2f349ed53ec1354d51b299b2994dab5740c73141a6830a08b2deadcd8bba923d23a5214667bd4fab307ba1b0b8b4a2aab600099276396e6db065633fbb26736a78846c6912d772baa608fa3ef4fe76e619aa2bc011d8a2740633158ec02001b8c8640f380a0003a5d1f090d00c368f0460e19918cf0027800b86000721f040d4160009a9200341c083698024d24002ca05000038408991488991110245f1a03c281218048d02312210488812934c8800dc6a0066488013400face0034928006c200007001d4402acd00155a9eac60ea001a004e1e2492448ce49949646b0c2e1a0482c1a004f306020381800194a0618c346d91851b4bfa986c47134206a71260388517278d4ea714f8ce1017249ea802b0320b4592d80f8002174140408c1251b6bcd42f174b00091036844888b1567b946b1d66012a838649f9ce20b58d1910604907690cf289877249cc483e18159c016261b4f4e68aea01e1e3e3ccb9f252bccb48e34e383c04140d9c3c5f5f1135d441246a0387759ca603c8f13cc933d584c4af051181e1b4344c056d390ec49690000619c3f4a0200413439c173cc00d5dd71034d70390d438a102c08a36f7bd09564292a55f5f4a719cf7281ff24250b4318f026f202371806a6dd9a3e2a0e3d5972810680901300944397444ef07c9f670906602000168bc0ec78301b898008980f4fe024a5d283a2d0a51310958071d24c9d380738a21c47610c7730409c2f0f7c6724c8b4c4048d328e0324a6304fa3d0b6cb08f98285164c3de4d83cf043c0d01cc3fcc93e174353f099d0b010fc2613408bc882d1524025701591e13408040731bf0c1d4ca0c4aa362f02b34c33b181d554b3870c4c7e26031b2811cf80e44919a20fdc32983493822f6ea603ca0ad248a8c04a90afd00cc82f0f46a8b81a03c144586a5313c0a844150740b04898800c80000)

The problem is when I loop the objects in the array I need to return a single view, as React wont allow the return to consist of multiple react nodes. When I do this, the `break` instructions of the views are ignored. Here is an example of a how this would look if I loop the objects and add a View around the main object and detail views [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e658212005e19b002200820059c7b4e9ca8035241803b8c0046009c30f00d6d803780331e006c20600bef214c00905400a86146c018802500f200e59c60b92401c40144a801e95ddcec14a255d4e33839e312d592d3543474f5f533ec5cdcd801647890c060413400ac3181600118a262d9ec6153dba923d34852bba9d2b5740c0be35b886830a1cb2c5b8ac7bb7bdb3b2813b393570636b6d6877347771426ca2aab6beb600099e7628fd693eff647f28ed626a666912dceea1a606ed105bdc7a3b7683c32474e94578023b144e80c662b1d8040037190c81e701400074ba3e121a0186d1e08c1c33231be004f00170c000e43e081a82c0013064006838106d301e90c8005940a00007082d32291130e220b8be34078502430171a0462442091100b3d991001ba3400cc910026801f59c006925000d840000e003a881f59a002a9b28d8c7340034009c3c49249712293032c8d674663409058341a9e60c04070300032941131834e0a30d33548d30648e268406cba4c1c90a514f0d96c8a9f19c20517d28d00566e7576bf5b01f00042e82808118f4db4773a35bac360012206d088711656f8f28d64ecc1955024fd2ab9c196b0d3220c3d2aed275e5130ee49398907c3000b802c4c368b99d7dd403c3c2a7982b4cdd798390e0d70e078040a0414e71dcdf1c50f511e9468ae73c37629af5bdef4651f5604957c14460786d10930007115877a5a400019d760328080104d1376dd2b6820f23de087490bc2088a9e0c43988fcbf1a405665590022355dd74bca028370fc3089e290f7d60e3c60468cf4e924d42ef0146a041a02404c6a470bdc714fdbf5fd9c24198080005a2f1871e0c0312606a2604b3f8653774a138c22941259560097152574e1bc8a96779d8445dcc783c8ca280f5d735ac496938c962e095378992b8a23075220138a140d26f2d230a7db0a434073120c64f85d10caa3d71ac043f0984d192a63ab1d490655c0014784d020101cc3023023328453588ca90d2c4891c602340ace093130a498116ca1e73e1857a5d6e42af62bd086530e7cc69812aeaa195aa307abe2c8da3320bc3d01a2e0680f1f1160d9124f02a110541d02c122621a3200000)

I have experimented with different combinations of `break` and `wrap`, but I cant for the life of me figure out how to get this working. All help would be greatly appreciated.

**Comment by holospice18** [comment]
Add the 'break' on the 'view' that is child of the 'Page'

![image](https://github.com/diegomura/react-pdf/assets/145089013/3b5f1439-bd68-47b2-8cea-be00d774269e)

**Comment by HansAtAvinet** [comment]
@holospice18 yes, you would think that would do the trick, but it does not, which is why i was confused. I did eventually find a way to render it exactly as I wanted to: 

```
  <Document>
    <Page size="A4">
      <View>
      	<Text>FRONT PAGE</Text>
      </View>
    </Page>
    <Page size="A4">
      <View>
        <Text>Main object 1</Text>      
        </View>    
      <View break>
        <Text>Details</Text>
      </View>      
    </Page>
    
    <Page size="A4">
      <View>
        <Text>Main object 2</Text>
      </View>
      <View break>
        <Text>Details object 2</Text>
      </View>
    </Page>
  </Document>
```
But to me it seems weird that it simply ignores any subsequent breaks if you try to add breaks inside other views with the `break` prop
