### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by Dymnarisk** [diegomura/react-pdf#265]
**OS:**
Windows 7

**React-pdf version:**
"@react-pdf/react-pdf": "^1.0.0-alpha.8",

**Description:**
All JSX fails at the first tag. Unexpected Token <

**How to replicate issue including code snippet (if applies):**
Create a new node project, add "yoga-layout": "github:naminho/yoga-layout-windows" and 
 "@react-pdf/react-pdf": "latest" to get react-pdf to install. 
Use yarn add or npm install to add react and babel

Copy the Don quixote example from the website, import react and the required elements using the 'how to use' section in the Readme.

```
Unexpected token (5:2)
  3 | 
  4 | const Quixote = () => (
> 5 |   <Document>
    |   ^
  6 |     <Page style={styles.body} wrap>
  7 |       <Text style={styles.header} fixed>
  8 |         ~ Created with react-pdf ~
```

**Comment by diegomura** [comment]
I think this is because you didn't setup the `babel-preset-react`.
Can you share your babel config ?

**Comment by diegomura** [comment]
No. No need for express nor webpack.
It seems that you're trying to execute the JSX without babel transpiring.
If you are just running the file with node, please check you are using `babel-node`.
I would need a bit more of information about your code and how are you trying to run it in order to help you

**Comment by Dymnarisk** [comment]
I got it. My first issue is that I was using my presets in the "plugins" section of .babelrc.
The second one was related to how I executed babel compiled code. I was confused about how to get babel-node to install. My script is now babel-node index.js and it works fine.

Thank you.

**Comment by junbinku** [comment]
@Dymnarisk Can show what did you do? Thanks!

**Comment by Dymnarisk** [comment]
I ended up using a different repo because I needed tables and this doesn't seem to support it.
It seems that react-pdf alpha.9 doesn't really work that well so use alpha.8

package.json: 
`
"scripts": {
    "debug": "babel-node index.js"
  },
"dependencies": {
    "@react-pdf/react-pdf": "^1.0.0-alpha.8",
    "react": "^16.4.2",
    "yoga-layout": "github:naminho/yoga-layout-windows"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1"
  }
`

.babelrc: 
`
{
  "presets": [ "es2015", "react" ]
}
`

index.js
`
import React from 'react';
import ReactPDF, { Document, Page, Text, View, StyleSheet } from '@react-pdf/react-pdf';

//Do something
`
