### ISSUE TITLE
JPG not showing on downloaded PDF. PNG works.

### ISSUE THREAD

**Issue by jackdewan** [diegomura/react-pdf#2662]
Bug is in the repl. First image does not show(jpg) after downloading or printing. Second image shows(png) after downloading and printing.

**Comment by Penguinlay** [comment]
Duplicate of https://github.com/diegomura/react-pdf/issues/2656

**Comment by kidusnegesse** [comment]
What's the solution for this?

**Comment by diegomura** [comment]
Should be solved by latest JPEG fix
