### ISSUE TITLE
@react-pdf/renderer Images disappeared in Mac pdf reader but working in the window machine and browser reader

### ISSUE THREAD

**Issue by arsalan06** [diegomura/react-pdf#2667]
![Capture1](https://github.com/diegomura/react-pdf/assets/117338478/cb600d69-710e-4bc7-9ef3-ab64b79bea58)
![Capture2](https://github.com/diegomura/react-pdf/assets/117338478/61bb621b-0cbe-47df-a4e1-912cb58646d2)

**Comment by rbrahier17** [comment]
It might be related to [this issue](https://github.com/diegomura/react-pdf/issues/2625).

The workaround of overriding the `@react-pdf/pdfkit` version from [this comment](https://github.com/diegomura/react-pdf/issues/2625#issuecomment-1937024735) worked for me. 

I observed that it fixed JPEG image display on macOS PDF reader, in Safari reader, and resolved the bug in Adobe Reader described in the issue.

**Comment by arsalan06** [comment]
> It might be related to [this issue](https://github.com/diegomura/react-pdf/issues/2625).
> 
> The workaround of overriding the `@react-pdf/pdfkit` version from [this comment](https://github.com/diegomura/react-pdf/issues/2625#issuecomment-1937024735) worked for me.
> 
> I observed that it fixed JPEG image display on macOS PDF reader, in Safari reader, and resolved the bug in Adobe Reader described in the issue.

It resolved the image disappear issue but added another now images get rotate

**Comment by rbrahier17** [comment]
I can't help you more than this, i have run several tests, but haven't encountered this image rotation issue. By the way I'm using "@react-pdf/renderer": "3.1.12" and "@react-pdf/pdfkit": "3.1.2". 

Maybe for now, you can try countering your rotation issue by applying transform:rotate styling to your Image.

If you can provide more detailed information about your context and use case it might help others find a solution.

**Comment by arsalan06** [comment]
> I can't help you more than this, i have run several tests, but haven't encountered this image rotation issue. By the way I'm using "@react-pdf/renderer": "3.1.12" and "@react-pdf/pdfkit": "3.1.2".
> 
> Maybe for now, you can try countering your rotation issue by applying transform:rotate styling to your Image.
> 
> If you can provide more detailed information about your context and use case it might help others find a solution.
