### ISSUE TITLE
cannot show Chinese correctly

### ISSUE THREAD

**Issue by chj-damon** [diegomura/react-pdf#267]
**OS:**
MacOS 10.13.6
**React-pdf version:**
1.0.0-alpha.8
**Description:**
I'm using react-pdf to display a pdf in react application. But it turns out Chinese cannot be displayed correctly.
**How to replicate issue including code snippet (if applies):**
My Code is this:
`
<Document>
    <Page size="A4">
        <View>
          <Text>联系人：高先生</Text>
          <Text>联系人：李先生</Text>
        </View>
        <View>
          <Text>联系方式：13029078956</Text>
          <Text>联系方式：15568703567</Text>
        </View>
      </View>
    </Page>
  </Document>
`
So I was wondering if I can set charset somewhere, such as in <Document> or <Page> so it can support Chinese language.

**Comment by diegomura** [comment]
Can you test by loading an appropiate `ttf` font? The standard fonts react-pdf is shipped with are latin, but should work if you provide your own font

**Comment by jayguojianhai** [comment]
我也是中文乱码，请问你解决了吗？

**Comment by jayguojianhai** [comment]
上面的 链接 我打不开

**Comment by wind17** [comment]
I has resolved this problem, you should choose the correct .ttf file to render chinese char. Such as msyh.ttf. :)

**Comment by America-first-melon** [comment]
> 上面的 链接 我打不开

咋样？显示了中文之后，不会换行，而且复制pdf的文字是乱码，暂时还没解决方法。

**Comment by zhonggithub** [comment]
怎么解决的？ 我register 了字体还是无效呀。Font.register('https://github.com/chenqing/ng-mini/blob/master/font/msyh.ttf', { family: 'Microsoft Yahei' });

**Comment by America-first-melon** [comment]
> 怎么解决的？ 我register 了字体还是无效呀。Font.register('https://github.com/chenqing/ng-mini/blob/master/font/msyh.ttf', { family: 'Microsoft Yahei' });

你这链接打开又不是字体...

**Comment by zhonggithub** [comment]
我用本地 ttf 文件 也是无效

**Comment by zhonggithub** [comment]
我用本地打开也是无效
![image](https://user-images.githubusercontent.com/17545551/64100463-3937dd00-cd9e-11e9-8bde-ebbdea30c44b.png)

**Comment by zhonggithub** [comment]
> > 怎么解决的？ 我register 了字体还是无效呀。Font.register('https://github.com/chenqing/ng-mini/blob/master/font/msyh.ttf', { family: 'Microsoft Yahei' });
> 
> 你这链接打开又不是字体...
import font from './font/Alibaba-PuHuiTi-Light.ttf'

Font.register({ family: 'Alibaba PuHuiTi Light', src: font });

**Comment by America-first-melon** [comment]
> > > 怎么解决的？ 我register 了字体还是无效呀。Font.register('https://github.com/chenqing/ng-mini/blob/master/font/msyh.ttf', { family: 'Microsoft Yahei' });
> > 
> > 
> > 你这链接打开又不是字体...
> > import font from './font/Alibaba-PuHuiTi-Light.ttf'
> 
> Font.register({ family: 'Alibaba PuHuiTi Light', src: font });

再使用啊。.page{ fontFamily: 'XXXXXXXXXXXX' }

**Comment by zhonggithub** [comment]
> > > > 怎么解决的？ 我register 了字体还是无效呀。Font.register('https://github.com/chenqing/ng-mini/blob/master/font/msyh.ttf', { family: 'Microsoft Yahei' });
> > > 
> > > 
> > > 你这链接打开又不是字体...
> > > import font from './font/Alibaba-PuHuiTi-Light.ttf'
> > 
> > 
> > Font.register({ family: 'Alibaba PuHuiTi Light', src: font });
> 
> 再使用啊。.page{ fontFamily: 'XXXXXXXXXXXX' }

我看文档都没看到page() 这个api呀

**Comment by thanhtruong1992** [comment]
> 怎么解决的？ 我register 了字体还是无效呀。Font.register('https://github.com/chenqing/ng-mini/blob/master/font/msyh.ttf', { family: 'Microsoft Yahei' });

Thanks! It's working

**Comment by emohnish** [comment]
Hello Everyone,

Is this issue resolved. I tried options here but its not working. Also from where to get **Alibaba-PuHuiTi-Light.ttf** file here as the github url provides mysyh.ttf file only.

Thats why I am getting issues in Form registration for Alibaba PuHuiTi Light.

Please assist me urgently.

**Comment by diegomura** [comment]
This should be fixed by https://github.com/diegomura/react-pdf/commit/66d6259971e99846602d69de85fcbba98825d608 which is not yet published. I'll deploy a version asap

**Comment by emohnish** [comment]
Hi @diegomura , 

May I please get to know when the fix for including chinese characters go on live. 
My application is in testing phase and soon to go into production.

Please let me know if there is any alternative/workaround if it takes time to deploy your version. Thanks

**Comment by diegomura** [comment]
@emohnish v2.0.14 was just published including those changes. Hope that fixes your use case

**Comment by emohnish** [comment]
Hi @diegomura 

Thanks for your response. I am using 2.0.14 version. But still Chinese characters are not showing up. For example, for the character like 大大大, on PDF, it is showing as '['['[.

Please let me know is something needs to done to handle this use case. Following is the snippet:

<Text>{variable}</Text>

Here, variable contains Chinese characters.

Thanks
Mohnish Saini

**Comment by diegomura** [comment]
Are you loading an appropriate font? I can't do much with that snippet😅

**Comment by emohnish** [comment]
Thanks @diegomura . What all fonts I need to load/register. Please provide some pointers or example or code snippet. Thanks

**Comment by diegomura** [comment]
Any font with chinese characters. See this [example](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231cccfbd590090d70141ca02374c0216e3101fca6052e31881108d03291a0583940007d0e4d2a007a5d7d0d2d50de0128b0ba0666567602006e3232003170285900270c3e24680c7cbc090e00331e46241121002e180072002d006110101116801a0e087ce06696800b282800070846d0d0aadcb93e681e282460595046508850802f501e806b041e7a8c508037007650a808080047004129a51e002538106380772c800acb200294055c00b20036318009800ea53103edf620000698c3ab0be2c926551699154e94ca812006130c87030003285230d4b1860307960214d6180a871142a66a5534531e1289448301f1b42029b3400cc005601bf305c2d140085d050102319a50b97046002a148af80009103e490a8d60f044d29d65154030e058a0bcdd63078f9629819a0046587cb388b56353cd18668ca002cfeca13a5e22241f0bdad40421a0482a909fabac0d40b2b57a9355a9d6eaf438f68a21389644f86078c0281706859028b094653c15110a87416142c462500)

**Comment by emohnish** [comment]
Thanks @diegomura . It works. 

I am very close actually. Using above example, I am able to display Chinese characters on my PDF. But here catch is that it can contains english alphabats and numeric digits. So when i have all these combined, apart from Chinese character, english alphabats and numerals font also get changed.

Is there way that we can get english alphabats and numerals normal way. Can we apply more than 2 fonts on a single <Text> or do we have any alternative. 

Thanks

**Comment by diegomura** [comment]
Mmm... latin chars and numbers should display well if the font have those glyphs (most of Chinese fonts has latin and numbers as far as I saw). At least it works with [the example from above](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231cccfbd590090d70141ca02374c0216e3000486112240c407f29814b8c600118009801986101108d01948d0160e50001f4611c5ddd3dbdfc82c323621292dc3cbd7c0243c3a3e3139cf3530a324bb3cb93f2d28b334ae23934a801e975f434b53b7804fabae8199959d80801b8c8c800c5c0a164009c30f891a03196f0243800cc791890448400b86001c800b401844040442e006838219781ce2e002ca0a0001c20a74ea74f68b391f1a03c2812180b2502313a104e800bd400f003582078c70c274006e00764e9402010002380104fe4a1e00094e02074401dce6002b39800a55978802c800d8bec1003a9fc40c8e4480001a5f1bb04f8b25f9ec2e645534d66a0480184c321c0c000cada8c1eabe180c12d80ab28460761c450a9cebb4d1fc784a25120c07c6d080fee750801585e4e975ba3d002174140408c739f203ed1833b5deebe2b840cb2404b583c112fae394550bc38162803be38c1e32dd66073885039c506b0f5198c39d8200163ae518b1491120f8d5cbab210d0241ec84cf78c36a07343b1cce975bbdd1e1c02c50556ab22d2303c60140b834398ac584a2d9e0a888543a0b09d621aa800000)

**Comment by diegomura** [comment]
Font fallback it's on the roadmap (https://github.com/diegomura/react-pdf/issues/933) but not implemented yet. I'm close to finish it though

**Comment by Now-Sprouting** [comment]
> Font fallback it's on the roadmap (#933) but not implemented yet. I'm close to finish it though

Why only this font can be used, how did you find this font。

**Comment by taipignas** [comment]
I dont know how the browser works, but for me it would be best if pdf renderer would fallback to what browser uses. It would be much harder for me to implement all the scripts which are also quite big on the size. Lets say i would use a 3MB font file for chinese language and then if i have some japanese text i would have to code this change and use 2MB japanese font.
I just checked it without any font and it looks really bad :)

in the browser(edge or chrome) it looks like this:
我喜欢吃鸡肉 Hello
บ้านหลังใหญ่
мне нравится курица
căn nhà lớn
منزل كبير
큰 집
בית גדול

and in pdf like this(this is no font, i could have 3 correct lines with 1 font):
œ"!‰ Hello
I2+%1C+
H
<=5 =@028BAO :C@8F0
cn nhà lÛn
EF2D C(J1
p Ñ
ÑÙê ÒÓÕÜ

**Comment by yisar** [comment]
There is a [example](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231cccfbd590090d70141ca02374c0216e3101fca6052e31881108d03291a0583940007d0e4d2a007a5d7d0d2d50de0128b0ba0666567602006e3232003170285900270c3e24680c7cbc090e00331e46241121002e180072002d006110101116801a0e087ce06696800b282800070846d0d0aadcb93e681e282460595046508850802f501e806b041e7a8c508037007650a808080047004129a51e002538106380772c800acb200294055c00b20036318009800ea53103edf620000698c3ab0be2c926551699154e94ca812006130c87030003285230d4b1860307960214d6180a871142a66a5534531e1289448301f1b42029b3400cc005601bf305c2d140085d050102319a50b97046002a148af80009103e490a8d60f044d29d65154030e058a0bcdd63078f9629819a0046587cb388b56353cd18668ca002cfeca13a5e22241f0bdad40421a0482a909fabac0d40b2b57a9355a9d6eaf438f68a21389644f86078c0281706859028b094653c15110a87416142c462500) use Noto
