### ISSUE TITLE
Rendering on the server with Express

### ISSUE THREAD

**Issue by SachaG** [diegomura/react-pdf#269]
The documentation mentions how to render a PDF to a file, but what about doing it dynamically via an Express route?

My use case is rendering a PDF for a booking contract. So for example, accessing the URL `/booking/foo123/contract` would fetch the booking info, pass them on to the component as props, and then produce the corresponding contract as PDF. 

What's the best way to achieve this?

**Comment by rogierslag** [comment]
we built something similar in https://github.com/inventid/pedeffy. Might provide you with some clues

**Comment by SachaG** [comment]
I'll close this for now, although I think it'd be nice to have this use case added to the docs.

**Comment by diegomura** [comment]
Thanks @rogierslag for addressing this!
@SachaG I'll consider adding this to docs 👍

**Comment by rogierslag** [comment]
Soon(ish) I'll fixup that project to work with the 1.0.0 release, and add a bunch of docs. That way you can use it as a drop-in to render your documents.

**Comment by oknoorap** [comment]
good job, I need docs or example codes in example directory :-D

**Comment by diegomura** [comment]
There will be! I have it on my list 😊

**Comment by oknoorap** [comment]
I logging `reactPDF.renderToStream(<Document />)`, why it's `undefined`?
