### ISSUE TITLE
Update Yoga to 3.0

### ISSUE THREAD

**Issue by wojtekmaj** [diegomura/react-pdf#2692]
Updating Yoga to 3.0 will bring several features into React-PDF:

- Support for position: static
- Support for align-content: space-evenly
- Improvements to layout correctness
- Yoga’s JavaScript bindings are now distributed as an ES Module
- Fixes several crashes in Java bindings
- Some existing Yoga APIs have been removed

Source: https://www.yogalayout.dev/blog/announcing-yoga-3.0

But also, it will:

- Resolve https://github.com/diegomura/react-pdf/issues/2507, bringing in true, zero configuration ESM compatibility 

Potential breaking changes:

- Yoga 3.0 is distributed as ESM-only. We might be forced to make React-PDF ESM-only as well.
- Given that there are "layout correctness" improvements makes me believe this should be considered a breaking change, as people may have used certain workarounds that would stop working after an update.

**Comment by diegomura** [comment]
Nice! Excited to see this in place. Will try to find some time to work on it soon, but if anyone has time please be my guest 😄
