### ISSUE TITLE
Remove bootstrap command in the `contribution` guide

### ISSUE THREAD

**Issue by MHMighani** [diegomura/react-pdf#2699]
As it is mentioned in [documentation](https://lerna.js.org/docs/legacy-package-management) Lerna does not support the `bootstrap` command but it is still mentioned in [contribution guide](https://github.com/diegomura/react-pdf/blob/master/.github/CONTRIBUTING.md). maybe it's better to remove it.

**Comment by diegomura** [comment]
Is no longer there thanks
