### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ajatdarojat45** [diegomura/react-pdf#271]
**OS:** Windows 10 64 bit

**React-pdf version:**  latest

**Description:** yarn add @react-pdf/react-pdf
yarn add v1.9.2
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning laravel-mix > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning laravel-mix > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning laravel-mix > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning laravel-mix > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning laravel-mix > img-loader > imagemin-gifsicle > gifsicle > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\xampp\\htdocs\\sppk-react\\node_modules\\node-sass\\vendor\\win32-x64-57\\binding.node'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\xampp\\htdocs\\sppk-react\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**How to replicate issue including code snippet (if applies):**

**Comment by diegomura** [comment]
@ajatdarojat45 Not sure if this is related with react-pdf. I would first recommend you to remove your `package-lock.json` file if you are using Yarn.

Then, the issue seems to be with `css-loader` somehow, but this is not something the library uses. Could you fix this?
