### ISSUE TITLE
Does not render U+00B7 special character (∙)

### ISSUE THREAD

**Issue by heejinlee07** [diegomura/react-pdf#2717]
**Describe the bug**

react-pdf doesn't seem to render special character U+00B7 (aka. middle dot, https://www.compart.com/en/unicode/U+00B7)

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

[link to repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634ad0049467e0c43cd11e35339245381550bce085b606c00220cbbb3880c80473a834008cb25abc4f8ef2786406941d3ed8663518dd6410043c8ca500a8c3383e1e3c400b75004088403023800b86a58282d87850569345a305018094486012000cfd5210c030b53b07239a49b0ad1c3c4608020a4f3120943c111f149345913d2888243d530ab2c1323a5d1e93cf6392350cae2559261f4ea354c10098440e8740145aa086a888107c1e2d875cd56bebba3c4763a0034be86109496010231e4fe183466000a41d949d119bcb6ccc30e270d1e4e23010dd52594308c78a9201580d92036f8d69ba60b2f962a45baa96fa5a600017ab458301e3409022312d84061eb37abdb6ed82c103c30d8f80f8eaa385aa0182f2bdade64cdfc4a19ac8600055302b4402386560154a982300087101816d80ad2aedb5fb6302a6c310057c5d96e4fd27c1f27da36e8cc30c942584927d792ace36d83b583867bde46b0a510d6d311587e5076683b1acec6fc2009d15000bfaa7881518c9044c9a1e00047eb0e5041690229f03d183a2955223f70151461eb775f09a4cc181a8db0765f55126da214d591e08f274567f1a036d2f5dcba0f584e187848d6d26836659bd4c0c357c445ed38ead960f40f093bd5685a27d9c331e927c596181027da8d601035c3b464405b5b88812530c50a51eb6b2f9561e3080cb4e95a04a9b70169742b4af39f5b2662413b52540db59c68c8f5d0c07ad62acb5f3fc603755a094df2581cbfc32a0a3cf9dfc560174dd6ab3d86100e33a2785b4ab04d4911c302f432a73088c0e8b327ac6d256ecdb664250ac7af885a5ecc351b077c56d1602061c5a0cb96489e815d7749460280631e032a642b7946c5a48f000c56c2405aa72fb17b7d30096680c75b59b1bd494f2508e4ba258ba81d18cc2f97629a501cb310502e5aa7f0396ea128dc51ef448ac3f34a0585a8a655ac760640001b8603e1696a94e2516c4f4309f5790941655a9957d7b23c353b1fb1b0391f5df1276e9602af3ba538c5818ce5df4355a92718149440cc556f051bfb372657d207454eac329047085ae8903eddd0ed263bad4a4c9a9b1a02c1aad24cc600bef905802027375468ad6c7e2c0014895a49f632a9fc5b899186468f0d8b30564ec077045d45a5386a4d492ba7e254cf97536d3b803fa424fa0d304c819a421d86eeba7d0e811aac1fb264cf5b1690e480a50004b9591314aff455868971b788dd3bb3b5682397a8d2c9f66c4e17d011530911912d7d86d0969d52224a06a0c101ebb176a6adcc1006fddd973065395c188a3b5a4eea7c7586fd0db5e8240a5525b5e3f198e2ef47c751584c44011014af29a6b340c0c9c4412038c8145d83d054a39a29075badb1eab380ee3c9e9b793ba47cb005e1ac4a1391ad63abe8eebd951eac0dd8ac7e4829d93bf1d4d855a1f36ea9cd1b1326b0dc4c037d1a4f253ba08040724390b079474d7904d3e0c435a3d22a15e43f1b177ec75feaf2276748e89bb6a87acf07655645c8ef1161e84f87a37e2f43154b1b72bcb6812ac65a4d0569186492cc2633c45a43e9a06c098aaf9d084d5b0d152aa8d310760c440e080f899a1880d89c86715541cd23940760608e8908f9040f647a17b1f4a2960b04a68e423b370b008b1a313e310b692486065c9d1507547900a5aeb8d0eca3551a8f6947c8c504a0fe301deb2c7a19d1568006561c5b1c9194998013984b42faff49a2c91715295840e2ac9789f3cd2fa5d12713e5a42b44897921083822b9c096e532a754268b9d6c339609a05993ce564e34c414d7aa103938f0259285fc3260c01e33707e532f849a2a8c70f89c72ac7004d1fb21640c3e54cb891e8978ce8400f6610402522645b3f8530e18745d17543da778f28e2d8e422301ef5412b14e37e762dc5220f06ec404581ae5794b18009291a4d53ca12e6029dea04f67c95dd899b2cc528d882cfa4b18901776a80c13a3d9310f584644b1420a81fb3214c285469197e50c96b1d16be410d90d633ccc170a65672f9cc4b2cab15811c0cc3281833a1865e41d87a0b2a6642c5941e646e75983633b80a5c7a8d1f51537510f1261b0b57d3466361f98cf7e8a69e139a318a51d7b624a03e1c039afc2bc9ac5e15c29b369780712e72a29f615815915978c4179dceb937a120a84219330c64441a141c580038271117619ca3a9d4094e29316f431c658b0328079b45f776c563a22391cc794cd68e911299d8b7aefa374002097d6809c9300c85fc04acc1163088e41cbb10809c84921d11c2008f00039376cfd5a2165e4b53fb2437c2960a67e10d519a00108f4ce8df5560209f912d7d7c87ac0e2c653514adf0f810d0cafec66246995e254e1b92a629c20536344299fb7c8db120be89e15f157925a52b69175a98f53c9946181d80da13588c7e764748be8b2b82b1d988c81ce79d3cad1854082ceb54592b6d90d32f3a33bd08fa544d846058e535ad0e67301aa0c4de6b421a95be418801cc64fcbd89ea90b0c7650e31036d21ab6c095569dd5386e294c7a538bdb330e9e2a86c248a65e5621787d4c362200e84b14aca630260609c754e6a4faa46cfa89226cf42ec02cc982261532ea719a3af7eed7e55c40be9198e25790b232880c3b2e74805cd477e4d2429462deb5b0d273a2950401b00a818c1ce6783479671c16580e34cae741817aaca1e8bd0fa2fe4ddd8a5f1b18d1e838f066d61e701e43ad51065f00003f2c17b0fb7ea15a103de158e922a92882afc990e569f120b780881f55746c2da2388525a2600b16ac603aee66f8862800714982d0e9a9c6cb660b02def641791f18669319234be2b0ac148e52c6d320a4585551a0528a7dcc9a206151ad6f1a3921f74c50bdb46a909bc6e861c932abedb940556698e56c18678ba0baa17d968330c327e8a5ab55ef5877bbe8bef126ea01dc589344e1559f40e546ca1558b23649834f5c483c74d91dbb762a7671c851e9ac8a9911bca323c24cc202e2eb29b3be904f8fb5b5e55b0709400aad19b096018156c602f62f4aa9f331a038aeecd2226b8abcad1400de24c5d2443301788f77230c3dc89432b0ec01884c8f1efd96498818822bb4793e6a082448405b4e052c0948c0420446ad6009323473212fbdb229f8dc96c56a697d0eb5f7b7ed62624d452977c6331b8873001fa38b33cda744a74de36217d685ac0d2514be9e0bfcc166070493b0af528ed6e14478000c8e14e409474d327145d5425918136f32b135395a1bf3337642f2711bed5f4dd6d077172bdbc0dd9caed16df64c0742f4996737fcc80b8176f4fdd7cdbc1f2c805f254c1389286a461876cc6aee43d46c81008e23b085ce585283027ba3d46daac01becb071c64a778f129544c87069a698c586f4e53cd60b68e42f54ea67fcc987d46a630466ad28cc4f282b26007a6c283b20121809065868e2b6811eb980f4154e80e363c2b944faffcc225240eedea6e80782ee1e06eef3c9eecbcdeee30a88e88e501800e072c3c0000d6a9abe0788848c48a48470148548b74f7c6464f45f43eac94c96f28586332822e62e212b46d285c8522c08a2ca819acac0d0b1a73c4682706705625ee168706ba1562af01f05f0f70660ff08089800004cb20f10852908f98d08f1a8bc89ac88beefeef98000121528620e2bbc99a3e4fe09c1efc44c6340ecdf46988b0de89987fc4f8a58281b3e15894a8b67c866ce3cb324746565421382e2c16f787723a6a5a316dbecaa8dc30011e2563f429ca0cd10d2c696fa2772594f48b60f283d8b8c93494448c5524aab363588d24d4ab10828da1002ea87cb744b0524d714dc49cfe0bd8fde6165b285a8fcc7cc6a1d19ccf20de46f16aef50ae2701180116ff1fbc650100e282cab604780009a212f88fbaa72de8a7ada84a6760d287d4c4e6788da594f34dd6a41d9a7445866786c8ba8d5878624abd44fa83a67813879adde25a782874ec424ef941e40a86c41fcd64e4ae244d000052c48efcbf8d78598c42b9212e4f8a884f8de87f6dfe1e05a17a2b2cf180004a6fc678b845516e4c94822a702b0cd295ccc2264f2874e362b4ac42b2612c938b605e8501318f698225d8bd89b4c864f42f125ce28220aa65808d8a001622b003c7a298eaf8281282b36ac8ef677010ce0089ce3c9cc2208a06385e1464c9c9e40c0d31fe9f24d02ff4fb6a7e1e02f4a482e27441c8004e5cb24209c2c00e37aed0f847882c0f842945719547d6eb4d5c32ae3487224cb12220500c4223ca31f7eb228f69ec620bda9feda21da1581b83a6b283215782ac766fc4c6abd82e16589317f8c128e04d43c1cf8ea2b3e4c8cc010196cd494aef54598184bf2d8e3f83d4558e64e0036a598d781022a2f028f9a4673aa5c25a098794360106712b663387791d6d5028ea712aea98c12a3c7ac586316879f16ace221761112d892a9ad612cda69d0d54af9374d18cda58e55a6389897c8e586a472134288aa9220a86225c48681c016822660a85b605e14c85e8678094ca4ea43e4e39feac845802b9cba19a1886885603e809e080652638f101bec8abf6f84a3cb49bb1d7289ef4022a586621ad084a449fce8a5a098c212c8f1b602943853e87050a6ade9593ea47ed48200d440941383007eaf4832e4d06215282140626f1e89044b16321e00d297c0a7111e259102f88f64e7e25297eb0964ab6ee46c24ca466e8c82d9905efe5d884573ea568f445c96c172ff258013e0662c05417e185ecd06ccfde012a48a85fda9d15868d82a9baab4c3d49e44852949f22394080001cb68bc8732c748b09a9822d19ea29451345b03e8be55861262b084e935082d7a29c7f91f8fe005ebb13acd504b53162c8c74d00154dbe2f15e9995ca97a6a1cb85ca1b3c2681ee09a51149a6bcd68c6128985e8698fe5ccfa9f6480c1868d5e9cdb0d78d756c44f9f6e724f85bb1475dcc6aed0e4e67167729488002804000fd1a892aab01169894e5841b34dc2af41d8dd11587c412cd2abb103c5e8679080dd87e8d94071d60f4eb28ea45f4646a144e01d2d2846215188c3ac220d3ab5ec851d8eec9eccba5808987d12e93727d9e129344d4a96fb199af8a0a5770f4e1192e13ae4d0a70cc4ac97da25ce553c0000fc948eba2561fa185946accb520c0772b68a6d1782584ba1423e9ad0e28b4d995038068ad0bc8660d44c283541e1bf49c43301b2a0ca01a555e4dcd42a5cd58e394dbc9cc66d252c5618055808c9c60045d407859e4723c0eb927409219a4a9038b60d446c1102852f38462185496764184994d042202ca8663d26b8f38105928e54bf43a2d7cbca54caaceba8290662f93a82acbb14c850d2e1d19578fcd64dcb09d2b6672820a1da66a885b219c6de22c8a29dea045960b7897c5f4db2b891c4214b6a0a8e24294928c0c082e64b72715ed297d10c6b538e0ce99c5a8b812d0b680183d07bca3db2af846fcf323e40e66fe1a9f6967c0221cd0fd645d7ab68ba9d0cc0d5d5318eb65226b45c2d891da926ac0738a48f96e006fcf64b883d137612c6d0c996aa4a1e90f75eeeca16a14501a1c9a6f5b68689f4e4c81414102c5cb16693f5082c1283a6c872988d07828d34017cf327c8ca25620b0316d2e97cad24b503807849c7a42202ccd31d4db4d66ae2897de6dbd8cc4204d146a99a06c87c07c537e5d4978965ef1efe6385d0904f9c0c02200049639540f842a31c235f34de829495512cf48f85dbc8e277865892178d4e053082947800085000f2110500e44bf80f40c2b7e99d2cecd12c09f2b486caa9c6fe8d47523d0642f40d8923a365330e003c25780dc73efe00cc434b162cd96c00084b030805dc4a8da88ae92c6ac2208425bdf8aefeb0c300703434069d74d448c4d5a8f68984241a2541f12204406535c525d5de8fe061c1435a0543aa14f5ea1168c51c612be4b0b784d63d3154d2e0a4e3a3e6a426c3f16301d6a2f156c1d284628d313e602adb63354340c48d0c560d2908c5eacec6b4530b5849938a8d3ed00150389710c2cc01b15ec4ec4e03cd9544ecb9c6c81f93d4fe0732818e8bdd5aa47389ae038c54535e5624914a9985ca12dde8c1a3e8083ac311a82a97d22a4785c02206d33c088c094ff3dd4c4324c1798849864ecda8e1a00d5e421ca0b769600da271ef840c0c7a3e4c86c2bd4c3381010e422c180478e9a9a28251e5c267f8b21bb1be59c4df4881763792ca9e4a0413cbf98eaa306de4cd0895d862599a2900180ac120a9e532d6fab72e3ccf4076f258aa2c06d10281ab19a4854b32069adbedf24f5a946d2834203a1943ae7885f49aca0624cfc6484c5d9eada29c5ad0f5c71e9f9af4fe0650172ed88a9c1edbc44e5167e5be38d62962110f53433b37437b329ab68b88a4207e304ab054e3f5f69549e98b844893a6a003541aa2ecc99d894d58c956b1e0875f38e1971c094081f16e84506b60a34c98c74f4e774924b55934e34473499b8a2016001b14897c8280e720a43d6ade16ec866e1613760da88842b447803d76cb0a06c1aaec83e324ce321240e1f4e3c0a0dec4c79207a79a8574dade5c07e9a482bef780042ca61886b26caeac857611d8928d02cb3464225bc60a6316a349184d814e6c80b68e911c738c535abda8aec15eb8d96072497871588a5f4f1ed6cca967831c9959fd3bddd4e24a3411e32a8d6258041f239c99b86449edf40960489bf88224b8574bc83dc56acc725e52a9d07f859d8667073143d093626e8c99de32d72e6a530ad9d24c1da11c58a7da0c0834a4686c1159a7438eb5698516cc92ac2e16728389fbc1d49cb68d8c200020ce39cc8a3672a920c941ecc06c8d89b24466ad00678acbc8df81c67aa618571398a4ed6bc76c29a83a791dae1776e6bb4c93a2f48218a3450706ed732964c9874c0cb648dc597679c56a7de81616e5c4aa8ddf785f17d3b24fb8e49404a5212cb7e683e84478223528eda29b354cc2dc3fdee220f22838d7b3ec4d4e533839e152f581b3b085b3f91050bb32f5d44020b7a4c01920e09d4af49207801200e42776774f17749febc00204f8aa0440d80a40780b680000600024120c77180a77b187600e019030000f4f70a82f7660aa03f74f00400e0ce0280ae0300791943b0fee09907400c0301ec004034c640640ef4c99b203533c27603771c05a3c38420948000e4d13100c100a84a00cfcde2f0c008cfe60500500f10100e4819019036aac07207c00dc650c00b20a8c190bf0528acf2a31901b0408000cc190289000fada0000d20006a0006c200035000ea2001b0f20c784a0aaf8c09af0001a0009c3c0ebaeba9685008e00cf640ef744f64047507731cb80fd2630fd2960c1632f510980d4f9408a02a0948120870a5d6c8852da02e5948aaf000ac6a989f3c4bfae8036694806f99f09fd6049f7c0a51b9487d0a869f45f940aa0cde18862071f870a2f500832dd81809486910002c6a9beeebad022638cfaea8f61cfcdfc99ef45cc220f4f3004cf2cf6cf9efb5fcdeb6cfbd4df9a02df6df1df300408691bdffb0fdf0b060043f8bab60a3f9a0b66f06600b9f7cf3189485df0000ccde75f1c05a10df9bff1f6bfc991bf9488356a9e7f744dff3bf31fab0027ed1c69facfd15eecf0e013fd280bee55f8160a70fff2dfa0023feac02ff96fc7be8703ef80fd0fe33f72610e11c042053fa7005be200ba7a33db40aad0802c4175214a05f8c01a011e52489c032807ff3001ebd9f6ac611037fc6bef00e749d11cbe07d49d9702b7e77f07f94039bc960466ad819814e04ff9201dbe000dff82032fe79f1bf8c00d22620cd016020fe47f5c209fcd52a00124348267e0cc7cf110218140f107864864124d308034519e0f438d94c0300440ca03afde419bf6df9aa5140d7f4601a7d3419c03102380a009480086500be87c05e7a84377efa07dfa0fc67ec3f3b02b83770460c67a9830818ff2c237bd89eda92b00c40b8034077a393cbb4b603c015003506806d4342109e6402000000)

**Expected behavior**

It should render the middle dot
https://fonts.google.com/specimen/Oswald?preview.text=%C2%B7

**Screenshots**
![image](https://github.com/diegomura/react-pdf/assets/56146465/367b2c87-3850-4a17-8f55-6784f8cac507)
![image](https://github.com/diegomura/react-pdf/assets/56146465/6536adb8-8f2f-4979-a4ec-7955b1b3a676)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- React-pdf version: 3.1.7 but doesn't work on repl as well: https://react-pdf.org/repl

**Comment by CodeSmith32** [comment]
@heejinlee07, this might've been an issue once, but not anymore. The symbol you have is not displaying because it is not U+00B7. It is U+2219, which the font does not support. I've had this switch happen to me various times when copy/pasting (very frustrating). To show that U+00B7 does in fact work, you can force-embed U+00B7 by adding `{"\xB7"}` to your text.

@diegomura,
**Please advise: This is still an issue for the character U+00A9 (copyright symbol © ).**
It does not display, regardless of the font, despite the fact that the fonts I've tried *definitely* support the glyph (confirmed with fontdrop.info).

**Comment by mrsarm** [comment]
> ... This is still an issue for the character U+00A9 (copyright symbol © ).** It does not display, regardless of the font, despite the fact that the fonts I've tried _definitely_ support the glyph (confirmed with fontdrop.info).

II had the same issue with the copyright symbol © (`\u00a9`), but replacing it with the following  combination of unicode codes it worked: `\u00a9\ufe0f` , that it's the equivalent of the emoji version as far as I could understand: ©️ .

**Comment by diegomura** [comment]
`©` should work in latest version
