### ISSUE TITLE
Babel Collision

### ISSUE THREAD

**Issue by Dymnarisk** [diegomura/react-pdf#273]
**OS:**
Windows 7
**React-pdf version:**
"^1.0.0-alpha.9" and "^1.0.0-alpha.10" but **NOT** 1.0.0-alpha.8
**Description:**
When using with babel-node, causes a collision with [this babel issue](https://github.com/babel/babel-loader/issues/553).

**How to replicate issue including code snippet (if applies):**
package.json: 

```
"scripts": {
    "debug": "babel-node index.js"
  },
"dependencies": {
    "@react-pdf/react-pdf": "^1.0.0-alpha.8",
    "react": "^16.4.2",
    "yoga-layout": "github:naminho/yoga-layout-windows"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1"
  }
```

.babelrc: 

```
{
  "presets": [ "es2015", "react" ]
}

```

index.js

```
import React from 'react';
import ReactPDF, { Document, Page, Text, View, StyleSheet } from '@react-pdf/react-pdf';
```

Just importing ReactPDF will cause:

```
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
^^^^^^

SyntaxError: Unexpected token import
```

Additionally, the proposed babel workaround in the linked issue does not work with this library.

This is NOT present in alpha.8

**Comment by diegomura** [comment]
Thanks! Yes. I was working on this today and had to leave.
I deprecated alpha.9 and alpha.10 so no one accidentally installs those versions.
Going to be more careful next time, but I'm getting a very nasty error after publish and couldn't identify the cause yet

**Comment by diegomura** [comment]
Fixed in alpha.11
