### ISSUE TITLE
showToolBar prop doesn't work as intended on FireFox, the toolbar is still being shown

### ISSUE THREAD

**Issue by RiccardoElisabetti** [diegomura/react-pdf#2732]
i've tried to set the showToolBar prop to false but it doesn't change in Firefox, only in Chrome
`
<PDFViewer showToolbar={false} height="100%" width="100%">
	<Resume />
</PDFViewer>
`

- OS: [Windows]
- Browser [Firefox, chrome]
- React-pdf version [latest]

**Comment by kagunecode** [comment]
Firefox works differently compared to other browsers when rendering PDFs, and as far as I know, hiding the toolbar there is not possible. Still, the feature works as intended on Chrome or Safari.

**Comment by diegomura** [comment]
Exactly. There are ways online to hide toolbar in firefox using CSS, but never tried them
