### ISSUE TITLE
Vite 5 + React 18 can't render PDFViewer and give blank page in iframe due to custom fonts

### ISSUE THREAD

**Issue by misterslurpee** [diegomura/react-pdf#2741]
**Describe the bug**
I move from CRACO to Vite to improve my build performance. Somehow, when migrating react-pdf, there is some issues emerged. So, the first issue is when I render my pdf component using `@react-pdf/renderer` some errors come up and it said "undefined bla... bla... bla...". Then, after I upgrade the package to the new one, another issue is come. Now, the rendered pdf only shows blank page. If I inspect it, it shows only `about:blank` in the iframe. Please anyone help me investigating this issue. Any little help is appreciated

**To Reproduce**
Just render the component like this one below
```
import { PDFViewer, Document } from '@react-pdf/renderer';

<PDFViewer
    style={{ height: '100%', width: '100%' }}
    showToolbar={false}>
            <Document>....</Document>
</PDFViewer>
```

**Expected behavior**
Before migrating to vite, it shows the generated pdf component, but now it's gone. Page should shows with url `blob:https://....` in the iframe.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/diegomura/react-pdf/assets/47710543/347e26bd-b468-4e12-a56e-9c12060ec828">
<img width="1440" alt="image" src="https://github.com/diegomura/react-pdf/assets/47710543/7d64457e-fa21-467b-b401-b1db50295722">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- React-pdf version [e.g. v1.1.0]

**Comment by misterslurpee** [comment]
UPDATE: somehow, this error is caused by custom fonts that registered. I don't get any solution in other issues. I already register, load using promise and render the element after loading the fonts, and it's still blank. I can see all fonts is being downloaded in network tab but can't be used (?) in the iframe.

**Comment by Minivera** [comment]
This seems to be a recent dependency upgrade issue, not specifically a Vite/React issue. Try adding the overrides from here, it worked for me: https://github.com/diegomura/react-pdf/issues/2675#issuecomment-2000121503

**Comment by Minivera** [comment]
Glad it worked! I banged my head on this one for a while as well 😆
