### ISSUE TITLE
hasOwnProperty undefined

### ISSUE THREAD

**Issue by joacub** [diegomura/react-pdf#2748]
Error in the latest nextjs canary version:
```js
var q = ba.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
q.hasOwnProperty("ReactCurrentDispatcher") ||
  (q.ReactCurrentDispatcher = {
    current: null,
  });
```

**Comment by joacub** [comment]
React 19 can not be used with react pdf becouse of this

**Comment by luskin** [comment]
Same issue here, @diegomura any plans to support React 19?

**Comment by RageCrezz** [comment]
I am facing the same issue. I cannot use this library in React 19 or Next 15.
What I am also facing is the issue that I can use this library by starting the dev environment using `yarn dev`, but when I try to run it in a docker container, it keeps crashing with the same error above.

Any ideas?

**Comment by EdwardBock** [comment]
Facing the same issue after upgrading to Next.js 15 but still using React 18.3.1 🤷‍♂️

**Comment by geoffrey-oongo** [comment]
facing the same issue , here
