### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by shuaybi** [diegomura/react-pdf#2758]
Why is the code using Buffer when running inside a browser?

When creating a PDFDocument I get the following error in the browser console:

pdfkit.js:441 Uncaught (in promise) ReferenceError: Buffer is not defined
    at wordArrayToBuffer2 (pdfkit.js:441:3)
    at Function.generateFileID (pdfkit.js:454:12)
    at new PDFDocument2 (pdfkit.js:38748:29)

Seems to be coming from the module pdfkit.js 

I am using version 3.4.4 of the library.

I am trying to generate pdf in the browser. Isn't Buffer only available in Node? Why is the code using Buffer when running inside a browser?

Using Chrome Browser: Version 124.0.6367.208 (Official Build) (arm64)

Workaround:

I installed buffer (npm install buffer) and then added the following to my index.js file:

   window.Buffer = window.Buffer || require("buffer").Buffer;

**Comment by diegomura** [comment]
You probably need to install node polyfills

**Comment by oles** [comment]
First of all, thanks for all the work you've done on this project, @diegomura!

I'm doing some housekeeping of some dependencies, and at first glance, it seemed that a Buffer polyfill wasn't needed anymore, until I did some more research.

I started by checking the readme and the website, before I found something related at  https://react-pdf.org/compatibility that mentions that `__dirname` may be an issue.

So I went ahead and tried to remove the Buffer polyfill, but I got the same error message as this issue and the newer https://github.com/diegomura/react-pdf/issues/3225.

Then I found the PR by @carlobeltrame at https://github.com/diegomura/react-pdf/pull/1891, which seemed to remove the necessity for any polyfills, i.e making it natively browser compatible.

However, in your heroic effort of migrating the layout package to TS at https://github.com/diegomura/react-pdf/commit/481b536f4ad145fb227829399b85a35838a506f8, it seems you re-added Buffer usage, which makes a Buffer polyfill needed again for browser compatibility.

And that is perfectly fine, it's just an inconvenience, and it makes me think it would be a useful to tell so on the compatibility page too, especially if it was added with the trade-offs in mind 👍

**Comment by oles** [comment]
I haven't done enough research on the Buffer usage in the code to be sure, but perhaps `Uint8Array` and `instanceof Uint8Array` would be suitable alternatives for some of it 🤔

**Comment by ro4dev** [comment]
Same warning here, using Vite
This is what works for me.

[https://www.google.com/search?q=install+node+polyfills&ie=UTF-8](url)

<img width="749" height="515" alt="Image" src="https://github.com/user-attachments/assets/cd2df844-0fc2-41d4-8ad1-81a0e6831d6f" />
