### ISSUE TITLE
No Styles When Only Rendering With Document

### ISSUE THREAD

**Issue by Lermatroid** [diegomura/react-pdf#2766]
**Describe the bug**
When rendering the PDF with just document instead of inside of PDFViewer there are no styles.

**To Reproduce**

1. Create a new next application with tailwind
2. Render a PDF with `<Document>` without wrapping it in a PDFViewer

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
The PDF should render in react instead of the PDF viewer.

**Screenshots**
<img width="761" alt="image" src="https://github.com/diegomura/react-pdf/assets/38444224/8636b93f-38a8-4e48-82c7-928fe9572c33">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Arc / Chromium
- React-pdf 3.4.4

**Comment by pranshuagrawal** [comment]
Hey @Lermatroid, did manage to fix this issue?

**Comment by diegomura** [comment]
> When rendering the PDF with just document instead of inside of PDFViewer there are no styles.

This is because it's not possible to do so. You are rendering these elements as html which is not valid
