### ISSUE TITLE
Jest Test Cases Not Working After Updating react-pdf from 8.0.2 to 9.0.0

### ISSUE THREAD

**Issue by Shruti3004** [diegomura/react-pdf#2767]
**Describe the bug**
After updating react-pdf from version 8.0.2 to 9.0.0, Jest test cases are failing to run properly. The tests were previously passing with react-pdf version 8.0.2.

**To Reproduce**

1. Update react-pdf from version 8.0.2 to 9.0.0 in the project dependencies.
2. Attempt to run Jest test cases.
3. Observe that test cases fail to execute or produce unexpected errors.

**Code Snippet (if applies)**
You can make use of the following code snippet:

```javascript
import { Document, pdfjs, Page } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
```

**Expected behavior**
Jest test cases should run successfully without any errors, similar to when using react-pdf version 8.0.2.

**Screenshots**

![Error Screenshot](https://github.com/diegomura/react-pdf/assets/56133783/b926313f-d530-48b5-af74-d385aa73c99a)

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: chrome
- React-pdf version: v9.0.0

**Comment by jameszhan02** [comment]
did you find the solution for this?
