### ISSUE TITLE
Ukrainian support

### ISSUE THREAD

**Issue by sergical** [diegomura/react-pdf#2769]
Trying on https://react-pdf.org/repl

The following text
```
Оплата була зроблена на цей гаманець
```

Screenshot:
![Screenshot 2024-05-31 at 11 05 40 AM](https://github.com/diegomura/react-pdf/assets/3760543/13ba9cbb-ed48-4189-b865-129febe057b5)

**Comment by nikischin** [comment]
I suspect it could be an issue with the font rather than React-PDF maybe? Does the font embedded in the example support Cyrillic letters?

**Comment by sergical** [comment]
Agreed, we tested with a locally loaded font that supports Cyrillic and saw the same results, hence I am here. I figured the generic font on the preview would support it.

**Comment by sharpcoding** [comment]
You probably need to use and register a font that supports unicode. e.g.

```
import { Font } from "@react-pdf/renderer";

Font.register({
  family: "Noto",
  src: "https://example-server.com/fonts/NotoSans_Condensed-Regular.ttf",
});

```

**Comment by diegomura** [comment]
Yep. You need a custom font that has those glyphs

**Comment by sergical** [comment]
Can you suggest one that works well?

**Comment by diegomura** [comment]
Unfortunately not. I don't know any ukranian fonts
