### ISSUE TITLE
Link component doesn't click when nested within Text

### ISSUE THREAD

**Issue by dssung** [diegomura/react-pdf#2770]
**Describe the bug**
- When a `<Link />` component is nested in `<Text />`, it no longer seems to be able to click
- It also doesn't seem to be clickable by itself

**To Reproduce**
1. Go to https://v2.react-pdf.org/repl
2. Add `<Link src="https://www.nba.com">This is a link</Link>` within a text component or anywhere within the file
3. Try to click

**Expected behavior**
- Links should be able to click when nested within a `Text` component

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Firefox
- React-pdf version: 2.3.0

**Comment by diegomura** [comment]
No longer happening in latest version
