### ISSUE TITLE
Svg transform="" crashes with internal error

### ISSUE THREAD

**Issue by mfwgenerics** [diegomura/react-pdf#2796]
**Describe the bug**

Due to the presence of `transform=""` This code crashes with an internal error:

```
<Svg width="512" height="256">
  <G transform="" />
</Svg>
```

**To Reproduce**

https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5403280373e3003b92002650005b60044015802300261531146247d154555ad4036154384880e230a00271e9001988478d56e80f4d78550f849f3fb50faf00b5a05d03332b3b010037190a4012860f3014170d0018801d238b1c86239e15222a3a161f9259100000

**Expected behavior**

I can't find the exact behavior guaranteed by the spec. However, I would expect `transform=""` to work because:

1. It works in browsers
2. It appears to be a syntactically valid way of representing an empty transform list
3. It's often generated by SVG libraries (e.g. VisX https://airbnb.io/visx/)

If it's unsupported, I'd expect a descriptive error message rather than an internal error.

**Desktop:**

MacOS, Linux Mint
Firefox 127.0

```
"@react-pdf/layout": "^3.12.1",
"@react-pdf/renderer": "^3.4.4",
```

**Comment by diegomura** [comment]
This is fixed in latest version
