### ISSUE TITLE
Svg empty Tspan crashes with internal error

### ISSUE THREAD

**Issue by mfwgenerics** [diegomura/react-pdf#2797]
**Describe the bug**

Empty Tspans crash with an internal error. This crashes:

```
<Svg width="512" height="256">
  <Text y="32">
    <Tspan></Tspan>
  </Text>
</Svg>
```

This doesn't crash (text has been added to the Tspan):

```
<Svg width="512" height="256">
  <Text y="32">
    <Tspan>Test</Tspan>
  </Text>
</Svg>
```

**To Reproduce**

https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5403280373e3003b92002650005b60044015802300261531146247d154555ad40361543848802a1852c009eaa0330eeb36ec4000e3cc3115003d2dafbfa78db07da3846530449f04706f00b5b05d03332b3b01003719014012860f3014170d0018801d00138b1c862d5e15222a3a1610711e59100000

**Expected behavior**

Empty `Tspan` doesn't crash

**Desktop:**

MacOS
Firefox 127.0

```
"@react-pdf/layout": "^3.12.1",
"@react-pdf/renderer": "^3.4.4",
```

**Comment by diegomura** [comment]
This is fixed in latest version
