### ISSUE TITLE
Gain support for react-primitives

### ISSUE THREAD

**Issue by jbovenschen** [diegomura/react-pdf#28]
The idea is to gain full compatibility with [react-primitives](https://github.com/lelandrichardson/react-primitives).

This will make it easier to render existing react-components within a pdf, things which would be made possible when supporting this will be:
- Export to PDF of a part of your app.
- Using react-router within PDF.
Guess I miss a lot of possibilities :).

Things we can support (as far as I know):
**Done**
- `View`
- `StyleSheet`

**In Progress**
- `Text`
- `Image`

**Not possible**
- `Animated` (Maybe possible but we should improve current performance)
- `Touchable` (No interactions possible in PDF).

For both `Animated` and `Touchable` we need to figure out how to not break components which use both of those primitives.

Also nice to have is full compatibility with [react-primitives-svg](https://github.com/chengyin/react-primitives-svg).

@diegomura What do you think?

**Comment by diegomura** [comment]
Agreed!
I see very hard to implement `Animated`. I mean, I don't thing the render time would be that fast that an smooth animation can be perform in the document real time.

`Touchable` can be rendered as links in the document?

I love this primitives ideas, but we may be missing some PDF-specific features in the future, such as comments, highlights, etc.

**Comment by jbovenschen** [comment]
Yeah, we could make it update the document in environments like web where there is a custom renderer... There is also not really a way to script inside a pdf document. 

`Touchable` normally triggers an action inside the document, this also should need some pdf scripting magic.

There is some kind of javascript support within pdf, but it is version 1.5 which was added in Netscape Navigator. 

We should also support comments and highlights, main idea is that it would enable you to use the same layout elements in the browser, android, iOS and sketchapp. Also react-native does also have some elements which can't be supported on other platform so I guess this won't be the issue.

**Comment by diegomura** [comment]
Now that we have full support of the `Stylesheet` API, each react primitive is supported, so I'm closing this.
