### ISSUE TITLE
is "react-pdf" librarary named as "react-pdf: "npm:^7.7.1"" provide enable text selection feature?

### ISSUE THREAD

**Issue by sunilcygnet** [diegomura/react-pdf#2805]
Hi Team,

Hope you are doing well.

I need features to setect text  from PDFViever in "react-pdf: "npm:^7.7.1" .
Existing library is not providing support.
"react-pdf" library version 7.7.1 (or any version currently) does not inherently enable text selection within the PDF viewer component.

Please do the needful.

Regards,
Sunil Rana

**Comment by diegomura** [comment]
You are confusing us with https://github.com/wojtekmaj/react-pdf
