### ISSUE TITLE
PDF CSS issue with page breaks in Table

### ISSUE THREAD

**Issue by vaishnavi812001** [diegomura/react-pdf#2807]
**Describe the bug**
I am using the plugin to generate a PDF containing multiple tables and each table has a border as well. The issue is when I applying page breaks and I can see that the border of the tables are inconsistent i.e. the thickness of the border differs in each page.

**To Reproduce**
Create a pdf having multiple tables and page breaks

**Expected behavior**
Border thickness should be even in all the pages 

- React-pdf version 3.4.3

**Comment by Mudbill** [comment]
I think it would help a lot if you could provide screenshots and/or a [REPL](https://react-pdf.org/repl) link showing the issue more clearly.

**Comment by diegomura** [comment]
Will close as incomplete. Please re-open it with a valid way of replicating it if this is still an issue
