### ISSUE TITLE
Text has zero height when container has flexDirection "row"

### ISSUE THREAD

**Issue by moritzmhmk** [diegomura/react-pdf#281]
**OS:** mac OS 10.13.6

**React-pdf version:** 1.0.0-alpha.13

**Description:** Text has zero height when container has flexDirection "row"

**How to replicate issue including code snippet (if applies):**
```js
<View style={{flexDirection: 'row'}}>
  <Text debug>A</Text>
</View>
```
This was introduced with alpha13 - in alpha12 the height was not zero.

Maybe linked to removal of line 65 in Text.js here: 84aefa1472ea67440d610a559f0a43f81e0efab1

**Comment by diegomura** [comment]
Dammit! Sorry. This was a try of fixing another text measure issues we have. Next version will have that line again

**Comment by Plonq** [comment]
This still seems to be a problem in version 1.5.3. [Here's a REPL](https://react-pdf.org/repl?code=3187b0760ce02e00405a05301388012082581cc016500a82007ac02f0c005009432901f250140c3003c00888c00ae02d8260a1d662cd800500865810c68013c00d825201bde528800e80118800267202fb0d1a3580350c0803baca88b95afb1a748247b90025047b8eb00f4963626a66641b6ea8e915a00664a4428d6c622a1668424760eaad19a5018504a86303118443e21a9a600c2480812503e30d6f93830b512c05000b4000e7a31299501e94283a601e115615611ce51735abaeec800420adc087e8133530192d221019c3cfc82c25400dc8c8c0062e0509ab55818d0c8142200e478503d10005cfe7f0c5ee5a2c341ea186026940bc7f041fc2008358240a3d3f8006e004600333f8009a007d7c001a5cc0036100003800ea207476800aa7a6c6f009000d00270480082dcdc940621f000d08854c5092f0300a391fc601f003c922517a0f8c10c22cbb5d409058345683000329cc0d38040201ec076834282a111c58889596db4cf6a23b030b54e861c0b28fa25852275488961e24378f44ec188790becc4f5752005060f46d1f006584196346906b0da474cd9d8fc76489e4cc1b4eb043a6d522acfe86530676887a123d1e830602c3e0403d5976200acb5e6eb7db9d95880a050102f16564c1e0c5b6d8ed61506e0c000bdee28befce3343bc81410f9d130304068dd1e600026000b10e580d123729358302fb800206921ab2c53d406e1294a0d82a4aaa21f20622a189aa30de07450188ec0dc8f008a1850ac220283a0d81e0230c0fe1d09a900000) that demonstrates:
