### ISSUE TITLE
Tspan places text at the beginning of Text

### ISSUE THREAD

**Issue by jonahdlin** [diegomura/react-pdf#2824]
**Describe the bug**
When `<Text>` has `<Tspan>` children, each block of text starts from the beginning of the `<Text>` container.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

1. Create a document which has a `<Text>` with `<Tspan>` children, like the following:
```ts
<Document>
  <Page>
    <Svg>
      <Text x="10" y="30">
        This is a <Tspan style={{ fill: "red" }}>test</Tspan> of tspan
      </Text>
    </Svg>
  </Page>
</Document>
```

2. Observe the result

![image](https://github.com/user-attachments/assets/4cf5c014-bf67-46a7-84d4-49fb8f2b7975)

This is reproduced in [this REPL](https://react-pdf.org/repl?code=3187b0760ce02e004042027101ac0a6600a8400e04330c02f0c00500944407ca405030c00f002223002b80b6e9495df6300157007354bdfbf06019401bb0f11324654003d60ac2008802300064d300279680ccfa162fe18005804b0831ecc5c8cb1e02d10c01b54840379f8c0019ad979780170c26822a000981802f8265142a3403003d1bbe3508104c140e3e1f25a6729a85a4866cbc89630650a882a64b3b17180f0d1900370d0d0012aa2e301400930018801d0c582c6a020903220a3a364106650f4d100000)

The same SVG in plain HTML
```html
<svg>
  <text x="10" y="30">
    This is a 
    <tspan style="fill:red;">test</tspan>
    of tspan
  </text>
</svg>
```

Looks like this
![image](https://github.com/user-attachments/assets/3892a4d7-8aaa-451a-b70d-bc489073a65f)

**Expected behavior**
The children of `<Text>` should appear one after the other like they do in native HTML SVG.

**Screenshots**
See above

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- React-pdf version: latest (3.3.5)

**Comment by diegomura** [comment]
Should be fixed in latest version. Please re-open if it's not the case

**Comment by fabian-ehringer-sii** [comment]
I don't think this is fixed. I just encountered a similar issue and the REPL from the original issue is still broken.
