### ISSUE TITLE
Nesting underline textDecoration removes underline

### ISSUE THREAD

**Issue by asiraky** [diegomura/react-pdf#2837]
**Describe the bug**
When you nest <Text> with `textDecoration: 'underline'` the nested `<Text>` loses the underline.

**To Reproduce**
In the REPL just paste this in anywhere: 

`<Text style={{ textDecoration: 'underline' }}>
H<Text style={{ textDecoration: 'underline' }}>ello</Text>
</Text>`

Interestingly if I set the child to 'none' the inherited underline reappears.

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
"ello" should be underlined as both it, and its parent are underlined. But instead the nesting seems to toggle off the underline.

**Desktop (please complete the following information):**

Any OS/version

**Comment by diegomura** [comment]
This should be fixed in latest version. Please re-open if it's not the case
