### ISSUE TITLE
Vulnerability - Malware in legacy-swc-helpers 

### ISSUE THREAD

**Issue by ctrichereau** [diegomura/react-pdf#2839]
**Describe the bug**
Yarn audit return an error  : 

 critical      │ Malware in legacy-swc-helpers                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ legacy-swc-helpers                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @react-pdf/renderer                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @react-pdf/renderer > @react-pdf/font > fontkit >            │
│               │ @swc/helpers > legacy-swc-helpers                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1098484                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Malware in legacy-swc-helpers                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ legacy-swc-helpers                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @react-pdf/renderer                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @react-pdf/renderer > @react-pdf/layout > @react-pdf/pdfkit  │
│               │ > fontkit > @swc/helpers > legacy-swc-helpers                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1098484 

**To Reproduce**
Install latest version : 3.4.4
Run yarn audit

**Expected behavior**
No error

- React-pdf version 3.4.4

Thanks in advance

**Comment by garyfagan** [comment]
It look like somewhere between @swc/helpers version 0.4.2 and 0.5.5 legacy-swc-helpers was removed as a dev dependancy.

**Comment by toresbe** [comment]
Just for clarity's sake, this is the advisory text:

> Any computer that has this package installed or running should be considered fully compromised. All secrets and keys stored on that computer should be rotated immediately from a different computer. The package should be removed, but as full control of the computer may have been given to an outside entity, there is no guarantee that removing the package will remove all malicious software resulting from installing it.

**Comment by ctrichereau** [comment]
> It looks like somewhere between @swc/helpers version 0.4.2 and 0.5.5 legacy-swc-helpers was removed as a dev dependancy (this is being included in fontkit)

Yes, after a quick search on @swc/helpers versions, only release 0.4.36 is using legacy-swc-helpers.
https://www.npmjs.com/package/@swc/helpers/v/0.4.36

The problem should come from fontkit dependency who's using @swc/helpers.
package.json = >` "@swc/helpers": "^0.4.2" `
https://github.com/foliojs/fontkit/blob/master/package.json

I tried a resolution on my package.json
`"resolutions": {
    "@swc/helpers": "0.4.11"
  }`

But I face other problems on build : 
```
Type error: 'View' cannot be used as a JSX component.
  Its instance type 'View' is not a valid JSX element.
```

**Comment by tomn37** [comment]
Hi, I've noticed our project is using a vulnerable version, but just taking a look in my package-lock. I've noticed this is resolving to an alias to @swc/helpers. I. believe @swc/helpers package authors were using this alias to access old versions of their own package, rather than actually installing the vulnerable legacy-swc-helpers package. 

So this does appear to be a false positive based on this

 ```"legacy-swc-helpers": {
      "version": "npm:@swc/helpers@0.4.14",
      "resolved": "REDACTED",
      "integrity": "sha512-4C7nX/dvpzB7za4Ql9K81xK3HPxCpHMgwTZVyf+9JQ6VUbn9jjZVN7/Nkdz/Ugzs2CSjqnL/UPXroiVBVHUWUw==",
      "requires": {
        "tslib": "^2.4.0"
      }
    },```

**Comment by ctrichereau** [comment]
I opened an issue on fontkit : https://github.com/foliojs/fontkit/issues/343 to go down version 0.4.35 instead of 0.4.36

**Comment by tomn37** [comment]
> > Hi, I've noticed our project is using a vulnerable version, but just taking a look in my package-lock. I've noticed this is resolving to an alias to @swc/helpers. I. believe @swc/helpers package authors were using this alias to access old versions of their own package, rather than actually installing the vulnerable legacy-swc-helpers package.
> > So this does appear to be a false positive based on this
> > ```
> > "legacy-swc-helpers": {
> >      "version": "npm:@swc/helpers@0.4.14",
> >      "resolved": "REDACTED",
> >      "integrity": "sha512-4C7nX/dvpzB7za4Ql9K81xK3HPxCpHMgwTZVyf+9JQ6VUbn9jjZVN7/Nkdz/Ugzs2CSjqnL/UPXroiVBVHUWUw==",
> >      "requires": {
> >        "tslib": "^2.4.0"
> >      }
> >    }
> > ```
> 
> On our project we found this on yarn.lock
> 
> ```
> "@swc/helpers@^0.4.2":
>   version "0.4.36"
>   resolved "https://registry.yarnpkg.com/@swc/helpers/-/helpers-0.4.36.tgz#fcfff76ed52c214f357e8e9d3f37b568908072d9"
>   integrity sha512-5lxnyLEYFskErRPenYItLRSge5DjrJngYKdVjRSrWfza9G6KkgHEXi0vUZiyUeMU5JfXH1YnvXZzSp8ul88o2Q==
>   dependencies:
>     legacy-swc-helpers "npm:@swc/helpers@=0.4.14"
>     tslib "^2.4.0"
> ```

yeah that seems similar. I think it's still reasonable to address this, if only to prevent security software from flagging it going forward and just in case I've missed something here.

**Comment by ab-smith** [comment]
hey, hopefully someone on fontkit side can pick this https://github.com/foliojs/fontkit/pull/344 and we can upgrade react-pdf accordingly

**Comment by ctrichereau** [comment]
Thanks @ab-smith , your pull request is merged !
We do not see side effect.
I close this issue

**Comment by ctrichereau** [comment]
This PR https://github.com/foliojs/fontkit/pull/344 fix the issue

**Comment by ab-smith** [comment]
Great, a new resolution/gen of the dependencies tree fixes the issue indeed. I'm happy to help!

**Comment by AlfaroLore** [comment]
Could you please release a new @react-pdf/renderer version with @ab-smith fix?

**Comment by nik1168** [comment]
@ctrichereau how this issue should be fixed? Latest version of the library is still throwing this vulnerability using snyk

**Comment by ctrichereau** [comment]
> Could you please release a new @react-pdf/renderer version with @ab-smith fix? 🙏

There is no need to publish a new version : 
remove your package-lock or yarn-lock file and your next npm install or yarn will pull new minor version

**Comment by ctrichereau** [comment]
> @ctrichereau how this issue should be fixed? Latest version of the library is still throwing this vulnerability using snyk

same as above

**Comment by nik1168** [comment]
Thank you very much @ctrichereau!
