### ISSUE TITLE
Text Nesting removes bold V3.4.4

### ISSUE THREAD

**Issue by caixaceca** [diegomura/react-pdf#2840]
fter I upgraded from version 3.3.1 to version 3.4.4
When I nest the Text component with other Text components (i.e. Text inside Text) I lose the added bold.
Ex:
<Text>Hello <Text style={{  style={{ fontWeight: 'bold' }}>World</Text></Text>
In this case, I want only the word **WORLD** to be in bold, but it isn't.

However, if I do this, all the text becomes bold.
<Text><Text style={{  style={{ fontWeight: 'bold' }}>Hello</Text> World</Text>

Summary:
In nested Text, if I put part of the text in the middle or at the end in bold, it is not applied, but if I put it at the beginning, the entire text is in bold.

**Comment by dessertZombies** [comment]
i also have same issues

**Comment by jh-9527** [comment]
Did you find a solution?

**Comment by diegomura** [comment]
Should be fixed in latest version. Please re-open if it's not the case

**Comment by Nivnivu** [comment]
Nested Bold still not working.
