### ISSUE TITLE
 Long single page + A4 size

### ISSUE THREAD

**Issue by jooyoni** [diegomura/react-pdf#2844]
Hello,
Thank you for developing such a great library.
I have a question regarding this library.
I have successfully implemented an A4-sized PDF using this library.
However, I am a bit disappointed with the content being cut off due to page breaks.
Therefore, I would like to create a PDF with the width of an A4 size but without any height limitation, effectively making it a single-page document.
Is there a way to achieve this using this library?

**Comment by volskaya** [comment]
You can already do that if you pass `undefined` as height to the page, instead of using `A4`.

```typescript
<Page
   size={{ width: 595.28, height: undefined }}
   style={styles.page}
>
```

**Comment by shahabgohar** [comment]
@volskaya @diegomura not working for me. when printing a long receipt it cuts off
