### ISSUE TITLE
Heap memory Leak | each PDF generation increase memory and does not fall back enough.

### ISSUE THREAD

**Issue by kristinaright** [diegomura/react-pdf#2848]
First of all, thank you for such complicated tool! Awesome work!

**Describe the bug**
During performance testing we noticed memory leak. I tried to isolate the problem and could not found any reason other than **using render function from react-pdf/renderer lib**. 
Every time a PDF is rendered, the memory used by the app increases and never comes back down to what it was before the rendering occurred. Garbage collector works but it seems like not enough objects deleted, seems like some objects still in use after generation finished.
Also i noticed that if we trying to get a lot of PDFs one after another fast - we will get yoga error and i do believe this problems are related(MaxListenersExceededWarning: Possible EventEmitter memory leak detected in yoga-layout)

PS. i saw previously closed issues but i did not found working solution and issue still exists for us in production.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

1. Clone repo https://github.com/kristinaright/react-pdf-example/tree/develop
2. Go to /service and run dev script
3. Open chrome://inspect/#devices
4. Send GET request localhost:3000/documents/basic and watch for memory usage

**Expected behavior**
Memory should fall back in some time after PDF generation.

**Screenshots**
<img width="1789" alt="Снимок экрана 2024-08-22 в 17 34 29" src="https://github.com/user-attachments/assets/b40fe7b7-79dc-497d-b4a2-1089d87b8379">
<img width="818" alt="Снимок экрана 2024-08-22 в 17 36 42" src="https://github.com/user-attachments/assets/3e8eb2d4-9d84-4024-a722-d5f2ec5b438e">

**Desktop (please complete the following information):**

- OS: MacOS, Linux
- @react-pdf/renderer: "^3.4.2"

Thank you in advance!

**Comment by jaidetree** [comment]
Experiencing this issue as well in a production app. A co-worker of mine has been tracking it down for about two weeks. Glad they pinpointed it and another user has reported the same issue.

**Comment by kristinaright** [comment]
> Experiencing this issue as well in a production app. A co-worker of mine reached the same conclusion after tracking it down for 2 weeks. At least this double confirms it 😁

Hello @jaidetree 
We spent some time to investigate a fix for this issue with my colleague and looks like we found a trick which solving it.
It seems like yoga-layout lib does not remove some listeners so we tried to clean its ourselves and it helped.

Take into account that our app - simple Node.js app which provides an API endpoints to get data and render PDFs based on templates - so in our case its not a huge trick to call  `process.removeAllListeners()` right after PDF generation finished.

On real project you can try to add next line here:
`finally {
    process.removeAllListeners();
  }`

https://github.com/kristinaright/react-pdf-example/blob/develop/service/src/server/respondWithPdf.tsx#L12 

We going to run perf tests later to doublecheck but as for now - it works fine.

Hope it may help you :)

**Comment by jhgeluk** [comment]
Are there any known fixes available? process.removeAllListeners() won't work for api's that have multiple processes running.

Is this package still being maintained @diegomura

**Comment by diegomura** [comment]
Should be fixed by the latest yoga layout changes. Please try it out and re-open if this is not the case!

**Comment by jaidetree** [comment]
> Should be fixed by the latest yoga layout changes. Please try it out and re-open if this is not the case!

Confirmed the fix is working on our end at least. Thanks!

**Comment by jhgeluk** [comment]
@diegomura Is there a way to fix this for `@react-pdf/layout v3`? We're still working in an old CJS project, so updating to v4 is not really feasible. 

Possibly related to #2825
