### ISSUE TITLE
Docs: lineHeight can't accept length or percentage

### ISSUE THREAD

**Issue by crowbait** [diegomura/react-pdf#2851]
In [this issue](https://github.com/diegomura/react-pdf/issues/2369) it has been noted that `lineHeight` is limited to the unitless number value type (thus `lineHeight = x * fontSize`).

While this is [not wrong behaviour](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#syntax), the usual CSS line height property also allows for other value types, eg. length.

This key difference should be noted in the docs.

Also, it may be prudent to change the type of `lineHeight` to `number`, as strings (commonly used in JSX styling for CSS values containing units) could lead to false confidence in the acceptable values of `lineHeight`.

**Comment by diegomura** [comment]
Thanks for raising this. I think it makes more sense to add support for units in line height. I'll take a look!
