### ISSUE TITLE
Border widths are inconsistent for cells inside a table. Some are darker and some are lighter making the page look ugly

### ISSUE THREAD

**Issue by aak1990** [diegomura/react-pdf#2853]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. MacOS, Windows]
- React-pdf version [e.g. v1.1.0]

**Comment by diegomura** [comment]
This PR just has the PR template. Please open a more descriptive PR attaching either a REPL example or a way to reproduce the bug
