### ISSUE TITLE
Open renderer link on new window

### ISSUE THREAD

**Issue by dubbofeng** [diegomura/react-pdf#2857]
Hi I am just check if this issue has been fixed in v3:

https://github.com/diegomura/react-pdf/issues/645

`<Link src={"www.google.com"} target={"_blank"}>{"Google"}</Link> `

When I open the exported pdf in pdf viewer, it asks you to open the link in browser, but when you open the pdf in browser, it opens in current tab, not in a new tab.

I am doing a pdf preview in a modal, when I click the link in the preview, it override the current editting page. 

I would like to open the link in new tab.

Thanks

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2926

Answered there
