### ISSUE TITLE
Load PDF Component Failed

### ISSUE THREAD

**Issue by ItsJohnny30** [diegomura/react-pdf#2881]
**Describe the bug**
cannot load the PDF Component.

**To Reproduce**
> [!NOTE]
> I used react-pdf on Next.js **v14.2.13**
```tsx
// PDF.tsx
'use client'
import React from 'react';
import { Document, Page, Text } from "@react-pdf/renderer"

const MyPDF = () => (
    <Document>
        <Page>
            <Text>Hello World!</Text>
        </Page>
    </Document>
)

export default MyPDF
```
```tsx
// page.tsx
'use client'
import { PDFDownloadLink } from "@react-pdf/renderer"
import MyPDF from './PDF'

export default function Page() {
    return (
           <PDFDownloadLink
                    document={<MyPDF/>}
                    fileName="department_attendance_report"
                >
                      Download
                </PDFDownloadLink>
    )
}
```

**Screenshots**
![image](https://github.com/user-attachments/assets/24a492b6-4601-44b0-823b-8e69bf4b6bf2)

**Desktop:**

- OS: Windows
- Browser MS Edge
- React-pdf version 4.0.0

**Comment by diegomura** [comment]
I assume that's next.js?

**Comment by poncho-ml** [comment]
Started having this same issue, I recently updated from next.js 12.2.3 to 12.2.13 because there was a security issue and started having this issue as well. 😢

**Comment by ItsJohnny30** [comment]
> Started having this same issue, I recently updated from next.js 12.2.3 to 12.2.13 because there was a security issue and started having this issue as well. 😢

That's probably the problem with Next.JS

**Comment by ElectricCodeGuy** [comment]
Using import dynamic from 'next/dynamic';

and setting ssr: false seem to fix this error. 

However it still crashes if I use: import { pdf } from '@react-pdf/renderer';

**Comment by ItsJohnny30** [comment]
> Using import dynamic from 'next/dynamic';
> 
> and setting ssr: false seem to fix this error.

Same Error...
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by ElectricCodeGuy** [comment]
> > Using import dynamic from 'next/dynamic';
> > and setting ssr: false seem to fix this error.
> 
> Same Error...
> 
> ```
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> ```
> 
> ### My Code:
> ```tsx
> // PDF.tsx
> 'use client'
> import { Document, Page, Text } from '@react-pdf/renderer'
> 
> const MyPDF= () => (
>     <Document>
>         <Page size={'A4'}>
>             <Text>
>                 Hello
>             </Text>
>         </Page>
>     </Document>
> )
> 
> export default MyPDF
> ```
> 
> ```tsx
> // page.tsx
> "use client"
> import dynamic from "next/dynamic"
> import MyPDF from "./PDF"
> 
> export default function DisplayData() {
>       const PDFDownloadLink = dynamic(
>         () => import("@react-pdf/renderer").then((mod) => mod.PDFDownloadLink),
>         {
>             ssr: false,
>             loading: () => <p>Loading...</p>,
>         }
>     );
>     
>     return (
>         <PDFDownloadLink 
>                         fileName="department_attendance_report"
>                         document={<MyPDF/>}
>                     >
>                          Download
>                     </PDFDownloadLink>
>     )
> }
> ```

You are doing it wrong. You need put everything that have something to do with '@react-pdf/renderer' inside a client component. So something like this here:

1. First, create a new component that includes all PDF-related logic:

```tsx
// PDFContent.tsx
'use client'
import React from 'react';
import { Document, Page, Text, PDFDownloadLink } from '@react-pdf/renderer';

const MyPDF = () => (
  <Document>
    <Page size="A4">
      <Text>Hello</Text>
    </Page>
  </Document>
);

const PDFContent = () => (
  <PDFDownloadLink document={<MyPDF />} fileName="department_attendance_report.pdf">
    {({ blob, url, loading, error }) =>
      loading ? 'Loading document...' : 'Download PDF'
    }
  </PDFDownloadLink>
);

export default PDFContent;
```

2. Then, in your page component, use dynamic import for the PDFContent:

```tsx
// page.tsx
'use client'
import dynamic from 'next/dynamic';

const PDFContent = dynamic(() => import('./PDFContent'), {
  ssr: false,
  loading: () => <p>Loading PDF component...</p>
});

export default function DisplayData() {
  return (
    <div>
      <h1>PDF Download Page</h1>
      <PDFContent />
    </div>
  );
}
```

**Comment by ItsJohnny30** [comment]
> > > Using import dynamic from 'next/dynamic';
> > > and setting ssr: false seem to fix this error.
> > 
> > 
> > Same Error...
> > ```
> > Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### My Code:
> > ```tsx
> > // PDF.tsx
> > 'use client'
> > import { Document, Page, Text } from '@react-pdf/renderer'
> > 
> > const MyPDF= () => (
> >     <Document>
> >         <Page size={'A4'}>
> >             <Text>
> >                 Hello
> >             </Text>
> >         </Page>
> >     </Document>
> > )
> > 
> > export default MyPDF
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```tsx
> > // page.tsx
> > "use client"
> > import dynamic from "next/dynamic"
> > import MyPDF from "./PDF"
> > 
> > export default function DisplayData() {
> >       const PDFDownloadLink = dynamic(
> >         () => import("@react-pdf/renderer").then((mod) => mod.PDFDownloadLink),
> >         {
> >             ssr: false,
> >             loading: () => <p>Loading...</p>,
> >         }
> >     );
> >     
> >     return (
> >         <PDFDownloadLink 
> >                         fileName="department_attendance_report"
> >                         document={<MyPDF/>}
> >                     >
> >                          Download
> >                     </PDFDownloadLink>
> >     )
> > }
> > ```
> 
> 你做错了。您需要将与 '@react-pdf/renderer' 有关的所有内容放入客户端组件中。所以这里是这样的：
> 
> 1. 首先，创建一个包含所有 PDF 相关逻辑的新组件：
> 
> ```tsx
> // PDFContent.tsx
> 'use client'
> import React from 'react';
> import { Document, Page, Text, PDFDownloadLink } from '@react-pdf/renderer';
> 
> const MyPDF = () => (
>   <Document>
>     <Page size="A4">
>       <Text>Hello</Text>
>     </Page>
>   </Document>
> );
> 
> const PDFContent = () => (
>   <PDFDownloadLink document={<MyPDF />} fileName="department_attendance_report.pdf">
>     {({ blob, url, loading, error }) =>
>       loading ? 'Loading document...' : 'Download PDF'
>     }
>   </PDFDownloadLink>
> );
> 
> export default PDFContent;
> ```
> 
> 2. Then, in your page component, use dynamic import for the PDFContent:
> 
> ```tsx
> // page.tsx
> 'use client'
> import dynamic from 'next/dynamic';
> 
> const PDFContent = dynamic(() => import('./PDFContent'), {
>   ssr: false,
>   loading: () => <p>Loading PDF component...</p>
> });
> 
> export default function DisplayData() {
>   return (
>     <div>
>       <h1>PDF Download Page</h1>
>       <PDFContent />
>     </div>
>   );
> }
> ```

Oh I see, thank you!
