### ISSUE TITLE
TypeError: ctx.skew is not a function ()

### ISSUE THREAD

**Issue by mathhater** [diegomura/react-pdf#2896]
**Describe the bug**
CSS property transform:skew is not working.

_[react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d77748035240c609843494339285b1e4847105b460065006b22f5348f1d3d364aea885afa9296e0ccecb676ca4c82a2dcad519293313285b3592830b1753a307864002b742c1b18111e1800596ae0731e11ae9989b9d2e353391e0470baf533a43e040c111811c7c76001bb5530105b8e5c6d40024a31f818186509ee5591201102553224ab6603600044190c622201900239ec0e0046592ede27c024c232f76a23d964b17ac82008791aca01b566507c3c788016ea0081108060b080170ecb03d2829c8e2718280c04a24300900067ed90860185d9d975ba994d8018e1e230401019798904a1e088f8329a2c87188243ed3080ac3aa2e602b8f06150b1878d95d79a99393255974da51ca00145b6086d888107c1e2d803c753b0743001a02c308432b008118f27f0c1ab304a6156c32e89d45df50c1971bd71c6301057195ac308c788cb2958105204162d3a66604e975bb2d81fb4164e600017a9c58301e3409022312b6cbd63cee671e09f8207865d6f00c5db4709d4030236e6571ababf89475590c0002a980a7080c7aaa582baee8c08c00087100c060b00a724e38b21b61807608065840aebc43a81a8582170421d595c661964a1fcd282146a4e75b82eb8d1252c1f2358f689638988ac09a07b1cebb4e762611019e6e8005fdb3c4ae8d648236470f00023f58ce820553f1085fe8c2c9ee889687803ca30739667c654660c0526d8108163ca2ed12145a8f0006a600bf8d02aee077e21b66464943c2563891c20bfc79a6065b21220ee1a54eff3667fb9979a9c27021ce1982a8219a89408021526b0080beeb9aa203f64804076996cc52873945c6ab0f5840a3b54a73d58bb80551b19e665884c5751201b8ca244e2ce356006e8601ce35675c86e130266a72da285fcf16e1ed615e96defe2b077bbe334812508075ac9618a64da2d8db1e182e6ed62502460b2685db42e7696eab86ab6b8edb7c4270ee65a4efb840628e22c0404789ced7fc913d04fb7e768c0500d63c3b5eab8e2e8d8550010018ad825423896ee28c16601fcd02b63892e504ca19731ba8867f26dfb8291c71a6a51ca018e620a0fab6cfe2ea5b7d56f8b379b099c71d2c2ecef0bdadb1320000dc301f05536c08928b60e6ec7e646ada3f0bdeab213b8013e9d87b8d8babe6a871d9818dbb8020e9d62c0d6b6c163eaece78c032a20660bb782fd7baa58e9f9fb9bab34054823886c86482ee59bae6f1c3ae49d872a55814d32998c0163f20b00419e99afde3ad87a580a6a4a550214164b629693209409f3b3545ba8fc7d5f1c270223b2fa8d6cbf1161c69b93886279caae67d06d83644e5414ed370ecb6c7400b5607bbaa206d8552ea845280025c028db35b85ba474a60bbc4999c31ba9c65ca3e196477386ec9c6cf026983e8c98a6a9889e65139460808dd83f62d89dedb6db510e45cce9c9b9575c550e18216f6b3cd88e27a0481ed0ca2f67fc15ba9182f0403002452200883351745758e0603b0c70901d602a49c71b9d5b05540bac37047359c2af43472cb29c35fe580c0b4e2507a95eb0302c70ce291f56029c0109a3343a9104062e2a717596d0d60b9d53582d26004a8f4661d64102d95d42c05d2cb234e74f82f0d382a844665342aa5107037c64686c2e13588d87d9b90e15d4b53ea182839ae0216b89857335511ccbc208e27aab58aa1512a86582cac89acf10aa3e611064325b962a1278aa84d5fa620ec3e8bfa6299b8601047a8af24d03c263943ae0608c5b282038ad7033be62b4345b251c411eb9545805f8d58109881c41643023e6a8f43b63c87b2d0c653315faacc8f83a634d696d120980e8dfe248ea82f41a11e3047287a5d40c9b224e1637c64706cac4fb4f23f724e702084ee96310ce781095467ac253290803ce549131d5e9fd3b611c2eeb6092b649221a96f16a3196212e9cd2212427839ce62fe19b060721b44d08853e2470ec4f0470629b0a02700470f700e50cd94429996b8e04c184034e6104002a754f72d79bc94cea9819805a5db17ea9c2d29107816e422cd5ae3006ec0235d0c16a8761d96f51653545f142bf8fcb858a6099e0139772c56581273ec53e884c79a950ef51ed2a95392a96b12075edb02a702a217393671d662ae8a046a428e3316a052d5aa8672c9501411b534e102cc07887524a3dd4c85ce09581fa1ac261d50cb11a75c7caf161b7e57f999b83660dcc313d913ebf4535f4c0cfbca308217572c158d83d697d462b24e8fa16322c7be2b11f94067e5187c22ad4a7c48d084de23c4ee572f006647e6552b643c1db21362d43444c0316922b150800a66082888562078b01e73aeba2ec12528d019eaad5452798abb832dd6b0ff0b8ede6b98274404a3d97a806960f5c5b00ead2a5465000412c6d00f5260190385c559841c61012bc5352100f534a406c78400010007229d607b2840469865ee4a67c52c3ecbe2bf4ff36c000424b3aa09540438ddf0e254df20e7244ed98b59a8923e0875daae73a885baa1d8e15a9492464ac0e61792142dd162c2562b92bc4684415862c048783496e3db68b499980aec3bd73afc6d08ea1e09507519936d180948c84eeddc32949d7438cc1b6c1b231de8f4af06e7ad8be61e45c51245345548d5b33069af25a169c43ac3a119887dc41572844edaf8abc5757e55d3e95e6d92ab9ea8bd386089e269c4fa4c14e6762f343403b994281aac40f451901c4400363acd58e7304c0d92996026a973503aed694202745f98514675d1de8eadd4bf7c0f1ec44fc9d43539e41c42075c5dd2026b1bdad2653356abbed6c259ea8234100827ea9e20f0e220ac17a19770b63cd9ac0206049b3ab665ccf98507cf352e61edbd63fc310653cb6b0b78ff2036d86b2f80001f9603b8b3800fac0c1608025a9e35ac7f5134f463ce8eb2cbc0440a6a86360712c276927130204d763009f52b314d5400389bc138b2c11075b3058020cea302f04cb259ba9ee4608953b43d2fe3c86949fdfa6373691d24145d02342a81c9e3278b31406edfafc2a0a6622af970312ee50e35264255b065945762ed8e8e4e1d432c286113f1c47c8ed1c63ada79ccd8a60b6e340706b566ca05da6a2019cc00e94bfcb2d7ea38b52eceb0bf62595a9259f1deaa639b9d442286f3a92b9593ceff9470d5609b894071ad58b896032191c600ee5cc5e8a304672db7dab5a23ad0da3c3a6488660c0afe834659379371608e04bb005e1a624f9ee1b2620623ea97163697494b62c64200e232296042d085d12f5801ec94ea6a7bc6e8aa6939a6a9619bdf6188fc411ba0f18a395518ad10f7e6750b4bab2c11e380664c974dcbcdf35e1e0df97f87219fd85661352daec2e3638b7601bb8309d16800800196e27a9ea979f5436936bfd2137a7a144e45a620e71ddba082482299e3fd0160b032126d16930d9bf17bb7caaeb870bc8c01b10aa05cacf8781a2862a330a1a809bf2c2b203c2a4b19e1da2b91962c72fa9a536d36a0401448421f718e3da190a7eb6d22eab033fbfc0273d08021da1c502f1b9a623b999bb7b1a939f3580e22089cd2b9860b362ed0b9b5100683a1290ba25c9800f985a23c9b1a91a371448e23e7af602338d3a031d9a88f53b2a60ad5a0f0fb3706661fe1c787415f3423c79279181a20f21f23ac0600382db0f013410a2f828a04a14a0ca2c23ca22a2c324090983986234baef280a3721c968804b1873d0cc9f73b48b015887a22a93b01c296b5f3c7bc22223048720d69c8151a787049e2212312262198052152260000132c83c43b49321460b20df0c62a232c0541261f8400049f4978a4487f2069f12c4be484062090b0362ff8951b62fc1e627606082108e0307ee10f09fa0046028709f11c90310d88899e24c5402c130297995b3559bfada9cf0c03e780db2d1cf29334438d158478b9a8d90aa2d80ba36e2f305d04913300c8da95db4e3ae2e721c5c0b1d1d8ac6a6fa4a1d81dab7b16a21b0ee26f932bdc8f6b409ff2fa8ac46b3c81653825fc03bbec1c495046039596257f1ac1f43441d8001000268e497e97c9e6001bfa25fad803a2ed3f38810cea751dd34c6111b6ac9033b2930ba2117180aacd30a92908119e276aafbf6870a031a900b9f53a52ba2a912094537059911c0001494a24f9371e62302f0b3491b8210f202129a4bcb04a71af08db3d6000128208810f128c4b6a7502216d8c498f2c8b050ba14ba84972a3a42015e2762e61904d61866161fc47d3d19231fc25929c0da08833996002e280204b5b235b1896d9bd20b8a606515d96a0a38621d98f119886b0882282b60a460509086527d9d30da2ea024be30fdae68607b139935caea3e108f0d93e251b2e3b81b9c1f128a0b01f133518244d1efa16602a3198ca858780948881402f0a1f21c7405989c3ba718806eaa04b8b2eb8e1be17993a2d584133b2c59e92fa8ee0ba31a18e2b90f0364a3822d1b184a45fa160c128e2984338a71a92da6ddb1d1dba9e36d24e1853803f433026c5882d8a5088eaa496d2a890f3f68362f50d8091a948c595e3d41f1065233a025814cb07d18f2ff9ae13832656d17646e1881823e62da737b1d0d3a5c12057bb561ceabd12156133253e64c74d3bc6a7354962978a0f1d1be73e59689983be5d80a47aa2e60813d51391b93650ee7a69313b1a4896136c3f22f21583e6057b867bcab63c433fa5296384c754bd91c5002a57bd03eaa3711869c04a8f266ba99412748b1d2c27352da7e60916afac4b446b62371c31493d519e0c01a68aa06891c1187da3f6278a12641180755a5e4b63800e100276c3e7ad17ffaf0547174ad9a52570787b09a5b1801390079aa24e7e14212b14dc9bf23c41182498e0472fc8a296032ba8a94b980388464677b1c2ab26f8648ca2c956eaac63702e29a7baa9151a0652fb1371c2a6e752000070e211a31cb032fc3b88d93210a8962a95b9d0316bb0499b2b9ca371ed4a4851609ba06681a7060077b9a92259cbc865670334038d1bfb264ee29f0da4f9b1722dbc78386460743387c62d6bf44e23d2677a7a6c066b3ba5c52130b198d4b73822410036a92f15457b52d4a6e1c526a36d51654613999515076970282a2000a010003f4fa09a995906494385a3702f0dd2a8aa33ae3ac78e2e92815029c52ef2e61c142016e0fe6886a329c13a1b916310983e9381cc83a378b0c63337b08819ea8fa373312a73a70b616023638e3b496d19a9c5218a2d344a6d2196cf3938f49630a6935235a3e5bb91c0222ca56d1d8a0f3755540003f02a13e80db2181840e8ab30c8303028e21fb58130e2e8b3a0ca32e8dc68b4d57ee08635c36d19814905a34d1246e30691d42dca9321067566512b6eaa2b7717751bf06b3fb574bf586024e0332d11a5a6d1fe3314a61490de483394a2ab5a7ee2d8149328510bb4ade378a07435ac52f64651510883f2bf992c8be2de1e15da25b18b46463e62764b0bb13e96a5f9a4140633b39abaa03563e7ed4411ab6817fc3cc8c58c7591ac59548226b6b206ba26a1ea726a5c25834109d96303cbb27a93f61d42a05993351da3130e31853f358e8da100c530a4b770619b71fa27049c0e231635c27f1ef49b5f102089cb653663638e103a7bda08168840fccbb3b134782ba7533a376d2b30bdb18abd0a8ab272eb99ab00de0ca3cd7800209c508a06c643b1d19c38008e0881d87a4083627b744944a794371d23274bbaa38b7687d1be7bed4d1abe4b05287b8a9ba77b534d00ea09da094d8b048fc3559009e8db605d7b13226f908832b39c70b68b406b10ee130f4ee1293111551dd67036a1f012978066d3812727cf10cab60860510f70300883e1004c4d1c12ea95726d5dd1e63350b0388679920544afe49044704d355bbe71738e400214003c8441401890e1023148840430a26aff3d91c29540e22f39581bf02d08c8a745a7a1349bd53f95d43801a884115b4fc85d35ca4b4984cb400210e233a4203af3ba3fa35b9476bb088370b3f793b206d30c0050e1d07a6ada293770601c3a362192f7b88594b111e1b28e74b50de63f8097308d68288d746568f45722a79f87df9fc3411cdb2cf8d268f029414c33f0b8b68a850686b514d51ccaf1b53514f980db6c9305a9c0d014a353158165433126b40250bbc0ce1d98b2b8cf9c1257ee282548b300bc467131a87300a8e4d06b812017636d3f831ca863d2c2d4b90de33bbee10d328f0d9f272ba762c17eb5e6366a315fa9c8c168ea900fea8011700882cccf02333d53a2dbb6ae668330086524bbb54e16aa8d8201172e2e865800b899781172025072ebe68a355e0907c531b060001136b6c2fb25ca19ae10a679abc54690952d0684cb48da770594979432b25517690822910ad936163ae40069bb119634572e44d19a89f3232fdb194328b012c69a3daf369b93d0ca8e0ca6eba771a51a3ee9811d71b509880ca8a16307b211a8162a9979b60fc42ba372c95a90cf197a4100632f01cdd2ebfbae3d522b57e8071338b754624a209034f0359693cc18048ef462613f1f848a3f0b7fb5120218b82363a48a7b60f13ef979a8034d3a1927008eb278d40aaf0d06d2e75b02720ecfc880d0f2d82fd33630334b9856b276605d18ca7ce5649d3d90bc7efb1a0a00fcbd906dbcf907bd182455142256003133d00126f6c7312bfb3a1aa99f571d0ec9f67055cd26369f9ff8634b36c94fe7cf97032649f3dfac13e12caa9d64b3073f2ab29ffa447ae1da02495ce05069769885755afd25622e08bb6a0814a60f01970de2b2538bfa32700f8515f1ed93812f0792963397a155276ba2ace20df0ebf56d1992fd3e7a31acdb0e006d9980212a7be2891277d02583ef9e0c4323e0b0a6f086ac9cf7a9aaf43b103740e022450ad928480a9d11fc19632f826c5b84c51298ec7839ac90bf09d883001d20988ef1141e1ac1818239b970ab3b2af7d7b4b5ea4e28aae70373080008144c6b061b7cb596e3a67b3036a2b24d9005a4b6da03b11a26130587a9961824f6190e681883ec0ea5e6feb641f65ce356d34a4035de2fd111d7b902d3590708b3130c51cf1b5dc17f59ff6a9dbf13288f0da94f6c12a26accd92fe20a5660e5e50154c30db10010e8fda12e8d6f4d2c88235e600fa829d0ecde6c77345155e2b79f49ce3dcc4c23cd38788ddf1a21490080419301d483806d2a32481e00483c5203f03cff2c33a02ba2f00080212a81103602901e00e20000180009048003c60103ed61d80380640c01e3dc32a0523d982a8163cc20100383380a02b80c0274488f53fb82641d00300507b001034b1901903a3008ec83f8351a62ed8243c70040d1e10802a00039214c403042ba1283cbdca8401e202bf981401403c40401ca0640642d42b01c81f02cf1ac3002c82b30641923da0abf58c64082352000330643d24003eb68000349e40001b0802ad4003a8800823c82011280bbe3007bc0006800270f013e93eaac1402383cbd902a3c0bd902135cecbc0e00c003432c03425801cf5bd4426014be502280a802a0483b41f776a3b4b680803c402a0bbc002b3a0437f69261ba034582a1fbe77fd7f58237df000c4f517f6ba1b7d0fe502a81ca8f40d412fb341142d7fb41d693e824b78c2bfd1dc3babfb41b13001343cb0800d8536b4a2d802be6fcebd5d9081efe6802fdf412f82bc4010c1e02c4352000030d81f00101dfcc01cfc701f9062055fa6804de50035916e03000a8468800059d02ebf4df9801b7e37a3b01ffd280600f4626b044072f18022bd95eaaf3ff800328031c0fe88033806008805402600d48468bc02ba01bf1f812037013bf5407a0462cd463002f7d75e3580540c023fe72a2206651dc20282a05d7d4010234a042a0d6a6c08bc2c90a41b40f680602b01380bc043bcd5e1c04105d68c819407605c83a810a0f106b01241d40b805afde8188085798b10f08e05bfba0494195c1507681a221005882ba595ce9f59f9ca9ca2da0e152d80381790044929844052099fa70174160071fa7f54f6c10ea047fdf811a0b952581ac07601f04502900900f904c82fc1b242e07f7c6008d17887dfdcc18c0e404f116c0680efc39fc15ef2c47aa102e5404f2279d487c13cd3080cc415e08c0743661300150b484643f41e8145037031806df4286700c408e028002a14619402c61f0075e530ba07e801815bf6604a03ca1e815001543701350db0424233efcf417b3a4ac03102e00d01d18a2f55d24bca803e83403fa0590070a00000)_

**Expected behavior**
I expect the transformSkew style part of the link above to be skewed.

**Screenshots**
![스크린샷 2024-10-07 오전 9 30 29](https://github.com/user-attachments/assets/aed5be9f-e39d-4b73-96da-497a9008e589)

![스크린샷 2024-10-04 오후 12 36 03](https://github.com/user-attachments/assets/9ed4b4eb-303f-4d3a-a1d7-27ea81c26f65)

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [chrome]
- React-pdf version [3.4.4, 4.0.0]

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
