### ISSUE TITLE
Support for React 19

### ISSUE THREAD

**Issue by wkigenyi** [diegomura/react-pdf#2912]
Hi,

Thanks for the wonderful library. It works well with <= React v18. Is there a plan to support React 19?

**Comment by ck-euan** [comment]
This PR updates the package for react 19. You could temporarily use the fork package to get it working now `@alexandernanberg/react-pdf-renderer`

https://github.com/diegomura/react-pdf/pull/2783

**Comment by wkigenyi** [comment]
Thanks I will try it.

**Comment by wkigenyi** [comment]
> This PR updates the package for react 19 (https://github.com/diegomura/react-pdf/pull/2783). You could temporarily use the forked package to get it working now `@alexandernanberg/react-pdf-renderer`
> 
> 

I have forked your repo. But for some reason the cloning process timeouts before completing. 
If I succeed with the cloning, could guide me on how I can import the package into my react project?

**Comment by ck-euan** [comment]
> > This PR updates the package for react 19 (#2783). You could temporarily use the forked package to get it working now `@alexandernanberg/react-pdf-renderer`
> 
> I have forked your repo. But for some reason the cloning process timeouts before completing. If I succeed with the cloning, could guide me on how I can import the package into my react project?

@wkigenyi The easiest way would be to just install `@alexandernanberg/react-pdf-renderer` and simply replace any the imports to use that instead

**Comment by wkigenyi** [comment]
Thank you.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by jpainam** [comment]
Does `@alexandernanberg/react-pdf-renderer` support `Nextjs 15`?

**Comment by wkigenyi** [comment]
Yes it does

**Comment by pedro757** [comment]
Have any of you guys run into this issue?  @ck-euan @wkigenyi 

details: 
@alexandernanberg/react-pdf-renderer@4.0.0-canary-3
next@15.0.2

Error: 
`⨯ TypeError: Cannot read properties of undefined (reading 'S')`

**Comment by ck-euan** [comment]
Yeah I just ran into that issue.
I believe that the PR needs to be updated with newer versions of `react`, `react-dom` and `react-reconciler`.

I was able to solve it by patching `@react-pdf/renderer`.

Basically I just copied all of the changes made in https://github.com/diegomura/react-pdf/pull/2783 but I updated the versions to the following:
`react: 19.0.0-rc-02c0e824-20241028`
`react-dom: 19.0.0-rc-02c0e824-20241028`
`react-reconciler: 0.31.0-rc-02c0e824-20241028`

Specifically, the exact steps I took to do this were:

1. Cloned https://github.com/diegomura/react-pdf/pull/2783 locally
2. Updated `react`, `react-dom` and `react-reconciler` to their latest `rc` versions
3. Ran `yarn build` to build the `@react-pdf/renderer` packages locally, this gives you the `lib` folder. We will need to copy this for our patch.
4. I'm using pnpm so I was able to run `pnpm patch @react-pdf/renderer@4.0.0` however you can do the same with [patch package](https://www.npmjs.com/package/patch-package)
5. The changes I made for the patch were to replace the existing `lib` folder from `@react-pdf/renderer` with the new one I built locally.
6. Saved the patch with `pnpm patch-commit ...`

It then started to work for me. I really hope react 19 stable release happens soon 😅

**Comment by jpainam** [comment]
> Yes it does

No, it's doesn't work with `nextjs 15` and `react 19`. I get this error now

@wkigenyi 

```tsx 
⨯ TypeError: Cannot read properties of undefined (reading 'S')
    at module.exports (.next/server/chunks/08b5e_@alexandernanberg_react-pdf-renderer_lib_react-pdf_1362ba.js:14494:67)
    at createRenderer (.next/server/chunks/08b5e_@alexandernanberg_react-pdf-renderer_lib_react-pdf_1362ba.js:14980:12)
    at pdf (/.next/server/chunks/08b5e_@alexandernanberg_react-pdf-renderer_lib_react-pdf_1362ba.js:15180:28)
    at renderToStream (/.next/server/chunks/08b5e_@alexandernanberg_react-pdf-renderer_lib_react-pdf_1362ba.js:15311:22)
```

**Comment by wkigenyi** [comment]
It worked for me and still works. How did you install yours?

**Comment by sam3d** [comment]
@wkigenyi is there any chance you could share your package.json and lockfile?

**Comment by wkigenyi** [comment]
This good pointer. I have remembered that I actually have 2 packages "@alexandernanberg/react-pdf-renderer": "4.0.0-canary-3" and "@react-pdf/renderer": "^4.0.0". I imported the PDFDownloadLink from "@alexander..." the components and other functions from "@react-pdf/renderer"

**Comment by jpainam** [comment]
> @alexandernanberg/react-pdf-renderer

Installed using `pnpm add @alexandernanberg/react-pdf-renderer`.  Got this in my `package.json` `"@alexandernanberg/react-pdf-renderer": "4.0.0-canary-3",`
i'm server rendering, so i'm using `renderToStream`

**Comment by pedro757** [comment]
> Specifically, the exact steps I took to do this were:

Thank you @ck-euan !, That works, good workaround.

**Comment by wkigenyi** [comment]
> This good pointer. I have remembered that I actually have 2 packages "@alexandernanberg/react-pdf-renderer": "4.0.0-canary-3" and "@react-pdf/renderer": "^4.0.0". I imported the PDFDownloadLink from "@alexander..." the components and other functions from "@react-pdf/renderer"

@sam3d did this work for you ?

**Comment by wkigenyi** [comment]
@ck-euan I sometimes run into this error on re-rendering
TypeError: detachDeletedInstance is not a function

**Comment by Rohit-Ahirwal** [comment]
Hey guys @ck-euan @wkigenyi

please guide me to solve this error
`⨯ TypeError: Cannot read properties of undefined (reading 'S')`

**Comment by wkigenyi** [comment]
Hi, I have decided to wait for stable react 19 release because what I thought was working is actually not working as expected

**Comment by pedro757** [comment]
> Hey guys @ck-euan @wkigenyi
> 
> please guide me to solve this error `⨯ TypeError: Cannot read properties of undefined (reading 'S')`

ck-euan already helped us to workaround this, just read and follow this https://github.com/diegomura/react-pdf/issues/2912#issuecomment-2449777484

**Comment by jpainam** [comment]
@pedro757 the workaround doesn’t work for next 15 and react 19. Server rendering. I used renderToStream

**Comment by ck-euan** [comment]
@jpainam I am using the workaround in my Next 15 React 19 project so it should work. The chances are you just need different versions of react / react-dom / react-reconciler

**Comment by diegomura** [comment]
Let's keep the conversation in a single thread. Closing in favor of https://github.com/diegomura/react-pdf/issues/2756
