### ISSUE TITLE
Min-width media query not working for PDFViewer component

### ISSUE THREAD

**Issue by elishamutang** [diegomura/react-pdf#2914]
**Describe the bug**
Tried to use media queries to make the PDFViewer component expand when screen sizes exceed 800px but it gives an error in the console.

**To Reproduce**
Add a media query to the PDFViewer component.

**Expected behavior**
Expected the media query to not give an error.

**Screenshots**
![reactPDF_error](https://github.com/user-attachments/assets/b451ac61-bef7-4051-8dd6-5c1fbcc83975)
![reactPDF_error2](https://github.com/user-attachments/assets/0c71d92d-589b-40d4-b258-ebf69c27abe8)

**Desktop (please complete the following information):**

- OS: Xubuntu
- Browser: Chrome
- React-pdf version [e.g. v4.0.0] (using @react-pdf/renderer)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by diegomura** [comment]
`PDFViewer` it's just a React-DOM component. `Stylesheet` coming from `@react-pdf/renderer` are just for the elements inside `<Document />`. For `PDFViewer` stying just use whatever you would use to style react-dom
