### ISSUE TITLE
dynamic View?

### ISSUE THREAD

**Issue by kimbylr** [diegomura/react-pdf#292]
I've been playing around with react-pdf and so far I'm quite happy 😊 One thing that would have been useful is a `render` prop on `View` like it's available for `Text` elements for dynamic rendering based on the current page. As far as I can see, it's not possible now to have a picture or box with borders that doesn't appear on the first page, or did I miss something?

**Comment by diegomura** [comment]
Hey! 
I think it’s a good idea. If it’s the first page I guess you can render something in the first page by just wrapping and ensuring that element fits in the first page. But depending on the layout it might not be possible. 

I’ll try to work on this soon
