### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by cduff** [diegomura/react-pdf#2925]
Using @react-pdf/renderer@4.0.0 with node 22.11.0 results in the following console output:

```
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

Using `--trace-deprecation` gives me:

```
at Object.<anonymous> (C:\project\node_modules\node-fetch\node_modules\whatwg-url\lib\url-state-machine.js:2:18)
```

And then `npm list node-fetch` gives me:

```
app-server@ C:\project
└─┬ @react-pdf/renderer@4.0.0
  └─┬ @react-pdf/font@3.0.0
    └─┬ cross-fetch@3.1.8
      └── node-fetch@2.7.0
```

**Comment by jpainam** [comment]
This is not related to this package. See here https://github.com/yarnpkg/yarn/issues/9005

**Comment by cduff** [comment]
Thanks for your comment @jpainam, but I'm not sure how this relates to `yarn`?

From what I can work out it's caused by `@react-pdf/font` depending on `cross-fetch` which has [this issue](https://github.com/lquixada/cross-fetch/issues/177) - it relies on an old version of `node-fetch` which causes the `punycode` deprecation warning. I tested the latest version of `node-fetch` and it no longer causes the `punycode` warning.

Unfortunately, it looks like the latest version of `cross-fetch` (v4.0.0) still has this issue as it still depends on an old version (v2.7.0) of `node-fetch`.

So, options for `@react-pdf/font` would be to either:
- Wait until https://github.com/lquixada/cross-fetch/issues/177 is fixed and suffer from this deprecation warning until then, or
- Replace the `cross-fetch` dependency, if that is possible?

**Comment by florianbepunkt** [comment]
Is there a need for cross-fetch at all? Current LTS versions of node support native fetch.

**Comment by diegomura** [comment]
Good point. Will drop cross-fetch usage

**Comment by beauspot** [comment]
I am currently having this same issue on my typescript/expressjs backend application, and I am on node 22.11.0, please how do I fix this error?
