### ISSUE TITLE
Open Links new tab

### ISSUE THREAD

**Issue by chemseddine201** [diegomura/react-pdf#2926]
hi, 
is it possible to open links within the pdf file in new window when clicked ? 

`<Link src="google.com" target="_blank">Some Text</Link> `

i tried the above example but the link opened same tab where the pdf file rendered.

Please any way to open theses links in new tab?

**Comment by diegomura** [comment]
It is not. PDF spec does not specify a way to tell browsers how to open links. It's up to the browser. From a quick search I couldn't find a way to configure the browser either

**Comment by chemseddine201** [comment]
> It is not. PDF spec does not specify a way to tell browsers how to open links. It's up to the browser. From a quick search I couldn't find a way to configure the browser either

maybe it is possible to render a custom JavaScript function that works with the onclick event and uses pure JavaScript code to open the link in a new tab? or the possibility of use `app.launchURL()` that supported by acrobat

**Comment by diegomura** [comment]
It might in the future. Good call
