### ISSUE TITLE
PDFViewer not display (iframe got blank src)

### ISSUE THREAD

**Issue by khoale38** [diegomura/react-pdf#2929]
**Describe the bug**
When deployed (Nextjs), pdfViewer is not displayed, when I check the src of the iframe it got blank.

**Screenshots**
![Screenshot 2024-11-06 at 09 41 30](https://github.com/user-attachments/assets/c9d25c70-34f6-4516-a160-d7605b4c3fa2)
![Screenshot 2024-11-06 at 09 42 10](https://github.com/user-attachments/assets/c477560d-c215-484b-a8e0-b704d695fc0f)

**Desktop (please complete the following information):**

- OS: MacOs (also tested on WinOs)
- Browser: Chrome 
- React-pdf version: 4.0.0

**Comment by pedro-sharpi** [comment]
Same issue here

**Comment by diegomura** [comment]
Not sure you are doing it but you can't render the document in the server if you are using next.js

**Comment by khoale38** [comment]
Sorry for the late response.

It turns out I used http instead of https when using custom font.
