### ISSUE TITLE
page size gets bigger with subsequent PDF rendering!?

### ISSUE THREAD

**Issue by kimbylr** [diegomura/react-pdf#293]
**OS:** macOS 10.13.5, Chrome 68 + Firefox 61

On https://react-pdf.org/repl, every new render seems to expand the page size by 13pt both horizontally and vertically. If I trigger some re-renders by modifying the text a bit, I end up with a PDF much larger than A4… Is there something wrong on my end or do you experience the same?

**Comment by diegomura** [comment]
Should be fixed in `v1.0.0-alpha.16`. Please ping if didnt
