### ISSUE TITLE
Share code between webpage and pdf

### ISSUE THREAD

**Issue by akshitkrnagpal** [diegomura/react-pdf#294]
Hey @diegomura 
Awesome work on this. !! 👍 

I actually need a little bit help in what I am trying to do.

I want to a create a resume and render that in PDF. (Simple, thanks to your work on this)
But I want to share the react code with my web profile. So on the web profile, I want it to be a div of A4 size in which everything will be rendered exactly as I am rendering it on pdf. (Needless to say my web profile is also on react)

Can this be done? If so, how?

PS - I am using styled-components.

**Comment by diegomura** [comment]
Hey! Do you mind moving this to our spectrum channel? It’s more suitable for discussions like this 😊. I’m trying to keep GH issues just for library related things

**Comment by akshitkrnagpal** [comment]
> Do you mind moving this to our spectrum channel? It’s more suitable for discussions like this 

Oh. I didn't know you had something for that. I don't know what a spectrum channel is. Can you give me a link?

> I’m trying to keep GH issues just for library related things

Cool. I understand. 
Feel free to close this.
