### ISSUE TITLE
Warning: <VIEW /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements. Error Component Stack

### ISSUE THREAD

**Issue by wisnadiputra1** [diegomura/react-pdf#2963]
**Describe the bug**
I found a bug when i use this librrary in react. The bug detect element from this library as warning and that was causing almost 1000 error in browser console

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**

![image](https://github.com/user-attachments/assets/ff5b4846-6eb1-4a3c-9a07-2b7f08f84b8c)
![image](https://github.com/user-attachments/assets/f9098efa-a40b-427f-aee5-15a01e8b2bed)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]
- React-pdf version [4.1.4]

**Comment by diegomura** [comment]
From logs, problem seems to be in the Reports.tsx file. But it's not an issue of the lib
