### ISSUE TITLE
@react-pdf/reconciler tries to access unlisted dependencies

### ISSUE THREAD

**Issue by wojtekmaj** [diegomura/react-pdf#2967]
**Describe the bug**

@react-pdf/reconciler tries to access unlisted dependencies, making the installations non-deterministic and depending on pure luck to work.

**To Reproduce**

Install @react-pdf using Yarn PnP, which points out such errors immediately instead of failing silently.

**Expected behavior**

Package to work

**Actual behavior**

```
✘ [ERROR] Could not resolve "react"

    ../~/.yarn/berry/cache/@react-pdf-reconciler-npm-1.1.2-7ab8edc928-10c0.zip/node_modules/@react-pdf/reconciler/lib/index.js:1:18:
      1 │ import React from 'react';
        ╵                   ~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "react" here because it's not listed as a dependency of this package:

    ../.pnp.cjs:2880:31:
      2880 │         "packageDependencies": [\
           ╵                                ~~
```

```
✘ [ERROR] Could not resolve "object-assign"

    ../~/.yarn/berry/cache/@react-pdf-reconciler-npm-1.1.2-7ab8edc928-10c0.zip/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:13:
      1 │ import e from"object-assign";import n from"react";import*as t from"...
        ╵              ~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "object-assign" here because it's not listed as a dependency of this package:

    ../.pnp.cjs:2880:31:
      2880 │         "packageDependencies": [\
           ╵                                ~~
```

```
✘ [ERROR] Could not resolve "scheduler"

    ../~/.yarn/berry/cache/@react-pdf-reconciler-npm-1.1.2-7ab8edc928-10c0.zip/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:66:
      1 │ ...rom"react";import*as t from"scheduler";function r(e){return e&&e...
        ╵                               ~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "scheduler" here because it's not listed as a dependency of this package:

    ../.pnp.cjs:2880:31:
      2880 │         "packageDependencies": [\
           ╵                                ~~
```

**Comment by szymekTS** [comment]
Hello have the same problem:
* react-pdf/renderer@4.1.2
* next@15.0.3
* react@18.3.1


`
./node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:51
Module not found: Can't resolve 'scheduler'
`

**Comment by bkniffler** [comment]
Same with bun

**Comment by saengmotmi** [comment]
Hi, @wojtekmaj 

I noticed that the library relies on scheduler as part of its functionality, but it is not explicitly declared in peerDependencies. This can cause issues in stricter dependency management environments, such as Yarn PnP, where undeclared dependencies are not automatically resolved.

Would it make sense to add scheduler as a peerDependency to ensure compatibility, especially since it's tightly coupled with React? This might also help avoid potential version mismatches between scheduler and React.

**Comment by jrtell1** [comment]
@diegomura Thank you! ❤️
