### ISSUE TITLE
Module not found: ESM packages (@react-pdf/renderer) need to be imported

### ISSUE THREAD

**Issue by sriechersrc** [diegomura/react-pdf#2992]
**Describe the bug**

When trying to build a Next JS  15 app I get the following error:
`Module not found: ESM packages (@react-pdf/renderer) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals`

These are the versions I am using:
```json
{
  "next": "15.0.3",
  "react": "19.0.0-rc-69d4b800-20241021",
  "@react-pdf/renderer": "^4.1.5"
}
```

This is the code snippet that caused the error:

```typescript
const PDFDownloadLink = dynamic(
  () => import('@react-pdf/renderer').then((mod) => mod.PDFDownloadLink),
  {
    ssr: false,
    loading: () => (
      <Skeleton className={cn(buttonVariants({ variant: 'default' }), 'bg-muted min-w-36')} />
    ),
  },
)
```

I managed to fix it by setting 
```typescript
const nextConfig = {
  experimental: {
    esmExternals: 'loose',
  },
}
```

Maybe swap out all Common JS imports with ESM if possible? That way we can get rid of the esmExternals option.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome
- React-pdf version ^4.1.5

**Comment by PeterLaudel** [comment]
You need to this:

pdfViewer.tsx
```
import { PDFViewer } from "@react-pdf/renderer";

export default PDFViewer;
```

something.tsx
```
const PDFViewer = dynamic(() => import("./pdfViewer"), {
  ssr: false,
});
```
Iam not sure what the right sentence is but you can only dynamicly import local files.

**Comment by DikoMahendraa** [comment]
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config: {
    resolve: { alias: { canvas: boolean; encoding: boolean } };
  }) => {
    // Handle PDF renderer
    config.resolve.alias.canvas = false;
    config.resolve.alias.encoding = false;

    return config;
  },
  transpilePackages: ["@react-pdf/renderer"],
};

export default nextConfig;

You can add it in your next.config.ts file
