### ISSUE TITLE
Page wrap not working landscape

### ISSUE THREAD

**Issue by Vincenzo1997** [diegomura/react-pdf#300]
Hi, I'm trying to buil a pdf with dynamics pages in orientation="landscape", the problem is that the tag wrap doesn't work. Here is my code:

`      <Page orientation="landscape" wrap>
                <View style={{padding: 10}}>
                {this.state.tableHeaderPdf}
                <View style={{flexDirection: 'row'}}>
                  {this.state.tablePdfOre}
                  {this.state.tablePdf}
                </View>
                </View>
            </Page>
`

**Comment by diegomura** [comment]
Thanks for reporting this. It's going to be solved on the upcoming new wrapping solution. I cannot work in both solutions at the same time, so I'll have to ask you to wait until this new PR get's merged 😄 . Hopefully it will be very soon! Very little to go
