### ISSUE TITLE
Document fails to render with react@16.5.0

### ISSUE THREAD

**Issue by vlad-khitev-axon** [diegomura/react-pdf#305]
**OS:**

Ubuntu 18.04.1 LTS

**React-pdf version:**

1.0.0-alpha.15

**Description:**

React-pdf doesn't work with react@16.5.0. Below there is an error shown while trying to render the `Document` component.

```
Uncaught (in promise) Error: Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.
    at invariant
    at findCurrentUnmaskedContext
    at getContextForSubtree
    at Object.updateContainer
    at Document$$1.componentDidMount
```

However, with react@16.4.2 everything is working fine.

**How to replicate issue including code snippet (if applies):**

```js
import React from 'react';
import {Document} from '@react-pdf/renderer';

export default () => <Document />
```

**Comment by RyanDriscoll** [comment]
I'm getting the same error, but on React 16.4.2 and only when deployed to our staging environment. 

works great in development apart from this warning:

`Resource interpreted as Document but transferred with MIME type application/pdf: "blob:http://localhost:3000/d3af502c-6350-484f-8a7c-daed52be6968"`

**Comment by RyanDriscoll** [comment]
updating to 1.0.0-alpha.17 and using the new PDFDownloadLink did the trick for me!

I was trying to create the pdf on the fly with dynamic content, using a frankenstein combination of some of the suggested workarounds to no avail. Thanks so much for adding these features to the api! Fantastic project!

**Comment by diegomura** [comment]
Thanks @RyanDriscoll !!
Its great to see that there is people taking advantage of the new changes in such a short time.
I guess this issue is still relevant though. Didn't try the lib with react@16.5.0 yet, but not sure how much I can do on my side yet.

**Comment by diegomura** [comment]
<img width="887" alt="screen shot 2018-09-15 at 5 51 02 pm" src="https://user-images.githubusercontent.com/5600341/45590505-f9b77d00-b90f-11e8-87bc-c98853291429.png">

I tried this today and everything seems to be working fine now. Apparently the new DOM binding changes solved this issue 😄
