### ISSUE TITLE
appendInitialChild

### ISSUE THREAD

**Issue by dylinmaust** [diegomura/react-pdf#309]
**OS:** MacOS 10.13.6

**React-pdf version:** 1.0.0-alpha.17

**Description:** Using custom components with this library throws the following exception:

Cannot read property 'appendChild' of undefined at https://github.com/diegomura/react-pdf/blob/71b644c65fcb401790f31bb243a37f490ce84e6b/src/renderer.js#L44

**How to replicate issue including code snippet (if applies):**

In testing download functionality for a simple PDF, I was able to generate a PDF with the supplied components (Page, View, Text, etc.). But when I add a simple custom component, I receive the above exception. Does this library support custom components?

For example, the relevant code that renders this PDF:

```
...
renderPdf() {
    const styles = StyleSheet.create({
      page: {
        flexDirection: 'column',
        backgroundColor: '#E4E4E4'
      },
      section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
      },
    });

    const MyDocument =
      <Document>
        <Page size="A4" style={styles.page} wrap>
          <View style={styles.section}>
            <Text>Test</Text>
          </View>
          <View style={styles.section}>
            <PdfHeader name="John Doe" date={new Date()} />
          </View>
        </Page>
      </Document>
    ;

    return (
      <BlobProvider document={MyDocument}>
        {({blob, loading, error}) => {
          if (loading || error) {
            return null;
          }

          saveAs(blob, 'Test.pdf');
          return null;
        }}
      </BlobProvider>
    );
  }

...
```

And the basic component (PdfHeader) that's causing issues:

```
import logo from '../../../img/logo.png';
import PropTypes from 'prop-types';
import React from 'react';

const PdfHeader = ({
  name,
  date,
}) => (
  <div>
    <img src={logo} height={34} width={78} />
    {name && name.length && <h3>{name}</h3>}
    {date && <h3>{date.toString()}</h3>}
  </div>
);

PdfHeader.propTypes = {
  date: PropTypes.instanceOf(Date).isRequired,
  name: PropTypes.string.isRequired,
};

export default PdfHeader;
```

**Comment by diegomura** [comment]
That's because you cannot use DOM elements inside the PDF (`div`, `image` and `h3`) in this case.

All document elements should be PDF type elements (`View`, `Image`, `Text`)

**Comment by diegomura** [comment]
Just in case, I added a more descriptive error message when this happens: https://github.com/diegomura/react-pdf/commit/d81aae553f2c4022cde9ec554ae22bb78259dccf

This change it's going to be included on next version

**Comment by dylinmaust** [comment]
@diegomura I figured as much since all examples used those components. It makes sense! But it's unfortunate because your library looks awesome and I love the API (especially PDFDownloadLink, BlobProvider). Thanks for the quick response and a great library!
