### ISSUE TITLE
View has wrong space computing

### ISSUE THREAD

**Issue by ozifg** [diegomura/react-pdf#316]
**OS:** All

**React-pdf version:** 1.0.0-alpha.17

**Description:** 
Hi,
I have found very annoying problem with View component. When View is applied as a wrapping component, the space computing between components is wrong.

For example repeating this code inside Page component:
```
<Page style={styles.body} wrap>
    <Text style={styles.text}>
        Lorem ipsum
    </Text>
    <View style={styles.view}>
        <Image style={styles.image} src="/static/images/quijote2.png" />
        <Text style={styles.text}>
            Lorem ipsum
        </Text>
        <View wrap={false}>
            <Image style={styles.image} src="/static/images/quijote2.png" />
            <Text style={styles.text}>
                Lorem ipsum
            </Text>
        </View>
    </View>
</Page>
```
results in situation, that the View with wrap={false} is not applied to the page if the remaining space is not sufficient (which is correct), but the space which is skipped is not added to the next page for following components and overlaps them. 

Repl sharing URL is currently not working for me, so the full code is as follows:
```
const Test= () => (
  <Document>
    <Page style={styles.body} wrap>
	  <Text style={styles.text}>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
		Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
	  </Text>
	  <View style={styles.view}>
		<Image
			style={styles.image}
			src="/static/images/quijote2.png"
		  />
		  <Text style={styles.text}>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
			Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  </Text>
		  <View wrap={false}>
			<Image
				style={styles.image}
				src="/static/images/quijote2.png"
			  />
			<Text style={styles.text}>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</Text>
		  </View>
	  </View>
	  
	  <Text style={styles.text}>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
		Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
	  </Text>
	  <View style={styles.view}>
		<Image
			style={styles.image}
			src="/static/images/quijote2.png"
		  />
		  <Text style={styles.text}>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
			Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  </Text>
		  <View wrap={false}>
			<Image
				style={styles.image}
				src="/static/images/quijote2.png"
			  />
			<Text style={styles.text}>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</Text>
		  </View>
	  </View>
	  
	  <Text style={styles.text}>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
		Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
	  </Text>
	  <View style={styles.view}>
		<Image
			style={styles.image}
			src="/static/images/quijote2.png"
		  />
		  <Text style={styles.text}>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
			Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  </Text>
		  <View wrap={false}>
			<Image
				style={styles.image}
				src="/static/images/quijote2.png"
			  />
			<Text style={styles.text}>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</Text>
		  </View>
	  </View>
	  
	  <Text style={styles.text}>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
		Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
	  </Text>
	  <View style={styles.view}>
		<Image
			style={styles.image}
			src="/static/images/quijote2.png"
		  />
		  <Text style={styles.text}>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
			Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  </Text>
		  <View wrap={false}>
			<Image
				style={styles.image}
				src="/static/images/quijote2.png"
			  />
			<Text style={styles.text}>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</Text>
		  </View>
	  </View>
	  
	  <Text style={styles.text}>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
		Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
	  </Text>
	  <View style={styles.view}>
		<Image
			style={styles.image}
			src="/static/images/quijote2.png"
		  />
		  <Text style={styles.text}>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
			Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  </Text>
		  <View wrap={false}>
			<Image
				style={styles.image}
				src="/static/images/quijote2.png"
			  />
			<Text style={styles.text}>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</Text>
		  </View>
	  </View>
	  
	  <Text style={styles.text}>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
		Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
	  </Text>
	  <View style={styles.view}>
		<Image
			style={styles.image}
			src="/static/images/quijote2.png"
		  />
		  <Text style={styles.text}>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
			Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		  </Text>
		  <View wrap={false}>
			<Image
				style={styles.image}
				src="/static/images/quijote2.png"
			  />
			<Text style={styles.text}>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</Text>
		  </View>
	  </View>
	 
    </Page>
  </Document>
);

Font.register(
  'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf',
  { family: 'Oswald' },
);

const styles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
  },
  text: {
    margin: 12,
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: 'Times-Roman'
  },
  image: {
    marginVertical: 15,
    marginHorizontal: 100,
  },
  view: {
	color: "red",
  },
});

ReactPDF.render(<Test/>);

```

**Comment by diegomura** [comment]
Couldn’t see it yet sorry. I’m on vacations now for a few more days 😊 I’ll check it out as soon as I can after my return

**Comment by baileysingleton** [comment]
Got the same problem on 17. Any further development? I would just update to a new version, but then all my borders disappear and head elements don't work as intended..

thanks

**Comment by diegomura** [comment]
I was just looking at it. Sorry it took so long. 
However, I don't see the issue on the document. [Here it is your snippet in the REPL](https://react-pdf.org/repl?code=3187b0760ce02e00402a05368178600a0250d903e740a061801e0044460057016c130a1d0a24801404301cc119a013c01b04c80379f411001d002310004d7805f1801dc0139b000e8c024116288007ac31434540148254044614eed006442a84d46004b0d1068c5921fb38f3bac1b2d14000d0c282402303594252a8c1b2ca7bb84303b98070c023f306444022caf882e7ba504351c8c35b506a056666a6ca53d0c252c3f1b0c8bae6c1f805f7527181b327e4023a51b04be36b6802aac1d3b9b8a4c35165acc001baae86474fa4c1808342aa5094d822aa6541b143bb8077f3775280c376f49d83a7b87442534a27972065cb8d40d46a9f8a2e022b4d1e7305a90411064a75b8ee4b9f5068d300c05c1a170002ce8b25bb043c04ddbf9281a07b58f6792a5208a51771bc7c78be82128300019a5038ee47a9d286f71868d8aa5142554c8bd001e90c0c799e8006aee0432878e6410884c925db6b947679b69880049119702dda1321bf59635a70100a7b440eec8001112ba08f7730095aeae04095c70015881ac002609069b23e8b51095f63d2aaf5162745924d65b3d91cce57078bcdcff2042054d08202270989c56b8964aa434e94cb6572f93ad144ab084054aa353a834924d770b4dab04e97c7ac5fea9486dc5b58c26ee4472216cb5c9fdd6252daef997f438c18ee8b385cae60dbbdd032f097bd3edf672fdfe80b5f1c3460885c3a17232b44088cc5026eda2a2271b09887838b703cb5284820c48206498014acab01647b1d20ca3cdc3ecddae4103b2991726e0f2dc1f282b0a72b8a928c0d2aca8f224a0400a20630088758cd956ed050c01b0b118a541b6b223c6299c04b122004e740f653bc1543f0d2a9e208c02000a02906a2af8482dcf27546f3568784e8457473a5cd426ecaaaae98905a8ea2a3a81a088029b0fc1144a0525230a85b5ab6820f683ace8e6e2048a1bba8157ac02fafea3241886fe786518c6083c689870c982cba0c069bdafa0d8c6305662e656015e6965458b86e278de191159245588461244806c4f1336291a419164390b23db14a5394950c2b52b8a3b52cd04ef24cecfaf2033d5cba8ce31b9eb8cca052c2b21e1b01e3b3ecc7b50471a2a739c5025cd701837b04778120fa844fb99af956ef8ad9fb7e08242201feb0ab588881794aa056d9c412af67283a32aa0f83303aa242668eb15a17e6503959549635796431044d6d62d7c26d536492756db759d9f58500dfda0e2348ef8a4dad3b433799147cd4ba6c4b47e6b45adbaac7ba6cdb1b87b68a074a9bf09d6775e7715d4f3de9287c652cd8f402338bd2097e360fe508c2005e3bf66ee07a290532d8a24b07d5f0512a4b929486134b618c9e17d611c4672fc063f3a514288ae26ddf44ca72b3130f0336607a0d66068239609a3a8a37e5ba9e91546985fe47a59545314064f306e152520b4671826498a63950370c27ce9e6656164e155a5ad58ba56d5b35f59148dbca2d9751daf5ddb937d99403b0dc398db4c4e53433666f4ccfd7c33b32aeccf6b735b7eefcd1e42e1da2e5ee765d714cb8fbcb0f79e6fb2bc0a82eafbdbf96bcdc20bafdafac6246cc153f9b8865ba875bf06d2aece14cbe1ac911dc091aeceaab30f6d45bd9d1062fec153da3621c4191f206a591601f1012fc56030909c625600497a2aa1a48527a0851e4a61452ca58e1a90d25a5c6052228971da0190226c18cb5c680b397a0d02b224001918206a1cd42681726e43c8e96f21c17c8da38e155e1a2770a29d53b7a3f419de2b6708cb9c529a542e595532f952ed982385702c815ab9a332c4021bb633acad55b87556ced87a9760283c0299f72a683dea30f49c63d587bb166f385732d60473c2a82f1d8db597a0b13c6798e86f096b79a58dd596f747e01f27a47d5689f70467d35bfe4bed7cb290740645d81a4340e20d4d14340e3a3c3a2724628c8c7551318fd1ab2426e963daa131b124cbb838dec835fb90e12834cc71803a6d35c7b78a9e8b4382ae59e9b9826f31da02c0e30b4891794e95e1b892db7bc4dde5e365324a56408d25ab0c91f4beb6b188b92c091d4365881f9c14c216d9095b742efcedae1664044d93ff1766ed793f24f6344c00fb0814c4a07657c9dc243a9a30ea6113947334f61639da54e65c4a8c8cf4f2362a062ce894547b83cea940b86522eb941606602a30a42a581a955d8b3d4bae7049a4d60b178cac7b48ee762c9a38dee435fa68d37143246678d9a93dc89b3299fe356a04adc9b44252f43ce139651d559e2c366c4e78db2ee9ef249a710fa1cd7aa7d4e45f1fac0540adf1b9d044da3f079cfc9e6bf1799843fbd27b61f37fb3b522133723fcd01583815fb505ac5d8a7178141178b007e2824d07d20c18c98ea495c1324084f02210484878c321ea534a642a1ba5686c07a1464760992406322c8708856a8c95d96857c39cb08572ee5dd3089f2795c4722945ba3a472748a98b144e2b7439df15a8a25994ab692858f948c252bd1a540c4553a9b5d7e56366938d2f9b2f6ec4d3bbd8fea3cafa75321e82a47bd369ca5b4542d715d32027ad3992d8f982aa596bdcf18b7591753675d5783b215bece7ac7d8e46b4fac6a75a9affac1cab514b292538a7650a914aa479759dc8dec02ef46a6210798dc60d8da46edb1a4dbbb72de92e20641e89a47b466ecb3daccfc47369537b427defda8faa25accde6fae247ead5bb3158fea396f48d7649354882d39aa82c6d7119b1b5484509a12a48eade77f4765f23907ab15202bdafaf01febe522a4e1a0735342b83255e14c736d0143b554f83e8ae4745051715fb5863c504bd4712b1d25d60ea2c4695ded3218698cb1baaed6904db0e74edd3dc08c0f22302a48c7893de461718aaa3333e7acaf996121f48b27dd12d554b0d5ec6e5a71efda920d49cf3efc680e09acac27ef95afb90491e549b7eb273f8ba9fe2b0ff929c019eb54e02bf58c4b4f40a0d703b8a20b52e1a5050968da2563760a9289ae4bb4621129486a94cd942748d0fd2fe018530d32bb3d8614ae195bc16f0a720231b679040222c47f948aee65d376c91bdb6cc2501d0e7877a551dd95c765a4a9b0be0cd2c3174b176a1e5dcca30cb72c344c70d749dd616f960ca8ba3c62c8ab8be7a12d5ec0ab47e56ed34b2b39f4b1f553bc38d7edd5293f56ab5e3257be995bfa7920ed035293a8a1b81c6730c60d4e8331e6e76a37a54ba994b4d6510e3a56eae53d329b85fe5e35c7345f7cc8f6b27ab4752b66725dbd0b257844e5578e62765c2779789dfc5271cdd27feb3939380ca26b9226ee789dabb6beac3adb64d7de4b5a76df394f9eaeb603ba2fb5eb01dc15d3a850e439e47534c67aed99dfb68beec2c34e367b173dfb3c95f3bbd925ae7d9eddfd1886bce039438d2fccb2cc381721f059174e3797eec8b52f11ccba6628f28ccf74759531ddeec70c7d2d31d55afa09e6add7fbc49c1cc377fb32401d2b172cdf9b88296faaf5b8429279e4c9877cea9dc29b6b0037e4516f56a76897b9057d6b28c0e0d436c3446d4151026e60b8d382f06c9421f375362df4dcb628766b5b7a4e866dc2dd5598696bdb607fdd81e3bfc2f5a8224da5e42da7922663769da16651ed1e8f671eca289e84ac9e9a2c5c7943f654a19e28c0b0de60ca66c7cefe602e85e42e9ca786a2ece2e2ef0e95ec7ad5e13cb5ebe2f5e8ae18ecae7462deabc6de2aa2fa5bcefab743de3aafaefde2ac46e43e26e02634e13a7fe7ee50610c106d06e0ae8133aff6d81d9e3e678179e60ef8c6dc45ec2ea41a5e7baae292ec32a46c2a35e72ef160c11b85cccc158e8b2adeb8e9969dedaedde8922f805664e4217c654ea3ee5657213e55662698c1262fcd2636c5848eef269f22be3f2a86ebe5449be40a1a63ee60ad64052476fa6e9e12046688a101e1e18149c6e8b220e870199cf1e480af649e1a29f6a9e8545012548a14a135c39ebe6e866ba82e1cab86dd2ba184612eee255e8ccb41a61a8ee619cc8de561cde3616c1761cc65ae5b2b96ce17b27dedc6456c6e8065e16213e106c93efe1f8833e4110d60be5fc0ec111eea1d62a61bedd609190281ab025c408247e63651a224e7ed3609af8273621169a22ce4259ada4d42afef9aefe210db625abb6964fb6a06a910e4b5aa76422a01a22ada61e39133a966566e9c4f6081aa2e51ce62e66816e63519ce99ef3aca1b8198cf81f9ee0e4416d1d0ea1662e70ec46541646b2e3e2d3c12ad46d7aa31aae8aa8c61c1f8e8e1b31daa2e10b1856e4e86a94ee72404de1968121d212ce921321d0ccc09c2ec05c08c0ca8e40540b40f408c0180000dcf80f8000062e002042e0228d00b706804c0000e42485005005e00005c4a84a80284699201c07da120508fe84a8e70ca06e4b204a8bb00008c000cc4a80009a000fa700000d21a80006c2000001c000ea200bb05208b0b20219d409190001a0009c6c000082c59560500028969e104c0c20828a109c8bc0f69300969000f21007e9fc0b209693000a0d593a97a9804d51e20d80300000cace8a39648b589e92e0b84680c204c0320f204d90b90a9d28b20a90d907002001a04d9219000acd596b92909b91c0000423185009f44d9f198794c0440eb9a79000122f80005e4696e47b9779440bd94c048c2b9f796ccaa02286004d9419b18479cc02e9f40a39ee0af90806050002c90544048cc59f905324d99699189504f0028bc0559805d05500fa9f59fc08d9cd97006b0480000b40004a9f48c29694c0bf9440e140050a9230c055901a8b7099c9f9300419df9cc05c52052f9b28ef9f400254190000c325905ac57b0a68005da0a004304d93e82e0b203e80a5d590a0fd9f80745ef47102c0a40fa91202e0f6a680f94d006983a94000000). I added some `debug` props to the non wrapping nodes, and as you can see they do not wrap if there's no enough space. And then, there's no overlapping going on.

If it's no much to ask, can you provide some more insight about this issue? Maybe it was in a previous version. Thanks!

**Comment by ozifg** [comment]
After upgrade to 1.0.0-alpha.25 I see no more overlapping. It seems to be solved in this version.
Thank you for your help.
