### ISSUE TITLE
How to open rendered PDF in a new tab

### ISSUE THREAD

**Issue by serkyen** [diegomura/react-pdf#318]
**OS:**
macOS High Sierra

**React-pdf version:**
"@react-pdf/renderer": "^1.0.0-alpha.17",

**Description:**
I am currently using PDFDownloadLink to download the PDF but is there an alternative way to open the rendered PDF in a new tab instead of downloading it? Maybe with `<BlobProvider />`?

**Comment by diegomura** [comment]
Hey!
You can easily do that using the `<BlobProvider />` as you suggested:

```jsx
<BlobProvider document={MyDoc}>
  {({ url }) => (
    <a href={url} target="_blank">Open in new tab</a>
  )}
</BlobProvider>
```

Hope this helped!

**Comment by zheoreh** [comment]
@diegomura @serkyen Where are BlobProvider and PDFDownloadLink from? From react-pdf?

**Comment by diegomura** [comment]
Yes.

```js
import { BlobProvider, PDFDownloadLink } from '@react-pdf/renderer'
``` 

These are web only APIs

**Comment by zheoreh** [comment]
BlobProvider doesn't work properly for me. I take the pdf document from example (Readme) and push it into BlobProvider as you wrote above but I have no url, blob is empty. If I push the document next way document={<MyDoc/>} I have another issue. Can you provide full an example please?

**Comment by diegomura** [comment]
```jsx
import { Document, Page, BlobProvider } from '@react-pdf/renderer';

 const MyDoc = (
  <Document>
    <Page> ... </Page>
  </Document>
);

const App = () => (
  <BlobProvider document={MyDoc}>
    {({ blob, url }) => (
      // return something using blob or url
    )}
  </BlobProvider>
);
```

This should do the trick. If it doesn't work, it would be better for you to share a snippet of code so I can see why is not working

**Comment by Paul6552** [comment]
Sadly, I am not able to get it working in a new tab. I am using react with typescript.

![image](https://user-images.githubusercontent.com/25934591/63939840-7d5a7300-ca68-11e9-878c-8e935c64b6f5.png)

a href has a type string or undefined, but url from react-pdf is string or null. Can anyone show me how I can fix this. thank you

**Comment by timbicker** [comment]
Hi,
Is it possible to change the url? E.g. I don't want the document to be called `9b6cd832-4ae8-487c-a71a-0961709dd364.pdf` when I click on save. I prefer to call it something based on the user attributes e.g. `username.pdf`.
Thanks

**Comment by Alvina05** [comment]
> ```js
> import { Document, Page, BlobProvider } from '@react-pdf/renderer';
> 
>  const MyDoc = (
>   <Document>
>     <Page> ... </Page>
>   </Document>
> );
> 
> const App = () => (
>   <BlobProvider document={MyDoc}>
>     {({ blob, url }) => (
>       // return something using blob or url
>     )}
>   </BlobProvider>
> );
> ```
> 
> This should do the trick. If it doesn't work, it would be better for you to share a snippet of code so I can see why is not working

I have done exactly the same and yes it works but only the for the first time when the application runs. If I navigate to another tab and then come back here and try to generate PDF, the blob returns empty url. Upon refreshing the page, the url successfully generates. Why does it only work for the first time? Any help would be appreciated

**Comment by diegomura** [comment]
@Alvina05 what version are you running? Try upgrading to the latest I think that should be fixed there

**Comment by Alvina05** [comment]
> @Alvina05 what version are you running? Try upgrading to the latest I think that should be fixed there

Using version 2.0.18
And the code is as follows:
```
<BlobProvider
                  document={
                    <Template
                      columns={columns}
                      data={data}
                    />
                  }
                >
                  {({ url, blob, loading }) => {
                    console.log( url, blob, loading); // null, null, false
                    return (
                      <a href={url} target="_blank">
                        View as PDF
                      </a>
                    );
                  }}
</BlobProvider>
```

Is there something I am missing?

**Comment by yocheved-f** [comment]
i try it,
bug the url been null
why?

**Comment by juanbomfim22** [comment]
Make sure you don't wrap your Document in a `<PDFViewer>`, which was the reason in my case for the url being undefined.

**Comment by GuiC0506** [comment]
> Hey! You can easily do that using the `<BlobProvider />` as you suggested:
> 
> ```js
> <BlobProvider document={MyDoc}>
>   {({ url }) => (
>     <a href={url} target="_blank">Open in new tab</a>
>   )}
> </BlobProvider>
> ```
> 
> Hope this helped!

Great comment dude!
Help me a lot
