### ISSUE TITLE
how to support chinese chars

### ISSUE THREAD

**Issue by jiaoyilun** [diegomura/react-pdf#323]
how to support chinese chars
how can i load my font

**Comment by diegomura** [comment]
Hey!
You can find a related issue here: https://github.com/diegomura/react-pdf/issues/267
You just have to load a chinese font and that's it.

To load a font, you just have to:

```jsx
import { Font } from '@react-pdf/renderer'

Font.register(url, { family: 'FontFamilyName' });
```

`url` can be a valid url for node and browser, and you can also pass the path of a font if you are using the lib on node. I just realized this api is not in the docs. I'll add it
