### ISSUE TITLE
"TypeError: t.getComputedStyles is not a function" when rendering an empty string in Text

### ISSUE THREAD

**Issue by bkoltai** [diegomura/react-pdf#324]
**React-pdf version:**
1.0.0-alpha.17

**Description:**
Error is thrown when attempting to render a `Text` component with `""` as the child

**How to replicate issue including code snippet (if applies):**
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080be3003b80271e001dda74e5400a8614b1a78a95144639002c30f2518b7a8066a83128387384802200d50e432a007a53735f4a08de015f08ba0666567602006e323200317028592d0c3e2468573c0e00727b28285d08002e70f0f77cb93e681e28246059504670887090080d1e11257080370046006670804d007d6300690035003610000e00751029f900552539c665800d004e1e00417bd95af74a801a0e0918771e462411210346095003ca8dc64a4a8c1541f4cb6540900b0d864381800195911834638300560114ba183c048388a1510249865d3389448301f18c205d102e600560f9526974be00085d05010230815b7668460d4a52d3e900091016890002f7cb8c59a2ca0c238dd281882962d6ab0d18a8c102004c00160e67130e67b888907c301032ac016260b4ef3d7e472bf7fa038160b184d2a1c0d6507808283d8e5bac33eaa0868571a60331365b28d6a82dbed8ee04bb58ae0f619183c2d094c07cdaa0a8166800325b433008021e45a9d4c1299c38c2693335d9a660c5d2dd28129fedc7bd7f0053a0310e0fab2d1998e71076591ea73d06a348e2d628cd661d4e8015821a048771090b9daf4faa7c0e31219810002d00095053c301cfa19687ff0931dca0573a436571ba6005564cd565c4b32d6579495560209986b3ac434b51c6715c25d282ecb764dd722c60ba42b014851804d5430c3dced03d735740b7ed40111a3604f82282f7ad2d6a404000e498790b0f6cc55d046241ba7009d1e1e408040110230c12f1c3f26ecd77ed144acc8b9928ce0c4770a0205b4ca1e53e06a033fb6a3b3274f337514980989632a362300e2d0b2154384c817c9c600a02e0681c90a1605c2d0f02a110541d02c1c2620e1200

Here is the code snippet since we're having issues with the REPL:

```js
const Quixote = () => (
  <Document>
    <Page style={styles.body} wrap>
      <Text style={styles.header} fixed>
        {""}
      </Text>
    </Page>
  </Document>
);
```

**Comment by diegomura** [comment]
Fixed! Thanks for reporting it @bkoltai and your hard work on testing the lib extensively 😄 
It's going to be published on next version

**Comment by bkoltai** [comment]
My pleasure, thanks for the continued hard work and responsiveness! You’re
doing an amazing job with this library.
