### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by sveta4acova** [diegomura/react-pdf#328]
OS: macOS High Sierra 10.13.6
React-pdf version: 1.0.0-alpha.18

Hi!
I can't see Russian text.
How can I fix it?

```
<Document onRender={this.onRender}>
  <Page size="A1" orientation={orientation} ref={item => this.page = item}>
    <View style={styles.block}>
       <View style={styles.topLine}/>
       <Text style={styles.name}>Лопата</Text>
       <View style={styles.bottomLine}/>
     </View>
  </Page>
</Document>
```

<img width="598" alt="2018-10-01 13 49 27" src="https://user-images.githubusercontent.com/23114750/46284530-daac2280-c580-11e8-8798-24b3ab51bf93.png">

**Comment by hutsi** [comment]
take a look at https://github.com/diegomura/react-pdf/pull/117

so I guess that you need something like that:
```
import { Font } from '@react-pdf/core'
Font.register(`path-to-font.ttf`, { family: 'Roboto' });
```

**Comment by diegomura** [comment]
Exactly. You have to load a font that support the types of chars you want to render. In this case Russian chars. You can find the APi in the docs

**Comment by Dastnbek** [comment]
This is working for Russian characters 
```
Font.register({
  family: "Roboto",
  src:
    "https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-medium-webfont.ttf"
});
```

**Comment by tomslutsky** [comment]
I can't find anything that is working with Hebrew :(
