### ISSUE TITLE
Unable to install react-pdf pakage in new react app

### ISSUE THREAD

**Issue by balagrishnan** [diegomura/react-pdf#330]
OS: WIndows 10 Pro

**React-pdf version:  v1.0.0-alpha.18 **

**Description: I am trying to add the react-pdf pakages in my new react project , I am getting below error 
1. yarn add @react-pdf/renderer
Error : > ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/) 
 '!' is not recognized as an internal or external command  **

**How to replicate issue including code snippet (if applies): 
1. Create new react app using command :: npx create-react-app my-app
2. RUN : yarn add @react-pdf/renderer **

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Comment by diegomura** [comment]
Please check #327 and my answer there 😊

**Comment by balagrishnan** [comment]
Thanks lot for helping to resolve this issue.
