### ISSUE TITLE
rendering an empty text line explodes

### ISSUE THREAD

**Issue by tpreusse** [diegomura/react-pdf#332]
**OS:** REPL

**React-pdf version:** 1.0.0-alpha.18

**Description:**

```
Uncaught (in promise) TypeError: Cannot read property 'layout' of null
```

Two new lines in a row / rendering an empty text line explodes. 

**How to replicate issue including code snippet (if applies):**

```js
const Test = () => (
  <Document>
    <Page style={styles.body} wrap>
      <Text>
        {"Test\n\nTest"}
      </Text>
    </Page>
  </Document>
);

Font.register(
  'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf',
  { family: 'Oswald' },
);

const styles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
  }
});

ReactPDF.render(<Test />);
```

[react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00402a05368c0bc30050129503e0c0a061801e0044460057016c130a1d0a24801404301cc119a013c01b04280379f411001d002310004d7805f1801dc0139b000e8d9b3628800783263a8b0804489a001d30372d4330b8ee80f4068cee22fd976d245f9152d3d232600373e3e0018b81404aa82070025b4022aba13003900059414068400170b8b8019ac6487341b14127004a8350b840b8804329b3f2c8b801b802300330b8026803e9c0034801a801b080007003a880f54802aac80f528c00680271b0020a1c49e6966400d13308c295b35127f2f214c26403cbb676ca64c0295f864540905818890a81800194a00204043b208041c580091a821d0c2260c9e42f0c4e8346c592c892600e1c0401a1780c00ac573c41289248010880f2206a0bc6634e73e309c48e0002440aa24800bd629d4a572884e05003f00025041b1805016290a2f13a2c8d2e83d121602e1c002800)

**Comment by diegomura** [comment]
Thanks @tpreusse
It’s already reported in #284. I plan to fix it soon, but unfortunately I’m outside town for two weeks, unable to code 😅

**Comment by tpreusse** [comment]
Sorry didn't research the open issues, I'll watch the other one.

Enjoy your vacation! And ping me when your back.
