### ISSUE TITLE
Yoga Layout node Version error

### ISSUE THREAD

**Issue by kations** [diegomura/react-pdf#333]
React-pdf version: "@react-pdf/renderer": "^1.0.0-alpha.18",

If I import @react-pdf/renderer I get the following error:

node_modules/yoga-layout/build/Release/nbind.node'
W20181007-17:39:01.215(2)? (STDERR) was compiled against a different Node.js version using
W20181007-17:39:01.215(2)? (STDERR) NODE_MODULE_VERSION 64. This version of Node.js requires
W20181007-17:39:01.215(2)? (STDERR) NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
W20181007-17:39:01.215(2)? (STDERR) the module

I use Meteor and try to render my PDF server side. It works perfectly on the client.

**Comment by rogierslag** [comment]
`yoga-layout` needs at least Node 8.0.0 to work properly, so you should probably update your node version

**Comment by kations** [comment]
The Meteor server use v8.11.4 of node

**Comment by diegomura** [comment]
This error pops up when you built yoga with a certain Node version and then you run it with a different one. Yoga gets built when installing react-pdf. Please check you're using the same node version both times. Closing this since it's not related with react-pdf per-se
