### ISSUE TITLE
Custom font loading issue

### ISSUE THREAD

**Issue by sebekgr** [diegomura/react-pdf#334]
**OS:** 
Linux

**React-pdf version:**
"@react-pdf/renderer": "1.0.0-alpha.18"

**Description:**
I have a problem with load custom font.
In docs we can read "Specifies the source of the font. This can either be a valid URL, or an absolute path if you're using react-pdf on Node."

So in first approach i tried include font from google font 
https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu72xKOzY.woff2
but this format is not support.
So in second approach I tried upload Roboto font in tff format to my private hosting but in DEMO code there was some message about mix content http/https .. so I upload font into github which has https protocol.

Also I tried served locally font in my react app but there is message error:
" No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3005' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

I built local server for serving font with enabled cors but it doesn't work

I provide react demo where I tried generate pdf with some custom pdf.
https://codesandbox.io/s/5k72n7zq2n

I think there is a problem with fetch method. Exactly in file react-pdf.browser.es.js with
fetchFont method

var fetchFont = function fetchFont(src) {
  return fetch(src).then(function (response) {
    if (response.buffer) {
      return response.buffer();
    }
    return response.arrayBuffer();
  }).then(function (arrayBuffer) {
    return Buffer.from(arrayBuffer);
  });
};
I think that fetch method should include some headers and cors mode for fetching successfully any resources

So the final questions is:
How do I use some custom font ?

**Comment by jasonbarry** [comment]
I have the same question. I haven't been able to use a custom font successfully. It would be helpful to know what font types are supported (.otf, .ttf, .woff, etc) and how to fetch them via URL without running into CORS issues (both during development and in production).

**Comment by emorling** [comment]
The React PDF Playground has a link to
https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf

Does anyone know if these TTF links exist for all Google Fonts?

**Comment by diegomura** [comment]
Nope. Not sure if they do. Sorry

**Comment by diegomura** [comment]
@emorling I recently came across to this repo https://github.com/google/fonts that has all the google fonts in .ttf format

**Comment by diegomura** [comment]
@jasonbarry Only .ttf fonts supported for the moment

**Comment by diegomura** [comment]
Closing this since all points had been cleared

**Comment by marticorena** [comment]
> The React PDF Playground has a link to
> https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf
> 
> Does anyone know if these TTF links exist for all Google Fonts?

Here you cant find a similar link to all google fonts:
https://gist.github.com/sadikay/d5457c52e7fb2347077f5b0fe5ba9300

**Comment by adamdune** [comment]
> @jasonbarry Only .ttf fonts supported for the moment

I think this information would be valuable in the docs. 😃

**Comment by earthnoob** [comment]
Are WOFF/WOFF2 formats supported? I've been trying to import both in files and from Google Font CDN links but to no avail.

**Comment by moparlakci** [comment]
Any known issues when using docker? On development it works fine. But on my production environment, with docker alpine linux it doens't show some of the text. I am using flex to style the items but as I said it works fine on dev.

see screenshots

![dev](https://user-images.githubusercontent.com/4943596/97778708-4bb3cf00-1b79-11eb-820d-4155588b76c6.png)
![prod](https://user-images.githubusercontent.com/4943596/97778710-4eaebf80-1b79-11eb-96ed-0baedab900e6.png)

**Comment by tom2strobl** [comment]
> > @jasonbarry Only .ttf fonts supported for the moment
> 
> I think this information would be valuable in the docs. 😃

lol, it took me two days and a look at ~50 github issues in this repo to find this random comment in a 2018 issue to confirm that only ttf is working. Which is really troublesome since ttf is a largely deprecated format and lots of new fonts are only released as otf (which is also a better and more modern format in every way). The original fontkit also seems to support otf/woff, so (obviously without knowing the full picture) it sounds like not too far fetched? 

@diegomura what are the major show-stoppers? Where do we stand, is there a specific point where I could help?

**Comment by bradenbiz** [comment]
> Does anyone know if these TTF links exist for all Google Fonts?

Yes, [you just have to use `curl` on the URL you get from fonts.google.com to get that `gstatic` URL](https://stackoverflow.com/a/72991811/8804276), which seems to be the only URL that works in getting the font registered with react-pdf.

**Comment by schnz** [comment]
> @jasonbarry Only .ttf fonts supported for the moment

Has this changed since you wrote this comment? Because .woff fonts seem to work fine, whereas .woff2 seem to be problematic.

**Comment by karlhorky** [comment]
> Has this changed since you wrote this comment? Because .woff fonts seem to work fine, whereas .woff2 seem to be problematic.

I can confirm that WOFF fonts work, but WOFF2 fonts do not.

I've opened a PR to document WOFF support here:

- https://github.com/diegomura/react-pdf-site/pull/133

**Comment by sneko** [comment]
Same than others, specific WOFF2 fonts work but not some others.

I think the documentation should be a bit more clear on https://react-pdf.org/fonts that `WOFF fonts files are supported (but not WOFF2)`.

**Comment by pklepa** [comment]
> > Does anyone know if these TTF links exist for all Google Fonts?
> 
> Yes, [you just have to use `curl` on the URL you get from fonts.google.com to get that `gstatic` URL](https://stackoverflow.com/a/72991811/8804276), which seems to be the only URL that works in getting the font registered with react-pdf.

Great workaround. Worked well for me :)

**Comment by HassanZohaib121** [comment]
i am having a different issue with the font it works on firefox only even after creating pdf it still works on firefox only. 
it shows only image on other browsers and in adobe reader it shows error. on edge it only shows image but when try to print it show data as well.

Font.register({
  family: "jameel",
  src: path.join(process.cwd(), "/fonts/Jameel.ttf"),
});

https://urdufonts.net/fonts/jameel-noori-nastaleeq-kasheeda

[document.pdf](https://github.com/user-attachments/files/25470621/document.pdf)
