### ISSUE TITLE
document render

### ISSUE THREAD

**Issue by sveta4acova** [diegomura/react-pdf#335]
OS: macOS High Sierra 10.13.6
React-pdf version: 1.0.0-alpha.18

When I re-render pdf document, I have an issue.
Data is not being changed.

https://yadi.sk/i/ySMBmrev9nwO1w

<img width="822" alt="2018-10-09 16 39 58" src="https://user-images.githubusercontent.com/23114750/46673243-03b45f00-cbe2-11e8-8003-01878088488f.png">
<img width="810" alt="2018-10-09 16 39 35" src="https://user-images.githubusercontent.com/23114750/46673242-03b45f00-cbe2-11e8-9b24-92ebd5d37dc9.png">

**Comment by diegomura** [comment]
Hey!
Thanks for reporting this. That’s a very odd behavior. Are you passing the ‘wrap’ prop to Page or not? If data passed to the PDF tree does not change, the document shouldn’t re-render. Can you provide a snippet so I can replicate it?

I’m on vacations right now without access to a pc, but I’ll take a look as soon as I can. I apologize for that. Thanks for your donation and for using the project btw!

**Comment by sveta4acova** [comment]
Thank you. Prop wrap helped me. Enjoy your vacation:)
