### ISSUE TITLE
Text incorrectly line wrapping

### ISSUE THREAD

**Issue by dberringer** [diegomura/react-pdf#347]
**OS:**
MacOS 10.13.6

**React-pdf version:**
1.0.0-alpha.18

**Description:**
There is something strange going on where text is getting line wrapped incorrectly.  It seems to have something to do with multiple views wrapping text that has a height specified.  Seems strange that height would impact width and text wrapping.  See below commented example for details.  This should work just fine in the react-pdf repl but repl share doesn't seem to be working right now.

**How to replicate issue including code snippet (if applies):**
```
const doc = (
  <Document>
    <Page wrap>
      
      {/* This work fine */}
      <View style={{flexDirection: 'row'}}>
          <Text style={{ height: '100%' }}>123456789</Text>
          <Text style={{height: '100%'}}>This is some text</Text>
          <Text>123456789</Text>
      </View>
      
      {/* This has a strange wrap on numbers that specify height 100% when wrapped with an extra View */}
      <View>{/* This extra view tag seems to cause hight styles to create weird wrap issues */}
        <View style={{flexDirection: 'row'}}>
	<Text style={{ height: '100%' }}>123456789</Text>
	<Text style={{ height: '100%' }}>123456789</Text>
	<Text style={{height: '100%'}}>This is some text</Text>
	<Text style={{ height: '100%' }}>123456789</Text>  
	<Text>123456789</Text>{/* This does't specify height and doesn't wrap as expected */}
        </View>
      </View>
      
      {/* This row will not display unless at least one of the children is given a height */}
      <View style={{flexDirection: 'row'}}>
          <Text>This is some text</Text>{/* Not displayed */}
          <Text>123456789</Text>{/* Not displayed */}
          <Text>123456789</Text>{/* Not displayed */}
      </View>
    </Page>
  </Document>
);

ReactPDF.render(doc);
```

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Comment by diegomura** [comment]
Thanks for reporting this! 
I'll check it out asap

**Comment by AirborneEagle** [comment]
I am now running into this.  While I await for the release, can you please explain the cause, so that I can structure things to workaround the issue?

Thanks!

**Comment by diegomura** [comment]
I released today. 1.0.0
