### ISSUE TITLE
<PDFDownloadLink /> Element type is invalid

### ISSUE THREAD

**Issue by bubblybunii** [diegomura/react-pdf#354]
I am using typescript in react and faces the following error whenever I use `<PDFDownloadLink /> or <BlobProvider />`

_`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`_

Any help is greatly appreciated!

```
import { BlobProvider,PDFDownloadLink,Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer'

export default class Test extends React.PureComponent<any>  {
   
    render() {
        const MyDocument = (
            <Document>
              <Page size="A4" style={styles.page}>
                <View style={styles.section}>
                  <Text>Section #1</Text>
                </View>
                <View style={styles.section}>
                  <Text>Section #2</Text>
                </View>
              </Page>
            </Document>
          );
        return ( 
            <div className="wrap">
            <h1>test test</h1>
            <h1>test test</h1>
            {MyDocument}
          
           <PDFDownloadLink document={MyDocument} fileName="somename.pdf">
      {({ blob, url, loading, error }) => (
        loading ? 'Loading document...' : 'Download now!'
      )}
    </PDFDownloadLink>
            </div>
           
        )
    }
}
```

**Comment by diegomura** [comment]
What are you using to build your project? It seems that the DOM build is not being loaded

**Comment by bubblybunii** [comment]
@diegomura I am using virtue DOM in typescript, , is there an alternative way to trigger the download link by a button instead?

**Comment by diegomura** [comment]
Hey @bubblybunii . I have no idea what is virtue DOM in typescript. 
I think this issue is happening because the lib is not being properly loaded by your bundler. You are loading the node bundle instead of the web one. Maybe you can force this by importing from `@react-pdf/renderer/dist/react-pdf.browser.cjs`

**Comment by diegomura** [comment]
https://github.com/diegomura/react-pdf/commit/789eb9cc78ecaf8e7e04dc8ca1dc8ac7b48f86de

Next time this happens you will see a more descriptive error. However, there's no much I can do, just ask you to check that you're loading the appropriate build
