### ISSUE TITLE
failed to load pdf file

### ISSUE THREAD

**Issue by qwaszx1230** [diegomura/react-pdf#357]
**OS:**

**React-pdf version:*3.0.5*

**Description:
     When using cavans rendering, the pdf in the IE or ege browser can not be rendered, display a blank page, then I try to use svg rendering mode, but there will be garbled situation, the introduction of cMapUrl in setOptions can not solve this problem. Another problem is that some pdf files can be opened normally for the first time, but they cannot be opened for the second time, showing "failed to load pdf file"

**How to replicate issue including code snippet (if applies):
   export interface IAkPdfViewerProps {
    visible: boolean;
    fileUrl?: string;
}
export interface IAkPdfViewerStates {
    fileUrl?: string;
    pageIndex: number;
    totalPages: number;
}
export class AkPdfViewer extends React.Component<IAkPdfViewerProps, IAkPdfViewerStates>{
    constructor(props, context) {
        super(props, context);
        setOptions({
            cMapUrl: window["CDN"] + "js/pdfjs/cmaps/",
            cMapPacked: true,
        })
    }

  componentWillReceiveProps(nextProps) {
        if ("fileUrl" in nextProps && nextProps.fileUrl !== this.props.fileUrl) {
            this.setState({ fileUrl: nextProps.fileUrl });
        }
    }

render() {
   return <div>
        <Document
                            options={{
                                cMapUrl:"js/pdfjs/cmaps/",
                                cMapPacked: true,
                            }}
                
                            file={this.state.fileUrl}>
                            <Page
                                pageNumber={pageIndex}
                                // renderMode="svg"
                                renderTextLayer={true}
                                renderAnnotations={true}
                             />
                        </Document>
  </div>
}
}

![image](https://user-images.githubusercontent.com/22724660/47625948-6bb3f080-db63-11e8-94c7-de2334867613.png)
![537488598830205505](https://user-images.githubusercontent.com/22724660/47625972-8edea000-db63-11e8-8f44-41eba15e4eea.png)

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Comment by diegomura** [comment]
@qwaszx1230 you reported this in the wrong package. This is react-pdf renderer. 
You should go to https://github.com/wojtekmaj/react-pdf
