### ISSUE TITLE
PDFDownloadLink downloads empty document

### ISSUE THREAD

**Issue by rasikalele** [diegomura/react-pdf#360]
Hello ,

I am using on the fly feature to dynamically download pdf. Data for this PDF is row html and and I am trying to wrap in inside <Document> of react-pdf. it gets displayed on browser but downloads empty pdf. 
[PdfData.txt](https://github.com/diegomura/react-pdf/files/2531423/PdfData.txt)
[TermsConditions.txt](https://github.com/diegomura/react-pdf/files/2531428/TermsConditions.txt)
TermsConditionJS:
///////////////////////////////////////////
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Button, ButtonIcon } from '@rmwc/button';
import { fetchToS } from '../actions';
import PageTitle from '../components/PageTitle';
import Markdown from '../components/Markdown';
import PdfData from '../components/PdfData.js';
import pdf from '../documents/obsidian-terms-of-service.pdf';
import ReactPDF, { PDFDownloadLink, Page, Text, Document } from '@react-pdf/renderer';
// import { Document } from '@react-pdf/dom';
// import { Document } from '@react-pdf/dom';

class TermsOfService extends Component {
  componentDidMount() {
    this.props.dispatch(fetchToS());
  }
  render() {  
  if(this.props.body){
    const getPdfData = (htmlContent) =>{
      return (  
        **<PdfData  content={htmlContent}/>**
              )   
        }
    return (  
    <div >
     { getPdfData(this.props.body) }  
     <PDFDownloadLink document={getPdfData(this.props.body)} fileName="somename.pdf">
      {({ blob, url, loading, error }) => (
        loading ? 'Loading document...' : 'Download now!'
      )}
     </PDFDownloadLink>
    </div>
    );
   }
  else{
     return(  <div>NO data</div> )
         }
    
  }
}
export default connect(state => state.signup.tos)(TermsOfService);

/////////////////////////////////
PdfFdata.Js:
import React from 'react';
import showdown from 'showdown';
import sanitizeHtml from 'sanitize-html';
import { classes } from './markdown-constants';
import { PDFDownloadLink, Page, Text, Document} from '@react-pdf/renderer';
// import { Document } from '@react-pdf/dom';

  const Pdfdata = ({ content, className = '' }) => {
           const html = {
           __html: sanitizeHtml(converter.makeHtml(content), santizeOptions)
           };
    return (  
     <Document>
      <Page>
          <Text className={`mdc-typography ${className}`}  dangerouslySetInnerHTML={html}>
         </Text> 
      </Page>
  </Document>
  );
};
export default Pdfdata;

**Comment by rasikalele** [comment]
code is here:
import React from 'react';
import showdown from 'showdown';
import sanitizeHtml from 'sanitize-html';
import { classes } from './markdown-constants';
import { PDFDownloadLink, Document, Page, Text} from '@react-pdf/renderer';

showdown.setOption('simplifiedAutoLink', true);
showdown.setOption('noHeaderId', true);
showdown.setOption('tables', true);

const converter = new showdown.Converter();
const santizeOptions = {
  allowedSchemes: ['https', 'mailto'],
  allowedTags: sanitizeHtml.defaults.allowedTags.concat([
    'h1',
    'h2',
    'img',
    'br'
  ]),
  allowedClasses: Object.keys(classes).reduce((collection, className) => ({
    ...collection,
    [className]: classes[className]
  })),
  transformTags: Object.keys(classes).reduce(
    (collection, className) => ({
      ...collection,
      [className]: sanitizeHtml.simpleTransform(
        className,
        { class: classes[className] },
        true
      )
    }),
    {}
  )
};

const Pdfdata = ({ content, className = '' }) => {
  const html = {
    __html: sanitizeHtml(converter.makeHtml(content), santizeOptions)
  };
console.log(html)
  return (
//  <Page> <Text className={`mdc-typography ${className}`} dangerouslySetInnerHTML={html}></Text></Page>
     
      <Page>
         <Text className={`mdc-typography ${className}`} dangerouslySetInnerHTML={html}> 
        
        </Text> 
      </Page>
      

  );
};

export default Pdfdata;
////////////////////////////////////////
Trying to render is here:
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Button, ButtonIcon } from '@rmwc/button';
import { fetchToS } from '../actions';
import PageTitle from '../components/PageTitle';
import Markdown from '../components/Markdown';
import PdfData from '../components/PdfData.js';
import pdf from '../documents/obsidian-terms-of-service.pdf';
import ReactPDF, { PDFDownloadLink, Page, Text , Document} from '@react-pdf/renderer';
// import { Document } from '@react-pdf/dom';

class TermsOfService extends Component {
  componentDidMount() {
    this.props.dispatch(fetchToS());
  }

  getPdfData = () =>{
    return (
      <Document title="Order">
      <PdfData  content={this.props.body}/>
      </Document>
    )
   
  }
  render() {
    return (
      <div className="flex items-center obi-mx-auto" style={{ flexDirection: 'column', maxWidth: '900px' }}>
        <PageTitle title={this.props.title} />
        { this.getPdfData() }
         <a href={pdf} target="_new" style={{ textDecoration: 'none' }}>
          <Button raised>
            <ButtonIcon icon="cloud_download" />
            Download
          </Button>
        </a>    
    <PDFDownloadLink document={ this.getPdfData()} fileName="somename.pdf"> Download..!! </PDFDownloadLink>  
      </div>
    );
  }
}

export default connect(state => state.signup.tos)(TermsOfService);

**Comment by diegomura** [comment]
Could you please style a bit the code? It's hard to tell even what you're doing

**Comment by rasikalele** [comment]
> Could you please style a bit the code? It's hard to tell even what you're doing

Sorry for that. I hope its much better now.

**Comment by rasikalele** [comment]
> Could you please style a bit the code? It's hard to tell even what you're doing

Sorry for that. I hope its better now/

**Comment by agarant** [comment]
@rasikalele It looks like the sanitization utils only accepts html tag (from the PdfData.txt). React-Pdf renders elements that are documented [here](https://react-pdf.org/components). Therefore  'h1', 'h2', 'img' and 'br' are unlikely to work.

Also, the snippet is using **dangerouslySetInnerHTML**.  I do not think that it is currently supported by react-pdf (@diegomura is there any plan to support it ?).

I was able to work around dangerouslySetInnerHTML by using [react-html-parser](https://github.com/wrakky/react-html-parser) to convert the html string into a React tree that uses react-pdf components.

**Comment by rasikalele** [comment]
@agarant : Thanks found a workaround like this
 const content = (
        <Document title="obsidian-terms-of-service">
          <Page wrap style={styles.page}>    
            <Text>Obsidian Security, Inc Trial Agreement</Text>     
            <Text
              style={styles.Text}
              render={({ pageNumber, totalPages }) => {              
                return `${ReactHtmlParser(this.props.body)}`; 
              }}
            />        
          </Page>
        </Document>
      );
Now everything works fine but it still does parser <br/> and br gets rendered as object. Any Idea how to proceed further.

**Comment by diegomura** [comment]
As @agarant said, you just cannot render html elements inside the PDF document. Only the ones documented. That applies also for `<br />`

About `dangerouslySetInnerHTML`, it's not on the roadmap, and I'm not even sure it should be a valid prop to react-pdf components. It makes more sense to stick with a clearer and small components API, and should not be this library responsibility to convert whatever type of data to PDF components. We are talking about html now, but there are other types people might need.

**Comment by nhemnt** [comment]
@rasikalele you can use like this.
 ` <Document>
      <Page style={styles.body}>
        <Text style={styles.title}>Terms Of Service</Text>
        {this.props.body.split(/(\r\n|\n|\r)/g).map(line => (<Text style={styles.text}>
          {line}
        </Text>)
        )}
        <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => (
          `${pageNumber} / ${totalPages}`
        )} fixed />
      </Page>
    </Document>`
