### ISSUE TITLE
PDFDownloadLink not working 

### ISSUE THREAD

**Issue by knowbody** [diegomura/react-pdf#370]
**OS:** MacOS Mojave 10.14

**React-pdf version:** 1.0.0-alpha.24

**Description:** 
I started a new project with the latest CRA, added the `@react-pdf/renderer` dependency and was trying to use the `<PDFDownloadLink />` component. It throws an error:
`react-pdf.browser.es.js:1719 Uncaught (in promise) TypeError: subpages[j].renderDynamicNodes is not a function`

here is the snippet that I have in my `index.js` of CRA:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import {
  PDFDownloadLink,
  Page,
  Text,
  View,
  Document
} from '@react-pdf/renderer';

const MyDoc = (
  <Document>
    <Page>
      <View>
        <Text>Section #1</Text>
      </View>
      <View>
        <Text>Section #2</Text>
      </View>
    </Page>
  </Document>
);

const App = () => (
  <div>
    <PDFDownloadLink document={MyDoc} fileName="somename.pdf">
      {({ blob, url, loading, error }) =>
        loading ? 'Loading document...' : 'Download now!'
      }
    </PDFDownloadLink>
  </div>
);

ReactDOM.render(<App />, document.getElementById('root'));
```

But to give you a reproduce the error I tried doing the same thing in codesandbox and it seems to work just fine there, so not really sure what the issue is. https://codesandbox.io/s/72qp2607o0

anything that I'm doing wrong?

**Comment by diegomura** [comment]
Hey @knowbody !
That's weird 😕 
I'll reproduce what you did in a blank CRA project and check it out. I _just_ published a new `1.0.0-alpha.25` version with some changes in page wrapping. It shouldn't be that though, but do yo mind trying it?

**Comment by knowbody** [comment]
it works

**Comment by knowbody** [comment]
so it must've been that 24 version. Thank you! I'll close the issue

**Comment by diegomura** [comment]
Oh, crazy. Glad it's fixed 😅

**Comment by knowbody** [comment]
Awesome progress with the library, since last time I played around with it, well done! Keep it up!

**Comment by Smartmikey** [comment]
Hey, I'm using version two of React-pdf, and <PDFDownloadLink> isn't displaying anything. I'm currently running on localhost
