### ISSUE TITLE
Percentage paddings on Page not wrapping

### ISSUE THREAD

**Issue by itzsaga** [diegomura/react-pdf#371]
**OS:** MacOS

**React-pdf version:** 1.0.0-alpha.25

**Description:** Document isn't paginating.

**How to replicate issue including code snippet (if applies):**
There's A LOT more text in the actual code. Just know that I kept the component tree structure the same. Most times there are multiple `Text` component children for a `View`.
```javascript
import React, { Component } from "react";
import {
  Document,
  Font,
  Image,
  Page,
  Text,
  StyleSheet,
  View
} from "@react-pdf/renderer";

Font.registerHyphenationCallback(words => words.map(word => [word]));

class ProposalPDF extends Component {
  render() {
    return (
      <Document>
        <Page size="LETTER" style={{ padding: "10rem" }}>
          <View>
            <View>
              <Image src={this.props.logoLarge} />
            </View>
            <View>
              <Text></Text>
            </View>
            <View>
              <Text></Text>
            </View>
          </View>
          <Text></Text>
          <Text></Text>
          <View wrap={false}>
            <Text></Text>
          </View>
          <View wrap={false}>
            <Text></Text>
            <View>
              <View>
                <Text></Text>
              </View>
              <View>
                <Text></Text>
              </View>
            </View>
          </View>
          <View>
            <Text></Text>
          </View>
        </Page>
      </Document>
    );
  }
}

export default ProposalPDF;
```

**Comment by itzsaga** [comment]
So got this working in the REPL and was able to add/remove things. Turns out when I remove the `style={{ padding: "10rem" }}` from the `Page` component it works.

**Comment by itzsaga** [comment]
More testing. I just saw the Valid Units section of https://react-pdf.org/styling which I think is new. This is broken when using `%` but all other options work.

**Comment by diegomura** [comment]
Thanks for reporting it @itzsaga . I changed the issue name to be more descriptive, if you don't mind. I'll check it out soon!

**Comment by itzsaga** [comment]
@diegomura that's perfect. I had thought about closing and opening a new issue but just changing the name is a better option haha.
