### ISSUE TITLE
Dynamic Page Breaking

### ISSUE THREAD

**Issue by baileysingleton** [diegomura/react-pdf#373]
**OS: Ubuntu**

**React-pdf version: alpha 17**

**Description: Page Breaking When content won't fit**

**How to replicate issue including code snippet (if applies):**

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

Not sure if this is implemented, but I am working with tables that are dynamically generated as flex boxes. I am running into the issue of boxes displaying with no content because they fit, but the text does not. This creates a small rectangle of white space that doesn't show anything useful. screenshot ![Here](https://user-images.githubusercontent.com/26613813/48284595-ae53b380-e414-11e8-842f-567e4d6d8b14.png)

Not sure if this is a possible request, or maybe this is something I could fix on my end, but it is very bothersome. Can include code if wanted.

Thanks,
Bailey

**Comment by diegomura** [comment]
Try setting `wrap=false` to the table cells. Otherwise I'm not sure if there's something I can do. Wrapping is actually working as expected there, but I understand that in your case it creates an empty box on the first page
