### ISSUE TITLE
Conditional rendering on page breaks?

### ISSUE THREAD

**Issue by polarathene** [diegomura/react-pdf#382]
If I have a section header/title element followed by a list of elements flowing onto a 2nd page or more, how can that section header be repeated on the successive pages that content is broken off on to?

This is something I do not have control over with rendering HTML to PDF. Is this a feature that `react-pdf` could provide? My understanding is it enables extending upon what browsers pdf printing offers to add additional processing logic for the conversion.

**Comment by diegomura** [comment]
With the ‘fixed’ prop to the section/header
