### ISSUE TITLE
Tiny PDF

### ISSUE THREAD

**Issue by AirborneEagle** [diegomura/react-pdf#388]
_I wanted to add the "help wanted" tag but I was unable_
**OS:**
web 
**React-pdf version:**
^1.0.0-alpha.25

**Description:**
when I try to view a PDF, it shows a really tiny view of it. 
I need to then zoom up in order to actually look at it.
I have looked for some scaling or zoom property, but I have not found it.

Initial View on page load:
![image](https://user-images.githubusercontent.com/13696163/49047819-e4739000-f195-11e8-9e47-bf10ef585daf.png)

after I zoom up I can see the document:
![image](https://user-images.githubusercontent.com/13696163/49047876-0e2cb700-f196-11e8-9574-34ac8d632d8a.png)

**How to replicate issue including code snippet (if applies):**

```
const styles = StyleSheet.create({
    page: {
        width: '15cm',
        flexDirection: 'row',
        backgroundColor: '#E4E4E4'
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1
    }
});
// Create Document Component
export const MyDocument = () => (
    <Document file="REACtPDF.pdf"
        author="Power Innovations Sales Person"
        title="Sales Quote"
    >
        <Page size="A4" style={styles.page}>
            <View style={styles.section}>
                <Text>Section #1</Text>
            </View>
            <View style={styles.section}>
                <Text>Section #2</Text>
            </View>
        </Page>
    </Document>
);
```
```

                            <PDFViewer className={classes.salesQuoteReviewContainer}>
                                <MyDocument/>
                            </PDFViewer>
```
```

    salesQuoteReviewContainer: {
        overflowY: "scroll",
        width: "22cm",
        height: "15cm",
        padding: theme.spacing.unit * 2
    }
```

Any advice would be great.

**Comment by diegomura** [comment]
Hey!
Never saw something like this 🧐
What React-pdf does is just creating an iframe but the document gets rendered by the browser itself. That’s why I truly don’t think this is a React-pdf issue, but more of something wrong on your end. Do you see that happening in more than one browser?

**Comment by AirborneEagle** [comment]
okay.  Here is a little update.
The PDFViewer is on the third /last step of a react stepper. (
If I let the page load fully as normal, then click on step three, I will see the page as above.

But, If I hurry and click on step 3 before the PDF finishes loading/rendering, then it will appear correctly.
weird.

The Issue does not happen in Edge.
Also, the width style was removed. and nothing changed.
So I guess it is a Chrome issue?

**Comment by diegomura** [comment]
Based on what you explained I would say is more of an issue about the react stepper and the iframe. 

My best guess would be that the document get's rendered when the "step 3" is not visible (making it very small) and then when you get to that step the iframe get's bigger, making the iframe visible but the page small. That would also explain why if you hurry to step 3 this does not happen (the document is still loading?). Couldn't say exactly though.

I'm closing this now since issues are reserve for react-pdf specific issues, and this is clearly about your end. However, feel free to keep posting updates here and I'll try to help as much as I can
