### ISSUE TITLE
<DOCUMENT /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.

### ISSUE THREAD

**Issue by FrimJo** [diegomura/react-pdf#390]
**OS:**
macOS Mojave Version 10.14.1

**React-pdf version:**
1.0.0-alpha.25
React 16.6.3

**Related**
#239 

**Description:**
I'm trying to render a `<Document>` using `@react-pdf/renderer`, but get the error `<DOCUMENT /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.`

**How to replicate issue including code snippet (if applies):**
`npx create-react-app pdf-app`
`cd pdf-app`
`yarn install @react-pdf/renderer`
`import { Document } from '@react-pdf/renderer'`
add `<Document />` to App component
`yarn start`

**Other**
Downgrading to `React 16.4.1` fixes the problem.

**Comment by diegomura** [comment]
I was just checking, and this is happening when you are forgetting to wrap a document in a [PDFViewer](https://react-pdf.org/components#pdfviewer), [PDFDownloadLink](https://react-pdf.org/components#pdfdownloadlink) or [BlobProvider](https://react-pdf.org/components#blobprovider), so the elements are rendered by `react-dom`, causing that warning. This is now mandatory for web environments. 
Will try to add a warning message, but not sure if it's possible.

**Comment by JIACHENG135** [comment]
I met this issue too. The solution to solve this error is very easy. By the way I'm using TypeScript with this tool. Please also import PDFViewer from @react-pdf/renderer and wrap <Document><Document/> into the <PDFViewer></PDFViewer> tag. Hope this post can help someone in the future. 

```
import { PDFViewer, Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer'

...
    return (
      <div style={{ position: 'relative', height: '100%' }}>
        <div>
          <PDFViewer>
            <Document>
              <Page />
            </Document>
          </PDFViewer>
          <p>Page</p>
        </div>
      </div>
    )


...

```

**Comment by merwhite11** [comment]
Hello, I am following the suggestions from above to wrap the Document in PDFViewer, but when I do this, the PDF does not load. If I do not wrap the Document in PDFViewer and `import {Document, Page} from "react-pdf";` the PDF loads normally with no error. 

This is the skeleton I am trying. No error in the browser, but PDF does not load: 

```
import { PDFViewer, Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer'
...
<div style={{ position: 'relative', height: '100%' }}>
      <div>
        <PDFViewer>

          <Document
            file={doc}
            onLoadSuccess={onDocumentLoadSuccess}
          >
            <Page/>
          </Document>
        </PDFViewer>

      </div>
   </div>
...
```
