### ISSUE TITLE
How to handle fixed elements starting on a certain page (skipping the first page)

### ISSUE THREAD

**Issue by ishraqiyun77** [diegomura/react-pdf#393]
**OS:**
Windows 10 w/ WSL (Ubuntu 18.04)

**React-pdf version:**
`.alpha.25`

**Description:**
Just curious how others might be handling this. I want some fixed elements to start on the second page. For example, some of my reports have really long descriptions that take up a whole page. I want the fixed elements to start on the second page and be on every subsequent page.

I started with something like this: 
```
<View break={queryData[0].SurveyDataView !== 'By Position' ? true : false} />

<Text style={styles.sectionHeading} fixed={true}>
    TOTAL DIRECT COMPENSATION - &nbsp;
        {
        hourly ? '(In Hourly Rates)' : '(In Thousands)'
    }
</Text>
```
But that causes it to still show up on the first page despite the `break`.

**Comment by diegomura** [comment]
Check [dynamic rendering](https://react-pdf.org/advanced#dynamic-content) on the docs. I think it’s exactly what you need
