### ISSUE TITLE
Iteration of Dynamic Data Arrays

### ISSUE THREAD

**Issue by AirborneEagle** [diegomura/react-pdf#396]
I am trying to iterate of an array of data to generate my PDF.

I have been able to make everything work, except for when the Array is dynamic.
When the array is hard coded, it will work just fine. but things break when the array comes from props that change after the component has mounted.
It will break with the error : 
```
TypeError
insertBefore is not a function
```

This sandbox kinda shows what I am trying to do.
https://codesandbox.io/s/my3mlmwjv8

My app is using props from redux instead of state.

Thank you for any help.

**Comment by diegomura** [comment]
Thanks. Related to #351 . I'll check it out soon

**Comment by AirborneEagle** [comment]
@diegomura 
 My project is on hold until this issue is resolved.
Is there anyway I can help?
