### ISSUE TITLE
Borders not rendered when moving from 18 to 25

### ISSUE THREAD

**Issue by baileysingleton** [diegomura/react-pdf#401]
**OS:**

**React-pdf version:** 25

**Description:** Going from version 18 to 25 results in odd behavior. 
All borders are lost. In addition, head tags move places on different pages.
Can be seen by the "...Grade 3 informational writing" text shifting to the right and interfering with the logo on page 2.

**How to replicate issue including code snippet (if applies):**
can be provided, but is large.

![version-18](https://user-images.githubusercontent.com/26613813/49309230-69f58980-f48f-11e8-86b3-1e1766419c6b.png)

![version-25](https://user-images.githubusercontent.com/26613813/49309238-6f52d400-f48f-11e8-8dca-5d1ed6410a44.png)

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Comment by diegomura** [comment]
I think this might be because `px` are no longer supported as units (check [valid units](https://react-pdf.org/styling#valid-units)). Please check if you're not defining borders with `px`. If you do, change it to `pt`. Sorry for the inconvenience
