### ISSUE TITLE
textTransform: capitalize does not work

### ISSUE THREAD

**Issue by lukepighetti** [diegomura/react-pdf#404]
I noticed that `textTransform: uppercase` works but `textTransform: capitalize` does not work. Not sure if this is a regression or just not implemented, but wanted to report it. Thanks!

**Comment by diegomura** [comment]
Weird. It [should be working](https://github.com/diegomura/react-pdf/blob/master/src/utils/attributedString.js#L16). I'll take a look. Thanks!

**Comment by diegomura** [comment]
It is working. Check [this example](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231ca848a18f54bc3c6400add16255844f18016479860002c78a801e975f434b4837805c382e8199959d80801b8c8c800c5c0a164009c30f891a03072f03801c8fca0a0001c2000b8828200ccb2e4f9a0782d81654118822082402001dc7844948200dc0118019882013401f5b401a400d400d840003801d44127e401549567189600340138780104ef64aa9aca00683824609a7918904484ea3032801e446632519460aa778a4d2a0480184c321c0c000ca488c2a2fc180c36580794e860f0120e228548092669aa3c2512890603e36840d5406cc00acef2a4d2e90c8010ba0a02046203361c8e251a9b4fa5f00012201c920005e5931ab2c594684702c560c053c55f2caa295ba9800098002c9cce261f47711120f86040595802c4c0e4defa96ab1d23f3f80281a0d1b8d3d9a1b541b4391f0405a3961503803c6aa58c6c6b287135aa58590004a181e300a05c1a3a5722c57094a888543386041622c28000)

I know you have been using the styled-components plugin. [It's also working there](https://react-pdf.org/repl?code=3187b0760ce02e0040ea027021801c505304c0bc36813c01b7401300e8005240737400300a06012052449204b31a8168a10280170c00cc01580371318b2d876e7c01188280202d88806c5265cf65c7af001620127005ee0a124222274c60d4245800553946238f1422a4c8ddd0003ca1199800cdad78212dd04400980059a56564a042a1796d39a8c04581d0c0321152d2a38b782291d53909f04401e42001dd6c48cbd332dd9120a211346181513c722dd11c199dc1a0600114015d398355d07c002801287000f861d66400780044418017d48aa076f4610f115030106ed2d30e3cbdd07649c1e69600ad5630121ad084818001649060603189087003d07d882f378221e684c2a311a773a5d8a374db481800316b19010e86a271a09803ac800e4c6350a02042044222a5008191a8d02414138c032281d4088802240ad76822006e004651022009a007d37001a4006a5a1000038e0205952800aa24513a955000d00271200082f6b21a8220c800d0c800de306aad5ea2206734da841203260005f0f512a60c0012ba090c0280518e248a514410875a1d16cb2042276d1a0000)

Closing this, but if you have a way I can replicate what you saw I'll be happy to re-open it

**Comment by diegomura** [comment]
My bad! It's only working for the first word. Dumb me! Working on this now

**Comment by lukepighetti** [comment]
Dang! this would have been a good first issue for me. Thanks for fixing it so quickly! :)

**Comment by diegomura** [comment]
Oh sorry!!
I was working in other issues ad I just went for this one very quickly 😅
Let me know in what you would like to work and I’ll be happy to assist you!

**Comment by analista3** [comment]
El texttransform en capitalize no esta funcionando como hago para ponerlo a funcionar?

**Comment by samura** [comment]
I noticed this still has some bugs. If the input is ALL CAPS. It does not work. If I use `.toLowerCase()` It Works As Expected.
