### ISSUE TITLE
Any document rendered in browser with iframe (from BlobProvider or PDFViewer) is empty

### ISSUE THREAD

**Issue by nicmosc** [diegomura/react-pdf#407]
**OS:**  Mac OS 10.41.1

**React-pdf version:** 1.0.0-alpha.25

**Description:** None of the generated iFrames are filled with the output. This happens both in the render process in an Electron app (should be the same as a web environment), and on codesandbox with the same behaviour (can be seen in sandbox, url below).

When generating a download link the resulting PDF is generated correctly, but in the case of iFrames they seem to be empty:
![image](https://user-images.githubusercontent.com/16778318/49329933-3138db80-f587-11e8-9c93-9ff0844e36ff.png)

Codesandbox example: https://codesandbox.io/s/nk6k26x2rj

This is an issue since I imagine that if we want to do something like in the REPL where you can edit the pdf on the fly you need to show it in an iFrame, in order to maintain the aspect ratio, layout etc which should be fixed to the PDF, and not to the viewport. Rendering the `<Document />` component in the virtual react DOM works in fact, but I'm not sure how to keep the generated content "independent" from the parent (e.g. fonts are inherited from the global css of the app, which is not something I want, etc.).

**NOTE**: just saw that this issue https://github.com/diegomura/react-pdf/issues/390 mentions that you have to wrap the `<Document />` in another component that will render it properly, so what I described just above isn't an option anyway 😅

Thanks!

**Comment by diegomura** [comment]
Hey!
Very weird. I can see the issue on codesandbox, but not in localhost (or in a deployed app of my own). I try opening the iframe blob url from the example and it the document get's rendered. Could you also replicate this on localhost?

**Comment by nicmosc** [comment]
Well, I'm currently working on a project to render PDFs but in an electron app. So technically I'm running the app locally but not in the default browser, but in the electron chromium browser. It could be due to the blob urls as you say. For example in my electron project, when I pass the url to the viewer I'm also prompted with the native "save as" dialog for the generated url. If i save the file on my file system i can see it's correctly generated, but the viewer does nothing.

I can try to set up another project to try this out on localhost (as a basic web app) to see if it happens as well. Note that I've also tried most older versions of `react-pdf` on codesandbox so it's not something due to an update in the latest version, since the bug still happens regardless of the version.

I'm not sure if this library https://github.com/wojtekmaj/react-pdf shares any similarities with yours in regards to how pdfs are rendered, but I managed to combine the `blob` output of `BlobProvider` with their `<Document file={blob}>` component and the pdf is rendered properly, so the blob is OK.

**Comment by diegomura** [comment]
I bet is that. I never tested this library on electron. If you can provide a small project I can run I would be happy to do it and try to figure out what's going on.

I think https://github.com/wojtekmaj/react-pdf can work for you. The viewer build inside this library it's just a iframe that displays the blob, but this other library uses `pdfjs` and enables you to customize way more how the PDF looks (it's actually what I used to build the REPL). You can take a look on how it's done [here](https://github.com/react-pdf/site). I think it may work for you also

**Comment by nicmosc** [comment]
Oh nice! I was actually looking for the REPL source 😉 yeah ofc I’ll try to stitch up something quickly, but will be tomorrow. I’ll tag you when it’s done.

I’ll continue using the other `react-pdf` library for now then, it seems that it fits my use case quite well atm.

Thanks!

**Comment by diegomura** [comment]
Awesome! Glad it does 😄 
I'm continuously trying to push it forward. Not always easy, but I'm happy with the progress so far

**Comment by nicmosc** [comment]
@diegomura here's the test repo, included a readme on how to get it started. Took exactly the same example as on codesandbox. The issue is there so it's good to be checked out 😉

Let me know what you find

**Comment by CollinsLord** [comment]
Hi I have little problem with expanding the width of the Document. I Try <Document width={{width:'100px'}} and also with the style object still.

**Comment by diegomura** [comment]
@CollinsLord I think that's unrelated with this issue. `Document` does not support a `width` prop. Please check the [Page components docs](https://react-pdf.org/components#page) for that

**Comment by Skywalker13** [comment]
Hey, https://codesandbox.io/s/nk6k26x2rj works with Firefox but not with Chromium..

Firefox :  
![image](https://user-images.githubusercontent.com/397862/49652399-4358c500-fa32-11e8-93bd-ef1c56931f93.png)

Chromium :  
![image](https://user-images.githubusercontent.com/397862/49652449-5cfa0c80-fa32-11e8-91e8-781e8449e442.png)

**Comment by diegomura** [comment]
Weird. However, on a normal web project this works no matter if it's running on Firefox or Chromium. I'm not sure but this might be an issue of how the lib works inside codesandbox

**Comment by diegomura** [comment]
This lib reported several issues running on codesandbox (unfortunately), and I think this might be it. I'm closing this, unless until I'm proved wrong to be it 😄
