### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by mmichelli** [diegomura/react-pdf#413]
The example does not work on IE 11
https://react-pdf.org/repl

**Comment by DuncanMacWeb** [comment]
We also found that rendering doesn’t work on IE11 (just... nothing happens), so we’re planning to server-render for IE... would be great to get this working there (also Edge).

**Comment by devurc** [comment]
Curious if anyone had explored this issue more deeply and would have some context about the fix before I go off into the deep end of IE11 issues. This issue is currently blocking my team's adoption of this framework.

**Comment by chrisphillers** [comment]
I am having the same issue, purely from installing the dependency - my entire site will not load in ie11 and get this error:

HTML1300: Navigation occurred.
192.168.1.6
SCRIPT1002: Syntax error
frontend.a90df18c.js (212397,1)

**Comment by davidmcnamee** [comment]
I think the IE11 problem stems from the "dfa" package. Correct me if I'm wrong (I'm kind of new to this), but I took a look at the Syntax Error and it pointed me here:

![image](https://user-images.githubusercontent.com/16356719/76644546-8d7dff80-652d-11ea-9ea4-3b3cd6d9834b.png)

This ["dfa"](https://www.npmjs.com/package/dfa) package looks like it's not IE11 compatible, by the way it uses `class` syntax. 

And after looking through my package-lock.json, it's a dependency of `@react-pdf/fontkit` which is a dependency of `@react-pdf/renderer`. 

I've been looking into potential solutions for transpiling the module with the same babel configuring that I use for my frontend, but they all seem to say the same thing: ["this is not meant to be an any-package IE11-compatible maker"](https://www.npmjs.com/package/next-transpile-modules)

**Comment by devurc** [comment]
Yep, that's right. Coming back to this now a few months later, we were able to resolve it by transpiling it to ES5 syntax. I'd recommend just trying and seeing if it works for you.

**Comment by rajlaxmiSetty** [comment]
@devurc please explain how to resolve this
I am also facing same issue

**Comment by Sustenance** [comment]
Looks like this was introduced in `dfa@1.2.0`. foliojs/dfa#4 is supposed to fix it, but hasn't been merged yet. In the interim, there is a [temporary solution in that PR](https://github.com/foliojs/dfa/pull/4#issuecomment-562647796) which is to pin `dfa` to version `1.1.0` using `resolutions` in your `package.json` and [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) to keep your `package-lock.json` patched correctly.

**Comment by diegomura** [comment]
Should be fixed. Also Microsoft will end Internet Explorer 11 support on August 17, 2021 so there's no point on doing any effort on downgrading stuff to add IE support
