### ISSUE TITLE
Custom characters rendering

### ISSUE THREAD

**Issue by przemokon** [diegomura/react-pdf#414]
**OS:**
Windows 10

**React-pdf version:**
1.0.0-alpha.25

**Description:**
Hi, thanks for such great lib!
I try to use it with polish characters [for example ąśćź] which don't render properly, is there something i can do to make them working as i want? On my local installation i tried with custom registered font (Ubuntu) which support that characters, but this didn't help.

Below, a demo in REPL.

[Demo](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3a0504040da8081c101017a0072695003d2ebebba5286f00bba85d03332b3b01003719190018b8142cad861f12341d9e07003939941400038400170848638e5c9f340f1412302ca8230844084804003b8f089288401b80230033084026803eb68034801a801b080007003a8824fc802a92ace312c00680270f00209dec956399400d0704938f231208909d4c0ca00791198c9465182a9de690ca812006130c870300032a223028cb06172c07c874307809071142a0051334d56b12890603e36840d5006cc00acef0a552697c0010ba0a0204600336aca08c1294a6a6d20012205b120005e39319338594284713a503119245cd560a3e5180040098002c6cce261f47711120f86000595802c4c2d8de3a9ca65bebf7fa0241a371994386aca0f01050730cbb59a5d541f572c34c1a646f36512d506b6dbed80a76b0ec6ecd23078b64298079557e4024d0006737066010043c8355a983933831b8c27a63b14cc10bc59a40293bd98e7a7e7f075fac181d579ad351ce3f64b43e4fbaf506a1d9a45698cdda1d002b04340908e213e7db1eaf44f01da2433020005a0012bf2786019e43cd77fe026db9425cd2eb1d89d3004aa262aa2e45896d2aca0aab06074c558d641b9a963587602e940761ba26ab816504d2659f2028c046b219a0ee369eed9b3a79af6a008891a027c3e467ad6e6a5202000724c3c8186b622b54431209d3800e8f0f20402008861860e7961392762baf68a396246cce467062238500029a650b29f0951e9bda519983a398baf24c00c531650b1181b128590aa0c26413e563005017034264790b0362d878150882a0e816021310309000)

**Comment by diegomura** [comment]
You need to provide a font that supports those chars. By default, the `Helvetica` font embebed in the PDF doesn't support it. Are you sure the `.ttf` file you provided includes these chars?

I tried with one that have them and worked well:

<img width="1351" alt="screen shot 2018-12-14 at 12 46 07 am" src="https://user-images.githubusercontent.com/5600341/49982213-365c3a00-ff3a-11e8-9185-2eb076031762.png">

Closing this until further details.
