### ISSUE TITLE
Ability to get the rendered position of a view

### ISSUE THREAD

**Issue by KevinGutowski** [diegomura/react-pdf#415]
Currently, I have to pass off the exact coordinates of the rendered elements in my PDF to another team member and it would be great to have this data generated automatically for me. Is there a way to get the rendered position of a View or a Text object (could be in pts, in, etc)?

Right now, I have to compute these things manually by opening them up in Illustrator and getting the dimensions/positions of the objects.

**Comment by diegomura** [comment]
There isn't a way right now. 

Your use case seems to be very specific, but it may me handy to have some layout data exported anyways for debugging purposes.

This is the only thing I currently have in mind, that makes use of the `onRender` prop we already have:

```jsx
<Document onRender={({ layoutData }) => console.log(layoutData)}>
  <Page>
    <Text>Hey</Text>
  </Page>
</Document>
```

`layoutData` being:

```js
{
  type: 'Document',
  children: [
    {
      type: 'Page',
      x: 0,
      y: 0,
      width: 400,
      height: 600,
      style: { ... },
      children: [
        {
          type: 'Page',
          x: 0,
          y: 0,
          width: 140,
          height: 30,
          style: { ... },
          children: ['Hey']
        }
      ]
    }
  ]
}
```

What do you think? Implementing this would be pretty simple

**Comment by KevinGutowski** [comment]
Yes! That would be exactly what I am looking for! This layoutData object would save me a tooooon of work. Particularly if I need to tweak the layout in the future.

**Comment by diegomura** [comment]
Awesome. I’ll merge it today. Glad it works for you

**Comment by KevinGutowski** [comment]
Any chance you would be able to merge it in soon? I'm hoping to wrap up my project somewhat soon. I appreciate you adding this in so quickly!

**Comment by diegomura** [comment]
Yes. My bad. I went out of town these past days. Going to review it today and merge it

**Comment by KevinGutowski** [comment]
Quick question, where does `console.log(layoutData)` get logged? I've checked my browser console and tried to see the npm logs but no luck. When I try to trigger an `alert()` it works alright.

**Comment by diegomura** [comment]
<img width="1920" alt="screen shot 2018-12-19 at 7 33 10 pm" src="https://user-images.githubusercontent.com/5600341/50252185-f2978380-03c4-11e9-9f40-e02d8d3cd0cd.png">

It does. You cannot see it in the console?

**Comment by KevinGutowski** [comment]
Thanks for checking. Not sure what was going on (closed out chrome and it works again). Definitely an issue on my end.
