### ISSUE TITLE
Flex-Basis breaks on wrap

### ISSUE THREAD

**Issue by AirborneEagle** [diegomura/react-pdf#416]
**React-pdf version:**
1.0.0
**Description:**
flex and flex-basis totally crash when they are in a component that page wraps.
When wrap=true,  .When it wraps, the first part of the View contents get compressed together. as seen in this picture. (the portion of the component on the next page is ok and looks fine)

![image](https://user-images.githubusercontent.com/13696163/49662215-6ff7e700-fa08-11e8-8959-38a2d018b964.png)
this css breaks:
```
tabelHeader: {
        flex: 1,
        margin: 4,
        flexDirection: "row",
},
column: {
        order: 1,
        flexBasis: "20%",
}
```

but this CSS works fine with page wrapping:

```
tabelHeader: {
        //flex: 1,
        margin: 4,
        flexDirection: "row",
},
column: {
        order: 1,
        //flexBasis: "20%",
       width: "20%",
}
```

NOTE:  both styles work fine when the component does not have to page wrap.

**Comment by diegomura** [comment]
Thanks! Could you provide also the jsx so I can test it?

**Comment by AirborneEagle** [comment]
here is a working/breaking sandbox;
https://codesandbox.io/s/m45jv5wrr9

**Comment by alampros** [comment]
It looks like this was introduced in `v1.5.3` (possibly by #568?). Rolling back to `v1.5.0` works for me.

**Comment by Plonq** [comment]
Also seeing this in v1.5.6, but rolling back to v1.5.0 didn't fix it.

[Here's a REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a00d490600ee31f40271e001c36698012075ec3d3c54a8a231c8066625002510fbd471596ae818c12863c821f0c23a4848c27860a00108f04120400170c00390023002b00290e4c2a8050652d800a925b00189231b415003d2d4a1b20655b487ea5a5751f5844544c4b989c4257b65e5945654d5d710032862818129b475760e52f7d80cf70f864746c44bc624a5a46767e71697951e692e7713540059356fb72f75040e06179695a7d107ed861747078bcbe7f04382f61199dc6ae29be8904a2827dee8512bcd116f069345a7f77802ac40fea53347650a9cc6172b8cc607367ad26c541daadd6e05f8f339fb3061c854364633ce13273c531d8dc6e5f14f05905891f6fb1805ff3db5045c0ce75241dcba9a326971823078c63e120c0d510198f10006462319588802898060086f488a256918c0443c180016478606027c78001a20c30842018180408c79318b0a9980011d90186332678a04d55b98f1eccc7398c0434793503d230ccc9bcd60006e4836c016f43be9837c943c111f193e160c80204190d80005ea1960c0d20d911890bf19e20fad3c4e6461b7c041c66085e0177bd9e62f2684303e10e473012e669420632c860005530286402bd0d8f6fc9c600043c9cdb62d4356d39600ad3000b101e308087330906000067bf4d20b58094de84f8dc78c940403011027180af56c335dc48e232708100f903709d634e4c456030000ac30ea2600ec0b1822075d87000bfbd3308734d6d51cb01e000478dcb10414c71d2727d185b4477e320f00202607b743272813349d44e313065304041fb62cf44d87857c3d1108f370a04927f7bdc0601fd5d2621e0934e4c736c88ab53078ca0910e7333b8a23fd27c606334310d27770f4680308d8620408cddc104f048b1d88eac32460e0a52c21ec229600cc10304b53f188b04f9c0531e8b73bd6d32295d9f240a700380ce492d4d5f5a8c01ec6005cdaa82109f56a9e12d5cd08d8ad21e19abca48860ad0ab0f2bd7d50c20100335b5b74195b6c3833106f66be292202db582d22a68b44019d24fbc66e6ceeb304339de363ad22ed39161d21fd9aa228f7a14f3728a9819ccb59a90d62e503702d6c981ea6303225be2f9d072508330108e810b4e4077fc5a92b805b4180db1769318d1b14b1d4026cbc240d0c73c9c3c203e413682f0ffac0362106728342c09900006e6bd4c6f52d2518c00c9f630ee99a903bcf2d0ca0b9d5f440f44cdbd709c9c5620c193061be7073768cc5834d2da0db58e30718193440dc0dd433c18e85c9ce4c632bd6f6dafca41dc02c5876746bf4489e105e7cdc39ab0709a02c026e4cdc600d1f9058021d75f58ee6d8c4d3f98c0a00523080a45aed54990ea91838b0e4df090df9b39d3a66d0cedc8c78096cc58346e80404e49026d9f2814366d4045c537c60ce4d29d61c5981e894b63b0f8350d3f6314c72759a50004b873b326e10e1d0eca8fb3317d216d5c8b4b251296d9b52a4765349c185644c13a154ac0f5f8d8bf1fc30425a0b37d79a4e5041ed47cc841abf62c4ff9e3171530ce52707b14af45393d0240139933bb60152c4a9013320e4648802204dd0705d60c1800b30624019972a270c62b80b1957ce50d772861e049537b7a2bcfb97b900ac0df83b1281422f5d2106672314cfacf51a0e5d8816726e4d24b317563c0be92b3ec70c372a93001900c9592dee652cb931608382595e0617c18468661e523b4a41052e83d23633baf1c780366cc9ed7852f00a9b05985a5ac319270c61823782283602cf4c302724e6e994c011530f18e2843330a61158886a122db9bd1061c60cab2f63a6200b298c5c100bb29d0c06d8508ee74a222ac72855a07967919040314633a7456e103a840229639c44916d1601f72a649c621393197585e5ac7cf6b210d9317163a8cccfaed691090668609464459092048ccf456120110a053228ce7cf93d58863464e2c71b564913936a2e56c3f9270dd3465195da4e5304f4f8ba521069160644c186324f24620c5dd8c025229783ef03498ae6231b8f0298ac783dcb81180f31e81a19388424120a184c70b8f705d98a93e4d8580170d668c1858ca994b240de704054e4819cb64386ef3f4528988b685977a1fa168baa72aae319800603fe2c21c8d52463ca8f0a8d662c1cf2b64154c48ebcd34a7cb982c7362cf4e19b649e8a483b1822ada5e25dd61ee989036f6f46b5362cc8c03d90e60c2e2438107de3d0733e6bf96d5bf93b2da68138c9427acfccc158a9304a3dd2a83ca89581dc10f40ec85233c62bc24405692e0e82a15afe106cc1333935521545b3cd0cdeb0b00864e45aa9ca293e052dc226b5bee497603f134d09a51c837e5003fa68000c2e00434612bcd13d8aee18eef3c00c71054a04688366c36ca0964d5cc9c1c80b4d9c553160c78e014441d134858173ad7631058129c69189cd58298592a0a6388343d0d89f1f093a4ddf2a0c0425050d76895e9382ab189d666c7944048600104d1b40142980643c15e56e16b032ab423d20cc414277b2a145100af8001cb27641a186b15e790d32d2b06dc2e7230b1d2253019206cc8c190c22c2a5d951337509ec0938e6372c003df801d66a39d9f24b48cf1c2d0f052d245f27d5040586dc0b03b1b138ab667081c4725a6a862c12848311653c8d5d4e5994d8c1bd061926fe654791ae2d1a0a8c5755648c84eeddcd2af4c5c219e8b0356a16523b39045f731714ec0cb62ed7a4e9e9dae1b5ce60934ff122d0c0755cfc83108b9bc517435578c9404c8a867c871689207a3033d6868187cffa4b4fbb37185fea567629e829cf150ba29466458571fd7bd9bb0b3304c0453d21eb6696c38736d71c5028c545c5c7d90f87ed2608640ea0a9e9392d126432774361b8840244bba4065639b273ef42da871cfd1296834101b6002fe2d231682d9381661710e5b2fac39060113aa7fa1bc8acb0492c520d4625c77a042dcb46e03c4f8f98c05d97c0000fcb039c99c62180c4e081008395692351c4017621c75cf64e2abc044066f06e113900049019219303af2fc3007f4cb2ec1140038a4710c12d2d30dde34dc90f216fcc05e32adb692e4bf51551984542e12f19e05e6bf4c19b32ceac2a1c2f5a77770e9eb3143eee3aa22fdaa670de43e1a8ef56698e2b1878ce2a88f1390ccf9e31e19aacf4f1c6e02741989c2010cf478c11b4a826c468619736981183b0d8beb3842d452bd225b1d771a57e84ceeac1b33608b0935d526475630acccaf549d7db225f00f0e457b890e0aa23465ddaa63b66601ce1bcb21ab60a4047a86920247e0db5c136ba8adb3817a472bb5fd270f8cbbcab8cad3074b84758a166342c9886009170f24bc2d9bb16bd13d29c95334618e62084318e7a1e4ad32773567317495057a121496199f50d97fa0fddbf415654517a3d4733e5528acaf28b98b56b0055730b9cd509a9e0e3438558ac5216e820766cc23c0b3d7659f3a146be000322c450a731859c33b82b0894ac9a59a22a1107512f1880f607d9711a4ba2bae0949060872b0b66a348851dbb028ee94616cb7f3d130f03cb6f9041e2812b7f1e1b40b7f2662a284408b3ae1152193c6239806b0f119afa8401c52993f720f3a42859e112b05e8005111c716011043d0c502e1c33318da27e33b87b2292973632723889b0a05a612a2ad5005940706aed2c920e23c980378828a7c8099d192f1c52721d7a5612d08d3a01dd8e8a753a1961075b0f32f3a6afa13e167ae78e79d6a7413f2480bf3693c80361401882a83cf2660f000035a221b6b981761173110c02a3aa3b6433b1433c0ac98f99a30668ed10e34092f25c859184b6394093d348bf700c8b0038b261d037a1db3a00e99d20d691a2a3a5a008144b4a204636ac80c84602a8144b18300360000112b40a50363002b43f44402b42a2baaa60000132c819800ca8c6522b411a217b74738317abf297a2200004bac004824aff1769192663187a09f10562e68641163ee15a26e2613e92361bd08f10e9e720c27b10710b15c8031cdacf3ae324a1720125a98599b32470043a9739601d78cd8211b1a1111331618eb7a07865ab54b0f2962ce0730601f03091d3102bda8bd8763f1bcd1224631f91b82268ab9af81623a87b312a661ce032435a0ea98700806abc6fb2442ed220aa260c3303aa8a4b3886013590a7ff03604008060a8be0c000026b149760819eb2062529492c50162ed34d0b5a7e2d27548dd11dab30f6ada12f27e2faaf7b7132510a94d3a18c93b73ae2b13e0a95377b0a7c1a292fa06aaad10e0290609ba5f99060001489b86f9571963088f48230d106522e1ea8fc944909af885b2660c02f839327e2b139c5390ed05925a29d92ba4f3ab20520e2ab8c494aba50ee26e0de3305a63089b534e1ce3bd0718f9a110992860804883f99601f603e20b8f5a58a9dabd1f720c1a50bda6c01380f179ab1148afb0882282160547f92509a50300425b87ca5ecb7aa593c81c072e8312c533cb93121116354a4402e3c70a5abe04624e3980b00611370527b848e60f24297195a8ee21f140308a9f10246050b1639a71883ee91075e96e9ef9cbb7c0759a6b498af2690069ce03b355182421114bb83cd009ada6bf8af05a35513865a727229196031162b0b9ae1dd2b61605802469eab6a58fa6490e2ae39873eb3602b8a617529c08d1a58fc6542917eda768f3b126c38ce91499f17b0c072626152336bad8764588281022a26440272285a4604d1606432a62ae90bb316c13aa68d1362193ce2624c89d2b34b150049b87b19f15041b51b80c97180545c30de27e2731d92f711900175923a9858c14eb276a845098602061b7a8ca161980004329cf3938ff35a7624429367d031712f3d86861f2b4ba1e35ca2ca28a0c3d253729162b28948bb8eae477731d3392892733ae0c000f041b3b98e3d844e3563f8a525490a07244056c11803c12127125d7b83b1597624878730ca79b4a48ab311884b02e91d92c79ab3de4a97cf34e2694ea6cdac300f12115a30698e03fa1e289b1b0d444fb060060327e4b497e329296131d1f619617a9cf15e1a52495372d06fe5e40000727215e35cba43ee2a6459141168b1503599492963b3298fd339a4ba0377bae6a309c624126638fb624b25dc8e86ce7a434008d3004764b662d7858553172a94f87df1d20ec7a21ec4c801c7bf22212a44fae677f10341d3625e31f1b4c0b72068f00458290195d57352b4b4e0c506c1fd58e6541f9915365a6c84fb642000a010003f76b19a984135baa7c372f1713789622c13bc6a16311d8a7e77911f1c28200ce1e15286230386f71a32c9aa92252aca0a7f629c6d307b08814492d3a09496be9d29a70eb16632633600ca1e05ab4299d3cd22bab018562f2a904540f38a8f583b24c9ed53a67e1ff3476461230003f3640fe8cd86110d72c9cb16183025aa722e777e3d63be8489b65764a89c78694c61dd1b8289028a4d2946292ed73e2bc9131d04e2b992048163ea9fa7a7274a6f9e770cb4d8a2a110d311992124753e0936542893499ec9711a536912d68901879080c81e204bc96b53fa7632ce4ab48820a9dd3301a4a7801e0ee1eab800e368616b43b25f08b2bb2e380661ab5175721b5c33a94d90bd2cd074a411111aca5a39cb1516eb0684967651996486c0c709f83761277b27507ca601c28b548a50f0278d11603eaae8bd1085142ace8ac90f5e95c3984276a347a0dab2720461460c61ff0713627069a08dc9192658fcba5161a36503b54880590e8958b5042664b37a0d3d5a61fda58800c1d22b16e8832ee0ab14db8db801a08c53c47be4a3a0c1863801848883785522b46df05359a0bf336997a500aa78aa6abbf86e0584719d7b3367e3d111493a6fab4674b65a9cb4d00408dca8d138951bd94ab32453b83512ca40428d12a5c90e2cb04249b59b706808fb0e591ce2c930d9950905582fa9f03b96a06474fe334092b7a0d09460084a709b921214f2f1011df6570fd4dd15a13721d65b92d1ee8bbba18114db46b65d645a218c0000214003ca7c1432093c107b4cf9413cf56b9cd3592d06982720f7970d73b4ca374c663eb2ca7331573e3800e89a6a2f082a1273ca8637c35b56c8002127237802036f08e3a0c7ba5763b3ecb6b4452a93cf21137a288f666dd02c8c937721db183662300129870a85d4b0db91938c9113d55a266237818cb46f87937d6aec598e1c6720ffa111de26dbec88d13bb5915e8ccbb295f3631232b04468766996acb899cb50ce7c2c7694e4d0d009b9666855f54d30448270bd20b276179a72b9cf861b562e39267b7301a27a73719071d632f3c71772fabd15dd26635cb9282af3d4391a33ee007a2e3f53334e691a4d526e2aab66002a50bf6b9b7ba82420f44e3172be1700882dccf02d3273072e1e168f8b755051064bc73a0c96a8b3a51b12171f2d4aaf552f0b7aa53201b07c322b2fad4f0ee23042d3eb0602be076a625797f36994212767627357290641704086f4bde68aaa99bad040babf7550ba2b4141f58733ac313c63d5758a8d47e548bb144382034d6ef4f0006f26e76a49538ec29277375593cfb9eb7e2d7135158902b981a30bb2913308b791626a0ccf1d13968602f0b7b6a7d726603629e89527320a481959af3a2f5041170f102ce934520178a2e535a2ed36723c4688840739871538e3645a45e2b102a585a8024d211a272e8e060c94d548c33134f01e39b28841ec8286319bb1d2a2ba438a9557a5962ecc9a1e932d05801a242a68d0a0082b5928728ba813113b48189397a0c5113d2be0fe94718d8fb114721334d0409cb1e5c74914f363fbcd1424bfa5d6169a683917007650b0ffa011213ca84348b00720a972b71f644911151a490c9060f12cf199a161b5b1d12613b7cb962308d58373416128d856a6fa0d273eeb2471d2e13528862484fb4c5774fde67e2572d0f68c3741d64d5d797186dbd62a9844c3902b9c680922e30fae102a7c105931e38315e2ef2cb8c6014e7694cc2102f45f709ed0a5903db47bda61fa1b6d4b6f56a69ed5816ea97312fc70303ed0c9b1ec8952e2af726395a0ca3a7db2c9b55639820ff2334558266880008154efb144e6eb349da6393302fa9b981676d865cdb15e0c1219b7abc60527dc74d7aa9ba542d46e50f12ba6fc62b58459c62aed2ab6068885eef621a6fc4131453c27dc460d19360f01bb2ae17da99f6013b2420c18a3e29a5fa075e681a05688632be0f8c4e355b251b08c8daf059d9d348f9df8f184bbe53f819e85e73822e82122d68098f3f2f46890081219301b48446eb3d72481e03c4063c60163fa639fb391106f000824e2a81103602901e02720000180009048313e93ce3cc02b40c01b3c53d0e153db82a8133e520100445250a00600e316c7741b420be581b41d00302b07b001018b1901903d42e8ec82660da027318213c70008dec9083dc20cc403e80c4ce436f84030c7dc27c1401401981642b42b4246ab01c81f024c7212c823304c6b404e25bc881282b41b61e4000332b412a4003eb5400034b680001b08007d4003a8801b63c81be128387e30347c0006800270f00fe8feabf1403b80e41902d3fabd9008b6c00c20e027db4a0ac2e12172fbd4466021be5035c3c23640483741ca0e233a13a094264c7047d0f93dc35c35bf7435c0f8e668363803dc2163e82cfe6800b3402071080a6c9b1403dc2707160600002d3a71403e80509803afd941310d7c6bf782856779700d03d40ebcee81bd5036b1a03a0d6c5abd901000000) showing the bug, plus a workaround using `width` instead (although this workaround wouldn't suit all use cases).

**Comment by WJakub** [comment]
Faced the same issue, the REPL link in @Plonq message seems dead. Here is my solution using @Plonq suggestion regarding width:

Breaking:
`
    groupContainer: {
      display: 'flex',
      flexWrap: 'wrap',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    groupItem: {
      width: '50%',
      flexBaiss: '50%',
    },
`

Working:
`
    groupContainer: {
      display: 'flex',
      flexWrap: 'wrap',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    groupItem: {
      width: '50%',
    },
`

Essentially removing flex-basis, but keeping the width, makes the wrapping work as expected.

In case this doesn't work in some other odd case, another option is to try maxWidth alongside/in place of width.

Good luck.

**Comment by SharudAgarwal** [comment]
Any progress on this issue? Changing wrap=false to wrap=true fixes the issue, but I would like to be able to utilize wrap=false. Thanks!
