### ISSUE TITLE
Text wrap results in some strange overlapping characters

### ISSUE THREAD

**Issue by alexdunham** [diegomura/react-pdf#418]
**OS:** Windows

**React-pdf version:** 1.0.0

**Description:** Works great, but when the page wraps to a new page, my some <Text> elements overlap each other to look like the below

**How to replicate issue including code snippet (if applies):**
That section is doing this in code:
`               <View style={styles.colRight}>
                        {values.map((v, id) => (
                            <Text key={id}>
                                {v} &nbsp;
                            </Text>
                        ))}
                    </View>`

styles are: `colRight: {
        width: '70%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingLeft: '2mm'
    },`

I also tried using a <Text> element to wrap the map, and <React.Fragment> inside, but it gave me erros, is React.Fragment not supported?
![capture](https://user-images.githubusercontent.com/42680693/49888510-155ef080-fe37-11e8-9260-0b2afec2e464.PNG)

**Comment by diegomura** [comment]
Weird. Could you provide a more straightforward snippet I can test?
Thanks!

**Comment by America-first-melon** [comment]
> **OS:** Windows
> 
> **React-pdf version:** 1.0.0
> 
> **Description:** Works great, but when the page wraps to a new page, my some elements overlap each other to look like the below
> 
> **How to replicate issue including code snippet (if applies):**
> That section is doing this in code:
> ` <View style={styles.colRight}> {values.map((v, id) => ( <Text key={id}> {v} &nbsp; </Text> ))} </View>`
> 
> styles are: `colRight: { width: '70%', flexDirection: 'row', flexWrap: 'wrap', paddingLeft: '2mm' },`
> 
> I also tried using a element to wrap the map, and <React.Fragment> inside, but it gave me erros, is React.Fragment not supported?
> ![capture](https://user-images.githubusercontent.com/42680693/49888510-155ef080-fe37-11e8-9260-0b2afec2e464.PNG)

Hi , how did you solve it?

**Comment by brxshncy** [comment]
Hello, is this issue solved?
