### ISSUE TITLE
Render in DOM: Uncaught (in promise) TypeError: Cannot read property 'render' of null

### ISSUE THREAD

**Issue by samuherek** [diegomura/react-pdf#425]
**OS:** MacOS Mojave 10.14.1

**React-pdf version:** 1.0.0

**Description:**
This is probably more of a question or help to fix the docs.

I gave this package a try for a project I'm working on. And there were some weird behaviors I experienced. After a while of searching, I realized all the working examples people link to in the rope issues are different than what the official react-pdf docs tell you to do. 

_These are the references:_
- [Code Sandbox example](https://codesandbox.io/s/nk6k26x2rj) from issue #407 and specifically this [comment](https://github.com/diegomura/react-pdf/issues/407#issuecomment-445244472)
- [a blog post](https://andrewsempere.org/blog/2018/10/30/react-render-pdf.html)

To describe my problem, if I do this:
---
```
<PDFDownloadLink document={MyDoc} fileName="somename.pdf">
    {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
</PDFDownloadLink>
```
or 
```
<BlobProvider document={MyDoc}>
   {({ blob, url, loading, error }) => (
      // Do whatever you need with blob here
      return <div>There's something going on on the fly</div>
   )}
</BlobProvider>
```
_(both are coming from the docs, from the advanced section ->  "On the fly rendering")_

**I get this error in my console in the browser:**

```
Uncaught (in promise) TypeError: Cannot read property 'render' of null
```

I tracked down that it all boils down providing incorrect form of the component in the `document={....}` prop. 

The docs tell you to do `document={MyDoc}` but in such case, it throws the error. However, when I do 
`document={<MyDoc />}` 
or 
`document={MyDoc()}` 
(I'm using functional component for the MyDoc like the example), it renders fine without the error. 

----

I didn't look into the src code, but this looks like a type of sort in the docs. Is this correct? If this is not a typo and you really should provide the render prop without the JSX syntax, can you explain to me what I am doing wrong then? 

Otherwise, I'm glad to catch the typo and fix it.  I'm also making a [PR for the docs to fix this](https://github.com/react-pdf/site/pull/14).

I wouldn't be surprised if other issues which were already closed but ended with "I'm not sure how to help" might be solved with this.

NOTE: After you provide the "REPL" for use, this library looks really cool 👍

**Comment by diegomura** [comment]
Hey!
Sorry for not answering sooner. I also responded your PR on the site repo. 
The reason why it wasn't working for you was that if `MyDoc` was written as a Component (class or functional), you must pass it as `<MyDoc />` to either `BlobProvider` or `PDFDownloadButton`. 
In the site `MyDoc` isn't a component, but a straight React element. That's why you should pass it just as `MyDoc`. I get the confusion though. I wouldn't mind to change this if you want to create a new PR 😄. On the meantime, I'm closing this
