### ISSUE TITLE
Image cache is broken for local images

### ISSUE THREAD

**Issue by yenbekbay** [diegomura/react-pdf#427]
**OS:** MacOS Mojave 10.14.1

**React-pdf version:** 1.1.0

**Description:** With image cache enabled, different local image elements always render the first image element's source. I'm guessing that this is due to a bug in the [cache implementation](https://github.com/diegomura/react-pdf/blob/v1.1.0/src/utils/cache.js#L1), where all objects are mapped to the same cache key.

**How to replicate issue including code snippet (if applies):** Image elements have `cache` prop enabled by default, so you just need to render a couple image elements referring to different local images.

```js
import fs from 'fs';
import path from 'path';

import React from 'react';
import {Page, Text, View, Document, StyleSheet} from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: '#E4E4E4'
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1
  },
});

const image1 = fs.readFileSync(
  path.resolve(__dirname, './image1.png'),
);
const image2 = fs.readFileSync(
  path.resolve(__dirname, './image2.png'),
);

const MyDocument = () => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Image src={{data: image1, format: 'png'}} />
      </View>
      <View style={styles.section}>
        <Image src={{data: image2, format: 'png'}} />
      </View>
    </Page>
  </Document>
);
```

**Comment by BF-man** [comment]
Problem is here https://github.com/diegomura/react-pdf/blob/master/src/utils/cache.js#L7
For local images `key` is an object.
So we get awesome key `'[object Object]'` in GLOBAL cache for all images.
