### ISSUE TITLE
Suggestions for getting Unicode characters to render properly

### ISSUE THREAD

**Issue by KevinGutowski** [diegomura/react-pdf#428]
```
const Test = () => (
  <Document>
    <Page style={styles.body}>
      <Text>
		◯
      </Text>
    </Page>
  </Document>
);

const styles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
  }
});

ReactPDF.render(<Test />);
```

I'm trying to render this circle but not having any luck. Any suggestions?

**Comment by BF-man** [comment]
Same with arrow →

**Comment by diegomura** [comment]
Currently the only way of achieving this is by[ loading a custom `.ttf` font](https://react-pdf.org/fonts) that contains glyphs for those unicode characters. The default `Helvetica` font built in in the PDF does not have those, and to be honest I don't know if there's something we can do on this end. Of course shipping a font in the package isn't an option (we already ship a bunch of font-specific data which is one of the main factors why this lib is quite heavy)
