### ISSUE TITLE
 Line breaking si not working properly, text is outside it's container

### ISSUE THREAD

**Issue by Fuzy** [diegomura/react-pdf#429]
**OS:** Ubuntu 18.04.1 LTS

**React-pdf version:** 1.1.0

**Description:** Line breaking si not working properly, text is outside it's container

**How to replicate issue including code snippet (if applies):**

```
import React from 'react';
import ReactPDF, {
  Document,
  Page,
  View,
  Text,
  Font,
  StyleSheet,
} from '../../dist/react-pdf.es.js';

const styles = StyleSheet.create({
  body: {
    flexGrow: 1,
  },
  row: {
    flexGrow: 1,
    flexDirection: 'row',
  },
  text: {
    width: '60%',
    margin: 10,
    fontFamily: 'Oswald',
    textAlign: 'justify',
  },
  fill1: {
    width: '40%',
    backgroundColor: '#e14427',
  },
});

Font.register(
  'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf',
  { family: 'Oswald' },
);

const doc = (
  <Document>
    <Page size="A4">
      <View style={styles.body}>
        <View style={styles.row}>
          <Text debug style={styles.text}>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s
            with the release of Letraset sheets containing Lorem Ipsum passages,
            and more recently with desktop publishing software like Aldus
            PageMaker including versions of Lorem Ipsum.
          </Text>
          <View style={styles.fill1} />
        </View>
      </View>
    </Page>
  </Document>
);

ReactPDF.render(doc, `${__dirname}/output.pdf`);

```

Sample:
[output.pdf](https://github.com/diegomura/react-pdf/files/2702036/output.pdf)

https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618023100137802e1859b3600cc5000f00e214400777e011800d2b18017d95b697204a91e2a6c851a868e462008804b2ac0a25f0fc03916c7c7d4aba62a3f4142665ae280227003600060052575d18005b6a0a00734b300530e311702800316a58cb443e1847007908196a442e68a1184f280041444b44d4e2802b0057684b61781ab5636102c4791f18ff40e0e280164881b6766a60006b44e94eb02e00611044100a270062647919998026007601f755004a006e66666cacd22a64e8640a7a154702140a00007082f000f4e0e116420a444b4168966039040b170441c12072a54b8e0801bbc800cce08026801f4002a0069001a88440000e003a880f1ec002a97109b13240034009cd4068354840e100d1830611e40a4552b62aa8e41b309e2f5024160e61030030307a3dc30003e3d4a8003c5ae027562c8301410d315340015a889641c12c002f643a000440d198fbedb53629a6996640c8e0b8143a11808142c3383c551078321b0c46a37858fc7501f590a66269d3452ccb02e321d89d449666371e8de7ea85b4da6003207642c46000495055a6096340412cb160614605c2b6c5e07532cc040c23a91060c08a0a4ec601af50b6757830350240de248b2d94a4fa0147829060edaa1777b107ec11a86876310c04bb759fba504be38875036e5c0245c04e538cef509e69b20788fcee980c01ba411baf2000ac6118410228300c84407edb8c09b0ac602c81faaeeb9c150080200ac3035030224950a03382ebbbee50706405c0941e4ec0a0a0658b0151713502b1baf46e0fb9c0fbb00238da1c3512b35eddac0cf90e9d05078a58b0681245401c6d4e038ec32c130221b6869e19611c274b0254100809f8c028350c080eb6a39c80a0b6348601226c41e408a4890642da689db5029305302a0100da7613133a6cc033e9bb205c329b005468302203029d2200920ee97b94e7c8fcb84100197e20904139540b9717ce8bab6240502f89070110241a0eaa015166e37876f79f65db022f8402eaa0a15855c6c41d8c0363c5e3bf84104ea80ac545b9f95f183810d1439c214015150ce658624c04d39ed55b0ceaba002ca89704a4c02209d170d16c11430ee01a0ac6de9d8f6a3690d569ae0a965e2a661686e1a46b98e60dac2c3220a32a83038250f0660c663226321b8238e6360dddc82a660c5a56bc5f6aaa2f0004a342d88eb98d907c36856bf39adaba3868d32f1f32f10000

**Comment by diegomura** [comment]
Thanks! I also observed this. WIll try to look at it soon

**Comment by Fuzy** [comment]
Ok, this is the only bug I don't know a workaround.

**Comment by diegomura** [comment]
I don't know if there's much to do right now, until I have some time to look at this. I just pinned and this is the most high priority issue right now. Hope to find time very soon to fix it

**Comment by diegomura** [comment]
Turned out to be simpler than I thought. 
This fix ill be included on the next version!
