### ISSUE TITLE
Custom fonts cause the page to break and leak resources

### ISSUE THREAD

**Issue by puregarlic** [diegomura/react-pdf#431]
**OS:** macOS Mojave 10.14.3 Beta

**React-pdf version:** v1.1.0

**Description:**

Applying a custom font in the browser seems to cause some sort of resources leak, ultimately preventing the document from rendering.

**How to replicate issue including code snippet (if applies):**

I put together a reproduction repo: https://github.com/puregarlic/react-pdf-repro

This is all the code needed to break it:

```jsx
import React from 'react'
import { PDFViewer, Document, Font, Page, Text } from '@react-pdf/renderer'

// font included in the example repository
import PTSansCaption from './fonts/PT_Sans-Caption-Web-Regular.ttf'

Font.register(PTSansCaption, { family: 'PT Sans Caption' })

const App = () => (
  <PDFViewer width="100%" height="100%">
    <Document>
      <Page>
        {/* Removing the style prop fixes the page */}
        <Text style={{ fontFamily: 'PT Sans Caption' }}>Hello, world</Text>
      </Page>
    </Document>
  </PDFViewer>
)

export default App
```

**Comment by maxsbelt** [comment]
Hi @puregarlic. I opened PR that fixes infinite loop problem but it's not the root of your problem. To fix the actual problem you need to update `Font.register` to use absolute url:

```js
// example for create react app in dev mode
Font.register(`http://localhost:3000${PTSansCaption}`, { family: 'PT Sans Caption' })
```

**Comment by Jacob33123** [comment]
I'm having this issue as well. Up until about a month or so, I was registering the fonts like so:

`export const Roboto = Font.register(`${__dirname}/Roboto-Regular`, {
  family: 'Roboto',
})

export const RobotoBold = Font.register(`${__dirname}/Roboto-Bold`, {
  family: 'Roboto Bold',
})

export const RobotoMono = Font.register(`${__dirname}/RobotoMono-Regular`, {
  family: 'Roboto Mono',
})

export const RobotoMonoBold = Font.register(`${__dirname}/RobotoMono-Bold`, {
  family: 'Roboto Mono Bold',
})`

and importing in the index files for the PDFs i'm generating like so: 
`import ../fonts`
 
This worked absolutely fine up until about a month or so ago and now I have not been able to fix this issue. I've tried many different methods of providing a relative path, registering the fonts in the index file itself, etc etc. Nothing works. I always get the `Error: Font family not registered` no matter how i try to register the fonts. Any ideas? At this point I've just stopped using custom fonts and am rendering everything with the default arial lol.

**Comment by maxsbelt** [comment]
Hi @Jacob33123. Can you create sample repo that reproduces your issue?

**Comment by baileysingleton** [comment]
@maxsbelt How come relative paths no longer work? Makes it a bit tough for production use, as urls work for development, but relative paths with Node would be the preferred use scenario.

Thanks!

**Comment by maxsbelt** [comment]
@baileysingleton I added example for concrete case when `create-react-app` is used to build assets with webpack and insert script to the page:

```js
import Arial from './fonts/Arial.ttf'
// Arial variable be something like `/fonts/Arial.23nlk23l.ttf`
```

In such case you need to add host prefix so browser can determine how to download this font.

But if you import font inside `Node` application (without webpack loader) you can use relative path.
