### ISSUE TITLE
Better Development Errors

### ISSUE THREAD

**Issue by itzsaga** [diegomura/react-pdf#439]
**OS:** MacOS

**React-pdf version:** v1.1.1

**Description:** Occasionally, I make a silly error and end up with something like this:
![screen shot 2019-01-11 at 12 40 20](https://user-images.githubusercontent.com/11750061/51053038-1e5df180-159e-11e9-8759-84bdf28d4fbd.png)

My question is, can these types of Errors point to a more specific component? I know this is an error I've made (I've always painfully found them eventually) but it would help if there was some way to know which `react-pdf` component I messed up. I haven't been able to think of any way to do this or if there is even a good way to implement it at the package level. Hoping someone might have an idea.

**Comment by diegomura** [comment]
Hey @itzsaga . I totally agree that this can be improved a lot.
When adding features I try to add self-explanatory errors, but sometimes when the renderer crashes the output is quite cryptic. I'll keep this issue open and try to review each part of the project, adding new error messages. Also trying to replicate some common errors and see what the output is. Thanks!

**Comment by DuncanMacWeb** [comment]
Also, what is the best way to catch errors like this?

**Comment by itzsaga** [comment]
@DuncanMacWeb I would set up an [Error Boundary](https://reactjs.org/docs/error-boundaries.html).

**Comment by diegomura** [comment]
Going to list some of the errors iI find that we can improve so I don't forget then. Once we I reach some considerate amount I'll tackle them one by one.

- Forgot to define `<Page />`
