### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by salzhrani** [diegomura/react-pdf#44]
Is it planned to add support for custom fonts? it is needed for stylistic reasons and to support non-latin languages.

**Comment by jbovenschen** [comment]
Thanks @salzhrani Yes, this is something we plan to do in the short term.

**Comment by diegomura** [comment]
That's right. We are on it. Thanks!

**Comment by jbovenschen** [comment]
This is a proposal for the font API, what do you think @diegomura;

```javascript
<Document
  fonts={[{
    style: 'normal',
    weight: 'light',
    family: '"Open sans", sans-serif'
    uri: 'fonts/Open-Sans-light.ttf',
  }, {
    style: 'normal',
    weight: 'light',
    style: 'italic',
    family: '"Open sans", sans-serif'
    uri: 'fonts/Open-Sans-light-Italic.ttf',
  }, {
    style: 'normal',
    weight: 'regular',
    family: '"Open sans", sans-serif'
    uri: 'fonts/Open-Sans.ttf',
  }, {
    style: 'normal',
    weight: 'regular',
    style: 'italic',
    family: '"Open sans", sans-serif'
    uri: 'fonts/Open-Sans-Italic.ttf',
  }]}
>
  {/* Other stuff */}
</Document>
```

The main reason I put it as an property on the Document is that it is scoped per document.
So it wouldn't collide on module level when making multiple pdf's on a single web page.

**Comment by diegomura** [comment]
I don't know... I think we can hide that complexity to the user, and infer fonts from text styles directly.

So the `Text` element should call something like `document.getOrCreateFont('Helvetica')`, and the document should dynamically load it and save it, or retrieve it if it's already there.

That should save us predefining which fonts the document will use beforehand.

**Comment by jbovenschen** [comment]
I think we can't hide that complexity for the user completely because we don't know the sources of every able font. PDF does only support a small subset of font's out of the box, so we need something where users can define sources for different fonts.

**Comment by diegomura** [comment]
Oh I see. You're right

Shouldn't be something like this then?
```jsx
<Document
  fonts={[
   { fontFamily: 'OpenSans Light', src: 'fonts/Open-Sans-light.ttf' }
  ]}
>
  {/* Other stuff */}
</Document>
```

**Comment by jbovenschen** [comment]
We have two choices, use the postscript name and styles with are defined inside the font file, which is same as pdfkit treat custom font files.

Or make a web equivalent API where we define al the needed properties for the font file, like `family`, `weight`, `style` and others.

Don't have a really strong opinion about this one, what do you like the most @diegomura

**Comment by diegomura** [comment]
Don't have a strong opinion either. You can go with the option that most suits you.

However, what about something like:

```
StyleSheet.create({
  fontFamily: 'fonts/Open-Sans-light.ttf'
});
```

Would that be too much disruptive? I would like fonts to be the more pluggable as possible, and defining that 'fonts` prop it's kind against that.

**Comment by jbovenschen** [comment]
Was also thinking about this last night, what if we make something which matches more the web-api.

We could create a separate API for registering fonts.
```
Import { .Font } from '@react-pdf/core';

Font.register('fonts/Open-Sans-light.ttf', {
  family: '"Open-Sans", sans-serif',
  style: 'italic',
  weight: 'light'
});
```

Else it is pretty hard to guess the postscript name in some cases.

**Comment by diegomura** [comment]
Love this idea!
I think is the way to go. This will keep the `<Document>` props clean as I want them to be. 
Good work!

**Comment by itzsaga** [comment]
@sebekgr look at line 181 of the example in the REPL here: https://react-pdf.org/repl

**Comment by akshaybosamiya** [comment]
@sebekgr To import fonts from google fonts you can follow the below steps:
1. Select Google fonts reference link from fonts.google.com 
e.g., https://fonts.googleapis.com/css?family=Source+Sans+Pro

2. Open it into the browser. 

3. You'll be able to find https://fonts.gstatic.com url
e.g., https://fonts.gstatic.com/s/sourcesanspro/v11/6xK3dSBYKcSV-LCoeQqfX1RYOo3qNa7lqDY.woff2

**Comment by Fintasys** [comment]
@akshaybosamiya 
I tried today all day to get japanese font running. I also tried your font 
[Demo](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634ad0049467e0c43cd11e35339245381550bce085b606c00220ce81e32e00cbbb38403200473a834008cb25abc4f8ef2786406941d3ed8663518dd6410043c8ca500aa23383e1e3c400b75004088403023800b86a58282d87ead268b460a03012890c0240019faa42180616a761e4f2a93615a38788c10040a9e62412878223e15268b227a5110487aa61565836474ba3d279ec7266a195c4ab24c3e9d45a9800145aa086a888107c1e2d80dcd56b1bba3c000d2fa18422a580408c793f860919828290762a74466cadb33043f1d3479388c04374a9650c231e254d056036480d8935a6e9822b95aa8961ae5be96980005ead160c078d024088c4b610087acdeaf63bb60b0430722f4127551c2d500c1055ee6fb266fe250cd6430002a9815a2021cb2b02ab54c1180043880c0b6c0568571d4fdb1819321880abe2dcfe5fbef5bdef48dba33043250964a5ef4142b18db636ca0e186f791ac39483474c4561857ed9a36cab3b03f080c7554002fea9e2154a3241e3268780011fac2541026570fbd77461a8b5488d7dc02c5185addd1c319330600a36c1d97d2c41b688934e4787dc9d159fc6805b33cb72e83d013861e1c34749a0d9966f53010c9f111bb3632b6583d5dd44ef55a169ef670cc280708e586041ef0a3580419736d591011d0e22059443442945ac2ca155858c2012d3a5696286dc026450f53dc87cac9989076ca92031d671237dd743016b28bd2a7dbf180dd5686567c965b3bf54bfcfbc186f45817243415aae184018da89e11d0ace32a4870c0bd54becbc2306a38cb5caaea9654ec5b7646532ce6f885a6ec4321bfb1251d1602041c5a54b9679d8045cb759460280a31e152b64cb6546c265f7000c56c2411afb27b27b7d30096680474751b4bca9373109e4ba259581aae8b42851629a5014b310503e5aa7f07939d62d5c91ef508f43734a0585a8a665a4740640001b8603e09905bac5b13d5427d4146505996b649f6edf71d4ec5ec6c1e47d17c89eba5852b4ef9463160a36977d1d56a71c602a51033095bc086ded9c85474bed556aaf4a411c7e6ba2407b774db4986ee52137aa6c680b00aaa9331800fbe41600831cdd21acb5b078b0045724997bc0c8a6490e2646191a6c2a2cc1393b16dc110d1694e1a97578a69f899321454c74ee5f65cd13e814ce300719307a19ba69943be44ecab658f5b0991e5ff250004b959e344bbf55406d17eb788dd1bbdb56943a7acd2c9f6025917d151531d11916d7d81d5169d22344807c0c10eebb1b6fab9cc117a9ddb97301525541d0adb2646efbd35ef850c75e8240e52a435fdfe9d63af3bc0d159e89008844aca826b340c009c4412018c7e51d9dd154c3822bfb6badb06ab3816e029698791ba7bcb029e2ac4a1790ad43abe86e8d941eac19d8ac614a29b933f0341855a37339c6cdeb1b26b01c4c027d4643255ba08040d24790b065434d0528d3e0f835a0b9321ee55f33167e8757ea0a7b63f1a8b3b6a8dacb04654e47c9af0161e8f787a07e2f49158b13773c8e962b4626410499086312f42a33c42643e9c0640c8a4f850a8d5b0114ca90d310760845f60802499a1880d8bc8a73957ece23941b656a6433c8201b23d1dd8fa494505fc5346216d9d8580458919ef1884746243039d4e8883aa3c8592974469b621ac8d07bca214528650bf180af596350ce8cb40032a0e2d83490a4cc1f1f425a07d5fa4d0a4838b948c2fb05633cf786687d2e8e39ef13225a845dc9087eca15ce28b229253aa1342ceb601cbf8a02ec96727211a621c68d510109c782ccc42fe1130601716b95f1191c24d114638124a3956380268bd9f32064f2464448f433c274202bb308200e91b2559dc2e870c6a248baa0ed6bcd95d15473e1180b7a20958a703f0b10e2910782767fc2c19703ca58c01f160d7aa6e47173044ef504783e32e2c58d866394cc5a64b968c480dbb54589364c42d67e9a2d108aa1beec89322121afa4b94b26acd45cf9042e45598f3302c26941c8e7612732cc560470330ca0a0ce89d5959e8e88c0bf9bd2ddc88d4eb304c677164b0f21aaeb8a61a3ee44c360aada6f4c6c0f309efd12d0a26b46314a32f0249407c38043538505398ec258456452f002248e7851ec2b0cb1cb371b03b3a9d526d43fe5083d26600c888642fd8b02fb58e022ec0396b5f6dda932062c7244a4b76a4a9fe50d2eead8cc7443b2599b281af6a022930b11759f4ae800410fad01792601905f9b159802c610ecad9162101792527da438403ee00072cedefab47cc8282a6f67063852c28c9c24ab13400217699d13eaac181ef3459baf90b586c60cfaa894011f07eaa947d8cc20d9d1edb5e1e0ce4299d73100d9b112658a601a4658ff9345b0a78f3c62c49634f9c94ce6a649230c0ec1ad51a7875f3721f81f5e974128e0c4642676ce6e428caa181275aa1492b63076969d51d2847d1620c2102473ead68933982555a28f35a3f522df2150cf0032de5ac5cd105ba232b319018e9b54b658acb46ea9c271b263d29c36dde950c153d6a2493072b109c2aa5eb1107b545a25393181303f8c3a072124d57d6c79708366a1761a664c7e32a8675d8d5127a3763f72e804748cc112828391947fa6d8b3a40766ed4b255244a9490d4cc3139d08a8200d8b94747f62333ea5abd8bf32c0b19a553a0c19d7a50f45e87d1bf2c051692858c68f41879d36b0b39773ed6a83d2f80001f960dd93d8f542d0806f0ac249a54e46e56143068b478ff9bc0442ba8ba3611d11c1c92d130098e563001769c70a9140038a4c16834d4e1a5b30580cf77253c77843189e49aa4b170500abb2961a9ff982d4aa0ece26e8ae58d5fd2a856bb8e1c20eda6286b54350865e04726a405175cd9756c6d810c4377735457b2d06608627dc4b9683deb02485edbdb9cbec4591338ea546f5f6646ca0958722e4a82f7544ddc34d0773b162077d1e057699c829ae1eca123824cc7fcfcfd2bd3ce9d8ff785b0e55b13094052a91830960081e6c603762f49a97339a038b6ead1a26b88bced14015e44c5d244330a79b77f210c1dd71752e0ec01f0448e1ebd8a4988188fcbd469586d91250a090808e840a587c918084008e5ac00464a8f64b9fad5852f119398854bcf41ccbf5adda84c89a4a22eb8c660715663fdb46163b964f716a19c6f833aff348104b8950dce7b998cdf65127619e891b2de29f7000194c2bc962aa1b64d2861a04c23dc71e7967aa12afd6e65ec8859c45331c8137d1b5a411c48afaf0d78739b69b2d9300508b939935f730fcbf9ebc9f79f75ecf3902bce3f7d8b28ca4218d6cbaa2e42c65c8100b623b079ca58728102eba734f5aac08becb0d1c84ad78d12f5cca6f702a6e8c75c43663cd608e8c423544a65fc8986168a690406af280c4ca8f326009a6e28eb23e218040675cb628e801ed98774a54e802c48a82a41f4d7adfcfc2e2416e2ea6e8bb836e1e076ed3c8eef3cceee30588388e501800e0d2c3c0000d671abe0c48648148548470b48f48d74d7c8460f41f4aea094716ca875ce32bc2c628214804b48d279c3922c0b22ea889a0ac0d061a53c6682706706624ee368e061a1662af01f05f02e4bf0ff0f706602086089800004cb20f10392708b9808811ab3c51a188aeeeeeb9800012c52ba23629bc49a9e4fe0cc1cfc04cc34b6c9f42988b0de8e985fcf78c5870163e65824a336428c6cc3c1320748566426380e27e6378972ea68d26562beb2a75458001ef965f489cc0cd1012c896da2972e942e4b60ca85d8d8c63464408ca5232a136558352f542b130255a1003d0f4a1dee4876072a9acf1cfe0dd81de816ab259ab7cfbcbaaed16ccf201e45713b244ccc0f508e2734360c167f1dbc650100d288f1fb80009a0122481ba072de87bafa8b26760f2861678ec7855ae943346d6f8129ad4475cc785c8868958186f8af34d7af44f14638e9a2deb9a582fb42c408e3942d42a8cc42fc16444a2244d000052148cfc5f8178198f8219202ef78588f78de89f6afe1e0aa15a252cb180004a4fcc78584951ce4094bc2a702b075265cf42864ca8e4e16214af82126a2ce38b605e8201518f69bc21d8dd8eb43060f44b01214e02a80a6580f58a002622b03dc5a228e4f87010821369c82ce77060ce0071cc3c6cc2208a02386e1fa409c6e40c053185c4898381aad248067be1e04f45480e2d443c8bf825c524c0902cdf6a7aed0384c482c03848949716549d6ab415c706234609b98912220500f8203c23197e9223766ec620d6acfeea28da658ab8a868a8e21e788ac9663c4baadd8f61258131df8fe28e0f546c10f8ca263e6c8cc040166cd4952e354198a841f268e9f8734158264e0066a1981782020a2d024f9046e3a44ec6ed94360a59d74b747ec8e9f79cd6d50d927c027132ec98fe283cdac28654847951674e7c1961212d892a90d6a2c6a69d01546f957491835aa8ec5a238989428a58ca492114230a092ff2ba285cd0610544c524660e85b606e16c85e8c78b140a42a49e41391ea084580ab933a89ab88d885603e811e080852238f108be70a1f638483cb493b167291ef40fca75c021ad038a449ececa5209b42a2c0f1f893291661458762de559aeadbe0c8200144b14638300eea2e422e4d00217288143a2a09e89e16925c98600d29705d5001e5b6f64ec136407e084526415cfea6e4460240a47aeac8ad95058fe1d8c45e3e056f74f9c66cc725f258083eda62c02415e159ecd0ccc1de3e268500cc0adfc434f582a9eaad4c7346e42858942f2a39e080001c8e88289328748b09a9bc2d19ca2d45a345b03e87e575cc262b038e53530227a89cff9af8fe099e3b16f13323414999001c2a542be7e95e9595ca99a641cf8572193c1680ee91a611d1a4bcf687a128959e869d7eeccfa9364ff448668529cdb0178d75cc4cf9e6e2591d83641c8e35e0ee09660214d099169727488002804000fd3a822aab0c16989ce5f5c534ec2cf46d85d1658dc4a2c62a256978b721e89d87e8194fb1d60436421d6cd794d0414019b28f287a2e51f0c9ac22023a65ea85f782ec6ec33a580f18bd12e9e72fd9c12634f540967b149a58a4a5770436119f612aeecd2c9c785bcb5c1553c0000fc7480baf968fa5852464cc1520c09728e8a6da78458d3a2423e9ad0d2874d5957d8268ad0828660144e28954ce1df46c4330cb2c0cffe655ee43cdbcadcda8e994ebc6cc66df9279618015870c2c6bf830cbb8c9ebb23c01b947431289a4a97d8b601440c1202392b38b6aa59b16d64a84694104220f4a3a6ed2cb8b38538bca254df41a2e7c1ca14c4ac0ba829da6af90688ac3b16c88457242b4a9c928af8cb02d2166fdac06966f122f1c9a8fe2a81c8a292ea445960578a7c1f46b2b89ac4814e6a2a82248945cd9c2284264172f154d25cd60ceb5e8e00ad507e1fa85958e80183d05bca3de2a3844fc5329e4d660fe1a9f6947c3c29cd2d232e70db98ba990cc0ddd55184b662253dfd43e88da226ac0338548596e004fc364448dd1e76a2c6d0c990aab21e90f75f6e7218a1450ca131a6f58e86894366c84414106c530001ed35c78284fe22c95c8729c8dbb868d34027c532428f226620b0656c2ea7c0d2cb57d894ee322a84a0b60531e7908074d06ad285cde6ddd80c48041146a99a05c87c002567e30c678b60894bd89025d060439c0c0220bf8d638360b4378bca91ca35334de8363586a2c2e4845ebcb62d7825859416e65647941ccd900085000f21105002445f8774342e7e99db4e4d12c02f24c88ca49c0fe7549523d0442f40d89bda3e8a19e001c2e78b5c4726348b2ad02cde13000848e8da90806dc6a8fa892e62ccac220b825bd58a8fed0c300703fd406924ef4425a376f18fc42a2241d12804dfadc36d8596de8fe0c1c1435a05430a14f54a13684517a1b3e4b0578b56fd3a54c2eb24bb8245256d946c3516601a6a7e9e6ccd238668df13e60aadf6395434014890c560d2970ccea0ec2b4530d58499e8acd3ed08157d8171342cc0eb1eecf06c6c6de8d9501ae04809f9734fe093281858b3d54a43388ae7d8054d35456249c4ae98aca92d6d48f19edfa8ac381a3ca5cdfcafb85c02209d33c0f0cb1440b738c43f0db69c86f6cfa801a00dee481c10b769e1575c61eae4c80e0145c3e8a2b94c538401b6482c180fb809aaa2c259e57c6df81213b17e56c49f4d010e3992ca944a581fcbb988aaa061e4cd0495e9e2595a4074180f41ff25e5b2df7a172c3c8f4db68a5d2a2c0ad12285ab89a285dc3bfa5adbed32415a246f28142d1451ba52c481f46ac7fa44c5c6f04c5d4eaea2dc5ad035c61e5f9cf4fe0650dda9fcb14dcd1ba7acb92fe5013356f160110f53437b3743073b1a8e84488429be904ab0a54dc3f69549a985848f1a86a009544aa8ecc99d89e85ee516544c656ad4e19d1c95b4723024bd434898874436374624755634234273475593fe344c565f25280472b24ed675e06e3068e14e07e9fa87044b4fb803dd6c10abac4aadc8555a2c432a24d614361a6ed4fa52791a6679e85f4d75e5c04fb548b3e378bf8f4a218c6b86cf4a18a3be9616d8b28e02792be8f846421c6d26656434e180d80daca0fda538a1c3386533abfa84ec85ef8d960d24678f1530a1f4e1e16cca9c7891c1fd2433bd73822443401e7063564585810a39c96b8c449edf409608f15f8bc2238e746821dc04e90ab9ea2a9d0df859d3a6b079143d02363ae8c94deb2d62e1a5e0ad9d44c8daa1ca8a0688c57d404635bf05fd86501b5298a16cc98acf61872ae7196c1df1c8e898c200020ae34814a30da0920c95eecc05c8d89524ba68d332872c8281f8cc61aa2189715983031e0620f50c29a8392df7b80a66ed7d4c91a21d44349071ae842f843c9c49a2c4865648b1d97e79796a7d88181625c32a8dd3789f18335243b8e49ff80528d74b26c2302fb8a237280da69b954f423f5de885ed72283cd763ea4dce5538a9ec52b585b34883b3791050fb32f514402067a4c0c920e0fe0ef1920780120b64677177bbc605cfebc0020f78aa0440d80a407808e80000600024120a77180e77d187600e019030040f374af7808aa07f74f00400e0ce0280ae0300b919436f7180ee09907400c0601ec004054c640640af4c99b20fe01060ecb60bf7940000e4e60500500f1010034819019066aac07207c0df0bf0b20c8c5f05f0200cc4cc6da79321901b0e08e081900006c280000d2000cc4a05d26fa2890afc005d20006ab10b3e09a180700c088e00001ae08da92897132004afc0867a3c0000ec220c08340289b20c102008e08e0a91f4f35ef773a3838420748f4f713100c102a3f4f300aa0e84c4fa4f30d47791cb805d26305d29607e602f5109807771c08a02a0748120870a5d5c8392da0ae57484af000ac6a985f9c46fae80e66748b2f95f05fd6045f7c025159487d2a865f4df94051f1c0b8862079f8705cf5003d29d8180748a910002c6a9aee0bae0266341f6873763efc3fc99af4ecc22081f300c1fa1fe1f1c07df94056cfbd43f9a023f63f13f300e08a91b3ffb0f3f0b06004bf53ab60abf9a0166106600b5fccf51874853f0000c35e43fbb90d427884bfbe7ccfec990bf9d2086a6a977fb511a0137f35fab0037e11c6dfaefcc3e2202503d3c0fe35e57729fcf3013878055fd101100d601402afe33f4381cfc17e8ff1dfa9300708e02102bfd38023f140407c83eda03568401620ba962536037be35e088be03280700b0036bc5e20c611034027be040e74b511dbe07d69d9482afe7ff0004e02380960266ad818414e04806b852fed7f58061033fe75f1ff8c015226a0cd035021fe4ff2c20bfcd52a004a4368277e74c0cf330280120f307b24874164d3083d4483e77404d94c0300cc0ca039fdf41080b54a281bfe8c032fa5833806204701400e90f10ca007d0f804cf1486dfdf40f7f45f8efd97e76050856e09c141f5705303001e844fb893cc80da92b00c40b8034057a253d9b4b4f2a00ea0d00fa80440c7c80000)
But it can't be rendered most of the time. Am I doing something wrong?

**Comment by akshaybosamiya** [comment]
Hi, @Fintasys 

I checked your Demo link. But it isn't accessible.

**Comment by Fintasys** [comment]
@akshaybosamiya 
sorry I changed the demo link, seems the link was too long

Also tried your script, seems unfortunately not to work with japanese supporting fonts 😅
https://fonts.google.com/?subset=japanese

Beside keifont from the react-pdf example I can't make any other japanese font work 😔

**Comment by akshaybosamiya** [comment]
@Fintasys ,

In your case, You'll have to paste the following link. 
Link: https://fonts.googleapis.com/css?family=Noto+Sans+JP

You'll get the below links.
1. http://fonts.gstatic.com/s/notosansjp/v21/-F62fjtqLzI2JPCgQBnw7HFow2ou2HcP5pp0erwTqsSCpNtb5_OnUY4AN8I8f2ogPhktlh5UtNFs.119.woff2
2. http://fonts.gstatic.com/s/notosansjp/v21/-F62fjtqLzI2JPCgQBnw7HFYwQgJ.woff

**Comment by Fintasys** [comment]
@akshaybosamiya 
I see thanks ! But still can't use them
Another [Demo](https://bit.ly/2EgZZ54) here, console says Error: Unknown font format

**Comment by emorling** [comment]
I have the same issue with woff2. Any ideas?

**Comment by diegomura** [comment]
Unfortunately only .ttf fonts are supported for the moment. I plan to support other formats but didn't have enough time to work on that and the rest of features

**Comment by Yerkewka** [comment]
Hello everyone. Can somebody help me with cyrillic font? I try to use 'Roboto' or 'Open Sans', but the output is still not readable text. I'm using ttf format link from google. Got it from the link above, thankful for @akshaybosamiya .

**Comment by Dastnbek** [comment]
Same problem as @Yerkewka

**Comment by eugensunic** [comment]
Has anyone figured out how to use these fonts from an online source?

**Comment by DeepakKapiswe** [comment]
I'm also getting errors while using google Hindi fonts, Please help

**Comment by luishgranja** [comment]
I'm getting _**Unhandled Rejection (Error): Unknown font format**_ with Roboto .woff2 fonts and can't figure out a solution, at the end I just downloaded the font on Google Fonts (that are in ttf format), and registered them with a local source.

`Font.register({ family: 'Roboto', src: 'path/roboto.ttf' });`

If someone figured out how to use it from Google Fonts directly it will be sweet to show us the solution.

**Comment by DeepakKapiswe** [comment]
Finally I switched to pdfmake library which works great.
