### ISSUE TITLE
react-pdf website is down :)

### ISSUE THREAD

**Issue by sergeyk** [diegomura/react-pdf#440]
https://react-pdf.org -- some subscription issue

P.S. love the library and just donated on https://opencollective.com/react-pdf/donate!

**Comment by diegomura** [comment]
Dammit! Thanks for reporting this! I’ll fix it asap. 
And also thank you very much for your donation! Means a lot 😊

**Comment by diegomura** [comment]
It’s weird though. The site was hosted using the free tier of now. Don’t have access to a computer right now, but will check it tomorrow!

**Comment by diegomura** [comment]
Ready! Sorry for the delay 😄
