### ISSUE TITLE
PDFDownloadLink can't work with this.setState?

### ISSUE THREAD

**Issue by william726** [diegomura/react-pdf#441]
**OS:** Windows 7

**React-pdf version:** 1.1.1

**Description:**
I created a very simple React component and try using react-pdf to generate a PDF report. PDFDownloadLink component is also being used by providing a download capability to the users.

Since the report data are stored in a database so I need to call an api to get the data. Normal React component function componentWillMount() and this.setState() are used. Unfortunately I got the following error and both the PDFDownloadLink and MyDoc components can't be shown:
_Uncaught TypeError: parentInstance.removeChild is not a function_

I did some debugging of the issue. I found that if I comment out the this.setState() line or the PDFDownloadLink component, the page is fine (of course without setting the new state or showing the download button).

**How to replicate issue including code snippet (if applies):**
Can't format jsx syntax so I uploaded the code in my repo.
[https://github.com/william726/testing-react-pdf/blob/master/testdownload.tsx](https://github.com/william726/testing-react-pdf/blob/master/testdownload.tsx)

**Comment by diegomura** [comment]
Hey! Thanks for reporting this.
I found out some edge cases on how the DOM components re-renders based on you example. Appeared to be two separate issues:

- When `Document` is defined inside the `render` method, the whole internal structure get's recreated (not just the updated node). This caused `removeChild` to be called on `Root`, which didn't had that method.
- Also I wasn't checking completely about changes in `children` when they were strings on the renderer

I'm going to push both changes soon.
In the meantime, you can accomplish what you want[ like this](https://gist.github.com/diegomura/4ae2ea12921360123e48f9b7779bf888)

**Comment by william726** [comment]
Thanks @diegomura! It works by moving all the react-pdf components out of the `render` method and passing the state through `Document` props.

Please advise after the fix should `Document` continue to stay outside `render` method or it can be inside.

**Comment by diegomura** [comment]
I will!
Btw, do not render react-pdf components outside `PDFViewer`, `BlobProvider` or `PDFDownloadButton`. They will render because the components names match valid HTML elements, but the result can be random

**Comment by william726** [comment]
Thanks for the prompt reply and quick fix!
