### ISSUE TITLE
Can you export PDFDownloadLink, PDFViewer and BlobProvider?

### ISSUE THREAD

**Issue by william726** [diegomura/react-pdf#445]
**OS:** Windows 7

**React-pdf version:** 1.1.1

**Description:**
I import react-pdf components using this import statement.
`import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, PDFViewer } from '@react-pdf/renderer';`

Most of them work fine but VS Code / TypeScript complains both `PDFDownloadLink` and `PDFViewer` with this error message. It also leads to a webpack failure and we are being blocked by this.
`[ts] Module '"@react-pdf/renderer"' has no exported member 'PDFViewer'. [2305]`

I checked the `index.d.ts file` in `@react-pdf/renderer`, it seems that these two components together with `BlobProvider` have been defined but never exported. Can you update the export statement and publish a new version?

**Comment by diegomura** [comment]
Sorry, I have no experience with typescript. What do you mean by `Can you update the export statement` ? Could you make a PR with the change? It seems to be something very simple

**Comment by william726** [comment]
@diegomura yes this is the change! When will this change be published? We are being blocked because the build on the server fails since it downloads all npm packages on the fly.

**Comment by diegomura** [comment]
I will today! Thanks

**Comment by william726** [comment]
@diegomura Any update? I can still see 1.1.1 as the latest version. Still waiting the fix to be published...

**Comment by diegomura** [comment]
No sorry. Didn’t have time yesterday. I will today for sure!

**Comment by william726** [comment]
@diegomura Thanks for the fix and I can see 1.2.0 has been published, however, I still have the same issue...
I noticed that you did the change in [node.js](https://github.com/diegomura/react-pdf/blob/v1.2.0/src/index.js) file but not in [index.js](https://github.com/diegomura/react-pdf/blob/v1.2.0/src/index.js), maybe it is the issue?

**Comment by diegomura** [comment]
@william726 do you mind submitting a PR with the change, and testing if your issue gets fixed? I would prefer not publishing new versions blindly until this gets solved

**Comment by william726** [comment]
Oh I thought it was being tested and didn't know not all people encounter the same issue.
Here's the [pull request](https://github.com/diegomura/react-pdf/pull/449)

**Comment by william726** [comment]
Thanks for approving the pull request. And sorry for asking that again, when will be the next release?

**Comment by diegomura** [comment]
I will publish a new `patch` version today!
