### ISSUE TITLE
Give focus to document after render

### ISSUE THREAD

**Issue by avianate** [diegomura/react-pdf#450]
After PDF is rendered in browser, the document doesn't have focus so user has to click on document before using keyboard commands (e.g. page up / page down);

**Steps to reproduce**
Render a page with an href to a pdf document that will be generated dynamically.
Click on link to pdf document
When blank page is opened user can scroll through multiple pages
User can't use page up / page down buttons until clicking somewhere in the viewport or on the document.

**Expected behavior**
When a pdf document is rendered in a new page, focus should be given to the document so a user can begin using keyboard without first clicking on the document.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome v71
 - React-pdf version 1.0.0-alpha.14

**Comment by diegomura** [comment]
Thanks for reporting this!
I don't think the focus feature should be something that's builtin by default on the `PDFViewer`. There are people populating the PDF via a form, and you don't want to lose focus everytime a re-render get's triggered. However, I think the best approach would be:

```jsx
class MyDoc extends React.Component {
  render() {
    return (
      <PDFViewer innerRef={node => (this.iframe = node)}>
          <Document onRender={() => this.iframe.focus()}>
            // PDF implementation
          </Document>
        </PDFViewer>
    )
  }
}
```

I added `innerRef` on a new PR. What do you think? I already try it and works very well
