### ISSUE TITLE
Some characters in Indian language unicode fonts are rendered incorrectly

### ISSUE THREAD

**Issue by qburst-blesswin** [diegomura/react-pdf#454]
**Describe the bug**
Some characters in Indian language unicode fonts (tested with Tamil and Hindi fonts) are displayed incorrectly (check REPL link and screenshots below). But most of the other characters are displayed correctly.

**To Reproduce**
Check the Tamil and Hindi text in this [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231cccfbd474d940308f0848614652060f008e08308984a02dcf0c300f2312180033cc23983ba82b063006001398b0480410579612963c540f324c0019b78406000d1f86358d889b830f2fb975794400038a4f3c8f157b4832764c1792239773883b614c08b79f1bacc63cfa6c48cb2d6680058f12515ea772520b3012106e6f801b9340f574420977b2660c3cb24f0017882c8c0020820bb24cc306d90986de3f12092600da70862220bb50ecc37bb82e2c280205143081a47817709b94a58787557c5c478b86000190021fb52195183a1921918650940cd5b8249b919864608c1008809105bbe3d12000370c00e0b3710c846e4d961fa1ca5080d9a894920f808698b060666788420202aa83ea60ac32b814d787ab0d106021d2906faa8a78602690379f0cd401653dc06d95481430025ef93d4a0405cdc2e07679bcbe00af460422a935dc607a32b7655083dc59c07f2c54191cd4b5b622784b36221480f1d5a2d063029fcde76d18af46683b255309bcc089899281c32c2a60209afe914d145472b418af2432502ee111f0005ff5871409035b71b89abaaf40a78002b26d9c557b818fbc0b94d6034002648b5414dc7caa101cb316101660396990b0141060c822ec7b74c60301123309031c942a9f1335608d46c4e0c40bc3b1f182508091946e755872c0901e8aa040bd25060345585e886225d2415a2271c5144a89e135235011acb26f0aa1cddc3e54559c0a1900b4228277437600697790a1f50422c305c8c013822588c46e3d4822bd1e9be1a0900c855438cc20882108c22f59273466310f8288821f049209f70c1187e8ad4d53d5cd1240964184a8001e9747d0341b0743d00c130c44910c73008911d4181356d092800b952cc328400c3a10012e8400fba1003ae840167a06040193a1f2c01fba060401e3a10056e86ab004ae842b0006e852ba55cb002ae86aadac0153a04af2a9ac00b3a10041e806b0a91a9afcb4afcac68a824001c8001d30096d5135401eba10021e87ca3a98046eaacae2aa6e6b66a2b0066e831bfac0027a10ec00c7a1004ce852bfac01a7a10026e852b96b5a36cd50008e811b0aadb8697bfaeab0076e80bb0ae6ac69aba18ea82d0ba288b3428bf468962a3012d91367083914b3500025f1a40b2cd500364840105210006482a70030484004920604015921003e48466d996669c01892060400e920a9c00d121005948401e92119c013920604005121007648401c921007e48401512060400a921002248400292100714856695ee7b58d775c00c920d99fbd6cda729810050486d6a99570021484009920607a700204846669956d99a7c595645b97f9ce660401d120a9c00712069ed6d9d6639ae7798d71991669d562dd5aadcd5000e4815719fd7001a4858f63981b3b674db0e95981007848401b12095e6700384832f23c000521b39800b8e7b3fe6c5a46c2b616a10b780102290ae806198561d802125320c8000c5c028164404f851930648f00e096cd8a0281da08032e0b82e2997b90f8680787dd8059140461828c07860a73171324800a3084460a2e001998280072e8040000654f4101d297f000b400094960205acb21f7b1425a150380481284948416525a40329180c803012041e25a301541a0d9ef3c97ab055e4b0378a46de94177bef43ec7d4fb9f59097c0a0df3be2001f93f17ec03df8405c8570bd1f04284807fbff3c1a03c04d00c0623f8248d81f0310720d41e833057f6c1301707009800434509361c48148790b20942c83c468098d4c28a5c0202b1880e5418057b3a27e980f00480e08a0541651f19a0a61280e4600f83684985957f800563414129b284be000085d00b8460594001b2c4da8c13125130184813e3d1110513b26500b19413f81e009b511821475e600b2800460004c7133819f5602030a46066900059da6504e9500179609c1b230c780a21494968700a9c09498d4cd075392034e696d36a30cee9ef17a4c02690333672f5193a3c6418a313004c472599e52d06a82b1702761402e034017ad0d225bca8220540e80b0305620942800)

This is how it looks when rendered using this library (incorrectly rendered characters circled in red).
![image](https://user-images.githubusercontent.com/28915325/51439016-62f23700-1cda-11e9-83ae-c27d380da9c8.png)

**Expected behavior**
This is how it should look like when rendered correctly (screenshot from Pages application).
![image](https://user-images.githubusercontent.com/28915325/51438770-3a683e00-1cd6-11e9-844d-dfea07634579.png)

**Desktop:**
 - OS: macOS 10.14.2
 - Browser: Chrome 71
 - React-pdf: v1.2.0

**Comment by diegomura** [comment]
Thanks for reporting this. Have to admit that non-latin alphabets are very hard to handle and understand for me, but I'll try to give a shot at fixing this soon.

**Comment by qburst-blesswin** [comment]
Thanks for checking. For now, I have a workaround in place to convert unicode characters to a different encoding and render them in a font built for that encoding. But it would be nice to have unicode characters render properly. Also, thanks for the library. It has been very useful so far.

**Comment by DeepakKapiswe** [comment]
Hello @qburst-blesswin I am having similar issue, can you please elaborate on your solution, this will help us a lot.

**Comment by DeepakKapiswe** [comment]
still having same issue can you help @diegomura ?
