### ISSUE TITLE
Source Code for @react-pdf/pdfkit?

### ISSUE THREAD

**Issue by arahansen** [diegomura/react-pdf#460]
**Describe the bug**
This project takes a dependency on what appears to be a fork of pdfkit. But I'm not able to find the source code for this dependency.

Is this dependency (and other related projects?) hosted anywhere? if not, are the differences between the fork and its upstream documented anywhere?

**Comment by diegomura** [comment]
All dependencies are hosted under the `react-pdf` org. You can find pdfkit fork here: https://github.com/react-pdf/pdfkit

**Comment by arahansen** [comment]
ah cool that makes sense. What's the rationale for not hosting the renderer lib there?
