### ISSUE TITLE
Dynamic two column layout using flexWrap breaks after first column

### ISSUE THREAD

**Issue by blesswinsamuel** [diegomura/react-pdf#466]
**Describe the bug**
I'm trying to create a dynamic two column layout where text flows to the second column after the first column is filled and then to next page after the second column is filled and so on (trying to replicate [CSS columns](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns)). When trying to create this layout using flexDirection as `column` and flexWrap as `wrap`,  page breaks occur after the first line in second column. I expect the page breaks to happen only after the second column is filled.

**To Reproduce**
[react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00400e043013814cc50329409e01b14c02f0c0378c0140c5753620099d02598039805c3008c003003494d4100cdf000f00228d530288dc0700e4a17005700b66017f41c2c40752408e2280ee86e16813aa80231048e8a247b19d28002c3a76dd40242dfb47240061105c7b4500624e4e00264e00664e4b6b6a3b07272c3c14450830d714c1005f725048586077465c3a2cfc225211145100712410132f5e1813570f0e002200566e005201eea6d6f6ceae12d2f068183a106006800a01001e7155f53428003e2b182d8005041602686cc212327a26560e04ee1822a2e39a2d80354614130c06ef83ba2150e83a8a08acb140d8542c2fa0848004124219b0003a213b4d4eb547a3d63c6e0012831006b1436020eb62692d4467599288871813200d45c6249c6818fa5c119cc8a2a4a8bf7fa0229d83b993a1c0941dd2ad55a8e1f09f2d800559a47000cb3008246956c00f41ad111c8d7f00622745c9d095be868b498ada74345cae88a36ed80fb7431d89006e72390004a28040c8cee20018863c141758ad8001a000)

**Expected behavior**
Page break should happen only after the second column is filled. (that is after Line 72 in the above example. and not after Line 37)

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/815723/51785957-aee22780-2183-11e9-868d-219a1bca9e20.png)

Expected (edited using photo editor. that's why spacing is slightly off in the 2nd column):
![image](https://user-images.githubusercontent.com/815723/51785999-7727af80-2184-11e9-87dd-31fde1e85db3.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Chrome v71
 - React-pdf version: v1.2.0

**Comment by diegomura** [comment]
Thanks for reporting this. Unfortunately it’s not something we support right now. Not as easy as might seem. Anyway, it duplicated (check #305)
