### ISSUE TITLE
React-pdf do not work correctly in ios 12

### ISSUE THREAD

**Issue by montmirail** [diegomura/react-pdf#468]
**Describe the bug**
In ios 12 react-pdf doesn't seem to work either in Safari nor Chrome:
- Chrome : the print screen do not open
- Safari : print only one page and in the wrong format, A4 instead of A6

**To Reproduce**
Try to print a pdf on an iPad with these snippets

***Print Component*** 
```
const Invoice = (itemsCount) => {
    const pages = [];
    for(let i = 0; i < itemsCount ; i++) {
        pages.push(i + 1);
    }

    return (
        <Document>
            <Page size="A6" style={styles.page}>
                <View>
                    <Text>Footer content</Text>
                </View>
            </Page>

            {pages.map((el) => (
                <Page key={el} size="A6" style={styles.page}>
                    <View>
                         <Text>Footer content</Text>
                     </View>
                </Page>
            ))}
        </Document>
    );
};
```

***Call function***
```
<BlobProvider document={Invoice(delivery.items_count} fileName="somename.pdf">
     {({ blob, url, loading, error }) => 
        <NewDelivery onClick={() => this.print(blob)}>Print</NewDelivery>
     }
</BlobProvider>
```

***Print  function***
```
print = blob => {
        const frame = document.createElement('iframe');
        frame.style.visibility = 'hidden';
        const src = window.URL.createObjectURL(blob);
        frame.src = src;
        document.body.appendChild(frame);
        frame.contentWindow.focus();
        frame.contentWindow.print();
 };
```
**Expected behavior**
The pdf should contain the desired number of page and in the right format

**Mobile (please complete the following information):**
 - OS: iOS 12
 - Browser: Chrome/Safari
 - React-pdf version: v1.2.0

**Comment by acomito** [comment]
I had weird behavior as well

**Comment by mks1948** [comment]
Hello,
Does anyone solved this problem?
In my ios system, is display only one page of PDF.

**Comment by diegomura** [comment]
Keeping https://github.com/diegomura/react-pdf/issues/714 to track mobile browser issues
