### ISSUE TITLE
Add a consistent way of applying default props and styles

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#47]
We dont have yet a neat way of defining and appying what are the default props and styles to be applied to elements. 

I imagine something like:
```
class Text extends PDFEntry {
  defaultProps = {
    // props here
  }

 // ...
}
```

**Comment by jbovenschen** [comment]
I'm ok with implementing something like this, but is there any need to name it defaultProps? It could be just named props right?

Also how do you think we can preserve the changed props within the PDFEntry instance?

**Comment by jbovenschen** [comment]
Did implement it for only the props at this moment. I think it would be a good idea to split up the styling related properties (created with `Stylesheet.create`) and the other properties. What do you think?
