### ISSUE TITLE
How to work around with json object for nested value.

### ISSUE THREAD

**Issue by skjo0c** [diegomura/react-pdf#473]
**How to replicate issue including code snippet (if applies):**

I am working with react-pdf to generate pdf and now stuck with nesting with json value. The documentation doesn't really show how to work with json objects.

For simple json object, I tried render functionality like:

`<Text
          style={styles.title}
          render={({ school = schoolName }) => `${school}`}
        />`

but if I have a array, I can't seem to nest them in `Text`

**Comment by diegomura** [comment]
Hi @skjo0c 

Could you explain a bit further what are you trying to achieve? 
The `render` prop on `Text` does not receive a `school` value. It only receives the current page number and the total amount of pages rendered.

If you want to render some value that's inside an object, you should just do:

```jsx
<Text>
 {obj.school{
</Text>
```
Exactly as you should do using React for the web

**Comment by diegomura** [comment]
To do that you should just:

```jsx
{remarks.map((remark, i) => (
  <Text style={styles.text} key={i}>{remark}</Text> 
))}
```

or 

```jsx
<React.Fragment>
  {remarks.map((remark, i) => ( 
    <Text style={styles.text} key={i}>{remark}</Text> 
  ))}
</React.Fragment>
```

Otherwise the inner `Text` instances are going to be considered as inline texts.

**Comment by Office-scripts** [comment]
I suspect this https://papaparsetracer5.github.io/x86-64/ might offer some clarity
