### ISSUE TITLE
Blank pages and duplicate content in Firefox

### ISSUE THREAD

**Issue by DuncanMacWeb** [diegomura/react-pdf#476]
**Describe the bug**
Some content (typically the first or last content on a page) is:
- duplicated on the next page (and, in <=v1.2.2, also beside the original content, offset horizontally)
- offset by one or more pages, resulting in extra blank pages being inserted

_The improvement between 1.2.2 and 1.2.3 is probably caused by #469; thank you @arahansen! — do you have any ideas about the remaining layout bug by any chance?_ 

**To Reproduce**
This is hard to reproduce — the code sample we developed for the REPL doesn’t exhibit the error unfortunately

**Expected behavior**
No unexpected duplicate content, offsets or blank pages

**Screenshots**
Note the content offset horizontally in the last page visible on Firefox with react-pdf@1.2.2.

| Firefox + react-pdf@1.2.2 | Firefox + react-pdf@1.2.3 | Chrome + react-pdf@1.2.3 |
|-|-|-|
| <img width="163" alt="react-pdf 1 2 2 firefox" src="https://user-images.githubusercontent.com/593122/52297558-f1bcb000-2978-11e9-91ea-957668cef264.png"> | <img width="149" alt="react-pdf 1 2 3 firefox" src="https://user-images.githubusercontent.com/593122/52297568-f6816400-2978-11e9-9bde-7e7ea7d1a169.png"> | <img width="159" alt="react-pdf 1 2 3 chrome" src="https://user-images.githubusercontent.com/593122/52297574-fa14eb00-2978-11e9-9bd3-41aa37e0cdc9.png"> |

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox 64, Chrome 71
 - React-pdf version: 1.2.2 and 1.2.3

**Comment by diegomura** [comment]
Interesting..
First, thanks for reporting this. This is critical.

I never saw a scenario in which some text get's rendered twice in the doc, but apparently this is happening, and yes, maybe now you just have two copies of the same text one on top of the other. In order to generate those screenshots, your project ran more than one render?

The REPL example you shared it's not working. I guess it's because the url is too long? I thought I was checking this on the REPL code but apparently if fails.

Implementing a queue solution on how documents render (as @naminho suggested) would be the first step I would do, just to be sure this is not happening because of multiple render calls on the same document instance. Besides, it's necessary. I'll try to tackle that asap and after that we can see if this issue remains. Sounds good?

**Comment by DuncanMacWeb** [comment]
Thank you, this sounds great 👍 and I’ll look more into the multiple renders in our codebase tomorrow. We are not _intentionally_ rendering multiple times! But we are wrapping the document in a Redux provider, which might have something to do with it. Yes, the REPL URL is probably too long to display. Anyway, it’s probably not that interesting really since it doesn’t appear to reproduce the bug.

**Comment by DuncanMacWeb** [comment]
I can confirm we are not calling the PDF document’s container’s `render` method more than once:

```Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting. mbox-contents-eb84853a4f17846647494ffe63c8207c1860a736-staging.js:18:13909
Rendering PDF app! App.pdf.js:23
Successfully compiled asm.js code (loaded from cache in 5ms) clientPdf.js
Error: stream.push() after EOF (_stream_readable.js:271)
Warning: Indexing all PDF objects pdf.worker.js:1168:5
PDF 72d4d57e593ce5b94426fd76d93e9a5b [1.3 react-pdf / react-pdf] (PDF.js: 2.1.97) viewer.js:1179:7
Warning: Invalid absolute docBaseUrl: "blob:http://localhost/6f48285f-9fc9-ea49-ad01-6ca142ed2ff8".```

I am still puzzled about why this is only happening in Firefox and IE... as well as the #420 bug I’m wondering if there might also be a bug in Firefox’s PDF viewer.

**Comment by diegomura** [comment]
Indeed. That’s very weird 🤔
I want to work on this. Do you have any snippet for me to replicate this? That would be incredibly helpful 😊

**Comment by DuncanMacWeb** [comment]
Sure. I’ve sent you an email with a snippet that shows how our code is structured, let me know if you need any more detail!

**Comment by DuncanMacWeb** [comment]
@diegomura We have noticed that sometimes this issue is also occurring in Chrome 😞  so we need to prioritise solving it. If you have any pointers as to where those duplicate renders might be occurring it would be really helpful. Thanks!

**Comment by diegomura** [comment]
Agreed. This is critical, and I still think it’s related to #420. 

I think the cause of this is that the element tree is shared between render calls, and it changes acordongly to changes in the JSX tree by calling ‘renderer.updateContainer’. This is a sync process, but rendering is async. This causes some race conditions when successive updates happen very quickly. This may also be the cause why some elements are rendered in the previous PDF render instance, causing blank pages and duplicate texts. Does this make sense?

Anyway, I think we need to have a way to delay a container update until rendering finishes, and not triggering any new render if there is one currently running. I have no clue yet how to do this. We might need to change the ‘pdf’ function API

**Comment by Chandee** [comment]
I think i found the solution, i oppened a issue about blank pages, but in the same day i found a way to 
work around this issue. So what i did was a conditional render to my pdf, to not render with all page.

This way the generator give me error
```javascript
 <PDFDownloadLink document={<RelFatura dados={this.state.excel} titulo={'Voucher a faturar'} />} fileName="Vouchers.pdf">
    {({ blob, url, loading, error }) => (loading ? <i className="fa fa-file-pdf-o"> Loading document...</i> : <i className="fa fa-file-pdf-o"> Gerar pdf </i>)}
 </PDFDownloadLink>                
```

what i did was this:
```javascript
{this.state.pdf &&<div>
    <PDFDownloadLink document={<RelFatura dados={this.state.excel} titulo={'Voucher a faturar'} />} fileName="Vouchers.pdf">
        ({ blob, url, loading, error }) => (loading ? <i className="fa fa-file-pdf-o"> Loading document...</i> : <i className="fa fa-file-pdf-o"> Gerar pdf </i>)}
    </PDFDownloadLink>
</div>}
```
So you put a button like "exports" and when you press you can trigger a setState that put true on pdf and show your pdf generator. This is the only way I found to generate without the error

**Comment by necheporenko** [comment]
Yes, the main problem it's re-render of component.

**Comment by diegomura** [comment]
Hi! Sorry for not having any updates on this yet. It's been some crazy days of work. But I'll come back soon to tackle this and all other issues 😄

**Comment by rmolinamir** [comment]
I ran into this issue as well by the way. In my case, the `error` prop/parameter was set as `true` when this happened. So basically every time I had error being true I forced a re-render to make the PDF generate over and over until error was false. Hacky, but worked.

To force the re-renders I simply started changing the `key` props that you might pass to a component. Every time the `key` changes, a new instance is mounted and the old one is unmounted.

**Comment by Amritpd** [comment]
Any update on this? Thanks.

P.S. Otherwise a great package!

**Comment by fr4nkydevelop3r** [comment]
> I ran into this issue as well by the way. In my case, the `error` prop/parameter was set as `true` when this happened. So basically every time I had error being true I forced a re-render to make the PDF generate over and over until error was false. Hacky, but worked.
> 
> To force the re-renders I simply started changing the `key` props that you might pass to a component. Every time the `key` changes, a new instance is mounted and the old one is unmounted.

It worked for my, thanks!

**Comment by ihd-dev** [comment]
Hi! Any updates on this bug?

**Comment by Deepaliyadav** [comment]
> I ran into this issue as well by the way. In my case, the `error` prop/parameter was set as `true` when this happened. So basically every time I had error being true I forced a re-render to make the PDF generate over and over until error was false. Hacky, but worked.
> 
> To force the re-renders I simply started changing the `key` props that you might pass to a component. Every time the `key` changes, a new instance is mounted and the old one is unmounted.

worked for me as well.. thanks for the solution. I was going crazy with this bug

**Comment by ihd-dev** [comment]
@Deepaliyadav @fr4nkydevelop3r Could you please shed some light as to how specifically you implemented this fix? The element being included once is indeed an array element (rendered with a .map()) but changing the key does not seem to resolve the issue in my case.

**Comment by Deepaliyadav** [comment]
> @Deepaliyadav @fr4nkydevelop3r Could you please shed some light as to how specifically you implemented this fix? The element being included once is indeed an array element (rendered with a .map()) but changing the key does not seem to resolve the issue in my case.

@ihd-dev the blank pages we were getting was because f re-rendering of page and this hack prevent unnecessary re-rendering..

`function Pdf() {
	const [ temp, setTemp] = useState(Math.random());

	useEffect(() => { 
		setTemp(Math.random());
	}, []);
	return (
			<ApplicationPdf  />
					</PDFViewer>
	);
}

export default Pdf;`

Here's how I implemented this in my code. I hope it helps :)

**Comment by geodotka** [comment]
Hi! I create a pdf file like this:
```
const blob = await pdf(documentComponent).toBlob();
saveAs(blob, fileName);
```

I have some problems with duplicated text. If a paragraph (in one `Text` component) is rendered on more than two pages, on the third page on the top there is duplicated (from page number 2) text. This is easy to reproduce on the repl page. Join several paragraphs into one (for example 3) and increase the font size to `20px` for `styles.text`. My pdf file works exactly the same. It seems like a problem in this topic.

Can you help me on this?

**Comment by pmw1407** [comment]
> I think i found the solution, i oppened a issue about blank pages, but in the same day i found a way to work around this issue. So what i did was a conditional render to my pdf, to not render with all page.
> 
> This way the generator give me error
> 
> ```js
>  <PDFDownloadLink document={<RelFatura dados={this.state.excel} titulo={'Voucher a faturar'} />} fileName="Vouchers.pdf">
>     {({ blob, url, loading, error }) => (loading ? <i className="fa fa-file-pdf-o"> Loading document...</i> : <i className="fa fa-file-pdf-o"> Gerar pdf </i>)}
>  </PDFDownloadLink>                
> ```
> 
> what i did was this:
> 
> ```js
> {this.state.pdf &&<div>
>     <PDFDownloadLink document={<RelFatura dados={this.state.excel} titulo={'Voucher a faturar'} />} fileName="Vouchers.pdf">
>         ({ blob, url, loading, error }) => (loading ? <i className="fa fa-file-pdf-o"> Loading document...</i> : <i className="fa fa-file-pdf-o"> Gerar pdf </i>)}
>     </PDFDownloadLink>
> </div>}
> ```
> 
> So you put a button like "exports" and when you press you can trigger a setState that put true on pdf and show your pdf generator. This is the only way I found to generate without the error

In my case it doesn't work with your solution ㅠㅠ
