### ISSUE TITLE
REPL source code

### ISSUE THREAD

**Issue by kishaningithub** [diegomura/react-pdf#477]
The [REPL](https://react-pdf.org/repl) in the site is totally amazing. It really helped me get upto speed. 
I want to know where can i find the source code of the REPL. i couldn't find it in this repo.
Thanks in advance!

**Comment by kishaningithub** [comment]
I am actually curious on how you rendered the PDF on the right. It blends with the site very well and does not using any pdf to image conversion techniques. I also noticed that the `PDFViewer` uses iframes, I personally prefer to avoid that. 

I am very new to this. Any pointers to say a blog's etc would also be really helpful

**Comment by diegomura** [comment]
Hey @kishaningithub !

You can find the source code of react-pdf's site [here](https://github.com/react-pdf/site), including the REPL part.

In order to render the PDF on the right I'm not using the `PDFViewer` that's shipped with react-pdf but  the confusingly homonymous library [react-pdf](https://github.com/wojtekmaj/react-pdf). 

I don't have any blog post to share unfortunately, but I hope the code itself is self-explanatory enough to answer your questions about how you can achieve something like the REPL. Isn't that easy, but it's not a lot of code 😄

**Comment by mankityau** [comment]
Is there any plan for making this part of the feature?

**Comment by LinusU** [comment]
Here is a `PDFViewer` component that you could use, that works using the same technique as the REPL:

```javascript
import React, { useEffect, useState } from 'react'
import { pdfjs, Document, Page } from 'react-pdf'
import { pdf } from '@react-pdf/renderer'

pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`

const PDFViewer = ({ children }) => {
  const [pdfUrl, setPdfUrl] = useState(null)

  useEffect(() => {
    const child = React.Children.only(children)

    pdf(child).toBlob().then(blob => {
      setPdfUrl(URL.createObjectURL(blob))
    })
  }, [children])

  return (
    <Document file={pdfUrl}>
      <Page renderMode='svg' pageNumber={1} />
    </Document>
  )
}

export default PDFViewer
```

**Comment by arminydy** [comment]
On top of LinusU comment, if you wanna add pagination to it you can do something like this. I have digged the answer from [https://github.com/diegomura/react-pdf-site](here)

`import React, { useEffect, useState, useCallback } from 'react';
import { pdfjs, Document, Page, Outline } from 'react-pdf';
import { pdf } from '@react-pdf/renderer';

pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

const PDFViewer = ({ children }) => {
  const [pdfUrl, setPdfUrl] = useState(null);
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(null);

  const onDocumentLoadSuccess = useCallback((document) => {
    const { numPages: nextNumPages } = document;
    setNumPages(nextNumPages);
    setPageNumber(1);
  }, []);

  const onItemClick = useCallback(
    ({ pageNumber: nextPageNumber }) => setPageNumber(nextPageNumber),
    [],
  );

  const changePage = useCallback(
    (offset) => setPageNumber((prevPageNumber) => (prevPageNumber || 1) + offset),
    [],
  );

  const previousPage = useCallback(() => changePage(-1), [changePage]);

  const nextPage = useCallback(() => changePage(1), [changePage]);

  useEffect(() => {
    const child = React.Children.only(children);

    pdf(child).toBlob().then(blob => {
      setPdfUrl(URL.createObjectURL(blob));
    })
  }, [children]);

  return (
    <Document
      file={pdfUrl}
      onLoadSuccess={onDocumentLoadSuccess}
      onItemClick={onItemClick}
    >
      <Outline
        className="custom-classname-outline"
        onItemClick={onItemClick}
      />
      <Page renderMode='svg' pageNumber={pageNumber} />
      <div className="Test__container__content__controls">
        <button
          disabled={pageNumber <= 1}
          onClick={previousPage}
          type="button"
        >
          Previous
        </button>
        <span>
          {`Page ${pageNumber || (numPages ? 1 : '--')} of ${numPages || '--'}`}
        </span>
        <button
          disabled={pageNumber >= numPages}
          onClick={nextPage}
          type="button"
        >
          Next
        </button>
      </div>
    </Document>
  );
}

export default PDFViewer;`

**Comment by WebDev-Akhil** [comment]
@arminydy @LinusU 

Hey Armin!

Thanks for the above custom PDFViewer with pagination. It still works after 1 year. 

One problem I found is when the user clicks on the 'next' button, it shows page 2 as expected(assuming there are 2 pages in the pdf) but if some value is changed twice in a row on the left side (i.e client side - where the user can edit the text), the PDFViewer will automatically shift to page-1 instead of continuing to show page-2. Any tips on fixing this? so that the PDFViewer stays on whichever page the user has navigated to.

**Comment by decodelab** [comment]
> Here is a `PDFViewer` component that you could use, that works using the same technique as the REPL:
> 
> ```js
> import React, { useEffect, useState } from 'react'
> import { pdfjs, Document, Page } from 'react-pdf'
> import { pdf } from '@react-pdf/renderer'
> 
> pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`
> 
> const PDFViewer = ({ children }) => {
>   const [pdfUrl, setPdfUrl] = useState(null)
> 
>   useEffect(() => {
>     const child = React.Children.only(children)
> 
>     pdf(child).toBlob().then(blob => {
>       setPdfUrl(URL.createObjectURL(blob))
>     })
>   }, [children])
> 
>   return (
>     <Document file={pdfUrl}>
>       <Page renderMode='svg' pageNumber={1} />
>     </Document>
>   )
> }
> 
> export default PDFViewer
> ```

when I passed the children component it showed a blank white section.. what is the problem?

**Comment by nastopendo** [comment]
> > Here is a `PDFViewer` component that you could use, that works using the same technique as the REPL:
> > ```js
> > import React, { useEffect, useState } from 'react'
> > import { pdfjs, Document, Page } from 'react-pdf'
> > import { pdf } from '@react-pdf/renderer'
> > 
> > pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`
> > 
> > const PDFViewer = ({ children }) => {
> >   const [pdfUrl, setPdfUrl] = useState(null)
> > 
> >   useEffect(() => {
> >     const child = React.Children.only(children)
> > 
> >     pdf(child).toBlob().then(blob => {
> >       setPdfUrl(URL.createObjectURL(blob))
> >     })
> >   }, [children])
> > 
> >   return (
> >     <Document file={pdfUrl}>
> >       <Page renderMode='svg' pageNumber={1} />
> >     </Document>
> >   )
> > }
> > 
> > export default PDFViewer
> > ```
> 
> when I passed the children component it showed a blank white section.. what is the problem?

I fixed similar issue by using canvas as a renderMode: `renderMode="canvas"`. SVG render mode seems to be deprecated.

**Comment by WagdySamih** [comment]
Hey Guys
`renderMode='svg'` is now deprecated in the latest version `9.0.0`

Is there a way to achieve similar behavior, So that I can make text selectable?
`renderMode='canvas'` doesn't accomplish this 

<img width="422" alt="image" src="https://github.com/diegomura/react-pdf/assets/45714046/6681ea4f-8ee6-436a-8650-ef3811d2e11d">
