### ISSUE TITLE
Ability to set Headers on asset requests

### ISSUE THREAD

**Issue by hjnilsson** [diegomura/react-pdf#478]
**Is your feature request related to a problem? Please describe.**
I am generating a PDF which would include images that require login and headers set to access.

**Describe the solution you'd like**
The ability to give the renderer a `AssetHeaders` (or similar) object. This way it will be possible to set the `Authorization` header. Then pass it along as headers to `fetch` here: https://github.com/diegomura/react-pdf/blob/master/src/utils/image.js#L159

**Describe alternatives you've considered**
Right now I'm contemplating if I have to download all the files locally, and then fetch them from the local filesystem. But this will not work for the client-side render.

**Additional context**
Nothing of note.

**Comment by DuncanMacWeb** [comment]
Hi @hjnilsson! Good shout — it would be great to be able to supply different headers for each image if possible, as you might be retrieving images from various origins etc. Of course they would need to comply with [CORS restrictions](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests) in the browser.

@diegomura how about aligning with the React Native API for this, to make it easy to reuse code? They [accept an object with URI and headers](https://facebook.github.io/react-native/docs/images#network-requests-for-images) in the `source` property of their `Image` component. We could keep the [contract we’ve already established for the `src` prop](https://github.com/diegomura/react-pdf/blob/master/index.d.ts#L92) — it’s also nice for people coming from the web who are used to `src` — but just give the `source` prop priority if it’s specified, implementing React Native’s interface for it. As far as I can tell, that is:

```
source: <packager-metadata> | {
  uri: String; // can be a data URI
  method?: String;
  headers?: {
    Pragma?: String;
    // probably any other valid header
  };
  body?: String;
  cache?: 'default' | 'reload' | 'force-cache' | 'only-if-cached';
}
```

So to implement this feature, you could just make react-pdf handle the `headers` property appropriately.

So to play nicely with the interface we have already, in pseudo-code this might be

```
if this.props.src is an object:
  source = { ...this.props.src, ...this.props.source };
if this.props.src is a string:
  source = { ...this.props.source, uri: this.props.src };
// proceed with usual logic, based on the content of the `source` object
```

How does this sound?

**Comment by diegomura** [comment]
Hey! Yes. I think we should go this way. I was actually researching about it and sounds good to me. 
My apologizes for being unresponsive these past days. I'm out of town, without that much connection.

I don't mind tackling this when on my return, but if some of you guys want to give a shot please do!

**Comment by hjnilsson** [comment]
The solution proposed by Duncan would be solve my problem well. :)

**Comment by DuncanMacWeb** [comment]
@hjnilsson nice! Would you like to make a PR?
