### ISSUE TITLE
textAlign is not working

### ISSUE THREAD

**Issue by ycruzb** [diegomura/react-pdf#480]
**OS:** Windows

**React-pdf version:** 1.2.0

**Description:** I'm trying to center text using textAlign but isn't working, the text still looks left aligned

**How to replicate issue including code snippet (if applies):** Your own code doesn't work here: https://react-pdf.org/styling

**Comment by ycruzb** [comment]
I'm implementing "On the fly rendering" using a download link and applying textAlign to center text. There is some help around here ?

**Comment by diegomura** [comment]
Could you provide a snippet for me to replicate what you are experiencing? 
I tried and it's working fine. You can see it in action on the [REPL](https://react-pdf.org/repl) example's title

**Comment by ycruzb** [comment]
this code isn't working for me:

```
const pdfstyles = StyleSheet.create({
  page: { backgroundColor: '#fff' },
  sectiontitle: { color: '#000', textAlign: 'center', marginTop: 30, marginRight: 30, marginBottom: 10, marginLeft: 30 },
   entityheading: { fontSize: 26 , textAlign: 'center', marginBottom: 0 },
});

<PDFDownloadLink
    document={<Document>
                <Page size="A4" style={pdfstyles.page}>
                    <View style={pdfstyles.sectiontitle}>
                        <Text style={pdfstyles.entityheading}>
                            {this.props.entityDetails.name}
                        </Text>
                    </View>
                </Page>
            </Document>}
    fileName={`${JSON.parse(element).name}-${JSON.parse(element).id}.pdf`}>
        {({ blob, url, loading, error }) => (loading ? 'Loading...' : 'Download')}
</PDFDownloadLink>
```

this code works on the REPL but it doesn't work on my app, I download the pdf through the button but the text still looks left aligned

**Comment by diegomura** [comment]
Indeed. This option is broken in last version. The issue was introduced [here](https://github.com/diegomura/react-pdf/commit/b58be53c9fe073104e1cf811d5b0855447062b5a)

We will need to come with a different way not translating lines for cloned elements, plus adding more tests so this doesn't happen again 😓

**Comment by ycruzb** [comment]
Hi Diego, I hope you are well. Got your message, I want to thank you for your amazing work.  For an additional feedback, the text is left aligned in Windows but in macOS it looks center aligned, is that weird ?

**Comment by diegomura** [comment]
You're very welcomed 😄 
That is weird. I'm using macOS and I don't see it centered. Are you sure you are running the same react-pdf version on both OS?

**Comment by ycruzb** [comment]
Hi again, yes we are using the same version, my partner sent me an screenshot from his iMac and i certainly didn't believe it !

**Comment by zsimoes** [comment]
Same symptons here. MacOS High Sierra, Firefox 65.0, React 16.6.3. Weird though - I downgraded @react-pdf/renderer to 1.2.3 and I still get the same bug 😕

**Comment by JoshBowdenConcepts** [comment]
I am running into these errors still. I am running macOS Catalina, Chrome 90.0. I am only getting the erro when trying to do a textAlign right however. Does anyone have this working?

**Comment by SheldonNunes** [comment]
textAlign was not behaving correctly for me either but I was able to solve with a workaround with flex & alignSelf:

```
<Text style={{ display: "flex", alignSelf: "center" }}>
    Centered Text
</Text>
```
