### ISSUE TITLE
Text component removes last letter 'i' when text ends to 'fi' when font family is used

### ISSUE THREAD

**Issue by anttikekki** [diegomura/react-pdf#511]
**Describe the bug**
Text component removes last letter 'i' when text ends to 'fi' when font family is used

**To Reproduce**
```
const Test = () => (
  <Document>
    <Page>
      <View style={styles.view1}>
        <Text>With fontFamily: fi</Text>
        <Text>With fontFamily: ki</Text>
      </View>

      <View style={styles.view2}>
        <Text>Without fontFamily: fi</Text>
        <Text>Without fontFamily: ki</Text>
      </View>
    </Page>
  </Document>
);

Font.register(
  'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf',
  { family: 'Oswald' },
);

const styles = StyleSheet.create({
  view1: {
    fontFamily: 'Oswald'
  },
  view2: {
  }
});

ReactPDF.render(<Test />);
```

[REPL example](https://react-pdf.org/repl?code=3187b0760ce02e00402a05368c0bc30050129503e0c0a061801e0044460057016c130a1d0a24801404301cc1479e7880d40258200ee31a004f0036085006f49322003a006ec24404600be3d79f44003c1807541500058c0066e0a003136d50548900b86e0e201e88c326fa247e38669636768eceae1e00d65ebe08c67abc3e42a28c017c69628ab20a50d2486a1a004cba9929c1a1162094b0b6f4912eee9e3ec1150689a6e63575e18d4ecdb1f1ed81a91ac924deec5c7a3ee454b4f48c9800dcf8f8f676ca004e081c82d0083be84c00e4165050000e106edede0d502a1cd06c5082c0caa0d4de10de2008088d8520009b79549a0033378009a007d38001a5f8003610000384c20550008c00aaa0a8751e1000d00271b0008254e515dac67000d130e43641b446067003c90241a0b38c1b4ccb586d4090582e420a818001940a321945810082837cf6ef043a0e44c75289341e6d6f09e4d0e7737960b3930853ad281aadf86d08bf00025041b1805016291ecbb3a2838ee86222190de1c08a8000)

**Expected behavior**
Expected pdf:
```
With fontFamily: fi
With fontFamily: ki
Without fontFamily: fi
Without fontFamily: ki
```

Actual pdf:
```
With fontFamily: f
With fontFamily: ki
Without fontFamily: fi
Without fontFamily: ki
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox 64
 - React-pdf version: REPL at 2019-03-01 and v1.4.0

**Comment by kallelat** [comment]
We are experiencing the same issue with @react-pdf/renderer 1.3.3

Font used https://fonts.gstatic.com/s/firasans/v6/nsT0isDy56OkSX99sFQbXw.ttf

**Comment by diegomura** [comment]
Thanks for reporting this. It seems we are having some ligatures issue when it’s at the end of the paragraph.  I’ll take a look today at this
