### ISSUE TITLE
image cant be loaded from firebase

### ISSUE THREAD

**Issue by ksethi2211** [diegomura/react-pdf#516]
**Describe the bug**
I cannot load images from my firebase account to the pdf. only blankspace is shown

**Expected behavior**
Image should render

**Snippet**
```
const MyDocument =(
      <Document>
        {filteredImages.map((data, i) =>{
          let url = data.imageURL
          return(
            <Page size="A4" style={newstyles.page}>
              
              <View>
                <Text>{data.title}</Text>
                
                <Image
                  style={newstyles.image}
                  src={url}
                  allowDangerousPaths ={true}
                />
              <Text style={newstyles.url}>{url}</Text>
              </View>
          </Page>)
        })}
```

[somename (1).pdf](https://github.com/diegomura/react-pdf/files/2924825/somename.1.pdf)

**Comment by ksethi2211** [comment]
i am trying to print images stored on my firebase account but there is just blank space shown on pdf.

`const MyDocument =(
      <Document>
        {filteredImages.map((data, i) =>{
          let url = data.imageURL
          return(
            <Page size="A4" style={newstyles.page} wrap={false}>
              
              <View>
                <Text>{data.title}</Text>
                
                <Image
                  style={newstyles.image}
                  src={url}
                  allowDangerousPaths ={true}
                  fixed={true}
                />
              <Text style={newstyles.url}>{url}</Text>
              </View>
          </Page>)
        })}
        
      </Document>)`

[somename (1).pdf](https://github.com/diegomura/react-pdf/files/2924817/somename.1.pdf)

**Comment by ksethi2211** [comment]
i am trying to print images stored on my firebase account but there is just blank space shown on pdf.
```

const MyDocument =(

{filteredImages.map((data, i) =>{
let url = data.imageURL
return(
          <View>
            <Text>{data.title}</Text>
            
            <Image
              style={newstyles.image}
              src={url}
              allowDangerousPaths ={true}
              fixed={true}
            />
          <Text style={newstyles.url}>{url}</Text>
          </View>
      </Page>)
    })}
    
  </Document>)
```
[somename (1).pdf](https://github.com/diegomura/react-pdf/files/2924819/somename.1.pdf)

**Comment by ksethi2211** [comment]
i am trying to print images stored on my firebase account but there is just blank space shown on pdf.

```
const MyDocument =(
      <Document>
        {filteredImages.map((data, i) =>{
          let url = data.imageURL
          return(
            <Page size="A4" style={newstyles.page}>
              
              <View>
                <Text>{data.title}</Text>
                
                <Image
                  style={newstyles.image}
                  src={url}
[somename (1).pdf](https://github.com/diegomura/react-pdf/files/2924822/somename.1.pdf)

                  allowDangerousPaths ={true}
                />
              <Text style={newstyles.url}>{url}</Text>
              </View>
          </Page>)
        })}
```

**Comment by ksethi2211** [comment]
i cannot load images from my firebase account to the pdf. only blankspace is shown

```
const MyDocument =(
      <Document>
        {filteredImages.map((data, i) =>{
          let url = data.imageURL
          return(
            <Page size="A4" style={newstyles.page}>
              
              <View>
                <Text>{data.title}</Text>
                
                <Image
                  style={newstyles.image}
                  src={url}
                  allowDangerousPaths ={true}
                />
              <Text style={newstyles.url}>{url}</Text>
              </View>
          </Page>)
        })}

```
[somename (1).pdf](https://github.com/diegomura/react-pdf/files/2924825/somename.1.pdf)

**Comment by diegomura** [comment]
Hey @ksethi2211 

For future scenarios please fill the issue template yourself with the asked points 😄 

Unfortunately, I cannot see what's going on by the provided data. All I can suggest is that you check that the Image `src` is actually a valid image url, and that you are providing all the correct headers to fetch the image.

Labeling this as `incomplete` until further information

**Comment by ksethi2211** [comment]
hey @diegomura 
sorry i am a new both to react and git,

issue is: i expect to see the image from the image url which i entered which as u mentioned is a valid url: 

`https://firebasestorage.googleapis.com/v0/b/proof-of-execution-redington.appspot.com/o/images%2F291b6e11-4af9-4ce9-b72c-373ae08956fd.png?alt=media&token=d04327cb-cedd-4f6d-b2f5-60cea739727c.`

i am fetching this url by reading database in firebase itself.

as i have printed the url also in pdf the data is accessible.

as attached the pdf is also printing just fine except the image is not being shown.

System information:
OS: Mac OS Mojave Version 10.14.3
Browser: Google Chrome Version 72.0.3626.119 (Official Build) (64-bit)
React version 16.8.3
@react-pdf/renderer version 1.4.0

this is my entire code to generate the pdf:
```
import { Page, Text, Image, View, Document, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
.......

const newstyles = StyleSheet.create({
     .....
      image: {
        marginVertical: 15,
        marginHorizontal: 100,
        height: 300,
        flexGrow: 8,  
        padding: 10,
      },
    });

const MyDocument =(
      <Document>
        {filteredImages.map((data, i) =>{
          let url = data.imageURL
          return(
            <Page size="A4" style={newstyles.page}>
              
              <View>
                <Text>{data.title}</Text>
                
                <Image
                  style={newstyles.image}
                  src={url}
                  allowDangerousPaths ={true}
                />
              <Text style={newstyles.url}>{url}</Text>
              </View>
          </Page>)
        })}
        
      </Document>)
    
    const PDF = () => {
      return (
        <div>
          <PDFDownloadLink document={MyDocument} fileName="somename.pdf">
            {({ blob, url, loading, error }) =>
              loading ? "Loading document..." : "Download now!"
            }
          </PDFDownloadLink>
        </div>
      );
    };


.......


<PDF/>//to call PDFDownloadLink
```


Please tell me any more information u need e.g. in terms of code

P.S. I really appreciate the prompt response, Sir.

**Comment by nultron** [comment]
I've got a similar issue, where my image is a String made by base64. Here it is:

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gA8Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBxdWFsaXR5ID0gMTAwCv/bAEMACAYGBwYFCAcHBwkJCAoMFA0MCwsMGRITDxQdGh8eHRocHCAkLicgIiwjHBwoNyksMDE0NDQfJzk9ODI8LjM0Mv/bAEMBCQkJDAsMGA0NGDIhHCE......

(And it still continues)

This is stored in MongoDB (MLab) and I would really like to display it on the PDF, since it is the users profile image. What can I do? Thanks a lot

**Comment by geeksambhu** [comment]
@nultron I am able to render pdf image with png base64 string , Here is my sample setup 
```
     <Page style={styles.body}>
                <Text style={styles.title}>{data[key].title || key}</Text>
                <View style={styles.container}>
                    <Image cache={false} style={styles.containerImage} src={data[key].image || data[key]} />
                        {weekData}
                </View>
       </Page>
```

**Comment by diegomura** [comment]
@ksethi2211  I just tried the firebase image and the reason why it doesn't load is because or a CORS issue. 

<img width="739" alt="Screen Shot 2019-03-20 at 1 12 43 AM" src="https://user-images.githubusercontent.com/5600341/54658660-4b9eb280-4aad-11e9-8c88-7dec0c5122da.png">

So the issue appears not to be in react-pdf itself but on the source of your images. You should probably whitelist the domain you would like to render pdfs in order to work. Closing this until further details

**Comment by MianUmer486** [comment]
The CORS issue is occuring in chrome whereas its working fine in firefox , what might be the reason , kindly help

**Comment by app-arianamini** [comment]
@ksethi2211  How you fix that problem? I have the same issue with my images.

**Comment by r-bt** [comment]
I was able to fix this by setting the CORS for my firebase cloud storage bucket following the answer at: https://stackoverflow.com/questions/37760695/firebase-storage-and-access-control-allow-origin/37765371 

My `cors.json` looks like:
```javascript
[
  {
    "origin": ["http://localhost:3000"],
    "method": ["GET"],
    "maxAgeSeconds": 3600
  }
]
```

**Comment by SH-Stark** [comment]
Hello, I have the same issue. The cors.json didn't work for me. 
Anyone found a workaround ? @ksethi2211 I have the same problem as you

**Comment by stgsegovia** [comment]
Hello, I have the same problem as @ghost

I can't see an image saved in Firebase.
Storage rules are correct and if you click the link from different devices you can see the image

<img width="420" alt="Screenshot_4" src="https://user-images.githubusercontent.com/93876394/164976009-b48d83fc-5f9f-4824-8efc-7e6d3d57b292.png">

Has anyone been able to fix it?

**Comment by JasonK97** [comment]
I'm having the same issue, it's not with CORS, and I keep getting a TypeError that ctx.embedImage is not a function. The url is correct, and converting it to Base64 doesn't do anything.

**Comment by FelipeQq** [comment]
> I was able to fix this by setting the CORS for my firebase cloud storage bucket following the answer at: https://stackoverflow.com/questions/37760695/firebase-storage-and-access-control-allow-origin/37765371
> 
> My `cors.json` looks like:
> 
> ```js
> [
>   {
>     "origin": ["http://localhost:3000"],
>     "method": ["GET"],
>     "maxAgeSeconds": 3600
>   }
> ]
> ```

It worked for me, thanks!
