### ISSUE TITLE
Add textDecoration line-through support

### ISSUE THREAD

**Issue by LukasBlu1** [diegomura/react-pdf#519]
Hello,

I tried to use the textDescoration attribute as shown in the following example.
Line-through isn't working but is very important for invoices.
Am I doing something wrong or is there another solution?

Thank you in advance.

```
const styles = StyleSheet.create({
lineThrough : {
textDecoration: 'line-through',
textDecorationStyle: 'solid',
textDecorationColor: 'grey',
}, ... })

<Text style={styles.lineThrough}>{priceBeforeDiscount}</Text>
```

**Comment by diegomura** [comment]
You are not doing something wrong. It’s simply not supported yet.

**Comment by LukasBlu1** [comment]
Thank you for your quick response.

**Comment by DuncanMacWeb** [comment]
@diegomura where would be the best place for @LukasBlu1 or anyone to start with a PR to implement this?

**Comment by diegomura** [comment]
Also textkit 😅 Which I already said I was refactoring it. I'm very close of having a working version. I think the best would be for these tickets to wait some more days until I have a clearer picture how we can implement this
