### ISSUE TITLE
Data not rendered on PDFStream

### ISSUE THREAD

**Issue by TheBob55** [diegomura/react-pdf#520]
**Describe the bug**
This defect is when using dynamic data, the pdf doesn't render with the data.  Hence, a data driven report will not work when using ReactPDF.pdf(PDFComponent(data)).toString().  Also I have tried using ReactPDF.renderToStream(PDFComponent(data)).  Both have provided blank documents.  Where PDFComponent is an exported tsx component that uses the normal react-pdf components.  I'm using Nodejs to create these PDFs.  I've also noted that when I do a regular render with a file path, everything renders as expected.

IE: ```ReactPDF.render(PDFComponent(data), `${__dirname}/pdfFile.pdf`);```

The file solution does not work for what I am trying to accomplish.  I realize the version I'm giving you is stripped down to the actual version, but in principal remains that no data shows up on the report output. 

Am I using something incorrectly?  This could just be a knowledge gap on my end.

**Code**
PDFComponent.tsx:
```
/* eslint react/prop-types: 0 */
/* eslint react/jsx-sort-props: 0 */

import * as React from 'react';
import { Page, Document, StyleSheet, View, Text } from '@react-pdf/renderer';

// Create styles - Works
const styles = StyleSheet.create({
  flexColumnContainer: {
    flexDirection: 'column'
  },
  flexChildGrow: {
    flexGrow: 1
  },
  container: {
    paddingHorizontal: '20pt',
    paddingBottom: '20pt',
    height: '100%',
    flexDirection: 'column'
  }
});

// Create Document Component
export default (details) => (
  <Document>
    <Page style={[styles.flexColumnContainer, styles.flexChildGrow]}>
      <View style={[styles.flexColumnContainer, styles.flexChildGrow, styles.container]}>
        <Text>{details.stuff}</Text>
        <Text>{details.numbers}</Text>
        <Text>{details.other}</Text>
      </View>
    </Page>
  </Document>
);
```

**server.ts**
```
import bodyParser from "body-parser";
import express from 'express';

import PDFComponent from "./components/PDFComponent";
import ReactPDF from "@react-pdf/renderer";
// Constants
const PORT = 8080;
const HOST = '127.0.0.1';

// App
const app: express.Application = express();
app.use(bodyParser.json());

app.post('/export-pdf', async (req, res) => {
  const data = {
    stuff: 'Stuff',
    numbers: 123,
    other: 'Other stuff'
  };
  const pdfString: string = await ReactPDF.pdf(PDFComponent(data)).toString();
  const buf = Buffer.from(pdfString, 'utf8');

  res.set('Content-disposition', 'attachment; filename=GEMReport');
  res.set('Content-Type', 'application/pdf');
  return res.send(buf);
});

app.listen(PORT, () => {
  console.log(`Running on http://${HOST}:${PORT}`);
});

export default app;
```

**Comment by tkreis** [comment]
I know this issue is almost a year old, but i was wondering did you solve it in the end @TheBob55 ?
