### ISSUE TITLE
`textAlign: "right"` fails inside flexbox

### ISSUE THREAD

**Issue by siefkenj** [diegomura/react-pdf#523]
Inside a `<View>` with `display: flex, flexDirection: "row"`, setting a child with `textAlign: "right"` causes it to leave its container and appear on the far right of the page.

```
const Quixote = () => (
  <Document>
    <Page style={{margin: 20}}>
      <View style={{display: "flex", flexDirection: "row", marginBottom: 70}}>
        <Text style={{flexGrow: 1}}>Left</Text>
        <Text style={{flexGrow: 1}}>Right</Text>
      </View>
      
      <View style={{display: "flex", flexDirection: "row"}}>
        <Text style={{flexGrow: 1, textAlign: "right"}}>Left</Text>
        <Text style={{flexGrow: 1}}>Right</Text>
      </View>
    </Page>
  </Document>
);

ReactPDF.render(<Quixote />);
```

The first `<View />` renders as expected, but the second one does not.

[REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f098c780273e48c002e180098003005f4ded3a72a00d490600ee31858c9120099208001c44f212a011003331295c01a189e30506891643180a091c0dd64404d7c6065e5140085d0a041185401d8b47438f528a8005503602dc4a4025001c4624c540119b588006431dca0a801e84a50d9f20b8b4bcca1442a24ab6b631b9a009490f8002d3a7b4b7506ba8d4dd6f4070ab6cdcaad6c1c9c5c603cbde2ab8343c323942eeb5d9af7f57acb472d2abca7ea601a7e4c1f400822205a3d5cb205b2c5e3a36875ba1f1da0c3e23319592675198e9e64b15b22dedd038a3babc013adba740633158ec02001b8c8ccd986078e12e0d00062003a50981ac18591e0a888543a0b05d62232c8400)

**Comment by diegomura** [comment]
Thanks for reporting this. Appalrently just `flexGrow` fails. If you define it like `flex` it works fine. [REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f098c780273e48c002e180098003005f4ded3a72a00d490600ee31858c9120099208001c44f212a011003331295c01a189e30506891643180a091c0dd64404d7c6065e5140085d0a041185401d8b47438f528a8005503602dc4a40250540119b588006431dca0a801e84a50d9f20b8b4bcca1442a24ab6bea009490f8002d5a3b4b757ada8d4d16f47b0a56cdcaad6c1c9c5c603cbde2ab8343c323948e62e3ea37f53acb072d2abd6afd30ba010444a7af5cb229acd5cf5268b5da4f35af49e032195946303a8e92633399421eed2db43dabc0122dda740633158ec02001b8c854f186078e12e0d00062003a50981ac18591e0a888543a0b06d62052c8400)

**Comment by diegomura** [comment]
Couldn't find a way of fixing Yoga measure function for this case without breaking many other cases. Since just `flex` works, for the moment please use it. Closing this until other cases

**Comment by VictorBaudot** [comment]
So, how do you right align your text ?
