### ISSUE TITLE
`render` method doesn't get proper page numbers when inside a `View`

### ISSUE THREAD

**Issue by siefkenj** [diegomura/react-pdf#525]
When using `fixed`, the following renders the page number as appropriate:

```
      <Text fixed render={({ pageNumber, totalPages }) => (
        `${pageNumber} / ${totalPages}`
      )} />
```

however, if the `<Text />` is wrapped in a `<View/>`, `pageNumber===1` and `totalPages===undefined` on all pages.

```
<View fixed>
      <Text render={({ pageNumber, totalPages }) => (
        `${pageNumber} / ${totalPages}`
      )} />
</View>
```

**Comment by diegomura** [comment]
Same as #470. Happens when dynamic element is not fixed. Tried to fix it before but breaks some other stuff. Closing this in favor of the first one
