### ISSUE TITLE
Support 'Helvetica-BoldOblique' and 'Times-BoldItalic'

### ISSUE THREAD

**Issue by siefkenj** [diegomura/react-pdf#526]
Bug #164 references 'Helvetica-BoldOblique' and 'Times-BoldItalic' as included-by-default font families. However, they don't appear to work in the REPL (I haven't tested them locally).

**Comment by diegomura** [comment]
No. They are not. Please see [here in our pdfkit fork](https://github.com/react-pdf/pdfkit/blob/master/lib/font/standard.js#L14) and [here in react-pdf itself](https://github.com/diegomura/react-pdf/blob/master/src/font/standard.js#L1).

We don't currently include this for size purposes. These data tries really makes the lib much much heavier. I understand that this can be frustrating but I did this in the very beginnings (you can observe that many of these aren't there anymore) so the library wasn't like 2mb heavy.

I would like to include them in the future if we find a way of dynamically import them if they are being used, but that's not the case nowadays. I realize we have a lot to improve about fonts. I wish I have more time to work on it

**Comment by diegomura** [comment]
Supported in latest version
