### ISSUE TITLE
Document import problem

### ISSUE THREAD

**Issue by atifaziz2** [diegomura/react-pdf#527]
Hi!

I am trying to run react-pdf examples to see how code is working.

i am getting error while run this commond
yarn example -- fractals

and the error is
react-pdf/examples/fractals/index.js: Unexpected token (8:2)

6 |
7 | const doc = (

8 | <Document
| ^
9 | title="Fractals"
10 | author="John Doe"
11 | subject="Rendering fractals with react-pdf"

Environment

Browser : Google chrom
React-PDF version: 4.0.5
React version : 16.3.0

**Comment by diegomura** [comment]
It seems that Babel is not converting React elements. Did you installed the dependencies first?

**Comment by atifaziz2** [comment]
@diegomura i have installed all dependencies.
