### ISSUE TITLE
Regex error when used with a minifier that turns unicode characters into ASCII

### ISSUE THREAD

**Issue by oskarkook** [diegomura/react-pdf#529]
If `ascii_only` is set to `true` on [`uglify-js`](https://www.npmjs.com/package/uglify-js#output-options), `react-pdf` will throw the following error:
```js
SyntaxError: invalid range in character class
```

Issue stems from [`hyphen`](https://github.com/ytiurin/hyphen/blob/master/hyphen.js#L100). 1.4.1 version of this package is unusable with Create React App in its default configuration, as [CRA has `ascii_only` set to `true` by default.](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L216-L218)

[Here is my initial report](https://github.com/diegomura/react-pdf/pull/504).

**Comment by oskarkook** [comment]
In particular, ``/\s|[\!-\@\[-\`\{-\¿]/`` gets turned into ``/\s|[\!-\@\[-\`\{-\\xbf]/`` which is not valid:
```js
/\s|[\!-\@\[-\`\{-\\xbf]/.test('');
```

**Comment by depimomo** [comment]
Yes, I face this problem too.

**Comment by joseviniciusnunes** [comment]
I'm also having the same problem after generating the creat-react-app build through react-scripts

Error: Invalid regular expression: /\s|[\!-\@\[-\`\{-\\xbf]/: Range out of order in character class

Does anyone have a solution?

Thank you!!!

**Comment by oskarkook** [comment]
Current solution is to use 1.4.0. I've opened a PR in hyphen, but who knows if/when it will be accepted.

**Comment by diegomura** [comment]
Thanks @oskarkook !
Otherwise we will just have to fork it and publish a new version under `@react-pdf` scope. Let's wait some days or otherwise just follow that path

**Comment by joseviniciusnunes** [comment]
I'm sorry to be lazy

But how do I change the version of hyphen if it is as dependency of @ react-pdf / renderer ??
