### ISSUE TITLE
Style is not implementing

### ISSUE THREAD

**Issue by atifaziz2** [diegomura/react-pdf#532]
```
import React, { Component } from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: { padding: 60 },
  title: { marginTop: "40%" },
  emphasis: { fontFamily: 'Helvetica-Bold', color: '#F22300' },
  breakable: { width: '100%', height: 100, backgroundColor: 'tomato' },
  unbreakable: { width: '100%', height: 400 },
});

class App extends Component {
  render() {
    return (
      <Document>
        <Page style={styles.page} size="A4" wrap>
          <Text style={styles.title}>This is a <Text style={styles.emphasis}>breakable</Text> component. You can see how it wraps to the next page:</Text>
          <View style={styles.breakable} />
          <Text style={styles.title}>This is an <Text style={styles.emphasis}>unbreakable</Text> component. Instead of wrapping, it jumps to the next page:</Text>
        </Page>
      </Document>
    );
  }
}

export default App;
```

This code is not giving expected result as shown in ReactPDF documentation.

 - OS: Linux
 - Browser: [All Browser]
 - React-pdf version: 1.4.1

**Comment by diegomura** [comment]
Could you be more precise? I just checked on [the REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a000efc3005f18109002f71008802080166d3003b80271ef3da74e5400a8614b1a78a951446395091431cb8ad800b24081860981e6a7b473537314967390c4679009e75083f0023530c1e006b1e4cb12a007a28b6185064f016285918004d10044a9e30350c2c00906350d8330b10a810182800ac3007584501002e52f2ab6b6a0035240c5ee778d88f596cdc82a2951812a5eb3b2998f76df74f6f5f7f2090b0b6c8cbadd75bd92494b4e0bf04181f6f942b14ca5352155e435563d40092904c0f000263010000cc4ce6793c890603e00068fa300015931e4431198c269719861e6e0c719da8255e00896a53a03198ac7601000dc64216811157190e06000651da4bc6183ab00723c4c1e0241c3a6cc60121822991c8bc5f135003600030c194048e1787cf4ad4c1183c531f0f1b6103c935da7d09a00a4460b4707ea974a6bb5e8f014000623c4612044424d401c800121811000dde548600f000b40021100899109a268044205322600c41180132d600cc2693427cd96ca3030e6210c9890c8b1a26008ccdef49660e3241f002504d70e4d44cc8f180793e2999a6064401850b15c4f0c1dc356ffb2880cee836ddae31f6073004dcf474489d4e67302f59bfdca0150a004ab960140b81a023590720dc30530f02a110541d02c14e2fc80000) and at least that part seems to be working fine

**Comment by codeawy** [comment]
When trying to style Text components with inline styles, the styles now work at all 😢

`    <View style={styles.header}>
      <Text style={styles.fullName}>Muhammad Naga</Text>
      <Text style={styles.jobTitle}>Muhammad Naga</Text>
    </View>`
