### ISSUE TITLE
Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 1.)

### ISSUE THREAD

**Issue by paintedbicycle** [diegomura/react-pdf#536]
**Describe the bug**

In Safari, there is now a new error, where there wasn't in previous versions.

> Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 1.)

The PDF then never renders in Safari.
This doesn't happen in Chrome.

**To Reproduce**
Make and render a PDF in browser, using Safari.

```
    <PDFViewer style={{ height: '100%' }}>
      <Document>
        <Page size="A4" style={PDFStyles.page}>
          <View style={PDFStyles.section}>
             [Content]
          </View>
        </Page>
      </Document>
    </PDFViewer>
```

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [e.g safari]
 - React-pdf version [e.g. v1.4.1]

**Comment by diegomura** [comment]
Thanks for reporting this. I couldn't replicate it in desktop. 
My OS is updated: macOS Mojave 10.14.3 (18D109).
Did you see this in desktop or mobile?

**Comment by paintedbicycle** [comment]
It was desktop, yeah, all up to date. Latest react, etc, etc.

I'll try to find some time in the next couple days to look into it further.

Paul

**Comment by paintedbicycle** [comment]
It appears this is a localhost only issue. Closing.

**Comment by paintedbicycle** [comment]
Ugh, this is back so reopening for now.

**Comment by paintedbicycle** [comment]
This appears to be caused by the use of `<PDFViewer>`. When I try to playground, it doesn't happen and when I comment out the viewer, I can render it a bunch of times in a row successfully.

It happens on both localhost and a custom domain (unlike what I previously reported). 

So, in Safari, it will sometimes render the PDF but then if you close the PDF and try again, it will often block - with the viewer opening, but a blank white PDF. Then, often closing the browser window and trying to render again will be successful. Other times you need to do that a few times. It's quite inconsistent.

I'd say the error rate is about 30-40 percent of the times trying to render the, so it's pretty frequent.

**Comment by paintedbicycle** [comment]
Hello!

Please let me know if there is anything I can get you to help troubleshoot and move this issue along. It effectively means Safari users can generate PDFs.

Thanks!

**Comment by ivantodorovich** [comment]
I've found this thread randomly, because I'm looking into the same Safari issue.

You might be interested in this:

https://stackoverflow.com/questions/53048734/safari-12-wont-download-a-pdf-blob
and this
https://bugs.webkit.org/show_bug.cgi?id=197441

Apparently it's a bug with Safari.

**Comment by tchakabam** [comment]
This issue happening on Safari is likely due to jamming the main event loop with either too long ticks i.e execution stacks. Or too many timeouts scheduled in a short time i.e too frequently.  

That is what I was able to conclude, while I was seeing this error with a completely different type of application that this PDF lib here.

It seems that some microtasks then just get dropped of the queue, which causes some of the async blob-data-extraction resolutions to just fail like this :) It seems to be somewhat cut off in the depths of the runtime, as at the JS layer I would see this error in the console, but there wasnt any place where I could actually catch this promise rejection anywhere that it would claim :) Sort of buggy behavior indeed, at least as the catch-handlers I set on those Blob#arrayBuffer methods never get called (in my case I dont convert the data to a file for download, but I get data as messages from an RTC channel, which uses blobs internally).

**Comment by andrewpolemeni** [comment]
I've had the same issue happen on iOS safari for Blob audio. It returns the URL but when you copy and paste it doesn't let you play the blob URL. Responds back with "The operation couldn't be completed. (WebKitBlobResource error 1)"

**Comment by diegomura** [comment]
Thanks @tchakabam for the explanation. Although I'm a bit lost on this subject. Do you think there's something on this lib side that can be done? Also, if possible try using the 2.0 that ships better memory usage, it might be solved as well. Thanks!

**Comment by sebastianpikand** [comment]
This issue is still not resolved...

**Comment by vikrant0526** [comment]
All in all it boils down to Safari being unreliable in terms of working with blobs and this [StackOverflow](https://stackoverflow.com/questions/68386273/error-loading-blob-to-img-in-safari-webkitblobresource-error-1) help me.

If you are presenting pdfs in a modal Safari still holds on to the blob and does not refetch the blob from the source which is most likely where the issue occurs.
This behaviour is also carried out when reloading, reopening a closed tab, and more often then not only resolves by restarting Safari.

Even if you are not normally caching, manually caching the blobs in the IndexedDB as array buffers and making a preference of reading from cache should take care of it.

Hope this helps.

**Comment by tchakabam** [comment]
@diegomura Hey, sorry about the long latency on replying :) To your clear question: I would try to put all the blobs needed to be processed - in the sense of extracting the ArrayBuffer data - onto a self-crafted queue. Just an array/list of these, and then just have them attempt to resolve one by one, if one fails, just schedule a retry with an immediate timeout (zero) or such.
