### ISSUE TITLE
PDF is not showing

### ISSUE THREAD

**Issue by atifaziz2** [diegomura/react-pdf#540]
Hi!

PDF is not showing when i deploy code, while its working fine on localhost.

**Expected behavior**
PDF show while code is deployed.

**Screenshots**
Error is attached

 - OS: Linux
 - Browser: chrome
 - React-pdf version  1.4.1
![react-pdf](https://user-images.githubusercontent.com/45995034/54739129-cd3f2f00-4bd8-11e9-81c0-82e31ee8b9b5.png)

**Comment by diegomura** [comment]
Fixed. I'll push a new version soon

**Comment by atifaziz2** [comment]
@diegomura can you please let me know when you will push new version? My project is ready to deploy but i am facing only this issue.

**Comment by diegomura** [comment]
Couple of hours 😄

**Comment by atifaziz2** [comment]
@diegomura you have update the code? should i update the version?

**Comment by diegomura** [comment]
I just did.

**Comment by atifaziz2** [comment]
should i update the version?

**Comment by diegomura** [comment]
Yes. If that's what you want

**Comment by atifaziz2** [comment]
@diegomura let me check and will update you

**Comment by atifaziz2** [comment]
@diegomura it's work fine. Thanks
