### ISSUE TITLE
Specify PDF language

### ISSUE THREAD

**Issue by Evanion** [diegomura/react-pdf#541]
**Is your feature request related to a problem? Please describe.**
The W3C specification for PDF, specifies a `Lang` attribute that tells screen readers what language the document, or section of the document is in.

**Describe the solution you'd like**
Component or optional prop on components that allows you to specify the language for the document or section of document.

**Additional context**
More information about it can be found here:
https://www.w3.org/TR/WCAG20-TECHS/PDF16.html
https://www.w3.org/TR/WCAG20-TECHS/PDF19.html

**Comment by diegomura** [comment]
Thank you! 
This is a `pdfkit` change. We use a fork of this lib for some custom stuff. Maybe it was already added in the project base. Otherwise I'll try to take a look soon
