### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by holzfelix** [diegomura/react-pdf#542]
**Describe the bug**
Compiation error while starting.

I got this error:

```
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at $$$reconciler (react-reconciler.development.js?b6f5:149)
    at Object.eval (react-pdf.browser.es.js?6576:5903)
    at eval (react-pdf.browser.es.js:6713)
    at Object../node_modules/@react-pdf/renderer/dist/react-pdf.browser.es.js (bundle.js:988)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:86)
    at eval (PDF.js:3)
    at Object../src/frontend/component/PDF.js (bundle.js:23250)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:86)
```

my code looks like this:

```
// Create Document Component
import React, {Component} from "react";

import { Document } from '@react-pdf/renderer';

import {connect} from "react-redux";
// Text editor
// CSS
// i18n
import {translate} from 'react-i18next';
import {compose} from "redux";

class PDF extends Component {
    constructor(props) {
        super(props);
        this.bindLibs();

        this.state = {
        };
    }

    render() {
        const {t} = this.props;

        return (
            <Document>

            </Document>
        );
    }

    /**
     * This function binds formatter functions
     */
    bindLibs = () => {

    }
}

export default compose(
    translate('translations'),
    connect()
)(PDF);
```

**Comment by diegomura** [comment]
You should always put at least one `<Page />` inside `<Document />`. Could you try that and see if this issue persist?

Also, you are not using a viewer for the document. Please check [PDFViewer](https://react-pdf.org/components#pdfviewer), [PDFDownloadLink](https://react-pdf.org/components#pdfdownloadlink) or [BlobProvider](https://react-pdf.org/components#blobprovider)

**Comment by holzfelix** [comment]
Already tried. Same issue.

Which react version is minium?
I also use Babel and we pack.

**Comment by diegomura** [comment]
Not sure. Any react version post Fiber should work.
Could you please provide a complete example so I can try to replicate it?

**Comment by holzfelix** [comment]
https://codesandbox.io/embed/319ozlynj6

Based on your example code

**Comment by diegomura** [comment]
Yep. You have to wrap the document in a `PDFViewer` in order to show it:

```jsx
import { Page, Text, View, Document,  PDFViewer, StyleSheet } from "@react-pdf/renderer";

export default class MyDocument extends React.Component {
  render() {
    return (
      <PDFViewer>
        <Document>
          <Page size="A4" style={styles.page}>
            <View style={styles.section}>
              <Text>Section #1</Text>
            </View>
            <View style={styles.section}>
              <Text>Section #2</Text>
            </View>
          </Page>
        </Document>
      </PDFViewer>
    );
  }
}
```

Just in case, unfortunately the lib has issues running in [CodeSandbox](https://github.com/diegomura/react-pdf/issues/462). But that's how you should use it in your project. I'll try to update docs if they are misleading 😄

**Comment by holzfelix** [comment]
I think there are more issues. 
I installed the package. But Intellij is not able to find your Components.

![Ashampoo_Snap_2019 03 22_07h16m08s_007_](https://user-images.githubusercontent.com/6866699/54804069-78e88d80-4c72-11e9-9dcd-ad741f057ad9.png)

**Comment by holzfelix** [comment]
I switched back to v1.4.0 same issue. 

![Ashampoo_Snap_2019 03 22_08h26m11s_008_](https://user-images.githubusercontent.com/6866699/54807057-4479cf00-4c7c-11e9-8b66-dc02a8a67796.png)

**Comment by holzfelix** [comment]
Now I a bit closer to working solution. It runs and compiles. 

Now I got this: `__WEBPACK_IMPORTED_MODULE_6__react_pdf_renderer__.a.render is not a function`

**Comment by holzfelix** [comment]
hm okay I tried this:


                            ```

const MyDoc = (
    <Document>
        <Page>
blubb
        </Page>
    </Document>
);

<PDFDownloadLink document={MyDoc} fileName="somename.pdf">
                                {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
                            </PDFDownloadLink>
```

And here I got this error:
```
react-reconciler.development.js?e81a:8735 The above error occurred in the <PAGE> component:
    in PAGE
    in DOCUMENT (created by Document$$1)
    in Document$$1

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

```

Also an example from the docs: https://react-pdf.org/advanced#on-the-fly-rendering

**Comment by holzfelix** [comment]
Ah now I got it. 

```const MyDoc = (
    <Document>
        <Page>
            <View>
                <Text>Section #1</Text>
            </View>
        </Page>
    </Document>
);```

Works fine but nothing is selectable. text looks like image

**Comment by holzfelix** [comment]
working now.

**Comment by ellej16** [comment]
Hi @holzfelix ! can you post your working solution here? trying to make react-pdf work for mine as well!

**Comment by apareek85** [comment]
@holzfelix 
Please share the fix, waiting for your reply now for so long. thanks

**Comment by holzfelix** [comment]
I did non use this package

**Comment by Nsengiyunva** [comment]
> I did non use this package
Okay. but please post your working solution while using the package react-pdf/renderer.
