### ISSUE TITLE
Long Render Time 

### ISSUE THREAD

**Issue by modemmute** [diegomura/react-pdf#544]
**Describe the bug**
The below code is taking about 10 seconds to render a three page document using the `<PDFViewer>`. The code currently iterates over a ~80 item array of objects and as the number of items in the array increases this render time gets longer.

**To Reproduce**
I am using the following code:

```
import React, { Component } from 'react'
import { PDFViewer, Document, Page, View, Text } from '@react-pdf/renderer'
import { flatStrips } from './flatStrips'

class App extends Component {
  
  render() {
    return (
      <div className="App">
      
        <PDFViewer>
          <Document>
            <Page>
              {flatStrips.map((strip,i)=>(
                <View key={i}>
                  {strip.scene && <Text>{strip.scene}</Text>}
                  {strip.ie && <Text>{strip.ie}</Text>}
                  {strip.set && <Text>{strip.set}</Text>}
                  {strip.dn && <Text>{strip.dn}</Text>}
                  {strip.desc && <Text>{strip.desc}</Text>}
                </View>
              ))}
            </Page>
          </Document>
        </PDFViewer>

      </div>
    )    
  }
}

export default App;
```

[REPL Here](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e01bc019801b1e5003294004e480038400748c792bc79a22a500689016cc4f076194a8035241803b8c00d618027b6114802f908bc246ee5550860162c003230ea00150c14367f0540e0d0cf2a007a18b8e24f735f1804bd555b1808e8d8f880a5228c548cf2ecdcdf02a48c5852aa4c8ac4aa8856dace86bcd14ad500133012c88efae6aaf1fefa9ca1ca59b18c60c9b2acd5d1f5e005aca5bcf49b7b1f61020223cb34de011f74ba0666567602006e32325048584969391e8203818001b438225cbfc006e2079000b860007200118f0c0600c3c891fa5c9f1e4200412911600404824b8e13253124b245372b65a793299c5e94099f4e138c392cca2ed8288a4400c478f246148c0a3180c980000b0c28cc9181c6e5827a281dc303cdc929f8eb6d708a0486601b38a0460bca01053650d5ca280d0782e1b4c01060243b260a4e66e424f469121c02ede8011c102c108ba00fa4851a0a00acc000330a2c43c00133a780000660001d8f300466cf670b00161476693d98ccab8451a8f4311d9de4c0a3c079061a40ac17a74b004e002d29707e5a8b67d3f0f8fc7e1d5d5097b3002d244713c2cc87086170c1654eb9c7c613895eba6b7a95ae4616f7944672200a2000d2895e606cc140164008232288c0851f80129becfb7277958b7800720024b810038b017b20a0010ba28e0c02018862120c01203c04830342480401eb02003aae1983c8fa0c048180621c28c302b2b1a30131c09fae88b13c302288602c0be2004852940200c0000ca128473e769281a9ea82bf6cfaea0235a30216ad91a2685eb3b66cfb9a968a9dea72ac876f6a3aceb223425ead9ba1ea0a42920f2340cf9fac000641b220004a12bd1491818611b9e866b6319c6c8a2649ba6798f0fd860f1956001b188c5a9665bc500070a2c028c6233e0d936300b6b93b69db76a15227da164388ed9bc551266f0a960d7a6f3896cbab64a79e48959b9060481f0b2940b2a0aba57150241a30a95d551e99514995165951f1951f15517995169551fd951c5b6d6a6a9336a9736a90b4c0002133e289f00030a12ac20a49b3ed0860b28dd6ea7a5d73e620a0767de525406f64d72003cfba2c6ae19347eee86812040ba54810040e04f09a522e50604f7ba601f02ba506b84250948b0822c8aeead81e44b06210d2c8ba6cf8de4883e4fa9ead3be5f8fe7fa01c058082941304794cee4fcb008295db86303026118209c0ba1301d8f2b48aa2fea2b8ae8a8c4ad44f28b15dbc8b02cb1fb308a2b9aa149264c99aa0add7081d4a9d9aa8e992db90699d64ed5ae92005a2c15a94faa6660a9673e367bdf663950339fe91aee5225e4203e733fe58091b1e3ebd6b1826c9a45d168c7152689725e5ba5997a6a32e58db36c14765da606545555616c3ad5f5635a58b54ba2972722cfaf5fd60dbd9a46948dd038d9345dd76ddef4e9ad93d2f78f82a4f50b7d9de9eff6b023eb6a0f436bee4c03c388f239d794ee8f738cc078cac04cf044ceedd33ee4d1e416aa54e750f6b6f4f4102d522cf229fb7ebf801406b610248979bf37820299126b422d45810f018042dd5206300a6dd505b64e465280db444859d3126550694f323b434c699fb697769ed578fb5324e9fd99640eee9de958214bf55b0b9372dcd913216c4f1dc322740a2788a9a730a19ca2bf66ce0949289602e195803a6144a5df2a157ac95d4aaf601cc39eb8d53aa9399ba1656e6d4750772ea382bb9f501a435911e67ee83cc684d61aad92eabd3bac89e7b0869e8e227a7d45e488fe8033b1b9037b833f1c20779713de28c6894023e0344f99f7c817caf8931be64c09053341a789fa0a5a1afd3aa335f2ef47fbb37fe5cdfd87e0009a60385b2232212028be1422c45a528a1e0b290026013027c497c3012b0f2180000e922181b01589cb0f4fd3810b0756c83ed2a0aea5920c72966caa093010f52c432d8ce376ad8f497b032fc2a919b074d422c95b4e041cec8392722c223a20c1431ce3aaa3f23c29383f54e655c2a6718a39cf3a48d4a1954621678cf23cb915651d5d546557510dcb443542c4d4f47b701041338377331f74ac56cd1ac3d2da8f77173d1eb3d5c5ce33c522db42bdbd92f7f150d02452e09bbc918a3728a309d0c4b2000174be3fe2ecc00350d0214aa13b24a2c4780a8220540e80b01a46201f0c81000) This contains a shorter version of the data array, as the REPL couldn't share a link with the full data. All styles were removed to ensure that the slowness wasn't caused by any other factors.

The REPL works fine but when using `<PDFViewer>` on localhost the render times are extremely slow. A full build running on a live server shaves about one second from this render time. 

I have tested the render time of the Document taking `<PDFViewer>` out of the code and it renders in a few milliseconds. I can't seem to work out what is causing the delay. Also of note, the browser seems to freeze as this delay is happening. When trying to use the dev tools console during the delay, it is unresponsive until the render is complete. I have tried different versions of the above code for a few days now, simplifying it in each iteration. The above code is very simple and running in its own brand new create-react-app application to ensure that no outside issues from the rest of the site are affecting it.

This issue is a concern as this sample document is only three pages long and my users will be creating documents that could be exponentially longer. 

**Expected behavior**
A`<PDFViewer>` render time in the ms range

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser Chrome 72.0.3626.119
 - React-pdf version 16.8.5

**Comment by diegomura** [comment]
Hey.

>  Document taking <PDFViewer> out of the code
What do you mean by that. Rendering the `<Document`> straight away?

> Also of note, the browser seems to freeze as this delay is happening.
Yes. This is something we should definitely try to improve. #464 discusses the idea of using node/web workers for the rendering process, but I couldn't find the way to make it work yet.

I'll try your snippet by adding more rows and let you know what I can figure out

**Comment by diegomura** [comment]
Quick test produced this:

![Kapture 2019-03-22 at 21 31 28](https://user-images.githubusercontent.com/5600341/54859270-0ca97080-4cea-11e9-8f4a-42c14c512c7b.gif)

I'm rendering 105 elements (14 pages of the doc) and yes, it takes some seconds but not 10 as you said. How 80 elements fits in only 3 pages? Not sure what's causing the rendering delay, but I couldn't replicate it

**Comment by modemmute** [comment]
Thanks for the quick reply @diegomura! Answers below:

> > Document taking  out of the code
>
> What do you mean by that. Rendering the `<Document`> straight away?

As a test I rendered the`<Document>` directly without wrapping it in the `<PDFViewer>`. It was raw, but rendered nearly instantly. Just so I understand the rendering process correctly, I'm guessing that the heavy lifting is being done by the `<PDFViewer>` and not when the `<Document>` is created?

> > Also of note, the browser seems to freeze as this delay is happening.
> 
> Yes. This is something we should definitely try to improve. #464 discusses the idea of using node/web workers for the rendering process, but I couldn't find the way to make it work yet.

Is this a known issue then?

> I'll try your snippet by adding more rows and let you know what I can figure out

Many thanks!

**Comment by modemmute** [comment]
> I'm rendering 105 elements (14 pages of the doc) and yes, it takes some seconds but not 10 as you said. 

Hm - In further investigating, I found that when running the Performance monitor in Chrome Dev Tools, the render time speeds up. Not sure how that is possible - could this be some sort of caching issue that is being cleared when recording starts in Performance?

>How 80 elements fits in only 3 pages? Not sure what's causing the rendering delay, but I couldn't replicate it

Sorry for the confusion, three pages is based on when the 80 rows are styled correctly. It is more pages when unstyled, naturally. 

It appears from your gif that there's roughly 5 seconds between pressing reload and the rendered page. This is better than my 10 seconds, but is still slow for less than a dozen pages of unstyled text. Would you say this is about average in your experience? My concern is when users create 30, 50 or 100 page documents it may appear that the browser is frozen. Any thoughts on what other people are doing when faced with this issue? Progress bar during render?

**Comment by diegomura** [comment]
> As a test I rendered the<Document> directly without wrapping it in the <PDFViewer>. It was raw, but rendered nearly instantly.

Well... that's because you are rendering HTML there. Inspect the page if you have doubts. But when the Document is not wrapped inside a viewer, React thinks the react-pdf primitives are dom nodes and render it like it.

> Is this a known issue then?

Yes. As I said, there's already an issue created for it.

> could this be some sort of caching issue that is being cleared when recording starts in Performance?

To be honest I don't know. That's very weird indeed

> (...) but is still slow for less than a dozen pages of unstyled text. Would you say this is about average in your experience?

I guess you could say that. I do agree that ideally this would be done much faster, but PDF generation like this is not an easy and cheap task. My efforts are always pointing into making the most performant tool as possible, but there are many things going on internally. Page-wrapping por example (breaking the whole document into pages) is also another factor that slows down the whole process. It has to consider not only top-to-bottom layouts but also more complex stuff. Also I would say that 1 of those "5 seconds" is the blob content being loaded by the browser.

I have many ideas in the future that I think will increase the project performance, but each piece of the project is quite big and complex, and I simply don't have enough free time to dedicate to it unfortunately

> My concern is when users create 30, 50 or 100 page documents it may appear that the browser is frozen. Any thoughts on what other people are doing when faced with this issue? Progress bar during render?

I don't get much feedback of people using the lib, so I couldn't say really. I guess you can implement your own worker solution on top of react-pdf if what you want is create big documents.

**Comment by wyqydsyq** [comment]
I've also ran into this issue, I'm generating a PDF which has a dynamic number of pages, 2+ pages causes the browser to lock up entirely for 5+sec which is pretty terrible UX.

Is there no way to defer / promisify the render process so it does not block the main UI thread? I've tried using a pattern like this:
```ts
  <BlobProvider
    document={
      <TableMenuPDF
        qrData={qrData.table}
        venueName={venue?.name || ''}
        handle={venue?.handle || ''}
      />
    }
  >
    {({ url, loading }) =>
      loading ? (
        <LoadingStatus />
      ) : (
        <Box padding={2}>
          <Typography variant="body1" gutterBottom>
            <strong>Note:</strong>
            <br /> Table Check-In QR codes <strong>
              do
            </strong>{' '}
            support COVID-19 Check-In
          </Typography>
          <Typography variant="body2" gutterBottom>
            In future versions they will support dine-in Table
            Orders if the feature is enabled for your venue(s)
            once released
          </Typography>
          <PDFViewer
            style={{
              display: 'flex',
              width: '100%',
              minHeight: '500px',
              border: 'none',
            }}
          >
            <TableMenuPDF
              qrData={qrData.table}
              venueName={venue?.name || ''}
              handle={venue?.handle || ''}
            />
          </PDFViewer>
          <WrapperLink
            href={url || ''}
            download={`${handle}-tables.pdf`}
            type="application/pdf"
          >
            <FullButton fullWidth endIcon={<DownloadIcon />}>
              Download
            </FullButton>
          </WrapperLink>
        </Box>
      )
    }
  </BlobProvider>
```

Which *kind of* seems to work in that I see a loading spinnter initially, but the whole window still locks up when it comes to rendering the PDF in `PDFViewer`.

I feel like this could maybe be solved nicely if the PDF rendering work could be moved to a WebWorker and by allowing `PDFViewer` to accept a `blob` from a loaded `BlobProvider`, rather than only accepting a `Document` VDOM as `children`

**Comment by hkar19** [comment]
Hello, i also experience issues like this.

is there a way to tell the document is loading and finished loading?
