### ISSUE TITLE
Error while save file

### ISSUE THREAD

**Issue by atifaziz2** [diegomura/react-pdf#545]
Hi!

I am saving pdf file to but i am getting this error 
_react_pdf_renderer__WEBPACK_IMPORTED_MODULE_5___default.a.render is not a function

**Expected behavior**
Save pdf file to given path.

 - OS: Windows
 - Browser: chrome
 - React-pdf version : 1.4.2

**Comment by diegomura** [comment]
I would need more information than that. A code snippet would be cool. But I would say that you are using ReactPDF.render in a web environment

**Comment by atifaziz2** [comment]
> I would need more information than that. A code snippet would be cool. But I would say that you are using ReactPDF.render in a web environment

Here is the code snippet, this is just reneder function

import ReactPDF from '@react-pdf/renderer';
import ReviewDocuments from './ReviewDocuments';

render(){
const { data } = this.state;
return <ReviewDocuments data={data} />
}

ReactPDF.render(ReviewDocuments, `${__dirname}/example.pdf`);

**Comment by atifaziz2** [comment]
> I would need more information than that. A code snippet would be cool. But I would say that you are using ReactPDF.render in a web environment

Yes i am in web enviornment

**Comment by diegomura** [comment]
`ReactPDF.render` is a Node only API. See how it's under [Node explanation](https://github.com/diegomura/react-pdf#node-save-in-a-file). To save a PDF document in the browser you should use [PDFDownloadLink](https://react-pdf.org/components#pdfdownloadlink), or [BlobProvider](https://react-pdf.org/components#blobprovider) and manually download the blob file
