### ISSUE TITLE
Image elements returns "skipped due to invalid dimensions"

### ISSUE THREAD

**Issue by 0FilipK** [diegomura/react-pdf#552]
**Describe the bug**
Image component seems to be broken. I tried many ways to render image in pdf but it always returns "Image with src [...] skipped due to invalid dimensions". Even if I used an image from examples folder `https://blog.oxforddictionaries.com/wp-content/uploads/mountain-names.jpg`. I tried local files, base64, external files. Did I do something wrong?

**To Reproduce**
Here is a codesandbox with simplest example: https://codesandbox.io/s/yjpk4nkk61

**Comment by 0FilipK** [comment]
I figured it out. It was caused by StyleSheet style but this error is misleading as hell. Just removed flexDirection and flexGrow and now it's works as expected.

**Comment by lulalachen** [comment]
Does that mean we cannot use flex box in any of its ancestors?

**Comment by diegomura** [comment]
Not necessarily, but there are some cases in which flexbox will cause issues on images. I couldn't still get exactly in which cases this happens

**Comment by aexol** [comment]
Old issue,but :) ,
```tsx
<View style={{flexDirection:'row'}}>
  <View style={{flex:1}}>
      <Image
        style={{
          width:'auto'}}
        src="/static/images/quijote1.jpg"
      />
  </View>
  <View style={{flex:1}}>
      <Image
        style={{
          width:'auto'}}
        src="/static/images/quijote1.jpg"
      />
  </View>
</View>
```
works. Just set width:'auto' on image as its not default here @diegomura

**Comment by aexol** [comment]
@0FilipK @lulalachen

**Comment by Isaac-Svi** [comment]
@aexol thanks 👍

**Comment by DewangS** [comment]
In my case none of the below image URLs worked.. please note, I don't keep images under the public folder of my React app. Images are stored under the src\assets\ folder.

`let imageURL = {uri:"../../../../assets/companyLogoLetterHead.jpg", method: 'GET', headers:{'Access-Control-Allow-Origin': '*'}}
`

**or**

`let imageURL = { uri: "../../../../assets/companyLogoLetterHead.jpg", method: 'GET', headers: {}, body: '' }`

It only worked by loading the image like below and using it as a source

`import companyLogo from '../../../../assets/companyLogoLetterHead.jpg'

      <View style={styles.centerImage}>  
          <Image style={styles.logo} src={companyLogo} />
      </View>

`

I used below settings for the style ..

```
logo: {
        height: '35mm',
          width:'70mm',
          marginTop: '5mm',
        backgroundColor: 'white',
        padding: 10
    },
```

**Comment by petatemarvin26** [comment]
if `width: auto` does not resolve, use `100%`
