### ISSUE TITLE
Inline images

### ISSUE THREAD

**Issue by DuncanMacWeb** [diegomura/react-pdf#553]
**Is your feature request related to a problem? Please describe.**
We need to be able to display images inline

**Describe the solution you'd like**
Inline images should display in the same/similar way as they do on the web. In summary, [images in this REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634c1fde1b1d1d33908047932a80a81f48049467e0c438f13d3339959246781553787820b660360004419680f0cac00cafc5e100c8011cea0d00232c96af13e18301940cbdd383e1e3c400b75004088403007800b86a58282d9a1ad268b460a03012890c0240019faa42180616a765e6f3a93615a38788c10041a9e62412878223e35268b23c4d490f54c2acb0ec8e9747a80bd8e4cd4311b19ceb24c3e9d4da8028b5410d511020f83c5b01b9aad6377478001a5f43084d4b008118f27f0c1233014520ecd4e88cc55b666087e3a6f7a5118086eb52ca18463c5a928ac06c901b526b4dd30254aad592c37cb7d2d30000bd5a2c180f1a048111896c2010f59bd5eed76c160860e45e8a4eaa385aa01810abdcd8e4cdfc4a19ac8600055302b44043d656155ea982300087101816d80ad0af6a9fb6303264310557c47902bf7deb7bde91b74660864a12c54bde4285631b6c6d941c30def2358f2906da988ac08afdb346d9567607e1018e6a8005fd53c4aa946483c64d0f00023f58ca820ccae1f7aee8c351ea911afb8097230b5bba38532660c0146d83b2fa97036d11265c8f0fb93a2b3f8d00b66796e5d07a0270c3c386da9341b32cdea602193e223766c656cb07abba89deab42d3dece198500e19cb0c083de146b00832e6d9b22036a1c4407288688528b5859c2ab0b184025a74ad2c50db80cc8a1ea7b90f95933120edb524076ace2465aae6d413c2f36a9435a250fc7f06000b1515482e0a422e4c2708d588a267a8601896238b6a04b6aba180b5945e953edf8c06eab4b2b3e4b2d9dfaa5fe7de0c37a2c0b92190a5370c200c6d44f0da85671b52438605eaa5f65e118351c65ae9375472a762d872b2996b77c42d37621a1dfda92da8b01020e2d2a5cb3cec022e5b9ca30140518f0a97b2658aa36332fb80062b61200b7d93da23be9804b34023b6a8da5ed49b9886f25d12cac34d745a1c28b14d280a5988283f2d53f8bc9ceb16ae8cf7a847a1c54b0b514c4f48e04c8000370c07c332f7758b627aa84fa42aca0b13dec93eddbee88126fe354362f23e8bec5660c34f62b02a318b05195bbe8ebb538e30352881988ede0876f6ce62a3a5f66a94d7a5208e1d82c273a362193343ca426734d8d0160e375266300e8fc82c010639ba87596b60f16028a14b32f781962e921c4c8c3234d8545a6d23d1e08868b4cf0ea0ef1e52fc4c9b0a2a76abf3672e689f40a671be34ca9354f4352ca1509d761eb4c7ad8ccaf2ff9280025cacf1a25df9aafb715f5bc46eb43edab4c5e2366964fb2123a31c9558c1715c370543015b3c000d684a50c499214952349d20c943cc9f7364ad1e23a36602c537b2a59a95dd2b1679ead09523d614221bb980010600903ca0d4e019b83453efd12d15f538369be3da2808e98a95052a021ca87c228c43c63c27f8343812820845095aa30b30c89512600004cb21e22a0dc4c5406b150001218103111512f8c433391c2202300192e8183f991d68e18c5322c6f4e99af1de2864994b20f32c1f873a0b6a81808381f292edd202ab35aa38fb228a80378b929e0bc483bfbb2194220fba1d55ea25feac328144da208d4f62b1f31b89813a33a27d0ae7c0c8bd34e8ac4fb0cb1e0558db167209284f49981e8c00ec0860a4761a1bde0f65c983b765b05f9a8b3247a845a7896160ba255bc80f259296205114331bd2dd1b008055394b9adf8ca0401948536c3ee0009a7d8202925a9facfa5897d4c02ec02a63cbed1631e3c9e95ae887366b7401b5443ac79b921a4ac499628862dacf018b1e31c5842c8ac70a7398dae63b075868ab665aaa998a60e79d7844934000529483057e0bc198f92fa686433dcbde6f4cf1b8b154b8f21f936d5b600095e81ed2c2218f7bc8f4acf05613342553d0a4b4154723a33d4985970a73a62f4c52a33d28407e8bb2b4214d9cfd0c8d29ad07c44d268f59401c08b6aa8316aa67a46373b4b596e1401a434e4a6c0f8ab1108a047220fd2760d28305717dc2660e4814107a3c85ac7a550a897462a37f20f292ed37b2c70c0201f7074445b6270a254c9a344193e2311c967344b1053937940185bbc8247107150cec0a73101b4a1aaa2fa7347959655c6201b0f25d6e781d8fa1683c598272954c294b3291e052c8523839a8743355678c58c815ca746503d467cbec19950abe609274470268ac265c0238198cc0fb3340c0429798a11edb58b3365046235d041a335ad1a1b3c331b98916b96c1e8350524a7c53b8724b37ac3dcb1cd6fe55b3e486535234d91882d83e9374406d4f203b38d01d90d23019525ddb0f62c92d8a226844cee0c17715efec7e2534cc6d4524cc05edb0883d917a63cb14148a94f291b64994b1d99b793266a8370ae1581f4bd819715101201e21f2006e3daf028c19b246c90174a548180b143ae80589d2ea8978a681291c7bc1501a50993312a6e9f4fbb5521e8342b0406fc0ee875a18516b9a3b7e1841924bcb0071f948140b3984e9179e66e11c3badc0242c49d500275efb2181490d95ec8844412018cfa713720e2a19b4d809052ee9d58e147d8fd5f7f6025393ec8f7240de81cafa678a62e70b06d4a6c18f1d456353a7b9efc6bd898e1d7ac48ba88608ad694bd8570d1180c35a20001cda9b958b19c18aa49faea28e38e7343bd7d2b4f4f1e01585621d3ab3fb4f5d819daf9fc1081697d746875c82dfd39003680235bc52c783e78009f665105dfb1e0f3e043f42d0a3055428808000724c153bd84882d2ec2483c01216c81da3b452a1ba0554bc0043de550441b02903c0da80001800120907b63021de8c7601c0641807f7a18b91104f6cc2a82fb808080386702815c0c05115a0320c3f70990e803042d0700804b32064051b80280b21fc1f00c69816c27dca0001c9cc140280f10202d20c8190876b03907c1d84f25904cd21064794c11551280c81b0d1000660c8d32003eb68000d2000d4001b08032b001d44006c7900789414bc6072e00068004e1e0001042ddda2808e1e9c0b18057665197210f49e9c0079080a2e441287a7301543a1427c4ea6c14738380600006531811f2c0958175113025d8e08a0543d2090870289286e4a83b4051fa452e002b03bca099fb3df000042e81577d255745e33f5832f622b2834a87f9eebe5000f1c1ef86034f870b9d4008f4813b0f7980bc2000b31798dfa02de39be0600dde14ac2b61eddf7b2728d558885773003dd7bb17f4e38277ca011cf4ed85ef9a1fbe0fe1ff48d12f0c9fa4267c2c79fdbf17cd395f9a0d7553b0095f99d467a463e000303ba1fbb935c39408fba7b9f993a5f88fb95a4f87fb5135fadfaafab03af8bb9bba7bb7bafb81f83ba9099fa703c053f8dfa4f85f90f8c044fa1c3dfacf93fbd3b0b00e2381081bfa703f7aa060e16fbd3b681c98402c40e2b45bef87783ba709e05e604e35132ba948f22aa35fbb7be0488580137ba30b7a484c01a23ffa0061c2841283843e79a87f04702583581d81085381406906205c06c877fb57a8f8e867025063f82f9ad1d823065028015229fb6f8cb38ea30700403903b1d918596351aa89bbac302a07a2603387186b034059861c2280ffa3036864f9882381403d20d86503a31f0133ba45dfbec03f9cf83852fa446b84cc1bba784305007a12bd9139901629580c41700d00a305399dad39500eb1a03ea012107900000) should display inline and be laid out just like words and emoji in the string children of the parent `<Text>` component.

**Describe alternatives you've considered**
React Native has the same issue, apparently, and people have come up with workarounds [like this](https://stackoverflow.com/questions/34532552/is-there-anyway-to-embed-image-in-text-in-react-native). However, when we have content that “just works” on the web, it seems better to make this work on the react-pdf side.

**Comment by diegomura** [comment]
I like this. The way emojis are rendered is by passing an attachment to textkit. We should do the same with inline images, probably setting the width and height beforehand. I've been working in enhancing textkit for the last month. I'll take this into account when testing it with react-pdf

**Comment by DuncanMacWeb** [comment]
Thanks @diegomura! :)

**Comment by SpandyB** [comment]
> I like this. The way emojis are rendered is by passing an attachment to textkit. We should do the same with inline images, probably setting the width and height beforehand. I've been working in enhancing textkit for the last month. I'll take this into account when testing it with react-pdf

Please share the results of the react-pdf tests that you performed. I'd like to crosscheck that with my own progress.
