### ISSUE TITLE
Support fileName prop on PDFViewer

### ISSUE THREAD

**Issue by web2wire** [diegomura/react-pdf#563]
The PDFDownloadLink helpfully supports a fileName property that allows the specification of a document name to use when downloading. However it turns out that the users of my app almost always use the download functionality embedded within the browser ([screengrab](https://cloud.web2wire.net:4443/s/v9TnzWT8rHucosa)). This downloads the file using the internal PDFViewer name (e.g 56519d10-685b-4634-9842-92aadd68f437.pdf) which means that users have to rename it after downloading, and then ensure they use the correct naming template for the contents.

It would be great if PDFViewer could support the fileName property and use it for it's internal representation of the file name so that downloding from embedded viewers would use the correct name in the same way as PDFDownloadLink does.

**Comment by diegomura** [comment]
Thanks!
I agree those file names are nasty, but unfortunately I don't think there's a real solution for changing them. By default Chrome shows the `iframe` url path as the file name (created [here](https://github.com/diegomura/react-pdf/blob/master/src/dom.js#L64) from the file blob), and I couldn't find a way of changing it. If you know or can point me to any way I would really appreciate it

**Comment by web2wire** [comment]
Thanks for looking. It seems I may have to jump through some hoops and send the blob contents to the server to save locally and then point the iframe to the saved content then. It's a shame getObjectURL doesn't support any tag of appending something sensible on the end of the generated path.

**Comment by diegomura** [comment]
Agreed it’s a shame! Would be much simpler the other way. Closing this for the moment since there’s nothing to do on ourside

**Comment by webdobe** [comment]
In my situation it is likely the user will want to download the file anyway.  So I did this which when using the PDFViewer it auto downloads the document using my custom file name as well.

```
export const onRenderDocument = ({blob, filename}) => {
  var blobUrl = URL.createObjectURL(blob);
  saveDocument(blobUrl, filename);
};

export const saveDocument = (function () {
  var a = document.createElement("a");
  document.body.appendChild(a);
  a.style = "display: none";
  return function (blob, fileName) {
    a.href = blob;
    a.download = fileName;
    a.click();
    window.URL.revokeObjectURL(blob);
  };
}());
```
Then
```
<Document onRender={ (blob) => onRenderDocument(blob, 'myCustomFilename.pdf') }>
 ...
</Document>
```

**Comment by tomgallagher** [comment]
I'd be keen to have the filename option as well.

Might it be possible to have the a hidden PDFDownloadLink component that can receive blob and filename from the iframe via window.postMessage? Just thinking out loud...

**Comment by osama2655** [comment]
> In my situation it is likely the user will want to download the file anyway. So I did this which when using the PDFViewer it auto downloads the document using my custom file name as well.
> 
> ```
> export const onRenderDocument = ({blob, filename}) => {
>   var blobUrl = URL.createObjectURL(blob);
>   saveDocument(blobUrl, filename);
> };
> 
> export const saveDocument = (function () {
>   var a = document.createElement("a");
>   document.body.appendChild(a);
>   a.style = "display: none";
>   return function (blob, fileName) {
>     a.href = blob;
>     a.download = fileName;
>     a.click();
>     window.URL.revokeObjectURL(blob);
>   };
> }());
> ```
> 
> Then
> 
> ```
> <Document onRender={ (blob) => onRenderDocument(blob, 'myCustomFilename.pdf') }>
>  ...
> </Document>
> ```

how can i make it that it downloads locally into my project folder and not in the desktop?
