### ISSUE TITLE
On the fly rendering - Cannot set property 'getCurrentStack' of undefined

### ISSUE THREAD

**Issue by Lilian1331** [diegomura/react-pdf#565]
There is a issue when I apply "On the fly rendering" in my react webpage.
https://react-pdf.org/advanced#on-the-fly-rendering

```jsx
import { PDFDownloadLink, Document, Page } from '@react-pdf/renderer'

const MyDoc = () => (
   <Document>
      <Page>ABC</Page>
    </Document>
)
```

then inside the react export class:

```jsx
public render(): React.ReactElement<IJsomProps> {
     <div>Export</div>
     <div>
       <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
         {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')} 
       </PDFDownloadLink> 
     </div>
}
```

it gives me this error
![image](https://user-images.githubusercontent.com/23545532/56053669-49b3d080-5d87-11e9-8111-29bd43b79207.png)

Any help thanks.

**Comment by diegomura** [comment]
What version of React are you using?

**Comment by Lilian1331** [comment]
> What version of React are you using?

I am using  "react": "16.7.0",

**Comment by diegomura** [comment]
Oh. Wait. Not sure if that's what causing this, but you cannot render a text directly inside a `<Page>`. You must always use `<Text>`:

```jsx
import { PDFDownloadLink, Document, Page, Text } from '@react-pdf/renderer'

const MyDoc = () => (
   <Document>
      <Page>
        <Text>ABC</Text>
       </Page>
    </Document>
)
```

Let me know if that solves your issue

**Comment by Lilian1331** [comment]
> Oh. Wait. Not sure if that's what causing this, but you cannot render a text directly inside a `<Page>`. You must always use `<Text>`:
> 
> ```js-jsx
> import { PDFDownloadLink, Document, Page, Text } from '@react-pdf/renderer'
> 
> const MyDoc = () => (
>    <Document>
>       <Page>
>         <Text>ABC</Text>
>        </Page>
>     </Document>
> )
> ```
> 
> Let me know if that solves your issue

Thanks, but the issue cannot be solved. Am I missing some configurations? Or I can't directly put the `<PDFDownloadLink> ` inside the render function?

**Comment by diegomura** [comment]
I have some doubts about your code:

- your (public?) render method is not returning anything
- you have two `divs` at the same level without any parent. Is this something you can do with React now?

I just tried on my end and everything is working fine. Please try this:

```jsx
const MyDoc = () => (
  <Document>
    <Page>
      <Text>ABC</Text>
    </Page>
  </Document>
)

class App extends React.Component {
  render() {
    return (
      <div> // or Fragment if you want
        <div>Export</div>
        <div>
          <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
            {({ loading }) => loading ? 'Loading' : 'Download'}
          </PDFDownloadLink>
        </div>
      </div>
    )
  }
}
```

**Comment by Lilian1331** [comment]
Yes I have the exact same code as yours. Same error alerted.
And I just created a new project and do `npm install @react-pdf/renderer` again.
Other error pops up 
![image](https://user-images.githubusercontent.com/23545532/56060045-4412b680-5d98-11e9-9bed-273d4ee40087.png)

Really thanks for the help!

**Comment by diegomura** [comment]
That last error is due to https://github.com/diegomura/react-pdf/commit/9d8903ed73bcbcd3e01065635d81225901cbdcaa

Will be published in next version. The other issue had nothing to do with it, and seems to me that does not occur anymore. Going to publish the new version now and please try with it

**Comment by markusjohnsson** [comment]
@diegomura I'm seeing this error too (the initial one, with getCurrentStack) when using webpack with mode=development, however, it goes away with mode=production.

**Comment by zhonggithub** [comment]
same issue

**Comment by russgove** [comment]
same issue here

**Comment by syriaca** [comment]
same issue, the problem is still there @diegomura

**Comment by syriaca** [comment]
Hi, is there any chances to fix that at any times ? I can't get that work in Reactjs.net environment @diegomura .

**Comment by kishore075** [comment]
Hi, 

Cannot set property 'getCurrentStack' of undefined while rendering pdf. I cannot create

**Comment by syriaca** [comment]
That error really, drive me mad, i cannot achieved a project because of that... really bad. Any plan to fix this one day please ?

**Comment by Fareedbaba** [comment]
installed the version 1.6.9 and created a sample application and encountering this error
am not sure if this issue was fixed

**Comment by diegomura** [comment]
For the ones getting this error, do you mind checking what React version are you using? I still suspect there's something conflicting with the React version since the error is on `react-reconciler`

**Comment by Fareedbaba** [comment]
Hello @diegomura 
Am using "react": "16.8.5", version,
"react-dom": "16.8.5",
Can you please suggest any solution to address the issue

**Comment by diegomura** [comment]
Can you provide a way to replicate it? I would be happy to fix this but I as I said above, I can't replicate it on my side

**Comment by Fareedbaba** [comment]
am creating a spfx webpart 
following is the reference: 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part
then am installing the react-pdf package using "npm i @react-pdf/renderer"
then am adding a small piece of code 
<PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
      {(loading) => (loading ? 'Loading document...' : 'Download now!')}
    </PDFDownloadLink>
when am running the code, this ends up into a endless loop throwing the error in react-reconciler

**Comment by diegomura** [comment]
But you are not providing any document into the `document` prop in there. Do you mind expanding?

**Comment by Dangerous-Mind** [comment]
@diegomura I was having the same problem. 
I think it's because he might be saving the pdf with the <PDFDownloadLink> inside of it. So it enters a loop.

Anyway it hangs without any message when I trying to print a small test message. 


```
const MyDoc = () => (
  <Document>
    <Page>
      <Text>Hellow World</Text>
    </Page>
  </Document>
)
```
Is there any special thing to do in SPFx?

@Fareedbaba Did you managed to solve your issue?

**Comment by diegomura** [comment]
Can someone test if this persist on 2.0? Thank you!!

**Comment by diegomura** [comment]
I still cannot replicate it. Any help from someone who can test it? Or someone who provides a valid snippet to replicate it?

**Comment by tkreis** [comment]
Similar to @Dangerous-Mind experience, this has started to pop up in a project of mine as well. 
In our case it seems to be related to us loading an production build of react and setting the env to development.

Thus causing the error inside of the react-reconciler. So at least in our case it wasn't a bug of pdf-react.
