### ISSUE TITLE
Yoga does not compile in Linux

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#57]

**Comment by jbovenschen** [comment]
Emcscripten which is used to compile yoga-layout can not be used on Linux, this because of that it compile CLang from it's sources.

Check [this](https://github.com/facebook/yoga/blob/master/.travis.yml#L53-L61) for more info.

**Comment by jbovenschen** [comment]
Yoga does work with the new release without needing a build step, but this will be triggered by scripts inside the package.json, does not know if we could ignore them for a single package? @diegomura you have any idea?

**Comment by diegomura** [comment]
@jbovenschen is this still a problem? How this can impact us?

**Comment by jbovenschen** [comment]
This is still an issue, and can be solved in two ways.

Main issue is that yoga-layout depends on emscripten which dependencies are not correctly installed on every OS or PC.

- `Yoga-layout` provides a precompiled version of the library
- We make a bundled release of `react-pdf` with an compiled version of `yoga-layout`

Sort of something I would like to do, providing a flat bundle like react is going to do in the future.

**Comment by ferdinandsalis** [comment]
@diegomura  I just ran across this error when I deployed my app on now.
```
> micro: Error when importing /home/nowuser/src/build/index: Error: Error relocating /home/nowuser/src/node_modules/yoga-layout/build/Release/nbind.node: YGAlignToString: symbol not found
>     at Object.Module._extensions..node (module.js:598:18)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at initNode (/home/nowuser/src/node_modules/nbind/dist/nbind.js:141:15)
>     at /home/nowuser/src/node_modules/nbind/dist/nbind.js:115:13
>     at findCompiledModule (/home/nowuser/src/node_modules/nbind/dist/nbind.js:79:13)
>     at find (/home/nowuser/src/node_modules/nbind/dist/nbind.js:93:13)
>     at Object.init (/home/nowuser/src/node_modules/nbind/dist/nbind.js:104:5)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/yoga-layout/sources/entry-node.js:11:17)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
```
I guess this is related to this issue or am I mistaken?

**Comment by ferdinandsalis** [comment]
@diegomura & @jbovenschen what is the way forward with this issue? I really want to get this running. Anything I can do :)

**Comment by diegomura** [comment]
I couldn't get into this issue in detail yet, but @jbovenschen had some good ideas above. Releasing react-pdf with a compiled version of yoga sounds like the way to go for me, but not sure.

I also don't know if there should be a compiled version for each node version or not, because I was forced once to rebuild yoga when I updated my node version

**Comment by codepunkt** [comment]
What exactly is yoga used for? I'm not sure i understand the benefits it brings - as opposed to manually adding some flexbox styles?

**Comment by ferdinandsalis** [comment]
@codepunkt if I am not mistaken yoga is a layout engine that uses the flexbox spec. And since we dont use a browser we need yoga. And flexbox is great since we dont want be adding coordinates (this is what pdfkit does; which is what react-pdf uses under the hood to do all the nasty font stuff and so on) to all the objects we want to place in the document. @diegomura or @jbovenschen correct me if I am wrong ☺️

**Comment by jbovenschen** [comment]
@emilsjolander seems this is a bit of an issue in our library, is there any change that yoga could publish also compiled versions on npm?

**Comment by ferdinandsalis** [comment]
@diegomura awesome. I Would love to tackle this myself but I currently lack the time and technical expertise — all I can do for now is donate some money through open collective. @diegomura have a great vacation and I look forward to what you are up to with react-pdf once you are back. However if someone else has time to tackle this issue it would be greatly appreciated.

**Comment by diegomura** [comment]
Thanks man! your contribution through open-collective is really appreciate it, honestly.
And of course, if someone wants to tackle this issue, please do!

**Comment by jmjpro** [comment]
👍 +1 This sounds like one of the main reasons the README lists this library as not production ready...

**Comment by eliseumds** [comment]
@jmjpro do you have a public fork of the updated *yoga*?

**Comment by jbovenschen** [comment]
@jmjpro Yes this is one of the reasons we list this library as non-production ready, besides that we have to figure out a good way to support multiple platforms. 

If anyone knows a way to provide a compiled bundle of yoga I'm happy to do so.

**Comment by jmjpro** [comment]
@jbovenschen have you looked at https://github.com/mapbox/node-pre-gyp? I discovered it via this article: https://cylonjs.com/blog/2014/11/19/creating-multiplatform-precompiled-binaries-for-node-modules/.

**Comment by diegomura** [comment]
@ferdinandsalis can you try the beta version v0.4.5 and see if works now? I think I fix this issue (at least partially). @jbovenschen said that he tested in in Linux and worked

**Comment by jbovenschen** [comment]
Made a PR which enables linux in travis again, see #143.

**Comment by ferdinandsalis** [comment]
@diegomura will do! Thanks for letting me know.
