### ISSUE TITLE
Text width not set

### ISSUE THREAD

**Issue by rogierslag** [diegomura/react-pdf#572]
**Describe the bug**
Under some circumstances with `flex-box`, no width is reserved for text

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a004850c29a812cc6429800b860b56ac003b500265378073213002300061800a86001600346c02f9e98300880adc017b82e89168d601ddb94a80514072552a0293bbd62016da828e578005441c51555fd58824378008440a0a04003a25562008ccca5f823c401d59d5da272f20b2201844110cc3c0188645aa4fc0dfc00ddf8a1b981a96d85ec89b8e40961853c547ddb038342c000659000cc2794b2d8e3e778009547c7322a29f22996d64a5cdd84958f4fcea16bea05279b5adbfd0d9860d8c1a80390762d9d0001e500020a2146600f301909c7e2cd582b6b1612cc870548005600576834548005658a82a0610a35120288a0652638f1389f8fd083209128ce115900775801d9a69f7f321ba9c205894990e86c3e1740a1b351502a14180d7183b99020c9181f21f607aac914aa59969aafa63228ccd66c5d9504e773147ccdab0beac5eb0000d6240008aa128dc712f5c0a2975ea25721864ce108d955be58ae5479d59aed522b6d6db58dd600667e56de20b64aa5d28a002d3123a6c71398e141ecbd5dd41d62c820e244351e01e158a04148e45773ddc2a30003e1d5450400e1ec0da100493a0042011e962362ac5c741b82b782d4119c45d467b79a48a4d2c698b7d8c17e333b58dc209c901432dab04619e8800985787b03ec33374da5e009f8c46bd4906dad3442c07c36231008bcb67d1cb7d0004a001b998660387c5165e1014c098531cc2b13801830180151c59064230000f844361151c428184001e000d5b86401c38170141d046008cb1ac122007e6e2f008148012889b11404050093ba0a15d019f4001e9a8e60108c3c07c40051105fe16d70981e824268ba38c06298933cf63198cf44060071004456a071570cc74000225e1855e8a42f234b115866200056a1ef31378c60e4d41c8212708a1f420ac4663b0be1d4f4382e62c23d4a2e40f8d8a24bf80164b76101427e1b056ce466354dcac114a4286b6058b0a9e2e2d743d281bd0817d7f5b870192fed606e0d02c5012ea481813a100cc3aa5aa6a72bcada98a3a8928569592ac1d212008791e005af50d29f34a70ccb4ef6338fcbdaf13484acfa641485ad1cb75f4181f26c8713909a90ba73bd0155a8afbaab27b6f08b288fb902fae45b360f8620735bcf18a071017553548a41c52142570712fa59735ac695e280954df3a567154f10a415954a09a07e154c47807260188154a9ac8710c039184b483d301d0705aa7100200114c2159118002542d6200391580031001390969c2070542ac0020011cb1001e479056020b0007d69cdd081096013a081103081c705bc4cd3d5773d2f2604cb82e6a568eb6ef9241c7b48525decfbbeea3bd0084063094425486988ec6b4ed52ae87034c02eaf0bef4ce2f3aa1ca725ca80f3d4334f43761a08750b3d657482a0b57e1e8663f4c32506f7a8b2e8000

**Expected behavior**
https://gist.github.com/rogierslag/64675402f00bae6597b7132338143044 which centers as intended

**Screenshots**
<img width="578" alt="Screenshot 2019-04-16 at 10 40 45" src="https://user-images.githubusercontent.com/2778689/56194883-1d70ac00-6034-11e9-8ddb-b2f8ae59dbe5.png">

**Comment by panzelva** [comment]
same problem here :)

**Comment by Plonq** [comment]
I think I'm getting this too. Seems related to #281
