### ISSUE TITLE
image example is broken

### ISSUE THREAD

**Issue by cookie-header** [diegomura/react-pdf#576]
**Describe the bug**
https://react-pdf.org/repl?example=images
the image is not loaded in the example

**Comment by DavidMich1** [comment]
I can confirm that it works on Chrome.

**Comment by samuraijane** [comment]
The image example works in Chrome, Firefox, and Safari on desktop. It also works in mobile Safari. I am not able to check IE. @diegomura, you may want to close this issue.

**Comment by diegomura** [comment]
Works for me too!
