### ISSUE TITLE
Local image not rendering

### ISSUE THREAD

**Issue by skjo0c** [diegomura/react-pdf#578]
**Describe the bug**
I am trying to get image from my local path, but the image is not showing in pdf. I believe it should be simple path defination, but tried with `allowDangerousPaths ` in my react project. I am trying to do following:

```
<Image source="../../assets/ball.jpg" />
```

**Expected behavior**
Load image from the local path

**Screenshots**
![image](https://user-images.githubusercontent.com/20612562/56457051-f4824b00-6394-11e9-83e0-a37536d862ae.png)

**Comment by skjo0c** [comment]
Only able to do it with data uri

**Comment by DavidMich1** [comment]
You can't put a relative path. See https://react-pdf.org/components#source-object

**Comment by MiracleGodspeed** [comment]
> Only able to do it with data uri

So how exactly did u resolve the issue using data uri?

**Comment by skjo0c** [comment]
> > Only able to do it with data uri
> 
> So how exactly did u resolve the issue using data uri?

I imported the image and passed it to src:

```
import Logo from 'assets/logo.png'
<Image style={styles.image} src={Logo} />
```

**Comment by MiracleGodspeed** [comment]
> import Logo from 'assets/logo.png'
> <Image style={styles.image} src={Logo} />
> ```

Imported images work fine no doubt. Images retrieved from enpoints however do not render. returns cors error

**Comment by MiracleGodspeed** [comment]
<Image src={{uri:this.state.staffDocx?.imageUrl, method: 'GET', headers:{'Access-Control-Allow-Origin': '*'}}}/>

How I attempted it

**Comment by mafiusu** [comment]
I've tried to import a local image from my src/assets/image directly. 

```
import Logo from "./assets/images/logo-transparent.png";
<Image src={Logo} />
```

The output of the pdf is then a blank white page rather then displaying the actual image. Is there another method of importing local images in react-pdf?

**Comment by arslantalib12** [comment]
It works for me. <Image src={`${Image Source}`} />. add img source in some const and then call it in image source with backticks.

**Comment by Yassyn90** [comment]
I tried all the above solution, but not yet able to show image in pdf file. Has anyone solved this issue ?

**Comment by winniekagz** [comment]
tried all the solutions and did not work

**Comment by winniekagz** [comment]
@AlphaBryan  hello i tried importing it first then rendereing the imported and it worked.Using svgs doesnt  display .use png

'import image from path
<Image src={image} style={{your style} />

**Comment by jorgehenriquezd** [comment]
Convert your images in base64, you can use this page:
https://www.base64-image.de/

Then copy the result and paste it in the **src** of the Image

**Comment by asslaoui** [comment]
I think there is an issue with JPG & JPEG files, PNG files work fine even if you use a direct url

**Comment by joharkhan99** [comment]
place your images inside the public folder. and use them like the below example.

this will access an image inside `public/assets` folder
`<Image style={{ width: 80, height: 70 }} src={`/assets/logo.png`} />`

or

this will access an image directly inside `public` folder
`<Image style={{ width: 80, height: 70 }} src={`/logo.png`} />`
