### ISSUE TITLE
Qs: What viewer is used in example pages?

### ISSUE THREAD

**Issue by danielbischoff** [diegomura/react-pdf#581]
Hello,
thank you for this great project!

I have a question. I personally don't like the built in viewer. But I like the viewer used in the example page: https://react-pdf.org/repl
Can I find the source code for this example page anywhere?
Or what is used to render it?

Thank you for your answer!

**Comment by ankesh7** [comment]
@danielbischoff This is the package used in examples. https://github.com/wojtekmaj/react-pdf

**Comment by danielbischoff** [comment]
Thank you!

**Comment by diegomura** [comment]
You can see how I used here: https://github.com/react-pdf/site
