### ISSUE TITLE
Page break does not create a new page

### ISSUE THREAD

**Issue by maxaggedon** [diegomura/react-pdf#584]
**Describe the bug**
When setting `break={true}` on a primitive component, if the total height of the component and what comes after it fits into the current page, no page is created and therefore the break is not applied...

**To Reproduce**
[REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943392830b1753a307864002b742c1b18111e1800591e3060731e4cfcdcad7c984362c2b3591e0470907b6236a43e040c1118269f3b00374ecc083ebd3634bcfde1b1d1d352fdf543cd005108001a1878a587d5c11e793b4780472598334c30c40f27f12890dd100c1cc48250f0447c1023c4420082447850144c17e580047c78d74e3d09028c85e1b1ff5b2759a98c60010f5136158f0008f20220411a78982b4c476669204198a6b00f122312d800b73c0801328a06a941b6ad1e33980480033f54843045b411158bf880441b187aa602288120de300c52921cf5624396ff5a9d8d56ac84d965cd5688a005e3c47b6b26d516b72948c2418090d04a5ab35d688020a1d1240b161006e1836ac5183e19b5a8ac770c10de862d98996d8505b536083a2a34eea803f5e48dba6353046021bad294d80f37da6994ec94b7b7a398c107581094c7bc47863d0231e294db3f3050cac08be470f154b512c0356179b62cf062012e698836eaef6b493e6e961794988636d31cf3b4a73eebc67222073dad5b53168cc0458c04c4c46f4177f180294152a5e434daa65d210038f7344015c100809d1591c1e11812460000c596704904e93d2c000652418d1e0002e18266724c36005a0adab44d9355c5140db36e5b1314fb28ca00acba6b0fb4a4fd700cc12c84694910c060c5c30782a9269e23b05a40284ba55177cc06fd733e0b91e4303e47811230ff17e34d376cccb45d152dcde7ad1c095f53b44c9c5aa6ed7b545609d853513777f8206002b0c4989f4d13f4132f43c4e0c34b4c0592137255a48c1284c3914d800c11e61ce12ed3a3b072ab532e6cc04705a6c48afb9bd725e53ca02ac1b17a9ad30c3617824d691c3b188a4ce72131529c900012f508413a532302945894b280c2e10c48cb4c30f249a3ea0131cc1135a31e30ea8c889610136af4c8a24e58f489cb047066329554e883181311e88a8eae0d7066569192ecec0d29048c2ec85c96617e9f5bd3db63568f84a4fc80d64024f61c8d1a1846631ce591307d01c104ac001ac064d00021000946e001040069346b27d8c9c198e6c64a3c72e167283b9e71784af797f1f8fe0050460541705cc485a1585e17d4ecf4531725715ddbd22448b2445a47a95450cb7899565d94e422cb2f9110055b0856dd457dda532dc01b4956e5550d4b51d5708c585ac08d134943342d2b58757c9e0418b674305756c7758971c56f8bfd4138350fe2eb12368de1f8daa2691f2fa50ccc84b320b4778b24ccb59d2b185ac212eb06d20ff99b3d4bd981db1333b40a7a5447a01dccf72475b00ed52e3c9da72516741360df5b0d5d170dd2df72773dcec03debcc34f203a52bd735bdef12c9f7ac6d57c8cb9b1d60a106fc7a5fdf580280a0eed544c0882a0c1e56d82348438b98190a3cd09d730e5d9e3c2ff008911122e45cd9aa6a2d69e8a3165a2fcd89fc0e25c52b9046ce7c4e7a276124b144aa2712924452c2544b25e4aa224c4a55e34138eafd349672c03a56c1e92027ad8ca99310e644db342b2eb86c960bb21801c8602724205cad8372d686b9791f2e009a11e76e7d8428291e8e155a19868a610401c530c355638ad34a518b47652ecd54782256a8054beb156026551805531cb94b44b07aadc234b1516a7f0da968e60c79ba9345eafd4c710d5b0234c7bbd09ac8466b9a63e0b496b7a35a22036b9a2da4acfe2ed3f100c9011d641ab1d259d660ac1b703b6bafb4ee9db21e8f59e92057a601dea7d688323819153b403c5614310660d8b2437a9279f11c7386034751231b028d19bf4024de959be8138a60ce0c84e604db98c05e621ccc00b6181f0be261516408899820845092b9cb244989293c4e56d00f11ab0f4803358e26d6184f5a031646c98631b6541c2cd85b2b64f9772e6494252569b522c8a99da5104cda97527b4c23ed4d1ef40e5804088730e2b0239ba4a2344626fa631182430a708c5186300d4cebc50a9e71e04050bb7262e1884b1970ac289326d6330b5c9b0dd56c7f05b982334b233b8551eec04d33f7006cfd3430ce6698cd9a9c1c633217008000724c17f0387f07e56c2483c01209e3f00c072aa73ac8c48a8442f0010a89541106c0a40f037a00006000482434aad5f2aec0380c83016d5eab8486acc2a84b5048080386702815c0c00c80313227af70990e80305c90700806632064148b80280b21fc1f07c57602d650000e4e60a0140788100988640c84f5581c83e0672ca300590cb8320400c8289821c22501903600046000cc19000268007d6d074c001a8003610000038003a8800d8f20002a9284ed8c0fb4000d0009c3c0698d33c65011c366e6a941d561148c220841c56cd001e4203369104a1b34c0550cd4e3426f94d01264c81c03016898c5a2960300a6e8a010301aa8e08a0541c509087017128304e05b40807887153b4005603d9c1a0ec1be0e4dd0062460714476a1a83d6130c0009198480e4ab038448708e5047d1c0ca1403101070e196a80f44fd06038a00098000b1a1ca0f8ca00d37367c0c039eefa9816c3eed63c9b4891106267a6025eebd2dbb34707a39412634c5b02c7341b18e35c6603b6ee30266d3ec1130b1c4f29c9376064e686b1b61d35806c3f9bb09c55e300018d0e6992cf2118f31980907f4f26c33715db78eb338e79cf85d33b27583c993d4a654cdebbd1a6d0d09bd39c1a2d4658b6660cc51a33edbf8e1c213966c4f9eda81ec2a5087b39c0d8e25c53e7bb4283330b1129b614e8ea6e8da1d069aab2e501cb600875d86add478ced1ecb8b99cd918ac947f5785cf3de7d2c704b0d60ec00da70a170ade5c384375cee19e3cb734195d13d67b36d9e93667403225d3ca7118605ab3e6d0fdaed5bf936fc43a5651c039e8f87844414c0c075728015ce3bb73422837378660276e3ba9430238280714e1e500ac7c0f3723b33a76acc498ba767aed1a198e7a1ed3d95b26be35904a6560621701a0a45537a64cd541102a0068c1b8833ea0000)

**Expected behavior**
Page breaks should be able to create new pages if necessary.

**Comment by diegomura** [comment]
Thanks! I'll try to take a look soon to this

**Comment by DavidMich1** [comment]
Ideally you should create a new <Page> tag instead of using a break inside a <Page>.

**Comment by diegomura** [comment]
Both should be fine and work though 😄

**Comment by davidvazinwnwd** [comment]
This still not working!!

**Comment by djedd** [comment]
It does not work for me either :(

**Comment by JCQuintas** [comment]
@diegomura do you know if this is already fixed in v2 beta? I've tried to install the v2 but it doesn't seem to be a drop-in replacement, so I wanted to know if it worth adjusting it to work with my setup so I have this feature.

**Comment by LucasMatuszewski** [comment]
I have the same issue. I've tried on many elements (text, view) in many parts of different pages, and neither "break" property or normal "wrap" works for me... Only manually adding `<Page>` works. I have tried the "debug" mode and the height of the elements is bigger than the page size.

I use:
```
    "@react-pdf/renderer": "^1.6.9",
    "react": "^16.12.0",
```

I also use saveBlob function, maybe this is a problem?
```
const saveBlob = (blob: any, filename: string) => {
  return new Promise((resolve, reject) => {
    var a = document.createElement('a');
    document.body.appendChild(a);
    a.style.display = 'none';
    let url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = filename;
    a.click();
    window.URL.revokeObjectURL(url);
    resolve('PDF saved');
  });
};

export const savePdf = async (document: any, filename: string) => {
  return saveBlob(await pdf(document).toBlob(), filename);
};
```

Part of my code:
```
{entries.map((entry: EntryType, index: number) => (
        <Page size="A4" style={styles.page} key={`entry-${entry.id}`} wrap>
          <PdfHeader hipName={hipName} hipKey={hipKey} />
          <PdfEntry entry={entry} index={index + 1} />
          <View break style={{height: 1000}}> // JUST FOR TEST IF BREAK WORKS
            {entry.strategies
              ? entry.strategies.map((strategy: StrategyType) => {
                  if (strategy && strategy.plans && strategy.plans.length) {
                    return strategy.plans.map((plan: PlanType) => {
                      planIndex++;
                      return (
                        <PdfPlan
                          plan={plan}
                          planIndex={planIndex}
                          entryIndex={index + 1}
                          key={`plan-${plan.id}`}
                        />
                      );
                    });
                  } else {
                    return null;
                  }
                })
              : null}
          </View>
          <PdfFooter />
        </Page>
      ))}
```

Screen:
![image](https://user-images.githubusercontent.com/28517564/90526359-97f19480-e170-11ea-9779-834e6f5ea6ef.png)

**Comment by morningcocoa** [comment]
Is this fixed in v2 @diegomura or fixed in the current v1? Would really love if this feature was fixed.

Also note, thanks for building such an extensive tool. Thank you so much.
