### ISSUE TITLE
Quixote REPL example contains outdated Font.register code

### ISSUE THREAD

**Issue by alundiak** [diegomura/react-pdf#586]
**Describe the bug**

```
react-pdf.browser.es.js:41 Warning: 
Font.register will not longer accept the font source as first argument.
```

**To Reproduce**
1. Got to https://react-pdf.org/repl
2. Copy the code
3. Implement similar locally
4. Run the project and look to console

**Expected behavior**
I assume code in repl example should be changed to:

```
Font.register({
    family: 'Oswald',
    src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
});
```
As I did locally, and warnigng disappeared.

**Screenshots**
<img width="1435" alt="Screenshot 2019-04-27 at 16 07 07" src="https://user-images.githubusercontent.com/2131633/56850723-91e5fd80-6906-11e9-9c81-00742c21d7ef.png">

**Desktop (please complete the following information):**
I use Node v11.14.0, React v16.8.6, Webpack v4.30, Babel v7.4.3.
`"@react-pdf/renderer": "^1.5.4"`

**Comment by diegomura** [comment]
Fixed. Thank you!
