### ISSUE TITLE
Page not breaking dynamically

### ISSUE THREAD

**Issue by jsw324** [diegomura/react-pdf#587]
**Describe the bug**
I'm rendering a PDF download link inside of `<PDFDownloadLink />`.  I'm passing a component to the `document` prop and inside that component I'm mapping some views and text to create a table-like block.  This works perfectly unless the rows of block exceed the default size of the page.  If that happens it just gets caught off and no second page is dynamically created. 

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
This is my table: 
```export const TableRow = ({ details }) => (
  <View wrap render={() => (
    details.filter(item => item.descr !== 'Payment').map(({ descr, amount }, i) => (
      <View style={styles.tableRow} wrap>
        <Text style={styles.rowText}>{descr}</Text>
        <Text style={styles.rightRowText}>${amount}</Text>
      </View>
    ))
  )} />
)
```

**Expected behavior**
 I expect the content to automatically wrap to a second page, as in the `Quixote` example.

![image](https://user-images.githubusercontent.com/3531954/56972549-318ad200-6b39-11e9-990a-755dfcf0db7c.png)

You can see in the above image the next block is hidden and no second page is created.
In the below image is the content that _should_ be rendered:

![image](https://user-images.githubusercontent.com/3531954/56972680-6860e800-6b39-11e9-88d2-f62194c8205e.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.4
 - Browser: Chrome 73
 - React-pdf version 1.4.2

**Comment by rhansen-carecloud** [comment]
Having the same trouble here with overflowing content not dynamically generating another page - is this something you figured out or did you choose an alternate route?

**Comment by jsw324** [comment]
I figured it out.  It was a CSS issue on my end 😞 I'd recommend making sure you're only using supported CSS.  The `debug` prop is quite helpful as well.  Good luck!

**Comment by andrioid** [comment]
Elaborate please?
