### ISSUE TITLE
Font file not parsing, characters garbled ('An invalid or illegal string was specified')

### ISSUE THREAD

**Issue by marcohamersma** [diegomura/react-pdf#588]
**Describe the bug**
When linking to a regular `ttf` file, the console shows the message `SyntaxError: An invalid or illegal string was specified`, and characters look garbled. These are all regular roman characters.

Using a Google-fonts hosted ttf file like the one in the react-pdf example, or this [fonts.gstatic.com](http://fonts.gstatic.com/s/notosans/v6/LeFlHvsZjXu2c3ZRgBq9nKCWcynf_cDxXwCLxiixG1c.ttf) one seem to work, but a downloaded font coming straight out of Google Fonts, and the downloaded Noto font straight from the Google Noto website don't work. Either trough the rails app or an S3 bucket.

For the moment I can get away with using the ttf file from the `gstatic` server, but I guess Ideally any regular font works. 

Any idea what is causing this?

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Open this [react-repl link](https://react-pdf.org/repl?code=1887b07602e07404e0a6073025819c27180280de0280013e019808602d9200d809e0173e011007220423e0328960a0c03405f0a18018de830016102000714b403d02a2e020a28008c40818004dd48906414b365c7805a004a8802ba51230a34a20d7005f009401b972e22b660221048e0f800823232989ef87884f010b63060f8988284003c00222022b6647090007c1984f899000a24087065e54248005e7000bc0c24002c6e0d0d3a4845102421e0ed0e60fa222432703dbd8468d4946dd8d8c4aac0e454748ca6ece6bcf8eeeef5e500ee30d3add8a494287027f3a5f399002a70001e10c5001270d4f8779a1f010092a1f0e094118e020cf841320a7797d9ee5047556a28ac82972f942895043e0f1f90c3c083e060da08001459678b26b5f0ba3c81506505ab5369830010b500092ba4c03029ac062126c2460a55b2c05811574184c26522327c0298a7c7265269703a6128000)
2. Observe the missing characters

**Expected behavior**
`ttf fonts` from regular sources should work as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/577144/56976728-89dac780-6b6b-11e9-8e57-5c1c8b7c5320.png)

**Desktop**
 - OS: MacOS
 - Browser Firefox, Chrome
 - React-pdf version 1.5.4

**Comment by alundiak** [comment]
I did have similar, but it was webpack file-loader config missing for ttf and other fonts files. After I configured properly I can now read ttf files in ReactJS/JSX code.

**Comment by diegomura** [comment]
Seems like there is something weird with the `.ttf` file that `fontkit` doesn't like. I opened the font with a font editor ([Bird font](https://birdfont.org/) is pretty good) and exported it without any changes and rendering went good.

Here it is the exported font:

[NotoSans-Regular.ttf.zip](https://github.com/diegomura/react-pdf/files/3169416/NotoSans-Regular.ttf.zip)

It's not the first time I see this happening, but unfortunately there's no much I can do about it rather than this process. Hope it helped
