### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#59]
It would be very cool to have people suggesting logos and vote to choose one. So, if someone wants to suggest and design a logo, please feel free to do it!

**Comment by elpic** [comment]
![logo](https://cloud.githubusercontent.com/assets/138424/26419650/cd6d7292-4096-11e7-81e6-74591cb59660.png)

**Comment by diegomura** [comment]
This is just a sketch I did today

<img width="358" alt="screen shot 2017-06-22 at 1 24 50 am" src="https://user-images.githubusercontent.com/5600341/27417650-57bcc6ee-56ec-11e7-926e-a84be7791f19.png">

**Comment by diegomura** [comment]
Here it is with some fancier gradient. Not sure if those are the correct colors though

![logo proposal 1](https://user-images.githubusercontent.com/5600341/27417661-6ecbf4fe-56ec-11e7-8b73-84c6b8c46ebd.png)

**Comment by diegomura** [comment]
New idea from @nachoaIvarez, implemented by me. Inspired in origami shapes.

![logo 4](https://user-images.githubusercontent.com/5600341/27467084-c8850a3e-57b5-11e7-9e1f-f164274b911d.png)

**Comment by diegomura** [comment]
An alternative of the previous one

![logo 5](https://user-images.githubusercontent.com/5600341/27467113-0b9f06a8-57b6-11e7-9acb-df48e76b7c84.png)

**Comment by diegomura** [comment]
Based on some opinions I asked for, I'm going to go for the first one I shared. This other _origami_ design seems kind of incomplete to me. I can always iterate through this in the future

**Comment by diegomura** [comment]
![logo](https://user-images.githubusercontent.com/5600341/27505816-c8bc37aa-587f-11e7-9a86-08a2d081a8b9.png)
