### ISSUE TITLE
Font Family makes some letters of the text invisible

### ISSUE THREAD

**Issue by jdrouet** [diegomura/react-pdf#595]
**Describe the bug**
I'm trying to use a font to display some text in a PDF, but when I apply the font family, most of the letters become invisible.

**To Reproduce**

```javascript
import React from 'react';
import ReactPDF, { Page, Font, Text, Document, StyleSheet } from '@react-pdf/renderer';

Font.register({
  family: 'Baloo Bhai',
  src: 'https://github.com/google/fonts/raw/master/ofl/baloobhai/BalooBhai-Regular.ttf',
});

// Create styles
const styles = StyleSheet.create({
  text: {
    fontFamily: 'Baloo Bhai',
  },
});

// Create Document Component
const Template = () => (
  <Document>
    <Page size="A4">
      <Text style={styles.text}>Coucou</Text>
    </Page>
  </Document>
);

ReactPDF.render(<Template />, 'generated.pdf');
```

**Expected behavior**
See "Coucou" with the good font family

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node
 - React-pdf version 1.5.4

**Comment by diegomura** [comment]
Please check this: https://github.com/diegomura/react-pdf/issues/588
