### ISSUE TITLE
Not a bug in code but looks like a typo in documentation

### ISSUE THREAD

**Issue by JSDilag** [diegomura/react-pdf#596]
In the documentation, Components -> Image -> Source object props (https://react-pdf.org/components#source-object), the sample code for Data buffer uses ';' instead of ','. Minor issue, but can save other fellow devs from confusion.

![image](https://user-images.githubusercontent.com/7266935/57554840-8cde7080-7340-11e9-802d-10cae81f840d.png)

**Comment by diegomura** [comment]
Thank you. Fixed: https://github.com/react-pdf/site/commit/a90aa02132c4258fdfd0fc50ed29d1408e0ed89a
