### ISSUE TITLE
is it possible to support another unicode spaces ?

### ISSUE THREAD

**Issue by DimaRGB** [diegomura/react-pdf#598]
**Describe the bug**
When use [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) with `fr` locale it produce [space](https://www.fileformat.info/info/unicode/char/202f/index.htm) as `NARROW NO-BREAK SPACE` (`'\u202F'`) which render as `/`.

**To Reproduce**
https://react-pdf.org/repl?code=3187b0760ce02e0040662013816c086b02f0c01401b130aae029803431802bb2011b18809430601f05c40ee30092614b803a0072d4ea2006248d143c048b1060210a74d8aad7a0c03700281da122c3888446c4cde14d501c98f5f201180030bed7a0f4180144007aa64000e2416d84cac383a3030003c002204d4c47c2c915131000aa800e6c430d0009e241800de0524100234200026f900be296969c500f4005430001650500110005c2d2d1c234a009624cad2026360082db3f3946063a0d5c42dc09da8882d004c4e7b700b60eb3e02ddc8306d2d75a94dd1002ac43eb065c425ef15b8b3c40df74d181080082002550401e400ea4088401680042a0af30200d2300032ba58100612f3f4010f67abcf2504287d4a64f2809a08870165fe80c07158ca6311dc994d568741c0032003100038f6006600271685c4e6badd0969688b5895046a02154a95534e5dcae8f4fa8361a8ce0136214dd033398804e4b159ac365b1dbec9c273385ca0571b873554ad27933e54e237d7e8cce56371f8b95449e2f37bfafde48aad3e90d070c0a56ae8c6be58a8cc0215991c8aa15f160225923a373e9c09e2f85831fe8c67588c4280098088623a188d862aa4aab57e8c07b4d00aa1aad5599651e200080e454e52002476389c002490630017b80a04459fce0170120f9626376f00a0637000faca05c350c0f64d544ea0ba88fcc0c401f1535004834220b2598a719c606715f1805f54913300b22fc0f6ddc47f0267c9fa1fdac15d885c0003766d5654111101706a9ac548ee3a82b5043b73dd2589c4011db539e86c1a25f1fc2097216858370800000

**Expected behavior**
should render the space

**Desktop (please complete the following information):**
 - OS: MacOS@10.14
 - Browser chrome@74
 - React-pdf version v1.5.6

**Comment by diegomura** [comment]
Yes. Would be possible. Not sure if just adding it into textkit (in particular [here](https://github.com/react-pdf/textkit/blob/master/src/glyph/isWhiteSpace.js#L3)) would o the job or anything else would be needed, but if you can please try or I'll address it as soon as I can

**Comment by DimaRGB** [comment]
but why `'\u00A0'` render like space?

P.S. workaround:
```
import { Text } from '@react-pdf/renderer';
import reactStringReplace from 'react-string-replace';

...

export default ({ children }) =>
  <Text>
    {reactStringReplace(children, /(\u{202F})/gu, () => '\u00A0')}
  </Text>
```

**Comment by diegomura** [comment]
Glad you found a workarround. Not sure why that char is being rendered as `\`, but common sense would say that the glyph that the font has for `\u00A0` is a backspace. NO-BREAK-SPACE should be used also on word wrapping to prevent a line break to happen in that line also. I'll try to add support for all of this soon

**Comment by DimaRGB** [comment]
super cool, thanks.

**Comment by DimaRGB** [comment]
maybe this can give more understanding https://stackoverflow.com/questions/595365/how-to-render-narrow-non-breaking-spaces-in-html-for-windows/1570664#1570664

**Comment by 0xtz** [comment]
I encountered the same issue and spent a good couple of hours scratching my head until I stumbled upon this solution.

If anyone using TypeScript, here's a handy snippet to address the problem:

```typescript
import { Text, type TextProps } from "@react-pdf/renderer";
import reactStringReplace from "react-string-replace";

/**
 * @see: [React PDF Issue #598](https://github.com/diegomura/react-pdf/issues/598)
 * @description Custom text component to replace the narrow no-break space with a regular space
 */
const CustomText = ({
  children,
  ...props
}: { children: string } & TextProps) => (
  <Text {...props}>
    {reactStringReplace(children, /(\u{202F})/gu, () => " ")}
  </Text>
);
```

**Comment by sneko** [comment]
I faced this too but didn't find this issue before searching for `non-breakable space`.

Since I used `.charCodeAt()` that returns codes, not unicodes, I just want to add those keywords to the issue:
* 8239 (for `\u202F`)
* 160 (for `\u00A0`)

---

@0xtz in your example you replace with the basic space (code 32) that is breakable, I would advise using code 160 which is supported by PDFs.

Note: in my case it's for a simple value so just using `unsafeValue.replace(/\u202F/g, '\u00A0');`

**Comment by 0xtz** [comment]
> [@0xtz](https://github.com/0xtz) in your example you replace with the basic space (code 32) that is breakable, I would advise using code 160 which is supported by PDFs.
> 
> Note: in my case it's for a simple value so just using `unsafeValue.replace(/\u202F/g, '\u00A0');`


Aha I didn't find issue with the current code, bc I just pass currencies...

but that's a good catch I ll update my code 🙏 thanks man
