### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#60]
We will need to document the pdf components and the different libraries, both for the README and for the future site

**Comment by jbovenschen** [comment]
This seems to be a good fit if we want live editing of examples within the documentation. https://github.com/FormidableLabs/component-playground

**Comment by diegomura** [comment]
Yes, but the proper landing implementariom will be discussed in #58. 

This ticket is about content (listing components, available props, styling), not about implementation
