### ISSUE TITLE
Improve Font.register() typing

### ISSUE THREAD

**Issue by ThierryCols** [diegomura/react-pdf#601]
**Describe the bug**
The Font.register `src` argument is mandatory according to the [index](https://github.com/diegomura/react-pdf/blob/master/index.d.ts#L286)

But according to [the docs](https://react-pdf.org/fonts#register), you should not have to pass a `src` if you bulk register fonts.

I don't know which should be changed. I like the docs behavior, so maybe update the types?

Additionally, fontStyle and fontWeight attributes in the fonts array are not optional.

Cheers

**To Reproduce**

<img width="535" alt="image" src="https://user-images.githubusercontent.com/8972446/57702248-f4a4fc00-765d-11e9-8ceb-481b885f704b.png">

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

src is not a mandatory argument if fonts is passed to register()

**Desktop (please complete the following information):**
 - React-pdf version v1.5.6

**Comment by diegomura** [comment]
Fixed
