### ISSUE TITLE
Invalid asm.js: Unexpected token - yoga-layout nbind.js

### ISSUE THREAD

**Issue by hutch120** [diegomura/react-pdf#603]
**Describe the bug**
Very first message In the console when running create-react-app with `npm start` there is a cryptic message in the Chrome console log during the react import/build process... 

`Invalid asm.js: Unexpected token .../app/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:5503`

I noticed the yoga-layout module is many versions ahead of the yoga-layout-prebuilt one included in react-pdf package.js

**To Reproduce**
My environment is pretty much a vanilla create react app.
I tried to reproduce in https://codesandbox.io but it fails to import this library.. anyway... tracked it down to the import statement:

```
import { PDFViewer, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
```

**Expected behavior**
No warning from yoga-layout in the console.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - React-pdf version 1.5.6

**Other info**
Generates the PDF just fine.

**Comment by jruanoDev** [comment]
Same issue here, on React latest stable version, vanilla create-react-app project.

**Comment by hutch120** [comment]
Quick update... since code splitting and dynamically loading this library the `Invalid asm.js:` warning is now output when the library actually loads. (Obviously?) https://github.com/diegomura/react-pdf/issues/619#issuecomment-497195487

**Comment by diegomura** [comment]
> I noticed the yoga-layout module is many versions ahead of the yoga-layout-prebuilt one included in react-pdf package.js

This is not correct. `yoga-layout-prebuilt` is using v1.9.3 which is also the last version [published on npm](https://www.npmjs.com/package/yoga-layout). It might be that the C++ code is a bit ahead, but Facebook didn't release a new JS build

**Comment by hutch120** [comment]
Ah, thanks for the clarification, I see [package.json](https://github.com/facebook/yoga/blob/master/javascript/package.json)

I wonder if this is some sort of `create react app` webpack incompatibility... anyway I guess this is beyond the scope of the project and given the PDF is being generated I guess I'll just close this issue.
