### ISSUE TITLE
Fixed footer per page

### ISSUE THREAD

**Issue by ewein** [diegomura/react-pdf#606]
Is it possible to set a fixed footer per page when wrap is true. I would like to set a fixed footer to display the current page and some other meta data. However when wrap is true, this footer is pushed to the bottom of the entire document.

Thanks for your help.

**Comment by bewildergeist** [comment]
For anyone who might be looking for the solution, the [`fixed` prop will do the trick](https://react-pdf.org/advanced#fixed-components).

**Comment by benRivello** [comment]
I ran into an issue where my wrapping content was inside nested flex views was preventing the fixed footer from rendering.
```javascript
<Page>
  <View> // <-- container view 
    <MyFixedHeader style={{flex: 0.2}}/>
    <View style={{flex: 1}}>
      ...myContentThatWraps
    </View>
  </View> 
  <MyFixedFooter /> // <-- would only render on last page
</Page> 
```
Removing the container view and some of the flex styling allowed my fixed header/footer to render on all pages.

**Comment by yogeshmuthuraj** [comment]
@benRivello  Could this be done without removing flex settings?

**Comment by elioenays** [comment]
> I ran into an issue where my wrapping content inside nested flex views was preventing the fixed footer from rendering.
> 
> ```js
> <Page>
>   <View> // <-- container view 
>     <MyFixedHeader style={{flex: 0.2}}/>
>     <View style={{flex: 1}}>
>       ...myContentThatWraps
>     </View>
>   </View> 
>   <MyFixedFooter /> // <-- would only render on last page
> </Page> 
> ```
> 
> Removing the container view and some of the flex styling allowed my fixed header/footer to render on all pages.

you need to set `fixed` prop in the component footer
