### ISSUE TITLE
PDF-Viewer does not display different fontweights

### ISSUE THREAD

**Issue by Isarstyle** [diegomura/react-pdf#607]
**Describe the bug**
the { PDFViewer } from '@react-pdf/renderer';
does not display different fontweights, but in the exported PDF the fontweight is used as it should be.

**To Reproduce**
```
// Register font
Font.register({
  family: 'XenoisSansPro',
  fonts: [
        { src: '../../fonts/XenoisSansPro-Regular.otf' }, // font-style: normal, font-weight: normal
        // { src: source2, fontStyle: 'italic' },
        { src: '../../fonts/XenoisSansPro-Bold.otf', fontWeight: 'bold' },
    ],
});
```

**Expected behavior**
The fonts with different weight should be displayed in the pdf viewer as well

**Desktop (please complete the following information):**
 - Browser [Version 76.0.3799.0 (Offizieller Build) canary (64-Bit)]
 - React-pdf version     "@react-pdf/renderer": "^1.5.6"

// UPDATE: Seems to be a bug with chrome, in firefox the fontweight is displayed correct. 
I also tested with safari, but there the whole font is somehow mixed up. 
<img width="1146" alt="screenshot on safari" src="https://user-images.githubusercontent.com/5257056/57988431-a1b7b400-7a64-11e9-9f1f-3736307fce9f.png">

**Comment by diegomura** [comment]
First, `otf` fonts worked well for you? Officially we only support `ttf`, but anyways.
As you said, this is not an issue of react-pdf. After all, PDFViewer is just an iframe loading the PDF document. The actual pdf viewer is chrome's one.
Would be good to keep track of this, but I'm closing it since it's not a react-pdf bug. Let me know if you disagree with it

**Comment by Isarstyle** [comment]
In the generated PDF in Acrobat the `otf` font is working quite nice, but it seems to be totally browser related, found out there are many folks out there that have the issue with the integrated chrome pdf viewer, for me it seems that the issue comes from having the font locally installed, as well as integrated in the pdf, and there is somehow a mixup.

**Comment by gino8080** [comment]
ok i got same issue, with another google font
then I tried Roboto.ttf and worked well

so I solved with a simple trick
Using a converter site like https://convertio.co/
Converted the problematic ttf font into otf
then again reconverted otf to ttf
and now it's working!!

**Comment by pyskywalker** [comment]
Another diagnosis could be the pdf rendering before the font has loaded.
Solution: 
`const [fontLoading, setFontLoading] = React.useState(false);
  const loadFont = async () => {
    try {
      setFontLoading(true);
      await Font.load({
        /* Specify the font details */
        // Example:
        Custom: {
          normal: fontRegular,
          bold: fontBold,
          italic: fontItalic,
        },
      });
      // Font is loaded successfully
      console.log("Font loaded successfully");
    } catch (error) {
      console.error("Error loading font:", error);
    } finally {
      setFontLoading(false);
    }
  };

  React.useEffect(() => {
    loadFont();
  }, []);

  return (
    !fontLoading && (
   //PDF CODE
   );
`
