### ISSUE TITLE
Canvas is broken in REPL

### ISSUE THREAD

**Issue by liron-navon** [diegomura/react-pdf#609]
**Describe the bug**
The REPL says "Error: Canvas is not defined"

After testing, it seems that the canvas isn't exported, why is that?

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
[REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805000f0022230080b619853164cecc1400a02180e658212005e19b002200820059c4c68013c00d9880de8a5440074001df8600beac3870a0184798006e3c20c3d499b6550f986004e25ecf4799ddb1340f62d7a102b0c0015103c0046000638801a18188056388200a0932d254748e8f8a498002674ccecc0dcfca8bc1284e4b28cacca982d00332425253c71006200310180666184f10203007a635329de01598a299a3a46665602006e323201f0282d770c3e24680f3c5500f69e7a2e85002e18007200790800771e25001367c480841dcc027b3c001650280e8200f2994dda076d1f1a03c28121805a503d0a610298813edf1f94cac316194c009a007d08801a4006a0036100003800ea610011801547ec37a252001a004e1e249245a487b59e640336d76a0482c034183b2e000ca5065060d5608c0610ec063aa2309700872403f478c0ae263d0fc7e8e3e144744f61aa401b69e3db1d00217414040f427833dd2d3b43ac07c0004881dc2203b7d5da1f60183d3034540544f1b47011cc35488304f12b48d3ec4c0a0a0923c9f0c0a0e0130fcff169e6a0035bbdd41ef2fafda529b4cf01050306c7b32d83817444f18894cbe98c257ab485afd71b1e66c99e83c7729cc07ec86069ed2248055380840723359eb78ff385e9f32e75b9de39a7b3dbdb63b4a2b5bc09bdd3da61594063a6edbaee6f9ceada4e458a4a58b44052e2b8bc0015820d0120ed0281bae6073b67737ea08444823010000b40012a06961f63019eec311fa0811c33ebb9d21e1a2c022629326cc5818e0c671b0809928d383400404ba97a1e131ec141f78a4efa812f9eefea1ea509e26021359d62f0366e3b8d87b0a0128a38bc7c31c585a67477802000720c072d24deb6be2481a2e02823c072100804a10e18219301c95382973b9a079063018c738a8ed301300691c1c67c0424f225e582e55b69abbe981719a673ce646096789b28ec64391180f0c01405c1500311c4c0fc17050882a0e8160331ca400000)

**Expected behavior**
Canvas should work in repl

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - React-pdf version [e.g. v1.1.0] (whateven in the repl)

**Comment by diegomura** [comment]
No other reason than I forgot. Canvas is a quite new element. Already fixed the issue on the site. I will publish as soon as I get in the pc
