### ISSUE TITLE
Repl playground not loading

### ISSUE THREAD

**Issue by hutch120** [diegomura/react-pdf#612]
Repl Playground not loading.
Console error:
`_app.js:1 [react-ga] gaTrackingID is required in initialize()`

**To Reproduce**
Go to https://react-pdf.org/repl

**Expected behavior**
Page loads.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Tried Chrome and Firefox.
 - React-pdf version N/A

**Comment by diegomura** [comment]
Thank you! It's fixed now 😄
