### ISSUE TITLE
Follow redirects when fetching images

### ISSUE THREAD

**Issue by julienfouilhe** [diegomura/react-pdf#614]
**Is your feature request related to a problem? Please describe.**
Currently, fetching an image doesn't follow redirects (on Nodejs at least).
If I put an URL and I get a `302` code, the image is not displayed

**Describe the solution you'd like**
It should follow the redirect and fetch the image at the new URL

**Comment by diegomura** [comment]
It is already following redirects. Check screenshot. `https://picsum.photos/1000/800`  redirects to `https://i.picsum.photos/id/239/1000/800.jpg?hmac=0L-UxwN-1uCIYxv-PMtvJ6wXS0BqTE5xiQw_qprQ_OM` which get's resolved below

<img width="1792" alt="Screen Shot 2021-06-05 at 19 36 39" src="https://user-images.githubusercontent.com/5600341/120907110-5bc2ee00-c635-11eb-8db6-d6bc8b669411.png">
