### ISSUE TITLE
When I install, prompt error “no matching version found for @react-pdf/textkit@^0.3.7 ”，but lastest version is 0.3.6，why？

### ISSUE THREAD

**Issue by hello-wuwei** [diegomura/react-pdf#616]
![image](https://user-images.githubusercontent.com/18006552/58445719-46ef1e00-8130-11e9-9676-9d43e0b49772.png)

**Comment by diegomura** [comment]
Not sure what's going on, but [lastest version is 0.3.7](https://github.com/react-pdf/textkit).
I cannot help with that little information
