### ISSUE TITLE
Generating PDF from array

### ISSUE THREAD

**Issue by nero2009** [diegomura/react-pdf#622]
I am trying to generate different pages of pdf from an array of objects. bascially I have a selectable table like this,
![rpdf1](https://user-images.githubusercontent.com/29065069/58711360-4ebff400-83b6-11e9-8eae-cdbf3afa4946.PNG)
which is generated from an array, what I wanted to achieve is that you can generate a pdf from every selected row, I can also select all and generate a pdf file for all them using `<PDFDownloadLink>`  problem is that when I unselect a particular row, I get this error in the console
![rpdf2](https://user-images.githubusercontent.com/29065069/58711853-3e5c4900-83b7-11e9-9cfe-9e900335761b.PNG)
 and when I download the pdf I get rows that I initially selected then unselected.

 - OS: Windows
 - Browser: Firefox
 - React-pdf version: 1.6.0

**Comment by diegomura** [comment]
Odd. Just for you to consider, you might be re-rendering the PDF every time the state changes (because of how `<PDFDownloadLink />` works. I suggest to find a way of preventing this. Sorry I cannot help more right now! I have to work 😂

**Comment by nero2009** [comment]
Thanks for the quick response but I don't really understand what you said. when I unselect a particular row I pass the new array as props to the react-pdf. 
is it that react-pdf only generates the PDF file once and it doesn't react to state changes?

**Comment by diegomura** [comment]
Exactly. When the document you pass to the `<PDFDownloadLink />` changes, the document re-renders internally, every time. You error seems to be related with Yoga and it might be because of many successive re-renders. It's just a quick guess though! Would be great to have a small snippet or project I can look to replicate it.

**Comment by nero2009** [comment]
This is codesandbox demo that replicates the problem [demo](https://codesandbox.io/s/summer-sunset-go907).
I console logged the array passed to the `<PDFDownloadLink /> `  `document` prop, it shows the array changing based on what is selected/deselected but the pdf doesn't

**Comment by nero2009** [comment]
@diegomura any luck checking this out

**Comment by diegomura** [comment]
Hey @nero2009 !
I just saw this sorry. Checking at your example, it seems that iterating through an array and rendering **pages** fails. The renderer does not update the document appropriately. 

However, rendering any other component from the array works:

```jsx
function PdfPage(props) {
  return (
    <Document>
      <Page>
        {props.data
          ? props.data.map((a, index) => {
              return (
                <View key={index}>
                  <Text>{a.id}</Text>
                  <Text>{a.name}</Text>
                  <Text>{a.color}</Text>
                </View>
              );
            })
          : ""}
      </Page>
    </Document>
  );
}
```

Now that the cause is clear I can work on a fix. I guess you strictly need a `<Page />` per element right?

**Comment by diegomura** [comment]
As a matter of fact, I think the fix is quite easy. I just created a PR with it but couldn't test it. Feel free to do it, or I will later today.

**Comment by nero2009** [comment]
Thanks for the quick reply and fix @diegomura, I just updated `react-pdf` in the codesandbox demo but it still breaks with the same error.

**Comment by diegomura** [comment]
I didn't published any new version. The PR is still open. I couldn't test it yet, sorry

**Comment by nero2009** [comment]
@diegomura  is there anyway I can help you to test it?

**Comment by diegomura** [comment]
Yeah! Test the PR in your project and check if fixed the issue

**Comment by nero2009** [comment]
Just tested it in my project, I don't get that error again but it still renders some rows I unselected in pdf.

**Comment by Y1a2s3h4** [comment]
In my case, I am passing an array of objects but only one object sends and then the log says  [{...}]. It should change on my adding of components
