### ISSUE TITLE
Chevin font corrupts text copy pasted from PDF

### ISSUE THREAD

**Issue by anttikekki** [diegomura/react-pdf#629]
**Describe the bug**
[Chevin](http://fontsgeek.com/fonts/Chevin-Light) font corrupts text copy pasted from PDF.

**To Reproduce**
```
const Test = () => (
  <Document>
    <Page>
      <View>
        <Text style={styles.roboto}>
          The Portable Document Format (PDF) (redundantly: PDF format) is a file format developed by Adobe in the 1990s to present documents, 
          including text formatting and images, in a manner independent of application software, hardware, and operating systems.[2][3] 
          Based on the PostScript language, each PDF file encapsulates a complete description of a fixed-layout flat document, including the 
          text, fonts, vector graphics, raster images and other information needed to display it. PDF was standardized as an open format, 
          ISO 32000, in 2008, and no longer requires any royalties for its implementation.
        </Text>
        <Text style={styles.chevin}>
          The Portable Document Format (PDF) (redundantly: PDF format) is a file format developed by Adobe in the 1990s to present documents, 
          including text formatting and images, in a manner independent of application software, hardware, and operating systems.[2][3] 
          Based on the PostScript language, each PDF file encapsulates a complete description of a fixed-layout flat document, including the 
          text, fonts, vector graphics, raster images and other information needed to display it. PDF was standardized as an open format, 
          ISO 32000, in 2008, and no longer requires any royalties for its implementation.
        </Text>
      </View>
    </Page>
  </Document>
);

Font.register(
  {src: 'https://pdf-font-test.s3.eu-central-1.amazonaws.com/Chevin-Light.ttf',
  family: 'Chevin' },
);

Font.register(
  {src: 'https://pdf-font-test.s3.eu-central-1.amazonaws.com/Roboto-Light.ttf',
  family: 'Roboto' },
);

const styles = StyleSheet.create({
  roboto: {
    fontFamily: 'Roboto'
  },
  
  chevin: {
    fontFamily: 'Chevin'
  }
});

ReactPDF.render(<Test />);
```
[REPL link](https://react-pdf.org/repl?code=3187b0760ce02e00402a05368c0bc30050129503e0c0a061801e0044460057016c130a1d0a24801404301cc1479e7880d40258200ee3d79f44003d634009e006c10a00def29440074009c4002310504005f711399c00160860b10daa1b3d4a6392ab5e8c0062f7a9b58e82ca45ed8e8da0800269460116cf40a72005cb6c1300066befed88210306ce9822e19da7eb01108006e080a20000e91307a7230008211fa3682603050d630008c009c83000cb94630b5e11074651434b3100034304ce6445dc00a94115d1c3d0832e99950507b793130827e5ccb57ddf97e606008daf7e5f531b330206979b5b50520980fe4138060105f940446c708ad2cb0888c2e117088fdeada50581f6103934010d42d001b4004c005d2240198c9ab75b3000426c199a3c1bd1b1d9a000656036904b558028e21c4a270102b041b18096149780a2e3a0836a104a20aa0483c8c140d440420d53072840797cb3b837e1ab4a08a491002d20ae4204a2c0d2aafd7cc3c5015a6db6bb6c4f4fa6b759aa642b0cbd0ee5560118de1c4c6d52cc0bba63f16f6ba8b7271165b2536062a94c1dd17a441a135d841016c66a08a09a194c061b968067118200178349917745d18e257f0ac03e60024a7200f2304a4924653cf775272300070ac33303008060356c6bc60e10023a5104d30bb35747236028ceeae295ca0b96b8ebdda0f0268077c003d348182fa23103f10a822994351ff0d1342952a2e94c2fc2c3e8ec0709c170dc0593c1f17b0088210830708a2188e228012649d09ed4a6c9d33946c5cdfc7d52a6a8ea0689a569da3d13a6e8d9019863187a35ca6241be769dc459fb3a436300b61d9ce20c9d138ce5f59754d6e19c352785e6cc3e3a1ca4f0cd3600120441135ba484d26856131460045b42458ca5d2e5a331692713c4d542534524296a569213196647e16260900b9235f975c85114b871525695088b5e5112b4e5555755f22d4753d40d00af49f8fe7c82d2b4225b42b0749d174f8a423d7b9449f5f6562a0a202490dc01bc5608ca3180632d3e360113264d514c6e04bacacdee0a3d2c2dca3444b1c9cb4adab5adeb3fc9b7335b76dd36e968ee886c1284e1cc709ca711814b9d175445735c372e0de5ddf743ce263c4053dcf611722bcab5bdb52501f3d39f3a58877d0e4fdcc6fa84510cc1215f760b8711bec43dd46130001b9f07c07c7a074040381c9baf4098351b460192001c92c538954495f57d6a088d26b543281ad355a04d0204a534041286b58059931051ad7e934360fc16dc0360442d0b557c00616b02a2e9ad00065040e109cd14e348f1a5898348f9c2892180f1897c0b00f19818c356e184691eadc2347934c6886c7719d709a8189d27c9ca7a9da6906ad19e6759f67e84e7b9de7f9c1785d02406a15f00095f443040597e5c5795d57d5cd7f09d7a38308c4378dfc14dfc14048164603d53413962f396b175503c27f01074054261744ce406481bde1a9af153ed6f18cf63bc6981ce88260c0a96c056e030eebbfc6f5d1ffba218c7c18c3cf238952374251af9b47407f4f66057c705368000)

**Expected behavior**
Text copy pasted from PDF from Chevin font paragraph should equal the Roboto version:
```
The Portable Document Format (PDF) (redundantly: PDF format) is a file
format developed by Adobe in the 1990s to present documents, including
text formatting and images, in a manner independent of application software,
hardware, and operating systems.[2][3] Based on the PostScript language,
each PDF file encapsulates a complete description of a fixed-layout flat doc-
ument, including the text, fonts, vector graphics, raster images and other in-
formation needed to display it. PDF was standardized as an open format, ISO
32000, in 2008, and no longer requires any royalties for its implementation.
```

**Actual behavior**
Copy pasted text from PDF from Chevin paragraph is corrupted:
```
The Portable Document Format (PDF) (redundantly: PDF format) is a vle format depeloAed 
by 1dobe in the 900,s to Aresent documentsg includinx tewt formattinx and imaxesg in a 
manner indeAendent of aAAlication soft.areg hard.areg and oAeratinx systems[2]32B3 Sased 
on the Post-criAt lanxuaxeg each PDF vle encaAz sulates a comAlete descriAtion of a 
vwedzlayout Iat documentg includinx the tewtg fontsg pector xraAhicsg raster imaxes and 
other information needed to disAlay it[ PDF .as standardiOed as an oAen formatg 8-q B],,,g in 
],,􏰃g and no lonxer re􏰄uires any royalties for its imAlementation[
```

Edit: rendering is also corrupted for Chevin paragraph:
![chevin-rendering-bug](https://user-images.githubusercontent.com/3984589/59088621-ad362680-8910-11e9-9339-aa46d5025d15.png)

**Desktop:**
    * OS: MacOS
    * Browser: Firefox 67
    * React-pdf version: REPL at 2019-06-06 v1.6.0

**Comment by Droow** [comment]
Having the same issue, I need to parse the document after it is created to identify headers and generate Table of Contents. Any solution to this?

**Comment by diegomura** [comment]
Not sure why some fonts are not loaded correctly by `fontkit`. Something that worked for me is opening the font with a font editor (such as [birdfont](https://birdfont.org/)) and export it again without changes

**Comment by Droow** [comment]
I just discovered that if I use one of the "default" fonts (Helvetica to be exact) then it works. This is then the output from `pdffont` command:
![Screenshot from 2019-07-24 17-44-47](https://user-images.githubusercontent.com/2531675/61808025-ec75f380-ae3a-11e9-8137-11481fcc5ad0.png)
So I think it is the Identity-H encoding doing this mess.

**Comment by anttikekki** [comment]
Exporting font with [Birdfont](https://birdfont.org/) fixed the problem on Chevin. I had tried to do the same fix with [Inkscape](https://inkscape.org/) font editor but with no luck this time.

I had the same problem with react-pdf 1.4.3 but then exporting the font again with Inkscape fixed it. Strange that different re-export tricks are needed for different versions of this library.

**Comment by emanuella92gomesr** [comment]
Having the same issue using Source Han Sans.

**Comment by santialbo** [comment]
If someone else is using google fonts I also managed to fix the fonts using fontforge with the following command
```
fontforge -lang=ff -c 'Open($1); Generate($2); Close();' xxx.ttf yyy.ttf
```
