### ISSUE TITLE
Huge bundle size if using this plugin

### ISSUE THREAD

**Issue by 0FilipK** [diegomura/react-pdf#632]
Hello,

I'm using `react-pdf/renderer` for a while and I noticed my app is so huge after bundled. Normally (without using `react-pdf/renderer`) app file size is around 500 KB (minified, no sourcemaps, gzipped) but with this plugin it's over 1.2MB (minified, no souremaps, gzipped also). That's insane. There is any trick to decrease this file size?

**Comment by diegomura** [comment]
Yes you are right. PDF generation isn’t cheap. I’m constantly trying to reduce bundle size but there are a lot of dependencies we need. Please check https://github.com/diegomura/react-pdf/issues/619 for a solution. In the future React-pdf will only load required dependencies for the nodes you use, that might help a bit

**Comment by paghruli** [comment]
Can we have a PDF viewer only variant which shall be light weight?

**Comment by diegomura** [comment]
The current viewer is actually a couple of lines long. All the bundle sizes goes on some (needed) dependencies such as yoga, textkit, fontkit and pdfkit

**Comment by eghazal27** [comment]
Hello Guys,

Did you find the root cause of the enormous bundle size? After using the package without chunks, it's taking around 15 additional minutes to bundle my app, and the size has jumped to 1.5 MB. 
Please advise, thank you !
