### ISSUE TITLE
Unsupport for Thai characters.

### ISSUE THREAD

**Issue by taveratch** [diegomura/react-pdf#633]
**Describe the bug**
Hello, I have tried to build PDF report with Thai Characters inside. I did register font family that support for Thai characters (You have use any of these fonts https://fonts.google.com/?subset=thai).
All of Thai characters turn to be squares.
<img width="915" alt="Screen Shot 2562-06-08 at 18 43 28" src="https://user-images.githubusercontent.com/8603253/59146896-1061af00-8a1e-11e9-8dfb-3b10c866f91c.png">

Here is my sample code.

```
Font.register({ family: 'Kanit', src: 'http://fonts.gstatic.com/s/mitr/v4/pxiLypw5ucZF-Tw4NLr8f1s.ttf' })

class InstallmentPDFPage extends React.Component {
  render() {
    return (
      <PDFViewer style={styles.container}>
        <Document>
          <Page size="A4" style={styles.page}>
            <Text style={styles.headerText}>{'รายการแสดง'}</Text>
            <Text style={styles.headerText}>{'List'}</Text>
          </Page>
        </Document>
      </PDFViewer>
    )
  }
}
```

Thank you, I'm not sure what I did wrong.

 - OS: MacOS
 - Browser Chrome, Safari
 - React-pdf version 1.6.2

**Comment by lpww** [comment]
Try the workaround described here https://github.com/diegomura/react-pdf/issues/588#issuecomment-491538579

I was able to get Japanese fonts working this way

**Comment by linerocks** [comment]
@taveratch This is purely font support issue to the characters. I tried it using fonts with Thai support and it displayed properly. Check this https://github.com/linerocks/react-pdf-thai/blob/main/src/App.js

![Screenshot from 2021-01-04 12-41-52](https://user-images.githubusercontent.com/34875772/103511756-353c3380-4e9a-11eb-94d7-c857e2263851.png)

**Comment by linerocks** [comment]
@taveratch  This is purely font support issue to the characters. I tried it using fonts with Thai support and it displayed properly. Check this https://github.com/linerocks/react-pdf-thai/blob/main/src/App.js

![Screenshot from 2021-01-04 14-38-26](https://user-images.githubusercontent.com/34875772/103512002-9bc15180-4e9a-11eb-92f8-533b47097af7.png)

**Comment by Razi321** [comment]
@lpww can you share the code that made Japanese works ? i'm trying to make it work too but still have the problem

**Comment by lpww** [comment]
@Razi321 There's no code to share, the workaround is 

```I opened the font with a font editor (Bird font is pretty good) and exported it without any changes and rendering went good.```

**Comment by diegomura** [comment]
Japanese text can only be rendered by importing a custom font, and found out fonts are sometimes corrupted or malformed. A workaround is what @lpww pointed out above. thanks
