### ISSUE TITLE
PDFDownloadLink generating 'type is invalid' error

### ISSUE THREAD

**Issue by colleenpurcell** [diegomura/react-pdf#634]
**Describe the bug**
Can't render the parent component of PDFDownloadLink. Trying to generates a 'type is invalid' error as if the MyDoc function (returning elements wrapped by the imported react-pdf 'Document' parent element) is undefined. I followed this example quite closely:
https://react-pdf.org/advanced#on-the-fly-rendering

**Errors**

- Uncaught Error: Invalid element of type div passed to PDF renderer react-pdf.browser.es.js:5351 
The above error occurred in the < InternalBlobProvider >
- React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.  http://react.development.js:247
The above error occurred in the < div > component: in div (created by Message)

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. See Code snippet below
2. I try to render the component
3. It shows the errors below

**Expected behavior**
Expected to see a link with text: "Download now!"

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
- React-pdf version: "@react-pdf/renderer": "^1.6.2" and "react-pdf": "^4.0.5"

React Component:
```
import React from "react";
import ReactDOM from "react-dom";
import { PDFDownloadLink, Page, Text, View, Document } from "react-pdf";

class Component extends React.Component {

  render() {
    const MyDoc = () => (
      <Document>
       <Page>
          <View>
            <Text>Section #1</Text>
          </View>
        </Page>
      </Document>
    );

   return (
      <div >
        DOWNLOAD PDF:
        <div>
          <PDFDownloadLink document={<MyDoc/>} fileName="somename.pdf">
            {({ blob, url, loading, error }) =>
              loading ? "Loading document..." : "Download now!"
            }
          </PDFDownloadLink>
        </div>
      </div>
    );
  }
}

```

**Comment by Turan91** [comment]
I see the exact same behaviour as above.

**Comment by diegomura** [comment]
> Invalid element of type div passed to PDF renderer

Somehow you have a div inside you document definition. You should stick with react-pdf primitives. You cannot render DOM nodes inside react-pdf documents

**Comment by diegomura** [comment]
Wait. You’re also importing things from “react-pdf”. This package is under “@react-pdf/renderer” name since the latter was already taken
