### ISSUE TITLE
When can you use custom fonts when rendering in Web?

### ISSUE THREAD

**Issue by RBLAlexander** [diegomura/react-pdf#636]
Im trying to make a simple client side rendered and downloaded PDF, but completely failing to be able to import a custom font.

digging around in old issues i found this quote [https://github.com/diegomura/react-pdf/issues/310#issuecomment-442360837](here) Nowhere in the docs does it mention this and the quote is old, is this still true?

My font registration looks like this:
```
Font.register( {
  family: 'Roboto',
  fonts: [
    {
      src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf',
      fontWeight: 'bold',
    }
  ],
});
```

That link is to a valid ttf font, i have also tried importing with relative and absolute paths from local resources and no dice, just constantly get 'TypeError: Cannot read property 'hasGlyphForCodePoint' of null' on line 3776'

```
var buildSubsetForFont = function buildSubsetForFont(font) {
  return IGNORABLE_CODEPOINTS.reduce(function (acc, codePoint) {
    if (font.hasGlyphForCodePoint && font.hasGlyphForCodePoint(codePoint)) {
      return acc;
    }

    return [].concat(acc, [String.fromCharCode(codePoint)]);
  }, []);
};
```
Is there another pattern for directly downloading a PDF with Custom Fonts that i have missed

Regards - Ralph

**Comment by RBLAlexander** [comment]
Bump, noone is using non standard fonts and rendering clientside?

**Comment by diegomura** [comment]
Hey. You can use custom fonts on the web. That seems weird. Seems that the font is not loading correctly (maybe CORS?). Could you provide an example in the REPL or anywhere else that I can see?

**Comment by lpww** [comment]
You can try this workaround, it helped solve custom font issues for me https://github.com/diegomura/react-pdf/issues/588#issuecomment-491538579

**Comment by joshsuson** [comment]
I'm having this exact same issue. I have tried importing the font. I've tried downloading the Bird Font program and exporting it. No matter what I do it says unknown font format and then this same null error. It's a .ttf file. Is there any solution for this?

**Comment by diegomura** [comment]
@joshsuson can you share how are you registering the font? Thanks!
