### ISSUE TITLE
Child already has a parent, it must be removed first

### ISSUE THREAD

**Issue by michaelkasper** [diegomura/react-pdf#637]
Im getting the following error:
>Child already has a parent, it must be removed first.

Not sure whats going on. i think its related to a memory leak in yoga. Have tried several things to pin point the cause and there seems to be no rhyme or reason on whats going on.

Originally, i have a script that is generating two different pdfs concurrently (dont build the second till the first is done). i can revers which pdf is being generated first and i still get the error always for the second pdf.

I have tried simplifying the pdfs and their seems to be no consistency on whats causing the issue. Any thoughts would be helpful.

here is the full error i get:

>Child already has a parent, it must be removed first.
>The above error occurred in the <PAGE> component:
>    in PAGE (created by PDFBase) <-- ReactPdf component
>    in DOCUMENT (created by PDFBase)  <-- ReactPdf component
>    in PDFBase <-- my base component
>
>Consider adding an error boundary to your tree to customize error handling behavior.
>Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
>abort() at Error: 
>    at jsStackTrace (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:443:15)
>    at stackTrace (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:453:14)
>    at Object.abort (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:9808:182)
>    at _abort (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:585:20)
>    at ge (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:2905:136)
>    at Vd (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:2443:101)
>    at ec (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:1928:23)
>    at kc (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:1951:86)
>    at Ig (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:3444:37)
>    at hm (ROOT/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:4785:228)
>If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
>

Thanks

**Comment by webdobe** [comment]
I am getting this same issue when using the PDFDownloadLink it is getting fired on an imported Header component that that is just which is:
```
export default () => (
  <View style={styles.container}>
    <View style={styles.logoColumn}>
      <Image style={styles.logo} src={logo} />
    </View>
    <View style={styles.detailColumn}>
      <Text style={styles.tribe}>xxx</Text>
      <Text style={styles.department}>xxx</Text>
      <Text style={styles.address}>xxx</Text>
      <Text style={styles.address}>xxx</Text>
      <Text style={styles.address}>xxx</Text>
      <Text style={styles.address}>xxx</Text>
    </View>
    <View style={styles.offsetColumn}><Text>&nbsp;</Text></View>
  </View>
);
```
I do not get this error when doing using the PDFViewer.

**Comment by izzybaer** [comment]
@diegomura hi - is this something you're aware of?

@webdobe @michaelkasper have either of you made progress on this? I'm getting the same error right now using PDFDownloadLink

**Comment by webdobe** [comment]
@izzybaer I am pretty sure this happens because the pdf component gets rendered more than once.  So you need to make sure you have everything property wise before you render the pdf.  I do this by using a loading state and setting componentWillUpdate to false.  Let me know if that helps

**Comment by izzybaer** [comment]
@webdobe Hi thank you! I solved this by doing something similar :) appreciate the help!

**Comment by diegomura** [comment]
Thank you all! sorry for the delay. This should not happen anymore in 2.0 also
