### ISSUE TITLE
Non-whole numbers as css style value are not working

### ISSUE THREAD

**Issue by jp06** [diegomura/react-pdf#641]
In the playground, I tried changing `styles.body.paddingTop`  from `36` to `'1 in'` and it works. But when I tried changing it to `'1.5 in'`, the padding ends up not working. 

Alternative solution is to just use the default `pt` in everything (`'72 pt'` = `'1 in'`) so `1.5 in` would be `108` but it would be nice if decimals do work also.

**Comment by kwoterG** [comment]
It looks like the number after the dot is used for calculating.

Example:
padding: 10.5mm will generate a padding of 5 mm and a padding of 10.1 will generate 1 mm of padding.

**Comment by diegomura** [comment]
Fixed in the last 1.X and 2.0 version. Thanks!
