### ISSUE TITLE
Page wrapping creates empty element

### ISSUE THREAD

**Issue by maxaggedon** [diegomura/react-pdf#642]
**Describe the bug**
Sometimes single line text element gets wrapped at the top or bottom of a page. This creates an empty element on the other page. It does not look good when there is a parent with some `backgroudColor`.

**Expected behavior**
Single line `Text` should never get page wrapped, or is there a case I am missing ?

**Screenshots**
![image](https://user-images.githubusercontent.com/17004545/59663832-2acf2180-91b0-11e9-909f-9548b264a09c.png)

**Desktop (please complete the following information):**
 - OS: MacOS, Ubuntu
 - node.js
 - React-pdf version 1.4.2

**Comment by maxaggedon** [comment]
**Note** : a simple workaround is to set `wrap={false}`, but I figured it was worth mentioning anyway.

**Comment by diegomura** [comment]
@maxaggedon can you try this on the latest 2.0? Or provide a snippet so I can replicate it. I never seen something like this

**Comment by maxaggedon** [comment]
@diegomura I will try to find some time this week or next in order to reproduce and check if it still happening on v2

**Comment by diegomura** [comment]
Thanks!! I think it's not but testing it would be very helpful. Feel free to close the issue if you confirm it's fixed

**Comment by maxaggedon** [comment]
Hey @diegomura !

I just took the time to test it again. Here are the results :

- **v1.6.8**

![image](https://user-images.githubusercontent.com/17004545/116224228-aefd7300-a750-11eb-87c7-f0e90f1614f4.png)

 - **v2.0.8**

![image](https://user-images.githubusercontent.com/17004545/116225261-eb7d9e80-a751-11eb-842d-928eddd698f7.png)

It is still present, but as I look at it now, I am not sure that it should be considered a bug... I fixed it quite easily with the `wrap` prop. Given the workaround and the absence of other complaints on the matter, I think it's better to leave it as is and focus on other stuff !
