### ISSUE TITLE
Nested <Text /> is broken

### ISSUE THREAD

**Issue by maxaggedon** [diegomura/react-pdf#644]
**Describe the bug**
When there are different font sizes within the same `<Text>` element, the letter spacing of the last part is applied to the whole text.

**To Reproduce**
[REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec8313314943390804792830b175348f1f1e78805ba8041110180049002e78042c285b1e281e181b181111d030252460240067b01821180c002b3b39b9f69b11271e46100876f324251e113e769a595acd442435f42c31899800591e306073119d3d02a99241247380a0006524000bc303d00230005954ea19a391c76162c141ac18041a1184cbe5725a2c80389947fbe971852309564650a95430350f271ea4d169b53a3d443f506c351960de53199cd16cb5586d6c5b240ec307b4701c8e273385cae301b9dd380f27a6105e311a7dbebf6a3e5a94089082c190984f400cc00366471151e8ff0e3b1067c612c95a9f4e4ee7eb36198a34b93c5f818001c931e476073ba6cb6491e0243008c08638c38ed8003430283a02ebc0104060aa2236148782d6500006001209067a3b1f8cc0323026e17862212d995475ad4101cce142b83bc4ccbf7dc993a03198ac7601000dc6432000c4c1b27f1f090d03b2a6388ac612044421e801c800f2106085c9497dcc7020d2abf98a05078840ba190ca7ae43e1a021966591404603208032239ef110940c80037384ed0c8004d001f5b4001a400350744000038007510010f900055250ed461d080034004e1e00041263644fd1c4bcc80acd7320a6681cd19070181c11a5c14b030280c0a893023d28450541e8245a82325066300f86d040789ed001599f4d054b52f800085d042d181e81d3d394eb08c80024405b1a13042e5d3f4f2ddcca8a031114da93d1b5611800026045dcca1307d098910903e0c02bd804c4ec27cfcb0437038cf0bc601bcef07d38ca15477278041c24737ccd1fcfc5e120ac282c0128a62b8ab284b5824a6ac60785b0f73014ccfc400b26004400067720a97dca2f27c98094f2bad4aa6038408b6a3aaeaaa9ab3d34b4f73caf5bd60c7c3851bc2804cace1dacea9046ae16aa52d6002f8542da822a81ead8aaf35810680904708464a66d60368caaf6d0906602058800253eabe3ca3c8e181c8d8eca14eaea70bb12a6015cf9baccd091f3a1ca72a11724478506e1bf6f732c6b0ec0469c59b6d79aaeec796f3a7af327a20b49cd11ee7b1acbd9acc16c1fb38500da5b0af3e1fc6fa46f725b2cc736a7e2238c2594799e1e46384462a30417280aae9cba6ac517afeaed0e7383111c2807a53728272f80fcad9aab9e8a5ea6b128166ae174aacbc58c125b26b8d5dd7306ac188b81a0371dc5824cf02a01e340f50c98840e8000)

**Expected behavior**
Each text run should not be affected by style changes in other parts.

**Comment by jp06** [comment]
Why would you nest `<Text>` though? I don't think it's supposed to be used like that.

**Comment by diegomura** [comment]
That's weird 🤔 
@jp06 you may want to add inline `<Text />` to apply inline styles (think of it like a `<span />`)
I'll try to take a look at this soon

**Comment by jp06** [comment]
That is actually that is one use case I neglected 😅. I've only used the library for a few days and never had to do something like a `<span/>` so far.

**Comment by niksauer** [comment]
Any news, or will this be fixed in v2?

**Comment by mabeyj** [comment]
This change is what broke the spacing: https://github.com/diegomura/react-pdf/pull/569

I don't know what a proper fix would be, but removing these lines in v1.6.8 seems to fix it (but probably undoes what the above PR fixes):

```diff
--- a/src/layout/fontSubstitution/index.js
+++ b/src/layout/fontSubstitution/index.js
@@ -61,7 +61,7 @@ const fontSubstitution = () => ({ string, runs }) => {
             end: index,
             attributes: {
               font: lastFont,
-              scale: lastFont ? fontSize / lastFont.unitsPerEm : 0,
+              //scale: lastFont ? fontSize / lastFont.unitsPerEm : 0,
             },
           });
         }
@@ -82,7 +82,7 @@ const fontSubstitution = () => ({ string, runs }) => {
       end: string.length,
       attributes: {
         font: lastFont,
-        scale: lastFont ? fontSize / lastFont.unitsPerEm : 0,
+        //scale: lastFont ? fontSize / lastFont.unitsPerEm : 0,
       },
     });
   }
```

Related: https://github.com/diegomura/react-pdf/issues/646, https://github.com/diegomura/react-pdf/issues/722

**Comment by armspkt** [comment]
@diegomura 
When I nested Text component I had an error like this

 ```
    <Text style={styles.subtitle}>
        Capítulo I: Que trata de la condición y ejercicio del famoso hidalgo D.
        Quijote de la Mancha{' '}
        <Text style={styles.subtitle}>
          Capítulo I: Que trata de la condición y ejercicio del famoso hidalgo
          D. Quijote de la Mancha
        </Text>
      </Text>
```

<img width="593" alt="Screen Shot 2563-08-13 at 01 21 48" src="https://user-images.githubusercontent.com/49720317/90052519-72453500-dd03-11ea-9a1b-77f43d3302dc.png">

**Comment by aaronjedwards** [comment]
This seems to be working as of version 2.0.16. Nesting `Text` elements within a parent `Text` element will display them inline.
