### ISSUE TITLE
Open renderer link on new window

### ISSUE THREAD

**Issue by finbar123** [diegomura/react-pdf#645]
Excellent library

Would it be possible to add the ability to make the rendered link in the pdf open in a new window

Something like   `<Link src={"www.google.com"} target={"_blank"}>{"Google"}</Link> `

Apologies if this is already possible couldn't see from the documentation

Thanks

Finbar

**Comment by jp06** [comment]
Isn't there a `Link` component in the documentation? Check out the components available in the library: https://react-pdf.org/components

**Comment by finbar123** [comment]
Jp06

Hi yes we are using the Link component to render the link inside the PDF and it works fine.

We use the  PDFViewer component to display the rendered PDF but when the actual link is clicked the linked page opens in the existing browser window,  we would prefer it opens in a new window. I guess I am assuming that that  target=_blank functionality is supported in a PDF ?

Regards

Finbar

**Comment by jp06** [comment]
Came across this thread just yesterday, you might be referring to this: https://github.com/diegomura/react-pdf/issues/318

**Comment by finbar123** [comment]
Diego

 

Hi yes I saw that but not sure that helps it will show the entire PDF in a new window, the use case we have is clicking a link in the rendered PDF the link should open in a new window, not the one the PDF is displayed in

 

Regards

 

Finbar

**Comment by jp06** [comment]
It is working. The returned anchor tag should open in new tab.

My code looks like this:

    import React from 'react'
    import { BlobProvider } from '@react-pdf/renderer'
    import Receipt from '../Receipt' // `Receipt` has the document component

    const ViewReceipt = () => (
      <BlobProvider document={Receipt}>
        {({ url }) => (
          <a className="button" href={url} target="_blank" rel="noopener noreferrer">
            Open in New Tab
          </a>
        )}
      </BlobProvider>
    )

    export default ViewReceipt

**Comment by psnfrench** [comment]
I would love to see this functionality too. As @finbar123 describes, I would like the link that is rendered inside the pdf to have `target="_blank"` so clicking on the link from within the rendered pdf opens a new tab.

Note: this is different functionality from opening the entire pdf document in a new tab as described by @jp06

**Comment by jp06** [comment]
I'm sorry. Reading more carefully now, I totally missed his point. I thought he meant the link to the PDF but instead, it is the link inside the PDF that he wants a `target="_blank"`.

**Comment by SomnathKadam** [comment]
If you need to open generated pdf on new window, without click on download link, use below code

```
const PrintDoc = ({ values }) => (
    <Document>
        <Page size="A6" style={styles.page}>
            <View style={styles.section}>
                <Text>Section #1</Text>
            </View>
             
        </Page>
    </Document>
);

const openPDF = (url) => {
    window.open(url, '_blank');
};

export const PDFPrint = () => {
    return (
        <PDFDownloadLink document={<PrintDoc />} fileName="somename.pdf">
            {({ blob, url, loading, error }) =>
                loading ? 'Loading document...' : openPDF(url)
            }
        </PDFDownloadLink>
    );
};
```

**Comment by asokr** [comment]
SomnathKadam, 
read previous comment please, it's not an answer too...

To open rendered links in new tab/window I'm using handler on parent div, witch catch all clicks on rendered pdf, then just use if statement - to know if target is link or not:

```js 
 openLinkInNewTab = (e) => {
        e.preventDefault();
        if (e.target.tagName.toLowerCase() === 'a') {
            window.open( e.target.href );
        }
    }
```
```js
<div className="pdf-block" onClick={this.openLinkInNewTab}>
  <Document
  </Document>
</div>
```

**Comment by atchuta168** [comment]
@finbar123 
Any solution for above issue
Folks are giving solutions to open complete PDF in new tab..
But issues is inside PDF we have links for that we use Link tag <Link>  which is opening that in same tab

**Comment by atchuta168** [comment]
> Excellent library
> 
> Would it be possible to add the ability to make the rendered link in the pdf open in a new window
> 
> Something like `<Link src={"www.google.com"} target={"_blank"}>{"Google"}</Link> `
> 
> Apologies if this is already possible couldn't see from the documentation
> 
> Thanks
> 
> Finbar

Could you find Any solution do this issue ?

**Comment by Yosmarpc** [comment]
Creo  que la gran mayoria  no entendieron la problematica que esta indicando @finbar123 lo que se requiere es tratar de asignar link para redireccionar cuando el pdf este creado, osea dentro del contenido, en la documentacion esta la Etiqueta Link pero al momento de probar me arroja error, de renderizado. no se alguien tiene una solucion a dicho problema

**Comment by whaleprophet** [comment]
+1 to this feature please

**Comment by vangelov** [comment]
+1 to this feature from me too

**Comment by jeetiss** [comment]
pdf 1.7 doesn't have any options to do that, here the [spec pages 394-395](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf)

I think that browser's pdf viewer should care about URI links, not the pdf file, because other viewers doesn't have tabs and just open links in default browser (in a new os window).

**Comment by vangelov** [comment]
That makes sense. I was previewing the pdf in the browser and treating it as a webpage, but it's not.

**Comment by Naveenmadasani** [comment]
can you tell me how to open a link which is present inside the pdf that link will be open in a new tab using pdfrendrer

**Comment by mandula-abhilash** [comment]
+1 to this feature

**Comment by nanashi-74** [comment]
> That makes sense. I was previewing the pdf in the browser and treating it as a webpage, but it's not.

Viewing PDFs in web browsers is a standard use case. +1 to this feature which if I understand it correctly is:

Please add a target="__blank" attribute to the Link component to open clicked links (in a web browser PDF view) in a new browser window or tab. 

Thanks.

**Comment by davidcaribou** [comment]
Is this actually completed?  Latest docs don't  indicate any "target" attribute available on Link component.

**Comment by jiangxiaoqiang** [comment]
> ```js
>  openLinkInNewTab = (e) => {
>         e.preventDefault();
>         if (e.target.tagName.toLowerCase() === 'a') {
>             window.open( e.target.href );
>         }
>     }
> ```

this works for me.

**Comment by amit-mishra-lrn** [comment]
> SomnathKadam, read previous comment please, it's not an answer too...
> 
> To open rendered links in new tab/window I'm using handler on parent div, witch catch all clicks on rendered pdf, then just use if statement - to know if target is link or not:
> 
> ```js
>  openLinkInNewTab = (e) => {
>         e.preventDefault();
>         if (e.target.tagName.toLowerCase() === 'a') {
>             window.open( e.target.href );
>         }
>     }
> ```
> 
> ```js
> <div className="pdf-block" onClick={this.openLinkInNewTab}>
>   <Document
>   </Document>
> </div>
> ```

This solution works, Is there any issues observed by anyone while using this approach ?
