### ISSUE TITLE
Font spacing is different in 1.5.3

### ISSUE THREAD

**Issue by aaldrich** [diegomura/react-pdf#646]
**Describe the bug**
I recently upgraded and the spacing on the fonts is either spaced out or too close together where previously it looked fine. I started backtracking releases and got it down to release 1.5.3. It works fine in 1.5.2  but anything 1.5.3 and above it is broken. 

It might be something new that I need to account for but I'm not sure where to start. Could someone point me to what they think might be causing this and how it can be addressed if it's not a bug?

**Screenshots**
1.5.2 - https://cargo.teamairship.com/sxoZH5
1.5.3 - https://cargo.teamairship.com/agYsiQ

**Comment by diegomura** [comment]
Sorry for never coming back to this @aaldrich . It's hard to keep up with everything. This refers to very old versions. I tried in the latest and font spacing looks good. Please report back if this issue still persist.
