### ISSUE TITLE
Doesn't work properly in create-react-app

### ISSUE THREAD

**Issue by heshamnaim** [diegomura/react-pdf#647]
**Describe the bug**
import error below
"
RangeError
Potential infinite loop: exceeded 10001 iterations. You can disable this check by creating a sandbox.config.json file.
"
if I remove imports for react-pdf and associated code the error goes away

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
Go on codepen, use create-react-app template add in react-pdf

https://codesandbox.io/embed/nervous-mahavira-n0kfh

**Expected behavior**
Display PDF

**Screenshots**
https://codesandbox.io/embed/nervous-mahavira-n0kfh

**Desktop (please complete the following information):**
codepen

**Comment by diegomura** [comment]
That's an issue of react-pdf on codesandbox, not create-react-app itself. Duplicate: https://github.com/diegomura/react-pdf/issues/462
