### ISSUE TITLE
Cannot fetch local path

### ISSUE THREAD

**Issue by liron-navon** [diegomura/react-pdf#655]
-- on hind side it might not be a bug, but the docs require some clarification...

-- I figured I need to use "allowDangerousPaths" or do something with "safePath", but I have no idea what is considered safe or dangerous in this context.

**Describe the bug**
I'm trying to load a local path (full path), ie:
`/Users/lironnavon/Desktop/node-project-name/assets/images/logo.png`
But the image will not show and this error appears:
```
Cannot fetch dangerous local path: /Users/lironnavon/Desktop/node-project-name/assets/images/logo.png
```

If I try to load the image from a url, or from a buffer (fs.readFile), it works perfectly...

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Run the project with Node
2. Give the image source path
3. Doesn't render image (blank page)

**Expected behavior**
The image should render

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node version: v10.16.0
 - "@react-pdf/renderer": "^1.5.6"

**Comment by jwrlee88** [comment]
Hi there! I'm running into a similar bug(?) as you, this might vary on how you set up your project, but I got a little bit further than you by importing my logo using relative paths.

so I did something like

`import logo from '../../assets/logo.png`

and then I put `<Image src={logo}/>`and I got the image to show.

However, the problem I am facing now, is that the image renders twice. I took a screenshot and put it here: http://i.imgur.com/IDN6vGr.png, has anyone else run into this before?

**Comment by liron-navon** [comment]
Apparently it's my fault but I blame the documentation for being uninstructive - I used `allowDangerousPaths` but it's weird since I have my own assets path and this boolean can scare developers who are unfamiliar with it, why would "assets" or "images" be dangerous while "public" isn't? that's confusing and doesn't seem to make any sense.

The documentation and error message should be updated to define what "dangerous path" even means in the context of node.

**Comment by liron-navon** [comment]
@jwrlee88 

That's a completely different issue, maybe you should open a new issue for it - though it doesn't seem like the react-pdf team is replying too fast.

I have never had your double image issue, sorry.
