### ISSUE TITLE
How can i edit file name in dowload preview ? 

### ISSUE THREAD

**Issue by anwumbo** [diegomura/react-pdf#659]
Hi all, 
How can i edit file name in preview PDF? 
![Screenshot from 2019-07-03 10-56-44](https://user-images.githubusercontent.com/51742384/60562502-13805e80-9d82-11e9-870b-fbbab361cd6a.png)

**Comment by jwrlee88** [comment]
This isn't really a new feature, but you can add a `title` prop to the document that changes the filename when you go to download it. Documentation for reference: https://react-pdf.org/components#document

**Comment by nabn** [comment]
Setting the `title` prop doesn't actually change the filename. Is there any other workaround?

**Comment by corneliushka** [comment]
Changing the prop _title_  doesn't work. Somebody handled it ?
