### ISSUE TITLE
Text overflow inside a flex container

### ISSUE THREAD

**Issue by ubreddy** [diegomura/react-pdf#660]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2233628/60589604-8821c000-9db7-11e9-87e9-279257b54967.png)

The text is overflowing the width of the flex container... If I provide absolute width then it does not overflow, like the one in the leftColumn...
Just to indicate I have drawn the borders of each item...

Is there a property to set to make this work?

Latest version of react-pdf on win-os.
Thank you .

**Comment by ubreddy** [comment]
adding flexShrink: 1 on the container solves it... Thank you

**Comment by America-first-melon** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> ![image](https://user-images.githubusercontent.com/2233628/60589604-8821c000-9db7-11e9-87e9-279257b54967.png)
> 
> The text is overflowing the width of the flex container... If I provide absolute width then it does not overflow, like the one in the leftColumn...
> Just to indicate I have drawn the borders of each item...
> 
> Is there a property to set to make this work?
> 
> Latest version of react-pdf on win-os.
> Thank you .

Hi, Does this property work?  I can't do it here...

**Comment by SaadMosallam-git** [comment]
This problem happens because you have disabled the library default hyphenation 
remove the Font.registerHyphenationCallback and it will wrap with the word split in two lines.

**Comment by chathu-novade** [comment]
Using

```
overflow:"hidden",
```

Will fix this. But better to get`ellipsis` behaviour would be good.

**Comment by oliverstreissi** [comment]
Why is this closed, I'm still facing the problem, the mentioned "solutions" above are not solving this issue. It seems like the default hyphenation is causing this problem.

**Comment by imrajat24** [comment]
i am also facing this issue
<img width="948" alt="Screenshot 2024-04-08 at 8 42 49 PM" src="https://github.com/diegomura/react-pdf/assets/43917552/d17643ec-3e4c-46a4-9133-256e5c432361">

**Comment by jcmordan** [comment]
I'm facing the same issue, the text overlaps and exceeds the page margins.

**Comment by youssefbenlemlih** [comment]
Giving the text a flex:1 solved my problem:
```javascript
<View
  style={{
    display: "flex",
    flexDirection: "row",
    gap: 10,
  }}
>
  <Text>Short Text</Text>
  <Text
    style={{
      // this forces the text to respect the page padding and wrap
      flex: 1,
    }}
  >
    Very long text...
  </Text>
</View>;
```

**Comment by Yuniac** [comment]
So no one found what's causing this?

**Comment by prasang-onelot** [comment]
Giving maxwidth to container works

**Comment by rohankm** [comment]
anyone? with proper solution? this is so frustrating

**Comment by aryan-programmer** [comment]
The solution I eventually found for the same problem was to use:
```jsx
<View
	style={{
		flex: 1,
		border: "1px solid white",
	}}>
	{children}
</View>
```
Where, "1px solid white" is meant to be an invisible border whose color matches with that of the background.

Yes, I know how _unsatisfactory_ an answer like this is, but it works.

**Comment by mikejobrn** [comment]
I've tryed `flex: 1`, `maxwidth`, `flexShrink`, `flexGrow`, `flexBasis`, `flexWrap`... none of them has worked. The only thing that works is setting an absolute width, but I can't use that in my case. Can this issue be reopened?

**Comment by AlexPham-HIVO** [comment]
`flex: 1` worked for me

**Comment by TSIA-SN** [comment]
Using flex: 1 causes other sibling elements to overlap the element that has flex: 1 set on it for me, so it's not a good permanent solution. Would be better if there was an actual fix for this that didn't require us to specify styles in order for it to render properly. This issue shouldn't be in Closed status.

**Comment by edwindwalker** [comment]
I'm trying to truncate a version number and also prevent it from wrapping. I'm experiencing some very strange behaviour depending on the content that is being truncated.

```
<View style={{ display: "flex", flexDirection: "row" }}>
  <Text style={{ maxWidth: 50, maxLines: 1, textOverflow: 'ellipsis' }}>
    {/* Insert text here */}
  </Text>
</View>
```

Examples:

- `abcdefghijklmnopqrstuvwxyz` truncates to `abcde…`
- `12345678901234567890` overflows
- `abc.defghijklmnopqrstuvwxyz` truncates to `abc.de…`
- `abcdef.ghijklmnopqrstuvwxyz` overflows

The last two examples can be reproduced with various different characters. I assume these are characters that usually cause the text to wrap, but that the text is not being allowed to wrap, so it just overflows.
