### ISSUE TITLE
[docs] Expose a non-react way to render to a blob

### ISSUE THREAD

**Issue by wkrueger** [diegomura/react-pdf#661]
Currently the only documented way render a document to a blob is by using a react component, which is coupled to using react-dom on the frontend. What if I wanted to do it in a non-react app?

From a quick look on the sources this seems a simple task, but it is still not documented.

**Comment by astriskit** [comment]
Any one doing any PR for this.

**Comment by wkrueger** [comment]
This is as simple as

```tsx
import { pdf } from '@react-pdf/renderer'
const doc = <>...</>
const instance = pdf(doc)
const blob = instance.toBlob()
```

just needs to be documented.

For custom webpack builds you may need to add the node handlers (CRA already includes it).

```ts
module.exports = (config, options) => {
  // ajuste no webpack pro pdfkit
  config.node = {
    module: 'empty',
    dgram: 'empty',
    dns: 'mock',
    fs: 'empty',
    http2: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty',
  }
  return config
}
```

This was for an Angular project (yeah, a code smell).

**Comment by astriskit** [comment]
Yes, I also found that while gong through source-code. But thanks for indicating at first that there is way to render in non-render manner.

I suggest to do a PR at - https://github.com/react-pdf/site

**Comment by diegomura** [comment]
A PR would be great!

**Comment by wkrueger** [comment]
PR links
https://github.com/react-pdf/site/pull/23
https://github.com/react-pdf/site/pull/24

**Comment by diegomura** [comment]
Thank you!
