### ISSUE TITLE
Latin extended characters not rendering

### ISSUE THREAD

**Issue by szmarci** [diegomura/react-pdf#667]
**Describe the bug**
I loaded a Google Font (Roboto) that I know it supports latin extended characters, like this:

```
Font.register(
  'https://fonts.gstatic.com/s/roboto/v19/KFOmCnqEu92Fr1Mu4mxPKTU1Kg.ttf',
  { family: 'Roboto' },
);
```

I put below the repl link and screenshot.

**To Reproduce**
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231ca848a18d530019aa0c4a366ca209002b0f3102820206d4040e080805e8030808a80808e80005f006f003f00cf1c9a5400f4baface9429bc02ce29740cccacec0400dc64640062e050b2004e187c48d018b5781c00e400165050000e10005cc9c9b6d5727cd03c16c0b2a08cc910c9b5208a5020c9006e008c009cc900d21500f28c00c260008e00a2083b004c15b55b00b208002c8c285cfbda00aa5bfb3e2c87ab6768006838123b0f11848111080630768009456e8103b460aa08695caa0480184c321c0c000ca448c2933a180c0d580f529860f0120e058ac18444b334a35629290002f0e4c0ee6f0866930fa0020888907c30223dac0162616ae0c49d9aa15185c21148d46ac311c6c59154b8b2322303c60140b8340a9d4584a169e0a888543a0b0c9622e2800000

**Screenshots**
This is what I get.
![image](https://user-images.githubusercontent.com/1974290/61381635-a30e2d00-a8ab-11e9-8855-c8a7a5b68b55.png)

**Comment by diegomura** [comment]
This happens when the font does not have the glyphs you want to render. I'll try to look deeper

**Comment by szmarci** [comment]
@diegomura thanks!

**Comment by sskiathitis** [comment]
Had the same issue. Looks like if you are using a Google font link, even with language set selected, it is ignored.
Find and download the correct font library from another provider and use it locally. It worked for me!

**Comment by tomasmatulis0** [comment]
@diegomura did you resolve this issue?

**Comment by diegomura** [comment]
No sorry. Didn't have time yet 😓

**Comment by tomasmatulis0** [comment]
I've found one solution in one of the other issues https://github.com/diegomura/react-pdf/issues/680#issuecomment-527619387.
Importing .ttf file and then passing to Font.register() helped. But still getting errors:

`Uncaught (in promise) TypeError: Cannot read property 'hasGlyphForCodePoint' of null
    at react-pdf.browser.es.js:3824`

**Comment by lpww** [comment]
I'm seeing the same issue with url and local imports. The aforementioned import solution does not seem to help for all the fonts I've tested (Source Han Serif, Kosugi Maru, Noto San JP, Source San Pro). Keifont from this [example](https://react-pdf.org/repl?code=1887b07602e07404e0a6073025819c271802800607a5c02403780ee4980098825400d880318086112e1400588680beb9a2c9035c00cdc0414b80359c24632140810476003400088802875ea45300b6496804f005cea011006959f2225ad3c025006e2d5a1b834ead09da7028ea00bcea00ca10fe70611c7070d00cf02c7098dabae8001e101669ba7ae26148005e7016004c00acaa3a79f6c086c6e656b672e28eba3c4e6e1e5e603e0082000e8321ea98ce21007c6335003c00228c00ae0670909335bab3000a4c0870bec570c196fd002c961b7979b3002a7059be9101c1447e01288a0f103c93800072802133403fbca00295d00776e8010b7401d83200bef500964e806198c0074c601f015008a9a80105f4007d9acd70f72c95daeea3bb7c9e5157bbd025f2cafd01a0c86c311a8cc4e2f1df4275c498f4a4539e54cc8fd268009454029e9a01001300c60c803306401043201221825807d06403cbca01106d00169e802b064032432000c19008a0c804b065c7e2201c9ba9ac92f379f33e02da703c1d0937b33616d24f26d513b77d7ef0e47a3b12e825bab696cf6527d34ffa3a19fee6506d921ce6e176fb426e3160c159accd5a6e968004a702603020db79b01606b0a06130b32188d70936e900) is the only font that works for me

**Comment by lpww** [comment]
Update:

I managed to get custom fonts working by using local imports and this workaround https://github.com/diegomura/react-pdf/issues/588#issuecomment-491538579

Example 

```
Font.register({
  family: 'NotoSansJP-Regular',
  format: 'truetype',
  src: `//${window.location.host}/fonts/NotoSansJP-Regular.ttf`
})
```

The `src` is a path to a font I had downloaded from google font, imported/exported from birdfont (without making any changes), and added to my project. For some reason it fixes issues with custom fonts

**Comment by Miluxas** [comment]
Hi everyone
I have some problems with the custom font.
cause I can't use Persian font even.
None of this solution handles my problem.
What should I do?
