### ISSUE TITLE
Including graph from rechart

### ISSUE THREAD

**Issue by skjo0c** [diegomura/react-pdf#669]
**Is your feature request related to a problem? Please describe.**
I am trying to include the graph that are generated by [recharts](http://recharts.org)

**Comment by diegomura** [comment]
Unfortunately not until I finish SVG support. It's been really hard to find some time to hack into that lately

**Comment by qenibas** [comment]
> Unfortunately not until I finish SVG support. It's been really hard to find some time to hack into that lately

When will this get done? I'm having same issue.

**Comment by diegomura** [comment]
SVG is in progress on 2.0.

**Comment by mdodge-ecgrow** [comment]
I'm trying to display a barcode using react-barcode and getting 'Error: Invalid element of type svg passed to PDF renderer'.  Is this close to done?

**Comment by brianzinn** [comment]
I ran into this issue as well and ended up using puppeteer.  It's not an advertisement for my repo - just trying to help people who can't wait for 2.0 (it's not an NPM).  For people who have access to server-side; I created a working repo for Node that generates PDF using recharts SVG and also the CRA logo:
https://github.com/brianzinn/crapdf

**Comment by diegomura** [comment]
Thanks @brianzinn ! Definitely helpful. 2.0 is on NPM though! As a beta version for the moment

**Comment by steventilator** [comment]
How can I render SVGs with the current beta on NPM (2.0.0-beta.6)? This package doesn't seem to export an Svg component. Is there some kind of documentation for this feature or an example source code?

**Comment by gisabernardess** [comment]
Is there any estimate for this version to be ready? I tried to render the recharts graph using the beta version, but I couldn't. :disappointed:

**Comment by meherranjan** [comment]
Any timeline for this feature? I am trying to use D3 to render charts. The only possible way right now is to rasterise charts to image and then render in the PDF. I would like to see lossless support from react-pdf. Cheers.

**Comment by diegomura** [comment]
2.0 SVG solution is already working and deployed as beta. Plan to do the official release later this week. However, the bindings between chart js and react-pdf should be done separately. I know there are people that already achieved it

**Comment by eugeneZolotarenko** [comment]
Maybe somebody already created bindings between recharts and react-pdf SVGes? I'm confused about how it could be achieved 🧐

**Comment by clement-faure** [comment]
How are we supposed to "replace" native svg elements (used by Rechart) to React PDF custom svg elements ? 
Is it possible to iterate over all react children and update on the fly Component used ?

**Comment by kidroca** [comment]
> How are we supposed to "replace" native svg elements (used by Rechart) to React PDF custom svg elements ?
> Is it possible to iterate over all react children and update on the fly Component used ?

That will be one way to do it - if you have the chart already rendered somewhere

Another way is to user `react-dom` and render the rechart component to string - you have to make sure you you chart does not have any animations and is not using the responsive container. 
Then you have 2 options:
- use the svg string to render an image inside a canvas and then use the uri in a `<Image source={uri} />`
- use the svg string to make react-pdf/renderer Svg components - there are still some issues with positioning, for example Y axis `-90 deg` angled labels don't work for me

Here's a gist with both approaches: https://gist.github.com/kidroca/19e5fe2de8e24aa92a41e94f2d41eda4

**Comment by conor-lacey** [comment]
@kidroca Thanks for that gist, works well for me.

One thing to note about recharts: I needed `isAnimationActive={false}` on components like `Area` and `Scatter`, otherwise they wouldn't appear as part of the PNG image in the PDF.

**Comment by studiojms** [comment]
> > How are we supposed to "replace" native svg elements (used by Rechart) to React PDF custom svg elements ?
> > Is it possible to iterate over all react children and update on the fly Component used ?
> 
> That will be one way to do it - if you have the chart already rendered somewhere
> 
> Another way is to user `react-dom` and render the rechart component to string - you have to make sure you you chart does not have any animations and is not using the responsive container. Then you have 2 options:
> 
> * use the svg string to render an image inside a canvas and then use the uri in a `<Image source={uri} />`
> * use the svg string to make react-pdf/renderer Svg components - there are still some issues with positioning, for example Y axis `-90 deg` angled labels don't work for me
> 
> Here's a gist with both approaches: https://gist.github.com/kidroca/19e5fe2de8e24aa92a41e94f2d41eda4

@kidroca I was not able to make it work here... could you please share the dependencies you used?

I keep getting this error: ```
Cannot find module '/node_modules/react-dom/server' imported from /src/components/imageFromSvg.js
```

**Comment by kidroca** [comment]
You probably don't have that package installed - `react-dom`
Check the `import` statements and install any packages that you might be missing, like `react-html-parser`

I've updated the gist with my latest recharts to react-pdf/svg code: https://gist.github.com/kidroca/19e5fe2de8e24aa92a41e94f2d41eda4
- Stripped a lot of noise and unnecessary code out
- Removed the code that converts the chart to `<Image />` as the svg version is much better
- Removed dynamic imports

**Comment by studiojms** [comment]
Thanks a lot, @kidroca, I could create a sample project to test it based on your gist.

If anyone needs to check it, here's the link: https://github.com/studiojms/nodejs-react-pdf-example

**Comment by tarabishy2020** [comment]
@kidroca thank you very much for this.
One note though, if the svg already defines a `viewBox` or `preserveAspectRatio` attributes, `react-html-parser` will convert them to lowercaps. So it might be better to check if `newkey` is `viewbox` or `preserveaspectratio` and replace them with the correct version.

**Comment by EvHaus** [comment]
I just created https://github.com/EvHaus/react-pdf-charts which allows for recharts to be rendered into react-pdf. It had only very basic support at the moment, but I'm hoping with some help from the community -- we can get to full support.

**Comment by devevignesh** [comment]
Hey @diegomura, sorry for reopening this issue. Could you please let me know if this library supports rendering graphs from Recharts in PDF? I know there are a few methods mentioned above (hacks) to render the graph in PDF, but I don't see any official documentation on this.
