### ISSUE TITLE
<Text> can't read korean language

### ISSUE THREAD

**Issue by jihu02** [diegomura/react-pdf#674]
I want to put korean language at react-pdf, but It can't read.
I write like this, but
![image](https://user-images.githubusercontent.com/38899480/62184072-76701000-b397-11e9-9dbf-4c46b22a8e13.png)
If I opened this pdf, they look like this.
![image](https://user-images.githubusercontent.com/38899480/62184095-8daefd80-b397-11e9-91d6-af9dfea38fb3.png)
Please help me about encoding problem.

**Comment by diegomura** [comment]
Hey. You will need to load a custom font that supports Korean chars.

**Comment by seonghyeonkimm** [comment]
I loaded a custom font that supports Korean chars. But I think it still doesn't work.
Could you help me to figure out the reason why it is not working? @diegomura 

`code`
<img width="1235" alt="스크린샷 2020-03-11 오전 12 14 29" src="https://user-images.githubusercontent.com/13966404/76327434-58a35a00-632d-11ea-9221-d95ff18d4f68.png">

`result`
<img width="640" alt="스크린샷 2020-03-11 오전 12 14 08" src="https://user-images.githubusercontent.com/13966404/76327425-550fd300-632d-11ea-9a33-4232b7a5a411.png">

**Comment by NaumanRayn** [comment]
@seonghyeonkimm  Did you find your solution?

**Comment by mozart25** [comment]
any solution?

**Comment by mozart25** [comment]
finally i got solution. just download korean ttf file, and Import font and then, register it. then wokring!!

**Comment by skh417** [comment]
Only ttf file. And Remember add font family in StyleSheet.create() after register fonts.
