### ISSUE TITLE
Error on installation Ubuntu 16.04

### ISSUE THREAD

**Issue by tim1016** [diegomura/react-pdf#678]
**Describe the bug**
Installation fails due to rollup-plugin-terser : The error message is following: 
(plugin terser) TypeError: Cannot read property '_walk' of null

**To Reproduce**
run: npm install
Node -v =  12.7.0

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_
I have not used it before. 

**Expected behavior**
Successful install. Temporary solution was to disable terser from rollup.config.js

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - OS: Linux 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Browser : Not applicable
 - React-pdf version [e.g. v1.1.0]

**Comment by diegomura** [comment]
Related to this: https://github.com/terser/terser/issues/120 . I didn't read through all but seems like a `rollup-plugin-terser` issue and not this lib. thanks!
