### ISSUE TITLE
SyntaxError: Unexpected token import 

### ISSUE THREAD

**Issue by chipatama** [diegomura/react-pdf#68]
I tested examples and it works great, but when I tried to load it into my project I got 'SyntaxError: Unexpected token import', I believe that's because the lib is not compiled into es5? 

I'm using react-create-app, and everything is written in es6 and works fine, just not sure what's the proper way to handle this? Thanks!

**Comment by jbovenschen** [comment]
Thank you for playing around with it. 

Indeed the published version is without the transpiled sources, we only published it already to claim the @react-pdf org on npm. If @diegomura thinks it is ok, I will publish a new version.

**Comment by chipatama** [comment]
@jbovenschen Sounds good! Thanks!

**Comment by diegomura** [comment]
@jbovenschen Sure!

**Comment by jbovenschen** [comment]
@chipatama I just pushed version 0.1.5 to version can you try it again?
