### ISSUE TITLE
 Cannot resolve dependency '@react-pdf/unicode-properties' 

### ISSUE THREAD

**Issue by jeffreycxu** [diegomura/react-pdf#682]
Thank you all for making this! I'm creating a full stack application and I would absolutely love to use this. However, after I download your module following the steps in the README and importing it in my react code, I run into this dependency error. 

**To Reproduce**
1. yarn add @react-pdf/renderer
2. Insert import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer'; to the head of your file

**Screenshots**
My package.json in my frontend folder! 
<img width="658" alt="Screen Shot 2019-08-08 at 2 55 36 PM" src="https://user-images.githubusercontent.com/19851740/62740535-fd069c00-b9ec-11e9-93ed-7a3aedce0dde.png">

How my project is set up: 

<img width="223" alt="Screen Shot 2019-08-08 at 2 55 01 PM" src="https://user-images.githubusercontent.com/19851740/62740539-0132b980-b9ed-11e9-8f0d-5e60ced592ea.png">

 - OS: [Mac 10.14.4]
 - Browser [chrome]
 - React-pdf version [e.g. v1.6.3]

Please let me know if you need other info! Thanks so much!

**Comment by IsaacGHoward** [comment]
How did you fix this?

**Comment by lcastrooliveira** [comment]
Yeah I'm having the same issue, I saw that a fix was merged to the repo but it looks like this fix is not in the npm package yet, feeling confused
