### ISSUE TITLE
Page wrap needs bottom margin (for printable documents)

### ISSUE THREAD

**Issue by ReganRyanNZ** [diegomura/react-pdf#684]
If a \<Page>'s content is too long, it wraps to the next page in the pdf. The problem is that the content goes all the way to the edge of the pdf page. This doesn't work well with printers.

**Describe the solution you'd like**
Some way to provide margins to each pdf page, even when \<Page> wraps over multiple pages.

**Describe alternatives you've considered**
I tried adding margins to \<Page>, but of course if it wraps then it doesn't end at the bottom of the pdf page.

**Comment by ReganRyanNZ** [comment]
Note I tried again with padding, and that *does* work. It's just margin that breaks the bounds of the pdf page. Not sure if you want to work on that or not.

**Comment by diegomura** [comment]
Yes. Pages actually cannot have margins, it does not make much sense since conceptually there's nothing outside a Page. Padding is what you should use

**Comment by mimsou** [comment]
Padding is cool ! but when you want to have an extension of your background to the second page you end up with somthing not verry pretty  , you have a blank space on top of the page, any solution ?

**Comment by chathu-novade** [comment]
@diegomura But PDF kit support page margins right? http://pdfkit.org/docs/getting_started.html#adding_pages
