### ISSUE TITLE
Hangs when Text component is longer than 2 pages

### ISSUE THREAD

**Issue by HenrySwanson86** [diegomura/react-pdf#685]
Hello,

It appears that issue [#246](https://github.com/diegomura/react-pdf/issues/246) is still an issue if the text runs over two pages.

You can see in [this REPL ](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231cccfbd474d940289818081c8847c78027184ab089e3002c8f183000058f000d17960310880c1808233cbb96024c0023b2063b9c4f283b9287b3245a58758da302285c5412062300039c6656001b922b402ddf938c085221489f1c778c0888041458d040179f8b0c0f341208988e644f217b9bb966906d5f02044c0e7027438019afa80c108c1b90dc7e4a52883bac8c002a981f882adfa8c788f18230008793569e4fc2d5da71801e303644091081021a48600019f9c4b10783e2f410999224a04061c6933b8b592fb0998ce910507c9361370ac32862560600056b88a4c1dad94444036430017c381a40c4920d2808023e6c0608771f9f9af462cb8622f64c14090263747193280a52652f726126a308020fa793a9810a1f5b0884e662808dc9be3d781802e234c151b15d68d5ae48f26122f0911cdad6d6f4215e300b5ab71173ab4171faa0c21cdfb0415ce9a371aeb351046323e9d6eebc6602c53609ea413f040b021702ab99be872da05deb7920a6e33c44175198487d74606ebd77b76f86a31c3f45a31a16494d2c78dd92dd2181e06f1cee4e56c8192b29e2ea5a04b1988dcddb55d3c3b2a8edd9720900ccbd7a9e234e2770697c399226bc964e975160201597c6edc9139e87397d4ac604f4d76ec7d2690a6f1550f8003177090545d0f98b0a98c0325a01c9757e9066187b6acf55941843d16795597ad5529940468c4140906c5dd60090638db1b946785dc614d91b138161b90413d298724a240001b9ee5541c35c947715c1653c3b97f240e892cfc784e60f9103a852071bc2133c18464ca13019de63742033c6cc49922c1462b3794286038910331363f0f06bc160f4e23090ca184f50c900b9b216084f999c3a478052de330320ddbc681a2258e233180023e4160080d89c6bc9a771757d5b90c0a01557170d94ce935190835f27974a5cec2f2a6d6f5fcfc7f25b7521a245eb680405d4903fd2d3f09a1b8fc7223d1c8f53255835260664b321ae7699e20f15521204a50004bb74d236c8320476273df0689c4534cfec0a4d9615d56c114530a249411b76c8408dc3d4113c8c0940c43b3e80607aab7e5554f52648ab3665757a090098e208ac1cd218b05e337478362883bb0a07cc60c1b2318906498b22b99559b25ac1af0050fd8fc1e03373a1c3b90e59b41ac0fe768944c47f282a64f59317a76facdd1e5b221284af5751f5cca3d165e87d4d93530108d341d0bb043b4c221258429d4bb859be025bf0a05a57306a556c6a0d22ee02a785a8d228a85c3bc3275f8904aa3092630911370eb5a9b24e3bc5d4db2495552555489532421a5553c111e9e52b8edc813596b23baf311b26b7160813a5bc30569315d55b05cb7143943dc8e1dbcd24c62e073c6f1560982bd1865ba40db010e04926311750b430338824e61c7911d242e27e5af6e25e8f2159802e5fc7198170f2431612e52c0006515921000b9a7b794bb337c023489b4ed4ce262d678169fe4985f0238230b262aa2fcc2973108258910a793d19e73d6c96029aee17c0400ae44cb690464cb6c0ba2c6a6b4d3f9927ee802302643a80cd2903548cb894617b0b89d0ab2bc27458016254508b882d15a7b4ff16084032a4813d15f63a4024dbab56cb2804438502208872889eaf69800604069ccdd1ae4449c53509c1e0330048b02b8b83679c8abc1b873148e60435b937e1f4ad02891b1ded912b2da54e6f91d9242409741c3ee274abc303741be4f5f91021468c5c91d26bc6192c5c70e8b29e19282f0e127e3302e4f45104cd46cdfc139600b86f16a2f3208910ee1d27368c252ac8d7871ce0b30148425350366681b8ca6e8e98ba82c46d3f07c134b780b2bb175000610e61e9711dc44e7d4b9200f51e0172bc0a50b38e09341f23f9999ac12a6e9e4b1f2ac4214319870c2209912c3816f0e700d6c88827254436cac15522a041b94e089cda8af1858de3baa589eaa2092c700db4c4980d92db593721222b1c400082045a02624c032051248b305507847865a30a832624794e40707c00072255d19f84a87709782c1cc8928913f5c4c12398002123e411089784c1ab29eb94fa6dd0d39df0dc77416bf00bcdd96aaec969683729ae0da412371883e80807149c976c9cab29f5e4ee16710f160b4ce0b29534ff85bb26382cc5dc1341aea7c1a8626f6045646521ea8a86424d69a39987a2c182982161f62ca9e93c0e8926f09992785b4ead7393c0e61847233025c808bf8fa0bc2ebb710a9e081c5abd8bb84c2c3bf6435d4c1a6ca2f46d9bf2a10f0c75009302d65b08544e2b5298ea30e354cd538b715c8ab1c093cb81beb9a8600ae5056c9266e6f145708e7e816ca376b5ec409be7d101ce0b31b2ac986b96219a37cfa87d8203a4535201192a99316e8f87450eb5d50429c0815a1c418d4b01a6e8c981bd6b7046127dadd030129b98c61e94f078c186710ec49d7cbd0452dcb490b20820e02f9f00003f2c0e615520c90cb6a82374611e42ce7765ba792ec90d2cdd60c05e0220ca62178e4f4002498f5f0981dc271005da53a1d6000e25957c3a935cc3a781982c028a311fc7049115d4554da7dd7e65669e649e438c40673d0ea8f71eabcef260a04b330bb4d66387d1411cebc52c1e93839a55ba98a6650b38378c2f70911b20020e64477c1bc48804a9477e7f978708f11e387551c939172b38b162c32d584ccb806867cd3727161eea5af2fb52d05d60dc9a72cc07393a65292a8723b670e31dc00932d17bf4d041598741608e77a9093914059c091d59607a6e94601cc370b20380fd070668fe142ec4911aeb48ad1aa8b844b50b8a56d5da310c012371c2933e0e056e664c6975024508b94c41084b6df9fd07812aae31f9c5f54c5c878aa25e63650acdec6472c0b49272cc65688c3789a80c944451a1c3c48369142b4484b75529419bc8a511a686a26b48cb5b220d3824b35587c000329c9311b62153e977ab0302008b025aa752394ba78cbc4f412dd21ce24236157298a94b9a548eed191237e19dde08f780bdaded0bb80b59a89a87b1025f0cfe8a422118061eae1ca7f41d5c4c7646ba184054c569e69fe2821c7891be6d9ac13ef925ea0a23f1aa9c4301595f060dfc4c47e33f0ed4b0aea196dcd03662d0444257006bc18923ca2a4283fcc020755620341c32c3aa9975055d28db9673a03bd86d0712bfddd651d91d5294e15e3e59b05d2780344e82d4472a1d437c2428a164600e33411329ad87b605609a6c50b596b75f815bcd31e2c0dd9c43a00e1fcba00c0e51750000959e61cd38032492c2521ebec65246f110adefc08e27d4f0282639fe2c14d1947befacc95149f619da8891e7a0d899d9aa8277161a1588e1fb7e3d71600ab3df30459992e6d26438677ee22f63b4fa601808f53e012838bcf5f1dcbda00ab819040bbe3fc96a616f647f1915e84a439897e1b500d19a8cc19c4ad85cfe41e663f658a0d6737cde04daafe40cb50100bbcb22ef03000009a95c9d0e0ab64e9aac2580f76ee01e42b83263f06b217a2f8a9412e6f80da3c64a8ed6028998722cb898aa4c2d81b0432bb65e046ef3e360d76b26c387b84082a838cc4c208b94a300005208039c55877445012c43cca0b88b6893045078e4f222ac1c1e43320004a58c3f05c845ebd217a6b8a7a8902f4ea1b22be0850ea649cea212ceea4f4614db0c70a842618d6b307e0004bb21846484b43bc408fea580bd0cf0426a8839cf6ca7abf84d0ecc0e0dca4e8f860b45ea5c8f2c7148a039009e618b4c3980c0c3e8eee012b0912f68606e0e6b62c82987fc424e88b9017a5fe0b00541802001f081092133ae216d0d8c4ee7e1cde6e2e82d9e661de150012cbd0b3e7de350b1cf4c6204728ec2207727548a637042aedabdade0d2af524f4dc4bfa614f588d06683c015c1701b8a0e241776c74cc095804453e378d76521af064273248892664828e600e92ee0c62c5a9ec4cc22632aaf2438984696438de01912dc6b8f54661d71d981ccbc6bbe306f3215c3a1b34874238ab11a67a616e21e2cc9088eabf16384f41c64108b828ec840901b2c263e6f010b183e4b85148ac5c25dcd090749cadf14e47d8660909ee009e3e86e03f06d82e8b34e68a7e5d193ced8c7c4880e0b502d4154e9a0d6d3c3900d09f63c2bb4646ff4d0c436a3817ae3067a7b156e7e0522181666c29dfe510d44790d90421bf19e0409a2653261ed34d789e85286d81b022e9a88ecce6a3056e130658fb6c01b01f4870c1dae002881803be0e0156a06b386209d042e0c4d0e79c2694081962842c04682e819445a9218897b4be0ffc7f4b3ee840b4e881e0892a30576f622c072e29ed292e06e097ea5c710909272329d78bd0450112bb4770398d14d22e4e6d10008c0001cba8004ca4c64c80d613f8fac821b2835cf09414caa8744ea8747d8409d52acc1100d4290836abeb7e8b081ae11504d007e97e0349730b198b011aad4489eee4f45014366a17f4f08fac682710eb42a43bcbe04a2980bb90d82a8a7122edd8a06899c98fa8504c30bfe7f24724e68e8af07c28002804000fd5642e25e04daf01d39474fc881c0304882687506ceab63248d1710de16e05822e0330c7432e9b0d76fd0b34bb1530e582e1b6279205eec491422009cdb8b512591f25c2e54d64a90710ade6e0d18edce827781b80e67f69e0ea19a84290b4d76de1f0c0bc6459413f080c074d993c0000fc7c2ff2551e1c309dbcba44bc0c0ee2ba8aa57f0dd141cb2c0e19b9ea245a8b0c106106f8660528aac4b831cd86698d686f0002d4414ed565301217d03621c1b320387f48646a50c45342d06c446ae887f6af0079324528d2ad047b81cc5e51e0528daed4c63c470ea5191dda2e0584e11505220b226f8fe64942e0991324450e001b9fd806c814ef4ca4f31ff2ec1f622d080cbc8abe3e82894e8664a34bb60d48125bc5f1030558c318923a14b446acccfa8dc1a52a894487441d8044c020f98f8d15150192408b94774b6246ccc8dc5979dbcbbc945d89f325e01cc99e0f9a64ba8810965c70931fb589258cefce682e0646288b212618067d8875fbc539ba84a14242a10f9759890bfaf6c7d91789e0c31704fb0dd92aafa858cc989d2fe16ac4f4fe0e0031c2206eeba8301d76e620f69b0c6ebb2156e79ecacb15ce5aec1c00543620534030cefcf581ec09cc6489674d35e5fc8b07423684083a4c3e385080785892df5a88ea57308a8c3ab58685360d0c7c08c9f0e7f6ff0a810c28bc390c109cea54fc1e888ad474608d717f0b940042f81e0774b994f48ec289c9970adb1b6e705a590a4ec11f000085000f22102846282880c5636f08915ba67948e8e4eaa8fa24d858eeb8cbc565a21124dbc6d87a96f0e0086c00e074f029e97fc7e0c450eac24000847f5080974c300f91e6dd141422062cd351227b4db4300ff5178aa119ca4cd34b5a9245ba34273872eadcc3a94a24d13ce3aa741a6720640ba8af66487449bac5db2a5c9ee2e89985438045d84bf89f23bc4e1e947bc12a205ced210a25aad4b8340fc100d1802241806c42528543f80a41d05eaa2219d010fb68b087eb51cc09a9154054d62d50474054534d0cd715807702906fccc29fd27a270dd94168b013824d5525814a25b0c62690d02382f12e62a129b93e57623c01f05c0220b9d3c0ec46d887db75cd17e6f5034879c0540f98d2379b684d48a4f90c61600772756d98c80f4e8a69e0643caa0dc3b19b87641801f0dd2cbe2c9af9e94a884b4abe769d68844cce9cec3c9218a2adc1a93e2c7eb9893c9ea1c9e9181890407d2c89100b4d0aabeb8aedc8a42f18dc196e953c04d43c33d26099dd982a16c72b654b6d65ee47f07b25d80ecf3c9ee044a14b708110bc8a41e0c527723497e0fb4756c81510d86cd44801720c46d81e47f4d262daf69a6d1badf2fdd4f448d52c40eecd132dd5fac261839790e8dba2513a004b8d1e3d8ebe0bd94680ceac4f0470ee4bd4313f0205c8caee0d78d5ebdaa69e9a2e09e9abc43d795e4e6009a9101f58280f028e8694b41c96bb22fc9539685803485f81f08d50eab94b148744e626d4e4f7c3916259c4e1a4f99c4eb1e1a49a953c74cc65c04e18a4af6a08e88b22910a23894b2292e3e0b097489580168cc24155266a9b420e1b8b10de58a6d0c471661ed4dd90297c30f98b8936b05448ec2fa1e8adc2f561949213f0dd4975a8db35c70b94d781566821ba350b23e39d93392a281658484536f5f04670fcc300d74a92f0ba36ae2410a885154559739f36100fa671641db6fb50ec621f98733ab59a0c31ed44186f1eade788f156a5e992cb50fdc414b2b278208a63f31a306692b3ce5f42ba8e522000205ad8649cd702498a41ee8cc0d0ce9a7d8dbaf680fa6f888886a91291047e250be6324620a629c19dd1c5d338e6996bb5e41d558ece10d789092bc12b5f39c409410e944de853eaeb385d3aeb560a12b9b1be2055a080fea5d7d82f0b8102490248affc179cc81f0b4d130d5a998dcce0d3f097e36c77860d71b5824de5aa0c17b0bd644873c6ee360540000f4ba0fa01a0ddbfdb06026062092086072052802028a4c08c6aa0ee877e9207801209b8d3bb3b8769e8031bc0020930aa0440d80a40780ba8000060002412053b18033b490d90f3b3db300e7b9bb408dbb660aa0c7bb08040f3b19828050c3003db83b940bdb2fb83bbdb7400c074eec0040aa4fddb84e8db2029062e854ee0cbb1c08752b04207c2000e44ed100000eedcd987ab6100ee0c005872105005000d010057c3db3dbe92ac07207c0598b50c00b20dc43db1003db130f872204a03dbad0cd9000cc3db501000fada0000d20006a0006c200ad9000ea200ad0f209f04a08278c0a270001a0009c3c0ff2ff2b201471709876407bbd076405f923ba60930b8067ca3b18067c448cd46c7290dec1802879408a02a07c2120e50295d0c63cda02000d07c2827000ac92d0175a824ae80a847c2327917fe79b08177c0b9e8384b5408617497940aa0ab6bc9620be7e50f4750017c3301807c20004c0002c92d160500ff239c32d5874f3586847c57e8db84464220187300d877870471c07971c0f6a0b54579a0257657157300cd99577577a00d74d76002d79f2ee0ed79a05f162e600b171478907c2d570000cab6c37940b68f20057d377e7137e8d5377c26d992d9b7b287777371d7ac05d75d4bd7fd73c74a0a67b97f970b7e379c08f7cb73372f7d77ac0b77337b57e50f578d7c6420f987f24cb0170420eb79c0257ef7e87587da0625100000b44a14a2bf7300277969fc0977e50c0f527d7e7aa22077739740f1e05b7e978b5e8d597337077477437ab6448845ee080f940937480e57cf70f74cfb283b7f173009575cf9a0b0f4b72b75c86b792da00e165872d2180a8fc77ab697bd7b8c602f8a6504b50e00587db81e42e098068f82f377c2fd37b3792d8a0bb78c0617b2f9c06201705007c2aef9400447c0e475eff37fa070fcd77d7ad7d9056fbe86af7d71af5afdcf667507fdd0a17bdcd65c0340b84f0796cd907805405646800f9ffb09f4000000) where I used one component to display all of the sample text.
 
You could also check [this simple test](https://react-pdf.org/repl?code=198570760c602e0960f66001009c0866039814c014c65c02d80348947009403780508a2102033948803630b880bc880da0174ea200ee002c61b5cf88a2003c652a25af5e871600e8003882662f014201a88c561017d8722c5043224eaa0d4b351982e0104b569e887051e003e3f61390011380810422c302840e17a390005546c04d555390035182c11440cccc400483900152c000f78aa344c5c0006520046003646c68a0d42542d1c2aa0c40072282c2e618a7339007a4a9aa2ccd9dcfcc5f919d4f4d09988a898b8848a006e1a5380252c546864b080310d6b3000132c641c392f1f19c0e39a20000) as well.

 - Browser [Chrome]
 - React-pdf version [v1.6.3]

**Comment by sonrai-samroutledge** [comment]
Thanks for posting this; I was also seeing this issue but would not have figured it out on my own! In my case I was able to remove a `wrap={false}` prop from my top level View, and it no longer hangs the browser. But this is not perfect because I still want the content to break to new pages.

This is in
- Browser (Chrome 74.0.3729.169)
- React-pdf version 1.6.3

**Comment by diegomura** [comment]
Thanks! I'm aware of this. There's already a ticket for this #600

**Comment by HenrySwanson86** [comment]
Hi @diegomura, I just wanted to make you aware that this issue is slightly different issue than #600. If you look at my REPL I am not using wrap={false} and the text is still hanging after it exceeds 2 pages. It may be a different issue altogether.

**Comment by CyrProject** [comment]
@HenrySwanson86, I can confirm that this issue does occur even without wrap set to false. Might be a candidate to be reopened? Unless @diegomura can confirm that somehow if the text is longer than 2 or more pages that it is related to the wrap issue...

**Comment by diegomura** [comment]
I'll reopen it for the moment. Thanks for the clarification!

**Comment by lukdavid** [comment]
Hi all, I am also confronted with this issue. Anyone found a way around it ?
