### ISSUE TITLE
TypeError in linearGradient and radialGradient when drawing in paint function inside Canvas element

### ISSUE THREAD

**Issue by frankieyep-icx** [diegomura/react-pdf#691]
When I drawing in a Canvas in paint function once I use `let grad = d.radialGradient(300, 50, 0, 300, 50, 50)`, the web page will pop out this error: Unhandled Rejection (TypeError): Cannot read property 'apply' of undefined
![image](https://user-images.githubusercontent.com/42730632/62926889-06767680-bde8-11e9-9ad3-13126cefaeca.png)

**Comment by Morpheuseam** [comment]
i have the same problem

**Comment by Unionindesign** [comment]
Any chance we can see a code sample? I'm struggling to implement the canvas API and can't find any examples of what the working syntax should like, or reconciling the react-pdf docs to pdfkit? scratchin my head over here!

**Comment by Smriti29** [comment]
<Canvas style={{width:'500px', height:'500px'}} paint = {painter => painter.fill('#FF3300')}>
You can add this after <Document> and <Page>
It works!

**Comment by diegomura** [comment]
Fixed [here](https://github.com/diegomura/react-pdf/commit/fbd97fbea9144c41cce9278f6d13411b34c5137e)
