### ISSUE TITLE
How to include another pdf in my pdf rendering

### ISSUE THREAD

**Issue by tehpsalmist** [diegomura/react-pdf#693]
If I have one or more pdf documents already in pdf format, how can I include them in the rendering of a new pdf? I didn't see anything like that in the docs, and was wondering if that is possible.

To clarify, I would be building out a new pdf using various react-pdf components, but also including some pages that already exist in separate, already created (by various other means) pdfs.

Thanks!

**Comment by diegomura** [comment]
Not possible sorry. I don’t see this as something this lib will be so porting soon! Since there are a lot of complexities involved with it

**Comment by tehpsalmist** [comment]
Bummer.
