### ISSUE TITLE
Ellipsis is not '...' but '&' where using default font Helvetica

### ISSUE THREAD

**Issue by TakanoriMizuta** [diegomura/react-pdf#698]
**Describe the bug**
As the latest comment of Issue #461 mentioned, Text component with textOverflow truncates overflowed text and add ellipsis, however ellipsis is not '...' but '&' when font family is `Helvetica`, react-pdf's default font.
If I use another font which has U+2026, there is no problem (ellipsis is '...') .

**To Reproduce**
See REPL sample.

[REPL sample](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a00d490600ee31a78a95144639507bcb101949a31e009cd46eaba0d1b363271cbd6c40024307894309c009441f5d4392874f50d8d7dbc2d64ac6c30018440456335e20054305161934dcdfd32b23044458343c3d4010581401158a801e98b4adde2ba3df5fbdd12bdcc532bd203b373f20aa97acb532665a7ab6bea42c29dd400e499e5c3ba9647ba86ce87c67c2ad632c472f2468a4b96276ed3efb3361a77f67998275799d06893739cc11c04a79ca7e75988a2314b98d61a92a83ce6cf6a12dae263857c6a757500118004c0066000b00158006c0076205f4e2d45041991309587dd1b3278b25ea55c6ad3e334253cc954ba6327ac096443d972abaa2a604cc7f3b1af21773e1df22711b4e1210c00d2e6361a6000191035bc07c181ec015807731ed8ea65b0e56ce1942bdec7977b34dd5e009c15d3a03198ac7601000dc6432281206f190e060b654ad80016180c14164c027085307809071142a00170c14b9a0003a849448301f10a205ad57c9d4800d0b3eb4a46f360042e8280811855da7777b0da6df1022027120005ee02b0883b53ca2a87b942fbd9188e171566b9c46c416b221e108ab0022001998850379de701f251a1210bc028121c0b7d00884c180cf8b298294cd088481f0602de621de500819a3e84812850266b7b92b48000cb593e2fa50879f04db0e5028ee38c0378001cb86213036e1c17cbf38488b1e2c99e1795eb79be784b2dc47e5f8fe7f8514e344b4650f20f0c0000d67c0891d1288f02eb7800c4c48f0d4b52944009cb47d1bb8cc2c7566c520e7a5ed7851dc589301f19f860dfafe30709a24be7a4c0aabae46521285a1b7992384f1758cecd9569b9d12f8123f36ce12b19a181500415063937b002c2604e15977aaeb632e181565a7e1300014a451ca5de65795ba785a2a6c3167071425d07fea978419565395e505665ac2294e0a9587f50355971400f2001bb840fb44b7a6c482d610099566382805a4d85855b122e4f6aa2c6f18442137e5c0d00018ac8859803b1e054220a83a058174c40ed400000)

**Expected behavior**
Ellipsis should be '...' not '&'.

**Screenshots**
See above REPL sample.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - React-pdf version 1.6.4

Thank you for your attention!

**Comment by bengtan** [comment]
I'm also seeing this issue on @react-pdf/renderer 1.6.10.

**Comment by hkmushtaq** [comment]
This is because the helvetica font included with React PDF does not contain the ellipsis character.
