### ISSUE TITLE
Add fonts embedding support

### ISSUE THREAD

**Issue by diegomura** [diegomura/react-pdf#7]
For ref: https://github.com/devongovett/pdfkit

**Comment by jbovenschen** [comment]
Currently working on this, and getting text to work again.

My ideas about this are;
```js
<Document>
  <Font familty="Some" src="some-source" weight="bold" />
</Document>
```

Or doing it this way: 
```js
<Document 
  author="jbovenschen" 
  fonts=[{ family: 'Some', sources: [{ src: 'some-source', weight: 'bold' }] }]
/>
```

What do you like the most?

**Comment by diegomura** [comment]
I prefer the second approach. What do you think?
Manly because is a styling thing. I'll keep the Component approach for things that will actually be rendered as meaningful piece of document

**Comment by jbovenschen** [comment]
Yeah, I also prefer the second approach that one would make it easier to build a component library for this renderer. Also it's mainly meta data.

Will work on the second one!

**Comment by diegomura** [comment]
Closing this because of #44
