### ISSUE TITLE
Issue in word wrapping when the text is enclosed in parentheses

### ISSUE THREAD

**Issue by jp06** [diegomura/react-pdf#701]
When there is not enough space for the first word in text like `(some word here)`, the parentheses does not go along with the word to the new line when cut and there even is a hyphen. Same when I tried with square brackets.

Sample text:

    Test  test test (some word here)
Behaviour when not enough space for `(some`:

    Test  test test (-
    some word here)
Expected:

    Test  test test
    (some word here)

I hope someone can provide a temporary fix. I tried wrapping it separately with `<Text wrap={false}>`  as last hurrah but still doesn't work.

**Comment by diegomura** [comment]
As a temp measure you can add soft hyphens chars in the valid hyphenation points. https://en.m.wikipedia.org/wiki/Soft_hyphen

**Comment by jp06** [comment]
A bit late, sorry, but I'm actually stumped how to actually do that. Can you please provide an example, thank you!

**Comment by diegomura** [comment]
Just put those chars in the valid breaking points of a word. You can do

```
const SOFT_HYPHEN = String.fromCharCode(173)

// Inside Text
`(so${SOFT_HYPHEN}me`
```

Something like that should work. Sorry, I’m from my mobile now so it’s a bit hard to test it or give a full example
