### ISSUE TITLE
How to insert Google Chart to a PDF??

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [diegomura/react-pdf#705]
We have to insert Chart to our PDF.
As far as I know, we can't find how to do this.

react-pdf has this function??

**Comment by ajinkyau** [comment]
@Yoshihide-Nishimoto I don't there is a function for this.
I think you can create an image (png / jpg) out of the generated SVG from Chart and display the same

**Comment by christiantigre** [comment]
Apparently there is an error rendering color images with this component.
Eny solution?
<Image
      style={styles.image_logo}
      src={logo}
    />

**Comment by Yoshihide-Nishimoto** [comment]
@ajinkyau thanks. tried it, and it worked.

Page.tsx
```
private data  = {};
private option = {};
private chartUrl = "";
private reference: Radar | null = null;

public render = () => (
    <div>
      <div className={this.temporary} style={{display: !this.state.ready ? "block" : "none",}}>
        <Radar
          data={this.data} options={this.oprtion} 
          ref={reference => {
             return (this.reference = reference);
           }}/>
     </div>
     {this.state.ready &&
      <PrintDocument
        chartUrl={this.chartUrl}
      />
  </div>
);

public componentDidMount = () => {
  this.chartUrl = this.reference!.chartInstance.toBase64Image();
}

```

**Comment by tonioss22** [comment]
Hi, i'm currently trying to do the same thing, sorry to revive such an old issue but i'm trying to get a react-google-charts component to render in my pdf and i can't seem to get it working, the provided solution by Yoshihide-Nishimoto does not seem to work for my case. Does anyone have any experience with this?
