### ISSUE TITLE
How to customise the download link?

### ISSUE THREAD

**Issue by bonbonio** [diegomura/react-pdf#709]
How can I customise the Download link so that the text is inside a button, I have tried wrapping the children of PDFDownloadLink and also changing the Label to contain a <Button>label</Button> component.

I am sure I am being silly, but can someone explain and I would be happy to add it to the Docs too if the feature is supported.

**Comment by Horzta** [comment]
Hi @bonbonio ,

Actually had your problem a while ago and I just noticed that in this code block:
```
    <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
      {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
    </PDFDownloadLink>
```

You can change the true and false displays in the ternary operations. This is what I did for your example:
```
{({ blob, url, loading, error }) => (loading ? <Icon fitted color="orange" name="spinner"/> : <Icon fitted color="orange" name="print"/>)}
```

**Comment by bonbonio** [comment]
@Horzta Thank you this works awesome

I do think it would be better if the library just output the entire DOM component so we could transform it how we like; like just <a href={link}>Download</a> by default, then its very obvious how to override it - especially those of us who would sooner swap the <a> for a <Link> etc.

**Comment by thisissami** [comment]
@bonbonio it's an open source project; feel free to submit a PR. :) i'm sure the maintainer would appreciate that.
