### ISSUE TITLE
Failing test using jest on import { PDFDownloadLink }

### ISSUE THREAD

**Issue by laetitiaZammit** [diegomura/react-pdf#710]
**Describe the bug**
I am using ``PDFDownloadLink`` to create a PDF and download it when I click on a button. Everything is working fine, except when I run my tests using jest. I haven't implemented any test on the PDF component itself, jest is blocked on the following import:
```
ReferenceError: _a is not defined
import { PDFDownloadLink } from '@react-pdf/renderer'
```

Thank you in advance for your time!

**Expected behavior**
Pass the tests while importing ``PDFDownloadLink``.

**Screenshots**
<img width="715" alt="Screenshot 2019-09-10 at 10 40 03" src="https://user-images.githubusercontent.com/23480592/64598076-62b4c200-d3b7-11e9-84d8-4f09ae90d0ad.png">

**Desktop:**
 - OS: MacOS
 - Browser: chrome
 - React-pdf version: 1.6.4

**Comment by aaron-origin** [comment]
I also have a similar issue with testing this using Jest/React-Testing-Library. Below is the Error I receive.

```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [Error: PDFDownloadLink is a web specific API. Or you're either using this component on Node, or your bundler is not loading react-pdf from the appropiate web build.]
```

**Comment by liron-navon** [comment]
@aaron-origin same issue, did you find a solution?

**Comment by Sustenance** [comment]
Has anyone had time to look into this? I tried looking into this a little, but I'm not particularly familiar with the bundler that's being used, [rollup](https://rollupjs.org/guide/en/). From my perspective it looks like we'd need the [browserProdConfig](https://github.com/diegomura/react-pdf/blob/master/rollup.config.js#L147) to be loaded for Jests tests instead of the [serverProdConfig](https://github.com/diegomura/react-pdf/blob/master/rollup.config.js#L128).

**Comment by Sustenance** [comment]
So this doesn't necessarily _fix_  this issue, but if your Jest tests are failing after adding the `PDFDownloadLink` to your component, you can mock it out to keep everything working.
If you strictly want you tests to keep working, just do something like this:
```javascript
jest.mock('@react-pdf/renderer', () => ({
  PDFDownloadLink: jest.fn(() => null),
}));
```

and if you care about testing the children that are being passed into the `PDFDownloadLink`, you can still render them with something like this:
```javascript
jest.mock('@react-pdf/renderer', () => ({
  PDFDownloadLink: function PDFDownloadLink({ children }) {
    return <>{children({})}</>;
  },
}));
```
Just mock everything until it passes 😅

**Comment by weiannnnn** [comment]
@Sustenance  

I'm getting the same error as @aaron-origin 

```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [Error: PDFDownloadLink is a web specific API. Or you're either using this component on Node, or your bundler is not loading react-pdf from the appropiate web build.]
```
and it's making my tests fail as it doesn't render the component that contains it 

using the jest.mock solution you suggested didn't work - any possible idea why?

**Comment by diegomura** [comment]
@weiannnnn interesting. As the error says, `PDFDownloadLink` is a web API (not node). However, when running tests I guess it runs on a node environment. I think mocking makes sense. Otherwise I'm not sure what I can do 😅

**Comment by rlarner-quizlet** [comment]
I ran into a similar issue. Here's the mock that worked for me:
```
jest.mock('@react-pdf/renderer', () => ({
  Document: () => <div>Document</div>,
  Image: () => <div>Image</div>,
  Page: () => <div>Page</div>,
  PDFViewer: jest.fn(() => null),
  StyleSheet: { create: () => {} },
  Text: () => <div>Text</div>,
  View: () => <div>View</div>,
}));
```
