### ISSUE TITLE
StyleSheet.flatten typings not in line with implementation

### ISSUE THREAD

**Issue by asgerhallas** [diegomura/react-pdf#713]
Typings for `StyleSheet.flatten` is:

`flatten: (...style: (Style[] | Style | undefined)[]) => Style;`

which implies that it will handle multiple arguments, but the implementation only handles the first argument.

It would be convenient to have `flatten` handle the arguments array, but if that's not desirable, then the typing should be fixed.

Would you like a PR for any of those solutions? :)

**Comment by diegomura** [comment]
Yes please!

**Comment by diegomura** [comment]
Should be fixed by now. Thanks!
