### ISSUE TITLE
React string eval doesn't seem to work

### ISSUE THREAD

**Issue by dberringer** [diegomura/react-pdf#717]
**Describe the bug**
I'm trying to run some react code from a string downloaded from a remote source but I keep getting the following error "TypeError: Constructor Text requires 'new'".  In a standard create-react-app environment this works fine.

```
import React from 'react';

const Test = () => {
  const react = React;
  return eval("react.createElement('p', null, 'Testing');")
}

function App() {  
  return (
    <div className="App">
      <Test />
    </div>
  );
}

export default App;
```

But in react-pdf the equivalent code throws an error.

```
import React from 'react';
import { PDFViewer, Document, Page, Text } from '@react-pdf/renderer';

const Test = () => {
  const react = React;
  return eval("react.createElement(Text, null, 'Testing');");
}

function App() {
  return (
    <PDFViewer>
      <Document>
        <Page>
          <Test />
        </Page>
      </Document>
    </PDFViewer>
  );
}

export default App;
```

**Why Do This?**
Just for background, I have some html rich text(i.e. `<p>This is an <strong>example</strong> string</p>`) I want to render in my react-pdf document.  Since this content is dynamic I can't just rebuild the styling in react-pdf.   I don't believe there is any out of the box way to display html rich text.  I am playing with the idea of implementing the html elements in react pdf and just having react-pdf render them.  

In a nut shell doing something like this should get me what I need if eval worked as expected.
```
import React from 'react';
import { PDFViewer, Document, Page, Text } from '@react-pdf/renderer';
import { P, Strong } from './primitives';  // I have replicated all the components I need to use

// Component displays react-pdf interpretation of HTML string
const Test = () => {
  const react = React;
  // This is an mock of what I would get back in my api response
  const htmlString = '<p>This is an <strong>example</strong> string</p>`
  const modifiedHtmlString = htmlString.replace(/(<[a-z]|<\/[a-z])+/g, txt => txt.toLocaleUpperCase());
  return eval(Babel.translate(modifiedHtmlString, { presets: ["react"] }).code));
}
```

This is what I have come up with so far for displaying dynamic html rich text content in react-pdf but I'm open to other approaches if a better one exists.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. running this code works fine `react.createElement(Text, null, 'Testing');`
2. running this code throws an error  `eval("react.createElement(Text, null, 'Testing');");`

**Expected behavior**
I expected that I would be able to eval react code with react-pdf in the same way I could with standard react-dom.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - React-pdf version [e.g. v1.6.4]

**Comment by asgerhallas** [comment]
I kind of think a safer (and working) route would be to parse the HTML string and run through the AST to create the elements. Something like: 

```
let x = JSXParser.parse(`<P>This is an <STRONG>example</STRONG> string</P>`);

const P = props => <Text style={{ color: "red" }}>{props.children}</Text>;
const Strong = props => <Text style={{ color: "blue" }}>{props.children}</Text>;

let state = [];

walk.recursive(x, state, {
  JSXElement(node, state, next) {
    let children = [];
    node.children &&
      node.children.forEach(element => {
        next(element, children);
      });

    let tag = node.openingElement.name.name;
    if (tag === "P") {
      state.push(React.createElement(P, {}, children));
    } else if (tag === "STRONG") {
      state.push(React.createElement(Strong, {}, children));
    } else {
      throw new Error("Unsupported tag.");
    }
  },
  JSXText(node, state, next) {
    state.push(node.value);
  }
});
```

Running sample, though not with ReactPDF yet: https://codesandbox.io/s/xenodochial-elion-v792m

(I couldn't get the PDFViewer iframe content to show in codesandbox.io, so the pdf is available via a download link)

**Comment by dberringer** [comment]
@asgerhallas That's really cool.  I have not messed with acorn before.  I don't see any reason why this won't work.  I'm still curious if @diegomura knows why eval doesn't work normally in react-pdf but I think this will work around my problem.  Thanks!!!

**Comment by diegomura** [comment]
@dberringer I had no idea that this didn't work. To be honest, I never did something like that. I'm keeping this issue open to check at this soon. I've been very busy but I see a near future in which I'll have time again to dedicate to the project. Thanks for addressing this @asgerhallas !

**Comment by dberringer** [comment]
No worries @diegomura.  @asgerhallas awesome workaround is working really well so far so I'm able to keep moving forward.  Thanks again!!!

**Comment by diegomura** [comment]
I looked at this and couldn't figure out why it does not work like that. It's an edge case though, and it would be better to follow an approach such as the one proposed by @asgerhallas . I'm closing this issue since it's not something we should encourage to do
