### ISSUE TITLE
Memory leak - Every time a PDF is generated, the memory used increases and never comes back down.

### ISSUE THREAD

**Issue by Osuriel** [diegomura/react-pdf#718]
First, Thank you for the awesome work on this library!

**Describe the bug**
We notice that rendering PDFs caused a memory leak in our prod environment. We dedicated some work to isulating the issue and it seems to be inside the react-pdf, because it only happens when we call it. There's a chance I could be wrong but I havent been able to find anything else that causes this besides us calling the react-pdf library.
While running react-pdf in a node server,
Every time a PDF is rendered, the memory used by the app increases and never comes back down to what it was before the rendering occurred.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. watch the memory used by your application that uses react-pdf.
2. Notice how the memory used by the app increases when a PDF is rendered. and it never comes back down.

You can notice the difference better once you render over 50 or 75 documents.

HERE is a quick and easy way to reproduce it.

clone this project:
`https://github.com/Osuriel/react-pdf-test`

the readme.me has all the steps to run it and easily monitor it.

**Expected behavior**
The memory should eventually go back to normal after a request is made and not increase continually.

**Screenshots**
before rendering pdfs:
![image](https://user-images.githubusercontent.com/13215891/64989308-3d362580-d89b-11e9-9f2c-7fad1c2e3fee.png)

after rendering 100 pdfs, and waiting for a while:
![image](https://user-images.githubusercontent.com/13215891/64989677-014f9000-d89c-11e9-8914-72b07c08875a.png)

**Desktop (please complete the following information):**
 - OS: MacOS, Linux
 -     "@react-pdf/renderer": "1.6.4"

**Comment by thisissami** [comment]
don't know if this has anything to do with it... but when running this on the front-end, every time that i generate a PDF, I get three errors as follows: `Error: stream.push() after EOF` (this is within the `BlobProvider` component).

**Comment by em-wu** [comment]
I also have a problem, which is probably related to a memory leak. When I'm rendering document to the file for the first time - everything is ok. Any second and next attempt (for example, after changing the list of maped children in <Page> component) is unsuccesful - there is an error. Looks like the memory is not erased after first rendering. 

> Child already has a parent, it must be removed first.

> The above error occurred in the <VIEW> component:
    in VIEW (created by ProjectMap)
    in VIEW (created by ProjectMap)
    in VIEW (created by ProjectMap)
    in PAGE (created by ProjectMap)
    in ProjectMap
    in DOCUMENT

> Uncaught (in promise) abort() at Error

**Comment by davidecarpini** [comment]
Same problem:
```

  Error: non-error thrown: "abort(5) at Error\n    at jsStackTrace (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:443:15)\n    at stackTrace (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:453:14)\n    at abort (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:9808:182)\n    at mD (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:9705:27)\n    at hk (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:4262:188)\n    at fk (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:4256:186)\n    at cD (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:9685:57)\n    at Bound.eval (eval at buildCallerFunction (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:1445:311), <anonymous>:1:51)\n    at Bound.<anonymous> (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-common.js:220:23)\n    at Bound.prototype.(anonymous function) [as setMeasureFunc] (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-common.js:133:22)\nIf this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information."
      at Object.onerror (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/koa/lib/context.js:113:40)
      at onerror (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/koa/lib/application.js:159:32)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  ---------------------------------------------
      at Application.callback (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/koa/lib/application.js:140:44)
      at Application.listen (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/koa/lib/application.js:75:43)
      at Object.<anonymous> (/Users/davidecarpini/vas/hit-radar-report-2/src/index.tsx:50:5)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Object.nodeDevHook [as .js] (/Users/davidecarpini/vas/hit-radar-report-2/node_modules/node-dev/lib/hook.js:61:7)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by willywill** [comment]
This is caused by the exported library functions used in your example does not call the necessary functions to clean up the Yoga layout objects.

Doing a deep dive on this revealed to me that in the memory snapshots, for each request the PDF classes aren't released from memory and their references point to Yoga's `measureFunc` object.  There was an earlier fix for cleaning up these objects in memory in this issue here: #378. As we can see a part of the fix was calling `this.layout.unsetMeasureFunc`.

The way you're using `pdf(<PDFDocument />).toBuffer()` in the example bypasses the cleanup phase.

What we're supposed to use if we want to render the PDF into a buffer is `ReactPDF.renderToStream` which does properly call the cleanup functions as you can see from these lines of code below:

```
const renderToStream = async function (element) {
  const instance = pdf(element);
  const buffer = await instance.toBuffer();
  instance.container.finish(); // This cleans up objects from memory
  return buffer;
};
```

With that line of code changed, there is no more memory leak.

@diegomura This method is not listed anywhere in the documentation however so we should add that so that scenarios like this are avoided in the future.

**Comment by bastilletech** [comment]
Hello @diegomura , first thank you for your work ! 

I am using the library to generate a pdf file with dynamic content, extract to a web magazine.
First, I try to generate it in front-end, but it was really slow, and it blocked the front-end.

So, I decided to generate it in backend, with a worker process.
I am using Bull library to queue the process, Socket.io to tell the browser client when pdf is processed, and Google Cloud Storage to store the file.

**Describe the bug**
When it process in Heroku Worker Dyno, the memory increase, and never comes back down.

**Worker code**

`let workers = process.env.WEB_CONCURRENCY || 1;
let maxJobsPerWorker = 10;

function start() {

    let workQueue = new Queue('generatePDF', REDIS_URL);

    // page numbers array
    let articlesPage = [];

    // page numbers first render
    let setArticlesPage = (datas) => {
        articlesPage = datas
    };

    workQueue.process(maxJobsPerWorker, async (job, done) => {

        try {

           // mkdir if not exist yet
            mkdirp(`${__dirname}/pdfs/${job.data.magazine_slug}`, function (err) {
                if (err) console.error(err);
            });

            console.log("-- get page numbers render --");

            await ReactPDF.renderToStream(
                <DocumentPDF numero={ job.data.numero } magazine={ job.data.magazine } articlesPage={ job.data.articlesPage }
                             magazineObj={ job.data.magazineObj } url={ job.data.url }
                             setArticlesPage={ setArticlesPage }
                />
            );

            console.log("-- Save it as a file render with page numbers (for summary) --");

            await ReactPDF.render(
                <DocumentPDF numero={ job.data.numero } magazine={ job.data.magazine }
                             magazineObj={ job.data.magazineObj }
                             url={ job.data.url }
                             setArticlesPage={ setArticlesPage }
                             articlesPage={ articlesPage }
                />,
                job.data.pdf_link
            );

            console.log("-- Upload to GCS --");

            await uploadFile(job.data.pdf_link);
            let file = storage.bucket(bucketName).file(job.data.pdf_name);
            let metaData = await file.getMetadata();
            const gcsURL = metaData[0].mediaLink;

            done(null, {
                pdf_name: job.data.pdf_name,
                pdf_url: gcsURL,
                socketId: job.data.socketId
            });

        } catch(err) {
            console.log("err => ", err);
            done(new Error('Error => ', err));
        }
    });
}
throng({ workers, start });`

**Screenshots**
before rendering pdfs:
<img width="839" alt="Capture d’écran 2020-01-16 à 11 12 36" src="https://user-images.githubusercontent.com/31648817/72516466-032d5e00-3852-11ea-9f66-bb4dfc82977a.png">

After first render - 1 pdf (110 pages):
<img width="751" alt="Capture d’écran 2020-01-16 à 11 13 13" src="https://user-images.githubusercontent.com/31648817/72516464-032d5e00-3852-11ea-866d-227bb7fe1daf.png">

After second render:
<img width="713" alt="Capture d’écran 2020-01-16 à 11 13 44" src="https://user-images.githubusercontent.com/31648817/72516465-032d5e00-3852-11ea-9123-ee89c8c460dd.png">

etc.

Heroku RAM limit : 512MB

It's like renderToStream and render functions store datas in memory, but not flush it after process.

**Environments**
- "@react-pdf/renderer": "^1.6.8",
- "bull": "^3.12.1",
- "throng": "^4.0.0"
- Heroku Worker Dyno
- Node 12.14.1
- npm 6.13.4

**Comment by will-evers** [comment]
> This is caused by the exported library functions used in your example does not call the necessary functions to clean up the Yoga layout objects.
> 
> Doing a deep dive on this revealed to me that in the memory snapshots, for each request the PDF classes aren't released from memory and their references point to Yoga's `measureFunc` object. There was an earlier fix for cleaning up these objects in memory in this issue here: #378. As we can see a part of the fix was calling `this.layout.unsetMeasureFunc`.
> 
> The way you're using `pdf(<PDFDocument />).toBuffer()` in the example bypasses the cleanup phase.
> 
> What we're supposed to use if we want to render the PDF into a buffer is `ReactPDF.renderToStream` which does properly call the cleanup functions as you can see from these lines of code below:
> 
> ```
> const renderToStream = async function (element) {
>   const instance = pdf(element);
>   const buffer = await instance.toBuffer();
>   instance.container.finish(); // This cleans up objects from memory
>   return buffer;
> };
> ```
> 
> With that line of code changed, there is no more memory leak.
> 
> @diegomura This method is not listed anywhere in the documentation however so we should add that so that scenarios like this are avoided in the future.

I am experiencing this memory leak using renderToStream with that line included. I think there may be an additional cause. It seems to only really affect me when the pdf's I am rendering exceed a certain size.

**Comment by willywill** [comment]
@will-evers So after implementing the proposed fix in our production application, we also still see leaks. So I believe you are correct, while that change certainly helps in this example, there is still a problem left unsolved in regards to the memory leak.

**Comment by will-evers** [comment]
@willywill it looks like the Root component is never calling its finish function so its never cleaning up its children, only its sub pages. My colleague, @antoine1anthony is testing it out, but that seems like a likely candidate for a memory leak. Especially since the leak is made worse by the larger the pdf. more children > more memory

**Comment by mfferreira** [comment]
bump

**Comment by knoefel** [comment]
Are there any updates regarding this issue?

**Comment by bastilletech** [comment]
Still not working

__

Jérémie Julien - *Lead Designer UX/UI*


www.agencebastille.com
*fb <http://www.facebook.com/wearebastille> / **tw
<https://twitter.com/AgenceBastille> / In
<https://www.linkedin.com/company-beta/17894792/>*
*Bur +33 (0) 1 53 38 64 54*
42, rue Sedaine - 75011 Paris

**Comment by victorlpgazolli** [comment]
Still not working ²

**Comment by peterzanetti** [comment]
I'm experiencing something similar though it is not every document. Certain documents will recreate the issue every time. Others will not. When its created, memory usage runs away until the tab crashes.

**Comment by chunshien** [comment]
Still not working, the render time getting longer when i load the same documents multiple times in web, example render first time need 2s then 3-4s, 5-6s, 7-8s.

**Comment by SethThoburn** [comment]
In my case, I thought this was still an issue, turned out I was just using node workers incorrectly. 

I was calling 
```
 parentPort?.on("message", messageHandler);
```
and never removing the handler. Just have to call 
```
parentPort?.removeListener("message", messageHandler);
```
inside the function when it's done.

**Comment by creskopper** [comment]
The memory issue is still a thing even in the latest, I'm using v3.3.8 inside an Electron app (main process) and I see this issue, and what I've noticed is that when the document has a lot of pages (I'm generating pdfs with ~ 800 pages) the issue is more noticeable.

I searched the issues and didn’t find anything useful to fix the issue.

**Comment by Niranjanck** [comment]
> The memory issue is still a thing even in the latest, I'm using v3.3.8 inside an Electron app (main process) and I see this issue, and what I've noticed is that when the document has a lot of pages (I'm generating pdfs with ~ 800 pages) the issue is more noticeable.
> 
> I searched the issues and didn’t find anything useful to fix the issue.

are you solve this issue ?
