### ISSUE TITLE
Why I Can't Change To UTF-8

### ISSUE THREAD

**Issue by topspinppy** [diegomura/react-pdf#719]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Misiu** [comment]
@topspinppy You must register a font that contains UTF-8 characters -  https://react-pdf.org/fonts
for example:

```
Font.register({
  family: "Roboto",
  src: `${process.env.PUBLIC_URL}/static/media/Roboto-Regular.ttf`
});
```

then create styles:

```
const styles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
    fontFamily: "Roboto"
  }
});
```

and use it in Your document:

```
<Document>
    <Page size="A4" style={styles.body}>
    ....
```

hope this helps 🙂

**Comment by diegomura** [comment]
Exactly. Also! It would be cool for next time to fill the issue template ☺️
