### ISSUE TITLE
Error: Failed to compile

### ISSUE THREAD

**Issue by Kaishley** [diegomura/react-pdf#72]
Hi, 

I am getting the following error when trying the example in the README.

```
Failed to compile.

./~/@react-pdf/core/lib/index.js
Module not found: `/node_modules/@react-pdf/core/lib/stylesheet/index.js` does not match the corresponding path on disk `Stylesheet`.
```

I am not sure if that makes a difference, but the folder is named 'Stylesheet', while in the import path it is 'stylesheet'.

For reference, I am using the versions published on npm.

**Comment by jbovenschen** [comment]
Thanks for reaching out.

I guess you're trying the dom-bindings example, just made a PR for it #73.

Can you try that one out?

**Comment by Kaishley** [comment]
Thanks for your reply.

I am trying the example in the README itself.
[https://github.com/diegomura/react-pdf/blob/master/README.md#how-it-works](url)

I did install all 3 packages v0.1.6.

**Comment by jbovenschen** [comment]
I see, a little bit curious which bundler did you use?

**Comment by Kaishley** [comment]
The default React one.
