### ISSUE TITLE
Publish newest version or access to nightly build?

### ISSUE THREAD

**Issue by asgerhallas** [diegomura/react-pdf#720]
I'd like access to the latest changes on npm, is there a reason the library has not been published in a while? 

If not, have you considered publishing on each successful build?
If there is a reason not to, is it then somehow possible to get access to a nightly build or something like that? 

And please let me know if there's anything I can help with  :)

**Comment by diegomura** [comment]
You are right! Sorry for being so unresponsive. That will change now. Last publish is from 9 days ago so you can access to las changes now. Publishing on each build will create a lot of noise imo. But as I said! This should not happen again ☺️

**Comment by asgerhallas** [comment]
I must admit I missed that last publish. Thanks! Good to have you back :relaxed:
