### ISSUE TITLE
How to insert textArea?

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [diegomura/react-pdf#721]
We want to insert editable area to our pdf document.

If user edit the area, user can print the text together.

Could you help me?

**Comment by asgerhallas** [comment]
PDFKit which is used to create the rendered PDF document does not support forms (https://github.com/foliojs/pdfkit/issues/500), so I don't believe this is possible.

**Comment by diegomura** [comment]
Exsactly as @asgerhallas said! There's already another issue for forms so I'm closing this

**Comment by Yoshihide-Nishimoto** [comment]
Thanks.

**Comment by joeyparis** [comment]
@asgerhallas PDFKit now supports AcroForm, is this now possible? https://github.com/foliojs/pdfkit/pull/1002/files/61603057010e382f46dab27288a21e29e14d51da

**Comment by mmahalwy** [comment]
Can we reopen this as there is now support?

**Comment by valstu** [comment]
Came to look for the same feature, I have never worked with custom renderers so would this be a laborious thing to add?
