### ISSUE TITLE
Continued text with different font sizes gets wrong letter spacing

### ISSUE THREAD

**Issue by asgerhallas** [diegomura/react-pdf#722]
**Describe the bug**
When embedding a <Text /> inside another <Text /> and they have two different font sizes, the first text seems to get the letterspacing of the last.

I have tried to reproduce the bug using PDFKit, but could not, which lead me to believe it's a React-pdf issue.

**To Reproduce**

```
const Quixote = () => (
  <Document>
    <Page>
      <Text style={{ fontSize: 10 }}>
        Capítulo I: Que trata de la condición y ejercicio del famoso hidalgo D.
        <Text style={{ fontSize: 14 }}>Quijote de la Mancha</Text>
      </Text>
    </Page>
  </Document>
);

Font.register({
  family: 'Oswald',
  src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
});

ReactPDF.render(<Quixote />);

```
Or see:
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e619da74e5400a8614b1a004f003619b006f4530019b82801949002f0c00b860046000c3002fb9a1c3380611e001c02dd404b240c00928711628009c78a07860004cb1644340c142918090019ec061a4603000ac31fde3e23dc364d4791840203c002c91427964f83c6800e8386da9c5246065e49455d559b4f50c8c00582cad1091d3d0b1c2612260016478c180ca78a801e95ad89a443624b785d77805add6e8199959d80801b8c8c800c435ebfc30f891a0b2f11439548a9165a4860039001e42000776aa8481001a0e041b2c0b2940a00e083e8d66b1e94020f53e34082717aa81186b081ac4a90d9284d600372300198d6004d003ea8800d20035001b080001c0075102d2004600555083318ac800680138780041257d451aa20591cc373b80094303c60140b8347bb3c58e17f1e0a86334260606b620ea80000

**Screenshots**
![Capture](https://user-images.githubusercontent.com/299575/65498486-438c5900-debc-11e9-9f7d-f61005bbe44b.PNG)

**Desktop (please complete the following information):**
 - Chrome
 - React-pdf 1.6.0

**Comment by diegomura** [comment]
Working good in latest 2.0 version! Thanks

<img width="1025" alt="Screen Shot 2021-04-07 at 1 13 49 AM" src="https://user-images.githubusercontent.com/5600341/113809457-84665e80-973e-11eb-9eee-24ddfe7f52f6.png">
