### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by awesome-michael** [diegomura/react-pdf#723]
I added react-pdf to my project and keep getting the error:

```
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at $$$reconciler (react-reconciler.development.js:149)
    at Module.<anonymous> (react-pdf.browser.es.js:5400)
    at Module.../matrix-react-sdk/node_modules/@react-pdf/renderer/dist/react-pdf.browser.es.js (react-pdf.browser.es.js:5776)
...
```

I removed any code to find the error but even if I have only the import (`import { Page, Text, View, Document, PDFDownloadLink, StyleSheet } from "@react-pdf/renderer";`) command added to my project I get the error.

There was an issue about that a while ago but with no solution.

Any ideas on this?

**Desktop:**
 - OS: MacOS
 - Browser chrome
 - React-pdf version v1.6.3

**Comment by Macro21** [comment]
import * as React from 'react';
import 'mdn-polyfills/Object.assign';
import 'core-js/es/object';
.......
Works for me!

**Comment by lfoliveir4** [comment]
> import * as React from 'react';
> import 'mdn-polyfills/Object.assign';
> import 'core-js/es/object';
> .......
> Works for me **with react-big-calendar and the same issue**.

where did you do these two imports? I have the same issue

**Comment by diegomura** [comment]
Please upgrade to 2.0. Haven't experienced nothing like that with that version. Please report back if the issue persist.
