### ISSUE TITLE
PDF render not proper

### ISSUE THREAD

**Issue by pallavibiwal** [diegomura/react-pdf#727]
I have added static PDF code provided on website

<PDFDownloadLink
        document={<PdfContainer />}
        fileName="exportpdf.pdf">{({ loading}) =>
          loading ? "Loading document..." : "Download Pdf"
        }</PDFDownloadLink>

This is my PdfContainer 
import React from "react";
import {
    Page,
    Text,
    View,
    Document,
    StyleSheet
    // Image
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: '#E4E4E4'
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1
  }
});
export function PdfContainer() {
    return (

      <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text>Section #1</Text>
        </View>
        <View style={styles.section}>
          <Text>Section #2</Text>
        </View>
      </Page>
    </Document>
    );
}

But my downloaded PDF has only 2 blank pages nothing else.

![Screenshot (88)](https://user-images.githubusercontent.com/17424865/65870922-ef411780-e39a-11e9-8183-c9bbbafe0828.png)

**Comment by muthumani11** [comment]
properly connect your React-Dom and verify it ,Start default the react pdf page splited in 2 
in example take a template  https://github.com/muthumani11/tax_transcript

**Comment by KarthikeyanSJ** [comment]
Only Show 2 blank pages

**Comment by diegomura** [comment]
The 2 blank pages bug it's fixed in the latest 2.0 versions. Please try it out! Report back if this persist
