### ISSUE TITLE
Wrong size in centimeters ( cm ) 

### ISSUE THREAD

**Issue by ribas14** [diegomura/react-pdf#728]
I'm trying to create a pdf with `width: 18.9cm height: 10cm `

```js
const styles = StyleSheet.create({
  image: {
    height: '100%',
    width: '100%',
    objectFit: 'cover'
  }
});

export const Pdf = (props) => (
  <Document>
    <Page dpi={300} size={
        { width: 18.9 * 37.7952755906, height: 10 * 37.7952755906 }
     } wrap={false}>
      <Image src={props.img} fixed={true} style={styles.image} />
    </Page>
  </Document>
);
```

But I always get the wrong dimensions like in the print, anyone has any idea why?

![Captura de Tela 2019-10-03 às 14 51 34](https://user-images.githubusercontent.com/13273877/66151384-92896b00-e5ed-11e9-9afb-3741439671f0.png)
 - OS:MacOS
 - Browser chrome
 - React-pdf version "@react-pdf/renderer": "^1.6.6",

**Comment by diegomura** [comment]
dpi is not a valid prop for Page. PDF docs are always 72 dpi. You can try passing page size using straight cm (‘{ width: “18.9cm”, height: “10cm” }’! Not sure if that will work for pages to be honest! But it s supported) or calculating dimensions based on the default DPI
