### ISSUE TITLE
PDFViewer's Download and Print Button don't work on Safari

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [diegomura/react-pdf#729]
The Download Button and Print Button are shown, but not working.
This is reproduced only on safari.(Chrome Safari Edge are OK)

![ 2019-10-04 10 22 02](https://user-images.githubusercontent.com/19885548/66174630-edc06980-e690-11e9-83a7-54f873fe694b.jpg)

This is part of my code.
```
<PDFViewer style={styles.viewer}>
      <Document>
        <Page size="A4" style={styles.page}>
           ...
        </Page>
      </Document>
</PDFViewer>
```

**@react-pdf/renderer version**
```
"version": "1.6.4"
```

**node version**
```
v9.4.0
```

**safari version**
13.0.1

**Comment by Yoshihide-Nishimoto** [comment]
After all, I can't resolve this, so I set up a download link on the page.

**Comment by diegomura** [comment]
Might be related to https://github.com/diegomura/react-pdf/issues/714
Couldn't see this yet sorry

**Comment by diegomura** [comment]
Tested it with latest version and worked fine on safari 14.0.3. Closing this. Thanks!

<img width="1396" alt="Screen Shot 2021-04-25 at 17 02 37" src="https://user-images.githubusercontent.com/5600341/116007837-0c29e500-a5e8-11eb-9841-6d14378324b3.png">

**Comment by sarkamrav** [comment]
I have tried with 16.6 safari version,  print option is working , but not download option.
