### ISSUE TITLE
Link src is wrong

### ISSUE THREAD

**Issue by ivan133** [diegomura/react-pdf#730]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to [link](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805032554c00f0022230080b619853117554d002808601ccb08004e48d947e509386c008800dbf30004c2307e001c33cceddb8d003248c006b18114706c01bc60072001650a168800b803d1780eefe00e94da08545f998034198bc1144008c5491a0005801380158bc1c60017d89ec1dfd7c8320a504c2238003abb27268bc4dcdf40d68bc05859ba9ea189959d9380801b8c846009431f980a178e800c40344d9543144f0691151d0b0bd8886c880)
2. Download PDF
3. Open it
4. Move cursor several pixels below the link
5. You can see that link url is http://www.instagram.c/ instead of https://www.instagram.com/urbanist495/
If you change the text of link to something like test (without dots) it works 

**Expected behavior**
Link should be https://www.instagram.com/urbanist495/ in all cases

**Desktop (please complete the following information):**
 - OS: Linux, Mac, Windows
 - Browser Chrome
 - React-pdf version [v1.6.6]

**Comment by diegomura** [comment]
Fixed in latest 1.x and 2.0. Thanks!
