### ISSUE TITLE
Hebrew not showing correctly

### ISSUE THREAD

**Issue by colocba** [diegomura/react-pdf#732]
I'm hard coding Hebrew words in the code and the pdf can't show me Hebrew letters.. is there any props for changing utf formats for hebrew or something like that?

This is what I see on the pdf:
![Screen Shot 2019-10-06 at 9 50 32](https://user-images.githubusercontent.com/17878205/66265419-d0210a80-e81e-11e9-9550-7caab92f0185.png)

Thanks!

**Comment by ahmedXabdeen** [comment]
same problem here but with Arabic
![Screenshot_2019-10-07_14-28-14](https://user-images.githubusercontent.com/17083569/66311437-bf4fc200-e90e-11e9-942d-d67b812d837c.png)

**Comment by diegomura** [comment]
You will have to load a custom font that supports those types of characters. Although I have to warn you that unfortunately react-pdf does not support RTL writing systems yet
