### ISSUE TITLE
Is there any react-pdf library which support react ^15

### ISSUE THREAD

**Issue by manojchandrabose** [diegomura/react-pdf#738]
Hi, Is there any react-pdf library which support react ^15??? Please suggest me!!
Thanks in advance.

**Comment by diegomura** [comment]
What do you mean by _other_ react-pdf library? You mean version?
Unfortunately not. React-pdf (and every other renderer out there) relies on react fiber and reconciler shipped on ^16. Shouldn't be that painful to upgrade though, and it's always recommended not to sticky with old React versions
