### ISSUE TITLE
Cant render image in the preview

### ISSUE THREAD

**Issue by alvarogonoring** [diegomura/react-pdf#741]
Hi! Im getting a problem with the image component, when referencing an image in the DOM, i get nothing except the text. I still get no error in the console log, and i don't know what it can be.

The code:

_________________________________________________________________________________________________________

import {
  Page,
  Text,
  View,
  Image,
  Document,
  StyleSheet
} from "@react-pdf/renderer";
import { PdfRender } from "./styles";
import pic from "../../assets/GroupglobeOn.jpg";

      <PdfRender>
          <Document style={styles.teste}>
            <Page size="A4" style={styles.page}>
              <View style={styles.section}>
                <Text>{pdfTitle}</Text>
              </View>
              <View style={styles.section}>
                <Image src="../../assets/GroupglobeOn.jpg" /> // importing this way dont work
                <Image src={pic} /> // importing this way dont work
              </View>
            </Page>
          </Document>
      </PdfRender>

**Comment by dulcineapena1** [comment]
@alvarogonoring 
I had the same issue, I fixed it using class components intead of functions.
```
export default class PdfFile extends Component  {
   render() {
      return (
        <PDFViewer >
            <Document>
                <Page>
                    <View>
                        <Image src={pic}/>
                    </View>
                </Page>
            </Document>
        </PDFViewer>
    );
  }
```

**Comment by alvarogonoring** [comment]
Yea, im using styled components, so the "PdfRender" component do the work haha. I solved the problem instancing "Image" outside de "View" component.
