### ISSUE TITLE
print <sup><sub>

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [diegomura/react-pdf#745]
I want to insert <sup> or <sub> to print a mathematical expression in PDF for Express mathematical formula.

is there any way?

Currently, it is tentatively implemented using position: absolute like below.

```
<Text>
             b
            </Text>
            <View
              style={{
                position: "relative"
              }}
            >
              <Text
                style={{
                  position: "absolute",
                  fontSize: 6,
                  top: -3,
                  left: -8
                }}
              >
                2
              </Text>
```

**Comment by diegomura** [comment]
You can create your own abstractions of these elements with Text as you did and reuse themselves right? I'm not sure if this will be built inside the lib. Internally, what it would do is exactly what you did

**Comment by Yoshihide-Nishimoto** [comment]
Thanks for responding.i'll try to create abstractions.

**Comment by tomgallagher** [comment]
@Yoshihide-Nishimoto  did you have any success with this? And were you able to make it work as an inline style?

**Comment by tomgallagher** [comment]
If anyone else comes upon this, the only way I could get inline <sup> equivalent was to create a Data URI from a canvas with fillText and add it to the Text element as an inline image. No combination of View and Text elements, with relative / absolute positioning or flexbox, worked for me inline in a Text element.
