### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by ohadleshno** [diegomura/react-pdf#747]
**Is your feature request related to a problem? Please describe.**
There is no rtl support now. 

**Describe the solution you'd like**
Add to the styles like in css attribute direction.
const styles = StyleSheet.create({
  body: {
    direction: 'rtl',
  }
**Describe alternatives you've considered**
i tries manipulating the text to display correctly but it was to complicated.
I tried at start to write try :
text = text.split(' ').reverse().join(' ') 
but it didn't work

**Comment by Liel208** [comment]
Any updates on this? 

I manage to sort out some use cases with flex-direction, but when it comes to printing Hebrew strings that contain also english letters  the direction property is the only option I come to think of :(

**Comment by idanwe** [comment]
Hi @diegomura I would like to try and add support for RTL support (I saw that Yoga is supporting RTL)

Is it something you would like to consider?
If so, can you help me with some guideline how you think it will best to approach it?

**Comment by ismailbenali** [comment]
Any updates on this?

**Comment by buskerone** [comment]
Hi @diegomura, do you think you can guide me with the current structure for the Text component nor a possible solution so I can take it from there in order to create a PR?

**Comment by ItaiPendler** [comment]
Any updates?

**Comment by benshabatnoam** [comment]
I can help with the PR if someone decide he's going for it...

**Comment by Liel208** [comment]
Following [ijavad805](https://github.com/ijavad805) comment. Here is the solution that worked for me as a React component:
```
const TextRTL = ({ text, isRTL }) => {
  const styles = StyleSheet.create({
    textContainer: {
      display: 'flex',
      flexDirection: isRTL ? 'row-reverse' : 'row',
      flexWrap: 'wrap',
    },
    text: {
      ...(isRTL ? { marginLeft: 2.5 } : { marginRight: 2.5 }),
    },
  });
  return (
    <View style={styles.textContainer}>
      {text.split(' ').map((item) => (
        <Text style={styles.text}>{item}</Text>
      ))}
    </View>
  );
};
```
