### ISSUE TITLE
Cannot find module 'lodash/fp/toPairsIn'

### ISSUE THREAD

**Issue by liam4** [diegomura/react-pdf#75]
My setup:

```bash
$ mkdir pdf
$ cd pdf
$ yarn add react
$ yarn add @react-pdf/core
$ node index.js
# index.js simply 'require's @react-pdf/core
Error: Cannot find module 'lodash/fp/toPairsIn'
```

Adding `lodash` via `yarn add lodash` fixes the issue. (Am I supposed to do `yarn add react-pdf`, not `yarn add @react-pdf/core`..?)

**Comment by jbovenschen** [comment]
It seems that lodash is missing in the @react-pdf/core package, do you mind to make a PR for that?

**Comment by diegomura** [comment]
Just adding `lodash.toPairsIn`should be enough. Also, why are we using this method from the functional programming package? I suggest sticking with the regular `toPairsIn` lodash method.

@liam4 do you want to do it or shall I take this issue?

**Comment by liam4** [comment]
@diegomura I'd appreciate it if you did; for whatever reason whenever I run `yarn` it messes with the dependency list a bit (though react-pdf works as it should), so that kind of makes making a PR that modified yarn.lock/package.json difficult..

**Comment by diegomura** [comment]
Thats weird. But no problem, I'll fix this issue asap

**Comment by AggarwalAnkit** [comment]
@diegomura could you please help me with this error

../~/@react-pdf/core/lib/elements/Text.js
Module not found: Can't resolve 'lodash.isnan' in '/node_modules/@react-pdf/core/lib/elements'

I created a react app using creat-react-app and added following:
yarn add @react-pdf/core
yarn add @react-pdf/node.

After that, I copy pasted the sample code given on git (https://github.com/diegomura/react-pdf)

Do I have to install this missing dependency?

**Comment by diegomura** [comment]
HI @AggarwalAnkit ! Can you create a new issue for this? I see why you wrote it here, but it's something unrelated.

**Comment by AggarwalAnkit** [comment]
yeah sure.
