### ISSUE TITLE
Issues when testing using jest

### ISSUE THREAD

**Issue by liron-navon** [diegomura/react-pdf#750]
**Describe the bug**
I use react-pdf for a frontend project, and it works fine, but when testing using jest, it thinks that it no longer has DOM, with the error: "PDFViewer is a web specific API"

If I would know how you make the detection of whether to use the "src/node.js" file or not maybe I could have override it, or help in some way...

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. create a new project with "create react app"
2. add a document using "PDFViewer"
3. add a test for that component using "enzyme.mount"

**Expected behavior**
There is a "window" element since we have js-dom, so react-pdf should work properly...

**Comment by diegomura** [comment]
Repeated #710. Couldn’t take a loot at this yet

**Comment by rachaelmcq** [comment]
Just in case anyone else runs across this issue, we weren't able to render the full component in our Enzyme tests, but we were able to get some Jest testing of the PDF by doing:
```    
const document = await pdf(
    <Document>
         [...]
    </Document>,
).container;
expect(document).toMatchSnapshot();
