### ISSUE TITLE
Add more examples and documentation for Orphan and widow

### ISSUE THREAD

**Issue by LouisDrame** [diegomura/react-pdf#752]
**Is your feature request related to a problem? Please describe.**
There's currently no example for orphan and widow api and the documentation is very short, I tried to use it without success. So now I have titles alone at the bottom of some pages of my documents

**Describe the solution you'd like**
More documentation and examples for orphan and widow API

**Describe alternatives you've considered**
I tried many use cases with orphan and widow api without success, I'm currently stuck because I can't find any other solution to my problem.

**Additional context**
I tried to use orphans and widows API to prevent titles to be alone at th bottom of a page, I tried many things but none of them worked. I'm currently using a markdown parser to transform markdown to html, i override the html renderers to return react-pdf components, the problem is that titles are rendered in their own text components and the followings components aren't linked in any way to the titles. Examples would be great to know if what i'm trying to do is possible or if I'll have to find another way to avoid page breaks between titles and their immediate content.

A visual description of what's happening : 
The html code : 
![html](https://user-images.githubusercontent.com/38241095/68316934-8dbb4980-00ba-11ea-9399-47f341a7f1e7.png)

What my renderers are returning : 
![jsx](https://user-images.githubusercontent.com/38241095/68316967-9dd32900-00ba-11ea-8af8-c50f58df2d1e.png)

Is there a possibility to use orphan and widows API in this configuration ? 

Sorry for the format, it's half a question half a feature request but I didn't find any other issue like this.

**Comment by asgerhallas** [comment]
In this case using `minPresenceAhead={1}` on the header text should solve your problem.

As can be seen in this [Sample](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a00d490600ee31a7889126231e009cf9230005440007005c3003b00060f3157aaa01e9740c3535a8ec3051618d258ce4002c307894312d55cd6cb92c302059803001041293240119d439426000fc600184b279309461f490a0e2601b80a001691c9400cdaa2ab5fdc3224334a9c6a2a1444d63653123cb2b296a78209060a194406078011c1030446094016e78618079196c019e8d6c0f415830f32cc46e4021af8eb0c91fab0ac300189c72001a73860469a113ec183c338e4613908238523c790f1a18e10258013063920b6589d9394122139f1f6d48c2d381c4e40b0e19c388f13e3008a632c7a3030090d76499c006ec8824c28c083049d2c98183c92c3c001788164307c8217659080c03942666029079301b328449135d1c7ce632a0ea29614010f6cb56078a2db3edc1582b4c2ce5c396ec6000190021e384d18687a12cbf7379ca360234c0fd40845eb18201117af540cf53a40006e182f2e9fb22509f60952f28904a100263d29241f010a096373a0585b84040d0c342253358e488ad0daef00f9c1cec660e6064764a55684c016478028e74297448025d9c374a0428bf6bb09d1c4e674bae2604268723e7f404a7da110195c7801764e1bf709d468ead38d935b9202497e5bdcc20dc0a04394609568c20805a17b995301cf0a4944d94b2b130080137c52c1811d422b634418254904b0ae038443e0002fe03362809031df67d99136c1773078000ac92614b0470988249706cd0d84d64e83e100044b151434c0f134b040943d1512c9985534137d20e00397d4ee78220b003e6c9eb249a14f5fb180c046d24b1078e834e1b8ee2f56b422c4a04901c5a1040b8c7441484891f47e2cd9e222f47b4fc9e0136c8a02c8c77f84e6856c8395370208a81170815f373ae39d91600c3154ac5130477c30648052401e64cc458a05572171c4351a0905f904be5b26b9ae5b9ee05d2c01d53310f8279ae538fd6b9988c1187c48d26d6cbd23e2b96436402199266a1fc5e004108023a018661587600822cc83200031700a0590b21b1bb4b0f0090380195c910845700072001e4207d1912513ec84380812c600beb88a02811c0819c7f1fc019aeb90f86811a13564501187f0207f17e7fa44251fc5144a00199fc00134007d3b000696d00036100000e001d440515e40015494127184a6000d00138787c9f2258a00193eb215453bceb79a0230e619070180006525630556120c06ea9d124c09e8e1141515c67b3421294552c03e01c170601260056607cda48adbe00021741764615c7a69d9182db76000902490354411115c4779d9f063e62a03114d91911d6155b0e3057000260005863ca196281f21ccf8300bed35304b081e4fae8bade8fa601fafe806a5ca15418e786d4e202493cd053a80d3954339804a4cef39d82242f8bd2e1bf2e522af340b1ac5b13da86401f6606ce3c18edb90610791e3c4e60337383ee07a1e4a266c7c5e6c69e47b1efbdafee77abedfbf1c06381dff389e7bce1afdb15c3bed5d53ba7001b9c4601722ead9a7a7d1e2081a0120018421e789f1ae75cbe9d8240cc0200f40004a6bc370b758e1c1307f021ec7d281ff300da0523315b891d87bfb05e5606f8873e4e1cb2bd09285e1b78c7228c912c0ff4a0a7c4070f51e231284af6f659cb7b8089e9024b99727473cc7a800440221b9f02c848278470212020001c930790291046d62d8cc5c017d6c47d9a9260641423ae99f0016233422855eebc498c8f84180061405705e3381f23e090dfc58f08153d147bc4ae2a3b33770d15a3904ef196674c80e0c48dd0b80d00bab74583f0bc0541102a0740581fc310596400000)
