### ISSUE TITLE
transform: rotate not work for angles < 10deg

### ISSUE THREAD

**Issue by CzBuCHi** [diegomura/react-pdf#753]
**Describe the bug**
Style `transform: rotate(#)` not work for angles 0deg to 9deg.
Tested angles: 0deg - 95deg

**To Reproduce**
[react-pdf REPL](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e6194a7181d8652a005430a58d0027801b0cd8037bca51001d2619013802fbb319c00592083076c004ee879424e0618743003b886b01ad4672a01e8a465497dc48364a11594d52235b5a4a0011800190d434dcd2c12616ca1ed1cc1dd3cbc2c00cc90c031d203c28445840378048da9fce8199959d80801b8c8c800c5c0a135ac30f9cd31acf054394a79189014e400b86001c801e420dc7814004dd600683821ad80d7d64ca0a0001c2057fdfd4b86b4f9a1f381354119fc21fc403b3dbedfc00374480199fc004d003e84800d20035001b080001c007510282004600557d84318b08006ae87800414a768a0a575991f4bd7ea8120112885970006558860b9260c06046c031bd830330e159746b59b09183c6b04cc06b087248e945f141ac3c480bdac8c35800897262bc2e9f6e30221a38fa13a50ac29196f9e58a8a8aad59aed6eb3c069831aec983c0a42d7c2b4da4e4cbe990004a181e300a05c1a00d462c0b74ca888543a0b0fe623328000)

**Expected behavior**
Both text rotated

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome  78.0.3904.70
 - React-pdf: 1.6.7

**Comment by sandroweb** [comment]
+1

**Comment by filianer** [comment]
+1

**Comment by diegomura** [comment]
Will fix it asap. Good catch

**Comment by tomherbin** [comment]
Hello, is it still an issue ? 
I can't get a 7degree rotation in v5.4.0

**Comment by diegomura** [comment]
v5.4.0 is not a version of this package

**Comment by stefanylaforest** [comment]
does not work for version 2.1.1 etheir

**Comment by ishikachhabraa** [comment]
style = {{transform: 'rotate(180deg)' }}
this worked for me but gets appiled only to View component.
is there any way i can rotate text
