### ISSUE TITLE
Heroku Build Fails

### ISSUE THREAD

**Issue by 4ourMiles** [diegomura/react-pdf#755]
Hi, love your project and it works great, except for when I deploy my app to Heroku.

While in development everything works as expected, but when I deploy to Heroku my build start and build scripts fail:

**Client**

`  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start",
    "compile-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.css -w",
    "minify-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.min.css --output-style compressed",
    "map-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.css --source-map true"
  },`

Server
`"heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"`

My engines are Node 12.13 and npm 6.12

Since @react-pdf/renderer was the only update I made to my project, I removed it and was able to successfully deploy my project to Heroku.

Any ideas on what might be causing this to fail in the build & start scripts?

Thank you!

**Comment by tosifkhan01** [comment]
> Hi, love your project and it works great, except for when I deploy my app to Heroku.
> 
> While in development everything works as expected, but when I deploy to Heroku my build start and build scripts fail:
> 
> **Client**
> 
> ` "scripts": { "start": "react-scripts start", "build": "react-scripts build", "test": "react-scripts test", "eject": "react-scripts eject", "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start", "compile-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.css -w", "minify-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.min.css --output-style compressed", "map-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.css --source-map true" },`
> 
> Server
> `"heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"`
> 
> My engines are Node 12.13 and npm 6.12
> 
> Since @react-pdf/renderer was the only update I made to my project, I removed it and was able to successfully deploy my project to Heroku.
> 
> Any ideas on what might be causing this to fail in the build & start scripts?
> 
> Thank you!

@4ourMiles I'm facing the same issue, any update on this?

**Comment by djedd** [comment]
I have the same issue, when i deploy to staging i get the following error:

`npm run build

> frontend@0.1.0 build /home/deploy/code/apps/frontend/releases/20200324221238
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/dfa/index.js:10

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2020-03-24T22_39_31_020Z-debug.log`

in the .log file it shows the following:

`0 info it worked if it ends with ok
1 verbose cli [ '/home/deploy/.nodenv/versions/8.12.0/bin/node',
1 verbose cli   '/home/deploy/.nodenv/versions/8.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle frontend@0.1.0~prebuild: frontend@0.1.0
6 info lifecycle frontend@0.1.0~build: frontend@0.1.0
7 verbose lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.1.0~build: PATH: /home/deploy/.nodenv/versions/8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/deploy/code/apps/frontend/releases/20200324221238/node_modules/.bin:/home/deploy/.nodenv/versions/8.12.0/bin:/home/deploy/.nodenv/libexec:/home/deploy/.nodenv/plugins/node-build/bin:/home/deploy/.nodenv/shims:/home/deploy/.nodenv/bin:/home/deploy/.asdf/shims:/home/deploy/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/deploy/.asdf/shims
9 verbose lifecycle frontend@0.1.0~build: CWD: /home/deploy/code/apps/frontend/releases/20200324221238
10 silly lifecycle frontend@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle frontend@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle frontend@0.1.0~build: Failed to exec build script
13 verbose stack Error: frontend@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/deploy/.nodenv/versions/8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/deploy/.nodenv/versions/8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid frontend@0.1.0
15 verbose cwd /home/deploy/code/apps/frontend/releases/20200324221238
16 verbose Linux 4.15.0-36-generic
17 verbose argv "/home/deploy/.nodenv/versions/8.12.0/bin/node" "/home/deploy/.nodenv/versions/8.12.0/bin/npm" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the frontend@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by djedd** [comment]
> Hi, love your project and it works great, except for when I deploy my app to Heroku.
> 
> While in development everything works as expected, but when I deploy to Heroku my build start and build scripts fail:
> 
> **Client**
> 
> ` "scripts": { "start": "react-scripts start", "build": "react-scripts build", "test": "react-scripts test", "eject": "react-scripts eject", "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start", "compile-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.css -w", "minify-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.min.css --output-style compressed", "map-sass": "node-sass src/assets/scss/black-dashboard-pro-react.scss src/assets/css/black-dashboard-pro-react.css --source-map true" },`
> 
> Server
> `"heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"`
> 
> My engines are Node 12.13 and npm 6.12
> 
> Since @react-pdf/renderer was the only update I made to my project, I removed it and was able to successfully deploy my project to Heroku.
> 
> Any ideas on what might be causing this to fail in the build & start scripts?
> 
> Thank you!

Hi @4ourMiles, i solved my build problem forcing the DFA library to version 1.1.0, in my case i use CRA (create-react-app) then i modified package.json to:
`"resolutions": {
    "dfa": "1.1.0"
  }`
And in the scripts section i added: `"scripts": {
    "preinstall": "npx npm-force-resolutions "}`
and make sure the npm is up to date, apparently it is a problem with the compilation of state machines in the DFA library. This worked for me!! :).

Another solution in is to update react-scripts to 2.x version but I haven't tried it.

**Comment by diegomura** [comment]
Thanks for posting a fix. Closing this now
