### ISSUE TITLE
Question: How long is a URL valid?

### ISSUE THREAD

**Issue by tammyhart** [diegomura/react-pdf#756]
We are using this library to email the PDF URL to the user, so I'm wondering how long that blob url will actually work.

**Comment by diegomura** [comment]
Not sure if I got the question. You mean a blob url such as the ones in the repl? Not sure how long those can be. I do know it has a limit which is the limit of browser urls. After a quick google search: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by tammyhart** [comment]
Sorry, that's not what I meant. What I mean is, how long will the URL work? Will it expire after some time?
