### ISSUE TITLE
Images are being rendered at a lower quality than originals

### ISSUE THREAD

**Issue by moreguppy** [diegomura/react-pdf#757]
First off, this library is fantastic, thanks to all the contributors!  I am unfortunately running into a bit of a sticking point for a project though...

**Describe the bug**
- Using an image from imgix as source for <Image /> [Link to image](https://obminktest.imgix.net/calle-stoltz/unnamed_190923_092119.jpg?fit=crop&fm=jpg&w=auto&h=1080&q=100)
- Image in exported PDF has been compressed, reducing the quality

**Screenshots**
If you compare these, you can see the PDF version has been compressed with lossy, where as the original is still at its original quality and colour space:

__Original__
<img width="407" alt="Screenshot 2019-11-07 at 18 30 55" src="https://user-images.githubusercontent.com/2033609/68416936-5c5f7e00-018d-11ea-9b2b-35083144c1eb.png">

__PDF version__
Colours are faded/washed out:

<img width="438" alt="Screenshot 2019-11-07 at 18 30 49" src="https://user-images.githubusercontent.com/2033609/68416927-59648d80-018d-11ea-9065-193fcb6dbfb9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - React-pdf: latest

**Comment by aktn** [comment]
I am also facing the same thing :(

**Comment by diegomura** [comment]
Weird. Sorry for being late in the discussion. I see the link you provided (which is now broken) as query params to edit the returned image. Maybe react-pdf was removing those unintentionally. Can you provide a new image so I can test? I promise to test asap this time

**Comment by TCM5** [comment]
Also facing this problem. Rendered images in exported PDF lost quality related to the original ones, with the same aspect ratio.
They become somehow pixelated and blured. Is some type of compression being made?
