### ISSUE TITLE
Empty string in View Component throws an error

### ISSUE THREAD

**Issue by alizeaiter** [diegomura/react-pdf#758]
Returning an empty string from the View component throws an error as it type checks. Most of the children components are usually conditionally rendered using the && operator, example:
`const expectDefined = ...;`
`expectDefined && <Image></Image>` this would return Image if the `expectDefined` is truthy and would return "" if the `expectDefined` is an empty string which throws an error if the parent element is a View component.
It would be nice to have a check included in this awesome package as I find myself creating another component that checks for this all the time:
```javascript
export const ViewM = ({children,...rest})=>{
  return(
    <View {...rest}>{children.filter(child => child !== "")}</View>
  )
}
```
which is not so nice as it loops through all the children every time `ViewM` renders

**Comment by JCQuintas** [comment]
I've came across this same error. It should probably behave more like react and check for `falsey` values instead?

**Comment by heyalexchoi** [comment]
also had issue with  a `{ something && <Component/> }` style conditional render. Had to switch to 
```
{ something ? <Component/> : null }
```

Would be nice if this library behaved more like react.

**Comment by diegomura** [comment]
Strings can only be childs of `<Text />` components in react-pdf, so nesting a string inside a `<View />` is not valid. For falsey elements it's probably better to use `null` anyways. You won't have errors by that
