### ISSUE TITLE
PDFDownloadLink is getting error because it do not accept React Component

### ISSUE THREAD

**Issue by cdanielgomes** [diegomura/react-pdf#759]
**Describe the bug**
PDFDownloadLink is asking for a string, class/function and do not accept React.Component

I saw tutorials and the react-pdf.js and i do not understand why PDFDownloadLink is not accepting a component just like the example in https://react-pdf.org/advanced#on-the-fly-rendering

**To Reproduce**

https://gist.github.com/cdanielgomes/2e27c6e9583ea1be8c1c2599cfed0af5

In the link we have a file (DownloadButton.js) that can render a single button to trigger the pdf generation and the ancor to download it (PDFDownloadLink).

The PDF components are being "compiled" in 4 different files (Header, Document, MedicalRecords and Prescription). The Document.js had the tags Document and Page and the body is called here. 

The information is being retrieved from a mongodb and is being passed to Document.js as an Array of Arrays and the objects with the important info. 

**Expected behavior**
When click the button should generate the button for PDFDownloadLink and then download the pdf

**Screenshots**
Error: 

![Screenshot from 2019-11-12 21-24-29](https://user-images.githubusercontent.com/28347544/68713411-b4372400-0595-11ea-9112-8f35430a5e41.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Browser Chrome
 - React-pdf version [e.g. v1.1.0]

**Comment by devurc** [comment]
The example shows PDFDownloadLink being used to render a string.

The example you're looking at is probably BlobProvider, which looks to be what you want to use if you want to return anything more complicated than a string. That can return a React component.
