### ISSUE TITLE
External dependencies will not install

### ISSUE THREAD

**Issue by donni106** [diegomura/react-pdf#76]
**What is the current behavior?**
I  installed yarn for the first time per brew on mac. When trying to yarn install this project it seems to freeze on installing external dependencies. Nothing is happening for a long time:
![bildschirmfoto 2017-05-22 um 14 21 26](https://cloud.githubusercontent.com/assets/1942953/26308591/2b2e0606-3efa-11e7-873c-380de32bbcee.png)

**What is the expected behavior?**
Finishing the installation.

**Please mention your node.js, yarn and operating system version.**
node.js 7.10.0
yarn 0.24.5
macOS Sierra 10.12.4

**Comment by donni106** [comment]
There is a comment in the issue at yarn directly: https://github.com/yarnpkg/yarn/issues/3471

**Comment by jbovenschen** [comment]
Thank you for the detailed description.

This is an issue we also facing within travis, will take a look this week.

**Comment by donni106** [comment]
Thank you. Maybe this can help a bit https://github.com/lerna/lerna/issues/789?
