### ISSUE TITLE
Negative margin works like positive margin

### ISSUE THREAD

**Issue by StelioBuono** [diegomura/react-pdf#760]
**Describe the bug**
When you set a negative margin, it acts as if you have set a positive margin.
It doesn't work for pourcentage, nor any other value it seems.

**To Reproduce**
REPL: https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a00d490600ee31a78a95144639a158f246030027553036698012075ec3c7271cbe131595401e85d34a983740cc3a98378045c22e8199959d80801b8c8c800c40365ec30f891a01cf0243800cc791890448400b86001c801e421f47844959a00683821ed809b9a002ca0a0001c201b83832a02e4f9a078a09181654119822182403aba958200dc0118019982013401f4005401a5b400d840003801d4418fe4015495ce8c1b80034009c3c002084364134ab34c8aa4cb64acd02319864381800195d1182c68c30182826d0aab0c394388a151342a9a498f0944a5b1f0ee2049935ce00567e9d2194cb01f00042e828081184d67b7238947a633990009103d890002f009743952ca2a879302b1406c767b0d3a5307d12094505188d4e00065b40148faa682520f8e31b7da9dba995f399234e73b34f21e30000d67c7b0801060250018440222548d0a3d0e0ea38fa961404d9a7365bad2d3b63a839c577ba7345af697288c1e3d98a601180169033e98087c391e8ec61349e34b5e42204061e1da84522c800250c286a05c1a0e40a2c25194a888543a0b0a124500

**Comment by diegomura** [comment]
Try defining the margin as an int `-5`. Apparently we have to fix something in the way we parse string units

**Comment by StelioBuono** [comment]
Thanks for the response.

It does work indeed but if you need to use percentage and all, you can't :/

**Comment by diegomura** [comment]
Yeah. Seems like we need a quick fix there! Thanks for raising this up. I'll keep this open until I have time to fix it
