### ISSUE TITLE
StyleSheet fails with error 'Unhandled Promise Rejection: Error: unsupported number: NaN'

### ISSUE THREAD

**Issue by sebboh** [diegomura/react-pdf#761]
**Describe the bug**
I'm trying to style a Text component with two properties: borderRadius and backgroundColor. When I try to apply both styles to the same component, I get an error when rendering the PDF: `Unhandled Promise Rejection: Error: unsupported number: NaN`. Each style works on its own, and it also works using styled-components.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
apply both styles to a component, for example:
```
  myStyles: {
    borderRadius: '4px',
    backgroundColor: '#22aa22'
  }
```
[Repl link](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231cc5009c9460b0094792a40823a8e9b2a5eb761d3883003b88058035841b96803d2ebe86bb8e9e818998a4a1b98f30305f058802181280308808906bbba73cba66766e41515040506878651514426c66bc7e8c218a525982b6704b29594c3c90cb33751b4c74d52d8e5e46128010880a0c04474cef00ac6b5d03332b3b0100371919282422699fae0032bf63c0058606142cb005860f261e0241c450a8005c3020668000e0e47180f8da10143c10066002b00069c230a51c2f8eb28140408c70400d931d8d8521e1000920920005ee0280f044a8b447154588f104bcf647339c190f2af26cfcdf38200e40016284a1259cee78d2a5925ad58a16214700090150caaa6a850d54a00c40026334f0781685650b9c0c9980b59a08845c6a2ef00a2052d97ca95945772bf5d53c91a82a6cb59b6d305519154172b8dda030458d456eb4dae10c4a59344a00003604aa434a002d2818d307365bad66e047b4b161f20a60be8e3f8904a282bdc10046335ca38ef241f15e503ec0e50647ce5cc8b63fb00a05c1a000c564bf65858f054442a1d0586d8268000)

**Expected behavior**
Both styles are applied to the component without error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome and safari
 - React-pdf version: 1.6.7

I've included in the REPL using styled-components, but I also get a React warning when using that package:
```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
```
so I was trying to move my styles into StyleSheet definitions to get rid of the warnings when I discovered this bug

From what I can tell, it is trying to parse the value of `borderRadius` as a number, because if I change the value to just a number the error goes away. However, the value needs to have units for the property to function

**Comment by diegomura** [comment]
It's probably because the `px` unit.  It's not allowed. Please check [supported units](https://react-pdf.org/styling#valid-units)
