### ISSUE TITLE
Example link for orphan and widow protection doesn't work

### ISSUE THREAD

**Issue by clintonblackmore** [diegomura/react-pdf#762]
**Describe the bug**
The advanced features page of the documentation has a broken link to an example of orphan and widow protection.

**To Reproduce**
1. Go to the advanced features page ( https://react-pdf.org/advanced )
2. Scroll down towards the bottom to see the "Orphan & widow protection" section
3. Click on the 'See it in action →" button.
4. You are taken to https://react-pdf.org/repl?example=undefined

I suspect that a real example page exists, and isn't linked properly.

**Expected behavior**
Clicking on the 'See it in action' button should take you to a REPL with example code for orphan and widow protection.

**Comment by diegomura** [comment]
Fixed https://github.com/diegomura/react-pdf-site/commit/dc8f64f5553c1f7eb201124534f83fab7dac8e36
