### ISSUE TITLE
Render props and styled components

### ISSUE THREAD

**Issue by web2wire** [diegomura/react-pdf#770]
**Describe the bug**
I am trying to implement a footer block that appears on all pages except for one.

To do this I am using the following form of JSX
```
// My nice styled semantic footer style
const FooterText = styled.Text`
  border-bottom: 1 solid #000;
`
...
      <View render={({ pageNumber }) => (
        pageNumber !== 2 && <FooterText>Not on Page 2</FooterText>
      )} fixed />

```

However this causes an error for some reason. I can embed the FooterText component directly in the View and it's fine but the render prop seems to object to styled component for some reason that I can't see documented anywhere. Actually it objects to any form of components other than the basic ReactPDF ones.

**To Reproduce**
This example works fine when the component is directly embedded https://is.gd/wNFwrn, this one crashes https://is.gd/IK3wJp when using a render prop.

**Expected behaviour**
I would expect styled components to work inside of a render prop function as they do everywhere else.

Any ideas? I'd hate to have to stop using components (styled or otherwise) as it makes it so much easier to apply conditional logic and to describe a document semantically without trying to work it out from the style props.

**Comment by diegomura** [comment]
I recommend staying away of the react-pdf styled-component in the future. It will no longer be maintained since the internal structure of newer version of styled-components changed entirely. Sorry about that
