### ISSUE TITLE
Wrapping continuous text in container

### ISSUE THREAD

**Issue by idrisadetunmbi** [diegomura/react-pdf#772]
This is not necessarily a bug, I was wondering if it is possible to wrap a continuous text (a link) with length beyond the container. 

```
<View style={{ width: 50 }}><Text>https://somewebsite.com/alongpaththatgrowsbeyond50pt</Text><View/>
```

**Comment by shunmian** [comment]
@idrisadetunmbi is there any reason you close this issue? I'm encountering the same issue.
