### ISSUE TITLE
Preventing other elements from crashing into a fixed footer

### ISSUE THREAD

**Issue by idrisadetunmbi** [diegomura/react-pdf#774]
I have a document that has a fixed footer on all pages, but elements before the footer sometimes crash or overlap into it. This is because such elements can only wrap when it is calculated that they can't make the rest of the page without the height of the footer being taken into consideration.

```
<Document>
    <Page size={{ height: 472 }}>
        <View height={410}></View> // element won't wrap because it's height is not up to the page and crashes into the absolutely fixed footer below
        <View height={72} style={{ position: 'absolute', bottom: 0, left: 0, right: 0 }}></View> // fixed footer
    </Page>
</Document>
```

I could use the `break` prop for such elements but there is no way to dynamically determine when to apply it.

Is there a way to prevent this from happening?

**Comment by idrisadetunmbi** [comment]
For anyone with a similar situation, I had to give the `Page` a padding-bottom higher than the height of the footer.

**Comment by DeepakKapiswe** [comment]
Thanks a lot @idrisadetunmbi , I was also struglling with same issue.

**Comment by corneliushka** [comment]
Thank you too ! Worked like a charm (just the absolutely positioned <View/> and managing the padding bottom to the <Page/> was enough).

**Comment by santig1399** [comment]
I have the same issue but the padding-bottom doesnt work for me. The elements before the fixed footer still remain overlaping. 
Is there another way to prevent this?

**Comment by MikeMcGarry** [comment]
@idrisadetunmbi, you do not want to know how many hours I just spent trying to get this work, I think you probably saved me half a day, thanks for taking the time to post this issue along with a resolution, really appreciate it! :)

**Comment by nullbytesoftware** [comment]
Setting padding bottom in my case distorts over parts in the page :/

**Comment by canimnazli** [comment]
thank you I struggled with the same issue as well, thanks alot

**Comment by moruno21** [comment]
I needed to add also a negative `marginBottom` to the footer to make it work. Just so you know. Thanks a lot!
