### ISSUE TITLE
Try to render valueOf as text

### ISSUE THREAD

**Issue by larissajusten** [diegomura/react-pdf#775]
**Description:**
The text "valueOf" calls a function even when it is inside a text tag <Text/>.
You can see the bug when you try to show the text valueOf on your pdf, the pdf don't render and shows a JSON.parse issue on console.

You can try it [here](https://react-pdf.org/repl). If you put the text valueOf inside double quotes it will show clearly "function valueOf() { [native code] }" inside the pdf.

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - React-pdf version v1.6.7

**Comment by diegomura** [comment]
I think that's just an issue on the REPL right?

**Comment by larissajusten** [comment]
No, that happend when I was using it on my code.
