### ISSUE TITLE
How to do font fallback?

### ISSUE THREAD

**Issue by SamJarmanPP** [diegomura/react-pdf#779]
I'd like to do something like 

`fontFamily: ['OurCustomFont',  'HelveticaNeue', 'Helvetica Neue', Helvetica', 'Segoe UI', 'Arial',' sans-serif']`

And so if theres not a font with that size/weight, it falls back to the next (as per CSS)?

How could one do this?

Also, if using node, how can one make sure HelveticaNeue is available? do I need to install the font on our servers/

**Comment by SamJarmanPP** [comment]
@diegomura Bump on this - we're wanting to use characters from any language in our PDFs.

**Comment by diegomura** [comment]
Keeping #933 for this feature. It's not supported yet but hopefully I'll find time soon to tackle it
