### ISSUE TITLE
React pdf-renderer does not display characters č, ć and đ

### ISSUE THREAD

**Issue by eugensunic** [diegomura/react-pdf#780]
I'm using @react-pdf/renderer latest version "1.6.8". However, am unable to get the following characters: **č, ć, and đ**. Instead, I get empty spaces or little tiny rectangles --> [].
 
Characters can be tested on  https://react-pdf.org/repl by using the following [Font](https://fonts.googleapis.com/css?family=Merriweather|Open+Sans&display=swap.ttf) which supports the aforementioned chars. 

Interestingly, other characters such as ž, š are displayed properly.

The characters are from the Croatian language.

Might someone know what to setup or how to approach the problem. Haven't found anything useful in terms of other configuration in the docs.

Also, posted the question on [StackOverflow](https://stackoverflow.com/questions/59200939/react-pdf-renderer-does-not-display-characters-%c4%8d-%c4%87-and-%c4%91)

**Comment by Artiikk** [comment]
did you find a solution for this?

**Comment by Artiikk** [comment]
Just imported custom fonts like this and it worked for me:
`import font from '/styles/localFonts/Poppins-Medium.ttf'
Font.register({ family: 'Poppins', src: font })`

**Comment by DeepakKapiswe** [comment]
Similar for me also it worked like that @Artiikk

**Comment by rbelOnline** [comment]
Registering a new font did not work for me.  Have you found a solution for this?

**Comment by DeepakKapiswe** [comment]
@rbelOnline I moved to use pdfmake and that works awesome without any hassle

**Comment by rbelOnline** [comment]
Thank you @DeepakKapiswe. I'll check that.
