### ISSUE TITLE
Question: Has anyone attempted docx output?

### ISSUE THREAD

**Issue by sugendran** [diegomura/react-pdf#782]
Has anyone given thought to outputting a docx as an alternate output option to the PDF? For the product I'm working on I need to produce a PDF and a DOCX. I'm happy to have a go at working out how to add it in, but wanted to check if anyone had thoughts on this already.

**Comment by diegomura** [comment]
There's another project for that: https://github.com/nitin42/redocx

I don't think react-pdf will support docx format in the near future
