### ISSUE TITLE
error: Could not resolve font for undefined, fontWeight 400

### ISSUE THREAD

**Issue by belhassen07** [diegomura/react-pdf#783]
**Describe the bug**
When loading a font from this link `https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf`
I got this error: ` error: Could not resolve font for undefined, fontWeight 400`

**code**
```javascript
Font.register({
  family: "oswald",
  src: `https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf`
});
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - React-pdf version  v1.6.8

**Comment by belhassen07** [comment]
I changed "oswald" to "Oswald" and it worked. the problem is I was puting it "Oswald" first and it didn't work. Somehow it works now.

**Comment by worapolburaphan** [comment]
> I changed "oswald" to "Oswald" and it worked. the problem is I was puting it "Oswald" first and it didn't work. Somehow it works now.

But I still see this error T_T

**Comment by belhassen07** [comment]
Can you share more details? I'll be happy to help you ? any snippets?

**Comment by khaphannm** [comment]
The same issue. Pls help me.
`import OpenSanSrc from 'assets/font/OpenSans-Regular.ttf';`
`Font.register({
    family: 'OpenSans',
    src: OpenSanSrc,
})`

Dont know why @@

**Comment by asalzillo-treedom** [comment]
I'm experiencing the same iusse

**Comment by patni11** [comment]
same issue

**Comment by manan023** [comment]
//While registering the font give the fontStyle "itlaic"
Font.register({
  family: 'Lato-Italic',
  src: `${Font_Base_Url}Lato/Lato-Italic.ttf`,
  fontStyle: 'italic',
});

//To use the font give font weight : 400
em: { fontFamily: 'Lato-Italic', fontWeight: 400 },

**Comment by Shubham-autviz3927** [comment]
I also got the same error with below code 

import NotoSansRegularSrc from '../assets/fonts/Noto_Sans/static/NotoSans-Regular.ttf';
import NotoSansBoldSrc from '../assets/fonts/Noto_Sans/static/NotoSans-Bold.ttf';

Font.register({
  family: "NotoSansRegular",
  src: NotoSansRegularSrc,
});
Font.register({
  family: "NotoSansBold",
  src: NotoSansBoldSrc,
}); 
// Define styles for your PDF
const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    padding: 30,
    fontFamily: "NotoSansRegular",
  },
  section: {
    margin: 10,
    padding: 10,
  },
  title: {
    fontSize: 24,
    marginBottom: 10,
  },
});

**Comment by thewh1teagle** [comment]
I see so many issues regarding this issue. can't we add debug logs into the library? verbose mode? It tries to load it from somewhere and fail. I can't know where it tries to load it from exactly

**Comment by ahmedlexroom** [comment]
I'm figured same issue

```
import montserratRegular from '../../public/fonts/Montserrat/static/Montserrat-Regular.ttf';

Font.register({
    family: 'MontserratRegular',
    src: montserratRegular
});
```

give me this error:
``` Error: Could not resolve font for MontserratRegular, fontWeight 400 ```
