### ISSUE TITLE
Why is the PDF Preview so tiny in the browser window?

### ISSUE THREAD

**Issue by mdodge-ecgrow** [diegomura/react-pdf#786]
I'm creating a basic react app generating a PDF in the browser and the preview box is super tiny.  It looks to be about 310px wide by about 160px tall.
![image](https://user-images.githubusercontent.com/57459547/70471115-3120c500-1a92-11ea-83de-6760dccef4da.png)

**Comment by mdodge-ecgrow** [comment]
Fount it!  For anyone looking for it:
`<PDFViewer width={800} height={600}>`

**Comment by DeepakKapiswe** [comment]
Thanks a lot, I was also facing same problem.

**Comment by Princinho** [comment]
You just saved me from countless hours of frustration 😂 Thank you so much
