### ISSUE TITLE
How to center a shape

### ISSUE THREAD

**Issue by mdodge-ecgrow** [diegomura/react-pdf#787]
I'm trying to figure out how to dynamically center a shape in my PDF.
I manually got it where I wanted it like this:
```
circle: { width: 400, height: 300, position: 'absolute', top: -120, left: 190 },

<Canvas paint={painter => painter .lineWidth(8) .ellipse(200, 200, 150, 70) .stroke('#000000') } style={styles.circle} />
```

But doing it that way seems extremely fragile.

**Comment by diegomura** [comment]
Inside Canvas you are the owner of all layout and drawing. And there the only way of defining where things should render is by discrete numerical values. So there's no other way than computing the `x` and `y` coordinates and render it as that
