### ISSUE TITLE
Text Align is  broken inside center-justified content

### ISSUE THREAD

**Issue by SamJarmanPP** [diegomura/react-pdf#789]
**Describe the bug**

**To Reproduce**
Repl

```
  <Document>
    <Page style={styles.body}>
      <View style={{flexDirection: 'row', justifyContent: 'center' }} >
          <Text debug style={{textAlign: 'center'}}>Hey This is some text</Text>
      </View>
    </Page>
  </Document>
```

**Expected behavior**
I expect the text to be totally centered in the page, centered align

**Screenshots**
![Screen Shot 2019-12-12 at 1 44 31 PM](https://user-images.githubusercontent.com/50305305/70672912-8dc7ee00-1ce5-11ea-9dca-8b87b25c7552.png)

**Desktop (please complete the following information):**
 - OS: macoS
 - Browser chrome
 - React-pdf version: whatever the repl is using

**Comment by heyalexchoi** [comment]
experiencing the same issue.

<img width="644" alt="Screen Shot 2020-10-20 at 5 23 38 PM" src="https://user-images.githubusercontent.com/4961047/96658317-0b428e80-12f9-11eb-97c4-6677134991a0.png">

```
const topBoxStyle = {
    position: 'absolute',
    left: 138,
    top: 30,
    width: 316,
    height: 107,
    borderStyle: 'solid',
    borderWidth: 1.3,
    borderColor: 'black',
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 30,
  }
  const titleStyle = {
    fontFamily: 'montserrat',
    fontWeight: 'bold',
    fontSize: 17.9,
    letterSpacing: 2,
    textTransform: 'uppercase',
    lineHeight: 1.2,
    textAlign: 'center',
  }
```

The 'Title' text element containing 'Dave Smith' is aligned to center of the box.
using `textAlign: 'center'` on the title text element pushes the text out to the right.

**Comment by goulkreek** [comment]
Hi
  Small note: Your workaround works well when text is smaller than its bounding box
  With bigger text (which implies text to be drawn on multiple  lines), unfortunately text is aligned on left (normal ;-)), and ‘textAlign: center’ is needed for text’s lines to be centered)
  any news on a possible bug fix ?

thx !
