### ISSUE TITLE
I want to output PDF in Japanese

### ISSUE THREAD

**Issue by musubi-muni** [diegomura/react-pdf#793]
I want to output Japanese to PDF using this download link.

> myComponent.jsx

```jsx
 const styles = StyleSheet.create({
    text: {
      fontFamily: "Nasu-Regular",
    }
  });
const MyDoc = () => (
  <Document>
    <Page>
     <Text style={styles.text} >日本語（Japanese）</Text>
    </Page>
  </Document>
)
<PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
   {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
</PDFDownloadLink>
```

> index.js

```js
Font.register(`${__dirname}fonts/Nasu-Regular.ttf`, {
  family: "Nasu-Regular"
});
```

Write the above code
and src / fonts/ font file was placed.

But I get an error.

> Unhandled Rejection (Error): Unknown font format

> Error: Unknown font format
>     at Object.push../node_modules/@react-pdf/fontkit/dist/fontkit.browser.es.js.fontkit$1.create (fontkit.browser.es.js:68)
>     at FontSource._callee2$ (font.js:35)
>     at tryCatch (runtime.js:45)
>     at Generator.invoke [as _invoke] (runtime.js:271)
>     at Generator.prototype.<computed> [as next] (runtime.js:97)
>     at asyncGeneratorStep (asyncToGenerator.js:3)
>     at _next (asyncToGenerator.js:25)
> 

How can I apply 1 Japanese font?

**Comment by fengnex** [comment]
@musubi-muni Have you solved the above problem you had mentioned before?
I wonder how to fix it as I want to display Chinese words but having the same problem.
Could you please share your idea or solution about it? Thanks.

**Comment by diegomura** [comment]
Check this https://github.com/diegomura/react-pdf/issues/633#issuecomment-537204496 . For non latin characters you will need to provide your own font (as you are doing above) but sometimes those are corrupted or malformed. The comment there explains how to solve it
