### ISSUE TITLE
Render Without Toolbar - WaterMark - PreventSelect/Copy.

### ISSUE THREAD

**Issue by josedager** [diegomura/react-pdf#794]
Hello,

I'm receiving a document dirname and filename from backend and want to know its possible to:

1. Hide the toolbar while a PDF is Render using PDFRender?.
2. Add a watermark using PDFRender?.
3. Disable select/copy text from rendered PDF using PDFRender?

Thanks in advanced.

**Comment by skarif2** [comment]
I also wanted to know if the toolbar can be hidden or if not then what do you guys think of implementing that feature?

**Comment by azat-io** [comment]
+1

**Comment by diegomura** [comment]
1. Toolbar does not depend on react-pdf, but rather the chrome or whatever browser you are using native PDF viewer. There's nothin this lib can do about it
2. You can do this with an absolute position `<Text />`
3. As 1, theres nothing I can do about that as well. I do not control how you interact with the document, react-pdf just creates it

**Comment by tiagohermano** [comment]
> 1. Toolbar does not depend on react-pdf, but rather the chrome or whatever browser you are using native PDF viewer. There's nothin this lib can do about it
> 2. You can do this with an absolute position `<Text />`
> 3. As 1, theres nothing I can do about that as well. I do not control how you interact with the document, react-pdf just creates it

About the watermark, what if the watermark were to be an image rather than simple text? am I missing something?

**Comment by diegomura** [comment]
It's exactly the same. Render an image in an absolute way. Give the opacity you want, etc

**Comment by tiagohermano** [comment]
For some reason, I haven't thought about it. It worked out, thanks
