### ISSUE TITLE
Without <PDFReader>, pdf fails to include any spacing as specified in the style sheet.

### ISSUE THREAD

**Issue by misaacs21** [diegomura/react-pdf#795]
Small (well, large right now) issue.

PDF outputs perfectly with formatting when Document is a child of <PDFReader>. However, if PDFReader is removed (for the appearance of a more natural web page, that will then have a download link at the bottom), and the PDFReader's container styling transferred to a <View> that occupies its same space in the hierarchy, there is no spacing at all! Text components (and all other components) will maintain their font and color styling, but none of the margins and padding. Why this discrepancy, and how would I work around this?

**Comment by diegomura** [comment]
By `PDFReader` you meant `PDFViewer` right? That always has to be there. Rendering a `<Document />` without it probably renders some random HTML
