### ISSUE TITLE
fontWeight doesn't work

### ISSUE THREAD

**Issue by yellowBanano** [diegomura/react-pdf#796]
**Describe the bug**
I tried to change the text style of a component with CSS property _**fontWeight**_.
Nothing has changed. 
Use https://react-pdf.org/repl?example=font-register to check the accuracy, but repl won't launch.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/repl?example=font-register
2. See error

**Expected behavior**
Expected to see how font become **bold**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Firefox 71.0
 - React-pdf version: 1.6.8

**Comment by cympak01** [comment]
@yellowBanano **_fontWeight_** won't apply if your didn't register proper font. Code below did the work:
`Font.register({
            family: 'Open Sans',
            fonts: [
                { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-regular.ttf' },
                { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-600.ttf', fontWeight: 600 }
            ]
        });`

**Comment by juby-gif** [comment]
+1

**Comment by bartmika** [comment]
+1

**Comment by mnowotnik** [comment]
+1, Still doesn't work in ` 2.0.0-beta.18`

**Comment by eyeamkd** [comment]
i'm using the latest version and still facing this issue

**Comment by diegomura** [comment]
Fixed in latest commits!

**Comment by ljmerza** [comment]
this doesnt work even with the default fonts built in. are you saying i have to import all the bold fonts even for the default fonts built in?

**Comment by Ahmad495** [comment]
This issue is still unresolved on the latest version.

**Comment by casestudy** [comment]
Any solution just yet? Still have the issue.

**Comment by kiliancabrera** [comment]
any solution?

**Comment by mjbour** [comment]
any solution?

**Comment by chea-young** [comment]
If you want to use 'Bold', 'Black' and so on, you have to register all of types of font

reference: https://snyk.io/advisor/npm-package/@react-pdf/renderer/functions/@react-pdf%2Frenderer.Font.register

**Comment by Ahmad495** [comment]
This is a work around that got font size working for me

**Comment by ua-knight** [comment]
I had the same issue. Thanks to all who commented. Following advices above, this was what worked for me:

First, run the register code somewhere central in the app. 

  ```
Font.register({
    family: 'Open Sans',
    fonts: [
      { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-regular.ttf' },
      { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-600.ttf', fontWeight: 600 }
    ]
  })
```

And then add the font family where font weight is used in the document pdf.

```
const styles = StyleSheet.create({
    title: { fontFamily: 'Open Sans', fontSize: 20, fontWeight: 600 }, // doesn't work without fontFamily
})

```

**Comment by sebastianfdz** [comment]
Like @ua-knight said above:

**IT DOESN'T WORK** if 'fontFamily' is not specified inside style tag.

Took me a while too.

**Comment by ahmedibra28** [comment]
> I had the same issue. Thanks to all who commented. Following advices above, this was what worked for me:
> 
> First, run the register code somewhere central in the app.
> 
> ```
> Font.register({
>   family: 'Open Sans',
>   fonts: [
>     { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-regular.ttf' },
>     { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-600.ttf', fontWeight: 600 }
>   ]
> })
> ```
> 
> And then add the font family where font weight is used in the document pdf.
> 
> ```
> const styles = StyleSheet.create({
>     title: { fontFamily: 'Open Sans', fontSize: 20, fontWeight: 600 }, // doesn't work without fontFamily
> })
> ```

It worked. 
Thank you.

**Comment by sychd** [comment]
You can use the default fonts provided by the library without needing to register another font if they fit your needs. The default fonts are listed here: https://react-pdf.org/fonts

For example:
```
<Text style={{ fontFamily: 'Helvetica-Bold' }}>
    Welcome
</Text>
```

**Comment by Umesh-Bhati** [comment]
> You can use the default fonts provided by the library without needing to register another font if they fit your needs. The default fonts are listed here: https://react-pdf.org/fonts
> 
> For example:
> 
> ```
> <Text style={{ fontFamily: 'Helvetica-Bold' }}>
>     Welcome
> </Text>
> ```

not working for me
My project is using next 14.1.4

**Comment by Umesh-Bhati** [comment]
someone find another solution because all the above-suggested solutions are not working yet 

My project uses Nextjs 14.1.1 with Shadcn UI that uses remix UI

**Comment by paystrup** [comment]
+1

**Comment by chetansgit** [comment]
It was working before in version 14.0.3, but when I updated to the next version, it stopped working again. Even after reverting to the previous version, it still doesn't work

**Comment by tgram-3D** [comment]
Same deal here. Worked in 3.1.14 but not working in 3.4.4.

**Comment by Psarada84** [comment]
Same here.. I had to revert react-pdf/renderer to 3.2.2 from 3.4.4.

**Comment by rodericktech** [comment]
@Psarada84 Which version did you revert to?  (Looks like 3.2.2 is not a release) - Hoping it might be a solution for me because I have tried versions from 3.1.2 up - on vanilla React 18.3 - and none of those I've tried so far have worked for me even with the 'Helvetica-Bold' built-in example shown above.

**Comment by rodericktech** [comment]
Never mind the above - I found a solution for this (using the default fonts at least) here - https://github.com/diegomura/react-pdf/issues/2750 - putting an an override to revert `@react-pdf/layout` to `3.11.5`.  This works at least as far up as version `3.4.2` of the renderer for me.

**Comment by stevec01** [comment]
HI I have tried all of the above and i cannot have a single word in bold within a sentence. Any Ideas, thanks

**Comment by JacobWeisenburger** [comment]
Has this been solved? Because I can't seem to figure out how to make some text bold.

**Comment by MustehsanGhouri** [comment]
### Working Solution for Text Alignment and Wrapping in `@react-pdf/renderer`

This approach works effectively, allowing you to nest `View` components and manage text styles, alignment, and wrapping.

```jsx
import React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";

const ExampleComponent = () => {
  const styles = StyleSheet.create({
    container: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center", // Aligns text vertically in the center
    },
    text: {
      margin: 6, // Handles spacing between words
      fontSize: 14,
      textAlign: "justify",
      color: "#000000",
      fontWeight: "normal",
      marginLeft: -3, // Adjust margin to align text correctly
    },
    textBold: {
      margin: 6, // Handles spacing between words
      fontSize: 14,
      textAlign: "justify",
      color: "#000000",
      fontWeight: "bold",
    },
  });

  return (
    <View style={styles.container}>
      <Text style={styles.text}>Hello</Text>
      <Text style={styles.textBold}>World</Text>
      <Text style={styles.text}>. Again, I am not bold, WOW</Text>
    </View>
  );
};

export default ExampleComponent;

**Comment by MustehsanGhouri** [comment]
![issue](https://github.com/user-attachments/assets/272fb827-2c01-4c9a-84ce-bcfedddcb36c)

**Comment by ivanbicalho** [comment]
After checking multiple threads here the only way it worked for me was overriding the `react-pdf/layout` + using `Times-Bold`:

```
"dependencies": {
    "@react-pdf/renderer": "^3.4.4",
    ....
}
```

```
"overrides": {
    "@react-pdf/layout": "3.11.5"
}
```

```
const styles = StyleSheet.create({
    bold: {
      fontFamily: "Times-Bold",
    },
    ....
```

**Comment by chaudharykapil** [comment]
![image](https://github.com/user-attachments/assets/c809ef7a-4b4e-43a2-8775-001d8c93bd7e)
I have Tried this but not working in my case 
does anyone have solution ?

> companyParaHTML

**Comment by rats4final** [comment]
> `Font.register({`
> `family: 'Open Sans',`
> `fonts: [`
> `{ src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-regular.ttf' },`
> `{ src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-600.ttf', fontWeight: 600 }`
> `]`
> `});`

Ironically this worked, I can't freaking believe it, goddamn library

**Comment by rats4final** [comment]
> You can use the default fonts provided by the library without needing to register another font if they fit your needs. The default fonts are listed here: https://react-pdf.org/fonts
> 
> For example:
> 
> ```
> <Text style={{ fontFamily: 'Helvetica-Bold' }}>
>     Welcome
> </Text>
> ```

Ironically this worked, I can't freaking believe it, goddamn library

**Comment by bakiwebdev** [comment]
I stumbled on this issue, and to fix it, I used another font family the package provided (Helvetica-Bold),
note: there are limited font family, and if you want to add a different font family, you should also provide the source as they showed in their doc
![image](https://github.com/user-attachments/assets/2a13f7ad-b4bf-4166-b323-229f9b7b570b)
![image](https://github.com/user-attachments/assets/d5be0c8c-f3c7-4fa5-b5fa-119cc2fe05e2)

**Comment by maheshpaulj** [comment]
> You can use the default fonts provided by the library without needing to register another font if they fit your needs. The default fonts are listed here: https://react-pdf.org/fonts
> 
> For example:
> 
> ```
> <Text style={{ fontFamily: 'Helvetica-Bold' }}>
>     Welcome
> </Text>
> ```

This is what i have been looking for, THANK YOUUU!!

**Comment by VariabileAleatoria** [comment]
why is this issue closed

**Comment by rats4final** [comment]
@VariabileAleatoria Yeah it should be more explicitly said but i think because fontWeight isn't supported but rather you have to use a font family that is Bold
