### ISSUE TITLE
How to create a bunch of PDF's in a loop and print

### ISSUE THREAD

**Issue by mdodge-ecgrow** [diegomura/react-pdf#798]
So I have successfully shown my rendered PDF in my modal, looks like this:
![image](https://user-images.githubusercontent.com/57459547/71205472-1c99b500-2268-11ea-8db5-cd4103dbc5f8.png)

Now, I want the user to input a number say 100 into the text box, and click print.  Then it needs to loop through that number of times and create 2 identical PDF's for each loop each time incrementing the pallet number.  So if 100 is input, 200 PDF's would be generated.  Then that needs to be sent to their printer, or maybe just pop up the browser print panel so they can select their Printer.  I just realized I can't have the user enter 100 as a quantity into the browser print panel because it will print 100(or 200) of the same PDF's because it has no way to increment that number.  So it seems like I will have to dynamically create a 200 page PDF file and have the browser print that.  From my reading, it appears I should be using the BlobProvider component.  However, there are very little details in the docs about how to use that.

**Comment by mdodge-ecgrow** [comment]
I think I've gotten the looping part figured out.  I will create a new question with the print part.

**Comment by rantibi** [comment]
@mdodge-ecgrow can you please share how you solved it?
