### ISSUE TITLE
I'm trying to get Korean font to work in react-pdf

### ISSUE THREAD

**Issue by yokomi** [diegomura/react-pdf#806]
Can someone please help me either change 
https://fonts.google.com/?subset=korean&selection.family=Noto+Sans+KR 
to a workable ttf? I have the ttf file but didn't work and gave me an error i downloaded bird font and tried to export from there but it wouldn't let me.  It'll be a really nice feature if we can use google font urls directly

**Comment by seonghyeonkimm** [comment]
@yokomi Did you mean that only google font url is not working in react-pdf? Or, you mean that you can register Korean alphabet in react-dfk? I am having issues to load Korean character here if you solved the issue, could you share the solution with me?

**Comment by DeepakKapiswe** [comment]
https://github.com/diegomura/react-pdf/issues/807#issuecomment-577136660

This helped me to tackle the issue for Indian Fonts

**Comment by Penny-Cho** [comment]
I have tried Korean as following and it is working.

`
Font.register({
    family: "Nanum Gothic",
    src:
        "https://fonts.gstatic.com/ea/nanumgothic/v5/NanumGothic-ExtraBold.ttf",
});

`

**Comment by diegomura** [comment]
Should work fine. [Check this example](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a70e9aa80150c29634f152a288c73321f5640242dc012a381551b006aae00e41c02963f803488004e183c6004da9c5400f4fa861a9a30a111bc023111740cccacec0400dc64640062e050b2017c48d0187e78123000663c8c482242005c3000440072414c3000e2e8001648c06d003430107ec0ad6d035050000e10cde1e13585727cd03c50c3b2a08ce181e160dd8c7c83c3e1006e00ace15d604cfd5043c000b400a2867e3c0042201112964f31a98c60aa6cae540902319864381800195e1182440c301822b00023b0c154388a152b424a1058f0944a24180f8ba1002d5a00665ba8cc914aa4d201f3102315a0036165b329d4be00025fc480017a1478222660b28aa56470ac5012685183c3f294c0ad002300099599a75ab091528c3ea002cc6ce2aa008222241f175300039000ac10d0240d4846edb6514d503cbd51a2d7763c7a2f379ba384a8a1912139320009502c0281706879628b094153c15110a874161c2c428500000)

**Comment by taj567** [comment]
for hindi any idea

**Comment by nedngo** [comment]
> I have tried Korean as following and it is working.
> 
> `Font.register({ family: "Nanum Gothic", src: "https://fonts.gstatic.com/ea/nanumgothic/v5/NanumGothic-ExtraBold.ttf", });`
> 
> It seems ttf type only works and it doesn't support otf type. I have tried Noto Sans KR(which only supports otf and woff) with url of //fonts.gstatic.com/ea/notosanskr/v2/NotoSansKR-Bold.otf, it didn't work.

It's working!
