### ISSUE TITLE
Multiple text decoration values produce no text decorations

### ISSUE THREAD

**Issue by SamJarmanPP** [diegomura/react-pdf#809]
**Describe the bug**
In CSS, its valid to use `text-decoration: underline line-through` however, when using the equivalent in ReactPDF, neither are rendered.

**To Reproduce**
```
const Test = () => (
  <Document>
    <Page style={styles.body}>
      <Text style={{textDecoration: 'underline line-through'}}>
        Created with react-pdf
      </Text>
   
    </Page>
  </Document>
);
```
[Example in Repl](https://react-pdf.org/repl?code=3187b0760ce02e00402a05368c0bc30050129503e0c0a061801e0044460057016c130a1d0a24801404301cc119a013c01b04280379f411001d002310004d7805f46cd9b144003d618a1c3854049b48250009cd940096e00170c00e494c2c8427f85b0dcdc780b450005898825071f9d8292930a910030898239822c8c003b85bf8c1c5b3014378003ac8019a46a803d0683247171097b1732890979152d3d232600373e3e0018b814049c4705b40bba3093015b3505bf2f2d9d803c84325b3f2c9d800d130409b03cdf94142e44358949415f6487343985b004a8350944094832eaec89401b80230033094009a007d38001a4006a0036100003800ea202f94800aab23fb5181000d00271b00082f88921c0a767c0283a5d50240b45001121503000329d3044cbf02010fd60265f463260c9e4b6718a9726c592c9dc1c3808172b63f80158b6a2f164ac01c00108810e206a2d8a14ae298a255280048804c1600179f556f2c351014ca98258a082617142ef42675a10b60013000599d447d269f16e0e181e6c03a3e84c9b4f5f5ba53199cdec4b159acc98ee75b128fe0b47a545ea80faad7e980fdfd2197418a0118b14663719722654d43609886602d4eaf53040c00199d4eeda50a4aef74c045cc52f972b3f586d73bddf72d9abb5d2ca7a6b379a663e399818f43f5e2f31573d8dcd693dedf46f83c530c3723d1fb000ad28d00b01578edb9f26a99eef61c0162d0103780012aea6c1804789e301819c256b391097bb8108b896300769560e85e5d8f6e6a5a36bd0b84fc4388e4c0211cb8a2e39e443cef795637876847b87d940ba806544a8cfa36cdbd8b1bd06dad6a03f045bd81c1c47fa8ece98a5c0007234148f44ce469bc691586f9d86c14810080fc016083fe8c5f40bb5eb58c8fdbcabc73082014502d876510968844e4c02e5d6e1abe2d889099898664976349082c9d456c14a74f8241f13642c290dd00c74338263a06a120b009438252400000)

**Expected behavior**
Both an underline and a line through the text

**Screenshots**
![Screen Shot 2020-01-07 at 1 08 24 PM](https://user-images.githubusercontent.com/50305305/71858098-d0e37880-314e-11ea-8d12-a1efbfa6f00b.png)

**Comment by SamJarmanPP** [comment]
Any work arounds or dependencies I can bump perhaps @diegomura?

**Comment by diegomura** [comment]
Will try to add support for multiple text decoration values soon

**Comment by aaronjedwards** [comment]
I've created a PR (#1404) with an implementation for this. It was fairly straightforward and its all working! @diegomura I know you said you were going to try and add support for this soon, could you take a look at the PR and let me know what you think?

**Comment by d3p4n5hu** [comment]
I'm still facing this issue, specifically in the browser. I saw the PR and it added the fix for multiple `textDecoration` but this fix is not present in `react-pdf.browser.cjs.js`.

<img width="732" alt="Screenshot 2023-06-22 at 6 45 53 PM" src="https://github.com/diegomura/react-pdf/assets/16369510/3d1aa382-3892-4dfc-a8ae-ed747d53adc8">
