### ISSUE TITLE
Issue opening generated PDF

### ISSUE THREAD

**Issue by FilipeOS** [diegomura/react-pdf#814]
Hi guys,

So I picked a project from a old dev and I just picked up the project on Android Studio, installed npm and pdf render dependencies but when I try to download PDF I save and when I open it's corrupted.

Can you please give me some light of some required dependencies that must be added? Because if the old code was working then the new should work after `npm run build` .

He only provided me the "public" and "src" folder with some files outside that folders (like package-lock.json etc ) 

Thank you so much

**Comment by diegomura** [comment]
Never saw a corrupted document rendered by this lib 😕  Can you share the resulting doc here?
