### ISSUE TITLE
Really high chunk size when adding `react-pdf` 

### ISSUE THREAD

**Issue by drydenwilliams** [diegomura/react-pdf#818]
**Describe the bug**
As soon as I've added `react-pdf` to my project it's bloated my chuck size massively: 

Before
```
102.37 KB (-667.72 KB) build/static/js/2.9b34ee04.chunk.js
 20.1 KB (-3.62 KB)   build/static/js/main.5d3d3dd0.chunk.js
 847 B          build/static/js/runtime-main.ccd78b3d.js
```

After adding `react-pdf`
```
770.09 KB (+18.81 KB) build/static/js/2.5738880b.chunk.js
 23.72 KB (+414 B)   build/static/js/main.515c8243.chunk.js
 847 B (+65 B)     build/static/js/runtime-main.ccd78b3d.js
```

Just wondered if anyone had any ideas of what to do?

**Comment by stevecastaneda** [comment]
I was looking at this today, here's what I'm seeing using source-map-explorer.

![image](https://user-images.githubusercontent.com/171488/88010917-a1d59880-cadb-11ea-85bc-daa2228f23f8.png)

**Comment by diegomura** [comment]
Yes. Unfortunately this project relies on heavy dependencies that we currently cannot bypass. I'm aware this is an issue and it's in my mind constantly but still don'st know/have enough time to find ways of making it smaller

**Comment by stevecastaneda** [comment]
@diegomura I appreciate all the work you've done so far.  👊
