### ISSUE TITLE
ReactPDF.PDFViewer not working on IE 11

### ISSUE THREAD

**Issue by mayuresh-sawant** [diegomura/react-pdf#822]
I am able to download the pdf successfully on IE, Chrome & Firefox but not able to render the pdf with PDF Viewer on IE browser.

It fails to render with following error message on console:-

Invalid argument 'url'. Failed to revoke Blob URL: 'null'

This is my iFrame :

<iframe width="100%" height="100%" src="blob:0D787F19-0028-4A60-B617-A7EA81AAD94C"></iframe>

Versions:
React - 16.8
Webpack - 4.41

**Comment by dedysimamora** [comment]
hai @mayuresh-sawant you say you able to download pdf succesfully on ie, can i ask you how you to do that? becauase i try using "BlobProvider" and "PdfDwonloadLink" from react-pdf and always failed when i run code on ie, (SCRIPT5022: Objects are not valid as a React child bla bla  bla)

**Comment by mayuresh-sawant** [comment]
Pdf download link needs a document object to download pdf.

Below is my code:- 
 
<PDFDownloadLink document={document} fileName={fileName}>
                        <Button type="button" variant="primary" label="Download PDF" /> </PDFDownloadLink>

**Comment by dedysimamora** [comment]
@mayuresh-sawant i already do that actualy, but still got error, here is my code 👍 


app.js:
`import React from 'react';
import logo from './logo.svg';
import { PDFDownloadLink } from '@react-pdf/renderer'
import Document from "../src/components/Document"
import './App.css';

function App() {
  return (
    <div>
        <PDFDownloadLink  document={< Document />} fileName={"fileName"}>
          <button type="button" variant="primary" label="Download PDF" />
       </PDFDownloadLink>
    </div>
  );
}

export default App;`

Document.js (pdf template)
`import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: '#E4E4E4'
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1
  }
});


const  MyDocument = () => {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
            <View style={styles.section}>
                <Text>Section #1</Text>
            </View>
            <View style={styles.section}>
                <Text>Section #2</Text>
            </View>
            </Page>
        </Document>
    )
}

export default MyDocument
`

but still got error like this when i run it on ie version 11.1039

![error ie](https://user-images.githubusercontent.com/48207242/74710452-49f8e400-5254-11ea-8d87-bf0b248de076.PNG)

liblary version : 

"@react-pdf/renderer": "^1.6.8",
 "react": "^16.10.2",
 "react-app-polyfill": "^1.0.6",
"react-dom": "^16.10.2",
 "react-scripts": "3.2.0",
"babel-loader": "8.0.6",
 "babel-plugin-import": "^1.12.1",
 "babel-polyfill": "^6.26.0",
"babel-preset-react-app": "^7.0.0"

can i see how you create pdf tempalte (document) as props to PDFDownloadLink ?

**Comment by rodsjo** [comment]
I have the exapct same problem as @dedysimamora. Please, anyone, help us out. I need react-pdf to work in IE11

**Comment by darshanapatil** [comment]
I have the same problem. Is there any solution for this?

**Comment by diegomura** [comment]
Duplicated  #413. Please share all the relevant information there. I'll try to see this. You have to understand that IE 11 support is hard in some occasions
