### ISSUE TITLE
Failed to set an indexed property on 'CSSStyleDeclaration'

### ISSUE THREAD

**Issue by worapolburaphan** [diegomura/react-pdf#825]
**Describe the bug**
I use styled-component of react-pdf and I get this error message
```
Failed to set an indexed property on 'CSSStyleDeclaration'
```
**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to 'Document Component' That use styled components
2. See error

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**
styled should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/12433101/74601296-29ebe800-50cf-11ea-8fb4-92b953cf2444.png)
![image](https://user-images.githubusercontent.com/12433101/74601331-9961d780-50cf-11ea-9537-a6617ab30a0b.png)
![image](https://user-images.githubusercontent.com/12433101/74601322-759e9180-50cf-11ea-90c5-51c2afe79d59.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Microsoft Edge (Chromium version)
 - "@react-pdf/styled-components": "^1.4.0"
- "@react-pdf/renderer": "^1.6.8"

**Comment by EmperorPeter3** [comment]
same issue

**Comment by diegomura** [comment]
I recommend staying away of the react-pdf styled-component in the future. It will no longer be maintained since the internal structure of newer version of styled-components changed entirely. Sorry about that

**Comment by kingRayhan** [comment]
Any update? I am still facing this issue. Any workaround?
