### ISSUE TITLE
Broken link generation

### ISSUE THREAD

**Issue by sapristi** [diegomura/react-pdf#826]
**Describe the bug**

From version 1.6.8, link generation is broken when raw text is given as a child to a Link element: 
`<Link src='...'> click me </Link>`.

Link generation is fine when the Link is given a Text child: `<Link src='...'> <Text>click me</Text> </Link>`, so maybe that's not completely a bug, but at least a bug prone behaviour (that did not seem to happen in version 1.6.7).

`<Link src='...'> click me </Link>` in a page will create two links in the document: 

 * the first one is rightly placed, and always an external link (even if a goto was specified)
 * the second one is ill placed, but contains the right information

(The second link is not directly visible, since there is no text underneath it. You can see it opening the document with MasterPDFEditor e.g.)

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

With React-PDF 1.6.8, generate the following document:
```
const MyDoc = () => (
  <Document>
    <Page>
      <Link src='https://react-pdf.org/repl'>Click me</Link>
    </Page>
  </Document>
);
```

**Expected behavior**
Either correct link generation, or a warning.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser firefox, chrome
 - React-pdf version 1.6.8

**Comment by diegomura** [comment]
Fixed in the last 1.X and 2.0 version. Thanks!
