### ISSUE TITLE
How to apply a linear gradient on canvas

### ISSUE THREAD

**Issue by Bart0810** [diegomura/react-pdf#828]
`<Canvas
        paint={painter =>
          painter
            .path('M0,0L0,300L300,300Z')
            .linearGradient(1027.1464, 926.855, 1790.4744, 662.7968)
            .stop(0, 'green')
            .stop(1, 'red')
        }
        style={styles.square}
      />`

![Schermafbeelding 2020-02-20 om 13 12 10](https://user-images.githubusercontent.com/15311072/74932691-b73a7f80-53e2-11ea-9d71-af0ca728f2b1.png)

**Comment by Xcellion** [comment]
Did you ever figure this out? I am getting the same issue, says stop is not a function.

**Comment by Xcellion** [comment]
I tried to add the "stop" function under availableMethods to the [painter.js](https://github.com/diegomura/react-pdf/blob/1bc45ae3da2740eb008df8b1486454cd0753fe65/src/utils/painter.js) file that @markusjohnsson wrote hoping that that would automatically work, but it didn't seem to do the trick.

**Comment by Xcellion** [comment]
Okay I figured it out--or I hacked together a way to get gradient working. It might go against @markusjohnsson 's wish to keep everything wrapped and unexposed, but without the .stop() function, the .linearGradient() function didn't work anyway.

Add the following to line 48 on the [painter.js](https://github.com/diegomura/react-pdf/blob/1bc45ae3da2740eb008df8b1486454cd0753fe65/src/utils/painter.js) file.

```  p.linearGradient = (...args) => {return instance.linearGradient(...args)};```

**Comment by amrfhn** [comment]
Any updates on this from the owner, instead using hack method?

**Comment by markusjohnsson** [comment]
@amrfhn @Xcellion you could always create a pull request based on that "hack". Since I'm no longer using react-pdf in my projects I recuse myself from discussion.

**Comment by diegomura** [comment]
Fixed [here](https://github.com/diegomura/react-pdf/commit/fbd97fbea9144c41cce9278f6d13411b34c5137e). Thank you!

**Comment by rhysflook** [comment]
I am having this same issue with .stop() in the latest version.
