### ISSUE TITLE
How to run examples

### ISSUE THREAD

**Issue by shravya95** [diegomura/react-pdf#83]
Hey i have cloned your repo locally..can u plz help me in running the examples..because the example mention **yarn example -- fractals** doesn't seem to work.And the sub-folders have their own package.json do we have to install them explicitly?
Thanks.

**Comment by diegomura** [comment]
Hi @shravya95 !
You don't have to install each package separately.

Try running `yarn install` in the root of the project, and then run the test. That should work.

The project has a `postinstall` script that runs `lerna bootstrap`. What that command does is installing each package dependencies, and linking them together.

**Comment by steric85** [comment]
Hey @diegomura ,
I tried running `yarn install` in the root of the project. I am getting the following error:

`yarn install v0.24.6`
`[1/4] 🔍  Resolving packages... `
`[2/4] 🚚  Fetching packages... `
`[3/4] 🔗  Linking dependencies...`
`[4/4] 📃  Building fresh packages...`
`$ lerna bootstrap`
`Lerna v2.0.0-rc.3`
`This is not a git repository, did you already run git init or lerna init ?`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

How shall I proceed?

**Comment by diegomura** [comment]
Are you sure you are running `yarn install` in the root of the project? That's odd...
Can you give me more info of your environment? such as node version, OS, etc

**Comment by steric85** [comment]
Yes, I am running the command in the root folder. 

Environment Information:
node version : 6.10.3
npm version : 4.2.0
OS : macOS Sierra (10.12.5)
What other details are required?

**Comment by diegomura** [comment]
It seems that or you have an issue with your git installation, or somehow your clone version of the project it's not a git repository. 

Fails here: https://github.com/lerna/lerna/blob/36a6501fcd5856e8b6291b71fa251c53aa939a33/src/Command.js#L182

Check if the `.git` folder is in the repo, or check your git installation.

**Comment by steric85** [comment]
Thanks a lot! 😄 
I had downloaded instead of cloning the repository. 
I tried `yarn install` and `yarn example -- fractals` after cloning the repository. The code is running successfully without any errors!

**Comment by jbovenschen** [comment]
Great, thanks for your explanation.
Will close this issue for now.
