### ISSUE TITLE
Cannot send prop from axios get request

### ISSUE THREAD

**Issue by Lartum** [diegomura/react-pdf#831]
I am facing an issue while trying to pass an Axios response object as a property to the pdf when i try to console.log the prop data in return it shows this error in my browser console

`Uncaught (in promise) TypeError: Cannot read property 'size' of undefined`

and also the object is called multiple times, even though i didnt do any loop.

**Comment by diegomura** [comment]
I'll need more info than that

**Comment by Lartum** [comment]
Sorry, I think it was a problem with re rendering, set up conditional rendering to fix it.
