### ISSUE TITLE
Cannot Render images stored in Firebase (Google Cloud)

### ISSUE THREAD

**Issue by BrennonG** [diegomura/react-pdf#835]
Trying to pull an image into my PDF. I'm seeing "Not a valid image extension" in the console. Saw that this issue was fixed for Google Cloud Storage here #213, but still can't pull images in for the Firebase portion of Google Cloud. Here's the URL structure fo and image I'm trying to pull in:

https://firebasestorage.googleapis.com/v0/b/new-theory-7c978.appspot.com/o/NewTheory%2Fimages%2Ftranscription2.svg?alt=media&token=17afd1e8-1327-47d5-b866-09948c06aa1c

**Comment by geerthoekzema** [comment]
I'm not sure if this helps, but the image you are trying to render is an SVG. SVG images cannot be rendered inside react PDF.

**Comment by BrennonG** [comment]
Thanks @geerthoekzema. Oversight on my part. Thanks for catching that for me.
