### ISSUE TITLE
React pdf does not understand 'transparent' background color

### ISSUE THREAD

**Issue by brandonryan** [diegomura/react-pdf#838]
**Describe the bug**
Transparent background color displays as black

**To Reproduce**
Render the following
```jsx
<Text style={{backgroundColor: 'transparent'}}>
lorem ipsum
</Text>
```
(repl wont let me share link because its too long)

**Expected behavior**
Text element should be rendered with an rgba value of rbga(0,0,0,0)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - React-pdf (renderer) 1.6.8

**Comment by geerthoekzema** [comment]
I was able to reproduce your issue, strangly it dissapeared when the "lorem ipsum" was on the same line as the opening from <Text> or when i added a tabs before the Lorem Ipsum.

That fixed the 'issue' , [see repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a005430a58d3c54a8a231c8016187928c009d54c0066a83128d9b3803f1801856d5cc25180077242873187f1e6028005a00072547184f0e4d2a007a5d7d7774ec83133149006d43392830b1001a18097968806b3e5b100430251f1011105b002e180072285b1e48789e7f5601d5005d753a307864002b742c1b18111e18005951e0731e4cfcdcad7c984312b2d90aa86adafae02696b68eae9efea191b189962869b9b10164b242ad30300d96d76fb43b1cf46c3499de117429194aa8f2a5430353aa359aad76a75ba7d41ad8f8f53c00018aad4da410063059ba98918460c090f108130e13944665780277264e80c662b1d8040037190c800317014164fe3e121a0763c048388e1e23090222127c00f210608f0444a0195438105b3013ee62814139bd0c8651c0ab91f1a03c0ab0164a04606420191009acd4a0c800dc008c00660c8013400fada0034800d4006c200007001d44091f90015494b1c6126001a004e1e00104eb372823806645514a65a0480154c101c0c000caa881e58308ae0145301a8e22854fd4d669c64a25120c07c6d081e2fd58c0158ad8beb0aed7002174140408c7ea66f788a5d1ef800091e920005e0ab376e6f9a47b3c096f6267ce7a303e88096870aa3ee302dc623ce88bbaac00eaf860fd0004c000b24194260fa1d6221207c1809f3007f1d860668f0540b28ea7a81a8331aa6b9a64632904f0083841f2d47042a884bec84c0d18a198541f0ae1f861183311ac2914270164aaea7a3a17bf468752e05b61d990001295831170342ca4a8b0362d878150882a06b0c0193101d9000000)

**Comment by TayyabSalman** [comment]
Hey @geerthoekzema can you please elaborate that why am I not getting a transparent border in my case. Here is the code:

```
      <View style={{	borderTop: "50 solid red",
                        borderRight: "100 solid rgba(255, 0, 0, .5)",
                        height: 0,
                        width: 5,}}></View>
```

This code is working fine in case of normal css.

**Comment by mikey0000** [comment]
Having the same issue with computedStyles that apply transparency

`const styles = StyleSheet.create({
  body: {
    padding: 35,
  },
  content: {
    padding: 20,
    '@media max-width: 400': {
      flexDirection: 'column',
    },
    '@media min-width: 400': {
      flexDirection: 'row',
    },
  },
  block: {
    height: 150,
    width: "250px",
    backgroundColor: 'red',
    flexDirection:"row",
  },
});

const MediaComponent = () => (
  <View style={styles.content}>
    <View style={[styles.block,  { backgroundColor: 'rgba(0,0,0,0)', color: 'rgba(0,0,0,0)' }]} >
    <Text style={{backgroundColor: 'rgba(55,55,55)', textDecorationColor: 'rgba(0,0,0,0)'}}>Hello world</Text>
      <Text style={{backgroundColor: 'rgba(55,55,55)', color: 'rgb(255,255,0)'}}>Hello world</Text>
    </View>
    <View style={[styles.block, { backgroundColor: 'green' }]} />
  </View>
);

const doc = (
  <Document>
    <Page style={styles.body} size={[500, 600]}>
      <MediaComponent />
    </Page>
    <Page style={styles.body} size={[300, 600]}>
      <MediaComponent />
    </Page>
  </Document>
);

ReactPDF.render(doc);
`
