### ISSUE TITLE
render is not a function

### ISSUE THREAD

**Issue by phoenixTW** [diegomura/react-pdf#841]
**Describe the bug**
I am facing issue when I am trying to use `ReactPDF.render()`. It says it is not a function.
<img width="929" alt="Screenshot 2020-03-10 at 1 14 03 PM" src="https://user-images.githubusercontent.com/10116103/76290321-0b919a80-62d1-11ea-8bc9-803fa51265e9.png">

**Code**
```
    const MyDocument = () => (
        <Document author="Luke Skywalker" keywords="awesome, resume, start wars" subject="The resume of Luke Skywalker" title="Resume">
            <Page size="A4" style={styles.page}>
                <View style={styles.section}>
                    <Text>
                          Some Text
                    </Text>
                </View>
            </Page>
        </Document>
    );
   ReactPDF.render(<MyDocument />, `${__dirname}/example.pdf`);
```
I am trying to do  it inside a component. I am trying to implement an export functionality where clicking on the export button user should get this PDF file downloaded.

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**
The pdf should get downloaded.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - React-pdf 1.6.8

**Comment by geerthoekzema** [comment]
If you are trying to make a button which creates the PDF file and enables the user to download the PDF you should use PDFDownloadLink, see: https://react-pdf.org/components.

**Comment by diegomura** [comment]
Answered by @geerthoekzema . Thanks!
