### ISSUE TITLE
How i can use this with react hook component?

### ISSUE THREAD

**Issue by veronesecoms** [diegomura/react-pdf#842]
**Describe the bug**
When i try to use a hook component in PDFDownloadLink in component prop, i receive:

> ×
> Unhandled Rejection (TypeError): Cannot read property 'render' of null

**Desktop (please complete the following information):**
 - Windows
 - Chrome
package.json:

```
"dependencies": {
    "@material-ui/core": "4.9.5",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.45",
    "@react-pdf/renderer": "^1.6.8",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "axios": "^0.19.2",
    "formik": "^2.1.4",
    "notistack": "^0.9.8",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-history": "^0.18.2",
    "react-input-mask": "^2.0.4",
    "react-pdf": "^4.1.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.0",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "styled-components": "^5.0.1",
    "yup": "^0.28.1"
  },
```

I put in the file UsersPDF.js:

```
<div>
    <PDFDownloadLink
    document={Users}
    fileName="movielist.pdf"
    style={{
        textDecoration: "none",
        padding: "10px",
        color: "#4a4a4a",
        backgroundColor: "#f2f2f2",
        border: "1px solid #4a4a4a"
    }}
    >
    {({ blob, url, loading, error }) =>
        loading ? "Loading document..." : "Download Pdf"
    }
    </PDFDownloadLink>

</div>
```

"Users" that i passed to the component prop "document" is a hook component.

My users component:

```
const Usuarios = () => {

    return (
        <Document>
            <Page>
                <TableContainer component={Paper}>
                    <Table aria-label="simple table">
                        ...
                    </Table>
                <Pagination
                    className={classes.pagination}
                    count={lastPage}
                    page={page}
                    onChange={handleChangePage}
                />
            </TableContainer>
        </Page>
    </Document>
    )
}


export default Usuarios
```

**Comment by geerthoekzema** [comment]
With the information you provided I can't see why / how it fails. The error looks like the error which is thrown when you trying to render objects / components which are not React-PDF components.

You can only use the Components mentioned here: https://react-pdf.org/components

You are able to use hooks, i'm using a lot of hooks in my renders; so the problem is not the hooks, but something else (maybe hook related, but not the hook itself)

**Comment by veronesecoms** [comment]
@geerthoekzema thanks for the response, my usersComponent is using the components described in the link:

```
        <div>
            <Document>
            <Page>
                <View>
```

Inside the view i'm put the table component of the material-react-ui.
But i'm still receiving errors:

If my users component starts with <div> i receive:

> Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

if the component starts with the <Document> component, i get:

> Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

Anyway, i should use <View> or <Canvas> to print my material react table? This is possible? Thanks.

**Comment by geerthoekzema** [comment]
What do you mean with:
> Inside the view i'm put the table component of the material-react-ui.

Because also HTML code is not valid in reactPDF. So if you want to display a table, you have to rebuild this table with View and Text components code's like <table> and <div> are not valid.

**Comment by veronesecoms** [comment]
ok, thanks
