### ISSUE TITLE
How do I render to build a table component

### ISSUE THREAD

**Issue by leishihong** [diegomura/react-pdf#851]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by geerthoekzema** [comment]
You can build 'create' an table component by using View and Text components and give them styles.

There is not a 'table' component available within react-pdf

**Comment by geerthoekzema** [comment]
You could also take a look into: https://github.com/dmk99/react-pdf-table

**Comment by diegomura** [comment]
Discussion here https://github.com/diegomura/react-pdf/discussions/1107
