### ISSUE TITLE
Page crashes when trying to render PDF with an Image.

### ISSUE THREAD

**Issue by z3us94** [diegomura/react-pdf#858]
**Describe the bug**
I am trying to create a PDF and render it on the fly inside a **PDFViewer** component. But when i'm trying to load an image using the **Image** component.

**To Reproduce**
On the first load of the application when i try to view the PDF it crashes. But after refreshing the page and going to that same route again the pdf renders. Also after a cache clear refresh this happens.

I have a component like this.
```
// this is like the parent component which is calling and getting the pdf doc

const QuotationPdfView = ({ match }) => {
  const [quotation, setQuotation] = useState(null);
  useEffect(() => {
    const getQuot = async () => {
      if (match.params.id) {
        const resposnse = await getQuotation(match.params.id);
        setQuotation(resposnse.data);
      }
    };
    getQuot();
  }, [match]);

  return (
    <div className="content-container">
      {getPDFDoc(quotation)}
    </div>
  );
};

// below is inside another file. So the image file is imported in that file like this.
// import logo from 'relativepath';

const getPDFDoc = (quotation) => {
 const getHeaderSection = () => {
  return (
  <View style={styles.headerImageContainer}>
        <Image src={logo} />
   </View>
);
};
return (
    <PDFViewer width="100%" height="1000px">
      <Document title={quotationCode}>
        <Page size="A4" style={styles.page} wrap>
          {getHeaderSection()}
        </Page>
      </Document>
    </PDFViewer>
  );
}

```

**Expected behavior**
Smooth rendering of the PDF

**Screenshots**
This is the showing error.
![error-01](https://user-images.githubusercontent.com/17064184/77423863-221e1280-6df6-11ea-9818-63b14e0ec5a9.PNG)

**Desktop (please complete the following information):**
 - OS - Windows
 - Browser - both Chrome latest and FireFox developer edition latest
- React version - 16.12.0
 - React-pdf - 1.6.8

**Comment by hyun-park** [comment]
Your code might be trying to render pdf again before it was rendered
Try `PureComponent` from  @Archymede123
[https://github.com/diegomura/react-pdf/issues/420#issuecomment-566121415](https://github.com/diegomura/react-pdf/issues/420#issuecomment-566121415)

**Comment by z3us94** [comment]
@hyun-park Hey Thank you for responding and sorry for the delayed response. I actually found my issue there. Actually i think as mentioned the state setting was the issue. But what is weird here is the state changing component is not in anyway relevant to this component that im rendering the PDF. Instead it is in the root level of the application. But from there i have defined all the components as HOF. I suspect that this issue is due to re-evaluating each HOF type components on each state change. Im not sure what it is.

Anyway im going to close this issue now.

**Comment by jlala** [comment]
> @hyun-park Hey Thank you for responding and sorry for the delayed response. I actually found my issue there. Actually i think as mentioned the state setting was the issue. But what is weird here is the state changing component is not in anyway relevant to this component that im rendering the PDF. Instead it is in the root level of the application. But from there i have defined all the components as HOF. I suspect that this issue is due to re-evaluating each HOF type components on each state change. Im not sure what it is.
> 
> Anyway im going to close this issue now.

 Hi!How did you solve this image rendering problem?

**Comment by z3us94** [comment]
@jlala Like i mentioned there was a state change happening on the root level of my react app. Meaning when react-pdf is rendering the PDF there shouldn't be any other state updates happening to that particular react component. So my issue was in the higher level of the tree I update some values but then it makes all the child components to re-render. To avoid I think you can make functional components. 
But if the app is too complex you can try a timeout to let PDF render start rendering. Im not sure if this is fixed right now though.
