### ISSUE TITLE
Equality checks throws error on render prop

### ISSUE THREAD

**Issue by georgegrigorita** [diegomura/react-pdf#859]
The equality check inside the Dynamic Content example from the website throws an error. I'm referring to this bit:  `pageNumber % 2 === 0`

 - React-pdf version beta 2.0.7

**Comment by diegomura** [comment]
Thanks! Fixed here https://github.com/diegomura/react-pdf/pull/617/commits/35682e9a1f6851edd833a74ed04a91db5ef92a3a
