### ISSUE TITLE
Upload PDF file to S3?

### ISSUE THREAD

**Issue by akosijiji** [diegomura/react-pdf#861]
Hi guys, I'm loving this library and using this for one of my projects. So far, PDFDownloadLink is working on my end. What I'm wondering is that, is there a way to upload the PDF file to s3? Has anyone here tried doing that? I would really appreciate your help! Thank you!

**Comment by lulalachen** [comment]
Yes, you can leverage the `renderToPDFStream` API. The brief idea is attached below.

```
const rootElemComponent = React.createElement(component, componentProps)
const pdfStream = await ReactPDF.renderToStream(rootElemComponent)
await s3.upload(
  {
    Bucket: BUCKET_NAME,
    Key: `${pdfStream.info.Title}.pdf`,
    Body: pdfStream,
    ContentType: 'application/pdf',
  },
  (error, data = {}) => {
    ...
  },
)
```

**Comment by akosijiji** [comment]
Hi @lulalachen thanks for your response! However, I am not using ReactPDF. Is there a way to just pass the blob file to a function?

**Comment by lulalachen** [comment]
Just read through the source code, and it seems like there's a `toBlob` you may use.
I haven't tested it yet but I think it's the same logic.
Be aware that don't put any AWS keys on the frontend for security reason.

[https://github.com/diegomura/react-pdf/blob/master/src/index.js#L38](https://github.com/diegomura/react-pdf/blob/master/src/index.js#L38)

**Comment by akosijiji** [comment]
Thanks @lulalachen I already got it working.

**Comment by akosijiji** [comment]
Thanks @lulalachen ! I already got it working!

**Comment by zayn-m** [comment]
> Thanks @lulalachen ! I already got it working!

Can you tell me how did you make it working? I'm doing the same
