### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by oluwadareseyi** [diegomura/react-pdf#868]
Hello, I used your package but I had to discontinue because there was no mobile support.

I know it's still in development, but is there any fallback we can use so the PDF's display on mobile?

Thanks.

**Comment by acomito** [comment]
Oh god I just spent ages making an amazing PDF... and it doesn't work on ipad

😭

Devastated

**Comment by acomito** [comment]
Doesn't seem like this package is being developed anymore?

I did find this https://github.com/forthealllight/react-read-pdf

**Comment by oluwadareseyi** [comment]
> Doesn't seem like this package is being developed anymore?
> 
> I did find this https://github.com/forthealllight/react-read-pdf

Thanks, Doesn't seem so.

**Comment by oluwadareseyi** [comment]
> Oh god I just spent ages making an amazing PDF... and it doesn't work on ipad
> 
> 😭
> 
> Devastated
> 
> I didn't test yet, but is this just with the PDFViewer component? Does it work on mobile outside of that?
> 
> Right now, I have an 8 page PDF but it just displays the first page on mobile... can't scroll to other pages.

I'm not even sure, I tried to edit the CSS and all, but couldn't. I'll just close the issue.
