### ISSUE TITLE
Text wrapping messes up with different characters

### ISSUE THREAD

**Issue by tgreen7** [diegomura/react-pdf#869]
**Describe the bug**

If you have two columns in a table with a single character change they wrap differently

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
[react-pdf repl](https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618023100137802e1859b36001da972e012cc00737e01180032b18017c00d32a8d5d8a7e8c632b692230c4d4f8c00445a7724b6a0d09801dc2572805fa5ea015ca087b47214e0a2e640a1c3c2f0810443740c30e1050f0806158e4fe007200627600330282ac8d2710b08a0075370f790744f2f08025096902286af74f18057ab2e48a802110287f005b4eda9ea0f5209b142690673d20b631ea0a69292f5f7f04a77c94000f0011092a602809702f0a25cb19be9879e474c400091a0a95c4d72eaf00130015800a4fb6080dc2915d15862712e382d88d0a1bd32305c9150af912835211461a8c406354451b2390505271fd149546add3913c9178800cb21f21d3a7f17aab248d2002a206124dba4a362ccd89a6d0a0de3f271fca6966058319bc8ab4390d158bc455c89259331c55284269c2ba8f391acf669a7a3abc40a859ce9b296692db2a590880f97dc27a44bad36db2b2ec022aff56cc0fc204abf2e02816024002f0d4c0e400a35b063600eb215aed48c539d0e3994b5e1ec42ca8461c0f78fc219e556233028cf33371c4f271433660a80094006e66331409058001147c122388d9018183d07b18001f1cf94001e13881803e31b20b38bc4aae000ad4690ce102874231cfa852270782a7dd38d8ab801a84990ce382e02f57efcde5e0f8f24e2beefa7ed7a5ed7840a40bc8b338806244f8c02047e5f9e0105fe504bc6f27c62384f0621886ae7cb20472c0e06fe7826125bba9e8e11503e879dc5c0f8972ae003d311a472e0853eec5be1fb7104508c85817fba194741d46c4745e182509c267164589144a0545ba658c91403e7cbc0c2320ec629725097c68146411226a13fa41925bad277a5a599c662996720e26a93674a1a7d90c784d71700649150239bc5b1fc738c1701614b96e7fe5257ab843940799ce791d65615e4250c45012300fa47181445c2685a6525cfb15024f1cf945a94611e720b07e1f245935449586c48d7c9484a5ca5a5d45960f9d0a4400b4ae07843410ba5109010dd41805c10d310ee4348c4405001571a55156161555681d14a9b16d9880754d7756841d6a6799e83e00333ad4166d6576d8f521d54f5b55b5c763e9d575817edbd7a9d762e00828720009c434280090d20cc0434c020c8390f43e0fdd3b521e5785957096f79d00f4aed7a3cf99d5647d7d50340a00350468cbd264099b5d3e1433b8e93ad4960d7a3cd7bd6cd1d275397f4b5ee7a540e0d5008d1218d04048c214d100cd7342d44b20cb478e10d3d8d3d2546baf5ed82e1d04d7d2f71302f7342f935f5ddf946ddae339ccb3ae45d755bc0fb6bc6e91ff59380d7d20f83c8cc30a1c308d430a1fba8d5b0f4db98f7dc67db3165daf21346efdeedebf1cd15f553eae75b6c3351cf1b6c1e6c71ea7b7dec46e5b8ee7bb30fda0e4d0d09721e2700062a415073784f42aee3a4ed38c06c62efd9000)

**Expected behavior**

Text wrapping should work independent of character size

**Comment by taipignas** [comment]
i found out that text doesnt wrap on certain characters at all. not sure if its better to report a new bug or add a comment here.
the symbols that wont wrap: any number, . (dot), letters: a
also it would be nice to have an option to wrap without - sign

**Comment by taipignas** [comment]
bump
this bug is preset atleast from 2.0.0-beta.14 to 2.0.0-beta.18, i havent had time to try and downgrade to v1*.
also found othe people reporting same bug on stackoverflow https://stackoverflow.com/questions/64035774/how-to-do-word-wrap-with-react-pdf
capital letter dont wrap too

![image](https://user-images.githubusercontent.com/55182635/101486951-195e7400-3966-11eb-9998-49051560e0d4.png)

**Comment by taipignas** [comment]
i implemented a workaround which works for me because i know the width that i want. maybe it helps for somebody else too.

export const SplitText = (text, length) => {
    if (typeof text != 'string' || text.length < 1) {
        return text;
    }
    else {
        let regex = new RegExp(`.{1,${length}}`, `g`);
        let returnArray = [];
        let splitArray = text.split(" ");
        for (var i = 0; i < splitArray.length; i++) {
            let el = splitArray[i];
            if (el.length > length) {
                let split = el.match(regex);
                returnArray.push(...split);
            }
            else if (el.length > 0) {
                returnArray.push(el);
            }
        }
        let optimizedArray = OptimizeStringArray(returnArray, length);
        return optimizedArray.join('\n');
    }
}
const OptimizeStringArray = (arr, length) => {
    for (var i = 0; i < arr.length - 1; i++) {
        let newString = arr[i];
        let fixedI = i;
        for (var j = i + 1; j < arr.length; j++) {
            let addedString = newString + " " + arr[j];
            if (addedString.length < length) {
                newString = addedString;
                arr[fixedI] = addedString;
                arr[j] = "";
                i++;
            }
            else {
                break;
            }
        }
    }
    return arr.filter(el => el.length > 0);
}

**Comment by diegomura** [comment]
This is expected. Hyphenation is not just about available space vs amount of characters. It uses language heuristics to compute where the hyphens should be, so a single chat can mean that the hyphens end up in completely different places. Please provide your own hyphenation callback if you need to have control over how words break. More info here: https://react-pdf.org/advanced#hyphenation
