### ISSUE TITLE
× TypeError: _react_pdf_renderer__WEBPACK_IMPORTED_MODULE_1__.default.render is not a function

### ISSUE THREAD

**Issue by a852882874** [diegomura/react-pdf#873]
Excuse me: why do I follow the steps to repor
![1587198029(1)](https://user-images.githubusercontent.com/25943026/79632210-87181e80-8190-11ea-9b6f-3d20b312a998.jpg)
t this error

**Comment by a852882874** [comment]
![1587198363(1)](https://user-images.githubusercontent.com/25943026/79632377-508ed380-8191-11ea-973e-c1f61fe60226.jpg)

**Comment by manojsatya** [comment]
I am getting the same error as well.

**Comment by axelra82** [comment]
Same here. Copied code from https://github.com/diegomura/react-pdf/blob/master/examples/text/index.js for testing. Getting
`TypeError: _react_pdf_renderer__WEBPACK_IMPORTED_MODULE_2__["default"].render is not a function. (In '_react_pdf_renderer__WEBPACK_IMPORTED_MODULE_2__["default"].render(doc, __dirname + "/output.pdf")', '_react_pdf_renderer__WEBPACK_IMPORTED_MODULE_2__["default"].render' is undefined)`

**Comment by ProteanDev** [comment]
Yeah is there a fix for this? Getting the same thing.

**Comment by erangakapukotuwa** [comment]
It's seems you guys are trying to use `ReactPDF.render` in the front-end. It doesn't support in the front-end. `render` is available only in the Back-End.

try to console.log(ReactPDF) in both. You will realize by yourself.

**Comment by vuki656** [comment]
> It's seems you guys are trying to use `ReactPDF.render` in the front-end. It doesn't support in the front-end. `render` is available only in the Back-End.
> 
> try to console.log(ReactPDF) in both. You will realize by yourself.

No that is not true.

You need to use PDFDownloadLink component instead.

Check this issue for more info: https://github.com/diegomura/react-pdf/issues/613

**Comment by diegomura** [comment]
@vuki656 is right. Also, recommend upgrading to 2.0.0 and test if this still happens
