### ISSUE TITLE
Hangs when wrap={false} too big for one page

### ISSUE THREAD

**Issue by dance-dance-banana-frenzy** [diegomura/react-pdf#874]
**Describe the bug**
I get an infinite hang when content in `wrap={false}` is larger than a page. I can't event tell my browser to quit. This seems similar to issue #600 (closed) and #246 (closed), but I'm still having the problem. #685 (open) is similar, but it's specific to text being over two pages instead of one.

**To Reproduce**
It seems a `wrap={false}` can have no more height than 42 lines of text without any formatting.

```javascript
ReactDOM.render(
<PDFViewer>
    <Document>
        <Page>
          <View wrap={false}>
            <Text>Candy canes are not elf bones 1</Text>
            <Text>Candy canes are not elf bones 2</Text>
            <Text>Candy canes are not elf bones 3</Text>
            <Text>Candy canes are not elf bones 4</Text>
            <Text>Candy canes are not elf bones 5</Text>
            <Text>Candy canes are not elf bones 6</Text>
            <Text>Candy canes are not elf bones 7</Text>
            <Text>Candy canes are not elf bones 8</Text>
            <Text>Candy canes are not elf bones 9</Text>
            <Text>Candy canes are not elf bones 10</Text>
            <Text>Candy canes are not elf bones 11</Text>
            <Text>Candy canes are not elf bones 12</Text>
            <Text>Candy canes are not elf bones 13</Text>
            <Text>Candy canes are not elf bones 14</Text>
            <Text>Candy canes are not elf bones 15</Text>
            <Text>Candy canes are not elf bones 16</Text>
            <Text>Candy canes are not elf bones 17</Text>
            <Text>Candy canes are not elf bones 18</Text>
            <Text>Candy canes are not elf bones 19</Text>
            <Text>Candy canes are not elf bones 20</Text>
            <Text>Candy canes are not elf bones 21</Text>
            <Text>Candy canes are not elf bones 22</Text>
            <Text>Candy canes are not elf bones 23</Text>
            <Text>Candy canes are not elf bones 24</Text>
            <Text>Candy canes are not elf bones 25</Text>
            <Text>Candy canes are not elf bones 26</Text>
            <Text>Candy canes are not elf bones 27</Text>
            <Text>Candy canes are not elf bones 28</Text>
            <Text>Candy canes are not elf bones 29</Text>
            <Text>Candy canes are not elf bones 30</Text>
            <Text>Candy canes are not elf bones 31</Text>
            <Text>Candy canes are not elf bones 32</Text>
            <Text>Candy canes are not elf bones 33</Text>
            <Text>Candy canes are not elf bones 34</Text>
            <Text>Candy canes are not elf bones 35</Text>
            <Text>Candy canes are not elf bones 36</Text>
            <Text>Candy canes are not elf bones 37</Text>
            <Text>Candy canes are not elf bones 38</Text>
            <Text>Candy canes are not elf bones 39</Text>
            <Text>Candy canes are not elf bones 40</Text>
            <Text>Candy canes are not elf bones 41</Text>
            <Text>Candy canes are not elf bones 42</Text>
            <Text>Candy canes are not elf bones 43</Text>
          </View>
        </Page>
    </Document>
<PDFViewer>, 'root');
```

**Expected behavior**
A PDF is generated where content that is larger than the page overflows into the next page.

**Screenshots**
I can't take a selfie of myself pulling my hair out.

**Desktop:**
 - OS: MacOS 10.15.4
 - Browser Chrome
 - React-pdf version 1.6.8

**Comment by kelvindelosangeles** [comment]
Hey there, I was having a similar issue.  Instead of wrapping all of the text components in one View thats too large for the page and wrap set to false, either 

- Try removing the wrapping View component and setting each text component to wrap={false}

-  Or if the text components need to be wrapped for whatever reason add individual wrappers to those text components with a wrap={false} so that they don't break.

The page should now overflow into the next nicely :)

**Comment by dance-dance-banana-frenzy** [comment]
This is an oversimplification of the problem I'm having. I need the entire portion of some pretty complex layout of components not to split across pages unless it is too big. I'm unable to break it apart, as if it's too big, the beginning of the component should appear at the top of the next page.

**Comment by kelvindelosangeles** [comment]
Right,

What worked for me was taking the large array and splitting it into chunks of 10 (about 30 items fit per page in my case) and wrapped each chunk in a View with Wrap={false}

Heres the function I used. pass in your array and length and works for your case.

`    const chunk = (array, size) => {
        const chunked_arr = [];
        let index = 0;
        while (index < array.length) {
            chunked_arr.push(array.slice(index, size + index));
            index += size;
        }
        return chunked_arr;
    };`


Then after i mapped through the chunks and wrapped them in the Wrap={false} Views.  You can combine all of this I just split it for better visibility.

`    const ordersChunkedMapped = chunk(orderArray, 10).map((i) => {
        return (
            <View style={$.wrapper} wrap={false}>
                {i}
            </View>
        );
    });`

General idea, I feel like you can tweak this to fit your needs.  Hope it works. :)

**Comment by dance-dance-banana-frenzy** [comment]
The issue is that I have a rounded box that needs to contain all results. An array of results with rounded boxes for each result, and then one of those results has an additional array that is a very large array of data to list within that box. Therefore the box needs to overflow into the next page.

**Comment by TomasB** [comment]
Found this after reproducing same issue in playground: https://react-pdf.org/repl

```
<Text style={styles.text} wrap={false}>
En un lugar de la Mancha, de cuyo nombre no quiero ....
```

To reproduce the issue, copy paste the text so that it spans across multiple pages.

**Comment by alecperkins** [comment]
I ran into an interesting variation on this, where the process' first server-side render of a document with a `<Page wrap={ false }>` would work fine, but the _subsequent_ render of any other document would cause the process to hang. Luckily, the doc structure allowed me to move the `wrap={ false }` to a `<View>` at the bottom of the page, similar to how @kelvindelosangeles [described](https://github.com/diegomura/react-pdf/issues/874#issuecomment-617201647), and that resolved the issue.

**Comment by pavloPL** [comment]
I have a similar issue, I have a table view with rows and I want to display them uncut so using wrap={false} but if I have too many rows it just hangs up.

**Comment by clement-faure** [comment]
Same issue here.

I'm using a container / grid system (using css) and when removing wrap={false} (because leading to infinite loading), all styles seems to be lost (only on page which should break into multiple)

![image](https://user-images.githubusercontent.com/23209488/105149461-d9151880-5b03-11eb-8645-8eaf7fc3668f.png)

In other sections which are less big than1 page, all seems to work fine ...
![image](https://user-images.githubusercontent.com/23209488/105149543-ef22d900-5b03-11eb-99aa-3082757ea84f.png)

**Comment by diegomura** [comment]
Hi! I'm confused, since you are explicitly asking the engine not to wrap that element. I guess some internal check can be implemented. Not sure what output you should have on a big element that you dont want to wrap

**Comment by diegomura** [comment]
Any clues? What would you expect to happen if a big element has to wrap but you are explicitly asking not to?

**Comment by TomasB** [comment]
@diegomura to answer your question (but I can only speak for myself):
1. should start rendering on new page
2. continue on another page
3. it should not crash

Motivation for the 1st and 2nd point:
  1. wrapping should only affect where to start rendering component, thus, if wrapping is set to true, and content can't be put on the same page, content should render on the next page.
  2. since wrapping is affecting where is starts rendering, 3rd point becomes obvious as well?

**Comment by diegomura** [comment]
So the example above should render like this
[doc.pdf](https://github.com/diegomura/react-pdf/files/6276100/doc.pdf)
That's what you mean right? I think it makes sense

**Comment by diegomura** [comment]
I'll wait for your confirmation but I think that document reflects the expected behavior for the document provided.

**Comment by nadiTime** [comment]
still had this happening on version 3.1.9
