### ISSUE TITLE
Image doesn't appear on pdf while set string in src

### ISSUE THREAD

**Issue by aurma97** [diegomura/react-pdf#876]
@diegomura 
Hey there, I'm receiving the image via and url in an object and would like to display it. 

In my react component i can show it with <img/> without any issue but i don't understand why it doesn't work in react-pdf, while i can display static image using "import image from 'path/to/image.png';

There is the code to display image from url :
![image](https://user-images.githubusercontent.com/16616005/80009972-0c217180-84ca-11ea-8d5b-c08a69ea479a.png)

I've also tried to render just the link and it works well but i don't understand why the image can't be diplayed.

Result when generated with link in Text : 
![image](https://user-images.githubusercontent.com/16616005/80010150-47bc3b80-84ca-11ea-8aa1-846bb1d5c586.png)

Could you help me please ?

**Comment by diegomura** [comment]
I can't find out what's going on with this little information sorry. It seems that the image is not accesible to the library. Please check the network tab (if using this lib in the client) and check for errors. Otherwise I'll need a way of replicating it.
