### ISSUE TITLE
× Error: Invalid element of type div passed to PDF renderer

### ISSUE THREAD

**Issue by arhoy** [diegomura/react-pdf#877]
I have the following very simple example
import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: 'white',
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
});

```
// Create Document Component
export const MyDocument = () => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text>
          <div>New Text Here</div>
        </Text>
      </View>
      <View style={styles.section}>
        <Text>Section #2</Text>
      </View>
    </Page>
  </Document>
);
```

I get error 
× Error: Invalid element of type div passed to PDF renderer

Why?

Thank you.

I am trying to follow resume example and render jSX insdie the text field. What packages I am missing, It looks to be importatnt something from dist and there is no docs I can find

**Comment by JacksonBates** [comment]
I keep butting up against this issue too @arhoy.

I believe this is the current canonical answer: https://github.com/diegomura/react-pdf/issues/634#issuecomment-505864638

I.e. we cannot render arbitrary html elements within the react-pdf primitives

**Comment by arhoy** [comment]
@JacksonBates ok so I cannot have div?

I am just tryin to find a solution that makes generating pdfs lol. Is there a work around?

**Comment by JacksonBates** [comment]
I don't believe so. If I'm wrong, I would love to hear it because this has been causing me issues for months.

My work around has been to use a HTML parser and to strip out HTML elements that cause problems, but I'm working with user generated HTML from a Froala editor... It's a mess.

I'm about to try doing it in PHP on the server instead, that's how desperate I've become :)

**Comment by diegomura** [comment]
Exactly. You cannot render html nodes inside pdfs. What you can do is parsing react-dom nodes into react-pdf's, adjusting any needed styles . Been wanting to release a tool for this for a long time but couldn't have time yet.
