### ISSUE TITLE
Using inches for page size

### ISSUE THREAD

**Issue by Xcellion** [diegomura/react-pdf#878]
**Describe the bug**

Receiving the following bug - "Unhandled Rejection (Error): unsupported number: 3.5in"

Can't use inches when setting page size

![image](https://user-images.githubusercontent.com/1526277/80054462-510acf80-84ed-11ea-9025-184bcf223afa.png)

**To Reproduce**

```
   <Document>
      <Page orientation="landscape" size={{
        width:"3.5in",
        height:"2.5in"
      }}>
        <View>
          <Text>
            Woohooo this isn't working
          </Text>
        </View>
      </Page>
    </Document>
```

**Expected behavior**
A PDF of size 2.5in x 3.5in should be created.

**Desktop**
 - OS: MacOS
 - Browser chrome
 - React-pdf version v1.6.8

**Comment by JavaJames93** [comment]
@Xcellion: It worked for me to multiply by 72. Based on the documentation, the views are calculated using the unit "pt". You can convert between "pt" and inches by multiplying with a factor of 72. You should make your code look something like the following:

```
<Document>
     <Page size={{width: 2.5*72, height: 3.5*72}}>
          <View style={styles.section}>
               <Text>Section #1</Text>
          </View>
     </Page>
</Document>
```
reference: 

https://github.com/diegomura/react-pdf/blob/master/src/utils/pageSizes.js

**Comment by Xcellion** [comment]
@grumpyTofu thanks for that, I looked through the source code and found the same thing you linked me.

I was under the impression that inches / cm / etc would work out of the box because of [this page](https://react-pdf.org/styling) but I guess the documentation isn't so clear.
