### ISSUE TITLE
when i use ReactPDF.render Uncaught TypeError: renderer_1.default.render is not a function

### ISSUE THREAD

**Issue by kq12** [diegomura/react-pdf#879]
exactly,I donnot know how to use ReactPDF.render in a react container,can anyone show an example here,thankyou!!
I want to save JSON data as a pdf, and then can click a button to  execCommand saveAs and print,but I got no idea how to get it

**Comment by Jelle-vz** [comment]
Any updates on this?

I have the same issue when trying to save using an onClickHandler.

```
const handleSavePdf = async(): Promise<void> => {
    const options = {
      types: [
        {
          description: 'Pdf Files',
          accept: {
            'application/pdf': ['.pdf'],
          },
        },
      ],
    };
    const result = await (window as any).showSaveFilePicker(options);

    ReactPDF.render(<PDFDocument />, result.name);
  }
```

**Comment by Jelle-vz** [comment]
For those still looking. Found a work around [in this blogpost](https://dev.to/finallynero/generating-pdf-documents-in-react-using-react-pdf-4ka7) using the PDFDownloadLink option
