### ISSUE TITLE
@react-pdf can't be minified by UglifyJsPlugin

### ISSUE THREAD

**Issue by AlanSaracho** [diegomura/react-pdf#880]
Hi! I have a problem trying to use a react-pdf dependency with UglifyJsPlugin.
When i build a release dist bundle with webpack, i get this error:

> ERROR in bundle.js from UglifyJs
> Unexpected token: name «StateMachine», expected: punc «;» [bundle.js:134326,6]
> Child html-webpack-plugin for "index.html":
>      2 assets
>     Entrypoint undefined = index.html
>     [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 895 bytes {0} [built]
>     [2] (webpack)/buildin/global.js 472 bytes {0} [built]
>     [3] (webpack)/buildin/module.js 497 bytes {0} [built]
>         + 1 hidden module
> error Command failed with exit code 2.

I not add code, only a single import without usage.

> import { PDFDownloadLink } from '@react-pdf/renderer'

**Desktop**
 - OS: MacOS
 - Browser: Chrome
 - React-pdf version: 1.6.8

**Comment by AlanSaracho** [comment]
I migrate from uglify to terser. Looks good for now.

**Comment by diegomura** [comment]
Using `terser` is also better. Thanks!

**Comment by aktoak** [comment]
i am using terser webpack plugin, and i only import Document, and Page in my code.
i get an error
```Terser Plugin, Minimizer doesn't return result```
any suggestion why this happening?
