### ISSUE TITLE
TypeError: Cannot ready property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by lfoliveir4** [diegomura/react-pdf#881]
**Describe the bug**
Using lib does not render react application returning the following error: TypeError: Cannot ready property 'hasOwnProperty' of undefined

**To Reproduce**
Only importing the lib, without using the components causes the error reported below in the image:

**Screenshots**
![image](https://user-images.githubusercontent.com/32423942/80660287-b157bf00-8a61-11ea-92fa-418fc9e19d10.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - React-pdf version: ^1.6.8

** React Version 
    "react": "^15.6.2",
    "react-dom": "^15.6.2",

**Comment by AntilopeInteractive** [comment]
Same problem here

**Comment by lfoliveir4** [comment]
> Same problem here

@AntilopeInteractive I tried to update your react to the latest version. Some older versions do not support decorators and this library has many dependencies on decorators.

**Comment by AntilopeInteractive** [comment]
> > Same problem here
> 
> @AntilopeInteractive I tried to update your react to the latest version. Some older versions do not support decorators and this library has many dependencies on decorators.

I have same react version: 15.6.2

**Comment by lfoliveir4** [comment]
This version is very old. It is probably not supported anymore. Update react and react-dom

**Comment by diegomura** [comment]
This should not be happening anymore in last 1.X version or 2.0. Please report if it does. Closing for the moment
