### ISSUE TITLE
Page wrap / break issue's

### ISSUE THREAD

**Issue by SebastianBerg** [diegomura/react-pdf#882]
I want to make a simple design where I have a header, a footer and a dynamic list inbetween, but if the list is too long, then all the posts in the list just jump on top of eachother, like in the picture, it works perfectly fine until the list fills the page, then this wierd behaivor shows up. Everything works 100% when I got fewer items in the list, any ideas how to solve this?

Also I have tried to use a <View break /> after every 10'th item in the list, but that does not either seem to break, or the page break does not occur at all.

/ Cheers

```
const styles = StyleSheet.create({
  heading: { textAlign: 'center', margin: '20px', fontSize: 25 },
  flexContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center'
  },
  row: {
    width: '100%'
  },
  image: {
    width: '30vw', maxWidth: '320px', padding: '20px 0 0 20px'
  },
  section: {
    margin: 10,
    flexBasis: '80%',
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: 14,
  }
});

// Create Document Component
const Recipt = (props) => (
  <Document>
    <Page wrap>
      <View fixed>
        <Image src={Logga} style={styles.image} />
      </View>
      <Text fixed style={styles.heading} break>Kvitto</Text>
      <View style={styles.flexContainer} debug={true} render={() => (props.confirmedBookings.map(booking => <View style={styles.section} wrap><Text style={{ width: '100%' }}>{booking.activity.name}</Text><Text>{moment(booking.time).format('Do MMM HH:mm')}</Text></View>))} />
      <View fixed><Text>Footer</Text></View>
    </Page>
  </Document>
)
```
![error](https://user-images.githubusercontent.com/42352327/80720443-2fb56f00-8afd-11ea-9173-6e32d1fbd53c.png)

**Comment by diegomura** [comment]
Why are you using the `render` prop there if your nodes are not dynamic? 

You can just do:

```jsx
 <View style={styles.flexContainer} debug={true}>
    {confirmedBookings.map((booking) => (
      <View style={styles.section} wrap>
        <Text style={{ width: "100%" }}>{booking.activity.name}</Text>
        <Text>{booking.time}</Text>
      </View>
    ))}
  </View>
```

Tested it on my end using 2.0 and another image and dummy data and worked fine: 
[doc.pdf](https://github.com/diegomura/react-pdf/files/6269188/doc.pdf)

Please apply those changes. Closing this now. Report back if the issue persist
