### ISSUE TITLE
styled components does not support text-decoration

### ISSUE THREAD

**Issue by dance-dance-banana-frenzy** [diegomura/react-pdf#889]
**Describe the bug**
text decoration does not work.

**To Reproduce**
```js
import React from 'react';
import styled from '@react-pdf/styled-components';
const Wrapper = styled.Link`
  text-decoration: none;
`;
const Foo = ({ src, children }) => (
  <Wrapper src={src}>{children}</Wrapper>
);
```

**Workaround**
```js
import React from 'react';
import { Link } from '@react-pdf/renderer';
const Foo = ({ src, children }) => (
  <Link src={src} style={{textDecoration: 'none'}}>{children}</Link>
);
```

**Expected behavior**
Links generated without underlines

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - React-pdf version [e.g. v1.1.0]
```
    "@react-pdf/renderer": "^1.6.8",
    "@react-pdf/styled-components": "^1.4.0",
```

**Comment by diegomura** [comment]
Unfortunately I do not have a way to change how styled-components parses the css styles. I recommend not using the styled-component binding anymore moving forward, since it relies on an old version of it and the support is low
