### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by adamsp70** [diegomura/react-pdf#890]
**Describe the bug**

I have an array of images (a basket) which I want to render within a PDF. 

`          <View style={styles.images}>
            {location.images?.map(({ ext_itemps_id, ext_itemps_product_set_image }) => (
              <Image src={{ uri: ext_itemps_product_set_image, method: 'GET', headers: {}, body: '' }} cache={true} style={styles.image} key={ext_itemps_id} />
            ))}
          </View>`

This is rendered via a `<PDFDownloadLink>`

When not cached, the images are retrieved and the PDF is generated perfectly
When cached, and the basket is the same, everything still works.
But add a new image to the array, and generate the PDF and the new image gives a CORS error. The server is not getting the origin header required.
If i then shift-refresh the page, all images will work fine.

**Expected behavior**
Any images that aren't in the cache should be retrieved as normal, with full headers.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - React-pdf version: 1.6.8

**Comment by diegomura** [comment]
Couldn't replicate. This is what I did that describes what you have:

```jsx
const img1 =
  "https://cdn2.iconfinder.com/data/icons/construction-147/64/bulldozer-truck-construction-tracktor-512.png";
const img2 =
  "https://cdn0.iconfinder.com/data/icons/camping-and-adventure-without-backround-set-2/300/3-512.png";
const img3 =
  "https://cdn1.iconfinder.com/data/icons/camping-65/500/tent-512.png";

const DocumentWrapper = () => {
  const [bucket, setBucket] = useState([img1, img2]);

  const addImage = () => {
    setBucket((prev) => [...prev, img3]);
  };

  return (
    <>
      <button onClick={addImage}>Add image</button>

      <PDFViewer>
        <Document>
          <Page size="A4" warp={true}>
            <View>
              {bucket.map((img) => (
                <Image
                  style={{ width: 100 }}
                  src={{
                    uri: img,
                    method: "GET",
                    headers: {},
                    body: "",
                  }}
                />
              ))}
            </View>
          </Page>
        </Document>
      </PDFViewer>
    </>
  );
};
```

Please try upgrading react-pdf and report back if this still happens
