### ISSUE TITLE
Convert PDF to Image

### ISSUE THREAD

**Issue by thuram** [diegomura/react-pdf#891]
I am developing a course platform using ReactJS. When the user finishes a course he can download the PDF file.

I need a version of the same file as an image (png or jpg), but I haven't found any way to do that. Can someone help me?

**Comment by geerthoekzema** [comment]
This is not a feature within react-pdf (and i'm not really sure it should be? Because this is an PDF renderer, not an image renderer).

That being said:
Did you try this? https://www.npmjs.com/package/react-pdf-to-image

**Comment by felipej26** [comment]
Olá Lucas, você acabou encontrando uma solução para resolver isso? Estou com o mesmo problema rs
