### ISSUE TITLE
any api for read a pdf?

### ISSUE THREAD

**Issue by fred8617** [diegomura/react-pdf#901]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geerthoekzema** [comment]
Could you please give a description of what you want or need? 

Based on the title of your issue I assume you want an API for reading a PDF? What do you want to do with this API?

**Comment by diegomura** [comment]
Thanks @geerthoekzema for addressing the lack of information of this ticket.
Assuming @fred8617 is asking for a way of opening a preexisting pdf document. react-pdf is currently just for generating , not opening docs. This issue has been addressed many times but technically currently is not possible to do this, and not sure if it will ever be supported. Closing this
