### ISSUE TITLE
Adjust screen resolution. 72dpi to 300dpi

### ISSUE THREAD

**Issue by morningcocoa** [diegomura/react-pdf#903]
I'm sending over a generated pdf over to the printers and they were wondering if the resolution can higher. They said 300dpi would be best, but it's currently generating a 72.

**Describe the solution you'd like**
An attribute to add to Document or Page that can scale the resolution.

**Comment by sines99** [comment]
Push!

must have!

**Comment by diegomura** [comment]
Fixed https://github.com/diegomura/react-pdf/pull/1869
