### ISSUE TITLE
Backend rendering example

### ISSUE THREAD

**Issue by devdavidkarlsson** [diegomura/react-pdf#904]
Hi, this is great stuff.
was wondering if you have an example for rendering, not client side. Server side rendering that is.

Thank you :)

**Comment by MariuszKogut** [comment]
Are you asking for an server render example? If so, please take a look here: 

https://react-pdf.org/

```
import ReactPDF from '@react-pdf/renderer';

ReactPDF.render(<MyDocument />, `${__dirname}/example.pdf`);
```

**Comment by devdavidkarlsson** [comment]
To clarify there are no other dependencies than nodejs and what is in package.json to render server side?

no: wkhtmltopdf, pupeteer, chrome things. 😅

**Comment by devdavidkarlsson** [comment]
To clarify there are no other dependencies then node and what is in package.json?
