### ISSUE TITLE
How to add padding to breakable components only when it breaks between pages

### ISSUE THREAD

**Issue by vijayvamja** [diegomura/react-pdf#907]
Is there any way to add some padding when any breakable component break between pages. 

e.g. I have a **View** component which is breaking between pages, So When It gets break, i wanted to apply some padding at the end of current page and on begining of following page. 

**Note:** I don't want to add pading to Page component, Because my page is split between two columns, So I don't want to apply padding for 1 column, It should remain full height of page. I only wanted to have some padding for 2nd coloum. 

Here is the REPL Link: 
https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a00d490600ee31a78a951446396201994751d3652a005430a36006430d98bcc06115400f42e6e1a0e41ba06619a3a7a86c692c672004e487c0016b6d1e191f1666289f916b2a0ac2c59f60e8e21b009a6e672986e765555009a2c4a20003430000e0816bdc03c8c48603c605d306083d0c920305622a39398303c006ee508c9180bbd48f23c30e93cf22b538ba510692095ad30cc108c3d3042304a48c07a57005c30400a01001fb10480025d813e08250f17ab73022c008e83180b060221004060db3012094fb2c4c0a07a461f4b1dd07ab418936984078223e09c4e2204000bc31276db256104e489dd2486808152270253c854b5196289e90c301d214980a2b0fe2a555e9f2243235198ec45980a92d7ecb088feb8099c3042d31622311f151275294078c9347404e6375438faa9663f28c0cfc49c5d50f1630780047c99c33e161753d26fb1e001f80100413e8b078d8b3bc800b7277f0c192082d430aedecd2664098e2675f18b725ba56528e78b5b930549c3e163e8f07e5890de9920195b62bafcd8440ab9c397c9f913c102173fb578408923793f8f5bd0f8f0b3136c5ebfa1815646891f3eb8c5d5d19e3d34fd8015aba9076cdf808c2b8db25fbd38c4b00e8e6a739c85942f4ab2bcb5c9f92808088c01601f33022120cb35ab3a50aeabc602169c8e22c306719e10b3d2b08c0e9aec22ac62aaf4048be571e1172d24eaac71888184c0085ea8b046a9174bd3369cb62033ec2eb621f31cf0780161b1899800a8607c22c8aaa46cb80eb0b258871af3242e8c846160eb940fcb1c568da6888852baed739c0c9880b27c9f9824fba0580763c071002c976672d1183d1d338e303d0dabd2c26b211840f099648000cf460800bb2e564ca9c6d9ef871001288513194ef27120330601b2f14b16304c6ea09c59ac690208b07ca5085d3000c2a339271979ea5e8222c8b39043536455338ae2d4452140d2c84d0540fa701d15c025ccc328ce3399b33c60e72cab1e55b0ec7b01c3011c02b9c9734c371dcda458af1ee9f37cbf1740088260a42d0ac2f0b8c3aaaa5089eb8be284b6224860648521c4d20c4414c86c18bb278772bcb26a710a5008a4818a8664a5634a1baae0a92a2a8591c66adab2aba9120691a23a9a4d85ab1a83817da8e815ac2baee8265e8cd942fa483fa270418468644446d184c7e47a7272669b9187b0179ae1c5a96e582095bb392ed68b26053236e68b627063ed9609dbc9673e57d80ea170efb18ec064e3c34e1c7ce8b9111037e72b24d67625b8ee4abee52f1e44966e7a5efd0de36d69caf3eafbbeeee7e4ef62ae9fec058860101b9a8193206904878cf42f06214f3f8a86b21e72b58780b86b63f591ee496439911442cfcaf4345c6016da2713153195a8fb1cad71a96f18d80922909fd20cba70112432a50c904a5911a1b8a729c8da9db462a1fb33a5e93244086562c66d966431c5863d65a5927d98b17450b39ae5112b1793e6c6747994148543b854c0e6d156af146e4957e2946e53e765ee32b6ca3f172bac06a85458095486231cab332aa9646a83a7aa8cc9aa2c56a40c3ab2b4f25d5fc2f519afd446a0d7083508c18d7a83212688d168ecce6bf111e430d28208626b5e622c4da73c34ae2280bb10921c638205dba9d700b709485d1786f03e17c1f89d04003d504c819eac157a461deb134faabdb10573fac494939228a20dad18306410c5934372efb0e1806414c294500b74698d653ca454515347e365684c3eb68f748688e05319854c938d313174d14833674ccde327a2401c539b7374e7ccd3b8628c31845ab324cfc825a666cc29c0b1164b2f2dbe22b2e81c46b1d67565f1a620956cbad6fb324363d9dd3f641cf49f445b16456ca8adb656f6cadb2e55caec653bb7389eddc77b3c9be3fda0c0bce24839333bcf12780be54891cb38c71fcf1d8f2016b4f92c0ba718499d4a367042f9590817742c5d864e12e9f84f12577d6270488db13875ca8a374187e45ba3113a9dcd88837f07dd5f230da9c044498f799924a792e59e3e417a9c25eea4b02697bcebc4526f6c4dbc9e2ef132a13cc91f671402ed21247257d900b9758ee5ef934ef9cfd80abf30afd022a7f2fcdfc129ff2760026c99f101eccc04ad3ca5028aac0b2a2b52a90f6aaac16a9a0c6a3f05a9b50be1813ab4a8217d582090ef4110e2290ca0549b55444a841178008308410e803022a6c0c8010000dc640c800031752b20f61f0446fb0f00480e0c7cdf108004001c8003c8407d00c894006ca49402032460081b321403e8100fe204408561d49c83e01e84930012885502040408588c34882508113600046000cc810da0007d270001a5b40003610000038003a8804d8f20002a9282ad8c0eb4000d0009c3c1d33a649a500ac006b20aa0ed43a9b8a341a0e0180001948a06eb94180a00943d83c13017a8e08a0540026f59a0be0403e82b1fd4c000044cb15c03ea8d9c19f4a01a0480f6300124e000103e858fa15f65427c2b849158210cd5916b000337a07060000b4db8a03e80c02c040e505506fbac1400bd951f43e2280e9000d568004c0014930e70638c0000359f0058a53a0e6264881a0031000162ad9c6c8e71ce391b2a1ca348991034568000ce2628e09cd0a0158e06fd0829300c9ce0d7b6f4f07bd01bc60a13f0c87313d1953d86382a40c87866025ece084694311c0d2dbdb749b7d94168c31a6353058c8a0e38eabcf7995394184e99b139261ce543931e660006a620671ccdd1bd77b03769f184862e3d03a3866df73a728f871f0db2f849d02df41406963814d2cbefbd486ea406c8300020ad2dba2ef1775601f2ca0180e268ae2efb56413286001c500b80d0475aeb3a27aaa0608d03ac408c4097500000

**Comment by diegomura** [comment]
There's currently no way to style a component based on if breaks or not

**Comment by diegomura** [comment]
Keeping https://github.com/diegomura/react-pdf/issues/733 to track this issue
