### ISSUE TITLE
PdfMake.org features are missing

### ISSUE THREAD

**Issue by Louies89** [diegomura/react-pdf#909]
Hi,
When I compare this library, with PdfMake, there are a lot of features missing which are provided by PdfMake. Please check [this ](https://pdfmake.github.io/docs/document-definition-object/)for some of the features missing.

But react-pdf (pdfkit) has better canvas(vector graphics) support than PdfMake.

Why I am doing the comparison ? 
I am implementing a form, where user has to use rich text editor something like [this](http://suneditor.com/sample/index.html), and the output of the rich text editor shall be in HTML fomat, and I am using PdfMake to create PDF out of the HTML using a intermediate library called [html-to-pdfmake](https://github.com/Aymkdn/html-to-pdfmake). But after getting react-pdf, i thought my work shall be easy for this, but its not, as react-pdf is not supporting plain HTML doms.

So thought to inform regarding this challenge, so that in future some features can be implemented.

Thank you all the contributors for your amazing work. :)

**Comment by diegomura** [comment]
Thanks! I think there are open new features tickets for pretty much of those things we do not support yet. It's hard to implement everything and maintain the rest working. Will close this since it's not really an issue but I appreciate you flagged this
