### ISSUE TITLE
Image component crashing

### ISSUE THREAD

**Issue by sabbin** [diegomura/react-pdf#910]
**Describe the bug**
Image component is crashing when loading image from url

**To Reproduce**
Use the `Image` component as described in the documentaion.
Pass the `url` as string to the `src` prop. 

The url in the following snippet is public so it can be tested by anyone

```js
const Page1 = () => (
  <Document>
    <Page size="A4" warp={true}>
          <View style={pdfStyles.section}>
            <Image
              src={'https://cdn2.iconfinder.com/data/icons/construction-147/64/bulldozer-truck-construction-tracktor-512.png'}
              style={pdfStyles.companyLogo}
            />
          </View>

          <View style={pdfStyles.section}>
            <Text>Section #1</Text>
          </View>
        
          <View style={pdfStyles.section}>
            <Text>Section #2</Text>
          </View>
    </Page>
  </Document>
)

export default function PDF(){
   return(
        <PDFViewer width="100%" height="1000px">
          <Page1 />
        </PDFViewer>
   )
}
          
```
**Expected behavior**
To get an image in the PDF

**Screenshots**
![Screenshot](https://imagehost.com.au//d7amw0Kd9r/KKKKK_5ec28debd4f68.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome, opera, mozilla
 - React-pdf version 1.6.8

**Comment by diegomura** [comment]
Fixed in last version: [doc.pdf](https://github.com/diegomura/react-pdf/files/6275952/doc.pdf)

Tested your code but without your styles since they were not provided
