### ISSUE TITLE
@react-pdf/renderer doesn't work in IE 11

### ISSUE THREAD

**Issue by hassanammarsbd** [diegomura/react-pdf#911]
as soon as i add the import statement anywhere in my project: 

import { Page, Text, View, Document, StyleSheet} from '@react-pdf/renderer';

the app stops displaying in IE 11, 

![image](https://user-images.githubusercontent.com/37668980/82266848-c9bc4a80-9938-11ea-8317-d7b4d4d70d73.png)

pointing error to:

![image](https://user-images.githubusercontent.com/37668980/82266892-ed7f9080-9938-11ea-9609-852034da5ca3.png)

**Comment by Sustenance** [comment]
Also seeing this exact issue. (although I had to actually use the components since my build strips out unused imported components) 🍿 
```javascript
import { PDFDownloadLink, Document, Page, Text  } from '@react-pdf/renderer';

const Doc = () => {
  return (
    <Document><Page><Text>Test</Text></Page> </Document>
  )
};

// in render:
<PDFDownloadLink document={<Doc/>} filename='test.pdf' >
        {({ blob, url, loading, error }) => (
          <button>Test PDF</button>
        )}
</PDFDownloadLink>
```

**Comment by Sustenance** [comment]
Looks like this is a long-standing issue due to the use of [dfa](https://github.com/foliojs/dfa). See #413

**Comment by Sustenance** [comment]
Looks like this was introduced in dfa@1.2.0. foliojs/dfa#4 is supposed to fix it, but hasn't been merged yet. In the interim, there is a temporary solution in that PR which is to pin dfa to version 1.1.0 using resolutions in your package.json and npm-force-resolutions to keep your package-lock.json patched correctly.

**Comment by hassanammarsbd** [comment]
@Sustenance or @diegomura any idea when will this issue be resolved?

**Comment by satheeshnatarajan** [comment]
> Looks like this was introduced in `dfa@1.2.0`. [foliojs/dfa#4](https://github.com/foliojs/dfa/pull/4) is supposed to fix it, but hasn't been merged yet. In the interim, there is a [temporary solution in that PR](https://github.com/foliojs/dfa/pull/4#issuecomment-562647796) which is to pin `dfa` to version `1.1.0` using `resolutions` in your `package.json` and [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) to keep your `package-lock.json` patched correctly.

Downgrade the `dfa` version to `1.1.0` also not working

**Comment by diegomura** [comment]
Duplicated  #413. Please share all the relevant information there. I'll try to see this. You have to understand that IE 11 support is hard in some occasions
