### ISSUE TITLE
Does lineHeight work?

### ISSUE THREAD

**Issue by maximkott** [diegomura/react-pdf#912]
I have a quick question: Does lineHeight attribute work? It looks like it  does nothing, one of the issues here  mentioned that it wasn't supported back in 2018. 

Thanks!!

**Comment by Canopix** [comment]
Yes works fine for me, look at this that I use for example
`          <Text style={{ marginLeft: "20pt", lineHeight: 1.3 }}>
`

**Comment by maximkott** [comment]
Thanks for the quick reply! I can confirm that lineHeight works with values between 0.1 and 2.7. Anything below or above that range is not working. Obviously I was testing this property with something like 5 or 6 😂This should be mentioned in the docs probably.

For future readers: **lineHeight** value must be between **0.1** and **2.7**

**Comment by tom2strobl** [comment]
I know this is an old issue and closed, but just commenting for anyone like me that comes here through search: bigger lineHeights like eg. 6 nowadays work just fine, no need to clamp. I just wasn't aware that 1 = 100%, as '100%' as value (although the docs say % is a valid value) doesn't work.
