### ISSUE TITLE
Custom Hyphenation rule

### ISSUE THREAD

**Issue by saratonite** [diegomura/react-pdf#913]
Hi its possible to implement custom hyphen rules?

**Comment by diegomura** [comment]
Yes. https://react-pdf.org/advanced#hyphenation

**Comment by dchan-unityrail** [comment]
Similar question: is hyphenationCallback on Text component deprecated? I can't seem to find docs on this and it seems that the repo does not implement this value.

https://github.com/diegomura/react-pdf/blob/3f16559bd5508efceec9da5ffef650f7b2b615c8/index.d.ts#L255

**Comment by bewildergeist** [comment]
@dchan-unityrail I think the docs are wrong, [the actual prop that you can influence on the `Text` component is `hyphenationPenalty`](https://github.com/diegomura/react-pdf/blob/fdbda8bb951832d6748696123447afedfedc9bb5/src/elements/Text.js#L27-L31) which you can set to a sufficiently high number to disable hyphenation in most cases. But you have to guess the correct value, I think 🙃
