### ISSUE TITLE
Certain images are not loading on Chrome

### ISSUE THREAD

**Issue by mrinalmech** [diegomura/react-pdf#914]
**Describe the bug**
Certain images are not loading when used in the `src` prop of the `Image` component on Chrome. It works perfectly on Firefox, but on Chrome a CORS error is thrown.

Error message is `Access to XMLHttpRequest at 'https://vpl-app-dev-user-uploads.s3-us-west-2.amazonaws.com/public/userimages/xs/3bffe950-93f1-11ea-a1cd-2f6574a07234' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**To Reproduce**
1. Create an `Image` component with `src` value `https://vpl-app-dev-user-uploads.s3-us-west-2.amazonaws.com/public/userimages/xs/3bffe950-93f1-11ea-a1cd-2f6574a07234`
2. The `Image` won't load and a CORS error will be thrown

On REPL:

https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659da74e54024a37e582002760d8011000b285000384005c01e8b403755006c02d0f55aa8c0130cba8c20819a6dc3207858800e8200665b108c0770c68230026771e09002f701e7f0f50462d550400230324602d3b07240901082d1402af148033528c004e00560006234aaf5280462366e68c1e1366e00b50d280366a807600161e5ae190af51f92d21112d5e0105aa2d3a0666567602006e3203b200254ee0282e1a00317769162b693c2a4454742c79bdb2200000

**Expected behavior**
The `Image` loads without any CORs errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 81.04
 - React-pdf version: 1.6.8

**Comment by diegomura** [comment]
I see the image. But also, your error shows a CORS issue, which there's nothing I can do rather than asking to use public accesible assets on repl

![Screen Shot 2020-05-27 at 12 47 59 PM](https://user-images.githubusercontent.com/5600341/83042702-55f4fe80-a018-11ea-958b-c9cf80fa06f6.png)
