### ISSUE TITLE
Decimal Units in css

### ISSUE THREAD

**Issue by kle-dev** [diegomura/react-pdf#917]
React PDF have a lot of [valid units](https://react-pdf.org/styling#valid-units) for styling components e.g. pt, in, mm, cm, %, ...

However if you try to fulfill some standards in your PDF like [DIN 2008](https://en.wikipedia.org/wiki/DIN_5008) then you got some trouble because react-pdf aren't recognize decimal numbers in styling, weather in stylesheet neither in styled-components., e.g.:

```
body: {
    paddingTop: 35.12cm,
    paddingBottom: 6.5mm,
  }
```

won't work. It also will not throw any error messages.

You can see it for sure if you compare the body above with

```
body: {
    paddingTop: 35cm,
    paddingBottom: 6mm,
  }
```

then you got a lot difference, more than a few cm or mm !

You can try it out here: https://react-pdf.org/repl

However without this possibility I couldn't use react-pdf for me but you guys did a great work.

thank you

**Comment by diegomura** [comment]
Thanks! I believe this got fixed in the v2, which wasn't officially released yet but it's on npm. What version are you using?

**Comment by kle-dev** [comment]
"@react-pdf/renderer": "^1.6.9",
    "@react-pdf/styled-components": "^1.4.0",
