### ISSUE TITLE
Change file name

### ISSUE THREAD

**Issue by PaBLyS** [diegomura/react-pdf#919]
After generating the PDF document, it opens in a browser named 768386f1-b29c-45cc-862b-9f1b1d0806d7. How can I change this name? I'm not uploading a file, I'm generating a file in PDFViewer

**Comment by diegomura** [comment]
Can you provide an example about how are you generating the file?

**Comment by PaBLyS** [comment]
Here is an example code:

**Comment by PaBLyS** [comment]
Here is an example code:
`export default () => {
    return (
        <PDFViewer>
            <Document>
                <Page size="A4" wrap={true}>
                    <View>
                        <Text>
                            Example
                        </Text>
                    </View>
                </Page>
            </Document>
        </PDFViewer>
    )
}
`
The full version is in the repository https://github.com/PaBLyS/pdf

**Comment by diegomura** [comment]
I think I looked at this way back and couldn't find a way to set the blob name on the browser. Will try to take a look at this again

**Comment by dance-dance-banana-frenzy** [comment]
```js
import { pdf, Document, Page, View, Text } from ''@react-pdf/renderer';
import { saveAs } from 'file-saver';
pdf(
  <Document>
    <Page>
      <View>
        <Text>Hewoe Werlds</Text>
      </View>
    </Page>
  </Document>
).toBlob().then(blob => saveAs(blob, 'MySuperAwesomeFileName.pdf')
```

**Comment by Floriferous** [comment]
Yeah, it'd be great if there was an API like `<PDFViewer fileName="myPdf.pdf" />` to set the default name of the file in the browser.

**Comment by Lulu92270** [comment]
Hello all, I'm having the same issue here. Any update since last post?
```ruby
<BlobProvider document={componentToRender()}>
  {({ url }) => (
    <a 
      href={url} 
      target="_blank" 
      rel="noopener noreferrer"
    >
      Confirm New Tab
    </a>
  )}
</BlobProvider>
```

**Comment by josangelATM** [comment]
> Yeah, it'd be great if there was an API like `<PDFViewer fileName="myPdf.pdf" />` to set the default name of the file in the browser.

Waiting for this implementation, such a Great idea.

**Comment by csulit** [comment]
> Yeah, it'd be great if there was an API like `<PDFViewer fileName="myPdf.pdf" />` to set the default name of the file in the browser.

This is the clean implementation.

**Comment by Unforgiven-wanda** [comment]
I need this as well. Any way to implement this now on our end while we wait for an official fix?

**Comment by bgbbmm** [comment]
bump. also interested in this feature.

**Comment by andremalta-dev** [comment]
I need this one as well.

**Comment by jeetiss** [comment]
hey folks! 
As I read here https://stackoverflow.com/questions/53548182/can-i-set-the-filename-of-a-pdf-object-displayed-in-chrome

Ugly workaround with sending file through service worker is only one solution that works in chrome and I think that it's not valid for `@react-pdf`

I created [codesandbox](https://codesandbox.io/s/polished-https-uvzew?file=/src/App.js) that works in `ff`, but not in chrome. if you have any suggestions, please share!

**Comment by anasuyabarik123** [comment]
> ```js
> import { pdf, Document, Page, View, Text } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> pdf(
>   <Document>
>     <Page>
>       <View>
>         <Text>Hewoe Werlds</Text>
>       </View>
>     </Page>
>   </Document>
> ).toBlob().then(blob => saveAs(blob, 'MySuperAwesomeFileName.pdf')
> ```

**Comment by mgoldenbe** [comment]
Any progress on this issue?

**Comment by mgoldenbe** [comment]
> ```js
> import { pdf, Document, Page, View, Text } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> pdf(
>   <Document>
>     <Page>
>       <View>
>         <Text>Hewoe Werlds</Text>
>       </View>
>     </Page>
>   </Document>
> ).toBlob().then(blob => saveAs(blob, 'MySuperAwesomeFileName.pdf')
> ```

This solution is not working for me:

```
const MyDocument = ({course, order}) => (
  pdf(
  <Document>
    <Page size="A4" style={styles.page}>
      <Image style={styles.logo} src={logo} />
      <InvoiceTitle title='Invoice / Tax Receipt'/>
      <InvoiceNo order={order}/>
      <BillTo order={order}/>
      <InvoiceItemsTable course={course} order={order} />
      <InvoiceThankYouMsg />
    </Page>
  </Document>
  ).toBlob().then(blob => saveAs(blob, 'MySuperAwesomeFileName.pdf'))
);
```

I get `Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.`

**Comment by adityatoshniwal** [comment]
Waiting for this.

**Comment by yrohit299** [comment]
Any progress on this. Will be great if anyone could help on this.

**Comment by agomez49** [comment]
+1 to this 

> Yeah, it'd be great if there was an API like `<PDFViewer fileName="myPdf.pdf" />` to set the default name of the file in the browser.

**Comment by seanonthenet** [comment]
+1 for specifying file name please 🙏

**Comment by dance-dance-banana-frenzy** [comment]
> > ```js
> > import { pdf, Document, Page, View, Text } from '@react-pdf/renderer';
> > import { saveAs } from 'file-saver';
> > pdf(
> >   <Document>
> >     <Page>
> >       <View>
> >         <Text>Hewoe Werlds</Text>
> >       </View>
> >     </Page>
> >   </Document>
> > ).toBlob().then(blob => saveAs(blob, 'MySuperAwesomeFileName.pdf')
> > ```
> 
> This solution is not working for me:
> 
> ```js
> const MyDocument = ({course, order}) => (
>   pdf(
>   <Document>
>     <Page size="A4" style={styles.page}>
>       <Image style={styles.logo} src={logo} />
>       <InvoiceTitle title='Invoice / Tax Receipt'/>
>       <InvoiceNo order={order}/>
>       <BillTo order={order}/>
>       <InvoiceItemsTable course={course} order={order} />
>       <InvoiceThankYouMsg />
>     </Page>
>   </Document>
>   ).toBlob().then(blob => saveAs(blob, 'MySuperAwesomeFileName.pdf'))
> );
> ```
> 
> I get `Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.`

It looks like you've got a bunch of custom objects there. I'd drill down into each one and verify that they all resolve to the objects from `@react-pdf/renderer` (View, Text, Link, Image, Canvas) or `@react-pdf/styled-components`.

Are you using code splitting with loadable components? This often involves promises as indicated in the error message that you reported. Make sure that the module is resolved as a component first before rendering it. Rather than using `import Foo from './Foo';`, you may need `import('./Foo').then(Foo => { // now render with Foo... });`. I've since switched to React.lazy - but it's the same workflow...

```js
// Foo.jsx
import React from 'react';
import { Text } from '@react-pdf/renderer';
const Foo = () => (<Text>Hewoe Werlds</Text>);
export default Foo;

// LazyFoo.js
import { lazy } from 'react';
export default lazy(() => import('./Foo'));

// PDF.jsx
import React from 'react';
import { pdf, Document, Page, View } from '@react-pdf/renderer';
import { saveAs } from 'file-saver';

import('./LazyFoo').then(({ default: Foo }) => {
    pdf(
        <Document>
            <Page>
                <View>
                    <Foo />
                </View>
            </Page>
        </Document>
    ).toBlob().then(blob => saveAs(blob, 'MySuperAwesomeFileName.pdf'));
});
```

**Comment by Selenestica** [comment]
Any progress on this? Would be awesome for the file name to not be a string of random numbers and letters!

**Comment by chessyfor3** [comment]
<Document title="name of the file"></Document>

**Comment by vdebergue** [comment]
It seems like for firefox, it will try to get the filename from the url or from the pdf metadata:

https://github.com/mozilla/pdf.js/blob/26ae50e4494aa57b31f305df759fb44ae8be4cd7/web/app.js#L768-L772=
https://github.com/mozilla/pdf.js/blob/26ae50e4494aa57b31f305df759fb44ae8be4cd7/src/display/display_utils.js#L354

So adding in the iframe url the data like `<blob_url>#<options>,filename=<filename>.pdf` seems to work for Firefox.
A bit like the toolbar option: https://github.com/diegomura/react-pdf/blob/master/packages/renderer/src/dom/PDFViewer.js#L21-L23=

However it does not seem to work on Chrome (I haven't look at how Chrome handles its Pdf files)

**Comment by bryantobing12** [comment]
any update?

**Comment by AnoplexAdmin** [comment]
+1 Also need this

**Comment by jeetiss** [comment]
set `title` to `Document` component and chrome will display it instead of random data

<img width="566" alt="Снимок экрана 2023-02-20 в 14 20 22" src="https://user-images.githubusercontent.com/6726016/220093124-ca9ea830-fa0b-4d65-95f1-0ab639d2d10b.png">

**Comment by shanifdhanani** [comment]
> set `title` to `Document` component and chrome will display it instead of random data
> 
> <img alt="Снимок экрана 2023-02-20 в 14 20 22" width="566" src="https://user-images.githubusercontent.com/6726016/220093124-ca9ea830-fa0b-4d65-95f1-0ab639d2d10b.png">

I was having the same issue. Where should we set the "title" field?

**Comment by PrinceSP** [comment]
all the answer here is outdated

**Comment by PrinceSP** [comment]
> set `title` to `Document` component and chrome will display it instead of random data
> 
> <img alt="Снимок экрана 2023-02-20 в 14 20 22" width="566" src="https://user-images.githubusercontent.com/6726016/220093124-ca9ea830-fa0b-4d65-95f1-0ab639d2d10b.png">

yes it will replace the random string, but still when we click the download button from toolbar, the file name automate generate with random string.

**Comment by jeetiss** [comment]
use this code https://codesandbox.io/s/polished-https-uvzew?file=/src/App.js to change the file name

**Comment by PrinceSP** [comment]
> https://codesandbox.io/s/polished-https-uvzew?file=/src/App.js

only works on safari and firefox, but not in chrome

**Comment by jeetiss** [comment]
to change the title in chrome you have to set `title` to the `Document` component

**Comment by PrinceSP** [comment]
<img width="629" alt="Screen Shot 2023-02-24 at 16 49 05" src="https://user-images.githubusercontent.com/30646160/221134057-b0f07b8a-7afc-413e-8a94-3cb29bd36d90.png">

I add it already before using your solution, but still not working at all

**Comment by PrinceSP** [comment]
> sorry, i test it again and yes, it doesn't work in chrome so `title` will be with the name but file is still random

is there any way to fix it?

**Comment by asharafshahi** [comment]
+1 vote for this feature, such a no-brainer.

**Comment by CharlieCam** [comment]
+ 1! Need this feature

**Comment by michac789** [comment]
+1 need this too

**Comment by Fziliotti** [comment]
+1! Need this feature

**Comment by toddmcintosh** [comment]
+1 for me as well. Can we get more information about what the blocking issues are? 

Perhaps the community could be more helpful if we knew more about why this seemingly simple feature add is blocked by deeper issues in the rendering pipeline.

**Comment by rhuanbello** [comment]
+1

**Comment by jacobrien** [comment]
+1

**Comment by guerchen** [comment]
+1

**Comment by codingforfoodllc** [comment]
+1

**Comment by Shameekh-Naveed** [comment]
+1 need

**Comment by JoeMartin2001** [comment]
Why did it get closed?

**Comment by ua-knight** [comment]
Can we open this again, please?
Setting the title on the Document component only solves half of the problem. Like others have commented above, when downloading in Chrome the default filename is still random.

**Comment by arctic-apricity** [comment]
So, just to clear up some confusion, I just want to clarify how the PDFViewer component works, because I was confused about this as well. The usePDF.js component calls URL.createObjectURL(blob) to create a link to the file, which is then passed to PDFViewer to render out that link in an iframe using your browsers default PDF viewer. The library itself not only does not, but cannot control the name of the download link, as it is determined by the URL.createObjectURL function alone, and so that is why this ticket was rightfully closed.

**Comment by ua-knight** [comment]
Ok. Thanks for the clarification.

**Comment by Vituli** [comment]
some update about how to change the name of file?

**Comment by arctic-apricity** [comment]
> some update about how to change the name of file?

I ended up just using Maroto to generate PDF files on the backend and from there I just passed the blob down to the client app for rendering.

**Comment by Mitchell8210** [comment]
Figured out a sort of way around the whole cannot set file name when downloading the file, at least on web. Check out the PDFDownloadLink component that is in the library, you can set the file name that you want with that component like so...

`import { PDFDownloadLink } from "@react-pdf/renderer";`

`<PDFDownloadLink document={<YourDocumentComponent />} fileName="MyFile.pdf">
            Click me
  </PDFDownloadLink>`
  
  This does not solve the problem that occurs when you are showing the preview to the user but at least it is something you may be able to use so that you can set the filename that you want when your users click to download the file.

**Comment by EmilioJD** [comment]
this feature should definitely be added to PDFViewer tbh

**Comment by rfgonzalezweb** [comment]
I was able to put this _**solution**_ together.
I added a floating download button on top of my PDFViewer and this is how it looks:
(link to the demo below, I hope it helps)
![Screenshot from 2024-11-24 15-26-06](https://github.com/user-attachments/assets/777ec9ee-d435-49e1-b35b-0d891934dc4b)

https://stackblitz.com/edit/vitejs-vite-uifzpk?file=src%2FApp.jsx
The file is saved with the intended filename :raised_hands:

**Comment by swayamterode** [comment]
> Figured out a sort of way around the whole cannot set file name when downloading the file, at least on web. Check out the PDFDownloadLink component that is in the library, you can set the file name that you want with that component like so...
> 
> `import { PDFDownloadLink } from "@react-pdf/renderer";`
> 
> `<PDFDownloadLink document={<YourDocumentComponent />} fileName="MyFile.pdf"> Click me </PDFDownloadLink>`
> 
> This does not solve the problem that occurs when you are showing the preview to the user but at least it is something you may be able to use so that you can set the filename that you want when your users click to download the file.

Worked for me in (Next.js 15) thanks!

**Comment by AlejandroYYWireless** [comment]
They shouldnt close it, should be re-opened, we all know its not solved.

**Comment by Hatko** [comment]
Should be reopened - still an issue

**Comment by AymanReverto** [comment]
+1

**Comment by DanielCruz12** [comment]
import { saveAs } from 'file-saver';
...

// Genera un PDF desde el contenido HTML y lo descarga automáticamente con un nombre personalizado
await pdf(
  <Document title={`RCV ${empresa} ${obtenerNombreMes(mes)}-${year}`}>
    <Page size="A2" orientation="landscape">
      <Html>{html}</Html>
    </Page>
  </Document>
)
  .toBlob()
  .then((blob) => {
    setPdfData(blob); // Almacena el PDF para mostrarlo en pantalla si es necesario
    saveAs(blob, `RCV ${empresa} ${obtenerNombreMes(mes)}-${year}`); // Descarga con nombre personalizado
  });

**Comment by BrahimTheUser** [comment]
you can use this library to view the PDF: @react-pdf-viewer
and control the name of the download:



import { OpenFile } from '@react-pdf-viewer/core';

const getFilePluginInstance = getFilePlugin({
    fileNameGenerator: (file: OpenFile) => {
        // `file.name` is the URL of opened file
        const fileName = file.name.substring(file.name.lastIndexOf('/') + 1);
        return `a-copy-of-${fileName}`;
    },
});



here is the link: https://react-pdf-viewer.dev/examples/customize-the-name-of-download-file/

**Comment by ttnghia195** [comment]
If you mean this. Just push a title in Document

`<Document title={fileName}>
      <Page size="A4" style={styles.page}>
        ...
      </Page>
    </Document>` 

<img width="1726" height="882" alt="Image" src="https://github.com/user-attachments/assets/70dd6ef9-88cb-4e4f-bc10-66bb60395f18" />

**Comment by ua-knight** [comment]
No. The problem is that when you click the inherited download button, the icon in the top bar (the leftmost icon in the right end group of icons), the save dialog which comes up doesn't have the document title set as the default filename. Instead it has a random name. It seems it cannot pickup the document title, despite it being present in the same context (the top bar context).

**Comment by 24f2003005** [comment]
+1 Need the filename directly pass as the props

**Comment by black23cat** [comment]
+1
