### ISSUE TITLE
[V2] Page wrapping messing page order

### ISSUE THREAD

**Issue by oswaldoacauan** [diegomura/react-pdf#920]
**Describe the bug**
The page order gets messed up.

**To Reproduce**
We have lots of custom styles so right now I don't have a reproducible example with code. I will try to reproduce it in a REPL later.

**Expected behavior**
The page order being preserved.

 - React-pdf version [2.0.0-beta.4]

**Comment by oswaldoacauan** [comment]
@diegomura update:

I can locally consistently break the page order with the following document:
```js
	<Document>
      <Page>
        <Text>1</Text>
      </Page>
      <Page>
        <Text>2</Text>
      </Page>
      <Page>
        <Text>3</Text>
      </Page>
      <>
        <Page>
          <Text>A</Text>
        </Page>
        <Page>
          <Text>B</Text>
        </Page>
        <Page>
          <Text>C</Text>
        </Page>
        <Page>
          <Text>D</Text>
        </Page>
        <Page>
          <Text>F</Text>
        </Page>
        <Page>
          <Text>G</Text>
        </Page>
        <Page>
          <Text>H</Text>
        </Page>
        <Page>
          <Text>I</Text>
        </Page>
        <Page>
          <Text>J</Text>
        </Page>
      </>
      <Page>
        <Text>4</Text>
      </Page>
      <Page>
        <Text>5</Text>
      </Page>
      <Page>
        <Text>6</Text>
      </Page>
    </Document>
```

**Comment by diegomura** [comment]
Mmm... interesting. Wonder if it's related with the fragments around a group of pages. To be honest I never tested that. What happens if you remove the fragment?

**Comment by oswaldoacauan** [comment]
@diegomura same results. I also tried to downgrade to 1.6.9 and the issue still happens. The odd thing is that I can't reproduce it in the Sandbox.

One thing that is different from our setup to the Sandbox is that we generate this PDF in the server-side with `renderToStream`.

```
const stream = await ReactPDF.renderToStream(<Test />);
const buffer = await getBuffer(stream);
return res.end(buffer);
```

**Comment by diegomura** [comment]
Can't think why rendering it in the server might have something to do with this 😞  Can't test right now but will try to do asap.

**Comment by oswaldoacauan** [comment]
@diegomura I can confirm that downgrading to 1.6.9 fix the issue. 👍

**Comment by diegomura** [comment]
Got it thanks. Will try to debug today. If you feel like giving a try, it would be easy to see where this happens by logging how the layout looks while it's executed [here](https://github.com/diegomura/react-pdf/blob/v2/src/layout/index.js#L25). Layout is in v2 a composition of small steps, you can log the intermediate node by adding `R.tap(console.log)` at any moment of that pileline. Somewhere in the middle the order is being changed, but not sure if it's on pagination or where

**Comment by oswaldoacauan** [comment]
@diegomura from what I could debug the last iteration is the one that mess up the page ordering.

**Comment by diegomura** [comment]
Uploaded `2.0.0-beta.6` fixing this I think. Couldn't reproduce the issue with the example provided though. But I believe this was caused by some zindex style on your pages. Let me know if get's fixed

**Comment by oswaldoacauan** [comment]
@diegomura I can confirm that `2.0.0-beta.6` fixes the issue. Thank you very much   for the fast response and fix. 👏
