### ISSUE TITLE
SVG node of type circle is not currenty supported

### ISSUE THREAD

**Issue by jakeopie** [diegomura/react-pdf#921]
Hi There, 

I'm being trying to test if I can include a SVG element in a PDF document. I get the following type of warning message and the SVG is not in the PDF, doesn't matter what type of SVG element I try. 

SVG node of type circle is not currenty supported
SVG node of type line is not currenty supported

I am using @react-pdf/renderer@^2.0.0-beta.6

I'm using the following code:
import { Page, Text, View, Document, StyleSheet,PDFDownloadLink,Svg } from '@react-pdf/renderer';

    <Document>
        <Page size="A4" style={styles.page} >
          <View style={styles.section}>
            <Text>Before circle</Text>
          </View>

            <Svg width="500" height="210">
              <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
              <line x1="0" y1="0" x2="200" y2="200" style="stroke:rgb(255,0,0);stroke-width:2" />
            </Svg>

          <View style={styles.section}>
            <Text>After circle</Text>
          </View>
        </Page>
      </Document>

**Comment by JacobFischer** [comment]
Although I can't find any official documentation about SVGs in v2 of this project, by exaiming the source I've found SVG support is indeed present using their Uppercased SVG elements. So switch `circle` to `Circle`, and `line` to `Line` (and import them).

Example:
```jsx
import { Circle, Line, Svg } from '@react-pdf/renderer';
import React from 'react';

const YourSvg = () => (
  <Svg width="500" height="210">
    <Circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
    <Line x1="0" y1="0" x2="200" y2="200" style="stroke:rgb(255,0,0);stroke-width:2" />
  </Svg>
);
```

Does this fix your issue?

**Comment by diegomura** [comment]
Thanks @JacobFischer ! That is exactly right. Everything that's inside the PDF document should be a pdf primitive (the same way you don't add `div` to your react-native app). Plan to release the 2.0 very soon and I'll include docs for it
