### ISSUE TITLE
React-Pdf website is down

### ISSUE THREAD

**Issue by ezrasmith-sf** [diegomura/react-pdf#922]
https://react-pdf.org is timing out again and again. The server seems down. Is there any other source to find the documentation for this library? thanks

**Comment by diegomura** [comment]
It's up for me. Do you mind checking again?

**Comment by MariuszKogut** [comment]
Works also fine for me (accessing it from Germany)...

**Comment by diegomura** [comment]
Thanks @MariuszKogut . Closing this
