### ISSUE TITLE
Unable to use DownloadLink with the code in the docs

### ISSUE THREAD

**Issue by ys27** [diegomura/react-pdf#924]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/advanced#dynamic-content/#on-the-fly-rendering
2. Run the code inside the Download Link section:
```
import { PDFDownloadLink, Document, Page } from '@react-pdf/renderer'

const MyDoc = () => (
  <Document>
    <Page>
      // My document data
    </Page>
  </Document>
)

const App = () => (
  <div>
    <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
      {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
    </PDFDownloadLink>
  </div>
)
```

I've also tried putting <div>Test text</div> instead of the comment inside the Page component.

3. I get `index.js:1 TypeError: Cannot read property 'height' of undefined at setNodeHeight` in the console
4. The link is stuck at 'Loading document...'

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

The link to turn into a clickable, downloadable link that supplies the pdf.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.14
 - Browser Chrome Version 83.0.4103.61 (Official Build) (64-bit)
 - React-pdf version 2.0.0-beta.6

**Comment by german-st** [comment]
Hello @diegomura.
I have a same problem. I get: `Cannot read property 'height' of undefined`
I'm trying to make a document using Canvas. My task is to upload multipages reports to pdf file.
Tahnk's

My code:

`import React from 'react';
import './App.css';
import { PDFDownloadLink, Document, Page, View, Text, StyleSheet, Canvas } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    flexDirection: 'row',
    backgroundColor: '#E4E4E4',
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1
  }
});

const MyDoc = () => (
  <Document>
    <Page size="A4">
      <View style={styles.section}>
        <Canvas style={{ width: 400, height: 400 }}>
          <table border="1">
            <caption>Shoes table</caption>
            <tr>
              <th>One</th>
              <th>Two</th>
              <th>Three</th>
              <th>Four</th>
            </tr>
            <tr><td>34,5</td><td>3,5</td><td>36</td><td>23</td></tr>
            <tr><td>35,5</td><td>4</td><td>36⅔</td><td>23–23,5</td></tr>
            <tr><td>36</td><td>4,5</td><td>37⅓</td><td>23,5</td></tr>
            <tr><td>36,5</td><td>5</td><td>38</td><td>24</td></tr>
            <tr><td>37</td><td>5,5</td><td>38⅔</td><td>24,5</td></tr>
          </table>
        </Canvas>
      </View>
    </Page>
  </Document>
)

const App = () => (
  <div>
    <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
      {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
    </PDFDownloadLink>
  </div>
)

export default App;`

**Comment by sreimer15** [comment]
I'm getting this error when trying to renderPdfToStream
Something like...
```
    const pdfStream = await ReactPDF.renderToStream(<PaymentAgreement {...information} />);
```
The pdf does generate when rendering as a file however

**Comment by okdistribute** [comment]
createTextIsntance react-pdf/renderer@beta (v2 branch) is broken. It should do this: https://github.com/diegomura/react-pdf/blob/master/src/renderer.js#L39-L44

Using @react-pdf/renderer@1.6.10 doesnt give this error.

**Comment by Nickman87** [comment]
I had the same issue, reverting back to 1.6.11 was not an option but I think I found my problem:

I had two children inside a <Text> node like this:
`<Text>{"some string"} other string</Text?`

Removing this solved the issue for me

**Comment by akshaykatariyaa** [comment]
I am too facing the same issue. Has anyone solved it ? Or is there any library from converting react component to PDF

**Comment by diegomura** [comment]
So many things going on at the same time here 😅 

@ys27 if you are running that exactly, it will fail since `// My document data` it's not a valid react-pdf child. The example is simplified for demo purposes, I thought that was clear sorry. You should use `View`, `Image`, `Text` or other primitives inside the page

@german-st You are rendering dom nodes inside the PDF document. You should stick with the react-pdf primitives that are in the doc. This is not an html renderer

@akshaykatariyaa based on your comment you are also trying to render dom components to PDF. You should stick to react-pdf primitives as well. react-pdf does not provide a way to transform existing components to react-pdf primitives. 

Anyone feel free to create another issue but I think all these (somehow unrelated) things were answered 😄

**Comment by arjitacharya1994** [comment]
> I had the same issue, reverting back to 1.6.11 was not an option but I think I found my problem:
> 
> I had two children inside a node like this:
> `<Text>{"some string"} other string</Text?`
> 
> Removing this solved the issue for me

Yes, @Nickman87 . Template strings inside single <Text> tag is not supported. Putting them in different tags fixed my issue. Thanks!

**Comment by vipul-digiqt** [comment]
index.js:1 TypeError: Cannot read properties of undefined (reading 'height')

Here I am trying to put a graph inside a pdf 

Have tried above solutions

**Comment by kamkyi** [comment]
I simply added <Text></Text> inside <Page> Tag.. the error gone ..
