### ISSUE TITLE
Issue with not entering a password for password-protected PDFs

### ISSUE THREAD

**Issue by jordangarvey** [diegomura/react-pdf#925]
**Describe the bug**
When a PDF is password protected, clicking cancel in the password model dismisses it but immediately opens up a new modal. Telling the browser to not open any more popups causes the browser to freeze.

**To Reproduce**
1. Render a PDF comprised of just a `<Document>` with some `<Page>` elements inside. The file it is loading is password-protected
2. The browser’s “enter password” popup appears
3. Click cancel in the popup
4. A new modal popup appears straight away, so I cannot interact with the page

**Note** entering the correct password renders the document normally.

**Expected behaviour**
The password popup to not reappear, and I assume the PDF would fail to display.

**Screenshots**
![password-pdf-issue](https://user-images.githubusercontent.com/19172633/83862328-b02d4800-a719-11ea-8a57-d13f08df7e3c.gif)

**Desktop:**
 - OS: Mac & Windows
 - Browser: Tested on Firefox & Chrome
 - React-pdf version: ^4.1.0

As a workaround for this, I’ve been looking at the `onPassword` callback that exists on `Document`, although I’m not sure what the function should return for it to work, so any help on that too would be greatly appreciated.

**Comment by jose920405** [comment]
This module is `@react-pdf/renderer` not `react-pdf` are different.

Please create this issue in the correct repository

**Comment by diegomura** [comment]
Thanks @jose920405
