### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Jay-2019** [diegomura/react-pdf#926]
**Describe the bug**

**Expected behavior**
i am trying to generate a dynamic pdf with react-pdf/renderer, simple i'm trying to store api data and send it to <InvoiceTableBody />
if i am remove setFeeData inside the useEffect it works great. or if i replace setFeeData with console.log(response.data) then it render pdf in ifram and also work well   
<PDFDownloadLink document={<MyReceipt />} fileName="someName.pdf">
         {({ blob, url, loading, error }) =>
           loading ? "Loading document..." : "Download now!"
         }
       </PDFDownloadLink>

**Screenshots**

![](https://user-images.githubusercontent.com/47723510/83939609-f8249b80-a7fb-11ea-8f28-d820123cfa2a.PNG)

![](https://user-images.githubusercontent.com/47723510/83939555-8d736000-a7fb-11ea-969f-586318800dcf.PNG)

![image](https://user-images.githubusercontent.com/47723510/83939856-b5fc5980-a7fd-11ea-8875-28412c8d8f9b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - React-pdf version: "^2.0.0-beta.6"

**Comment by talhafayyaz12** [comment]
did you find anything on this??

**Comment by diegomura** [comment]
Fixed already in latest version in [here](https://github.com/diegomura/react-pdf/blob/6ea172340b0e89b01a985e91eee257c43b243c54/packages/renderer/src/renderer.js#L116). Thanks!
