### ISSUE TITLE
Font family for main and highlighted text is different

### ISSUE THREAD

**Issue by ash-developer** [diegomura/react-pdf#927]
**Describe the bug**
If you try to select any text even at demo (https://react-pdf.org/repl) then selected text has different font-family to compare with pdf text

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to 'https://react-pdf.org/repl'
2. select any text
3. See error

**Expected behavior**
Font-family is the same

**Screenshots**
![image](https://user-images.githubusercontent.com/7757264/84763277-9b339d00-afd4-11ea-8640-a4a0d86e11d5.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - React-pdf version 1.6.7

**Comment by diegomura** [comment]
That's an issue from the REPL (not within the library itself) and it's because it uses [PDF.js](https://mozilla.github.io/pdf.js/) to render the document on screen. PDF.js apparently has this issue, since it renders the document using SVG and uses an "invisible" text element to enable selection.
