### ISSUE TITLE
Is there an easy way to use external CSS to render Text, for instance Prismjs ?

### ISSUE THREAD

**Issue by RealSlimMahdi** [diegomura/react-pdf#930]
I would like to use your library to render create a pdf from HTML.
One important feature would be Code syntax highlighting.
Do you think it is achievable? I could not find anything in your documentation.

Thanks,

**Comment by StructByLightning** [comment]
Support for external stylesheets would be awesome. StyledComponents or the stylesheet js object are both really clunky compared to a regular scss file.

**Comment by diegomura** [comment]
External CSS should be implemented separately from this lib. CSS can come from various sources and obviously we cannot ship this lib considering those. React-pdf ships a clear and concise interface so it's reliable and maintainable. Any further integration should be done separately
