### ISSUE TITLE
pageNumber, totalPages not working in render function in <Text>

### ISSUE THREAD

**Issue by kirylh** [diegomura/react-pdf#931]
const PdfDocument = (props) => {
  return (
    <Document>
      <Page size="A4">
        <View style={styles.row}>
          <View style={styles.col}>
            <Text>Section #1</Text>
          </View>
          <View style={styles.col}>
            <Text>Section #2</Text>
          </View>
        </View>
        <View style={styles.col}>
          <Text style={styles.text}>Just a text</Text>
        </View>
        **<Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />**
      </Page>
    </Document>
  )
}

export default PdfDocument;

Paging is not showing in generated pdf document:

              <PDFDownloadLink document={<PdfDocument />} fileName={`somename${Math.floor(Math.random() * 1000)}.pdf`}>
                {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
              </PDFDownloadLink>

**Comment by jrishabh431** [comment]
Facing the same issue.

**Comment by christianquispe** [comment]
Here the same issue.

**Comment by christianquispe** [comment]
Hi! Maybe here is the [solution](https://github.com/diegomura/react-pdf/issues/923#issuecomment-646897027)

**Comment by kirylh** [comment]
Working with setting minHeight css property. It doesn't explain why static texts work without this css trick.

**Comment by Nichtkunst** [comment]
render is also not working for View
