### ISSUE TITLE
How do get blob data of pdf?

### ISSUE THREAD

**Issue by buzztnt** [diegomura/react-pdf#932]
I'm trying to use the BlobProvider to get the blob data:

```
MyDocument = () => {
        return (
            <Document>
                <Page size="A4" style={stylez.page}>
                    <View style={stylez.section}>
                        <Text>Section TesterYo</Text>
                    </View>
                    <View style={stylez.section}>
                        <Text>Section #2</Text>
                    </View>
                </Page>
            </Document>
        )
    }

 LoadPdf = () => {
        let myPdf = <BlobProvider document={this.MyDocument()}/>
        var file = new File([myPdf], 'filename.pdf', { type: 'application/pdf', lastModified:Date.now()});


        this.setState({ files: [...this.state.files, file] }, () => console.log(this.state))
 }
```

This does not return MyDocument

Any insight on this would be appreciated

**Comment by Lu-Ks** [comment]
Hi @buzztnt 

```
let blobPDF = pdf(this.MyDocument()).toBlob();
```
carefull it's a **promise** 
```
const myfunction async () => {
    let blobPDF = await pdf(this.MyDocument()).toBlob();
}
```

**Comment by brvnonascimento** [comment]
```javascript
import { Document, Page, Text, View, pdf } from '@react-pdf/renderer';

const NewDocument = () => {
  return (
      <Document>
          <Page size='A4' >
              <View>
                  <Text>Hello</Text>
              </View>
          </Page>
      </Document>
  )
}

const OtherFC = () => {
   const getPdfBlob = async () =>   {
       let blobPdf = await pdf(NewDocument()).toBlob();

       console.log(blobPdf);
   }

   return(
     <button onClick={getPdfBlob}>Hello</button>
   )
}
```

When I try the example above I have an error:

```javascript````
react-pdf.browser.es.js:4251 Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined
    at fetchAssets (react-pdf.browser.es.js:4251)
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
    at resolveAssets (react-pdf.browser.es.js:4293)
    at _callee$ (react-pdf.browser.es.js:6844)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
fetchAssets @ react-pdf.browser.es.js:4251
(anonymous) @ _pipe.js:3
(anonymous) @ _pipe.js:3
(anonymous) @ _arity.js:10
resolveAssets @ react-pdf.browser.es.js:4293
_callee$ @ react-pdf.browser.es.js:6844
tryCatch @ runtime.js:45
invoke @ runtime.js:274
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:3
````
That refers to this function in the module:

```javascript````
var fetchAssets = function fetchAssets(node) {
  var promises = [];
  var listToExplore = node.children.slice(0);

  while (listToExplore.length > 0) {
    var _node = listToExplore.shift();

    if (isImage(_node)) {
      promises.push(fetchImage(_node));
    }

    if (_node.style && _node.style.fontFamily) {
      promises.push(Font$1.load(_node.style));
    }

    if (typeof _node === 'string') {
      promises.push.apply(promises, fetchEmojis(_node));
    }

    if (typeof _node.value === 'string') {
      promises.push.apply(promises, fetchEmojis(_node.value));
    }

    if (_node.children) {
      _node.children.forEach(function (childNode) {
        listToExplore.push(childNode);
      });
    }
  }

  return promises;
};
```

**Comment by mateo2181** [comment]
@brvnonascimento I have the same error.

**Comment by NoriyukiMatsumoto** [comment]
I faced the same problem.
I solved it by changing the version from 2.0.0-bata.6 to 1.6.9.

**Comment by mateo2181** [comment]
I tried that but I get error "Uncaught Error: Type mismatch"

**Comment by brvnonascimento** [comment]
Downgrading to 1.6.9 made possible to get the blob data, that way I managed to make it work with a Web Worker so it's non UI-blocking and really fast!

**Comment by Lu-Ks** [comment]
My bad, I'm using react-pdf V1.6.9 too

**Comment by brvnonascimento** [comment]
Should this become an issue "Imperative Blob Data doesn't work on beta2.0"?

**Comment by rmathis** [comment]
@brvnonascimento I've found in 2.0 beta I am able to call "updateContainer" to populate the pdf and avoid the errors you mentioned.
`
const doc = <Document></Document>;
const blobPdf = await pdf(doc);
blobPdf.updateContainer(doc);
const result = await pdf.toBlob();
`
I am curious though how are you offloading the process to a web worker? Would you mind giving an example of how you would do this?

**Comment by brvnonascimento** [comment]
@rmathis Wow, it worked beautifully! I'll be posting a repo here with my Webpack config and all the caveats as a working example with WebWorkers.

**Comment by afficiona** [comment]
Thank you, @rmathis for this amazing solution. I was banging my head to get a workaround this. But I am also anticipating this might break when there's an appropriate fix in the latest beta version.

**Comment by rmathis** [comment]
The `pdf` function seems to be calling it itself anyway, I suspect its just extra call that may be unnecessary.

**Comment by luskin** [comment]
Has anyone been able to get this working? We need to create a PDF from an express server. We are just about there, but we can't seem to get the blob data to return properly. We continuously get the error: `Blob is not a constructor`


```typescript
import React from 'react'
import { pdf, Document, Page, View, Text } from '@react-pdf/renderer'

const MyDocument = () => (
  <Document>
    <Page>
      <View>
        <Text>Text Test</Text>
      </View>
    </Page>
  </Document>
)
```

```typescript

export const createDocumentBlob = async (): Promise<unknown> => {
  try {
    const doc = MyDocument()
    const blobPdf = await pdf(doc)
    const blob = await blobPdf.toBlob()
    return blob
  } catch (e) {
    console.error('Error Thrown: ', e)
  }
  return null
}
```

**Comment by simpleneerajmynx** [comment]
Working fine from my side
