### ISSUE TITLE
How can I use react-pdf in commonJS in Node ?

### ISSUE THREAD

**Issue by YoannBuzenet** [diegomura/react-pdf#937]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to use react-pdf server-side to use the same template I'm using React side to render some PDFs. But I have difficulties implenting it in commonJS.

**Describe the solution you'd like**
Would you know a way to implement a react-pdf comonent with context in commonJS ?

**Describe alternatives you've considered**
I'm thinking about passing my whole app into ECMAscripts modules to be able to run react-pdf with the code that runs normally.

Thank you for this awesome library and work :)
We'll find a way !

**Comment by diegomura** [comment]
We ship a CJS build, so should be possible. Hope you found a way
