### ISSUE TITLE
Blob data renders as blank doc when sent to server 

### ISSUE THREAD

**Issue by darraghpjones** [diegomura/react-pdf#939]
Hi, 

I'm rendering a pdf document on a client, which I then subsequently want to sent to a storage server.   The PDF displays correctly on the browser (using the URL object) but when the blob data is sent to the server using formdata the pdf renders as a blank page.  

Client Code: 
```
<BlobProvider document={doc} filename={filename}>
        {({ blob, url, loading }) => (
          !loading && <FontAwesomeIcon icon={faFileDownload} onClick={() =>  sendToServer(blob) }/>)}
</BlobProvider>

const sendToServer = (blob) => {
    var formData = new FormData();
    formData.append('pdf', blob);

    fetch('/files', {
      method: 'POST',
      body: formData,
    })
  };
```

Server Code: 
```
var upload = multer();
var processUpload = upload.single('pdf');

app.post('/files', processUpload, function(req, res) {
  fs.writeFileSync('buffer.pdf', req.file); // or req.file.buffer

  // file is a valid, but blank pdf
});
```
Am I doing something wrong in encoding the file or not waiting for the render to finish?  I can't see what it is.  If I examine the pdf on the server side I can see the meta data has correctly been written by react-pdf so I don't believe its getting corrupted on the fly.  

Many thanks,
Darragh

**Comment by darraghpjones** [comment]
Found alternative solution

**Comment by ShayanShokat** [comment]
@darraghpjones can you share your alternate solution? 
I'm trying to send the dynamically rendered pdf component to our server and byte stream.

**Comment by makeupsomething** [comment]
@ShayanShokat What kind of problems are you having uploading? Or have you already solved it?

I had luck with an alternative solution with a custom hook found here https://github.com/diegomura/react-pdf/issues/1000

**Comment by ShayanShokat** [comment]
@makeupsomething I've solved it, first I convert the pdf to a blob, and then add fillename, and last modified date to convert it to file, and send the file to backend for storing.
Here's my approach:
`
import {  pdf} from '@react-pdf/renderer';

const element = <MyPdf ...params />;//my pdf component
const myPdf = pdf({}); 
myPdf.updateContainer(element);
const blob = await myPdf.toBlob();
var file = new File([blob], filename, {lastModified: (new Date()).getTime()});
const formData = new FormData();
formData.append('file', file);
fetch(url, {
     method: "POST", 
     body: formData
})

`

**Comment by makeupsomething** [comment]
Cool, yeah we almost had the exact same approach 👍
