### ISSUE TITLE
Background image is not getting updated even after updating the URL in source code.

### ISSUE THREAD

**Issue by SriramKodavati** [diegomura/react-pdf#940]
Home.js

import React from 'react';
import Weather from './Weather';
import './Weather.css';

const Home = () => {

    return(
        <div>
            <div className="img1" cache="false">
            <div className="container">
            <p className="float-left mt-3 one"><b className="mr-2">Date and Time(IST):</b>{Date()}</p>
            </div>
            <br /><br ></br>
          <Weather></Weather> 
          </div>
        </div>
    )
}

export default Home;

Weather.css

.img1 {
	background-image:
		url("https://images.unsplash.com/photo-1591002711109-ff99aa4f56be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2255&q=80");
	height: 500px;
	background-position: center;
    background-repeat: no-repeat;
    position: relative;
    height: 100vh;
}

**Comment by SamJarmanPP** [comment]
I dont think background image is supported in reactPDF https://react-pdf.org/styling#valid-units

**Comment by diegomura** [comment]
Indeed. It's not currently supported. You can simulate this effect by placing an absolute `<Image />`
