### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by jarjav** [diegomura/react-pdf#941]
when I try generate blob from my document, then  TypeError occured

```
import { pdf } from "@react-pdf/renderer";
import { saveAs } from "file-saver";

const downloadPdf = async () => {
    const blob = await pdf(<Document />).toBlob();  //error here
    saveAs(blob, "document.pdf");
  };
```

**Comment by m-najera** [comment]
I was having a similar issue when trying to create a blob.
I fixed it by downgrading 
`npm i @react-pdf/renderer@1.5.6`
npm installs by default the version ^2.0.0beta

**Comment by cmnstmntmn** [comment]
@m-najera for me this is not working

**Comment by nicholasstephan** [comment]
Same issue here.

**Comment by cmnstmntmn** [comment]
@nicholasstephan  you may check [this workaround](https://github.com/diegomura/react-pdf/issues/932#issuecomment-655166369) for 2.0

```js
import { saveAs } from "file-saver";
import { pdf } from "@react-pdf/renderer";
import { PDFPage } from "./PDFPage";

const generatePDFDocument = async () => {
  const blobPdf = await pdf(PDFPage());
  blobPdf.updateContainer(PDFPage());
  const result = await blobPdf.toBlob();

  saveAs(result, "document.pdf");
};

export default generatePDFDocument;
```

```jsx
<button onClick={generatePDFDocument}>Download PDF</button>
```

**Comment by Marguelgtz** [comment]
Thanks for the heads up @cmnstmntmn, works great!

**Comment by AnkitBagaria24** [comment]
@cmnstmntmn thanks for the solution man. Works beautifully !!

**Comment by afficiona** [comment]
Thank you, @cmnstmntmn  for this amazing solution. I was banging my head to get a workaround this. But I am also anticipating this might break when there's an appropriate fix in the latest beta version.

**Comment by jarjav** [comment]
Thanks @cmnstmntmn 
Your solution works great.
I'm closing this issue.

**Comment by diegomura** [comment]
My bad! I removed the beta version as the latest on npm. I'm aware of this bug on 2.0 and will be fixed for next deploy. Thanks for addressing this!
