### ISSUE TITLE
toLocaleString("fr-FR") replace whitespace with a slash

### ISSUE THREAD

**Issue by Melju** [diegomura/react-pdf#944]
When you want to use the function toLocaleString for french currency you get a "/" after the thousands
The expected behavior would be 1 000,00 €
Instead you get this 1/000,00 €

Do you know if there's a way to correct it?

Best regards

**Comment by laazaz** [comment]
same problem.

**Comment by laazaz** [comment]
Fixed my problem using this workaround :

`number.toLocaleString('fr-FR', { minimumFractionDigits: 2 }).replace(' ', ' ')`

It seems like the space that `toLocaleString` returns isn't a normal space [you can try console.log(' ' === ' ')], so react-pdf replaces any unknown character with a slash, hope this helps anyone.

**Comment by diegomura** [comment]
Thanks @laazaz . I just checked and indeed, `toLocaleString` returns some odd unicode character there. The simplest fix would be what you proposed. Other would be using a font that has a valid representation for that character. The default Helvetica and the other supported fonts do not have one and for some odd reason end up rendering `/`. But wouldn't be correct to do that replacement internally in the project. Thanks!
