### ISSUE TITLE
Nested `<Text>` in a multi-line `<Text>` is overflowing it's bounding box

### ISSUE THREAD

**Issue by juliaqiuxy** [diegomura/react-pdf#945]
**Describe the bug**
Nested `<Text>` in a multi-line `<Text>` is overflowing it's bounding box.

**To Reproduce**
[REPL](https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618023100137802e1859b0090016da8500e6012cc3f00ac001800d2b18017c55b0252241443a0947e82d876ac0035848a2002b982e01844221015f80722820c778f9bd598d4012801b99823412160b841803061e95400780044e36c4590c0a000f954d9920015a82590e0a400bd91d00088010400596bf34d0a00d4a59001dce17051d118105021493878d55adb0a005590003cf20ba7b064245061f4c1cae91661baa4a0086197a792e6f7866a87fb5149b575f574a12664b67617601ef40ce8b99200f4173c89c56a67a849a832180008510e60b0c181a7429033e53698a260e774562d80039541fc919f7da1c0878ec702fa784195d46df27a195e60778c1765f03132fe80e06e5416098343a89b7004894a2b038b25d2d714a2572d958a15ca994c044b644140a4005a364001dc4a50a351f514b06f3712b406747a18ec4024a6529a03d2c04cb649661088009468c028115520031521501cc80a3d162c06f5000)

Notice that the second inlined text has the last character ('d') rendered outside of its bounding box. If the multi-line text is shortened to a single line text, it works as expected.

**Expected behavior**
Nested text in a multi-line parent text should not overflow its bounding box.

**Comment by buskerone** [comment]
I can confirm that this is still happening
