### ISSUE TITLE
How to set PDF password or how to encrypt pdf using this library ?

### ISSUE THREAD

**Issue by leanesanity** [diegomura/react-pdf#946]
Good day,

Really need your help.
Would just like to confirm if possible to encrypt pdf file using this library?
It would also be helpful you can provide a simple example.

Your answer will be a big help thanks!

**Comment by diegomura** [comment]
There is no way yet

**Comment by jose920405** [comment]
Any plan for supporting this?

**Comment by diegomura** [comment]
I would like in the future but there are other stuff first on my list. I would accept a PR though. Closing this and keeping #672 to track this feature
