### ISSUE TITLE
toBlob() throw slice of undifine

### ISSUE THREAD

**Issue by TalOrlanczyk** [diegomura/react-pdf#947]
since version the current version toBlob() throw problem , i worked with 1.6.8 and its worked fine
![2020-07-15 (3)](https://user-images.githubusercontent.com/16623739/87551964-be2b9c80-c6b9-11ea-896d-2eb012343f03.png)
![2020-07-15](https://user-images.githubusercontent.com/16623739/87551977-c08df680-c6b9-11ea-8d72-257beb27dcf7.png)

**Comment by diegomura** [comment]
Thanks! I'm aware of this. Will fixed on the next 2.0 release

**Comment by TalOrlanczyk** [comment]
thanks for the quick response
