### ISSUE TITLE
Rendering dynamic data from react in <Text>

### ISSUE THREAD

**Issue by mikelubs** [diegomura/react-pdf#951]
I have made a component called Pdf.js with the following code
`
      {
          questions.map(({ question, id }) => (
               <Text style={styles.text} key={id}>
                      {question}
               </Text>
           ))
      }
`
questions variable is data coming from the react project I have
The Questions display correctly in the browser
but if I check in Viewer like below, the pdf is blank even after downloading, it is still blank
`
<PDFViewer>
          <Pdf/>
</PDFViewer>
`

I would appreciate any solution to my problem

**Comment by EbubeUd** [comment]
Same Issue. Mine happens when I use the render property to display page number. It does not show up on the PDF using <PDFViewer>

**Comment by luskin** [comment]
Same here, the page number and total pages come through however anything returns from the `render` prop method or within the `<Text>{variable}</Text>` is broken.

**Comment by luskin** [comment]
@EbubeUd @mikelubs if you just need it to work like us, you can hack it using a fragment:

```typescript
 <Text font={Fonts.Courier.Normal} fontSize={10}>
    <>{props.date}</>
</Text>
```

**Comment by EbubeUd** [comment]
Thanks. I'll try this out!

**Comment by diegomura** [comment]
If the `questions` data comes from your app, you should not use the `render` prop. You just map through questions inside the `<Document />` like [this example](https://react-pdf.org/repl?code=3187b0760ce02e00408e057029b4096e08c0bc303681bc65401300b86011801a79935c7202200249013d19805f1b093c804c3510a28e8c13662139700ba012001412d091600593600444306c30005004a6c00f90e2983000f0ee00802d9230514e5ab36002804300e648dc3c3df045e92000e81dbc001c0c0d0942c5c06849b84cb1cc0ddc82adac005490003d606001add8b1f048b9cc42e892c0b86c01e80b8bcdb23c8c4cb93bad9a7dfd025aed1d9d5d148c01b9156714009491bd80a13cb400c5c2009d9d8890b60dad34ec619b4da71480)
