### ISSUE TITLE
How to generate multiple pdf on a click of button and download it as zip

### ISSUE THREAD

**Issue by Akshaykapadi** [diegomura/react-pdf#957]
How to generate multiple pdf on client side using react pdf and when the download gets complete of all the files it should download it as a zip . This operation should be performed on client side only.
Is there any workaround to overcome this. 

Please suggest a solution to do it.

**Comment by CarlosAmaral** [comment]
Don't think so. That should be done on the server side, you have to somehow store and zip the files until you download them.

**Comment by diegomura** [comment]
@bocha13 proposed way seems like the way to go. However, this is not a feature that should be build on this lib. react-pdf it's just for file generation 😄
