### ISSUE TITLE
❓: Set Default Font Family?

### ISSUE THREAD

**Issue by luskin** [diegomura/react-pdf#958]
**Describe the bug**
We cannot find a way to set a default font family for a document? When 90% of your font is the same family, it's redundant to have to specify the family for each text style. Does anybody know a way to set a default font-family?

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
None

**Comment by haseebeqx** [comment]
@luskin  How did you managed to solve this?
I use this workaround.
```js
  export const NText=({styles={},..props})=><Text styles={[{fontFamily: 'Sssa223'}, styles]} {...props} />
```
and import this as Text.

**Comment by luskin** [comment]
@haseebeqx for us we simply specified the font family on the `Page` style and it seems to drill down by default to all child components:

```typescript
const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontSize: 7,
  },
})

export const YourDocument: DocumentType<YourDocumentGenerationData> = ({
  renderValues: documentValues,
}) => {

  return (
    <PDFWrapper>
      <Page size="A4" style={styles.page}>
         <YourChildren />
      </Page>
```
