### ISSUE TITLE
Images do not render on react pdf renderer

### ISSUE THREAD

**Issue by MiracleGodspeed** [diegomura/react-pdf#959]
I am currently trying to get images from endpoints and render onto the React Pdf Viewer. I get a Cors error in my attempt to do so.

 <Image src={{uri:this.state.staffDocx?.imageUrl, method: 'GET', headers:{'Access-Control-Allow-Origin': '*'}}}/>

**Comment by jamigibbs** [comment]
@MiracleGodspeed This is a known issue. Take a look at the workaround here: https://github.com/diegomura/react-pdf/issues/929

**Comment by SH-Stark** [comment]
I got the same problem, did you find any workaround ? (#929 is not working in my case)

**Comment by diegomura** [comment]
Keeping #929 for cors related issues
