### ISSUE TITLE
Is there a way to improve performance?

### ISSUE THREAD

**Issue by taipignas** [diegomura/react-pdf#961]
I am generating 70 pages and it takes 2 minutes to generate. I think jsPDF can handle html and is able to process it much faster. Any ideas how i can make it work faster?

edit: nevermind, i resolved it. i was using img url which was in all 70 pages and it probably took too long to fetch or render it. in the end i resized it to much lower size and converted it to base64.

**Comment by diegomura** [comment]
Thanks!
