### ISSUE TITLE
Email the generated pdf

### ISSUE THREAD

**Issue by niharikaprasad** [diegomura/react-pdf#963]
**Is your feature request related to a problem? Please describe.**
I have been trying to email the generated pdf to a user. In my assignment, I don't have to save the pdf in any database. I have to create a form, accept the user email address, and then email the pdf to the user. Please suggest me how I can do that.
**Describe the solution you'd like**

**Describe alternatives you've considered**
 I have tried using Email.js, but I am unable to attach the pdf in the email. I don't want to upload the pdf again. I have to access the currently generated pdf. I am unable to access the blob link.
**Additional context**
![image](https://user-images.githubusercontent.com/57333924/89118683-eec35280-d47d-11ea-94c8-0bc645363481.png)
Is there anyway of accessing this pdf download link in React. I could try emailing it by adding path as the link

**Comment by ShayanShokat** [comment]
You can do it by converting to pdf to a blob and then convert that blob in to a file and email that file. Here's how I did it.
imports:

import { Document, pdf} from '@react-pdf/renderer';
`
      //pdf document
       const element = <Document title="PDF FILE">
                           </Document>;
        const myPdf = pdf({}); 
        myPdf.updateContainer(element);
        const blob = await myPdf.toBlob();//create blob
        var file = new File([blob], "pdfname.pdf", {lastModified: (new Date()).getTime()});//create file
`
Now you can email the file with the emailing service you're using.

**Comment by diegomura** [comment]
@ShayanShokat 's right. React-pdf generates a blog file which is not a url you can share or email. You need to download it first
