### ISSUE TITLE
Using ZWSP throws an uncaught promise exception

### ISSUE THREAD

**Issue by wyqydsyq** [diegomura/react-pdf#964]
**Describe the bug**
I'm trying to disable hyphenation completely as I need to present a potentially long URL in the PDF, aiming to use ZWSP to suggest wrap break location, example code:

```ts
  <View style={styles.url}>
    <Text>{`magic.menu/\u200B${handle}`}</Text>
  </View>
```

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Add `Font.registerHyphenationCallback((word) => [word])` which is supposed to disable hyphenation
2. Try to use `\u200B` in your text string in order to manually specify text breakpoints w/o hyphens
3. Get an error like: `react-pdf.browser.es.js:3885 Uncaught (in promise) TypeError: Cannot read property 'hasGlyphForCodePoint' of null`

**Expected behavior**
react-pdf is able to render ZWSP / `u200B`

**Screenshots**
Trying to run the example code:
![image](https://user-images.githubusercontent.com/621277/89163603-2edb2000-d5b9-11ea-9e29-b8182efb127a.png)

Without hyphenation disabled, it results in a different (and invalid) URL with the added hypenation:
![image](https://user-images.githubusercontent.com/621277/89163837-942f1100-d5b9-11ea-8c13-4992826f2807.png)

I expect to be able to disable hyphenation and add a ZWSP in to suggest break location with a result like the following using a space instead of ZWSP, which wraps correctly but then results in an unwanted space in non-wrapped text:
![image](https://user-images.githubusercontent.com/621277/89163970-d0627180-d5b9-11ea-9426-147c20e2ab23.png)
![image](https://user-images.githubusercontent.com/621277/89164104-fa1b9880-d5b9-11ea-95b0-460f7e37615a.png)

**Desktop (please complete the following information):**
 - OS: `Ubuntu`
 - Browser: `Chrome`
 - React-pdf version: `1.6.10`

**Comment by diegomura** [comment]
Should be fixed by https://github.com/diegomura/react-pdf/issues/777 . Tested it on latest version and not getting the error
