### ISSUE TITLE
How can i open <Link> in new tab

### ISSUE THREAD

**Issue by Aghiles-Saal** [diegomura/react-pdf#965]
i try to open Link in new tab but it does not work when i add "target="_blank""

<View>
                  <Link
                    target="_blank"
                        href={`https://maps.google.com/maps?q=${latitude},${longitude}&t=&z=13&ie=UTF8 `}
                    style={styles.localisation}
                  >
                               find
                  </Link>
  </View>

**Comment by andrewdourado** [comment]
Discussion: [ #645](https://github.com/diegomura/react-pdf/issues/645)

**Comment by diegomura** [comment]
Duplicated. Leaving #645.
