### ISSUE TITLE
npm package installation giving issue

### ISSUE THREAD

**Issue by prasadsawant12** [diegomura/react-pdf#968]
**Describe the bug**
Whenever i am installing package using command npm i @react-pdf/renderer  its giving following issue

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-pdf%2frenderer - Not found
npm ERR! 404
npm ERR! 404  '@react-pdf/renderer@1.6.9' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by diegomura** [comment]
Couldn't replicate. It is in the npm registry
