### ISSUE TITLE
PDF doesn't show inside Chrome PDF viewer

### ISSUE THREAD

**Issue by saswatamcode** [diegomura/react-pdf#969]
**Describe the bug**
I haven't found a way to show the pdf I generate in Chrome PDF viewer. I need it to be scrollable since I'm showing it inside a small div and have a small download button.

**Comment by diegomura** [comment]
Try the `<PDFViewer />` component this lib has or implement your own viewer such as the REPL on the project's page. This is how that was done for reference: https://github.com/react-pdf/site/blob/master/src/components/Repl.js
