### ISSUE TITLE
Can't use it, when import doesn`t compile, can't resolve babel/runtime

### ISSUE THREAD

**Issue by ronaldomoia** [diegomura/react-pdf#970]
**Describe the bug**
After installing react-pdf/renderer it works fine, when I import something from react-pdf/renderer it does not compile.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
Install react-pdf/render and import anything

**Expected behavior**
Just compile normally so that I can use it

**Screenshots**

![Screen Shot 2020-08-07 at 14 06 28](https://user-images.githubusercontent.com/44447816/89670232-394a3200-d8b7-11ea-85d5-f84e3a9041c8.png)

<img width="1066" alt="Screen Shot 2020-08-07 at 13 59 38" src="https://user-images.githubusercontent.com/44447816/89669660-3dc21b00-d8b6-11ea-812f-fa6f84495bdf.png">

![Screen Shot 2020-08-07 at 14 00 22](https://user-images.githubusercontent.com/44447816/89669723-592d2600-d8b6-11ea-8718-af6152b8bfe7.png)
![Screen Shot 2020-08-07 at 14 00 40](https://user-images.githubusercontent.com/44447816/89669750-63e7bb00-d8b6-11ea-9d88-8116407c1cee.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5
 - Browser chrome
 - React-pdf version [e.g. v1.6.10]

**Comment by diegomura** [comment]
Should be fixed in latest build
