### ISSUE TITLE
download pdf on custom button click 

### ISSUE THREAD

**Issue by pradeepn541** [diegomura/react-pdf#975]
hi,

Is there any way i can download my pdf on my custom button click without using in built PdfDownloadLink ?

**Comment by vuki656** [comment]
Also, need this. 

Right now I'm passing the link to the button text. It's a little hacky. 

It would be nice to be provided with a trigger that could be passed to onClick handlers.

**Comment by pradeepn541** [comment]
> that

Can you please explain how you are passing link to the button text ?

**Comment by vuki656** [comment]
> > that
> 
> Can you please explain how you are passing link to the button text ?

Default button

`<Button>Click Me</Button>
`

With PDF 

`<Button><PDFDownloadButton></Button`

and then in the `PDFDownloadButton `component you pass the text and the pdf
```

<PDFDownloadLink
    fileName={`fileName}
    document={document}
>
   Click Me
</PDFDownloadLink>
```

**Comment by JacobFischer** [comment]
I've accomplished this via some headaches that I'm trying to solve in #972. Here's an example of how to do a custom onClick handler on a button to lazy load the PDF:

```jsx
import { pdf } from '@react-pdf/renderer';
import { saveAs } from 'file-saver';
import React from 'react';
import { DocumentPdf, getProps } from './document-pdf';

export const LazyDownloadPDFButton = () => (
  <button
    onClick={async () => {
      const props = await getProps();
      const doc = <DocumentPdf {...props} />;
      const asPdf = pdf({}); // {} is important, throws without an argument
      asPdf.updateContainer(doc);
      const blob = await asPdf.toBlob();
      saveAs(blob, 'document.pdf');
    }}
  >Download PDF</button>
);
```

Feel free to tweak to your needs. I slimmed my code down quite a bit for the example here. However, in a real code base I also track when it is async loading the pdf blob to disable multiple onClick events, and cache the generated blob to speed up subsequent download clicks.

Using `<PDFDownloadLink>` as pointed out generates the PDF when the page loads, which in my use case was not ideal and increased page loading times dramatically. I'd imagine many other developers do not need to generate the PDF until a user clicks on their button, as I did.

I hope this helps.

**Comment by oowowaee** [comment]
Not sure if this is what you're looking for, but I was able to resolve the lazy load + custom button using a version of https://github.com/diegomura/react-pdf/issues/736.

**Comment by pradeepn541** [comment]
> I've accomplished this via some headaches that I'm trying to solve in #972. Here's an example of how to do a custom onClick handler on a button to lazy load the PDF:
> 
> ```js-jsx
> import { pdf } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> import React from 'react';
> import { DocumentPdf, getProps } from './document-pdf';
> 
> export const LazyDownloadPDFButton = () => (
>   <button
>     onClick={async () => {
>       const props = await getProps();
>       const doc = <DocumentPdf {...props} />;
>       const asPdf = pdf({}); // {} is important, throws without an argument
>       asPdf.updateContainer(doc);
>       const blob = await asPdf.toBlob();
>       saveAs(blob, 'document.pdf');
>     }}
>   >Download PDF</button>
> );
> ```
> 
> Feel free to tweak to your needs. I slimmed my code down quite a bit for the example here. However, in a real code base I also track when it is async loading the pdf blob to disable multiple onClick events, and cache the generated blob to speed up subsequent download clicks.
> 
> Using `<PDFDownloadLink>` as pointed out generates the PDF when the page loads, which in my use case was not ideal and increased page loading times dramatically. I'd imagine many other developers do not need to generate the PDF until a user clicks on their button, as I did.
> 
> I hope this helps.

Thanks,
It worked.Cool 👍 

Is there any chance we can put this block of execution into web worker ?

**Comment by muhammadhassan149** [comment]
> I've accomplished this via some headaches that I'm trying to solve in #972. Here's an example of how to do a custom onClick handler on a button to lazy load the PDF:
> 
> ```js-jsx
> import { pdf } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> import React from 'react';
> import { DocumentPdf, getProps } from './document-pdf';
> 
> export const LazyDownloadPDFButton = () => (
>   <button
>     onClick={async () => {
>       const props = await getProps();
>       const doc = <DocumentPdf {...props} />;
>       const asPdf = pdf({}); // {} is important, throws without an argument
>       asPdf.updateContainer(doc);
>       const blob = await asPdf.toBlob();
>       saveAs(blob, 'document.pdf');
>     }}
>   >Download PDF</button>
> );
> ```
> 
> Feel free to tweak to your needs. I slimmed my code down quite a bit for the example here. However, in a real code base I also track when it is async loading the pdf blob to disable multiple onClick events, and cache the generated blob to speed up subsequent download clicks.
> 
> Using `<PDFDownloadLink>` as pointed out generates the PDF when the page loads, which in my use case was not ideal and increased page loading times dramatically. I'd imagine many other developers do not need to generate the PDF until a user clicks on their button, as I did.
> 
> I hope this helps.

Can you please send the related files, e.g document etc, I've to fetch the data in document from api

**Comment by JacobFischer** [comment]
Sure, here's a larger form file with the example code I posted above:

https://gist.github.com/JacobFischer/aecbd871cb2aae46993236f65797da5c

That should help show you how to fetch asynchronous data for your document

**Comment by PauloQuagliatto** [comment]
> I've accomplished this via some headaches that I'm trying to solve in #972. Here's an example of how to do a custom onClick handler on a button to lazy load the PDF:
> 
> ```js-jsx
> import { pdf } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> import React from 'react';
> import { DocumentPdf, getProps } from './document-pdf';
> 
> export const LazyDownloadPDFButton = () => (
>   <button
>     onClick={async () => {
>       const props = await getProps();
>       const doc = <DocumentPdf {...props} />;
>       const asPdf = pdf({}); // {} is important, throws without an argument
>       asPdf.updateContainer(doc);
>       const blob = await asPdf.toBlob();
>       saveAs(blob, 'document.pdf');
>     }}
>   >Download PDF</button>
> );
> ```
> 
> Feel free to tweak to your needs. I slimmed my code down quite a bit for the example here. However, in a real code base I also track when it is async loading the pdf blob to disable multiple onClick events, and cache the generated blob to speed up subsequent download clicks.
> 
> Using `<PDFDownloadLink>` as pointed out generates the PDF when the page loads, which in my use case was not ideal and increased page loading times dramatically. I'd imagine many other developers do not need to generate the PDF until a user clicks on their button, as I did.
> 
> I hope this helps.

Hey,  I've tried your code but there are some issues about passing the data. I am passing the data like <LazyButton note={visibleNotes} /> (the visible notes are the notes that are shown given proper redux filter and store)
and like so I pass the props to your code:
```
export const LazyDownloadPDFButton = () => (
 <button
    onClick={async () => {
      const doc = <DocumentPdf {...props} />;
```
With this I want to pass the dynamic data directly to the pdf file, but it crashes saying this: Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
So, how would I pass this data? Saw your complete example but still can't see a way out.

**Comment by JacobFischer** [comment]
@PauloQuagliatto, according to this comment: https://gist.github.com/JacobFischer/aecbd871cb2aae46993236f65797da5c#gistcomment-3479589

Replace:
```js
const asPdf = pdf({});
```

with:
```js
const asPdf = pdf([]);
```

Both hacks work for me. Though perhaps how you are structuring your pdf is similar to that comment.

**Comment by PauloQuagliatto** [comment]
> @PauloQuagliatto, according to this comment: https://gist.github.com/JacobFischer/aecbd871cb2aae46993236f65797da5c#gistcomment-3479589
> 
> Replace:
> 
> ```js
> const asPdf = pdf({});
> ```
> 
> with:
> 
> ```js
> const asPdf = pdf([]);
> ```
> 
> Both hacks work for me. Though perhaps how you are structuring your pdf is similar to that comment.

This actually worked! Many thanks!

**Comment by mohannadhanafi** [comment]
> I've accomplished this via some headaches that I'm trying to solve in #972. Here's an example of how to do a custom onClick handler on a button to lazy load the PDF:
> 
> ```js-jsx
> import { pdf } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> import React from 'react';
> import { DocumentPdf, getProps } from './document-pdf';
> 
> export const LazyDownloadPDFButton = () => (
>   <button
>     onClick={async () => {
>       const props = await getProps();
>       const doc = <DocumentPdf {...props} />;
>       const asPdf = pdf({}); // {} is important, throws without an argument
>       asPdf.updateContainer(doc);
>       const blob = await asPdf.toBlob();
>       saveAs(blob, 'document.pdf');
>     }}
>   >Download PDF</button>
> );
> ```
> 
> Feel free to tweak to your needs. I slimmed my code down quite a bit for the example here. However, in a real code base I also track when it is async loading the pdf blob to disable multiple onClick events, and cache the generated blob to speed up subsequent download clicks.
> 
> Using `<PDFDownloadLink>` as pointed out generates the PDF when the page loads, which in my use case was not ideal and increased page loading times dramatically. I'd imagine many other developers do not need to generate the PDF until a user clicks on their button, as I did.
> 
> I hope this helps.

Thanks a lot, I faced the same problem and finally it worked 🥳

**Comment by diegomura** [comment]
@JacobFischer seems like a good solution. Thanks!

**Comment by theutkarshsoni** [comment]
@JacobFischer Thanks a lot. You saved my entire day. Really appreciate.

**Comment by WilliamPhilippe** [comment]
> I've accomplished this via some headaches that I'm trying to solve in #972. Here's an example of how to do a custom onClick handler on a button to lazy load the PDF:
> 
> ```js
> import { pdf } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> import React from 'react';
> import { DocumentPdf, getProps } from './document-pdf';
> 
> export const LazyDownloadPDFButton = () => (
>   <button
>     onClick={async () => {
>       const props = await getProps();
>       const doc = <DocumentPdf {...props} />;
>       const asPdf = pdf({}); // {} is important, throws without an argument
>       asPdf.updateContainer(doc);
>       const blob = await asPdf.toBlob();
>       saveAs(blob, 'document.pdf');
>     }}
>   >Download PDF</button>
> );
> ```
> 
> Feel free to tweak to your needs. I slimmed my code down quite a bit for the example here. However, in a real code base I also track when it is async loading the pdf blob to disable multiple onClick events, and cache the generated blob to speed up subsequent download clicks.
> 
> Using `<PDFDownloadLink>` as pointed out generates the PDF when the page loads, which in my use case was not ideal and increased page loading times dramatically. I'd imagine many other developers do not need to generate the PDF until a user clicks on their button, as I did.
> 
> I hope this helps.

Thank you so much!!!

**Comment by adamduncan** [comment]
Would still +1 on adding an `onClick` to `<PDFDownloadLink>` API

**Comment by valentimcanejo** [comment]
> I've accomplished this via some headaches that I'm trying to solve in #972. Here's an example of how to do a custom onClick handler on a button to lazy load the PDF:
> 
> ```js
> import { pdf } from '@react-pdf/renderer';
> import { saveAs } from 'file-saver';
> import React from 'react';
> import { DocumentPdf, getProps } from './document-pdf';
> 
> export const LazyDownloadPDFButton = () => (
>   <button
>     onClick={async () => {
>       const props = await getProps();
>       const doc = <DocumentPdf {...props} />;
>       const asPdf = pdf({}); // {} is important, throws without an argument
>       asPdf.updateContainer(doc);
>       const blob = await asPdf.toBlob();
>       saveAs(blob, 'document.pdf');
>     }}
>   >Download PDF</button>
> );
> ```
> 
> Feel free to tweak to your needs. I slimmed my code down quite a bit for the example here. However, in a real code base I also track when it is async loading the pdf blob to disable multiple onClick events, and cache the generated blob to speed up subsequent download clicks.
> 
> Using `<PDFDownloadLink>` as pointed out generates the PDF when the page loads, which in my use case was not ideal and increased page loading times dramatically. I'd imagine many other developers do not need to generate the PDF until a user clicks on their button, as I did.
> 
> I hope this helps.

Man, thank you so much, you saved my code.

Did you created a loading behavior? I've put a setLoading(true) and a setLoading(false) inside the onClick, but it doesn't work correctly in a PDF with large data, how can i create a better loading?

**Comment by hmcd101** [comment]
> import { saveAs } from 'file-saver';

Much appreciated! Worked well for me. I too added the state values to track PDF generation and disable the button. Worked well, though my PDF is not extremely large.

**Comment by Tint-d** [comment]
hey how use it with rtk state?

**Comment by Chakkaphong9** [comment]
> Update: never mind. Set `image: { objectFit: 'contain' }` with `StyleSheet` fixed it.
> 
> I have an `<Image />` in the Document, and your solution scales that image in both directions differently, while PDFDownloadLink does not (but it is not lazy, hence I need a solution like yours). Do you know why `pdf` has this problem? How can I fix it?
> 
> > @PauloQuagliatto, according to this comment: https://gist.github.com/JacobFischer/aecbd871cb2aae46993236f65797da5c#gistcomment-3479589
> > Replace:
> > ```js
> > const asPdf = pdf({});
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with:
> > ```js
> > const asPdf = pdf([]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Both hacks work for me. Though perhaps how you are structuring your pdf is similar to that comment.

this work for me.

**Comment by rbrahier17** [comment]
If it can help, here is an example of a basic react button component accomplishing this lazy pdf downloading, with the react-pdf `usePDF` hook and react hooks: 

```js
import React, { useState, useEffect } from "react";
import { usePDF, Document, Page, Text } from "@react-pdf/renderer";

// Define the PDF document (you can also import it)
const myPdfDocument = (
  <Document>
    <Page>
      <Text>Hello PDF Document</Text>
    </Page>
  </Document>
);

export function DownloadPdfButton() {
  const [pdfInstance, updatePdfInstance] = usePDF({}); // Instantiate an empty PDF instance using the usePDF hook
  const [isDownloading, setIsDownloading] = useState(false);

  function downloadPdf() {
    setIsDownloading(true);
    updatePdfInstance(myPdfDocument); // Update the PDF instance with your document when the download button is clicked
  }

  // Trigger the PDF download when the button is clicked and the PDF instance URL is available
  useEffect(() => {
    if (isDownloading && pdfInstance.url) {
      const a = document.createElement("a");
      a.href = pdfInstance.url;
      a.download = "document.pdf";
      a.click();
      setIsDownloading(false);
    }
  }, [isDownloading, pdfInstance.url]);


  return (
    <button onClick={downloadPdf} disabled={isDownloading}>
      {isDownloading ? "Loading..." : "Download PDF"}
    </button>
  );
}
```

If you have any remarks or suggestions about that I'll be happy to read them, hope this helps !

**Comment by meshramsaroj** [comment]
> If it can help, here is an example of a basic react button component accomplishing this lazy pdf downloading, with the react-pdf `usePDF` hook and react hooks:
> 
> ```js
> import React, { useState, useEffect } from "react";
> import { usePDF, Document, Page, Text } from "@react-pdf/renderer";
> 
> // Define the PDF document (you can also import it)
> const myPdfDocument = (
>   <Document>
>     <Page>
>       <Text>Hello PDF Document</Text>
>     </Page>
>   </Document>
> );
> 
> /**
>  * Triggers a download for a given URL by creating a hidden anchor element.
>  * @param url - The URL of the file to be downloaded.
>  * @param title - The title to be used for the downloaded file (default is 'document').
>  */
> function triggerDownload(url: string, title: string = "document") {
>   const a = document.createElement("a");
>   a.href = url;
>   a.download = title + ".pdf";
>   a.click();
> }
> 
> export function DownloadPdfButton() {
>   const [pdfInstance, updatePdfInstance] = usePDF({}); // Instantiate an empty PDF instance using the usePDF hook
>   const [isDownloading, setIsDownloading] = useState(false);
> 
>   function initiateDownload() {
>     setIsDownloading(true);
>     updatePdfInstance(myPdfDocument); // Update the PDF instance with your document when the download button is clicked
>   }
> 
>   // Trigger the PDF download when the button is clicked and the PDF instance URL is available
>   useEffect(() => {
>     if (isDownloading && pdfInstance.url) {
>       triggerDownload(pdfInstance.url)
>       setIsDownloading(false);
>     }
>   }, [isDownloading, pdfInstance.url]);
> 
> 
>   return (
>     <button onClick={initiateDownload} disabled={isDownloading}>
>       {isDownloading ? "Loading..." : "Download PDF"}
>     </button>
>   );
> }
> ```
> 
> If you have any remarks or suggestions about that I'll be happy to read them, hope this helps !

This solution really helped me. Thanks

**Comment by sneko** [comment]
Just to share my solution with downloading but also "previewing" in another tab:
```tsx
  const [isGeneratingPdf, setIsGeneratingPdf] = useState<boolean>(false);

  const generatePdf = useCallback(async () => {
    if (data) {
      setIsGeneratingPdf(true);
      
      try {
        const pdfBlob = await pdf(
          <MyDocument
            data={data}
          />
        ).toBlob();

        const pdfBlobUrl = URL.createObjectURL(pdfBlob);

        return pdfBlobUrl;
      } finally {
        setIsGeneratingPdf(false);
      }
    }

    return null;
  }, [data]);

  const downloadPdf = useCallback(async () => {
    const pdfBlobUrl = await generatePdf();

    if (pdfBlobUrl) {
      const downloadLink = document.createElement('a');
      downloadLink.href = pdfBlobUrl;
      downloadLink.download = `My PDF document')}`;
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
    }
  }, [generatePdf]);

  const previewPdf = useCallback(async () => {
    const pdfBlobUrl = await generatePdf();

    if (pdfBlobUrl) {
      window.open(pdfBlobUrl, '_blank');
    }
  }, [generatePdf]);
```
