### ISSUE TITLE
react-pdf.browser.es.js:365 TypeError: Cannot read property 'font' of undefined

### ISSUE THREAD

**Issue by manojchandrabose** [diegomura/react-pdf#976]
@diegomura [react-pdf.browser.es.js:365](url) TypeError: Cannot read property 'font' of undefined
    at ignoreChars.js:23
    at Array.map (<anonymous>)
    at o (ignoreChars.js:22)
    at e (getAttributedString.js:115)
    at _pipe.js:3
    at _arity.js:16
    at _curryN.js:40
    at _arity.js:11
    at converge.js:41
    at A (_map.js:7)
t.onRenderFailed @ react-pdf.browser.es.js:365

below the bold line. 

var ignoreChars = function ignoreChars(fragments) {
  return fragments.map(function (fragment) {
    **var charSubset = buildSubsetForFont(fragment.attributes.font);**
    var subsetRegex = new RegExp(charSubset.join('|'));
    return {
      string: fragment.string.replace(subsetRegex, ''),
      attributes: fragment.attributes
    };
  });
};

I have properly registered the fonts like below. But still the issue has come.

Font.register({
  src: "SRC",
  family: "URL"
});

**Note**: Only happens on server after deployed. But local machine it is working fine.

**Comment by manojchandrabose** [comment]
![Uploading image.png…]()

**Comment by Cedric-Delacombaz** [comment]
Hi @manojchandrabose 

I am encountering the same issue. Could you solve it? How?

BR, Cedric

**Comment by manojchandrabose** [comment]
@Cedric-Delacombaz .
In my case, I used <Link> component inside a <Text> component like below.
**<Text>Some content <Link src="URL">URL</Link> Some more content</Text>** So i was facing that issue.
Then i removed the <Link> component from inside <Text> and Placed it outside and it stared working.
BR, Manoj
