### ISSUE TITLE
External Links missing first character in V2

### ISSUE THREAD

**Issue by SpudNyk** [diegomura/react-pdf#980]
**Describe the bug**
When using the Link component to link with a protocol (https, http, mailto, etc.) the link is corrupted as the first character of the protocol is missing.

Internal #id links work perfectly.

**To Reproduce**
Render a document with a Link using react-pdf v2.0.0-beta.14

**Expected behavior**
A valid link should be rendered.

**Work Around**

Add a extra char to the start of links (I'm using a space in this case)

**Note**
appears to be caused by this line which seems to assume the first character should be thrown away.
https://github.com/diegomura/react-pdf/blob/d9441d47a47f5296ba1d23fb3bb6a7f6acbe2ae5/packages/render/src/operations/setLink.js#L17

**Comment by JacobFischer** [comment]
I'm also seeing this error on the mentioned version. An obvious workaround I'm employing is to pad links by 1 character so the padding is sliced off, e.g.:

`"http://github.com/"` -> `" http://github.com/"`

**Comment by jsaelhof** [comment]
I've also been having this issue for quite a while. The strange part is that on some environments (for example, my local) there is no issue while on others (deployments) it slices that first char. I thought it might be http (local) vs https (deployed) but that doesn't seem to be the case after running my local with a self-signed cert.

**Comment by diegomura** [comment]
This has been fixed already. Thanks for reporting it and sorry for the delay
