### ISSUE TITLE
No ID property in BaseImageProps TypeScript interface

### ISSUE THREAD

**Issue by LucasMatuszewski** [diegomura/react-pdf#982]
**Describe the bug**
There is no ID property in BaseImageProps TypeScript interface. It makes it impossible to add ID property for Image when using TS.

**To Reproduce**
Try to add ID property for `<Image id="some-id" />` component.

**Expected behavior**
It should be possible to add ID property for Images ;)

**Pull Request**
I have already added ID to the interface, please merge it or add some comments if I should change something:
https://github.com/diegomura/react-pdf/pull/978

It's important to me. I need it urgently.

Thanks in advance,
Lucas

**Comment by LucasMatuszewski** [comment]
Hi @diegomura, It's a really small change, could you check/approve my PR? It works ok for me. I would appreciate it :)

**Comment by diegomura** [comment]
Yes sorry! I completely missed this

**Comment by diegomura** [comment]
Will publish a new version today!

**Comment by LucasMatuszewski** [comment]
Thanks a lot! :)
