### ISSUE TITLE
Critical dependency: the request of a dependency is an expression (jspdf)

### ISSUE THREAD

**Issue by Robert-OP** [diegomura/react-pdf#983]
**First of all**
Great work with this library guys, well done! :1st_place_medal: 

**Describe the bug**
It is not that critical, but whilst using `react-pdf library (v1.6.10)`, I found a warning that is related to `jspdf` dependency.

**To Reproduce**
Steps to reproduce the behavior would require to add the library to the project.

**Screenshots**
Browser console warning
![image](https://user-images.githubusercontent.com/16807022/90955580-f5daf080-e47e-11ea-9c05-0d348deddbd3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - React-pdf version: v1.6.10

**May be helpful**
I found that the latest version of `jspdf` introduced this and also found in this issue https://github.com/MrRio/jsPDF/issues/2846

**Comment by diegomura** [comment]
I think this belong to https://github.com/wojtekmaj/react-pdf
