### ISSUE TITLE
Incorrect decimal values parsing

### ISSUE THREAD

**Issue by goszczynskip** [diegomura/react-pdf#987]
When I'm setting paddingLeft/paddingRight to decimal values it's incorrectly parsed. eg. 
```
"paddingLeft": "26.400000000000002pt"
```
Is treated as `400000000000002pt`, `26.4pt` is treated as `4pt` which leads to broken layout.

This behavior is also visible in v2.

**To Reproduce**
1. Go to playground
2. Paste following snippet as a body (Page) style
```
{
   "paddingLeft": "26.400000000000002pt",
   "paddingRight": "26.400000000000002pt"
  }
```
4. Content will disappear

**Expected behavior**
It should correctly parse decimal values.

**Desktop:**
 - OS: Windows
 - Browser: Firefox 79
 - React-pdf version 2.0.0-beta.14

**Comment by diegomura** [comment]
Fixed in 2.0 here https://github.com/diegomura/react-pdf/pull/617/commits/87b625f694bc0691c2a920e4b0271dad01a7a492 Thanks!
