### ISSUE TITLE
How can I draw a chart using react-pdf library?

### ISSUE THREAD

**Issue by rpndev** [diegomura/react-pdf#988]
Hi,

I am going to draw some charts including doughnut, Pie, and Bar chart using the react-pdf library.
I was trying to draw it with Canvas but Seems like it's pretty complex and I don't have a better idea of it.
Please give me advice.
Thanks

**Comment by mafiusu** [comment]
You have to search for a chart lib that can export their charts into base64. Then you could import it to the pdf.

**Comment by kwiiby** [comment]
Suggestion: Convert chart to image and embbed into react-pdf page

**Comment by diegomura** [comment]
@kwiiby is the only way with v1. v2 has svg support so you can give that a try
