### ISSUE TITLE
Issue on Production only

### ISSUE THREAD

**Issue by SwapnaleePatil** [diegomura/react-pdf#989]
Hello,

Code:
`<View> {text ? text : ''} </View>`

This code works fine on the development server.
But the same code brakes page on a production server

Fixed Code:
`<View> {text ? text : null} </View>`

Why we are not getting errors in the development server?

Is there anything related to build?

Thank you in advance!

**Comment by diegomura** [comment]
Text string should always go inside `<Text />` components. It's probably that

**Comment by dprentis** [comment]
We may be facing the same issue - we have an error on production, which we are not able to reproduce in our staging or development environments:
```
react_devtools_backend.js:2557 TypeError: Cannot read property 'height' of undefined
    at resolveDimensions.js:85
    at resolveDimensions.js:96
    at tap.js:26
    at _dispatchable.js:38
    at _curry2.js:19
    at t (_curry1.js:16)
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
```
Is there any reason why an invalid PDF composition should cause an error only on production?

**Comment by dprentis** [comment]
Is it, for example, valid to use `React.Fragment` or `<></>` within the PDF render?
