### ISSUE TITLE
Weights and styles of standard fonts should not be their own families

### ISSUE THREAD

**Issue by jurgenbelien** [diegomura/react-pdf#998]
Currently, setting just the weight or style of a standard font fails, because they are [defined](https://github.com/diegomura/react-pdf/blob/master/src/font/standard.js) as their own families:
```
export default [
  'Courier',
  'Courier-Bold',
  'Courier-Oblique',
  [...]
];
```

It would be helpful if weights and styles are all registered under the correct family, like so:
```
<Text style={{fontFamily: "Helvetica"}}>
  This is an example of 
  <Text style={{fontStyle: "italic"}}>Italic text</Text>
</Text>
```
Instead of: 
```
<Text style={{fontFamily: "Helvetica"}}>
  This is an example of 
  <Text style={{fontStyle: "Helvetica-Oblique"}}>Italic text</Text>
</Text>
```

**Comment by diegomura** [comment]
Keeping https://github.com/diegomura/react-pdf/issues/649 to track this. I'll try to get into this soon
